### ISSUE TITLE
Set abs_zero appropriately in some TensorMechanics tests

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10001]
## Rationale

When running tests in parallel (-p 2) some of my TensorMechanics tests are diffing, eg:
```
test:capped_weak_plane.pull_and_shear_1step:    stress_xx      rel diff: -7.4505806e-09 ~ -3.7252903e-09 = 5.00000e-01 (block 0, elmt 1)
```
This is just because abs_zero is not set appropriately in the tests file.

I need to go through the tests and set abs_zero appropriately.

## Impact

More robust testing

**Comment by WilkAndy** [comment]
Wow, 10001 issues!

**Comment by cpgr** [comment]
Quick Andy - PR 10,000 is up next. Maybe you could put in a little change such as deleting the phase field module so that we can use the abbreviation PF in porous flow ...

**Comment by WilkAndy** [comment]
Sounds like a plan, heheheh
