### ISSUE TITLE
Can we make MooseApp::errorCheck() protected (instead of private)?

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#10002]
## Rationale

Following a recent commit (c35a93d320e56236c604354373b998b924647926), Rattlesnake no longer complains about unused parameters (not even a warning). This is because we override ```MooseApp::executeExecutioner()```. This could be fixed in one line if ```MooseApp::errorCheck()``` were protected instead of private.

## Description

If it does not have any negative impact (that I would be unaware of), I would suggest to make ```MooseApp::errorCheck()``` protected instead of private.

## Impact

This would allow to minimize code duplication in Rattlesnake.

@YaqiWang

**Comment by permcody** [comment]
I don't see a problem with this, go for it.
