### ISSUE TITLE
Improve error message of HIT parser warnings in TestHarness

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#10005]
## Rationale

The new HIT parser is more strict on the correctness of the input file syntax. This is causing several developers to encounter the "FATAL PARSER ERROR" message from the TestHarness. Unfortunately, the actual error is difficult to find since it's not colored and interleaved with normal TestHarness output. The parser messages should come out in a summary at the bottom. It wouldn't hurt to have the message colored as well in the TestHarness status.

## Description

Add a syntax error to a test spec file (e.g. tests) and run the TestHarness to reproduce. 

## Impact

Easier for developers to find errors, no impact to functionality.

**Comment by sveerara** [comment]
Can this input/tests file syntax check be performed at the precheck phase instead of during the execution phase of the tests?

**Comment by permcody** [comment]
That wouldn't really help here. All these things are happening asynchronously so the result of any given test would still happen in the middle of the run somewhere. We just need to keep track of them and summarize them at the end. Right now, the parser just aborts and tells the TestHarness there was a problem but we can save that result for later.
