### ISSUE TITLE
Mesh adaptivity gets called when there are no elements to refine/coarsen

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#10024]
## Rationale
The refine_and_coarsen_elements() function gets called even when there are no elements to be refined or coarsened. This causes unnecessary slowdowns, especially on large meshes across many CPU's.

## Description
Run a problem with mesh adaptivity on many (8+) cpus and lots (100K+) of elements and use a marker that is set to "do_nothing" and you'll see lots of time being spent on mesh adaptivity even though none is occurring.

## Impact
Skipping the mesh adaptivity call could result in significant speed ups in some cases.

**Comment by jessecarterMOOSE** [comment]
I'm working up a PR to address this. Really though, the mesh adaptivity routines in libmesh should be investigated.

**Comment by roystgnr** [comment]
Was this adequately resolved by libMesh/libmesh#1446?

**Comment by jessecarterMOOSE** [comment]
Yes it was. Thanks @roystgnr
