### ISSUE TITLE
libmesh test fails with vtk

### ISSUE THREAD

**Issue by broncodev** [idaholab/moose#10031]
Rationale
=========

Cannot run tests after re-building

Description
===========

-   I had run MOOSE in the Summer course.
-   I created a fork to run a tensor mechanics tutorial
    (<http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/BasicTutorial/>),
    and got an error.
-   I assumed that my built MOOSE was not working.
-   I changed `scripts/update_and_rebuild_libmesh.sh` to include
    `--enable-vtk`
-   I ran `scripts/update_and_rebuild_libmesh.sh` successfully
-   I did

    ``` {.bash}
    cd test
    make -j8
    ```

-   I got

```
Linking Library /usr/local/share/moose/test/lib/libmoose_test-opt.la...
libtool: warning: library '/usr/local/share/moose/framework/contrib/pcre/libpcre-opt.la' was moved.
/bin/grep: projects/moose/scripts/../libmesh/installed/lib/libmesh_opt.la: No such file or directory
/bin/sed: can't read projects/moose/scripts/../libmesh/installed/lib/libmesh_opt.la: No such file or directory
libtool:   error: 'projects/moose/scripts/../libmesh/installed/lib/libmesh_opt.la' is not a valid libtool archive
make: *** [/usr/local/share/moose/framework/libmoose-opt.la] Error 1
```

Impact
======

I imagine that my MOOSE is broken.

Specs
=====

``` {.bash}
gcc --version
printf "Linux-libre kernel: "
uname -srp
printf "\n"
cmake --version
autoconf --version
```
```
gcc-4.8.real (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Linux-libre kernel: Linux 4.2.0-42-lowlatency x86_64

cmake version 2.8.12.2
Autoconf version 2.13
---
Autoconf 2.13 chosen by Debian wrapper script.
For information and tuning advice see autoconf(1).
```

Post
====

Currently building without --enable-vtk

**Comment by broncodev** [comment]
Same result without --enable-vtk.

**Comment by andrsd** [comment]
1. Why are you building MOOSE in `/usr/local/share/` ?
2. `projects/moose/scripts/../libmesh/installed/lib/libmesh_opt.la: No such file or directory` means that  `scripts/update_and_rebuild_libmesh.sh` did not finish successfully.
3. You should be building MOOSE with our supplied compilers (wrapped in MPI), i.e. the ones that comes with the MOOSE environment.
4. Have you seen [this](http://mooseframework.org/getting-started/)? If so, did yo follow the instructions?

**Comment by broncodev** [comment]
>    Why are you building MOOSE in /usr/local/share/ ?

I have an SSD over there. I'm guessing that it's not different than ~/, /tmp or any other directory where I have all the permissions that I want:
```
$ ls -ld moose
drwxrwxr-x 16 myuser myuser 4096 Oct  4 14:44 moose
```
(I did the `git fetch` here without problems). Is it really necessary that I move it?

>    projects/moose/scripts/../libmesh/installed/lib/libmesh_opt.la: No such file or directory means that scripts/update_and_rebuild_libmesh.sh did not finish successfully.

It does not report any error. Should I run make clean? I thought that was not necessary (I saw something which looked like the `configure` going on).

>    You should be building MOOSE with our supplied compilers (wrapped in MPI), i.e. the ones that comes with the MOOSE environment.

I didn't change anything else other than `--enable-vtk` in the build files. I installed using the .deb binary that you provide. I did not specify any MPI variables either.

>    Have you seen this? If so, did yo follow the instructions?

Yes. MOOSE was running in the Summer course. I just made a fork and updated the git repository. I was going to reinstall the .deb binary, but I noticed that it was the same as I had originally.

Any advice? I can simply dump my installation and run again. I think that will solve _my_ problem.

**Comment by broncodev** [comment]
This is the error that I get when I run the tensor mechanics tutorial, which made me think that I needed to recompile the whole thing

```/usr/local/share/moose/modules/tensor_mechanics```:
```
make -k
...
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \```

(There is a lot more than just that.)

Disclaimer: I'm not pretending to know what I'm doing out here. Your help is most welcomed.

**Comment by andrsd** [comment]
If you had MOOSE running before and now you are having problems, it can be that your environment changed. Double-check that `~/.bashrc` is sourcing MOOSE environment (see the [post install](http://mooseframework.org/getting-started/ubuntu-1204/) step). Also do the `module list` command to see if the modules are loaded. They should create the environment so that you will successfully build libmesh, etc. There is no point in running or building anything if your environment is not right.

Also, I do not understand why MOOSE is in `/usr/local/share` and libMesh in `projects/moose/...`. If you moved some directory, that's a sure way how to hose up your setup. Recommended way is to have the source code in your home dir. Build and run there.

Lastly, if you do not want to diagnose the problem you are having, you can start from the beginning, which might be the easiest way how to get yourself up and running again. Do not forget to back up all your work, if you have any.

**Comment by permcody** [comment]
@broncodev - In the future you should use the mailing list for help like this. This isn't an issue with the framework. Thanks.

**Comment by broncodev** [comment]
@andrsd Thanks!
@permcody Sorry, I didn't know.
