### ISSUE TITLE
Peacock cannot load PyQt

### ISSUE THREAD

**Issue by yongchangli** [idaholab/moose#10036]
When I running Peacock, It always shows 

Traceback (most recent call last):
  File "/home/myname/projects/moose/gui/peacock", line 12, in <module>
    raise ImportError("Cannot load either PyQt or PySide")
ImportError: Cannot load either PyQt or PySide

But it can be used before, I have tried my best to solve it , but it still don't work.
it confused me a long time, Would you please help me to solve this problem?

**Comment by permcody** [comment]
Please use the the mailing list for help. This isn't an issue with the framework. This means that neither one of those graphics modules are in your python path.  If you are using a very recent version of the MOOSE package you should be using the "new" peacock which is located in the python folder. The version in the GUI folder is now deprecated.
