### ISSUE TITLE
Need a function in MooseApp to return the names of mesh modfiers

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10056]
## Rationale
Need this function to programmatically set the `depends_on` parameter for later added mesh modifiers in an action system.

## Description
The mesh modifiers added by the action system are executed always after all mesh modifiers in the input. Thus it is not very user friendly to ask users to pass the mesh modifiers in the input file to the action. With this function, the action can obtain those mesh modifiers and set the `depends_on` parameter background.

## Impact
Trivial interface function. None.

**Comment by dschwen** [comment]
Yaqi, can you be sure that you action runs after the manually specified MeshModifiers are constructed? Is there anything in MOOSE that guarantees this? Aren't both the manually specified MeshModifiers and the action run on the same task?

**Comment by YaqiWang** [comment]
Yes, I added a new task `add_multiscale_mesh_modifier` that depends on `add_mesh_modifier`. The mesh modifiers added by the action will have `depends_on` set to the manually added mesh modifiers.

**Comment by YaqiWang** [comment]
Ideally, I should throw a warning in this function when it is running inside `add_mesh_modifier` task. OK, let me add a note in the header file.
