### ISSUE TITLE
Tests for Smeared Cracking in Tensor Mechanics Module

### ISSUE THREAD

**Issue by zahom** [idaholab/moose#10051]
## Rationale
Adding regression tests to check if the Smeared Cracking code is functioning properly

## Description
All the existing tests in the solid mechanics module are being moved to tensor mechanics. 

## Impact
The tests will make sure that the tensor mechanics code for smeared cracking is functioning correctly.

**Comment by bwspenc** [comment]
Reopening because we still need to move the cracking_function test over.
