### ISSUE TITLE
Need generic AuxKernel to compute flux for diffusion problems

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#10050]
## Rationale
The MOOSE framework provides a basic Diffusion kernel, and diffusion problems are solved using either that or derived classes in a lot of applications. I would like to have the ability to output the components of the flux vector for diffusion problems. 

## Description
This seems analogous to the diffusion kernel, so I think it belongs in the framework. The flux is computed as $$J=-D\frac{\partial C}{\partial X}$$, where J is the flux, D is the diffusivity, C is the concentration variable, and X is the coordinate. 

## Impact
Add an AuxKernel (I'd name it `FluxAux`) that computes components of the flux vector using the gradient of the diffusion variable and the diffusivity. Also add a test in moose/test/tests/auxkernels.

**Comment by YaqiWang** [comment]
`VariableGradientComponent` is almost doing this except missing the diffusion coefficient. We can enhance it to accept a material property for D. We had one in Rattlesnake `VariableCurrentComponent.C` doing this. If this is in place, we can remove it.

**Comment by bwspenc** [comment]
Thanks, I didn't notice that. It seems more user-friendly to me to have an object named after what it actually does for this, though. I was looking for something with 'Flux' in the name for what I needed, and didn't see anything, so I assumed it didn't exist.  If we just added this as an option to `VariableGradientComponent`, other users would probably make the same mistake. I still think it's better to add an AuxKernel called `FluxAux` for this purpose.  Anyone else have thoughts on this?

**Comment by YaqiWang** [comment]
`FluxAux` is not very good for radiation transport because we use `flux` for naming the primal variables of the transport equation. I do not have a good suggestion.
