### ISSUE TITLE
Can we have MultiAppMeshFunctionTransfer transfer a vector of variables rather than a single variable?

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#10061]
## Rationale

```MultiAppMeshFunctionTransfer``` currently transfers a Variable ```source_variable``` to a Variable ```variable```. If many variables are to be transferred, many transfers will have to be created.

## Description

If this suggestion is approved, I would change ```source_variable``` and ```variable``` to be vectors of variables, ```_from_var_name[i]``` corresponding to ```_to_var_name[i]```. As far as I can see, it only requires to add a few ```for``` loops.

## Impact

The user input will be simplified if more than one variable is to be transferred.

In my particular case, I need to transfer many variables to a 'master' mesh that is spatially smaller than (but not necessarily embedded in) the 'slave' mesh, prior to saving the results for use in a ```SolutionUserObject```.

**Comment by permcody** [comment]
Most of the objects in MOOSE "act" on only one variable at a time. They may couple to many variables though. We keep it that way to keep the coding simple. Our thinking is that if you often need to create lots of duplicate syntax that you'll eventually create actions to create multiple objects.

That being said, I'm not completely against adding this capability however it should be noted that it would make it different from almost every other block and different can lead to confusion.

**Comment by vincentlaboure** [comment]
Oh I see your point

That being said, we are already planning to reduce the number of objects in Rattlesnake using ArrayKernels (#6881) so it looks like some objects are already moving towards acting on more than one variable.

So I guess it's you guys' call.

**Comment by permcody** [comment]
Well maybe... ArrayKernels have their own issues that are difficult to solve. I believe a lot of things did fall into place nicely until we got to dealing with calculating the Jacobian parts of ArrayKernels. This may be a long time in the making if we resurrect it at all.

**Comment by YaqiWang** [comment]
I think this is a useful enhancement and does not impact our current capabilities. As we did for coupled variables, we can support multiple variables transfer in one loop. This will increase the efficiency of transfer if variable number is large.
