### ISSUE TITLE
A logic issue in adding variables

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10069]
## Rationale
https://github.com/idaholab/moose/blob/devel/framework/src/base/SystemBase.C#L521
add empty set for variables not restricted blocks. I think the more correct way is to set
```
_var_map[var_num] = _mesh.meshSubdomains();
```
I do not know other implications, but the new logic can fix make `SystemBase::getSubdomainsForVar` return something making sense.

## Description
As in Rationale.

## Impact
Looks like the impact is very small on framework. With the following
```
diff --git a/framework/src/base/SystemBase.C b/framework/src/base/SystemBase.C
index 38890dc0b2..927ff9956a 100644
--- a/framework/src/base/SystemBase.C
+++ b/framework/src/base/SystemBase.C
@@ -518,7 +518,7 @@ SystemBase::addVariable(const std::string & var_name,
     _vars[tid].add(var_name, var);
   }
   if (active_subdomains == NULL)
-    _var_map[var_num] = std::set<SubdomainID>();
+    _var_map[var_num] = _mesh.meshSubdomains(); //std::set<SubdomainID>();
   else
     for (std::set<SubdomainID>::iterator it = active_subdomains->begin();
          it != active_subdomains->end();
diff --git a/test/tests/restrictable/undefined_ids/tests b/test/tests/restrictable/undefined_ids/tests
index 86632bb94f..9fdb2d93d0 100644
--- a/test/tests/restrictable/undefined_ids/tests
+++ b/test/tests/restrictable/undefined_ids/tests
@@ -2,7 +2,7 @@
   [./block]
     type = 'RunException'
     input = 'undefined_block_kernel.i'
-    expect_err = "The object 'kernel_with_undefined_block' contains the following block ids that do not exist on the mesh: 10"
+    expect_err = "In object kernel_with_undefined_block the defined blocks are outside of the domain of the variable"
   [../]
   [./boundary]
     type = 'RunException'
```
Moose framework test pass. Do you think we should make this change?

**Comment by permcody** [comment]
I believe the thinking was if it's unrestricted you shouldn't be using that parameter or information at all. If for instance you used a mesh modifier to add a new subdomain on the fly, this could potentially cause an issue (perhaps not since mesh modifiers run before any kind of objects are setup). I'm not completely against this change, but I'd like to understand why you want it.

**Comment by YaqiWang** [comment]
I want to check on what subdomains a variable is defined so that I can skip elements when I loop through elements for a custom preconditioner. Then I realized I have to check if the returned set is empty or not. Maybe we should just change `SystemBase::getSubdomainsForVar`. I am fine it we do nothing because the code is not in critical path.

**Comment by YaqiWang** [comment]
Looking into libMesh `Variable`, I am convinced that we can leave the code as it is. I can do the check on my side. Thanks.
