### ISSUE TITLE
Petsc-3.4.5 Support

### ISSUE THREAD

**Issue by kevindugan** [idaholab/moose#10083]
## Rationale
I'm working on coupling the Moose framework with codes which do not rely on the libMesh library. One such code, Proteus, depends on an earlier version of Petsc (version 3.4.5).

## Description
Most of Moose seems ready to accept this earlier version of Petsc. There is one location in PetscSupport -> colorAdjacencyMatrix which is not supported in version 3.4.5. I plan to wrap this code in a preprocessor directive which is not compiled if the Petsc version is less than 3.5.0.

## Impact
This change should not affect the developers nor users, since the changes will only take place if the Petsc version specified is less than 3.5.0. The current suggested version is 3.6.4.

**Comment by kevindugan** [comment]
@moosebuild ,

I'm testing these changes I've made, but I have one test failing; it's the mesh partitioning test [mesh/subdomain_partitioner.subdomain_partitioner_linux]. When I'm looking at the results for the test, the difference appears in how the domain is partitioned among the processors. The loads look similar to what the gold file produces, just that some nodes are assigned to a different processor. Here is the output from exodiff:

```
   *****************************************************************
              EXODIFF	(Version: 2.69) Modified: 2013-07-11
              Authors:  Richard Drake, rrdrake@sandia.gov
                        Greg Sjaardema, gdsjaar@sandia.gov
              Run on    2017/10/13   10:18:27 EDT
   *****************************************************************

Reading first file ...
Reading second file ...
  FILE 1: /home/pqd/WarthogPlayground/myMoose/test/tests/mesh/subdomain_partitioner/gold/subdomain_partitioner_out_linux.e
   Title: subdomain_partitioner_out.e
          Dim = 2, Blocks = 8, Nodes = 935, Elements = 1560, Nodesets = 0, Sidesets = 0
          Vars: Global = 0, Nodal = 2, Element = 1, Nodeset = 0, Sideset = 0, Times = 2

  FILE 2: /home/pqd/WarthogPlayground/myMoose/test/tests/mesh/subdomain_partitioner/subdomain_partitioner_out_linux.e
   Title: subdomain_partitioner_out_linux.e
          Dim = 2, Blocks = 8, Nodes = 935, Elements = 1560, Nodesets = 0, Sidesets = 0
          Vars: Global = 0, Nodal = 2, Element = 1, Nodeset = 0, Sideset = 0, Times = 2

exodiff: INFO .. Map option is not needed.
Coordinates will be compared .. tol:    1e-06 (absolute), floor:        0
Coordinates will be compared .. tol:    1e-06 (absolute), floor:        0
Time step values will be compared .. tol:  5.5e-06 (relative), floor:    1e-10
No Global variables on either file.
Nodal variables to be compared:
	proc_id                          tol:  5.5e-06 (relative), floor:    1e-10
	u                                      5.5e-06 (relative),           1e-10
Element variables to be compared:
	proc_id                          tol:  5.5e-06 (relative), floor:    1e-10
No Element Attribute variables on either file.
No Nodeset variables on either file.
No Sideset variables on either file.

  ==============================================================
  NOTE: All node and element ids are reported as global ids.

  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
Nodal variables:
Element variables:
  --------- Time step 2, 1.0000000e+00 ~ 1.0000000e+00, rel diff:  0.00000e+00 ---------
Nodal variables:
   proc_id  rel diff:  1.5000000e+00 ~  0.0000000e+00 = 1.00000e+00 (node 115)
Element variables:
   proc_id  rel diff:  2.0000000e+00 ~  0.0000000e+00 = 1.00000e+00 (block 2, elmt 93)

exodiff: Files are different
```

Is there a way to resolve this test failing?

**Comment by permcody** [comment]
Well that's a little odd. I don't think a different version of PETSc would cause this. This is a function of the partitioner.

**Comment by kevindugan** [comment]
I agree, this is a little strange. However, since libMesh depends on Petsc, I don't think that it's impossible that the version change would affect the partitioner. 

I ran the libMesh test suite and everything passes. Also, as I mentioned in a previous comment, the differences shown in the test are superficial in my opinion. It shouldn't matter which processor gets assigned to which section of the domain, as long as the load is balanced, right? Could we design a test that was better at capturing this type of behavior?

**Comment by permcody** [comment]
Why that’s true we also need to detect changes in partitioning to detect
problems. Both kinds of tests are appropriate. This particular test could
be restricted to a specific version of Petsc since it is sensitive. It
appears it’s already restricted to Linux.

**Comment by kevindugan** [comment]
I would be happy with that strategy. I'll work on applying that restriction to the test.

**Comment by fdkong** [comment]
Do you have a fundamental thing that Proteus does not work with the new PETSc?

**Comment by fdkong** [comment]
I would strongly suggest you update to a new version of PETSc for Proteus, if possible?

**Comment by kevindugan** [comment]
That would be the best solution, however it's not a solution that is available to me. There are no plans that I'm aware of to upgrade Proteus to support a newer version of Petsc.
