### ISSUE TITLE
SuperLU in PETSc versions newer than 3.6.4 is broken

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#10084]
## Rationale
This is a follow-on to closed issue #8200, which was closed (when it shouldn't have been, in my opinion) even though we still have problems that fail in newer PETSc versions. We rely on the SuperLU preconditioner for contact problems, and it is unreliable in PETSc versions newer than 3.6.4, and still is. It generally works on the regression problems, but we're already seeing real-world models failing with 3.7.6, which supposedly has this issue fixed.

## Description
SuperLU fails sometimes in the factorization of the matrix on problems that have contact. When that happens, it fills the solution with NaNs, and the first place this gets caught on the MOOSE side is in the geometric search code, which gives this error:
```
 *** ERROR ***
Failure in NearestNodeThread because solution contains inf or not-a-number entries.  This is likely due to a failed factorization of the Jacobian matrix.
```

## Impact
The latest manifestation of this is that we have three regression tests that are failing now that the Intel testing switched over to 3.7.6. Now three of the contact verification problems fail with this error.

This is not, however, just an isolated issue with a few tests on a nonstandard platform. This has rendered any version of PETSc newer than 3.6.4 completely useless for BISON simulations. We have been, and will continue to instruct BISON users to use version 3.6.4 until we figure out a solution for this that reliably works on real-world problems.

**Comment by fdkong** [comment]
@bwspenc, the tests do not work on INTEL only? Have similar issues on all other platforms?

**Comment by brianmoose** [comment]
FYI, for the Civet Intel target, we upgraded the Intel compiler version from 2013 -> 2017 as well as updating PETSc from 3.6.4 -> 3.7.6
