### ISSUE TITLE
Rework isotropic guarantee in ComputeMultipleInelasticStress

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10116]
## Rationale

At the moment TensorMechanics ```ComputeMultipleInelasticStress``` contains things like:
```
    if (_is_elasticity_tensor_guaranteed_isotropic)
    {
      _stress[_qp] = _elasticity_tensor[_qp] * (_elastic_strain_old[_qp] + _strain_increment[_qp]);
      // InitialStress Deprecation: remove these lines
      if (_perform_finite_strain_rotations)
        rotateQpInitialStress();
      addQpInitialStress();
    }
    else
      _stress[_qp] = _stress_old[_qp] + _elasticity_tensor[_qp] * _strain_increment[_qp];
```
I would like to use ```_stress[_qp] = _elasticity_tensor[_qp] * (_elastic_strain_old[_qp] + _strain_increment[_qp]);``` even with anisotropic elasticity tensors.

## Description

I believe we need the above isotropy check because BISON has a problem with using the old strain in finite-strain simulations.  Therefore we could:
(1) Change the isotropy check to a check on large strain (eg, using ```perform_finite_strain_rotations```)

Or

(2) we could include another use input parameter "use_old_strain", defaulting to false.

Any thoughts, @sapitts , @bwspenc ?

## Impact

Change to ComputeMultipleInelasticStress so that my models can use the old strain instead of the old stress, even though they don't have isotropic elasticity tensors (they are all small-strain models, by the way).

**Comment by bwspenc** [comment]
It is because of finite strain.  If you have finite strain, you would need to rotate the elasticity tensor forward somehow. We discussed doing this, and I think we quickly gave up on the idea because it was a big can of worms. If you want to limit yourself to small strain, I think it would be fine to allow anisotropic elasticity tensors.

**Comment by sapitts** [comment]
I'm fairly certain that we do rotate the elasticity tensor in the crystal plasticity codes (in ComputeElasticityTensorCP) so it might "just" be a matter of figuring out how to apply the updated elasticity tensor rotations that are in the crystal plasticity specific code to a more general set of elasticity tensors....
