### ISSUE TITLE
Enable use of all MaterialProperties during initQpStatefulProperters

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10113]
## Rationale

At present non-stateful MaterialProperties are not defined during initQpStatefulProperties.  I would like to be able to use them to compute my stateful properties.  I do not want to promote all MaterialProperties to be Stateful just so i can use them during initQpStatefulProperties.

## Description

For instance, in ComputeEigenstrainFromInitialStress, the elasticity tensor is used to compute an Eigenstrain.  The Eigenstrain is stateful, but i don't want the elasticity tensor to be, in order to reduce computation and memory use.  Because the elasticity tensor is not defined during initQpStatefulProperties, i cannot define the Eigenstrain at that time.  Instead, i have to do a ```if (_t_step==1) then computeEigenstrain``` approach.

If the non-stateful elasticity tensor were available in ComputeEigenstrainFromInitialStress::initQpStatefulProperties i could use it to compute the Eigenstrain.  This is not just for code cleanliness.  It is because the Eigenstrain computed using the current scheme will be incorrect if the elasticity tensor changes between time=0 and the end of the first timestep.

Tagging @bwspenc , @sapitts .

## Impact

Less use of ```if (_t_step==1)```, and code that is physically correct.  I can't think of any negative consequences.

**Comment by permcody** [comment]
We’ve been down this road before and it’s much trickier than it might sound
here. To have regular properties available, we have to run the normal
reinit element and then compute properties routine, but as you know.
Regular properties can couple to everything else, like nonlinear variables,
aux variables, postprocessors, etc. So to make this work we’d have to have
a pre-initQpStatefulProperties material property loop where you couldn’t
access all that goodness, but what would that interface look like?

However, I do understand the need. What we’ve done is this:
Set initial stateful prop values
Calculate initial regular properties
Reset initial stately prop values

Hopefully you should be able to make this scheme work.

**Comment by YaqiWang** [comment]
I think `if (_t_step==1)` is fine. We have to be aware the difference between initial condition and initial evaluation. Since initial evaluation happens after initial condition, evaluation wins. If everybody is aware of this situation, MOOSE will not need to reset the initial prop values to make the initial condition win.

**Comment by WilkAndy** [comment]
Well, i disagree with you @YaqiWang , but i've caught a glimpse @permcody 's problem.  I think the scheme of (1) set stateful; (2) calculate regular; (3) reset stateful, would work for me.

**Comment by YaqiWang** [comment]
Well, what I am saying is to avoid initial evaluation of stateful properties if they are set in initQpStatefulProperties. Initial evaluation and condition should be used one or another but not at the same time. There could be some logical issues if you are doing both.

**Comment by permcody** [comment]
OK, I'm closing this ticket then since we don't have any plan to change the interface in a way to make this work any better than it does today.
