### ISSUE TITLE
Remove old peacock from repo

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#10112]
## Rationale
New peacock is pretty functional and becoming more stable and is what we are pushing users toward.  Old peacock's removal is blocking #10107.  It will still be in history if anybody needs/wants it.  I'd personally prefer to remove this sooner rather than later FWIW.

## Description
Just rm the old ``gui`` dir from the repo.

## Impact
Users will need to use the new peacock gui.

**Comment by friedmud** [comment]
Please don't do this yet - there are several things I still use old peacock for (It's still much faster to render large meshes for instance... and playback in the Result Viewer is smoother)... and it's good to have around as a point of reference.

The day is coming pretty soon though.  New Peacock is definitely shaping up nicely!  I'm using it 90% of the time now.

**Comment by rwcarlsen** [comment]
Sure.  I just wanted to make an issue while I was thinking about it.  We can revisit this again periodically.

**Comment by rwcarlsen** [comment]
@friedmud - could you point to and/or create issues that should block this for you so we can track progress toward this?

**Comment by friedmud** [comment]
Yeah - I’m working on it - I trickle in the tickets as I can. I’ll try to
put one in about rendering speed and one about flashing during playback.

**Comment by brianmoose** [comment]
Closed via #10573
