### ISSUE TITLE
Add an accessor to retrieve the dimension of SolutionUserObject

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#10139]
## Rationale

We have created a `Function` constructing a `SolutionUserObject` and we would like to check that the `MeshFile` read by the `SolutionUserObject` has the same dimension as the mesh for the current simulation.

## Description

If this change is approved, I would simply add a public accessor to `SolutionUserObject` returning `_mesh->spatial_dimension()`.

## Impact

This will help enforce that the mesh dimensions are consistent.

**Comment by andrsd** [comment]
How about the case where mesh has lower-dimensional elements in it? Let's not forget that this is allowed in MOOSE, i.e. a single sweep through a mesh can give elements of dimension 1, 2 and 3.
