### ISSUE TITLE
Add a post-processor to compute the relative difference between 2 post-processors

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#10148]
## Rationale
It is useful to be to able to test that 2 post-processor values are relatively equal; this can be achieved by computing the relative difference between them and comparing to a tolerance. For instance, a test might output this relative difference value to a CSV file and then use the `CSVDiff` tester with `abs_zero = my_relative_tol` and `rel_tol = 0`.

## Description
This adds a post-processor that computes the relative difference between 2 post-processor values.

## Impact
This only adds a new post-processor; it does not affect any existing code.

**Comment by mangerij** [comment]
We have this. Look up PercentDifference post processor

**Comment by joshuahansel** [comment]
I do not see any `PercentDifference` post-processor. Could you tell me where this is located? The closest thing I see is `PercentChangePostprocessor`, but this is measuring the percent difference of a single post-processor between time steps, whereas I'm wanting to compute the percent difference between 2 post-processors for a given time level.

**Comment by mangerij** [comment]
My apologies. I read your PR wrong :)

Carry on MOOSing!
