### ISSUE TITLE
Python error - can't run tests

### ISSUE THREAD

**Issue by manmanhu** [idaholab/moose#10153]
Hi,

I'm following the steps (http://mooseframework.org/getting-started/) updating Moose. But when I try to run the tests using "./run_tests -j8", it returns:
"
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
"
Did anyone have the same issue before?

**Comment by brianmoose** [comment]
I saw this after I replied to this question on the mailing list:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/vp0RtQ5H8kk/B7_s2CZTBAAJ

**Comment by permcody** [comment]
@manmanhu - We have tickets open already to improve the error messages under various "not ready" configurations. We'll handle this request on the mailing list which you can follow with the link above. Welcome to the community.
