### ISSUE TITLE
Add a --version or -v option to MOOSE

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#10163]
## Rationale

Having a `--version` CLI option that prints out the current repository/release version from MOOSE would be handy in a few situations. The one that typically gets me is making sure that I have a synced up executable with the repository when I run `moosedocs`. This option could also be used during user support or troubleshooting.

## Description

Add a `--version` or `-v` option that would print the current version of the code. There is already a header file that's generated as part of the Make process that contains the version information that should be printed. This generated file exists in each application and can be found in "include/base/*Revision.h".

## Impact

Does not impact current functionality.

**Comment by jessecarterMOOSE** [comment]
I like this @permcody since one can easily muck around in the framework, revert changes, and forget to recompile.

Is there something similar, or can we get something similar, to check the libmesh version?

**Comment by andrsd** [comment]
@permcody I have this in RELAP already, go steal it from there :-) I built is for Gregg, when he was beta testing the code, so he could easily report his results.

**Comment by permcody** [comment]
> Is there something similar, or can we get something similar, to check the libmesh version?

Yes, but I'm not sure I want to add it just yet. We use a python script to run a few git commands (fails safe) to retrieve information about the version and writes a C++ header file. This all happens when you run make. We could do the same thing in the libMesh submodule if we really wanted to. However, this is generally not necessary. MOOSE will either compile or not with the version of libMesh you have. When you run 'make' and your libMesh is out of date, you'll see an error at that point in time, but we don't have anything that comes out at runtime. If you need something I might be convinced...

**Comment by jessecarterMOOSE** [comment]
I was thinking more along the lines of being _ahead_ of the libmesh submodule. Like recently I've been trying to stay up to date with the libmesh master or even applying individual patches to benchmark the optimizations that @roystgnr and @jwpeterson have been doing. It would be nice if I could do something at runtime to remind me which changes I'm testing.

Maybe an alternative would be to print the libmesh hash at the beginning of the simulation right next to the MOOSE and PETSc versions.

**Comment by roystgnr** [comment]
We ```#define LIBMESH_BUILD_VERSION``` to be the git hash, in ```libmesh_config.h```, so it'd be easy for MOOSE to just print that.

I don't think I've ever looked at what that macro does when we're building from a tarball, though...  Unless I'm misunderstanding the m4 files, I think we must just end up with ```#define LIBMESH_BUILD_DEVSTATUS "External Release"``` and ```#define LIBMESH_BUILD_VERSION "external"```, which seems inadequate...

**Comment by jessecarterMOOSE** [comment]
Hmm, on my work machine, `LIBMESH_BUILD_VERSION` in `libmesh_config.h` is defined as "external". 

However, we have a weird build setup where tarballs are brought in (because of a firewall), but are still processed through git. This should be transparent to the end user as moose/libmesh is still installed with git clone and git submodule commands (pointing at our own internal git server). The only difference is that the hash values don't line up with Github, but that shouldn't be a problem, unless the libmesh configuration has `github.com` hard-coded somewhere.

**Comment by roystgnr** [comment]
We don't hardcode github.com, we just require that a git executable is in your path and that $srcdir/.git is a directory.  Are those not both true for you?

**Comment by jessecarterMOOSE** [comment]
Yes and no. 

git is in my path, but libmesh/.git is a file that reads
`gitdir: ../.git/modules/libmesh`
likely because libmesh is set up as a moose submodule. Is that not standard? (We use Microsoft TFS to host git repos internally)

**Comment by roystgnr** [comment]
Ha!  That's almost certainly standard, since it's what the standard git 1.8.3.1 seems to have done in ~roystgnr/git/moose/libmesh/.git for me, but it's not something our m4 file was prepared for.

Could you try replacing the '-d' test with '-e' in libMesh m4/config_environment.m4:38 and see if (after rebootstrap and reconfigure) you get a git hash instead of just "external"?

**Comment by jessecarterMOOSE** [comment]
Yep, that did it!

I suggest we move the conversation regarding actually implementing this in MOOSE to here: #10184

**Comment by jessecarterMOOSE** [comment]
@roystgnr if that change in the m4 file is something you want to keep, I could submit a libmesh PR later today if you don't get to it first.

**Comment by roystgnr** [comment]
I'd appreciate it, thanks!

**Comment by jessecarterMOOSE** [comment]
It's the least I could do... literally.
