### ISSUE TITLE
Fix fluid properties compiler warning

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#10171]
## Rationale
Clang on my mac gives an infinite recursion compiler warning for `TabulatedFluidProperties`

## Description
The error message is
````
/moose/modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C:277:1: warning: all paths through this function will call itself [-Winfinite-recursion]
{
````

## Impact
Fix possible bug?

**Comment by cpgr** [comment]
The offending code is
````
Real
TabulatedFluidProperties::mu(Real pressure, Real temperature) const
{
  Real rho = this->rho(pressure, temperature);
  return this->mu(rho, temperature);
}
````

which should be
````
Real
TabulatedFluidProperties::mu(Real pressure, Real temperature) const
{
  Real rho = this->rho(pressure, temperature);
  return this->mu_from_rho_T(rho, temperature);
}
````

I'll fix this now @andrsd

**Comment by andrsd** [comment]
Did you compile in debug? Or what version of clang are you using? I have not seen this warning (also using clang).  I made this mistake in another class, but discovered the recursion through a unit test. Obviously this one slipped through...

**Comment by cpgr** [comment]
Yep, in debug to track down an unrelated error in some work I am doing. I'm using clang 3.9.0
