### ISSUE TITLE
Add libmesh version to simulation output

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#10184]
## Rationale

Nothing is listed in the output describing the version of libmesh that is being used.

## Description

Add the libmesh git hash or something more descriptive to the screen output.

## Impact

New capability, no impact.

**Comment by jessecarterMOOSE** [comment]
Currently there is a `#define LIBMESH_BUILD_VERSION` in `libmesh_config.h`. Do we want to simply print that or do something more descriptive like what is done for the framework version: "`git commit abababa on 2017-10-31`"?

**Comment by permcody** [comment]
The version is sufficient for libMesh. The reason for the more verbose output on the MOOSE side is to support better messages for releases. Right now we are all working on the devel and master branches on some commit that changes all the time. However, in the future when applications are deployed this string will automatically print the release (e.g. 1.0.0).

**Comment by jessecarterMOOSE** [comment]
In that case, I can submit a PR for this later today.

**Comment by permcody** [comment]
@jessecarterMOOSE - We are having a big discussion about this right now. We have a lot of different versions floating around (app, framework, dependencies) and we want to make sure they come out in some consistent format, but also allow apps to customize this a little bit. Let us take care of this. We'll get you the libMesh version and also allow you to customize your version for your app.

**Comment by jessecarterMOOSE** [comment]
Sounds good.
