### ISSUE TITLE
Fix heavy tests using augmented lagrange contact

### ISSUE THREAD

**Issue by acasagran** [idaholab/moose#10193]
## Rationale
The new augmented lagrange contact feature recently implemented changed the input file syntax and several heavy tests need to be updated. Also new tests using frictional contact and the augmented lagrange method will be added.

## Description
The input file syntax will be updated and some new heavy tests will be added.

## Impact
No impact on the code.

**Comment by lindsayad** [comment]
Was this closed by #10214?

**Comment by acasagran** [comment]
Yes. I'll close it out.
