### ISSUE TITLE
New libmesh interferes with MOOSE performance logging

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#10196]
## Rationale

Recent improvements to the libmesh performance logging (libMesh/libmesh#1462) seem to interfere with MOOSE performance logging system in a way that is not currently tested.

## Description

After upgrading to newer libmesh version (later than the current submodule hash), PerformanceData Postprocessor values are all zeros except for the ACTIVE and ALIVE events, I think.

## Impact

More robust testing.

Possible path forward:
1. Add a test that checks the PerformanceData Postprocessor _values_ of events (or just an event) other than what is currently tested. I have this ready.
2. (Optional) Do a libmesh update to show the above test fails.

I figured doing 1. is prudent to get the test in there. Doing 2. is just my way of getting your attention :smile:  However, once 1. gets merged, it's possible that libmesh CIVET tests will fail.

I'd like to get this addressed soon. It's getting in the way of my benchmarking. 

tagging @permcody @roystgnr

**Comment by permcody** [comment]
@jessecarterMOOSE - Welcome to the forefront of MOOSE development. You are welcome to put up a PR with your new test and fix along with a libMesh submodule update. That's all the core MOOSE team does. CIVET will checkout the requested version of libmesh (usually the HEAD of master) build and run the full suite against the new hash. If it passes we can decide to merge or wait for other changes/fixes in the works. However, feel free to initiate this if you want to move forward more quickly than we do.

**Comment by jessecarterMOOSE** [comment]
this can be closed when libmesh submodule is updated to include libMesh/libmesh#1482

**Comment by permcody** [comment]
Latest libMesh merged

Note: This was never an issue with the devel branch in MOOSE. It was only present if people were running further ahead of the submodule hash.

**Comment by jessecarterMOOSE** [comment]
Right you are @permcody
