### ISSUE TITLE
TestHarness output file race condition checking

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#10204]
## Rationale

We already have output file race condition checking to make sure that any group of tests that are allowed to run concurrently don't stomp on each other's output files (to the best of our ability, which is admittedly is poor), however there are a few cases we might be able to detect better.

One such case is where you have two tests like this:
```
   [./test1]
      type = CheckFiles
      input = foo.i
      ....
   [../]
   [./test1]
      type = RunApp
      input = foo.i
   [../]
```

Since the first test is a CheckFiles test it produces output files. The second test which uses the same file is likely to stomp on those files. This of course breaks down if `cli_args` is used.

## Description

See the test case above.

## Impact

Improved robustness of TestHarness

**Comment by permcody** [comment]
@milljm - Interesting case that we might work on at some point.

**Comment by permcody** [comment]
We got hit by this again in Relap this time. There was a test that was being run 3 times to test 3 different outputs (not the way I'd do it since all 3 outputs are being written in a single run). Since a different gold file was being used in each of the three cases, the TestHarness didn't see the conflict).

**Comment by permcody** [comment]
Another new case today in BISON:

They had an output block for Exodus where the file_base was inside of the block:
```
[Outputs]
  [./Exodus]
    type = Exodus
    file_base = foo
  [../]
[]
```

When the file_base was changed for duplicate tests, it didn't (wouldn't) change the top level file_base so the checkpoints are stomping on each other. The Exodus files themselves don't but it's only recover tests that are failing.

**Comment by jasondhales** [comment]
FYI, I have a merge request in Bison to fix this issue.  There is a documentation build error that is holding up the merge.

**Comment by permcody** [comment]
Yes, thanks! Just noting all the ways that our parallel testing can fail. Looking for a real solve-all solution!

**Comment by permcody** [comment]
@friedmud suggested that we consider serializing all of the tests in each directory of tests in the suite. We'd still get plenty of parallelism between directories. This would essentially make file-based race conditions impossible in testing. @milljm - can you hack something together to try this out? Just add an artificial dependency between every test in a given directory.

**Comment by permcody** [comment]
Once again this has bitten us for like the 50th time. My comment above (7/11/18) is still valid and would be fairly easy to implement but I have another idea that would allow us to keep our full parallelism and could possibly make an interesting intern project.

The idea would be to have a mode in the TestHarness where we could check for outputs from each individual test. The way it would work is that we'd setup each test to run with a clean workspace (`git clean -xfdq` in the working directory) separately (serially). After running the test, we'd compare the before and after to see what was created and we'd record which files were created (or even appended to). We'd use that information in conjunction with the existing DAG to see what overlaps (taking dependencies into account) to figure out where we have race conditions. This would give us a pretty bullet-proof way to test for race conditions. The funny thing is that in order to do this, we'd have to basically serialize each test in each directory anyway...
