### ISSUE TITLE
Don't create more copies of MOOSE objects than necessary

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#1022]
Right now we create a lot of copies of MOOSE objects:

For each block
For each thread
For volume, boundary and neighbor

We need to cut it out!

We _do_ need a copy for each thread.  And the copy for volume, boundary and neighbor are needed _when their needed_.  We _shouldn't_ create a copy in these instances:

- For each block.
- For neighbor when we don't have any DG kernels.
- For boundary when we don't have any integrated BC's

**Comment by aeslaughter** [comment]
I think I have cleaned up a lot of this with the new warehouses.
