### ISSUE TITLE
Extend water formulation to higher pressures

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#10234]
## Rationale
At the moment, porous flow simulations using water are limited to pressures less than 100 MPa, corresponding to the upper pressure limit for IAPWS Industrial Formulation 1997. This also impacts simulations using brine (which uses water properties to calculate brine properties).

@hsheldon is interested in using brine fluid properties at higher pressures (around 120 MPa). The brine formulation is valid for pressures up to 500 MPa, *if* water properties are available at these pressures. Using IAPWS-IF97 in the brine formulation reduces the maximum allowable pressure to 100 MPa.

## Description
Provide a water implementation that is valid for higher pressures.

## Impact
Extends the maximum pressure of water (and consequently brine), enabling @hsheldon to use porous flow at these higher pressures

**Comment by cpgr** [comment]
The "proper" long-term solution would be to implement IAPWS95, which is valid up to 1000 MPa. However, this won't help @hsheldon  in the short-term because:
- It is a fair bit of work!
- It would be slow for porous flow, as density would need to be found by iteration from pressure and temperature (this could be sped up using TabulatedFluidProperties or, even better, properly implementing the IAPWS spline-base table lookup - more work!)

After discussing with @hsheldon and @WilkAndy, I investigated extrapolating the current IAPWS-IF97 formulation to higher pressures, as this could be done quickly and with minimal effort.

First, some brief background. IAPWS-IF97 is divided into 5 regions, see below:
![iapws97](https://user-images.githubusercontent.com/7664823/32634604-8b7d8742-c600-11e7-9d09-25114244ce93.png)

I calculated water properties up to 190 MPa, and compared with the results obtained using IAPWS95 (using a python implementation from https://github.com/jjgomera/iapws).

Briefly, we find that extrapolation is reasonable in regions 1 and 3 up to 180 MPa, but only up to 140 MPa in region 2, with relative errors of less than 0.5% in these regions.

For example, comparing the density, we see that there is only a noticeable difference in the upper-right corner (region 2) and a little spike at the boundary between regions 1 and 3 at 190 MPa.
![density](https://user-images.githubusercontent.com/7664823/32634799-90a99e9e-c601-11e7-8889-914006b12569.png)

Similar observations are made with other properties such as internal energy and enthalpy. Plotting the relative errors:
![density_relerr](https://user-images.githubusercontent.com/7664823/32634879-ef81e796-c601-11e7-8938-2be7fd2ea572.png)
![enthalpy_relerr](https://user-images.githubusercontent.com/7664823/32634884-f3639878-c601-11e7-95b4-bc81be87d091.png)
![internal_energy_relerr](https://user-images.githubusercontent.com/7664823/32634886-f6801f86-c601-11e7-9997-83dd0eb364c3.png)

**Comment by cpgr** [comment]
The error introduced by extrapolation is much less than the uncertainty in other parameters typically used in our simulations, so we propose relaxing the pressure restriction in `Water97FluiProperties` to
- 180 MPa in regions 1 and 3
- 140 MPa in region 2

so that higher pressure regions can be used in porous flow without having to expend a lot of effort.

We will throw a warning to the console when the pressure and temperature are first in this extrapolated region to let the users know that there is a small increase in the error in this region. This will also need to be fully documented in the code and documentation.

**Comment by WilkAndy** [comment]
How about viscosity?

**Comment by cpgr** [comment]
Good question - IAPWS Formulation 2008 for the Viscosity of Ordinary Water Substance is valid for up to 300 MPa for T < 1173K, so is ok to keep what we have

**Comment by WilkAndy** [comment]
Aha, wow, someone(s) been doing tonnes of experiments on water!

**Comment by hsheldon** [comment]
Luckily for us!
Thanks for doing this @cpgr

**Comment by hsheldon** [comment]
Using tabulated properties in conjunction with IAPWS95 is an interesting idea. I wonder how finely you could resolve this table before the performance would be no better than iterating from P and T? Does the table have to have uniform increments across the whole range? I'm thinking you might need finer resolution in some parts of the P, T space.

**Comment by cpgr** [comment]
I use tabulatedfluidproperties instead of CO2 for the same reason and it is roughly 80% faster for me.

IAPWS have a release on a spline-based table lookup (SBTL) that has timings and it is typically much faster when you have to do iterations

**Comment by hsheldon** [comment]
Revisiting this again.
I was looking into using TabulatedFluidProperties as an interim measure, using the python implementation of IAPWS95 that you mentioned above to generate the tabulated values. TabulatedFluidProperties reads density, enthalpy and internal energy from a table, and gets other fluid properties (e.g. viscosity) from a SinglePhaseFluidPropertiesPT user object, which could be CO2FluidProperties or Water97FluidProperties for example. The additional fluid properties that I need are viscosity, specific heat and thermal conductivity. Viscosity and thermal conductivity could be obtained from Water97FluidProperties, however the function for specific heat in Water97FluidProperties is divided by regions, so it will not work for P > 100 MPa. So, we're back to having to modify Water97FluidProperties to extend the allowable range of P.

**Comment by cpgr** [comment]
Hi Heather,

I remember doing this but I must not have pushed the change. Nevertheless, the good news is that TabulatedFluidProperties can now do all of those properties, and is much faster than calculating them using Water97FluidProperties (see #11084, #11086 and #11060).

The documentation of TabulatedFluidProperties should show you how to use the extra properties, see
[here](http://www.mooseframework.org/moose/documentation/systems/Modules/FluidProperties/TabulatedFluidProperties.html)

**Comment by hsheldon** [comment]
Great! Thanks for that. Don't quite understand how I was looking at an old version of TabulatedFluidProperties, but anyway... I see it now. I'll give it a go and let you know how it goes.

**Comment by cpgr** [comment]
I'm going to close this as using TabulatedFluidProperties seems to be the better solution. @hsheldon has reported that using TabulatedFluidProperties in these higher pressure regimes is working well using values generated externally. As a bonus, it is also giving a speedup of 1.3!
