### ISSUE TITLE
Move AuxKernel::isNodal() implementation to header file

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10240]
## Rationale
This tiny function shows up in one profiling report and is taking non-negligible time.

## Description
Move the function into the header file will make it inlined. I think we need to be careful on these little function calls which on the computing critical path. It is worthwhile to inline them.

## Impact
Slightly improve the performance with aux kernels without growing the executable much.

**Comment by permcody** [comment]
Any more information about this? You didn't say which test or how to replicate. Makes it hard for anyone but you to work on this so these kinds of tickets just sit around open for a long time. We need to be better about putting in everything necessary for somebody else to pickup and run with these kinds of requests.

**Comment by YaqiWang** [comment]
I was playing with a Rattlesnake basic test for SAAF-SN transport scheme, with Google perf tools. The test is `rattlesnake/yak/tests/actions/saaf_sn_cfem/saaf_sn.i` with `Mesh/uniform_refine=4` and BoomerAMG preconditioning. I can send in a small PR for this.
