### ISSUE TITLE
AuxKernel for computing Darcy velocity in fractures

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10269]
## Rationale

Tagging @cpgr in case i've made an error in the stuff below.

PorousFlow is being used to simulate flow in mixed-dimensional meshes.  The 3D mesh contains 2D elements that represent thin, highly conductive fractures.   Because of MOOSE's dimensional independence, no extra code has been needed: the input file must just supply appropriately scaled permeability and porosity.  Specifically, the input-file-porosity = a * experimentally-measured-fracture-porosity and input-file-permeability = a * experimentally-measured-fracture-permeability.   Here "a" is the actual fracture thickness.  These input-file quantities are prescribed to Materials defined on the 2D elements.

Crazy results can be produced when calculating the Darcy velocity using the AuxKernel PorousFlowDarcyVelocityComponent, according to Philipp S.  I don't know exactly what results he's getting, but it's clear this AuxKernel doesn't work in this situation.

Here is the desired behaviour.

1. It will be assumed the user has an elemental AuxVariable (can either be constant or first order in the current PorousFlow setup) defined only on the 2D elements.  We want to calculate the DarcyVelocity in the 2D elements.

2. The fundamental assumption behind this 2D+3D approach is that the 2D elements are supposed to represent very thin 3D elements, inside which grad(P).n = 0, where n is the normal vector to the element.  Only then can the thin 3D element be replaced by a 2D one.   So, as far as the fracture is concerned, grad(P) should point in the tangential direction to the element.  I need to check that MOOSE actually does this.   The fracture does not care that outside (in the 3D elements) grad(P) is pointing somewhere else: **within the fracture grad(P).n = 0**.

3. The gravity vector will be projected to the element's tangential direction, and the vector (grad(P) - density*projected_gravity) will be formed.   This is appropriate because at steadystate this vector will be zero.

4. The result will be multiplied by the permeability.  The user should have chosen their permeability tensor so that the resultant vector is tangent to the element.   For instance, their permeability should not have components that mix tangential and normal directions.  I don't think this AuxKernel is the place to check this, however, because of the computational burden and because it would be extremely rare (I can't remember any experimental work that measures off-diagonal permeability components).  Better to state this in the ClassDescription.

5. The user extracts the components of this vector as usual.

## Description

Very little difference between this and PorousFlowDarcyVelocityComponent.  I have to quickly convince myself that MOOSE actually makes grad(P) lie along the element.  But all the code will include is a projection of gravity.  All the remaining stuff in PorousFlowDarcyVelocityComponent is the same.

## Impact

Ability to extract sensible Darcy velocity in simulations with mixed-dimensional elements.

**Comment by cpgr** [comment]
So is fluid flowing through along the 2D elements at an expected rate, and is it just this velocity aux calculation that isn't working?

**Comment by WilkAndy** [comment]
Yes, that is correct.  Philipp S has actually produced some nice documentation of this that he's going to add as a PorousFlow example very soon.   But in doing that he noticed this Aux was incorrect, so i have to fix it.

**Comment by cpgr** [comment]
Ok, thats a much better problem to have!

**Comment by WilkAndy** [comment]
Tagging @philippschaedle

**Comment by WilkAndy** [comment]
Calling @jwpeterson !    What's needed here is the ability to project a 3D vector (physically, gravitational acceleration) onto a lower-dimensional elements.  The most common use-case would be the lower-dimensional element is a 2D planar element embedded in the 3D mesh: it's not a sideset, but it's part of a separate subdomain.  Another less-common use case is that the lower-dimensional element is a line embedded in a 2D mesh.  A possible use case that i've never actually seen is that the lower-dimensional element is a line embedded in a 3D mesh.  Another possible use case that i've never seen is that the lower-dimensional element is a non-planar element embedded in the 3D mesh.

In all these cases, the user supplies the full vector as a RealVectorValue and i want to project it onto the lower-dimensional element at each quadpoint in the AuxKernel evaluation.

For this i was imagining knowing the normalised normal vector(s) to the lower-dimensional element, but obviously orthonormal tangent vector(s) would be fine too.

Can Libmesh please supply this functionality?

**Comment by WilkAndy** [comment]
@philippschaedle , if this is going to come from Libmesh, we might have to wait a while.  Please be assured that PorousFlowDarcyVelocityComponent provides the correct answer to your problem if: (1) there's no gravity; and (2) if the permeability tensor is isotropic.  If there is gravity, you will have to manually project it onto the plane of your fracture, and provide that Vector to PorousFlowDarcyVelocityComponent instead of the full gravitational acceleration.  If your permeability tensor is anisotropic then for the DarcyVelocity to make any sense you must ensure that permeability is such that it doesn't rotate a vector lying in the fracture plane to a vector that is not in the plane.  If that is the case then you'll be fine.

Eg 1
If gravity = (1,1,1) and your fracture is lying in the (x,y) plane, you should tell the PorousFlowDarcyVelocityComponent AuxKernel for the fracture velocity that gravity=(1,1,0)

Eg 2
If permeability = diag(1,2,3) and your fracture is lying the (x,y) plane then you'll be fine, because for any V=(vx,vy,0), the product permeability*V still lies in the (x,y) plane.

**Comment by WilkAndy** [comment]
@jwpeterson - are you planning on implementing the functionality described in libmesh?

**Comment by jwpeterson** [comment]
Sorry, I couldn't grasp what you are after exactly? Projection of a given vector onto the surface of a 2D element living in 3D? I'm not sure about the math, but at each quadrature point, the vectors `FEMap::get_dxyzdxi()` and `FEMap::get_dxyzdeta()` form a basis for the plane which is tangent to the element at that point. You should be able to project any vector into this plane using standard geometric formulas... does that help?

**Comment by WilkAndy** [comment]
Yes, those vectors look they'll be exactly what i need.  Thanks @jwpeterson
