### ISSUE TITLE
Allow the user to add a minimum number of non-linear steps

### ISSUE THREAD

**Issue by jhaase1** [idaholab/moose#10306]
## Rationale

The reason for this enhancement is that in simulations with time varying conditions, it is possible to be at the minimum achievable nl_abs_tol for one portion of a simulation, while at a later point reaching the nl_abs_tol immediately, meaning the simulation no longer evolves. Setting a minimum number of non-linear steps (an analog to nl_max_its), would force the simulation to continue evolving, even if the evolution is small.

In a [question ](https://groups.google.com/forum/#!topic/moose-users/R_sJDPulNNk) on the Google group, another user (andrew.wilkins) thought adding this feature would be beneficial.

## Description

This enhancement would be an analog to nl_max_its. I believe this would just consist of adding an additional condition to a while loop.

## Impact

This change would allow users to further control their simulations, especially in the situation outlined above. As there is already an analogous maximum, I believe it would be easy to implement and have negligible influence on the code.

**Comment by lindsayad** [comment]
@jhaase1 Can you point me to the while loop? :-) We handle our convergence testing through petsc. (see https://github.com/libMesh/libmesh/blob/master/src/solvers/petsc_nonlinear_solver.C#L675) It may be hypothetically possible to modify our non-linear convergence criteria outside of PetSc, but it would not be really that simple or elegant. 

I think perhaps one option you could use is the petsc option `-snes_no_convergence_test`. This will execute your non-linear solve however many times you specified with `nl_max_its` in your input file, e.g. it will not perform convergence checks (e.g. test against `nl_abs_tol` and `nl_rel_tol`) until the very last iteration. Then if your solve failed to achieve `nl_abs_tol` or `nl_rel_tol`, then the time step will be cut as usual.

In this way you could iterate an arbitrary number of times regardless of where you are at relative to a steady-state; the con is that you will *always* use the number of iterations specified by `nl_max_its`. If you think that something like this would be satisfactory enough combined with the other existing options you're aware of (it looked like you may have had an epiphany on the list after you created this issue), then I'll close this.

**Comment by jhaase1** [comment]
Alex,

I hadn't found the while loop. I assumed that it was how the iteration
process was implements. I solved my issue by fiddling with the absolute and
relative tolerances.

Regards,

John R. Haase
jhaase1@nd.edu

**Comment by lindsayad** [comment]
Closed because @jhaase1 was able to achieve his desired solution behavior using existing solve options
