### ISSUE TITLE
Add VectorPP transfer

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#10319]
## Rationale

When doing multi-scale calculations, often a large number of PPs has to be transferred to 
sub-apps distributed in the domain where each sub-app gets one value. It would be easiest
to collect a VectorPP instead of many PPs and then assign each sub-app's postprocessor
the right value from the VectorPP. 

## Description

Implement multi-app transfer from VectorPP to PPs.

## Impact

Added capability.

**Comment by permcody** [comment]
Closed by #10320.
