### ISSUE TITLE
MultiApp Restore Enhancements

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10337]
## Rationale
Right now a MultiApp makes a decision about whether or not it needs to be restored for each solve of Picard based on the options that have been selected (sub_cycling, max_failures, catch_up_steps, etc.).  The thing is: this can be pessimistic.

For instance: if you really want the sub-app to take the full timestep all in one step.  If it fails and cuts back and does several catch up steps to make it to the final time... that final time solution value would be a REALLY good guess for the next Picard iteration which is again going to ask it to take a full step... BUT since we're using catch_up_steps... the MultiApp system will currently wipe out that solution by doing a restore at the beginning of the next iteration.

## Description
What is needed is to try to do this:

1.  Try to take the full step
2.  Let it fail and take catch_up_steps
3.  On the next Picard iteration _don't_ restore
4.  Resolve the full step
5.  If it fails... THEN restore... and start doing catch-up-steps again
6. Repeat

## Impact
This will have impact in the very complicated `TransientMultiApp::solve()` code.  It's never fun to muck around in there and any changes could have unintended consequences....

**Comment by lindsayad** [comment]
PR #10334 touches our super fun `TransientMultiApp::solveStep` code :-), although it is not related to restore
