### ISSUE TITLE
Peacock2: Block Selection in Exodus Viewer

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10336]
## Rationale
In OG Peacock we could select which blocks we wanted to view in the Exodus file.  It was SUPER handy.  The color bar also changed to reflect the min/max of only the currently visible blocks.  Need to get this back.

## Description
Add back the ability to select visible blocks in Peacock

## Impact
Add capability

**Comment by friedmud** [comment]
Ok - this exists - but doesn't quite do the right thing... the colorbar/scale needs to get rescaled using only the blocks that are showing.

**Comment by aeslaughter** [comment]
closed by #11627
