### ISSUE TITLE
DerivativeParsedMaterial does not update jitcache when variable dependence is added to material properties

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#10333]
## Rationale
DerivativeParsedMaterial does not update jitcache when variable dependence is added to material properties, so derivatives of the supplied material property are not properly calculated.

## Description
The DerivativeParsedMaterial class can use other material properties specified by `material_property_names`. If `M` is a material property listed in `material_property_names`, dependence of `M` on variables `c1` and `c2` can be declared using the syntax `M(c1,c2)`. If a user does not specify this dependence initially, the jitcache is created without awareness of the variable dependence. If the user then adds the variable dependence, the jitcache is not updated, and derivatives of `M` wrt `c1` and `c2` are not calculated. A temporary solution is to remove the old jitcache file.

## Impact
The fix will need to occur in LibMesh; this is being documented here for user awareness.

**Comment by tophmatthews** [comment]
@dschwen or @laagesen does the `M(c1,c2)` syntax always have to be supplied to ensure the derivatives wrt to `c1` and `c2` are taken, or is it that variable dependence can't be changed once jitcache is created?

**Comment by laagesen** [comment]
If you want to take derivatives with respect to `c1` and `c2` you do need to use the `M(c1,c2)` syntax in all cases. The problem this issue is addressing is when you initially specify `M` in your input file, then later in the same directory, change your input file to `M(c1,c2)` and run again. Currently there is nothing to tell MOOSE to update the .jitcache file to reflect the newly added variable dependence, so any derivatives with respect to `c1` or `c2` will incorrectly be zero. Hopefully this answers the question, please let me know if not. It should go away with the libmesh fix that Daniel mentioned.

**Comment by tophmatthews** [comment]
Oh, I misread, it's if it is given via `material_property_names`, not for the calculated material property. I assume that `DerivativeSumMaterial` naturally does this, such that `M(c1,c2)` isn't necessary?

**Comment by dschwen** [comment]
The relevant libmesh update made it into MOOSE a long time ago.
