### ISSUE TITLE
Deprecate old execute flag interface

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#10363]
## Rationale

The method for storing and using execute_on flags is changing, see #10110

## Description

This change will add deprecated messages to the old interfaces.

## Impact

The messages will cause warning in applications that are not updated to the new interface.

**Comment by aeslaughter** [comment]
@YaqiWang Yes.

**Comment by YaqiWang** [comment]
It is so nice of you. btw, is there an easy way to see which tests are containing deprecation messages?

**Comment by aeslaughter** [comment]
I think if your use run_tests with --error it will do what you want, we do that in MOOSE by default.

**Comment by permcody** [comment]
Closed by #10499
