### ISSUE TITLE
warehouse for tagged kernels

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#10366]
## Rationale
For each kernel, there may be several tags associated with it.  When we form the Jacobian and the residual, only active tags should have contribution. For the kernels without active tags, we should simply ignore them for removing the redundant work. 

## Description

Build a map from tags to warehouse. For a given set of tags, the associated warehouse is built. The warehouse stores the kernels that have at least one active tags.  

With this capability, we should be able to remove the kernel type.

## Impact
Impact everywhere.

**Comment by permcody** [comment]
@fdkong - This ticket looks incomplete. Can you flesh it out please?

**Comment by friedmud** [comment]
Ok - I'm working on this now - going to try to remove KernelWarehouse...
