### ISSUE TITLE
Add yet another option to update_and_rebuild_libmesh.sh

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#10384]
## Rationale

Sometimes developers and advanced users like to run with newer (or different) versions of libMesh from the blessed hash that's checked into the MOOSE repository. However, the current update script normally runs submodule update which clobbers a user's currently checked out version. We currently have the `--fast` option but that method doesn't run configure so that doesn't quite meet the needs of some users either. 

The use case should support somebody wanting to checkout a fresh copy of the repository but build with a different version of libMesh. Maybe the new option should be `--keep-version`, `--keep-submodule` or `--keep-sha1`. I'm open to more suggestions.

## Description

Running `update_and_rebuild_libmesh.sh` clobbers the currently checked out hash or with the fast option doesn't run configure.

## Impact

No impact, new feature.

**Comment by permcody** [comment]
FYI - @jwpeterson

**Comment by jwpeterson** [comment]
> I'm open to more suggestions.

`--skip-submodule-update` seems more natural to me (cue the skip-not-update jokes...)

**Comment by jessecarterMOOSE** [comment]
> `--skip-submodule-update`

I like this idea. When I want to compile against a specific version of libmesh, I have make a commit for the sole purpose of skipping the submodule update.

**Comment by WilkAndy** [comment]
It would be nice if this script could provide "help" if you ran it with a "-h" flag.  I know i can just read the script and see what options are available but mostly i don't have the time or inclination to do that.  A "help" is so much nicer.
