### ISSUE TITLE
execute_on = first_timestep

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10391]
## Rationale

Often in my simulations the first timestep does something special, eg things come to equilibrium before i provide a forcing function.  After that first timestep has completed i want to record something, eg displacements, and from that time onwards i want to reference things to those recorded results.  I think for this purpose, an execute_on = first_timestep would be nice, as i can record the "equilibrated" variables in AuxVariables for later processing.

## Description

AuxKernels, Postprocessors and Outputs (and probably other things) should have the "execute_on = first_timestep" functionality.

## Impact

I'm hoping one of the MOOSE developers will be able to implement this for me.  Or perhaps someone can think of an existing feature in MOOSE that fits the bill.

**Comment by permcody** [comment]
Well it's certainly possible but not very convenient. @aeslaughter even has a new custom execute_on capability where users can add new places all they want, but the catch is that you have to also inherit from the Executioner and add in the additional calls to the problem to actually perform "extra" executions of objects so it's not 100% clean. I think that the downsides to inheriting from the Executioner outweigh the benefits of adding new custom flags for most users.

There are other ways to make this work though. You could always check against time step numbers inside your objects (again, not ideal, but certainly works).

You could also look into using the "Controls" system. Every object has an "enabled" flag that you toggle. You could build a control that could grab the objects you wanted to turn off after the first time step and just toggle their flag. The Controls system is actually really nice for this as you can create arbitrary "tags" and attach them to objects so you can control groups of them at once. There's a little bit of documentation and several examples to get you going here:
http://mooseframework.org/docs/moose_docs/site/documentation/systems/Controls/framework/TimePeriod/index.html

**Comment by WilkAndy** [comment]
Holy Dooley, that Controls stuff looks fantastic.  I think i can probably just use TimePeriod to do what i want.  Thanks @permcody
