### ISSUE TITLE
Add examples for KKS phase-field model coupled with elasticity

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#10408]
## Rationale
Provide users examples to increase usefulness for phase-field modeling

## Description
Providing two input files in `moose/modules/combined/examples/phase_field-mechanics/`. One demonstrates the Voigt-Taylor scheme, one demonstrates Khachaturyan's scheme, as described in L.K. Aagesen et al., Computational Materials Science, 140, 10-21 (2017).

## Impact
None

**Comment by dschwen** [comment]
No impact? I think you are selling yourself short! This will send a thunder through the world of phase field / mechanics modelling!

**Comment by laagesen** [comment]
What can I say, I'm a Midwesterner, modesty is in my DNA

**Comment by laagesen** [comment]
:1st_place_medal:
