### ISSUE TITLE
Quetion: What is your relation to https://github.com/BhallaLab/moose ?

### ISSUE THREAD

**Issue by yurivict** [idaholab/moose#10418]
The project seems to be the same, and both have recent updates.
So what is the difference?

**Comment by dschwen** [comment]
https://help.github.com/articles/fork-a-repo/

**Comment by yurivict** [comment]
I know that it is a fork. But what is the difference between forks?
If I want to create a package for FreeBSD, which one should I choose?

**Comment by andrsd** [comment]
Hold on! There is __no__ connection between idaholab/moose and bhallalab/moose.  The idaholab one is a framework for solving PDEs, see [homepage](http://mooseframework.org/) and the latter is a neural system simulator, see [home page](https://moose.ncbs.res.in/?q=home). They are not forks of each other!

**Comment by yurivict** [comment]
Thanks for clarifying this! I totally thought that they are forks of each other. They sound really similar:

```
Idaholabs MOOSE is "Multiphysics Object-Oriented Simulation Environment (MOOSE)"
Bhallalabs MOOSE is "Multiscale Object-Oriented Simulation Environment"
```

Thanks again!

**Comment by mangerij** [comment]
:open_mouth: 

queue the lawyers!!

**Comment by yurivict** [comment]
In case anybody is interested, Bhallalabs MOOSE is a simulator of chemical reactions. It shows graphically how concentrations of particular chemicals change overtime. They have a lot of examples based on scientific research papers. One example, for instance, shows how a reaction can be cyclical when it has a feedback loop. I didn't know before that this was even possible in chemistry! Sounds a lot like electrical circuits. -)
