### ISSUE TITLE
Duplicate test names in same tests file gives confusing error

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#10424]
## Rationale
When a test name is replicated in the same test file, a confusing error occurs when running `run_tests`. A clear error or check should be made to avoid confusion.

## Description
If two tests have the same test name, the following error occurs:
```
Traceback (most recent call last):
  File "./run_tests", line 25, in <module>
    TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)
  File "/Users/topher/projects/moose/python/TestHarness/TestHarness.py", line 42, in buildAndRun
    harness.findAndRunTests()
  File "/Users/topher/projects/moose/python/TestHarness/TestHarness.py", line 222, in findAndRunTests
    self.scheduler.schedule(testers)
  File "/Users/topher/projects/moose/python/TestHarness/schedulers/Scheduler.py", line 320, in schedule
    raise SchedulerError('Runnable tests in addition to Skipped tests does not match total scheduled test count!')
TestHarness.schedulers.Scheduler.SchedulerError: Runnable tests in addition to Skipped tests does not match total scheduled test count!
```

## Impact
Helps users (aka me) avoid simple mistakes like similar test names.

**Comment by permcody** [comment]
Tag @rwcarlsen. I'm sure the fix is simple but either I (or @milljm) may need some quick guidance from you, or you might want to take this ticket when you get a chance.

**Comment by rwcarlsen** [comment]
Off the top of my head I can't think of any way my changes would have affected this behavior.  If we want we can certainly detect this lower at the parsing level - which I could do or provide some direction on (not too hard), or we could detect it later in the test harness itself; we probably should check for it at the parsing level.

**Comment by permcody** [comment]
My guess is that the old parser/old scheduler simply combined the two blocks which would sometimes work and possibly work or possibly fail but with a different bizarre error. In either case, this probably has never worked properly. I know you have a duplicate walker. For this, we'd just want to make sure we don't have duplicate test nodes and error out appropriately.

**Comment by milljm** [comment]
I think this is going to be a Scheduler issue. When we create the DAG, we are also creating a Tester Name to Tester Object dictionary. When we try to add the duplicate test to the Tester Name dictionary, we are in fact altering an item already in the dictionary.

**Comment by milljm** [comment]
Looks like Roberts parser already detects duplicates (the attributes anyway) which causes an interesting side effect after I (the scheduler) handles a duplicate test appropriately:

```pre
./run_tests -i duplicate_tests
tests/test_harness.duplicate_test_name...... skipped (duplicate test)
tests/test_harness.duplicate_test_name............................ OK


Parser Errors:
---------------------------------------------------------------------
/Users/milljm/projects/moose/test/tests/test_harness/duplicate_tests:2: duplicate section "Tests/duplicate_test_name"
/Users/milljm/projects/moose/test/tests/test_harness/duplicate_tests:6: duplicate section "Tests/duplicate_test_name"
/Users/milljm/projects/moose/test/tests/test_harness/duplicate_tests:3: duplicate parameter "Tests/duplicate_test_name/type"
/Users/milljm/projects/moose/test/tests/test_harness/duplicate_tests:7: duplicate parameter "Tests/duplicate_test_name/type"
/Users/milljm/projects/moose/test/tests/test_harness/duplicate_tests:4: duplicate parameter "Tests/duplicate_test_name/input"
/Users/milljm/projects/moose/test/tests/test_harness/duplicate_tests:8: duplicate parameter "Tests/duplicate_test_name/input"
---------------------------------------------------------------------
Ran 1 tests in 0.9 seconds
1 passed, 1 skipped, 0 pending, 0 failed, FATAL PARSER ERROR
```

If the parser detected an error, I am not sure why the Scheduler was told to do work. And pass for that matter. Is that supposed to be how it operates?
