### ISSUE TITLE
ParsedMaterial fail_on_evalerror weirdness

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#10427]
## Rationale
The `fail_on_evalerror` is a great tool to debug problems with `ParsedMaterial`. However, there seems to be some weirdness with if and when it works.

## Description
`fail_on_evalerror=true` seems to work when `enable_jit=false` and a variables is involved with the troubled math such as `sqrt(-positive_value)`. If a number or `constant_expression` is used, no error is thrown, and the solve fails as the `nan` is passed. If `enable_jit=true`, no error is thrown either.

The following input deck can be used to test

```
[Mesh]
  type = GeneratedMesh
  dim = 1
[]

[Variables]
  [./positive_value]
    initial_condition = 1
  [../]
[]


[Kernels]
  [./positive_value]
    type = MatDiffusion
    variable = positive_value
    D_name = D
  [../]
[]

[Materials]
  [./material]
    type = ParsedMaterial
    f_name = 'D'
    args = 'positive_value'
    function = 'sqrt(-positive_value)'
    fail_on_evalerror = true
    enable_jit = false
  [../]
[]

[Executioner]
  type = Transient
  num_steps = 1
  dtmin = 1
[]
```

## Impact
This will help debug failing solves by avoiding `nan` values from being thrown around.

**Comment by tophmatthews** [comment]
ping @dschwen

**Comment by tophmatthews** [comment]
This almost seems like you can do a check for a `nan` `FunctionParserUtils::evaluate(ADFunctionPtr & parser)`, since it is passing a `nan` with no error code.

**Comment by dschwen** [comment]
Use `disable_fpoptimizer = true` for debugging purposes (you'll get the error for `sqrt(-1)` as well in that case).
