### ISSUE TITLE
Documentation (*.md) file standards

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#10423]
## Rationale
As we begin to increase our efforts in updating documentation for modules, a set of standards for documentation writing and layout seems to be in order.  My intent with this issue is to start a conversation about what reasonable standards are before we add a page to MOOSE and/or the apps pages. Pinging @aeslaughter @bwspenc @permcody @dschwen @WilkAndy  @jiangwen84 @acasagran  for comments 

## Description
The following suggestions are from my work updating the BISON documentation and are intended to be amended as we discuss this issue:

**Web Page Layout**
- Give class name with spaces as the title in a human-readable manner
- Begin the *.md file documentation with the second-level heading `Description`
- Use the actual name of the class, in single quotes, within the first paragraph of the Description
- If the class documentation runs long (over one nominal webpage), use multiple second level heading to break up the text. The second level headings show in the right hand side bar to aid in page navigation.
- Immediately before including example syntax from an input file, use the second level heading `Example Input File Syntax'
- If multiple blocks are required to run an input file (e.g. the eigenstrain and strain/ master action blocks in tensor mechanics), include both blocks in the example input file syntax section.
- Use a second level heading of `References` above the bibliography command at the end of the *.md file 

**Documentation page (*.md) content**
- Focus on the theoretical base and the user facing options (generally automatically generated by `!syntax parameters`) over code implementation (e.g. inheritance) which is covered in doxygen
- Avoide duplication of citation information in the text (biblography style prints the author name and year)
- If a reference isn't in the existing bibtext file, add the reference rather than leaving citations out.
- Use American English spelling

**Equations**
- If explaining terms used in an equation immediately after the equation (e.g. the sentence begins with "where the term...."), do not include a new line between the equation and the sentence
  - Necessary to avoid starting a new paragraph in the eventual pdf document
- Use only math options supported by katex: [list here](https://khan.github.io/KaTeX/function-support.html)
  - Don't use `\mbox`
  - Do use `aligned` and `cases` environments
- To reference an equation, use `\label` within the equation environment
- If an equation includes a few or more constant value parameters, use a table to list the constant parameter variables and values instead of paragraph or a list
- Powers/ orders of magnitude should be formatted as $ 6 \times 10^{-6} $ not $ 6 \cdot 10^{-6} $ nor $ e^{-6} $
- Exponential terms should be written as $ exp \left( stuff-in-exponent \right) $ instead of $ e^{stuff-in-exponent} $

**Units**
- For dimensionless parameters, use the notation `(dimensionless)` instead of `(-)` or `(-/-)`
- Give units in regular font (not bold) (e.g. $ \mu $ m, not $\mu m$ )

**Tables and Figures**
- Include a caption to describe contents
- If applicable, include a label to reference the table/figure within the text
- Take care to set the figure image width in a manner to ensure the wrapped text is readable
  - Suggest 90-95% of text width or 70-40% text width
- All numbers and variables in tables should be in bold for consistency

## Impact
Consistent look and feel of documentation in modules and apps for easier navigation; clearer communication of documentation expectations to developers

**Comment by aeslaughter** [comment]
I like having a standard, this should be a page somewhere on the current page. Also, in the future we might be able to enforce the standard programmatically, we will have access to a complete abstract syntax tree so we can do analysis of that tree.

**Comment by sapitts** [comment]
Having automatic syntax checks would be awesome! Once we have a consensus on standards, I'll add a page with standards to an appropriate place in the documentation system.

**Comment by WilkAndy** [comment]
I'm quite happy for these to be guidelines rather than strictly enforced standards.  Before worrying about these, however, it would be quite useful for me to: (1) be able to generate the webpages on my computer (i presume all the tools are part of the moose downloadable package, but don't know how to do it); (2) be able to generate PDFs with some button-click on the webpage.  As you see, even though i've written quite a lot of markdown doco, i'm really behind-the-times !

**Comment by sapitts** [comment]
Those are fair points Andy. I'm planning to try to update a lot of documentation in tensor mechanics this week/ early January, so I'm pushing for some consensus on documentation standards to avoid having to redo documentation updating work. Not that it's hard work, yet it can be time consuming

**Comment by permcody** [comment]
> (1) be able to generate the webpages on my computer (i presume all the tools are part of the moose downloadable package,

They are in fact!

> but don't know how to do it);

It's a little clunky, IMHO, but it'll get better as we continue to work on these. Right now you start up a web-server and point a web browser at it. As you save your files in your editor, they get re-rendered in your web browser on the fly.

> (2) be able to generate PDFs with some button-click on the webpage. As you see, even though i've written quite a lot of markdown doco, i'm really behind-the-times !

The PDF generation capability is a little bit elusive. I think it can be done, but it's difficult coming up with a way to generate nice LaTeX and HTML pages with a single source without significant compromises. For out part, we are making sure that the HTML route is as seamless as possible. It needs to work without a network, it needs to be fast and easy. We are pushing people to consider using HTML for more of their documentation needs in the future because the interface is just a little bit richer and has more potential than LaTeX, which shines as a print format.

**Comment by WilkAndy** [comment]
@sapitts - yes, very time consuming!!!   Part of your mission to prevent Modules from decaying.  Thank you!

@permcody - thanks for the info.  I can't remember having ever created a web-server, so will report back if it doesn't work.  PDF - rather necessary for old-fashioned pedantic "standards" or "regulator" type of people.  Let's hope we (you!) get something working at some stage.

**Comment by WilkAndy** [comment]
@sapitts - to encourage use of your standards, how about creating a simple template.md that i can use?  Many of your suggestions (although not all of them) could be summed up in a template.md that was very short.  My entire modus-operandi is to find some file that is similar to what i want, rename it, and overwrite with my new material.  If i could use your template.md as my starting point i bet i'd almost always conform to your standards.

**Comment by WilkAndy** [comment]
Another standard: use American English

**Comment by sapitts** [comment]
Thanks @WilkAndy for both suggestions!  I've added the American variant of English to the list, and I'll look into how to make a template and push a pull request for review from @aeslaughter, you and others

**Comment by aeslaughter** [comment]
I am working on the system as a whole to take what we have learned over the
past year of using what we have. For the new system, I am focusing on speed
and latex conversion. The latex conversion will fall short of having a
button, but it should be a simple command.

To build the current documentation you will need a recent package and then
do the following.

1. cd ~/projects/modules
2. make -j8
3. cd ~/projects/moose/docs
4. ./moosedocs.py build --serve
5. Open a browser with the web address shown after 4 finishes (it will take
about 3 to 5 min.)

**Comment by WilkAndy** [comment]
Oh, those steps sound pretty easy, thanks @aeslaughter

**Comment by sapitts** [comment]
Closed by #10510
