### ISSUE TITLE
run_tests trys to pull in git branches named tests

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#10435]
## Rationale
If there is an old branch named `tests`, `run_tests` tries to parse the file as a typical `tests` file, and throws a `Fatal Parser Error`. I don't remember seeing this before, so maybe this is a result of a recent change? It may not be a branch name exactly, it may be a merge request, but you get the idea.

## Description
If there is an old branch called `tests`, `run_tests` throws the error:
```
Parser Errors:
-------------------------------------------------------------------------------------------------------------
/Users/topher/projects/fecd_tools/.git/logs/refs/remotes/origin/tests:1: expected '=' after parameter name '0000000000000000000000000000000000000000', got 'b'
/Users/topher/projects/fecd_tools/.git/refs/remotes/origin/tests:1: expected '=' after parameter name 'bf66d831484225ae3d215de7a933b49f2d89f252', got '
'
-------------------------------------------------------------------------------------------------------------
```

## Impact
Only `tests` files will actually be tested, decreasing user issues.

**Comment by permcody** [comment]
Holy Dooley!

Tag @milljm

**Comment by brianmoose** [comment]
This just bit a raven PR: https://www.moosebuild.org/job/146040/

**Comment by brianmoose** [comment]
The TestHarness doesn't even ignore submodules properly. If there is a "tests" **file** in a submodule it will still try to process it. It will ignore directories in the submodule though.

**Comment by permcody** [comment]
Nice catch @brianmoose!
