### ISSUE TITLE
Separate MooseApp::meshOnly() into two parts

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10434]
## Rationale
We had few more actions that are required to be executed in mesh only mode. So I suggest to split `MooseApp::meshOnly()` into two, one for executing actions required for mesh-only and is virtual, another is for outputting the mesh. In this way, applications can override the first part without worrying potential changes in the second. Other suggestions are welcome.

## Description
As above.

## Impact
Internal interface change for new capability.

**Comment by permcody** [comment]
This sounds reasonable. For curiosity sake, can you elaborate on what you plan to do in your application?

**Comment by YaqiWang** [comment]
We have something called multischeme transport capability in Rattlesnake. If there are more than one transport systems specified in an input, Rattlesnake will add mesh modifiers to change the mesh slightly for applying different weak forms on subdomains. This modifiers are done through a new action task, which runs after moose `add_mesh_modifiers` task and is desired to be in the task list for mesh only.
