### ISSUE TITLE
Add a new parameter in EqualValueConstraint

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10433]
## Rationale
A new parameter in `EqualValueConstraint` is desired. This parameter will control how the Jacobian for this constraint is assembled. Currently, we implemented the off-diagonal Jacobian and on the diagonal the Jacobian is zero. This creates a saddle point matrix and precludes usage of some preconditioning techniques. On the other hand, we can do domain split preconditioning.

## Description
So this new parameter will be used to fill identity matrix corresponding to the constraint variables on the diagonal and disable the assembling of the off-diagonal Jacobian. By doing this, we can still use preconditioners like with BoomerAMG for PJFNK.

## Impact
A new capability.

**Comment by YaqiWang** [comment]
I could send in a PR if you agreed. Tag @andrsd.

**Comment by andrsd** [comment]
It looks like a new object would be a better solution than a parameter in `EqualValueConstraint`

**Comment by YaqiWang** [comment]
I will close this then.
