### ISSUE TITLE
Delete call to computeResidual at end of FEProblemBase::computeJacobian

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#10446]
## Rationale
There's no solve reason to do this.

## Description
The actual residual vector used in petsc is not passed to us during a Jacobian computation (see https://github.com/libMesh/libmesh/blob/master/src/solvers/petsc_nonlinear_solver.C#L158). We could possibly access the residual through the `snes` object but there's not really a reason to. Petsc will compute finite differences through calls to `__libmesh_petsc_snes_residual` and consequently our MOOSE residual routines; the MOOSE jacobian calculation thread is not called during finite differencing.

If we simply delete those lines, only four tests fail:
```
multiapps/picard_failure.test............................................................... FAILED (EXODIFF)
materials/material_dependency.dont_reinit_mat_for_aux....................................... FAILED (EXODIFF)
outputs/iterative.csv....................................................................... FAILED (CSVDIFF)
postprocessors/all_print_pps.test........................................................... FAILED (CSVDIFF)
```
If that call was truly necessary for our finite differencing then I would expect a ton of test failures.

## Impact
This will save one residual evaluation for every non-linear iteration when performing matrix-free solves.

**Comment by lindsayad** [comment]
17 fails in modules; all in combined and related to contact I believe:
```
combined/test:contact.4ElemTensionRelease_no_new_nonzeros................................... FAILED (EXODIFF)
combined/test:normalized_penalty.kin_Q4..................................................... FAILED (EXODIFF)
combined/test:normalized_penalty.kin_Q8..................................................... FAILED (EXODIFF)
combined/test:catch_release.test............................................................ FAILED (EXODIFF)
combined/test:contact.4ElemTensionRelease_constraint........................................ FAILED (EXODIFF)
combined/test:contact.4ElemTensionRelease_dirac............................................. FAILED (EXODIFF)
combined/test:nodal_area.Hex20.............................................................. FAILED (EXODIFF)
combined/test:nodal_area.Hex20_3............................................................. FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/single_pnt_2d.mu_0_0_pen_sm................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/single_pnt_2d.frictionless_pen_sm............. FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/single_pnt_2d.mu_0_0_kin_sm................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/single_pnt_2d.frictionless_kin_sm............. FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/plane_3.frictionless_kin...................... FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/cyl_3.frictionless_kin........................ FAILED (ERRMSG)
combined/test:contact_verification/patch_tests/single_pnt_2d.mu_0_2_pen...................... FAILED (ERRMSG)
combined/test:generalized_plane_strain_tm_contact.generalized_plane_strain_tm_contact........ FAILED (ERRMSG)
combined/test:nodal_area.Hex27............................................................... FAILED (ERRMSG)
```

**Comment by lindsayad** [comment]
@andrsd @fdkong Are you able to look at GitHub?

**Comment by lindsayad** [comment]
@jasondhales @bwspenc In my experience this call helps with contact convergence, but I don't really understand why it should. I feel like this has to be some interplay between the update of the contact set and computation of the contact force.

**Comment by fdkong** [comment]
> @andrsd @fdkong Are you able to look at GitHub?

Yes, I am able to look at GitHub now :). I do not understand why it is  added at the first place.

**Comment by bwspenc** [comment]
My first take is that those tests all involve the contact area. Maybe the contact area isn't up to date the first time through?
