### ISSUE TITLE
TestHarness filter for types of blocks

### ISSUE THREAD

**Issue by kevindugan** [idaholab/moose#10457]
## Rationale
I have a test case which I would like to filter when a specific type of Executioner is not present. The current implementation does not seem to account for this situation

## Description
The test harness currently can filter out objects that are in the "blocks", "subblocks", and "subblock_types" categories of the JSON executable output. When I attempt to filter a specific type of Executioner, for example, the filter does not locate my executioner because the executioner is located under Executioner/types/*. I would like to append a new category ("types") to the object search.

## Impact
This change should not impact the public API. The only detrimental impact I can see would be the extra time needed to search through the new category, but preliminary testing doesn't show a significant impact.

**Comment by permcody** [comment]
I'm curious what you are after here. 
I'm the one who originally put that code in there and I don't like it because it bleeds semantics from the input file into the TestHarness which ideally should just run tests based on specifications. The code in question was added to avoid running two part tests when they were steady but the same functionality could have just as easily been added to MOOSE (e.g. exit when trying to do a "half transient" or "recover" with a "steady" executioner which is all pretty MOOSE specific). 

Anyway, I'm not saying that we shouldn't support what you are after, I just want to make sure it's the right solution and that there aren't better options available.

**Comment by kevindugan** [comment]
I've got a situation where I'm coupling two external codes which both solve similar problems, but aren't quite compatible (as far as linking codes goes). The two codes have data structures which have lots of overlap in naming; making it difficult for them to be compiled together within MOOSE. 

To get around this, I'm inserting switches in the app Makefile which look like the MOOSE module switches. So when I turn off one of the two solvers, that part of the source code doesn't compile. My problem appears when these tests go looking for the turned-off solver. This is why I was wanting to turn off the specific tests which require the Executioner linked to the turned-off solver.

I think it's a very similar situation to how the modules are set up in MOOSE, but for the moment it's a matter of not compiling a handful of files; I thought that creating a full module was a little overkill for this case. What I'm wanting to change seems like a quick-fix, but it had minimal impact on the existing code.

As an aside, I had thought of another solution but it involves a little more code surgery. I think if we were to parse the JSON dump of the executable into a tree instead of a dictionary, we could access nodes of the parse tree like Executioner.types.myExecutioner. This would move the input syntax to the test file instead of in the test harness. Though I'm not certain how this strategy would affect other parts of the code.

**Comment by permcody** [comment]
> As an aside, I had thought of another solution but it involves a little more code surgery. I think if we were to parse the JSON dump of the executable into a tree instead of a dictionary, we could access nodes of the parse tree like Executioner.types.myExecutioner.

This is actually possible and may already be at your fingertips. We developed a new parser called "hit" which does exactly that. It's loads the input into an AST that you can query naturally. I haven't been involved in this but we've converted over MOOSE and many of the other python projects that read our "Getpot" format. It's a possibility.

Another option is to create more caveats that we can inspect with the test harness to just tests on or off conditionally based on your flags. We have a system in the TestHarness right now that reads the "libmesh_config.h" file to figure out all sorts of system related information. We then use that information to run tests based on platform, compiler, configuration options, etc. For your case, it might make sense to read your flag and make a decision on whether or not to run a test. If this sounds good to you I can point you to the right places in the code and advise you on how to proceed.

**Comment by kevindugan** [comment]
I much prefer a solution which has some generality and others might be able to use. What I've got so far is pretty specific.

I think looking at the hit parser might be the best option here. My condition wouldn't necessarily be system specific but would be build specific. This is why I was wanting to proceed with flags in the Makefile. I'd like to hear your advice on how you would proceed, though.

**Comment by brianmoose** [comment]
@permcody It sounds like he is just trying to skip tests if they don't have a specific type in the JSON dump, using the "required_objects" in the tests spec file (introduced in #9575 to allow mammoth to conditionally skip tests depending on compilation flags).
 Ie, in the `tests` file, something like:
`required_objects = MyCustomExecutioner`
The names that `required_objects` looks at just needs to add the various "types", which for some reason wasn't included and really should be. Should be a one line change.

**Comment by kevindugan** [comment]
@brianmoose This is what I've done in the first commit to this issue (e5609d4). I think Cody was not liking this solution because this requires hard-coded input syntax in the TestHarness. I'm playing around with leveraging the hit parser to move that syntax out of the TestHarness.

**Comment by brianmoose** [comment]
As @dschwen pointed out in #6781 , object names are unique in MOOSE, so we don't really need to specify the whole path to the object, like `Executioner.types.myExecutioner`. `myExecutioner` suffices. That is the current reason we just have a set of object names that `required_objects` checks.

**Comment by permcody** [comment]
Oh thanks @brianmoose. I had completely forgot about the required objects capability. That may be your best bet. Yes, it still bleeds a little bit of MOOSE specific "stuff" into the test specification, but it's a pretty reasonable approach. Writing code to look at a Makefile or config file is just as project specific. See if Brian's suggestion works for you.

**Comment by permcody** [comment]
>  This is why I was wanting to proceed with flags in the Makefile.

Well if those objects aren't showing up in the dump, that's what the `required_objects` parameter is for.

**Comment by kevindugan** [comment]
Yes, this is the way I was originally wanting to proceed. 

I can submit a pull request for the changes made in commit e5609d4, which adds a search under the "types" section of the JSON file generated from the executable.

**Comment by brianmoose** [comment]
closed via #10465
