### ISSUE TITLE
A dummy FEProblem for testing?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10451]
## Rationale
We only need to test a particular object like a postprocessor, a mesh, etc. For such a test, we have to repeatedly add dummy variables, kernels, bcs, etc. to make the input valid. Can we have a new FEProblem like `SteadyTestFEProblem`, so we can just add this in the input
```
[Problem]
  type = SteadyTestFEProblem
[]
```
or in command like `--test-steady`, instead of adding those dummy objects?

## Description
Just an idea. Looks like we already have `--minimal` which is similar.

## Impact
A new capability for adding test more easily.

**Comment by permcody** [comment]
I think I'd prefer to flesh out the use of "Minimal" a bit more rather than add another new type. Do you make use of the "solve = false" and "kernel_coverage_check = false" parameters? That also helps minimize the number of objects you need in a test input file.

**Comment by YaqiWang** [comment]
Yes, you are right, "solve = false" and "kernel_coverage_check = false"  help unless a dummy variable with a random distribution is required for providing a source.

**Comment by YaqiWang** [comment]
I am closing this because "solve = false" and "kernel_coverage_check = false"  meet my requirement.
