### ISSUE TITLE
FEProblem::adaptMesh Should Return bool

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10459]
### Description of the enhancement or error report
It can be useful to know if the mesh actually changed.  `FEProblem::adaptMesh()` should return a `bool` stating whether or not the mesh actually changed.

### Rationale for the enhancement or information for reproducing the error
Currently there is no way to tell externally that the mesh changed when you call `adaptMesh()`

### Identified impact
None

**Comment by andrsd** [comment]
> Currently there is no way to tell externally that the mesh changed when you call adaptMesh()

Well, systems should be notified via `MeshChangedInterface::meshChanged()` if mesh changed. Why cannot you use that?
