### ISSUE TITLE
Add LANL copyright info to COPYRIGHT

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#10466]
## Rationale
This is in preparation of future LANL collaboration to the framework, while keeping the lawyers happy.

## Description
For LANL created or modified models, the following header will be applied to the .h and .C files:
```
/****************************************************************/
/*               DO NOT MODIFY THIS HEADER                      */
/* MOOSE - Multiphysics Object Oriented Simulation Environment  */
/*                                                              */
/*           (c) 2010 Battelle Energy Alliance, LLC             */
/*         (c) 2017 Los Alamos National Security, LLC           */
/*                   ALL RIGHTS RESERVED                        */
/*                                                              */
/*          Prepared by Battelle Energy Alliance, LLC           */
/*            Under Contract No. DE-AC07-05ID14517              */
/*            and Los Alamos National Security, LLC             */
/*            Under Contract No. DE-AC52-06NA25396              */
/*            With the U. S. Department of Energy               */
/*                                                              */
/*            See COPYRIGHT for full restrictions               */
/****************************************************************/
```

The COPYRIGHT file will then include the full wordage
```
Copyright (2017). Los Alamos National Security, LLC.
This material was produced under U.S. Government contract DE-AC52-06NA25396 
for Los Alamos National Laboratory (LANL), which is operated by 
Los Alamos National Security, LLC for the U.S. Department of Energy. 
The U.S. Government has rights to use, reproduce, and distribute this software.  
NEITHER THE GOVERNMENT NOR LOS ALAMOS NATIONAL SECURITY, LLC 
MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY LIABILITY 
FOR THE USE OF THIS SOFTWARE.
```

## Impact
Files modified by LANL will need to retain the copyright header, and that may mean if there is a header check script, it'll have to be modified.

**Comment by tophmatthews** [comment]
ping @permcody @rcm59. This issue will only address the `COPYRIGHT` file changes, the header changes will be applied on the fly as files are added or changed. Mostly, this is just to get the method all fleshed out.

**Comment by permcody** [comment]
@tophmatthews - Looking at this new header, I think we see several shortcomings on our part. Now that we are adding LANL, we really should be granting credit to contributors from other laboratories and other universities etc.

I think it's time for us to change the header on all of MOOSE to direct people to the copyright and license files where we can maintain a curated list of contributors and copyright holders. Let me throw up a different header and see if you think that'll suffice.
