### ISSUE TITLE
An issue in CoupledForce?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10475]
## Rationale
`CoupledForce::computeQpJacobian()` is always returning 0. How if the coupled variable is the variable itself? At least the code does not stop us from doing that. Looks like the Jacobian will not be assembled correctly in this case if I am understanding correctly.

## Description
https://github.com/idaholab/moose/blob/devel/framework/src/kernels/CoupledForce.C

## Impact
Make implementation more robust.

**Comment by permcody** [comment]
Umm, Don't use CoupledForce for coupling in "this" variable?! We have a multiple forcing kernels which add a forcing term to "this" variable. This particular kernel is intended to get the forcing term from a coupled term which is assumed to be from a different equation. Yes, I supposed we could add an error check to prevent you from coupling to yourself, but that's never been needed before.

**Comment by permcody** [comment]
We will accept a PR that checks for this condition (just make sure to provide a test).
