### ISSUE TITLE
MooseDocs can get tangled up in libMesh submodule content

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#10513]
## Rationale

If you are using the libMesh submodule it is possible that MooseDocs, when searching 
for class definitions in the source code, can have problems. In addition, searching 
libMesh source code is not needed.

## Description

I can't reproduce it, but see the problem when walking over all directories in MooseClassDatabase.

## Impact

Internal change only, the MooseClassDatabase just needs to be restricted.

**Comment by permcody** [comment]
What kind of English is this? Title makes no sense.
