### ISSUE TITLE
Adjust HEMFluidProperties for use in Bison

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#10549]
## Rationale
The current interface is not sufficient for Bison's needs.

## Description
Quality from saturation temperature and enthalpy, density from pressure, temperature, and quality, and enthalpy from pressure, temperature, and quality are needed.

## Impact
This will extend the API, making it useful for Bison.

**Comment by andrsd** [comment]
Looks like this was supposed to be closed, but it was only referenced. If more work is needed, new issue should be opened.
