### ISSUE TITLE
A script for formatting inputs

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10541]
## Rationale
Input files are not well formatted as the codes.

## Description
We could have a script to take care of the indentation, removing parameters whose values are equal to their default.

## Impact
As the clang formatter, this will save both developer and reviewer's time.

**Comment by permcody** [comment]
This is already possible with the HIT parser. However, we don't currently enforce any standard, nor do we have a script that will just apply formatting. Before we do something like this, we'll have to make sure we have the ability to check for formatting through CIVET to avoid regressions.
