### ISSUE TITLE
some redirected out is not available, but others are

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#10570]
## Rationale
For parallel tests that are supposed to crash (RunException), we are checking for files that we expect to be available. When we find a file is not available, we process none of the files that _are_ available.

## Description
TestHarness util.py checkOutputReady is returning False when it discovers a file is not readable. The problem with this, is when we have multiple output files, and some of them never completed (MPI killed the process before it had a chance to write output), we never try and check the output that _is_ created from the others processes that did complete (and error correctly).

## Impact
None

**Comment by permcody** [comment]
Oh! Good catch!
