### ISSUE TITLE
Updating accessibility of `_func` member in `FunctionPenaltyDirichletBC`

### ISSUE THREAD

**Issue by BruceWyxv** [idaholab/moose#10580]
## Rationale
The member `_func` has private accessibility in `FunctionPenaltyDirichletBC`, preventing any subclasses from being able to use it.

## Description
`_func` was moved to the `protected` block.

## Impact
Makes `_func` accessible for use by subclasses. No impact to the standard user.

**Comment by permcody** [comment]
This change is fine, but in general you might be surprised at how much changing a method from private to protected might impact the framework down the line. Sometimes developers need to be able to control a private parameter but by making it public, derived classes can start changing the parameter at will which can cause certain assumptions to be violated and in the worst case unexpected consequences to arise when refactoring. 

I reviewed this class and there's no issue with this particular change. Will merge when it's done testing.
