### ISSUE TITLE
Add a parameter uniform_refine in FunctionDT

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10598]
## Rationale
This can make convergence study by uniformly refining time step sizes easier.

## Description
It is like `uniform_refine` in `Mesh`, but works in time.

## Impact
None. A new capability.

**Comment by YaqiWang** [comment]
It will just dividing all elements in `_time_dt` by two `uniform_refine` times. I will send it a PR for this.

**Comment by andrsd** [comment]
I personally do not like this. I think what should actually happen is that `FunctionDT` should take a function (and for backwards compatibility `_time_t` and `_time_dt`). Then to do your convergence study you'd use `PiecewiseConstant` and uniform refine in time would be achieved by using the `scale_factor` parameter.

**Comment by YaqiWang** [comment]
You are right. The name of `FunctionDT` is misleading. It actually only supports piece-wise linear or constant functions. It does not accept a general function. The only problem is that it will require a refactoring and possibly lots of input file changes. It is unfair to me in that I am only using a small functionality of this stepper and adding a small enhancement. I suggest we get this in and create a new issue to fix `FunctionDT`. How does this sound?

**Comment by andrsd** [comment]
As I said `_time_t` and `_time_dt` is gonna stay and will be deprecated. If used, we fall back to the old behavior. If the new function name parameter is specified, we use the function. That's pretty easy to do. I can work on it, if you do not have time. With that in mind, I do not see much reason to put this in.

**Comment by YaqiWang** [comment]
Works for me. You can create a new issue to better represent the work to do and feel free to close this one and the PR.
