### ISSUE TITLE
TestHarness suppresses errors

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/moose#10607]
## Rationale

When working on a new Tester subclass using the Python test harness framework, if an instance of the subclass throws a Python exception, minimal information is provided, and often insufficient to quickly debug the reason for the exception.  Additionally, this can result in a false positive for passing tests.

### Observed Behavior
When a Tester subclass instance being used in a `runWorker()` call results in a run-time Python exception being thrown, it is caught generically by the `TestHarness.schedulers.Scheduler.runWorker()` method, which is wrapped entirely in a try-catch.  The resulting information to the user is `runWorker Exception:` followed by a printout of the exception message, without any additional information.

Furthermore, this exception does not result in the overall tests reported as crashed or failing; instead, if tests have passed up to when the exception was raised, the test harness reports an "all passed" state, which is misleading at best.  See for example:
```
[...]
framework.external_xml.................................................................................... OK
framework.custom1D........................................................................................ OK
framework.LHSVariables.................................................................................... OK
framework.SimulationTags.................................................................................. OK
framework.testExternalModelReseed......................................................................... OK
runWorker Exception: Error tokenizing data. C error: Expected 4 fields in line 3, saw 5

-------------------------------------------------------------------------------------------------------------
Ran 27 tests in 117.1 seconds
27 passed, 13 skipped, 0 pending, 0 failed

Successfully tested raven.
```
Even though the application from this example has over 400 regression tests, after the runWorker exception is printed, the harness exits with a "success" status on the 27 tests run, while the result of the remaining tests is unknown.

### Desired Behavior
What is missing in the crash report is the test in which the exception occurred, the module and method that raised the exception, and the line number at which the exception was raised, which is typically provided by the Python traceback.

Additionally, a non-passing state passed to CIVET would prevent faulty assumptions about tests passing when run automatically.

## Impact

Changing the lines of code after the `except Exception` at the end of `runWorker` to call `self.killRemaining()` and then _raise_ the exception (`raise e`) might provide the missing details that would be useful.

I don't know immediately how the reporting of pass-fail can be changed, but would be happy to investigate it further.

Both these changes seem straightforward initially, and I'd be happy to prepare a PR with them.

This would have positive impact on developers of MOOSE-based apps that use custom testers, by increasing the accuracy and transparency of the test harness performance.

**Comment by milljm** [comment]
Catching errors that happened in a child thread is difficult. Which is why it looks as if the TestHarness does not error. Example difficulties capturing exceptions in threads: https://stackoverflow.com/questions/2829329/catch-a-threads-exception-in-the-caller-thread-in-python

I am open to suggestions! and PRs!

Have you tried your solution? When I try to raise e, I certainly don't get a stack trace. The child thread simply dies, while the parent moves on regardless of a raise. Which is why I instead print the exception, and then ask the parent to kill all its children because well... we did error _somewhere_.

I know there are betters ways, and I welcome a better solution...

**Comment by milljm** [comment]
@brianmoose 
Just gave me a solution to this:

```python
        except Exception as e:
            import traceback
            print('runWorker Exception: %s' % (traceback.format_exc()))
            self.killRemaining()
```
That will print your stack 🥂

**Comment by PaulTalbot-INL** [comment]
Excellent, thanks!  I'll work on that here shortly.
