### ISSUE TITLE
getPostprocessorValue in Executioner does not work properly with default value

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10603]
## Rationale
If we give a default value to a parameter in type of `PostprocessorName` in Executioner, it will prevent us from getting the correct postprocessor value even if the postprocessor is set to a defined postprocessor.

## Description
Did I miss something? I vaguely remember I had similar issue with the action system and have to give up using the default value.

## Impact
Fix another brain damage.

**Comment by permcody** [comment]
Yes, this is the whole "late binding" problem. I have a fix that takes care of it, and it passes every test in every application except for a few in Rattlesnake (Yak) that were complicated. I think it also cleans up a number of other things related to Postprocessors, but I really hit a wall with your application. 

https://github.com/idaholab/moose/pull/5607

**Comment by YaqiWang** [comment]
Really? I possibly can check out that to take a look.
