### ISSUE TITLE
Adding DynamicTensorMechanicsAction through another action does not work

### ISSUE THREAD

**Issue by cbolisetti** [idaholab/moose#10619]
## Rationale
I am trying to set up DynamicTensorMechanicsAction as a part of a bigger action, but it does not get executed.

## Description
DynamicTensorMechanicsAction is setup to get executed during three tasks. But when set up using an action (called `SetupDynamicTensorMechanicsAction` in the commit), it is executed only during one task. I created two test problems that highlight this issue. 

When I run the test problem (3D_QStatic_1_Ramped_Displacement_noaction.i) I see the following tasks: 
```
[DBG][ACT] TASK (     setup_mesh_complete) TYPE (    DynamicTensorMechanicsAction) NAME (DynamicTensorMechanics)
[DBG][ACT] TASK (validate_coordinate_systems) TYPE (    DynamicTensorMechanicsAction) NAME (DynamicTensorMechanics)
[DBG][ACT] TASK (              add_kernel) TYPE (    DynamicTensorMechanicsAction) NAME (DynamicTensorMechanics)
```
When I run the same test problem with the action I set up (3D_QStatic_1_Ramped_Displacement_withaction.i), I see only one task as follows: 
```
[DBG][ACT] TASK (     setup_mesh_complete) TYPE (    DynamicTensorMechanicsAction) NAME (DynamicTensorMechanics)
```

## Impact
Not a huge impact for MOOSE, but this needs to be figured out for MASTODON app and possibly for the TensorMechanics module.

**Comment by dschwen** [comment]
I'm not buying it. There is nothing special about that action. Can you point us to the code where you try this meta action setup?

**Comment by permcody** [comment]
I'm happy to look into this issue, push your branch so I can check it out.

**Comment by cbolisetti** [comment]
Thanks @permcody I just pushed my branch and updated the issue.
