### ISSUE TITLE
Bug in NodalKernel compute jacobian thread

### ISSUE THREAD

**Issue by sveerara** [idaholab/moose#10620]
## Rationale
When two child objects of nodal kernel are in the input file, the first one acting on disp_y and the second one acting on disp_x, the computeJacobian() function gets called only on the first nodal kernel object.

## Description
The ComputeNodalKernelJacobiansThread and ComputeNodalKernelBCJacobiansThread call the computeOffDiagJacobian function for a set of active block and boundary restricted nodal kernels, respectively. Due to a break statement present in these two classes, the list of active nodal kernels is not correctly updated.

## Impact
Minor bug fix. Should not affect any tests.

**Comment by andrsd** [comment]
Please, do not edit the template. Need the description section. Thanks!

**Comment by sveerara** [comment]
Sorry about editing the template. I will remember not to do that the next time. Thanks.
