### ISSUE TITLE
peacock mouse interaction broken

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#10632]
## Rationale

@milljm found that interacting with the VTKWindow using a mouse doesn't work.

## Description

Can't zoom in/out, rotate, etc.
Looks to be caused by #10614 . I reverted those changes and it started working again.
@aeslaughter Any ideas?

## Impact

Make peacock work again.

**Comment by aeslaughter** [comment]
I have no idea why this would change things.

**Comment by brianmoose** [comment]
It appears that the culprit is:
`self.__vtkinteractor.RemoveAllObservers()` from [here](https://github.com/idaholab/moose/blob/8df375ab78c8ed7569e13a54634311b9c5b2c347/python/chigger/RenderWindow.py#L238)

@aeslaughter I am not overly familiar with VTK, is one of the observers an Mouse event observer?

**Comment by aeslaughter** [comment]
@brianmoose You likely nailed it, I was thinking that function would clear all observers that are added by the "observers" option, I did not think about any existing observers. This will need to be improved, I have an idea. It should be possible to loop over all the "observers" coming from the user and only had them if they do not exist.

**Comment by brianmoose** [comment]
closed via #10640
