### ISSUE TITLE
'gold_dir' not respected for CSVDiff

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#10647]
## Rationale
The `gold_dir` option for `CSVDiff` tests doesn't seem to be respected. `Exodiff` works great, with similar input.

## Description
If you move the `kernels/ode` gold directory back one directory:
```
mv test/tests/kernels/ode/gold test/tests/kernels/gold
```
and then add `gold_dir = '../gold'` to each of the tests in `test/tests/kernels/ode`, the `Exodiff` tests succeed, but the `CSVDiff` fails.

## Impact
This will allow `CSVDiff` to use gold directories other than the default.

**Comment by tophmatthews** [comment]
I think I already have a fix for this, I'll do a pr

**Comment by tophmatthews** [comment]
Wait...how is `test/tests/test_haress` tested?

**Comment by permcody** [comment]
Looks like you figured it out!
