### ISSUE TITLE
Dependency is wrong!

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10672]
## Rationale
@fdkong and @lindsayad 's recent work made me look into one of my runs carefully and noticed that the nonlinear residual norm disagrees with the residual norm of the linear iteration in the next nonlinear iteration. After some painful debugging, I found the dependency of two auxkernels on linear are not resolved properly.

## Description
I am able to produce this with a MOOSE test with the change as follows:
```
diff --git a/test/tests/kernels/adv_diff_reaction_transient/adv_diff_reaction_transient_test.i b/test/tests/kernels/adv_diff_reaction_transient/adv_diff_reaction_transient_test.i
index 84172a3f6a..e8e73555f9 100644
--- a/test/tests/kernels/adv_diff_reaction_transient/adv_diff_reaction_transient_test.i
+++ b/test/tests/kernels/adv_diff_reaction_transient/adv_diff_reaction_transient_test.i
@@ -61,6 +61,31 @@
 
 []
 
+[AuxVariables]
+  [./v1]
+    family = MONOMIAL
+    order = CONSTANT
+  [../]
+  [./v2]
+    family = MONOMIAL
+    order = CONSTANT
+  [../]
+[]
+
+[AuxKernels]
+  [./v1]
+    type = VariableTimeIntegrationAux
+    variable = v1
+    variable_to_integrate = v2
+    execute_on = linear
+  [../]
+  [./v2]
+    type = SelfAux
+    variable = v2
+    execute_on = linear
+  [../]
+[]
+
 [BCs]
 
   active = 'btm_sca rgt_sca top_sca lft_sca'
```
If you add print-outs in `AuxKernel`, you will see `v2` is executed after `v1` although it should be before. Am I missing something?

## Impact
The impact is unknown could be huge.

**Comment by permcody** [comment]
Superseded by #10713.
