### ISSUE TITLE
moosedocs.py fails on new system

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10674]
## Rationale

moosedocs.py -h returns:

The following packages are missing but required:
 - markdown
 - pybtex
 - livereload
 - pylatexenc
 - anytree

## Description

Today, I upgraded to HighSierra, re-did the xcode command-line tools, quartz, installed the latest HighSierra MOOSE package, pulled the latest devel MOOSE, cleaned and rebuilt absolutely everything (blah, even including libmesh), so I think everything is completely fresh.

## Impact

Ease of use

**Comment by permcody** [comment]
Tag @milljm

**Comment by milljm** [comment]
@aeslaughter Are these the things that are now needed?

**Comment by milljm** [comment]
These things are already included in the package. This is not a moose issue, but a mailing list question on its use.

**Comment by WilkAndy** [comment]
OK, i'll write a mailing-list email,

a
