### ISSUE TITLE
Make test harness save the screen output somewhere even when tests are OK

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10681]
## Rationale
With this saved screen output, which contains the convergence history, and the screen output with failing tests, we can check the diff fairly quickly.

## Description
Maybe just add an extra link under *Results*, like `Download full output as tarball`.
Considering that it is a little painful to build two versions of applications, this could be a handy feature.

## Impact
Just keep possibly useful information for developers. No impact.

**Comment by permcody** [comment]
This has been a feature for like 8 years!

```
 -x, --sep-files       Write the output of each test to a separate file. Only
                        quiet output to terminal. This is equivalant to
                        '--sep-files-fail --sep-files-ok'
```

**Comment by permcody** [comment]
If you are talking about CIVET, that doesn't have anything to do with the TestHarness. I hesitate to do this because we run over a million tests every day and we are limited on storage space.
