### ISSUE TITLE
Initial residual evaluation should not evaluate objects only on linear

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10699]
## Rationale
Otherwise, some side effect could show up.

## Description
This is a subtle issue revealed by one Rattlesnake heavy test. In that test, we are using `CrankNicolson` time integrator, which requires a residual evaluation on initial. That test contains an auxiliary kernel on `linear`, which is integrating another variable in time with `VariableTimeIntegrationAux`. Its corresponding auxiliary variable is coupled back in kernel evaluations. The initial residual evaluation will actually invoke that aux kernel and change the variable from its initial value. My fix in https://github.com/idaholab/moose/pull/10564 changes the behavior because the current solution is copied to the old solution before the fix but not after the fix, thus the evaluation on that aux kernel gives different values. Neither gives the correct answer though. The initial value of the variable should not be changed.

The correct way is to not update that aux variable and use the values set by the initial condition. Although currently that aux kernel is only on linear, MOOSE will call it on the initial residual evaluation.

I think the proper solution is to create one function `FEProblem::computeInitialResidual()` which is almost identical to `FEProblem::computeResidualType()` except that
1. It does not need the third argument for kernel type. The kernel type will be always `Moose::KT_NONTIME`.
2. It does not need `_nl->computeTimeDerivatives()` in the function.
3. All `EXEC_LINEAR` needs to be replaced with `EXEC_INITIAL`.

If you think this is the right move, I can submit a PR really quickly. I do need your opinions. Tag @andrsd @permcody.

## Impact
The impact should be small. It should only affect a subset of tests using Crank-Nicolson time integrator.

**Comment by YaqiWang** [comment]
Another thing to be considered is that the initial residual evaluation requires evaluation of initial objects, which has been done in `FEProblemBase::initialSetup()`. We possibly just need a flag in `FEProblemBase` indicating if initial residual evaluation is needed or not. Then we can simple call `NonlinearSystemBase::computeResidual` in `FEProblemBase::initialSetup()` right after https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblemBase.C#L705.

**Comment by YaqiWang** [comment]
Another issue bothering me for a while, https://github.com/idaholab/moose/issues/5459, can be solved with this idea.

**Comment by permcody** [comment]
Save-in is going to be deprecated soon anyway after the vector tagging capability is rolled out.

**Comment by YaqiWang** [comment]
Similarly an initial residual evaluation might be needed so that the tagged vectors can be filled in correctly after initial setup.

It is funny that there is already a `NonlinearSystemBase::_computing_initial_residual` flag, which is used to do some thing in `NonlinearSystem::solve()`.  It may not be related.

**Comment by permcody** [comment]
Yes, the bootstrapping problem never goes away. In the general case, everything can depend on everything so it's a difficult problem in a framework. We do have longer term ideas on how to solve that bigger problem but they are long ways off. I'm open to fixing these up as best we can as we find these nasty edge and corner cases.

**Comment by YaqiWang** [comment]
I am working on another solution, will push it into that PR soon.
