### ISSUE TITLE
Command line argument syntax check is not complete

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10691]
## Rationale
I made a mistake on command line, while I intended to have 
```
Executioner/end_time=0.10 Executioner/num_param_updates=4
```
but accidentally deleted the space between two arguments like
```
Executioner/end_time=0.10Executioner/num_param_updates=4
```
However, the code runs fine.

## Description
When the code parses the command line arguments, it should check the validity of the argument. I think right now it takes `0.10Executioner/num_param_updates=4` as the value of the first argument and uses `0.10`. The second argument is thus completely ignored.

## Impact
Better user experience.

**Comment by permcody** [comment]
Hmm, Well I don't claim that we've removed all of the bad or incomplete conversion code throughout MOOSE, but at least we have a robust utility here to fix this:

https://github.com/idaholab/moose/blob/devel/framework/include/utils/MooseUtils.h#L372-L394

@rwcarlsen - Do you know exactly where this is occurring?

**Comment by rwcarlsen** [comment]
The problem is that what @YaqiWang mistakenly typed in is actually valid hit syntax with exactly the meaning suggested.  I can take a look to see if there are any obvious ways to improve it, but this probably won't make it to the top of my list for the near term.

**Comment by permcody** [comment]
Very easy to replicate:

```
cd test/tests/kernels/simple_transient_diffusion
../../../moose_test-opt -i simple_transient_diffusion.i Executioner/num_steps=5BCs/left/value=5
```

**Comment by dschwen** [comment]
Why isn't there a check for unprocessed leftover characters when doing a
conversion to a number?

**Comment by rwcarlsen** [comment]
@permcody The reinterpret casts are for a different reason.  @dschwen We do check for unprocessed leftover characters.  There is something else going on here.
