### ISSUE TITLE
Switching threading model default from TBB to OpenMP

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10724]
## Rationale
TBB is no longer needed and ads headache / complication that is unnecessary (especially when debugging).

## Description
TBB is essentially "random"... making it difficult to do things like timing - or reliably caching - or debugging, etc.  We should switch away from it to OpenMP/Pthreads which is more repeatable.

In addition, OpenMP/pthreads are supported everywhere... when TBB is tough on some systems (Bluegene and Cray for instance).

Finally, OpenMP is also utilized by underlying libraries like Hypre... which means that MOOSE can share the same thread pool (which I've shown a few times to be more efficient).

To ditch TBB all we need to do is set `--with-thread-model=pthread` in our configure script.  It will automatically pickup OpenMP if available - or fallback to pthreads if it's not (OpenMP really should be available everywhere though!).

There is one small change I am going to make to libMesh's OpenMP/pthread code before we do this though...

## Impact
It will change the default threading model that everyone is using.  It should make things easier to debug and add portability.

**Comment by permcody** [comment]
closed by https://github.com/idaholab/moose/pull/10754
