### ISSUE TITLE
heat_conduction/recover test failing sporadically on Intel

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10737]
## Rationale
For some reason heat_conduction/recover:recover_3 test is failing sporadically when using the Intel compiler.  It's not really clear why but we're going to skip that test for now as it's always been somewhat problematic (loose tolerances, right on the edge of determinism).  That said: this could be a real bug so we should look into it soon.

## Description
Skip the test

## Impact
We do tons of testing of recover for all the other tests in MOOSE so it's unlikely that removing this one test uncovers some critical piece of code.

**Comment by tophmatthews** [comment]
Should be closed by #12958  @friedmud

**Comment by permcody** [comment]
Intel compilers are no longer supported - closing this issue.
