### ISSUE TITLE
Deprecation Enhancements

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10745]
## Rationale
Deprecations currently cause failure that must be immediately fixed - this goes against the idea of deprecating things!

## Description
We should enhance deprecations in a few ways:

1.  Add back in the idea of a removal date
2.  They should be their own special kind of warning
3.  They should NOT ever be promoted to errors automatically
4.  We should allow them to be promoted to errors by `run_test` - but ONLY if you explicitly provide a command-line option

## Impact
Better workflow for changing API's and input file syntax.

**Comment by tophmatthews** [comment]
FYI, #6780 may go along with this.
