### ISSUE TITLE
SLIB Namespace Collisions Between MOOSE and Trilinos.

### ISSUE THREAD

**Issue by mbairdphys** [idaholab/moose#10761]
## Rationale
Fix build issue with SLIB namespace.

## Description
When building VERA, which contains MOOSE and Trilinos, namespace collisions occur with SLIB namespace in SEACAS.

## Impact
SLIB namespace needs to be unique so potential fix would be to rename namespace.  This would impact anything downstream that is using the SLIB namespace, but this seems to be limited.

**Comment by brianmoose** [comment]
closed via #10760
