### ISSUE TITLE
Need 'make install' for applications

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10786]
## Rationale
Sometimes we would like to give users access to the executable of the application but not the source code. It will be very handy to us if we can just do `make install` to copy all necessary libraries, executables, including headers, documentations, etc. into a separate folder which users can access.

## Description
I guess most of operations can be done by framework, but possibly we will need to provide some sorts of flexibility to app developers so that they can decided to add more in the distribution. This can also facilitate the automated update to the distribution on HPC.

## Impact
New capability.

**Comment by permcody** [comment]
What's your time frame for this? I know we need to do this eventually, but I hadn't planned on assigning a resource to this until it was absolutely necessary (e.g. a program is asking for it in the near future).

**Comment by YaqiWang** [comment]
We do not have a deadline for this. But our team members frequently need to recompile mammoth on hpc, which is quit painful. If we can have this, we can have a nightly target for mammoth to update the executable so that everybody can just load it. We could keep all old versions with version tags as well.

**Comment by permcody** [comment]
>We do not have a deadline for this. But our team members frequently need to recompile mammoth on hpc, which is quit painful.

It's time to start spreading the word. You and your team should start using unity builds. These can drastically reduce the compile times of our big applications (~10x improvement). To use just export  MOOSE_UNITY=true in your environment on your workstations and the cluster. Please let us know how it goes.

> If we can have this, we can have a nightly target for mammoth to update the executable so that everybody can just load it. We could keep all old versions with version tags as well.

So we specifically talked about `make install` not necessarily being for developers, but for users only. We were talking about not including headers or anything else, just the binary, which may not be exactly what you need. Try my first suggestion and lets see if that helps out. I expect it will. Feel free to pass this information on. We will probably roll it out to everyone by default soon.
