### ISSUE TITLE
SolutionUserObject does not work with distributed mesh

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10794]
## Rationale
We do not have to distribute the mesh used by the SolutionUserObject. Actually it may not even be a good idea. If desired, we could just issue a warning like what we did in exodus file output with distributed mesh.

## Description
While the simulation can still use the distributed mesh, we just construct the SolutionUserObject with the replicated mesh.

## Impact
Small tests using SolutionUserObject can be tested with distributed mesh.

**Comment by permcody** [comment]
What are you suggesting here. That we add two meshes to the problem? With DistributedMesh, we normally delete the unneeded elements and nodes before most objects are constructed. I'm not really seeing a good way to make this work. Also, what if you start from a pre-split mesh?

Yes, I agree that SolutionUserObject should be made to work with DistributedMesh. I don't think that we should try to make MOOSE keep a replicated mesh around just for SolutionUserObject.

**Comment by YaqiWang** [comment]
I guess I am really suggesting remove this line:
https://github.com/idaholab/moose/blob/devel/framework/src/userobject/SolutionUserObject.C#L418

We can just have distributed runs with a solution user object using replicated mesh.
