### ISSUE TITLE
Accidentally checked in checkpoint files?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#10796]
## Rationale
Looks like
https://github.com/idaholab/moose/tree/devel/test/tests/checkpoint/gold/checkpoint_interval_out_cp
should not be there?

## Description
I accidentally removed that folder and all tests are still passing.

## Impact
None.

**Comment by permcody** [comment]
Right, That test is checking for the creation of checkpoints, but it's not comparing them so they shouldn't be in the gold directory. Nice catch.
