### ISSUE TITLE
Chemical reactions: add more tests

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#10808]
## Rationale
More tests are required in the chemical_reactions module to make sure that the code is working properly and also to provide more examples for users to follow

## Description
Add more tests and possibly more detailed examples

## Impact
Better tests and more examples for users to follow

**Comment by cpgr** [comment]
I'll progressively add more tests and examples to the chemical reactions module, so wanted a general issue number that I can refer to in the next few weeks/months.

**Comment by permcody** [comment]
Closed by #10809
