### ISSUE TITLE
Compiling with GCC 7.2.0 on Mac Fails

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#10817]
## Rationale

It's nice to have support for multiple compilers on a platform. One good reason is to try to keep the code as clean as possible in terms of warning messages. Another is better standards compliance since compiler-specific tricks may not work across different compilers.

## Description

We typically use clang to compile on Mac, but it's still possible (theoretically) to use a hand-built GCC compiler. However, the 7.2.0 version fails to build with "isnan" conflicts in the exodiff contrib. We need to either patch, or update exodiff. It looks like our current version is 4 years old.

## Impact

Hopefully minor. Exodiff is used extensively by the testing system, but it not a core component of the framework. If there are problems with exodiff, we'll see them in the testing system (CIVET).

**Comment by brianmoose** [comment]
dup of #10813?

**Comment by permcody** [comment]
Yes, I'll close that ticket since this one will be closed upon merge.
