### ISSUE TITLE
Add off-diagonal jacobian entries for coupled weak plane stress 

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#10816]
## Rationale

Off-diagonal jacobian entries to couple the out-of-plane strain variable in the weak plane stress formulation with in-plane displacement variables and temperature variable are required in order to improve the convergence of the weak plane stress simulation.
## Description

Off-diagonal jacobian entries were implemented and the difference with respect to finite difference calculation is now less than 1e-8.
## Impact

This change will not affect any existing code or results of existing tests. The convergence for weak plane stress simulation should be improved.

**Comment by permcody** [comment]
I don't see an impact listed. You must be inviting an audit!

**Comment by bwspenc** [comment]
Reopening because the commit that did this deprecated the 'direction' parameter, which needs to be removed. I have a commit read that will close this.
