### ISSUE TITLE
Max Failures no longer works

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#10822]
## Rationale
The TestHarness is supposed to stop and alert the user that it hit a max failure count.

## Description
The TestHarness when encountering a max failure count, continues to schedule tests (which fail immediately). The TestHarness is also not alerting the user that it actually hit a max failure count.

## Impact
None

**Comment by milljm** [comment]
Change of plans. Seems the current mode of operation is indeed the correct one. But upon discussing it, there is room for improvement.

**Comment by permcody** [comment]
Max failures still works. The only issue is that with parallel scheduling. We do often run more than the max since we don't stop scheduling until we've hit the max but then we still have to clear out the tests that are being scheduled.
