### ISSUE TITLE
HIT: Formatter

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#10845]
## Rationale

A HIT formatter that can read a file and format it so that it has consistent spacing would be ideal for keeping input files and test specifications consistent throughout the project.

## Description

We need a tool that can format HIT files like clang-format formats source files. This formatter should support a max characters per line parameter much like clang-format does. This capability will be used in the "tests" specification to keep longer requirement statements from getting too unwieldy. 

## Impact

None - new capability

Tag @rwcarlsen

**Comment by dschwen** [comment]
This has existed for a while now
