### ISSUE TITLE
Quoted booleans should still be booleans

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10856]
## Rationale
Putting `something = 'false'` should be just the same as `something = false`

## Description
Right now the first one is treated as a string and makes an error if you try to retrieve it as a boolean

## Impact
Unnecessary errors

**Comment by permcody** [comment]
I'm not sure when this was fixed but I tried it in both MOOSE and the TestHarness and verified that it works (with quotes). If you continue to see issues, please reopen.
