### ISSUE TITLE
Hit doesn't compile in windows for RAVEN.

### ISSUE THREAD

**Issue by derekstucki** [idaholab/moose#10863]
## Rationale

RAVEN uses the test harness, which uses hit. Hit doesn't compile in Windows, which RAVEN must support.
## Description

Hit, as configured, fails to compile. Using setuptools/distutils for the compilation of the cython generated code can remedy this.
## Impact

This change should not affect anything other than compiling on windows.

**Comment by permcody** [comment]
Seems like more of a feature to me. Seriously though, this looks like it has been resolved for now.
