### ISSUE TITLE
Piecewise Function generalization

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#10860]
## Rationale
I have a custom class that creates a x/y piecewise linear function that does a lot of the same things as `Piecewise`. However, I have a custom way of setting the x/y data based on specific input (ramp rates, holding rates, holding values, etc). `Piecewise` only allows you to set the data from a data file, from x, from y, or from xy pairs. I need to do some internal calculations to spit out the x/y pairs, but none of the methods to set the data are virtual, meaning I have to do a brand new class that inherits from function...not really a big deal. However, I want to use it as a `timestep_limiting_function` in `IterationAdaptiveDT`. In order to do that, the function must be a `Piecewise` function.

## Description
I can see two ways to do this. The first is to make a `PiecewiseBase` class that sets a lot of the internal methods (`functionSize`, `range`, etc), but doesn't do any x/y data setting. Those can be retained in the `Piecewise` class. `IterationAdaptiveDT` can then require a `PiecewiseBase` class, and my new class can inherit from `PiecewiseBase` as well.

The second and easier way is to make a new virtual function `buildData` in `Piecewise` that is called during the constructor, and contains the current data creation in `Piecewise`:

```
  if (isParamValid("data_file"))
    xy = buildFromFile();

  else if (isParamValid("x") || isParamValid("y"))
    xy = buildFromXandY();

  else if (isParamValid("xy_data"))
    xy = buildFromXY();

  else
    mooseError("In Piecewise ",
               _name,
               ": Either 'data_file', 'x' and 'y', or 'xy_data' must be specified.");
```

My class, and others, can then override `buildData` as necessary. The disadvantage with this method is some of the `InputParameters` need to be suppressed (`x`, `y`, `data_file`, etc), making it not as clean.

I put up examples of either as a pr if there is a preferred direction.

## Impact
Extends applicability of `Piecewise` functions beyond the current x/y data setting.

**Comment by permcody** [comment]
> make a new virtual function buildData in Piecewise that is called during the constructor

Absolutely not! This is a recipe for disaster:
https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP50-CPP.+Do+not+invoke+virtual+functions+from+constructors+or+destructors

> The disadvantage with this method is some of the InputParameters need to be suppressed (x, y, data_file, etc)...

Sounds like a new base class is the better design of the two.

**Comment by tophmatthews** [comment]
Whew, that saved a bunch of time breaking things. I'll put together a PR with the base class.

**Comment by tophmatthews** [comment]
Nothing like suggesting "Noncompliant" code to get a fast response...noted for future reference :)
