### ISSUE TITLE
MaterialStdVectorStdVectorAux Kernel needed

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#10869]
## Rationale

In PorousFlow we have some Material Properties that are ```std::vector<std::vector<Real>>``` and I need to save components off to AuxKernels.  So I need the MaterialStdVectorStdVectorAux

## Description

Ability to extract components of ```std::vector<std::vector<Real>>```

## Impact

Necessary for me.  But i'll put this in framework.

How many Material (StdVector)^n Aux do we need?  MaterialStdVectorStdVectorRealGradientAux ?

**Comment by permcody** [comment]
What is your use case here? What are these properties?

**Comment by WilkAndy** [comment]
They truly do exist: in this case, a concentration of a certain chemical component (vector) of certain fluid phase (vector).  So i think this is/will-be needed somewhere in MOOSE.  But in the specific case i'm working on, i can get the information i want in another way, and i'm a bit lazy to write the MaterialStdVectorStdVectorAux, so, yea, either in PorousFlow or not-at-all-for-now.

**Comment by WilkAndy** [comment]
Closing due to lack of interest
