### ISSUE TITLE
Error when using AxisymmetricCenterLineAverageValue AND volumetric_locking_correction = true

### ISSUE THREAD

**Issue by novasr** [idaholab/moose#10866]
## Rationale
When using the AxisymmetricCenterLineAverageValue post processor AND volumetric_locking_correction = true in a coord_type = RZ thermomechanics simulation, I get the following error right after the solve converges for the first time step: 
*** ERROR ***
Rank Two Tensor is singular

## Description
See attached input file. If volumetric_locking_correction = true in the GlobalParams block AND the post processor AxisymmetricCenterLineAverageValue is enabled, you will get the error. If AxisymmetricCenterLineAverageValue is not used, or if volumetric_locking_correction = false, it will run.

## Impact
If this is the intended behavior, adjust the error message to be more specific about what's wrong. If it's not the intended behavior, fix it.

@bwspenc , @sapitts , @gardnerru , @gambka 

[ranktwotensor_singular_demo.txt](https://github.com/idaholab/moose/files/1746182/ranktwotensor_singular_demo.txt)

**Comment by gambka** [comment]
I believe this postprocessor should work with the volumetric_locking_correction.
