### ISSUE TITLE
Improve warehouse design to allow for arbitrary tags

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#10896]
## Rationale

The current warehouse design is limited in its ability to store groups of items, for example the AuxGroup tag and the execute flags cause two levels of warehouse nesting. If we want to add new groups this nesting will get even more out of control.

## Description

I propose that all "tags" in MOOSE (e.g., execute_on, aux_group, boundary, blocks, etc.) map to a unique integer. It will then be possible to extract objects on arbitrary sets by getting the sets for each flag and compiling a single list of objects that appear in all the lists. 

The get method would be converted to:

```
getObjects(ACTIVE, PRE_AUX, EXEC_INITIAL, 42);
```

I know there are some problems with this, but I think it is the step in the correct direction. Lets use this ticket to figure out if this is feasible.

## Impact

This is a major change but it should be mostly internal.

@idaholab/moose-team

**Comment by permcody** [comment]
Closed by #11994
