### ISSUE TITLE
Dynamic linking is not robust when using apps in MultiApp

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#10911]
## Rationale

Linking error like this shows up:
```
Unable to open library file 'libxyz-opt.la'
```

## Description

1. In a makefile, say:
    ```
    APPLICATION_NAME = xy-z
    ```
    This will build:
    ```
    xy-z-opt
    libs/libxy-z-opt
    ```
2. In your C++ code have:
    ```
    class XYZApp {}  // note there is no -, because it is not allow in C++
    ```

3. Have an input file with [MultiApps] block:
    ```
    app_type = XYZApp
    ```

4. The dynamic linking code will look for `libxyz-opt.la`, because the class name does not have `-`.

5. FAIL!

## Impact

Unable to run code under above conditions, because class names do not have to match application names.

**Comment by permcody** [comment]
Oh Relap-7, why you always using dashes?

**Comment by andrsd** [comment]
I blame the people who make decisions and do not write code. The general problem, however, is that the app name and the C++ class name can be inconsistent and then this happens.

There are 2 solutions I can think of:

1.  we would pass the library name in the multi app block, which would override the auto generation algorithm, i.e. we would have `library_path` and `library_name`

2. we would pass app name, i.e. we would have  `app_type = XYZApp` and `app_name = XY-Z`.

But I think 1. is better.

**Comment by permcody** [comment]
I'm fine with either solution but I thought we had already solved a similar problem on the Stork side. Perhaps we just need to copy that solution to the relevant C++ code in MOOSE that handles the library loading?

**Comment by andrsd** [comment]
I tried to create a new app with a `-` in the name and stork generated a class name with the dash in it, i.e. we get uncompilable code. I think what you are thinking was generate revision script where dashes were not turned into underscores.

So we will need to patch stork as well.  (1) We could turn dashed into underscores, which would solve the inconsistency issue for the newly created apps. Or (2), we can check the name passed into stork and if it contains special characters, we error out.

As for fixing the RELAP-7 related issue, I am gonna go with 1.
