### ISSUE TITLE
Clean up `SinglePhaseFluidProperties` interfaces

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#10921]
## Rationale
The interfaces in `SinglePhaseFluidProperties` are inconsistent and terrible.

List of terribleness:
* There are 2 sound speed functions: `c(v,e)` and `c_from_v_h(v,h)`. It'd be easy to mistake `c(v,e)` for the other function since they have the same signature.
* `pressure` and `temperature` functions are spelled out instead of using symbols like the other 50 functions.
* `dp_duv` provides both pressure *and* temperature derivatives. There is no other function to give temperature derivatives.
* `rho_e_dps` provides values and derivatives for both `rho` and `e`, unlike any other interface.

## Description
I propose that a property call `y(a,b)` have 2 interfaces:
* `Real y_from_a_b(a, b)` for computing the value alone
* `void y_from_a_b(a, b, & y, & dy_da, & dy_db)` for computing the value and its derivatives

## Impact
These changes should be able to avoid breaking dependent applications by using the following process:
1. MOOSE PR: Declare the new interfaces in `SinglePhaseFluidProperties` as virtuals with default implementations (can just contain `mooseError`). Give default implementations to old interfaces.
2. App PR: Update MOOSE, implement the new interfaces, and delete the old interfaces.
3. MOOSE PR: Delete the old interfaces.

**Comment by joshuahansel** [comment]
@andrsd This is my plan for the fluid properties.

**Comment by andrsd** [comment]
You cannot have 2 virtual methods with the same name, so you will need a different name for the derivative version. Other than that, good plan....

**Comment by joshuahansel** [comment]
I don't understand; we already have 2 virtual methods with the same name (`c_from_v_h`). Why wouldn't it be ok, as long as they have different signatures?

**Comment by andrsd** [comment]
I think we ran into a problem where we had 2 virtual methods with the same name earlier. Let, me check if I can reproduce the problem...

**Comment by joshuahansel** [comment]
It seems vaguely familiar, but it might be me remembering you saying this when I was putting in `c_from_v_h` 😛

**Comment by andrsd** [comment]
I tried a simplified version of what we want to do and it works just fine. Must be my memory  failure. SO go ahead...

**Comment by joshuahansel** [comment]
I just accidentally ran into the rule you were thinking of, so you're not crazy: *you cannot overload a virtual function with the same arguments prototype, even if the return type is different.*
