### ISSUE TITLE
Scientific Notation Should Be Fine For Integer Parameters

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10930]
## Rationale
Integers can be really big.  It's easier to specify them with scientific notation sometimes.  It used to work with the old parser - it should still work.

## Description
The HIT parser should accept scientific notation for integer parameters.  I'm now seeing this all over the place (I have a LOT of input files using this notation!)

```
 invalid integer syntax for parameter: UserObjects/ecr/num_rays=1e5
```

I'm setting this as "Normal" priority... but it's a pretty serious issue.  I have dozens of input files that use this notation for multiple parameters....

## Impact
Better parsing

**Comment by permcody** [comment]
I see your point, but I don't think this is quite as critical as you think. We've had it in there for awhile and it hasn't broken anybody else yet ;) Having said that, I think it's reasonable to see if the floating point specification is a valid integer and allow it.

**Comment by friedmud** [comment]
This can’t be hard to fix - and seriously screws me up.  I have _multiple_
parameters in dozens of input files I’ll have to go in and manually change…
plus it makes those input files less readable (hard to tell how many zeroes
there are in 200000… especially when there are multiple parameters like
that).

Also: my scripts that generate input files and run parameter sweeps are
setup to do this too.

It’s pretty damn annoying and has to be an easy fix.

**Comment by YaqiWang** [comment]
We could have a rating system on the hardness of issues maybe from 1 to 5. The easier issues can be scheduled faster. Or if you rate people's performance based on number of issues closed, this will be automatically taken care of, lol.

**Comment by permcody** [comment]
No, it's easy to fix.

Tag @rwcarlsen

**Comment by friedmud** [comment]
@rwcarlsen Any movement on this?  Let me know if you don't have time to look at it and I'll do it myself (I'm currently pretty held up by this).  If you can point me to what to do I can do it.
