### ISSUE TITLE
Optimize Makefiles

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#10981]
## Rationale
It's taking ~9 seconds `make junk` in `moose/modules`.  That lag time is annoying every time you compile.

## Description
Try to figure out what is causing the slowdown and fix it!

## Impact
Lower latency on build times

**Comment by permcody** [comment]
Current time is down to 4 seconds, which isn't perfect but it's going to be pretty challenging to do much better than that. I'm closing this.
