### ISSUE TITLE
Bool parameter set in GlobalParams causes error in Peacock

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#10987]
## Rationale
Setting a boolean parameter in GlobalParams results in an error in Peacock

## Description
See for example `test/tests/time_integrators/explicit-euler/ee-1d-quadratic-neumann.i`,
which has
```
[GlobalParams]
  implicit = false
[]
```

 Running this in peacock causes this error:
```
*** ERROR ***
field node 'GlobalParams/implicit' does not hold a bool-typed value (val=''false'')
```

## Impact
Can't run some simulations with peacock

**Comment by brianmoose** [comment]
Peacock doesn't know the type of the parameter in the GlobalParams block so when it writes out the temporary input file it writes the value as a string: `implicit = 'false'`
@rwcarlsen I vaguely remember this coming up before and that this could be fixed on the hit/moose parser side?

**Comment by rwcarlsen** [comment]
This is subtley different than (but related to) that issue.  The issue before was that hit treated quoted booleans as strings instead of booleans.  This is the opposite where Peacock is "forgetting" that (unquoted) boolean is *not* a string after it reads an input file where hit provides the information identifying it as a boolean.  However, just to make @friedmud happy - we may allow quoted booleans via a minor mod to Parser.C :-)  - which would resolve this issue.

**Comment by friedmud** [comment]
Globalparams is a free for all - there’s no way for Peacock to know the type.

The parser should always allow reading single values from within quotes: no matter the type.

**Comment by rwcarlsen** [comment]
That is true about GlobalParams, but hit uses syntax to note that a certain
variable is a boolean - and then Peacock is forgetting that information.
I'm not disagreeing about solutions - just saying that hit already provides
Peacock enough information to avoid the particular problem cited in this
issue.

**Comment by friedmud** [comment]
How does HIT know that a GlobalParams parameter is boolean?  There is no
syntax for it.

**Comment by rwcarlsen** [comment]
If it is unquoted and "looks" like a boolean.  Regardless, we can just modify Parser.C to allow string "bools" to work too.  It is a simple change.

**Comment by friedmud** [comment]
👍 

Is there a simple way to enable _every_ type to work with quotes like this?  It's not just bools... it happens to ints, etc. in GlobalParams too

**Comment by rwcarlsen** [comment]
With hit there are only bool, numbers (float+int), and string types.  We
already to this for numbers, strings are already strings - so doing this
for bools will basically accomplish that.

**Comment by friedmud** [comment]
Please fix this - ASAP.  This just got hit by a trainee.  It's embarrassing.

Quoted single values should _always_ work - regardless of type.
