### ISSUE TITLE
Exodus Viewer Borks If you view a component of a vector that doesn't exist

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11015]
## Rationale
It would helpful if Peacock would allow you to continue to view results after selecting a component of a vector that doesn't exist in the Exodus viewer.

## Description
Run a 2D problem (such as tutorial step 06) and try to view the `z` component of velocity.  It will not be viewable - and nothing will ever again.

## Impact
We can't view solutions

**Comment by aeslaughter** [comment]
closed by #11627
