### ISSUE TITLE
Implement MathUtils::pow in fluid properties where appropriate

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#11048]
## Rationale
There are a lot of places in the `fluid_properties` module where values are raised to integer powers, which I have been informed can be calculated a lot faster using `MathUtils::pow` rather than `std::pow`.

## Description
Replace `std::pow` with `MathUtils::pow` when raising values to integer powers in the `fluid_properties` module.

## Impact
Internal optimisation only

**Comment by mangerij** [comment]
Isn't it Utility::pow<int>(arg) and not MathUtils? Is there duplicate
somewhere ?

FYI I was getting almost 100% speed up by dumping std::pow, but my kernels
had quite a bit of these powers.

**Comment by permcody** [comment]
Yes John, There are two. I'm not entirely sure if we've pitted them against one and other. One of these is a template method that just expands into a series of multiplications. The other does some clever multiplication and bit shifting. They are both superior to calling a library method.

**Comment by WilkAndy** [comment]
Wow, 100% speedup is super impressive.  Would it be worth this into one of the "prechecks" for each PR?  I'm sure to frequently forget and use std::pow just because my fingers type it automatically.

**Comment by mangerij** [comment]
I think my speedup was because I had 50+ instances of these in each of my
residual, on-diag, off-diag jacobian entries in something like 6 different
kernels and I was using the full Newton method.  It's probable problem
specific

**Comment by permcody** [comment]
Can't easily add a pre-check. These methods only work with integer powers. Also, if you are only using the library method once per time step or maybe in the setup, it's fine. Several of us are starting to watch for these now though in PR reviews (that's how I just made Chris aware of these), so we do catch them.

**Comment by dschwen** [comment]
The one in MathUtils allows you to specify the exponent at runtime. The
libmesh Utility pow template needs the exponent at runtime but is even
faster.

**Comment by permcody** [comment]
I don't think you meant runtime twice there. The libmesh version is compile
time, correct?

**Comment by dschwen** [comment]
Yes! Edited.

**Comment by cpgr** [comment]
OK, I've found one problem with doing this. Some of the powers are negative integers, and `MathUtils::pow` doesn't like them, returning `inf`.

Otherwise, using `MathUtils::pow()` seems to be at least three times faster than `std::pow` to evaluate the kinds of powers that are in the fluid property formulations.
