### ISSUE TITLE
Split MooseApp::getCheckpointFiles()

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11069]
## Rationale
We want to split `std::list<std::string> MooseApp::getCheckpointFiles()` into two parts, one obtain the checkpoint directories and another for finding all files under the directories. The reason we want to have this split is that we want to use a function like `std::list<std::string> MooseApp::getCheckpointDirectories()` to store an auxiliary file used for recovery. 

## Description

We really do not want to do this but have to. We have some restartable data required for building a material, but the data will not be available during material construction. The data is quite simple so we can just output it into a separate file under recovery folders during construction and can be loaded later in recovery mode. If you are curious, the data is material IDs, related with mesh.
Any comments or better suggestions?

## Impact
New interface function.

**Comment by YaqiWang** [comment]
If the restartable data was loaded during construction, we would not need this. But I guess that is impossible currently.

**Comment by permcody** [comment]
I'm not crazy about this. So you have material that requires parameters during construction. Is there no way to create memory, buffers, etc. that can be filled in just a little later? I know you've mentioned this problem to me before, but I'd really like to try to find a better solution to this whole problem.

**Comment by YaqiWang** [comment]
The construction of that material is pretty heavy and I even cannot think the consequences of delaying the construction. We need the material IDs on the blocks where the material is defined, which cannot be obtained right now at the construction time with recovery. Or if the recovery system is flexible allowing individual object load its own restartable data, (I guess mesh already did this, right?), this is not a problem as well. We have to create a special recover file for a particular user object, which may be a reasonable extension of the current design. If the user data is available in mesh, our current design and implementation can be replaced easily. So I will push in a PR for this. Thanks.

**Comment by friedmud** [comment]
I still think the ultimate answer to all of this is for libMesh to just add
another `sub_block` member variable to `Elem`.  It should be something
fully supported by libMesh / MOOSE.  There are WAY too many applications
that exist where it would be useful to have finer grained
materials/kernels, etc.

**Comment by permcody** [comment]
Yeah, or even more general, [this](https://github.com/libMesh/libmesh/issues/1439). I'm not sure how long it'll be before we get back to this though.
