### ISSUE TITLE
No releases: How to support Moose in HPC environments?

### ISSUE THREAD

**Issue by cmeesters** [idaholab/moose#11063]
Dear Moose-Developers,

## Rationale

In order to support stable, reliable software stacks for our users (this applies to other HPC sites, too - as we suppose), we need softwares (applications/libraries) which reliably build for a given release, where the joined team of developers can agree upon (does build, pass tests).

Moose does not show any (recent) releases. Nor does it display another reliable branch / fork scheme for this purpose.

## Description

What we encountered so fare: we need to checkout the master branch, which may receive commits at any time (which may or may not break dependencies or fix issues). Therefore a reliable build with a definite feature stack is not possible to build.

## Impact

We would like to support the project by commiting an easybuild config file to the easybuild community. easybuild is a widely adopted framework to deliver software stacks to HPC end users. This, however, would require some sort of reliable release cycle.

We would appreciate any suggestion to solve this issue.

Best regards,
Christian Meesters

**Comment by mangerij** [comment]
Couldn't this easybuild config file be continuously integrated?

See civet.inl.gov for the continuous tests that performed on all of the framework, modules, submodules, apps, subapps, etc in the MOOSE herd. 

Also, the required submodule libMesh is on a semi-annual release schedule, and that is usually where I experience hiccups installing on HPC environments so maybe it would be good to start there. I'm not an expert and I'm sure one of the developers will come along and propose a solution.

**Comment by cmeesters** [comment]
Thanks, John, for pointing to this weakness of my argument:

This is what we want to avoid: The point in gathering commits (fixes + additional features) for a particular release, guarantees that everybody knows what to talk about. And it is hardly feasible to re-build a module every time some new commit hits the users eye.

A libMesh version could also be associated with a particular Moose version (or several) in order to avoid such "hiccups". Installing one module for libMesh (per version / and other dependencies) and defining it to be a dependency, is the way to minimize overhead in the long run.

However, semantic versioning is not a particularly great project overhead and in use for many projects.

**Comment by permcody** [comment]
Hi Christian, We do have plans to support releases of MOOSE in the future. These releases will be rigorous requiring a developer to sign off on the contents of that release so we have an understanding of any known limitations or issues (should there be any). However, our dual branch system actually is a lot more stable than you might realize. Even though MOOSE receives several commits every day, those changes undergo peer review and three rounds of testing before they are merged into our "master" branch. Those three levels are PR level, development level against stable versions of applications and finally in the "master" branch against developmental versions of applications. What this means is that **every** version of MOOSE is stable meaning that it passes all tests and passes *most* tests in downstream applications. So the idea is that you shouldn't have to worry about picking a release, any release should be thoroughly automatically tested.

An actual traditional release wouldn't give us a lot more stability. Presumably, it would just add a human into the mix, but would still pass the same tests we already pass for every merge to "master". 

Again, we will support actual releases in the future but with releases come additional support, which we really aren't staffed to support today. We plan to do this, once we have a customer that can help pay those additional costs.

In the meantime, I suggest that you simply pick a reasonably current release of master as a stable version. If you use civet.inl.gov, you can verify for yourself that the master commit you pick has passed all of the tests that we threw at it, plus any downstream application tests. libMesh is tightly bound to every single version of MOOSE through the use of submodules so for any particular version of MOOSE you can be assured that there is a single unique version of libMesh you should use.

**Comment by permcody** [comment]
I should also say that you make it clear to your users when you will update. Since we don't have release numbers, maybe use a calendar date. How about you update monthly on the 1st of the month and call your versions of moose by month?

**Comment by cmeesters** [comment]
Thank you.

https://civet.inl.gov/branch/4/ demonstrates that some tests may break, even though a commit made it to the master branch. Without an apparent change log, there is no way to tell users what changed (other than going trough all commit in a time frame). Alas, we need to support more than one software.

Let us clarify:

- we are not sure that the master branch actually builds (compiling on our - admittingly "old" AMD bulldozer nodes (64 cores, Centos 7.3, gcc 6.3) took 6 h and crashed upon linking). A colleague of mine will comment on this, but the point for this issue is the always nagging question: Is this due to a particular commit stage or due to a glitch upon building on our side?
- with the proposed steps we would do the release management for Moose on our site: users have no chance to know which scientific stage the software has

The conclusion would be: we do not support the software as such, but hope for one commit to actually build and build it in a given group directory.

Sorry, as a mail this sounds a lot harsher than I intend it to be.

**Comment by WilkAndy** [comment]
My main problem with the continuous integration is that users are running along happily and suddenly their input file doesn't work because of a changed parameter name, etc.  So i just create my own releases: moose_2018_1; moose_2018_2; etc, which people use in their job scripts.  MOOSE always prints out version info at the start of the run, so people can always track down exactly what moose_2018_1 actually means if they ever want to.

**Comment by permcody** [comment]
@cmeesters - It's true that some master targets might and do fail. We consider those non-essential. Everything that *must* pass occurs on the devel branch prior to merging into the master branch. As we develop, sometimes we add new targets to master to see what they will do (i.e. how many new failures will we see with some new testing configuration). That's another reason you'll see failures there. Also, there's the rare, but not impossible, non-deterministic test that gets added.

In lieu of us doing releases in the short-term, let us know how we might better assist you staying up to date. At some point in the future when we have an operational budget, we might be able to reasonably support releases of the product.

**Comment by permcody** [comment]
All testing has been moved to next and devel branches. The only targets left on master are the update recipes. Additionally we have just released a new "Software Quality Assurance" plan specifying exactly how the release process works, which incidentally is separate from the master branch.
