### ISSUE TITLE
"thermal_expansion_coeff" in `ComputeThermalExpansionEigenstrain` has to be either required or has to have default value

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#11074]
## Rationale

If people do not provide "thermal_expansion_coeff" parameter in `ComputeThermalExpansionEigenstrain` they get an uninitialized value.

## Description

Reproduce:

1. Use `ComputeThermalExpansionEigenstrain` in your input file
2. do not set "thermal_expansion_coeff" parameter

## Impact

Input files using `ComputeThermalExpansionEigenstrain` and not providing the parameter needs to be fixed.

**Comment by andrsd** [comment]
@dschwen, @bwspenc, @sapitts I can easily fix this either way, what would you guys prefer?

**Comment by bwspenc** [comment]
I agree with @sapitts. It should definitely be a required parameter -- defaults don't make sense here.
