### ISSUE TITLE
Tutorial Step09 Broken?

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#11070]
## Rationale

We need the tutorials to work during training.

## Description

Displacement fields in the mechanics example are always zero. One issue we already know about is that the temperature isn't coupled into tensor_mechanics by default, but even after coupling temperature in, there is still no displacement values. What's going on?

While we're at it, I think the restriction of having the axis of rotation being "Y" for RZCoordinates has been relaxed. If that is indeed the case, this example should be updated so that it is consistent with the first 8 steps of the tutorial (step 10 will also need to be updated).

## Impact

Embarrassment in training - it's already occurred so the damage is done :)

**Comment by permcody** [comment]
Also, perhaps this has been broken for awhile. We don't Exodiff these tutorial steps. We only check that they "run".

Tag @dschwen or @aeslaughter or @andrsd.

**Comment by andrsd** [comment]
> While we're at it, I think the restriction of having the axis of rotation being "Y" for RZCoordinates has been relaxed. If that is indeed the case, this example should be updated so that it is consistent with the first 8 steps of the tutorial (step 10 will also need to be updated).

I thought the point of using a different axis in step 9 and 10 was to show how users would go about it and that it is possible. But may be I remember something incorrectly?  I can understand that it can be confusing to change this in last 2 steps of the tutorial...

**Comment by amjokisaari** [comment]
Happy to help on this, but where exactly are you talking about?  Mike Tonks and I took a different approach for teaching TM at TMS 2018...

**Comment by andrsd** [comment]
See #11075 for more details why step 9 and 10 are aligned with y-axis

**Comment by amjokisaari** [comment]
Looks like you guys are on it, but I think we (I?) need a broader discussion offline about the training materials.  Things seem kind of scattered and not up-to-date but it could just be that I'm out of the loop.

**Comment by permcody** [comment]
The materials didn't seem out-of-date to me, but they are a little scatter. The design of the course is to interleave discussions about math and framework features between the steps of the turorial. We pull live changes of code and we try to keep them fixed up. I did fix several minor things and have a list of more changes that need to be made when I get back to Idaho. However, I'm more than happy to discuss changes, new directions with the training material.

**Comment by tonkmr** [comment]
Which tutorial are you talking about here? @permcody are you talking about the Darcy Flow tutorial used for the general MOOSE training?

**Comment by amjokisaari** [comment]
I changed some slides up for TensorMechanics so that 1) it would incorporate the new Master action more easily and 2) be of the appropriate length for our 1-day MOOSE/phase field training.  I wonder if we should maintain two sets of training material, one for the longer trainings and one for the phase field short course.  Definitely would like to discuss more when @permcody is back.

**Comment by tonkmr** [comment]
@amjokisaari, I believe that Cody is talking about the general MOOSE training material that they now do around an example problem on Darcy Flow: http://www.mooseframework.org/wiki/MooseTutorials/DarcyThermoMechanical/

How we want to manage slides for the mesoscale trainings is a separate issue, I think, but also one that we need to deal with.

**Comment by amjokisaari** [comment]
@tonkmr, ah I see now, that was my confusion.  I have much to learn, I retract previous comments re: TM! 

Agreed we need to address the mesoscale trainings additionally.
