### ISSUE TITLE
Specify name of csv file generated by a vector post processor when execute_on = final in Outputs block

### ISSUE THREAD

**Issue by novasr** [idaholab/moose#11087]
## Rationale

@aeslaughter, per our discussion:

Currently, the file coming from a vector postprocessor (like LineValueSampler) has the time step number appended to it's name, e.g. line_plot_0100.csv, where 100 is the time step number. Please make available the option for the user to specify the name of the last file written when the execute_on = final parameter is used in the Outputs block.

## Description

When a time stepper, such as IterationAdaptiveDT is used, there is a possibility for the number of time steps to be different from run to run, or when running the simulation on different machines. This changes the file name of the last file written (relative to a gold file name) and makes it difficult to use csvdiff when checking the results of a simulation in an automated testing system, for example, diffing line_plot_0101.csv with gold/line_plot_0100.csv.

## Impact

The user's ability to name the last .csv file created will allow a testing system to always compare the last file written in a simulation to a gold file. Like, line_plot_final.csv to gold/line_plot_final.csv. This will help applications maintain robust testing systems.

**Comment by aeslaughter** [comment]
I think I will optionally create a symlink on final to the last written file, the following would create:

```bash
foo_0100.csv 
foo_FINAL.csv # symlink to above
```
```text
[csv]
  type = CSV 
  create_link_on_final = True 
[] 
```

**Comment by tophmatthews** [comment]
I'm interested in this as well. If moving the output, say to a LaTeX location, would you have to then copy both final the the last time step? Would it make more sense to have unique new output at final tied to `execute_on` parameters? That way if you only want to calculate something once in a Postprocessor or elsewhere, you can have` execute_on=final` for that object, and the csv?

**Comment by permcody** [comment]
Seems like a nice capability but perhaps when using this option, we should update the link every time the file is written and not just create it when the last step is written. That would make it so that if your simulation quits or is terminated early, you'd still have this link for the last file created.

If that was your intention, it's not clear from the name you proposed "create_link_on_final". Since we use `LATEST` in several other places in MOOSE, that might be a more appropriate name. How about "create_latest_link"?

**Comment by friedmud** [comment]
I think the `final` (lowercase) symlink should only get written in the case where you make it to the end of the solve.  It really denotes the _final_ value of something... not just the _last_ value.

Now I have a question.  If you have a VectorPostprocessor executing on `timestep_end` and on `final` do you get two files out in the end... or just one?  Are there two evaluations done but one overwrites the other?  How does that work?
