### ISSUE TITLE
Adjust tests for PETSc-3.8.3

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#11118]
## Rationale
We are going to use a new PETSc release (PETSc-3.8.3). Some tests are targeted  at the number of residual evaluations, and they may not have a little different number in the new release. We will regold  this kind of tests.  

## Description
Regold reasonable tests and fixed the failing  tests. 

## Impact
Everywhere.

**Comment by permcody** [comment]
These kinds of tests are generally a bad idea. Before regolding, lets see if we need these tests or figure out different ways of achieving the purpose (goals) of these tests. Otherwise, we'll just have to do this again the next time we update PETSc and so on.

**Comment by fdkong** [comment]
@permcody, I agree. It is better to redesign this kind of tests.
