### ISSUE TITLE
Add LaForce THM benchmark to PorousFlow

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#11110]
## Rationale

We have benchmarked PorousFlow vs a complicated analytical solution to a nontrivial dynamic THM problem derived by LaForce et al.  Add the test and doco to PorousFlow

## Description

This is a "tour de la force", heheheh, of PorousFlow's THM capability.  PorousFlow agrees extremely well with the analytical solution and it'll be very instructive for users to see the agreement and how the input file is constructed.  We are still awaiting the "OK" from our funders before we can add to the repo, however.  @cpgr, do you want to prompt JEK about this?

## Impact

Perfect example of PorousFlow for the repo - not a complicated mesh, but super complicated physics and analytical solution.

**Comment by cpgr** [comment]
I don't see that there is a problem with adding it, as it is quite generic (no site-specific geology). I'm woking from home today, but will check with Jonathan tomorrow.
