### ISSUE TITLE
Single screen update when variable switching in ExodusViewer

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11164]
## Rationale
Peacock performs two screen updates when switching from a variable and no applied mesh displacements to a variable with applied mesh displacements. This is irritating when trying to compare fields.

## Description

It is nice that peacock remembers the state of the _Displacements_ checkbox per variable, but it is very irritating that upon switching to a different variable (for display purposes) two distinct visual updates occur

1. On the current mesh the new variable field is displayed
2. The mesh changes its displacement state.

## Impact

Better UX

**Comment by dschwen** [comment]
![out](https://user-images.githubusercontent.com/202302/38118303-121c6fb4-3377-11e8-9a8b-775f136fcaa3.gif)

**Comment by friedmud** [comment]
Not only annoying - but also problematic because it can be very slow if
you’re running a large problem!

**Comment by aeslaughter** [comment]
closed by #11627
