### ISSUE TITLE
Parser doesn't support parameters of type size_t

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#11167]
## Rationale

Some users define indexing loops with integer type input parameters

## Description

These user indexing loops that use the input parameter as the max index are often used in the same routine as loops with `container.size()`. It would be nice for consistency's sake to have the indexes all be of the same type.

## Impact

Prevent parsing errors like:
```
*** ERROR ***
unsupported type 'unsigned long' for input parameter 'GlobalParams/l_direction'
```

**Comment by permcody** [comment]
I know I've looked at this before and it wasn't a quick fix. That was back with the GetPot parser. It might be something that can be addressed though now that we are using HIT.
Tag @rwcarlsen
