### ISSUE TITLE
./run_test -a writes to terminal

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#11175]
## Rationale

`-a` option does not behave as it used to. It now prints errors into the terminal.

## Description

To replicate, run:
```
$ cd moose
$ git checkout ed661394449ea9b11c370132ed85b272c5730527
$ cd test
$ rm tests/kernels/2d_diffusion/gold/out.e
$ ./run_tests -a --re=2d_diffusion
```

This will print the error message into the terminal and into a file.  The old behavior printed only into a file, so the terminal would not be cluttered.

## Impact

Happy users, particularly me 😄

**Comment by brianmoose** [comment]
Probably caused by #11123 
@milljm
