### ISSUE TITLE
Build failure caused by libmesh request for libpmi.la

### ISSUE THREAD

**Issue by fshriver** [idaholab/moose#11184]
## Description

While trying to follow the instructions posted here:

http://mooseframework.org/wiki/ClusterInstructions/

for a single-user installation, I get stuck on step 3, compiling libmesh. There doesn't appear to be any issues up until it tries to use a random library, libpmi.la, whereupon it spits out:

`make[2]: Entering directory `/home/joel397/projects/moose/libmesh/build/contrib/gzstream'
  
CXX      libopt_la-gzstream.lo 
 
CXXLD    libopt.la

/bin/grep: /opt/slurm/lib64/libpmi.la: No such file or directory

/bin/sed: can't read /opt/slurm/lib64/libpmi.la: No such file or directory
libtool:   error: '/opt/slurm/lib64/libpmi.la' is not a valid libtool archive
make[2]: *** [libopt.la] Error 1
make[2]: Leaving directory `/home/joel397/projects/moose/libmesh/build/contrib/gzstream'
make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory `/home/joel397/projects/moose/libmesh/build/contrib'

make: *** [all-recursive] Error 1
`

I can't find what this file is used for other than being formerly present in Slurm, but then removed; we likely won't need to actually utilize a submission system, so is there an easy fix to this? I need to patch this post-haste.

**Comment by permcody** [comment]
I recommend you post this issue on the mailing list. It's unlikely to be a bug or issue in our build system. It's much more likely to be an environment issue on the system you are working on and many more developers and users monitor the mailing list than do the activity in the ticket system. Perhaps "configure" detected a stall library path or something along those lines. 

I'm closing this ticket until we can prove that there's an actual repeatable issue here.
