### ISSUE TITLE
cli_args parameter in testroot files not handled properly

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#11204]
## Rationale

When there is a `cli_args` parameter in the `testroot` file, these parameters are passed along to the moose executable with each character separated as its own command line argument.

## Description

@milljm noticed this on the modules tests since `modules/testroot` has
`cli_args = '--color-first-directory'`

To see the problem, in modules:
`./run_tests -v --re  solid_mechanics/test:kernels/simple_diffusion.test`

The app command line is:
`Running command: moose/modules/combined/combined-devel -i simple_diffusion.i   - - c o l o r - f i r s t - d i r e c t o r y   --error --error-unused --error-override --no-gdb-backtrace`

@rwcarlsen Are the `cli_args` parameters in the `testroot` file only supposed to be for the TestHarness command line args?

I don't think this is currently breaking anything but I suppose it could with the right combination of arguments.

## Impact

More robust testing

**Comment by rwcarlsen** [comment]
``cli_args`` is suppose to work for passing params to the moose executable.

**Comment by rwcarlsen** [comment]
... well - actually maybe it was just meant for the test harness.  I can't remember :-/

**Comment by brianmoose** [comment]
The parameters in the `testroot` file are used as default values for the testers.
Since `cli_args` is a valid parameter for the testers, it is being passed along (although not correctly).
However, the `cli_args` are currently setting TestHarness arguments.
Maybe we should have a different `run_test_args` instead of using `cli_args`?

**Comment by rwcarlsen** [comment]
It would definitely be good to clearly distinguish between test harness and moose app flags.
