### ISSUE TITLE
Hypre Documentation

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11221]
## Rationale

Hypre is our most-used preconditioner... and something we talk about a lot.  However, getting the most out of Hypre means digging down into the options and customizing it to the needs of your solve.

We need some documentation showing all of the options and discussing their use on a few different problems

## Description

Add a Hypre documentation page

## Impact

None: New Documentation

**Comment by friedmud** [comment]
No particular link - it's just part of Hypre.

**Comment by aeslaughter** [comment]
completed by #11221
