### ISSUE TITLE
Add option to CSVDiff to override global tolerances with variable specific values

### ISSUE THREAD

**Issue by acasagran** [idaholab/moose#11250]
## Rationale

This change will allow one to customize the relative and absolute tolerances for the CSVDiff tester in a similar way that the Exodiff tester currently works. This will help to make the regression and assessment tests more robust.

## Description

Add options named override_columns, override_rel_err and override_abs_zero to the CSVDiff tester parameters which will change the default tolerances to specific values for individual variables in the CSV output file.

## Impact

Added functionality. No change to current tests.

**Comment by permcody** [comment]
I'm closing this ticket since it was completed. I'm going to open a new one to create a whole new utility.
Closed by #11251.
