### ISSUE TITLE
Seg fault in RZ when volumetric_locking_correction and use_finite_deform_jacobian are true

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#11261]
## Rationale

In tensor mechanics, when running with `coord_type=RZ`, `volumetric_locking_correction=true` and `use_finite_deform_jacobian=true`, a seg fault occurs. Both these options are more advanced, but are becoming important in high strain models.

## Description

`coord_type=RZ`, `volumetric_locking_correction=true` and `use_finite_deform_jacobian=true` result in a seg fault. The error occurs in `StressDivergenceRZTensors::calculateJacobian` line 203 when `_avg_grad_phi[_j][jvar]` is accessed. This seems to be due to skipping a resizing of `_avg_grad_phi` when `volumetric_locking_correction` is used, but doesn't occur here.

## Impact

This will allow `volumetric_locking_correction` and `use_finite_deform_jacobian` to run simultaneously.

**Comment by dschwen** [comment]
I have a fix for this.
