### ISSUE TITLE
Fix mortar periodicity documentation in phase field

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11280]
## Rationale
Some parts of the mortar periodicity docs were not migrated properly.

## Description
Move and merge some documentation files. This also makes the legacy `docs` directory go away/

## Impact
Clean up. Make existing docs show up on the website.

**Comment by mangerij** [comment]
Obligatory semi-annual "does Mortar work for MPI?"

:)

**Comment by dschwen** [comment]
This is the wrong thread to ask this. @jwpeterson might know. But we have somebody working on the strain periodicity without mortar (or interface kernels). That should work just fine with MPI once it is done.

**Comment by dschwen** [comment]
Merged in #11288
