### ISSUE TITLE
PorousFlow: allow salt to be a nonlinear variable in brine-CO2 class

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#11302]
## Rationale

Currently, the salt mass fraction in the brine is treated as a constant in `PorousFlowBrineCO2`. In reality, the salt mass fraction can change as CO2 is injected/transported. This should be generalised so that the salt mass fraction can be included as a nonlinear variable and allowed to advect, diffuse etc. See prior discussion in #10167 with @WilkAndy when he was in Zurich.

## Description

This will involve some changes to `PorousFlowBrineCO2` and related objects to enable this. Most of the work will be in making sure that the correct derivatives are included when salt mass fraction is added as a variable. I've done most of this, and it seems to be working ok.

## Impact

Additional capability for more realistic simulations of CO2 and brine in geological models.

**Comment by WilkAndy** [comment]
Cool, thanks for this, @cpgr
