### ISSUE TITLE
Remove duplicity between RealTensorValue and RankTwoTensor

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11388]
## Rationale
Eliminate use of `RealTensorValue` material properties in favor of `RankTwoTensor` properties to improve compatibility between materials and kernels.

## Description
MatAnisoDiffusion requires a `RealTensorValue` mobility. Various stress and strain classes operate with `RankTwoTensor`. A material that provides rotated 3x3 matrices in a polycrystaline system needs to exist in two variants. One that provides `RealTensorValue`s if anisotropic crystal orientation dependent mobilities are used, and `RankTwoTensor`s if eigenstrains are used.

The duplicate classes `RealTensorValue` and `RankTwoTensor` are redundant and confusing.

## Impact
This could break stuff that inherits from changed classes.

**Comment by dschwen** [comment]
This is tricky (because RTT * RTV = RTT but Real *RTV = RTV, and we use RTV for coupled second derivatives). RTT and RTV have different interfaces (`tr()` vs. `trace()`, which make templating a pain).

I think the way to go here is have RankTwoTensor derive from RealTensorValue. This would make assignments between the two easy as well.

**Comment by WilkAndy** [comment]
Thanks for doing this, @dschwen .  One of those largely thankless tasks that make things simpler for everyone.

**Comment by permcody** [comment]
Closed by #11403
