### ISSUE TITLE
Warehouse sorting algorithm is slow on Falcon

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11396]
## Rationale

I am experiencing a very very slow initial setup with one of my example problems on Falcon.
After adding bunch of print-outs, I finally located the line causing the problem: https://github.com/idaholab/moose/blob/devel/framework/src/problems/FEProblemBase.C#L554
which calls https://github.com/idaholab/moose/blob/devel/framework/include/interfaces/DependencyResolverInterface.h#L90.
The number of materials I have is only 352.

## Description

I can try reducing the number of materials, but looks to me that something is not properly implemented (352 is not big at all).

## Impact
Make users happy and simulations faster.

**Comment by rwcarlsen** [comment]
If you provide an input file, I can investigate.  You can send it to my inl email or create a rattlesnake issue.

**Comment by permcody** [comment]
If this is a dependency resolver complexity issue, a unit test will be way easier to troubleshoot this with.

**Comment by YaqiWang** [comment]
I pushed the input into a branch `simple_atr_example` of my rattlesnake repo. The input is `rattlesnake/examples/ATR/atr_diff_nda.i`. It runs with a multiapp, where the issue shows. The size of the problem can fit on my desktop.

**Comment by permcody** [comment]
This functor (which is used by the sort algorithm) is now doing two vector::find() calls. It used to do a set::find() call. Neither one is great as this is the comparator function for the sort which means we are already inside of a O(n log n), so O(n^2 log n).

**Comment by YaqiWang** [comment]
I should have mentioned that the issue seems more severe on Falcon. On my Mac, it appears ok.

**Comment by permcody** [comment]
Well it might be imbalance or something else. This is why you want to get the stack trace from *all* processors before really diving into a line of code.

**Comment by YaqiWang** [comment]
I assume all processors are doing the same sorting and no communication involved, right?

**Comment by permcody** [comment]
Yes but even with the possible problem in the sort 352^2 * log_2 352 ~ 1 millions integer operations which should run in a few milliseconds.

**Comment by rwcarlsen** [comment]
Is it slow for you in serial or just parallel (and how many procs)?

**Comment by rwcarlsen** [comment]
And are you using replicated or distributed mesh?

**Comment by YaqiWang** [comment]
I know it does not make sense. It is just ridiculously slow on Falcon with 4*36 processors. (I did not verify if number of processors can affect the time.)

**Comment by YaqiWang** [comment]
I was using `parallel_type = DISTRIBUTED` in the inputs.

**Comment by YaqiWang** [comment]
Thanks for the quick fix!
