### ISSUE TITLE
Memory imbalance with distributed mesh

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11413]
## Rationale

I am running a case on one Falcon node with over 4M elements and *distributed* mesh. I noticed 
 that one processor is taking significantly more memory than others. See the second process in the picture bellow:
![screen shot 2018-05-02 at 2 27 51 pm](https://user-images.githubusercontent.com/6607496/39547527-15149512-4e15-11e8-86ea-d2b48d953d5a.png)

## Description

I suspect that processor is the master and some thing should be deallocated but is actually not. I am pretty sure that much memory can be used on application side. I am doing a normal PJFNK solve with BoomerAMG preconditioning.

## Impact
Better parallel runs.

**Comment by friedmud** [comment]
That's definitely processor 0.

What kind of output are you using?  Exodus?  Nemesis?

**Comment by YaqiWang** [comment]
Exodus.

**Comment by friedmud** [comment]
That's your problem.  Processor 0 has to have a full copy of the mesh.

If you use Nemesis this should (mostly) go away.

(Processor 0 will always use a bit more memory)

**Comment by YaqiWang** [comment]
I guess this forces me to pre-split the mesh. But I have to say, this is not user unfriendly.

**Comment by YaqiWang** [comment]
While I am using `--split-mesh`, I got a segfault...

**Comment by friedmud** [comment]
1.  No it doesn't.  Nemesis works fine without pre-split mesh.  Just turn it on instead of Exodus.
 2. "not user unfriendly" means it _is_ user friendly.
 3.  Pre-split is INCREDIBLY easy these days: http://mooseframework.org/moose/documentation/systems/Mesh/index.html
 4.  Pre-split will make your initial-setup phase _incredibly_ fast.  Once you start using it you will use it all the time (I use it even on much smaller problems than 1M elements these days)
 5.  Issues are not the correct forum for this.  Let's have a discussion on moose-users.

**Comment by YaqiWang** [comment]
I was looking at that page. It is documenting split clearly. But when I try to do `my-app-opt -i my_input.i --split-mesh 36`, I get a segfault. I am making a debug version and see if I can get a backtrace. I have to finish this run by tomorrow and did not expect I will hit a wall like this...

**Comment by permcody** [comment]
@YaqiWang - I wouldn't change directions this late in the game then. 

If you are running out of memory, then there are other solutions. You can simply request few ranks on the first node but still all of the memory (I didn't this frequently with my GrainTracker runs). The Nemesis thing should just be a ready to roll fix too.

**Comment by YaqiWang** [comment]
Looks like it is Exodus output consuming the memory but not the mesh. Is there a good alternative of the output for visualization? VTK?

**Comment by permcody** [comment]
Nemesis is the good alternative for output. Just try it, it works in Paraview.

**Comment by permcody** [comment]
You can verify yourself here: https://github.com/idaholab/moose/tree/devel/test/tests/mesh/nemesis

**Comment by YaqiWang** [comment]
Is it necessary to have `Mesh/nemesis = true` when using nemesis output?

**Comment by friedmud** [comment]
No.  Just put `nemesis = true` in your `Outputs` block.

**Comment by friedmud** [comment]
This is really something we should talk about on the mailing list so it's archived there.  I'm closing this.
