### ISSUE TITLE
AddPeriodicBCAction on all variables fails if scalar variables are in the system

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11417]
## Rationale
If no `variable` argument id provided to this action it defaults to a list of _all_ non-linear variables:
```
    var_names_ptr = &nl.getVariableNames();
```
However, this apparently includes ScalarVariables, causing the setup of the periodic BCs to fail with the error

```
*** ERROR ***
Variable 'myscalar' does not exist in this system
```

where `myscalar` is a ScalarVariable.

## Description
`AddPeriodicBCAction` should default only to field variables as periodic boundary conditions (PBCs) do not make sense for ScalarVariables. This would allow users to keep using the compact default form when applying PBCs to all field variables.

## Impact
Set a more sensible default behavior.

**Comment by dschwen** [comment]
Ugh, this looks like API-insanity to me. This code:

```
var_names_ptr = &nl.getVariableNames();
for (const auto & var_name : *var_names_ptr)
  unsigned int var_num = nl.getVariable(0, var_name).number();
```

will always fail if a scalar variable exists in the system. It makes no sense that `nl.getVariable` chokes on a name returned by `nl.getVariableNames`. Or am I missing something here? (ping @lindsayad maybe?)

**Comment by dschwen** [comment]
f93c689 fixes the issue for me. Comments?

**Comment by lindsayad** [comment]
Yes, the method name `getVariable` is too generic for what it does. `getVariable` retrieves a spatial variable. `getScalarVariable` is the accessor for scalar variables. Your fix looks the most sensical to me given our APIs.
