### ISSUE TITLE
static builds broken with all-static libmesh config

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#11426]
## Rationale

Static builds lead to unregistered object errors when libmesh is configured via `--enable-all-static` instead of `--enable-static`. 

## Description

app.mk needs to be updated to check both `libmesh_static` and `libmesh_all_static` makefile variables (instead of just the former as it does currently).

## Impact

Make static builds work more reliably.  No API impact.

**Comment by permcody** [comment]
Notes: Initial problem is fixed but we might want to add a static build target. Tag @brianmoose, @milljm

**Comment by brianmoose** [comment]
I have successfully built an all static `combined-opt` (using `--disabled-shared --enable-all-static` when configuring libmesh).
A bunch of errors while running tests in the modules though, some with errors like:
`A '<object>' is not a registered object.`

Others with errors like:
`moose/modules/combined/test/tests/eigenstrain/variable.i:94: unused parameter 'Materials/var_dependence/enable_jit'`

`moose/test` works fine though.

Configuring libmesh with `--disable-shared --enable-static`, running tests in modules I get the "not a registered object" errors but not the "unused parameter" errors.

**Comment by brianmoose** [comment]
Also, it looks like all the unregistered object errors are objects registered to the test apps.

**Comment by brianmoose** [comment]
OK, it looks like the "unused parameter" warnings for `enable_jit` are due to libmesh not having `LIBMESH_HAVE_FPARSER_JIT` defined. `enable_jit` is only included when it is defined but input files use the parameter freely.

The reason it isn't defined is because libmesh disables `dlopen()` when configured 
with `--enable-all-static` and fparser jit requires `dlopen()`.

**Comment by rwcarlsen** [comment]
That's exactly what I was thinking.

**Comment by brianmoose** [comment]
Static and all static builds now work with moose (including modules) and we are testing these configurations.
