### ISSUE TITLE
Static VectorPostprocessor

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11436]
## Rationale

If the sizes of vectors of a VectorPostprocessor do not change during the entire simulation, we should be able to output the postprocessor like normal postprocessors. This kind of vector postprocessor is simply a collection of normal postprocessors.

## Description

Implementing this type of vector postprocessor should be fairly simple and derived class is not expected to change the sizes after construction. Coupling this type of vector postprocessor in other systems should be also simple. I am creating this issue for discussions per @permcody suggestion.

## Impact
Better design.

**Comment by permcody** [comment]
Closed by #11326
