### ISSUE TITLE
Screen output behavior changed recently when executing actions

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11435]
## Rationale

If we turn `Debug/show_actions=true`, the old behavior of screen output is to output on screen immediately during action. But now looks like all the outputs are delayed to the end of all actions. The change must be very recent although I do not know which commit. I was using the hash with new tagging system merged, and noticed the change today after updating MOOSE.

## Description

This is desired for users who want to monitor the progress of a large run.

## Impact
User friendliness.

**Comment by permcody** [comment]
@aeslaughter - There was some minor change recently to the console related to "Solve Converged!" Is it possible that's tied to this ticket?

**Comment by YaqiWang** [comment]
@friedmud this is the issue.
