### ISSUE TITLE
--split-mesh does not work with mesh/parallel_type=DISTRIBUTED

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11434]
## Rationale

We had difficulty on splitting a mesh with an input file (got segfault). Then @fdkong found he can split the mesh. We sat together and realized the culprit is the parameter `mesh/parallel_type=DISTRIBUTED` in my input file!

## Description

We should error out if the parameter is set or change it back to `REPLICATED` internally for mesh splitting.

## Impact
User friendliness.

**Comment by permcody** [comment]
Oh wow - this is a problem.
