### ISSUE TITLE
AnalyzeJacobian derive from FileTester

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#11433]
## Rationale

New capability to prevent common errors.

## Description

AnalyzeJacobian should derive from FileTester because it creates a predictable output file name based on the input file name that the TestHarness should be made aware of.  This will prevent race conditions.

## Impact

Testing robustness as new tests are added.

**Comment by permcody** [comment]
@milljm - Good ticket for you to work on. Should be easy. Should be able to undo the prereq @brianmoose added here: https://github.com/idaholab/moose/pull/11295#discussion_r186205706

**Comment by brianmoose** [comment]
Wouldn't this just tell the user that there is a race condition? And they would still need to add the prereqs to avoid the race condition?

**Comment by permcody** [comment]
Umm... Yes....

That's still a huge step forward in identifying the potential problem. I guess what I mean, is "test with the fix here, instead of undo the fix here."
