### ISSUE TITLE
Mesh splitting webpage has minor issues

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11445]
## Rationale

For few of commands, `-i` command-line argument is missing.

## Description

Maybe few other minor decoration issues.

## Impact
Better for dummy users.

**Comment by permcody** [comment]
Tag @rwcarlsen

**Comment by YaqiWang** [comment]
FYI, clicking the link `Using Split Meshes` has a funny effect (vibrating contents) on my browser maybe because my screen barely fit the content but not quite.

**Comment by permcody** [comment]
The "bumping" effect is known. Thanks.
