### ISSUE TITLE
moose-dev-gcc on Falcon should set MOOSE_JOBS

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11440]
## Rationale

This is probably the reason why people think it takes "hours" to compile libMesh on Falcon... we're not setting `MOOSE_JOBS` by default... so `update_and_rebuild_libmesh.sh` is only using _1_ processor!

## Description

I suggest `12`

## Impact

None

**Comment by permcody** [comment]
Tag @milljm

**Comment by milljm** [comment]
The HPC guys tell us we should only use 6 cores on the head node... But I get what you are saying. Anything higher than 1 is a good thing.

There are internal instructions for building libMesh while on a node... in which case, we can entertain:
```pre
MOOSE_JOBS=`cat $PBS_NODEFILE | wc -l`
```

I'll see what I can do in our module files to make this work properly.

**Comment by friedmud** [comment]
The headnodes are not that loaded... and compiling doesn't take forever
anymore.  I see speedup all the way to 16 cores.

I think 10-12 is a reasonable default.

Derek

**Comment by friedmud** [comment]
Also: using the PBS_NODEFILE doesn't make sense... parallel compiling
doesn't use MPI...

Derek

**Comment by milljm** [comment]
Done.
While on a head node only, MOOSE_JOBS will have a value of 12.

Cheers!
