### ISSUE TITLE
Option to specify periodic direction for strain periodicity

### ISSUE THREAD

**Issue by SudiptaBiswas** [idaholab/moose#11448]
## Rationale

The current periodic strain capability, as developed in #11358, only works when periodic boundary condition is applied to all the directions. Additional capability is needed to add the option to choose the direction to activate periodicity.  

## Description

We can either extract the periodic directions from the boundary condition or allow user to provide direction input to `GlobalStrainUserObject`. 

## Impact

Improvement of the periodic strain capability.

**Comment by permcody** [comment]
Make sure you don't re-invent anything here. There are several methods on MooseMesh that can help you figure out periodic related queries. Let us know if you have any questions.

**Comment by SudiptaBiswas** [comment]
Closed via #11494
