### ISSUE TITLE
Improve Jacobian Debugger Documentation

### ISSUE THREAD

**Issue by arovinelli** [idaholab/moose#11450]
## Rationale

The actual web-page [http://mooseframework.org/wiki/JacobianDebugging/](url) describing how to use the build in Jacobian check need some clarification.

## Description

There are a couple of things that need to be clarified:
   -   The current version of the web-page suggests that no preconditioning block is required to check the user defined Jacobian. I would add a sentence saying that the following preconditioning block need to be present and active in the input file to check the user supplied Jacobian.
[Preconditioning]
  [./SMP]
    type = SMP
    full = true
  [../]
[]

  -  It is not clear which boundary conditions are supported by the moose Jacobian checker. An example is: how do you check that a user Jacobian implementations is correct for a kernel which requires an imposed displacement boundary condition to be active.

## Impact

This changes will clarify how to use the Jacobian checker and will reduce the amount of question on the mailing list. This will save time to developers.
As this is only a documentation improvement the code will not be impacted.

**Comment by dschwen** [comment]
> how do you check that a user Jacobian implementations is correct for a kernel which requires an imposed displacement boundary condition to be active

No solve is being performed during the check. You would simply set the initial condition to have a non-zero displacement to check the Kernel.

I can expand the documentation accordingly.

**Comment by arovinelli** [comment]
Daniel, thanks for addressing this issue.
Now the documentation is clear is and exhaustive.

All the best

Andrea
