### ISSUE TITLE
Race conditions exist where TestHarness functionality does not detect

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#11454]
## Rationale
There exists the possibility of a race condition not currently being detected by the TestHarness.

## Description
Consider the following spec file:
```conf
[Tests]
  [./a]
    type = Exodiff
    input = good.i
    exodiff = exodiff_out.e
  [../]
  [./b]
    type = 'AnalyzeJacobian'
    input = 'good.i'
    cli_args = 'Materials/elastic_strain/inelastic_models="creep_ten"'
    prereq = a
  [../]
  [./c]
    type = 'AnalyzeJacobian'
    input = 'good.i'
    cli_args = 'Materials/elastic_strain/inelastic_models="creep_ten creep_zero"'
  [../]
[]
```
The DAG would look like: [A, C], [B]. Jobs A and C launch immediately.
When Job A finishes, Job B will be allowed to launch, while Job C might still be running/writing output.

AnalyzeJacobian testers write to output filenames based on the input parameter. So B and C write to the same file (good-_[some name here]_).
 
## Impact
We think this is low. As we do not have many (if any) spec files where two different Tester types are depending on one another in this fashion.

**Comment by permcody** [comment]
Per our conversation we learned several things:

- This has nothing to do with `AnalyzeJacobian`, it's about a faulty algorithm for detecting possible overlaps. I recommend changing the test case to all one type (e.g. Exodiff).
- New algorithm should look like this (pseudo-code):
```
    # populate map of outputs to jobs
    output_to_job_list = {}
    for (job in dag)
    { 
       output = job.getFileOutpu()
       output_to_job_list[output].append(job)
    }

     # Go through the map and make sure that there is a dependency for any multiplicity
     for (job_list in outputs_to_job_list)
         if job_list.length() > 2
             checkForAtLeastOneDependencyAmongJobs(job_lists)
```
