### ISSUE TITLE
`./moosedocs check --generate` does not generate anything

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11476]
## Rationale
`./moosedocs check --generate` should generate stubs for newly registered MOOSE objects. But it does not.

## Description
Running the above command in my app (Marmot) after adding and registering new classes will not generate any new .md files. A `./moosedocs build` issued next will complain about the missing .md files.

## Impact
Make it work as advertised.

**Comment by friedmud** [comment]
Pretty sure this is the same as #11375

**Comment by dschwen** [comment]
@friedmud, you are right. Closing this issue.
