### ISSUE TITLE
DistributedGeneratedMesh

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11485]
## Rationale

With our focus on distributed mesh... it would be great to be able to just generate a distributed mesh if you're using a "generated" mesh.

I propose adding a new mesh type: `DistributedGeneratedMesh` that does just that.

## Description

Each processor will only generate the portion of the mesh that it owns.

## Impact

None - new capability

**Comment by permcody** [comment]
I think we should definitely have this capability but I don't think exposing a new type is the right thing for the end user. I would suggest that try to get this to work with the existing `GeneratedMesh` + `parallel_type` and do the right things under the hood.

**Comment by friedmud** [comment]
I like the idea of auto-promoting when we can.  Let's try to do that.

**Comment by permcody** [comment]
closed by #11505
