### ISSUE TITLE
Access to LinearViscoelasticityBase internal variables

### ISSUE THREAD

**Issue by agiorla** [idaholab/moose#11496]
## Rationale

Several material properties in LinearViscoelasticityBase are defined as `MaterialProperty<std::vector<RankTwoTensor>>` or `MaterialProperty<std::vector<RankFourTensor>>` which makes it impossible to access them for post-processing purposes. This makes validation or testing of new viscoelastic models particularly difficult.

## Description

These properties should be defined as `std::vector<std::reference_wrapper<MaterialProperty<T>>>` instead, with each element in the vector being given a separate name. This would allow the use of `RankTwoAux` and `RankFourAux` to extract values from these properties.

## Impact

Improved output capabilities for viscoelastic materials. Some internal changes in `LinearViscoelasticityBase` and derived classes.

**Comment by friedmud** [comment]
This is way more than a minor change... every object that consumes those properties will need to change.  In addition - all of the internal code in LinearVisoelasticityBase will have to change as well (you're inverting a loop basically).

**Comment by agiorla** [comment]
Granted, it is not that minor. But it is rather straightforward to do, and has no impact on results.

**Comment by permcody** [comment]
The result is only one consideration though. It's a different way of thinking that's feels different then most everything else in MOOSE. Instead of having a property that is itself a vector, now we have a bunch of individual named values.

The usage is also different for Kernel developers. Instead of just getting a property, now you have to pick which property you want from the list, etc. Sure this is a valid implementation and clearly can, work. We are just asking the question on whether we should go in a different direction here. Will this ultimately be more difficult for users to consume?

Can you elaborate on "impossible to access them for post-processing purposes"? There might be other ways of solving your problem.

**Comment by agiorla** [comment]
So, there are a few things to consider.

At the moment, there are no `AuxKernel` that can access the internal strains and the elasticity tensors corresponding to the different springs in the spring-dashpot assembly. Which means we can't check that these are assigned correctly or that the internal procedure is correct.

We could make a `VectorRankTwoAux` and `VectorRankFourAux` to do that. But then we would find some mismatch between the index and the traditional notations. The traditional notations give `E_0` the Young's modulus of the first spring (for a Kelvin-Voing model), and `E_1` to `E_n` the moduli of the other springs, associated to the dashpots `eta_1` to `eta_n`

With a `VectorRankFourAux`, extracting `E_0` and `E_1` would look like that:

`[E_0]
type=RankFourAux
variable=E_0
rank_four_tensor=first_spring_elasticity_tensor
[../]
[E_1]
type=VectorRankFourAux
variable=E_1
rank_four_tensors=spring_elasticity_tensors
position=0
[../]`

With the proposed method, each would have its separate variable, and the index would be consistent with the traditional notations

`[E_0]
type=RankFourAux
variable=E_0
rank_four_tensor=spring_elasticity_tensor_0
[../]
[E_1]
type=RankFourAux
variable=E_1
rank_four_tensors=spring_elasticity_tensor_1
[../]`

I personally find the second solution easier for the user, even though I admit it doesn't look great in the source code...

**Comment by agiorla** [comment]
(and now that I think about it, one way to use a VectorRankTwoAux/RankFour while keeping the indexes the same would be to have `_first_spring_elasticity_tensor` inside the `_spring_elasticity_tensors`, which would make one less material property. The indexing might get messy though)

**Comment by permcody** [comment]
I haven't thought about this a lot so I was just posing the question. Perhaps in the longer term, MaterialProperty itself could be made to be a little easier to work with, but if several locations are being held onto with references, I don't see a way to make that work. Your solution is actually pretty clever if not for the syntax for digging out the property. 

I'm not going to hold this change up. Just commenting.
