### ISSUE TITLE
Enable cohesive zone modeling

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#11546]
## Rationale

We have at least one user (@arovinelli) very interested in conducting cohesive zone modeling through MOOSE.

## Description

I'm not a domain expert with respect to cohesive zone modeling, but we need to be able to add residuals based on quantities like the gap between split meshes. This is perhaps most appropriately done through a `FaceFaceConstraint` type object; however, it *may* also be implementable through an `InterfaceKernel` as long as the master/slave element pairings are the same as from an initial un-split mesh. If the latter implementation is used, we need to make sure we can use stateful material properties within the `InterfaceKernel`. This is something that we should make sure works regardless of whether we're working with a split mesh (e.g. a more "regular" use case).

## Impact

Enables modeling of a new class of problems with MOOSE: cohesive zone problems.

**Comment by lindsayad** [comment]
We've had a [report](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/hQkaOVbrm88/83g2AqKTCgAJ) of odd behavior getting material properties for an `InterfaceKernel`. Need to look into this.

**Comment by lindsayad** [comment]
@arovinelli In the `czm_wen` branch, is this the input file I should be looking at? `modules/tensor_mechanics/test/tests/CohesiveZoneJunction/czmTestJunctions_2D.i`

**Comment by arovinelli** [comment]
@lindsayad Alex, tahnks a lot for opening this issue. You are correct modules/tensor_mechanics/test/tests/CohesiveZoneJunction/czmTestJunctions_2D.i which is associated to 4ElementJunction.e  mesh 

If you prefer i can make a virgin branch in which I only add what you need for debugging.

Anyway here is a quick list
of all the C module I wrote and that are used from this input file.

- modules/tensor_mechanics/src/mesh/CohesiveZoneMesh2D_JunctionTest.C (manual mesh splitting)
- modules/tensor_mechanics/src/userobjects/CohesiveLaw_3DC.C (UO computing residual and jacobian coefficients)
- modules/tensor_mechanics/src/materials/DisplacementJumpBasedCohesiveInterfaceMaterial.C (Material for the interface, also contains all the kinematics to go from global mesh coordinates to cohesive elemnt coordinates)
- modules/tensor_mechanics/src/InterfaceKernels/DisplacementJumpQuadratic.C (Cohesive Interface kernel)

Also the modified base modules are (pulled from Wen's cohesive branch): 

- framework/src/base/ComputeMaterialsObjectThread.C
- framework/include/materials/Material.h
-  framework/include/materials/Material.C
- framework/src/base/ComputeResidualThread.C
- framework/src/interfacekernels/InterfaceKernel.C

Thanks again for the help, I really appreciate it

**Comment by lindsayad** [comment]
Is this mesh generated with cubit? If so, can you push up the journal file? (It may actually already be there...on my phone right now)

**Comment by lindsayad** [comment]
I wanted the journal file (not the mesh file) but perhaps I can do without. Boundary 100...is it a node set or a side set? To be true to their concept, interface kernels should really be defined with respect to side sets. And then that also gives materials meaning too...a material on a node-set really doesn't make much sense...what does it mean to have a material at the interface of two sub domains? But a material defined on a side set has a clear meaning...it should have the properties of the medium/subdomain to which it is attached. I suspect you've already thought about all these things...I'm recording them here as we think about the fundamental concepts behind defining the czm problem.

**Comment by lindsayad** [comment]
I believe I found your problem @arovinelli :-) Add the latter line in the `ComputeJacobianThread::onInterface` method in `ComputeJacobianThread.C`:
```c++
      _fe_problem.reinitMaterialsFace(elem->subdomain_id(), _tid);

      _fe_problem.reinitMaterialsBoundary(bnd_id, _tid);
```

It looks like @jiangwen84 added this line in `ComputeResidualThread` but didn't do it for `ComputeJacobianThread`

**Comment by arovinelli** [comment]
I'll get the journal file to you as as I can access trelis (we have floating licenses).
Let me explain. The interface is defined with respect to a sideset. However elemnt sides are added to the boundary when the mesh is splitted.
The splitting and boundary creation is done manually (i.e. I hardcoded element sides to add to boundary 100, to make sure that possible bugs of the mesh splitting algorithm are not introduced at this stage).

The mesh is a square composed of four tri3 elements. Each element is a block. All the 4 common sides are added to 

```
void
CohesiveZoneMesh2D_JunctionTest::addInterfaceBoundary()
{
  Elem * elem;
  BoundaryInfo & boundary_info = getMesh().get_boundary_info();

  elem = getMesh().elem(0);
  boundary_info.add_side(elem->id(), 0, 100);
  boundary_info.add_side(elem->id(), 2, 100);

  elem = getMesh().elem(1);
  boundary_info.add_side(elem->id(), 2, 100);


  elem = getMesh().elem(2);
  boundary_info.add_side(elem->id(), 0, 100);

  // assign a name to the interface
  boundary_info.sideset_name(100) = "interface";

}
```

**Comment by arovinelli** [comment]
OMG!!!!! Alex you are awesome!! Now everything works!!!! I can't say thank you enough for the help!

**Comment by arovinelli** [comment]
Now I have one question. How can we incorporate the changes to the base routines to allow for a PR?
I don't think what has been done with the basic routines are merge-able!

**Comment by arovinelli** [comment]
Quick update, I renamed the branch for this issue as `czm_DG_#11456` and rebase it.

**Comment by lindsayad** [comment]
You and @jiangwen84 have done all the work on this. I would recommend you clean it up in a way you see fit and then submit a pull request that we can review. I suspect you've mostly adhered to our coding standards (and I'm pretty sure you've submitted PRs before), but if you need a refresher our coding standards are [here](http://mooseframework.org/wiki/CodeStandards/)

**Comment by arovinelli** [comment]
Dear Alex, 
I'm working to clean up the code and do some nice tests for the kernel and the mesh splitting algorithm. Then i will write the documentation and I'll open the pull request when everything is nice and clean.
@jiangwen84, let me know if you want to review the code before submitting the PR.

**Comment by lindsayad** [comment]
That's a good plan

**Comment by liuwei15544** [comment]
nice answers

**Comment by arovinelli** [comment]
Ok, I cleaned the code, created some tests and opened the pull request, making sure to mention that we need suggestion on the path forward.
