### ISSUE TITLE
Peacock: Changing the size (xmax, ymax) of a mesh doesn't rescale it in the Exodus Tab

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#11548]
## Rationale

Better Peacock usability

## Description

When using a generated mesh, if you change the size of the mesh, it won't rescale it in the Exodus tab. This can lead to a tiny or large view of the mesh that doesn't zoom properly. 

## Impact

Useablity

**Comment by aeslaughter** [comment]
I don't understand this problem. Are you wanting the results tab to reset the camera if the mesh geometry changes? At a minimum, you have to re-execute so the results even contain the changes to the mesh. 

Lets say you did re-execute, but in the result you have the camera positioned a certain way. How does peacock know that you want to reset the view to fill the screen? That is, what changes that allows us to blow away a camera view that the user established?

**Comment by permcody** [comment]
Yes, this issue is a camera reset issue which I've run into in several other places in Peacock.  Any time the size of the mesh changes, the Exodus tab needs to reset the camera. Actually, just having a reset camera button would go a long ways to making Peacock a little more friendly to use. When I was working with BISON this week and tried to rescale the y-axis. Most of the time the mesh just disappeared completely. When I was lucky enough for it not to disappear, I couldn't reset the camera so I had to carefully zoom in on it to see anything.

**Comment by aeslaughter** [comment]
@brianmoose Do you have the ability to emit a signal from the Input tab when the mesh block is changed?
