### ISSUE TITLE
Apply a FunctionPresetBC or FunctionDirichletBC incrementally

### ISSUE THREAD

**Issue by agiorla** [idaholab/moose#11559]
## Rationale

In several problems for tensor mechanics we need to increase the displacements on a boundary of the specimen starting from a preloaded initial configuration (either through other BCs or through eigenstrains), which is generally unknown. However, the `FunctionPresetBC` and `FunctionDirichletBC` impose the new value of the displacement without considering the previous state of the material. We need to be able to evaluate the BC incrementally such as: 

`u(t_n+1) = u(t_n) + g(t_n+1) - g(t_n)`

Which might be different from `g(t_n+1)` if the BC was not active at `t_n` or before.

## Description

Add an `incremental` boolean flag (default false) that would let the BC to be computed incrementally if requested by the user. If false, we fall back on the existing version `u(t_n+1) = g(t_n+1)`

## Impact

More versatile `FunctionPresetBC` and `FunctionDirichletBC`.

**Comment by permcody** [comment]
This might be a little too physics specific. Let's see what you come up with and make a decision about whether this BC should just live in TensorMechanics.

**Comment by agiorla** [comment]
Sure! I've started the PR, let me know what you think. I can move it in TensoreMechanics if needed.

**Comment by agiorla** [comment]
@jasondhales just indicated that there is a PresetVelocityBC in the tensor_mechanics module that already does what I wanted to do. I tried it and it worked for my case, so I'm closing that issue. Thanks!
