### ISSUE TITLE
Add peridynamics module

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#11561]
## Rationale

Peridynamics is an alternative discretization scheme that has proven well-suited for fracture mechanics problems. It was originally developed for continuum mechanics problems, but is applicable for other physics. It re-casts the differential equations that are typically used to represent mechanics problems into integral equations, which alleviates some of the difficulties encountered with representing discontinuous behavior such as fracture within the standard finite element method.

## Description

Peridynamics is nonlocal, and a given node interacts with all of the nodes that are located within a horizon, which is a user-specified parameter that controls the degree of nonlocality. Although peridynamics does not require a mesh, it is straightforward to implement it within a finite element code using one-dimensional line elements to represent the interactions between nodes within the horizon, and this has been done by multiple authors. This approach has been taken to develop a peridynamics implementation based on MOOSE, using finite elements to represent peridynamic interactions.

## Impact

To make this available for a variety of applications, add the core peridynamic functionality to a module within moose. This does will solve additional physics, but permits the physics models already being solved by MOOSE using finite elements to be solved using a peridynamic discretization.

**Comment by bwspenc** [comment]
FYI @hchen139 @permcody

**Comment by permcody** [comment]
Let's setup a meeting with our software review board and talk about this. Mike Short also wants to add a new module related to cluster dynamics. 

Tag @rcm59 and @friedmud
