### ISSUE TITLE
Add PorousFlow permeability material for variable multiplied by tensor components

### ISSUE THREAD

**Issue by hsheldon** [idaholab/moose#11611]
## Rationale

It is sometimes desirable to calculate permeability from a scalar multiplied by tensor components, where the scalar might be some function of depth, for example, but the tensor components (representing the anisotropy of the permeability) remain constant. Currently this can be achieved using PorousFlowPermeabilityConstFromVar but this requires a separate variable for each component of the permeability tensor, resulting in untidy and error-prone input files.

## Description

Add new PorousFlow permeability material enabling user to specify permeability in terms of a coupled var multiplied by tensor components.

## Impact

Ability to specify permeability in terms of 2 input parameters (a scalar variable and a tensor).

**Comment by WilkAndy** [comment]
Sounds like good functionality to have in PorousFlow.  Are you planning on doing the work?

**Comment by hsheldon** [comment]
Yes I’m onto it!
