### ISSUE TITLE
PorousFlowPorosity (and other coupledNodalValue?) fixes

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#11620]
## Rationale

PorousFlowPorosity classes (and other PorousFlow classes?) are error-prone when they're grabbing coupled Variable values.

## Description

PorousFlowPorosityConst definitely needs to grab coupledNodalValue instead of coupledValue, if ```at_nodes=true```

Possibly less trivial: if at_nodes=true, PorousFlowPorosity classes need to check that the supplied coupled Variable is indeed a LINEAR LAGRANGE.  This check may also be needed for other PorousFlow classes that use coupledNodalValue.  Currently i'm just blindly constructing _v(coupledNodalValue("blah")), but what if "blah" is a CONSTANT MONOMIAL?  Later i use _v[_qp] in the Material, where _qp ranges over the number of nodes of the element (it is called _qp just to make the code look like all MOOSE Material classes: if ```at_nodes=true``` then in fact _qp indexes over the nodes of the element).

## Impact

Bug fix!

**Comment by WilkAndy** [comment]
OK, so i changed my mind completely here.

Now i think that the input porosity (```porosity_zero``` in the case of PorousFlowPorosity, and ```porosity``` in the case of PorousFlowPorosityConst)  should always be a constant monomial.  It is certainly true that physically porosity belongs to a 3D volume of material, so the input porosity should not be a linear lagrange.  So, i will assume it is a constant monomial and **just use the zeroth** element, eg, ```_porosity_zero[0]``` **not** ```_porosity_zero[_qp]```.  Then it doesn't matter whether this is a "nodal" Material (computing porosity at the nodes of the element) or an ordinary Material (computing porosity at the quadpoints of the element).

Another option is to use ```[_qp]``` for ordinary Materials and ```[0]``` for nodal Materials, but every PorousFlow input file i've seen uses constant monomial anyway, so the argument is a bit irrelevant.

Before putting in a PR i'm awaiting thoughts from @hsheldon .

**Comment by hsheldon** [comment]
I agree, and I'm glad you changed your mind - it does not make sense for the input porosity to be anything other than elemental. Does the example that I sent you now work the same with both kinds of porosity (PorousFlowPorosity and PorousFlowPorosityConst)? If so I'm happy with this change.

**Comment by WilkAndy** [comment]
Yes, i can confirm that using ```[0]``` as in PR #11630 fixes your problem.  "PorosityConst" and "Porosity" give the same result, and there is no nonlinear convergence problem (up to t=3E12 anyway).

**Comment by hsheldon** [comment]
Great, thanks for fixing.

**Comment by WilkAndy** [comment]
Thanks for finding this important bug !!
