### ISSUE TITLE
Enable MatPartitioning

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#11628]
## Rationale
We need more partitioning options, and a simple way is to enable MatPartitioning of PETSc. We then should be able to use all external packages via a simple interface. 

## Description
We will add PetscMatPartitioner in MOOSE

## Impact
Does not impact anybody if they do not try the new interface

**Comment by permcody** [comment]
@fdkong - Looks like this can be closed? Is it finished, merged?

**Comment by fdkong** [comment]
Yes, we should close. Why I did not close it in my PR?
