### ISSUE TITLE
coupledNodalValue interface should check if the supplied variable is nodal

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#11623]
## Rationale

If users supply a non-nodal variable into `coupledNodalValue` (and its related methods), we should report back an error.

## Description

Add an integrity check into `coupledNodalValue`, that the supplied variable is nodal.

## Impact

Improve simulation integrity

**Comment by andrsd** [comment]
tagging @WilkAndy

**Comment by WilkAndy** [comment]
This looks good, thank you @andrsd
