### ISSUE TITLE
Fixed float operations in StatisticsVectorPostprocessor

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#11634]
## Rationale

`std::accumulate(stat_vector.begin(), stat_vector.end(), 0.)`.` std::accumulate` determines the data type accounting to the last parameter. We want to always use double, and hence use `0. ` instead of `0`. 
## Description
If we put ` 0`, the calculation will be considered based on integers.  

## Impact
Impact users who are using `StatisticsVectorPostprocessor`

**Comment by permcody** [comment]
Fande, please fill out the 3 sections (NQA requirements).
