### ISSUE TITLE
MeshGenerators System

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11640]
## Rationale

It's that time again!  Time for the _final_ code system to be added to MOOSE.  This time it's: `MeshGenerators`.  We want to provide a smoother way to generate a complete mesh from scratch using just MOOSE.

This idea was developed with @YaqiWang @snschune and @jortensi 

The idea is to make a graph of `MeshGenerators` that depend on the output of each other.  The dependency will be implicit based on the input `MeshGenerator`s.  Each `MeshGenerator` will provide an output `ReplicatedMesh`... which can be used as input to the next `MeshGenerator`.

What's going to happen is all of our existing `MeshModifiers` _and_ `MooseMesh` derived objects will fit in the new system.  This will make it possible to use `PatternedMesh`, `StitchedMesh`, `TiledMesh`, etc. *at the same time*... while also doing extruding, transforming, sideset modifications, etc.

## Description

See Above

## Impact

Initially zero.  We're going to grow the new system completely independently from `Mesh` and `MeshModifiers`.  HOWEVER: at some point we will probably deprecate `MeshModifiers` and eventually remove it... and we'll also deprecate and eventually remove some `MooseMesh` derived objects.

**Comment by YaqiWang** [comment]
This will be a highly extendable system. It will help streamline lots of our simulations and make the code more user friendly. I will make more comments.

**Comment by friedmud** [comment]
After another conversation with @YaqiWang we're going to support something interesting.

The original design was that each `MeshGenerator` (MG) was going to create a mesh to output.  The reason is that when you have multiple consumers... they would all presumably be sharing the same input.  But that doesn't make sense for "simple" things like adding a sideset, etc... no reason to make a whole copy of the mesh to output from each MG.

So: instead... each MG is meant to _operate_ on the incoming mesh(es) and the output will be the same mesh (when possible... obviously some MGs will create a new mesh for output like `PatternedMesh`, `StitchedMesh`, etc.)

But, to deal with the multiple consumer case here's how it's going to work: the _inputs_ to the multiple consumers will get duplicated just after the MG is finished.  That will give each consumer a clean copy they can operate on/with.

This is going to require some decent accounting to get right... but it's going to be very worth it.

**Comment by jortensi** [comment]
We need to also start thinking about block_id assignment and other user supplied data (like material_id, equivalence_id and depletion_id).

**Comment by snschune** [comment]
> We need to also start thinking about block_id assignment and other user supplied data (like material_id, equivalence_id and depletion_id).

In particular, who stores the `material_id`, `equivalence_id`, and `depletion_id` during the execution of the `MeshGenerators`? Ultimately, we want to inject them into the `ElemIDUO`.
Adding user objects happens too late so we need to stash that info somewhere.

**Comment by permcody** [comment]
MeshGenerator system has been completed and is in-use. Closing
