### ISSUE TITLE
Add 2-phase fluid properties object that takes 1-phase fluid properties as inputs

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#11641]
## Rationale
It is useful to run "2-phase" problems with arbitrary combinations of 1-phase fluid properties. For example, there are cases when a 2-phase problem can be designed such that it should reduce to 2 1-phase problems acting independently.

## Description
This would add a 2-phase fluid properties class that takes the names of its two 1-phase fluid properties objects. It also throws an error if a 2-phase fluid properties interface ever even gets called, to guarantee that the two phases are indeed independent.

## Impact
2-phase fluid properties user objects now can take the names of their 1-phase fluid properties user objects constituents. Also, added the independent 2-phase fluid properties class.

**Comment by joshuahansel** [comment]
Why didn't this issue close?

**Comment by permcody** [comment]
I don't think you ever made a PR and had that merged. Those commits are just on a local branch as far as I can tell.

**Comment by joshuahansel** [comment]
Oh I see what happened. In addressing some changes, I rewrote a commit message and then accidentally referenced the PR number (#11642) instead of the issue number. Closing.
