### ISSUE TITLE
Add InterfaceUserObject Class

### ISSUE THREAD

**Issue by arovinelli** [idaholab/moose#11647]
## Rationale

This class is similar to InternalSideUserObject, but allow to works on Interfaces

## Description

`InterfaceUserObject` is a new class inheriting from `boundaryRestrictableRequired`.
`loop/ComputeUseroObjectThread` adn `loop/ComputeMateirlasThread` now have an `::onInterface` Method

## Impact
This will help in developing the interface kernel based, cohesive zone model (#11575 #11546 )
No cons, only a new feature users can enjoy.

**Comment by arovinelli** [comment]
I have a problem when grabbing material properties on both side of the interface....

It gives me all zero rather than actual values... did I forgot to update something in the loops?

**Comment by permcody** [comment]
Closed by #12902.
