### ISSUE TITLE
framework userobject -> userobjects

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#11674]
## Rationale

The userobject directory in all the modules is called userobjects (with an "s") but in framework it's called userobject (no "s").  Change framework.

## Description

Perhaps this is deliberate.  Please just close if so.   I'd prefer not to address this issue - i'm a bit stressed right now.

## Impact

Uniformity

**Comment by permcody** [comment]
Yes, we are well aware of this. It's been bugging us for years. We didn't want to lose line history, but git does preserve it if we just move things. We should probably just do this... Thanks for reminding us.

**Comment by WilkAndy** [comment]
I think if someone actually does this they won't refer to this issue as they'll make a new one.  Closing.
