### ISSUE TITLE
Add add_aux_variables boolean in TensorMechanicsAction

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#11684]
## Rationale
Currently the TensorMechanicsAction has a boolean called `add_variables` that can be used to have the action add both variables (displacements) and AuxVariables (e.g., stresses and strains).  

When running thermo-mechanical problems I prefer to see all of my primary variables included in the `[Variables]` block  but have the action create the AuxVariables and associated AuxKernels for stresses and strain. Unfortunately both the creation of variables and AuxVariables are triggered by the `add_variables` boolean.  Thus, if I want the action to create the aux_variables I must have it create the primary variables as well.  I can get the AuxKernels created with the `generate_output` option in the action but must still explicitly list the AuxVariables in the input file. 

## Description
Add an additional boolean called `add_aux_variables` to the action that is used to trigger the creation of the AuxVariables instead of using `add_variables`.

## Impact

Moderate.  The changes to the code minor but input files that currently have `add_variables=true`
will need to have `add_aux_variables=true` added in the TensorMechanics Master action block.

**Comment by dschwen** [comment]
I don't like having to add this new parameter. I find it hard to see a
scenario where stuff aux variables have to be added by hand. Just make the
add variables parameter control only non linear variables.

**Comment by gambka** [comment]
That works for me.
