### ISSUE TITLE
Put action times into a separate catalog 

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11715]
## Rationale

Currently https://github.com/idaholab/moose/blob/devel/framework/src/actions/ActionWarehouse.C#L355 is using `Setup` as the catalog name for actions, which is used by some other performance logs.

## Description

It will make things a little clearer if we can use a dedicated catalog name for actions, such as `Actions`.

## Impact
Minor, just to make the output a little nicer for looking the times of all actions.

**Comment by friedmud** [comment]
This will be fixed with the PerfGrpaph: #11551 #11552
