### ISSUE TITLE
EqualValueEmbededConstraint

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#11722]
## Rationale

In the current framework, we have EqualValueConstraint and EqualValueBoundaryConstraint to handle face to face equal-value constraint. The EqualValueEmbededConstraint adds capability to enforce equal-value constraint for overlapped portions of two blocks. Our plan is to further build upon EqualValueEmbeded Constraint to do Rebar-to-Concrete constraint, where reinforcing bars can be embeded in a concrete (a block)

## Description

EqualValueEmbededConstraint uses contact models to enforce constraint. Currently it supports "glued + kinematic" and "glued + penalty" formulations.

## Impact

This adds a new type of constraint in the MOOSE framework. No impact on other code as it is new capability.

**Comment by lindsayad** [comment]
Closed by #11828
