### ISSUE TITLE
MooseDocs markdown locations

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#11730]
## Rationale
Markdown pages, in general, match up with header files. Therefore, the markdown pages should 
mirror the include path for the content being documented.

## Description
The MooseDocs.tree.syntax.py nodes require the ability to select file locations based on the header or the input file syntax, the later will be deprecated.

## Impact
Applications will need to be updated for the location change, but this can be scripted.

**Comment by friedmud** [comment]
I guess I don't see why those wouldn't be under the "actions"
subdirectories for their individual modules.  That's presumably where the
Action itself actually is - right?

Derek

**Comment by permcody** [comment]
I agree with Derek - The situation with Actions is even worse currently since they are scattered over all directories without a single logical place to write up the design.

**Comment by aeslaughter** [comment]
The problem is not with where to put the action objects, where do I put the documentation for the `[Variables]` block itself?

```
Variables: /Variables hidden=True removed=False groups=set(['MOOSE', u'MooseTest']) alias=None
│   ├── AddVariableAction: /Variables/AddVariableAction hidden=True removed=False groups=set(['MOOSE']) alias=None markdown=framework/include/actions/AddVariableAction.md
│   ├── CopyNodalVarsAction: /Variables/CopyNodalVarsAction hidden=True removed=False groups=set(['MOOSE']) alias=None markdown=framework/include/actions/CopyNodalVarsAction.md
```

**Comment by joshuahansel** [comment]
Perhaps there is one documentation tree for documentation-by-file and another for the systems descriptions (and maybe whatever else doesn't match up with files)?

**Comment by aeslaughter** [comment]
The conclusion of multiple discussions:

- `doc/content/source` will contain MooseObject and Action object documentation organized as done in the include directory.
- `doc/content/syntax` will contain pages for syntax blocks only, i.e., the index.md files that already exist organized with input file syntax.
