### ISSUE TITLE
Allow IterationAdaptiveDT to reject very large time steps

### ISSUE THREAD

**Issue by agiorla** [idaholab/moose#11745]
## Rationale

`IterationAdaptiveDT` only modifies the next time step. However, for problems with highly discontinuous material behavior (i.e. continuum damage for quasi-brittle material), the first time step at which the discontinuity occurs (damage initiates) is critical for the rest of the simulation. If it is too large, the damage will be artificially spread over a very large area. Allowing `IterationAdaptiveDT` to restart (if requested by the user) the current time step if the time step is too large compared to the ideal time step would prevent such artifact from happening.

## Description

The lag by 1 time step can be observed by using a `MaterialTimeStepPostprocessor` in the context of plasticity or continuum damage with an `IterationAdaptiveDT` (and has been reported in the `MaterialTimeStepPostprocessor` documentation).

## Impact

New capability.

**Comment by agiorla** [comment]
I have an implementation that provides the behavior I need for continuum damage simulations with BlackBear, as far as I can tell. However, there are a few things that I did that I am not 100% sure that it is the "MOOSE way" of doing things, and there was one thing which I was unable to do. I believe that this is something that would be useful not for me/BlackBear, but for other usages as well, so I would appreciate any form of feedback and suggestion for that one ;)

**Comment by agiorla** [comment]
@bwspenc It seems I don't have the right to reopen it. Do you mind reopening it? Also, let me know if there are any other changes you would like me to do compared to the previous PR.

**Comment by bwspenc** [comment]
I just reopened it.  I think there's just that one issue to address.

**Comment by agiorla** [comment]
Thanks. I had a closer look at it. In the current version, it uses the post-processor, the function, or the `_tfunc_times` vector [which I am not sure what it corresponds to to be honest (it seems to be a list of instants defined by the user? I don't know this is pretty confusing)] to determine whether we reject the step. Do we need to restrict that just to the post-processor, to the post-processor and the function?
