### ISSUE TITLE
Create a post-processor to compute the product of other post-processors

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#11764]
## Rationale
As far as I know, there is no post-processor which computes the product of other post-processors.

## Description
This would add a post-processor to compute the product of other post-processors. For generality, this can include the following:
* arbitrary number of post-processors in the product
* scaling coefficient for the product
* value to add to the product

## Impact
No API change. Additional post-processor.

**Comment by permcody** [comment]
I don't think we have a general postprocessor that does this. You might consider making it even more general by just allowing users to pick their desired operator (*, +, etc).

**Comment by joshuahansel** [comment]
I'm thinking we just need `ParsedPostprocessor`, if that's feasible.

**Comment by joshuahansel** [comment]
`ParsedPostprocessor` is possible, but I just realized that `ParsedFunction` can use post-processor names in its parameter `vals`, so I think that this together with `FunctionValuePostprocessor` gives us all of the capability we need. Making `ParsedPostprocessor` would just combine the two, but I don't think that this is necessary, so I'll close this issue.
