### ISSUE TITLE
Add off-diagonal jacobian of phase-field fracture variable respect to displacements

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#11790]
## Rationale

We are using AllenCahn to solve phase field fracture equation, but we cannot automatically add off-diagonal term respect to displacements to existing AllenCahn system. We need to write a new separate kernel to calculate those terms.  

## Description

Improve the convergence behavior. 

## Impact

The convergence behavior of some related tests might change.

**Comment by permcody** [comment]
Closed by #11795
