### ISSUE TITLE
New Intel Compiler Diffs

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#11835]
## Rationale

The fixes in #11552 use new C++ syntax that our old version of the Intel compiler on the build boxes can't compile.  Therefore, we need to update the version of the intel compiler.  To do that we need to fix the diffs with the new version.

## Description

See above

## Impact

None - just fixing diffs with a new compiler

**Comment by permcody** [comment]
Support dropped in #12713 - closing for now.
