### ISSUE TITLE
Nodal Patch Recovery in Auxkernel

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#11880]
## Rationale
Currently nodal aux kernel cannot grab values that only live on qp, i.e. gradient, stress, strain etc.
From a framework standpoint, we want to provide users who need accurate nodal approximations of gradient / stress / strain for their algorithm.
From a visualization/postprocessing standpoint, nodal values will show a smooth field 

## Description
Currently if want those nodal values, we need to project them onto higher order monomials.
We propose here a different technique that uses a local element patch to fit nodal values. The fitted nodal value will be superconvergent and more accurate than those projected onto monomials.

## Impact
This will provide more accurate nodal values and better visualization of gradient fields.

**Comment by permcody** [comment]
Closed by #11881
