### ISSUE TITLE
Better command line parameter checking

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11906]
## Rationale

For example:

```
./mooseapp-opt -i input.i --n-threads=12
```

will run with 12 threads, while

```
./mooseapp-opt -i input.i --n-threads 12
```

will - without any complaints - run single threaded. :-(

## Description

It would be nice to catch at least the CLI argument moose is responsible for and throw an error if parameters are missing (I realize we pass unrecognized arguments right on to PETSc).

## Impact

Help users avoid CLI syntax errors.

**Comment by permcody** [comment]
This is really annoying but it's not a MOOSE problem. MOOSE's command line object reads both forms correctly. libMesh reads this value from the command line on it's own. We'll either need to patch libMesh, figure out a way to pass it in, or some other third thing...   Check out libMesh init.

Tag @roystgnr

**Comment by roystgnr** [comment]
Agreed that this is really annoying, agreed that it needs to be fixed at the libMesh level.  I guess what we need to do is to give GetPot a crazy default, via something like ```command_line_value("n_threads", -1)```, then if we're handed that default *back* we scream and die.  I'll see if that works.

**Comment by permcody** [comment]
I'm open to about any idea. I thought about changing how we call LibMeshInit or creating a mutator to change it after instantiation, but then I realized that pure libMesh users would still run into this issue so it would be better to fix it directly in libMesh. Anything is better than silently ignoring that common CLI variation.

**Comment by permcody** [comment]
Just confirmed that this issue is indeed closed after updating the libMesh submodule in MOOSE. Thanks!
