### ISSUE TITLE
Broken XDR files in recover tests (framework / modules)

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#11905]
## Rationale

I've just moved my workflow to a new computer and now see some framework-test failures.  Please close this if the failures are irrelevant for some reason.

## Description

multiapps/picard_failure.test CSV diffs:
^[[33mmultiapps/picard_failure.test: ^[[0m  --------- Time step 3, 1.5000000e-01 ~ 2.0000000e-01, rel diff: -2.50000e-01 (FAILED)
^[[33mmultiapps/picard_failure.test: ^[[0mGlobal variables:
^[[33mmultiapps/picard_failure.test: ^[[0m   elem_average_value  rel diff:  5.0911309e-01 ~  5.1174759e-01 = 5.14805e-03 (FAILED)
^[[33mmultiapps/picard_failure.test: ^[[0mNodal variables:
^[[33mmultiapps/picard_failure.test: ^[[0m   u  rel diff: -3.1285758e-02 ~  3.1942237e-02 = 1.97945e+00 (node 7)
^[[33mmultiapps/picard_failure.test: ^[[0m   v  rel diff:  5.1822619e-01 ~  5.2349519e-01 = 1.00650e-02 (node 2)

multiapps/picard_failure.test_csv CSV diffs:
mmultiapps/picard_failure.test_csv: ^[[0mIn picard_master_out_sub0.csv: The values in column "elem_average_value" don't match
^[[33mmultiapps/picard_failure.test_csv: ^[[0m  rel diff:  0.511747593203 ~ 0.509113093413 = 0.00514804529556
^[[33mmultiapps/picard_failure.test_csv: ^[[0mIn picard_master_out_sub0.csv: The values in column "time" don't match
^[[33mmultiapps/picard_failure.test_csv: ^[[0m  rel diff:  0.2 ~ 0.15 = 0.25
^[[33mmultiapps/picard_failure.test_csv: ^[[0mIn picard_master_out.csv: The values in column "time" don't match
^[[33mmultiapps/picard_failure.test_csv: ^[[0m  rel diff:  0.2 ~ 0.15 = 0.25

mmultiapps/picard_catch_up.test CSV diffs:
^[[33mmultiapps/picard_catch_up.test: ^[[0m   picard_its  rel diff:  7.0000000e+00 ~  5.0000000e+00 = 2.85714e-01 (FAILED)

materials/material_dependency.dont_reinit_mat_for_aux  CSV diffs:
^[[33mmaterials/material_dependency.dont_reinit_mat_for_aux: ^[[0m   mat_prop  rel diff:  3.0500000e+01 ~  2.6500000e+01 = 1.31148e-01 (block 0, elmt 1)

outputs/iterative.csv CSV diffs:
moutputs/iterative.csv: ^[[0mIn iterative_csv_out.csv: The values in column "iterations" don't match
^[[33moutputs/iterative.csv: ^[[0m      rel diff:  204.0 ~ 238.0 = 0.142857142857

## Impact

Increased number of platforms where the tests pass

**Comment by dschwen** [comment]
As posted on the ML, the error is triggered because a `*_mesh.cpr` item is a file rather than a directory. Here is a hexdump of one of those in one of my failing recover tests:

```
hexdump -C combined/test/tests/adaptive_timestepping/adapt_tstep_function_change_restart1_checkpoint_cp/0065_mesh.cpr
00000000  00 00 00 0e 63 68 65 63  6b 70 6f 69 6e 74 2d 31  |....checkpoint-1|
00000010  2e 32 00 00 00 00 00 00  00 00 00 08 00 00 00 03  |.2..............|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00              |............|
0000003c
```

**Comment by dschwen** [comment]
And here is a stack trace from that failure (test `combined/test:adaptive_timestepping.test_function_change_restart1`):

```
Error with file `adapt_tstep_function_change_restart1_checkpoint_cp/0065_mesh.cpr/1/header.cpr'
Stack frames: 15
0: 0   libmesh_opt.0.dylib                 0x000000010a7ffa68 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1256
1: 1   libmesh_opt.0.dylib                 0x000000010a7fb8b1 libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 273
2: 2   libmesh_opt.0.dylib                 0x000000010ae1be1e libMesh::Xdr::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 5182
combined/test:adaptive_timestepping.test_function_change_restart1: 3: 3   libmesh_opt.0.dylib                 0x000000010ae1a965 libMesh::Xdr::Xdr(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, libMesh::XdrMODE) + 101
4: 4   libmesh_opt.0.dylib                 0x000000010aa513a1 libMesh::CheckpointIO::write(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 305
5: 5   libmoose-opt.0.dylib                0x0000000109e4e8d7 Checkpoint::output(MooseEnumItem const&) + 647
6: 6   libmoose-opt.0.dylib                0x0000000109e6af8d Output::outputStep(MooseEnumItem const&) + 157
7: 7   libmoose-opt.0.dylib                0x0000000109e6d929 OutputWarehouse::outputStep(MooseEnumItem) + 89
8: 8   libmoose-opt.0.dylib                0x0000000109fa1f68 FEProblemBase::outputStep(MooseEnumItem) + 120
9: 9   libmoose-opt.0.dylib                0x0000000109cab3be Transient::endStep(double) + 222
10: 10  libmoose-opt.0.dylib                0x0000000109ca95dd Transient::execute() + 125
11: 11  libmoose-opt.0.dylib                0x000000010a16fed0 MooseApp::executeExecutioner() + 96
12: 12  libmoose-opt.0.dylib                0x000000010a170463 MooseApp::run() + 227
13: 13  combined-opt                        0x0000000109b7fb63 main + 163
14: 14  libdyld.dylib                       0x00007fff7610d015 start + 1
combined/test:adaptive_timestepping.test_function_change_restart1: [0] ../src/utils/xdr_cxx.C, line 176, compiled nodate at notime
combined/test:adaptive_timestepping.test_function_change_restart1:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
combined/test:adaptive_timestepping.test_function_change_restart1: [unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
combined/test:adaptive_timestepping.test_function_change_restart1: :
system msg for write_line failure : Bad file descriptor
```

**Comment by permcody** [comment]
So we do write both files and directories for checkpoint. The file version is the normal serialized checkpoint output file. The directory version is for splits. I have no idea how this got so hosed though!

**Comment by permcody** [comment]
Can you tell me if the --recover tests in MOOSE pass or fail? I want to know what might be causing this. It looks like it might be related to "xdr = true". Does it have anything to do with "checkpoint = true"?

**Comment by dschwen** [comment]
Looks like the `--recover` framework tests pass.

**Comment by WilkAndy** [comment]
My ```--recover``` tests also pass (apart from 11 of them).

a

**Comment by WilkAndy** [comment]
Oh, i may have spoken too soon.  On this new computer, I just pulled my ```ConservativeAdvection``` PR from github and what-do-you-know, lots of those tests fail with ```--recover```.  Please note, the error might be nothing to do with this Issue.

kernels/conservative_advection.none_in_all_out: Internal error in Transient executioner: _t_step is equal to 0 while recovering in init().

**Comment by permcody** [comment]
Just to be clear we are not currently testing --recover with the modules
because there are a large number of failures that will have to be gone
through. That's why I asked specifically about the moose test suite where
we know there shouldn't be any errors.

**Comment by WilkAndy** [comment]
Closing because something has changed: maybe MOOSE, or the system i was using, maybe something else.  Anyway, i can't get the framework tests to fail in recover now, so it's pointless to keep this issue open.
