### ISSUE TITLE
Create a post-processor to compare post-processors

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#11910]
## Rationale
The feature described below is useful for tests that require some equality or inequality on post-processor values.

## Description
This would create a post-processor that has similar functionality to `VectorPostprocessorComparison`, but it would be used to compare post-processors, not vector post-processors. That is, it is used to compare two post-processor values with a variety of different comparison options (==, >=, <=, >, <), all using a potentially "fuzzy" comparison. 

## Impact
Additional post-processor.

**Comment by andrsd** [comment]
![meme](https://i.imgflip.com/2eqpko.jpg)
