### ISSUE TITLE
Make contact work for 2D elements not in the xy-plane

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#11913]
## Rationale

Simulations involving contact in 2D are confined to the xy-plane as the outward normal between the contacting surfaces used for determining the contact point and detecting penetration is hardcoded as the cross product between `dxyz_dxi[0]` and the out of plane normal to the xy-plane `0 0 1`  resulting in the normal for contact being the hardcoded line below:

`normal = RealGradient(dxyz_dxi[0](1), -dxyz_dxi[0](0))`

To enable simulations in the xz-plane, yz-plane or any other plane the out of plane normal to the 2D elements needs to be used such that the normal becomes:

`normal = dxyz_dxi[0].cross(out_of_plane_normal)`

## Description

Make the calculation of the outward normal between the master and slave contacting surfaces for 2D elements more general in FindContactPoint.C and PenetrationThread.C.

## Impact

New capability. Ability to run 2D simulations with contact that are not in the xy-plane.  Existing tests for xy-plane will run as before.

**Comment by gambka** [comment]
The above changes only get thermal contact working in arbitrary planes.  Additional work is required for the constraints in mechanical contact before the patch will be ready.

**Comment by permcody** [comment]
Closed by #12441.

**Comment by gambka** [comment]
@permcody I got thermal contact working but I never did get the mechanical contact work and priorities changed and it would be a nice feature but not high priority right now. You can keep it closed if you want and  new issue made if it is revisited.
