### ISSUE TITLE
RangeChecked param does not work for unsigned int & param_name > 0

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#11919]
## Rationale
adding a range checked `unsigned int` parameter with check `param_name > 0` does not do the right thing. 
See 76898065aa383a05b71a39da940f8c431462bfb5

## Description
`rangeCheck()` grabs the parameter first, making `-1 -> 4294967295` which then passes the check. 

## Impact
Should be fixed, but I don't know what the best way of doing it us.

**Comment by snschune** [comment]
@lee7632

**Comment by permcody** [comment]
Ok, but checking that an unsigned int is always greater than zero is always
true anyways! This is a common problem that people don’t really consider.
It’s better to check not equal to zero. See if that works.

**Comment by permcody** [comment]
Oh... hang on... Never mind. That only applies to >= 0. This should be
fixable

**Comment by snschune** [comment]
What I'd like to use `RangeCheckedParam` for is to prevent misuse of an unsigned int parameter that must be non-negative but is set to a negative number. It's hard to check unless you read an int, check that and then cast it to unsigned int internally; that's clunky . Motivated by #11794.

**Comment by snschune** [comment]
Actually, `RangeCheckedPAram` is not the right thing to use for that. We should specialize `getParam<unsigned int>` to do that check because it will result in undesired behavior almost all the time to provide a negative number to an `unsigned int` parameter.

**Comment by jmeziere** [comment]
@permcody @snschune When implementing this, should we throw an error if the number is too large, or go with the route previously suggested of reading it in as an int, checking if it is negative, and then converting it to an unsigned int?

**Comment by permcody** [comment]
Ideally the implementation should handle all possible "unsigned ints" but as you've seen with the discussion the only way to do that is to use a 64-bit type because "int" can only represent half of the positive range. I'd be satisfied if it worked for handling negative numbers OK. It's funny how difficult these things can be. BTW - there are existing utility routines for reading and converting numbers in MooseUtils.h. There are a lot of edge cases to something that you'd think should "just work".

**Comment by dschwen** [comment]
The best approach would be to determine if the number is negative _before_ it is parsed into a number type! It may be as simple as checking if it has a leading `-`.

**Comment by GiudGiud** [comment]
Closing
This was fixed, in that rangeCheckedParam are no longer necessary for unsigned int, in https://github.com/idaholab/moosetools/pull/39
