### ISSUE TITLE
Single-phase fluid properties need interface for molar mass

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#11930]
## Rationale
Molar mass for a fluid is an important property that is useful anytime a conversion from mass to moles is needed. This is particularly important in the computation of transport properties in some models, for example, some mixture models.

## Description
This would add a required interface `molarMass()` (not dependent on fluid state - it is a fluid-dependent constant) to `SinglePhaseFluidProperties` to return the molar mass of the fluid.

## Impact
New required interface for classes deriving from `SinglePhaseFluidProperties`.

**Comment by andrsd** [comment]
Closed by #11951
