### ISSUE TITLE
GrainTracker crashes if no features are found

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11943]
## Rationale

In debug the following assertion is hit:
```
Assertion `!_feature_sets.empty()' failed
Feature sets empty!
at /Users/schwd/Programs/moose/modules/phase_field/src/postprocessors/GrainTracker.C, line 385
```

## Description

We'd like GrainTracker to deal with this case more gracefully. A scenario that we need is the nucleation of grains from a melt pool. At t=0 only liquid (no grains, all OPs are zero) are present. This currently causes the GrainTracker to throw up.

## Impact

Added capability. Tagging @amjokisaari

**Comment by permcody** [comment]
I feel like I'm being trolled.  The GrainTracker fails if there are no grains 🤣 

OK, I'm sure it's fixable

**Comment by dschwen** [comment]
Duplicate of #12200. Closing the older one as the newer one is being referenced.
