### ISSUE TITLE
MooseDocs does not alphabetize between different sources

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#11940]
## Rationale

In RELAP-7 docs, which include framework docs, the lists of objects for each syntax are listed alphabetically for their respective source (RELAP-7 and MOOSE) and then these alphabetized lists are listed after one another, instead of alphabetizing the entire (RELAP-7 + MOOSE) list. For example, I see:
```
ARELAP7
BRELAP7
DRELAP7
CMOOSE
EMOOSE
```
instead of
```
ARELAP7
BRELAP7
CMOOSE
DRELAP7
EMOOSE
```
This makes it more difficult to find a particular object. It would also be fine if instead of mixing the lists, some kind of separator, perhaps with a small label denoting each source, appeared between the alphabetized lists.

## Description

(See above)

## Impact
Easier navigation in MooseDocs.

**Comment by joshuahansel** [comment]
@andrsd

**Comment by andrsd** [comment]
You wanted to tag @aeslaughter  :-)

**Comment by joshuahansel** [comment]
Oops, I wanted to tag both of you. I included you just to let you know, in case you have wanted the same.

**Comment by andrsd** [comment]
I write the code, I do not have to read docs :-)
