### ISSUE TITLE
Unclear distance metric reported by GrainTracker

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#11954]
## Rationale

Upon remapping GrainTracker reports info like this:

```
- Depth 0: Remapping grain #10 from variable index 7 to 4 whose closest grain (#9) is at a distance of 114725
```

A "distance" of 114725 is confusing given that the simulation cell is just 1000x1000. Are you missing a `std::sqrt()` here?

## Description

The grain to grain distance reported upon remapping is confusing.

## Impact

Improve diagnostic output.

**Comment by permcody** [comment]
I purposely don't use sqrt() because of how slow it is. Overlapping values are handled separately so the square root isn't necessary to differentiate positive values. However, it's reasonable to report the sqrt when printing...
