### ISSUE TITLE
change terminology in DiscreteNucleationInserter and associated documentation

### ISSUE THREAD

**Issue by amjokisaari** [idaholab/moose#11959]
## Rationale

The DiscreteNucleationInserter (phase field module nucleation) takes an input parameter called "probability" which is confusing and not in line with the literature.  

This "probability" is actually a nucleation rate density.  See J. W. Christian, The theory of transformations in metals and alloys, Pergamon Press, 1975; J. P. Simmons et al., Mat. Sci. Eng. A 365 (2004) 136-143; A. M. Jokisaari, Multiphysics phase field modeling of hydrogen diffusion and delta-hydride precipitation in alpha-zirconium, University of Michigan, 2016.  

## Description

Changing the terminology of "probability" to "nucleation rate density" will bring the code in line with the existing literature, simplify understanding for users and alleviate confusion.

The code calculates the real probability in the execute() function as P = nucleation rate * dt * dv.  You may also wish to update this to remove the linearized form and replace it with P = 1 - exp(-nucleation rate density * dt * dv).  

## Impact

Test input files and documentation will need to be updated.

tagging @dschwen

**Comment by andrsd** [comment]
Please, do not edit the template. It is there to satisfy our SQA requirements. Thanks!

**Comment by dschwen** [comment]
This was done in 53c6265
