### ISSUE TITLE
l_abs_step_tol is completely broken

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#11970]
## Rationale
If the user supplies any positive number for `l_abs_step_tol` in `Executioner`, linear solves always converge in 1 iteration, even if the linear solve is nowhere even close to convergence.

Furthermore, the check in `FEProblemBase::checkLinearConvergence` is completely wrong anyway; it does
```
| ||r^{old}|| - ||r^{new}|| | < l_abs_step_tol
```
This is just wrong. For instance, the two residual vectors could be very different, yet have the same norms, so step convergence would be detected falsely.  The correct implementation is
```
||r^{old} - r^{new}|| < l_abs_step_tol
```

## Description
In `FEProblemBase::checkLinearConvergence`, print out `rnorm` and `system._last_rnorm`. You'll see that on the second call to this function in each linear solve, `rnorm` and `system._last_rnorm` are exactly equal, which seems to suggest that `system._last_rnorm` is updated with the new `rnorm` *before* calling this function.

There appears to be only 1 input file in MOOSE where `l_abs_step_tol` is even used: `modules/combined/examples/mortar/mortar_gradient.i`. You'll notice that those linear solves converge in 1 iteration.

## Impact
Fix broken linear convergence monitoring.

**Comment by YaqiWang** [comment]
Has this defect been fixed? We had a users asking questions about this parameter.

**Comment by joshuahansel** [comment]
As far as I know, no one has fixed this.

**Comment by joshuahansel** [comment]
What is happening is this: PETSc does the linear convergence check, and then MOOSE does its own linear convergence check afterward, which can potentially modify that convergence flag. MOOSE's linear convergence check (`FEProblemBase::checkLinearConvergence`) has some serious brain damage regarding `l_abs_step_tol`: it always converges if `l_abs_step_tol` is positive (its default value is negative, so this only happens if the user provides this parameter). I talked to @permcody and @fdkong about this, and Cody says MOOSE convergence checking is stupid and should be removed. He suggested that Fande could do it when he has time. For a quick fix, I think it would be fine just to remove the following lines from `checkLInearTolerance`:
```
  if (std::abs(rnorm - system._last_rnorm) < system._l_abs_step_tol)
    reason = MooseLinearConvergenceReason::CONVERGED_RTOL;
```
Then PETSc's convergence flag would be respected.
