### ISSUE TITLE
MultiApp PerfGraph may not show up

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#11973]
## Rationale

This is my suspect based on my understanding.

## Description

This part of the code 
https://github.com/idaholab/moose/blob/devel/framework/src/executioners/Transient.C#L382-L388
looks like will be never called in a `TransientMultiApp`.

However, if we put it into `postExecute`, it will be called through `FEProblemBase::postExecute`. So I am suggesting move the code into `postExecute` in `Transient`. We may want to do the same for `Steady` for consistency although `FullSolveMultiApp` does not have the issue.

## Impact
Better user experience.

**Comment by permcody** [comment]
Closed by #12672.
