### ISSUE TITLE
Bug with material property initialization and threads

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#11995]
## Rationale

A Bison test initializes a material property to a nonzero value and reports the constant monomial representation of that property at the initial state.  The reported value with two threads is half that of the correct value without threads.

## Description

This seems to be corrected with `Threads::parallel_reduce(elem_range, cmt);` immediately after `cmt(elem_range, true);` in FeProblemBase.C.

## Impact

Consistent behavior when using threads.

**Comment by permcody** [comment]
So you already have a fix? Can you submit a PR? Your description of the fix sounds accurate to me.

**Comment by jasondhales** [comment]
It looks like with threading the material properties are not ready for use following the call to initQpStatefulProperties but are following a call to computeQpProperties.  In the Bison test, a material was checking for the first step in computeQpProperties and skipping calculations if it was the first step.  I've changed the Bison material, and it works now without the change to FeProblemBase.C.

So, I'm not sure if the behavior in MOOSE is what is intended, but I have it working.  I'm closing the issue.
