### ISSUE TITLE
Allow actions to set problem type

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12002]
## Rationale

Currently there are two ways of setting FEProblem type: either through `Problem/type` input parameter or based on the executioner type if `Problem` input block is missing. The relevant actions are `CreateProblemAction` and `DetermineSystemType` actions. It is desired to provide developers another way of setting FEProblem type though actions. It is useful when developers create new FEProblem types and do not want users to explicitly set the FEProblem type in the input.

## Description

The big issue is that `DetermineSystemType` creates `CreateProblemAction` in its `act()` only when `Problem` input block is missing, thus gain the control of setting the type programatically. If users have to set another parameter in `Problem`, users will be forced to set the type correctly (error will be thrown otherwise).

I am suggesting to let MOOSE always add `CreateProblemAction`. We can provide a mutating function like `CreateProblemAction::resetProblemType(const std::string & newtype)` with code like
```
  {
    _type = newtype;
    if (!_skip_param_construction)
    {
      _moose_object_pars = _factory.getValidParams(_type);
      _moose_object_pars.blockLocation() = _pars.blockLocation();
      _moose_object_pars.blockFullpath() = _pars.blockFullpath();
      _app.parser().extractParams(_pars.blockFullpath(), _moose_object_pars);
      _moose_object_pars.set<std::vector<std::string>>("control_tags")
          .push_back(MooseUtils::baseName(_pars.blockFullpath()));
    }
  }
```
mimic what `Parser` is doing. The above code can be even in `MooseObjectAction` although we do not have to be that aggressive. In this way, any action including `DetermineSystemType` can reset the problem type programmatically.

Another solution is to let `CreateProblemAction` be an action created by another action (maybe just `DetermineSystemType`) but not the parser, whose `type` parameter can be changed by other actions.

## Impact
No impact on MOOSE side. Adding new capability. Cleaner code logic.

**Comment by permcody** [comment]
Thanks for working on this. I actually may need this myself so I'm interested in making sure it's been implemented correctly. I will look at this tomorrow (8/24).
