### ISSUE TITLE
Typo in preconditioning options?

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#12016]
## Rationale

Not sure if this is supposed to be there or not, but one of the options in `petsc_options` in the preconditioned block is `-snew_ksp_ew`. I know that `-snes_ksp_ew` (which is also one of the options) is a flag that is used by petsc, but not sure that `-snew_ksp_ew` is.

## Description

See above.

## Impact

Possible invalid option. Of course, it might be valid, in which case feel free to close this one.

**Comment by andrsd** [comment]
`-snew_ksp_ew` is not a valid option. The pattern used in PETSc is that the first group refers to a PETSc systems. It would be things like `PC`, `SNES`, `KSP`, etc. So, `snew` is a typo and it would be save to remove it, or you can try to fix the typo a see if the convergence improves.

**Comment by cpgr** [comment]
Yeah, I thought it must be a typo, but just wanted to check first. `-snes_ksp_ew` is also in the list, so we can just remove the `-snew_ksp_ew` one from here:

https://github.com/idaholab/moose/blob/474ba7209e8bdbd13a511f9c6725275a51cf6624/framework/src/utils/PetscSupport.C#L859-L865

and replace it in any input files (I can only see it used in a couple).
