### ISSUE TITLE
Stateful Material Properties don't play nicely with NodalPatchRecovery

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#12036]
## Rationale

The nodal patch recovery addition to MOOSE (PR #11881) uses information from surrounding elements to calculate a patch value of a material property, ect, at the node. When running in parallel, the nodal patch needs to access material properties off processor. In codes that use stateful old material properties, where the old material properties are not initialized for off processor elements, the use of nodal patch recovery with these plasticity codes causes a seg fault.

## Description

The attached input file will throw an error after the timestep_end when run in parallel with two procs because the code takes the inverse of an old Rank-2 material property: (`mpiexec -n 2 ~/projects/moose/modules/tensor_mechanics/tensor_mechanics-dbg -i crysp_patch_recovery_debug.i`)
[crysp_patch_recovery_debug.i.zip](https://github.com/idaholab/moose/files/2319129/crysp_patch_recovery_debug.i.zip)

@permcody identified `ComputeMaterialsObjectThreads` as the routine to be expanded to include the layer of elements used by the nodal patch recovery. Tagging @fdkong for implementation help, fyi @laagesen 

## Impact

Extended use of the nodal patch recovery capability with complicated plasticity models when run in parallel.

**Comment by fdkong** [comment]
Could you send` input_slip_sys.txt` as well?

**Comment by sapitts** [comment]
@fdkong I'm sorry about the bad file.  Here's a new zipped folder with an input file that I've made sure runs and the text file you need for the problem. 
[debug_test.zip](https://github.com/idaholab/moose/files/2319824/debug_test.zip)

**Comment by sapitts** [comment]
@bwspenc and @permcody, I ran the nodal patch recovery with a finite strain problem (the current regression test uses small strain which doesn't have old properties and didn't see this problem).  Running this finite strain problem, input file attached ( [patch_finite_stress.i.zip](https://github.com/idaholab/moose/files/2319885/patch_finite_stress.i.zip) ), in serial and with two procs produces different results (on mac):

```
Sideset Distribution Factors:
  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
Nodal variables:
  --------- Time step 2, 1.0000000e-02 ~ 1.0000000e-02, rel diff:  0.00000e+00 ---------
Nodal variables:
   disp_x               rel diff:  1.5394023e-20 ~  6.8177187e-20 = 7.74206e-01 (node 3)
  --------- Time step 3, 2.0000000e-02 ~ 2.0000000e-02, rel diff:  0.00000e+00 ---------
Nodal variables:
   disp_x               rel diff: -3.1451793e-19 ~ -6.6134124e-21 = 9.78973e-01 (node 3)
   stress_xx_recovered  rel diff:  1.0009265e+03 ~  7.4931018e+02 = 2.51383e-01 (node 3)
   stress_yy_recovered  rel diff:  4.9963470e+03 ~  3.7412505e+03 = 2.51203e-01 (node 3)
  --------- Time step 4, 3.0000000e-02 ~ 3.0000000e-02, rel diff:  0.00000e+00 ---------
Nodal variables:
   disp_x               rel diff:  1.0802020e-19 ~  9.1769791e-20 = 1.50439e-01 (node 3)
   stress_xx_recovered  rel diff:  1.4950803e+03 ~  9.9398203e+02 = 3.35165e-01 (node 3)
   stress_yy_recovered  rel diff:  7.4570146e+03 ~  4.9594761e+03 = 3.34925e-01 (node 3)
  --------- Time step 5, 4.0000000e-02 ~ 4.0000000e-02, rel diff:  0.00000e+00 ---------
Nodal variables:
   disp_x               rel diff:  6.2651365e-19 ~  4.6483175e-20 = 9.25807e-01 (node 3)
   stress_xx_recovered  rel diff:  1.9850892e+03 ~  1.2366198e+03 = 3.77046e-01 (node 3)
   stress_yy_recovered  rel diff:  9.8933375e+03 ~  6.1657595e+03 = 3.76777e-01 (node 3)
  --------- Time step 6, 5.0000000e-02 ~ 5.0000000e-02, rel diff:  0.00000e+00 ---------
Nodal variables:
   disp_x               rel diff: -5.5176049e-19 ~ -1.9809075e-18 = 7.21461e-01 (node 3)
   stress_xx_recovered  rel diff:  2.4709998e+03 ~  1.4772460e+03 = 4.02167e-01 (node 3)
   stress_yy_recovered  rel diff:  1.2305792e+04 ~  7.3603322e+03 = 4.01881e-01 (node 3)
```

The first file in the comparison is the serial run and the second file is the parallel run. 
The displacements are quite small in absolute value and the recovered stress values are calculated with the nodal patch recovery option. That the `disp_y`, which is the variable actually being loaded, does not show up as an exodiff and that the monomial values of `stress_xx` and `stress_yy` are the same is reassuring.

I'll still work on putting in an error message for the nodal patch recovery to error out when running in parallel--unless @fdkong  gets a solution to the crystal plasticity problem into Moose before I figure out the error message :-)

**Comment by sapitts** [comment]
@fdkong How is the effort to expand the stateful properties loop going? Is there a branch I could grab to try the patch with my model?

**Comment by permcody** [comment]
Currently waiting on a Patch from Roy. There's a known issue in the iterator that we want to use. Gary's stuff is basically a no go. It's not going to work robustly because of object creation order. We really need to rely on the RelationshipManager system, which is close but needs that other patch. What's your time-frame all this? I know "yesterday" would be ideal, but there's a lot of machinery here. We might be able to come up with some ugly hacks if you need something a little faster...

**Comment by sapitts** [comment]
Dang it :( I'd really like to have access to this functionality mid-September; I have something due mid October and my runs take up to two weeks to complete

**Comment by YaqiWang** [comment]
It is not ideal, but you can convert stateful properties to aux variables first. If there was shape functions defined with quadrature points (some people call it self-lumping shape functions), the expansion coefficients or values in the solution vector would just be the values on quadrature points. Even this is not available, you can use an elemental variable with a little higher order for the conversion.

**Comment by permcody** [comment]
Just talked to @sapitts - She says she needs nonlocal information too (neighbor element) information so it's slightly more involved. @fdkong and I are going to see if we can come up with a general user object that will cache element ranges that keep the extra elements needed (looks like the old semi-local range) where she can perform these calculations. The RelationshipManager _should_ also be active but probably isn't necessary if she's only one element off from the local set. Thanks for the input @YaqiWang - hoping we can come up with something and improve MOOSE at the same time.

**Comment by hugary1995** [comment]
Sad... Let me know if I can do anything to help.

**Comment by fdkong** [comment]
@hugary1995 We fixed in https://github.com/fdkong/moose/commit/9bb2bced5e742518414cba935802b5388a125d95
