### ISSUE TITLE
Merge SinglePhaseFluidProperties and SinglePhaseFluidPropertiesPT

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#12050]
## Rationale

We want to provide single interface to obtain fluid properties. No matter what equation set is being solved, users should be able to pull in the interface and interrogate it to obtain needed quantities. Currently they need to obtain the one or another based on their primary variables.

## Description

There will be several steps to achieve this:

1. Merge the PT version in non-PT version. The PT base class will inherit from the non-PT and will print a deprecated message to inform people to change their base class.
2. Update `porous_flow` module
3. Update apps
4. Update the API to conform to the naming standard in `SinglePhaseFluidProperties`, i.e. X_from_Y_Z(Y, Z)
5. Update doco

## Impact

Simplified access to fluid properties. Class hierarchy change. The steps should prevent any breakage.

**Comment by andrsd** [comment]
Tagging @WilkAndy @cpgr @aprilnovak @joshuahansel

**Comment by WilkAndy** [comment]
Cool, thanks for doing this @andrsd

**Comment by cpgr** [comment]
Yeah, thanks @andrsd.

**Comment by andrsd** [comment]
@veeshy @WilkAndy @cpgr  The 1. stage is in `devel` now and there is a breaking change (unfortunately). If you are using `cp`, `cv` in your `FluidProperties`-derived classes, to fix it, you have to rename them to `cp_from_p_T` and `cv_from_p_T` and fix all the call.

**Comment by andrsd** [comment]
Also, if you could ping me when your code is patched, so I can proceed with stage 2.

**Comment by cpgr** [comment]
I'm not using them, so am ready for you to proceed.

**Comment by WilkAndy** [comment]
I presume you're not talking about PorousFlow/other parts of MOOSE, but our Apps.  If so, then i'm not using those, so am ready for you to proceed.

**Comment by veeshy** [comment]
I'll be waiting until you finish your process, we usually stay on a devel a little behind the actual one and it'll be easiest to get up to date once you're happy with the fp class

**Comment by lcarasik** [comment]
> I'll be waiting until you finish your process, we usually stay on a devel a little behind the actual one and it'll be easiest to get up to date once you're happy with the fp class

We've resolved any issues associated with this, you don't have to worry about us before you move forward.

**Comment by andrsd** [comment]
This is done as far as I can tell.
