### ISSUE TITLE
PorousFlowCapillary UserObjects should inherit from DiscreteElementUserObject

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#12057]
## Rationale

Currently these UserObjects inherit from GeneralUserObject, and they compute things like capillary pressure, saturation, etc.  However, now we have a user who wants to include user-defined Functions in their derived PorousFlowCapillary class.  So the PorousFlowCapillary must know something about the (x,y,z,t) point where the various functions (capillary pressure, saturation, etc) are being evaluated.  This will be possible if they inherit from DiscreteElementUserObject, and no other changes to PorousFlow are needed.

Later, the user thinks they might also want to use coupledVariables in their derived PorousFlowCapillary class.  This will mean some changes are needed to some PorousFlow Material classes, as the Materials will need to pass the quadpoint to the PorousFlowCapillary, so that it knows at which quadpoint to evaluate those coupledVariables.  This extension will *not* be made in this Issue, but i wanted to mention it in case it's pertinent to the above paragraph.

## Description

```PorousFlowCapillaryPressure``` inherits from ```DiscreteElementUserObject``` instead of ```GeneralUserObject```

## Impact

No impact on tests or other users, except it allows more flexibility in writing custom PorousFlowCapillary classes

**Comment by WilkAndy** [comment]
Tagging @cpgr

**Comment by WilkAndy** [comment]
We've realised that more is needed for @MarinaGrimm to be able to implement her requirements. We need to have _qp passed through to the public capillaryPressure (etc) methods. I've decided to implement this using a default argument value, such as

Real capillaryPressureCurve(Real saturation, unsigned qp = 0)
I toyed with the idea of overloading just the capillaryPressure method: one version would have just the Real saturation argument, while the other version would have Real saturation, unsigned qp. This requires less code changes, but it would require more regression tests to be created, and would always "sit off the side of PorousFlow".

**Comment by WilkAndy** [comment]
As part of this Issue, I'm going to change PorousFlowBrineCO2 (as that's what @MarinaGrimm is interested in) and its associated Material, to allow for quadpoint-dependent capillarity.

**Comment by andrsd** [comment]
If you are planning on doing this:
```
virtual Real capillaryPressureCurve(Real saturation);
virtual Real capillaryPressureCurve(Real saturation, unsigned int qp);
```
It won't work, you cannot overload virtual methods like this. They would have to have different return type. But you could name the other method like `capillaryPressureCurveQp` and you would be fine. Just a heads up.

**Comment by andrsd** [comment]
Also, having the second one as:
```
Real capillaryPressureCurve(Real saturation, unsigned qp = 0)
```
is a no go, because compiler will give you an error when you do:
```
a.capillaryPressureCurve(s);
```
it would not know which version to call.

**Comment by WilkAndy** [comment]
I get it, thanks @andrsd 

a

**Comment by andrsd** [comment]
Yeah, I know you do. I replied to this before I actually see what you did in your PR :-)
