### ISSUE TITLE
Allow ReferenceResidualProblem to group some variables together to check convergence

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#12053]
## Rationale

ReferenceResidualProblem is able to check the convergence of the solution norm of each variable against a reference residual. For some cases, we might want to group several variables together to check their grouped solution norm, such as to group all the displacements. Another case is for a problem which has a number of scalar variables. It makes more sense to group all the scalar variables together instead of checking a single solution number for each variable. 

## Description

Add a new capability to allow users to specify which variables they want to grouped together in the ReferenceResidualProblem. 

## Impact

The change should be backwards compatible and does not affect any existing tests.

**Comment by lindsayad** [comment]
Seems like this was closed by #12069...?
