### ISSUE TITLE
Move MatDiffusion from Phase field module to framework

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#12074]
## Rationale

The MatDiffusion implements a diffusion kernel with a mobility that can vary spatially and can depend on variables in the simulation. It is generic and seems to be reasonable to move this kernel from phase field to framework.

## Description

After moving this kernel to framework, all the modules can use it without the dependence on phase field module. 

## Impact

No effect.

**Comment by jiangwen84** [comment]
@dschwen @bwspenc I just found we have a simpler version MatDiffusion exists in framework/test/src/kernel/MatDiffusion.C I am not sure if we should just move that one to framework/kernels or do something else?

**Comment by jiangwen84** [comment]
forgot to tag @permcody  any suggestions?

**Comment by jiangwen84** [comment]
@andrsd If I am going to rename the MatDiffusion in the test folder, do you have any preference about the name? `MaterialDiffusion`, `IsotropicDiffusion`, `TestDiffusion`? Thanks!

**Comment by dschwen** [comment]
@andrsd we are aware of the fine line, however the MatDiffusion Kernel turned out to be of interest to modules other than phase field. Maybe it is time to again think about a "common" module?

**Comment by YaqiWang** [comment]
This will be a fun conversation. To add some oil, I suggest to rename current `Diffusion` to `Stiffness` for education purpose and copy `MatDiffusion` to `Diffusion`. My argument is that diffusion must have a diffusion coefficient. I also suggest to merge `FuncDiffusion`, `CoefDiffusion` into `Diffusion`.

**Comment by andrsd** [comment]
Ok, `Diffusion` was not the best example, `TimeDerivative` is probably better. My point is that this was the point were the discussion stopped the last time we had it. And we did not get to any resolution. I would like to see a good solution to this - do not get me wrong...

**Comment by lindsayad** [comment]
@friedmud might have an opinion on this... 🔥🔥🔥

**Comment by friedmud** [comment]
I’m fine with having MatDiffusion in the framework. Leave Diffusion alone.

**Comment by permcody** [comment]
Closed by #12080.
