### ISSUE TITLE
--use-split shouldn't uniform_refine the mesh

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#12084]
## Rationale

The pre-split versus online split behavior should be the same when using MOOSE. At least one mesh block parameter is going to get run once, there may be others and this shouldn't be happening.

## Description

If you have `Mesh/uniform_refine=<n>` in your mesh file, it will get run TWICE, once during `--split-mesh` and once during `--use-split`. This will definitely give you different behavior if you are running a distributed mesh problem with and without splits. 

## Impact

Makes MOOSE less user friendly if modifications to the input file are required to obtain the same results between different modes of operation (that should otherwise be the same).

**Comment by friedmud** [comment]
Yeah - definitely not right... and not intentional.

**Comment by friedmud** [comment]
@rwcarlsen do you think you might have some time to fix this?

**Comment by rwcarlsen** [comment]
I can take a look.
