### ISSUE TITLE
MultiSmoothSuperellipsoidIC segmentation fault fix

### ISSUE THREAD

**Issue by FHilty** [idaholab/moose#12092]
## Rationale

When semiaxis_variation_type is set to "none" but semiaxis_a/b/c_variations are not provided a segmentation fault is produced from an error message's logical statement attempting to access an element in an empty vector. 

## Description

The logical statement to trigger the error message was changed to check the size of the semiaxis_a/b/c_variation vector rather than the value of an element in the vector, preventing the Segmentation Fault error. Additionally the 3 statements were combined into one and the message was changed to a Warning instead of an Error. It is now a Warning because the IC performs without any problems if semiaxis variation values are provided but disabled with the semiaxis_variation_type bool. This check is just to remind the user that a type needs to be provided for the variations to be applied.

Unrelated to the segmentation fault problem, a variable's description and an error message were corrected for clarity and accuracy. 

## Impact

This change does not modify the performance of the IC, besides eliminating a possible Segmentation Fault.

**Comment by FHilty** [comment]
Could someone shed some light on why all the tests are failing with Failed Dependencies? The details for each test are not giving me any information about the cause.

**Comment by permcody** [comment]
All of the recipes depend on the "pre_test" which contains are basic code checks and formatting. We don't actually compile and run until the pre_test passes. That's all the "failed dependencies" message is saying. In your case, you just need to "clang-format" your code. You can download the appropriate formatting patch in the pre-check output:
https://civet.inl.gov/job/228487/
