### ISSUE TITLE
KaTeX equation numbering when using with Include extension

### ISSUE THREAD

**Issue by cbolisetti** [idaholab/moose#12121]
## Rationale

When documentation files with equations are included, and these equations are referenced inline, the references do not show the correct equation numbers.

## Description

file1.md 
```
\begin{equation}
\label{eqn1}
\zeta &= \frac{\xi_t}{2 \pi} \; \frac{6}{(\Delta f)^3} \; [b(f_1,f_2) - a(f_1, f_2) \; f_1 f_2] \\
\eta &= 2 \pi \xi_t \; \frac{2 f_1 f_2}{(\Delta f)^3} \; [a(f_1, f_2)\; ({f_1}^2 + {f_2}^2 + f_1 f_2) - 3 b(f_1, f_2)]
\end{equation}

\begin{equation}
\label{eqn2}
\zeta &= \frac{\xi_t}{2 \pi} \; \frac{6}{(\Delta f)^3} \; [b(f_1,f_2) - a(f_1, f_2) \; f_1 f_2] \\
\eta &= 2 \pi \xi_t \; \frac{2 f_1 f_2}{(\Delta f)^3} \; [a(f_1, f_2)\; ({f_1}^2 + {f_2}^2 + f_1 f_2) - 3 b(f_1, f_2)]
\end{equation}

[eqn1] and [eqn2] are the same.
```

file2.md
```
\begin{equation}
\label{eqn1}
\zeta &= \frac{\xi_t}{2 \pi} \; \frac{6}{(\Delta f)^3} \; [b(f_1,f_2) - a(f_1, f_2) \; f_1 f_2] \\
\eta &= 2 \pi \xi_t \; \frac{2 f_1 f_2}{(\Delta f)^3} \; [a(f_1, f_2)\; ({f_1}^2 + {f_2}^2 + f_1 f_2) - 3 b(f_1, f_2)]
\end{equation}

!include file1.md
```

file2 would now have three equations numbered 1, 2, and 3 (2 and 3 being from file1). File 2 will now show 

> Eq1 and Eq2 are the same.

while it should be

> Eq2 and Eq3 are the same.

## Impact
Will change numbering in equation references in documentation when Include and KaTeX extensions are used together. The equation numbering itself currently works as expected.

**Comment by aeslaughter** [comment]
fixed in #12528
