### ISSUE TITLE
tanh interfaces for smooth circle ICs

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12143]
## Rationale

Add an option to select the functional form of the interface profile generated by the family of initial conditions that derive from `SmoothCircleBaseIC` (which should actually be called `SmoothCircleICBase`!).

## Description

With a very pinpointed addition we can improve a whole group of ICs. The equilibrium interfacial profile for some phase field problems is known to be of a hyperbolic tangent shape. Providing this in the initial condition would allow users to seed (near) equilibrium configurations.

Ping @laagesen 

## Impact

Added capability.

**Comment by permcody** [comment]
BASE CLASS!

**Comment by dschwen** [comment]
![tanh_sin](https://user-images.githubusercontent.com/202302/45697221-89347a00-bb22-11e8-9dfc-e284751e9ff0.png)

The purple curve shows a tanh profile and the green curve shows the current sine default.

**Comment by dschwen** [comment]
I have introduced a scaling that keeps the interface widths comparable.
