### ISSUE TITLE
Automate Grand Potential parameter computation

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12147]
## Rationale

To select a specific interfacial width and energy the user has to go through a complex manual procedure. We should automate this by creating a `GrandPotentialMaterial`

## Description

The procedure involves inverting a function that is not analytically invertible, selecting a median interfacial energy, and computing material constants for each phase. We can automate the function inversion using bisection, determine the median free energy automatically, and generate the necessary material properties.

## Impact

Simplify use of the Grand Potential model.

Tagging @laagesen

**Comment by laagesen** [comment]
This is a great idea. One thing I wanted to mention is that the analytical approximation function that lets you get gamma as a function of g is limited in the range of g it's valid for. This is something that Pierre-Clement noticed. I can help look in to the range of validity.

**Comment by dschwen** [comment]
We could use the analytical approximation to obtain an initial guess. But I suspect that if we do a numerical inversion by doing bisection search we won't really need the approximation (this is only done once during setup, so speed is not crucial). Correct me if I'm missing something here (for example if _g_ is not monotonous!)
