### ISSUE TITLE
Failed assert with 1D mesh and ElementalVariableValue

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#12165]
## Rationale
[Archive.zip](https://github.com/idaholab/moose/files/2402751/Archive.zip)

The attached input file crashes with a failed assert but runs fine opt:

Assertion `_current_subdomain_id == _current_elem->subdomain_id()' failed
current subdomain has been set incorrectly
at /Users/halejd/gitProjects/bison/moose/framework/src/base/Assembly.C, line 714

## Description

This runs in debug if the Postprocessors are removed.

## Impact

Run properly in debug.

**Comment by permcody** [comment]
Thanks! I don't believe that assert is over-zealous, it's definitely catching a potential problem here. We probably need to fixup a different threaded loop to make sure that value is properly synchronized.

**Comment by YaqiWang** [comment]
I changed this. Right, if we had a test, we would capture this failure long ago. Thanks Cody.
