### ISSUE TITLE
Make computeResidual and computeJacobian simple

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12188]
## Rationale

It is likely that users will override `computeResidual` and `computeJacobian` in their derived Kernels, BCs, DGKernels, constraints, InterfaceKernels, etc. I suggest to make the two functions only contains the evaluation of local `Re` or `Ke` but nothing else. Currently the functions also supports save-in, tagging, etc. It could be dangerous that users' kernels are missing them (or any possible additional capabilities added in kernels), or users are forced to make lots of copy-paste in their derived kernels.

## Description

There are bunch of kernels in my applications that were created before the new tagging capability but are not updated. Making the transition will be painful.

## Impact
Better code maintainability.

**Comment by friedmud** [comment]
We already did that: it's called `computeQpJacobian()` and `computeQpResidual()`.  As always with MOOSE is if you choose to override lower-level functions then you are opening yourself up to more possibility for API change impacting you.

The code in `computeResidual()` and `computeJacobian()` has to go somewhere!  It can't just work by magic!

**Comment by dschwen** [comment]
And on top of that we have the once per element preCompute functions for
optimization purposes...

**Comment by YaqiWang** [comment]
For the most of the parts I agree. But I have few cases that I need to switch the loop ordering of test functions and quadrature points because some really costly evaluations is test function independent. I am fine this is closed. Just need to watch on those kernels.
