### ISSUE TITLE
Add AnnularMesh

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12205]
## Rationale

@jwpeterson has coded up a new way of generating annular meshes (a circular mesh with a hole in it with mesh radiating out from the hole).  @leorachapuis will help translate his libMesh code over into a MooseMesh derived object.

## Description

See above.

## Impact

New capability.

**Comment by jwpeterson** [comment]
![bassi_rebay_32x16](https://user-images.githubusercontent.com/1775907/46108245-cc35c380-c19a-11e8-94de-02a89863de87.png)

Reverse-engineered based on the meshes used in seen in F. Bassi and S. Rebay, “High-order accurate discontinuous finite element solution of the 2D Euler equations,” Journal of Computational Physics, vol. 138, pp. 251–285, Dec. 1997. https://doi.org/10.1006/ jcph.1997.5454.

**Comment by jwpeterson** [comment]
The original libmesh code for generating these meshes is also available in a [gist](https://gist.github.com/jwpeterson/2176f26de8a758adf69f6722538072e1).

**Comment by WilkAndy** [comment]
Can you have rmin=0 (ie, a disc)?

**Comment by jwpeterson** [comment]
Not currently, no. I was thinking we could do something similar to your `AnnularMesh` approach to get down to r=0.

**Comment by friedmud** [comment]
@WilkAndy You can generate a disk with `ConcentricCircleMesh`: http://mooseframework.org/source/mesh/ConcentricCircleMesh.html

**Comment by jwpeterson** [comment]
Closed by #12220.
