### ISSUE TITLE
Sorting of Sampler entries that have the same position

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#12209]
## Rationale
I'm trying to clean up the diffing HPC tests and found a few tests that are all diffing because of the same issue:
```
tensor_mechanics/test:line_material_rank_two_sampler.rank_two_sampler
tensor_mechanics/test:line_material_rank_two_sampler.rank_two_scalar_sampler
solid_mechanics/test:line_material_symm_tensor_sampler.test
```
It has to do with how the entries in the VectorPostprocessor are sorted, as explained below.

## Description
These tests are all outputting the material properties for the elements along a line. The values for all qps in those elements are output, and then they are sorted by position along the line (id). The problem is that these models have regular quad meshes, and the line is horizontal, so you end up with multiple qps with the same position along the line.

This isn't typically a problem in practice -- we use this capability pretty widely.  However, for the tests to pass reliably across multiple platforms, we need deterministic behavior. Some options:

1. Modify the tests so that we don't have two qps projecting to the same point along the line.
2. Modify the `indirectSort()` method used to do the sorting to do something deterministic if the values are the same within tolerance. Maybe preserve the original ordering for those values.
3. Same idea as option 2, but do it in `SamplerBase::finalize()` after `indirectSort()` is called.
4. Same idea as option 2, but in `LineMaterialSamplerBase::finalize()`
5. Slightly tweak the projected positions in `LineMaterialSamplerBase` so that they never have the same value.

## Impact
This will have minimal impact.  When fixed, the tests should reliable sort the values the same way, regardless of the platform.

**Comment by bwspenc** [comment]
@permcody @friedmud I'd like your thoughts on this.  It would be easy enough to just modify the tests, but it seems like the tests actually nicely show a corner case that we should handle consistently in the code.

**Comment by bwspenc** [comment]
After thinking this over a bit, I think the best option is to fix this in `LineMaterialSamperBase`. In `LineMaterialSamplerBase` we are doing the computations to project those qps onto the line. That's really the source of the problem. I imagine that we're not ending up with equal values for that projection, but values that are really close, and with ordering that could be switched depending on the platform. Messing with the sorting routines would really only be able to address the case where you have multiple exactly equal values.

**Comment by friedmud** [comment]
You can sort by "ID" too... not just direction.  Just make your ID selection be deterministic (like always visit the qps in the same order).
