### ISSUE TITLE
Add interface for fluid properties to choose between quiet and loud NaNs

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#12234]
## Rationale

There are currently some fluid properties classes, such as some in IAPWS95, that emit quiet NaNs. The intention is that evaluation of fluid properties in invalid states should not necessarily terminate a simulation, just allow time step size to be cut, even when trapping NaNs in debug mode, as other NaNs might be the objective of such traps. However, there are also cases when it is desired to terminate with these NaNs as well. Therefore, it would be useful to have an option for this. Note that there might also be other cases (not just fluid properties) where this option would be useful.

## Description

The current idea to solve this issue is to create an interface class, for example, `NaNInterface` that has a boolean parameter `emit_trappable_nans` and a function `getNaN()`, which returns either a loud (and trappable) NaN or a quite NaN, based on the value of `emit_trappable_nans`. 

## Impact

New interface class that fluid properties classes could use, for example.

**Comment by joshuahansel** [comment]
@andrsd

**Comment by andrsd** [comment]
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfIO4An_USun117tLQM6S3pNT-iYBuk_5FBG3TDRHEIy-6jxOU)

**Comment by permcody** [comment]
There is another option you may be aware of, but I feel like I should mention it here just to make sure. When running in debug mode you can always use `--no-trap-fpe`, but that is indeed a global option. It won't trap any FP exceptions of any kind.

**Comment by andrsd** [comment]
As we observed, quiet NaNs were not trapped in debug mode where trapping is on by default. We want to be able to make the quiet NaNs loud, so they get trapped when debugging problems.

**Comment by joshuahansel** [comment]
> you can always use `--no-trap-fpe`, but that is indeed a global option

Right, we discussed and decided we wanted to avoid the "globalness" because the generation of NaNs can sometimes be normal/desired transient behavior (cutting time step size), and we may want to see other NaNs in this case. For example, we're about to boil, but the large time step size times the heating rate to the liquid put it into a non-physical state for liquid, but smaller time step sizes would be fine. There might be some other NaN in this run we want to investigate.

**Comment by permcody** [comment]
Great! I honestly didn't know. Glad you guys have figured all of this out.

**Comment by permcody** [comment]
Note: #12335 referenced this issue in error, it should be #12334.
