### ISSUE TITLE
Residual save-in with block-restriction is buggy with MPI

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12239]
## Rationale

While working on multi-scheme transport in Rattlesnake, I hit a bug and am able to reproduce it with a MOOSE input. The bug shows up with block restricted variables when using save-in.

## Description

I modified an input file like
```
diff --git a/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i b/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i
index 4eb06fb2c7..e48883c631 100644
--- a/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i
+++ b/test/tests/interfacekernels/2d_interface/coupled_value_coupled_flux.i
@@ -41,6 +41,15 @@
   [../]
 []
 
+[AuxVariables]
+  [./ures]
+    block = 0
+  [../]
+  [./vres]
+    block = 1
+  [../]
+[]
+
 [Kernels]
   [./diff_u]
     type = CoeffParamDiffusion
@@ -68,6 +77,8 @@
     neighbor_var = v
     boundary = master0_interface
     penalty = 1e6
+#    save_in = 'ures vres'
+#    save_in_var_side = 'm s'
   [../]
 []
 
@@ -76,11 +87,15 @@
     type = VacuumBC
     variable = u
     boundary = 'left_to_0 bottom_to_0 right top'
+    # this should error out, but not
+    save_in = 'vres'
   [../]
   [./v]
     type = VacuumBC
     variable = v
     boundary = 'left_to_1 bottom_to_1'
+    # this results into behavior change with MPI
+    save_in = 'vres'
   [../]
 []
 
@@ -95,6 +110,16 @@
     variable = v
     block = 1
   [../]
+  [./ures_int]
+    type = ElementIntegralVariablePostprocessor
+    variable = ures
+    block = 0
+  [../]
+  [./vres_int]
+    type = ElementIntegralVariablePostprocessor
+    variable = vres
+    block = 1
+  [../]
 []
```
Initially I thought it is caused by `InterfaceKernel`, but later realized that it is probably related with node visiting with block restriction. I only left the save-in in the boundary condition of `v`, and the integral of the residual with one processor is
```
+----------------+----------------+----------------+----------------+----------------+
| time           | u_int          | ures_int       | v_int          | vres_int       |
+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   2.398597e+00 |   0.000000e+00 |   7.287195e-01 |   1.646896e-01 |
+----------------+----------------+----------------+----------------+----------------+
```
With two processors
```
+----------------+----------------+----------------+----------------+----------------+
| time           | u_int          | ures_int       | v_int          | vres_int       |
+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   2.398597e+00 |   0.000000e+00 |   7.287195e-01 |   2.078455e-01 |
+----------------+----------------+----------------+----------------+----------------+
```
You see `vres_int` value changed. Increasing number of processors will cause the value increased further. If you comment out the block restriction of `vres`, the bug will not show up. Another thing is not right is that save-in does not error out when saving into a variable not defined on the block a boundary condition is on.

## Impact
Impact Rattlesnake multi-scheme capability or anybody using the save-in with block restriction.

**Comment by lindsayad** [comment]
@YaqiWang this should be fixed, but should we also update Griffin to use the tagging system instead of relying on save-in?

**Comment by YaqiWang** [comment]
@zachmprince do you remember what exactly the reason we need to stay using save-in with IQS? @lindsayad did you apply the diff and run the test? Is the test covering this corner case now? If so, I can fix some codes in Griffin.

**Comment by lindsayad** [comment]
So as to the "this should error out, but not", you do get a debug mode failure because libmesh checks and sees that the size of the local residual does not match the  number of dof indices of the save-in variable (e.g `_local_re.size() == 4` while `dof_indices.size() == 0`)

**Comment by zachmprince** [comment]
I did implement the residual tagging version a while ago, this was a big effort, but my concept was shot down. So the residual save in has remained.
