### ISSUE TITLE
Benchmark / Performance action

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12244]
## Rationale

It would be good practice to have a standard set of _inexpensive_ postprocessors in production runs and Bison assessment cases, such as

* Number of linear and non-linear iteration per timestep (`num_lin_it`, `num_nonlin_it`, `tot_lin_it`, `tot_nonlin_it` are the names already being used for those).
* Physical memory
* Timestep size
* Wall time
* Number of DOFs

## Description

To make things easy I propose a simple parameterless action 

```
[BenchmarkData]
[]
```

that sets up the postprocessors, potentially with a separate csv output object XXXX_benchmark_data.csv, which would avoid cluttering the main csv output with the benchmark data.

## Impact

Added capability.

**Comment by YaqiWang** [comment]
How about use `Debug/enable_benchmark_data`?

**Comment by dschwen** [comment]
Yeah, I thought about that but don't like it. It is one line more, it creates the impression that something is de_bugged_ and potentially slow, and it requires us to put a lot of stuff into the SetupDebugAction (and to register it to additional tasks).

**Comment by friedmud** [comment]
I'm definitely against this particular proposal.

We are actually talking about making drastic changes to _reduce_ the number
of "top level" syntax blocks... and this would add another one.

If you want this - feel free to add it to your own application, but it
doesn't belong in MOOSE.  It's just a bit too specific, some people will
only want some of those outputs - others will want more...

Derek

**Comment by dschwen** [comment]
Ok, so we'll add one copy in Marmot and another copy in Bison then.

**Comment by friedmud** [comment]
I'm only one vote - but yeah.  I suspect that the two will begin to deviate
almost immediately.  BISON guys will add tons of stuff to theirs that you
guys don't care about and visa-versa....

**Comment by dschwen** [comment]
No, probably not. For one I'd be the one adding it to bison and there is a fairly well defined set of low/no cost performance metric postprocessors.

**Comment by friedmud** [comment]
Ok - we’ll revisit this in one year to see if they’re exactly the same. My guess: over time the Bison guys will add some you didn’t originally add (they have different metrics they care about).

[Derek Gaston - Contact Using Hop](http://GetHop.com/?_hmid=1538629602)

On October 4, 2018 at 4:57 GMT, Daniel Schwen <notifications@github.com> wrote:

No, probably not. For one I'd be the one adding it to bison and there is a fairly well defined set of low/no cost performance metric postprocessors.
