### ISSUE TITLE
Discrete nucleus space-time coordinates from file

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12262]
## Rationale

For direct comparison and testing it would be nice to have a `DiscreteNucleationInserter` that, rather than randomly sampling the Poisson statistics, inserts nucleation sites at predetermined times and points in space.

## Description

Add a `DiscreteNucleationFromFile` class that uses the `CSVReader` to read a list of `time,x,y,z` points and inserts at the given times and points (potentially add a hold time column?).
This would seamlessly plug in with the existing system.

We could then perform mesh convergence studies (which would otherwise lead to differing random number steams and thus different nucleation histories).

## Impact

Added capability for verification.

**Comment by permcody** [comment]
Looking forward to this. I should be able to use this to manufacturer some splitting grains tests

**Comment by friedmud** [comment]
This is definitely a good idea!
