### ISSUE TITLE
Plugin based 2D batch plot generation tool with data pipelines

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12263]
## Rationale

Per discussion with @bwspenc we'd like to make an attempt to get this into MOOSE.

The proposed tool will accept HIT files with a description of data sources (e.g. CSV file columns), data preprocessors (e.g. Difference and Unit conversion), and outputs (e.g. matplotlib line plots) to simplify the batch generation of plots for example for assessment cases that run automatically.

## Description

A python tool using the moose python factory system will be developed to simplify the generation of large sets of plots.

## Impact

Added capability

**Comment by friedmud** [comment]
Guys - please don't start something different from Chigger.  Chigger can
already do most of this.  To me this sounds like a new use of Chigger - or
possibly just feature extensions of Chigger.

We've already spent too much time and effort doing Chigger to start
something different.

Derek

**Comment by dschwen** [comment]
No

**Comment by dschwen** [comment]
@friedmud is wrong

**Comment by dschwen** [comment]
@bwspenc I told you this reply would be triggered :-D

**Comment by friedmud** [comment]
Well... if you knew it was going to go down this way... why post it like this?

Don't underestimate the amount of time necessary to make something like this work well.  We really need to stay focused on Chigger and pool our resources (mostly our person-power) to make one really great scriptable plotting tool.

**Comment by dschwen** [comment]
You must have missed the part where I wrote 

> The proposed tool will accept HIT files with a description of data sources (e.g. CSV file columns), data preprocessors (e.g. Difference and Unit conversion), and outputs (e.g. matplotlib line plots) to simplify the batch generation of plots for example for assessment cases that run automatically.

And you may not be aware of @aeslaughter 's position not to develop Chigger in this direction.

Also we need vector plots. That'd be a bit of a stretch for Chigger, given that it is VTK based.

**Comment by friedmud** [comment]
What are you talking about?  Have you even used the Postprocessor or
Vectorpostprocessor tabs in Peacock?  You do know those are rendered by
Chigger... right?  You can even save out the .py file and run them in batch
mode to regenerate the plots.

**Comment by dschwen** [comment]
That's great, but a separate .py file for each assessment case is exactly what we're trying to replace here.

**Comment by friedmud** [comment]
What do you mean?  They .py file just says what columns to plot, what to label the axes, etc.  You gotta put that somewhere.

**Comment by friedmud** [comment]
Ok - I'm calling it.  Let's not discuss this anymore until I get back.  This will go better in person with @aeslaughter and @bwspenc .

**Comment by dschwen** [comment]
> You gotta put that somewhere.

Yeah, an input file. Lots of data already is in the outputs. We'll be using Chigger for various tasks here anyways. For reading global values form exodus files for example. If requested we can even use it as one of the output plugins to generate plots.

**Comment by dschwen** [comment]
It might help if I post an example input for the current work in progress version:

```
#
# Difference between the fission gas curves
# (this is up top to give the dependency resolver some work)
#
[./diff]
  type = Difference
  source1 = fgr1
  source2 = fgr2
[../]

#
# These blocks generate the actual plots (one is PDF, one is PNG)
#
[./pdf1]
  type = Plot
  sources = 'fgr1 fgr2'
  file = fgr.png
  x_label = Time
  y_label = 'Fission gas release'
[../]
[./pdf2]
  type = Plot
  sources = 'diff'
  file = diff.png
  x_label = Time
[../]

#
# Fission gas curves read from two different CSV files
# (note the different column names)
#
[./fgr1]
  type = CSV
  file = out1.csv
  x_data = time
  y_data = fgr
[../]
[./fgr2]
  type = CSV
  file = out2.csv
  x_data = time
  y_data = release
[../]
```

**Comment by aeslaughter** [comment]
FYI. The VPP/PP plotting in Peacock uses matplotlib, not chigger.

**Comment by aeslaughter** [comment]
![data_pipeline](https://user-images.githubusercontent.com/341333/46629678-fb372800-cafe-11e8-8c89-768caca58015.png)
