### ISSUE TITLE
Multiple input files capabilities

### ISSUE THREAD

**Issue by mooseframework** [idaholab/moose#1226]
It would be practice to have a list of the recent input file, to be able to have a quick access to it. For example, BISON's user's often refer to multiple input files depending on the analysis they want to carry out, or to compare two input files when there are convergence issues. 

By the way, it could also be nice to be able to copy a whole block from a different input file into your current input file.

**Comment by permcody** [comment]
The new peacock keeps a list of recently used input files. This enhancement now exists.
