### ISSUE TITLE
Input file parser warns about unused variable

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#12270]
## Rationale

If an input file variable is *only* used in a dollar bracket expression (DBE), the input file parser warns that it is unused.

## Description

Should be reproducible in any input file by adding a variable which is only used in a DBE:
```
foo=12
...
bar = ${foo}
```

## Impact

Just produces a warning, so not critical.

**Comment by rwcarlsen** [comment]
I can't reproduce - could you provide an input file?

**Comment by jwpeterson** [comment]
Yeah... let me cut down this application input file where I'm seeing the problem...

**Comment by jwpeterson** [comment]
I'm an idiot. We had two input file variables with almost the same name, one of which was unused. Commenting out the *other* one makes the warning go away...
