### ISSUE TITLE
registerAll migration instructions in newsletter

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12276]
## Rationale

Going over these instructions (and reminiscing of the times when PRs were made to apps after such API changes), I found them to be a cumbersome.

## Description

Example code has a bug (missing return type). <s>Maybe I'll try add a more structured description.</s>

## Impact

Improved docs

**Comment by dschwen** [comment]
Would be nice if the `associateSyntaxInner` pattern was described @rwcarlsen.

**Comment by rwcarlsen** [comment]
The associateSyntax pattern is not necessary - it is just a convenience to allow deprecating the old functions (in cases where the module/app is depended on by other apps that may not have been updated yet) while still making it possible to avoid duplication of code between the old and new functions.
