### ISSUE TITLE
Transformation Between MultiApps

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12293]
## Rationale

Apps running within the MultiApp system can often be oriented differently - and use different units for lengths.  They may also be using different coordinate systems (cartesian, rz, spherical).

Some of this is coming out of the discussion here:  #12281

## Description

What we need is a generic transformation capability to move points back and forth between apps.  It should support rotation, translation and stretching.  That usually comes down to defining transformation matrices: but we want something more user-friendly for the "common-cases".

## Impact

None - new capability

**Comment by GiudGiud** [comment]
Following our discussion, I ll lay down all the reasons we could want a VectorFunction (so mapping from point + time to point (+time?)) for this transformation. VectorFunction might not be the best name. Maybe "map" is it

- symmetry of the system between to_multiapp and from_multiapp
- can still create a default VectorFunction if users do not provide one, so I m not that worried the syntax will be too difficult for users
- possibility for custom mappings: map to a different time in the subapp, change mapping location in time (subapp is moving!)
- possibility for weird mappings. RZ in subapp but only to map from a quarter cylinder in the main app
- reuse of the system for exodus restart from different geometries (this comes up)
- reuse of the system for mapping from two different equation systems (longer term)

Also summing up our discussion, we'd want:
- unit conversion
- what is up conversion
- RZ-XYZ and all other possibilities conversion

**Comment by lindsayad** [comment]
I think that nothing precludes us from using the concept you're describing as one of the possible tools for defining an application's position in space and time. Do you have a preference on whether this concept is prescribed in something like the `MultiApp` block vs. the individual input files? After the discussion today I prefer the individual input files because then applications can programmatically set their transformations if they wish. If we went with this latter implementation, then your `VectorFunction` would have to prescribe a transformation to a reference coordinate since there is no relative-to relationship like there would be if you prescribed this function in something like the `MultiApp` block

**Comment by GiudGiud** [comment]
I think the MultiApp block can create a default one (so the action, based on info gathered from the main app and the subapp) if it s not user-specified in a [Map] block and given to the multiapp as a parameter. 

Yeah so the VectorFunction (or Map) would have to take in a position coordinate as well as the local coordinate.

**Comment by friedmud** [comment]
In the App object and/or in the sub-app input file.

We already get enough feedback saying MultiApp input syntax is complicated... we don't need to make it moreso! :-)

**Comment by GiudGiud** [comment]
The App object is in the sub-app input file right?

**Comment by friedmud** [comment]
@GiudGiud not literally - but yes

**Comment by lindsayad** [comment]
So generally speaking, "what is up" is not enough to uniquely define orientation. For instance, I could define my reference space to have gravity in the (0, 0, -1) direction (e.g. +z is up). Now if a user defines gravity as (-1, 0, 0), such that +x is up, I can rotate +x onto +z but then I could spin around my azimuthal angle 360 degrees and still meet my up criteria.

**Comment by lindsayad** [comment]
For a 2D mesh, "what is up" is sufficient

**Comment by GiudGiud** [comment]
I agree we need a rotation matrix, but what's up was funnier :)

**Comment by lindsayad** [comment]
I know you are fully down for a rotation matrix (and I am too), but I think @friedmud was pretty serious about at least the concept of "what is up"

**Comment by lindsayad** [comment]
I'm going to proceed forward with rotation angles as possible inputs for the coordinate transform, based on libmesh/libmesh#3171. I think those are clear enough concepts, that at least one application developer will know how to program this for their application. And I believe with documentation pointing to the right diagrams, the rotation angles concepts are pretty clear for users who would wish to specify them in their inputs

**Comment by friedmud** [comment]
Add all the angles you want... but 99% of the time people will be using REALLY simple transforms... and we should make the input simple.

**Comment by friedmud** [comment]
@lindsayad ideally - yes

**Comment by friedmud** [comment]
@lindsayad - but that part should be automatic based on what `coord_sys` is set to.
