### ISSUE TITLE
Several tests fail with PETSc > 3.9

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#12303]
## Rationale
There are some test fails when using PETSc-3.9.4.  Some of them are related to Jacobian tests, and others are exodiff. 

## Description
Try to fix these issues by check PETSc changes. 

## Impact
Anyone using PETSc-3.9.4

**Comment by permcody** [comment]
All tests have been updated. Petsc 3.9 works with all MOOSE tests.
