### ISSUE TITLE
questions about PressureBC, CoupledPressureBC and Explicit Dynamics

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#12308]
## Rationale
This is a question about implementations of pressure boundary conditions.

## Description
1. Implementations of PressureBC and CoupledPressureBC are slightly different. One of them might be a legacy code. As I see it, the implementation of PressureBC is more complete and CoupledPressureBC should follow it, or even get merged into PressureBC.
2. Is it okay if I add a CoupledNeumannBC in the framework that takes in a coupled variable to enforce the BC, and add a CoupledTractionBC in TensorMechanics that derives from the CoupledNeumannBC to take into account the time integration and use displaced mesh?
3. It appeared to me that if we add the explicit dynamics capability later on, we need to let these BCs that utilize time integration aware of the time integrator we are using. For example, line 50 of Pressure.C should evaluate the function at (_t - _dt) instead of (_t + alpha * _dt). Correct me if I am wrong.

## Impact
My appreciation.

**Comment by andrsd** [comment]
Regarding 1, read [the discussion on PR 11566](https://github.com/idaholab/moose/pull/11566) for more details about `CoupledPressureBC` and why is it the way it is.

**Comment by permcody** [comment]
Why did you open an issue to ask questions? What's wrong with the mailing list? Only a few people see these (by default). I'm not sure there is any Action here so I'm closing.
