### ISSUE TITLE
Input file checking for correct variable "braces"

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#12313]
## Rationale

MOOSE currently does not throw an error in the `[Variables]` block if a variable is declared with a missing period as so:

<pre>
[Variables]
  [/u] # missing the period before the slash, but no error
    initial_condition = 500.0
    block = '3'
  [../]
[]
</pre>

Forgetting the period, however, does not give any error to the user, but results in the statements within the `u` block not executing. In the above example, forgetting the period causes `u` to be defined on all of the blocks of the problem (the default) instead of just block 3, with a zero initial condition (the default) instead of 500.0.

However, forgetting a period in the definition of a kernel _does_ throw an error:

<pre>
[Kernels]
  [/diffusion] # throws "missing required parameter 'Kernels//diffusion/type" error
    type = Diffusion
    variable = u
  [../]
[]
</pre>    

If this is not the intended behavior, an error should be thrown to the user that they have incorrect syntax in the `Variables` block - it took me super long to figure out why my initial condition wasn't being set.

## Description

An example input file is attached. 

## Impact

Reduce input file typos and improve expected code behavior.
[test.zip](https://github.com/idaholab/moose/files/2479440/test.zip)

**Comment by permcody** [comment]
Thanks for the report. We do need to check for this. We have a near-term goal is to drop most slashes and periods in most input files. Exceptions would be when you want to specify multiple layers in a single block:
```
[Foo/bar]
    variable = value
[]
```

Tag @rwcarlsen
