### ISSUE TITLE
Remove default ghosting

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12327]
## Rationale

The default GhostingFunctors in libMesh are often overzealous.  We're handling this much more carefully now using the RelationshipManagers - so we should remove the default ghosting that libMesh gives us.

## Description

Obliterate the default ghosting coming from libMesh... replace it with our own.

## Impact

If I do my job... then hopefully none!

**Comment by permcody** [comment]
Default ghosting has been removed in the modern RelationshipManager system.
