### ISSUE TITLE
Improve MemoryUsage Postprocessor

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12333]
## Rationale

When running in a cluster environment with the `MemoryUsage` Postprocessor it would be convenient to get statistics not only on a per rank basis, but also on a per node basis. Also getting data on total RAM available on a node would be neat.

## Description

Utilize `MPI_Get_processor_name` to generate a unique node id. Figure out how to reliable get installed RAM amount on macOS/Linux (getting there). Provide min max node memory utilization in %.
Potentially add a VectorPostprocessor to list all those values per rank or per node.

Getting useful and reliable memory statistics is notoriously tricky. I'm willing to give this a shot though. Having this data readily available for every run without launching jobs with wrapper scripts, running external memory diagnosis tools etc. would help us build a library of performance data for all of our HPC runs.

Comments @friedmud ?

## Impact

Added capability for diagnosing HPC runs on the fly.

**Comment by friedmud** [comment]
Yes!  I would love this.  VectorPostprocessor is the right way to go... then we can use VectorPostprocessorVisualizationAux to actually visualize the memory usage on the mesh also.

**Comment by dschwen** [comment]
Ok, I think I've got physical RAM available down (tested on mac and on falcon with parallel runs -  it correctly identifies the ranks that share a RAM pool; i.e. two CPUs with a total of 36 cores share ~128GiB RAM). I'm factoring out the memory meassuring routines now and will add a VPP.
