### ISSUE TITLE
(Automatic Differentiation) Moose 792f3da71 commit in master causing a noticeable benchmarking time increase 

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12332]
## Rationale

As showed in https://hpcsc.inl.gov/ssl/RATTLESNAKE/timing/

## Description

Do you notice anything similar in MOOSE benchmark timing?

## Impact
Run-time efficiency.

**Comment by permcody** [comment]
Automatic differentiation... I'm not surprised that caused a little slowdown. It's spread all over and is an important capability

**Comment by permcody** [comment]
We'll have to benchmark and see if there are some places we can fixup.

**Comment by lindsayad** [comment]
Have you profiled this or do you have a representative test case that I can profile?

**Comment by lindsayad** [comment]
I just profiled `twigl.i` and didn't see any boxes pertaining to AD. Looking at your timings, it definitely suggests that he AD PR did something. Maybe one of the other benchmarks will show something to me tomorrow.

**Comment by YaqiWang** [comment]
Thanks for investigating this.

**Comment by YaqiWang** [comment]
Did you increase the problem size by `-r 2` to see if there is significant cpu time increase? If the increase is less than 5%, I am not too concerned.

**Comment by lindsayad** [comment]
Yes I’ll try increasing the problem size. That will be better for more stack trace samples as well.

**Comment by lindsayad** [comment]
Ok, with `-r 3`, before AD took 202 seconds, and after AD took 195 seconds for the `twigl` benchmark. That's within 4%. The top offenders for the small slowdown don't appear related to the AD code:

![screen shot 2018-12-12 at 10 22 57 am](https://user-images.githubusercontent.com/10248304/49886808-d78ea780-fdf7-11e8-8a58-e351fa93e45d.png)

Is it ok if we close this @YaqiWang?

**Comment by YaqiWang** [comment]
Yes. Thanks for the investigation.
