### ISSUE TITLE
Compare diffusion in RDG with PorousFlow

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#12346]
## Rationale

We hope that RDG will produce less numerical diffusion than PorousFlow.  Currently the diffusion is quantified in these two pages:

http://mooseframework.org/modules/porous_flow/numerical_diffusion.html
http://mooseframework.org/modules/rdg/index.html

I want to document some experiments with the RDG module and include the results in the PorousFlow documentation, so that people like @hsheldon can see what to expect when RDG is implemented in PorousFlow.

It is possible this may also shed some light on ways to implement RDG in PorousFlow, or possibly alternatives to RDG, which i'm still thinking about.

Tagging @permcody , @yidongxiainl , @andrsd , @joshuahansel , @mrodb , @rpodgorney , @lingzou , @cpgr , @YaqiWang , @philippschaedle , @hsheldon

## Description

```AEFVKernel``` and ```AEFVBC``` will be more convenient to use if they have a "velocity" input, as the aforementioned PorousFlow documentation does not assume v=1.

There is a bug in ```AEFVBC``` in the computeJacobian - it needs to size the result correctly (this isn't picked up in the test)

I'll make PorousFlow depend on the RDG module

I'll include the tests in the PorousFlow test suite, alongside the existing tests and documentation.

## Impact

Clarity on what to expect from RDG.  Probably improve my understanding of RDG.

**Comment by WilkAndy** [comment]
Actually, it is the ```AEFVFreeOutflowBoundaryFlux``` UserObject that didn't correctly compute the Jacobian.

**Comment by joshuahansel** [comment]
Regarding the "velocity" input, I think this would belong to the flux class `AEFVUpwindInternalSideFlux`, not the kernel or BC.

**Comment by andrsd** [comment]
> I think this would belong to the flux class `AEFVUpwindInternalSideFlux`, not the kernel or BC.

Agree.

**Comment by WilkAndy** [comment]
OK, i'll put the "velocity" in the UserObject
