### ISSUE TITLE
CSV Differ re-work

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#12363]
## Rationale
Currently a CSV test can only be tested via through the TestHarness (true?)

## Description
Design a stand alone CSV differ tool (like the exodiff binary)

## Impact
Possibly some API changes effecting several Apps

**Comment by milljm** [comment]
@permcody Because I am not very familiar with exactly what we want our csvdiff tool to do, would an already created python module work for us? https://pypi.org/project/csvdiff/

If not, I will need a refresher on what you are expecting as the results of such a tool. Thanks!

**Comment by milljm** [comment]
I pip install'd csvdiff... and yeah. It is not what we want...  So nm on that idea.

**Comment by tophmatthews** [comment]
Just a reminder to retain the capability discussed #11751 :)

**Comment by milljm** [comment]
@tophmatthews I am not sure this applies. The testers are all serial operations either called directly (subprocess.Popen[exodiff]) or from a serialized thread within the TestHarness to our python tester objects.

In other words, we allow ./run_tests -j <this amount> of tests to be tested at the same time. But we do not run mpiexec -n <this many> ./run_tests's at the same time.

Just to be clear, RunApp calls your app (or another binary) that generates a result. But the process involved checking to see if that result is a good one, is serial.

**Comment by permcody** [comment]
Jason, This looks good so far - it's exactly what I asked for technically. What I'd also like to explore though is if we can rewrite part or much of the internals of this utility using the pandas library. We can focus on the config file part first if you'd like. They are independent tasks.
