### ISSUE TITLE
Banish Problem/error_on_jacobian_nonzero_reallocation

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12397]
## Rationale

With all of the new work being done for ghosting #12354 #12327 we are getting closer to being able to turn on `Problem/error_on_jacobian_nonzero_reallocation`.  While #12354 and #12327 are about Algebraic and Geometric ghosting... `error_on_jacobian_nonzero_reallocation` is about the _Coupling_Functor.  The RelationshipManager system that we already have in place should be able to be used for the DofMap CouplingFunctor as well... which should allow us to connect individual degrees of freedom together regardless of geometry.

Using this we should be able to get the correct sparsity pattern even for Mortar/Contact and other 
non-local things.

Note that there are a few other Issues related to this including #5819 #4690 #4275

## Description

See Above

## Impact

Will speed up Mortar/Contact problems.

**Comment by GiudGiud** [comment]
#23943 is more representative of the current state of this problem.

We also do not want to remove / banish the parameter, it's useful early on before the sparsity pattern has been well preserved
