### ISSUE TITLE
Threads issues with tagging system 

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#12417]
## Rationale
We access some data using `matrix(idx, idx)` does not support threading. 

## Description
Add one lock before` matrix operator ()` so that only one thread can call `GetRow` and `RestoreRow`. 

## Impact
Only impact `TagMatrixAux kernel`. It is used to save the matrix diagonal for testing the tagging system.

**Comment by permcody** [comment]
Please fill out the full template! This ticket would fail an audit.
