### ISSUE TITLE
Problem with restoring MultiApps when only some failed

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#12477]
## Rationale

If a master has two sub apps and only the first one fails, the time step of the master app is not cut, as it is if only the first one was used by the master app.

## Description

This error can be reproduced by adding a second non-failing subapp to `moose/test/tests/multiapps/picard_failure/picard_master.i`.

It seems that the culprit is: https://github.com/idaholab/moose/blob/devel/framework/src/problems/FEProblemBase.C#L3542

I believe it should be:

```
for (const auto & multi_app : multi_apps)
  success = multi_app->solveStep(_dt, _time, auto_advance) && success;
```

and not:

```
for (const auto & multi_app : multi_apps)
   success = multi_app->solveStep(_dt, _time, auto_advance);
```

I will send in a PR shortly.

## Impact

Fixing this bug will allow to recover properly when only one subapp failed.

**Comment by YaqiWang** [comment]
Should we immediately return false when we see one app `solveStep` fails?

**Comment by vincentlaboure** [comment]
I think you are right: if I break the loop as soon as `success` becomes `false`, it avoids running the second app and the results seem identical.
