### ISSUE TITLE
Allow ability to skip version tests when git is not available

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#12483]
## Rationale
Circumstances exist when `git` does not exist or when the current application is not a git repository.

## Description
Tests requiring `git` need the ability to be skipped when `git` is not available or when the current repository is not a git repository.

## Impact
None.

**Comment by permcody** [comment]
@milljm - I updated this a little bit. There are two cases here where you'd want to make sure you skipped a test: No git, and current directory is not a git repository.
