### ISSUE TITLE
Spherical Layered Average

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12542]
## Rationale

Need to be able to do layered averages in spherical "shells"

## Description

Just what it says

## Impact

New capability

**Comment by dschwen** [comment]
We have `moose/framework/include/vectorpostprocessors/SphericalAverage.h` which does radial binning.

**Comment by friedmud** [comment]
Perfect!  Thanks!

**Comment by friedmud** [comment]
Yep - just looked.  That will work for now... thanks again!
