### ISSUE TITLE
MeshGenerators Should Require Input

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12571]
## Rationale

Any `MeshGenerator` that requires input (like the Extruder) should have the `input` parameter as a required parameter.

Any that can get input from multiple places should double check that at least _some_ input has been given

## Description

Better usability and errors

## Impact

None - new capability

**Comment by permcody** [comment]
This issue (requirement) has been incorporated even though it's not specifically referenced. The 'input' parameter is controls the DAG execution. Closing this ticket.
