### ISSUE TITLE
Macros/using declarations for hiding AD this-> syntax

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#12615]
## Rationale

Since we decided to hide `this->` syntax from AD users (at least as best we can) we need to make sure we cover the data/methods used by users with proper `using` declarations and macro syntax for dependent template methods.

## Description

Until this coverage is complete, users exploring the AD systems won't know when they need to use `this->` syntax.

## Impact

Make the AD experience for consistent for users.

**Comment by lindsayad** [comment]
Uncovered members:

- [ ] `isParamValid`
- [ ] `_q_point`

**Comment by veeshy** [comment]
Is it possible to make this work for things declared in a base class so a child class can use the base class members without having to use this->?

**Comment by tophmatthews** [comment]
_name

**Comment by tophmatthews** [comment]
`getFunction`
`getPostprocessorValue`

**Comment by tophmatthews** [comment]
`isCoupled`

**Comment by dschwen** [comment]
For easy copy and pasting (and because I'm lazy and just copied it out of my code):

```
  using ADKernel<compute_stage>::_JxW;
  using ADKernel<compute_stage>::_coord;
  using ADKernel<compute_stage>::_local_re;
  using ADKernel<compute_stage>::_qrule;
  using ADKernel<compute_stage>::_save_in;
  using ADKernel<compute_stage>::_has_save_in;
  using ADKernel<compute_stage>::_current_elem_volume;

  using ADKernel<compute_stage>::coupled;
  using ADKernel<compute_stage>::coupledComponents;
  using ADKernel<compute_stage>::getBlockCoordSystem;
```

**Comment by lindsayad** [comment]
Very lazy 🙄

**Comment by veeshy** [comment]
`_is_transient`

**Comment by lindsayad** [comment]
This is no longer relevant after AD 2.0
