### ISSUE TITLE
Add a new meshgenerator to create 1D meshes from text file

### ISSUE THREAD

**Issue by sveerara** [idaholab/moose#12631]
## Rationale

For analyzing simple portal frame problems using beam elements, it would be easier if the mesh can be created using a text file than using Cubit.

## Description

The BeamMeshGenerator generates mesh from a text file that contains node positions, element connectivity, nodeset and block information.

## Impact

This should not affect any existing code but will improve the usability of the beam or other 1D elements in Moose and Mastodon.

**Comment by dschwen** [comment]
Doesn't libmesh already have ASCII mesh format support for reading? I'd
check that's first before creating a new format.

**Comment by permcody** [comment]
libMesh does have an ascii format. It's called XDA. I suggest that you
create a 1D mesh with GeneratedMesh and output it to XDA. You should be
able to read that right back in. Take a look and see if that'll work for
you.

**Comment by sveerara** [comment]
@dschwen and @permcody, thanks for your comments. I looked at abaqus_io.C in libmesh and followed a similar method of reading the lines of the file and creating the mesh from that. But I agree that if a parser and a format already exists, then it would be better to use that instead of creating a new format. I will look at the XDA mesh file corresponding to a GeneratedMesh and a more complicated mesh generated using Cubit and see if I can use XDA format for this case.
