### ISSUE TITLE
Add AD versions of some kernels

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#12633]
## Rationale

Some kernels can sometimes use complicated material properties or highly deformed meshes (#12535). Using automatic differentiation can help alleviate these problems.

## Description

Reproduce some kernels as ADKernels
- [x] ADHeatConduction
- [x] ADHeatConductionTimeDerivative (needs ADTimeDerivative)
- [x] ADMatHeatSource
- [x] ADMatDiffusion
- [x] ADSoret
- [x] ADDensity

## Impact

More usability for the AD system.

**Comment by tophmatthews** [comment]
Whoops this wasn't supposed to get closed, can you reopen @lindsayad

**Comment by tophmatthews** [comment]
@lindsayad I want to have an `ADHeatSource` that uses a material property as the coefficient. The current implementation of `HeatSource` is just a reworking of `BodyForce`. `BodyForce` takes a Real and functions as scalars. Is there a case where AD would help for a duplication of `BodyForce`? Maybe highly deformed meshes since it's a volumetric term? If so, I can make an `ADBodyForce` and `ADHeatSource`. If there is no need for an `ADBodyForce` I can make a `ADMatHeatSource`.

Make sense?

**Comment by lindsayad** [comment]
`ADMatHeatSource` sounds more generic to me. One could always make the material property depend on a function

**Comment by tophmatthews** [comment]
@lindsayad Is there plans for an ADDiracKernel? That will allow thermal contact to be converted over as well.

**Comment by lindsayad** [comment]
> Is there plans for an ADDiracKernel?

There are. I have a branch for laser-welding simulations that contains `ADNodalBC` and `ADIntegratedBC` as well as a further abstraction of `ADKernel` that allows it to operate on scalar and vector variables (e.g. LAGRANGE_VEC or NEDELEC_ONE) (don't worry, this abstraction won't change the work you've been doing). @fdkong has a branch with `ADDGKernel`. Admittedly, it might take a while for one of us to get to `ADDiracKernel`; it will happen...but if an outsider wants it faster s/he is welcome to take a stab at it! 😄

**Comment by dschwen** [comment]
Hey @tophmatthews I'll be working on Tensor Mechanics AD kernels in the next weeks (starting today). Just FYI so we can coordinate our efforts :-)

**Comment by tophmatthews** [comment]
@dschwen Awesome! I'm trying to get an entire BISON solve using AD. The pieces missing are the TensorMechanics, TimeDerivative, and Thermal contact (DiracKernel). Let's do this!

**Comment by dschwen** [comment]
@tophmatthews did you already have a list for things that need to be added to the `usingKernelMembers;` macro? I have a ton to add. I cannot find it but thought I saw it in passing in an email.

**Comment by tophmatthews** [comment]
@dschwen Yeah, #12615

**Comment by tophmatthews** [comment]
Quadrature thermal contact touches:
- `GapValueAux`
- `PenetrationAux`
- `GapHeatTransfer` boundary condition
- `GapConductance` material

**Comment by tophmatthews** [comment]
@dschwen @bwspenc I wonder if this is one of those cases where an aux makes more sense? Can the pieces for thermal contact be turned into materials for ad?

**Comment by bwspenc** [comment]
@tophmatthews My initial take on this is that we can't convert those to materials. Sorting this whole system out is a little complicated, but as I recall, we use an AuxKernel to compute the temperature on the opposing face. It would probably be a good idea to convert this whole thing over to be based on Constraint, although I don't think that is supported by AD yet either.

**Comment by tophmatthews** [comment]
https://mooseframework.inl.gov/newsletter/2019_01.html

Looks like constraints are in the near future. It'd be great to get this going since this is the last piece of the thermal solve of a typical bison run.

@lindsayad Is there much benefit for adding ad pieces of the material and dirackernels but missing the constraint pieces? In other words, how much is gained by only doing AD for part of the solve. I imagine it's dependent on how much the solve depends on the non-AD part.

**Comment by lindsayad** [comment]
> @lindsayad Is there much benefit for adding ad pieces of the material and dirackernels but missing the constraint pieces? In other words, how much is gained by only doing AD for part of the solve. I imagine it's dependent on how much the solve depends on the non-AD part.

Since this question presupposes we don't have AD in constraints, I'm going to assume we're setting `solve_type = PJFNK` in general. So with that established, the efficiency of the linear solve will depend on whether your preconditioner is capturing the important terms accurately. If your materials and dirackernels are strong contributors to your physics, then having the correct Jacobian will be very valuable.

**Comment by tophmatthews** [comment]
A couple other questions @lindsayad:
Do you have to specify a preconditioner for AD to work?
Does AD still do finite differencing or is it all symbolic? An example of why I ask is what happens with material properties that depend on tabular data passed via a function? I imagine if it is finite differencing, jacobian information is still correctly handled, as long as the function is smooth. If it is symbolic, how do you imagine getting around tabular data?

**Comment by lindsayad** [comment]
> Do you have to specify a preconditioner for AD to work?

If you have any off-diagonal terms, then yes.

> Does AD still do finite differencing or is it all symbolic? An example of why I ask is what happens with material properties that depend on tabular data passed via a function? I imagine if it is finite differencing, jacobian information is still correctly handled, as long as the function is smooth. If it is symbolic, how do you imagine getting around tabular data?

It is closest to being symbolic...it uses the analytic derivative at every operation. So it is perfectly exact, which finite differencing is not. For tabular data, you have to do some work. If you want perfect derivatives you'd need to use an interpolation object like `SplineInterpolation` or `LinearInterpolation` that has a `sampleDerivative` method. Then say if you've coupled in the coupled variable `_T`, then you would do something like:
```c++
_some_prop[_qp].value() = _linear_interpolator.sample(_T[_qp].value());
_some_prop[_qp].derivatives() = _linear_interpolator.sampleDerivative(_T[_qp].value()) * _T[_qp].derivatives();
```

**Comment by tophmatthews** [comment]
Awesome, thanks for the insight!

**Comment by bwspenc** [comment]
If AD constraints really are in the near future, maybe we should be looking into how to convert the current system over to constraints. Based on my experience with mechanical contact, it will simplify things quite a bit -- it will just require a single Constraint object, rather than a hodgepodge of other objects strung together.

**Comment by tophmatthews** [comment]
@bwspenc There is already `GapConductanceConstraint` in the heat conduction module I think added by @andrsd way back when? How does that perform?

**Comment by tophmatthews** [comment]
ping @bwspenc, do you know how `GapConductanceConstraint` does compared to the current "Action" system for thermal contact?

**Comment by bwspenc** [comment]
@tophmatthews Sorry for the late reply.  I didn't even know that existed. It looks like that is based on the current Mortar constraint system in MOOSE, which requires the user to provide a reduced dimensionality mesh between the two surfaces, and won't work with large displacements. While that is helpful for some problems, the fact that it doesn't update the mortar space automatically won't work for us.

What I had in mind is a system that would do evolving node/face constraints like what we use now, but using the Constraint system. That would be an intermediate solution until we get a fully functional mortar system in place.

**Comment by tophmatthews** [comment]
@bwspenc Thanks for the insight Ben. I'll finish up cleaning the actions as they stand, but leave the full conversion to Constraint to you guys? Let me know how I can help the process along, since the thermal contact is the last thing before getting all of the temperature solve in as AD for bison runs.
