### ISSUE TITLE
Create ADKernelValue and ADKernelGrad 

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12658]
## Rationale

The `KernelValue` and `KernelGrad` classes provide a `precomputeQpResidual` method to override which computes the part of the residual that is independent of the test function index `_i`. That result is then multiplied by all test functions (or their gradients respectively). This approach allows a loop reordering causing the residual to be re-computed significantly fewer times. This optimization would be even more significant in the AD system when in the JACOBIAN compute stage.

## Description

Implement intermediate base class templated that replicate the loop reordering optimization of `KernelValue` and `KernelGrad`.

## Impact

Faster kernel evaluation for residuals which allow the test function or the test function gradient to be factored out.

Tag @lindsayad

**Comment by tophmatthews** [comment]
@dschwen So when should this be used , and where should regular `Kernel` be used? Should this always be used?

**Comment by lindsayad** [comment]
IMO this should always be used. There are kernels out there that have both `_test` and `_grad_test` terms but it is our MOOSE mantra that things should be as modular as possible with ideally a single kernel representing a single PDE term. If that is done, then either the `ADKernel`Grad` and `ADKernelValue` classes can be used every time
