### ISSUE TITLE
An issue in app.mk executable rule?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12666]
## Rationale

If users specify `ADDITIONAL_LIBS`, the libraries may depends on a library in its build but the same library exists in the system library folder. So if we add `$(ADDITIONAL_LIBS)` at the end of linking rule, the linker will pick up the system library instead of the one suitable to the additional lib.

## Description

One solution is to move `$(ADDITIONAL_LIBS)` in front of `$(libmesh_LIBS)`. This fixes an issue in Rattlesnake for compiling a GUI application.

## Impact
Should no impact to current framework and applications.

**Comment by permcody** [comment]
This is probably OK. We have a few applications that use ADDITIONAL_LIBS though. Give me a chance to test this out.

**Comment by permcody** [comment]
Haven't checked yet. I'll get back to you.
