### ISSUE TITLE
Make path lookup in MD links require complete file/directory names

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12673]
## Rationale

Currently we allow a link `[Mass Lumping](lumping.md)` to resolve to `mass_lumpiung.md`. While this is superficially convenient it is both confusing and infuriation when adding new pages causes errors due to ambiguous lookups. 
We're having a bunch of those as we are adding AD versions of existing kernels and materials (with the same name - only prefixed with AD). This breaking unrelated doc pages is inconvenient.
There is also no reason that linking to `[Kernel](Kernel.md)` should cause ambiguity with `AuxKernel.md`.

## Description

Let's not match partial file names but only partial paths where the _segments_ themselves are complete. I.e. `[Kernel](Kernel.md)` will behave like `[Kernel](/Kernel.md)` once implemented.

## Impact

Make documentation paged more robust and enforce proper specification of link targets (e.g. discourage `[Terminator](nator.md)`)

**Comment by tophmatthews** [comment]
Doesn't `[Kernel](/Kernel.md)` help this? I think that the slash makes it that the whole file name is `Kernel.md`. I guess that can fail if you have two `Kernel.md` files.
