### ISSUE TITLE
Exodiff like summary report for CSV Differ tool

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#12682]
## Rationale
Request for a similar output style like Exodiff.

## Description
The csvdiff tool should output a summary report more similar to an exodiff report. Even though some of the output may not make sense if you had no idea what an Exodiff summary was.

But, because we are already printing information relating to what an Exodiff summary outputs, we might was well bring them closer together.

## Impact
None

**Comment by milljm** [comment]
tagging @bwspenc

**Comment by milljm** [comment]
proposed changes would create summaries like the following:

```
csvdiff.py -s a
TIME STEPS relative 5.5e-06 floor 1e-11  # min: 0 @ t0  max: 0 @ t1

GLOBAL VARIABLES relative 5.5e-06 floor 1e-11
    all                       # min: 7.000e+00 @ t0          max: 7.000e+00 @ t0
    bottom                    # min: 1.200e+00 @ t0          max: 1.200e+00 @ t0
    right                     # min: 2.300e+00 @ t0          max: 5.300e+00 @ t1
    time                      # min: 0.000e+00 @ t0          max: 5.000e-01 @ t1
```

**Comment by bwspenc** [comment]
Yes, that's exactly what it should look like.  I assume this will also involve more than just changing what running with `-s` generates, because csvdiff.py will also need to read this updated syntax.

**Comment by milljm** [comment]
It already does... It never cared about any other key words other than what proceeded directly after 'relative, abs_zero, floor, keywords etc). Is why this is a very simple PR.

I did find a mistake with TIME STEPS though. It appears I was searching for the phrase 'time step', not the plural grammatical version.

And... that the parser function was _not_ ignoring possible commented fields. I have another push I am working on for these two issues.
