### ISSUE TITLE
Odd API for MooseApp::restore()

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#12692]
## Rationale

MooseApp::restore() is actually two methods in one:
1) restore
2) don't restore, just cache

It appears that you choose which action to take based on the existence of an Executioner? This doesn't make sense and should be cleaned up. 

I propose a design where restore (the virtual that needs to be overridden by end user apps) should just restore. The caching mechanism should be a different (internal) function.

## Description

The Redcrab App Restore doesn't work properly during a "disk" restore (or recover). As I dug in, I realized that the API is just odd. It appears that you can't (shouldn't?) restore during the first call to restore upon startup. Multiapp::createApp() calls MooseApp::restore(), which knows to just save off the backup and use it later. As an end user, this is pretty confusing that you have to know to do two different things in one function. This should be changed.

## Impact

Moderate: user facing API that needs to be changed.

**Comment by permcody** [comment]
@friedmud - Any comments here? Does this sound right? I think I'll take a stab at adding a new method that will handle the caching portion of this function so that end users don't run into issues when they actually implement restore.

**Comment by friedmud** [comment]
Good luck.

This is like this because of the order of initialization of the master app and MultiApps.

The master has to get restored earlier than the MultiApps can be.

**Comment by friedmud** [comment]
That said - I'm sure the externally facing API can be easily cleaned up.  Just make a `baseRestore()` or something that does the caching or calls `restore()` for instance.
