### ISSUE TITLE
Add template aliases for Types that automatically are dual when needed

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12719]
## Rationale

Writing ADMaterials and ADKernels choosing the right local type that is either dual in the JACOBIAN stage or non-dual in the RESIDUAL stage requires a tedious and long type specification:

```
typename RealType<compute_stage>::type a;
typename RankTwoTensorType<compute_stage>::type b;
```

(`typename` is always required for dependent name resolution here).

## Description

I propose (after discussing this with @lindsayad) that we repurpose `ADReal`, `ADRankTwoTensor`.. to be a template alias that automatically does the right thing.

In framework code (Assembly etc.) we can make this a typedef that is always dual (that usecase is different from the materials and kernels which are downgraded to non-dual when the derivatives are not required). I think this would make the code very readable and is in line with other `ad` prefixes that we already use in the kernels and materials systems

## Impact

More concise and readable code.

**Comment by lindsayad** [comment]
Seems like this was closed by #12721
