### ISSUE TITLE
Website missing topbar using ./moosedocs.py build

### ISSUE THREAD

**Issue by veeshy** [idaholab/moose#12717]
## Rationale
Website renders nicely only when --serve flag is used. Without it, the site misses the topbar. Tested on a the heat conduction app as well as my local app

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/5826161/51277756-59409a80-198d-11e9-8adc-d4b3035baa4c.png">

## Description

Running in doc folder,
```./moosedocs.py build```
leads to this issue, but adding the `--serve` flag gives what is expected

## Impact

I serve our doc website from our tester on a local network so I was only using the build cmd to get the site to write to ./local/share/moose/site, I have a hack that runs the --serve cmd and times out after some time so that the local site writes correctly but this hack is not useful to the moosedocs. Sorry I don't know the last moose commit that this worked on.

**Comment by aeslaughter** [comment]
The only reason for this might be that I changed the location of the main website to /modules/doc, it was in combined. So, running the following should do the trick, it works on my machine:

```bash
cd moose/modules
make -j12 
cd doc
./moosedocs.py build --serve
```


```bash
$ git log
commit 0ea1a2d93a3466e2d1f2649b38db5a5e2121ffb4 (HEAD -> devel, upstream/devel)
Merge: 0392cf1fef 56c895afa6
Author: Derek Gaston <friedmud@gmail.com>
Date:   Wed Jan 16 17:33:15 2019 -0700
```
![untitled](https://user-images.githubusercontent.com/341333/51337410-450ba480-1a44-11e9-8fab-a9c467f41c51.png)

**Comment by veeshy** [comment]
Hm, I can't recreate this issue with the modules/doc. I compared my config.yml with the module/doc one and saw my menu was under a different context than the modules/doc one, updated it and now I think I've resolved the issue I reported on my end too with my app.

**Comment by veeshy** [comment]
I’m closing this as user error, the website functions as expected when the right config was used. Thanks for trying to recreate on your end!
