### ISSUE TITLE
MeshGenerator system needs some serious DistributedMesh fixups

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#12775]
## Rationale

The MeshGenerator system doesn't seem to work at all with DistributedMesh, even in cases where equivalent DistributedMesh-friendly MooseMesh and MeshModifier objects do work. These need to be fixed up. Reference this ticket for those cases. 

## Description

Run any MeshGenerator tests with DistributedMesh

## Impact

Moderate: New system will eventually replace existing system and needs to be functional with DistributedMesh

**Comment by permcody** [comment]
FYI @friedmud

**Comment by lindsayad** [comment]
This is for the simple reason that `MeshGenerators` are executed before we've added any geometric ghosting functors. So if any mesh generators rely on non-local elements (beyond possibly libmesh's default geometric ghosting functor), they're screwed!

**Comment by lindsayad** [comment]
Superseded by #14329

**Comment by lindsayad** [comment]
Noting that at this time, geometric relationship managers are now added before mesh generators, and mesh generators get those geometric rms added to them
