### ISSUE TITLE
package_version is not being honored

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#12776]
## Rationale
MOOSE PR's should honor the package_version file.

## Description
An update to the moose-environment package is triggering MOOSE PRs to use that version, when in fact, civet should be honoring $MOOSE_DIR/package_version

Going to use this PR to invalidate targets, until I can figure out how to solve this.

## Impact
For now, none. As there were no library stack changes from package version 179 to 182.

**Comment by permcody** [comment]
@milljm - This isn't an issue right? We understand how this works now. Maybe we should document this a bit and close this issue.

**Comment by milljm** [comment]
Compiler stacks are used in the following order:

- moose/package_version
- civet_recipes/scripts/env.sh (we will call this civet)
- $HOME/singularity/bind_paths/configs/release_build_CONTAINER (we will call this singularity)

Let's use [target](https://civet.inl.gov/job/426855/) as an example. As this target is using two different versions (at the time of that PR).

The 'Clean Machine' target does not use a compiler stack. Does not ask for one, and for obvious reason, moose/package_version isn't available. So this target will use what singularity is set for.

The 'Fetch and Branch' target does not use a compiler stack. But it does ask for one _after_ it clones/branches the repo. Until it finishes cloning/branching the repo however, it uses singularity. Once complete, and in the case of the MOOSE repo, moose/package_version becomes available. And thus instructs Civet to use what ever is set in this file. If moose/package_version is _not_ available (as is the case for any repo other than MOOSE), it then asks civet for a version.
