### ISSUE TITLE
MultiApp transfer between meshes with different spatial extent

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#12770]
## Rationale

For multiscale simulation, it is common to combine a coarse-mesh solution of a domain (the mesoscale) with several fine-mesh solutions over smaller regions of the domain (the microscale). It would be advantageous to be able to view the microscale solution on the mesoscale mesh, which requires an interpolation between meshes defined on different spatial extents. From my understanding, the `MultiAppInterpolationTransfer` interpolates between different meshes assuming the same spatial extent.

## Description

Create a new multiapp transfer that transfers a variable defined on one mesh to another, where the meshes do not necessarily exist over the same range in space. For example, a mesoscale mesh may exist over `0 < x < 1`, while a microscale mesh may exist over `0 < x < 0.1`, and is positioned at `x = 0.4` within the mesoscale mesh. The transfer should be able to interpolate the variable defined on the microscale mesh to a variable defined on the mesoscale mesh. For this example, this would look like the microscale solution centered at `x = 0.4` in the mesoscale mesh, with a value of zero for `x < 0.35` and `x > 0.45` because the microscale variable is only defined over a spatial range that is 0.1 in width.

I have attached a simple input example for a 2-D domain. The `mesoscale.i` file solves over `0 < x < 1` and `0 < y < 1` and has a sub app microscale solution in `particle.i` that solves over `0 < x < 0.1` and `0 < y < 0.1`. The microscale solution should interpolate into a variable defined on the mesoscale mesh, which should look like a square of width 0.1 centered at `x = 0.2`, `y = 0.4` with values equal to the microscale solution, and zero outside of this range.

## Impact

Improved visualization of multiscale solutions without needing to write external scripts for visualization. Additional documentation required.

**Comment by aprilnovak** [comment]
[example.zip](https://github.com/idaholab/moose/files/2797611/example.zip)

**Comment by GiudGiud** [comment]
This should be possible with the coordinate transfer system that we are getting in https://github.com/idaholab/moose/pull/20451

**Comment by GiudGiud** [comment]
@aprilnovak #20451 got merged. You should be able to scale (and rotate and translate) multiapps meshes to match physical domains on the main app using the coordinate transform system

Do you want to try this out to decide if this can be closed?

**Comment by GiudGiud** [comment]
Closing as addressed by #20451
