### ISSUE TITLE
Add Green-Lagrange strain calculator to TensorMechanics

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12787]
## Rationale

The Green-Lagrange strain _E_ is uses in hyperelastic models like the Saint Venant - Kirchhoff model. It allows the computation of the Second Piola-Kirchhoff  stress, which should - in conjunction with solving the stress divergence equation on the _undisplaced_ mesh - result in a working total large deformation hyper elastic model.

## Description

Add a cartesian Green-Lagrange strain calculator.

## Impact

Added capability.

**Comment by GiudGiud** [comment]
@dschwen can this be closed now?

**Comment by dschwen** [comment]
No, let's wait 3 more years :-D.

Actually I think I already implemented it

**Comment by GiudGiud** [comment]
nice. Commits say you did. Closing
