### ISSUE TITLE
Need a way to identify the hardware node-name as an Aux Field

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#12788]
## Rationale

When things are going wrong - it would be useful to be able to know the actual node-name in the cluster that a part of the simulation is running on.

## Description

I propsose adding two things to the `RankMap`: `hostname` and `hostname_id`.  `hostname` is just what it sounds like... but `hostname_id` will be a numerical identifier made from the hostname.

The way that will work is that it will be constructed of pulling out all of the numbers out of the hostname.

So... 

On Lemhi:
`lemhi0023 -> 23`

On Falcon:
`r2i2n5` -> `225`

This will allow the value to come out in VectorPostprocessors and viewed in Auxiliary fields.

## Impact

New capability

**Comment by friedmud** [comment]
Also need to know the local RankID (i.e. the local MPI rank).

**Comment by permcody** [comment]
Closed by https://github.com/idaholab/moose/pull/12630
