### ISSUE TITLE
Create mirror partitioner

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#12799]
## Rationale

We need a `MirrorPartitioner` that can ensure things like:

- Exact same partitionings for un-displaced and displaced meshes
- Exact same partitionings for multi-apps running on the same mesh

## Description

It's currently possible (see this thread [here](https://groups.google.com/forum/#!topic/moose-users/RI-2ZEiKzms)) to get different partionings for different runs of METIS in parallel. (Hypotheses for why this is: random number generation and different order of non-blocking MPI communications).

## Impact

We won't get random failures for the above listed scenarios any more.

**Comment by permcody** [comment]
I might recommend calling it "CopyPartitioner"? We have a few other objects named "Copy", which maintain parody with the other object that they are working with.

**Comment by permcody** [comment]
... or parity if that works, your choice:

![image](https://user-images.githubusercontent.com/3036960/52018322-3d69e800-24a7-11e9-9417-373f263c42c5.png)

**Comment by YaqiWang** [comment]
@snschune do you want to make a comment on this? In our NDA implementation, if the mesh of the low-order system is coarser than the mesh of high-order system (a multiapp), we have to ensure all elements of the high-order mesh must be on the same processor of their low-order elements. We had to create a custom partitioner for this, but I cannot remember what exactly we did. When the meshes are the same, we always assume the partitioning of the two meshes are the same.

**Comment by lindsayad** [comment]
> When the meshes are the same, we always assume the partitioning of the two meshes are the same.

In parallel we have demonstrated that this is unfortunately not the case when using METIS
