### ISSUE TITLE
Prettify information report about subapp runs

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12806]
## Rationale

This issue was raised by @gleicher27 who practice multiphysics coupling calculations a lot. We can use this issue for making the output for these kinds of calculation prettier.

## Description

So far, we possibly can create a vector postprocessor to report time steps a sub-application takes during sub-cycling. Residual norms of subapps before and after they are solved are the important information about the Picard convergence, thus we might want to highlighting them in some way. There will possibly more we can think of.

## Impact
Improved user experience.

**Comment by YaqiWang** [comment]
Another thing I noticed is that when we have lots of subapps, the screen output is pretty messy. Things will get even worse if we have multiple levels of subapps. We should think of a way to trim down outputs of subapps so that we can stay focused on important messages from subapps. I do not have very good implementation suggestions though.

**Comment by permcody** [comment]
Closed by #13282
