### ISSUE TITLE
Update Hertz contact heavy regression tests

### ISSUE THREAD

**Issue by acasagran** [idaholab/moose#12831]
## Rationale

The original versions of these tests used volumetric locking with quad8 elements. Recent work has shown that quad8 elements are more accurate without volumetric locking and these problems also demonstrate this behavior.

## Description

Regold the solutions for the Hertz contact regression tests using the results without volumetric locking which are more accurate compared to the analytical solution.

## Impact

Improves the results for this set of contact regression tests.

**Comment by permcody** [comment]
Closed by #12834.
