### ISSUE TITLE
Need ThreadedNodeLoop

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#1287]
Should work like ThreadedElementLoop... make all nodal loop functors inherit from it.

**Comment by friedmud** [comment]
This has risen in priority due to #5815

**Comment by permcody** [comment]
@friedmud  - I was just looking this over and poking around. I can't see much reason for both `ThreadedElementalLoopBase<>` and `ThreadedElementalLoop<>`. The former class is only the ancestor of one class, it contains no virtuals and is doesn't contain any abstraction that can't be merged into the latter class. Clearly this isn't critical but it looks like this is a good candidate for merging prior to implementing this new class.

**Comment by friedmud** [comment]
The difference has to do with FEProblem.  ThrededElementLoop _has_
FEProblem... while ThreadedElementLoopBase does not.  There is somewhere in
the code where we need to do an element loop but don't have access to
FEProblem (or at least, there was at one time).

Definitely something that could be handled as part of this work...

**Comment by permcody** [comment]
Oh I see CachedChangeListsThread in MooseMesh... Ok, that's the one place.

**Comment by friedmud** [comment]
Yeah - Doesn't look like MooseMesh has access to an FEProblem.
