### ISSUE TITLE
AD boundary conditions for Tensor Mechanics problems

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12903]
## Rationale

Add AD enabled versions of BCs commonly used in tensor mechanics.
- Pressure
- PresetBC
- FunctionPresetBC

## Description

To improve Jacobians AD enabled versions of the above BCs should be added (in particular Pressure, which runs on the displaced mesh will benefit).

## Impact

Better Jacobians

**Comment by tophmatthews** [comment]
Closed via #13261
