### ISSUE TITLE
Add a new input parameter to control Picard iteration

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#12939]
## Rationale

There are cases where a number of Picard iteration is desired but not treated as unconverged. There are also cases where users want only their own custom convergence check and want to avoid the extra not-so-cheap residual evaluations.

## Description

To support these cases, a new input parameter to control Picard iteration can be added, with a name like `disable_picard_residual_norm_check`. Its default value is false, but when it is true, no residual norm will be evaluated and `picard_rel_tol`, `picard_abs_tol` and `picard_force_norms` will be inactive and reaching the maximum number of Picard iterations will be treated as converged. This parameter allows more flexible control on the Picard iteration.

## Impact
A new capability that does not have impact on the current codes.

**Comment by permcody** [comment]
Is this really the behavior we want? "Disabling the check altogether"? I was under the impression that you wanted to be to move forward when _either_ the Picard convergence was reached or you hit max its. What if you are actually converged after a single iteration, won't this force additional solves that won't really help?
