### ISSUE TITLE
MultiAppMeshFunctionTransfer uncorrectly gives a 0 value at a boundary node

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#12947]
## Rationale

I have a 3-D mesh with multiple 1-D channels to which I want to transfer a variable `T_wall`. As a test, I am setting it to a quadratic function `40*x*(5.22-x)+668` but get the following on the subapp:

![twall](https://user-images.githubusercontent.com/17411984/53197320-29616400-35d7-11e9-9f9b-a7feb23ec9b5.png)

For some reason, the node at `x=0` gets a zero value.

## Description

The branch [here](https://github.com/vincentlaboure/moose/tree/issue_MultiAppMeshFunctionTransfer/test/tests/transfers/multiapp_mesh_function_transfer/issue) has a working example to reproduce the issue.

I was not able to reproduce it with a GeneratedMesh so the mesh is in that same folder. A couple observations that may help diagnose the problem:

1. A dirty workaround is to make the sub-app mesh start at 0.001 instead of 0

2. the subapp is located in the middle of an hexagon, i.e. is on interfaces between elements 

3. If I use more than one channel (all in the middle of an hexagon - e.g. use `centers_relap.txt` in the aforementioned branch), only some of the channels have this erroneous behavior.

## Impact

Make `MultiAppMeshFunctionTransfer` more robust.

**Comment by fdkong** [comment]
@vincentlaboure Thanks for your reports, here. I finally have a chance to look at this. 

Could you possible make this test as a pure-moose test? Your example looks requiring `Relab` and `SabertoothApp`.

**Comment by fdkong** [comment]
Does not look like I can reproduce this issue. Everything is running smoothly on my machine. Are you using some ancient moose?

I have T_wall transfer correctly without any issue. 

![twall_transfer](https://user-images.githubusercontent.com/10508374/54154084-b47b9000-4406-11e9-8dde-7d57bee3271e.png)

**Comment by fdkong** [comment]
I made small change on the input file:

```
diff --git a/test/tests/transfers/multiapp_mesh_function_transfer/issue/moose_modules_transient.i b/test/tests/transfers/multiapp_mesh_function_transfer/issue/moose_modules_transient.i
index 9b5af7da9f..5c112cf8df 100644
--- a/test/tests/transfers/multiapp_mesh_function_transfer/issue/moose_modules_transient.i
+++ b/test/tests/transfers/multiapp_mesh_function_transfer/issue/moose_modules_transient.i
@@ -87,9 +87,10 @@ all_blocks = '
     specific_heat = 1700.0
   [../]
   [./graphite_density]
-       type = Density
-       density = 1800
-       block = '${all_blocks}'
+    type = GenericConstantMaterial
+    prop_values = 1800
+    prop_names = density
+    block = '${all_blocks}'
   [../]
 []
 
@@ -130,7 +131,7 @@ all_blocks = '
 [MultiApps]
   [relap]
     type = TransientMultiApp
-    app_type = SabertoothApp
+    app_type = HeatConductionApp
     positions = '0 1.24707658145 0.0'
     # positions_file = 'centers_relap.txt'
     input_files = 'relap.i'
```

**Comment by vincentlaboure** [comment]
@fdkong Thank you for looking at this!

The MOOSE I used was from Feb 21 so it was the latest at the time. What did you use to run this problem? Did it include RELAP-7? So far, I haven't been able to reproduce this without it but I can take another look.

**Comment by fdkong** [comment]
@vincentlaboure, Please let me know once you figure out how to reproduce this issue.

**Comment by fdkong** [comment]
Close now. If @vincentlaboure  can reproduce this issue, we can reopen it.  The code is just running fine right now.
