### ISSUE TITLE
Conservative transfers

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#12948]
## Rationale

Some customers are increasingly requesting conservative transfers.

## Description

A (scalable and transfer-agnostic) option could perhaps be to specify - in the `Transfers` block - the postprocessors on both the master and sub app that should match. The target fields could then be scaled using the ratio of these postprocessors.

## Impact

Key quantities of interest could be preserved during transfers.

**Comment by YaqiWang** [comment]
My understanding: what @vincentlaboure wants are two more parameters in the transfer base class
```
postprocessor_to_be_preserved_on_master_side = 'pp_on_master'
postprocessor_to_be_preserved_on_subapp_side = 'pp_on_subapp'
```
When a transfer is done, on the *to transfer* side, do a postprocessor evaluation, get one scalar value `v2`, then use the ratio between the *from transfer* side postprocessor value `v1` and `v2` as a scaling factor to redo the transfer (assuming `v2` is linear). This sounds simple but can be quite complicated.

**Comment by fdkong** [comment]
Looks like we need to execute     `postprocessor` twice. But we only trigger this when users speficy to use the conservative transfer.

**Comment by vincentlaboure** [comment]
@fdkong Thanks for looking at this! @YaqiWang's summary seems accurate. 

I think a good test problem could be as follows:

Master app defined for 0 < x < 1, 0 < y < 1; block 0 for 0 < x < 0.5, block 1 for 0.5 < x < 1
Sub app defined for 0 < x < 0.5, 0 < y < 1; block 10 for 0.2 < x < 0.3 and 0.2 < y < 0.8, block 11 otherwise
Two sub abbs: `positions = '0 0 0 0.5 0 0'`

The goal would be to:
- Transfer power density field `p` from master app block 0 to sub app 0, block 10 such that `\int_{master, block 0} p dx = \int_{sub0, block 10} p dx`
- Transfer power density field `p` from master app block 1 to sub app 1, block 10 such that `\int_{master, block 1} p dx = \int_{sub1, block 10} p dx`

- Transfer power density field `q` from sub app 0, block 10 to master app block 0 such that `\int_{master, block 0} q dx = \int_{sub0, block 10} q dx`
- Transfer power density field `p` from sub app 1, block 10 to master app block 1 such that `\int_{master, block 1} q dx = \int_{sub1, block 10} q dx`

A first step might be to do that same problem without block restriction on the sub apps.

Does this make more sense? If you want, I can create some input files for that proposed test problem.

**Comment by fdkong** [comment]
> @fdkong Thanks for looking at this! @YaqiWang's summary seems accurate.
> 
> I think a good test problem could be as follows:
> 
> Master app defined for 0 < x < 1, 0 < y < 1; block 0 for 0 < x < 0.5, block 1 for 0.5 < x < 1
> Sub app defined for 0 < x < 0.5, 0 < y < 1; block 10 for 0.2 < x < 0.3 and 0.2 < y < 0.8, block 11 otherwise
> Two sub abbs: `positions = '0 0 0 0.5 0 0'`
> 
> The goal would be to:
> 
> * Transfer power density field `p` from master app block 0 to sub app 0, block 10 such that `\int_{master, block 0} p dx = \int_{sub0, block 10} p dx`
> * Transfer power density field `p` from master app block 1 to sub app 1, block 10 such that `\int_{master, block 1} p dx = \int_{sub1, block 10} p dx`
> * Transfer power density field `q` from sub app 0, block 10 to master app block 0 such that `\int_{master, block 0} q dx = \int_{sub0, block 10} q dx`
> * Transfer power density field `p` from sub app 1, block 10 to master app block 1 such that `\int_{master, block 1} q dx = \int_{sub1, block 10} q dx`
> 
> A first step might be to do that same problem without block restriction on the sub apps.
> 
> Does this make more sense? If you want, I can create some input files for that proposed test problem.

Sounds good for me. 

@vincentlaboure, please create some input files, and added to my PR #13060. I will take care of them.

**Comment by vincentlaboure** [comment]
@fdkong I created a branch showing input files that should make a really good test. I am aware that this might not be a trivial task but it would extremely useful for us and our customers.

Please let me know if you have any questions about it.

**Comment by vincentlaboure** [comment]
The input files are [here](https://github.com/vincentlaboure/moose/commit/a8c8dcce47bec8ccd11d5ef69087b55bb9cd4cca)
