### ISSUE TITLE
Introduction of units into MemoryUtils broke VectorMemoryUsage

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12951]
## Rationale

`MemoryUtils::getMemoryStats()` functions now take a "unit" (actually what they really take is a _unit prefix_, which on top of all uses the wrong kilo,mega,giga instead of kibi,mebi,gibi). VectorMemoryUsage also uses `MemoryUtils::getTotalRAM()` which does _not_ take a memory unit prefix.

## Description

I don't like this design. The helper functions that wrap the OS calls to obtain memory sizes should just always return size in bytes. If you want to output in kibi bytes or whatever then the conversion should be done at output time. The way it is now the code is dividing bytes and mebibytes to get a node utilization.

## Impact

Fix wrong output. Tagging @permcody who messed this up. I'll fix it.

**Comment by permcody** [comment]
You mad bro?

**Comment by friedmud** [comment]
![1e1d1e409907ec8c1a793df5c06d1e19](https://user-images.githubusercontent.com/870705/53267030-a0fac600-369f-11e9-9629-fab1f46b14f0.png)
