### ISSUE TITLE
Fix --dump and --json for AD objects

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#12960]
## Rationale

The `--dump` and `--json` options for MOOSE apps output two entries for each AD object, one with a `<RESIDUAL>` postfix and one with a `<JACOBIAN>` postfix. Yet neither version is accepted in the input file, only the name without a (C++ template) postfix is.

## Description

Output only one copy for each AD object syntax - without the template parameter junk. That's what is expected in the input files. The template junk currently breaks auto completion and makes generated Documentation files look awkward.

## Impact

Better syntax output.

**Comment by permcody** [comment]
Well this didn't work at all... Reopening...

This was re-reported by @lefebvrera today. Should be a really quick fix. I'm not sure why this previous attempt didn't work but I'm seeing brackets on all of the AD objects still.

**Comment by lefebvrera** [comment]
@mbairdphys this is the issue we were discussing earlier.

**Comment by permcody** [comment]
closed by https://github.com/idaholab/moose/pull/13476
