### ISSUE TITLE
Dynamic loading tests looking for non-existent libraries

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#12974]
## Rationale

The dynamic loading tests in the `misc` module look for the `phase_field` and `tensor_mechanics` libraries, but doesn't require them to be compiled when `misc` is being built. This likely flew under the radar because everyone always has `phase_field` and `tensor_mechanics` already compiled, thus the tests work just fine. If you compile _only_ the `misc` module, it will look for libraries that are not there.

## Description

```
cd ~/projects/moose/modules/
make clobberall
cd ~/projects/moose/modules/misc
make -j4
./run_tests -j4
```
Will result in several failures:
```
test:dynamic_loading/dynamic_obj_registration.dynamic_object_loading_syntax: *** Warning ***
test:dynamic_loading/dynamic_obj_registration.dynamic_object_loading_syntax: Unable to open library file "../../../../../phase_field/lib/libphase_field-opt.la". Double check for spelling errors.
```
```
test:dynamic_loading/dynamic_obj_registration.dynamic_object_loading_wrong_app: *** ERROR ***
test:dynamic_loading/dynamic_obj_registration.dynamic_object_loading_wrong_app: Unable to open library file "../../../../../tensor_mechanics/lib/libtensor_mechanics-opt.la". Double check for spelling errors.
```
```
test:dynamic_loading/dynamic_obj_registration.dynamic_object_loading: *** Warning ***
test:dynamic_loading/dynamic_obj_registration.dynamic_object_loading: Unable to open library file "../../../../../phase_field/lib/libphase_field-opt.la". Double check for spelling errors.
```
```
test:dynamic_loading/dynamic_load_multiapp.dynamic_load: Unable to locate library for "PhaseFieldApp".
test:dynamic_loading/dynamic_load_multiapp.dynamic_load: We attempted to locate the library "libphase_field-opt.la" in the following paths:
```

## Impact

"More better" testing.

**Comment by permcody** [comment]
Yeah, we are aware of this. Are you proposing that we add a check in the test harness that will gracefully skip these tests in that case? Normally we run "make test_subs" which builds every module prior to running the tests. The error messages here are normal and expected when you build just the one module so what would you like to see?

**Comment by tophmatthews** [comment]
I'm not suggesting anything, just making note of it, but it sounds like you are already aware.
