### ISSUE TITLE
MooseDocs does not align expansion arrows with text

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#12987]
## Rationale

The expansion/collapse arrows in MooseDocs appear *above* the section text for which content is being expanded/collapsed, which is misleading and visually unappealing. It would be best if the arrow *alongside* the header text, but if that's not possible, it would be at least be an improvement to move it *below* the text.

## Description

View an object's documentation page. An example is attached: 
![expansion arrows](https://user-images.githubusercontent.com/23108676/53780767-1138f100-3ec3-11e9-99c3-41284be32900.jpg)
Personally, if for example, I want to expand the content for "Required Parameters", I would naturally click the second arrow instead of the first.

## Impact

Visual changes only.

**Comment by joshuahansel** [comment]
@aeslaughter Do you agree? If so, would it be an easy fix?

**Comment by aeslaughter** [comment]
I just saw this, can you point me to a page where this is happening?

**Comment by joshuahansel** [comment]
I can't find this anymore. It was on all pages of RELAP-7 documentation, for example. I don't know what happened to make it not occur anymore. I guess this can be closed until we run into it again, if we ever do. If so, I'll give better instructions on how to reproduce.
