### ISSUE TITLE
Update Getting Started instructions for module loading

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#12983]
## Rationale
An incoming change to the package will require an update to our Getting Started instructions.

## Description
We will no longer be loading the moose-dev-??? modules by default for every new terminal window opened.

Instead, our instructions will inform users _how_ to load modules. This should alleviate some of the issues we see when a user has other profiles ebbing their way into ours (homebrew, anaconda, etc). As well as preventing our installer from ebbing our way into their environments. -it will now be under the control of the user. Not us.

As a side benefit, it will introduce new users to the module system. Several times we have had to instruct users about 'there is already a module for this' (VTK for example).

## Impact
Peoples workflow in how they do things will change. Might cause some new emails on the mailing list.

**Comment by permcody** [comment]
We have reversed our decision on this. We still load modules. However, we've also added information to the Getting Started pages about how to load modules (e.g. loading the profile, then loading the module(s)).
