### ISSUE TITLE
MooseDocs does not support \newcommand

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13002]
## Rationale

It would be advantageous to be able to use `\newcommand` to define LaTeX commands to be used in MooseDocs-generated documentation. 

## Description

Try to use `\newcommand` in a MooseDocs page.

Note that the KaTeX extension used by MooseDocs should provide API to achieve the desired feature.

## Impact

New MooseDocs feature.

**Comment by aeslaughter** [comment]
closed by #13114
