### ISSUE TITLE
Scalar variable initial_from_file_var?

### ISSUE THREAD

**Issue by veeshy** [idaholab/moose#13040]
## Rationale

Should moose be able to read IC from file for scalar variables? If so, this is a bug report, if not this is a feature request. 

## Description

If this feature is thought to be possible, this patch in moose tests shows `test/tests/kernels/ode/ode_expl_test.i` fail if the coupled aux scalar variable uses `initial_from_file_var`.

[ode_expl_test_patch.txt](https://github.com/idaholab/moose/files/2958449/ode_expl_test_patch.txt)

## Impact

It would allow me to use IC from file when scalar kernels are involved in my sims. At the least, this is an unhandled error since MPI_Abort is called w/o a useful message.

It looks like if I used checkpoints I could get around this, however I prefer the IC from file approach since I'm not looking for a "restart"

**Comment by permcody** [comment]
I'm pretty sure that nobody has asked for that before. It's definitely possible to implement, it just hasn't been done.

**Comment by veeshy** [comment]
Oh, I see! Is this on the moose side or libmesh in the exo reader?

**Comment by permcody** [comment]
Probably the MOOSE side. Here's the relevant function that may need
additional work if you are so inclined:
https://github.com/idaholab/moose/blob/next/framework/src/systems/SystemBase.C#L913-L914

Also look at CopyNodalVarsAction:
https://github.com/idaholab/moose/blob/next/framework/src/actions/CopyNodalVarsAction.C
