### ISSUE TITLE
Evaluate Curl in MooseParsedVectorFunction

### ISSUE THREAD

**Issue by cticenhour** [idaholab/moose#13041]
## Rationale

When calculating the scattered electromagnetic field resulting from an incoming field wave, general absorbing boundary conditions often require both the value of the incoming field as well as its curl (see an absorbing BC example proposed in Jin's _The Finite Element Method for Electromagnetics_ 3rd Ed, Chapter 9). I have been using `MooseParsedVectorFunction` to define my incoming field for use in BC. Currently, it only provides the value of the field vector. I propose adding a `vectorCurl` virtual function to allow for the evaluation of the curl given user-provided curl components, similar to how the gradient is evaluated in `MooseParsedGradFunction`. 

## Description

A new `vectorCurl` virtual function would need to be added to the `Function` class, and overridden in `MooseParsedVectorFunction`. `_curl_value` and `_curl_function_ptr` would be added to store the input functions and point to the parsed function wrapper object for the curl. No changes should be needed in `MooseParsedFunctionWrapper` (I think). 

## Impact

New capability.

**Comment by permcody** [comment]
This seems alright to me. Can you possibly add a unit or regression test so that we hit those new lines of code?

**Comment by cticenhour** [comment]
Currently working on a test for it. Hopefully I can get the formal PR submitted today.
