### ISSUE TITLE
Generalize ADKernelSUPG

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#13044]
## Rationale
The SUPG term for the shallow water equations uses a SUPG term that takes a non-standard form.

## Description

Create ADKernelStabilized with ADKernelSUPG inheriting

ADKernelStabilized::computeResidual
```C++
for (_qp = 0; _qp < _qrule->n_points(); _qp++)
 {
    const auto value = precomputeQpStrongResidual() * _ad_JxW[_qp] * _ad_coord[_qp] ;
    for (_i = 0; _i < n_test; _i++) // target for auto vectorization
      _local_re(_i) += _grad_test[_i][_qp] * computeQpStabilization() * value;
}

ADKernelSUPG::computeQpStabilzation()
{
return _velocity[_qp] * _tau[_qp];
}

```

## Impact
Minimal, this class hasn't only been around for a few hours.

**Comment by aeslaughter** [comment]
@lindsayad What do you think of something along these lines?

**Comment by lindsayad** [comment]
Looks good to me
