### ISSUE TITLE
ThermalContact does not work with -r 1 uniform mesh refinement

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#13043]
## Rationale

It appears that `ThermalContact` does not work with uniform mesh refinement. 

## Description

No heat transfer across the gap if uniform mesh refinement is specified. Example:
```
/moose/modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/gap_conductivity_property.i
```

Execute using provided mesh:
```
../../../../heat_conduction-opt -i gap_conductivity_property.i
```
Report of average block temperatures, `temp_1` and `temp_2`:
```
+----------------+----------------+----------------+
| time           | temp_1         | temp_2         |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   3.214286e+02 |   3.785714e+02 |
+----------------+----------------+----------------+
```

Execute with `-r 1`:
```
../../../../heat_conduction-opt -i gap_conductivity_property.i -r 1
```
Average block temperatures:
```
+----------------+----------------+----------------+
| time           | temp_1         | temp_2         |
+----------------+----------------+----------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   3.000000e+02 |   4.000000e+02 |
+----------------+----------------+----------------+
```

These are the left and right boundary conditions, respectively, and hence the
solution you'd expect when you insulate the two blocks from each other. 

## Impact

Bug fix.

**Comment by snschune** [comment]
Digging a little bit shows that `_penetration_locator->_penetration_info[qnode->id()];`  fails
in `GapConductance::computeGapValues()`. After that it gets a bit involved.  

https://github.com/idaholab/moose/blob/86b5d3230b29d9bc7edf7478a961aa9a6aed1d9a/modules/heat_conduction/src/materials/GapConductance.C#L407

**Comment by permcody** [comment]
Yeah - this is a known issue. So I'm guessing you need this?

**Comment by snschune** [comment]
No, I'd refine by hand, but the code should at least error out and not just keep on going when 
it's about to inject garbage into your simulation.
 
If the actual fix is hard and you agree with what I said, I'd prep a PR doing that.

**Comment by snschune** [comment]
What is the verdict on this one? I think there should be at least a one-time warning if
garbage numbers are about to be introduced.

**Comment by permcody** [comment]
Sounds good to me - do you have time to throw up a PR?

**Comment by snschune** [comment]
Yeap.
