### ISSUE TITLE
Alert note title in MooseDocs not visible

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#13095]
## Bug Description

The background of the title section in an `!alert note` is white, so that the white text title is not visible. The background should be blue so that the heading can be seen, but it isn't getting set properly.

## Impact
Minor annoyance but looks simple to fix

**Comment by cpgr** [comment]
Yep, easy fix. I'll push a PR now.

**Comment by milljm** [comment]
@cpgr Can you provide a link to mooseframework.org where this is occurring? The annotations I am comparing your PR with, have is no visual difference. I am wondering if this is instead a browser issue. 

I'll accept the PR regardless, as it appears (to me), that this does not change anything noticeable on my end (Chrome, Firefox, Safari look just fine with your PR and the current Live version)

[Live](https://mooseframework.org/python/MooseDocs/extensions/alert.html) V's [Your PR](https://mooseframework.inl.gov/docs/PRs/13096/site/python/MooseDocs/extensions/alert.html)

**Comment by milljm** [comment]
I take that back. It looks wrong in Safari!

**Comment by cpgr** [comment]
Oh, I forgot to mention that it was Safari that this was broken in!
