### ISSUE TITLE
Ideal gas fluid properties can be inconsistent

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13118]
## Bug Description
When the (v,e) and (p,T) versions of `IdealGasFluidProperties` were merged via !12971, inconsistencies were introduced. Specifically, the user was given a myriad of options that have dependencies: `R` (specific gas constant, not universal), `gamma`, `cv`, `cp`, and `M`. Some manual checks override user-given parameters to try to ensure consistency, but some are missing.

As per the suggestion of @MatthiasKunick, I think the correct fix to all of this is to give the user exactly 2 parameters: `gamma` and `M`. The rest of the set can be computed from this set alone. This completely avoids any inconsistency in this set and simplifies input logic.

## Steps to Reproduce
Look at the implementation for `rho_from_p_T` and compare this to the combination of `e_from_p_rho` and `T_from_v_e`. The consistency condition you get is the following:
```
M/R = 1/(cv*(gamma-1))
```
You'll notice that the default values don't quite satisfy this; they are off by 1e-3. With non-default parameters, this has the potential to be even worse.

## Impact
This is important for any clients of `IdealGasFluidProperties`. Bad things can result from inconsistency.

**Comment by joshuahansel** [comment]
Just so I don't forget: the calculation sequence would be
```
R_sp = R / M
```
```
cp = gamma * R_sp / (gamma - 1)
```
```
cv = cp / gamma
```

**Comment by andrsd** [comment]
Tagging @cpgr

**Comment by MatthiasKunick** [comment]
All correct! Save computing time with cv=cp-R_sp
This is going to be a boost! (If that is the only calculation you perform.)

Outlook für iOS<https://aka.ms/o0ukef> beziehen

________________________________
Von: joshuahansel <notifications@github.com>
Gesendet: Dienstag, März 26, 2019 11:02 AM
An: idaholab/moose
Cc: MatthiasKunick; Mention
Betreff: Re: [idaholab/moose] Ideal gas fluid properties can be inconsistent (#13118)


Just so I don't forget: the calculation sequence would be

R_sp = R / M


cp = gamma * R_sp / (gamma - 1)


cv = cp / gamma

**Comment by aprilnovak** [comment]
Maybe this is already on your radar, but the ideal gas fluid properties with default settings (i.e. the user not specifying anything) gives inconsistent results. 

- `R_specific` is calculated by default as `286.7055103448276`
- `gamma` is calculated by default as `1.3997214484679665`
- but then if you calculate `cv` as `R/(gamma-1)`, you get `717.2632628138892` instead of the default `718`. 

This took me so long to debug :/

 @rwcarlsen FYI this is what was causing the bad convergence in MMS tests for Pronghorn AD updates.

**Comment by aprilnovak** [comment]
Maybe throw an error if the user doesn't specify some consistent set of inputs?

**Comment by cpgr** [comment]
I thought this was fixed? In any case, I would be in favour of removing the deprecated input parameters (R, cv & cp) and just setting them using the expressions above. I think that all of the tests were already updated to only use gamma and M.

**Comment by aprilnovak** [comment]
The problem is that a user can set:

`[FluidProperties]`
`  [./fp]`
`    type = IdealGasFluidProperties`
`  [../]`
`[]`

and no error will be thrown, but depending on which methods they call in their application, will get inconsistent answers for properties.

**Comment by cpgr** [comment]
Yep, but if cp, cv and R are removed as input parameters, no default values of these can be used so they have to be calculated during construction and will then be consistent?'

So the code would look something like
```
IdealGasFluidProperties::IdealGasFluidProperties(const InputParameters & parameters)
  : SinglePhaseFluidProperties(parameters),
    _gamma(getParam<Real>("gamma")),
    _molar_mass(getParam<Real>("molar_mass")),
    _R_specific(_R / _molar_mass),
    _cp(_gamma * _R_specific / (_gamma - 1.0)),
    _cv(_cp / _gamma),
    _mu(getParam<Real>("mu")),
    _k(getParam<Real>("k")),
    _T_c(getParam<Real>("T_c")),
    _rho_c(getParam<Real>("rho_c")),
    _e_c(getParam<Real>("e_c"))
{
}
```

**Comment by andrsd** [comment]
It is time to get rid of the deprecated params. People had enough time to update their input files.

**Comment by joshuahansel** [comment]
Yes, removing the deprecated parameters will fix all of this, but yes, in hindsight, there should have been some warning/error for that default value case that bypasses the deprecated parameter warnings.

**Comment by joshuahansel** [comment]
I will start the MOOSE PR for the deprecated parameters removal.
