### ISSUE TITLE
Change effective saturation to saturation in PorousFlow

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#13131]
## Reason

I believe that it is correct for PorousFlow to return **saturation** rather than **effective saturation** when using capillary pressure to compute saturation.

## Design

Currently the saturation calculators set the saturation equal to the effective saturation returned by the capillary-pressure user object.  Change this to plain-old saturation.

## Impact

This is potentially a significant change for users who employ a nonzero  ```sat_lr```.  I'm not aware of users doing this, however.  The saturation enters the relative permeability - so potentially a big change here - and also the fluid mass calculation, which is probably a smaller impact because we're computing time derivatives of saturation.

Before this change gets merged, i need @cpgr to agree it's the right thing to do.

**Comment by WilkAndy** [comment]
What a cool issue number

**Comment by cpgr** [comment]
Palindrome issue!
