### ISSUE TITLE
Add DenseMatrix<DualReal>

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#13146]
## Reason
For use in an ADMaterial I require a `DenseMatrix` templated on `ADReal`. However, there is no explicit instantiation on `DualReal` in libMesh yet.

## Design
Add an explicit instantiation of `DenseMatrixBase` and `DenseMatrix` on DualReal.
(This depends on libMesh/libmesh#2090)
Some Blas stuff will probably have to be template specialized to throw an error (and to provide a hook for a DualNumber-compatible custom implementation - such as the Cholesky solve).

## Impact
Use `DenseMatrix` calculations in ADKernels and ADMaterials

**Comment by dschwen** [comment]
I could probably just drop the explicit instantiations into `MooseTypes.C` ...

**Comment by dschwen** [comment]
@lindsayad, now that we have a libmesh update, are you proceeding with a PR for https://github.com/lindsayad/moose/commit/29250f6dd8 ?

**Comment by lindsayad** [comment]
Yea. Is it critical? Could it wait a couple days? If not, I'll get it done
