### ISSUE TITLE
Document PorousFlow tests

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#13155]
## Reason

For new users, and to demonstrate we have QAed the code, it would be nice to markdown-document the PorousFlow tests suite.  We currently have a fair bit of latex documentation and need to transfer to markdown, and build doco for the remainder of the test suite.

## Design

One thing is that i won't want this to be yet another burden on developers who create new tests.  So fully markdown-documenting new tests shouldn't be manditory.  Just doing the current set of tests will be an enormous improvement.  Todo:

- [ ] actions
- [ ] fluids
- [ ] numerical_diffusion
- [ ] adv_diff_bcs
- [ ] fluidstate
- [ ] plastic_heating
- [ ] aux_kernels
- [ ] flux_limited_TVD_advection
- [ ] poro_elasticity
- [ ] basic_advection
- [ ] flux_limited_TVD_pflow
- [ ] poroperm
- [ ] broadbridge_white
- [ ] functions	
- [ ] pressure_pulse
- [ ] buckley_leverett
- [ ] gravity
- [ ] radioactive_decay
- [ ] capillary_pressure
- [ ] heat_advection
- [ ] relperm
- [ ] chemistry
- [ ] heat_conduction
- [ ] rogers_stallybrass_clements
- [ ] density
- [ ] heterogeneous_materials
- [ ] sinks
- [ ] desorption
- [ ] jacobian
- [ ] thermal_conductivity
- [ ] dirackernels
- [ ] mass_conservation
- [ ] thm_rehbinder
- [ ] dispersion
- [ ] newton_cooling
- [ ] energy_conservation
- [ ] non_thermal_equilibrium

## Impact

QA for users

**Comment by WilkAndy** [comment]
Just pick ones you want to do, @cpgr.  Today i'll try to create a stub for each.  Some of them won't be difficult as the latex exists.

**Comment by WilkAndy** [comment]
Hi @cpgr .   I've discovered parts of this are a bit convoluted.  The problem is that some of the figures aren't in the git repo, but are hanging around on all the computers that i use, so i have to organise them all into the porous flow repo.  So i think i should do as much as possible myself before you chip in.   It'll take a couple of weeks, i think, since this isn't incredibly high priority.

**Comment by cpgr** [comment]
No worries Andy.

**Comment by WilkAndy** [comment]
Oh my goodness, this latex-to-markdown is turning out to be quite a chore.  I've started on the lengthy documentation, and every day i pray that it'll get easier.  Not so far :-(
