### ISSUE TITLE
Populate restartable data in mesh objects earlier than initialSetup

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#13166]
## Reason
Restartable data on the mesh is needed in an action and currently restartable data is not read in on restart until `initialSetup` which is too late. 

## Design
Populate mesh restartable data separate from other object restartable data such that objects such as actions have access to it upon restart/recover. 

## Impact
Changes behavior of restartable data in mesh objects only.  Should not change the behavior for any other systems.

**Comment by gambka** [comment]
@permcody @friedmud 

Please add additional details on the design of this feature based upon your discussion.  I do not know the details of what is required but I wanted to create an issue to make sure we don't forget about the need for the capability.

**Comment by YaqiWang** [comment]
I am curious to know this as well. We had one user object holding some mesh information that is doing its own `dataStore` and `dataLoad`. If mesh can restart some of its data, we can remove this user object.

**Comment by gambka** [comment]
@YaqiWang When I discussed my use case to Cody yesterday, he mentioned your user object being another use case.  You can declareRestartableData in the mesh object but for me I need to use the restarted member variables in an action but the data has not be through the dataLoad that early as far as I understand.

**Comment by YaqiWang** [comment]
Nope, I need that data in the actions as well, which is the reason why we have to handle its restarting manually. (Data is restarted in the user object constructor.) If you have access to Rattlesnake, you will see what I mean easily by looking into the `ElementIDUserObject`.

**Comment by gambka** [comment]
@permcody I think this can be closed with the implementation of the MeshMetaDataStore?

**Comment by permcody** [comment]
Yes it can - Thanks for the tip!
