### ISSUE TITLE
`TotalVariableValue` is poorly named

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13180]
## Reason
The name `TotalVariableValue` is a misnomer. This post-processor computes a time integral ("total" is vague in this sense). Furthermore, it integrates *post-processors*, not *variables*.

## Design
Rename to `TotalVariableValue` to something better, like `PostprocessorTimeIntegral`.

## Impact
Deprecate old name.

**Comment by joshuahansel** [comment]
I always have such a hard time finding this post-processor because its name is not too helpful!

**Comment by permcody** [comment]
TotallyTubularVariableValue?

**Comment by andrsd** [comment]
Or `IncorrectlyNamedPostprocessor`. That should make it easy to find 😈

**Comment by joshuahansel** [comment]
`JoshSeriouslyLookHerePostprocessor`?

**Comment by joshuahansel** [comment]
Closed by https://github.com/idaholab/moose/pull/19051
