### ISSUE TITLE
Scalar Transport Module

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#13192]
## Reason
At a minimum this module would serve as a good tutorial for concepts like hyperbolic PDEs and methods for solving them, e.g. SUPG, DG, RDG.

## Design
Following up on the reason above, this should pull in the RDG module. We should be able to use the Scalar Transport module to reproduce the results shown in some of @yidongxiainl's test problems [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/moose-users/yidong$20xia$20discontinuous$20galerkin%7Csort:date/moose-users/p6h7PqZNOrA/sNmPZiDBumkJ).

## Impact
MOOSE is a general multi-physics tool and I think it's an excellent platform for exploring and teaching concepts of FEM. Showing that we can do different transport methods and illustrate the results expected from literature is a good thing in my book!

**Comment by lindsayad** [comment]
@jwpeterson In the vein of this new proposed module, I did some looking at the temporal convergence rate of SUPG stabilized transient-advection. Here are some results:

### No stabilization

Here we see the desired convergence rate for both backwards Euler and Crank-Nicolson:
![transient-advection-no-stab](https://user-images.githubusercontent.com/10248304/55738187-d7886800-59e3-11e9-9fa6-8e0aaecfc8c6.png)

### Time derivative contribution to non-time residual

Just for fun I showed what happens we add the transient term to the non-time residual (this is still no stabilization):
![transient-advection-no-stab-bad-time-derivative](https://user-images.githubusercontent.com/10248304/55738185-d7886800-59e3-11e9-96f2-ff27014c72ed.png)

### SUPG with transient SUPG contribution added to non-time residual
![transient-advection-tau-mod-stab-transient-stab-to-non-time-resid](https://user-images.githubusercontent.com/10248304/55738184-d7886800-59e3-11e9-8ce0-b7b015c11243.png)

### SUPG with transient SUPG contribution added to time residual
![transient-advection-tau-mod-stab-transient-stab-to-time-resid](https://user-images.githubusercontent.com/10248304/55738183-d7886800-59e3-11e9-94f6-257c4a257be8.png)

### SUPG with no SUPG contribution from the time term

E.g. we only have `tau * velocity * grad_test * velocity * grad_u`:
![transient-advection-tau-mod-stab-no-transient-term-in-stab](https://user-images.githubusercontent.com/10248304/55738182-d6efd180-59e3-11e9-8129-f8a7759211f4.png)

### Summary

So we see that SUPG does destroy the temporal convergence rate of the higher-order method, and it might even be best not to include the time term at all in the SUPG contribution!

**Comment by jwpeterson** [comment]
Interesting results... I guess your conclusion "best not to include the time term" refers to the term in the strong form of the residual? I guess it may be correct for this test problem and the form of tau we are currently using, but I think in general you want to keep those terms to maintain consistency with the original PDE.

Some other questions that came to mind were: 

1. What was your MMS for these test cases? Are you refining in both space time to make these plots?
1. You mentioned that this is a transient advection case, so I assume that you've chosen BCs appropriately (i.e. only at the inflow boundary) but you may want to double-check this. 
1. Computing the space L2-norm of the error at the final time isn't technically a space-time norm, you'd have to take the max spatial L2-error over all times or integrate the spatial L2 integral from t=0 to T, but the fact that it converges at first-order is sufficient to show it can't be better than first-order overall.
1. Are you using the "sum of the inverse squares" approach for computing tau (i.e. equation (31) in the paper)? In the limit as dt -> 0, holding h constant, we should have that tau = O(dt). I'm not sure if this is sufficient to conclude that we should a priori expect first-order convergence in time, but I don't think it's very promising... you typically have to show that the error is O(dt^3) at each individual timestep to show that the overall error is O(dt^2), and we probably don't have that.
1. Let me see if I can dig up any papers this evening that might have more information on expected convergence rates...

**Comment by lindsayad** [comment]
>     1. What was your MMS for these test cases? Are you refining in both space and time to make these plots?

Solution was one that I took from your transient convergence testing: `t^3 * (x^2 + y^2)`. Only refining in time

>     2. You mentioned that this is a transient advection case, so I assume that you've chosen BCs appropriately (i.e. only at the inflow boundary) but you may want to double-check this.

This was something I was wondering about given the first order nature of the spatial derivative here. In the plots shown above, I imposed the exact solution on all boundaries (this was 2D). I just ran the same simulations again, only imposing the boundary on the "inflow" boundary, and the convergence rates were actually a bit worse for all the SUPG cases, between a half order and a full order for Crank-Nicolson. Perhaps I should select a different MMS?


>     3. Computing the space L2-norm of the error at the final time isn't technically a space-time norm, you'd have to take the max spatial L2-error over all times or integrate the spatial L2 integral from t=0 to T, but the fact that the error at the final time converges at first-order is sufficient to show it can't be better than first-order overall.

Thanks for this note.

>     4. Are you using the "sum of the inverse squares" approach for computing tau (i.e. equation (31) in the paper)? In the limit as dt -> 0, holding h constant, we should have that tau = O(dt). I'm not sure if this is sufficient to conclude that we should a priori expect first-order convergence in time, but I don't think it's very promising... you typically have to show that the error is O(dt^3) at each individual timestep to show that the overall error is O(dt^2), and we probably don't have that.

Your conjectures here make sense to me.

>     5. Let me see if I can dig up any papers this evening that might have more information on expected convergence rates...

Yea, I feel like there has to be some studies out there. I was kind of drumming this up fairly quickly for @aeslaughter. Don't feel a need to spend a lot of your own time on this, but I do think this is interesting!

**Comment by YaqiWang** [comment]
Can you give your weak forms here? Is your tau constant over time? I thought we should have the desired rates without losing consistency.

**Comment by lindsayad** [comment]
> I thought we should have the desired rates without losing consistency.

Do you have a reference for this? I've never seen an article talking about the preservation of temporal convergence rates when using SUPG; only space.

**Comment by jwpeterson** [comment]
> Solution was one that I took from your transient convergence testing: `t^3 * (x^2 + y^2)`. Only refining in time

OK, so if you use quadratic elements, there should be no spatial component of the error? Sometimes this is necessary to guarantee that the error you are measuring is actually due to the time discretization, but since you already got 2nd-order convergence for CN in the unstabilized case, I suspect it is fine.

> I just ran the same simulations again, only imposing the boundary on the "inflow" boundary, and the convergence rates were actually a bit worse for all the SUPG cases, between a half order and a full order for Crank-Nicolson. 

Well, you can't just turn "off" the Dirichlet BCs on the outflow boundary because then you will be imposing zero flux weakly, which doesn't match your MMS. You have to introduce some kind of "free" BC that computes the boundary integral contribution and adds it to the residual... this may be why you lost a half power of h.

**Comment by lindsayad** [comment]
> OK, so if you use quadratic elements, there should be no spatial component of the error?

I was using quadratic elements.

> Well, you can't just turn "off" the Dirichlet BCs on the outflow boundary because then you will be imposing zero flux weakly, which doesn't match your MMS.

Is this true if you don't have **any** terms that are integrated by parts? I kind of don't think so.

**Comment by YaqiWang** [comment]
Rattlesnake has SUPG for simple convection-reaction equation. We do not have to have MMS and just use the solution diff between two next time refinements to do the plot. Unfortunately I did not do this before. I also do not have a reference. Note that we basically convert PDE to a set of ODE, if the matrix on the time derivative term is constant, we should have the desired convergence rate.

**Comment by jwpeterson** [comment]
> Is this true if you don't have any terms that are integrated by parts? I kind of don't think so.

Ah, I had just assumed that you would integrate the convective term by parts but I guess it's not necessary...

**Comment by jwpeterson** [comment]
@YaqiWang what Tau do you use in the time-dependent convection-reaction case? Does it have a dt dependence?

**Comment by YaqiWang** [comment]
No, it is typically only the inverse of the reaction coefficient, which is typically constant over time.

**Comment by jwpeterson** [comment]
@lindsayad you might want to check if commenting out the dt contribution to tau makes any difference in your results?

**Comment by lindsayad** [comment]
Commenting out the dt contribution to tau is a bad idea. See below plots.

- simple: tau is simply computed as h / (2|U|); e.g. no transient character in tau!
- squares: our equation 31
- none: no SUPG


### Transient term not in strong residual for SUPG
![no-transient-term-in-supg](https://user-images.githubusercontent.com/10248304/55749200-9bfa9780-59fd-11e9-86ae-a549dd4f3167.png)
### Transient SUPG term contribution in non-time residual
![transient-term-in-non-time](https://user-images.githubusercontent.com/10248304/55749235-a87ef000-59fd-11e9-95d6-c3c002c44134.png)
### Transient SUPG term contribution in time residual
![transient-term-in-time](https://user-images.githubusercontent.com/10248304/55749283-c9474580-59fd-11e9-9da3-f847479b739a.png)

### Summary

- I need to get this all on one mega-plot
- If there's no transient character in tau, then there is no convergence w.r.t time
- The convergence rate is 1 for:
    - Squares supg  implicit euler
    - No supg implicit euler
    - Squares supg Crank-Nicolson
- How you include the transient term (u_dot) in the strong residual (or whether you include it at all) doesn't affect the convergence rate but it does affect the error offset, with the errors being from best to worst:
    1. No inclusion
    2. Inclusion in the time residual
    3. Inclusion in the non-time residual

**Comment by YaqiWang** [comment]
Did you change all kernels that have tau? SUPG requires `(tau * grad u^test, residual)`, where residual is the entire equation including the time derivative. If residual is zero, this term is also zero, which makes SUPG consistent.

**Comment by lindsayad** [comment]
Yes, I've done SUPG a thousand times

**Comment by lindsayad** [comment]
1000 times isn't enough, but 1001 appears to be enough in this case. Thanks @YaqiWang for forcing me take a second look...sure enough I'd included the MMS forcing function as a parameter in the SUPG kernel but then never actually added it to the residual!

Here's the final mega result:
![final-results](https://user-images.githubusercontent.com/10248304/55754068-1250c700-5a09-11e9-8a33-ff0309934dda.png)

As @YaqiWang suggested, the full accuracy of the method is preserved when all terms are included in the strong residual ***and*** as @jwpeterson hypothesized the transient SUPG term is added to the time residual. This is true whether we use our equation 31 for computing tau, which includes a component based on `_dt`, or the canonical `h/(2|U|)`. It does appear that the error is ***slightly*** better with the simpler tau formulation.

When using `CrankNicolson`, not including the transient SUPG term at all or adding it to the non-time residual is equally deleterious. When using the "squares" tau, the convergence order is reduced to 1; when using the "simple" tau, there is no convergence at all!

In the `ImplicitEuler` case, we can of course get away with adding the transient term to the non-time residual since they all go to the same place. If we don't add the term at all, however, then we don't get any convergence at all...consistent with the inconsistency of the method :smile: Thanks again @YaqiWang

**Comment by jwpeterson** [comment]
Looks good! Glad you were able to get it figured out and that the method remains 2nd-order for CN.

**Comment by jwpeterson** [comment]
Also interesting that adding the "squares" tau to the non-time residual happens to "work," albeit not at the correct order. Do you think you'll go back and update the INS formulation to fix that at some point?

**Comment by YaqiWang** [comment]
Hehe. I questioned based on my faith. Not sure if you are aware of some discussions in https://github.com/idaholab/moose/pull/12157. If the coefficient of time derivative term is time dependent, there could be implications to maintain the expected convergence order.

This module will be really good for education. For real applications, it will have problems of all other general kernels, like coefficient (or velocity) could be from users, a material property, or a variable in another physics, etc. Application developers will possibly need to create more complicated kernels for their own cases.

**Comment by lcarasik** [comment]
Just to chime in unsolicited, I believe this module would be a very useful educational tool for students as well.

**Comment by aeslaughter** [comment]
@lindsayad  @jwpeterson 

There was some some BC stuff above so I was hoping someone could shed some light on the behavior I am seeing with respect to performing a spatial convergence for an advection equation: dh/dt + div(uh) = 0, where h is the unknown and u is a known constant velocity.

For a 1D problem with assumed solution of h = t sin(2pi * x) I am getting super convergence if I set the boundary conditions to match the known solution via Dirichlet condition. This behavior happens with and without integration of the advection portion by parts. When not using a BC I do nothing, so in one case there is no-flux and the other there is just nothing set on the boundary; the no BC plot is the same regardless (I am showing the integrated by parts version here).

I am just curious to what I should do with respect to writing this up, I don't want to show super convergence unless I can explain it. Then in the other case just ignoring the boundary conditions or setting them to no-flux also seems inconsistent, but I get the correct convergence. In the end I would like to explain all the behavior and make a useful document for people who do this sort of work in the future. 

![mms_spatial](https://user-images.githubusercontent.com/341333/56160816-5dc52100-5f85-11e9-876a-17a440bd7255.png)

![compare](https://user-images.githubusercontent.com/341333/56161276-636f3680-5f86-11e9-97ec-827180b5f1e7.png)

![compare](https://user-images.githubusercontent.com/341333/56161395-a29d8780-5f86-11e9-8619-3ed01576eb71.png)

**Comment by jwpeterson** [comment]
>  When not using a BC I do nothing,

I'm not clear what this means. You should always be setting a BC on the inflow boundary. Assuming u>0, the "inlet" will be on the left-hand side of your 1D domain. You must set a BC on the inflow boundary regardless of whether or not you integrate by parts.

Whether or not you integrate by parts controls whether you will have a BC to implement on the outflow boundary or not. If you do integrate by parts you will need to implement a "free" BC at the outlet, this is done in e.g. the `navier_stokes` module in a few places.

I have no idea why you would observe O(h^3) convergence with linears and O(h^2) convergence with quadratics... are you sure you didn't just get the results mixed up??

**Comment by aeslaughter** [comment]
> I'm not clear what this means. You should always be setting a BC on the inflow boundary. Assuming u>0, the "inlet" will be on the left-hand side of your 1D domain. You must set a BC on the inflow boundary regardless of whether or not you integrate by parts.

I get O(h^3) if I set just the left BC as well.

> I have no idea why you would observe O(h^3) convergence with linears and O(h^2) convergence with quadratics... are you sure you didn't just get the results mixed up??

I messed up the legend for the one plot. These are both with 1st order elements, with and without the BC being set.

![mms_spatial](https://user-images.githubusercontent.com/341333/56163340-4d17a980-5f8b-11e9-92dd-004de1ab2c94.png)

**Comment by YaqiWang** [comment]
An input could be helpful.

**Comment by jwpeterson** [comment]
I don't think it's worth further investigating the case where you don't set any boundary conditions, as it simply isn't relevant to anything. As far as why you observe a superconvergent result for this simple test problem, I'm not entirely sure what would cause that. If I recall correctly, @aprilnovak saw some superconvergent results on some simple test problems in Pronghorn as well, maybe she could chime in if that's the case.

I would suggest trying a discontinuous initial condition with a zero forcing function. For this equation, the discontinuity should simply be advected to the right at constant speed u, so you can still compare to the exact solution.

**Comment by aprilnovak** [comment]
I've seen superconvergence (for linear elements only) all the time when using SUPG with MMS tests. Typically, I would see convergence rates between 2 and 3 in the L2 norm for linear elements, where the convergence rate depends on the specific MMS solution. So, I'm still unsure of exactly what was the underlying cause.

Below is a figure showing convergence rates for linear and quadratic elements for three different MMS solutions (cases A, B, and C) for the same PDE and types of BCs from Pronghorn.

[GENERATED_L2Error_continuity_eqn_SUPG_test.pdf](https://github.com/idaholab/moose/files/3085854/GENERATED_L2Error_continuity_eqn_SUPG_test.pdf)

**Comment by aeslaughter** [comment]
After taking a week off from looking at it, I went through my problem again from scratch and the superconvergence isn't happening anymore. The following plot shows what I am getting for the pure advection equation with and without SUPG as well as the advection-diffusion equation. The results generally look good, with the exception of the advection equation with second order elements.

However, as @friedmud mentioned the reduce convergence rate for the advection equation with second order elements might be expected to behave sub-optimally (see https://rdcu.be/byjkF). I am going to do some more digging in the literature to see if I can find more evidence.

![mms_spatial](https://user-images.githubusercontent.com/341333/56537979-190a2e80-651f-11e9-8209-62b1b61a982e.png)

**Comment by jwpeterson** [comment]
Are these results still for the time-dependent problem? 

Regardless, I believe you are seeing the "expected" convergence rate for quadratics on the pure advection problem, since the weak form for this PDE is non-coercive. There is actually an even/odd pattern as you increase polynomial order for this problem (see: Figure 4 of [this paper](https://arxiv.org/abs/1612.06312), where hierarchic elements are used). All odd-order discretizations (p=1,3,5,...) converge at the optimal rate in L2 and H1 norms, all even-order discretizations are suboptimal by a power of h but have a lower error constant than the preceding power, exactly as you are seeing here.

**Comment by aeslaughter** [comment]
@jwpeterson These are for the time-dependent problem, but I have a steady-state version that is getting the same results. Thanks for confirming and for the reference, I found a book that talks about the lower order, but makes no mention of the even/odd stuff. I am going to write all this up for future reference.

**Comment by aeslaughter** [comment]
FYI to those following this thread, I stumbled across this document. It seems to be a really nice summary of transport problems, especially for rookies like me. http://www.mathematik.uni-dortmund.de/~kuzmin/Transport.pdf

**Comment by lindsayad** [comment]
I don't think we need a specific module for scalar transport. I think that if #18321 is achieved, then there can be additional scalar transport examples using `rDG` in addition to the existing scalar transport examples using FV in the `navier_stokes` module

**Comment by lindsayad** [comment]
Re-opening this. I would like to move the bulk of TMAP8, at least the physics, into MOOSE modules so that different applications can leverage the physics and can develop in a common layer (if they wish). TMAP8, at least, should also leverage `Component` syntax from `thermal_hydraulics`. Branches of transport like mass transport, which can depend on flow fields, are not really a part of `navier_stokes` or `thermal_hydraulics` so I think a new module that depends on `thermal_hydraulics` (which in turn depends on `navier_stokes`) is fully appropriate

**Comment by lindsayad** [comment]
This new module should also depend, conceptually at least, on something like `chemistry` for reactive transport
