### ISSUE TITLE
AD rank two tensor eigen-decomposition

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#13191]
## Reason

In AD tensor mechanics, we sometimes want to solve an eigen-decomposition of a ranktwotensor.
But the current eigen-decomposition solver in ranktwotensor is calling LAPACK and it does not seem to be compatible with AD.

## Design

I need a 3X3 eigen-decomposition solver in ranktwotensor that works with AD.

## Impact

AD materials and kernel that used to call the old eigen-decomposition solver need to call the new one.

**Comment by permcody** [comment]
Closed by #13405
