### ISSUE TITLE
Modify FeatureVolumeVectorPostprocessor so it can calculate areal coverage of a boundary

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#13202]
## Reason
Need to calculate what fraction of a grain boundary is covered by features that are connected to a simulation domain boundary.

## Design
FeatureFloodCount already detects which features are connected to a domain boundary and outputs that via FeatureVolumeVectorPostprocessor. We will add the capability to calculate how much of a specified SideSet is covered by each feature. For 3D simulations the sideset (2D) will be the grain boundary plane. The capability to supply boundaries will be added by making FeatureVolumeVectorPostprocessor inherit from BoundaryRestrictable. If a boundary is not specified, the default behavior will be that the volume of each feature will be calculated, as before.

## Impact
None

**Comment by laagesen** [comment]
@permcody could you take a look at what I've done so far?
-Added boundary restriction capability
-If boundary parameter is supplied it will loop over supplied elements and do reinitElemFace on faces that are on the user-supplied boundary 

Next thing is to create a new function that will calculate areas of elements on the user-supplied boundary similar to existing accumulateVolumes. Similar to that I will set it up so it can integrate normally or use a single feature per element.

**Comment by permcody** [comment]
Yeah - I'll get to this in the next hour.

**Comment by permcody** [comment]
Sorry - won't get to this today. On my list for tomorrow AM.

**Comment by laagesen** [comment]
Thanks and no worries - I am scrambling to finish some proposal reviews this afternoon anyway...
