### ISSUE TITLE
A corner case of command-line parameter overwriting

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#13210]
## Reason
I am meeting a strange corner case that can be produced with the following change
```
diff --git a/test/tests/kernels/2d_diffusion/2d_diffusion_test.i b/test/tests/kernels/2d_diffusion/2d_diffusion_test.i
index cdc4fc2e94..36ddce5e21 100644
--- a/test/tests/kernels/2d_diffusion/2d_diffusion_test.i
+++ b/test/tests/kernels/2d_diffusion/2d_diffusion_test.i
@@ -8,7 +8,14 @@
 ###########################################################
 
 [Mesh]
-  file = square.e
+  type = GeneratedMesh
+  dim =
+  xmin = 0
+  xmax = 165
+  ymin = 0
+  ymax = 165
+  nx = 11
+  ny = 11
 []
 
 [Variables]
```
Even I do `../../../moose_test-opt -i 2d_diffusion_test.i Mesh/dim=2`, I am still getting an error like
```
*** ERROR ***
/Users/wangy2/projects/training/mammoth/moose/test/tests/kernels/2d_diffusion/2d_diffusion_test.i:13: invalid character '='
```
I do not know how the number `13` is from.

However, if the change is
```
diff --git a/test/tests/kernels/2d_diffusion/2d_diffusion_test.i b/test/tests/kernels/2d_diffusion/2d_diffusion_test.i
index cdc4fc2e94..d26b9bc4aa 100644
--- a/test/tests/kernels/2d_diffusion/2d_diffusion_test.i
+++ b/test/tests/kernels/2d_diffusion/2d_diffusion_test.i
@@ -8,7 +8,8 @@
 ###########################################################
 
 [Mesh]
-  file = square.e
+  type = GeneratedMesh
+  dim =
 []
 
 [Variables]
```
I do not see the error.

## Design
Need this fixed so that we can use this in our training materials and still have tests to check the syntax for the rest of the inputs.

## Impact
A bug fix?

**Comment by YaqiWang** [comment]
Looks like if I move `dim =` to the end of `Mesh` block, I do not get the error, otherwise I do. This could be useful for fixing this.

**Comment by permcody** [comment]
@rwcarlsen - Can you take a look at this? This looks like an error that should be caught during HIT parsing.
