### ISSUE TITLE
Transfer PolycrystalVoronoiVoidIC to UserObject based initial condition

### ISSUE THREAD

**Issue by SudiptaBiswas** [idaholab/moose#13267]
## Reason
Currently, `PolycrystalVoronoiVoidIC` does not use the UserObject based` PolycrystalVoronoi` algorithm. As a result, it fails to utilize the faster coloring algorithms.  

## Design
Redesign`PolycrystalVoronoiVoidIC` based on `PolycrystalVoronoi` UserObject to create grains and voids.

## Impact
Faster grain growth with void simulation.

**Comment by permcody** [comment]
closed by #13278
