### ISSUE TITLE
Add simple inflow & outflow BCs in NS module

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#13283]
## Reason

Simple boundary conditions for fluid flow problems.

## Design

Boundary conditions of the form:
```
 test * u * velocity * normals
```
that applied of `velocity * normals` either greater or smaller than 0.

## Impact

No objects.

**Comment by YaqiWang** [comment]
I remembered we had this thing and just found it:
https://github.com/idaholab/moose/blob/next/test/src/bcs/OutflowBC.C
https://github.com/idaholab/moose/blob/next/test/src/bcs/InflowBC.C

**Comment by snschune** [comment]
Yes, they exist, but they are actually both not general enough, e.g. velocity is not a variable, and they apply the contribution regardless of the sign of `vel * normal`.

**Comment by YaqiWang** [comment]
Yes, it might be also desired to merge the two into one and switch calculations on qp basis.

**Comment by snschune** [comment]
Is there any instance where you would apply BCs on an outflow side?

**Comment by snschune** [comment]
> Is there any instance where you would apply BCs on an outflow side?

This BC will usually be applied on the outflow. Inflow as in the example usually Dirichlet.
