### ISSUE TITLE
misc fracture_flow test to work in parallel

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#13318]
## Reason

We want to be able to use "-p 2" in the test receipe for the misc module.

## Design

I want the misc/test/tests/fracture_flow/single.i test to work in parallel.  I had forgotten about this test.  It's actually quite nice, so i'd like to leave it.  I'll also add a pointer to the latex documentation from the PorousFlow fracture-flow example documentation, because the latex documentation is actually pretty good, but i haven't time to markdown it all and merge it with the PorousFlow stuff

## Impact

Better test coverage

**Comment by permcody** [comment]
@WilkAndy - We have started:
https://civet.inl.gov/job/328769/

I notice that there are a few failures there related to dynamic loading. I'll get those fixed up tomorrow and we'll go from there.

**Comment by WilkAndy** [comment]
Glad to see you called this "modules parallel" as i hope to get PorousFlow added to this soon.
