### ISSUE TITLE
Add pi and Euler's constant to ${fparse ..} in input files

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13329]
## Reason
These constants are commonly used in mathematical expressions that could be created for `fparse` in input files.

## Design
This would add the constants "pi" and "e" to the `FunctionParser` object used by the parser.

## Impact
New constants available for `fparse` in input files. If anyone is already defining quantities with these names in their input files, they will get a warning for unused parameters by the parser.

**Comment by dschwen** [comment]
Just to clarify, those are already added to parsed `Function` objects (see `libmesh/parsed_function.h`). Are you talking about making them available in parsed _material_ objects?
