### ISSUE TITLE
Restore Favicon to MOOSE Website

### ISSUE THREAD

**Issue by cticenhour** [idaholab/moose#13335]
## Bug Description
From discussion on https://groups.google.com/forum/#!topic/moose-users/EKwyrrR8m_o, it was noted that the Favicon from the deprecated MOOSE webpage no longer exists in the new webpage. It might be helpful to some users with customized browser toolbars to have that icon back.

## Steps to Reproduce
Go to the current version of https://mooseframework.inl.gov

## Impact
Other than personal preference, no user impact.

**Comment by dschwen** [comment]
> helpful to some users with customized browser toolbars

![image](https://user-images.githubusercontent.com/202302/56998869-243a0b80-6b6a-11e9-932b-341ced3ab0bb.png)

**Comment by cticenhour** [comment]
Well, customized browser *bookmark* bars is probably a better description 😄
