### ISSUE TITLE
More diffuse interfaces for phase field ICs

### ISSUE THREAD

**Issue by itgreenquist** [idaholab/moose#13331]
## Reason
The phase field module requires diffuse interfaces, but currently very few of the ICs allow diffuse interfaces. So phase field simulations start with sharp interfaces, which slows down simulations and can affect the validity of their results.

## Design
I want to add diffuse interface support to the following common IC systems:
- BoundingBoxIC Initial Condition
- PolycrystalCircles User Object
- PolycrystalVoronoi User Object

There is also a minor improvement that can be made to the hyperbolic tangent interface option in SmoothCircleBaseIC.

## Impact
Additional parameter `int_width` for some IC and User Object blocks. Probably some adjustments to existing tests.

**Comment by permcody** [comment]
Please don't delete the template when you submit a ticket.
