### ISSUE TITLE
Better Error When Split is Not found

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#13348]
## Reason
If you have a split mesh for 100 procs... but you try to run with 50... you get this message:

```
*** ERROR ***
ERROR: cannot locate header file for input '/scratch/gastdr/meshes/mesh.cpr'
```

The message is not helpful because `/scratch/gastdr/meshes/mesh.cpr` _does_ actually exist... it's just that the split you are looking for does not.  The error message should be something like:

```
Error: split for 50 processors not found in '/scratch/gastdr/meshes/mesh.cpr'
Available splits are:
100
200
```

## Design
See above

## Impact
Better error messages

**Comment by JackHanni** [comment]
@permcody I am working with @jmeziere at BYU-Idaho and I have been looking all over for the error message mentioned, but cannot find it. Could you help me locate it?

**Comment by andrsd** [comment]
This error message comes from libMesh. Actually I should have said used to come from libMesh. @permcody changed it on May 21, 2019 (see libmesh/libmesh@669e79883b4e384474be6fd50043880f83d2c39a). It used to be in `src/mesh/checkpoint_io.C`.

**Comment by permcody** [comment]
Oops - this should have been closed then. Thanks for finding that reference. Sorry for wasting your time on this one @JackHanni. Let us know if you have other questions on any other tickets you are looking at.
