### ISSUE TITLE
Add FlibeFluidProperties to fluid_properties module

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#13383]
## Reason
Add flibe fluid properties so that several MOOSE applications can reduce code duplication and eliminate differences during coupling applications where multiple applications require flibe properties.

## Design
Add flibe fluid properties as a derived class from SinglePhaseFluidProperties in the fluid_properties module.

## Impact
Remove flibe property implementations from Pronghorn and SAM. No changes to any applications provided there isn't a name collision elsewhere.

**Comment by aprilnovak** [comment]
I'll do this issue

@rui-hu FYI

**Comment by andrsd** [comment]
@aprilnovak Please, do not edit the template. It need to have all the sections filled our. It is required by our SQA process. Thanks!

**Comment by aprilnovak** [comment]
Sorry for that @andrsd, I was unfamiliar with the feature request vs. bug report so I just clicked "open a regular issue," which doesn't have any template.

**Comment by aprilnovak** [comment]
## Reason
Add flibe fluid properties so that several MOOSE applications can reduce code duplication and eliminate differences during coupling applications where multiple applications require flibe properties.

## Design
Add flibe fluid properties as a derived class from `SinglePhaseFluidProperties` in the `fluid_properties` module.

## Impact
Remove flibe property implementations from Pronghorn and SAM. No changes to any applications provided there isn't a name collision elsewhere.

**Comment by andrsd** [comment]
Oh, I see...
