### ISSUE TITLE
Nemesis outputs are overwritten when running with recover

### ISSUE THREAD

**Issue by SudiptaBiswas** [idaholab/moose#13396]
## Bug Description
While recovering a simulation with mesh adaptivity and nemesis outputs, the new output files override the previous ones instead of creating new files.  

## Steps to Reproduce
Run any test file with mesh adaptivity and output `nemesis=true`

## Impact
Recover does not work with nemesis and adaptivity.

**Comment by SudiptaBiswas** [comment]
Even without adaptivity, the nemesis outputs are not appended when ran with recover.

**Comment by permcody** [comment]
Did you try the little local patch the @friedmud showed you? I'm curious if that worked for you.

**Comment by GiudGiud** [comment]
Can we close this? Seems fixed by libmesh/libmesh#2566

**Comment by GiudGiud** [comment]
Closing since no one replied and a fix was merged
