### ISSUE TITLE
Add FlinakFluidProperties to fluid_properties module

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#13400]
## Reason
Add flinak fluid properties so that several MOOSE applications can reduce code duplication and eliminate differences during coupling applications where multiple applications require flinak properties.

## Design
Add flinak fluid properties as a derived class from SinglePhaseFluidProperties in the fluid_properties module.

## Impact
Remove flinak property implementations from Pronghorn and SAM. No changes to any applications provided there isn't a name collision elsewhere.

**Comment by WilkAndy** [comment]
You learn a new thing every day.  Today it was "flinak" for me.  Initially i thought it was a mis-spelling of "final" or something similar 😃
