### ISSUE TITLE
Remove 'failed but allowed' on PorousFlow parallel tests

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#13403]
## Reason

I believe all PorousFlow tests should now pass in parallel (-p 2), so any "failed but allowed" specifications should be removed.

## Design

Please fail all PRs that cause PorousFlow to fail in parallel.  Perhaps @milljm is in charge of this?  Perhaps it has already been done, or perhaps PorousFlow never had the "failed but allowed" flag associated with it, I'm not sure!  Please just close this issue if it isn't an issue :-)
 
## Impact

Improved testing for PorousFlow.

**Comment by permcody** [comment]
This is planned. I think all of the tested modules are now passing. Watch for this soon.

**Comment by WilkAndy** [comment]
Has this issue been addressed, can it be closed?

**Comment by permcody** [comment]
Yes it has - Thanks Andy!
