### ISSUE TITLE
Automatic method for enabling SMP for AD

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#13411]
## Reason

When AD objects are used you need to have the following in the input file, but this isn't intuitive.

```
[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  type = Steady 
  solve_type = NEWTON
[]
```

## Design

I propose the following that will automatically add the correct Preconditioning if it is not provided.

```
[Executioner]
  type = Steady 
  solve_type = AD_NEWTON
[]
```

## Impact

This will make using MOOSE with AD easier and less prone to errors.

**Comment by aeslaughter** [comment]
@idaholab/moose-team Are people OK with this or have a better idea?

**Comment by lindsayad** [comment]
I personally think that any time a user specifies `solve_type = NEWTON`, the default behavior should be to add `SMP` with `full = true` regardless of whether AD is being used or not. However the Jacobian is being computed, `NEWTON` requires a complete (and accurate) Jacobian in order to be successful

**Comment by fdkong** [comment]
I kind of agree with @lindsayad. If we use NEWTON, we should trigger ``full=true" by default. But I think we also should reserve an option so that users can turn it off if they want. For example, if the equation is very simple, we do not  need to form the world.

**Comment by tophmatthews** [comment]
If I remember correctly...`NEWTON` isn't really explicitly newton right? I've used it in the past with a close enough jacobian. Also, a full SMP is used sometimes with `PJFNK`. How about
```
[Executioner]
  type = Steady 
  solve_type = PJFNK/NEWTON
  SMP = none/partial/full
[]
```

**Comment by rwcarlsen** [comment]
I'm with @fdkong and @lindsayad.  I have been converting a bunch of stuff to AD and it is really easy to forget to set `solve_type=NEWTON` along with an `full=true` SMP preconditioner in input files.  I frequently forget to set one or more of those things.

**Comment by rwcarlsen** [comment]
To be clear - `solve_type=AD_NEWTON` would be an improvement over the status quo, but I'd still might forget to update files to use that that already have `solve_type=NEWTON`.

**Comment by lindsayad** [comment]
> If I remember correctly...`NEWTON` isn't really explicitly newton right?

It depends on whether you're using a line search or not. If you're using `line_search = basic` (which really means no line search), then you are conducting pure Newton. If you're using a line search (e.g. a globalization strategy), then yes in terms of jargon, you're using a Quasi-Newton method.

> I've used it in the past with a close enough jacobian

You can definitely achieve convergence with a non-perfect Jacobian using Newton (or Quasi-newton), but you'll be pretty unlikely to achieve a quadratic convergence rate at any point in the non-linear solve.

> [Executioner]
>   type = Steady 
>   solve_type = PJFNK/NEWTON
>   SMP = none/partial/full
> []

I'm not quite sure what you mean here.

**Comment by tophmatthews** [comment]
Thanks for the replies @lindsayad. I was suggesting having an SMP input parameter as an enum with options `none`, `partial`, `full`, similar to how the `solve_type` is an enum. You can even throw a warning if `solve_type=NEWTON` without `SMP=full` which should fail tests, but allow you to set it to none if you wish.
