### ISSUE TITLE
Multiapp Steady-Transient does not restart properly

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#13438]
## Bug Description

I am considering a `Steady` master app with a (pseudo) `Transient` sub-app. When trying to restart both the master and the sub-app after the steady-state has been reached for both, only the master seems to be able to properly restart. A null-transient cannot be achieved.

## Steps to Reproduce

The following [input files](https://github.com/vincentlaboure/moose/commit/0123b73594290fb5bb19ed2bc0cdf4730666dda2) reproduce the issue: the sub-app restarts from a zero initial condition instead of the value from the checkpoint file.

If I make the input files to restart from a Steady-Steady or Transient-Transient (for the master and sub app), then the restart seems to work fine.

## Impact

This limits the generality of restart.

**Comment by permcody** [comment]
Is this related to the "skip_additional_restart_data" flag? I can see that it's commented out in these files.

**Comment by vincentlaboure** [comment]
`skip_additional_restart_data` is used in the master app (since it is a `Transient` restarted from a `Steady`) but its value in the sub app does not matter (since it is a `Transient` restarted from a `Transient`).

It is also noted that if I run the sub-app by itself (`bison_ss.i` with `AuxVariables/initial_condition=5e2` followed by `bison_tr.i` with `Problem/restart_file_base = bison_ss_out_cp/LATEST`), then the null-transient is achieved as expected.

**Comment by permcody** [comment]
Short answer - Steady was never designed for restart because if there is only a single solve, then you either run it or you don't. There's really not much of a reason for saving and restoring before the one solve. Now I realize that things get more complicated with Picard and Mulitapps, but it makes the case stronger for dumping the Steady solver and moving everything to the "MooseExecutioner" and just handling a few special cases. The solution to this will basically be to copy a lot more data from Transient into Steady because we'll have to do backups and restores.

**Comment by permcody** [comment]
Actually no - "restart" should be ok, even for Steady solves. It's recover that doesn't make any sense....

**Comment by permcody** [comment]
So I'm planning on flipping the default for the `skip_addition_restart_data` flag. I have a PR up that already does that. If I remove the `Multiapp/no_backup_and_restore` flag from your input it appears to restart just fine. Perhaps, your test files aren't quite complex enough to show the issue?

To complicate things further, there's a parameter called `keep_solution_during_restore` in `TransientMultiApp` which probably achieves what you want in regards to what you are trying to accomplish with the `no_backup_and_restore` flag. 

I need a little more feedback from you. Does removing the `no_backup_and_restore` flag solve your issue or do you need me to look at the keep solution option?

**Comment by vincentlaboure** [comment]
Are you saying that if I run:

```
> ~/projects/moose/test/moose_test-opt -i mammoth_eigenvalue.i MultiApps/no_backup_and_restore=false
> ~/projects/moose/test/moose_test-opt -i mammoth_transient.i
```

then the bison transient is a null-transient?
If I do that, I get:

```
Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+
| time           | pwr_avg        | temp_avg       | temp_max       | temp_min       |
+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   5.577775e+02 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   5.577775e+02 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
|   2.000000e+00 |   5.577775e+02 |   4.539293e+02 |   4.633090e+02 |   4.476206e+02 |
|   3.000000e+00 |   5.577775e+02 |   4.689758e+02 |   4.924059e+02 |   4.501758e+02 |
|   4.000000e+00 |   5.577775e+02 |   4.696672e+02 |   4.939479e+02 |   4.501837e+02 |
|   5.000000e+00 |   5.577775e+02 |   4.697000e+02 |   4.940226e+02 |   4.501841e+02 |
|   6.000000e+00 |   5.577775e+02 |   4.697016e+02 |   4.940262e+02 |   4.501841e+02 |
|   7.000000e+00 |   5.577775e+02 |   4.697016e+02 |   4.940264e+02 |   4.501841e+02 |
|   8.000000e+00 |   5.577775e+02 |   4.697016e+02 |   4.940264e+02 |   4.501841e+02 |
|   9.000000e+00 |   5.577775e+02 |   4.697016e+02 |   4.940264e+02 |   4.501841e+02 |
|   1.000000e+01 |   5.577775e+02 |   4.697016e+02 |   4.940264e+02 |   4.501841e+02 |
+----------------+----------------+----------------+----------------+----------------+


Advancing MultiApps on TIMESTEP_END
bison0: 
bison0: Postprocessor Values:
bison0: +----------------+----------------+----------------+
bison0: | time           | pwr_density    | temp_fuel_avg  |
bison0: +----------------+----------------+----------------+
bison0: |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
bison0: |   1.000000e+00 |   5.577775e+02 |   4.539293e+02 |
bison0: |   2.000000e+00 |   5.577775e+02 |   4.689758e+02 |
bison0: |   3.000000e+00 |   5.577775e+02 |   4.696672e+02 |
bison0: |   4.000000e+00 |   5.577775e+02 |   4.697000e+02 |
bison0: |   5.000000e+00 |   5.577775e+02 |   4.697016e+02 |
bison0: |   6.000000e+00 |   5.577775e+02 |   4.697016e+02 |
bison0: |   7.000000e+00 |   5.577775e+02 |   4.697016e+02 |
bison0: |   8.000000e+00 |   5.577775e+02 |   4.697016e+02 |
bison0: |   9.000000e+00 |   5.577775e+02 |   4.697016e+02 |
bison0: |   1.000000e+01 |   5.577775e+02 |   4.697016e+02 |
bison0: +----------------+----------------+----------------+
bison0: 
Finished Advancing MultiApps on TIMESTEP_END
```

which indicates that bison restarts with a zero initial condition.

Or maybe I am misunderstanding what you mean.

**Comment by fdkong** [comment]
@vincentlaboure Do you still have issue on this?

**Comment by vincentlaboure** [comment]
@fdkong What do you mean update the input files? Do they no longer run?
