### ISSUE TITLE
Enable LinearInterpolation for AD

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#13432]
## Reason
Models using the automatic differentiation system that use `LinearInterpolation` require an AD enable version of the linear interpolator.

## Design
Create templated `LinearInterpolation<T>` template and have `LinearInterpolation` be a template alias (analogous to `RankTwoTensor`)

## Impact
Added capability.

**Comment by dschwen** [comment]
@lindsayad how do we feel about modifying the derivative vector of a Dual Number directly?

**Comment by lindsayad** [comment]
What's the motivation?
