### ISSUE TITLE
L2_LAGRANGE variable not transferred properly

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#13446]
## Bug Description

I am trying to transfer a `FIRST L2_LAGRANGE` from a master to a sub-app, both having the exact same mesh. 

The integral on the master mesh is ~666.7
The integral on the sub-app mesh is ~166.7

The 2-D results further indicate that the transfer does not work properly. 

## Steps to Reproduce

This can be reproduced using these [input files](https://github.com/vincentlaboure/moose/commit/15dd42030f337133d52801022d9b95d5da74f750). Both `MultiAppMeshFunctionTransfer` and `MultiAppNearestNodeTransfer` (and maybe others) exhibit this behavior.

## Impact

This limits the usability of `L2_LAGRANGE` variables.

**Comment by fdkong** [comment]
Good news, I am able to reproduce this issue

**Comment by fdkong** [comment]
Addressed
