### ISSUE TITLE
2D and 3D Patch Mesh Generators

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#13453]
## Reason
In mechanics, patch test meshes are used to ensure proper behavior for irregularly shaped elements. Currently, we have external meshes for these relatively simple mesh configurations. 

## Design
The node positions of the elements in the 2D and 3D patch tests are known. Therefore, it should be possible to create a mesh generator that works for QUAD4, QUAD8, HEX8 and HEX20 elements.  The standard sideset names from `GeneratedMeshGenerator` would be used.

## Impact
Many small exodus files that have been copied around throughout the repository for patch tests in tensor_mechanics (and other applications such as Bison) will be removed once the tests are updated to use the new MeshGenerators.

**Comment by gambka** [comment]
Here is an example of a 2D Patch test mesh.
![Screen Shot 2019-05-21 at 9 11 19 AM](https://user-images.githubusercontent.com/8386043/58108269-bef59b00-7ba8-11e9-9faf-bdffd76d5baa.png)

**Comment by gambka** [comment]
@bwspenc @jasondhales

**Comment by GiudGiud** [comment]
This mesh generator needs a rename. This is not what we expect from something that would "patch" meshes
