### ISSUE TITLE
MeshGenerator from file should allow for initial_from_file_var

### ISSUE THREAD

**Issue by veeshy** [idaholab/moose#13473]
## Bug Description
Currently you must load a mesh using the traditional [Mesh] file = 'file_name' to use the initial_from_file_var. I think this should be supported with `FileMeshGenerator` too, or at the least error when using both FileMeshGenerator and initial_from_file_var.

## Steps to Reproduce
Looks like only `PolycrystalVariables_initial_from_file.i` uses from file, so changing this to read the file mesh with MeshGenerator would make the test fail.

## Impact
Potentially a silent failure but easy enough to work around since visualizing the failed solve's IC shows the problem pretty easily, figuring out why was not so intuitive.

**Comment by permcody** [comment]
This isn't a bug - a feature request is just that. I'd prefer to reserve the bug tag for feature that exist that are broken. That being said, I completely agree with this ticket!

**Comment by veeshy** [comment]
This feature was added in https://github.com/idaholab/moose/issues/15554
