### ISSUE TITLE
FunctionInterface should return a const reference

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#13480]
## Bug Description

Currently, it is possible to create a Function object and have calls to value, etc. modify it from other objects.

## Steps to Reproduce

The problem is within all objects that get a reference to a Function object via the getFunction method.

## Impact

All Function objects will need to be updated to have const for the 'value' and other methods; and all objects using getFunction need to use a const reference. 

It might be possible to deprecate the old syntax with const/non-const overloads.

**Comment by permcody** [comment]
This is an old ticket: https://github.com/idaholab/moose/issues/7830

**Comment by permcody** [comment]
Did this old ticket not come up when you tried to create a new issue? We need to get better at searching for old issues since this is almost a perfect match...
