### ISSUE TITLE
Provide citation link(s) for MOOSE on webpage

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13507]
## Reason
Users/developers should be encouraged to cite MOOSE and be shown how to cite it. There may be information about citing MOOSE somewhere on the webpage, but I cannot find it.
 
## Design
This would add link(s) to a page describing how to cite MOOSE or just download an appropriate *.bib file. Some ideas on where on website links could be are the following:
* FAQ entry: "How do I cite MOOSE?"
* Homepage, possibly link "Cite MOOSE" under MOOSE logo
* Help > Information and Tools > Citing MOOSE

## Impact
More MOOSE citations, more convenience. Each time we make a new "definitive" MOOSE paper, we can change the preferred citation here.

**Comment by joshuahansel** [comment]
On this same note, it would be nice to have a page listing publications with MOOSE. Maybe the citation link could even provide an optional form to have them notify us of their publication.

**Comment by andrsd** [comment]
> it would be nice to have a page listing publications with MOOSE

There is [one](https://mooseframework.inl.gov/old/wiki/MoosePublications/) in the old wiki. It just needs to be moved to MOOSEDocs, I guess.

**Comment by lindsayad** [comment]
Yea I think this is a critical issue (@fdkong), and if no one else gets to it, I might work on it this week.

**Comment by fdkong** [comment]
This should already happen ten years ago.

**Comment by aeslaughter** [comment]
@lindsayad The list on the old wiki isn't very complete.

@jwpeterson Where did you store your list of MOOSE papers, this is the one we need to use and update.

**Comment by aeslaughter** [comment]
@lindsayad Also, we just need the bibtex somewhere, I will create a MooseDocs extension that converts it so something nice for the website.

**Comment by jwpeterson** [comment]
It was in the idaholab/papers repository, I think under bibtex or something like that. I no longer have access so I can't check :-)

**Comment by joshuahansel** [comment]
@lindsayad Did you mean to close this issue with #13685 or just reference it? Anything you still want to do before closing it?

**Comment by lindsayad** [comment]
Nah I guess that PR does satisfy the title of this issue. Thanks for catching, abstract art man.

This issue closed by #13685
