### ISSUE TITLE
Assertion 'feature_id < num_features' failed with FeatureVolumeVectorPostprocessor

### ISSUE THREAD

**Issue by jarinfrench** [idaholab/moose#13520]
## Bug Description
FeatureVolumeVectorPostprocessor fails the assertion 'feature_id < num_features.'  

## Steps to Reproduce
Change the following block in grain_growth_2D_graintracker.i input file (moose/modules/phase_field/examples/grain_growth/)
 
<pre>
[UserObjects]
  [./voronoi]
    type = PolycrystalVoronoi
    grain_num = <b>8</b> # Number of grains
    rand_seed = 10
    <b>coloring_algorithm = bt</b>
  [../]
  [./grain_tracker]
    type = <b>Faux</b>GrainTracker
    threshold = 0.2
    connecting_threshold = 0.08
    compute_halo_maps = true # Only necessary for displaying HALOS
  [../]
[]
</pre>
And add the following `VectorPostprocessor` block:
```
[VectorPostprocessors]
  [./grain_volume]
    type = FeatureVolumeVectorPostprocessor
    flood_counter = grain_tracker
    execute_on = 'INITIAL TIMESTEP_END'
    contains_complete_history = true
  [../]
[]
```

Then run as normal.  On my machine (Mac Sierra 10.12.6), I have tested from 1 to 12 cores, and it doesn't consistently fail - from one to three cores it doesn't seem to fail within the first few timesteps.  For 4-12 cores, it fails with the seg fault error.

## Impact
Unable to explicitly track individual grain volumes using this method.

**Comment by permcody** [comment]
Note: The contains_complete_history option should not be used in FeatureVolueVectorPostprocessor. It doesn't make any sense and data can be lost/truncated. That option needs to be hidden.
