### ISSUE TITLE
SamplerPostprocessorTransfer becomes slow for large number of samples

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#13555]
## Bug Description

For a large number of samples,  SamplerPostprocessorTransfer becomes very slow to collect results from sub app. It is caused by calling initialize() function for every sample to transfer back data. This should be avoided.  

## Steps to Reproduce

I tried to run 100000 samples with 20 mpi processes and a significant slow-down after all the sub apps finish was observed.  

## Impact

It will prevent users from running Monte Carlo simulation with large number of samples.

**Comment by aeslaughter** [comment]
closed by #13556
