### ISSUE TITLE
Linking error in Test

### ISSUE THREAD

**Issue by jijn** [idaholab/moose#13552]
## Bug Description
I run **make** in the test folder. But got the following error:

```
Linking Executable /opt/modules/software/moose/moose/test/moose_test-opt...
/opt/modules/software/moose/moose/framework/libmoose-opt.so: error: undefined reference to 'vtkAlgorithm::GetOutputPort(int)'
/opt/modules/software/moose/moose/framework/libmoose-opt.so: error: undefined reference to 'vtkImageAlgorithm::GetOutput()'
collect2: error: ld returned 1 exit status
make: *** [/opt/modules/software/moose/moose/test/moose_test-opt] Error 1
```

It seems the problem is caused by linking the library **libvtkCommonExecutionModel**.

I run **make -n**, and noticed that this library is not linked. I fixed this problem by manually run the link command with **-lvtkCommonExecutionModel-8.2** at the end.

So I guess it is a bug in test/Makefile.

**Comment by permcody** [comment]
You should probably start with an issue like this on our mailing list where many more eyes will see it. 

We'll need a lot more information about your system and your configuration log for libMesh. Are you wanting/intending on using VTK for output or the image reader? If not, you might just want to skip attempting to configure the library for working with libMesh.

**Comment by permcody** [comment]
Adding a hardcoded library like **-lvtkCommonExecutionModel-8.2** is definitely not the right solution. What happens if VTK on your system changes version? The problem here is that VTK isn't being picked up correctly on your system by libMesh's configure. I can assure you that if you provide the right options, it will work. We rely on VTK to tell us what to link.

**Comment by lvkas521424** [comment]
> ## Bug Description
> I run **make** in the test folder. But got the following error:
> 
> ```
> Linking Executable /opt/modules/software/moose/moose/test/moose_test-opt...
> /opt/modules/software/moose/moose/framework/libmoose-opt.so: error: undefined reference to 'vtkAlgorithm::GetOutputPort(int)'
> /opt/modules/software/moose/moose/framework/libmoose-opt.so: error: undefined reference to 'vtkImageAlgorithm::GetOutput()'
> collect2: error: ld returned 1 exit status
> make: *** [/opt/modules/software/moose/moose/test/moose_test-opt] Error 1
> ```
> 
> It seems the problem is caused by linking the library **libvtkCommonExecutionModel**.
> 
> I run **make -n**, and noticed that this library is not linked. I fixed this problem by manually run the link command with **-lvtkCommonExecutionModel-8.2** at the end.
> 
> So I guess it is a bug in test/Makefile.

excuse me, sir, I meet the same question, please tell me how to deal it ,such as how to link the library
