### ISSUE TITLE
Timed Print

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#13569]
## Reason
We need an object that will print out a message after a certain amount of time... and print a `.` every once in a while if something is taking a long time.

## Design
My idea here is to make it act like a "scope guard" like so:

```C++
{
  TimedPrint tp("message", 5);
  // possibly long running thing
}
```

This would print `"message"` after 5 seconds... and every second after that would print a `.`.

## Impact
Better information for long running operations.

**Comment by friedmud** [comment]
This would work by spawning a thread that sleeps... and then the destructor would kill that thread.

**Comment by YaqiWang** [comment]
I am not sure but I observed that after the timed output about occupy one line of the screen, it stops printing.

**Comment by permcody** [comment]
Possibly a terminal issue. It’s definitely printing more but perhaps when it exceeded the width of your terminal it didn’t get automatically wrapped? I’ve already been thinking that we should go ahead and put a line limit in so that it will wrap for you instead of having the terminal handle that.
