### ISSUE TITLE
git clang-format doesn't like adding symlinks

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#13560]
## Bug Description

When symlinks are added, such as done in the tutorials directories, clang-format fails.

## Steps to Reproduce

```bash
cd ~/projects/moose/tutorials/darcy_thermo_mech/step07_adaptivity/src/bcs
rm HeatConductionOutflow.C
ln -s ../../../step06_coupled_darcy_heat_conduction/src/bcs/HeatConductionOutflow.C .
git clang-format upstream/devel

`git diff-files --name-status ` returned 128
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

## Impact

This is currently preventing symlinks from being added to the repository because of the clang-format pre-check

**Comment by permcody** [comment]
Tag @rwcarlsen to see if he knows anything about this. It seems like we've encountered this before and "cheated" to get this into the repository.

**Comment by GiudGiud** [comment]
Closing as this has been fixed a while ago with updating clang-format
