### ISSUE TITLE
Add IntegratedBC support to eigenvalue systems

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#13564]
## Reason
Homogeneous integrated BCs are valid for eigenvalue problems. They are currently not supported (not tagged in the `NonlinearEigenSystem` and there is not currently a method to verify if an `IntegratedBC` is homogeneous. See #13550.

## Design
Possibly add a method to distinguish homogeneous `IntegratedBC`s from those that are not homogeneous. `IntegratedBC`s can then be added to the tagging in `NonlinearEigenSystem::initialSetup()` and appropriately checked in `NonlinearEigenSystem::checkIntegrity()`.

## Impact
None. New capability.

**Comment by YaqiWang** [comment]
It is noted that without this the new eigen solver is not usable by Rattlesnake because almost all BCs are integrated BC in Rattlesnake. @fdkong
