### ISSUE TITLE
MOOSE has no gallery

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13580]
## Reason
MOOSE-curious website visitors should have access to a summary of MOOSE's scope and accomplishments, as well as a gallery showcasing results obtained with MOOSE.

## Design
This gallery should be high-visibility, probably on the front page.

## Impact
More MOOSE users.

**Comment by lindsayad** [comment]
@aeslaughter has talked about this a lot. I'm pretty sure it's on his to-do list
