### ISSUE TITLE
Too many AD types

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#13599]
## Bug Description
We have too many AD types. There's really no reason to have `ADResidual` for example. To be consistent with how all our traditional compute objects return `Real` for residuals and Jacobians, we should return `ADReal` from compute objects. I honestly thought that @dschwen and I had done this, but I'm sitting here in training and I'm seeing that it's everywhere 😢 

## Steps to Reproduce
Look in `MooseTypes`

## Impact
We are inundating our users with names that they have to remember. Additionally, someone coming from our old systems should have as consistent an interface as possible.

**Comment by permcody** [comment]
Is this really a defect? It might be annoying but what's "broken" here?

**Comment by lindsayad** [comment]
The other template option is "feature request". Neither fit great, but defect seemed better

**Comment by permcody** [comment]
The problem with "defect" is that it means something as far as NQA-1
deployments go.

**Comment by lindsayad** [comment]
Do we have that NQA stuff documented somewhere? Maybe the template should be more specific about what a defect is as defined by NQA. If I don't know what constitutes a defect, then certainly external folks opening a ticket won't know.

**Comment by permcody** [comment]
We do in fact. It's in PLN-4005, part of our required reading ;)

**Comment by lindsayad** [comment]
Required reading before opening a ticket huh? Alright you've got me!

**Comment by permcody** [comment]
No - required reading for MOOSE devs. Sorry I'm paranoid today, our auditor
will be inspecting everything tomorrow.

**Comment by lindsayad** [comment]
Alright alright looking more closely at the template text, I agree that I shouldn't have clicked it haha. Something like a "clean up" or "maintenance" template would be a good match for something like this.

<img width="817" alt="Screen Shot 2019-06-18 at 10 42 54 AM" src="https://user-images.githubusercontent.com/10248304/59702899-c5d2f600-91c6-11e9-9aee-1726992e5726.png">

**Comment by permcody** [comment]
To be fair, I just changed this again last week. We should chat about
better language and how to direct people to the right button. I'll be
talking to our auditor about requirements and recommendations to make this
easier/better.
