### ISSUE TITLE
LowerDBlockFromSideset should take names

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#13607]
## Reason
Currently the `LowerDBlockFromSideset` mesh modifier take a vector of boundaryIDs as its sideset input.

## Design
Like most of our objects, this should take a vector of BoundaryNames where the user can provide names or IDs. 

## Impact
This makes things much more flexible for users. I was working with @joshuahansel today and we had to try and dig into Paraview to try and find the sideset IDs. This is cumbersome.

**Comment by GiudGiud** [comment]
Fixed by Topher in https://github.com/idaholab/moose/commit/125c1c6dfea9d6b6a6750b149df493802fe48fc3
