### ISSUE TITLE
ResidualObject?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#13609]
## Reason
There are some significant code duplications in `Kernel`, `BoundaryCondition`, `InterfaceKernel`, `DGKernel`, `Constraint`, `NodalKernel`, for example, the code for save-in and tagging capabilities.

## Design
A suggestion is to create a common base class like `ResidualObject` (possibly derived from `MooseObject` and several interface classes), where we can put the common codes in. This also provides us a capability to check if an object is changing residual or Jacobian during the run-time.

## Impact
A suggestion for better code.

**Comment by permcody** [comment]
FYI @fdkong
