### ISSUE TITLE
Initializing equation system......................................................................................................................................................................................................................................................................................................

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#13615]
## Reason
Has the _Initializing equation system_ stage gotten slower? I suddenly have (dbg mode) tests in Marmot failing, where this takes the bulk of the run time. The enhancement request would be to make it faster :-). Totally not a bug, NQA people!

## Design
Designs needs to be discussed, if this is an issue at all.

## Impact
Performance improvement.

**Comment by permcody** [comment]
Are we sure that this is slower? The TimedPrint thing was added this week to show us where we are spending time (when we spend time). Have you compared the Perf graphs? Can you give us any more information about when this may have happened?
