### ISSUE TITLE
Acronyms in documentation

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#13611]
## Bug Description
In the documentation system (e.g., moose_srs.md), the !!acro FRED!! construct is broken.  It appears that everything on the line after that appearance is thrown away.

## Steps to Reproduce
See https://mooseframework.org/sqa/moose_srs.html

## Impact
This makes the documentation very tough to follow.

**Comment by permcody** [comment]
FYI @aeslaughter

**Comment by aeslaughter** [comment]
Yes, I added a comment extension that used !!. The !!acro ...!! acro syntax was changed, I just didn't update it.

**Comment by aeslaughter** [comment]
closed by #13625
