### ISSUE TITLE
MOOSE Tutorial Updates

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#13617]
## Reason

Over the years the MOOSE tutorial has gained several part a, part b stuff. It is would be better for the flow to create new steps instead of sub-dividing.

There also needs to be a descriptive version on the main website; the slides are not intended to be followed outside of our live workshops.

Also, there are some more general improvements with respect to the language used.

### New (old) steps for tutorial

- [x] 1 (1): Simple Diffusion
- [x] 2 (2): Kernels (DarcyPressure -> Kernel)
- [x] 3: DarcyPressure -> ADKernel
- [x] 4 DarcyPressure -> ADDiffusion, discuss optimization and object inhertence (KernalGrad, KernalValue); 
- [x] 5 (3): Material
- [x] 6: Function (new; update PackedColumn to use functions instead of constants)
- [x] 7: Convert to ADMaterial; discuss getAD...; 
- [x] 8 (4): Velocity Aux (update to use VectorAuxVariable)
- [x] 9: (5): Heat Conduction (remove BC for later)
- [x] 10: ICs: Create and Initial condition that varies with vertical (radial) direction
- [x] 11 BCs; create HeatConductionOutflow 
- [x] 12: (6) Equation Coupling
- [x] 13: Add data interpolation functions to ADMaterial (material coupling)
- [x] 14: (7) Adaptivity (remove d)
- [x] 15: MeshModifiers/Generators (use current 7d)
- [x] 16 (8):  Postprocessors and VPPs (and use PP to compare out flow conditions)
- [ ] 17: Controls: use TimePeriod to disable stuff during BC ramp-up
- [x] 18 (9): Mechanics
- [x] 19 (10): MultiApps/Transfers
- [x] 20 (11): Actions

##  FEM, Shape Functions, Solver...
We need to break up these sections, dumping them all on the user at the same time is too much. It should be possible to sprinkle them in through the sections as we go, but we need to talk about how and where they fit in.

### Other Improvements

- [x] The solver pages should only cover NEWTON and PJFNK, adding JFNK and FD slides just
adds confusion, we can add numerical solve debugging section and then talk about FD.
- [x] There needs to be specific pages on preconditioning, I think it should be separate from the solver pages (i.e., doc/content/numerical/preconditioning.md)
- [ ] The movie for multi-scale displacement 500x should be 50x
- [x] Investigate the 'por_var' in current step10_micro.i
- [x] The producer/consumer language should be used as much as possible
- [x] The title slides for the systems (and any other import information) should link to our main website pages. Doing this is a bit tricky since the tutorial is created independently, so links will have to be create as relative html links that just will be broken if the main website is not there, which should be fine since the plan is to just use the website when giving the training.

## Impact

This will add an improved training experience.

**Comment by aeslaughter** [comment]
@friedmud FYI, this is the issue I started for training revisions.

**Comment by aeslaughter** [comment]
@lindsayad Should ADMaterial have "_ad_q_point" if you are wanting to propagate derivatives through to properties that are evaluated from a spatially varying function?

**Comment by aeslaughter** [comment]
In one of the steps we have the following:

```c++
template <ComputeStage compute_stage>
void
PackedColumn<compute_stage>::computeQpProperties()
{
  Real value = _radius.value(_t, _q_point[_qp]); # _radius is a Function
  _permeability[_qp] = _ad_permeability_interpolation.sample(value); # 
}
```
It seems like the function should accept the _ad_q_point[_qp] so the derivative is correct going into the ADLinearInterpolation object.

**Comment by dschwen** [comment]
ADFunctions are not quite there yet and there is a libmesh issue for ad qpoints that needs to be resolved if I recall correctly.

**Comment by aeslaughter** [comment]
Thanks, I will just use _q_point for now, with upgrading later in mind.

**Comment by lindsayad** [comment]
Yea as @dschwen said we can't feed a `DualNumber` into a function yet...

**Comment by GiudGiud** [comment]
#25381 will catch the rest of what mattered here
