### ISSUE TITLE
Handling PETSc options database with multiple PETSc apps

### ISSUE THREAD

**Issue by BarrySmith** [idaholab/moose#13623]
When MOOSE is running a simulation that involves two or more PETSc applications it becomes difficult to utilize the PETSc options database in the applications since by default it is shared by all applications. 
Recently I added a new feature to PETSc https://bitbucket.org/petsc/petsc/pull-requests/1782/add-petscoptionspush-and-petscoptionspop/diff 

PetscOptionsPush(PetscOptions options) and PetscOptionsPop() which allow users to change the default options database for parts of their simulation based on a suggestion by Sophie Blondel.  With this,. each MOOSE app can manage their own options database. But it occurred to me it could go a bit further and MOOSE could manage the Pushing and the Poping. Before each time entering a MOOSE app the framework could push the appropriate PetscOptions and immediately on exiting pop the options. The pushing and poping is very light weight and MOOSE could do it for all of its running apps without worrying about which ones are PETSc apps or not.

A slightly more difficult question is how each app should "load" its database. The simplest model just has each app mange this themselves with, for example, PetscOptionsInsertFile() or PetscOptionsInsertString()

**Comment by friedmud** [comment]
Thanks @BarrySmith !  This looks perfect for our usage.  We’ll put in support for it soon.

Thanks again!

**Comment by permcody** [comment]
FYI - @fdkong

**Comment by fdkong** [comment]
It is interesting. We have been thinking about this capability for a while.
