### ISSUE TITLE
Document memory and compute usage for PorousFlow Kuzmin-Turek

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#13637]
## Reason

Kuzmin-Turek stabilization is memory and compute intensive.  It would be good to have documentation quantifying this.

## Design

At the moment i'm using `porous_flow/test/tests/numerical_diffusion/framework.i` and `porous_flow/test/tests/numerical_diffusion/pffltvd_action.i`, and increasing their mesh sizes, running over multiple processors, and recording the output.  I'll document the results in a new markdown page.

## Impact

Easier for users to understand memory and CPU usage, and therefore run MOOSE more effectively.  Also, i might be able to figure out ways of reducing mem+CPU as i do this study.

@hsheldon

**Comment by permcody** [comment]
Closed by #13647.
