### ISSUE TITLE
MOOSEDocs: links are same color as note box heading background

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13658]
## Bug Description
There is at least one instance where a link is used in a note box header: the "Core Extension" page of the MOOSEDocs documentation. The link "Markdown" is invisible in the first note. The fix may just be to not use links in note headers, rather than change colors.

## Steps to Reproduce
See above.

## Impact
The link text is invisible.

**Comment by aeslaughter** [comment]
This is just a CSS change that needs to be made, it would be nice if you could find the example.
