### ISSUE TITLE
getUserObject in FEProblemBase is shadowed by the new member function macros

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#13650]
## Bug Description
```
error: 'class FEProblemBase' has no member named 'getUserObjectTempl'; did you mean 'getUserObjects'?
       from_problem.getUserObjectTempl<NeutronicsSpectrumSamplerBase>(_neutronics_pdf_name);
                    ^~~~~~~~~~~~~~~~~~
```

In multi app contexts it may be necessary to access user objects form other FEProblems. It is not possible to use `_problem.getUserObject<...>` anymore because this gets substiituted by the new macros to `_problem.this-> template getUserObjectTempl<...>`, which is garbage. We need a `_problem.getUserObjectTempl<...>` member!

## Steps to Reproduce
Look at https://civet.inl.gov/job/358308/ for example.

## Impact
Breaks multi app stuff. (Yes, this is a bug @permcody!)

**Comment by permcody** [comment]
I'm not sure why you have to point out what a bug is to me, I am aware 😉

**Comment by permcody** [comment]
Working hard to get apps updated. This was a big API-breaking change.

**Comment by dschwen** [comment]
Sorry, should have double checked first!

**Comment by dschwen** [comment]
Yeah, better now than later.
