### ISSUE TITLE
Add option to enable mortar contact to ContactAction

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#13676]
## Reason
To facilitate the adoption of the new mortar based contact system we should add an option to enable it in the existing `ContactAction`.

## Design
Keep design of the existing action, add additional code path to add objects required for mortar based contact. (as discussed in #13508).

## Impact
Ease of use.

**Comment by tophmatthews** [comment]
Just so this doesn't fall off the map...is there plans to wrap up this feature?

**Comment by dschwen** [comment]
Yes, thanks for the reminder. I'm on travel right now but I'll try to get back to it in a week or two.
