### ISSUE TITLE
Investigate capturing STDERR and appending it to STDOUT for failed tests

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#1368]
It would be nice to see the error message when tests crash in the TestHarness output.  Right now we typically have to run the test individually to see all of the output.

**Comment by permcody** [comment]
Pretty sure this is simply not possible. I don't usually say that either...

**Comment by friedmud** [comment]
I don't understand?  Why is this not possible?

It looks to me like @milljm already kinda did it... is it not working now?

**Comment by friedmud** [comment]
Note: I reopened because I don't want to lose track of this...

**Comment by permcody** [comment]
As far as I know you can't capture messages from the OS. I can't capture
the fact that a test received a signal 11 from the OS. All I know is that
it exited with a non-zero error code but I lose the actual message...

**Comment by friedmud** [comment]
This ticket is about capturing `stderr` though... not OS messages.

My question is: are we properly capturing `stderr` and combining it with `stdout` for our logs?  If so... then we can close this ticket...

**Comment by permcody** [comment]
We are capturing stderr
