### ISSUE TITLE
A mesher with Triangle

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#13695]
## Reason
Often times it is desired to have an integrated mesher that can generate unstructured meshes (instead of loading a pre-generated mesh by meshers) for subdomains of the entire geometry, for example, reflector domain surrounding the core, neck shim housing assembling in ATR, etc., where other parts of the geometry is meshes with some other tools including MOOSE mesh generators.

## Design
Using Triangle that have been wrapped in libMesh is a good starting point. This mesher will be in the mesh generation system and of course will only work when libMesh is configured with `--disable-strict-lgpl`.

## Impact
New capability. Minor works could be needed in the existing generators so that meshes from Triangle mesh can be stitched with other meshes.

**Comment by GiudGiud** [comment]
This https://github.com/idaholab/moose/issues/20192 is the preferred way forward on this.
Closing this
