### ISSUE TITLE
Skip bounding box test in MultiAppUserObjectTransfer

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#13701]
## Reason

`MultiAppUserObjectTransfer` does not set value in `to_elem` if it is not within bounding
box of `from_app`. This is a rather arbitrary and honestly confusing behavior. At the very least, there are legitimate cases where the bounding box check makes no sense, e.g. transferring 1D layered values from RELAP-7 to another app.

## Design

Allow user to switch this check off.

## Impact

Additional option, none.

**Comment by GiudGiud** [comment]
@snschune fyi in the coming general field UO transfer, this will not be included as is but it will be an option to set the size of the bounding boxes manually (so as infinity it will have the same effect)
