### ISSUE TITLE
AD support for scalar variables

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#13703]
## Reason
Folks should be able to couple scalar variables into AD objects and have their Jacobians work out like they're used to.

## Design
Add methods like `adCoupledScalarValue` to `ScalarCoupleable` and add AD calculations to `MooseVariableScalar`.

## Impact
Continue to make AD more flexible and generally useful for users

**Comment by joshuahansel** [comment]
THM is very interested in this. We have our 0-D components that make use of scalar variables, for example, so we cannot fully  adopt AD until there is this support.

Also, I think it is not strictly required, but AD scalar kernels would make things much easier.

**Comment by lindsayad** [comment]
As this issue is described, this is actually closed by #13704. But we could change this to include creation of ADScalarKernels

**Comment by joshuahansel** [comment]
We'll keep this issue's description, so it's closed. I'll make a new issue.
