### ISSUE TITLE
Remove a global communication from getBoundaryIDs

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#13715]
## Bug Description

In` MooseMesh.C, getBoundaryIDs`, we try to collect all boundary IDs together, which involves 
one global communication. It is expensive and unnecessary since `_mesh_bounary_ids` already has the same information.

## Steps to Reproduce

Remove unnecessary  code.

## Impact

Improve parallel performance

**Comment by permcody** [comment]
Not a bug. This would be an enhancement. The code worked properly before, it was just not efficient. Try to think about the classification when you open an issue.

**Comment by fdkong** [comment]
> Not a bug. This would be an enhancement. The code worked properly before, it was just not efficient. Try to think about the classification when you open an issue.

It is indeed a bug. Think about you run the code with a lot of cores, and the interior cores might not see any boundary.  Boundary cores will call `addBC`, but the interior cores do not `addBC`, and then the code will be deadlock. I hit this in RattleSnake it is why I was attempting to change this.
