### ISSUE TITLE
Expand coupling functor support in RelationshipManager system

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#13736]
## Reason
@WilkAndy has reported that he's seeing a lot of mallocs in `MatSetValues` in PETSc which is indicative that we don't have the sparsity pattern correct.

## Design
We already have `RelationshipManagerType::COUPLING`, so when that enumerator is chosen we can make sure to call `DofMap::add_coupling_functor`. We will also want to make sure that we make use of the information in our `CouplingMatrix` so that we don't end up greatly expanding our sparsity pattern in an unnecessary way.

## Impact
Avoid `MatSetValues` mallocs which ***dramatically*** slow down simulations.

**Comment by WilkAndy** [comment]
I'm really grateful that you're doing this, thank you Alexander,

a

**Comment by WilkAndy** [comment]
For testing, you could use
```
cd moose/modules/porous_flow/test/tests/flux_limited_TVD_advection
../../../porous_flow-opt Executioner/end_time=6E-2 VectorPostprocessors/tracer/num_points=1 Mesh/nz=N Mesh/ny=N -i fltvd_3D.i
```
where you should see some speedup for N>10, and probably x2 speedup for N>16
