### ISSUE TITLE
PiecewiseMultilinear sensitive to number of spaces (possibly GriddedData bug)

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#13740]
## Bug Description
An extra space in the data file causes an error in this function (I haven't looked but I think that it is probably in GriddedData).

## Steps to Reproduce
Just add an extra space in one of the tests. For example, consider the test https://github.com/idaholab/moose/blob/next/test/tests/functions/piecewise_multilinear/twoDa.i

This test reads the following data file (https://github.com/idaholab/moose/blob/next/test/tests/functions/piecewise_multilinear/twoD1.txt)
```
# This is the function 1 + 2x + 3y
AXIS X
-1.0 0.0 2.0
AXIS Y
-1.0 2.0 3.0
DATA
-4.0
-2.0
2.0
5.0
7.0
11.0
8.0
10.0
14.0
```

If we add an extra space in the `AXIS X` data like so:
 ```
# This is the function 1 + 2x + 3y
AXIS X
-1.0  0.0 2.0
AXIS Y
-1.0 2.0 3.0
DATA
-4.0
-2.0
2.0
5.0
7.0
11.0
8.0
10.0
14.0
```
then the test doesn't run and gives the following error:

```
*** ERROR ***
According to AXIS statements in GriddedData, number of data points is 12 but 9 function values were read from file
```

It looks like the extra space is being counted as a data point in the AXIS data, so that now 12 data points are expected.

## Impact
It is hard to see the error in the data if it is just an extra space.

**Comment by cpgr** [comment]
@WilkAndy - I think you wrote this. Any hints where the problem might be?

**Comment by WilkAndy** [comment]
Yea, the problem lies in GriddedData::splitToRealVec(...).  I think we might need something like `if (!item.empty())` then do the push_back.

**Comment by cpgr** [comment]
Ok. I'll have a go at fixing it tonight

**Comment by WilkAndy** [comment]
Thanks @cpgr
