### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by nburgessCarbon** [idaholab/moose#13745]
## Bug Description
While trying to compile the moose tests I get the following error:
/home/nburgess/Software/moose/framework/src/variables/MooseVariableData.C:693:51: error: no matching function for call to ‘std::vector<Eigen::Map<Eigen::Matrix<double, 3, 1> > >::resize(unsigned int&, std::nullptr_t)’
       _mapped_grad_phi_face[i].resize(nqp, nullptr);
                                                   ^
In file included from /usr/include/c++/7/vector:64:0,
                 from /home/nburgess/Software/moose/scripts/../libmesh/installed/include/libmesh/perf_log.h:32,
                 from /home/nburgess/Software/moose/framework/build/header_symlinks/Moose.h:12,
                 from /home/nburgess/Software/moose/framework/build/header_symlinks/MooseTypes.h:12,
                 from /home/nburgess/Software/moose/framework/build/header_symlinks/Coupleable.h:13,
                 from /home/nburgess/Software/moose/framework/build/header_symlinks/CoupleableMooseVariableDependencyIntermediateInterface.h:12,
                 from /home/nburgess/Software/moose/framework/src/variables/CoupleableMooseVariableDependencyIntermediateInterface.C:10,
                 from /home/nburgess/Software/moose/framework/build/unity_src/variables_Unity.C:2:
/usr/include/c++/7/bits/stl_vector.h:689:7: note: candidate: void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type) [with _Tp = Eigen::Map<Eigen::Matrix<double, 3, 1> >; _Alloc = std::allocator<Eigen::Map<Eigen::Matrix<double, 3, 1> > >; std::vector<_Tp, _Alloc>::size_type = long unsigned int]
       resize(size_type __new_size)
       ^~~~~~
/usr/include/c++/7/bits/stl_vector.h:689:7: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/7/bits/stl_vector.h:709:7: note: candidate: void std::vector<_Tp, _Alloc>::resize(std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = Eigen::Map<Eigen::Matrix<double, 3, 1> >; _Alloc = std::allocator<Eigen::Map<Eigen::Matrix<double, 3, 1> > >; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::value_type = Eigen::Map<Eigen::Matrix<double, 3, 1> >]
I'm using gcc 7.4.0 to cpmpile moose and Eigen 3.3.4 on Ubuntu  18.04 LTS. Because I'm compiling in parallel I get several of these exact same errors for different lines of code in different files.  

## Steps to .Reproduce
cd <path to moose>/test
make -j 4
## Impact
Since I can't compile I can't really do anything.  
Do I need to set a flag in gcc to get around this?

Thanks, 
Nick

**Comment by permcody** [comment]
Is it possible that you have a separate version of Eigen installed? We expect to pickup Eigen from libMesh. We aren't running into this on any of our Mac or Linux workstations so I'm trying to figure out what's different about your system.

**Comment by YaqiWang** [comment]
That line is doing something similar like the code snippet at the end of this link (https://eigen.tuxfamily.org/dox/group__TutorialMapClass.html).

**Comment by permcody** [comment]
I'm just confused why 2 people have reported this now, but we can't seem to replicate it on any system we have.

**Comment by YaqiWang** [comment]
Based on that link, `nullptr` seems a valid constructing way for a map. Maybe we should have
```
resize(nqp, Eigen::Map<RealDIMValue>(nullptr));
```
?

**Comment by permcody** [comment]
I believe it is for our version of Eigen. Note that in general, nullptr isn't valid unless the object you are constructing accepts a nullptr argument or you have an actual pointer object as your value. That's why I'm questioning versions of Eigen here.

**Comment by YaqiWang** [comment]
@nburgessCarbon can you try this patch really quick?
```
diff --git a/framework/src/base/Assembly.C b/framework/src/base/Assembly.C
index 90dcac5233..5ed88f197d 100644
--- a/framework/src/base/Assembly.C
+++ b/framework/src/base/Assembly.C
@@ -1092,7 +1092,7 @@ Assembly::reinitFEFace(const Elem * elem, unsigned int side)
   _current_normals.shallowCopy(
       const_cast<std::vector<Point> &>((*_holder_fe_face_helper[dim])->get_normals()));
 
-  _mapped_normals.resize(_current_normals.size(), nullptr);
+  _mapped_normals.resize(_current_normals.size(), Eigen::Map<RealDIMValue>(nullptr));
   for (unsigned int i = 0; i < _current_normals.size(); i++)
     // Note: this does NOT do any allocation.  It is "reconstructing" the object in place
     new (&_mapped_normals[i]) Eigen::Map<RealDIMValue>(const_cast<Real *>(&_current_normals[i](0)));
diff --git a/framework/src/variables/MooseVariableData.C b/framework/src/variables/MooseVariableData.C
index e09145a614..2c7629b2bd 100644
--- a/framework/src/variables/MooseVariableData.C
+++ b/framework/src/variables/MooseVariableData.C
@@ -678,7 +678,7 @@ MooseVariableData<RealEigenVector>::computeValues()
     _mapped_grad_phi.resize(num_dofs);
     for (unsigned int i = 0; i < num_dofs; i++)
     {
-      _mapped_grad_phi[i].resize(nqp, nullptr);
+      _mapped_grad_phi[i].resize(nqp, Eigen::Map<RealDIMValue>(nullptr));
       for (unsigned int qp = 0; qp < nqp; qp++)
         // Note: this does NOT do any allocation.  It is "reconstructing" the object in place
         new (&_mapped_grad_phi[i][qp])
@@ -690,7 +690,7 @@ MooseVariableData<RealEigenVector>::computeValues()
     _mapped_grad_phi_face.resize(num_dofs);
     for (unsigned int i = 0; i < num_dofs; i++)
     {
-      _mapped_grad_phi_face[i].resize(nqp, nullptr);
+      _mapped_grad_phi_face[i].resize(nqp, Eigen::Map<RealDIMValue>(nullptr));
       for (unsigned int qp = 0; qp < nqp; qp++)
         // Note: this does NOT do any allocation.  It is "reconstructing" the object in place
         new (&_mapped_grad_phi_face[i][qp])
```

**Comment by rwcarlsen** [comment]
@YaqiWang - that is the right fix let's get a PR in for it quick.

**Comment by nburgessCarbon** [comment]
Hi everyone, 
Thanks for all your responses.  I can confirm that the diff fixes the problem.  I've removed my system Eigen and recompiled libMesh to see if that's the only issue.

**Comment by rwcarlsen** [comment]
Note that the patch should fix this problem for *any* version of eigen.
