### ISSUE TITLE
XFEM Moving Interface with Two Discrete Materials

### ISSUE THREAD

**Issue by jbtompkins** [idaholab/moose#13756]
## Reason
In order to simulate two materials in contact with each other where a discrete boundary between them moves through the system, there is an instantaneous jump in the value of the flux at the interface between materials. This jump in flux can be described using Real values or Functions, but currently only Real values are allowed.

## Design
Need to add capability for XFEMSingleVariableConstraint to accept a function (instead of a Real value as it currently does) for the jump_flux variable to accurately simulate the change in flux between material regions at the interface location at each timestep. Tests for the type change implementation and verification of the XFEM module running a two material problem with a moving interface are needed.

## Impact
The only change affecting other code is the type change of the jump_flux variable. Usage of the current default (jump_flux = 0) of type Real is not a problem as any constant Real value is converted to a parsed function to fit the parameter's new type (Function). Testing of the XFEM module shows this to be the case.

**Comment by permcody** [comment]
Closed by #13808.
