### ISSUE TITLE
PNGOutputter resolution doesn't make sense and can't select the variable for the image.

### ISSUE THREAD

**Issue by Hysrok** [idaholab/moose#13780]
## Reason

We need to be able to use resolution and know exactly what we're going to get with it.  We also need to be able to select the variable that we want to use to create the image.

## Design

Make resolution represent something measurable (such as length of longest side in pixels).
Make it possible change which variable we are using to create the image (such as "bnds" instead of "gr0")

## Impact

Minor

**Comment by permcody** [comment]
closed by #13782
