### ISSUE TITLE
TestHarness printout should handle new nesting layers in test spec

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#13793]
## Reason

The MOOSEDocs system recently augmented the available syntax for Test Specs making another layer possible

e.g.
```
[Tests]
  [some_requirement]
    requirement = 'The system shall do this thing:'
  
    [1D]
       ...
       detail = 'in 1D, and'
    []
    [2D]
       ...
       detail = 'in 1D.'
    []
  []
[]
```

It would be handy if the way we printout the test included these levels.

## Design

Make that TestHarness merge all of the levels of the testing hierarchy in the printout. Right now the middle level (in the example above "some_requirement") does not appear in the printout.

## Impact

Minor: Usability

**Comment by permcody** [comment]
@milljm - Do you have any time to take a look at this? It's actually pretty important since sometime the innermost level is not unique. So it'll look like we are running the same test multiple times. Also, we'll want to make sure that REs work with the intermediate level, etc.

**Comment by permcody** [comment]
Promoting to "critical" priority!

**Comment by milljm** [comment]
I'll look into it

**Comment by permcody** [comment]
There are several in the tests/postprocessors/* directory that were merged in last week. Take a look at the diff here to find them:
https://github.com/idaholab/moose/pull/13779/files
