### ISSUE TITLE
ElementVariablesDifferenceMax could be refactored to use SamplerBase

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#13792]
## Reason

This VPP records a piece of information and then several other attributes about that piece of information. This is precisely what the `SamplerBase` does. This VPP could be refactored to inherit from that post processor eliminating most of the code.

## Design

Make ElementVariablesDifferenceMax VPP inherit from SamplerBase

## Impact

Minor

**Comment by pbehne** [comment]
I have started working on this and have run into a potential issue. The refactor strategy would involve eliminating attributes `_a_value`, `_b_value`, `_max_difference`, `_position_x/y/z`, and `_all` and instead store this information in `SamplerBase`'s attributes, via the `addSample` method. This would likely be done in `ElementVariablesDifferenceMax::execute`. Being an `ElementVectorPostprocessor`, `execute` is called for every element on the local mesh. In the current implementation of `execute`, quadrature points in the element are looped over and when a new maximum difference is found, relevant variable values are overwritten. If the refactor were to follow the same general logic, `addSample` would be called every time a new max difference is found. However, this would not overwrite previously added samples during the search for the maximum, which would increase storage requirements. I can think of 2 way around this:

1. Do not call 'addSample' in 'execute'. Instead, keep those original attributes (`_a_value`, `_b_value`, `_max_difference`, `_position_x/y/z`, and `_all`) and use them to call `addSample` in `finalize`. I think that this defeats the purpose of the refactor and is therefore silly.
2. Add a new method(s) to `SamplerBase` that allows the deletion or overwritting of previously added samples. When a new max difference is found, use "deteleSample", followed by `addSample`, or just use "replaceSample" (method in quotes do not currently exists and would have to be defined).

If neither option is desirable, maybe the vpp should be left as is.

**Comment by pbehne** [comment]
After speaking with @permcody, it was decided that the purposes of `ElementVariablesDifferenceMax` and `SamplerBase` are fundamentally different. While `SamplerBase` was designed to store variable information for many different spatial positions, `ElementVariablesDifferenceMax` was designed to store variable information for a single spatial point. Therefore `ElementVariablesDifferenceMax` should not be refactored to inherit from `SamplerBase` and this issue should be closed.

**Comment by permcody** [comment]
Agreed, closing as "won't fix"
