### ISSUE TITLE
Allow automatic scaling factors to be printed

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#13795]
## Reason
This would allow users to see the scaling factors that are computed by MOOSE.

## Design
A possible design would be to print these to the console whenever the `verbose` parameter of the `Outputs` block is true and automatic scaling is used.

## Impact
Extra output.

**Comment by joshuahansel** [comment]
@lindsayad I already have this done, so I'll just go ahead and make a PR for this.

**Comment by lindsayad** [comment]
awesome
