### ISSUE TITLE
Enhancements of BlockDeleter

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#13807]
## Reason
Currently `BlockDeleter` only allows deletion of one block (subdomain). It will be nice if we can delete multiple blocks in one modifier. Also it could desired that we can delete all other blocks but keep those in the block list.

## Design
`ElementDeleterBase` has done the majority of the job, so it should be fairly simple to extend `BlockDeleter`. Also we need to extend its corresponding mesh generator.

## Impact
New capability.

**Comment by permcody** [comment]
Mesh Modifiers are being deprecated today! No need to do any more work on the old system. I'll be pushing up a PR to make that official and will start removing tests, etc. It's time to settle on one system.

**Comment by YaqiWang** [comment]
Yes, if we implement this, currently we need to do the same at two places.

**Comment by GiudGiud** [comment]
BlockDeletionGenerator does all that was asked for. See my old PR a year ago:
#17056
