### ISSUE TITLE
Recent changes in MOOSE make several tests consistently timeout in dbg mode

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#13802]
## Reason
Several Rattlesnake tests consistently time out currently in debug mode. It can be checked out on Civet Rattlesnake devel page. This prevents merge requests to be merged into Rattlesnake. Timely print-out shows the slowness is in Initializing equation system.

## Design
Looks like something accidentally slows down the debug executable significantly.

## Impact
Testing and our work-flow.

**Comment by permcody** [comment]
Yaqi - Do you have time to revert this PR? https://github.com/idaholab/moose/pull/13775

I suspect we are adding coupling functors that probably don't need to be added causing your slowdown. This was merged 3-days ago to speed up the previous coupling functor merge that happened prior to that. I'm not immediately sure if this is it, but it appears your slowdowns started 3 days ago, which was when this was merged. 

Any ideas @lindsayad?

**Comment by permcody** [comment]
Nevermind - I just reviewed and merged #13806. Will close when we have verified that the issue has been resolved.

**Comment by YaqiWang** [comment]
Thanks Cody. I forgot letting @lindsayad to refer to this issue.

**Comment by permcody** [comment]
Closed by #13806
