### ISSUE TITLE
Restartable Mesh MetaData store

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#13841]
## Reason

MeshGenerators are not rerun on restart. Instead we reload a checkpointed mesh object. This is a problem if Actions or other parts of the system want to interrogate the specific type of Mesh object for information to setup other parts of the system.

## Design

The design will be to introduce a data store of some type either on the mesh or as a separate object that is all restartable (probably key/value pairs), values also might be different types so perhaps a restartable "Parameters" object.

## Impact

Moderate: This needs to be designed and deployed before MeshModifiers can be removed (they are currently deprecated).

**Comment by YaqiWang** [comment]
Will the mesh generators still be constructed during restart? If so, that may be sufficient for other systems that interrogate the mesh generators.

**Comment by permcody** [comment]
Ultimately we are heading down a road to where we have only one type of Mesh. Eventually we will deprecate **all** derived types. Everything else will be converted to a MeshGenerator. The reason for this is to return to simplicity. No more dynamic casting mesh or having special cases on restart, which we are finding is increasingly difficult. There will be MooseMesh and arbitrary generators. The  data store will be the new mechanism for storing "extra" data whatever that may be. Generators will have full access to populate that data as they see fit. So the interrogation will also be uniform. It'll take some time to get there, but I think this will be a more straight-forward system.

**Comment by permcody** [comment]
If you have any comments or questions about the design - stop by sometime and we can chat before we get this implemented. In the meantime, I'll probably extend the dates out on the MeshModifiers for some time as we clearly can't remove them quickly.

**Comment by permcody** [comment]
Tag @gambka

**Comment by permcody** [comment]
Closed by #14190.
