### ISSUE TITLE
Strange argument skipping logic in Parser::hitCLIFilter

### ISSUE THREAD

**Issue by scgehin** [idaholab/moose#13851]
if (!afterDoubleDash) would never evaluate true if it's running after if (arg.find("=", 0) == std::string::npos). If arg doesn't contain an "=", then if (arg.find("=", 0) == std::string::npos) continues. If it does, then else if (arg.find("=", 0) != std::string::npos) will set afterDoubleDash to true. There's also quite a few unnecessary else ifs.

**Comment by permcody** [comment]
Tag @rwcarlsen
