### ISSUE TITLE
PorousFlow minor optimisations

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#13857]
## Reason
The good thing about the porous flow module is its generality, but this does mean that some cases run a bit slower than they otherwise could. Some small optimisations could be introduced to avoid some calculations and speed up these simulations.

## Design
There are probably heaps of things we could do internally without having to change any input files. There is definitely some low hanging fruit that can be cleaned up easily enough.

## Impact
Make some simulations faster for users

**Comment by permcody** [comment]
Closed by multiple PRs listed above.
