### ISSUE TITLE
Minor fix of typos in RotationTensor.C

### ISSUE THREAD

**Issue by rayaprolu143** [idaholab/moose#13864]
## Reason

The components of the rotation tensor are incorrectly mapped (e.g. R11, R12....).
## Design

Fixing the comments
## Impact

No functional changes. This change clears any confusion when one is looking both EulerAngleUpdater.C and RotationTensor.C for computing Euler angles from rotation matrix.

**Comment by rayaprolu143** [comment]
The comments after line 43 in RotationTensor.C have to fixed. I propose the following changes.

`void
RotationTensor::update(const RealVectorValue & euler_angles)
{
  const Real phi_1 = euler_angles(0) * (libMesh::pi / 180.0);
  const Real Phi = euler_angles(1) * (libMesh::pi / 180.0);
  const Real phi_2 = euler_angles(2) * (libMesh::pi / 180.0);

  const Real c1 = std::cos(phi_1);
  const Real c2 = std::cos(Phi);
  const Real c3 = std::cos(phi_2);

  const Real s1 = std::sin(phi_1);
  const Real s2 = std::sin(Phi);
  const Real s3 = std::sin(phi_2);

  // doing a Z1, X2, Z3 rotation
  // RealTensorValue is formed row-wise

  _coords[0] = c1 * c3 - c2 * s1 * s3;  // R11
  _coords[3] = -c1 * s3 - c2 * c3 * s1; // R21
  _coords[6] = s1 * s2;                 // R31

  _coords[1] = c3 * s1 + c1 * c2 * s3; // R12
  _coords[4] = c1 * c2 * c3 - s1 * s3; // R22
  _coords[7] = -c1 * s2;               // R32

  _coords[2] = s2 * s3; // R13
  _coords[5] = c3 * s2; // R23
  _coords[8] = c2;      // R33
}
`

**Comment by dschwen** [comment]
Just make a pull request. We can see the changes there.

**Comment by permcody** [comment]
closed by #13866
