### ISSUE TITLE
Cleanup deprecated tests and code in moose test and modules

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#13909]
## Reason

 Recent changes in #13849 and #13769 have caused deprecation failures in these modules and my downstream app that depends upon these modules.

## Design

Make the necessary changes to the action API in the actions and cleanup tests using the deprecated MeshModifiers to use the new nested generator approach.

## Impact

Make tests in the TensorMechanics, Contact, and HeatConduction modules pass deprecated.

**Comment by lindsayad** [comment]
@gambka Let me know if you *have not* started working on this yet, and I will take care of it

**Comment by gambka** [comment]
@lindsayad I have started TM.  I updated the max-failures on run tests to 800 and it said 574 tests failed the deprecated syntax. I've updated the actions and fixed the majority of the MeshModifer and MeshGenerator deprecation. I have 11 tests remaining. I was going to do each module as a separate PR (many input files needed to be modified for the MeshModifier deprecation), so if you want to do HeatConduction and Contact (I am sure other modules are affected) but these were the ones that I need.

**Comment by lindsayad** [comment]
Alrighty sounds like a plan. I think SM might also need work as well. I will do SM too

**Comment by gambka** [comment]
SM is likely similar to TM.  In the near future the whole SM module will be deprecated as TM can reproduce the same functionality but a different system and input file syntax.

**Comment by gambka** [comment]
I have almost all of the deprecated tests for TM fixed (both add*Variable API and MeshGenerator deprecations) including heavy, examples, and tutorials.  One test in the tutorials that I cannot get to match.  By switching to use the MeshGenerator syntax by applying a `ExtrudeGenerator` on a read in `FileMesh` complains that a boundary doesn't exist in the mesh.  Why would the MeshModifier and `FileMesh` approach work correctly but the MeshGenerator approach does not? It is the last test to ensure TensorMechanics has no failures with --error-deprecated.

**Comment by lindsayad** [comment]
I am currently working on cleaning up all remaining deprecation messages in all the modules, so hopefully no one else is doing the same!

**Comment by gambka** [comment]
I am not working on any more modules but I did run into an addVariable API deprecation message from an action in the framework itself. From: `SetupResidualDebugAction.C`. Can you check framework as well?

**Comment by lindsayad** [comment]
Closed by #14061
