### ISSUE TITLE
Add AD support to support functions

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#13927]
## Reason
AD requires templated versions of several helper functions in order to make the transition easier.

## Design
- [ ] `ElasticityTensorTools::getIsotropicBulkModulus`
- [ ] `ElasticityTensorTools::getIsotropicYoungsModulus`
- [ ] `ElasticityTensorTools::getIsotropicPoissonsRatio`

## Impact
Mo' better AD proliferation

**Comment by tophmatthews** [comment]
@lindsayad @dschwen not sure who can get to it and when, but at least we can start listing them.

**Comment by dschwen** [comment]
I can add those

**Comment by tophmatthews** [comment]
that was quick 🤘
