### ISSUE TITLE
Critical Time Step for Explicit Solver

### ISSUE THREAD

**Issue by somu15** [idaholab/moose#13975]
Created a new PP "CriticalTimeStep" for computing the critical time step for an explicit integration scheme. "CriticalTimeStep" is geared to be a general class that should work for different element types. 

This class receives an "effective stiffness" from an element class and density from the user. This implies modifications should be made to the element classes to compute "effective stiffness." Such modifications for this issue and PR are made to elastic solid elements and elastic beam elements.

**Comment by dschwen** [comment]
There are still issues with this. For example in https://github.com/idaholab/moose/blob/e50815de01659e787fa3008d3f8345ab7c20f6b0/modules/tensor_mechanics/src/materials/ComputeIsotropicElasticityTensor.C#L44 @somu15 does exactly what @permcody complained about here https://github.com/idaholab/moose/pull/13985/files#r323343438

Also I believe @hugary1995 has some things to say about the effective local stiffness calculation.

This is not meant as putting blame anywhere, but more as an observation: The review of this feature went wrong at some point. Maybe the mechanics team dropped the ball here, but this should have been reviewed not only by framework people.

**Comment by dschwen** [comment]
The isotropic guarantee on a `Real` makes no sense. And I think the design should be revised overall. This adds a material property to the base class that is used and written to by only two sub classes (and is otherwise 0).

**Comment by somu15** [comment]
Thanks for your pointing these, @dschwen I will re-open this issue.

**Comment by dschwen** [comment]
Ha, this goes right back at me. @hugary1995 just alerted me to the fact that my review was requested and is still pending :-D. So, I should assign blame... to myself.

**Comment by hugary1995** [comment]
Here is the related issue: #15445
