### ISSUE TITLE
Documentation formatting error in C0TimoshenkoBeam.html

### ISSUE THREAD

**Issue by yw5aj** [idaholab/moose#14016]
At this page: https://mooseframework.org/modules/tensor_mechanics/C0TimoshenkoBeam.html

It seems like the equation formatting is messed up:

![image](https://user-images.githubusercontent.com/3477741/64639255-5c751480-d3bc-11e9-9b90-874180f245e1.png)

**Comment by permcody** [comment]
@aeslaughter - Is this a markdown issue or a parsing issue?

**Comment by aeslaughter** [comment]
This was fixed in [4f2700256a9f322b4c7b5bd05feec3b5e2fae18d](https://github.com/idaholab/moose/commit/4f2700256a9f322b4c7b5bd05feec3b5e2fae18d#diff-64c3056adc08eed3c989b56c6d40e303)

**Comment by aeslaughter** [comment]
FYI: `\end{equations}` should be `\end{equation}`
