### ISSUE TITLE
NodalBC has a member that may not be initialized

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14027]
## Bug Description

NodalBC::_qp is not initialized in the ctor of the object. This makes it possible for derived classes to access that member before initialization. This is possible since shouldApply() does get called before routines that initialize that member.

## Steps to Reproduce

Attempt to access _qp in NodalBC::shouldApply()

## Impact

Moderate: While none of our existing code accesses a qp index in shouldApply, there are valid reasons for doing so and you are likely to receive garbage if you do.

**Comment by lingzou** [comment]
@permcody Thanks for fixing this.

**Comment by permcody** [comment]
I have a patch ready for SAM. I need this merged so I can update their submodule. Tag @andrsd
