### ISSUE TITLE
MeshExtruderGenerator should not delete subdomain names of the mesh that is extruded

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#14037]
## Bug Description

The behavior of the `MeshExtruderGenerator` is different than the `MeshExtruder` mesh modifier in that existing subdomain names on the mesh to be extruded are deleted.  The subdomain IDs are the same between both cases. 

The behavior should be the same using Mesh and MeshModifiers or MeshGenerators when extruding a 2D mesh.

## Steps to Reproduce

One can see this behavior using the part_3_1.i input file in `modules/tensor_mechanics/tutorials/basics/`.  The old way is to use the following:

```
[Mesh]
  file = necking_quad4.e
  uniform_refine = 0
  second_order = true
[]

[MeshModifiers]
  [extrude]
    type = MeshExtruder
    extrusion_vector = '0 0 0.5'
    num_layers = 2
    bottom_sideset = 'back'
    top_sideset = 'front'
  []
[]
```
And the new way is:

```
[Mesh]
  [file_mesh]
    type = FileMeshGenerator
    file = necking_quad4.e
  []
  [extrude]
    type = MeshExtruderGenerator
    extrusion_vector = '0 0 0.5'
    num_layers = 2
    bottom_sideset = 'back'
    top_sideset = 'front'
    input = file_mesh
  []
  uniform_refine = 0
  second_order = true
[]
```
where the necking_quad4.e input mesh contains sidesets named bottom, left, right, and top. Using the old method the final extruded mesh contains 6 named sidesets, bottom, left, right, top, back, and front.  Using the new approach, the final mesh only contains named sideset front and back.  The IDs of the bottom, left, right, and top are the same in the final meshes using both approaches. 

This causes an issue when BCs, Postprocessors, etc. are defined to operate on the named boundaries when converting from the old deprecated syntax to the new approach as input files have to be further modified to use the boundary IDs rather than names. I also prefer to use names for the boundaries in my input files.

## Impact

This is an annoyance.  Eventually MeshModifiers will be removed and the same behavior should be preserved in the MeshGenerator approach.

**Comment by lindsayad** [comment]
@gambka should the title be about subdomains or side/nodesets?

**Comment by gambka** [comment]
You are probably correct it should be side/nodesets.  However, I did not check say block names.  Maybe the same behavior occurs with the block name being thrown away as well?

**Comment by permcody** [comment]
Yes, @lindsayad you are correct. I have updated the Title.
