### ISSUE TITLE
Make the input file parser accept fractions where Real numbers are requested

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#14041]
## Reason
It would make input files more readable and easier to write, if instead of for example `0.0666666666667` the users could specify `1/15`. Also, how many 6es do I need? Is the 7 cut off at some point and the number parsed as 0.0666666666? Will I need more sixes if I compile libmesh with higher precision numbers?! 

## Design
Wherever we parse a Real, check (if the parsing failed) if we can split the string into two halves with a `/` separator and parse the the parts as Reals. If this succeeds, interpret the parts as numerator and denominator. Perform the division and use that as the parsed value.

## Impact
Added capability. Tagging @permcody, @rwcarlsen, and @friedmud

**Comment by YaqiWang** [comment]
So is `/` the only operator we are going to support? For example, do we want `sqrt(2)`? I can see this `/` is useful to me ;-)

**Comment by permcody** [comment]
@dschwen - as discussed this extension would go into Parser.C as a specialization. I'm not sure how carried away we want to get. Supporting all const expressions is equivalent to function parsing. If you just want to support division great, but then Yaqi is going to want sqrt. Go ahead an put up a PR and let's take a look.

**Comment by dschwen** [comment]
Apparently people do not see as clear a line between fractional numbers and arbitrary mathematical expressions as I do. I'm not inclined (no pun intended) to be dragged into a "slippery slope" argument.
