### ISSUE TITLE
Enable multi-level Picard iterations to restart from the latest solution

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#14056]
## Reason

In #13310, the behavior of multi-level Picard iterations was fixed. However, for pseudo-transient calculations, it can be very efficient to be able to restart from the latest solution when taking starting another Picard iterations.

Consider the same as setup:

-  Steady master calls a FullSolveMultiApp with picard iterations
- Transient subapp level1 calls a TransientMultiApp from t = 0 to t = 1 with dt = 0.2
- Transient subapp level2 from t = 0 to t = 1 with dt = 0.2

When level1 passes information back to master, and master takes another full solve, it then passes something back to level1 which currently would restart from t = 0. For large pseudo-transient problems, it is not only wasteful but is also hard to tell when the Picard iteration has converged (because even when fully converged, restarting from the initial condition means that the residual is still very large)

## Design

It would be ideal to have a flag, similar to `FullSolveMultiApp/*/no_backup_and_restore = true` to make the desired behavior possible.

## Impact

It will enable efficient pseudo-transients for a fairly standard multiphysics setup (eigenvalue calculation + pseudo time-dependent physics)

**Comment by fdkong** [comment]
@vincentlaboure Do you have a simple inputfile to demonstrate this?

**Comment by vincentlaboure** [comment]
@fdkong Just sent you a PM directing you to a test in Sabertooth
