### ISSUE TITLE
Penalty Dirichlet BC for nodesets

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#14092]
## Reason
Similar to the PenaltyDirichletBC for sidesets, sometimes it is desired to have this capability for nodesets.

## Design
Nodal kernel was used to implement penalty method for Dirichlet BC for nodesets.

## Impact
New capability. No impact on existing codes or tests.

**Comment by permcody** [comment]
Nodesets are a special case of sidesets. I don't see why the existing BC shouldn't work. You can verify this by creating a Nodeset and applying any of the existing Dirichlet boundary conditions. The downside to using a Nodeset though is they don't work like you would expect once you switch on adaptivity, e.g. newly created nodes don't automatically get added to the nodeset. Now using a NodalKernel is a separate system generally for enforcing constraints on interior sidesets (again node sets usually aren't as nice). Did you verify that you can't use a Nodeset already? I think it should work.

**Comment by hchen139** [comment]
> Nodesets are a special case of sidesets. I don't see why the existing BC shouldn't work. You can verify this by creating a Nodeset and applying any of the existing Dirichlet boundary conditions. The downside to using a Nodeset though is they don't work like you would expect once you switch on adaptivity, e.g. newly created nodes don't automatically get added to the nodeset. Now using a NodalKernel is a separate system generally for enforcing constraints on interior sidesets (again node sets usually aren't as nice). Did you verify that you can't use a Nodeset already? I think it should work.

I think the problem here is that can we always construct sidesets from nodesets for all meshes? I know LibMesh automatically do this construction by default for FE meshes. As long as you already have the sidesets, one can always apply penalty Dirichlet BC to 'nodesets'. However, in my special case, i think there are also other cases, there are only nodesets in the mesh and you cannot construct sidesets easily.

@bwspenc may have other reasons to have this capability for nodesets.

**Comment by permcody** [comment]
> I think the problem here is that can we always construct sidesets from nodesets for all meshes? 

Other way around. You can always construct nodesets from sidesets and we have this turned on by default in MOOSE.

> As long as you already have the sidesets, one can always apply penalty Dirichlet BC to 'nodesets'.

Yes, which is why you shouldn't need anything special to apply a BC to a nodeset.

> i think there are also other cases, there are only nodesets in the mesh and you cannot construct sidesets easily.

There are cases where you can't construct sidesets easily but that's not what you are doing here. BTW, we do have the ability to do this, it's _not_ on by default but it does work well.

**Comment by hchen139** [comment]
> > I think the problem here is that can we always construct sidesets from nodesets for all meshes?
> 
> Other way around. You can always construct nodesets from sidesets and we have this turned on by default in MOOSE.
> 

There are no sidesets at the first place. There are only nodesets.

> There are cases where you can't construct sidesets easily but that's not what you are doing here. BTW, we do have the ability to do this, it's _not_ on by default but it does work well.

We want to apply Dirichlet BC to nodesets using the penalty method when there are no sidesets at the first place and constructing sidesets from available nodesets is nontrivial for certain models. For example, in peridynamics, we have one node (material point) connected to all neighboring nodes (material points) within certain user specified distance using Edge elements. We have nodesets for the nodes, but constructing sidesets from these nodesets using a general method is impossible. This is the motivation why we want this capability at least for peridynamics application.

Or I can have this penalty method for my application only, without adding new stuff to the framework.

**Comment by permcody** [comment]
I don't have a problem adding it, but just want to make sure we need it. Sorry, I haven't run the code yet so I could be mistaken, but with Dirichlet boundary conditions in particular. We actually generate a nodeset to apply the Dirichlet condition on. We don't apply it to the sideset. I just wanted you to check to see if it works or not.

**Comment by hchen139** [comment]
> I don't have a problem adding it, but just want to make sure we need it. Sorry, I haven't run the code yet so I could be mistaken, but with Dirichlet boundary conditions in particular. We actually generate a nodeset to apply the Dirichlet condition on. We don't apply it to the sideset. I just wanted you to check to see if it works or not.

I think there were some miscommunication here. The normal Dirichlet BCs are for nodesets and should be applied on nodesets. This is how it is normally done in MOOSE. There is another way to impose Dirichlet BC using penalty method. MOOSE currently has this penalty method for Dirichlet BC implemented but on **sidesets**. Again, this goes back to the question that in cases when we don't have sidesets but only nodesets and generating sidesets from nodesets is impossible, and we want to apply Dirichlet BC using the penalty method. Under circumstances like this, we will need this developed capability.

**Comment by bwspenc** [comment]
It's not clear to me why this was closed. Is this because PenaltyDirichletBC indeed works on nodesets? If it does, that's great.

**Comment by hchen139** [comment]
> It's not clear to me why this was closed. Is this because PenaltyDirichletBC indeed works on nodesets? If it does, that's great.

The PR for this issue has been merged.

**Comment by bwspenc** [comment]
Now I feel like an idiot. I guess my annual break from working on actual code to scramble to get milestones done was particularly long this time.
