### ISSUE TITLE
Improve steady-state detection criteria

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#14105]
## Reason
Currently, the steady-state check criteria is the following:
```
_sln_diff_norm < _steady_state_tolerance
```
where `_sln_diff_norm = (||u||^{n+1} - ||u||^n) / ||u||^{n+1}`. The problem is that this criteria weakens as the time step size decreases; the criteria can be met at some arbitrary point in a transient by decreasing time step size. I suggest that a more appropriate criteria is
```
_sln_diff_norm / _dt < _steady_state_tolerance
```
This mimics a steady-state residual norm (barring differences between time integrators), which is the ideal quantity for steady-state determination.

## Design
This would use `_solution_change_norm` (which is just `_sln_diff_norm / _dt`) instead of `_sln_diff_norm` in the steady-state convergence criteria in `Transient`.

## Impact
This will change steady-state convergence criteria, so some steady-state tests may diff.

**Comment by joshuahansel** [comment]
@friedmud I think you were the one who implemented the tolerance originally. Do you have thoughts on this? Was there a reason why you did not include `_dt` in the criteria?

**Comment by lindsayad** [comment]
So this has switched and now for a sufficiently *large* timestep you can get a false detection of steady-state

**Comment by lindsayad** [comment]
I think it would be reasonable to add a parameter that controls whether `_dt` is included in the solution diff norm calculation

**Comment by joshuahansel** [comment]
> I think it would be reasonable to add a parameter that controls whether _dt is included in the solution diff norm calculation

Seems reasonable to me.
