### ISSUE TITLE
Enable and establish simpler convention for defining validParams

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#14135]
## Reason
defining valid params is confusing with AD - we have cryptic macro syntax that new users don't understand well - and that is inconsistent with how they define valid params for non AD objects.

## Design

Make validParams be a static member function of each object.  Then users can create implement the validParams functions more or less just like we use to even for AD-ified objects.

## Impact
We will deprecate the old-style validParams functions, but no behavior/APIs are modified - we will automagically detect when the new static function is available to use, otherwise, just use the old way.

Here is a list of systems that need to be updated - please check a box as soon as you *start* working on a system:

- [x] actions
- [x] auxkernels
- [x] bcs
- [x] constraints
- [x] controls
- [x] dampers
- [x] dgkernels
- [x] dirackernels
- [x] distributions
- [x] executioners
- [x] functions
- [x] geomsearch
- [x] ics
- [x] indicators
- [x] interfacekernels
- [x] kernels
- [x] linesearches
- [x] markers
- [x] materials
- [x] mesh
- [x] meshgenerators
- [ ] meshmodifiers
- [x] multiapps
- [x] nodalkernels
- [x] outputs
- [x] partitioner
- [x] postprocessors
- [x] preconditioners
- [x] predictors
- [x] problems
- [x] relationshipmanagers
- [x] restart
- [x] samplers
- [x] splits
- [x] systems
- [x] timeintegrators
- [x] timesteppers
- [x] transfers
- [x] userobject
- [x] variables
- [x] vectorpostprocessors

**Comment by aeslaughter** [comment]
This has been merged.

**Comment by permcody** [comment]
Closed by all PRs listed here.

**Comment by bwspenc** [comment]
Hey, basic question here.  I noticed that when you guys did this, you left the old declarations of `validParams`.  For example, I still see the old declaration in the header:
```
template <>
InputParameters validParams<LeastSquaresFitHistory>();
```
along with the new one:
```
  static InputParameters validParams();
```
Are the old ones still necessary?

**Comment by dschwen** [comment]
That's for the legacy way. Downstream apps may still call the global
function template. Once everything gets updated to call static members it
could go away...

**Comment by dschwen** [comment]
Hey, couldn't we just add a template

```
template <class T>
InputParameters validParams()
{
  return T:: validParams ();
}
```

to have an automatic fallback for the global functions that direct to the static members?

**Comment by dschwen** [comment]
Ok, insert slowpoke meme. That code already is in `InputParameters.h`. Why do we need the legacy parameters macros which do nothing other than implementing a template specialization that does exactly what the general template does??!!

**Comment by bwspenc** [comment]
Nice, @dschwen . I'm interested to see if your PR passes the tests!

So on the downstream app side, we should completely convert over to the new style, and I imagine we can get rid of the forward declaration of the current class as well.

**Comment by rwcarlsen** [comment]
I think this is going to turn out to be a chesterson's fence

![](http://www.dumpaday.com/wp-content/uploads/2015/10/gates.jpg)
