### ISSUE TITLE
Mac OS 10.15 (Catalina) Support 

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14130]
## Reason

Apple has released a new operating system. This ticket is here to reference for changes made to support this new operating system.

## Design

Support for Mac OS 10.15 (Catalina)

## Impact

High: Apple highly encourages upgrading to the latest operating system. New macs will ship with this operating system by default almost immediately.

Tag @milljm

**Comment by milljm** [comment]
/usr/include is gone, and will not be coming back:

https://apple.stackexchange.com/questions/337940/why-is-usr-include-missing-i-have-xcode-and-command-line-tools-installed-moja

To build a simple hello world application, I needed to employ this '-isysroot' flag during compile time:

```bash
clang++ hello_world.c -isysroot$(xcrun --show-sdk-path)
```

**Comment by dschwen** [comment]
Ugh, is that because we are not using the compilers shipped with the SDK? Can you bake this path into the shipped compiler? Otherwise using the MOOSE compiler to build anything else will mean having to manually supply this option.

**Comment by permcody** [comment]
As with every release, we need to look at everything to come up with the most sane way of working. I believe this is the state of the options we have:

 - System compiler
   - No Fortran compiler support?
   - No OpenMP support?
   - LLDB may have issues, we need to investigate
 - Brew
    - No package for Catalina yet
 - Conda
    - No package for Catalina yet
 - Hand built compiler
    - Should work, but always hangups getting it going

**Comment by permcody** [comment]
Closed by https://github.com/idaholab/moose/pull/14256
