### ISSUE TITLE
GCC 9

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14138]
## Reason

MOOSE should compile with GCC 9 without warnings.

## Design

GCC 9 is forcing explicit definitions of copy constructors and copy assignment operators when they are used an other copy constructors or destructors are defined. We need to fill in the missing ones, generally with `default`.

## Impact

Minor: Removes warnings with GCC9, which we do not allow.

**Comment by permcody** [comment]
@roystgnr, @jwpeterson - Does libMesh have an official minimum platform support? My guess is no, and since we don't test that platform, it's probably shaky at best as the recent libMesh update in MOOSE exposed. I propose that we determine a minimum supported platform (perhaps the same as MOOSE, but it could be different) and we test it with some regularity (probably per PR). What do you think?

**Comment by jwpeterson** [comment]
Certainly sounds reasonable to me, I'd vote for MOOSE's min-clang and min-gcc versions...

**Comment by permcody** [comment]
Ok then, let me get a recipe set up and we can verify that my min patch works.

**Comment by permcody** [comment]
Umm... we already have min GCC and Clang targets for libmesh. They are just optional on PRs and merges. I'll just turn them on.

**Comment by permcody** [comment]
closed by #14139.
