### ISSUE TITLE
Website menu broken in some cases

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#14143]
## Bug Description

I don't know if it is just me, but I see the following sometimes:

<img width="1330" alt="moosedocs" src="https://user-images.githubusercontent.com/7664823/66615311-e280b700-ec17-11e9-985d-955a064f6304.png">

## Steps to Reproduce

I can reproduce this on a Mac (both High Sierra and Mojave) with both Safari and Chrome in the following order:

1) Go to https://mooseframework.inl.gov/python/MooseDocs/specification.html
2) Then hover the mouse over `Documentation` to try and navigate somewhere else

## Impact

Minor usability issue that might be affecting others and not just me

**Comment by WilkAndy** [comment]
i get the same, macbook air, mojave, safari 12.1.2

**Comment by cpgr** [comment]
At least it isn't just me then!

**Comment by permcody** [comment]
I've seen the same!

**Comment by cpgr** [comment]
Going through my old issues - I can't reproduce this anymore, so I'm closing it. Something must have changed to fix it
