### ISSUE TITLE
3D crack propagation using XFEM

### ISSUE THREAD

**Issue by liuusu** [idaholab/moose#14157]
## Reason
3D crack propagation is a useful capability for MOOSE to model failure mechanisms of materials and structures.  

## Design
The 3D crack propagation capability will depend on:  (1) a mesh cutter object (MeshCut3DUserObject), which describes a 3D crack using a surface mesh that can grow as needed;  (2) The EFA code which handles fragmentation of elements when split by cracks;  and other XFEM components such as the fracture integral calculations.  

## Impact
1. The previously merged MeshCut3DUserObject code will need some revision to allow crack growth over time.  

2. The EFA code needs additional testing and bug fix for 3D applications.  One bug that prevents correct prediction of 3D propagation lies in EFAElement3D::addFaceEdgeCut.  It is coded to cut the physical faces of elements only, while it should cut fragment faces as well.  This bug may lead to incorrect predictions of the number of embedded nodes and the number of cuts.

**Comment by permcody** [comment]
Closed by #14158.
