### ISSUE TITLE
ParsedFunction has difficult errors

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#14169]
## Reason
If a bad `vals` is used by `ParsedFunction` (e.g. incorrect scalar, function or postprocessor name), then a very difficult to understand error is thrown, with both `opt` and `dbg`.
```
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

## Design
There should be an error check to make sure the scalar/function/postprocessor exists.
This can be tested by running
```
../../../moose_test-opt -i combined.i Functions/fn/vals='sv cos_fn pp'
```
in `moose/test/tests/functions/parsed`

And changing `sv`, `cos_fn`, or `pp` to any other value.

## Impact
This will help debugging inputs a bit better.

**Comment by tophmatthews** [comment]
I'm guessing... @dschwen ?

**Comment by permcody** [comment]
I'm curious if the error is better in debug mode. If it is, it might be changing an assert to an error.

**Comment by tophmatthews** [comment]
Yeah, I was hoping debug would do better, but it gives the same answer.

**Comment by dschwen** [comment]
> I'm guessing... @dschwen ?

Not my code, but I'd be happy to work on it.

**Comment by dschwen** [comment]
I have something ready. Sitting in a meeting without WiFi...
