### ISSUE TITLE
--n-threads>1 test recipe for PorousFlow

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14173]
## Reason

I'd like to be able to test PorousFlow with --n-threads.  I can do this on my own machines, but would like an optional recipe that i can occasionally activate in my PRs that tests PorousFlow with n_threads>1.  This will enable me to more accurately keep track of PorousFlow.

## Design

I think just testing PorousFlow, probably in debug, with --n-threads=2 or --n-threads=3 would be good, but i'll leave this up to @milljm 's judgement.  If @milljm thinks this whole idea stinks, please just close the issue.

## Impact

Add ability to manually test PorousFlow on INL machines, when desired

**Comment by WilkAndy** [comment]
Also notifying @cpgr

**Comment by permcody** [comment]
I would suggest just adding it to the existing parallel modules testing.

**Comment by cpgr** [comment]
Thanks @milljm. I hope it doesn't fail and break the smooth running of civet.

**Comment by WilkAndy** [comment]
Thanks from me too, @milljm
