### ISSUE TITLE
Make GeneralizedPlaneStrain use TaggingInterface

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#14227]
## Reason
This is required in order to use `GeneralizedPlaneStrain` use the "new" form for `ReferenceResidualProblem` introduced in #14004

## Design
Use `accumulateTagged*` and `prepare*Tag` methods

## Impact
Allows continued updating of tensor mechanics problems to the new `ReferenceResidualProblem`

**Comment by lindsayad** [comment]
Re-opening this because I need to make sure that we're accumulating the reference residual calculation from the user object into the reference residual vector. Currently, I'm accumulating the residual user object calculation into the reference residual vector such that the residual vector and reference residual vector will always be the same and convergence will never be achieved.

**Comment by bwspenc** [comment]
Reopening because we need to add a little bit of code to the TensorMechanics Master action and GeneralizedPlaneStrain action to set this stuff up in a user-friendly way.

**Comment by bwspenc** [comment]
@lindsayad The deprecated old way of using ReferenceResidualProblem pre-tagging is scheduled for removal on Jan 1, 2020.  Happy New Year!  I think we have everything ready to go on the BISON side for that.  Maybe @gambka knows if there are lingering issues.  Is anyone working on removing that code?  I assume this issue should be re-opened for that.

**Comment by gambka** [comment]
In BISON we still have a couple cases that use the old way which use MultiApps.  I was told by others that there was an issue running with new tagging interface and MultiApps for reference residual, but I do not know the details.
