### ISSUE TITLE
Let Coupleable support coupling a variable in any solution vector

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14225]
## Reason
The variable can be a primal (nonlinear) or auxiliary variable. I have an existing executioner using old solution for iteratively solving a problem although the problem is a steady-state problem. I have kernels coupled in the old solution (which is the solution of previous iteration). I'd like to modernize this executioner to avoid touching system old solution vectors by creating a tagged solution vector for both nonlinear and auxiliary systems. I will need the capability of using tagged vector to evaluate variable values on quadrature points for the kernels.

## Design
We should have almost all fundamental capabilities we need. Just need to add more interface functions. One concern is that the solution vector could be used for kernel tagging, which will be changed during residual evaluation when its value can be used by kernels. We need to have machinery to prevent this from happening.

## Impact
Make custom executioners with iterative methods less hackery.

**Comment by YaqiWang** [comment]
@lindsayad We need to raise the priority of this issue a little plus this can be done fairly quickly I guess. The reason I am asking is that we have a few executioners in Griffin solving a steady-state problem with a custom iteration (`RichardsonIteration`), which is using old solution for the iteration. If we can have this in place, we can add a vector for those executioners and let kernels work on the vector. Otherwise those executioners may have bad interference with #16339. @loganharbour may also be interested.

**Comment by loganharbour** [comment]
I just spoke with @YaqiWang to tell him that this _should_ be supported using the tagging system and the tagged variable access. I'm going to give it a try and will close if the current capability is sufficient.

**Comment by lindsayad** [comment]
If current capability is not sufficient, I will add it to the NEAMS MP TA project and move it towards the top.

**Comment by YaqiWang** [comment]
If someone can tell me for sure if this is supported, it will be great, otherwise I will need to check it out on my own.

**Comment by loganharbour** [comment]
It is. I can chat in 15 min to discuss if you’d like.

**Comment by YaqiWang** [comment]
I will close this then. We can reopen if issues were found.
