### ISSUE TITLE
`ADDensity` and `Density` required variables are not the same

### ISSUE THREAD

**Issue by elementx54** [idaholab/moose#14222]
## Bug Description

`ADDensity` has displacements as required coupled variables. `Density` does not, but has them as optional coupled variables. For thermal only simulations, required displacements does not work.

## Steps to Reproduce

Find any thermal only tests that has `Density` and convert it to an automatic differentiation (AD) approach; this usually requires changing the kernels to AD as well.

## Impact

I am currently converting non-AD material models to AD. In doing the tests, ADDensity did not behave as I expected it to. The required displacements are preventing the converted tests from running.

**Comment by elementx54** [comment]
Well, I'm stuck cause I'm new to AD. I'm following what the non-AD `Density.C` does but I can't seem to use `_zero` for when "displacements" is not provided. Specifically I've tried:
```
_disp_r(isCoupled("displacements") ? adCoupledValue("displacements", 0) : _zero),
```

Does AD have a `_zero` and I just don't know the name? And if you care, the compile error I get at that line is:
```
error: incompatible operand types ('const MooseArray<MetaPhysicL::DualNumber<double, MetaPhysicL::NumberArray<50, double> >>' and 'const MooseArray<libMesh::Real>')
```
which makes sense.

**Comment by tophmatthews** [comment]
Density retains the old deprecated way of coupling displacements, eg `disp_x = disp_x`. The better way to do this is to finally rip the bandaid and get rid of the old way, and enforce displacements.

**Comment by dschwen** [comment]
To clarify: The Density Kernels only make sense if you have displacement
variables (and a displaced mesh), otherwise density is constant anyways.
There is no "thermal only" case here.

**Comment by tophmatthews** [comment]
I don't have a good answer for your compiling question though, I've run into similar problems. What is the `_zero` for AD?

**Comment by dschwen** [comment]
_disp[i] = &adZeroValue();
      _grad_disp[i] = &adZeroGradient();

**Comment by tophmatthews** [comment]
>For thermal only simulations, required displacements does not work.
For what Daniel is saying,
```
[./density]
  type = GenericConstantMaterial
  prop_names = 'density'
  prop_values = '1'
[../]
```

**Comment by elementx54** [comment]
I could guess that for a constant material, AD does nothing. Can MOOSE mix AD materials and non-AD materials? Do I need to make a `ADGenericConstantMaterial` just to get the material properties to be the right type?
