### ISSUE TITLE
JSON dump doesn't list initial_condition for non-typed Variables and AuxVariables

### ISSUE THREAD

**Issue by brandonlangley** [idaholab/moose#14231]
## Bug Description
There are many valid MOOSE test inputs with `[Variables]` and `[AuxVariables]` that are not of any specific `type` that have a parameter named `initial_condition`, e.g.,

```
{MOOSE}/test/tests/auxkernels/nodal_aux_var/nodal_aux_init_test.i
```

```
[Variables]
  active = 'u'
  [./u]
    order = FIRST
    family = LAGRANGE
    initial_condition = 5
  [../]
[]
```

This Variable named `u` does not have a `type` specified (also `type` is not defaulted for this block), and according to the JSON input definition dump, `initial_condition` does not exist as a parameter of general `/Variables/*`.

The parameters that do exist for general `/Variables/*` are:

```
active
inactive
type
family
order
scaling
initial_from_file_timestep
initial_from_file_var
```

and `initial_condition` does exist as a paramter for `Variables` of these specific subblock_types:

```
/blocks/Variables/star/subblock_types/ArrayMooseVariable
/blocks/Variables/star/subblock_types/MooseVariable
/blocks/Variables/star/subblock_types/MooseVariableBase
/blocks/Variables/star/subblock_types/MooseVariableConstMonomia
/blocks/Variables/star/subblock_types/MooseVariableScalar
/blocks/Variables/star/subblock_types/VectorMooseVariable
```

but since the Variable in the above legal input does not have a `type` specified, it appears that the JSON input definition dump is incorrect.

## Steps to Reproduce
Examine the JSON input definition dump produced from running MOOSE with the `--json` command line parameter.

## Impact
The NEAMS Workbench is translating the JSON input definition dump to a schema which is used for input validation and autocomplete assistance across all MOOSE based applications.

Every input with a `initial_condition` parameter inside a non-typed `[Variables]` or `[AuxVariables]` block is being reported as invalid.

**Comment by brandonlangley** [comment]
@permcody -

Just FYI, this is one of the two issues that you recommended via our email correspondence that I open. (1/2)

**Comment by lefebvrera** [comment]
Are there any updates on this issue? ETA for the fix?

**Comment by nstauff** [comment]
While working on Griffin and Bison input files and executing them successfully from Workbench, I still have the following input validation errors:

- /variables/temp/initial_condition is not a valid piece of input
- /AuxVariables/power_density/block is not a valid piece of input
- /AuxVariables/Tfuel/block is not a valid piece of input
- /AuxVariables/fuel_thermal_conductivity/block is not a valid piece of input
- /AuxVariables/fuel_specific_heat/block is not a valid piece of input
- /AuxVariables/monolith_thermal_conductivity/block is not a valid piece of input
- /AuxVariables/monolith_specific_heat/block is not a valid piece of input
- /AuxVariables/Tf/initial_condition is not a valid piece of input
- variable value "specific_heat" does not exist in set: [../../../../AuxVariables/*/decl ../../../../Variables/*/decl]
- variable value "thermal_conductivity" does not exist in set: [../../../../AuxVariables/*/decl ../../../../Variables/*/decl]
- densities value "1.0" does not exist in set: [../../../../AuxVariables/*/decl ../../../../Variables/*/decl]
- power_density_variable value "power_density" does not exist in set: [../../../../AuxVariables/*/decl]
- NonlinearEigen_type has zero of: [../GlobalParams/bx_norm/value" "bx_norm/value"] - at least one must occur
- TransportSystems/saaf/family is not a valid piece of input
- TransportSystems/saaf/order is not a valid piece of input
- TransportSystems/saaf/fission_source_as_material is not a valid piece of input

It should be noted that some of my inputs are referencing other inputs when using the `MultiApp` function.

Another comment is that the `type` input value cannot be auto-completed, while there should be a list of authorized block Type.

**Comment by rwcarlsen** [comment]
The issue here is that while there is no high-level `initial_condition` parameter, since _every_ variable subtype in implementation (sort of) individually supports this parameter, it is still valid.  Perhaps the solution is just to migrate the `initial_condition` parameter up to the higher-level shared parameters for all variables.  I'll take a stab at this.
