### ISSUE TITLE
PETSc Build System Broken for Containers

### ISSUE THREAD

**Issue by herter4171** [idaholab/moose#14258]
## Bug Description
@permcody, I recently uncovered some odd behavior with the PETSc build system that broke my CI/CD for MOOSE and the general ability to build PETSc in a container.  

Satish Balay at ANL has been very helpful, and it looks like [the fix is in](https://gitlab.com/petsc/petsc/commit/53a5e9c0558560048914cf899e06b52f068f9586).  There isn't a clear timeline for how that commit will make its way to a tag, so I'll keep an eye on it.  If they make a v3.12.2 tag with the fix in it, I will try submitting an update PR referencing this.  If, however, ANL doesn't make a tag in short order, I will reach out to see how this might proceed.

## Steps to Reproduce
Attempt to run PETSc (revision addfb3b) configuration on Ubuntu, Debian, Amazon Linux, or OpenSUSE in a Docker container.  CentOS works for unknown reasons, and behavior using Singularity has not been tested.  Essentially, the build system successfully downloads, makes, and installs HYPRE, but it gets confused about the version number shortly after.

## Impact
Impact is pretty severe.  KP is effectively ham-strung on updating herd codes and building the latest from MOOSE.  Falling behind on this front has its own perils, of course.

**Comment by permcody** [comment]
If I'm reading this correctly, this isn't a MOOSE problem per se, but there are a few versions of PETSc that effectively cause you serious headaches. I'm assuming you are fine on slightly older PETSc, and now with this patch, bleeding edge PETSc. In general, we do stay up to date on compiling against PETSc so there's a good chance you could build your own PETSc and MOOSE will compile and run against it. The PETSc submodule script in MOOSE is for staying _ahead_ if you will. We distribute a stable version of PETSc, which is usually a version or two behind the development version. So, I'd suggest see if you run into any issues building bleeding edge PETSc. You can even use our script and submit a submodule update if you'd like (as long as it passes our CI). We are more than willing to move forward.

Tagging @fdkong
