### ISSUE TITLE
peacock: no module named 'hit'

### ISSUE THREAD

**Issue by PaulMazzuca** [idaholab/moose#14278]
## Bug Description
I ran "peacock". PATH is set correctly. I did install some python packages after being prompted. I can't quite figure out what "hit" is in this case.  I do see the import statement, but I can't find the module, and I don't see a requirements.txt file.

I am running MacOS 10.15 Python 3.7.0

```python
ModuleNotFoundError: No module named 'hit'
```

## Steps to Reproduce
I cloned the project and tried to run peacock as described in the documentation

## Impact
Cannot run peacock.

**Comment by permcody** [comment]
A few things: First we don't support OS 10.15 yet. There's a big note on our getting started pages:
https://mooseframework.org/getting_started/index.html

We are working on support and it's likely to be out next week. Once we do support Catalina, the proper place for an issue like this would be the mailing list (moose-users@googlegroups.com). Typically this kind of error is an environment problem, however in this case it's your OS.

**Comment by PaulMazzuca** [comment]
Right on. Thanks for the clarification. I will test it when the new version is available and use the mailing list if I run into any issues.
