### ISSUE TITLE
Speedup Slower Tests (again)

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14289]
## Reason

We are seeing a few timeouts in the modules that are pretty consistent. These are causing headaches with automated CIVET testing as these tests have to be invalidated each time they fail.

## Design

Re-evaluate tests and shorted as possible.

## Impact

Minor: CIVET automation

**Comment by tophmatthews** [comment]
I kept getting this as well for new tests I put in. What about adding a "soft" time limit so when tests are created that are close to the limit, they can be changed at that point?

**Comment by permcody** [comment]
We've talked about this many times in the MOOSE cube but we always worry that any sort of leeway in the time limits will be immediately taken up by the developers and we'll have an even fatter suite of tests. I don't mind the hard failures most of the time. We run millions of tests a week and people need to learn how to whittle them down as much as possible. I still see proposed tests go in with thousands of timesteps and tens of thousands of elements on a regular basis that I have to reject. Every once in awhile I tell the devs to go back and clean them up and they/we do.
