### ISSUE TITLE
Attach preconditioner for Eigen solver

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#14297]
## Reason
In Rattlesnake, there is a useful preconditioner that accelerates transport problems significantly. Right now this preconditioner is utilized by doing `attach_preconditioner` on the `nonlinear_solver` used in `NonlinearSystem`. The new `NonlinearEigenSystem` uses a different object called `eigen_solver`, which does not have an `attach_preconditioner` function.

## Design
Not sure what this would require on the PETSc or libmesh side, but having a similar function as `attach_preconditioner` in the `EigenSolver` class would be ideal.

## Impact
This would enhance the usability of the new eigen solver by adding the ability to add custom preconditioning.

**Comment by zachmprince** [comment]
@fdkong

**Comment by fdkong** [comment]
This requires changes in libmesh.
