### ISSUE TITLE
ReferenceResidualProblem crashes if grouping is used without specifying solution variables

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#14334]
## Bug Description
In the transition to the tagging system, and issue was introduced in ReferenceResidual problem in which the code will crash if the user specifies `group_variables` but not `solution_variables`.

Also, the output of the individual variables' residuals and corresponding reference quantities was inadvertently removed except for when grouping is used.

## Steps to Reproduce
See above. One simply needs to use ReferenceResidualProblem with `group_variables` specified but without specifying `solution_variables`. The code hangs for a while, and then dies with signal 9.

## Impact
This is mostly an annoyance. It does not result in any incorrect calculations.

**Comment by bwspenc** [comment]
Scratch what I said about the output of individual variables not working. That's not actually an issue.

**Comment by bwspenc** [comment]
Reopening because a recent modification to at test triggers the deprecation message created as part of the resolution to this issue, and also because this needs to be kept open until we remove the `solution_variables` parameter on Jan 1, 2020.

**Comment by bwspenc** [comment]
It'll probably actually be Jan 2.  I doubt that will be the first thing I do to ring in the new year!

**Comment by lindsayad** [comment]
Can this be closed?

**Comment by bwspenc** [comment]
Looks like it, @lindsayad.  I also see that we were supposed to remove 'save-in' on January 1, 2020. I just checked my calendar, and it's March 2021. I recall that there were some issues with some BISON models that were holding that up, but I think those were fixed quite a while ago. Is that right, @gambka?

**Comment by gambka** [comment]
I think they are fixed but I will double check.
