### ISSUE TITLE
Enable executioners setting controls

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14361]
## Reason
The reason for this is that: in neutronics calculations, we often have something called criticality search, during which we basically adjust a parameter in the input so that the eigenvalue reaches a certain value. If we can make a parameter controllable and add a function in `Executioner` like
```
  ControllableParameter getControllableParameter(const std::string & param_name) const
  {
    return _app.getInputParameterWarehouse().getControllableParameter(getParam<std::string>(param_name));
  }
```
we can let executioner accept a controllable parameter and change the parameter during the calculation.

## Design
Using `Control` in the input file will be really difficult not only for developers but also for users. I personally think this is a reasonable feature. If you agree, I can send in a PR. 

## Impact
New feature.

**Comment by permcody** [comment]
I think this is OK. The only issue is that Executioners have a pretty powerful API in that they control everything else. It's a little difficult to narrow down the API to control the Control at specific times. Perhaps that's OK. Let's see what you've got.
