### ISSUE TITLE
TestHarness might crash when reading bad characters

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14370]
## Bug Description

It appears that it's possible for the TestHarness to crash when reading test output.

## Steps to Reproduce

Unknown, but it happened here:
https://moosebuild.inl.gov/job/220497/

## Impact

Moderate: The TestHarness shouldn't crash when reading output.

**Comment by YaqiWang** [comment]
This link shows the problem is more severe: https://moosebuild.inl.gov/job/220419/

The test script crashed and did not finished all the tests but falsely marked the test target success. I'd see this is a critical issue.

**Comment by permcody** [comment]
Upgrading to critical since it appears that it's possible that the TestHarness will mark the step as successful when this decode error occurs.

**Comment by permcody** [comment]
Well that was easy. @milljm was able to figure out a simple string that fails to decode and crashes the TestHarness just like your error message. He's already created a new unit test to avoid that in the future.

I just compiled and ran the head of Mammoth in opt mode with the "--pedantic" flag to run_tests and discovered 3 race conditions! This is why we are getting corruption in the output file so that needs to be fixed. Jason will patch the TestHarness so that it won't fail in this way. 

When you get a chance compile Mammoth and fixup the race conditions.

Thanks!

**Comment by YaqiWang** [comment]
Good to know. Thanks.

**Comment by milljm** [comment]
Darn, works on Darwin machines... working on it.
