### ISSUE TITLE
RealMaterialAux does not trigger the evaluation of interfacematerial

### ISSUE THREAD

**Issue by arovinelli** [idaholab/moose#14387]
## Bug Description
If one uses an interfacematerial and ask to pull out interfacematerial properties via `MaterialRealAux` the interface material will never be evaluated.
Most likely there is something missing in the loops
@lindsayad  

## Steps to Reproduce
just go into `test/tests/materials/interface_materials/interface_value_material.i` comment the interface kernel block and the InterfaceValuaMaterial::computeQpProperties will not be executed. Check the exodus and all the interface material property will be 0

## Impact
Prevents user to compute interface material properties if the `interfacematerial` is not associated to an InterfaceKernel

**Comment by lindsayad** [comment]
Interesting. I will take a look soon

**Comment by arovinelli** [comment]
@lindsayad I also found another interesting behaviour:

- If I create an interface material making a simple average between bulkMP at the interface, use an aux var and an boundary restricted aux kernel to dump it it out everything is fine.
- If I do the same thing with an action I got a segfault 
-if I do the action for `interfacematerial1` and add a manual `interfacematerial2` + `AuxKernel` + `AuxVar` directly in the input file, then thing works...

I'll try to put together a simple branch for these case

**Comment by arovinelli** [comment]
@lindsayad below the test cases

`test/tests/materials/interface_material/interface_value_material_noIK.i`
and 
`test/tests/materials/interface_material/interface_value_material.i`
