### ISSUE TITLE
Distributed Mode for SamplerPostprocessorTransfer and StochasticResults

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#14410]
## Reason

The aim is to be capable of handling over 1e9 stochastic runs. With 1e9 runs a single PP will require 8GB to store on a single rank. Thus, the resulting data must have the option to remain distributed.

## Design

The SamplerPostprocessorTransfer passes data to StochasticResult VPP, currently the transfer is doing parallel communication to build the complete data that is sent to the VPP. This should only communicate the local part.

The StochasticResult object is a VPP designed to hold a vectors of PP values from the sub-application runs. This object should have a "parallel_type" option that control if the data is distributed or replicated across ranks. When populated by a transfer it should only have the local part, the "parallel_type" should dictate if the communication should happen.

Also, if "parallel_type = distributed" then the StochasticResult should warn/error if CSV output is enabled.

## Impact

This will change will allow for very large stochastic runs to distribute the stochastic simulation data for use by other aggregation routines, such as confidence level intervals, to reduce the data reported to a manageable size.

**Comment by aeslaughter** [comment]
In distributed mode, there should also be an option to output values from a specified processor. This will mainly be for testing.

**Comment by jiangwen84** [comment]
@aeslaughter could you explain why the csv output should be disabled when parallel_type = DISTRIBUTED?

**Comment by jiangwen84** [comment]
If we cannot output the `StochasticResults` into a CSV, how do we analysis the stochastic results?

**Comment by aeslaughter** [comment]
Handling the output is future work: see #14480
