### ISSUE TITLE
std::vector<Action *> & getActionsByName (const std::string &name)

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#1442]
Can we create this interface in ActionWarehouse? If the name is unique for each action, we can simply return Action*.

**Comment by YaqiWang** [comment]
Sorry for reactivate this really old issue. Seems to me the function `getActionByName` now changes to something more like `getActionByTask`. I realized I do need `getActionByName` for my action systems and now I have a better idea. We can create one with the interface 
```
  template <class T>
  const T & getAction(const std::string & name);
```
like `FEProblem::getUserObject()`.

Any comments before I send in a PR?

**Comment by permcody** [comment]
@aeslaughter has changed what a "Name" is on an object which is probably why you are running into this. What exactly do you mean by name? Is it the name of the class? the name of the syntax block? the fully qualified syntax block?

**Comment by YaqiWang** [comment]
What is the difference of the last two? It should be the name as in the input.

**Comment by permcody** [comment]
The difference between the last two:
"Kernels/diff" vs just "diff"

@aeslaughter is calling this input syntax some sort of "tag" now.

**Comment by YaqiWang** [comment]
oh I see, then it the name of the syntax block.

**Comment by aeslaughter** [comment]
Whatever is passed into the create methods (Factory::create,
AppFactory::create, ActionFactory::create) is the object "name" (i.e.,
returned by the name()) method.  If the object is created by the Parser,
the Parser will add "parser_syntax" to the objects InputParameters (this is
the full syntax, i.e., "Kernels/diff"). There is also the ability to add
"tags" to object for Control logic purposes via the "control_tags"
parameter, but these are only used by the Control logic system.

In my opinion, you should never rely on the "parser_syntax", it is only
there for legacy reasons.

**Comment by YaqiWang** [comment]
OK, full name is better.
