### ISSUE TITLE
Uniform refinement should be converted to a mesh generator

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14435]
## Reason
Current parameter `Mesh/uniform_refine` will go away with the new mesh generator system. Thus we need to create a new mesh generator to do the same like `UniformRefine`, which takes output of an input mesh generator and output the uniformly refined mesh.

## Design
This might have some implications on recovery like what we did before to move uniform refinement early from problem initial setup to mesh generation stage. But I guess this will clean things up further. Note that `-r` command line option needs to be considered properly.

## Impact
Internal interface change, will require applications to stop using `Mesh/uniform_refine`.

**Comment by YaqiWang** [comment]
We possibly should do the same for `add_mortar_interface`. Basically, after `set_mesh_base` task, the mesh is final, then we proceed for partitioning, initialization, stuff.

**Comment by GiudGiud** [comment]
Closed as completed by #18744 on a per-block basis

note that uniform_refine is still there, as is -r
Not much push for them to leave I think
