### ISSUE TITLE
Let the update_and_rebuild_petsc script support 64bit build on command line

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14447]
## Reason
When we run large simulations, 32bit integer could be not enough. We need to turn on 64-bit build in PETSc and correspondingly to let libMesh configure with `--with-dof-id-bytes=8`.

## Design
It would be handy if we can have a command-line argument like `--enable-64-bit` for the script. Also if libMesh can detect the PETSc integer type and set `--with-dof-id-bytes=8` internally, it will be great. Otherwise we will need to have a similar command-line argument for update_and_rebuild_libmesh script.

## Impact
New capability.

**Comment by permcody** [comment]
@YaqiWang - libMesh already automatically detects this. You only have to configure PETSc with the size you want and libMesh will use that value. So I think this issue can be closed.

**Comment by YaqiWang** [comment]
You mean I change the script every time I do so? It will make my check-out dirty though.

**Comment by permcody** [comment]
> You mean I change the script every time I do so?

Perhaps I don't understand, what are you needing to change? There shouldn't be any changes necessary to the libMesh build script. Ideally you shouldn't have to build PETSc on the cluster, but hey, there are people that do need to do that. In those cases, you can simply pass the extra option right on the command line and the wrapper script will pass it along to PETSc. So even in that case there shouldn't be a change that you need to make. Am I missing something?

**Comment by YaqiWang** [comment]
Oh! You mean the script can honor `--with-64-bit-indices` on command line already?! Thanks and sorry about this.

**Comment by permcody** [comment]
Yes, both scripts (libmesh and Petsc) accept additional command line options. No problem, sorry you weren't aware. It's not widely advertised, but it does work.
