### ISSUE TITLE
Interface with TAO

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#14444]
## Reason

PETSc's ability to solve systems with underlying non-convex potential is limited.
Solving such systems will be much easier If we can interface with external optimization packages, e.g. TAO.

## Design

Libmesh has an interface with TAO I believe (correct me if I am wrong). We may inherit the interface in SystemBase or elsewhere, and using the tagging system to get gradient of the objective (FEM residual) and hessian of the objective (FEM jacobian).

## Impact

New capability.

**Comment by hugary1995** [comment]
I want to add one more point: I think MOOSE will likely become the go-to framework for people from the gradient-damage/phase-field fracture community if we have this interface.

**Comment by GiudGiud** [comment]
@lynnmunday I think this can be closed?

**Comment by lynnmunday** [comment]
@GiudGiud We are using TAO for optimization but I think @hugary1995 is wanting to solve a different kind of optimization problem with TAO.  @hugary1995 do you think you could solve this type of problem with our current TAO interface in MOOSE.

**Comment by hugary1995** [comment]
I think so, yes. Mike Tupek and Brandon Talamini from SNL have demonstrated this in their code. Though I am not terribly motivated to do this in moose any more. I have had mixed feelings about moose not heading this direction, but that's okay. I'm closing this now.
