### ISSUE TITLE
Strange behavior with pkg-config --exists libpng

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#14459]
## Bug Description
While attempting to build a conda moose-env, I discovered a couple libpng tests are being skipped due to some strange pkg-config behavior.

## Steps to Reproduce
```
[~/projects/moose] > pkg-config --exists libpng
[~/projects/moose] > pkg-config libpng --exists
[~/projects/moose] > pkg-config libpng --libs  
-L/Users/milljm/libs/miniconda3/envs/moose-env/lib -lpng16 -lz
[~/projects/moose] > file /Users/milljm/libs/miniconda3/envs/moose-env/lib/libpng16.dylib 
/Users/milljm/libs/miniconda3/envs/moose-env/lib/libpng16.dylib: Mach-O 64-bit dynamically linked shared library x86_64
[~/projects/moose] > 
```

```
[projects/moose/test] > ./run_tests --re=outputs/png.image_tests/square_domain
outputs/png.image_tests/square_domain ................................ [LIBPNG!=TRUE] SKIP
------------------------------------------------------------------------------------------
Ran 0 tests in 2.5 seconds.
0 passed, 1 skipped, 0 pending, 0 failed
```
The same behavior can be experienced using the moose-environment package. It would seem `pkg-config --exists` may not be the right way to detect libpng.

## Impact
Tests always being skipped?

**Comment by dschwen** [comment]
I found

ifeq ($(shell pkg-config fftw3 && echo go),go)

To work well (in magpie)

**Comment by permcody** [comment]
This is expected. You +have+ to run ./configure now to enable libpng. I've moved the on-the-fly check for libpng out of the Makefile since it was causing other issues there. The configure check should make it a little less finicky.
