### ISSUE TITLE
Create SamplerVectorPostprocessorTransfer

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#14455]
## Reason

Applications require the ability to transfer a vector of data from the sub-application to the master for stochastic simulations.

## Design

The design will mimic SamplerPostprocessorTransfer.

## Impact

This is a new feature.

**Comment by aeslaughter** [comment]
The following needs to happen to make the vector and non-vector stuff to have similar structure:

SamplerPostprocessorTransfer -> StochasticToolsResultsTransfer
SamplerVectorPostprocessorTransfer -> StochasticToolsVectorResultsTransfer 

StochasticVectorResults needs to be created to work iwth StochasticToolsVectorResultsTransfer.

The Transfer objects need to create the vectors on the StochasaticResults objects this will allow the VPP version to create the correct vectors supplied in the input file.

**Comment by zachmprince** [comment]
This has been addressed with SamplerReporterTransfer
