### ISSUE TITLE
MeshGenerators and DistributedMesh

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#14451]
## Bug Description
Look at our dependency set in `Moose.C`. We add geometric ghosting after execution of mesh generators.

## Steps to Reproduce
Look at `Moose.C`.

## Impact
This makes it impossible to tell the mesh what elements we need ghosted before they are deleted by `MeshGenerators` like `FileMeshGenerator` and `GeneratedMeshGenerator` which both call `prepare_for_use`.

## Solution Ideas

- Prevent `prepare_for_use` calls and/or don't allow remote element deletion during the mesh generator execution phase
    - this would be consistent with our outlined dependency set which has `prepare_mesh` well down the chain (after geometric relationship manager addition)

**Comment by YaqiWang** [comment]
It does not make sense to distribute the mesh (removing remote elements) inside `MeshGenerator::generate`. Since `libMesh::MeshTools::Generation::build_cube` is calling `prepare_for_use`, we possibly need to create a function `MeshTools::Generation::build_cube_without_distribution` that can be used by `GeneratedMeshGenerator` and `libMesh::MeshTools::Generation::build_cube`. Or I suggest `MeshMesh::buildMeshBaseObject` always return `ReplicatedMesh` and we do mesh distribution or mesh split at the end. Distributed mesh generators should not mixed with normal generators.

**Comment by lindsayad** [comment]
I definitely share the opinion that we should not be removing remote elements during the mesh generation phase.

**Comment by arovinelli** [comment]
These are my two cents:
I 'll start saying that run should always be performed only on `DistributedMesh` and generation should always use `Replicated` mesh. When generation is competed the mesh should switch from `Replicated` to Distributed`.
for realistic problems with a lot of Dof (milions) using a replicated mesh is basically impossible (I have a case were only the mesh it 40GB with approx 100Milion dof). I would push towards a more integrated way of performing serial generation and then distributing the mesh only at the end while removing unused elements.  This will make all generator and loading tools consistent and it's nothing more than using `--split-mesh` utilizing only 1 cpu.
The only limitation of this approach would be the mesh memory size being smaller than the memory available on a single node.
Distributed mesh generation should only be used when the previous requirement cannot be satisfied (I guess it's rare enough as a normal cluster node nowadays have at least 128GB).

With this being said I think element removal should happen at the end of the generation steps.

**Comment by permcody** [comment]
@arovinelli - That's the view that many of us share. The default should be not to delete elements. I do want to make "distributed generation" possible though and we have an idea for a consumer based advertising system that should allow this in the future. For now, we will turn off remote element deletion until we have something better in place.

**Comment by permcody** [comment]
Tagging in @friedmud. This is an import topic we need to nail down. I'm putting it on my list of things to discuss with the team when @lindsayad is here in mid-December.

**Comment by lindsayad** [comment]
Closing in favor of #14329
