### ISSUE TITLE
libMesh Doxygen link on website doesn't work

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#14499]
## Bug Description
Link to doxygen on the main website doesn't work.

## Steps to Reproduce
Go [here](https://mooseframework.org/docs/doxygen/libmesh/classes.html)

## Impact
Doxygen is useful. Necessitates changing of my bookmarks

**Comment by permcody** [comment]
Tag @milljm?

**Comment by loganharbour** [comment]
@aeslaughter knew something about this too but I do believe he got tired of me asking about it...
