### ISSUE TITLE
Finite strain rotation in multiple inelastic stress

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#14495]
## Reason
@WilkAndy , why is it required to rotate a guaranteed isotropic elasticity tensor if a tangent operator other than the elastic approximation is used? I'd think isotropic is isotropic and stays the same no matter how you rotate it?!

Elasticity tensor rotations make up a substantial chunk of run time for some cases (up to 15%!!).

## Design
Skip elasticity tensor rotation even if elastic tangent operator approximation is _not_ used.

## Impact
Faster simulations.

**Comment by WilkAndy** [comment]
Have to be careful here.  The elasticity tensor may be isotropic, but the plastic model may not be.  A case in point is "WeakPlane" plasticity, where the material contains weak planes with orientation in one direction.  Modellers usually give this type of material an isotropic elasticity tensor, but it fails preferentially along some direction.  So the consistent tangent operator is not isotropic.

I totally agree with getting rid of rotations is we don't need them, eg, in small-strain situations.

We could have a boolean called "isotropic_plasticity" or something similar.

**Comment by dschwen** [comment]
Argh, yeah, I just looked at the code again...

**Comment by dschwen** [comment]
We could use the guarantee system for that as well. The plasticity models could state if they are isotropic or not. I assume it would require all inelastic models to be isotropic to avoid rotating the jacobian mult tensor?

**Comment by WilkAndy** [comment]
Your last sentence is correct

**Comment by dschwen** [comment]
My first sentence unfortunately is not

**Comment by dschwen** [comment]
@WilkAndy , what do you say to 285cc64 ?

**Comment by dschwen** [comment]
[PK23 before this PR](https://github.com/idaholab/moose/files/3945617/PK23_before.pdf)
[PK23 after this PR](https://github.com/idaholab/moose/files/3945618/PK23_after.pdf)
