### ISSUE TITLE
Inconsistent ICs with different #s of MPI procs

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#14507]
## Bug Description
For nodal variables, initial conditions for nodes on the interface between two adjoining subdomains with block-restricted initial conditions are not set consistently.  Interface nodes between two subdomains unpredictably receive the initial condition specified for one or the other blocks depending on which subdomain's element is visited last in the mesh traversal.  This can cause the IC value along the interface to jump back and forth between each subdomain's IC value for complex meshes, and even worse, the IC values assigned to each node can be different depending on how many MPI procs the problem is run with.

## Steps to Reproduce
Using this input file fragment:

```
[Mesh]
  [./cartesian]
    type = CartesianMeshGenerator
    dim = 2
    dx = '1'
    ix = '3'
    dy = '1'
    iy = '2'
  [../]

  [./blocks-outer]
    type = SubdomainBoundingBoxGenerator
    bottom_left = '0 0 0'
    top_right = '1 1 0'
    input = cartesian
    block_id = 2
  [../]

  [./blocks2-inner]
    type = SubdomainBoundingBoxGenerator
    bottom_left = '.2 0 0'
    top_right = '.8 .5 0'
    input = blocks-outer
    block_id = 1
  [../]
[]

[AuxVariables]
  [./porosity]
  [../]
[]


[ICs]
  [./p1]
    type = ConstantIC
    variable = porosity
    value = 1.0
    block = '1'
  [../]
  [./p2]
    type = ConstantIC
    variable = porosity
    value = 0.5
    block = '2'
  [../]
[]
```

I get different subdomains' ICs winning on the boundary between them depending on how many MPI procs I run with.  Here is output for 1 proc:

![mpi-n1](https://user-images.githubusercontent.com/1351242/70638330-ecae3a00-1bf5-11ea-93af-f542903e8cd1.png)
 
And for 2 procs:

![mpi-n2](https://user-images.githubusercontent.com/1351242/70638345-f46dde80-1bf5-11ea-9075-2bd139b583ed.png)

And for 3  procs:

![mpi-n3](https://user-images.githubusercontent.com/1351242/70638394-09e30880-1bf6-11ea-9694-c91e6d417ed5.png)

There For more complicated meshes, you can also generally see initial condition values jumping back and forth between the values set by objects on two interfacing subdomains as the element looping order may hit one or the other subdomain last for each interface node - so you don't get clean, consistent interface values even for one MPI proc.

## Impact
The fix should not affect any APIs, but it will most likely cause test failures that use block-restricted initial conditions - but the failures should be easy to inspect and fix and/or regold.

**Comment by permcody** [comment]
See #14469.
