### ISSUE TITLE
Want to Run Tests in Parallel for Jenkins CI/CD

### ISSUE THREAD

**Issue by herter4171** [idaholab/moose#14532]
## Reason
Running the tests in serial is generally the most time consuming step, because typically only MOOSE has to be built thanks to the Docker build cache.

## Design

What's given [here in docker_ci/Jenkinsfile](https://github.com/idaholab/moose/blob/2fb844933ef7f58582808304f6a50ccb99dd1f9b/docker_ci/Jenkinsfile#L54), will be changed to run parallel tests.  I'm a bit confused on the best way to do this.  

By far, the fastest way I've found to run, assuming 36 cores, is 
```
make test -j 36
```
### Trouble with Color
Unfortunately, this defaults to color output, which isn't ideal for a log file.  I tracked down the boolean make variable `MOOSE_COLOR` in the module makefile, but both of the following crash spectacularly and still with color.
```
# With color spec as prefixed env var
MOOSE_COLOR=false make test -j 36

# Using make's -e flag and syntax
make -e "MOOSE_COLOR := false" -j 36
```

### Using Parallel Flags on Test Runner
The other method I've been working with is below.  It looks like some things run simultaneously, but overall run-time is still about the same as running in serial.
```
./run_tests -p --n-procs 36
```
Is there a way to run the tests in parallel without printing in color?
 
## Impact
No impact to the framework.

**Comment by cpgr** [comment]
Can't you just use
```
./run_tests -jn --no-color
```
to run with `n` cores?

**Comment by permcody** [comment]
@cpgr is correct. Just build and test separately as a workaround to your issue. There's no need to use the "make test" target. That being said, we could make the MOOSE_COLOR environment variable work with the TestHarness. I'm surprised it's not already.
