### ISSUE TITLE
ConcentricCircleMeshGenerator is not smoothing nodes on outer square

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14533]
## Reason
`ConcentricCircleMeshGenerator` is not smoothing nodes on outer square thus can create some strange looking mesh when smoothing is turned on. It does not look good and also can generate less accurate solutions.

The issue can be see with the following input:
```
[Mesh]
  [./ccmg]
    type = ConcentricCircleMeshGenerator
    num_sectors = 12
    radii = '0.248036411 0.328121329 0.350776456 0.372054616 0.382249781 0.39218'
    rings = '8 8 2 2 1 1 12'
    inner_mesh_fraction = 0.60
    has_outer_square = on
    pitch = 1.25984
    portion = top_right
    preserve_volumes = off
    smoothing_max_it = 1
  []
[]

[Outputs]
  exodus = true
[]
```
![quarter-pin](https://user-images.githubusercontent.com/6607496/71023773-aad33700-20c0-11ea-8e53-912ff9555019.png)

## Design
Looks to me this can be fixed by changing the order of adding side sets on outer boundaries and smoothing.

## Impact
Make this generator generate a better mesh.

**Comment by YaqiWang** [comment]
I checked the code, this is actually a libMesh thing. When smoothing, libMesh will fix nodes on boundary and block interfaces. This is fine for most of cases, but here, we only want to fix nodes on block interfaces. Boundary nodes should be moved by smoother. One solution is to add an optional argument in the smoother for controlling whether or not fix the boundary nodes. @jwpeterson Do you think adding optional arguments in `LaplaceMeshSmoother::smooth` is ok? If so, I can send in a small PR in libMesh. I am double checking this is indeed the reason.

**Comment by YaqiWang** [comment]
This is actually more complicated than I thought. There are three sets of nodes on boundary: four corner nodes, nodes also on block interfaces, and the rest nodes. The first two sets need to be fixed. The third set can be moved but has to be on the boundary specified by the four corner nodes. Please discard my previous comment. I do not have a good solution for this.

**Comment by jwpeterson** [comment]
Right, currently it's not an option to smooth boundary (or block boundary) nodes, since in most cases smoothing them would move Points outside/inside the domain (or block boundary) and invalidate the mesh. I agree that it would be possible to make moving these nodes optional, but note that there is no underlying description of the "geometry" that would allow a node to e.g. slide back and forth on the boundary so it would be tricky to do correctly in general.
