### ISSUE TITLE
Refactor Dirichlet/Preset BCs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14552]
## Reason

Dirichlet and Preset BCs are mathematically the same. However, there are two different implementations that work in similar ways that can give you different solver behaviors. PresetBCs can help reduce your initial solves, but can sometimes break initial solves depending on other conditions in the system. It's good to have both types available. The problem is that they are currently separate and there's not a good way to reuse code between them. We'd like to refactor these two types of BCs so that we can reduce copied or similar code.

## Design

Ideally we'd like to consolidate these two BCs into a single object and switch between the two with a parameter. This will mean we can remove duplicate objects.

## Impact

Moderate: Will require rewriting several input files but we should be able to deprecate the use of the old system for a period of time.

**Comment by bwspenc** [comment]
Another suggestion to further consolidate these:  Now that we can supply constant values where a function is expected, it seems to me that there is no need for `FunctionDirichletBC` either.  We can just make `value` in `DirichletBC` accept a function, and then supply either a constant number or a function.  Opinions?
