### ISSUE TITLE
Extension of IdealRealGasMixtureFluidProperties for e_from_p_rho and its derivatives

### ISSUE THREAD

**Issue by MatthiasKunick** [idaholab/moose#14571]
## Reason
The function e_from_p_rho and its derivatives w.r.t. p, rho, and x (composition) are required for the implementation of (velocity, density) boundary conditions with prescribed outlet pressure.

## Design
Extension of IdealRealGasMixtureFluidProperties and its base class VaporMixtureFluidProperties for e_from_p_rho and its derivatives w.r.t. p, rho, and x (composition).

## Impact
Extension of the current fluid properties interface for mixtures.

**Comment by MatthiasKunick** [comment]
@andrsd :
Let me know whether you need more than e_from_p_rho and its derivatives w.r.t. p, rho, and x (composition) right now.

**Comment by andrsd** [comment]
`e_from_p_rho` should give us the capability for mass flow rate inlet BC and outlet p BC IIRC. This should be good for our short term goals.

Long term, we would like to also have stagnation p and T, but that needs a lot more functions. I will get that list for you the next (European) week (or this - American-wise - week) :-D
