### ISSUE TITLE
Design doc for PorousFlow + ChemicalReactions

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14586]
## Reason

In the coming months, we plan major additions to ChemicalReactions and PorousFlow.  It may be a good time to refactor both codes.  This design document will direct and help organise our efforts.

## Design

I imagine the document will contain
 - details on how ChemicalReactions and PorousFlow work currently
 - proposed additions
 - descriptions on how we plan to add the new material, and potential refactors

## Impact

Organisation and clarity of direction.

@cpgr, this document might never appear in the PorousFlow documentation, but i think the moose markdown is a useful format for this document, hence i'm including it as a MOOSE issue.  Depending on the final form of the document we may choose to include it in the PorousFlow documentation.  We can just work on my branch for now, however.

Also notifying @rpodgorney .   @rpodgorney , could you please email an example of the type of chemical reaction you're interested in studying.

**Comment by WilkAndy** [comment]
Hi @cpgr .  Feel free to look at the above commit in my repo.  Nothing new yet... but it'd be good if you could comment on the Joiner+action stuff (although i hope we don't have to have any "joiner" stuff at all if we refactor).

**Comment by cpgr** [comment]
I'll add a bit about the hidden stuff tonight - I'll have to take a look at the code to remember what everything does!

**Comment by WilkAndy** [comment]
Heheheh, that's why i left it to you :-)   Don't spend too long on it, as i hope it'll either stay exactly the same, or be completely superseded.  Just write "this is done by some Actions" if you want.

**Comment by WilkAndy** [comment]
Hey @cpgr .  I've thought of a potential design.  I'm really interested to see what design you come up with (don't look at mine :-)   The design depends quite a bit on various assumptions regarding the chemistry - is it block dependent, do the activity coefficients depend on concentration, how many phases are there, etc.   I'm still not sure what's involved in GeoTES, and gas storage.

I'll probably leave this now for a few days until you've had time to think about it.

**Comment by WilkAndy** [comment]
This is old, and first round of geochem coding has been completed.  Closing
