### ISSUE TITLE
Documentation: table empty entry not displayed properly

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#14592]
## Bug Description

MooseDocs does not parse empty entry in Table properly. i.e. https://mooseframework.org/modules/phase_field/Phase_Field_Equations.html

## Steps to Reproduce

It happens at least in my up-to-date Chrome on Ubuntu 16.04, 18.04 and android.

## Impact

It confuses people who are trying to understand the equations.

**Comment by gambka** [comment]
I've seen this before as well. If I recall correctly having four spaces between the two | | for the empty entry in the table in the .md file renders correctly.  I'm not sure why this is the case. I know as a user you shouldn't have to modify the .md file for this particular file but could you verify if that corrects the issue?

**Comment by gambka** [comment]
I see the incorrect parsing @hugary1995 reports on Chrome on a Mac as well when I open the link provided.

**Comment by hugary1995** [comment]
This has been fixed.
