### ISSUE TITLE
CSV cannot output VPPs on nonlinear

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#14618]
## Bug Description
CSV creates VPP file names based on the time step index, even if `execute_on` does not just include "initial" and "timestep_end". For "nonlinear" for example, the same file name would be used for each nonlinear iteration.

## Steps to Reproduce
Create a VPP and a `CSV` with `execute_on = NONLINEAR`.

## Impact
Medium priority - execution/output of VPPs on "nonlinear" is useful for debugging convergence difficulties.

**Comment by joshuahansel** [comment]
I propose just giving an index to `CSV::getVectorPostprocessorFilename` that gets incremented at the end of each call to `CSV::output`, instead of always using the time step index.

**Comment by permcody** [comment]
> I propose just giving an index to CSV::getVectorPostprocessorFilename that gets incremented at the end of each call to CSV::output, instead of always using the time step index.

Maybe I don't understand your suggestion. Are you suggesting that we append an extra index or replace the time step index? It seems that in the 99% case tilmestep is exactly what you want. Like you said though, for debugging it'd be handy not to have your file overwritten so in that case we'd like to add something else. What would you do though if you had TIMESTEP_END and NONLINEAR? You have to think about all combinations. 

What I would propose is that if you turn on output at any frequency greater than once a tilmestep that we then add an extra suffix to the filename. That way everything works like it always has but you still get unique filenames that have some relationship to the timestep when you need it.

**Comment by joshuahansel** [comment]
> Are you suggesting that we append an extra index or replace the time step index?

I was suggesting *replacing* the timestep index with some other index.

> It seems that in the 99% case tilmestep is exactly what you want.

I agree with that: I would think that if your `execute_on` were `INITIAL TIMESTEP_END` (the 99% case), then my suggestion wouldn't change anything - I'll go ahead and try this to see if it's true. However, I expect it *would* change the indexing if `INITIAL` were omitted though - it would shift all of the indexes by one toward zero.

> What would you do though if you had TIMESTEP_END and NONLINEAR? You have to think about all combinations.

My suggestion wouldn't treat any combination differently - the index just corresponds to the index of the call to `output()`, which I thought would be the most flexible. For instance, if `execute_on = 'INITIAL NONLINEAR TIMESTEP_END'` and you take 2 nonlinear iterations, then the indices would correspond to the following:

Index | Output
-|-
0 | (initial)
1 | NL 0
2 | NL 1
3 | NL 2
4 | TS 1

The idea is that if the user is going to be doing something other than `INITIAL TIMESTEP_END`, then they are responsible for knowing how the indexing works... otherwise it should correspond to the timestep index, as expected.

**Comment by joshuahansel** [comment]
Or we can do as you suggest:

Index | Output
-- | --
0000 | (initial)
0001_0000 | NL 0
0002_0001 | NL 1
0003_0002 | NL 2
0001 | TS 1

If they request `LINEAR`, then we give them the middle finger.

**Comment by permcody** [comment]
The reason I like two indices is that you can quickly and easily find the time steps in the mix. With one index you really have no idea what is a timestep and what isn't. You are right though that if you have NONLINEAR and LINEAR on you really should have one more index but we could flatten that stage. I don't really have strong feelings about it. Go nuts.

**Comment by joshuahansel** [comment]
Closing in favor of #14634.
