### ISSUE TITLE
snesmf_reuse_base needs more protection

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14644]
## Reason
Based on conversation with @fdkong , that this parameter (default to true) optimized out one unnecessary residual evaluation when computing Jacobian based on the assumption that the residual from the previous last linear iteration can be reused since the same solution vector is passed in. However, users may accidentally introduce some state in the residual evaluation making the residuals with the same solution different the first and the second time calling the evaluation.

## Design
Thus I propose it is better to have a MOOSE assertion in debug mode, where we always not reuse the base, and check if the new residual and the residual from the linear iterations agree. If not, we issue message to let user turn `snesmf_reuse_base` to false in the input and also tell users something like
```
there is state in your residual evaluation, you may want to double check you input bla bla.
```
In this way, whenever users met problem, they can go debug mode to see if everything is sane.

Also when the solve is not converged, it is better to print non-converged reason. I agree when converged, we do not have to print, but in case of non-convergence, it is better to see something on screen to make users have less frustration.

## Impact
Reduce frustration.

**Comment by lindsayad** [comment]
> Based on conversation with @fdkong , that this parameter (default to true) optimized out one unnecessary residual evaluation when computing Jacobian based on the assumption that the residual from the previous last linear iteration can be reused since the same solution vector is passed in.

The assumption is that the last computed nonlinear residual and the zeroth linear residual should be the same. As you say in wonky cases, this assumption can be false.

**Comment by lindsayad** [comment]
@YaqiWang I don't suppose you have an example input file for which you know these residuals are different?

**Comment by lindsayad** [comment]
Never mind, I believe this phenomenon can be readily observed in mechanical/thermal contact. I'll just examine some of those cases.

**Comment by YaqiWang** [comment]
Great, otherwise it is a little pain for me to prepare one, ;-)

**Comment by fdkong** [comment]
> Also when the solve is not converged, it is better to print non-converged reason. I agree when converged, we do not have to print, but in case of non-convergence, it is better to see something on screen to make users have less frustration.

Totally agreed on this!

**Comment by lindsayad** [comment]
So @fdkong we should append `-snes_converged_reason -ksp_converged_reason`? But I guess that's not what we want if we don't want to print if we are converged.

**Comment by fdkong** [comment]
> So @fdkong we should append `-snes_converged_reason -ksp_converged_reason`? But I guess that's not what we want if we don't want to print if we are converged.

No, we already know the converged reason since we control that in moose. You could print it out when not converged. Do not need to use petsc options

**Comment by lindsayad** [comment]
Ok, I'll do that. It's interesting, when I reuse base in mechanical and thermal contact tests, everything passes. @fdkong do you remember why you had to turn off reuse base for those physics? Was it for BISON or something?

**Comment by fdkong** [comment]
> Ok, I'll do that. It's interesting, when I reuse base in mechanical and thermal contact tests, everything passes. @fdkong do you remember why you had to turn off reuse base for those physics? Was it for BISON or something?

I remembered there were several failing tests. We might already improve them
