### ISSUE TITLE
Create PPs to compute min/max/average of a material property

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#14648]
## Reason
One may need the min, max, or average of a material property over a domain.

## Design
I suggest two PPs: `ElementExtremeMaterialProperty` (like `ElementExtremeValue` for variables) and `ElementAverageMaterialProperty`.

## Impact
New PPs.

**Comment by aeslaughter** [comment]
I know you already have what you need, but here is some food for thought.

In #14633 I am working on creating stateless "Calculator" objects that work in serial or parallel for use in computing similar stats of VPP data. I did this foremost to support the parallel calculation as well as to allow for creating and adding new calculators easy.

It seems that these objects could be utilized for this task as well or perhaps the Statistics VPP could be extended to work on Materials
