### ISSUE TITLE
Discussion point: create a new "geochemistry" module?

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14725]
## Reason

This year, @cpgr, @rpodgorney and I are planning major additions to MOOSE in order to accurately model geochemical reactions.  The current `chemical_reactions` module already has reasonable functionality, but
 - it is designed (I think!) to be a generic solver for chemical reactions
 - it is difficult to use compared with standard geochemistry solvers
 - it does not have the functionality required for anything but the most basic geochemistry
 - it will require substantial refactoring to enable it to simulate geochemistry adequately, as many of its fundamental equations are inappropriate, and its design will probably need modification

Therefore, i'm asking whether people think creating a new `geochemistry` module is a good idea.  Apart from a proliferation of modules, I don't see any disadvantages.  The advantages include:
 - the name is clear: we are solving geochemical reactions only
 - no backwards compatibility issues
 - we start with a geochemistry-motivated design
 - ability to interface more readily with `porous_flow` to perform sophisticated flow+transport

## Design

A new module

## Impact

Ease of modelling geochemistry

**Comment by andrsd** [comment]
I personally think, new module is a better option (in case there will be a vote). It will definitely save you bunch of headaches. I see this to be similar to when tensor mechanics replaced solid mechanics - kind of...

**Comment by WilkAndy** [comment]
Thanks for your thoughts, @andrsd

**Comment by permcody** [comment]
Tag @rcm59

**Comment by WilkAndy** [comment]
If nobody has any objections, could you create a new "empty" `geochemistry` module, @permcody ?

**Comment by permcody** [comment]
OK - two things I need to chat with the team about (the other being the license PR (#14720). I'll get back to you on both today.

**Comment by WilkAndy** [comment]
OK, sure, thanks @permcody and team

**Comment by permcody** [comment]
@WilkAndy - Rich has given you the OK to add your module. Go nuts! If you need help getting it started let me know. It's a bit of a process as you know.

**Comment by WilkAndy** [comment]
Great, thanks everyone.   Actually, i don't know how to create a new module.  The last times you've done it for me.   Can you point to instructions?

**Comment by permcody** [comment]
Umm, OK - I probably don't have instructions good enough to successfully create one without missing something. I propose that I create the module and also write up instructions for future use. Sound good?

**Comment by WilkAndy** [comment]
Sounds great to me, of course, because i don't have to do anything!

**Comment by bwspenc** [comment]
I'm somewhat interested in this because I wonder if there are common features with this and with the models we have for moisture transport and chemical reactions in BlackBear.  I think what we do there isn't really considered porous flow: we use a diffusion equation with relative humidity as the solution variable.  Here's an example input file that does moisture transport:

https://github.com/idaholab/blackbear/blob/devel/test/tests/concrete_moisture_heat_transfer/maqbeth.i

We also have a capability for defining chemical reactions between species, which probably has some features in common with what you are developing here:
https://github.com/idaholab/blackbear/blob/devel/test/tests/concrete_sulfide_attack/sulfide_attack.i

**Comment by WilkAndy** [comment]
That's interesting, @bwspenc .   I don't think the transport part looks much like what we'll be doing, but the reactions are probably similar.  But i suspect we'll be using rather different solution techniques -  we will be using activities, redox couples, surface complexation, and other rather specialised things.   In the next week i'll be writing up the theory as `geochemistry` documentation and there you can see what i mean.

**Comment by bwspenc** [comment]
@WilkAndy Sounds good.  I'll take a look at your theory write-up when you do that and see if anything looks like it would be common for both applications.
