### ISSUE TITLE
New race condition testing not working correctly

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#14732]
## Bug Description

A recent change to CIVET appears to check for race conditions in testing.  I believe the command is `--pedantic-checks`.  It is observed that this check is causing failure in BISON but the reported error is nonsense and incorrect. The tests listed by the check absolutely do **not** modify the list of files that are being reported under the heading

` Each of the tests in this set create or modify each of the following files:`

From what I've observed it only occurs during the recover and heavy testing targets. 

## Steps to Reproduce

In the case of the recover failures I think the source of this incorrect behavior has to do with the directory structure.  Consider two tests files set up as so:

```
test/tests/my_awesome_model/tests
test/tests/my_awesome_model/more_specific_tests/tests
```

Upon recover the `--pedantic-checks` is reporting that input files insides of `my_awesome_model` are writing to files located in `my_awesome_model/more_specific_tests` which is not happening.  

In the heavy tests case it appears that the `--pedantic-checks` is not honoring any setting of `Outputs/file_base=` inside of `cli_args` in the `tests` file as it says all files are writing to a file that is not actually created by any of the tests due to the setting of `Outputs/file_base=`.  

Moreover, the reporting of the tests that fail the check appears to be sporadic.  Each time the tests are run a different set of inputs are being reported as having race conditions in CIVET. 

## Impact

Significant impact.  Cannot do any development as all MRs are failing on BISON.

Can new CIVET recipes and checks not be turned on and tested prior to roll out to all applications causing failures?

**Comment by gambka** [comment]
@lindsayad I don't think your commits address my issue here.

**Comment by lindsayad** [comment]
No, they don't. But I was making fixes for the MOOSE repo race conditions, and you were the first person I saw with a `pedantic-checks` issue

**Comment by gambka** [comment]
`pedantic-checks`  appears to be reporting incorrect information and causing failures when there shouldn't be.  I don't think the fix is in the `tests` file, it is a fix to be behavior of the `--pedantic-checks` itself. Unless I'm missing something.

**Comment by gambka** [comment]
@milljm @permcody

**Comment by permcody** [comment]
@gambka - I do believe that there is a bug in the pedantic checker. You are correct in that it appears to be grabbing tests in nested directories. I looked at the logic and I believe I see the issue. I think it's pretty easy to patch it. Watch for that patch shortly.
