### ISSUE TITLE
Check for Race Conditions only when needed

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14739]
## Reason

The Race Condition checker is useful but very expensive. We should work on a way to run it only when necessary.

## Design

Git has the capability to report all changed files. We could pass that information to the pedantic checker so that the TestHarness could only turn on pedantic checks when processing tests in an affected directory.

There is one weakness here. If somebody changes an object or code somewhere so a completely new file is written out. The strategy to look for changed tests or changed input files would completely fail.

## Impact

Moderate: Could speed testing but may miss some rare race conditions.

**Comment by cticenhour** [comment]
@milljm It looks like this should have been closed with #14771, but didn't get closed. This is true?

**Comment by milljm** [comment]
hmm yep. Closing.
