### ISSUE TITLE
Add ability to automatically populate 'prereq' for tests within a single specification

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#14734]
## Reason

To test or avoid race conditions it might be desirable to run all the tests within a specification in order.

## Design

The run_tests command should include a flag --auto-prereq to enable the aforementioned execution mode.

## Impact

This will be a new feature to allow for race condition handling as needed.

**Comment by aeslaughter** [comment]
@milljm We don't need this anymore do we?

**Comment by milljm** [comment]
Nope... everything is serial now (within tat test group).
