### ISSUE TITLE
TestHarness should move to a sandbox model

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#14745]
## Reason

For many years we've been running all tests in place and we've been using the "prereq" parameter to list both "true" and "order only" dependencies. The problem is that developers make many mistakes in listing prereqs, which in the past has led to many regressions in the testing system. We recently pushed a "pedantic checker" to monitor the filesystem before and after all concurrent tests to look for file output conflicts. This has slowed testing down quite a bit and shows us just how many other cases could potentially bite developers when running several tests concurrently. 

We are thinking about switching gears and moving towards a "sandboxing" approach for running every test. 

### Cons: 
The one thing that sandboxing will impact is the I/O. We will need to create and cleanup several temporary directories while running. We'll also have to retrain users to find their simulation outputs when running in the test system.

### Pros: 
Must more simple prereq specifications. Only true dependencies will need to be specified.

## Design

Sandboxing every test will mean that we can drop "order only" dependencies throughout every system which will simplify test specifications. It should also increase the robustness of the testing system in that each test will be treated independently. 

We will create a temporary directory for every test (separate test in the test spec) based on the test name (e.g. simple_diffusion-XYZ141). We will then change directory into that folder and run the input file. Output will appear in the cwd where we can diff it as normal. The temporary directory handling should be handled at the JobDAG level in the TestHarness. The reason for this is to properly handle true dependencies. If we had a test directory with a true dependency, we'd want to create the directory before running the first test, then keep that directory around until the second test was able to run. The Job can query the JobDAG to obtain a test directory, the JobDAG would either generate a new test directory or pass a handle back to the current one. The JobDAG should create/remove the test directories. Removal should only occur if all tests using that DAG return a successful status code.

## Impact

Moderate: While this won't effect the simulation results, it has a significant impact on the testing infrastructure. We can mitigate most of this by supporting the sandboxing as an optional mode for awhile before we completely replace the current non-sandboxed mode.

**Comment by permcody** [comment]
Tag @milljm

**Comment by rwcarlsen** [comment]
How will we name directories for multiple simulations (that depend on each other)?  This proposal involves a many to one relationship between tests and directories.

**Comment by permcody** [comment]
What about creating soft links for dependencies to the original directory?

**Comment by rwcarlsen** [comment]
That should work.  It will be a bit weird if the first test passes (the one the directory is named after) but a later one fails - then we will have to leave the directory for the first test there even though it passed just so that the later "failing" soft-links have something to point to.

**Comment by permcody** [comment]
I don't think that's weird. Every other alternative would likely require the first directory to stick around (because you'd be putting other test stuff in it). You could also append all the names together but for long chains, that would be ridiculous. Do we really want to copy lots of files around? What are you thinking?

**Comment by rwcarlsen** [comment]
I wasn't thinking of any solutions - just pointing out problems :-)
