### ISSUE TITLE
Mistake in the beam documentation

### ISSUE THREAD

**Issue by yw5aj** [idaholab/moose#14742]
A minor typo in:

https://github.com/idaholab/moose/blob/3541430c12315f5dd64e059d6285bb23a20de7e1/modules/tensor_mechanics/doc/content/modules/tensor_mechanics/C0TimoshenkoBeam.md#stress-calculation

For the calculation of delta M3(x), the coefficient should be E not G.

**Comment by cticenhour** [comment]
Closed via #14743
