### ISSUE TITLE
Add saturation temperature and pressure functions for fluid properties module

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#14755]
## Reason
Users may need to compute saturation temperature or pressure from pressure and temperature, respectively. This is useful for a number of reasons, such as the following:
- computing initial conditions of a two-phase fluid at a saturated state (and thus avoiding users describing invalid thermodynamic states)
- computing saturation properties for use in the post-processor system

## Design
This would add two functions:
- saturation temperature from given pressure function
- saturation pressure from given temperature function

The saturation properties will be supplied by a `TwoPhaseFluidProperties` object.

## Impact
This would create new functions.

**Comment by permcody** [comment]
We could do better on "reason" and "design". It's just asking why you need it and then the design would be mostly what you have in the reason.

**Comment by joshuahansel** [comment]
Sorry about that, it should be better now.
