### ISSUE TITLE
create joss_porous_flow branch in idaholab/moose

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14796]
## Reason

For our recently submitted article to Journal of Open Source Software (JOSS), the bot that creates the paper needs to have the address of the repo

https://github.com/idaholab/moose

It then searches for a file "paper.md" and "paper.bib".   We can give JOSS this information, but then it might appear like we're claiming that we wrote the entire MOOSE framework and all physics modules!  It also precludes anyone other MOOSE person publishing in JOSS while our paper is under review.   A better idea, suggested in openjournals/joss-reviews#2118 is to create a separate branch, say `joss_porous_flow` , get the bot to build from that , and do all amendments in that, and when the paper is published, merge the branch into `next`.

## Design

Create `joss_porous_flow` branch in idaholab/moose from current `next` or `master`.    Perhaps you want to do it @permcody or other MOOSE devels?

## Impact

The JOSS bot will be able to build our paper, and we'll be separate from the rest of the MOOSE community.

**Comment by WilkAndy** [comment]
Forgot to notify @cpgr

**Comment by WilkAndy** [comment]
Is this actually going to happen, @permcody ?    If not, then we can give JOSS the repo https://github.com/idaholab/moose   .   I think the `paper.md` documentation makes it clear we're just talking about PorousFlow, not the entirety of MOOSE and i don't think anyone else is publishing in JOSS right now.

a

**Comment by permcody** [comment]
Sorry - I kind of glazed over the fact you needed me to take action. Yes, I'd be happy to do this. Do you have a specific commit or do you want me to just point it to the current master? Another thought would be to tag it instead? That might be more appropriate since tags are generally permanent. Let me know your preference and I'll do this for you.

**Comment by WilkAndy** [comment]
Thanks @permcody .   I think just a branch, pointing to the current master, is fine.  Tagging is probably unnecessary - after the JOSS paper we will simply rename `paper.md` to `joss_porous_flow_paper.md`, merge this branch with "next", and delete this branch.

**Comment by permcody** [comment]
This has been completed.

**Comment by WilkAndy** [comment]
Thanks @permcody
