### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#14827]
## Reason

I would like to start a discussion on **units**. While we've kept saying MOOSE does not have specific units, and that the user has to make sure parameters are provided with consistent units, it would be nice to have the option of declaring base units of *length* and *time* (and possibly others).

## Design

Add a new `addParamWithUnits` input parameter function (at first only to replace `Real` parameters) that allows specifying a default unit (e.g. `m/s^2`).

We will develop a small parser that takes a string argument and parses it in to a vector containing elements `{prefactor, SI unit, exponent}` where the `prefactor` is derived form the unit prefix (k, m, G, etc.) and a possible conversion factor (feet to meters etc.), the `SI Unit` is the base unit,m and the `exponent` should be self explanatory. `km/s^2` would resolve to 

```
{{1000, m, 1}, {1, s, -2}}
```

From the default unit we would be able to check the dimensionality of the value (i.e. length over time square), permitting 

- ... users to supply numbers without units as they have done before (`accel = 0.004`)
- ... a sanity check if the supplied units `accel = 4 m/s^2` has consistent units  
- ... the computation of a conversion factor to `getParam` the value in the system units 

the latter would permit optional parameters in the problem block(?)

```
[Problem]
  length_unit = nm
  time_unit = s
[]
```

For all problem units not supplied in the problem block we would not perform any parameter scaling (i.e. we'd retain the current MOOSE behavior).

I think these changes would affect our InputParameters object and our parser.

## Impact
This will simplify model parameterization by making unit conversions by the user obsolete. It will enable input parameter unit checking. It could allow MOOSE to make suggestions for adjusted unit systems.

Tagging @WilkAndy who has shown interest in units in porous flow

**Comment by lindsayad** [comment]
Would this interact with `scaling`?

**Comment by dschwen** [comment]
I think it is semi orthogonal. This would make it easy to choose sensible
length units and not have your mesh go from 0 to 1e-8. Similarly with time
units.

**Comment by lindsayad** [comment]
So it's like [this](https://en.wikipedia.org/wiki/Semi-orthogonal_matrix)?

**Comment by WilkAndy** [comment]
I've found that new users find it a bit perplexing that we don't specify units, and that most users of PorousFlow think of parameters in non-standard SI units.  We have the ability to specify units in certain parts of PorousFlow, and this is made complicated because FluidProperties I/O only uses standard SI units (m, s, kg,..), and not more convenient things like (km, days,...).  There is quite a detailed discussion at

https://mooseframework.inl.gov/source/materials/PorousFlowSingleComponentFluid.html

which might help you get an appreciation of the difficulty of choosing nonstandard SI units in PorousFlow simulations.

**Comment by dschwen** [comment]
> So it's like this?

No like this:

![image](https://user-images.githubusercontent.com/202302/76025157-99444300-5ee9-11ea-9335-65d811397c98.png)

**Comment by amjokisaari** [comment]
Yes.  Yes.  Absolutely yes.  This would very, very helpful to make sure we didn't do something really stupid in doing the conversion by hand, and would likely maintain better precision.

**Comment by dschwen** [comment]
I've got the parser for unit strings done. Everything is reduced to base SI units. Some debugging output:

```
Parsing : m^3
m^3

Parsing : N*m
m^2*kg*s^-2

Parsing : mm
0.001 m

Parsing : kg/(m*s^2)
m^-1*kg*s^-2

Parsing : kg/(m*s)^2
m^-2*kg*s^-2

Parsing : eV/at
1.60218e-19 m^2*kg*s^-2*at^-1

Parsing : J/mol
1.66054e-24 m^2*kg*s^-2*at^-1

Parsing : m/s*s/m
1

Parsing : km/s*s/m
1000

Parsing : (km/s)*(s/m)
1000

Parsing : GPa
1e+09 kg*m^-1*s^-2

Parsing : psi
6894.76 kg*m^-1*s^-2

Parsing : kbar
1e+08 kg*m^-1*s^-2
```

**Comment by dschwen** [comment]
Btw, @friedmud , I'm all for leveraging existing solutions, but the person who wrote the Livermore units library has obviously never heard of the shunting yard algorithm. Their code is a lot longer and more complicated that it needs to be.

**Comment by lindsayad** [comment]
What a great algorithm name

**Comment by dschwen** [comment]
Argh, intensive vs. extensive quantities. Parameter units in the inputparameter definition need to be split into intensive and extensive parts (not in the input files though!). An energy per atom does contain length but will not scale with the mesh length units (however an energy density will).

**Comment by GiudGiud** [comment]
@dschwen do we have everything you were considering at this point? What's missing?

**Comment by dschwen** [comment]
I did all that I think should be done and that people can stomach.

**Comment by GiudGiud** [comment]
Ok so as far as people’s stomachs are concerned, this is good for closing.
