### ISSUE TITLE
Sparse quadrature grids for multidimensional function integration

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#14833]
## Reason
The naive method for integrating multidimensional functions is to use a cartesian product of one-dimensional quadratures. This method suffers heavily from the curse of dimensionality since the number of points is approximately N^D with N being the number of one-dimensional quadrature points and D being the dimensionality of the function. The main purpose of the integrations is to integrate polynomial basis functions, these functions typically involve complete monomials. These polynomials are more efficiently integrated with sparse grids. The most common sparse grids are Smolyak sparse grids. These are much more efficient than full tensor grids in high dimensional space. This feature is most applicable for non-intrusive polynomial chaos since the number of training sample is reduced significantly.

## Design
The easiest way to implement sparse grids would be to integrate another code's API. [Tasmanian](https://tasmanian.ornl.gov/)  is a great open source option. Otherwise, the method would have to be implemented in the utilities of the stochastic tools module. In the end, the implementation would involve a grid class that accesses abscissas and weights for each quadrature point.

## Impact
This feature would more efficiently train the polynomial chaos surrogate model.

![image](https://user-images.githubusercontent.com/12819067/76051318-a08a4180-5f27-11ea-9542-c089ad8fbf24.png)

**Comment by zachmprince** [comment]
@aeslaughter This should go in the stochastic tool project

**Comment by aeslaughter** [comment]
Done in #14934
