### ISSUE TITLE
JOSS PorousFlow paper amendments

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14831]
## Reason

@cpgr, reviewers (= @hsheldon) have suggested the following changes:

- Include the reference: Sheldon, H.A., P.M. Schaubs, Teagan N. Blaikie, Marcus Kunzmann, S. Schmid, and S Spinks. 2019. "An Integrated Study of the McArthur River Mineral System: From Geochemistry, Geophysics and Sequence Stratigraphy to Basin-Scale Models of Fluid Flow." In Annual Geoscience Exploration Seminar (AGES) Proceedings, 81-86. Darwin: Northern Territory Geological Survey

- Include the reference: Sheldon, H A, and P M Schaubs. 2017. "Predicting the Location of Unconformity-Related Uranium Deposits Using Numerical Simulations on a Supercomputer" In 18th International Association for Mathematical Geosciences Conference 2017, 54. Fremantle: IAMG.  @hsheldon , is this correct?  I can't find it online.

- Remove the reference to `[@heather]` (in favour of the above 2)

- Perhaps mention other applications where PorousFlow is useful, for instance industrial processes.

- Specify how PorousFlow is different from OpenGeoSys, PFLOTRAN and OPM.  (Andy thinks this might be difficult in just a few words, and we don't want to denigrate these excellent codes.)

## Design

Change modules/porous_flow/paper.md and modules/porous_flow/paper.bib .    Probably do this after #14796 is done.

## Impact

Better documentation

**Comment by WilkAndy** [comment]
Also, add this reference, which involves geothermal work:

Jin, W. and Podgorney, R. and McLing, T.  "THM coupled numerical analysis on the geothermal energy storage and extraction in porous fractured reservoir".  In 54th US Rock Mechanics Symposium, Golden, Colarado, USA, 28 June-1 July 2020, ARMA 20-1338.  1--10.

**Comment by WilkAndy** [comment]
Hi @cpgr , I've included the above references.  What's your opinion on @hsheldon 's other comments:

- Perhaps mention other applications where PorousFlow is useful, for instance industrial processes.

- Specify how PorousFlow is different from OpenGeoSys, PFLOTRAN and OPM. (Andy thinks this might be difficult in just a few words, and we don't want to denigrate these excellent codes.)

**Comment by cpgr** [comment]
They are both good points, but I think the paper is already near the word limit isn't it? It might be hard to do both?

**Comment by WilkAndy** [comment]
True about the word limit

**Comment by WilkAndy** [comment]
@cpgr just told me that Permann paper is now published - see #14851

**Comment by WilkAndy** [comment]
Closed by the above commit
