### ISSUE TITLE
Update Mesh View _While_ selecting boundary in parameter editor

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#1485]
If you select a "boundary" or "block" in the Parameter editor... the mesh view should update at that moment to show you which one you are selecting.

**Comment by permcody** [comment]
AFAIK - this works - tested it in simple_diffusion and I'm seeing the correct behavior.

**Comment by friedmud** [comment]
Nah - it's not working.  What the ticket is about is to update the mesh view while you're in the "parameter editor".  i.e. you've double-clicked on a BC and you are modifying the "boundary" parameter... I wanted it to update the mesh view (in the window behind the parameter editor) at that time... so you could tell what you were doing.

Maybe it's not important - but it's not "fixed"

**Comment by permcody** [comment]
@aeslaughter, @brianmoose 

We aren't fixing this in the old peacock. It's probably not relevant in the new peacock. Please look at it and close if appropriate.

**Comment by brianmoose** [comment]
In the new peacock, within the parameter editor, if you change the boundary then hit apply it will update the mesh view (the parameter editor is still open). Is the desired behavior to automatically update the mesh view whenever it changes and before apply is pressed?

**Comment by aeslaughter** [comment]
I think hitting apply is reasonable, otherwise you could get a bunch of calls to running an application with --mesh-only piled up.
