### ISSUE TITLE
Create geochemistry database reader

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14897]
## Reason

All geochemistry simulations will start with reading from a database, so we need it

## Design

The database is just a text file - we will read it and store data in appropriate data structures.   This issue may result in a small PR (just the reader) or a rather large PR (the reader; ability to query what minerals, secondary species, primary species, etc, are present; ability to do basis swaps; caches of info over several nodes; temperature interpolation, and so on) because it's difficult to know what functionality and data structures the reader needs to have before writing more geochemistry functionality.

Tagging @cpgr and @rpodgorney 

## Impact

Ability to read geochemical databases, and probably additional functionality mentioned above.

**Comment by cpgr** [comment]
I'm doing this atm!

**Comment by WilkAndy** [comment]
Great!  How do you want to schedule our efforts?  Do you want to push to a private repo while we get it right, or just issue an idaholab PR?

**Comment by cpgr** [comment]
I'm just doing some unit tests for what I have so I can push it up tomorrow. Still need some documentation so maybe you could add to that once I have pushed instead of me having to wait until the documentation PR gets merged?

**Comment by WilkAndy** [comment]
Yep, i'd like to do the doco.  i used to hate doco, but over the past years i've become a Mutant Documentation Lover.  If you PR to idaholab, i will do the doco.  Otherwise, tell me the branch and i'll fetch it from your repo.

During my bike ride home,  i specified, in my mind, the methods that we'll need from this Reader.  The whole `geochemistry` architecture/design is starting to settle in my mind - lots of work, but it's getting clearer every time i think about it.

See you tomorrow.  I've had quite a few wines - sorry if this is rambling!

a

**Comment by WilkAndy** [comment]
I'll add some doco to #14790 unless @cticenhour merges and closes that PR before i get a chance.  Not doco of your actual implementation, just doco of the functionality that will probably be required, so you can see what i'm thinking.  Then we can gradually "meet halfway" between your actual implementation and my dreaming.

**Comment by cticenhour** [comment]
> I'll add some doco to #14790 unless @cticenhour merges and closes that PR before i get a chance. Not doco of your actual implementation, just doco of the functionality that will probably be required, so you can see what i'm thinking. Then we can gradually "meet halfway" between your actual implementation and my dreaming.

Just merged and didn't see this in time - sorry about that! 😄 I would either make a new issue/PR so you can have that discussion, or follow-on to @cpgr's once that is up.

**Comment by WilkAndy** [comment]
No probs, @cticenhour  - adding that "database" doco to PR #14790 wasn't really appropriate anyway

**Comment by WilkAndy** [comment]
Closed by #14911
