### ISSUE TITLE
Let input parameters support std::map

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14894]
## Reason
There are cases that having map style input can be useful. For example, `petsc_options_iname` and `petsc_options_value` can be merged into one parameter
```
params.addParam<std::map<std::string, std::string>>("petsc_options", {{"-pctype", "lu"}}, valid_keys, "Available PETSc options in input files");
```
Then in the input users can give
```
petsc_options = '-pctype lu'
```
as the command line arguments.
Valid keys is used to detect any input errors on typing in the keys. We should be able to detect errors like duplicated keys in the inputs. Of course, the parameter can be optional, i.e. the default parameter does not have to be provided.

This is just one example. In reactor analysis, we often need to give the initial atomic densities of a set of isotopes. Currently we have to ask users to have
```
initial_isotopes = 'H1 O16 U235'
initial_densities = '0.1 0.1 0.1'
```
It will be nice we can have something like
```
initial_isotopes =
'
  H1   0.1
  O16  0.1
  U235 0.1
'
```
This will make input cleaner especially when we have lots of isotopes.

## Design
Looks like supporting map in parameters is a non-trivial task. It may require changes in libMesh as well.

## Impact
An alternative on inputting parameters that can make inputs more user friendly.

**Comment by permcody** [comment]
This would definitely require changes to libMesh.

**Comment by aeslaughter** [comment]
Did we talk about this a few months ago with syntax like:

```
options="year:1980 month:6"
```

**Comment by permcody** [comment]
You did. I want to caution against overuse of the map type. @aeslaughter for your case, using existing syntax is probably better because the list of valid keys is finite and small. Yaqi in this ticket gives a good use case (e.g. isotope information), which is something that wouldn't be feasible with existing syntax. So the criteria for using a map for a collection of input parameters instead of just adding additional parameters should consider the possible keys (left hand side information).

@roystgnr - Has anyone talked about map support in the Parameters system before? Do you anticipate any road blocks in adding that capability?

**Comment by roystgnr** [comment]
This looks quite sane to me.  The only obvious roadblock is that parameters.h currently assumes that any type you want to set has operator<< overloaded, whereas the C++ philosophy on making operator<< work with containers is "They're asking about that again? Get the user appreciation bat."  But we could replace direct operator<< with a template class that uses << by default and does more sophisticated printing with partial template specialization.

You know, now that I type that all out, it seems really stupid that we didn't put such capability in Utils a decade ago.  If I was smart I'd have added it alongside OStreamProxy and made that use it by default.

**Comment by roystgnr** [comment]
Hmm... if I decide to be lazy and just use overloaded OStreamProxy methods rather than a whole new class then this might be easy.  Let me check and see.

**Comment by YaqiWang** [comment]
Yes, I did a little coding in MOOSE and realized that parameter print function is giving trouble that uses the operator<<.

**Comment by YaqiWang** [comment]
@lindsayad looks like this is very close to finish. This is quite useful for Griffin. Maybe you want finish it?

**Comment by lindsayad** [comment]
Okie I'll try to get to it early next week

**Comment by lindsayad** [comment]
@rwcarlsen what kind of syntax would you think is best for this. It's unfortunate that I think the required code will not be so clean as what @rwcarlsen has done with `Field::vecIntVal, Field::vecFloatVal, Field::vecStrVal`

**Comment by YaqiWang** [comment]
What is this `Field::vecIntVal, Field::vecFloatVal, Field::vecStrV`? In my mind the syntax is like
```
Fe      0.01
U235 0.01
U238 0.01
O16   0.01
```

**Comment by lindsayad** [comment]
> What is this `Field::vecIntVal, Field::vecFloatVal, Field::vecStrV`?

These are the methods down in the hit parser that convert the input file syntax into the correctly typed parameters

**Comment by rwcarlsen** [comment]
The easiest thing to do would be to leave HIT alone and just do a strided string vector - i.e. `foo = 'Fe .01 O1600 .03 Pu3000 -42 ...'` and then just parse it into a map inside Moose's parser class.

**Comment by rwcarlsen** [comment]
Right now hit doesn't have any container data types really.  It would be nice to support things like lists and dicts sort of like json does.  If you want a key-value dict for use *within* the input file - you can do something like this:

```
[isos]
    u235 = 0.01
    pu1776 = 1492
    ...
[]

[foo]
    param1 = ${fparse 23 * ${isos/u235}}
    param2 = ${fparse 42 * ${isos/Pu1776}
    ...
```

**Comment by lindsayad** [comment]
> The easiest thing to do would be to leave HIT alone and just do a strided string vector - i.e. `foo = 'Fe .01 O1600 .03 Pu3000 -42 ...'` and then just parse it into a map inside Moose's parser class.

I like that idea

**Comment by aeslaughter** [comment]
> The easiest thing to do would be to leave HIT alone and just do a strided string vector - i.e. `foo = 'Fe .01 O1600 .03 Pu3000 -42 ...'` and then just parse it into a map inside Moose's parser class.

If you need some inspiration, I did something similar for ReporterName so you can include the object name and value name in one parameter.
