### ISSUE TITLE
Extend GeneratedMesh to include dim=0 case

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14893]
## Reason

Many geochemical models are zero dimensional - we just want to solve some reactions inside a test-tube.  I *think* to best use the MOOSE architecture i want to use a zero-dimensional mesh.

## Design

I think just create a single node with no elements.  The node should be part of a nodeset.

At the moment i need to check:
 - nothing crazy happens when i spread this over multiple processors
 - i can apply a BC to this node
 - i can apply a DiracKernel to this node

## Impact

Ability to run 0D models in MOOSE.  Wow, if you think that sounds stupidly simple, soon i'll want to run "D=-1" cases.  That is no space and also no time!

**Comment by tophmatthews** [comment]
> nothing crazy happens when i spread this over multiple processors 

Will you ever gain anything running on multiple processors with no mesh?

**Comment by tophmatthews** [comment]
Another way is to have one element, one qp, two nodes, but force all calculations to apply to both nodes?

**Comment by WilkAndy** [comment]
Yea, @tophmatthews , i think i'm going to have to use the D=1 mesh instead.  I'll just use one of the nodes for my calculations.  Not as clean as i'd like, and perhaps it'll muck up a multiapp approach one day.

**Comment by WilkAndy** [comment]
I'm not going to work on this.  I tried to get something working, but failed, and i haven't got time.  So, closing.
