### ISSUE TITLE
Support AD INS in RZ coordinate

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#14901]
## Reason

Currently, we can solve RZ INS using standard kernels and it will be great to implement AD version as well.

## Design

Need to modify related Kernels and Materials. 

## Impact

New capability.

**Comment by jiangwen84** [comment]
@lindsayad I do not think we have this capability so far, correct?

**Comment by lindsayad** [comment]
```bash
lindad@pop-os:~/projects2/moose/modules/navier_stokes/src/kernels(normal-nodal-lm-tangential-tolerance)$ ls *INS*RZ*
INSMassRZ.C  INSMomentumLaplaceFormRZ.C  INSMomentumTractionFormRZ.C
```

**Comment by lindsayad** [comment]
You can also look at the `RZ_cone` test. Additionally, we go through the RZ derivation in [our paper](https://www.sciencedirect.com/science/article/abs/pii/S0965997817310591)

**Comment by jiangwen84** [comment]
That is great! How about AD version?

**Comment by lindsayad** [comment]
Hmm...it looks like I didn't do the AD version :-(

**Comment by jiangwen84** [comment]
It is not a high priory and maybe I could work on it.

**Comment by lindsayad** [comment]
K, I'll let you choose whether you want to assign this to me or to  yourself
