### ISSUE TITLE
Add examples and associated documentation to STM

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#14933]
## Reason

For the purposes of teaching people to use stochastic tools.

## Design

The following is am (incomplete) list of examples needed.

- [x] Running perturbed simulations
- [x] Computing statistics and confidence level intervals from perturbed simulations
- [x] Training a surrogate model
- [x] Running a trained surrogate model
- [x] Polynomial Chaos...
- [x] Creating a custom SurrogateModel (be sure to talk about "training" parameters")

## Impact

This will be documentation, hopefully we will gain users.

**Comment by aeslaughter** [comment]
@zachmprince Can you edit the main comment? If so, please add what you think is needed.

**Comment by zachmprince** [comment]
I am not able to edit the main comments, so I'll put some stuff here.

Polynomial chaos:

- [ ]  Using Monte Carlo sampler
- [ ]  Using quadrature sampler and various types of sparse grids
- [ ]  Computing statistical moments
- [ ]  Computing local sensitivities
- [ ] Computing global sensitivities

**Comment by aeslaughter** [comment]
This has been done, see:
https://mooseframework.org/modules/stochastic_tools/index.html
https://mooseframework.org/modules/index.html
