### ISSUE TITLE
Running application with full-path to input file and no file_base creates dir structure. 

### ISSUE THREAD

**Issue by dylanjm** [idaholab/moose#14942]
## Bug Description

If you try to run an application specifying the full-path to the input file and the input file doesn't specify a `file_base` then it will create an empty directory structure inside the directory you ran the app from. 

## Steps to Reproduce

```bash
./app-opt -i <full/system/path/to/input/file>
```

for example:

```bash
> cd $HOME/Documents/projects/moose
> cd test
> ./moose_test-opt -i /Users/mcdodj/Documents/projects/moose/tutorials/darcy_thermo_mech/step01_diffusion/problems/step1.i
```

produces empty `Users` directory:

```
❯ tree Users
Users
└── mcdodj
    └── Documents
        └── projects
            └── moose
                └── tutorials
                    └── darcy_thermo_mech
                        └── step01_diffusion
                            └── problems

8 directories, 0 files
```

## Impact

Unexpected behavior.

**Comment by YaqiWang** [comment]
Wow, indeed ;-)

**Comment by dschwen** [comment]
@aeslaughter, I wonder if the root of this behavior lies [here](https://github.com/idaholab/moose/blob/5a6fabeba1e6a3bee85911f1bb3e46bba38dfc42/framework/src/outputs/FileOutput.C#L85). That line dates back 6 years(!)

**Comment by aeslaughter** [comment]
That seems about right, nice find. You passed my test, it only took 6 years for someone to find.
