### ISSUE TITLE
Add exclusive private parameter in BlockRestrictable

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#14944]
## Reason
There are objects that if it is defined on a block, no other objects in the same type should be defined on the same block. We currently do not have a machinery to prevent this from happening. I cannot think of a solid case just with MOOSE unfortunately.

## Design
I am thinking to have a private parameter `exclusive` in `BlockRestrictable`. This parameter defaults to false, when it is set to true in `ValidParams` of a class, MOOSE will conduct a check when adding an object, to make sure the object is the only one of the same class defined on the blocks. I have not coded this up yet to try if this works or not.

## Impact
New feature.

**Comment by permcody** [comment]
Same class or same base class?

**Comment by YaqiWang** [comment]
Classes including itself and all derived classes.

**Comment by lindsayad** [comment]
Your example in in the Griffin overleaf document is for materials, but wouldn't our problem integrity detect that a material property is being supplied multiple times on the same block?

**Comment by YaqiWang** [comment]
Interesting. I did not think of this. But looks like we did not get the error. Let me try and report back.

**Comment by YaqiWang** [comment]
I did get the error both in MOOSE and Griffin. Mark once complained something which made thought this was not in place. Then possibly I do not need this. Let me close it.
