### ISSUE TITLE
Geochemistry temperature interpolator

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#14950]
## Reason

Equilibrium constants and certain other things are evaluated at certain temperature points.  These things need to be interpolated to arbitrary temperature.

## Design

GWB uses a 4th-order polynomial fit.  I think @cpgr told me that other databases use other interpolations.  I'm not sure of the best design, but note that this function will be hit at least once for every node for every secondary species, so can't be too slow.  Perhaps we instantiate one of these interpolator objects for each secondary species at each node (memory!) or maybe just once for each equilibrium species over the entire mesh (but what about if we have different equilibrium species at each node).  I'm not sure.   Do you think you could do this, @cpgr ?

## Impact

Ability to interpolate.

**Comment by cpgr** [comment]
You're on fire Andy! I'll do this

**Comment by WilkAndy** [comment]
Thanks Chris.  I think we'll be churning out code much faster than the MOOSE guys can review it.

a

**Comment by WilkAndy** [comment]
Hey Chris - can you make the interpolator also produce derivative information?  It'll be useful when we have to do Newton stuff.

**Comment by cpgr** [comment]
I'm pretty sure it will

**Comment by WilkAndy** [comment]
This is closed by the PR  #14982
