### ISSUE TITLE
Add "working directory" option to RunCommnad.py script

### ISSUE THREAD

**Issue by jortensi** [idaholab/moose#14962]
## Reason
We are about to push a tutorial into griffin/tutorials/sph_tutorial. Two relevant directories under this one: sph and transients. There is a bash script in directory sph that prepares the data for the transients. Then there are two cases under the transients directory to prepare and initial condition and run a transient. These 3 tests are dependent on each other across multiple directories, which is currently not possible in MOOSE. 

## Design
The harness should include a "working_directory" option to allow dependent test cases to execute in different directories.
[Tests]
  [./prepare_data]
    type = RunCommand
    working_directory = 'sph'
    command = 'bash run_sph.sh'
    requirement = "Generate the sph library"
    group = 'tutorials'
    heavy = true
  [../]
  [./run_search]
    type = 'Exodiff'
    working_directory = 'transients'
    input = '1-D-sph-search.i'
    exodiff = 'out_1-D_hom_10Gt_sph_pmatch.e'
    requirement = "Set the initial condition for the null transient"
    prereq = 'prepare_data'
    abs_zero = 1e-7
    group = 'tutorials'
    heavy = true
  [../]
  [./run_null]
    type = 'CSVDiff'
    working_directory = 'transients'
    input = '1-D-sph-null.i'
    csvdiff = 'out_1-D_hom_10Gt_sph_null.csv'
    requirement = "Run the null transient"
    prereq = 'run_search'
    group = 'tutorials'
    heavy = true
  [../]
[]

## Impact
Adds significant flexibility to the test harness by allowing dependent test cases to execute in different directories.

**Comment by permcody** [comment]
One thing I'll add here as far as design is concerned is that the working directory should be a relative path. We should disallow any absolute path in the specification (i.e. cannot start with a leading slash). Ideally, we should be thinking about cross-platform support for anything like this, but I know we aren't doing this consistently in the TestHarness yet.

**Comment by permcody** [comment]
@milljm - Do you have any time to work on this task?

**Comment by milljm** [comment]
@jortensi 
Given your text block examples, the TestHarness will `cd` into 'working_drecitory' to perform the actual test and post-test (check gold file), which is also inside transients (transients/gold/gold_file).

Giving the above, the directory structure will look something like this after the test has run:

```pre
└─ simple_diffusion
   ├─ transients
   │  └─ gold
   │     └─ out_1-D_hom_10Gt_sph_null.csv
   │     └─ out_1-D_hom_10Gt_sph_pmatch.e
   │  └─ 1-D-sph-null.i
   │  └─ 1-D-sph-search.i
   │  └─ out_1-D_hom_10Gt_sph_null.csv
   │  └─ out_1-D_hom_10Gt_sph_pmatch.e
   ├─ sph
   │  └─ run_sph.sh
   └─ tests  #<-- spec file
```

Is this the functionality you are expecting?
