### ISSUE TITLE
If the mooseapp main folder name is different from the software name, moosedocs.py do not fine the markdown files

### ISSUE THREAD

**Issue by pbalest** [idaholab/moose#15017]
## Bug Description
I cloned my moseapp in a folder named moseapp-new1 to perform multiple task at the same time (like running cases and developing) but if I use `moosedocs.py` to build the documentation in the moseapp-new1 folder `moose/python/mooseutils/mooseutils.py` do not find the mooseapp executable.
at `line 109` of `mooseutils.py`
```python
name = kwargs.pop('name', os.path.basename(loc))
```
initialize name as `moseapp-new1` and then at `line 124` of `mooseutils.py`:
```python
    # Search for executable with the given name
    else:
        for method in methods:
            exe_name = os.path.join(loc, name + '-' + method)
            if os.path.isfile(exe_name):
                exe = exe_name
            break
```
the class do not find the file `projects/moseapp-new1/moseapp-new1-opt` and error out.

## Steps to Reproduce
``` bash
git clone mooseapp.git mooseapp-new1

```
compile the code there and then make the documentation.

## Impact
I like to have multiple repos one for running the code that I do not touch at all for development and one for development, to keep them in the same folder I have to use two different names.

**Comment by pbalest** [comment]
@aeslaughter any thought on that?

**Comment by rwcarlsen** [comment]
Why is the binary name different in the `new1` repo?  I would expect it to be the same since all the code (including makefiles) should be the same.  Are you modifying your makefile?

**Comment by pbalest** [comment]
Nope I am not modifying anything except the mooseapp ROOT folder name. The binary file is named correctly `appname-opt` when is generated, but the python scripts that are used to generate the documentation do not find it because they use the folder name to define the bin file name.

**Comment by rwcarlsen** [comment]
Maybe the doc scripts could use the `testroot` file (if one exists) to get the app name.  Otherwise the only options are scraping the project Makefile, or using the directory name.

**Comment by rwcarlsen** [comment]
@loganharbour ref'd this issue by mistake in another PR. reopening.

**Comment by aeslaughter** [comment]
I somehow missed this until now. I am not sure there is a solution. How do we determine the binary name in an application? The script needs to use that if it exists.

**Comment by rwcarlsen** [comment]
I think the testroot file would be a good option.  Python has code that
looks starting in cwd for a "testroot" file and up to each parent directory
until it finds the file.  That file, if it exists, contains the name of the
binary.  If it's not found, then we could just fallback to the current
behavior.

**Comment by aeslaughter** [comment]
I might also be able to look in the Makefile, I think APPLICATION_NAME is used. I will try to get to this soon.
