### ISSUE TITLE
Add empty definite integral method to Function

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#15013]
## Reason
Sometimes definite integrals are needed in order to calculate cumulative distribution functions. `Function::integral()` is already an empty virtual method for Functions for indefinite integrals. This can be easily extended for definite integrals.

## Design
Overload integral
```
  virtual Real integral(const Real start, const Real end) const;
```

## Impact
More flexibility with functions while not breaking built-in capabilities with Functions (e.g. `getFunction`)

**Comment by loganharbour** [comment]
Did you mean to close this after closing #15015?
