### ISSUE TITLE
Add documentation for update_and_rebulid_petsc.sh script

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#15057]
## Reason
There are some functionalities of `update_and_rebulid_petsc.sh` that are unclear, such as when internet is limited or unavailable. Functionalities like this and what the script does would be nice to have in one documented location.

## Design
Add `update_and_rebulid_petsc.md`

## Impact
Better understanding of how `update_and_rebulid_petsc` can be used.

**Comment by tophmatthews** [comment]
ping @fdkong

**Comment by fdkong** [comment]
You could do something like:

updated_and_rebulid_petsc.sh --download-parmetis=your/parmetis/dir/parmetis.tar.gz

Is this enough?

**Comment by tophmatthews** [comment]
Oh, I didn't realize you could just pass it through the script!

**Comment by fdkong** [comment]
> Oh, I didn't realize you could just pass it through the script!

Yes, you could override any parameter in the script through a proper command-line option.

BTW, in case you are unaware, external pcakges can be found here http://ftp.mcs.anl.gov/pub/petsc/externalpackages/

You could download the packages to your laptop, and then copy them over to the HPC that does not have internet.

**Comment by tophmatthews** [comment]
Wow awesome!
Is this documented on the website somewhere?

**Comment by fdkong** [comment]
> Wow awesome!
> Is this documented on the website somewhere?

No document, right now. Possibly we should do

**Comment by tophmatthews** [comment]
> o document, right now. Possibly we should do

I can change this! :)

**Comment by tophmatthews** [comment]
Rather, I can change this issue...you gotta do the work!

**Comment by tophmatthews** [comment]
well...does #15292 elevate this a bit? :)

**Comment by tophmatthews** [comment]
In all seriousness, this submodule makes it a lot easier, and I want to push the responsibility to users instead of having to build petsc for everyone that uses it on our HPC.

**Comment by tophmatthews** [comment]
Also, I do run in to this problem with the script:

```
...
          CC arch-moose/obj/tao/matrix/submatfree.o
     CLINKER arch-moose/lib/libpetsc.so.3.12.4
gmake[2]: Leaving directory `/home/topher/projects/moose/petsc'
*** Building slepc ***
*** Installing slepc ***
gmake[1]: Leaving directory `/home/topher/projects/moose/petsc'
Now to check if the libraries are working do:
make PETSC_DIR=/home/topher/projects/moose/scripts/../petsc PETSC_ARCH=arch-moose check
```

What does work is:
```
cd /home/topher/projects/moose/petsc
make check
```

**Comment by fdkong** [comment]
> What does work is:
> 
> ```
> cd /home/topher/projects/moose/petsc
> make check
> ```

`make PETSC_DIR=/home/topher/projects/moose/scripts/../petsc PETSC_ARCH=arch-moose check
`

should work

**Comment by fdkong** [comment]
> well...does #15292 elevate this a bit? :)

Yes. `conda moose-petsc` is the same as the PETSc submodule. So users should expect the same results by using `conda` or DIY.

I will do the documentation soon! Sorry @tophmatthews

**Comment by tophmatthews** [comment]
> BTW, `make check` is an optional step. You do not have to do that. You could go to build your libmesh right now

Yeah, Libmesh worked fine.

The error occurs when you are not in the moose/petsc directory. This is because I ran the script from the moose directory. Is there a way to modify the script to run the make file in petsc/makefile?

**Comment by tophmatthews** [comment]
Or take it out complete, so it doesn't freak out people that see an error. Maybe even have a screen out put that says `Petsc version 3.x.x built successfully`?

**Comment by fdkong** [comment]
> Or take it out complete, so it doesn't freak out people that see an error. Maybe even have a screen out put that says `Petsc version 3.x.x built successfully`?

Great suggestion! I can not assume users know PETSc -:)
