### ISSUE TITLE
Convective heat transfer interface kernel

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#15114]
## Reason

Modeling conjugate heat transfer between solid and fluid requires a term like this:

```
-k * normal * grad_Ts = h (T_s - T_f)
```

Currently, this does not exists.

## Design

Keep in mind that the fluid energy balance may be solved for `rho_E` (density times internal energy) so `T_f` may not be the variable of the fluid energy equation.

I would structure the parameters like this:

```
variable = T_solid
neighbor_var = rhoE
fluid_temperature = T_fluid
```

In case we use primitive variables so `T_fluid` is the variable we solve for, we'd have:

```
variable = T_solid
neighbor_var = T_fluid
fluid_temperature = T_fluid
```
 
## Impact

New capability.

tag @cticenhour

**Comment by cticenhour** [comment]
Are there other places in heat conduction where they handle the switch between `rho_E` and `T_fluid`? I think it'll be a minor change, but I've only just started working on the `heat_conduction` module.
