### ISSUE TITLE
Geochemistry: Replace 500.0000 in log10K

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15145]
## Reason

When log10(K) is unknown for equilibrium reactions, the geochemical databases write "log10(K)=500.0000".  This is dangerous when doing basis swaps, because the matrix of log10(K) values are multiplied by the swap-matrix, and the 500.0000 information gets lost and results in crazy-large values of K~1E500.  So, during construction of the matrix of log10(K) values, replace the 500.0000 with something reasonable.

## Design

It is sufficient to replace the last line of
```
  // populate the stoichiometry                                                                                                                
  for (const auto & species : overlap)
  {
    const unsigned row = _model.eqm_species_index[species.name];
    for (unsigned i = 0; i < num_temperatures; ++i)
      _model.eqm_log10K(row, i) = species.equilibrium_const[i];
```
in `PertinentGeochemicalSystem` with a check that if `species.equilibrium_const[i] == 500.0000` then create a `EquilibriumConstantInterpolator` object (when #14982 is merged) and substitute the interpolated value of log10K instead of the 500.0000

## Impact

Robustness of Geochemistry against these edge cases.

**Comment by cpgr** [comment]
Hi Andy,

I've been looking at this a bit. Would it be easier to not populate the MOOSE json database with these missing data values, and instead fill it with proper values during the python conversion?

So, if there are 8 valid logk points, just fill the json database with these values. If there are only 2, then linearly interpolate them to all other temperature points in the python (easy to do). 

Then we don't have any of these missing values when doing this sort of thing?

**Comment by WilkAndy** [comment]
> Hi Andy,
> 
> I've been looking at this a bit. Would it be easier to not populate the MOOSE json database with these missing data values, and instead fill it with proper values during the python conversion?
> 
> So, if there are 8 valid logk points, just fill the json database with these values. If there are only 2, then linearly interpolate them to all other temperature points in the python (easy to do).
> 
> Then we don't have any of these missing values when doing this sort of thing?

Yea, that would be fine, i think, providing we keep provenance info about where the database has come from, and probably make some note in the file saying "we linearly interpolated log10K for these species....".  I can imagine geochemists might look at a database with 500.0000 and think "oh, so the log10K is not well measured, so i should do such-and-such", but if we populate the 500.0000 with numbers we've "guessed" they won't have that capability.

**Comment by WilkAndy** [comment]
> > Hi Andy,
> > I've been looking at this a bit. Would it be easier to not populate the MOOSE json database with these missing data values, and instead fill it with proper values during the python conversion?
> > So, if there are 8 valid logk points, just fill the json database with these values. If there are only 2, then linearly interpolate them to all other temperature points in the python (easy to do).
> > Then we don't have any of these missing values when doing this sort of thing?
> 
> Yea, that would be fine, i think, providing we keep provenance info about where the database has come from, and probably make some note in the file saying "we linearly interpolated log10K for these species....". I can imagine geochemists might look at a database with 500.0000 and think "oh, so the log10K is not well measured, so i should do such-and-such", but if we populate the 500.0000 with numbers we've "guessed" they won't have that capability.

I should have been clearer: yes, i think this is a GOOD idea, thanks Chris.

**Comment by cpgr** [comment]
I can't decide if this is a good idea or not. If we move the logic of dealing with the missing value to the python utility, then I think we make the module susceptible to people hand-editing the database and introducing the 500's. 

Maybe it would be best to leave the 500's in the database so that is clear that they are missing (as you noted above), and create an interpolator for every species, and sample for each species in the code you posted in this issue. It would probably be more robust? Or am I overthinking it?

**Comment by WilkAndy** [comment]
I feel the chance of people hand-editing and introducing 500's is really small.  I reckon we go with your idea of filling during python conversion, with a note saying what we've done.
