### ISSUE TITLE
Record interpolation type in Geochemistry

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15146]
## Reason

We need to record the temperature interpolation type in `GeochemicalDatabaseReader` so we can use it in interpolations (when #14982 is merged).

## Design

Just need somehting like a new field in `GeochemicalDatabaseReader` along with a suitable getter.  Do you have time to do this, @cpgr ?

## Impact

Ability to use different interpolations.

**Comment by cpgr** [comment]
Yep, was going to do this but totally forgot. I'll do it.

**Comment by WilkAndy** [comment]
Thanks Chris,

a
