### ISSUE TITLE
Clean up elemental_as_nodal/scalar_as_nodal definition in outputs

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#15151]
## Reason
Currently, there are multiple `isParamValid()` and `getParam()` calls for the `elemental_as_nodal` and `scalar_as_nodal` input params in `AdvancedOutput` and `Exodus`. It makes it difficult to follow the logic, and also has the potential for uninitialized values for `_scalar_as_nodal` and `_elemental_as_nodal`.

## Design
Minimize the use of `isParamValid()` and `getParam()` in these objects.

## Impact
Should be none.

**Comment by permcody** [comment]
@loganharbour - thanks for your efforts to clean up the framework. Also thanks for labeling issues with components!
