### ISSUE TITLE
ADtemplate form

### ISSUE THREAD

**Issue by vanwdani** [idaholab/moose#15213]
## Bug Description
Using GenericMaterialProperty for AD templates causes problem with qp index, specifically within TensorMechanics for small plane strains
## Steps to Reproduce
This PR does the same as #14740, but causes exodiffs for 21 cases in TensorMechanics when the new AD/non-AD template form is used

## Impact
The correct values are calculated, but the qp indices are off, which cause exodiff answers

**Comment by permcody** [comment]
Closed by #15214
