### ISSUE TITLE
Add Traction form on INS AD kernels

### ISSUE THREAD

**Issue by anicolas91** [idaholab/moose#15221]
## Reason
It would allow to solve for cases where the viscosity simplification cannot be assumed.

## Design
It would be nice to have the equivalent of the MomentumTractionForm and MomentumTractionFormRZ kernels in the AD versions, at least in the INSADMomentumViscous.

## Impact
It would really help solve for cases where the Laplace form cannot be assumed. In my particular case, I'm looking at solving cases where the viscosity is not constant, and so far I can do that with the MomentumTraction kernels but not the MomentumLaplace kernels. Not sure if it is even possible to make such an addition (the traction form) on the AD equivalent. Sadly not an expert.

**Comment by lindsayad** [comment]
Thanks for submitting this issue @anicolas91. I will hopefully get to it in the not-too-distant future!
