### ISSUE TITLE
Integrate MOOSE Workshop with Main Website

### ISSUE THREAD

**Issue by crswong888** [idaholab/moose#15232]
## Reason
The idea is to create a more comprehensive version of the workshop slides that has its own place in `modules/doc` and appears much like any other section of the website, but perhaps with some of its own unique features/enhancements that improve the reader experience. This new section of the website would be intended for the at-home user and should be clear enough to supplement the workshop itself, to some extent. 

## Design
The general flow of this new workshop should, at the very least, follow the current one, with the restructurings which have been addressed in Issue #13617 as well. But there are certainly some further improvements which could be made, and should be made. For example, some of the more advanced modules, like the contact module, could use some updating and more demonstration. The `darcy_thermo_mech` tutorial shall still serve as the archetype for presenting the important concepts, but without the constraint of time that the in-person workshop has, there's hardly a limit on how far this can go...

Ideally, this new workshop should have its own address in the website that is obvious and easy for new user's to identify. It seems that we have allocated a position already, i.e., `modules/doc/content/tutorials`. So at first, I shall start adding content here. However, I will add that I believe what we end up calling this thing, whether its the "workshop", a "tutorial", a "user's guide", or whatever, is one of the most critical decisions, and it should be titled such that it begs a brand new user to click on it.

## Impact
The workshop content in a typical MOOSEDown format will be superior to the current slide format in many ways. First and foremost, the slides are intended to be complemented with an actual speaker, and so creating this more comprehensive version will allow it to be read as more of a narrative. The slides also feel a bit awkward and out-of-place with the rest of the website, and so this would certainly be an aesthetic improvement. Other improvements include the ability to link to other pages on the MOOSE website and enable all of the other features available with MOOSEDown, as well as increased performance compared to building, serving, and loading the slides.

**Comment by crswong888** [comment]
@aeslaughter let me know if the basic idea, here, is in agreement with what you intended for this project.

**Comment by crswong888** [comment]
@aeslaughter I started making some commits which reference this issue if you want to track my progress. Also, I'm not sure if its necessary or makes sense to assign me and/or yourself to this issue, but I don't have the authority to do that...

**Comment by aeslaughter** [comment]
When you are ready for me to take a look at something, create a Pull Request. In the first PR I would like to see the tutorial landing page and step 1 complete.

**Comment by crswong888** [comment]
@aeslaughter acknowledged.

**Comment by crswong888** [comment]
This ticket has become cluttered and unfocused so I have opened a [new issue](#18968) and will now close this one.
