### ISSUE TITLE
Check if a block has a material property or not

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#1525]
We already have checkMatProp() in SubProblem.h. But this method will error out when the input block does not have the property. I would like another method basically doing the same thing but returning a bool telling if the input block has the property or not. This is desired to me because I have a material depend on a material property in another material. If the property in another material is not defined, I use zero in the material. I need to call getMaterialProperty conditionally.

A small patch is created for this (I added two more methods for convenience):

Index: src/base/SubProblem.C
===================================================================
--- src/base/SubProblem.C	(revision 14769)
+++ src/base/SubProblem.C	(working copy)
@@ -80,6 +80,42 @@
   _active_elemental_moose_variables[}
 
+bool
+SubProblem::hasMaterialPropertyOnBlocks(const std::string prop_name,
+                                        const std::vector<SubdomainID> blocks)
+{
+  for (unsigned int i=0; i<blocks.size(); i++)
+  {
+    std::set<std::string> & prop_names = _map_material_props[blocks[i](tid].clear();
)];
+    bool hasit = false;
+    for(std::set<std::string>::iterator name_it = prop_names.begin();
+        name_it != prop_names.end();
+        ++name_it)
+      if(*name_it == prop_name) hasit = true;
+
+    if (!hasit) return false;
+  }
+  return true;
+}
+
+bool
+SubProblem::hasMaterialPropertyNotOnBlocks(const std::string prop_name,
+                                           const std::vector<SubdomainID> blocks)
+{
+  for (unsigned int i=0; i<blocks.size(); i++)
+  {
+    std::set<std::string> & prop_names = _map_material_props[blocks[i]];
+    bool hasit = false;
+    for(std::set<std::string>::iterator name_it = prop_names.begin();
+        name_it != prop_names.end();
+        ++name_it)
+      if(*name_it == prop_name) hasit = true;
+
+    if (hasit) return false;
+  }
+  return true;
+}
+
 std::vector<SubdomainID>
 SubProblem::getMaterialPropertyBlocks(const std::string prop_name)
 {
@@ -150,3 +186,18 @@
   }
 }
 
+bool
+SubProblem::hasMatProp(SubdomainID block_id, const std::string & name)
+{
+  std::map<unsigned int, std::set<std::string> >::iterator it;
+  if ((it = _map_material_props.find(block_id)) != _map_material_props.end())
+  {
+    std::set<std::string>::iterator jt;
+    if ((jt = (*it).second.find(name)) == (*it).second.end()) return false;
+  }
+  else
+    return false;
+
+  return true;
+}
+

Index: include/base/SubProblem.h
===================================================================
--- include/base/SubProblem.h	(revision 14769)
+++ include/base/SubProblem.h	(working copy)
@@ -182,6 +182,7 @@
 
   virtual void storeMatPropName(SubdomainID block_id, const std::string & name);
   virtual void checkMatProp(SubdomainID block_id, const std::string & name);
+  virtual bool hasMatProp(SubdomainID block_id, const std::string & name);
 
   /**
    * Will make sure that all dofs connected to elem_id are ghosted to this processor
@@ -194,6 +195,18 @@
   virtual void addGhostedBoundary(BoundaryID boundary_id) = 0;
 
   /**
+   * Check if the material property is defined on a list of blocks
+   */
+  virtual bool hasMaterialPropertyOnBlocks(const std::string prop_name,
+                                           const std::vector<SubdomainID> blocks);
+
+  /**
+   * Check if the material property is not defined on a list of blocks
+   */
+  virtual bool hasMaterialPropertyNotOnBlocks(const std::string prop_name,
+                                              const std::vector<SubdomainID> blocks);
+  
+  /**
    * Get a vector containing the block ids the material property is defined on.
    */
   virtual std::vector<SubdomainID> getMaterialPropertyBlocks(const std::string prop_name);

**Comment by permcody** [comment]
This is very old and there are several enhancements that have been added to MOOSE. Please open a new ticket if additional functionality is needed.
