### ISSUE TITLE
PorousFlow JOSS review improvement tips

### ISSUE THREAD

**Issue by jbrezmorf** [idaholab/moose#15268]
[PorousFlow JOSS review issue](https://github.com/openjournals/joss-reviews/issues/2176)

**Installation**
Minor issue with following [Moose instructions](https://mooseframework.org/getting_started/installation/conda.html). Activation of the conda environment using `conda activate moose` didn't work, the `source activate moose` did the job. Not clear to me as the former syntax should apply for the latest conda version I have used (following the instructions).

***Build***
Both MOOSE and PorousFlow builds fine. However, it took me some time to figure out that PorousFlow build actually makes the final MOOSE application. It would be helpful to add sort of "Get started" instructions to the first tutorial. In particular the formulation "The PorousFlow module is a library of physics for fluid" was confusing for me.

***Documentation***
Overall the documentation is complete and well structured. The tutorials cover the main applications of the framework and help a lot to begin with creation of own configuration files. 

***Lava tutorial***
- 1phase case works fine and the solution seems to be physically correct, in particular, the fingering phenomenon is captured. 
- using 4 threads leads to speedup 2.6 (from 20min to 7.5min), quite good
- 2phase case, can not proceed over the time 270352
  the nonlinear solver fails to converge which leads to timestep reduction down to about 0.001.
  I stop the calculation after 90min of the single thread calculation.
- The porosity is a random field, however it is not clear how the seed of a pseudorandom generator is determined. According to [the general MOOSE doc](https://mooseframework.inl.gov/old/wiki/MooseTraining/random/), it seems that the seed is not the same between application runs, but it is in contradiction to the claim that the PRNG is consistent for serial and parallel run. I found this generic page about PRNG as unsufficient to really understand the "multi-level random seeding scheme" in use. Having a command-line option to set the global application seed would be helpful.
- Please add a piece of information about the raw execution times of the tutorial problems. Knowing how demanding the lava tutorial is I would do the tests on the cluster using more cores.

***fracture transient***
Very good agreement between the 2d fracture `fine_thick_fracture_transient.i` and 1d fracture `fine_transient.i`.

**Comment by loganharbour** [comment]
I know that `conda activate` is the new and preferred method of activating Conda environments. However, we have found that `source activate` is necessary on some of our testing machines.

What OS did you counter this on and with what version of conda?

**Comment by loganharbour** [comment]
One more request: is `conda activate` simply unavailable or do you end up with an error?

**Comment by jbrezmorf** [comment]
It resulted in:
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

While the shell configuration steps make no difference. I'm suspicious that it can be caused by some previous installations of older conda versions.

**Comment by loganharbour** [comment]
What version of Conda (`conda -V`) and what operating system are you using?

I'm trying to replicate this so we can add some additional notes to the documentation.

**Comment by jbrezmorf** [comment]
```
 ~$ ~/miniconda3/bin/conda -V
conda 4.8.2
 ~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by cpgr** [comment]
Thanks for the thoughts on some of the examples @jbrezmorf. I'll add some notes to the documentation and input files for those examples that are more computationally expensive to make the user aware before they find out for themselves.

I'll double check the two phase convective mixing example too. It did work for me when I made it but it is possible that something has changed. 

Thanks again for the suggestions!

**Comment by cpgr** [comment]
@WilkAndy - I'll update the docs for these

**Comment by WilkAndy** [comment]
Thanks @cpgr.  For some reason i missed this issue completely - ooops.  I just set about fixing the umlauts in Phil's name: see #15320 (changed `{"a}` to `{\"a}` in the Acknowledgements).  So you don't need me to address any of the reviewer comments?

Remember to put in a PR to the `joss_porous_flow` branch - not to `next`.

**Comment by cpgr** [comment]
Oh, I would have pushed to `next` if you hadn't reminded me!

I'll look after all them today or tonight. I did notice that the paper is missing some capitilisation in the references for conference proceedings - things like the country names being lowercase. Can you fix them when you do #15320?

**Comment by WilkAndy** [comment]
If you want to check that the paper looks OK, go to https://whedon.theoj.org/ and enter your moose github repo address and your branch name.

I couldn't get the umlauts to work on Schaedle - i remember mucking around with that at the time of submission too.  The umlauts work OK in the bib file with the `{\"a}` method.  I know that Phil spells his name Schaedle (that is `ae` instead of `{\"a}`) so I think we should use that in the Acknowledgements, unless you can get the umlauts working.

**Comment by WilkAndy** [comment]
I'm a bit snowed under with a lot of admin stuff right now.  Unless you want to combine #15320 and #15268 into one PR, let's leave the umlauts and capitalisation until @rpodgorney has also done his review.  He might notice other things that need tweaking.   Just note the stuff you haven't done here or in #15320 and i'll address them in a couple of days.

**Comment by WilkAndy** [comment]
The paper has been published and @cpgr has addressed the suggestions, so this can be closed.
