### ISSUE TITLE
GenericRankNTensor

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#15276]
## Reason

When I am converting some of my AD materials, I need GenericRankTwoTensor<is_ad>

## Design

Add typedefs to MooseTypes.h

**Comment by dschwen** [comment]
We might want to create a macro to build a whole bunch of GenericXXX templates. There will be DenseMatrix and RealVectorValue and possible more.

**Comment by dschwen** [comment]
Actually, why don't we make this

```
template <typename T, bool is_ad>
struct Generic;
```

I have a few cases of classes templated on types (Real, or RankTwoTensor). And this way would be more flexible.

**Comment by hugary1995** [comment]
I like this idea!
