### ISSUE TITLE
Avoid copy in Stochastic Tools results transfer

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#15296]
## Reason

As pointed out in the following thread the computed stochastic result vectors may be copied in the current implementation.

https://github.com/idaholab/moose/pull/15273#discussion_r425465667

## Design

Improve the data handling in SamplerPostprocessorTranfer and StochasticResults.

The Transfer should populate the StochasticResults vector without copying data, if possible.

https://github.com/idaholab/moose/blob/e470dd3296b2d58901ee77a166e3c36987118166/modules/stochastic_tools/src/transfers/SamplerPostprocessorTransfer.C#L92

https://github.com/idaholab/moose/blob/e470dd3296b2d58901ee77a166e3c36987118166/modules/stochastic_tools/include/vectorpostprocessors/StochasticResults.h#L55

## Impact

Memory performance will improve the changes are internal and should have no impact on users code.

**Comment by aeslaughter** [comment]
Some useful links:

[lvalues/rvalues and their refernecess](https://www.fluentcpp.com/2018/02/06/understanding-lvalues-rvalues-and-their-references/)

[moving doesn't move](https://crascit.com/2015/09/21/when-moving-doesnt-move)

**Comment by lindsayad** [comment]
There are no performance concerns with the current design. It's just not as flexible as a `const` lvalue reference would be (which would have the exact same performance). There's a reason that the default signature for copy construction/assignment and move construction/assignment are
```
Foo(const Foo &);
Foo & operator=(const Foo &);
Foo(Foo &&);
Foo & operator=(Foo &&);
```
But if the code compiles as it is now and you know you only ever want to bind to rvalues, then keep it as is.

**Comment by aeslaughter** [comment]
This is a function that is not intended to be used outside it's current scope. If that scope changes then the copy construction/assignment methods can be added.
