### ISSUE TITLE
peacock error starting on Ubuntu20.04

### ISSUE THREAD

**Issue by akpopoola** [idaholab/moose#15314]
## Bug Description

Cannot start peacock on ubuntu20.04. When the command "peacock" is issued it throw the error below about pyqt5
## Steps to Reproduce

(moose) akxxxxxx@precision-m6700:~/projects/moose/examples/ex01_inputfile$ peacock
Traceback (most recent call last):
  File "/home/akxxxxxx/projects/moose/python/peacock/peacock", line 36, in <module>
    run_peacock()
  File "/home/akxxxxxx/projects/moose/python/peacock/peacock", line 28, in run_peacock
    sys.exit(main(sys.argv))
  File "/home/akxxxxxx/projects/moose/python/peacock/peacock", line 12, in main
    from peacock.CheckRequirements import has_requirements
  File "/home/akxxxxxx/projects/moose/python/peacock/__init__.py", line 11, in <module>
    from . import base
  File "/home/akxxxxxx/projects/moose/python/peacock/base/__init__.py", line 10, in <module>
    from .MooseWidget import MooseWidget
  File "/home/akxxxxxx/projects/moose/python/peacock/base/MooseWidget.py", line 10, in <module>
    from PyQt5 import QtCore
ImportError: cannot import name 'QtCore' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)

## Impact

command line line works OK and example output displayed on Paraview, I would just like to use peacock capabilities

**Comment by milljm** [comment]
It is interesting that I don't see this issue when using Ubuntu 20.04 within a WSL environment. And according to this: [systemd change](https://www.howtogeek.com/673018/systemd-will-change-how-your-linux-home-directory-works/) (the 'Limitations and Issues' near the bottom), I don't think we will be installing Ubuntu 20.04 on any multi-user, remote-access-only, system in our data center anytime soon (the inability to ssh into machine without an account already pre-created).

**Comment by milljm** [comment]
@akpopoola  I am running into many issues trying to get a good build of PETSc going (let alone a MOOSE build so I can run Peacock). How did you install Ubuntu 20.04? Was this an upgrade?

A fresh install requires quite a few tweaks. So far, the list of packages I've needed to install:

```bash
apt install build-essentials git bison python3-distutils
```
And because Ubuntu 20.04 removed and/or does not link python to python3, I have had to do that myself:

```bash
ln -s /usr/bin/python3 /usr/local/bin/python
```

Without the above symbolic link hack, I can not build PETSc. So this makes me curious about your setup.

**Comment by milljm** [comment]
I am able to run Peacock on Ubuntu 20.04 (fresh install) when I perform the following apt get installations:

```bash
sudo apt install build-essentials \
  git \
  bison \
  flex \
  cmake \
  python3-distutils \
  python3-dev \
  python-is-python3 \
  python3-pyqt5 \
  python3-matplotlib \
  python3-vtk7 \
  python3-pandas
```

And then build PETSc:

```bash
cd moose/scripts
./update_and_rebuild_petsc.sh
```

And then build libMesh:

```bash
cd moose/scripts
./update_and_rebuild_libmesh.sh
```

And then build MOOSE:

```bash
cd moose/test
make
```

And then run Peacock. I believe this is not a defect. Feel free to continue to comment here and I will try and help. But you may get quicker responses if you post these issues to our mailing list https://groups.google.com/forum/?nomobile=true#!forum/moose-users

Cheers!

**Comment by akpopoola** [comment]
Hi @milljm I actually followed the instructution on the website step-by-step. I used the conda environment which made things easier
https://www.mooseframework.org/getting_started/installation/conda.html

My Ubuntu20.04 was a fresh install, so it uses python3 by default.
