### ISSUE TITLE
Checkpoint restarts and MultiApp causing faulty behavior for coupled simulations

### ISSUE THREAD

**Issue by harterj** [idaholab/moose#15333]
## Bug Description
When a transient, coupled (using MultiApp) simulation is restarted from a steady state solution, a few things go wrong.
 
1) The temperature (auxvariable at the subapp level) is not properly restarted at the subapp level:

`bison0: Postprocessor Values:`
`bison0: +----------------+----------------+--------------------+`
`bison0: | time           | avg_temp       | disp_x_max_element | |`
`bison0: +----------------+----------------+--------------------+`
`bison0: |   0.000000e+00 |  -3.158068e+06 |       1.348055e-01 |  `
`bison0: |   1.000000e+01 |   9.598427e+02 |       2.699262e-01 |   `
`bison0: +----------------+----------------+--------------------+`
(I only showed two postprocessors here. The full output can be seen by running the included examples)
In this case, it does not affect the solve because the temperature from master is transferred before the calculation takes place. But that weird initial temperature will undoubtedly confuse analysts and indicate a problem with the restart system.
 
2) The displacements seem properly restarted, but oddly get “doubled” after the first time step. We think the thermal expansion eigenstrain is being reset during the restart causing the temperature change to once again impose a displacement. This behavior should not be occurring.

## Steps to Reproduce
 
To test the proper restart behavior, we run a null-transient, that is we first run a steady-state calculation and restart from it with a Transient executioner, expecting the solution to be time-independent.
 
More specifically, input files and mesh files are included in `examples/doubling_example` [https://github.com/harterj/moose/tree/doubling_bug](https://github.com/harterj/moose/tree/doubling_bug) These are for a simple problem coupling temperature to mechanics. 
Run `master_ss.i` first, and then run `master_tr.i` -- `master_tr.i` restarts from the steady state solution. You will see a negative, large initial value for temperature (problem 1)). You will also see the values for displacement restart, and nearly exactly double. This is present in this pared down example, but also in larger complex simulations.

## Impact
We are trying to couple neutronics and thermal mechanics for a micro reactor project. This prevents us from advancing on our project and we would like as much assistance as possible, please.

Tag @vincentlaboure @elementx54 @YaqiWang @jortensi @snschune

**Comment by lindsayad** [comment]
@harterj in the future can you put your input files in module examples directory corresponding to the modules needed to execute the input file? In this case it looks like it would need to be in `combined/examples`. Then I can just build and run without first looking through the input files and figuring out what modules I need to build

**Comment by lindsayad** [comment]
I do really appreciate the simplicity of these MOOSE-input-only files though for debugging purposes :+1:

**Comment by lindsayad** [comment]
So at least for the incorrect display of temperature in the beginning, I can see that the problem is that the nonlinear system for a transient simulation has at least a couple more vectors than the steady-state nonlinear system so we're reading data into new nonlinear system vectors in the transient restart that was actually the auxiliary data from the steady-state simulation. Then by the time we're trying to read in the aux data for the transient restart we're reading data from the IO buffer that has nothing to do with the correct aux vector data from the steady-state simulation...

**Comment by harterj** [comment]
> I do really appreciate the simplicity of these MOOSE-input-only files though for debugging purposes 👍

Oh, sure! And in the future I'll make sure to put the input files in module examples -- I haven't opened a MOOSE PR before...this was meant to be the first of many ;) (not sure if that's a good or bad thing)

> So at least for the incorrect display of temperature in the beginning, I can see that the problem is that the nonlinear system for a transient simulation has at least a couple more vectors than the steady-state nonlinear system so we're reading data into new nonlinear system vectors in the transient restart that was actually the auxiliary data from the steady-state simulation. Then by the time we're trying to read in the aux data for the transient restart we're reading data from the IO buffer that has nothing to do with the correct aux vector data from the steady-state simulation...

I see. Ok, so that garbage value makes some sense now, then... Cool. Looking forward to what you find out!

**Comment by vincentlaboure** [comment]
What confuses me is that `temp` is an Auxvariable in both the steady-state and transient sub-app. So the steady-state auxiliary data should be read into the transient auxiliary data.

**Comment by vincentlaboure** [comment]
@lindsayad What confuses me is that `temp` is an auxiliary variable for both the steady-state and transients sub-apps.
Because the transfer happens on `timestep_end` in `master_tr.i`, the garbage value comes from the restart of `temp` in the sub-app. So as far as I understand, this issue does not involve the nonlinear system. Or am I missing something?

**Comment by lindsayad** [comment]
For the example below, lets's say your steady-state nl system had 2 vectors but your transient simulation has 3. You  have an output stream from the steady-state simulation that looks something like this:

SS buffer:

nl vec 0 x x x x x x x x x nl vec 1 x x x x x x x  nl vec 2 x x x x x x x x x aux vec 0 x x x x x x x aux vec 1 x x x x x x x x x

Now you have an input stream in the transient simulation

nl vec 0 x x x x x x x x x nl vec 1 x x x x x x x nl vec 2 x x x x x x x x x nl vec 3 x x x x x x x x x aux vec 0 x x x x x x x x x x

When you read the data for nonlinear vector 3 from the input stream, you are actually reading data that is meant for the auxilary system!

**Comment by vincentlaboure** [comment]
I see, so you're saying that `aux vec 1` would not have anything to read and would get those garbage value -3.158068e+06.

I thought that's what `skip_additional_restart_data = true` used in `master_tr.i` was supposed to address. But maybe it does not propagate to the sub-app?

**Comment by lindsayad** [comment]
Correct. That option only applies to the master app.
