### ISSUE TITLE
Geochemistry: add time-dependency

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15330]
## Reason

Need to be able to simulate equilibrium reactions with time-dependency

## Design

Probably need to employ a NodalUserObject that uses coupledVars for temperature, etc, and does the initial solve in initialize() and subsequent solves in execute().  Whatever the design, here is some functionality that is required:

- after the initial solve, need to be able to change the constraint type in the `EquilibriumGeochemicalSystem` from "free_molality" to "bulk_moles" (and similar for minerals) EXCEPT for species with specified time-dependent activity and gases with specified time-dependent fugacity.  This is so that we can add or remove chemicals from the system.
- at any stage, change fixed-activity to "bulk_moles".  Probably the best user interface is a couple of std::vectors: remove_fixed_activity_name and remove_fixed_activity_time.  The opposite ("bulk_moles" to "fixed_activity") is unlikely to be required, and also requires setting the activity, so i suggest a user should use the save+restore feature mentioned below.
- at any stage, change fixed-fugacity to "bulk_moles".  Similar user interface.  This will require a swap of the gas out of the basis in favour of its aqueous counterpart (or, more generally, a secondary species).
- temperature can be time dependent.  Probably best way is to have temperature as a coupled variable, since that's what it'll be when we couple to transport
- Adding/removing chemicals from the system: the bulk mole number of a basis species (not gases or species with specified activity) can be time-dependent.  `EquilibriumGeochemicalSystem` should therefore be able to change the bulkMoles of species.  However, any chemical in the `MinimalGeochemicalDatabase` should be able to be added, not just the basis species, hence secondary species are decomposed into their basis components and these are added to the aqueous solution according to the stoichiometries (of course, if one of the basis components has fixed activity then its bulk composition is fixed by that, not by the addition of the chemicals).  Probably best that the *rates* of these added chemicals be coupledVars, even though they probably won't be Variables (only AuxVariables).
- Adding reactants at a temperature different from the aqueous-solution temperature.  This is a combination of the above two things (with the final temperature determined by heat capacities, eg  Bethke14.2: i'm not sure where we'll get the heat caps from).  Although we could, in principal, be adding reactant_i at temperature_i, I suggest just having the ability to set *one* temperature.  The reason is ease of building the user interface and the clarity of the user interface (and that i've never seen examples of multiple temperatures).   Of course, if reactants are added at a different temperature from the aqueous solution, then the temperature two bullet-points back will not be honoured.  THEREFORE, i suggest that the temperature two bullet-points back is either: (a) the temperature of the aqueous solution, if all the rates of addition/removal are zero for that timestep; (b) the temperature of the added reactants, otherwise.  This will require clear documentation, although in practice i think it'll be obvious to most users (since they won't be adding reactants *and* changing the aqueous solution temperature at the same time).
- changing activity or fugacity: probably best implemented using an AuxVariable for each one.  This means that log10Activity or log10fugacity does not need to be treated separately inside `geochemistry`: the user can just defined a ParsedAux that's `10^(-9+2*t)` or whatever.
- "dumping" minerals: need to be able to set the mineral free mole number (n_k) to zero, and shift the bulk moles accordingly (M_k -> M_k - n_k).  Remember this means that the free mole number of surface-sorbed species (m_q) must be set zero, and the free mole number of surface sites (m_p) set to zero, and the bulk moles of surface sites, M_p, will have to be altered.  The total amount of minerals removed needs to be reported.  Finally, swaps should be used to remove all the minerals from the basis in favour of secondary species.  I suggest that "dump" is an AuxVariable: if !=0 at some timestep then minerals get dumped at the beginning of that timestep.
- "flow-through": need to shift the bulk moles of all minerals in the basis M_k -> M_k - n_k, and then set n_k really small (but not so small that the minerals get swapped out)  (similar sorption remarks hold as for "dump").  The total amount of minerals removed needs to be reported.  This is obviously really similar to "dump" except no swap is performed.  I suggest that "flow-through" is an AuxVariable: if !=0 at some timestep then minerals get removed at the beginning of that timestep.
- "flush": this is adding pure water and removing reactants at the same rate, in order to conserve the overall mass.  It is very similar to adding chemicals (compare Bethke Eqn13.12 with Eqn13.5, etc) so i suggest that "flush" is an AuxVariable: if !=0 at some timestep then the system is acting in "flush" mode (Eqn13.12, etc) otherwise it is acting in "normal" mode (Eqn13.5, etc)
- "save": ability for `EquilibriumGeochemicalSystem` to save all molalities of the aqueous system (primary and secondary) into a file
- "restore": ability for `EquilibriumGeochemicalSystem` to read this file to initialise molalities.  The constraint meanings should be set by the user during this initialisation process.  The constraint values should be either set by the file (eg, calculating bulk_moles from the molalities, or activity from the molalities) or set by the user (to do another simulation, for example).  This is probably easily implemented by having another std::vector<bool> input, "value_from_file" that's either true or false.

## Impact

Ability to model common time-dependent geochemical systems.

Notifying @rpodgorney and @cpgr

**Comment by WilkAndy** [comment]
The "restore" should happen before doing the swaps.  Then the user can choose a different basis to a previous solve - advantageous if they want to fix fugacity of a gas that was previously a secondary species, for instance.

**Comment by WilkAndy** [comment]
Probably the "save" should mean that we need an AuxVariable for each species (basis, secondary, etc) and should save into an Exodus file.  Then restore should happen via a SolutionUserObject, etc.  I wonder whether an Action can add AuxVariables that specified by the `GeochemicalModelDefinition` UserObject?

**Comment by rpodgorney** [comment]
@andywilkins,  I worry having AuxVariables for each species will become overly cumbersome without some overlying Action


--
Robert Podgorney, PhD, PG
Geothermal Program Manager, Idaho National Laboratory
Modeling and Simulation Lead, Utah FORGE Program
Thermal Systems Co-Lead, INL Integrated Energy Systems Initiative

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: robert.podgorney@inl.gov<mailto:robert.podgorney@inl.gov>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by WilkAndy** [comment]
Yea, you're absolutely right.  There are usually at least 10 primary species and probably 100 secondary species.  We need an Action!

**Comment by YaqiWang** [comment]
Another possibly solution could be array variable/auxkernel. You may have one single array variable for all 100 species.

**Comment by WilkAndy** [comment]
Oh, can you give me an example, @YaqiWang ?

**Comment by YaqiWang** [comment]
https://github.com/idaholab/moose/blob/next/test/tests/kernels/array_kernels/array_diffusion_reaction.i is a test using array kernels. When I added array variable capability, I was not in needs of aux array kernels, so I did not added (but can be added easily). The number of components of a array variable can be any number.

**Comment by rpodgorney** [comment]
I like this approach, need to look a bit closer at the code


--
Robert Podgorney, PhD, PG
Geothermal Program Manager, Idaho National Laboratory
Modeling and Simulation Lead, Utah FORGE Program
Thermal Systems Co-Lead, INL Integrated Energy Systems Initiative

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: robert.podgorney@inl.gov<mailto:robert.podgorney@inl.gov>
Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by WilkAndy** [comment]
Cool, thanks @YaqiWang .  I'll consider it.  The disadvantage is that i won't know the names of the species, so will somehow have to record that.  I'll have a think....

**Comment by WilkAndy** [comment]
> The "restore" should happen before doing the swaps. Then the user can choose a different basis to a previous solve - advantageous if they want to fix fugacity of a gas that was previously a secondary species, for instance.

Actually, i don't think this ordering of "restore" is necessary (or even desirable).  The "restore" can happen at any time because it is just setting molalities.  Just have to be careful with constraints

**Comment by WilkAndy** [comment]
Woohoo, @rpodgorney and @cpgr, i just did my first time-dependent simulation and it all went really well.

https://mooseframework.org/modules/geochemistry/tests_and_examples/adding_feldspar.html

Lots of work to go, but the core machinery seems behave itself really nicely, so i'm quite pleased.

**Comment by rpodgorney** [comment]
well done @WilkAndy!

**Comment by WilkAndy** [comment]
OK, coding is basically done.  Need to spend a few days tidying.
