### ISSUE TITLE
JSON dump lists 'file_base' parameter as required for Outputs type blocks

### ISSUE THREAD

**Issue by brandonlangley** [idaholab/moose#15350]
## Bug Description

There are many valid MOOSE test inputs with `[Outputs]` type blocks that do not have a `file_base` parameter present, e.g.,

```
[Outputs]
  perf_graph = true
  print_linear_residuals = false
  [./out_displaced]
    type = Exodus
    use_displaced = true
    execute_on = 'initial timestep_end'
    sequence = false
  [../]

  [./console]
    type = Console
  [../]
[]
```

Above, neither the `[Outputs]/<Exodus>` block nor the `[Outputs]/<Console>` block have a  `file_base` parameter, and there is no `file_base` parameter defined in the `[GlobalParams]`.

However, the JSON input definition dump states that `file_base` is **required** for the following `[Outputs]` type blocks:
- `CSV`
- `Checkpoint`
- `Console`
- `DOFMap`
- `Exodus`
- `GMV`
- `Gnuplot`
- `Nemesis`
- `OutputObjectTest`
- `SolutionHistory`
- `Tecplot`
- `VTK`
- `XDA`
- `XDR`

Recently, in https://github.com/idaholab/moose/pull/14461, this parameter was changed from `params.addParam()` to:

https://github.com/idaholab/moose/blob/55438f1a558a9ee17f04446046c001866238483c/framework/src/outputs/FileOutput.C#L30-L35

It is now added via `addRequiredParam`, however the description that is being added with it seems to indicate that it is not required:

> The desired solution output name without an extension. If not provided, MOOSE sets it with Outputs/file_base when available. Otherwise, MOOSE uses input file name and this object name for a master input or uses master file_base, the subapp name and this object name for a subapp input to set it.

Since it appears to be such a common occurrence in MOOSE and MOOSE apps to have `[Outputs]` type blocks without the `file_base` provided, is this parameter supposed to be added as **required**?

## Steps to Reproduce

Examine the JSON input definition dump produced from running MOOSE with the --json command line parameter.

## Impact

The NEAMS Workbench is translating the JSON input definition dump to a schema which is used for input validation and autocomplete assistance across all MOOSE based applications.

Every input with a `[Outputs]` type block that does not contain a `file_base` parameter is being reported as invalid.

**Comment by brandonlangley** [comment]
@permcody -

This  is something that we are seeing quite a lot of when validating MOOSE application in the NEAMS Workbench. 

It translates to a Workbench validation error telling the user that a (seemingly) optional parameter is required to be present in some highly used blocks.

Should this be added to the **NEAMS Support General (FY2020)** milestone?

**Comment by YaqiWang** [comment]
The fix could be to simply make `file_base` parameter in `FileOutput` not required parameter. Its default value is set by MOOSE but not by `validParams` of `FileOutput`.

**Comment by lefebvrera** [comment]
Can this be added to our NEAMS FY20 [milestone](https://github.com/idaholab/moose/milestone/9)?
