### ISSUE TITLE
Implementing a Polynomial Regression in STM.

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#15361]
## Reason
This will give an alternative non-intrusive option to create surrogate models for parametric problems.

## Design
The new classes will inherit from the SurrogateTrainer/SurrogateModel classes and will override virtual functions.

## Impact
This will allow users to choose from multiple surrogate modeling techniques for their uncertainty quantification/design optimization/sensitivity analysis in their projects.

**Comment by aeslaughter** [comment]
Done by #15371
