### ISSUE TITLE
Incompatibility between periodic boundary conditions and a Lagrange multiplier constraint implemented as a scalarkerel/scalarvariable in tensor_mechanics

### ISSUE THREAD

**Issue by reverendbedford** [idaholab/moose#15365]
## Bug Description
I am trying to impose Hill-Mandel type constraints on a periodic RVE with the ability to impose arbitrary macroscale stress or strain conditions on the cell.  I would like to impose periodic BCs using the existing MOOSE system and then impose the cell average constraint using Lagrange multipliers.

As an initial test I've implemented the approach in a branch on my fork (https://github.com/reverendbedford/moose/tree/lagrange_periodic) for small strains and just for control over the macroscale stress.  This branch works if you just impose the cell-average constraint (+ constrain rigid body modes) but does not work if you then turn on periodic boundary conditions.  Whatever MOOSE does to enforce the periodic conditions affects the Jacobian contributions of the Lagrange multiplier, making the system really, really singular (essentially the Lagrange multiplier equation becomes 0 = 0).

## Steps to Reproduce
1) Clone https://github.com/reverendbedford/moose/tree/lagrange_periodic.  This includes only two new objects: 
a) A scalarkernel to enforce the Lagrange multiplier constraint: DummyLagrange (though not really, see below)
b) A kernel to provide the off-diagonal entries to the StressDivergenceTensor Jacobian: HomogenizationConstraint (though not really, see below)
2) Run the examples in the modules/tensor_mechanics_examples/lagrange_periodic directory

I provided 4 1D examples.  All the same problems occur in 2D and 3D.

1) 1d-noperiodic-works.i: just the lagrange multiplier, does what it should.
2) 1d-pbcs-fails.i: lagrange multiplier + PBCs: fails to converge
3) 1d-periodic-nodecon-penalty-works.i: applies periodic boundary conditions using node-node constraints and the penalty formulation: works
4) 1d-periodic-nodecon-kinematic-fails.i: applies periodic conditions using node-node constraints and the kinematic formulation: fails

So things don't work if periodic constraints rearrange the system of equations.  Things work if the equations aren't rearranged (either no periodicity or enforce it with a penalty).

## Impact
We've discussed an alternate implementation on the mailing list (something like the current GeneralStrain capability but with a stress so that it works for large deformations) but I would much prefer this method as it seems much cleaner.

## Potential causes
1) Actually my DummLagrange scalarkernel does nothing except provide an explicit 0 for the on-diagonal Jacobian for the lagrange multiplier (this zero is the correct exact Jacobian).  All the work in imposing the residual and off-diagonal (non-zero) Jacobian contributions is done in the HomogenizationConstraint kernel.  This is very non-MOOSE like, but as the example in moose/test/tests/kernels/scalar_constraint points out, it is much more efficient than doing things with the proper division of labor between the kernel and the scalarkernel.  Does this oddity cause my issue though?
2) The system is actually unstable with the PBCs.  I don't think so as
a) The penalty method works
b) It turns out in 2D just imposing the average stress constraint by itself results in an unstable system, presumably because you need the periodic constraint to fully-constrain things.
3) An actual bug with PBCs.

## Why I think this might actually be a bug and not a problem with how I'm trying to implement things
If you compare the Jacobian between the 1d-noperiodic-works case and the 1d-pbcs-fails case you see that MOOSE is actually altering the linear equations provided by the Lagrange multiplier (the last row of the matrix contains non-zero entries for the first case and is all zeros for the second case).  Why should the periodic constraint on disp_x do anything to that equation?

**Comment by bwspenc** [comment]
@reverendbedford Folow-up to our conversation:  the code that computes the periodic constraints is in libmesh in `compute_periodic_constraints` in `FEBase.C`.

**Comment by reverendbedford** [comment]
We found a better way to do this, PR in progress.
