### ISSUE TITLE
Standalone `hit` tool should accept files from stdin

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15382]
## Reason
I'm working on a hit format plugin for atom, anticipating a hit format check hitting civet in the foreseeable future, and to help people write input files that look pretty. It would be nice to have the `hit` formatting tool accept `-` as a filename, and just read from stdin in that case.

## Design
1. allow `-` as a filename (currently the options parser spazzes out)
2. change `std::ifstream f(fname);` to `auto f = fname == '-' ? std::cin : std::ifstream(fname);` or something along those lines.

## Impact
Added functionality and more unixy feel for the `hit` tool. @rwcarlsen

**Comment by rwcarlsen** [comment]
Fine with me.  The hit tool/exec was really born just as a quick hack to scratch my own itch(es).  It definitely could be improved in this and many other ways.
