### ISSUE TITLE
Make more use of constant_on in Materials

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15417]
## Reason
A bunch of material classes in MOOSE are implicitly constant over either elements or subdomains. The Material base class has the `constant_on` parameter, which however is not being made use of to the extent possible.

## Design
Go over framework and modules classes to check where we can default the `constant_on` parameter to anything other than `NONE`.

## Impact
Potential speed-ups.

**Comment by tophmatthews** [comment]
Is this to try and speed up things, ie elasticity tensor? A constant over timestep would be helpful as well, e.g. compute elasticity tensor based on the previous temperature, especially if it was a one line change to be able to provide prototyping vs production runs
