### ISSUE TITLE
Quaternion Algorithm in EBSDReader Does Not Scale

### ISSUE THREAD

**Issue by frombs** [idaholab/moose#15418]
## Bug Description
A quaternion based method to average grain orientations in `EBSDReader` was added to MOOSE in  PR #13893 based on issue #13869.  The algorithm runs fine for small test problems but does not scale well as the problem size increases.  As the quaternion matrix size grows, the memory usage also increases until all the system memory is used.  On my mac, the program continues to run until the virtual memory runs out (~450GB) at which point the simulation exits with an "out of memory" error.  A stack trace for a 2D simulation with mesh size of 1376x1376 follows:  [stack_trace.txt](https://github.com/idaholab/moose/files/4747967/stack_trace.txt)

The memory issue seems to originate from [line 260](https://github.com/idaholab/moose/blob/060931b612a0532c3acc9449e4621a18cee5239a/modules/phase_field/src/userobjects/EBSDReader.C#L260).  By adding print statements to `EBSDReader`, it is clear the simulation crashed when averaging a large feature in the dataset. ![console_1](https://user-images.githubusercontent.com/8171022/84069634-10c1bc80-a988-11ea-8a5c-44268f2fd6cf.png)

Here is the `memory_logger` plot:
![figure_1](https://user-images.githubusercontent.com/8171022/84069742-423a8800-a988-11ea-959f-b5e5fbf01760.png)

@rayaprolu143 & @dschwen, can the algorithm be made more robust or optional?  

For my use case, the angles output from DREAM.3D were already averaged using quaternions so it does not make sense to average them again...especially if it causes large memory spikes or extra CPU time to perform.  

Note: DREAM.3D performs the same quaternion averaging with very little memory usage.  Perhaps we should look at their method? 

## Steps to Reproduce
The mesh size of the current tests are too small to crash.  Need to find a larger problem to test against or I can upload my dataset if needed.

## Impact
Currently, not able to run moderate to large EBSD problems.

**Comment by frombs** [comment]
@permcody, after thinking about this, I ran it on my mac with a single processor so the memory issue isn't caused by running on multiple processors.

**Comment by dschwen** [comment]
have you tried setting `bins = 1` ?

**Comment by dschwen** [comment]
The code implements the first answer from https://stackoverflow.com/questions/12374087/average-of-multiple-quaternions

which is solving an eigenvalue problem for the QQ^T matrix. That matrix should be only 4x4 though. Even though the Q matrix is 4xN (with N being the number of datapoints in the grain). 

I suppose one could build QQ^T without building the Q matrix! That would probably solve this issue.

**Comment by dschwen** [comment]
The fact that the weight matrix is explicitly allocated sure does not help either. If at least that matrix were sparse.
