### ISSUE TITLE
Conda installation instructions should include a mention of conda init

### ISSUE THREAD

**Issue by cticenhour** [idaholab/moose#15436]
## Reason
In the current documentation we have the following sentence:
```
Some folks may receive additional instructions when attempting to activate a profile. Follow those instructions, and try to activate the moose environment again.
```
Users commented during the workshop that this was too vague and could be outlined a bit more. The main pain point is whether someone uses the GUI installer (where you don't get much of an initialization prompt, if any) and the command line installer (which does request that you perform `conda init`. If there is a glitch in the GUI install (or a missed command line prompt), then users are left to guess at what might have done wrong. 

## Design
A short discussion of what users will see when they perform the installation, perhaps, so that it's completely clear what needs to be done if they miss these instructions and have an issue with not initializing their conda installation. 

## Impact
Improved documentation and user support.

**Comment by cticenhour** [comment]
Tagging @milljm for comments about what is best here.

**Comment by GregVernon** [comment]
Documentation might include pointers for how to determine what shell the user is using  (e.g. `echo $0`)  Perhaps this could just be piped into the `conda init` command for the user to copy?

**Comment by milljm** [comment]
Some of this is being addressed in an FAQ/Troubleshooting guide I've been working on, but is not yet linked to the main Getting Started instructions:

https://mooseframework.inl.gov/help/troubleshooting.html#buildissues

**Comment by cticenhour** [comment]
In that case, would you want me to close this issue in favor of another one? I wasn't aware this was being addressed as part of another issue.

**Comment by milljm** [comment]
As for what to do... I wish we can simply offload the issue to a Conda HowTo page... but man... they are EXTREMELY lacking in support

**Comment by milljm** [comment]
I honestly want to drop any mention of Anaconda. No linking to Conda. Just supply our own cut and paste instructions to clear up any confusion...

**Comment by milljm** [comment]
Basically, I want to remove this section:

note:Anaconda also works

You may choose to use Anaconda if you so desire: Anaconda for Python 3.x

You may follow Miniconda's instructions: Install Miniconda3, however we continuously receive reports of difficulty doing so (especially from our MacOS users). With that said, please use our instructions to install Miniconda instead:


Just skip right on down to our copy/paste instructions (starting with curl)

**Comment by GregVernon** [comment]
> Basically, I want to remove this section:
> 
> note:Anaconda also works
> 
> You may choose to use Anaconda if you so desire: Anaconda for Python 3.x
> 
> You may follow Miniconda's instructions: Install Miniconda3, however we continuously receive reports of difficulty doing so (especially from our MacOS users). With that said, please use our instructions to install Miniconda instead:
> 
> Just skip right on down to our copy/paste instructions (starting with curl)

I agree, I'll freely admit that I first went down a rabbit hole when I saw first saw this.  Confused the heck outta me.

**Comment by milljm** [comment]
@cticenhour, na... lets leave this issue open... I will address it as I update the FAQ
