### ISSUE TITLE
Remove mention of moose-environment packages

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#15441]
## Reason
We have (possibly a few) a markdown page still referencing the now deprecated moose-environment packages.

## Design
Modify impacted markdown pages to reference our Conda MOOSE Environment instead.

## Impact
Removal of moose-environment packages.

**Comment by cticenhour** [comment]
Closed via #15443

**Comment by milljm** [comment]
I forgot to check more areas possibly mentioning moose-environment packages! Re-opening.

**Comment by milljm** [comment]
And module load commands
