### ISSUE TITLE
Rename master/slave to primary/secondary in contact

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15457]
## Reason
Historic connotation of the master/slave relationship is more than problematic. It seems like we are trivializing this by continuing to use these terms in the context of a mechanical contact simulation. 
 
## Design
Rename to `primary` and `secondary`. These terms do not convey any less meaning and do not have the same baggage.

## Impact
Everyone should be proud and comfortable working in the MOOSE developer and user space. Our environment should be as inclusive and inviting as possible. Using terms fraught with historical atrocity does not accomplish that goal

**Comment by bwspenc** [comment]
I'm totally on board with changing the name to something else, but I don't think the 'primary/secondary' nomenclature is very descriptive. We need to have more discussion of the replacement naming before jumping in and doing this.

**Comment by GregVernon** [comment]
I agree wholeheartedly with this issue.  To @bwspenc's point, I think it would be helpful to have the broader FEM community involved in this discussion; it would be nice to introduce a systemic change to our field.

**Comment by friedmud** [comment]
I am ok with changing this - there really is no avoiding it at this point... we'll look like an anachronism if we don't.

I agree with @bwspenc though... primary/secondary doesn't do it for me.

**Comment by friedmud** [comment]
Well - I'm coming around on primary/secondary... I can't see many other options.

**Comment by bwspenc** [comment]
I'm coming around to primary/secondary too.

**Comment by GregVernon** [comment]
A few suggestions that have come up from my circles:

1. Captain/Cadet
2. Leader/Follower
3. Master/Follower
4. King/Pawn
5. Master/Minion

It would be nice to have a terminology that is objectively precise - probably only 2 & 3 accomplish this, whereas the others are "cute" but perhaps not very useful/precise.  I also continue to think that we should try to bring about a systemic change beyond MOOSE.  It would be nice if the FEM community and especially the various DOE entities could all adopt a congruent terminology.  I also think it's fair to deprecate the usage in such a way that helps users understand the change that was made.

**Comment by lindsayad** [comment]
#15473 has been merged, but I'm not going to consider this closed until after I get "slave" (and all possible case matches) into the banned keywords list in `civet_recipes`
