### ISSUE TITLE
PorousFlow doco bug

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15454]
## Bug Description

As reported from a user:

In the PorousFlow documentation there is a tiny error.

https://mooseframework.org/modules/porous_flow/tutorial_08.html

The link to "boundaries" in the first paragraph should be instead of

https://mooseframework.org/modules/porous_flow/porous_flow/boundaries

https://mooseframework.org/modules/porous_flow/boundaries.html

**Comment by cpgr** [comment]
I also noticed recently that the images in https://mooseframework.org/modules/porous_flow/coal_mining.html aren't rendering properly if you want to fix them too!

**Comment by WilkAndy** [comment]
Thanks @cpgr

**Comment by aeslaughter** [comment]
This is just a documentation error, correct? Or are you reporting something that is documented correctly that gives the wrong rendered result.
