### ISSUE TITLE
Allow custom face-quadrature rules in different subdomains

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#15472]
## Reason
Allow custom higher quadrature where necessary (for accuracy, stability, etc.) without causing any larger performance penalty than necessary.

## Design
A desgin has already been implemented for custom element (volume) quadrature (see #14055 and #14214 and #15470).  This just needs to be extended for specifying custom face quadrature rules as well.  The challenge is that along boundaries between two subdomains, for things like DG kernels, the face integration will be run from either of the face's two neighboring elements (whichever has the lower element ID).  The lower element id side for each face may be different depending on how the elements are all numbered - mesh partitioning can also affect this.  The end result is that along boundaries between subdomain the chosen custom quadrature rule could jump back and forth between the one specified for each subdomain - rather than being consistent.  This problem/challenge is similar to the one recently tackled with subdomain restricted ICs.  Resolving this ambiguity satisfactorily is the crux of adding this feature.

## Impact
Shouldn't impact any existing users/capability.  Just new stuff to play with.

**Comment by YaqiWang** [comment]
Ideally on the face, we should use the higher order of the two sides.

**Comment by jortensi** [comment]
when should we be expecting this?

**Comment by rwcarlsen** [comment]
I suppose it depends on how urgent it is for you guys?  I will probably be
able to get around to this within the next month or so.  If you need it
sooner, let me know and I can probably start working on it next week.

**Comment by YaqiWang** [comment]
@rwcarlsen you told me to work on this this week or the previous week? What happened?

**Comment by rwcarlsen** [comment]
@YaqiWang - Sorry.  Other things came up.  If this is important for you guys, I can get crackin' on it within the next couple business days.

**Comment by rwcarlsen** [comment]
Do you guys need to be able to specify face quadrature order independently from volume quadrature order?  Or do you just need the face quadrature order to match/follow the volume quadrature order?

**Comment by YaqiWang** [comment]
The later. Face quadrature order needs to be the maximum of two sides.

**Comment by rwcarlsen** [comment]
Great.  I'll see what I can come up with over the next couple days.

**Comment by snschune** [comment]
This is still in progress after several months. When will this be completed?
