### ISSUE TITLE
Implement Gaussian Process Surrogate Modeling 

### ISSUE THREAD

**Issue by iwhalvic** [idaholab/moose#15482]
Implement Gaussian Process Surrogate Modeling  

## Reason
Gaussian Process modeling can provide a fairly flexible tool for QoI prediction based on previously collected data. This fits in well with the purpose of surrogates within MOOSE’s stochastic toolbox. 

A desirable aspect GP modeling has is the ability to provide a prediction of the uncertainty in the returned value.

## Design
Basic Gaussian Process implementation using user-specified hyper-parameters and user selectable kernels (covariance functions).

The implementation should allow for new kernel functions to be implemented fairly rapidly should a user wish for a function not provided by default.

The implementation should anticipate near-future development in which the hyper-parameters are automatically “tuned”.

## Impact
Enhancement should be contained within the existing surrogate framework, and not significantly modify the function of the basic framework used by other surrogates.

Given that GP’s provide not only a predicted value(mean) but also a measure of uncertainty, special handling for the uncertainty may be necessary in the vector post-processors typically used with surrogate modeling. Still, no adverse impact on existing surrogate models should occur.

**Comment by iwhalvic** [comment]
TODO: The existing Surrogate model lacks an `initialize()` equivalent function. This could be helpful is there is some initial data to be computed or more complex setup of data stored by the training object. Thic cannot be accomplished in the constructor as the data may not yet be available.

In the GaussianProcess this would be helpful for computing the Cholesky decomposition of the covariance matrix. 

This could be done in the trainer, but could be complex object to data-store/data-load. Doable though. This will likely be pursued if we do not wish to have an initialize equivalent for surrogates.  

At the time of this comment a decomposition is being calculated for each evaluation. 

Requires a larger discussion around surrogate framework.

**Comment by zachmprince** [comment]
Initial implementation complete. Will open new issues for enhancements.
