### ISSUE TITLE
Enhancement of new eigenvalue solver

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#15513]
## Reason

The new eigenvalue solver has delivered most of the capabilities required by Griffin. However, some features still need to be enhanced.

1) Better support of Picard iteration. `Eigenvalue`  should be able to work as either a mater app or a sub-app. See details https://github.com/idaholab/moose/issues/12767

2) The `Eigenvalue` should be able to start from a given initial solution. It is useful for depletion calculations.  See details https://github.com/idaholab/moose/issues/12767

Closes #12767

3) Output eigenvalue after solve. I want to output a regular eigenvalue in console, but I would also add one option to allow users to output the inverse of eigenvalue. Nuetroinic community always wants to see the inverse of eigenvalue. Closes #14292

4) It is better to make the residual monitors (Nonlinear |R| and Linear |R| ) consistent with those of the regular nonlinear solver. 

5) Add short cuts: `PJFNK`, `JFNK`.  Some users may like to use the new eigenvalue solver via old input file options.

6) Autoscaling in the new solvers. Closes #15048

## Design

Need to refactor SLEPc again, and add more interfaces to hook up monitors.

## Impact
Make griffin better

**Comment by fdkong** [comment]
@YaqiWang, @zachmprince The list is complete? Do you guys have anything to add?

**Comment by YaqiWang** [comment]
Thanks @fdkong . Yes the list is almost complete except missing one #15048. One big thing is that I'd like the free power iteration part in PJFNK to reside in executioner init. I remembered I made a comment before but forgot the exact reason why I wanted that. It is probably related with #12767.

**Comment by YaqiWang** [comment]
One small suggestion is to try to convert one Griffin input and see if something can still be improved during working on this. I will give feedbacks and provide review comments for sure. Thanks again!

**Comment by fdkong** [comment]
> One big thing is that I'd like the free power iteration part in PJFNK to reside in executioner init.

I do not understand this part. Could you explain it a bit? And why you need it?
