### ISSUE TITLE
Error ParsedFunction is supplied a non-linear Variable

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#15523]
## Reason

I common mistake is to use a nonlinear variable name in the 'vars', 'vals' inputs. If a non-linear variable is supplied MOOSE should provide a message explaining that it can't be done.

## Design

Check the 'vals' parameter against the known nonlinear variables, error if it is found.

## Impact

This will provide better error messages for users.

**Comment by socratesgorilla** [comment]
Can start working on this, but I need more information on what files to look at, and where to go to fix the problem.

**Comment by aeslaughter** [comment]
https://github.com/idaholab/moose/blob/next/framework/src/functions/MooseParsedFunctionBase.C

In the loop starting on 41 the "var" should be checked if it is a variable, if it is provide an error message. Use _pfb_feproblem member of this class to call for the check. There should be a function in FEProblemBase to call to make the check, hasVariable or something similar. I will let you dig that up, don't want to give you all the answers. 😄

**Comment by socratesgorilla** [comment]
Worked on this while going through all my old assigned issues. 

It looks like the capability to handle non-linear variables was added, as adding this check just breaks a bunch of tests. Recommend closing both the issue and the PR if no objections @permcody
