### ISSUE TITLE
Adding Reduced Basis surrogate modeling capabilities with Proper Orthogonal Decomposition. 

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#15538]
## Reason
To have an intrusive surrogate modeling technique in the stochastic tools module. POD-RB is getting more and more popular in the surrogate modeling community. This method would allow users to employ POD-RB surrogates for parameterized steady-state linear PDEs with affine parameter dependence. 

## Design
This would involve creating two new Transfer objects to move solution vectors and residuals between sub-applications and a Trainer object. Moreover, a new MultiApp, Trainer and Surrogate object will be created as well. 

## Impact
It will add entirely new content, at this point no modifications are envisioned to the already existing code.

**Comment by zachmprince** [comment]
Initial implementation complete. Will open new ones for more features and enhancements
