### ISSUE TITLE
Add mean-zero-pressure approach for a pure Dirichlet INS problem

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#15549]
## Reason

For a pure Dirichlet INS problem, current approach is to specific a single value of pressure at some point on the boundary. For some cases, this approach would introduce undesirable oscillation to the velocity field. To overcome this issue, a global "mean-zero pressure" approach is supposed to work better.  

## Design

The "mean-zero pressure" approach uses a Lagrangian multiplier to enforce the integral of pressure to be zero. MOOSE already has implemented ``ScalarLagrangeMultiplier`` and ``PostprocessorCED`` that can be used here. Those two kernels are currently in a test folder and will be moved to framework folder with some necessary modifications. 

## Impact

New feature for INS.

**Comment by lindsayad** [comment]
@jiangwen84 can correct me if I'm wrong, but I believe this was closed by #15570
