### ISSUE TITLE
PorousFlowPolyLineSink auto point generation

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#15547]
## Reason
It would be nice if, when creating a PorousFlowPolyLineSink object, that we could automatically generate a point for each element the desired line sink/source passed through - instead of having to manually add points to a file.  This would help with parameter sweeps we are doing with some geothermal porous flow work (using the `falcon` app) in addition to just being generally convenient.

## Design
We could just use the existing ray-tracing utils to do this.  I have a prototype that seems to work - adding a point at the midpoint of each line segment chopped by the cell faces the line passes through.  Would @WilkAndy be interested/okay with this sort of functionality being added?

## Impact
Shouldn't affect existing APIs

**Comment by WilkAndy** [comment]
That would be very beneficial (provided it works with adaptivity).  I actually don't find it a problem having a gazillion points in a file, since my files are generated by python, !!!! HOWEVER !!!!  i'm pretty sure that there is an ancient bug somewhere in MOOSE or PorousFlow which means that an incorrect Jacobian is produced if you have too many points (see #10471)

**Comment by rwcarlsen** [comment]
What happens currently with adaptivity?

**Comment by WilkAndy** [comment]
Users must ensure there are enough points in the file so that an element always has a point

**Comment by rwcarlsen** [comment]
The easy approach would be to let users just tell us how many points to stick in each cell.  The harder one would be to dynamically adjust the number of points when the mesh changes.  At least for an initial swing, I'd say just have a parameter that allows users to specify how many points to stick in each cell.  We could even make it required with no default to force them to consider the issue.

**Comment by rwcarlsen** [comment]
Well - we could make it required if they try to use the single-point/line-direction approach.

**Comment by WilkAndy** [comment]
In practice, i can't see why you'd want more than 1 point per ele.  The element size is setting your resolution and i think you're fooling yourself if you think that by shoving more points in an ele you're gaining lots more resolution.

**Comment by rwcarlsen** [comment]
The points per elem would be to handle adaptivity.  Users could over-specify the point density to ensure 1 point per element in the face of expected refinement levels during simulation.

**Comment by WilkAndy** [comment]
Yea, ok.  It'd be nicer if the points could be refined during mesh refinement, especially because of the jacobian problem when there are too many points per ele, but if that's not possible too bad.

**Comment by rwcarlsen** [comment]
Okay - I think I've got an implementation that handles mesh adaptivity automatically.  As soon as I come up with a good test for it, I'll put up a PR.

**Comment by WilkAndy** [comment]
Oh cool, thanks @rwcarlsen 

a
