### ISSUE TITLE
Add percentile stats and example for confidence level interval calculation

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#15564]
## Reason

The Statistics VPP should include the ability to gather percentile information from the supplied vectors to help quantify the distribution of the supplied data. With this an example that explains the statistics and associated confidence level calculations should be added to avoid confusion.

## Design

The Statistics should include new options for computing percentiles of data and an example will be created that demonstrates it use. The demonstration should include numerous runs with increasing number of samples and show how the confidence intervals on the compute statistics narrow with the number of samples.

## Impact

New capability and documentation

**Comment by zachmprince** [comment]
This has been addressed
