### ISSUE TITLE
Enhance hit substitution to allow for composited parameter values

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15579]
## Reason
```
ad_prefix=''

[Materials]
  [provider]
    type = ${ad_prefix}DerivativeMaterialInterfaceTestProvider
    block = 0
  []
[]
```

It would be cool if the above piece would work. Then I could add `cli_args = 'ad_prefix=AD'` in the `tests` file and get an AD version of the test "for free". 

## Design
Whatever @rwcarlsen thinks is best :-). 

## Impact
Added capability

**Comment by dschwen** [comment]
FYI, currently this results in 

```
*** ERROR ***
/Users/schwd/Programs/moose/test/tests/materials/derivative_material_interface/const.i:17: expected '=' after parameter name 'DerivativeMaterialInterfaceTestProvider', got '
'
```

**Comment by dschwen** [comment]
So it looks like the bracket substitution `${ad_prefix}` is not merged with the string that follows. Instead it is taken as a separate token and the `DerivativeMaterialInterfaceTestProvider` is taken to be the next parameter name.

Maybe the solution is to add a `${concat strA strB ..}` operator...

**Comment by rwcarlsen** [comment]
This should work if you put it in string quotes.

**Comment by rwcarlsen** [comment]
Like this: `type = '${ad_prefix}DerivativeMaterialInterfaceTestProvider'`

**Comment by rwcarlsen** [comment]
ping @dschwen?
