### ISSUE TITLE
Remove solid_mechanics module

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#15575]
## Reason
I'm surprised that we don't have an issue dedicated to this. There have been many issues related to migrating specific features in solid_mechanics to tensor_mechanics. Now that the functionality of solid_mechanics has been completely migrated to tensor_mechanics (with the exception of the UMAT interface, which will be handled separately), we're ready to remove the solid_mechanics module.

## Design
Remove the solid_mechanics module, as well as all tests that use it. Also, update any references in the documentation that point to it.

## Impact
This will break any apps that depend on solid_mechanics, but we have gone through an extensive process to remove that dependency.

**Comment by bwspenc** [comment]
By the way, the publicized removal date is July 31, 2020

**Comment by sapitts** [comment]
@bwspenc can we close this issue?

**Comment by bwspenc** [comment]
YES!!!
