### ISSUE TITLE
Geochemistry: make moles/kgwater = 55.5 instead of 55.51

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15603]
## Reason

55.5 is the exact number used by Geochemists Workbench.  For accurate benchmark comparisons, we should use the same value.

## Design

change in `GeochemistryConstants.h`

**Comment by dschwen** [comment]
This reminds me of https://en.wikipedia.org/wiki/Indiana_Pi_Bill :-D

**Comment by WilkAndy** [comment]
Heheheh.  Also, i'm pretty sure that i'm going to have to set ln(10) = 2.303 :-)
