### ISSUE TITLE
Hit: chained fparse expressions don't work when the dependency is quoted

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#15638]
## Bug Description

Chained fparse brace expressions die with an error when the one depended on by another is quoted.

## Steps to Reproduce
Put:

```
foo = '${fparse 42}'
bar = ${fparse foo}'
```

in an input file.  It will error out on `bar`'s line saying that foo has the wrong type (not float).

## Impact
Fix it.  It won't break anything.  It will only make people happier.

**Comment by dschwen** [comment]
Looks like this is not fixed. I'll provide a minimal example.

**Comment by dschwen** [comment]
My bad!
