### ISSUE TITLE
Enhance ExternalPetscSolverTestApp to take both petsc and moose input files

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#15647]
## Reason

There are several indigents in `ExternalPetscSolverApp` to handle specific Petsc coupling, while `ExternalPetscSolverTestApp` is a regular moose app so that it can not take a particular petsc input file.

## Design

Derive `ExternalPetscSolverTestApp` from `ExternalPetscSolverApp` instead of MooseApp.  Then `ExternalPetscSolverTestApp` will be able to handle input files of moose and petsc.

## Impact
None

**Comment by mangerij** [comment]
2020 mvc (most valuable coder) nomination to @alindsay for most activating the GitHub traffic this year

On Jul 23, 2020 1:53 AM, Alex Lindsay <notifications@github.com> wrote:

*Message sent from a system outside of UConn.*


Closed #15647<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidaholab%2Fmoose%2Fissues%2F15647&data=02%7C01%7Cjohn.mangeri%40uconn.edu%7C110ef3aa2a3f40d307d308d82e9a5cc6%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637310587798328958&sdata=S7drDLD6SZRhMPC0TQ5YOfHViWic2x0MWtpQkkCUS10%3D&reserved=0> via #15648<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fidaholab%2Fmoose%2Fpull%2F15648&data=02%7C01%7Cjohn.mangeri%40uconn.edu%7C110ef3aa2a3f40d307d308d82e9a5cc6%7C17f1a87e2a254eaab9df9d439034b080%7C0%7C0%7C637310587798338946&sdata=chk0aYxfVg8K%2Fm1a0DUJFS2CeHSiLuDa6AcanXgoFzQ%3D&reserved=0>.
