### ISSUE TITLE
Filter faces in ParsedGenerateSideset by neighbor subdomain id as well

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#15651]
## Reason

`ParsedGenerateSideset` is my go-to when there is no easy way to add sidesets. The only thing it can't 
do is filter by the neighboring subdomain id like `SidesetBetweenBlocks`.

## Design

Add another parameter to this object that allows to specify the included neighboring subdomain ids.

## Impact

Optional parameter that is ignored if not provided.

However, I would like to hear opinions if I am pushing it a bit too far with `ParsedGenerateSideset`.
It has so many parameters now that it rivals `IterationAdaptiveDT`.

**Comment by dschwen** [comment]
It's an egglaying woolmilkpig!
