### ISSUE TITLE
Single mesh and equation system for displaced calculations

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#15660]
## Reason
We do a whole lot of gymnastics to keep reference-displaced mesh and equation-system objects in sync, and the whole process is quite brittle as @fdkong is discovering. For example, take this fairly straightforward case: We are using a `DistributedMesh` and then we perform exodus output. Guess what happens? We serialize the reference mesh, while the displaced mesh stays distributed. Now one can argue that after serialization and exodus output, the reference mesh should be re-distributed, and that's a valid argument, but this just goes to show how easy it is for the objects to get out of sync.

## Design
I'm sure there are things I'm not thinking of, but I would simply execute all reference-mesh based objects, displace the mesh, execute all displaced-mesh base objects, undisplace the mesh. Off the top of my head, I would imagine this would double our warehouse count.

But just imagine for things like adaptivity, we wouldn't have to worry about doing things like undisplacing the displaced mesh copy in order to make sure that things like Hilbert keys are identical!

## Impact
Make the interactions between reference and displaced much less brittle. No need to ever sync meshes or solutions. No more double copies of all variables, Assembly, MooseMesh, EquationSystems, and no need for `DisplacedSystem`. Sounds awesome to me.

**Comment by fdkong** [comment]
It is a great idea for me. It is just so hard to sync them correctly

**Comment by lindsayad** [comment]
Closing in favor of libmesh/libmesh#2661
