### ISSUE TITLE
Geochemistry: transport

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15668]
## Reason

Implement transport in geochemistry

## Design

I'm seeking comments from @cpgr , @hsheldon , @rpodgorney , @loganharbour .    First off, let me say i really want to keep the transport *simple*.  I do not want to be solving for pressure or temperature distributions: i'm assuming that they will be given by an "external agent" (which will eventually be PorousFlow, hopefully).  I do not want to implement super advanced stabilisation algorithms.  The functionality is supposed to be for nice-and-easy reactive transport solves, as we can use PorousFlow for more complicated things.

The equations are discussed at https://mooseframework.org/modules/geochemistry/transport.html .  See the block of equations near the bottom of the page.

There are three terms: the time derivative, the advection via Darcy and the dispersion.

Here are my opinions:

- The bulk concentrations, C, and the "involved in transport" bulk concentrations, C_T will be Variables
- We need to do some numerical stabilisation because otherwise we'll certainly get negative concentrations for virtually any Darcy velocity.  I suggest mass lumping with full upwinding since it's the easiest, and is well studied in PorousFlow.  In this case:
- The time derivative needs to be fully lumped, which is easy except for the blasted porosity.  In principal it depends on the element and it depends on the node.  I suggest using an ElementUserObject to provide porosity at each node, given an element.  This is probably more robust than PorousFlow's "nodal" Material method.  Most users will just supply the ElementUserObject with a fixed porosity, perhaps block-restricted, but i suppose some users could supply a monomial AuxVariable to define porosity.   Or perhaps we should just keep it much simpler: porosity is just a constant monomial variable!   I'm sort of leaning towards this latter idea.  Any comments?
- The advection via Darcy usually needs to be fully upwinded, because the mobility is different for each node, but in this case mobility is constant, woohoo.  Darcy velocity can be a  specified monomial AuxVariable (eg, coming from a previous or concurrent PorousFlow solve using PorousFlowDarcyVelocityAux) or maybe a specified material property (perhaps default to `PorousFlow_darcy_velocity_qp`).  At the moment I'm not sure what happens if someone puts a crazy Darcy velocity that causes one node to "run out of fluid" - perhaps that's too bad - the geochemistry ractions will probably just crash, just like other geochem codes, but this is a minor point.  Mainly i'm looking for comments on the Darcy AuxVariable or Material idea.
- The dispersion needs no special consideration, except for the jolly porosity again.  I'm actually just tempted to average the porosity within an element, since dispersion is always poorly constrained anyway, so minor things like porosity being different at the nodes is not going to be a big deal.  Even better maybe: we could just use MatDiffusion and expect the user to provide a material property that is porosity * dispersion.  Comments?

I'll start working on this pretty soon (hopefully tomorrow).

**Comment by WilkAndy** [comment]
Thinking overnight on this one: porosity, Darcy velocity and dispersion should be AuxVariables (constant monomials).  It's the simplest thing.  Anything fancier should be handled by PorousFlow instead.

**Comment by rpodgorney** [comment]
Agreed.

Robert Podgorney, PhD, PG
Lead, Geothermal and Fossil Energy
Energy and Environment Division
Idaho National Laboratory

Office: 208-526-1524<tel:208-526-1524>
Cell: 208-520-9361<tel:208-520-9361>
email: robert.podgorney@inl.gov<mailto:robert.podgorney@inl.gov>

-sent from my mobile device, please excuse any typos or autocorrect errors

Statement of Confidentiality
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.


On Jul 28, 2020, at 15:36, Andy Wilkins <notifications@github.com> wrote:

﻿

Thinking overnight on this one: porosity, Darcy velocity and dispersion should be AuxVariables (constant monomials). It's the simplest thing. Anything fancier should be handled by PorousFlow instead.

**Comment by cpgr** [comment]
I also think you should make this as simple as possible - you don't want to have to reproduce any of the complicated porous flow transport. 

Why don't you want porosity, diffusivity etc to be normal material properties rather than aux vars?

**Comment by WilkAndy** [comment]
@cpgr : we could certainly use materials rather than aux.  I'm leaning towards aux because

- they seem to be clearer to users, ie you name an AuxVariable "porosity" and know what you're doing, rather than using a Material that you just hope provides the right property (or look in the C file to see its property name).  On the other hand, probably a GenericConstantMaterial or FunctionMaterial would overcome this because you actually name your material property.

- i think it's easy to read AuxVariables from exodus files, which people might do.  Eg, they know their injection scheme, so run a porous-flow sim to give Darcy + porosity + temperature, and then these stay fixed when doing various geochem studies.  Might as well run the porous-flow sim once, and read the results into the geochem sims

- i've been mucking around with MultiApps - running a porousflow sim, transferring stuff to a geochem sim, and it just seems easier with AuxVariables.

- Nicer for visualisation

I'm happy for you to convince me otherwise!!

**Comment by cpgr** [comment]
All good points, was just curious! Is the multi-app to do operator splitting? Seems like a neat way to achieve it.

**Comment by WilkAndy** [comment]
Notes for Andy:

- Reactor has to know about porosity and nodal volume in order to transfer between concentration changes, mole changes and mass fluxes.  Or, should the Reactor just work on mole numbers, and be fed the correct info by something else?  Latter idea is probably better for existing unit testing, but obviously need an I/O interface to users who will work in concentration variables.  Also, latter is better because when porosity changes (in PorousFlow sims) then PorousFlow will automatically compute the mass flux, and this can easily be fed to the Reactor (if the Reactor worked in concentration variables it'd have to undo the PorousFlow calculation, uggh).  One disadvantage here is that if porosity changes in a purely `geochemistry` simulation then it is assumed the DarcyVelocity will redistribute the fluid correctly - i think that users who create such complicated models will probably understand this.
- Something needs to supply or accept the "transported" concentrations Variables.
- Time derivative Kernel should just involve the "transported" concentration Variable at present.  Later, when doing fully coupled (not operator split) can add another Kernel that involves changes in the "non-transported" Variable.
- save_in for Time derivative Kernel is AuxVariable that is rate for chemistry

**Comment by WilkAndy** [comment]
@cpgr - yea, the MultiApp is *SO COOL*.  I just setup a prototype PorousFlow + geochemistry simulation using operator splitting and it all seems to work!!!   `PorousFlow` calculates all the advection, diffusion, dispersion, temperature evolution, etc, and `geochem` does the chemistry.  Oh my goodness, it's pretty easy.  There's a fair amount of work to do before this is user friendly, but it's nice to have the end-goal in sight.

**Comment by WilkAndy** [comment]
Oh my goodness, it's so nice to be coding in MOOSE-land now, writing things like:
```
Real
GeochemistryTimeDerivative::computeQpResidual()
{
  return _test[_i][_qp] * _porosity[_qp] * _nodal_u_dot[_i];
}
```

**Comment by hsheldon** [comment]
That all sounds excellent, MultiApp seems to be really powerful and exactly what’s needed here. Agree with using AuxVars rather than materials for porosity etc, they are much more user friendly.

Re. stabilisation, I suspect full upwinding will be too diffusive in some (many?) cases. What do other geochem codes do about this I wonder?

Heather.

**Comment by WilkAndy** [comment]
My current implementation can use full upwinding or no upwinding - i don't really want to be more sophisticated.  As far as i can see, other geochem codes use explicit timestepping with no numerical stabilisation or other tricks.  I wonder whether, in their heart-of-hearts, geochemists treat transport as "fancy icing on the cake which shouldn't be treated too seriously".

a

**Comment by WilkAndy** [comment]
Geochem as described above is done
