### ISSUE TITLE
framework: ConservativeAdvection velocity to VectorVariableValue

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15683]
## Reason

Currently the ConservativeAdvection Kernel accepts a RealVectorValue for the advective velocity.  I want to enhance this to a coupledVectorValue, because this is exactly advection in the `geochemistry` module (issue #15668).  Then i don't have to copy-and-paste the entire ConservativeAdvection into the geochemistry module!

## Design

Just change `RealVectorValue _velocity;` to `const VectorVariableValue & _velocity;` in ConservativeAdvection.h and similar changes in the C file

## Impact

Ability for `geochemistry` module users to use ConservativeAdvection instead of me creating something that's almost identical.

OK, @loganharbour ?

**Comment by loganharbour** [comment]
Sounds good to me!
