### ISSUE TITLE
Using `use_displaced_mesh` in TensorMechanics/Master with `generate_outputs` causes a segfault

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#15716]
## Bug Description
If the `TensorMechanics/Master` Action is used, and a user sets `use_displaced_mesh` and `generate_outputs`, the model will segfault. I assume that is because `use_displaced_mesh` is getting passed into something with `applyParameters() when it shouldn't.

I think the fix here is to just suppress `use_displaced_mesh` in the TM/Master input block, because the user shouldn't need to set it.

## Steps to Reproduce
See above. Set up a model with `TensorMechanics/Master`, `use_displaced_mesh`, and `generate_outputs`. Also, this only appears to occur if a `NeumannBC` is used as well.

## Impact
This is mostly an annoyance. We just need to guard against setting `use_displaced_mesh`.

**Comment by dewenyushu** [comment]
Thanks, Ben! 

However, I think the issue partly comes from how the BCs are handled: if I do not have NeumannBC, then I can set `use_displaced_mesh ` and `generate_outputs ` together without an issue

**Comment by bwspenc** [comment]
I guess I need to add that little bit on how to get the error.
Regardless, we should never be setting `use_displaced_mesh` in the TM/Master action.

**Comment by dewenyushu** [comment]
> I guess I need to add that little bit on how to get the error.
> Regardless, we should never be setting `use_displaced_mesh` in the TM/Master action.

Thanks Ben! I am wondering under what circumstances should I set `use_displaced_mesh=true`? I had the impression that this should apply for large deformations but it seems like I have been wrong about this

**Comment by bwspenc** [comment]
If you're using the TM/Master action, you should never set it for any material models. Determining where you should set it is kind of confusing, and that was one of the primary motivations for creating that action. It should never be set for material models, but should be set for the Kernels if you're using finite strain.

With the TM/Master action, you can just set strain=FINITE and generally not worry about it, except that you would want to set it for other Kernels you might add (like Gravity, or maybe a heat conduction kernel).

**Comment by dewenyushu** [comment]
> If you're using the TM/Master action, you should never set it for any material models. Determining where you should set it is kind of confusing, and that was one of the primary motivations for creating that action. It should never be set for material models, but should be set for the Kernels if you're using finite strain.
> 
> With the TM/Master action, you can just set strain=FINITE and generally not worry about it, except that you would want to set it for other Kernels you might add (like Gravity, or maybe a heat conduction kernel).

This makes sense. Thanks Ben!
