### ISSUE TITLE
MooseDocs fails with Python 3.8

### ISSUE THREAD

**Issue by srinath-chakravarthy** [idaholab/moose#15763]
## Bug Description
When trying to generate local documentation. moosedocs.py generates files with no content, because of "RuntimeError: dictionary keys changed during iteration"

## Steps to Reproduce
Run ./moosedocs.py with Python version > 3.8

**Comment by cticenhour** [comment]
MOOSE (and dependencies) support for Python 3.8 was addressed as part of #17106. Closing this PR.
