### ISSUE TITLE
Update PETSc installation documentation

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#15764]
## Reason

PETSc submodule is used as our default PETSc, and some PETSc installation instructions are out-of-date.

## Design

Use the update-and-rebuild-petsc script to install PETSc. This is able to unify some instructions.

## Impact
None

**Comment by fdkong** [comment]
This is also related to #15057

**Comment by milljm** [comment]
This can be closed. We have centralized the build/install process of PETSc to a single script; `./update_and_rebuild_petsc.sh`, for the following use-case scenarios:

- Users
- Conda Packages
- HPC Binaries
- Spack buildfarm
