### ISSUE TITLE
Segfault in mechanical contact with first order variables  in a second order mesh

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#15761]
## Bug Description

In tensor mechanics there is a check for consistency between the order of the displacement variables and the order of the mesh. This check produced a useful error message when the displacements are FIRST order and the mesh is SECOND order. However, this check is bypassed when using the TM action and the parameter `add_variables = true`. Eventually, in a case that has contact a segfault is encountered as soon as mechanical contact is established for one of the midside nodes in a QUAD8. 

## Steps to Reproduce

I have attached 3 input files with extension changed to .txt to be able to add to the issue. In input file TM_kernel.i I use the `TensorMechanics` kernel and set the variables in the `Variables` block. This fails immediately when using modules-opt with the useful error:

`Error: mesh has SECOND order elements, so all displacement variables must be SECOND order.`

In the second input file TM_action_add_variables_false.i I use the TM action to setup the strain calculator but I still set the variables in the `Variables` in the variables block. This fails with the same error above. In TM_action_add_variables_true.i I use the TM action to set the variables the simulation runs fine and by passes this check because in the TM action we have this check for setting the displacements:

```
    const bool second = _problem->mesh().hasSecondOrderElements();

    params.set<MooseEnum>("order") = second ? "SECOND" : "FIRST";
    params.set<MooseEnum>("family") = "LAGRANGE";
```
Therefore in this third case we end up having temperature as a first order lagrange variable with 2nd order displacements. Eventually you get the following stack trace from a debug run of the 3rd problem. 

```
Assertion `comp < this->n_comp(s,var)' failed.
comp = 0
this->n_comp(s,var) = 0

Stack frames: 36
0: 0   libmesh_dbg.0.dylib                 0x00000001210f7d9c libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 460
1: 1   libmesh_dbg.0.dylib                 0x00000001210eec1a libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) + 218
2: 2   libcontact-dbg.0.dylib              0x000000010e6b9793 libMesh::DofObject::dof_number(unsigned int, unsigned int, unsigned int) const + 1587
3: 3   libcontact-dbg.0.dylib              0x000000010e712dd8 MechanicalContactConstraint::nodalArea(PenetrationInfo&) + 104
4: 4   libcontact-dbg.0.dylib              0x000000010e71254a MechanicalContactConstraint::computeContactForce(PenetrationInfo*, bool) + 12122
5: 5   libcontact-dbg.0.dylib              0x000000010e70f4b4 MechanicalContactConstraint::shouldApply() + 244
6: 6   libmoose-dbg.0.dylib                0x0000000114acd4e4 NonlinearSystemBase::constraintResiduals(libMesh::NumericVector<double>&, bool) + 1412
7: 7   libmoose-dbg.0.dylib                0x0000000114ac9a7c NonlinearSystemBase::computeResidualInternal(std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 4348
8: 8   libmoose-dbg.0.dylib                0x0000000114ac8423 NonlinearSystemBase::computeResidualTags(std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 627
9: 9   libmoose-dbg.0.dylib                0x00000001143adaba FEProblemBase::computeResidualTags(std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 2346
10: 10  libmoose-dbg.0.dylib                0x00000001143acc06 FEProblemBase::computeResidualInternal(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 230
11: 11  libmoose-dbg.0.dylib                0x00000001143ac86c FEProblemBase::computeResidual(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&) + 252
12: 12  libmoose-dbg.0.dylib                0x00000001143ac676 FEProblemBase::computeResidualSys(libMesh::NonlinearImplicitSystem&, libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&) + 102
13: 13  libmoose-dbg.0.dylib                0x0000000114ab223e ComputeResidualFunctor::residual(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, libMesh::NonlinearImplicitSystem&) + 94
14: 14  libmesh_dbg.0.dylib                 0x0000000121cc6450 libmesh_petsc_snes_residual + 1648
15: 15  libpetsc.3.12.dylib                 0x0000000125798751 SNESComputeFunction + 337
16: 16  libpetsc.3.12.dylib                 0x000000012578cc11 SNESLineSearchApply_Basic + 385
17: 17  libpetsc.3.12.dylib                 0x000000012578eabc SNESLineSearchApply + 284
18: 18  libpetsc.3.12.dylib                 0x000000012576d0d3 SNESSolve_NEWTONLS + 2147
19: 19  libpetsc.3.12.dylib                 0x000000012579f76a SNESSolve + 1770
20: 20  libmesh_dbg.0.dylib                 0x0000000121cc5abf libMesh::PetscNonlinearSolver<double>::solve(libMesh::SparseMatrix<double>&, libMesh::NumericVector<double>&, libMesh::NumericVector<double>&, double, unsigned int) + 3535
21: 21  libmesh_dbg.0.dylib                 0x0000000121d5afd4 libMesh::NonlinearImplicitSystem::solve() + 596
22: 22  libmoose-dbg.0.dylib                0x0000000114d0349d TimeIntegrator::solve() + 45
23: 23  libmoose-dbg.0.dylib                0x0000000114abe448 NonlinearSystem::solve() + 1016
24: 24  libmoose-dbg.0.dylib                0x00000001143aa276 FEProblemBase::solve() + 374
25: 25  libmoose-dbg.0.dylib                0x0000000113e8c9e4 FEProblemSolve::solve() + 36
26: 26  libmoose-dbg.0.dylib                0x0000000113e92893 PicardSolve::solveStep(double, double&, double, double&, bool, std::__1::set<unsigned int, std::__1::less<unsigned int>, std::__1::allocator<unsigned int> > const&) + 1619
27: 27  libmoose-dbg.0.dylib                0x0000000113e90d07 PicardSolve::solve() + 3687
28: 28  libmoose-dbg.0.dylib                0x00000001148d200c TimeStepper::step() + 44
29: 29  libmoose-dbg.0.dylib                0x0000000113e98c70 Transient::takeStep(double) + 288
30: 30  libmoose-dbg.0.dylib                0x0000000113e9837b Transient::execute() + 171
31: 31  libmoose-dbg.0.dylib                0x0000000115023e98 MooseApp::executeExecutioner() + 232
32: 32  libmoose-dbg.0.dylib                0x0000000115024ddf MooseApp::run() + 335
33: 33  bison-dbg                           0x000000010c931c66 main + 342
34: 34  libdyld.dylib                       0x00007fff5b42a3d5 start + 1
35: 35  ???                                 0x0000000000000003 0x0 + 3
```

It looks like with mechanical contact all variables temperature AND displacements should be the same order as the mesh. I've also verified if you take example 1 or example 2 and explicitly set 
```
    order = SECOND
    family = LAGRANGE
```
in the displacement variables and leave  temperature as a FIRST order it will run and hit the same same segfault above with the same stack trace. 

## Impact

Annoyance where you forget to change the order of your variables to SECOND for a second order mesh. There are physics were you can mixed order variables so if you try to do that with contact applications segfaults are likely.
[TM_action_add_variables_true.txt](https://github.com/idaholab/moose/files/5066048/TM_action_add_variables_true.txt)
[TM_action_add_variables_false.txt](https://github.com/idaholab/moose/files/5066050/TM_action_add_variables_false.txt)
[TM_Kernel.txt](https://github.com/idaholab/moose/files/5066051/TM_Kernel.txt)

**Comment by gambka** [comment]
@dewenyushu @dschwen @bwspenc @jiangwen84

**Comment by dschwen** [comment]
This looks unrelated to the tensor mechanics action. A check in the contact
action is what's required here.

**Comment by gambka** [comment]
That is probably the case.  I was only able to reliably reproduce the segfault in contact while when using tensor mechanics (obviously since it is required for mechanical contact). As you said is it simply adding a similar check that is for the displacements on the temperature variable order.  However, I had a discussion with @jiangwen84 and says he usually a l lot of mixed formulations in terms of variable order on a 2nd order mesh. Perhaps he wants to use contact in those applications in the future and something else needs to be done. 

For my applications the simple check on temperature would suffice.

**Comment by dschwen** [comment]
Yes, next level world be actually making this work.

**Comment by bwspenc** [comment]
I think the displacements have to be the same order as the mesh. If you're using other variables with different orders, that's probably OK because contact isn't touching them.
I agree this is a good idea. I think we should just remove the `order` parameter from contact, and have it set it to the mesh order automatically (and make sure that's the order of the displacement variables).

**Comment by gambka** [comment]
@bwspenc I must have been clear in my description in the third example when you use the TM action it automatically creates the second order displacement variables.  The issue is that temperature remains first order and I think temperature is used in the off-diagonal contributions even in mechanical contact (correct me if I'm wrong) and you get the segfault if you set the temperature to also be 2nd order it works fine.  There is already the error check to ensure that the displacements have the same order of the mesh, I see that error when using one of the first 2 input files I described.

**Comment by gambka** [comment]
After talking with @bwspenc some more about this, we should be able to support contact with higher order displacements and a lower order temperature. However, the inclusion of order = FIRST in the GlobalParams sets the order parameter in the ContactAction itself as well as for the temperature variable and the segfault is not coming from the temperature being lower order but rather the order in the ContactAction should be the same as the mesh order and displacements. We have the error check to check that the displacements are of the correct order, we should probably set the order parameter in Contact itself based upon the mesh order like we do in the tensor mechanics action.
