### ISSUE TITLE
Add GenericRealArgument<is_ad> type

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15828]
## Reason
Passing in `Real` values into functions by value is the standard thing to do, while for complex aggregate types the standard is to pass by `const &`.

## Design
`GenericRealArgument<is_ad>` would be similar to `GenericReal<is_ad>` except the `is_ad = true` case would resolve to a type reference typedef rather than a value type.

## Impact
Better function parameter typing.

**Comment by friedmud** [comment]
My view: all modern compilers compile passing simple things as const reference to the same thing as passing by value: so just always pass by const reference if it's ever possible to get something large coming in as an argument.

Loooking for proof...

I found this: https://stackoverflow.com/a/49523201

Which points here: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

**Comment by lindsayad** [comment]
Yea, I'd note no on this

**Comment by dschwen** [comment]
ok
