### ISSUE TITLE
Hit format breaks hand formatted multiline strings

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15879]
## Reason
`hit format` the automatic HIT formatting tool unbeautifies hand formatted multiline strings, the likes of which are frequentty used to make multicolumn data more readable in input files.

```
  [./youngs_modulus]
    type = PiecewiseLinearInterpolationMaterial
    xy_data = '0          10e+6
               599.9999   10e+6
               600        9.94e+6
               99900      10e3'
    property = youngs_modulus
    variable = temp
  [../]
```

is turned into

```
  [youngs_modulus]
    type = PiecewiseLinearInterpolationMaterial
    xy_data = '0          10e+6
               599.9999   10e+6
               600        9.94e+6
   '
              '            99900      10e3'
    property = youngs_modulus
    variable = temp
  []
```

(from `moose/modules/combined/test/tests/thermo_mech/youngs_modulus_function_temp.i`)

Formatting will look worse for longer multiline strings.

## Design
Either
* Do not change multiline strings (this might lead to inconsistent indenting after the first line, but this can easily be manually adjusted)
* Keep line breaks and adjust the amount of space after the linebreak to maintain consistent indenting (gold star solution)
* introduce `# hit-format off` and `# hit-format on` tags analogous to clang-format (again potentially causing indentation inconsistencies that would have to be ajusted manually)

The main objective would be to have a solution that is stable w.r.t. repeated formatting and does not hurt the readability of the inputs (all three approaches satisfy this).

## Impact
Make `hit format` non-pessimizing. This issue is a blocker for blanket application of `hit format` to our input file base.

@rwcarlsen we chatted about this a month ago on Slack. Putting up an issue to keep track of this.

**Comment by rwcarlsen** [comment]
I think the conclusion I came to after looking in to this a bit was that hit-format should basically just ignore multiline strings - because there isn't really anything reasonable we can do to handle the in-string newlines while reflowing any of the text.

**Comment by dschwen** [comment]
I may have opened a duplicate of #15797 here...

**Comment by rwcarlsen** [comment]
Yes - these are indeed duplicates - and it seems I reached the same conclusion/solution-approach in both cases :D
