### ISSUE TITLE
Make INSAD work with multiple fluid domains

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#15884]
## Reason
@fdkong is working on a dry cask simulation in which we wants model fluid flow in a room and the cask separately.

## Design
Get rid of the `static` design of the `INSADObjectTracker`. Think of an intelligent way to add single `INSADObjectTracker` objects per block and be able to retrieve that per-block tracker even from sidesets which border the block. May even require adding the user object to the input file and then explicitly adding a user object name parameter to the objects that use the `INSADObjectTracker`

## Impact
Enable multi-block fluid simulations with INSAD.

**Comment by fdkong** [comment]
Cool!
