### ISSUE TITLE
Create a tagged version

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#15908]
## Reason

Hi @permcody , Do you think you could create a tagged version of "master" as it currently stands?  We are trying to publish our PorousFlow work in Journal of Open Source Software, and they would like a tagged version (Eg v1.0.1) to be archived.    Is this a problem for you?

andy

## Design

Create a tagged version of MOOSE

## Impact

Allow archiving and paper publication.

**Comment by WilkAndy** [comment]
Hey anyone (@andrsd , @loganharbour , ...) - any comments on this?

**Comment by loganharbour** [comment]
Yes, we can. Is most recent hash acceptable?

**Comment by WilkAndy** [comment]
Yep, that's be great, thank @loganharbour

**Comment by WilkAndy** [comment]
Just reminding you about this @loganharbour

**Comment by WilkAndy** [comment]
Reminding you about the tag, @loganharbour

**Comment by loganharbour** [comment]
Good to go @WilkAndy!

https://github.com/idaholab/moose/releases/tag/snapshot-20-10-27

Close if this works for you, please.

**Comment by WilkAndy** [comment]
Perfect, thank you @loganharbour
