### ISSUE TITLE
Allow applications to register custom stress/strain names in the Tensor MechanicsAction

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15926]
## Reason
In blackbear we use the NEML library for constitutive models. It's glue code uses the general material property name `inelastic_strain` (as it can capture creep, plasticity, etc. of the combination of multiple such effects). This material property name is not utilized in MOOSE at all, so adding it to the list of potential outputs seems inappropriate. Yet it would be convenient to have it in blackbear.

## Design
Make the list of available stress/strain names non-const static and protected and add a public static `registerOutput` method to the action. This would permit app developers to put e.g.
```
TensorMechanicsActionBase::registerOutput("inelastic_strain");
```
to make `inelastic_strain` available.

## Impact
Added capability.

**Comment by srinath-chakravarthy** [comment]
What is inelastic_stress ?? Have not come across such a definition

**Comment by dschwen** [comment]
Sigh... that was copy paste nonsense.

**Comment by srinath-chakravarthy** [comment]
Sorry for the curt message, but hit send before I typed the rest of it.
Meant to also say that I completely attest this. I would personally like
such a system. Would it be available to arbitrary things other than strain
type terms ?

Cheers
Srinath
