### ISSUE TITLE
Correctly handle HTML special character codes in MooseDocs

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#15927]
## Bug Description

HTML codes do not render correctly with MooseDocs.

## Steps to Reproduce

Place one of the following into a markdown file and render with MooseDocs

```
Sch&auml;dle

Sch&#228;dle
```

## Impact

Limits the flexibility of documentation. The correct fix is to add an extension for handling special characters. An extension is preferred to allow for testing, the ability to enable/disable the behavior, and to add to if needed in the future.

**Comment by zachmprince** [comment]
@aeslaughter not sure this is relevant. But I noticed when having characters like `<` in input parameter descriptions, it doesn't render properly. This is specifically relevant for the C++ type in parameter drop down. See [CartesianMeshGenerator](https://www.mooseframework.org/source/meshgenerators/CartesianMeshGenerator.html) as an example. I'm guessing we will need to detect escape characters in the parameter token.

**Comment by aeslaughter** [comment]
@zachmprince I will see if I can fix that as well. I will add it to the associated PR idaholab#15927.

**Comment by aeslaughter** [comment]
closed by  #15928
