### ISSUE TITLE
Migrate all necessary pages from old website

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#15932]
## Reason

After many years the old website should go away. All pages that are needed should be moved to the new site.
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/

## Design

Review the old website, if a page is needed migrate it to the new system.

## Impact

Reduces our need to maintain two sites and improves current documentation.

**Comment by jessecarterMOOSE** [comment]
Some of the phase field topics [here](https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/PhaseField/) are not on the new site. I have found the discussion on units, polynomial two phase energies, mechanics, and the tutorial helpful.

**Comment by WilkAndy** [comment]
I couldn't find the following pages on the new website (many of these contain lots of pictures too).  Probably these can be put under a new page: "benchmarking rock-mechanics plasticity models"

https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/ReturnMap/
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/CTO/
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/WeakPlaneTensile/
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/WeakPlaneShear/
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/Tensile/
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/MC/
https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/DP/

Also, the following page, that should be included in the new website:

https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/TensorMechanicsBasics/PoroMechanics/

This page just contains some links to 4 PDF documents, but i think the PDF documents and the page should be ported to the new website:

https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/Richards/

**Comment by WilkAndy** [comment]
These may be in the new website, but i couldn't find them.  I think they're useful

https://ec2-52-88-120-143.us-west-2.compute.amazonaws.com/wiki/PhysicsModules/TensorMechanics/Identities/

**Comment by WilkAndy** [comment]
When you opened this issue @aeslaughter , i thought you were offering to do the migration.  But given that there are no PRs referencing this issue, i suspect you wanted me to do the migration.  I'm just checking that the migration never happened (i can't find the above doco on the new site).

**Comment by aeslaughter** [comment]
I have not done the migration and was hoping people familiar with the content would do it, since I am sure much has changed from the content on the old wiki.

**Comment by aeslaughter** [comment]
I think this ship has sailed.
