### ISSUE TITLE
Better handling of mesh preparedness in MeshGenerators

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#15945]
## Reason
As see in #15937 , it is possible for `MeshGenerator` objects to leave the mesh in an unprepared state.  This is a _feature_ .  The reason why is that not every `MeshGenerator` needs a fully prepared mesh to operate... and extraneous `prepare_for_use()` calls are something to be avoided (we've actually worked REALLY hard to remove them from the framework over the years because it's so expensive).  However, leaving the mesh unprepared can lead to segfaults and incorrect behavior in later `MeshGenerators` that are relying on the mesh to be prepared.  Therefore, we need a better way to track the state of the mesh.

## Design
I propose that we add a bit of metadata to `MeshGenerators` so that the `MeshGenerator` system can know what each one needs.  We can do that by adding a private param:

`requires_prepared_meshes`: A `MeshGenerator` will set this to true if that MeshGenerator requires that the mesh be prepared before running.

We will also need a `MeshBase::set_isnt_prepared()` that allows `MeshGenerators` to mark the mesh as not prepared (this approach and name came from a discussion with @roystgnr )

With these two things in place it will be possible for the `MeshGenerator` system itself to call `prepare_for_use()` _before_ calling a `MeshGenerator` if that is necessary.  It will also allow calling `prepare_for_use()` at the end if it hasn't been done already.

## Impact
Lots of things using and depending on `MeshGenerator`s - this will hopefully make them more robust.

**Comment by lindsayad** [comment]
It would be nice to consolidate this with #14329

**Comment by friedmud** [comment]
@lindsayad @roystgnr was against `is_prepared(bool)` because it should only really be "prepared" by calling `prepare_for_use()`... so having `set_isnt_prepared()` instead will help keep this straight.

I agree with removing `_is_prepared` related stuff in `MooseMesh`

Also: thanks for digging up that older ticket - there is some good info on there too... especially about Ghosting... that's going to be a tough one to solve.  Let's take this first step though.

**Comment by lindsayad** [comment]
> `set_isnt_prepared()` instead will help keep this straight

That sounds good to me

**Comment by lindsayad** [comment]
Closing in favor of #14329
