### ISSUE TITLE
Single tick in comment

### ISSUE THREAD

**Issue by mooseframework** [idaholab/moose#1597]
ParseGetPot.py failed to correctly parse this input file from 
5161092ae3baa24764756d4eb96d13087bf6e47a_moose/tests/pump_test/Isothermal_Pump_Reverse_test.i 15565
[ global_init_P = 1.e5
  global_init_V = 0.1       #Important, don't change it
  global_init_T = 300.

  #2=2 eqn, 1D isothermal flow
  #3=3 eqn, 1D non-isothermal flow
  #7=7 eqn, 1D 2-phase flow
  model_type = 2
# supg = 'false'

(GlobalParams]
)

The problem seems to be that it found the ' in the comment, and tried to find the matching one.

**Comment by permcody** [comment]
Need to reinvestigate this - it may be fixed.

**Comment by permcody** [comment]
While this is still an issue, while we are planning on consolidating parsers rather than fixing this issue. It is duplicated several times. Referencing this ticket:
#8365
