### ISSUE TITLE
Programmatic heap profiling

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#15990]
## Reason
We support generating CPU profiles for every process through the environment variable `MOOSE_PROFILE_BASE`. We should allow something similar for heap profiling

## Design
I was hoping I could just duplicate what's done for CPU profiling by adding appropriate calls to `HeapProfilerStart` and `HeaProfilerStop` but while I'm told at the top of a simulation that heap profiling has started, no files are ever written.

## Impact
Allow easy heap profiling like we have for CPU profiling (which is awesome).

**Comment by lindsayad** [comment]
@rwcarlsen just so you're aware. Not assigning you in case I have time to delve into this before you get to it

**Comment by fdkong** [comment]
OK. I will add a PR for this
