### ISSUE TITLE
Add getZeroMatrialProperty that returns a static zero property and does not create a named property

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#15993]
## Reason
`getZeroMatrialProperty` (and its AD and generic variants) take a property name. They return a property reference that is zero _unless_ a material declares a property with the given name and populates it with a value. Effectively this provides an optional material property will be set to zero if it is not provided by any material.

Sometimes, however, in certain input parameter combinations we do not want a material property but simply want to point a property reference to a constant always zero value.

Currently some developers try to achieve this by passing _dummy names_ to this method. This is dangerous as there is no guarantee that the dummy name wont exist in the future with a non zero property value.

## Design
I propose an overload of `getZeroMatrialProperty` (and its AD and generic variants) that does not take a property name argument.

## Impact
Added capability.

**Comment by tophmatthews** [comment]
"some developers"  😬

**Comment by dschwen** [comment]
Ay 🐕 ...

`getGenericZeroMaterialProperty` provided to Materials beghaves differently from `getGenericZeroMaterialProperty` provided to all other systems. If you call it from a Kernel, you always get zero back! No matter whether the property exists or not.

That method was added for derivative parsed materials, and was never intended to be used directly by developers. But here we are. In `getDefaultmaterialProperty` I actually check if the property exists and only return the zero property if it does not. 

I will move that check into `MaterialPropertyInterface::getGenericZeroMaterialProperty` to make the behavior more consistent! Yeah... something never felt 100% right about this design...

**Comment by tophmatthews** [comment]
Yeah, also I was thinking `_porosity(_use_current_porosity ? &getADMaterialProperty<Real>("porosity") : nullptr),` doesn't seem too terrible, and results in less run-time memory, right?

**Comment by dschwen** [comment]
no, not right. The zero property would return a reference to a static object. Same memory requirement as a pointer.

**Comment by dschwen** [comment]
the question is really how often will you want a value of zero in your equation for that missing material property, vs. checking a pointer and doing a completely different calculation. Maybe in some cases you want 1 (or the identity tensor) as a standin for a non-existing / unused property.

**Comment by tophmatthews** [comment]
That is true too, and maybe a one property could help there.

Where I often use it is when I want to use a current or old material property value. For non-AD, it's very easy since they're the same basic structures. For AD, the current value is full of ADReals, while the old value is Reals.

**Comment by tophmatthews** [comment]
I don't think the nullptr is a bad way though. I'm trying to find where I've used Zero property in the past, but can't really find many cases...

**Comment by dschwen** [comment]
Closed by #16000
