### ISSUE TITLE
Let MOOSE support chain rules on Jacobian evaluation

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#16002]
## Reason
I should have created this issue long ago. More and more I am feeling the pain when adding new kernels with the proper evaluation of the Jacobian.

I am having a kernel depending on a material property depending on aux variables depending on primal variables. All the dependencies are not complicated but passing the necessary information into the kernel for evaluating the Jacobian properly is difficult and hard to manage because the relevant codes are scattered into aux kernels and materials. To be more specific, I illustrate this with some simple pseudo codes here:
My aux kernel:
```
Real
FooAux::computeValue()
{
  return c1 * _primal_var1[_qp] + c2 * _primal_var2[_qp];
}
```
My material:
```
void
FooMaterial::computeQpProperties()
{
  _prop[_qp] = _aux_var1[_qp] * b1 + _aux_var2[_qp] * b2;
}
```
where aux var1 and aux var2 are evaluated with the `FooAux` with different coefficients.

My kernel
```
Real
FooKernel::computeQpResidual()
{
  return _test[_i][_qp] * _prop[_qp];
}
```
The real situation is more complicated but these pseudo code can already reveal the issue. We have rightful reasons to set up the kernel in this way, i.e. we do not want everything to be in the kernel otherwise we will not have this issue.

To properly have the `FooKernel::computeQpOffDiagJacobian(unsigned int jvar)`, I have to pass all coefficients in and the required primal variables for evaluating the aux variables.

## Design
I know we have `ADKernel` can automate the evaluation of Jacobian and material property derivatives. But both are not ideal for my case. `ADKernel` may introduce noticeable impact on the residual evaluation, whose performance is critical to my applications. I used material property derivatives although did not practice much on it, but have a feeling that bookkeeping is tedious and it only solves part of the problem.

I am proposing a new feature in MOOSE to let MOOSE support chain rules on Jacobian evaluation in `AuxKernel` and `Material`. If, for example, we have N aux variables and M primal variables, we maintain a N*M dense matrix possibly in `AuxiliarySystem` and have a `AuxKernel::computeQpDerivative(MooseVariableFEBase & jvar)`  and a `Couplable::coupledDerivative(const VariableName & var, unsigned int comp)`.
My aux kernel would be:
```
_primal_var1_deri(coupledDerivative("primal_var1")), // Note: if var1 is primal, this will return trivial values
_primal_var2_deri(coupledDerivative("primal_var2"))

Real
FooAux::computeValue()
{
  return c1 * _primal_var1[_qp] + c2 * _primal_var2[_qp];
}

Real
FooAux::computeQpDerivative(MooseVariableFEBase & jvar)
{
  return c1 * _primal_var1_deri[_qp][jvar.number()] + c2 * _primal_var2_deri[_qp][jvar.number()];
}
```
Similarly we can have `Material::declarePropertyDerivative(const MaterialPropertyName & name)` and `Material::computeQpPropertyDerivative(MooseVariableBase & jvar)`.
My material:
```
_prop_deriv(declarePropertyDerivative<Real>("name")),
_aux_var1_deri(coupledDerivative("aux_var1"))
_aux_var2_deri(coupledDerivative("aux_var2"))

void
FooMaterial::computeQpProperties()
{
  _prop[_qp] = _aux_var1[_qp] * b1 + _aux_var2[_qp] * b2;
}

void
FooMaterial::computeQpPropertyDerivative()
{
 // _i is the index maintained in Material::computePropertyDerivative() like
// for (unsigned int _i; _i < [number of primal vars]; ++_i)
//   call computeQpPropertyDerivative()
  _prop_deri[_qp][_i] = _aux_var1_deriv[_qp][_i] * b1 + _aux_var2_deriv[_qp][_i] * b2;
}
```
In this way, in my kernel,
```
_prop_deri(getMaterialPropertyDerivative<Real>("prop_name"))

Real
FooKernel::computeQpResidual()
{
  return _test[_i][_qp] * _prop[_qp];
}

Real
FooKernel::computeQpOffDiagJacobian(unsigned int jnumber)
{
  return _test[_i][_qp] * _prop_deri[_qp][jnumber] * _phi[_j][_qp];
}
```

The relevant evaluations are still distributed in materials, aux kernels. This feature will provide an alternative to the developers on the existing capabilities without the issues I mentioned earlier. I do not want to say this initially: We can have the similar thing in `UserObject` including post-processors.

## Impact
Make the Jacobian evaluation easier to manage.

**Comment by YaqiWang** [comment]
Since I am kind of desperate on needing this, I am willing to add this feature in MOOSE. It should not take me much long time. But of course I need to get the good-to-go first.

**Comment by dschwen** [comment]
We literally already have declarePropertyDerivative! As I said, please take a few minutes before you implement stuff that already exists it collide with existing APIs.

**Comment by YaqiWang** [comment]
I am not saying this requires reimplementing `declarePropertyDerivative`, just to make the idea complete. It will be in a detailed implementation.

**Comment by lindsayad** [comment]
It is sad that we had this problem completely solved before we removed the templating of `ADKernel`

**Comment by dschwen** [comment]
Just to bring back templating with `is_ad` ... :rofl:

**Comment by tophmatthews** [comment]
We made a move away from aux to materials a year or so back in Bison for similar reasons. I forget the exact math, but the gist was that you interpolate twice going from primal to aux to primal (qp to node to qp), where material properties allow you to stay on the qp all the time. I try to only use Aux for output and for variable replacement for testing/simplification. I'd be curious to hear if you require aux's.

If everything is in material property space, trying out AD is relatively painless with the new templating for kernels and materials now. I do notice speed hits with certain systems, especially PJFNK. For example, solving all temperature dependence is the same time AD/Reg with PJFNK, but tensor mechanics is much, much slower with PJFNK due to the Rank four and Rank two tensors floating around. Easily tested though.

Beyond AD, I would also second the derivative methods developed for materials though. I use the system heavily our cluster dynamics code Centipede, and it is an elegant solution to the problem. If you can take analytical derivatives, that is probably the way to go.

**Comment by YaqiWang** [comment]
I have relatively strong opinion on this. Residual evaluation is already pretty slow to us, we cannot take any performance hit anymore. I do not have urgent need on this because we found few ugly short-cuts. In the future, I want to add something if I get time. I am not expecting this would be a huge amount of work more than a week. Basically we just need to maintain a two-dimensional array in size of number of material properties times the number of primal variables. Users can get the reference through `getMaterialPropertyDerivative`, which can be accessed though `_prop[var_number][qp]`. Material property derivative is what I really need. I do not need to support aux kernels even though we can do the similar thing for auxiliary variables on qps only.
