### ISSUE TITLE
Enhance anisotropic material model support in TensorMechanics

### ISSUE THREAD

**Issue by recuero** [idaholab/moose#16016]
## Reason
Augmented capabilities. Needed for the analysis of structural materials in nuclear engineering applications.
- [X] Finite strain anisotropic elasticity
- [X] Anisotropic creep model (Hill tensor-based)
- [X] Hill tensor anisotropic plasticity
- [X] Hill tensor anisotropic elasto-plasticity
- [X] Anisotropic creep can be used in combination with other anisotropic creep classes with *isotropic* parameters
- [X] Automatic time stepping based on creep rate numerical integration error 
- [x] Hill parameters can change as a function of variables (temperature)
- [x] Hill parameters can be rotated by the user to accommodate component orientation
- [x] Hill parameters can be rotated due to rotation of large strain kinematics

## Design
Finite strain elastic stress class will be augmented to capture anisotropy. 
Anisotropic creep and plasticity behaviors will grant its own generalized return mapping class hierarchy that handles a return to a yield surface based on stress tensor components. Algorithm probably based on:

Versino, D, Bennett, KC. Generalized radial‐return mapping algorithm for anisotropic von Mises plasticity framed in material eigenspace. Int J Numer Methods Eng. 2018; 116: 202– 222. https://doi.org/10.1002/nme.5921

## Impact
Enable the simulation of more accurate material models.

**Comment by dschwen** [comment]
Example for using Eigen with `ADReal`:

```
#include "ADReal.h"

#include <Eigen/Core>
#include <Eigen/Eigenvalues>

namespace Eigen
{
namespace internal
{
template <>
struct cast_impl<ADReal, int>
{
  static inline int run(const ADReal & x) { return static_cast<int>(MetaPhysicL::raw_value(x)); }
};
} // namespace internal
} // namespace Eigen

int main()
{
  typedef Eigen::Matrix<ADReal, 6, 6, Eigen::DontAlign> StiffnessMatrix;

  StiffnessMatrix X = StiffnessMatrix::Random(5, 5);
  StiffnessMatrix A = X + X.transpose();

  std::cout << "Here is a random symmetric matrix, A:" << std::endl << A << std::endl;
  X = StiffnessMatrix::Random(5, 5);
  StiffnessMatrix B = X * X.transpose();
  std::cout << "and a random postive-definite matrix, B:" << std::endl
            << B << std::endl
            << std::endl;

  Eigen::GeneralizedSelfAdjointEigenSolver<StiffnessMatrix> es(A, B);
  std::cout << "The eigenvalues of the pencil (A,B) are:" << std::endl
            << es.eigenvalues() << std::endl;
  std::cout << "The matrix of eigenvectors, V, is:" << std::endl
            << es.eigenvectors() << std::endl
            << std::endl;

  auto lambda = es.eigenvalues()[0];
  std::cout << "Consider the first eigenvalue, lambda = " << lambda << std::endl;
  auto v = es.eigenvectors().col(0);
  std::cout << "If v is the corresponding eigenvector, then A * v = " << std::endl
            << A * v << std::endl;
  std::cout << "... and lambda * B * v = " << std::endl << lambda * B * v << std::endl << std::endl;

  return 0;
}
```

The caveat here is that you must avoid decompositions that use complex numbers. I.e. the example above requires a symmetric matrix.
