### ISSUE TITLE
levelset multi material system

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#16046]
## Reason

Currently we have LevelSetBiMaterial classes for switching between two sides of a levelset.
More general cases exist where we want to switch among regions defined by multiple levesets.

## Design

Create a LevelSetMultiMaterial system.

## Impact

This should replace the existing bi-material system.

**Comment by aeslaughter** [comment]
I have done something similar to this in MASTODON, you might want to check that implementation out. It is a bit more generic in that it works with any number of values, but it also becomes more complicated.

https://github.com/idaholab/mastodon/blob/devel/include/materials/LayeredMaterialInterface.h

**Comment by hugary1995** [comment]
Thanks @aeslaughter this is helpful.

**Comment by hugary1995** [comment]
closed by #17042
