### ISSUE TITLE
FV: Indicators not working

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#16069]
## Bug Description
Adaptivity indicators are not working with finite volume variables. Including an indicator results in `*** ERROR ***
unordered_map::at: key not found`. 

## Steps to Reproduce
Simply add an indicator to one of the FV tests.

## Impact
Can't use indicator-based mesh adaptivity using FV variables.

**Comment by cpgr** [comment]
Hey @lindsayad, I'll have a go at this while you guys are watching the election, but if it gets too hard I might have to ask for help.

FYI @sci-sjj

**Comment by lindsayad** [comment]
Sounds good!
