### ISSUE TITLE
LAGRANGE_VEC not supported by nodal aux kernels, even though it should be

### ISSUE THREAD

**Issue by gridley** [idaholab/moose#16076]
## Bug Description
See discussion in #15776 

## Steps to Reproduce
Discussed in #15776

## Impact
Impacts any nodal aux kernel on LAGRANGE_VEC variables. This is not used in the framework at the moment, but it should be able to do this. E.g., taking the magnitude of a LAGRANGE_VEC vector in an aux kernel does not work right now.

**Comment by aeslaughter** [comment]
@lindsayad You might be interested
