### ISSUE TITLE
Modules code coverage does not include unit tests

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#16084]
## Bug Description

The modules code coverage, for instance as reported at https://mooseframework.inl.gov/docs/coverage/geochemistry/ , does not include the unit tests.

## Steps to Reproduce

Look at https://mooseframework.inl.gov/docs/coverage/geochemistry/src/utils/GeochemistryActivityCalculators.C.gcov.html and you'll see that `log10ActCoeffDHBdotAlternative` is apparently not covered.   However, the function does appear in `unit/src/GeochemistryActivityCalculatorsTest.C`

## Impact

This is not super urgent, but i require the code coverage to be correctly reported for quality-assurance purposes, and to inform me personally of deficiencies in my testing.  If it could be fixed in the next fortnight or so i'd very very appreciative :-)

**Comment by WilkAndy** [comment]
Hi @aeslaughter , is extending the code coverage to the unit tests a big task?  In a couple of weeks i'm giving a presentation to managers and would like to quantify my code coverage.

**Comment by aeslaughter** [comment]
> is extending the code coverage to the unit tests a big task?

I am not sure, it is not something I have ever run. Perhaps @milljm would know more.

**Comment by loganharbour** [comment]
This should be in civet shortly. will test it in a moment.

**Comment by loganharbour** [comment]
Also refs #15422

**Comment by WilkAndy** [comment]
This has been fixed, yippee, thanks @loganharbour
