### ISSUE TITLE
Make global AD indexing with sparse container MOOSE default config

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#16091]
## Reason
Pros:
- Much simpler code
- Much lower chance of accidentally creating slow code because if you try to do a bunch of `DualNumber` math with an unseeded sparse container, you don't take much of a performance hit. You can see #16089 for an example of why nonsparse containers are a pain
- Much more flexible code. You can build residuals depending on totally arbitrary nonlinear degrees of freedom and track it with ease
- Maintain speed over a broad class of physics and dimensionality. It's nice to able to do a 3D Navier-Stokes calculation and a 1D diffusion calculation with the same binary and not see a penalty in performance in the 1D calculation

Cons:
- Maybe it's slower sometimes? Someone has yet to show me a concrete example of this, however.

## Design
It's already done. Just have to change `MooseDefaultConfig.h`. I'm going to give users some time to give feedback before making this change. If I see enough concrete examples of global-sparse AD being slow relative to local-nonsparse AD, then I won't make the change. ***Unless that happens, however, I'm planning to make the change in January.***

An important note is that even if we change to global-sparse as the default config, nonsparse isn't going to disappear as a configure option, at least not for the foreseeable future and not without proper deprecation warnings (they would be compiler-time warnings).

## Impact
I think I would probably spend a lot less time doing AD maintenance in a framework that was global-sparse-AD based. For example I've sunk a half-day into #16089 which I wouldn't have if we lived in a world of global-sparse-AD. Also if we were to one day deprecate the nonsparse code, our AD code base would get much simpler and it would be easier to do AD development. Moreover, I think it would positively impact users for the reasons mentioned above.

**Comment by lindsayad** [comment]
I'm going to give users some time to give feedback before making this change. If I see enough concrete examples of global-sparse AD being slow relative to local-nonsparse AD, then I won't make the change. Unless that happens, however, I'm planning to make the change in January.

An important note is that even if we change to global-sparse as the default config, nonsparse isn't going to disappear as a configure option, at least not for the foreseeable future and not without proper deprecation warnings (they would be compiler-time warnings).

**Comment by veeshy** [comment]
Very cool! Any examples of the non local jac usage alluded to in https://github.com/idaholab/moose/issues/15732? I’m guessing in FV somewhere?

**Comment by lindsayad** [comment]
It may not be appropriate to call it nonlocal, but yes gradient reconstruction in FV uses neighbors of neighbors, which is a larger stencil than any of our previous FE objects.
