### ISSUE TITLE
Newsletter about Google groups, Linking more tutorials to Getting Started, and minor Tutorial 1 edits

### ISSUE THREAD

**Issue by crswong888** [idaholab/moose#16096]
## Reason
I want to kill a few birds with one stone here. First, the website needs to be updated to reflect our recent move to GitHub discussions. Also, there is also a few tutorials and example sets that could be linked in Getting Started. Finally, there are some minor typos to fix in the new tutorial.

## Design
I shall created a newsletter blurb about the move to GitHub discussions and also update the "Join the Community" section in Getting Started (it looks like help/contact has already been updated). I also will link in the phase field tutorial and the examples for the stochastic tools and level set modules to "Examples and Tutorials".

## Impact
Improved documentation.

**Comment by cticenhour** [comment]
If you want to add to the newsletter, could you add that bit of it under #16071?
