### ISSUE TITLE
Getting lots of errors from moosedocs.py

### ISSUE THREAD

**Issue by herter4171** [idaholab/moose#16093]
## Bug Description

@aeslaughter, for context, this is basically my email `Trouble Building Docs` verbatim.

I’ve been having a rough time trying to build documentation for KP’s BISON.  Russell says it works fine on his machine, but I can’t seem to get any variant of container/non-container and standard/non-standard submodule locations to behave.  In the file `playbook.txt` (real extension is `*.yml`, but GitHub wouldn't let me upload with it), you can see that I’m trying to create a non-container install on Amazon Linux 2 (`yum` package manager) that matches the standard/expected pathing with the Git submodules to rule out any funny business from either of those variables.
 
For that vanilla run, I used the following command, and the output is in `vanilla.log`.
 ```
python3 doc/moosedocs.py build 2>&1 | tee vanilla.log
 ```

Of greater interest is to us is containerized Ubuntu.  I used the command below, and the output is in `container.log`.
 ```
./doc/moosedocs.py build 2>&1 | tee container.log
```
Files I mentioned:
* [playbook.txt](https://github.com/idaholab/moose/files/5497698/playbook.txt)
* [container.log](https://github.com/idaholab/moose/files/5497692/container.log)
* [vanilla.log](https://github.com/idaholab/moose/files/5497695/vanilla.log)

## Steps to Reproduce

I'm not sure if you folks use Ansible at all, but tweaking the playbook for your platform, running it, and trying to build docs seems like a decent approach.  The issue should also manifest in one of the MOOSE Docker images that KP publishes publicly, e.g. `herter4171/ubuntu-moose:latest`, and you can see how those images get built in the `docker_ci` directory of MOOSE with `Jenkinsfile` running the show using `Dockerfile`.

## Impact

We need to figure out the right way to build with `moosedocs.py` to have docs at the ready for SQA purposes, along with supporting end-users with hosted docs as we ramp up production activities over the coming months.  I would hope to see this resolved this quarter, because I'm a bit on the hook for it internally.

**Comment by aeslaughter** [comment]
Try to run the commands from within the doc directory.

```
cd doc
./moosbuild.py build
```

**Comment by herter4171** [comment]
Hey @aeslaughter, thanks for the suggestion.  I still get the same behavior running in `doc`.
* Container
  * `./moosedocs.py build 2>&1 | tee container_2.log`
  * [container_2.log](https://github.com/idaholab/moose/files/5512191/container_2.log)
* Non-container
  * `python3 moosedocs.py build 2>&1 | tee vanilla_2.log`
  * [vanilla_2.log](https://github.com/idaholab/moose/files/5512193/vanilla_2.log)

**Comment by aeslaughter** [comment]
Is this just regular Bison or a custom application that uses Bison? All your errors are from missing files, so your content is incomplete. If you have a separate application you need to make sure that the doc/config.yml has all the desired locations listed in the [Content] section. 

Also, depending on how the application is setup: to use a submodule or not of Bison will make a difference. You might need to extend moosedocs.py to setup BISON_DIR environment variable. This variable can then be used in the config.yml [Contents] section to make sure it pulls from either location (submodule or not).

**Comment by herter4171** [comment]
Context is our internal repo for BISON.  I just pulled down the latest INL code and ran with INL BISON using default submodule paths like the vanilla runs before, and I'm still getting the same behavior.
* `python3 moosedocs.py build 2>&1 | tee vanilla_3.log`
* [vanilla_3.log](https://github.com/idaholab/moose/files/5513263/vanilla_3.log)

Shouldn't that have worked out of the box?  I don't have a clue as to what I'm missing here.

**Comment by aeslaughter** [comment]
Here are some things to try out:

1. Try setting BISON_DIR environment variable. 
2. Run build with --dump and make sure the bib files are listed
3. Run build with --disable MooseDocs.extensions.bibtex, see if it runs without the bibtex extension
4. What version of pybtex are you using? conda list should give you this information. I have the following
    ```
    pybtex                    0.22.2           py37hc8dfbb8_2    conda-forge
   ```

**Comment by aeslaughter** [comment]
I am thinking the version of pybtex is the problem. The first error that shows up happens up front and is preventing the database from being populated, thus all the entries get. It seems they just release ver. 0.23, which probably changed some behavior. I am going to try this out.

**Comment by herter4171** [comment]
Good call on `pybtex`.  I down-graded from 0.23 to 0.22.2, and I got zero critical and zero errors on the vanilla setup with INL BISON without setting `BISON_DIR`.

For vanilla with KP-Bison, I ran with
```
BISON_DIR=/home/ec2-user/KP-Bison python3 moosedocs.py build 2>&1 | tee vanilla_4.log
```
and got one error.  It looks like something still expects `bison` as the top repo directory in spite of `BISON_DIR` ([vanilla_4.log](https://github.com/idaholab/moose/files/5513768/vanilla_4.log)).

In our containers, the basic environment is as follows.
```
MOOSE_DIR=/opt/moose
LIBMESH_DIR=/usr/local
BISON_DIR=/opt/KP-Bison
PETSC_DIR=/usr/local
```

We've been using this arrangement for years now, but something is still getting tripped up in the docs.  92 errors is a lot less than before, at least ([container_4.log](https://github.com/idaholab/moose/files/5513797/container_4.log)).

**Comment by aeslaughter** [comment]
> It looks like something still expects `bison` as the top repo directory in spite of `BISON_DIR` ([vanilla_4.log](https://github.com/idaholab/moose/files/5513768/vanilla_4.log)).

The bison directory is hard-coded into this listing, it shouldn't have "bison" in the path. You will need to make a PR into Bison to fix this.
```
!listing bison/assessment/metallic_fuel/FFTF/IFR1/analysis/IFR1.i   
```

**Comment by herter4171** [comment]
Just talked to Russell, and it's a known error that he's going to fix.  Container issues are still a mystery.

**Comment by aeslaughter** [comment]
The container errors seem to be from missing images/movies. You probably just need to perform a `git submodule update --init large_media` in the MOOSE repo

**Comment by herter4171** [comment]
Beautiful.  Thanks for the pointers.  Everything is looking good on my end.
