### ISSUE TITLE
Interest in keeping Windows 7 as an option

### ISSUE THREAD

**Issue by steinfel00physicer** [idaholab/moose#16107]
## Reason
 Windows 7 (64-bit) is more stable than Window 10.   In my opinion, Win 7 is more logical than Win 10. 

## Design
 I wish to have my question answered. I see that a Windows 10 version of MOOSE is available to install.   It it possible to install MOOSE (windows-10 version) onto a Computer which has Windows-7 rather than Windows-10 for its O.S. ?    Or is a download of a Windows-7 version of MOOSE available to install ? 

## Impact
  
 It it possible to install MOOSE (windows-10 version) onto a Computer which has Windows-7 rather than Windows-10 for its O.S. ?    Or is a download of a Windows-7 version of MOOSE available to install ?

**Comment by cticenhour** [comment]
Please limit questions to our GitHub Discussions forum. Issues are designed for feature requests or bugs. I have answered your question regarding Windows 7 compatibility in #16108. 

Closing this issue and referring future users who come across this to the linked discussions post.
