### ISSUE TITLE
Add copyright to geochemistry objects

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#16134]
## Reason
Geochemistry is missing a few copyrights for the code introduced in #15698 

## Design
Add the copyrights

## Impact
Copyrights need to be there

@WilkAndy any chance you can take care of this?

**Comment by WilkAndy** [comment]
Yep, i can do that.  Please assign to me

**Comment by loganharbour** [comment]
Done. Thank you @WilkAndy!
