### ISSUE TITLE
Minor SONDefinitionFormatter update for NEAMS input validation

### ISSUE THREAD

**Issue by brandonlangley** [idaholab/moose#16165]
## Reason

The `SONDefinitionFormatter` builds a schema from the `JsonSyntaxTree` via `--definition` for the NEAMS Workbench.

The `ExistsIn` schema rule is made of lookup paths built from a parameter's `cpp_type`  plus  `global/associated_types`.

For example, this entry in the `global/associated_types` section:

```
"VariableName": [
    "AuxVariables/*",
    "Variables/*"
]
```

indicates input of `"cpp_type": "VariableName"` must be defined in either the `[Variables]` or `[AuxVariables]` blocks.

This `ExistsIn` rule is used for two separate purposed by the NEAMS Workbench.

   1. **Input validation errors** are shown when values not defined at any of the input lookup paths

   2. **Autocompletion assistance** presents a selection list of all values defined at the input lookup paths

Often the validation (**1**) is correct, e.g., most `VariableName` parameters are defined in `[Variables]` or `[AuxVariables]`.

However, it **is** legal for input with an `ExistsIn` rule to **not** be defined - if that piece of input is never actually used.

Therefore, these `ExistsIn` paths cannot be used for input validation errors (**1**) because those could be false positives.

But, using these paths to present a list of options to the user for autocomplete assistance (**2**) is always helpful.

So instead of just removing this rule, a newly named rule holding these lookup paths can be dumped instead of `ExistsIn`.

The Workbench will then use this new rule for autocompletion assistance (**2**) but **not** input validation errors (**1**).

## Design

Only a few lines should be modified in the `SONDefinitionFormatter` changing the name of the schema rule that is output.

This will also require a minor update to the `expect_out` regex of the associated `RunApp` tests with this new rule name.

## Impact

The NEAMS workbench will continue to provide helpful autocompletion without these false validation errors in MOOSE apps.

**Comment by brandonlangley** [comment]
@permcody -

I'm planning to make this minor update soon to `SONDefinitionFormatter` for Workbench input validation of MOOSE apps.

Could you add this to the [NEAMS milestone](https://github.com/idaholab/moose/milestone/9)?

**Comment by permcody** [comment]
Done

**Comment by rwcarlsen** [comment]
I'm not completely understanding what you mean in your last few sentences:

```
However, it is legal for input with an ExistsIn rule to not be defined - if that piece of input is never actually used.
Therefore, these ExistsIn paths cannot be used for input validation errors (1) because those could be false positives.
But, using these paths to present a list of options to the user for autocomplete assistance (2) is always helpful.
So instead of just removing this rule, a newly named rule holding these lookup paths can be dumped instead of ExistsIn.
The Workbench will then use this new rule for autocompletion assistance (2) but not input validation errors (1).
```

Could you try clarifying this a bit for me?

**Comment by brandonlangley** [comment]
@rwcarlsen -

Sorry about the confusion.

For context, this goes back to a question I asked @permcody on September 19, 2019 in an email:

Question:

> ... finally, something we are seeing a lot of in MOOSE test inputs is the use of variables, functions, postprocessors, etc. that were not defined in their respective `[Variables]`, `[AuxVariables]`, `[Functions]`, `[Postprocessors]`, etc. blocks. e.g.,
> 
> ```
> {MOOSE}/test/tests/parser/parse_double_index/parse_double_index.i
> ```
> 
> ```
> [UserObjects]
>   [./double_index]
>     type = ReadDoubleIndex
>     function_name_di = 'function_name00; function_name10 ...
>     multiapp_name_di = 'multiapp_name00; multiapp_name10 ...
>     postprocessor_name_di = 'postprocessor_name00; ...
>     output_name_di = 'output_name00; output_name10 ...
>   [../]
> []
> ```
> 
> while the input definition for these parameters according to the JSON dump state that they are of these `cpp_type`s:
> 
> ```
> "std::vector<std::vector<FunctionName>>"
> 
> "std::vector<std::vector<MultiAppName>>"
> 
> "std::vector<std::vector<PostprocessorName>>"
> 
> "std::vector<std::vector<OutputName>>"
> ```
> 
> and the `global/associated_types` section of the JSON definition maps those `cpp_type`s to needing to be defined in these locations:
> 
> ```
> FunctionName      --> Functions/*
> 
> MultiAppName      --> MultiApps/*
> 
> PostprocessorName --> Postprocessors/*
> 
> OutputName        --> Outputs/*
> ```
> 
> However, none of these blocks exist in the input:
> 
> ```
> [Functions]
> 
> [MultiApps]
> 
> [Postprocessors]
> 
> [Outputs]
> ```
> 
> So, how are all of those components being used?
> 
> Is there a set of special reserved keyword names that do not have to be defined for the `global/associated_types `mapping in the JSON definition?
> 
> There are 209 cases across MOOSE test inputs that where referential lookups into the following blocks fail to validate:
> 
> ```
> [Adaptivity][Indicators]
> 
> [Adaptivity][Markers]
> 
> [AuxVariables]
> 
> [AuxVariables]
> 
> [Functions]
> 
> [MultiApps]
> 
> [Outputs]
> 
> [Postprocessors]
> 
> [Variables]
> 
> [VectorPostprocessors]
> ```

Cody's answer:

> Looks like you opened a can of worms on this one. The truth is that we’ve never enforced having those blocks because normally MOOSE would do the checks if those names were actually used (e.g. we can read the strings inside of an object all we want but we won’t error until we ask MOOSE to retrieve the object type associated with those names). You could argue that this is a poor design but it’s currently what we have. From an input validator this could be problematic as you don’t really know if the object is going to use those names or not. The best you can do is warn if a block doesn’t exist for now.

So since it seems we cannot do a hard validation error if variables, functions, postprocessors, etc. are not defined in their respective `[Variables]`, `[AuxVariables]`, `[Functions]`, `[Postprocessors]`, etc. blocks, I'm planning to open a small pull request to the `SONDefinitionFormatter.cpp` code to simply change all

```
ExistsIn=[ path/one path/two ]
```

from the the `--definition` schema dump to something like

```
InputChoices=[ PATH:path/one PATH:path/two ]
```

in then Workbench will use use this new construct for input autocomplete assistance (i.e. dropdown list of all variables, functions, postprocessors, etc. that are defined in the input) but not present the validation errors if these components are not defined - since they do not **have** to be defined if they are not actually used.

I'm hoping to open that small `SONDefinitionFormatter` pull request within the next week. Does this make more sense?

**Comment by rwcarlsen** [comment]
Sounds good.  Thanks.
