### ISSUE TITLE
Inconsistently failing PorousFlow test

### ISSUE THREAD

**Issue by smharper** [idaholab/moose#16201]
## Bug Description
The `jacobian/line_sink03.i` test will sometimes fail in CIVET.

## Steps to Reproduce
Unfortunately this bug is intermittent. Invalidating the test in CIVET will sometimes result in a success.

Perhaps this bug has something to do with the use of `-snes_type test`. [This petsc-users thread](https://lists.mcs.anl.gov/pipermail/petsc-users/2019-February/037584.html) suggests that `-snes_type test` is now outdated and should be replaced with `-snes_test_jacobian`. Even with `-snes_test_jacobian`, running the test on my local machine results in a solve that never converges.

## Impact
This results in intermittent CIVET failures on unrelated PRs.

**Comment by smharper** [comment]
@WilkAndy, it looks like you originally wrote the test. Do you have any idea why it's causing us trouble?

**Comment by WilkAndy** [comment]
The link you give above now shows all green.  I don't know why the test fails at present, but obviously i need to look into it.  I'm not suprised the simulation never converges if you don't use `test` as it was only designed to do the jacobian test.  There are hundreds (i think literally) of `-snes_type test` tests in PorousFlow, i wonder why this particularly one fails.

**Comment by smharper** [comment]
Ah darn. Yeah I invalidated the test to get it to run. If I remember correctly, the test spit out a nonlinear residual of `inf` or `nan` then failed saying the Jacobian wasn't correct.

**Comment by WilkAndy** [comment]
> Ah darn. Yeah I invalidated the test to get it to run. If I remember correctly, the test spit out a nonlinear residual of `inf` or `nan` then failed saying the Jacobian wasn't correct.

OK, that gives me something to go on, thanks.

**Comment by smharper** [comment]
Ooh, luckily I had the results visible in an old browser tab!

```
Framework Information:
MOOSE Version:           git commit dc8bdf2951 on 2020-11-14
LibMesh Version:         4f3fa5a6a2104ab8784a6519677589738b9aef6f
PETSc Version:           3.13.3
SLEPc Version:           3.13.3
Current Time:            Sat Nov 14 14:00:53 2020
Executable Timestamp:    Sat Nov 14 13:56:49 2020

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh: 
  Parallel Type:           replicated
  Mesh Dimension:          3
  Spatial Dimension:       3
  Nodes:                   
    Total:                 8
    Local:                 8
  Elems:                   
    Total:                 1
    Local:                 1
  Num Subdomains:          1
  Num Partitions:          1

Nonlinear System:
  Num DOFs:                56
  Num Local DOFs:          56
  Variables:               { "ppwater" "ppgas" "massfrac_ph0_sp0" "massfrac_ph0_sp1" "massfrac_ph1_sp0" 
                             "massfrac_ph1_sp1" "temp" } 
  Finite Element Types:    "LAGRANGE" 
  Approximation Orders:    "FIRST" 

Execution Information:
  Executioner:             Transient
  TimeStepper:             ConstantDT
  Solver Mode:             NEWTON
  PETSc Preconditioner:    bjacobi 
  MOOSE Preconditioner:    SMP


Time Step 0, time = 0

Time Step 1, time = 1, dt = 1
 0 Nonlinear |R| = inf
  ---------- Testing Jacobian -------------
  Run with -snes_test_jacobian_view and optionally -snes_test_jacobian <threshold> to show difference
    of hand-coded and finite difference Jacobian entries greater than <threshold>.
  Testing hand-coded Jacobian, if (for double precision runs) ||J - Jfd||_F/||J||_F is
    O(1.e-8), the hand-coded Jacobian is probably correct.
  ||J - Jfd||_F/||J||_F = nan., ||J - Jfd||_F = inf.
  Linear solve converged due to CONVERGED_ITS iterations 1
 1 Nonlinear |R| = inf
Nonlinear solve converged due to CONVERGED_ITS iterations 1
 Solve Converged!

Outlier Variable Residual Norms:
  ppwater: 5.325854e+01
  ppgas: 1.069374e+01
  massfrac_ph0_sp0: inf
  massfrac_ph0_sp1: inf
  massfrac_ph1_sp0: 1.287106e+00
  temp: 7.894062e-01

################################################################################
Tester failed, reason: INCORRECT JACOBIAN
```

**Comment by WilkAndy** [comment]
Thanks @smharper

**Comment by WilkAndy** [comment]
Can you assign this to me, please?

**Comment by WilkAndy** [comment]
Hi @smharper - i've modified the test.  It is a long-standing issue, unfortunately.  I added some notes into the input file to alert future-me to that fact.   Feel free to review the changes at #16259
