### ISSUE TITLE
addDeprecatedCoupledVar does not work as intended for required coupled vars

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#16204]
## Bug Description

If I use the following to deprecated the temp coupled var in favor of temperature

```
  params.addRequiredCoupledVar("temperature", "Coupled temperature");
  params.addDeprecatedCoupledVar("temp", "temperature", "December 31st, 2020");
```
It will correctly print out the deprecated parameter message, but immediately fail due to the required variable not being specified. My understanding is deprecation is meant to warn the user of impending removal of old syntax and to update, but should not cause their inputs to fail until after the deprecated syntax removal date.

## Steps to Reproduce

Attempt to deprecate any required coupled var in the approach above and see immediate failure.

## Impact

Cannot deprecate required coupled vars using the simplified above syntax as user input files will immediately fail. 

Maybe the approach is to create a `params.addDeprecatedRequiredCoupledVar`?

**Comment by gambka** [comment]
@dschwen

**Comment by dschwen** [comment]
This is a duplicate of #16175

**Comment by gambka** [comment]
I will close this one. I did not see your previous issue.

**Comment by dschwen** [comment]
There's a PR now: #16245
