### ISSUE TITLE
Output PerfGraph to JSON and/or CSV

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#16256]
## Reason
It would useful to be able to get performance graph information from a file instead of looking though a console output.

## Design
Include a `to_json` and/or `to_csv` parameter in PerfGraphOutput. Might need to add some API to PerfGraph for this.

## Impact
Easier analysis to performance results.

**Comment by aeslaughter** [comment]
@friedmud This might be of interest.

**Comment by aeslaughter** [comment]
What will be your approach. I think I want to see a PerfGraphReporter, then just implement a to_json function for the PerfGraph type.

**Comment by zachmprince** [comment]
That makes sense. So the JSONOutput would take care of handling the output?

**Comment by aeslaughter** [comment]
> That makes sense. So the JSONOutput would take care of handling the output?

Correct.
