### ISSUE TITLE
Allow negative strain timestep calculations

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#16266]
## Reason
In `RadialReturnStressUpdate`, `RadialReturnStressUpdate`, and `ADViscoplasticityStressUpdateBase`, some derivative classes may compute a negative inelastic strain. When the timestep is computed, this results in a negative time limit, which is unphysical.

## Design
Use the absolute value of the inelastic increment.

## Impact
Better options for derivative classes.

**Comment by bwspenc** [comment]
Sorry, super late to this. Why are they computing a negative inelastic strain increment?
