### ISSUE TITLE
Add JSON syntax output for the TestHarness

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#16270]
## Reason
With MOOSE syntax transitioned to JSON it would be neat to have the same output format for the TestHarness, which only offers YAML output.

## Design
Add `--json` option to `run_tests` that outputs a compatible JSON syntax.

## Impact
This will permit me to finally add autocompletion for `tests` files.

**Comment by dschwen** [comment]
Side note, the MOOSE JSON syntax output is absolutely fantastic. It has every bit of information that is needed!

**Comment by socratesgorilla** [comment]
Would like to start working on this

**Comment by socratesgorilla** [comment]
On closer inspection, it appears that not only is there not a json output, but the supposed yaml output does not actually work either. Unless instructed otherwise, I will only add the JSON functionality.

**Comment by aeslaughter** [comment]
If the YAML is broken then I would also remove it. JSON is the way to go.

**Comment by hugary1995** [comment]
![test](https://user-images.githubusercontent.com/31555204/104519070-d5930600-55c6-11eb-8b60-06d668d6d766.png)

**Comment by dschwen** [comment]
Didn't I already do this?

**Comment by dschwen** [comment]
Yeah

```
./run_tests --json
```

outputs a compatible syntax definition. What remains to be done it to support it in the VSCode plugin.

**Comment by dschwen** [comment]
See #21460

**Comment by dschwen** [comment]
My bad, I had forgotten about this issue (that I opened) and opened a new issue. I never saw your commit f299c3e... but that didn't quite solve the problem anyways. The TestHarness JSON must follow the same Schema as the MOOSE JSON to be useful.

**Comment by socratesgorilla** [comment]
Yeah I wasn't sure although I had seen you working on it so I reopened. If you got it done it's all good
