### ISSUE TITLE
gperftools can generate too many heap profiling files with large number of processors

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#16316]
## Reason
Currently we start the profiler on all processors, which can cause too many profiling files generated with large number of processors. One of my runs with about 1000 processors, generated a few hundreds of files of all processors each in size of 1MB. This exhausted my quota quickly.

## Design
We can have a parameter to profile only selected processors.

## Impact
Give users a control on the number of profiling files useful when using lots of processors.

**Comment by dschwen** [comment]
Reduce sampling rate instead!

**Comment by YaqiWang** [comment]
I am not sure how. The setting I am using is 100MB which is already pretty coarse.
