### ISSUE TITLE
Avoid creating unnecessary vectors (transient solution states) and matrices

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#16339]
## Reason
The base System classes in MOOSE should not create transient libMesh systems, instead, we should use the non-transient systems and manage the old/older/older-er states on our own so that we do not excessively create states that we do not need. In addition, we should avoid building matrices when using pure PJFNK.

## Design
Replace the use of the transient libMesh systems in things like the AuxiliarySystem and NonlinearSystem with the non-transient versions. Set basic system use only when matrices do not need to be built.

## Impact
Reduce unnecessary CPU and memory usage when they are not needed.

**Comment by lindsayad** [comment]
I plan to work on this in the next week or two as the NEAMS annual review allows. If another MOOSE team member gets to it before me, then just reassign

**Comment by loganharbour** [comment]
@lindsayad I think that for the purposes of the NEAMS project this can be renamed and closed, correct? With a separate PR made for the intended System change. We got around the matrix allocation issue with a fix from @fdkong.

**Comment by lindsayad** [comment]
Yea if you rename this to something like "Don't create unnecessary vectors/matrices", then this ticket can be closed

**Comment by loganharbour** [comment]
Closed with https://github.com/idaholab/moose/pull/16363, https://github.com/idaholab/moose/pull/16696, and https://github.com/libMesh/libmesh/pull/2832.
