### ISSUE TITLE
Avoid creating copies of vectors in ArrayKernel

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#16360]
## Reason
In ArrayKernels `computeQpResidual` returns a vector, so we need to be careful in the assembly process about creating copies. In ArrayKernel.C we have:
```
RealEigenVector residual = _JxW[_qp] * _coord[_qp] * computeQpResidual();
```
Which is creating two vectors.

## Design
Utilize RVO or move semantics to avoid creating an extra vector.

## Impact
Improving run time by avoiding allocation and deallocation.

**Comment by dschwen** [comment]
Be careful of _pessimizing moves_. How would you coax the compiler into using RVO where it isn't using it already?

**Comment by zachmprince** [comment]
Not sure what you mean by pessimizing moves. Is it not more efficient than copy assignment? I wasn't completely sure how RVO works, so I didn't want to rule out improving on that front. I will have a small PR soon, hopefully someone with more C++ skills can tell me if I'm doing something wrong.

**Comment by dschwen** [comment]
See here for example: https://stackoverflow.com/questions/62061433/how-to-avoid-the-pessimizing-move-warning-of-nrvo
