### ISSUE TITLE
Coupled variable function IC

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#16405]
## Reason
I need to set ICs for variables based on the values of other variables. An easy way would be an IC that allows me to couple in a set of (up to 4 variable) the values of which are then substituted into a moose function (into x,y,z, and t) and the function value is taken as the IC. This woudl allow me to use PiecewiseMultiLinear data to interpolate tabulated datasets.

## Design
Add IC that can couple in variables and use them to evaluate a function to determine the IC value.

## Impact
Added capability

**Comment by WilkAndy** [comment]
I really like the `depends_on` input of `MeshModifiers`.

**Comment by dschwen** [comment]
The variable coupling should determine the IC order automatically.

**Comment by dschwen** [comment]
Ok, this works great for the phase field problem I'm running. No convergence with the guessed IC for some internal DOFs that depend on the variables I'm initializing, but pretty good convergence on the first step when using a PiecewiseMultiLinear interpolation function with data tabulated from a quick run to equilibrate all internal degrees of freedom.
