### ISSUE TITLE
MultiApp transfers support array variables  

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#16429]
## Reason

Array and vector variables are used frequently in many apps and modules. It is time to support these kinds of variable in MultiApp transfers.

## Design

Refactor current field transfers  or create new transfers to take these variables. 

## Impact
Enable more applications

**Comment by GiudGiud** [comment]
Connected to #15799

**Comment by GiudGiud** [comment]
also #14445 and #9420

**Comment by GiudGiud** [comment]
Splitting off vector variables in their own issue.
