### ISSUE TITLE
Disallow nl_rel_tol looser than 1e-8 for tests

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#1643]
Throw an error if a test is trying to use an nl_rel_tol looser than 1e-8.

I'm not sure if this should be done in the test harness... or if this should be done in MOOSE (maybe turned on my a command-line switch?)... but I'm tired of tracking these down.

**Comment by permcody** [comment]
We've decided not to enforce this. Closing for now, we can always dig up Sterling's patch if we want it.
