### ISSUE TITLE
Add a soft fail capability to the Terminator UserObject

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#16452]
## Reason
Add switch to put the terminator into "stun" mode :-D. This just marks the current timestep as failed, to trigger a dt cutback and a new attempt.

## Design
Add bool parameter and call a function of FEProlem to make teh solve as failed instead of terminating the entire simulation.

## Impact
Added capability

**Comment by tophmatthews** [comment]
how is this different than exceptions? Can the stun mode be optionally turned off and on, and only checked at timestep_end?

**Comment by dschwen** [comment]
Yeah, checking at the end of a timestep is the main point. You might want to make a decision based on your converged solution whether you may have gone beyond the validity limit of your model.

**Comment by tophmatthews** [comment]
Yeah good, this is what I was thinking about with #14996 too.
