### ISSUE TITLE
tensor_mechanics AD performance

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#16465]
I have been using AD for tensor mechanics applications for quite a while, and I observe that in some cases AD is slightly slower but acceptable, but in some cases AD is ~5x slower.

We've had this discussion many times at many different places. I think it is time to sit down and look at the performance seriously. I hope this can be a good starting point for some AD performance improvements in tensor mechanics.

I put together three really simple test cases using the tensor mechanics module only.
The input files can be found at [https://github.com/hugary1995/moose/tree/AD_performance/modules/tensor_mechanics/examples/perf](https://github.com/hugary1995/moose/tree/AD_performance/modules/tensor_mechanics/examples/perf)

## Model
 
This is a 2D square domain with RZ coordinates. The bottom edge is fixed in z, and the left edge is fixed in r. The top edge is being pulled upward (on the displaced mesh). There is a nonhomogeneous eigenstrain applied on the domain.

Each of the test case uses a different constitutive law. A total small strain linear elastic model, an incremental small strain power law creep model, and an incremental finite strain power law creep model.

## Configuration

configuring with derivative backing array size of 50
configuring with AD indexing type global
configuring with derivative type sparse

>Note: local indexing + dense gave me really similar performance.

### Performance

All tests ran in serial.

<table>
 <tr>
  <td>&nbsp;</td>
  <td colspan="2">total small strain elastic</td>
  <td colspan="2">incremental small strain creep</td>
  <td colspan="2">incremental finite strain creep</td>
 </tr>
 <tr>
  <td>&nbsp;</td>
  <td>total_nl_its</td>
  <td>total_time (sec)</td>
  <td>total_nl_its</td>
  <td>total_time (sec)</td>
  <td>total_nl_its</td>
  <td>total_time (sec)</td>
 </tr>
 <tr>
  <td>non-AD</td>
  <td>26</td>
  <td>3.900</td>
  <td>78</td>
  <td>23.239</td>
  <td>95</td>
  <td>29.928</td>
 </tr>
 <tr>
  <td>AD</td>
  <td>20</td>
  <td>6.980</td>
  <td>65</td>
  <td>72.463</td>
  <td>74</td>
  <td>118.143</td>
 </tr>
</table>

**Comment by hugary1995** [comment]
I should've put this into discussion.

**Comment by dschwen** [comment]
With AD we need to refocus our attention to the cost of full tensor operations. I'd like to see high symmetry tensor classes and either 

1. the use of templating to support them in calculations
2. an enum in the tensor class to indicate symmetry and active entries

Gary, you mentioned that your group is already working on point 1. It would be great if we could convince them to share their approach. Otherwise we need to waste resources to do something similar.
