### ISSUE TITLE
Moose not finding some modules.

### ISSUE THREAD

**Issue by helen-brooks** [idaholab/moose#16489]
I recently pulled to  commit 2482f584452c9028bc6afa0937fee8c9a0feaa75 and noticed that my app could no longer find the heat_conduction module at run time, complaining with the error

```
*** ERROR ***
A 'ADHeatConduction' is not a registered object.

If you are trying to find this object in a dynamically linked library, make sure that
the library can be found either in your "Problem/library_path" parameter or in the
MOOSE_LIBRARY_PATH environment variable.
```

Bizarrely, I *do* see the object if I run with the --registry option. 

I find I can reproduce this issue in the darcy_thermo_mech tutorial directory if I modify the Makefile therein and turn off the phase_field and tensor_mechanics modules, and attempt to run step 5. Given that these modules should not be needed in this step, I believe there is a bug somewhere in one of the build scripts. 

On the other hand, if I modify my app Makefile to include either phase_field or tensor_mechanics modules and rebuild my app, everything runs fine.

I'm currently running on Ubuntu 20.04, and building from source, in case that is relevant. I ran make clobberall prior re-building after pulling.

**Comment by aeslaughter** [comment]
The heat conduction is required for step5: [`type = ADHeatConduction`](https://github.com/idaholab/moose/blob/13cc680a2cd9f90c9ba3487e29f26e0305decf47/tutorials/darcy_thermo_mech/step05_heat_conduction/problems/step5a_steady.i#L17)

**Comment by helen-brooks** [comment]
I think perhaps you misunderstood my point? I *want* to use the ADHeatConduction kernel. What I am saying is that if in the Makefile I modify the module lines to
```
CHEMICAL_REACTIONS        := no
CONTACT                   := no
FLUID_PROPERTIES          := no
# heat_conduction is required by Steps 5+
HEAT_CONDUCTION           := yes
LINEAR_ELASTICITY         := no
MISC                      := no
NAVIER_STOKES             := no
# phase_field is required by Step 10.
PHASE_FIELD               := no
POROUS_FLOW               := no
RICHARDS                  := no
# tensor_mechanics is required by Steps 9-10.
TENSOR_MECHANICS          := no
XFEM                      := no
```
i.e. specificially I have turned off the `PHASE_FIELD` and `TENSOR_MECHANICS` modules, which should *not* be required for step 5, then at runtime Moose failed to find the ADHeatConduction kernel, despite listing it amongst registered objects. As soon as one of these two modules are turned back on, and the darcy_thermo_mech app is rebuilt, everything again works fine.

**Comment by loganharbour** [comment]
If you take a look at [ModulesApp.C](https://github.com/idaholab/moose/blob/next/modules/module_loader/src/ModulesApp.C), you can see where this registration is handled (given that the Makefile variables are set and the application calls on the `ModulesApp::registerAll()` method).

I've spent a little time fishing through there and can't see anything out of place.

To be clear here, you're replicating this in `tutorials/darcy_thermo_mech/step05_heat_conduction`, is that correct?

**Comment by loganharbour** [comment]
I made the following changes (which I believe are the changes that you're saying you made): https://github.com/loganharbour/moose/commit/412d254ac56c4f45d4ebeca07173d6354b536ddd

From within `tutorials/darcy_thermo_mech/step05_heat_conduction`:

```
make clobberall
make -j 12
./run_tests
```

Leads to passing tests for me.

Is there a chance that you could provide us access to your application to see if we can replicate the issue there?

**Comment by aeslaughter** [comment]
I just did the same as @loganharbour, everything works fine for me as well.

**Comment by helen-brooks** [comment]
I had already run make clobber all from my app directory, but not from the tutorial directory. So I repeated make clobberall from the tutorial directory and now I have no issues with step 5, and all those tests pass. So some improvement there at least. But make clobberall from my app still does not seem to fix the issue there. Is there any reason make clobberall might not work?

**Comment by loganharbour** [comment]
Are you using a MOOSE submodule or are you pointing to moose via `MOOSE_DIR`? 

I would suggest cleaning up your repo (make sure you have no non-committed files), and running

```
git clean -xfd
```

Make sure that `MOOSE_DIR` is pointing to the MOOSE that you were just working on, or if a submodule, I would clean it too.

**Comment by helen-brooks** [comment]
On a side note, having run make clobberall once already for a given app, why is it not sufficient to run make clean from within another app? It seems inefficient to rebuild moose for every different app. Is there no simple way to re-link in the moose framework and its modules?

**Comment by loganharbour** [comment]
If you have `MOOSE_DIR` set to a MOOSE used by all applications and you ever hit issues, running `make clobber` from within your application root should clean up only its files and get you in a good state.

It's important to note that we're working on the make system in order to avoid these issues all together.

**Comment by helen-brooks** [comment]
> If you have `MOOSE_DIR` set to a MOOSE used by all applications and you ever hit issues, running `make clobber` from within your application root should clean up only its files and get you in a good state.
> 
> It's important to note that we're working on the make system in order to avoid these issues all together.

Ok, good to know.

**Comment by helen-brooks** [comment]
> Are you using a MOOSE submodule or are you pointing to moose via `MOOSE_DIR`?
> 
> I would suggest cleaning up your repo (make sure you have no non-committed files), and running
> 
> ```
> git clean -xfd
> ```
> 
> Make sure that `MOOSE_DIR` is pointing to the MOOSE that you were just working on, or if a submodule, I would clean it too.

I'm using MOOSE_DIR, and it does point at the version of moose I'm using. (I even added a printout inside the makefile just to be sure). I don't have any submodules. Sadly git clean didn't fix it.

**Comment by loganharbour** [comment]
Does your `<AppName>.C` file have a call to `ModulesApp::registerAll()` in it?

**Comment by helen-brooks** [comment]
yes, it does

```
void
AuroraApp::registerAll(Factory & f, ActionFactory & af, Syntax & s)
{
  ModulesApp::registerAll(f, af, s);
  Registry::registerObjectsTo(f, {"AuroraApp"});
  Registry::registerActionsTo(af, {"AuroraApp"});

  /* register custom execute flags, action syntax, etc. here */
}

```

**Comment by loganharbour** [comment]
@helen-brooks found that she could replicate the behavior with a new storked app. Looking into this shortly.

**Comment by loganharbour** [comment]
I just used stork with

```
HEAT_CONDUCTION             := yes
````

and ran the input `modules/heat_conduction/test/tests/ad_heat_conduction/test.i` with the minor change (so that I could run it from my storked app)

```
diff --git a/modules/heat_conduction/test/tests/ad_heat_conduction/test.i b/modules/heat_conduction/test/tests/ad_heat_conduction/test.i
index b612d3246a..8e3ec2ad55 100644
--- a/modules/heat_conduction/test/tests/ad_heat_conduction/test.i
+++ b/modules/heat_conduction/test/tests/ad_heat_conduction/test.i
@@ -73,9 +73,9 @@

 [Materials]
   [./k]
-    type = ADThermalConductivityTest
-    c = c
-    temperature = T
+    type = ADGenericConstantMaterial
+    prop_names = 'thermal_conductivity'
+    prop_values = 1
   [../]
 []
```

And I was able to get it to run.

**Comment by helen-brooks** [comment]
I finally found a fix. I ran `git clean -xfd` in the root moose directory.Tutorial, clean app and my app all now finding heat conduction. The question remains however, is make clobberall not removing some files that it should be?

**Comment by aeslaughter** [comment]
> I finally found a fix. I ran `git clean -xfd` in the root moose directory.Tutorial, clean app and my app all now finding heat conduction. The question remains however, is make clobberall not removing some files that it should be?

Great! There must be something missing with `make clobberall` it is a constant battle to do the correct cleanup with that command, but `git clean` never fails. It is what I always use.
