### ISSUE TITLE
RayTracing: doco suggestions

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#16507]
## Reason

I was just reading the doco and there are a few places where i thought it could be slightly modified.  Tagging @loganharbour .   Feel free to close if you think these suggestions stink.

## Design

- Does RayTracing only work for 2D meshes?  The lead page states "planar finite elements" that suggests 2D, but then in my naivety i can't see why 3D meshes are super difficult.
- In the first equation of https://mooseframework.inl.gov/modules/ray_tracing/examples/line_integrals.html , what is "u_h"?  Why isn't it just "u"?   Also, i wouldn't include the measure (dr) as i think that's confusing.
- The second equations of https://mooseframework.inl.gov/modules/ray_tracing/examples/line_integrals.html should have r_1 and r_2 - currently they just have r_1.
- I think it'd be nice in https://mooseframework.inl.gov/modules/ray_tracing/examples/line_integrals.html  to actually write what you're trying to compute, viz something like \int_{0}^{5} dx sqrt{2}x/5 (or however you want to write it), just because in order to verify the results i had to look back at the input file and see that u = x/5 for this example.
- In https://mooseframework.inl.gov/modules/ray_tracing/examples/line_sources.html i really think you need to write the DE you're trying to solve, viz \nabla^{2}u = 5\delta(x-ray), where ray is specified by the RepeatableRayStudy (and \delta is the 2D Dirac delta function).  The reason is that it took me a while to figure this out - i wondered what the "5" was in LineSourceRayKernel, for instance.
- Might be nice to see the mesh in the pics in https://mooseframework.inl.gov/modules/ray_tracing/examples/line_sources.html 
- Might be nice to mention more about Jacobians.  These are really important in PorousFlow so i need to know whether i can include all Jacobian contributions.

## Impact
Better user experience with improved documentation.

**Comment by loganharbour** [comment]
> Does RayTracing only work for 2D meshes? The lead page states "planar finite elements" that suggests 2D, but then in my naivety i can't see why 3D meshes are super difficult.

Definitely supports 3D! I changed this:

```
Supports tracing in meshes with planar sides (2D and 3D)
```

> In the first equation of https://mooseframework.inl.gov/modules/ray_tracing/examples/line_integrals.html , what is "u_h"? Why isn't it just "u"?

It's u_h because it's the integral of the FEM solution. I added in the measure 

> Also, i wouldn't include the measure (dr) as i think that's confusing.

Hmm. How about u_h(r) dr?

> The second equations of https://mooseframework.inl.gov/modules/ray_tracing/examples/line_integrals.html should have r_1 and r_2 - currently they just have r_1.

Doh. Fixed.

> I think it'd be nice in https://mooseframework.inl.gov/modules/ray_tracing/examples/line_integrals.html to actually write what you're trying to compute, viz something like \int_{0}^{5} dx sqrt{2}x/5 (or however you want to write it), just because in order to verify the results i had to look back at the input file and see that u = x/5 for this example.

TODO
