### ISSUE TITLE
Pass-by-reference for ArrayKernel evaluation

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#16504]
## Bug Description
When doing some profiling of ArrayKernels, I found that despite my best efforts `computeQpResidual` was still unexpectedly allocating temporary memory. After much reading and headache I began to understand how Eigen does matrix-vector operations and learned when it creates temporary objects. From this, I learned how to better do in-place operations and realized that pass-by-reference was the best way to take advantage of this.

## Steps to Reproduce
At the end of this is an input with a simple diffusion problem with a bunch of components to an array variable.  Using instruments on my mac, I saw the allocation and deallocation sequences within `computeQpResidual`:
![image](https://user-images.githubusercontent.com/12819067/102286656-fd267e00-3ef5-11eb-8e12-10add6ea0b9b.png)

Changing the residual evaluation in `ArrayDiffusion` to pass-by-reference and using in-place operations:
```
void
ArrayDiffusion::computeQpResidual(RealEigenVector & vector)
{
  vector.noalias() = _grad_u[_qp] * _array_grad_test[_i][_qp];
  vector.array() *= (*_d_array)[_qp].array();
}
```
There is no more memory thrashing inside `computeQpResidual`. As a result `computeQpResidual` for this problem dropped by ~20%.

## Impact
Using the pass-by-reference would have significant impacts on derived objects of ArrayKernel, since this changes the API. Although I believe Griffin is the only app using array kernels, so this will be on me to make changes.

```
[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 10
  ny = 10
  nz = 10
[]

[Variables]
  [u]
    order = FIRST
    family = LAGRANGE
    components = 500
  []
[]

[Kernels]
  [diff]
    type = ArrayDiffusion
    variable = u
    diffusion_coefficient = dc
  []
[]

[BCs]
  [right]
    type = ArrayDirichletBC
    variable = u
    boundary = '1 2'
    values = '1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1'
  []
[]

[Materials]
  [dc]
    type = GenericConstantArray
    prop_name = dc
    prop_value = '1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1

              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1
              1 1 1 1 1 1 1 1 1 1'
  []
[]

[Executioner]
  type = Steady
  solve_type = JFNK
  l_max_its = 100
  nl_abs_tol = 1e-12
  nl_rel_tol = 1e-14
[]

[Outputs]
  [pg]
    type = PerfGraphOutput
    level = 10
  []
[]
```

**Comment by zachmprince** [comment]
Tagging @YaqiWang @loganharbour @lindsayad @dschwen

**Comment by loganharbour** [comment]
Wahoo! Glad to see that there's more we can squeeze out of this.

I'm for the API change if it enables in-place operation + no temporaries.

**Comment by YaqiWang** [comment]
The argument `vector` will be owned by `ArrayKernel` base class, thus I suggest we directly make the variable protected, available to derived class. We have had similar member variables such as `_i`, `_j`, `_u`, `_phi`, etc. I do not know much about `Eigen`, what will happen if we do not have `noalias` in the first line of your `computeQpResidual`? Why
```
_vector = (*_d_array)[_qp].cwiseProduct(_grad_u[_qp] * _array_grad_test[_i][_qp]);
```
does not work as expected (I guess)?

**Comment by loganharbour** [comment]
> The argument vector will be owned by ArrayKernel base class, thus I suggest we directly make the variable protected, available to derived class.

I don't like this because the API is not as clear. It's much clearer as an argument.

**Comment by YaqiWang** [comment]
There is no point to allocate a pointer in the function call stack. It is not more clear than a member variable.

**Comment by loganharbour** [comment]
If you were a newcomer to this, and you saw

```
void computeQpResidual(RealEigenVector & vector)
```

vs

```
void computeQpResidual()
```

I completely disagree.

**Comment by lindsayad** [comment]
> There is no point to allocate a pointer in the function call stack

This is a weak argument. With all our memory usage, 8 bytes on the stack is a drop in the ocean

**Comment by lindsayad** [comment]
> When doing some profiling of ArrayKernels, I found that despite my best efforts `computeQpResidual` was still unexpectedly allocating temporary memory

I'm not sure I would say this is unexpected. My mind was blown when you shared the profiles of your previous work and the memory allocation/deallocation were no longer present. It was as if a construction in `computeQpResidual` and move assignment in `computeResidual` were being combined into a single copy elision...when we were copying into an object that was already constructed! (See https://github.com/idaholab/moose/pull/16361#issuecomment-740150413). So I'm glad that my understanding of C++ is not completely borked, and we were still doing memory allocation/deallocation with the `computeResidual/computeQpResidual` stack

**Comment by YaqiWang** [comment]
@zachmprince in your previous PR, you showed a graph without memory allocation. What is the difference of the setting for generating that graph and this one? I thought the returned value from `RealEigenVector computeQpResidual()` is directly evaluated in `_work_vector`. Is not that the case? I am a little puzzled here.

**Comment by lindsayad** [comment]
> We have had similar member variables such as `_i`, `_j`, `_u`, `_phi`, etc.

This is a much stronger argument. If we have a history of not documenting input with our API, then perhaps you can reasonably argue that there is not a need to document output with our API.

**Comment by zachmprince** [comment]
> I thought the returned value from RealEigenVector computeQpResidual() is directly evaluated in _work_vector.

This is still true, it is doing a copy elision at the`computeResidual` level. But there are still temporary objects being constructed inside `computeQpResidual`. I thought originally this was unavoidable whether we return-value or pass-by-reference. But learning more about Eigen::Matrix I found some API that avoids this, namely `noalias()` and `array()`. And the only way to take advantage of this API is to pass in the vector.

**Comment by zachmprince** [comment]
These are two pages that I found very useful in my investigation:
[http://eigen.tuxfamily.org/dox/group__TopicAliasing.html](http://eigen.tuxfamily.org/dox/group__TopicAliasing.html)
[http://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html](http://eigen.tuxfamily.org/dox/group__CoeffwiseMathFunctions.html)

**Comment by zachmprince** [comment]
```
_vector = (*_d_array)[_qp].cwiseProduct(_grad_u[_qp] * _array_grad_test[_i][_qp]);
```
Create two temporary objects, one for `_grad_u[_qp] * _array_grad_test[_i][_qp]` and another for `(*_d_array)[_qp].cwiseProduct` then it assigns it to the vector.

**Comment by lindsayad** [comment]
> This is still true, it is doing a copy elision at the`computeResidual` level.

I don't think this is true. You can see [this article](https://shaharmike.com/cpp/rvo/#assignment) which outlines that RVO (which is the copy elision variant we would be considering here) does not happen with assignment.

**Comment by lindsayad** [comment]
My code from https://github.com/idaholab/moose/pull/16361#issuecomment-740087402 showed copy elision from the first line of main, but showed a move assignment and destructor call for the temporary from line 2 of main:
```c++
int main()
{
  A a = foo();
  a = foo();
}
```

**Comment by zachmprince** [comment]
Thanks Alex, I still need some teaching on RVO apparently haha. I really mean my PR got rid of deallocation that was originally in `computeResidual`. But all the temporary objects inside `computeQpResidual` were still being constructed. Basically, this:
```
int main()
{
  A a;
  for (...)
    a = foo();
}
```
was showing better performance than this:
```
int main()
{
  for (...)
    A a = foo();
}
```

**Comment by lindsayad** [comment]
See here what's fascinating to me. Here is the output from your code 1 above with two executions of the for loop:
```bash
empty constructor
empty constructor
move assignment
destructor called
empty constructor
move assignment
destructor called
destructor called
```
And then output from your code 2:
```bash
empty constructor
destructor called
empty constructor
destructor called
```
It's not immediately obvious to me why 2 should be better than 1...in fact I would think it would be worse!

**Comment by lindsayad** [comment]
My only conclusion is that Eigen is doing something very clever in their move assignment and destructor methods

**Comment by lindsayad** [comment]
This article looks really good http://scottmeyers.blogspot.com/2014/06/the-drawbacks-of-implementing-move.html

**Comment by YaqiWang** [comment]
`array` and `cwiseProduct` are probably doing the same thing. Maybe we should do the simple linear algebra without using Eigen? The code is not very intuitive to developers.

**Comment by dschwen** [comment]
Yeah, I'm not sure we can we expect devs to understand what `noalias` does. This has the potential to give wrong results if people just copy paste and modify code and end up putting the same vector on both sides of the assignment.

**Comment by YaqiWang** [comment]
My second thinking is that: because `20%` is pretty significant, I support this interface change even it may result into some not good-looking codes. Also naming `vector` as `_qp_residual` could be a good idea. We will need to document this including add in-line comments carefully so that developers will not fall into the trap because that I can see if happens will be a pretty nasty bug.

**Comment by zachmprince** [comment]
> `array` and `cwiseProduct` are probably doing the same thing.

Yes they are, my mistake.

> Maybe we should do the simple linear algebra without using Eigen?

Do you mean writing our own loops to do matrix vector products? I'm pretty sure Eigen, when used properly, is faster than this since it is calling lapack routines. We could call the lapack routines directly, but that sounds like a nightmare to me haha.

The `noalias` is a nonintuitive thing. Would inline comments be enough to deter wrongful usage?

**Comment by YaqiWang** [comment]
I regret that when I added array kernels, I did not summarize the most useful Eigen functions that can be used in array kernels. I think if you are going to make this change, time to add that. You may check our fancier kernels to generate the function list.  This page needs to be updated: https://mooseframework.inl.gov/source/variables/ArrayMooseVariable.html. If Eigen provides a configure flag to turn off `noalias`, we can do that in dbg mode. Inline comments will be definitely needed.

**Comment by YaqiWang** [comment]
Yeah, abandoning Eigen just for code readability is probably a bad idea. Handling BLAS is tricky and we do not want to do that.

**Comment by zachmprince** [comment]
Sounds good. I would be happy to document proper Eigen usage. I'm sure others will run into the same things I'm looking at.

I have one problem with the `_qp_residual` functionality. With this, there will need to be three different members:
```
RealEigenVector _qp_residual;
RealEigenVector _qp_jacobian;
RealEigenMatrix _qp_off_diag_jacobian;
```
The last two could be confusing. What do you think? I think the pass-by-reference is the most intuitive way since it tells the developer exactly what they need to modify. With the member variables they could be modifying the wrong one without any compile errors.

**Comment by YaqiWang** [comment]
I do not think optimizing jacobian evaluation is that important. So keeping the current simpler interface for them is a better idea in my opinion.

I argued to directly use member variables. Note that we have an assertion to ensure the size of the residual vector is correctly set by `computeQpResidual` function. We can even set it to size 0 in dbg mode before calling `computeQpResidual`. As a c developer before, I tend to not do redundant things. Even `computeResidual` is virtual, meaning allowed to be modified by developers, I do not see the point of passing it as a reference.

**Comment by YaqiWang** [comment]
Oh, did not realize you already did similar changes to the two jacobian functions. I think it is better to revert the changes there as @lindsayad pointed out that those changes are arguably causing performance improvements.

**Comment by YaqiWang** [comment]
You will have another pain with `ArrayDGKernel`.

**Comment by zachmprince** [comment]
Also just learned a bit about expression templates. So it is better to have all the linear algebra operations all in one line I think.

Changing my orignally posed code to this improved `computeQpResidual` a bit:
```
residual.noalias() = (*_d_array)[_qp].asDiagonal() * _grad_u[_qp] * _array_grad_test[_i][_qp];
```

**Comment by zachmprince** [comment]
I'm still not convinced that using a member variable is better than pass-by-reference, so I did some profiling. I tried out both pass-by-reference and using a member variable. And I found there was almost no change in performance between the two. For the problem I posted, here is the average time of `NonlinearSystemBase::computeResidualInternal` for 5 runs each:

pass-by-reference:
```
0.178
0.183
0.179
0.181
0.180
```

member variable:
```
0.182
0.183
0.177
0.179
0.178
```

As reference, return-value was about 0.27.

I believe that pass-by-reference still has a similar interface as non-array kernels, as it is clear what needs to be returned. The member variable API adds an extra layer of required knowledge to do things properly. So if there is no evidence of performance difference, I don't see much point in adding this extra layer. Arguments?

**Comment by rwcarlsen** [comment]
Pass it as an argument.  I have spoken.

**Comment by rwcarlsen** [comment]
In fact, now that we often use AD - where the residual is not a simple POD data type, there would be wins (although not as significant as here) to always pass the "output" residual by ref - not just for array kernels.

**Comment by permcody** [comment]
I vote for pass by writable reference.

**Comment by YaqiWang** [comment]
Note that this sets an example of how base class to expose something to its derived classes. I am ok either way because it does not change memory usage nor cpu time. I guess it is better to treat an output residual differently than other protected members.

**Comment by friedmud** [comment]
I vote for pass by writable reference as well.  It has the advantage that it's very clear what needs to be done (no outside knowledge of member variables is necessary).

**Comment by fdkong** [comment]
If the performance is the same, I would just pass as a reference
