### ISSUE TITLE
Support strumpack (a sparse direct solver)

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#16501]
## Reason

For certain problems, I found `strumpack` beat all other direct solvers. I think it is a good idea to support this.

It might be interesting for @lindsayad @bwspenc as well 

## Design

"`--download-strumpack`". Also need to add something into libmesh configuration so that we have `strumpack=true` ready for use in `tests` 

## Impact
Better direct solver

**Comment by lindsayad** [comment]
Yes we probably need to get `LIBMESH_PETSC_HAVE_STRUMPACK` done first

**Comment by dschwen** [comment]
We had a workpackage item on this in FY19. We saw some decent results for some Bison assessment cases.

**Comment by dschwen** [comment]
Without disclosing too much info on a public forum
![image](https://user-images.githubusercontent.com/202302/102293029-87291380-3f03-11eb-8a87-e7c842c9c5a9.png)

**Comment by lindsayad** [comment]
So you sped-up every single test?! Or is there a bottom-half cut-off there?

**Comment by bwspenc** [comment]
I think some ran a little slower, @lindsayad, which is what that first plot shows. Overall, though, I think if you just swap out solvers on all cases, there was an advantage to going to strumpack. It might have used less memory too, although I don't really remember. My understanding is that strumpack comes from the same groupl that develops superlu, but their development emphasis is now on strumpack. That alone is a good reason for us to have good support for it.

**Comment by dschwen** [comment]
Bottom line is use strumpack where it speeds up your run, and _don't_ use it where it slows it down. D'uh...
