### ISSUE TITLE
Alternative to ReferenceResidualProblem for nl_abs_tol

### ISSUE THREAD

**Issue by r-williams-2** [idaholab/moose#16519]
## Reason

This would be useful in simulations with multiple physics where the residuals are of different orders of magnitude when the problem is approaching a steady state. For additional background leading to this suggestion, see #16491.

## Design

The ability to set an absolute tolerance for each residual of choice. I imagine this would work in a very similar manner to ReferenceResidualProblem only comparing each residual with each provided absolute tolerance, rather than comparing each residual against a chosen reference quantity.

## Impact

This would allow the solution of problems where all physics are approaching a steady-state but using a single `nl_abs_tol` would inhibit some residuals from converging sufficiently.

**Comment by lindsayad** [comment]
Superseded by #17249
