### ISSUE TITLE
Non-deterministic pffltvd_1D_adaptivity_threads

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#16558]
## Reason
The test `pffltvd_1D_adaptivity_threads` exhibits non deterministic behavior. 

@cpgr @WilkAndy 

I thought we had an issue open for this but could not find it.

## Design
Make it deterministic?

## Impact
Better porous flow threaded behavior.

**Comment by cpgr** [comment]
Was it #14558?  In any case, we still need to work out why we have a random failure.

**Comment by loganharbour** [comment]
Closing over #14558
