### ISSUE TITLE
Consistent FV variable evaluations on surfaces between objects

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#16585]
## Reason
For finite volume applications, there is often the need to compute variables on element faces. For example, an advection kernel in incompressible navier stokes will use Rhie Chow interpolation to compute the velocity on the face between two elements. It is important to be consistent between objects for this purpose. However, numerous pieces of codes, such as Side*postprocessors are not aware of the advanced interpolation used in the kernels, which can lead to inconsistencies. The interpolation code, specific to INS, lives on the kernel. But we need it to be used everywhere if we want to be able to re-use a wide range of objects.

For example, in incompressible navier stokes, SideIntegralVariablePostprocessors on velocity at the inlet and outlet will not report conservation of mass as they use the cell value, when advection kernels are using interpolation. 

## Design
There are a few ways to go about this problem:
- save the variable on every face when the kernel evaluates them. This is easier implementation-wise and will be trivial to use in the future, however this is expected to be a 4x increase in memory in 2D, 6x in 3D (quad mesh). For a coarse-mesh CFD tool this is ok. For other applications, this may be an issue. Note that we already incur that cost of saving face values, we just don't save the RC value, because it's not the only value velocity can take on faces.
- move the interpolation to an INS-FV material. Materials are naturally accessed by all the relevant objects. This restricts the possibility of using different interpolation methods for different kernels
- move the interpolation to the variable object. MooseVariableFV is too general, it goes beyond incompressible flow. But a subclass could be made, specific to INS-FV applications. The disadvantage is that in my understanding there's a lot of plumbing involved with adding a new variable class. 
- move the interpolation to the variable object, but as a function attribute that is used for calculating face values. Then an object can attach the interpolation rule it needs to the variable. We would only attach a single interpolation rule to the variable. The advantage is that the interpolation code can still live in the kernel object.
- have the interpolation be done by a userObject, like a RhieChowInterpolator that is passed to the kernels and objects that need it

## Impact
Consistency between objects using the same variable
Facilitate future developments

**Comment by rwcarlsen** [comment]
I'd vote for the fourth bullet - allowing objects to attach interpolation rules - and kernels/objects that want the interpolated value then explicitly couple to (or ask for) the interpolated value.  Ideally - we'd make them call a function (e.g. in their compute qp function) whenever they want the value - this way we could trivially add caches or other fanciness later without affecting the object APIs.

**Comment by GiudGiud** [comment]
I'll wait for the NormalGradientBCs in #16732 to be merged in before changing anything about RC

**Comment by GiudGiud** [comment]
@dzenun I think that s the issue with coupling with RC. Postprocessors are not getting the right value for velocity on the wall, so mass or temperature is lost in the coupling between the 2D pipe and the rest of the channel

**Comment by lindsayad** [comment]
Closed by #18563
