### ISSUE TITLE
Remove/fix poorly conditioned tests

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#16595]
## Reason
Tests that are poorly conditioned are subject to failure when changing PETSc versions or when changing architectures. This can hold-up development.

## Design
The fix will be test dependent.

## Impact
Improve developer experience

## List of tests

- [ ] `porous_flow/test:fluidstate.theis_nonisothermal`: `SVD: condition number 1.390123944521e+22, 1 of 123 singular values are (nearly) zero`. Author: @cpgr

**Comment by loganharbour** [comment]
Closed in #16717
