### ISSUE TITLE
Remove MooseMesh from GridPartitioner

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#16632]
## Reason

It is not necessary to create an actual MooseMesh in order to use GridPartitioner.  Creation of MooseMesh generates some noise for @lindsayad, and also increases the maintainance burden. 

## Design

In order to partition a mesh based on processor grid, we only need to kind of "virtual" data. The partition can be done by doing some intelligent calculations to figure out processor coordinate according to coordinates of each mesh element. 

## Impact
Better than ever before

**Comment by lindsayad** [comment]
> Better than ever before

Hahaha I love this
