### ISSUE TITLE
Multiapp Tutorial

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#16660]
## Reason

Create a Multiapp tutorial to help new developers use the system.

## Design

Create a second tutorial for the website with optional slides

## Impact

Improved documentation.

**Comment by aeslaughter** [comment]
Closed by #16660

**Comment by friedmud** [comment]
@aeslaughter did this ever actually get merged?

**Comment by aeslaughter** [comment]
Yes. https://mooseframework.inl.gov/getting_started/examples_and_tutorials/tutorial02_multiapps/index.html
