### ISSUE TITLE
fixed_meshes option for NearestNode Transfer with multiple sub-apps broken

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#16673]
## Bug Description
This is a large bug that needs to be fixed immediately.

If you have multiple sub-apps at different positions and you use the `fixed_meshes` option for `NearestNodeTransfer` the transfers are _wrong_.  What happens is that all of the transfers happen as if they are in the same position!

## Steps to Reproduce
Have multiple sub-apps in different positions and use `fixed_meshes = true`... they will all receive the same data!

## Impact
This impact is huge - anyone using NearestNodeTransfer like this is severely impacted!

**Comment by friedmud** [comment]
I'm assigning @fdkong since he's working on Transfers right now - let's get this one fixed quickly!

**Comment by fdkong** [comment]
Why I can not reproduce this issue? You received the same data because the subapp generated the same solution?

**Comment by GiudGiud** [comment]
Fixed by #21748
