### ISSUE TITLE
In MOOSEDocs many pages are reported as Input Parameters instead of the class name in the source list

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#16749]
## Bug Description

See https://mooseframework.inl.gov/source/index.html and search for Input Parameters, numerous bcs, postprocessors, kernels and others are listed as Input Parameters rather than the class name.

## Steps to Reproduce

Look at https://mooseframework.inl.gov/source/index.html 

## Impact

 Quite annoying.

**Comment by loganharbour** [comment]
@lindsayad looks like many of these are yours with NS. You need to add headers with the object names to the markdown files.
