### ISSUE TITLE
Passing Outputs/perf_graph=true or similar on command-line causes failure in fluid_properties

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#16763]
## Bug Description

Passing Outputs/perf_graph=true or similar on command-line causes failure in fluid_properties

## Steps to Reproduce

```
cd moose/modules/fluid_properties/test/tests/fp_interrogator
$ ../../../fluid_properties-devel -i 1ph.p_T.i Outputs/csv=true
```
## Impact

Does not allow cli_args from tests to include output changes.

**Comment by aeslaughter** [comment]
@andrsd Can you shed some light on what fluid_properties is doing with Output?

**Comment by andrsd** [comment]
Fluid property negotiator takes a thermodynamical state, runs it through the selected class and outputs resulting quantities. Best to understand on an example: you know pressure and temperature and need to know everything else like density, viscosity, conductivity, etc. So, it does not run any kind of simulation it is a tool for users to set up their problems.

But, passing additional Outputs should not crash the execution. If you don't see those outputs, that might be a problem.

For example, if you say things like `csv = true`, there is no CSV output, so nothing should come out. For `perf_graph`, we could still output the performance log.

**Comment by andrsd** [comment]
debug mode hits this assert:
```
Assertion `common_actions.size() == 1' failed
Should be only one common_output Action
at /path/to/moose/framework/src/base/MooseApp.C, line 915
```
So I guess, we are not setting up the output action correctly. Hopefully, the fix will be trivial...

**Comment by aeslaughter** [comment]
The commit I have here fixes the assertion, but that uncovers a problem I can't figure out.

**Comment by andrsd** [comment]
In case @loganharbour did not tell you, I am looking into a proper fix for this...

**Comment by andrsd** [comment]
But I was in meetings most of today, so I did not get too far... :-(

**Comment by andrsd** [comment]
@aeslaughter @loganharbour Check the patch I made for fixing this problem. I had to relax the check to only have 1 instance of `CommonOutputAction`. IDK if that's kosher with the original design. The idea behind adding our own `CommonOuputAction` is to suppress printing of the system info (since we are not running any sim, we don't want to see it). The reason why we do it this way is that we can't drill into the `Console` output and start messing with its data members - which we probably don't want to allow any way. 

Let me know what you guys think and we can go from there. I am open to solutions.

**Comment by aeslaughter** [comment]
> The reason why we do it this way is that we can't drill into the `Console` output and start messing with its data members - which we probably don't want to allow any way.

Why not? You could just create a Console with "execute_system_information_on = none" in an Action, prior to the CommonOutputAction running. The CommonOutputAction should not create one if it already exists.
