### ISSUE TITLE
Add [Partitioner] capability with MeshGenerators

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#16776]
## Reason
Currently, the [Partitioner] block has no effect with MeshGenerators.

## Design
Get it working?

## Impact
Expanded capability.

**Comment by loganharbour** [comment]
I looked for another issue that involves this, but couldn't find one. Please let me know if there is one.

@lindsayad is there any chance you would have time to support this? I know we've discussed it in the past, but the discussions are now past our message limit... If not, I would be happy to give it a try after a short chat on the path forward.

**Comment by lindsayad** [comment]
I can do this relatively soon. Thanks for creating the issue. What is the customer application?
