### ISSUE TITLE
PETSc switch to 64-bit indices by default

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#16779]
## Reason

More and more large moose simulations are emerging. For these large problems,
`64-bit-indices` are required.  

## Design

Build 64-bit indices by default.

## Impact
Run large problems smoothly.

**Comment by mangerij** [comment]
I'm curious. How many dof/proc before it's considered "large"?

**Comment by fdkong** [comment]
> I'm curious. How many dof/proc before it's considered "large"?

I would like to call the simulation large If you are using more than a hundred cores or the total DOFs is more than 10M

Different people might have different definitions, haha

**Comment by mangerij** [comment]
Does 64 bit petsc use less memory?

**Comment by fdkong** [comment]
> Does 64 bit petsc use less memory?

No. It will use more memory. But for large problems you have to use 64-bit indices anyway, otherwise you will run into integer overflow issues
