### ISSUE TITLE
Allow unicode in markdown

### ISSUE THREAD

**Issue by smharper** [idaholab/moose#16804]
## Reason
I would like to be able to use non-ASCII characters in documentation. This has come up in the theory documentation of #16795, for example, where I'm referring to non-English scientist names like von Kármán.

## Design
The unicode characters in `.md` and `.bib` files seem to be working well with MooseDocs on my local machine. As far as I can tell, we simply need to modify the pre-check script to allow these characters.

## Impact
We will now be able to faithfully represent non-English proper names in our documentation. Potentially, some folks will find other uses for unicode characters in the docs.

**Comment by loganharbour** [comment]
Closed in https://github.com/idaholab/civet_recipes/pull/2291.
