### ISSUE TITLE
location param  in SideSetsFromBoundingBoxGenerator doesn't work as described in documentation

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#16813]
## Bug Description

The `location` parameter only seems to be applied and used for option 2 (`boundary_id_overlap = True`) on the `SideSetsFromBoundingBoxGenerator` documentation: https://mooseframework.inl.gov/source/meshgenerators/SideSetsFromBoundingBoxGenerator.html.

However, the first option states that setting `location = OUTSIDE` when providing a bounding box, `new_boundary_id `and `old_boundary_id` should put all nodes in `old_boundary_id` outside of the bounding box would be applied to the `new_boundary_id`. This is not how it works. If `boundary_id_overlap = False` (the default) it will never use the `location` parameter. The source code branch for this case even has a comment:

` // check if active elements are found in the bounding box`

and an error if no elements are found INSIDE the bounding box:

```
    if (!found_element)
      mooseError("No elements found within the bounding box");
```

If this is in the intended behavior then the documentation should reflect.  If I specify `location = OUTSIDE` I get the exact same behavior as `location = INSIDE`.

## Steps to Reproduce

Add ` location = OUTSIDE` to 

```
  [./createNewSidesetOne]
    type = SideSetsFromBoundingBoxGenerator
    input = gmg
    boundary_id_old = 'left'
    boundary_id_new = 10
    bottom_left = '-0.1 -0.1 0'
    block_id = 0
    top_right = '0.5 0.5 0'
  []
```

in the `generate_sidesets_bounding_box.i` input file in test/tests/meshgenerators and run with the input with --mesh-only and you will get the exact same sidesets as with` location = INSIDE` (the default)
## Impact

This is causing me problems because based on the documentation I expected this to work for a case I'm trying to create and I keep getting this unexpected behavior.

**Comment by GiudGiud** [comment]
@socratesgorilla if you are interested in the other SideSetsFromBoundingBoxGenerator issue, you could grab that one at the same time. It s mostly documentation and understanding what s going on with these options
