### ISSUE TITLE
Support auxvariable velocities with `INSFVScalarFieldAdvection`

### ISSUE THREAD

**Issue by smharper** [idaholab/moose#16853]
## Reason
Sometimes it makes sense for fluids problems to solve the conservation of mass and momentum in one app and then the conservation of energy and other passive scalars in a separate app. For example, maybe the temperature dependence of the fluid density is negligible for a particular problem. Separating these uncoupled physics into different apps can lead to big speedups. This means that the velocity would be represented with an `AuxVariable` on the app that handles the scalars.

Currently, we don't support this. The `INSFVScalarFieldAdvection` requires us to specify `FVBCs` for the velocity variables. (It needs these BCs to figure out what the velocity is on the faces that lie on a problem boundary.) But we can't specify BCs for the velocity `AuxVariable`s

## Design
The user should be able to specify the fluid velocity distribution using `AuxVariables` and then use that velocity to advect passive scalars.

## Impact
This will allow for more efficient simulations of some problems with fluid flow.

**Comment by lindsayad** [comment]
Per the call today I think this can be solved when #16283 is implemented.

**Comment by smharper** [comment]
Tagging @snschune on this issue.

**Comment by loganharbour** [comment]
@lindsayad can this be closed?

**Comment by lindsayad** [comment]
I'm thinking probably not

**Comment by GiudGiud** [comment]
I do that routinely now. And my PR #21607 enables it for the NSFV Action
Closing
