### ISSUE TITLE
Handle applications with custom syntax to inherit complete documentation

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#16868]
## Reason

Applications can have custom syntax, which includes removing the default syntax. For example, an application could remove the use of AddPostprocessorAction and use a different syntax with a different action: e.g., AddMyPPAction that operates on a `[PPs]` block. 

When inheriting documentation from the framework in such an application the AddPostprocessorAction.md causes failures, because of the various calls to the syntax: e.g.,`syntax parameters /Postprocessors/AddPostprocessorAction`. 

As is, there is no way to include the page in application documentation. But, this causes problems for SQA because the SQA documents for one application must include the SQA pages of all the apps that it uses. 

## Design

There are a few solutions that I am considering, but would like input from others.

1. Allow SQA documents to point to external websites, rather than a local build. This is probably ruled out because the documentation in the link would not be kept in sync with the application docs.
2. List all pages in the config.yml that have this problem and bypass the errors and output something useful in-place of the syntax commands. The problem with this is that if we add an object or system to MOOSE a documentation error would arise and require a patch to animals.
3. Allow parts of the "Contents" section in the config.yml to be flagged such that the syntax commands produce some information regarding the unavailable syntax, rather than error. This flag could potentially be automatically set based on the git repository information. I am leaning towards this option, because I don't immediately see a major problem. With the exception that this will require the most code development.

@idaholab/moose-ccb I am looking for some additional input, if you have any ideas. 

## Impact

Feature will result in a more flexible system for SQA in applications.

**Comment by rwcarlsen** [comment]
Option 3 seems the least bad to me I think.  But I haven't thought about it nearly as much as you.

**Comment by YaqiWang** [comment]
I feel that applications should not override the input syntax. If we have a herd application with two sub-applications both overriding the same input syntax, which one should we choose will be an issue. Applications can choose to inheritance syntax or not in its `MyApp` but it should not change the inherited syntax. Applications can always create new syntax.

**Comment by aeslaughter** [comment]
> I feel that applications should not override the input syntax.

This is not something we can control and it is already being done.

**Comment by YaqiWang** [comment]
Yes, we can control it. Just delete the function in MOOSE for doing this. But it will possibly require updates of some applications. We hit an issue in the past in BlueCrab where SAM overrides the add postprocessor action and causes bluecrab executable unable to drive lots of inputs.

**Comment by rwcarlsen** [comment]
I guess I'd be willing to consider how important this overriding is.  It certainly would be simplest and most robust to just not allow it.  @aeslaughter - do we have use cases where this feature is non-negotiable?

**Comment by aeslaughter** [comment]
> do we have use cases where this feature is non-negotiable?

Yes, SAM and any application that doesn't want to have all possible object combinations to exist. Perhaps an application only want to present the user with one or two equations that can be solved.

**Comment by aeslaughter** [comment]
Option 3 wasn't too bad to implement, pages that are marked external in the Content section of config.yml will disable the calls to syntax and put a warning at the top.

Is there a better name for the flag, besides "external"?

```
Content:
    - ${ROOT_DIR}/doc/content
    - framework:
            root_dir: ${MOOSE_DIR}/framework/doc/content
            external: True
```


![Screen Shot 2021-02-05 at 2 37 56 PM](https://user-images.githubusercontent.com/341333/107091955-d717ae80-67bf-11eb-9831-d41a12bae183.png)
