### ISSUE TITLE
pyhit init file missing imports

### ISSUE THREAD

**Issue by knw7x9** [idaholab/moose#16900]
## Bug Description
Add `import os` and `import subprocess` to init file for the pyhit module.

moose\python\pyhit\__init__.py:4: in <module>
    testdir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'test'))
E   NameError: name 'os' is not defined

## Steps to Reproduce
When `from . import hit` fails.

## Impact
It is preventing me from getting my work done.

**Comment by loganharbour** [comment]
> It is preventing me from getting my work done.

😆
