### ISSUE TITLE
How to test average interpolation of velocities in INSFV with its pressure oscillations

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#16918]
## Bug Description
When solving the Navier Stokes equations with an average interpolation of velocity, there is a decoupling in space between variables in the direction of flow, which results in oscillations. The solver is able to converge to a mass & momentum conserving solution regardless in most situations. However, recent test failures of #16767, #16911 show that the solution depends on the platform. Choosing a LU preconditioner will also fail on some tests, I presume it's because the problem is ill-conditionned. 

## Steps to Reproduce
Run modules/navier_stokes/postprocessors tests with average interpolation

## Impact
Impedes testing of average velocity interpolation. This interpolation method is generally not to be used for real simulations, as Rhie Chow is preferred.

**Comment by GiudGiud** [comment]
@aeslaughter how do I fix:
/opt/civet/build_1/moose/modules/navier_stokes/test/tests/postprocessors/tests:fv_straight:20
Test will not execute because it is marked as skipped or deleted
Control this message using: 'log_testable'
in SQA failures

**Comment by loganharbour** [comment]
> @aeslaughter how do I fix:
> /opt/civet/build_1/moose/modules/navier_stokes/test/tests/postprocessors/tests:fv_straight:20
> Test will not execute because it is marked as skipped or deleted
> Control this message using: 'log_testable'
> in SQA failures

You can’t have skipped/deleted tests.

**Comment by GiudGiud** [comment]
like you cant add new ones? You can only skip existing ones?

**Comment by loganharbour** [comment]
You can't have skip = at all

**Comment by lindsayad** [comment]
>  Choosing a LU preconditioner will also fail on some tests, I presume it's because the problem is ill-conditionned.

Did it fail even with `-pc_factor_shift_type NONZERO`?

**Comment by GiudGiud** [comment]
yes

**Comment by lindsayad** [comment]
If it still fails (which I think they should still fail... we haven't changed any solve behavior), then I'd definitely be interested in the result of `-pc_type svd -pc_svd_monitor`

**Comment by GiudGiud** [comment]
This was the fail:
https://civet.inl.gov/job/676642/

pc_type svd is as follow:

**Comment by GiudGiud** [comment]
Ok it passes with LU but not asm. 
I'll switch it over to LU

**Comment by lindsayad** [comment]
Ok with the knowledge that the problem is nonsingular, we should be able to solve it somehow. At least on my machine locally, this `fv-straight` test runs fine with `-pc_type lu -pc_factor_shift_type NONZERO` with all our tested mixes of distributed, parallel, and threads.

**Comment by lindsayad** [comment]
Oope seconds apart...I already pushed

**Comment by GiudGiud** [comment]
Ok good. Should be good for the PR then.

**Comment by GiudGiud** [comment]
Through time and experience solution to this is:
- dont use average interpolation when possible
- high tolerances when you must
