### ISSUE TITLE
Don't use MUMPS in a couple of PorousFlow examples

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#16951]
## Reason

MUMPS is great, but some people don't have MUMPS installed.  I don't need to use it in 
```
examples/tutorial.13 ...................................................................... [MUMPS!=TRUE] SKIP
examples/thm_example.2D ................................................................... [MUMPS!=TRUE] SKIP
```

## Design

Just remove the "skip" in the `tests` file and modify the input files accordingly

## Impact

1. More thorough testing (these two tests will run on machines without mumps after this issue is fixed)
2. Ability to run these examples for users who don't have mumps

**Comment by loganharbour** [comment]
Please update with an impact 😬
