### ISSUE TITLE
PorousFlow: at_nodes parameter needed in specialized situations

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#17025]
## Reason

In recent PR #16995, i found that the `at_nodes` parameter was needed in `modules/combined/examples/geochem-porous_flow/forge/porous_flow.i`, viz:

```
  [./relperm] # this is necessary because of the use_mobility = true used in the PorousFlowPeacemanBorehole objects
    type = PorousFlowRelativePermeabilityConst
    at_nodes = true
    phase = 0
  [../]
```

The `at_nodes` parameter is supposed to be invisible to users, but this is a special situation where it is currently necessary.  It'd be nice to make it invisible.

## Design

It would be nice if the `at_nodes` parameter didn't need to be specified.   Hopefully @cpgr can do something magical with his Actions.

## Impact

Ease of use of PorousFlow, since `at_nodes` is a complication that we had hoped to hide from users.

**Comment by cpgr** [comment]
I'll fix this up Andy

**Comment by WilkAndy** [comment]
Hey @loganharbour , could you assign this to @cpgr ?   (I'm not sure how Chris works, but i often look on github to see what's assigned to me, maybe Chris does the same, so this will remind him about this issue.)   No rush, @cpgr - obviously no one has noticed this in the last few years of PorousFlow!

**Comment by cpgr** [comment]
I was waiting on your PR to go through before starting. Will fix this tonight

**Comment by WilkAndy** [comment]
@cpgr, it's not super urgent!  Don't feel you need to do it in the evening.

**Comment by cpgr** [comment]
I think I have figured out how to fix this. I'll make sure it works properly before pushing the fix

**Comment by WilkAndy** [comment]
Well done.  This stuff is quite complicated.  I bet the number of changes are tiny, but super hard to figure out which lines to change.

**Comment by WilkAndy** [comment]
I'm just going through all my "old" issues.  did you figure this out @cpgr ?

**Comment by cpgr** [comment]
It turns out it was getting too hard with the various different actions and sinks that could lead to this problem, especially in regards to rel perm. I thought that the easiest thing would be just to add a nodal rel perm material just in case it is needed for objects that have `use_mobility` or `use_relperm`, as it isn't very expensive to compute. Thoughts?

**Comment by WilkAndy** [comment]
Yea, i think that's fine, except we should document it all-over-the-place so that future people know what we've done.

a

________________________________________

**Comment by cpgr** [comment]
I'll do that then - it's something easy for me to do with one hand!
