### ISSUE TITLE
Uniformize PorousFlow test-file syntax

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#17024]
## Reason

As mentioned by @cpgr  in #16995, some PorousFlow test/example files have

```
[blah]
  blah
  blah
[]
```

while others have

```
[./blah]
  blah
  blah
[../]
```

## Design

Use the former syntax everywhere

## Impact

Uniform look-and-feel will help new users

**Comment by loganharbour** [comment]
FYI - we plan on eventually using consistent HIT formatting everywhere and enforcing it on PRs. Not quite there yet, unfortunately.

**Comment by WilkAndy** [comment]
What's "Hit formatting" ?
