### ISSUE TITLE
Finite volume Rhie-Chow coefficients for weakly compressible flow

### ISSUE THREAD

**Issue by joe61vette** [idaholab/moose#17046]
## Reason

Many flow applications involve a range of fluid states from subcooled liquid (nearly incompressible) to vapor flow where the density is significantly affected by the gravitational head.  INSFV can handle the incompressible flow situation.  The upcoming CNSFV will be able to handle the compressible case for high-speed flows where continuity across shocks is important. However, there is not an option for a flow model for weakly compressible conditions (Ma < 0.3) that is capable of spanning the range of fluid states.  Such a flow model would be cast in terms of primary variables (P, V, T) and require the usage of Rhie-Chow interpolation to avoid the checkerboard effect due to variable collocation.

The current implementation of Rhie-Chow in INSFV is tailored to the assumptions governing incompressible flow, namely that the fluid density is constant in space.  For a weakly compressible flow model, it would need to be reformulated to be consistent with a density that can vary spatially.  This issue is related to https://github.com/idaholab/moose/issues/16809.

## Design

The RC coefficients are evaluated at the element centroids and used in FV flux kernels.  The proposed way to handle this would be to instance an RC material property.  The flux kernels would then access the RC material property for both "elem" and "elem_neighbor".  The implementation difficulty is due to the necessity for the RC calculation to be able to access the density from all of the neighboring elements in addition to the cell-centered velocities.  What is needed is the capability to fetch a material property in much the same way as a FV variable can be accessed.  Namely:

     neighbor_velocity(_u_var->getNeighborValue(neighbor, *fi, elem_velocity(0)))

## Impact

The enhancement would add a new capability enabling the development of both single-phase and multi-phase FV flow models for weakly compressible (Ma < 0.3) flow conditions.

**Comment by lindsayad** [comment]
@joe61vette I just re-read this issue today, and you put the issue so perfectly! Note that I've referenced this issue in our road-map super-issue #18215. I'm starting to at least think about development for this because the unphysical diffusivity of our CNSFV implementations in #17900 for law Mach numbers is simply not acceptable

**Comment by lindsayad** [comment]
closed by #18563
