### ISSUE TITLE
Do not compute aux vars, matl props as part of damping

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#1706]
The process of computing dampers currently involves computing auxiliary variables (and material properties).  This is problematic since the damping system is meant to limit large changes in solution variables and may be used to prevent these large changes from reaching material classes.

A better approach would be to compute aux vars and material properties selectively based on whether the damping needs them.

**Comment by permcody** [comment]
Closed in https://github.com/idaholab/moose/commit/d7f14bfbe816d653afaec0d696b642b0adc03fed
