### ISSUE TITLE
Finite volume interface kernels for porosity jumps, contact, ..

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#17087]
## Reason
For many different physics, we do not want to resolve sharp transitions at interfaces with the mesh, and would rather introduce a discontinuity that captures this transition. 

## Design
A kernel that only contributes to the residual on faces that belong to an interface. 
There will probably be many similarities to FVFluxKernels, which only act on (all element's) faces. 

## Impact
Huge boost to finite volume modeling of nuclear reactors

**Comment by lindsayad** [comment]
@GiudGiud the way I handled this for CNSFV was to apply the divergence theorem to the epsilon * grad_pressure term. The resulting epsilon*pressure should be much smoother so I just use the same epsilon-pressure `FVFluxKernel` across the whole domain with no special treatment at porosity jump interfaces.

**Comment by lindsayad** [comment]
Although the math is not quite right on that, is it...

**Comment by lindsayad** [comment]
Actually the math is good as long as epsilon doesn't have a gradient within a cell. If it does, then you would need an additional term:

-\int Ip * \nabla \epsilon dV

The problem is in implementation...we know that Green-Gauss computations of either grad_p or grad_eps will be problematic near interfaces where both p and eps are discontinuous

**Comment by GiudGiud** [comment]
What do you do at boundaries then? Is that kernel executed on boundaries?

I think Paolo wanted to have the option to define a form loss coefficient too. 

We dont need grad_eps for this term?

**Comment by lindsayad** [comment]
But at least in the case of epsilon it will almost always be constant within cells or at worst have a user-prescribed function with in a cell whose gradient is clearly defined...e.g. we wouldn't have to do Green-Gauss with information from discontinuous faces

**Comment by lindsayad** [comment]
> What do you do at boundaries then? Is that kernel executed on boundaries?

Yes in general this `FVFluxKernel` or rather a `FVFluxBC` relative must be executed on boundaries.

> I think Paolo wanted to have the option to define a form loss coefficient too.

In this case we would want a `FVInterfaceKernel` for sure

> We dont need grad_eps for this term?

Which term?

**Comment by GiudGiud** [comment]
The momentum pressure term.
