### ISSUE TITLE
Update to Python 3.9

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#17105]
## Reason
The packages we require in Conda which allows Peacock to function, have progressed to using Python 3.9. These new libraries are also required while using Peacock in MacOS Big Sur.

## Design
Bump the Python version allowed in moose-tools

## Impact
We will be keeping up to date with Conda's library stacks, as well as allowing Peacock on Big Sur to function

**Comment by mangerij** [comment]
Older python3 will still be supported right?

**Comment by milljm** [comment]
Indeed!
