### ISSUE TITLE
Inconsistent automatic differentiation and automatic scaling behavior

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#17138]
## Bug Description
When using automatic scaling, sometimes the initial residual differs based on whether AD is being used or not.  If automatic scaling is off, the AD and non-AD initial residuals are equal.

## Steps to Reproduce
[debug.txt](https://github.com/idaholab/moose/files/6044465/debug.txt)
Run the attached file as is.  Then run as 'app-opt -i debug.txt Materials/matprop/type=ADParsedMaterial Kernels/var_a/type=ADMatDiffusion Kernels/var_b/type=ADMatDiffusion'.  The initial residuals do not match.  If you comment out Executioner/automatic_scaling and run again (non-AD and AD), the initial residuals match.

## Impact
I don't know how many cases are being affected by this or how severely this affects results, but it is confusing at best.  I tried many things in an attempt to get the initial residuals to match and stumbled upon commenting out automatic scaling.

**Comment by lindsayad** [comment]
@jasondhales seems like you're doing a fair amount of technical work lately which I'm happy to see! I will try to look into this ASAP

**Comment by lindsayad** [comment]
So this is actually behaving exactly as it should. Here are the different scaling factors:

hand:
Automatic scaling factors:
  var_a: 2.29446e+08
  var_b: 2.29446e+08

AD:
Automatic scaling factors:
  var_a: 1.99667e+08
  var_b: 2.29446e+08

What's the reason for the difference? The difference comes from the fact that `ADParsedMaterial` computes derivatives of `matprop` with respect to `var_a` and then this derivative information gets fed to the Jacobian, which is what is used to determine automatic scaling factors. `ParsedMaterial` does not compute those derivatives and there is no communication of the dependence of `matprop` on `var_a` into the Jacobian and consequently the scaling factors.

**Comment by lindsayad** [comment]
I should also note that it is the Jacobian *diagonal* that is used for computing scaling factors, which is why we don't see the scaling factor for `var_b` get modified

**Comment by jasondhales** [comment]
@lindsayad thanks for investigating this, and thanks for the explanation.  I obviously assumed that AD and automatic scaling were independent.  Makes sense now.
