### ISSUE TITLE
Check InterfaceMaterial dependence resolution

### ISSUE THREAD

**Issue by arovinelli** [idaholab/moose#17171]
## Bug Description
I don't know if this is bug or not, but we don't have tests for checking `InterfaceMaterial` dependence resolution.
So appropriate tests should be added

## Steps to Reproduce
Example about what was trying to do and didn't worked out properly (possibly because of this issue):
InterfaceKernel consumes property from `interfacematerial1`
`interfacematerial1` needs update properties from `interfacematerial2` and `interfacematerial3`
`interfacematerial2`  needs update properties from `interfacematerial3`
`interfacematerial3` use a coupled variables to generate the required properties.

The execution order was the following at every step (printed out from screen).
interfacematerial2::computeQpProperties()
interfacematerial3::computeQpProperties()
interfacematerial1::computeQpProperties()

## Impact
Prevents from designing more modular code.

@lindsayad is already aware of this, as per our conversation on slack.

**Comment by lindsayad** [comment]
are stateful properties involved?

**Comment by arovinelli** [comment]
> are stateful properties involved?

neither stateful properties nor old variables.
