### ISSUE TITLE
Remove unused temperature from TensorMechanics action

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#17186]
## Reason
I'm _fairly_ certain that the `temperature` input parameter for the `TensorMechanicsActionBase` isn't actually used anywhere in that class or its derived classes. As a very new users, this is somewhat confusing as to its purpose (since all the tests still pass a `temperature` in to avoid `--no-warning` failures).

## Design
Remove the `temperature` parameter from `TensorMechanicsActionBase` and update any tests to remove the extraneous info.

## Impact
More straightforward understanding of the action system.

**Comment by bwspenc** [comment]
I'm pretty sure that the reason temperature is there is because that is needed for creation of the off-diagonal Jacobian entries when you have thermal eigenstrains. The problems probably all still run when you don't provide it, but they converge better if you include that parameter (and you are using the off-diagonal entries in the preconditioning matrix). Let me check on that, though.

**Comment by loganharbour** [comment]
> I'm pretty sure that the reason temperature is there is because that is needed for creation of the off-diagonal Jacobian entries when you have thermal eigenstrains. The problems probably all still run when you don't provide it, but they converge better if you include that parameter (and you are using the off-diagonal entries in the preconditioning matrix). Let me check on that, though.

After looking at the BISON convergence failures in the PR associated with this one, I think this is correct.

**Comment by aprilnovak** [comment]
Really? But all I did was remove an input parameter - nothing was even coupled in to the "temperature" parameter:

The only source code change is here: https://github.com/idaholab/moose/pull/17187/files#diff-9498edbb8c31b0cd0bcac600fcb189e04f1ec3bd0dcbe25939d876a9103eeb0e:~:text=modules%2Ftensor_mechanics%2Fsrc%2Factions%2FTensorMechanicsActionBase.C

**Comment by bwspenc** [comment]
It's because it's applied with `applyParameters()`, so there's actually no code in the Action needed to handle it.

**Comment by aprilnovak** [comment]
Ah, my mistake then - I didn't notice that! When I removed it, all the tests passed in tensor mechanics so I figured it was ok to delete

**Comment by bwspenc** [comment]
No worries, it's not terribly obvious. I wish there were a better way to handle this.

**Comment by loganharbour** [comment]
It may be worth in the future at least adding a comment in the parameter/source as to why this is done
