### ISSUE TITLE
Allow multiple target/source boundaries in MultiAppNearestNodeTransfer

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#17214]
## Reason
For more complicated inputs with Cardinal, I often want to transfer temperatures on two boundaries in a master app to two boundaries in a sub-app. This transfer can be much faster if I set a `target_boundary` and `source_boundary` with the `MultiAppNearestNodeTransfer`. However, for multiple boundaries, this requires you to split up the transfer for each individual boundary like this:

```
[to_sub1]
  type = MultiAppNearestNodeTransfer
  source_boundary = '5'
  target_boundary = '3'
[]
[to_sub2]
  type = MultiAppNearestNodeTransfer
  source_boundary = '10'
  target_boundary = '4'
[]
```

But this isn't really a workaround either, for (at least) two reasons:

1. This splitting will be wrong for elemental transfers (which do not actually use the `target_boundary` parameter), because whatever transfer is listed last will overwrite the ones before it. 
2. If there isn't a neat correspondence between the boundaries in the master and sub apps, the transfer will be wrong. For instance, suppose there's a domain in the master and sub apps that has boundary IDs labeled like this:

```
master: |------ 5 ------|----------------- 10 --------------------|
sub:    |---------------3------------|-----------------4----------|
```

Then, even though you want to transfer from boundaries 5+10 as a group to boundaries 3+4 as a group, you can't do this correctly because boundary 5 cannot be exactly matched to 3, and boundary 10 cannot be exactly matched to 4. 

## Design
Allow a vector of boundary IDs to be provided for both the `source_boundary` and `target_boundary`. This will basically involve expanding the bounding boxes for the source boundary to consider multiple boundaries, and the target nodes to be pushed to for multiple boundaries.

## Impact
More flexibility in transfers, and correcting wrong behavior in any inputs that met either of conditions (1) or (2) above.

**Comment by GiudGiud** [comment]
#17417 should address this, it supports multiple boundaries for NN and ShapeEvaluation (ex- MeshFunction)
