### ISSUE TITLE
Make ADDensity::_initial_density a protected attribute

### ISSUE THREAD

**Issue by helen-brooks** [idaholab/moose#17227]
Currently the attribute `_initial_density` in the material class `ADDensity `(in modules/misc) is private, whereas the equivalent attribute `_orig_density` in the non-AD material, `Density,` is already declared as protected.  It would be desirable to make `  _initial_density `a protected attribute, not just because it makes the two classes more comparable, but also so that inherited classes will have access to this member. 

The use case for this is that in the application I am developing it is relevant to know the relative density change, and therefore it is useful to know what was the original density assignment for a given material.

This change should not  give rise to any external behaviour changes. Although the attribute will be accessible to derived classes, since it is already declared as a const it cannot be modified so there is no danger of side effects.

**Comment by loganharbour** [comment]
Closed in #17199
