### ISSUE TITLE
Varying Output Frequency with time

### ISSUE THREAD

**Issue by mooseframework** [idaholab/moose#1728]
To vary the time step interval for output associated with the actual simulation time. For example, during the first 300 s, I would like to output every time step, but for the rest of the time, I would only output once every 5 or 10 time steps.

**Comment by permcody** [comment]
Please reference a ticket or give a supporting reason to close this issue.

**Comment by aeslaughter** [comment]
TimePeriod objects capable of this where added in ca5fff07f51ea31e98794d0e8cbeb7a4ebeac873

**Comment by aeslaughter** [comment]
Also, you can do this same thing with the Output object 'start_time' and 'end_time' parameters and multiple output blocks (see https://github.com/idaholab/moose/blob/devel/framework/src/outputs/Output.C)
