### ISSUE TITLE
Input file substitution not working in GlobalParams block

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#17291]
## Bug Description
Dollar bracket substitution does not appear to be occurring in some cases.

## Steps to Reproduce
At the top of my input I have:
```
interp_method='upwind'
```
and then I have this `GlobalParams` block:
```
[GlobalParams]
  flux_interp_method = ${interp_method}
  interp_method = ${interp_method}
[]
```
When I execute this input I get the error:
```
*** ERROR ***
Invalid option "${interp_method}" in MooseEnum.  Valid options (not case-sensitive) are "average upwind".
```
It's as if the bracket substitution is not occurring.

## Impact
This hinders me from writing single input files that can be easily reused with different interpolation schemes, but this is a much more general issue than that. Maybe I'm doing something wrong, but whatever I'm doing wrong is not intuitive from the error message.

Halp @rwcarlsen

**Comment by lindsayad** [comment]
If I do the substitutions in blocks other than `GlobalParams` this works. I've updated the title accordingly

**Comment by rwcarlsen** [comment]
I think there might be some shadowing going on here.  What if you rename your top-level param to `global_interp_method`?

**Comment by lindsayad** [comment]
Yes that works

**Comment by rwcarlsen** [comment]
Yeah - so your `foo = ${foo}` is just replacing `${foo}` with the contents of itself :P

**Comment by rwcarlsen** [comment]
So I wouldn't call this a bug - it is working as designed - but it is definitely worth reconsidering the design.  In general we probably don't want to allow substitution to pull from the parameter the substitution expression is in.

**Comment by lindsayad** [comment]
Why is `GlobalParams` different though? I put `advected_interp_method = ${advected_interp_method}` in other blocks all the time. Are `GlobalParams` and global scope params handled in the same way? Is that delineation I should draw? On the one hand, global scope params + "GlobalParams", and on the other hand, all the other block params?

**Comment by rwcarlsen** [comment]
It should be the same.  I failed to reproduce this problem using mods to simple_diffusion.i.

**Comment by lindsayad** [comment]
Same. Also failed with a MOOSE test with an object that has a `MooseEnum` param, so the `MooseEnum` param is not the problem. Maybe it is just a bug in my input yet undiscovered. I'll close for now.
