### ISSUE TITLE
Add custom FunctionExpression type to some contexts

### ISSUE THREAD

**Issue by brandonlangley** [idaholab/moose#17325]
## Bug Description

   In #9752, a custom FunctionExpression type was added to parameters improving the input validation of NEAMS Workbench:

   1. /blocks/AuxKernels/star/subblock_types/ParsedAux/parameters/function/cpp_type/value ("FunctionExpression")

   2. /blocks/Bounds/star/subblock_types/ParsedAux/parameters/function/cpp_type/value ("FunctionExpression")

   3. /blocks/Functions/star/subblock_types/ParsedFunction/parameters/value/cpp_type/value ("FunctionExpression")

   4. /blocks/UserObjects/star/subblock_types/Terminator/parameters/expression/cpp_type/value ("FunctionExpression")

   However, there are still JsonSyntaxTree parameters with the wrong std::string cpp_type instead of FunctionExpression:

   1. /blocks/Materials/star/subblock_types/ADDerivativeParsedMaterial/parameters/function/cpp_type/value ("std::string")

   2. /blocks/Materials/star/subblock_types/ADParsedMaterial/parameters/function/cpp_type/value ("std::string")

   3. /blocks/Materials/star/subblock_types/DerivativeParsedMaterial/parameters/function/cpp_type/value ("std::string")

   4. /blocks/Materials/star/subblock_types/ParsedMaterial/parameters/function/cpp_type/value ("std::string")

   5. /blocks/ScalarKernels/star/subblock_types/ParsedODEKernel/parameters/function/cpp_type/value ("std::string")

## Steps to Reproduce

   Examine the JSON input definition dump produced from running MOOSE with the --json command line parameter.

## Impact

   NEAMS Workbench translates the JSON into a schema for MOOSE application input validation and autocompletion assistance.

   MOOSE application specifications correctly using any of the input components noted above are being reported as invalid.

**Comment by brandonlangley** [comment]
@permcody -

I believe this should be a simple update like the one @brianmoose made [here](https://github.com/idaholab/moose/pull/9752/commits/e5435489c79488ae578221fdeb3c6286332c10b1) in 2017.

There are a handful of functions in various inputs that are trying to be validated as strings.

I think the custom FunctionExpression type only needs to be added to the few places I listed.

Could this be added to the [FY 21 NEAMS Multiphysics Technical Assistance Support](https://github.com/idaholab/moose/projects/8) Project?

**Comment by dschwen** [comment]
Sounds like a 5 moon job. I'd be happy to do this , as it seems to affect
only classes written by me :-)
