### ISSUE TITLE
Peacock switches variables when rerunning simulation

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#1735]
I've found that if I have the "elemental_as_nodal" option enabled and I'm viewing an elemental variable in the visualizer, peacock will switch to the nodal version if I return to the execute tab and run it again.  You must have some logic in there that selects the variable by name and it fails to select the right version.  Take a look at tests/auxkernels/element_aux_var_test.i

**Comment by permcody** [comment]
@brianmoose - This was a really annoying bug in the old peacock. I doubt it's in the new one. In fact. Feel free to click on the "Peacock" label and look at all the open issues. We just aren't going to fix them in the old peacock but it'd be nice to make sure that they aren't issues in the new peacock.

**Comment by brianmoose** [comment]
Yes, this should work in the new peacock. I believe @aeslaughter even has a test for it.

**Comment by permcody** [comment]
@brianmoose - Go ahead an close these that you know are fixed. Just make sure you say something for auditing purposes.
