### ISSUE TITLE
Address performance degradation for many multi-apps

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#17378]
## Reason
Between `7bf83a6dac` and `d059e681c8`, there is a huge reduction in performance for inputs that use large numbers of multi-apps, such as using a `CentroidMultiApp` on a master app mesh with a not-so-huge number of elements. Those two git hashes directly enclose the merging of #17213.  

We noticed a slowdown of between 25x (opt mode) and 100x (debug mode) in a syntax test in Pronghorn for an input that creates a heat conduction app in every element in the master app; this is causing a debug failure in Pronghorn. 

You can also reproduce the slowdown using just MOOSE tests - increase the mesh in the `test/tests/multiapps/centroid_multiapp/centroid_multiapp.i` test to have `nx = 50` and `ny = 10` so that there's a high number of sub-apps. Then make the test just a `RunApp` test (so that none of the runtime is associated with the solve on the larger mesh):

```
[Tests]
  [./test]
    type = RunApp
    input = 'centroid_multiapp.i'
    check_input = true
  [../]
[]
```

With this change, I see a factor of 50x slowdown in `opt` mode and 100x in `dbg` mode. Here's the `opt` mode results:

```
~/projects/moose/test:d059e681c8 ✗ ➭ ./run_tests --re=centroid_multiapp
multiapps/centroid_multiapp.test ..................................................................... RUNNING
multiapps/centroid_multiapp.test ...................................................... [FINISHED] SYNTAX PASS
--------------------------------------------------------------------------------------------------------------
Ran 1 tests in 51.3 seconds. Average test time 49.6 seconds, maximum test time 49.6 seconds.
1 passed, 0 skipped, 0 pending, 0 failed



~/projects/moose/test:7bf83a6dac ✗ ➭ ./run_tests --re=centroid_multiapp
multiapps/centroid_multiapp.test ................................................................. SYNTAX PASS
--------------------------------------------------------------------------------------------------------------
Ran 1 tests in 2.6 seconds. Average test time 0.8 seconds, maximum test time 0.8 seconds.
1 passed, 0 skipped, 0 pending, 0 failed
```

## Design
Somehow fix the slowdown.

## Impact
Allow Pronghorn's debug tests to pass and achieve reasonable setup times for our larger runs. 

tag @andrsd @snschune

**Comment by loganharbour** [comment]
This change has only added time when checking input, right? Because we went from not creating the applications to creating them? I suspect that #17213 didn't change full solve times, just the bare-bones (syntax check) runs.

Is that correct?

**Comment by aprilnovak** [comment]
Oh yeah, you're totally right. We saw the debug error and concluded that, because this is one of our heaviest tests (we don't run the actual test in our test suite, just the syntax check) that the failure was due to high numbers of multiapps.

Do you suggest just making the timeout higher for this Pronghorn test? Or perhaps restricting it to just `opt` mode?

**Comment by loganharbour** [comment]
Hmm, if it's just syntax checking I think that leaving it to opt is sufficient in this case. We do want to avoid _extremely_ long tests as much as possible. In reality, I'd actually like to decrease the allowed timeouts on a per-application basis, but that's a whole other story 😬 

Good news is, I think that in this case the extra time is worth it seeing that we're now properly running syntax checks on the multiapps as well.

**Comment by aprilnovak** [comment]
Ok we'll restrict the test to opt mode then - thank you for clearing this up! Very glad that it's just a misunderstanding on our end :)
