### ISSUE TITLE
Addition of wrap markers around SON definition dump

### ISSUE THREAD

**Issue by brandonlangley** [idaholab/moose#17395]
## Reason

NEAMS Workbench uses the `--definition` option to make an input validation and autocompletion schema for MOOSE apps.

However, applications control their own header that is printed before all output - including the output of `--definition`.

Any app can override the virtual `MooseApp::header()` method (which is empty by default) with its own custom header.

For example, BISON's header / banner contains:
 - ASCII art and lab info 
 - a `NOTICE` section
 - an `EXPORT RESTRICTIONS` section
 - the BISON version with the `git commit`

This header is always printed early in `MooseApp::setupOptions()` and is not togglable for specific command line options:

```
  // Print the header, this is as early as possible
  std::string hdr(header() + "\n");
  if (multiAppLevel() > 0)
    MooseUtils::indentMessage(_name, hdr);
  Moose::out << hdr << std::flush;
```

So, Workbench must first strip off the header / banner (if it exists) from the `--definition` output to get the actual schema.

With BISON for example, it currently uses logic specific to to the `BisonApp::header()` mentioned above to strip everything before and including the `git commit` line.

With other apps able to define their own custom headers, Workbench may not be able to strip this header in a general way.

## Design

The Moose::out print line for the --definition option in MooseApp::setupOptions() will be updated.

Special SON comment marker lines will be added before and after the SONDefinitionFormatter output.

This will allow any headers and banners to be scraped from schemas of all MOOSE apps consistently.

A RunApp test will also be added making sure these markers are in the produced schema as expected.

## Impact

The NEAMS Workbench can use the validation and autocompletion schema produced with `--definition` by any MOOSE app in a general way without needing application specific logic to remove custom header information.

**Comment by brandonlangley** [comment]
@permcody -

This is the issue you asked me to open during our Workbench / MOOSE integration testing meeting last week.

This will also help generalize the integration testing of any MOOSE app and Workbench.

Could this be added to the [FY 21 NEAMS Multiphysics Technical Assistance Support](https://github.com/idaholab/moose/projects/8) Project?

**Comment by dschwen** [comment]
For the JSON stuff we use start stop markers to make the scraping really
easy.
