### ISSUE TITLE
Ansys mesh cannot be used in moose

### ISSUE THREAD

**Issue by liangyu-psi** [idaholab/moose#17412]
## Bug Description
The mesh generated by ICEM or Ansys Mesh cannot be recongized by MOOSE.

## Steps to Reproduce
The format of mesh is .msh. It's will cause a dimension error.
But when I use Gmsh. Although the format is still .msh, it will be recongized by MOOSE.

## Impact
It's not convenient to create a mesh by familiar software. I don't know if the mesh file of Ansys does not meet the MOOSE standard. Hope someone can answer. Many thanks.

**Comment by liangyu-psi** [comment]
Is there anybody know the reason?

**Comment by dschwen** [comment]
You might be confusing a file extension with a mesh format. While both files end in .msh they might not be the same format at all. Is there a different format you could export your mesh to with Ansys?
