### ISSUE TITLE
Sodium properties cannot be used in Porous flow module

### ISSUE THREAD

**Issue by liangyu-psi** [idaholab/moose#17411]
## Bug Description
I'm learning moose not long ago. I don't know if it is a bug.
I can't use SodiumProperties in porous flow calculation.
I have open the porousflow module and fluid properties module in makefile.

## Steps to Reproduce
I tried to exchange the fluid property used in one example of porous flow. The address of that example is shown below.
GitHub\moose\modules\porous_flow\examples\tutorial\05.i
The original property is water. I want to use SodiumProperties instead.
So I just change the following sentence:

```
[Modules]
  [./FluidProperties]
    [./the_simple_fluid]
      type = Water97FluidProperties
    [../]
  [../]
[]
into:
[Modules]
  [./FluidProperties]
    [./the_simple_fluid]
      type = SodiumProperties
    [../]
  [../]
[]
```

But it will cause a 'Segmentation fault'.

## Impact
I don’t know if I made a mistake, because I found that it’s okay to use CO2FluidProperties.
I am a rookie, which prevents me from carrying out the next step. I hope every expert can answer it. Thank you very much.

**Comment by WilkAndy** [comment]
@cpgr or @andrsd , can you comment?  To me it looks like SodiumProperties wasn't setup for this kind of thing.

**Comment by WilkAndy** [comment]
@liangyu-psi , can you please comment on whether this is impacting your work a lot, or whether you were just trying it out of interest?

**Comment by liangyu-psi** [comment]
> @ liangyu-psi，您能否评论一下这是否对您的工作有很大影响，还是只是出于兴趣而尝试？

Thanks for your reply. Yes. It does have a certain impact. I‘m trying to use MOOSE to calculate such porous flow problems.

**Comment by liangyu-psi** [comment]
> @liangyu-psi , can you please comment on whether this is impacting your work a lot, or whether you were just trying it out of interest?

Thanks for your reply. Yes. It does have a certain impact. I‘m trying to use MOOSE to calculate such porous flow problems

**Comment by andrsd** [comment]
The `SodiumProperties` class you speak of was built for some specific simplified case and was not meant to be used within the subsystem of `SinglePhaseFluidProperties` hierarchy. However, I know there is a class that implements sodium properties at saturation conditions that can be used with `SinglePhaseFluidProperties` subsystem. You would probably need to implement some methods to gain full compatibility with porous flow.

If you want, I can ping the authors if they would be willing to contribute this class into `fluid_properties` module. Let me know.

**Comment by cpgr** [comment]
A quick workaround in the meantime could be to just create a table of values in a csv file for the properties you want and then use `TabulatedFluidProperties`? Wouldn't take long to do I wouldn't think?

**Comment by liangyu-psi** [comment]
@andrsd Thanks for your kindly reply! Yes, it would be nice if the authors are willing to contibute complete soidum proterties for **SinglePhaseFluidProperties**. Hope they can updated this class.

**Comment by aprilnovak** [comment]
@liangyu-psi I am working on adding sodium properties based on the `SinglePhaseFluidProperties` base class - I will have an implementation soon, and will reference this issue when the implementation is ready.

**Comment by liangyu-psi** [comment]
@aprilnovak Thank for your excellent contribution!

**Comment by aprilnovak** [comment]
@liangyu-psi, I am unfamiliar with the porous flow module - do the new sodium properties contain all of the functions you'll need? https://github.com/idaholab/moose/pull/17563

If not, please let me know and I can try to add the additional functions you need.

**Comment by liangyu-psi** [comment]
@aprilnovak Yes. It contains all of the required functions. I want to use and check the new properties you added. I tried to update MOOSE. But, I can not find the new file named SodiumSaturationFluidProperties. Could you tell me how to use your property file? Or, may I need to copy it to my App?
I also add some required properties and I can compare both properties to ensure the correctness.

**Comment by aprilnovak** [comment]
Hi @liangyu-psi , the new properties haven't been merged yet into MOOSE; once it is merged, then all you'll need to do is update MOOSE again. 

You can access the new properties (before they're merged) by either checking out the `sodium-props` branch on my [MOOSE fork](https://github.com/aprilnovak/moose/tree/sodium-props) or you could copy the source files from my open PR locally for the time being.

**Comment by liangyu-psi** [comment]
Hi. @aprilnovak , that's cool. I copy source files and it works. Let me check the correctness first.

**Comment by liangyu-psi** [comment]
@aprilnovak 
The files you write are very professional！
Some properties are not very accurate. Maybe you can refer to the following reference to get accurate properties.
### 'Sodium Coolant Handbook: Physical and Chemical Properties , IAEA, 2018'
When temperature over 1600K, the density seems not that exact. Maybe you can use original one recommended by Fink and Leibowitz.
```
{density = 219.0 + 275.32 * (1 - temperature / 2503.7) + 511.58 * sqrt(1 - temperature / 2503.7);
drho_dp = 0.0;
drho_dT = -275.32 / 2503.7 - 511.58 / 2.0 / 2503.7 / sqrt(1 - temperature / 2503.7);}
```
The same as v_from_p_T.
The enthalpy almost the same as Fink, but it still has some error.
```
  if (temperature > 371 && temperature < 2000)
  {
    Real hliqsa = (-365.77 + 1.6582 * temperature - 4.2375e-4 * temperature
                  * temperature + 1.4847e-7 * temperature * temperature
                  * temperature + 2992.6 / temperature) * 1000.0; // 1000 for KJ/kg/K to J/kg/K
    return hliqsa;
  }
  else
  {
    Real hliqsa = (2128.4 + 0.86496 * temperature - 0.5 * (393.37 * (1 - temperature
                  / 2503.7) + 4398.6 * pow((1 - temperature / 2503.7),0.29302)))
                  * 1000.0; // 1000 for KJ/kg/K to J/kg/K
    return hliqsa;
  }
```
Cp, Cv, K, Mu, the results of these parameters do not deviate too much from the results recommended in the reference.
If you want, you can fit a more accurate formula based on the data in that reference mentioned above.

Thanks again for your huge contribution to sodium properties.

**Comment by aprilnovak** [comment]
Hi @liangyu-psi, the properties I implemented are the models used in SAM, another MOOSE application that we would like to use these sodium properties with. You are of course welcome to add additional sodium property models as a derived class of `SodiumSaturationFluidProperties` if you want to use other correlations for rho and enthalpy.

**Comment by aprilnovak** [comment]
I should also note that at 1600 K, sodium is well above the boiling point; these models correspond to saturated liquid conditions.

**Comment by liangyu-psi** [comment]
@aprilnovak Oh, I see. I just checked the SAM User's Guide. 
You are right. Working conditions which are higher than the boiling point are rare, especially above 2000K. 
Under normal circumstances, the influence of these deviations on the final calculation may not be very large.
