### ISSUE TITLE
Moosedocs not including list of input files for templated classes

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#17426]
## Bug Description
For classes such as GenericConstantMaterial that use templating to create non-AD and AD versions, the corresponding documentation pages do not contain a list of input files that use the class even though '!syntax inputs ...' appears in the .md file.

## Steps to Reproduce
See https://mooseframework.inl.gov/source/materials/GenericConstantMaterial.html as an example.

## Impact
Lessens the effectiveness of the documentation pages and makes them inconsistent.

**Comment by aeslaughter** [comment]
MooseDocs uses a regex to look for C++ class inheritance. It likely just needs to be expanded to include these types of templates.
