### ISSUE TITLE
The Reporter system does not support getting a value before it is declared

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#17468]
## Bug Description

If a ReporterValue is declared in initialSetup a reference cannot be defined in another objects constructor.

## Steps to Reproduce

A test showing the problem will be added to this Issue.

see https://github.com/aeslaughter/moose/commit/321469c564042a214df8b955cef1220781f51f8d

## Impact

Reduces the flexibility of the Reporter system.

**Comment by aeslaughter** [comment]
@zachmprince Is the solution as simple as running the Reporter check after initialSetup is complete?

**Comment by zachmprince** [comment]
@aeslaughter Yep, doing `ReporterData::check()` right after `UserObject::initialSetup()` worked.

**Comment by lindsayad** [comment]
So we have code in moose that declare reporter values in `initialSetup`?
