### ISSUE TITLE
Lagrangian mechanics kernels with correct large deformation Jacobians

### ISSUE THREAD

**Issue by reverendbedford** [idaholab/moose#17472]
## Reason
The Jacobian for the current StressDivergenceTensors kernel is wrong.  Moreover, it would be nice to have a large deformations option that doesn't use_displaced_mesh (i.e. a total Lagrangian option).

## Design
We should have:
- Mechanics kernels that have correct Jacobians for large displacements.
- Options for both updated and total Lagrangian formulations.
- Compatibility with the existing tensor_mechanics material system. 

## Impact
- At least for now I suggest adding *new* kernels, not replacing the current ones, so that we can gradually build up the functionality until we can replace the current StressDivergenceTensors which cover a lot of options (cylindrical and spherical coordinates, beams and bars, etc.).
- So the new mechanics kernels would supplement those in tensor_mechanics.

**Comment by dschwen** [comment]
Also, I want to point out ADComputeGreenLagrangeStrain, but that might not cover your needs.
