### ISSUE TITLE
Use same normal field in mortar constraint objects as we use for projection when building the mortar mesh

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#17539]
## Reason
Currently we use a `_normals` in `(AD)MortarConstraints` that is obtained essentially through `fe_map->get_normals()`
after reinit'ing the secondary element face at reference points provided by the mortar mesh. I don't believe this results in variational consistency (it certainly doesn't result in *consistency* within the mortar system) for mechanical contact methods.

## Design
I'm not quite sure yet. Currently we get it very simply through `_assembly`. I think we might have to go through the `AutomaticMortarGeneration` object to get this right.

## Impact
Certainly more consistency in our mortar objects (e.g. use the same normal field for *everything*), and hopefully more variational consistency as well.

**Comment by recuero** [comment]
`_normals` doesn't average between adjacent elements, does it? It appears it depends only on the element face.

**Comment by lindsayad** [comment]
Correct, the current `_normals` depends only on the element face and per our conversations (and this issue) we're going to change that

**Comment by lindsayad** [comment]
Ok I will create a table for some solve results for the thermomechanical contact problems I added in #17252. I am looking at the RZ finite strain high gap conductivity calculation because that seems to be the hardest one to solve. When mesh order is first I use dual basis. When mesh order is second I use mixed standard mortar with first order LM.

normal method | mesh order | total nonlinears | total linears
--- | --- | --- | ---
face | first | 475 | 1072
face | second | 480 | 1090
interpolated nodal | first | 475 | 1069
interpolated nodal | second | 482 | 1097

Pure nodal result to come, and then I will also push a PR so @recuero can do his own testing

**Comment by lindsayad** [comment]
Ok updated with pure nodal results

**Comment by recuero** [comment]
| Normal method (problem) | Nonlinears     | Linears     |
| -------------------------- | ------------- | ----------|
| Face   (bouncy-frictionless-rigid-master)      |216 | 779  |
| Interpolated  (bouncy-frictionless-rigid-master)  | 210  | 735  |
| Nodal  (bouncy-frictionless-rigid-master)  | 211  | 745  |
| Face   (bouncy-frictionless-soft-master)      | 267 | 1579  |
| Interpolated  (bouncy-frictionless-soft-master)  | 265 | 1547  |
| Nodal  (bouncy-frictionless-soft-master)  | 265  | 1545  |
| Face   (frictionless-cylinder)      | 97 | 358  |
| Interpolated  (frictionless-cylinder)*  | 97* | 343*  |
| Nodal  (frictionless-cylinder)  | 98 | 365 |

@lindsayad The interpolated option for the cylinder problem (*)  consistently avoids initial stagnation of linear iterations. All these problems show the new methods converge better.

**Comment by lindsayad** [comment]
Very nice!!
