### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by rksin8** [idaholab/moose#17558]
## Reason

In several python scripts, we get TypeError: 'map' object is not subscriptable as in python3 map returns an iterable object of type map, and not a subscriptible list.

## Design

Converting the iterable object of type map to list. 

## Impact

The test python script will work with python3.

**Comment by WilkAndy** [comment]
Making an issue is the right way to start, @rksin8 .  Great!  Are you planning to contribute occasional things like this to MOOSE?  If so, then you should probably try to do it "properly" - have a look at https://mooseframework.inl.gov/framework_development/contributing.html and try to follow the recipe.   But if you're only ever going to contribute the changes in #17557 then i think i should just do the pull-request for you.

**Comment by loganharbour** [comment]
Closed in #17971.
