### ISSUE TITLE
"Replay Engine" capability for MOOSE

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#1756]
This request actually came from Cristian Rabiti.  The idea is to be able to compute new PostProcessors after the fact, without recomputing the entire solution.  Suppose that you have an existing solution file with several timesteps worth of data in it.  Then you start a new simulation that reads each timestep one at a time, computes the new postprocessor value for that step, and continues on.  Basically it would do everything that a normal MOOSE simulation needs to do except for the solve, which would be replaced by reading from the input file.

**Comment by permcody** [comment]
Interesting idea, but we have no plans and no customer for this. It could be done with a full history of checkpoint files.
