### ISSUE TITLE
Incorrect parallel behavior for MultiAppNearestNodeTransfer

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#17680]
## Bug Description
I was puzzled why #17248 was failing in parallel, and while I'm not certain this is _the_ cause, I've discovered inconsistent parallel behavior with this transfer, _before_ I added any of my changes. Basically, if you transfer from a FIRST LAGRANGE variable in a sub app to a CONSTANT ELEMENTAL variable in a master app, a gold file created in serial cannot be reproduced in parallel. 

## Steps to Reproduce
Check out `7f273c475`, the commit just before my `target-source-elemental` branch was merged. In serial, run the `master_test.i` input, and save the output files to be golded. Create a test:

```
[./maybe_a_bug]
     type = 'Exodiff'
     input = 'master_test.i'
     exodiff = 'master_test_out.e master_test_out_sub0.e'
[../]
```

Running serially works fine (obviously):

```
./run_tests --re=maybe_a_bug --parallel 1
```

But running in parallel fails:

```
./run_tests --re=maybe_a_bug --parallel 4


transfers/multiapp_nearest_node_transfer.maybe_a_bug:   --------- Time step 2, 1.0000000e+00 ~ 1.0000000e+00, rel diff:  0.00000e+00 ---------
transfers/multiapp_nearest_node_transfer.maybe_a_bug: Nodal variables:
transfers/multiapp_nearest_node_transfer.maybe_a_bug: Element variables:
transfers/multiapp_nearest_node_transfer.maybe_a_bug:    w_from_sub_f_to_e  rel diff:  2.5000000e-01 ~  5.0000000e-01 = 5.00000e-01 (block 0, elmt 17)
```

```
./run_tests --re=maybe_a_bug --parallel 6


transfers/multiapp_nearest_node_transfer.maybe_a_bug:   --------- Time step 2, 1.0000000e+00 ~ 1.0000000e+00, rel diff:  0.00000e+00 ---------
transfers/multiapp_nearest_node_transfer.maybe_a_bug: Nodal variables:
transfers/multiapp_nearest_node_transfer.maybe_a_bug: Element variables:
transfers/multiapp_nearest_node_transfer.maybe_a_bug:    w_from_sub_f_to_e  rel diff:  0.0000000e+00 ~  7.5000000e-01 = 1.00000e+00 (block 0, elmt 1)
```

## Impact
This prevents #17248 from being fully integrated into `next`, because the verification tests use Lagrange -> elemental transfers. I could simply re-write the test to just use elemental -> elemental transfers, or we could add a restriction to the nearest node transfer to prevent anyone from trying to use this mixed-type transfer. But it's probably better to just figure out what the actual error is.

**Comment by aprilnovak** [comment]
[example.zip](https://github.com/idaholab/moose/files/6378643/example.zip)

tag @loganharbour @fdkong  - I believe this is the culprit of #17248 not integrating.

**Comment by aprilnovak** [comment]
Also, it is interesting to note that the transferred fields, `w_from_sub_e_to_e` and `w_from_sub_f_to_e` are *different*, even though they are both CONSTANT MONOMIAL, and the source variable from which they are obtained is set with the same `FunctionIC` `ParsedFunction`. I would have expected `w_from_sub_f_to_e` and `w_from_sub_e_to_e` to be exactly the same in serial:

(a) Transfer from `x+2y+z` as a FIRST LAGRANGE auxvairable in the sub-app, to a CONSTANT ELEMENTAL variable `w_from_sub_f_to_e` in the master app.
(b) Transfer from `x+2y+z` as a CONSTANT MONOMIAL auxvariable in the sub-app, to a CONSTANT ELEMENTAL variable `w_from_sub_e_to_e` in the master app.

But they are different in serial. This might be relevant to this issue.

**Comment by GiudGiud** [comment]
I'm adding nodal to elemental and back and mixed orders testing to #17417 for the general field transfers. We should have better support there

**Comment by GiudGiud** [comment]
So in the nearest node transfers tests we have this 
```
[Transfers]
  [to_sub_nodal_to_nodal]
    type = MultiAppNearestNodeTransfer
    to_multi_app = sub
    source_variable = u
    variable = nodal_source_from_parent_nodal
  []
  [to_sub_nodal_to_elemental]
    type = MultiAppNearestNodeTransfer
    to_multi_app = sub
    source_variable = u
    variable = nodal_source_from_parent_elemental
  []
  [to_sub_elemental_to_nodal]
    type = MultiAppNearestNodeTransfer
    to_multi_app = sub
    source_variable = u_elemental
    variable = elemental_source_from_parent_nodal
  []
  [to_sub_elemental_to_elemental]
    type = MultiAppNearestNodeTransfer
    to_multi_app = sub
    source_variable = u_elemental
    variable = elemental_source_from_parent_elemental
  []
[]
```
so I m inclined to think we support these mixes between lagrange and constant monomials already.
