### ISSUE TITLE
Fix compiler warnings (MOOSE)

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#1777]
None

**Comment by dschwen** [comment]
@andrsd the new Mersenne Twister uses the deprecated ```register``` keyword and adds a whole bunch of compile warnings (even in opt mode).

**Comment by permcody** [comment]
+1 for the brain-damage board. I believe there is a pragma we can use when including headers to ignore those warnings

**Comment by andrsd** [comment]
> the new Mersenne Twister uses the deprecated register keyword and adds a whole bunch of compile warnings (even in opt mode).

The code by itself is pretty horrible (IMO). I was thinking about "fixing" it, but diverging from the upstream is not a good thing (in case we will need to update again in future).

**Comment by dschwen** [comment]
How often do you really need to update a Mersenne Twister? Isn't that a straight forward algorithm? :confused:

**Comment by andrsd** [comment]
Unfortunately the way it is written is:
1) there are 2 modules, one for RNG another one for random distributions. The latter one uses the former one.
2) Most RNG-related function are in the *header file* and when you include it you have to `#define` 3 macros in a way that you generate the symbols for linking just once. 
3) I already had to change (add) the random distribution module so we do not get duplicate symbols.

If it was my call, the implementation would be solely in .c and .h would have just declarations. Maybe the author will decide to do that later. May be not. If not and if we had the "improved" version, then the next person who will be updating it will be most likely WTF?

**Comment by jwpeterson** [comment]
Can we close this issue since it is forever-ongoing and just refer to it as needed?

**Comment by permcody** [comment]
I like that idea. sure

**Comment by jwpeterson** [comment]
Interesting warning I haven't seen before from the latest (El Capitan) clang compiler:

```
/Users/moose/projects/moose/framework/src/executioners/Transient.C:742:28: warning: expression with side effects will be evaluated despite being used as an operand to
      'typeid' [-Wpotentially-evaluated-expression]
    return demangle(typeid(*_time_stepper).name());
                           ^
```

**Comment by friedmud** [comment]
What are the side effects of dereferencing something?

**Comment by jwpeterson** [comment]
> On Oct 6, 2015, at 8:38 PM, Derek Gaston <notifications@github.com> wrote:
> 
> What are the side effects of dereferencing something?
> 
This seems really picky, but according to the answer here: http://stackoverflow.com/questions/9563600/what-exactly-is-a-side-effect-in-c

"Accessing an object designated by a volatile glvalue (3.10), modifying an object, calling a library I/O function, or calling a function that does any of those operations are all side effects, which are changes in the state of the execution environment."

And dereferencing a non-constant pointer falls into the first category.  I had never heard of this before...

**Comment by roystgnr** [comment]
Nope.  Here "volatile" doesn't mean "the opposite of const", it means "one of those crazy things that systems programmers use to warn the compiler about memory that changes by itself or triggers I/O".  And since the compiler is allowed to assume that an unqualified pointer points to a non-volatile memory address, it can assume that a simple dereferencing of it (where no assignment follows) doesn't have side effects.

My best guess is that the warning is because each of those cases includes a function call (```MooseSharedPointer::operator*```, ```std::vector<KernelBase*>::operator[]```), and in the debug cases those function calls probably use assertions, and failed assertions trigger side effects.

**Comment by YaqiWang** [comment]
Reporting two warnings I saw on my mac:

```
/Users/wangy2/projects/moose/framework/src/base/NonlinearSystem.C:2434:54: warning: unused parameter 'tid' [-Wunused-parameter]
NonlinearSystem::reinitIncrementForDampers(THREAD_ID tid)
                                                     ^
/Users/wangy2/projects/moose/framework/src/base/SubProblem.C:294:8: warning: unused variable 'block_type' [-Wunused-variable]
  bool block_type;
       ^
```

**Comment by permcody** [comment]
Reference ticket #1777 when you fix compiler warnings.

**Comment by YaqiWang** [comment]
@permcody this issue has been accidentally closed.

**Comment by jwpeterson** [comment]
We were leaving it closed on purpose... it's just a number to reference.

**Comment by YaqiWang** [comment]
oh, I see. I am going to refer it.
