### ISSUE TITLE
Fix DTK Transfer Tests

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#1782]
Does not run in DBG mode - in fact there are more serious issues with debug mode on Linux with the new multiapp system.

**Comment by permcody** [comment]
@milljm or @brianmoose - I believe this is fixed in our Trilinos build. We only test DTK with Trilinos and I think it's all working. Please evaluate and close if appropriate.

**Comment by brianmoose** [comment]
It seems most of the DTK tests got removed in #7124 per #7123
Note that we currently don't do anything with Trilinos and debug mode.

**Comment by permcody** [comment]
Tests replaced. This ticket is no longer relevant.
