### ISSUE TITLE
Phase field systems documentation not rendering properly

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#17843]
## Bug Description
Phase field systems documentation page has a weird sidebar that is preventing some links from being clicked. See attached image. Tried on Firefox and Chrome.

![image](https://user-images.githubusercontent.com/12945054/118336735-43e9c580-b4e0-11eb-8853-cf5e08e4b00b.png)

## Steps to Reproduce
Go to https://mooseframework.inl.gov/modules/phase_field/systems.html

## Impact
Page is almost unusable.

**Comment by jessecarterMOOSE** [comment]
ping @aeslaughter for doco stuff

**Comment by jessecarterMOOSE** [comment]
Also not sure why the AuxKernels are being shoved over to the side like that.

![cropped](https://user-images.githubusercontent.com/12945054/118497849-73bce700-b6f3-11eb-8606-0ea3a107f013.png)

**Comment by aeslaughter** [comment]
@crswong888 Can you try to fix this, I think somehow the table headings are being set to the wrong level causing them to show up in the sidebar.

**Comment by crswong888** [comment]
@aeslaughter sure! I will take a look.

**Comment by jessecarterMOOSE** [comment]
https://mooseframework.inl.gov/docs/PRs/17887/site/modules/phase_field/systems.html

Looks good to me! :+1:
