### ISSUE TITLE
MultiApp Transfer VectorPostprocessor to VectorPostprocessor, and related things

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#17854]
## Reason

@lynnmunday , @cbolisetti , @rpodgorney , KT and I are working on simulating flow through fractured porous media using a MultiApp approach. In this work, the "fracture" is a 2D mesh living within the "matrix", which is a 3D mesh. The fracture nodes/elements don't usually conform with the matrix nodes/elements. We want to transfer information (heat flows) from the fracture to the matrix.

Another issue, #17835, describes one way of achieving this.  In the discussion, #17806, @hugary1995 suggests an alternative approach:

1. in the fracture app, use `save_in` in the `PorousFlowHeatMassTransfer` to record the Joules/second (or kg/s in the mass-transfer case) flowing from each fracture node.
2. write this to a `VectorPostprocessor` using a `NodalValueSampler` (can have `outputs=none`)
3. `Transfer` this VectorPostprocessor to the matrix App
4. In the matrix App, use a `VectorPostprocessorPointSource` `DiracKernel` to perform the heat addition to the matrix

## Design

At the least, this requires:

- [ ] create a suitable `VectorPostprocessorTransfer` (transfers all values from one VectorPostprocessor to another)
- [ ] check that this works for multi-processor simulations.  I'm not sure whether the receiver of the `Transfer` should ignore any points outside its mesh, or the sender shouldn't send such information , because `DiracKernels` might throw an error if a Dirac point is outside the mesh
- [ ] check performance - would be a shame if the `DiracKernel` keeps having to figure out which elements the Dirac points are in (but i think this is cached automatically).  **BUT** what if the fracture App (source App) changes its mesh via adaptivity?

## Impact

Ability to transfer VectorPostprocessor information between Apps, and to use this information in `DiracKernels` to apply sources/sinks.

Tagging @lynnmunday since he is going to actually do this work, or #17835, depending on what he's feeling like!

Tagging @cbolisetti to let him know the issue number of this.

**Comment by lynnmunday** [comment]
I'm going to try using this before I use #17835

**Comment by zachmprince** [comment]
We already have the capability to transfer vpp to vpp using MultiAppReporterTransfer. Unless I am missing something.

**Comment by WilkAndy** [comment]
> We already have the capability to transfer vpp to vpp using MultiAppReporterTransfer. Unless I am missing something.

Thank you @zachmprince - this looks exactly what we need, i agree!

**Comment by WilkAndy** [comment]
> > We already have the capability to transfer vpp to vpp using MultiAppReporterTransfer. Unless I am missing something.
> 
> Thank you @zachmprince - this looks exactly what we need, i agree!

I just tried this.  It doesn't quite work.  You can see what i tried at
- main app https://github.com/cbolisetti/multiappfracflow/blob/main/fracture_diffusion/fracture_app_dirac.i
- sub app https://github.com/cbolisetti/multiappfracflow/blob/main/fracture_diffusion/matrix_app_dirac.i

The problem is that the 'x y z' of the sub app is different than the 'x y z' of the main app.  In the main app I have:
```
[VectorPostprocessors]
  [heat_transfer_rate]
    type = NodalValueSampler
    outputs = none
    sort_by = x
    variable = joules_per_s
  []
[]
[Transfers]
  [heat_to_matrix]
    type = MultiAppReporterTransfer
    direction = to_multiapp
    multi_app = matrix_app
    from_reporters = heat_transfer_rate/joules_per_s
    to_reporters = heat_transfer_rate/transferred_joules_per_s
  []
[]
```
In the sub app I have
```
[VectorPostprocessors]
  [heat_transfer_rate]
    type = NodalValueSampler
    outputs = mad_csv
    execute_on = NONE
    sort_by = x
    variable = transferred_joules_per_s
  []
[]
```
But upon running MOOSE, the `transferred_joules_per_s` is things like:
```
id,transferred_joules_per_s,x,y,z
0,0.00098871731927696,0,0,0
0,0.0019326282358169,0,0,0
0,0.0018668693231171,0,0,0
0,0.0018030041413887,0,0,0
...
```
Note that (x,y,z) = (0, 0, 0) for all these values.  We actually need the (x, y, z) that are generated by the main app.

**Comment by hugary1995** [comment]
Is this "issue" resolved yet? It seems that at least the first two bullet points are done.

**Comment by lynnmunday** [comment]
@WilkAndy @zachmprince this issue is resolved.   The reporter transfer Zach told us to use solved our problems. This examples for this issue are resolved in PR https://github.com/idaholab/moose/pull/18294

**Comment by GiudGiud** [comment]
Ok closing since it's resolved.
