### ISSUE TITLE
Remove MooseArray

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#17865]
## Reason
The time has come.  `MooseArray` was originally invented to allow for shallow-copying while still using `operator[]` semantics: somehting that we really couldn't do any other way back in 2008.  These days we have much better alternatives... like just using `move` semantics with `std::vector`.

## Design
Replace `MooseArray` with `std::vector` and use `move` semantics.

## Impact
Should be negligible.  Applications shouldn't interact with `MooseArray` directly very much (but maybe I'm not thinking of a use-case).  Most of the types that use `MooseArray` are already typedefs.

**Comment by lindsayad** [comment]
If applications *are* using `MooseArray` directly, we can get away with a
```c++
template <typename T>
using MooseArray = std::vector<T>;
```
if the methods being used are methods common both to current `MooseArray` and `std::vector` (and most of the methods are)

**Comment by friedmud** [comment]
Closing because this is a bad idea.

**Comment by dschwen** [comment]
What made you change your mind?

**Comment by friedmud** [comment]
It wasn't possible to do... the usage mechanism that we have for MooseArray is too specific.  Even with `move` we can't get there with `std::vector`
