### ISSUE TITLE
Module unit tests not run in opt mode

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#17908]
## Bug Description

Module unit tests are not run at all in opt mode. See for example [https://civet.inl.gov/job/745128/](https://civet.inl.gov/job/745128/)

## Steps to Reproduce

compile module unit tests in opt mode.

## Impact

Test coverage compromised.

**Comment by hugary1995** [comment]
It's probably not related to opt. Even though I compile in dbg mode it still doesn't work. Now I'm guessing it's related to Ubuntu.

**Comment by loganharbour** [comment]
Closing due to duplicate #16092
