### ISSUE TITLE
Failed to detect PETSc

### ISSUE THREAD

**Issue by qingyang0315** [idaholab/moose#17931]
## Bug Description
When I try to make the makefile in Moduls, It always show that PETSc can not be detected. However, I have successfully installed PETSc. Is there something I should menstion? Thanks.

**Comment by lindsayad** [comment]
This is likely not a defect with MOOSE. Please look at our [Getting Started](https://mooseframework.inl.gov/getting_started/installation/index.html) page or search the GitHub Discussions for similar discussion of installation problems. Finally if you are unsuccessful then open a Discussion and see if we can resolve your problem before creating an Issue.
