### ISSUE TITLE
clarify MultiAppMeshFunctionTransfer documentation

### ISSUE THREAD

**Issue by lynnmunday** [idaholab/moose#18023]
## Reason
The documentation for this transfer is confusing and makes it sound like it is only applicable to postprocessors

## Design
Look at the code and clarify in the documentation what the transfer is doign.

## Impact
More information for users.

**Comment by lynnmunday** [comment]
@lindsayad @fdkong @GiudGiud @WilkAndy     I opened this ticket but I wasn't going to actually work on it.  At least not right now.

**Comment by GiudGiud** [comment]
Linked to #17994

**Comment by fdkong** [comment]
OK, it is identical to #17994

We need to keep only one of them
