### ISSUE TITLE
PorousFlow: create equivalent of OutflowBC

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#18037]
## Reason

Notifying @cpgr .   I've wanted to do this for so long!

We need a BC that represents an "invisible" boundary.  That is, if fluid or heat is flowing to the boundary, it just flows naturally out of the model without any impediment.

## Design

Similar to a combo of OutflowBC and DiffusionFluxBC, but in the context of PorousFlow.    This development might take a few days, due to extensive testing and documentation that is required.

## Impact

A nice addition to PorousFlow, hopefully removing the necessity of using the  PorousFlowPiecewiseLinearSink trick in many cases.

**Comment by cpgr** [comment]
Ooh, I love this idea.

**Comment by cpgr** [comment]
Ooh, I love this idea.

**Comment by cpgr** [comment]
I loved it so much I accidentally commented twice!
