### ISSUE TITLE
Libmesh fatal error during compile: "cstdlib: No such file or directory"

### ISSUE THREAD

**Issue by czadeh** [idaholab/moose#18050]
## Bug Description

I receive this error message when I try to compile the Darcy Pressure problem in Step 5 of the tutorial.

> /home/cameron/miniconda3/envs/moose/libmesh/include/libmesh/libmesh_common.h:36:10: fatal error: cstdlib: No such file or directory

It terminates the compile step and I cannot proceed. This seems like a bug because I made sure conda, moose, petsc, and libmesh were all updated but something is still missing.

## Steps to Reproduce

I made sure I had all of the following updated: conda, moose, petsc, libmesh.

conda moose environment is activated.

I followed all the steps in the tutorial up to [Step 5 just before the "Input File" section.](https://mooseframework.inl.gov/getting_started/examples_and_tutorials/tutorial01_app_development/step05_kernel_object.html#input-demo)

Compile with `make -j4`.

Receive this output:
```

Using HIT from /home/cameron/projects/moose/moosetools/contrib/hit
Compiling C (in opt mode) /home/cameron/projects/babbler/src/kernels/DarcyPressure.c...
In file included from /home/cameron/miniconda3/envs/moose/libmesh/include/libmesh/threads.h:24,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/HashMap.h:13,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/MooseUtils.h:13,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/InputParameters.h:13,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/MooseObject.h:13,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/ResidualObject.h:12,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/KernelBase.h:12,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/ADKernel.h:12,
                 from /home/cameron/projects/moose/framework/build/header_symlinks/ADKernelGrad.h:12,
                 from /home/cameron/projects/babbler/build/header_symlinks/DarcyPressure.h:4,
                 from /home/cameron/projects/babbler/src/kernels/DarcyPressure.c:1:
/home/cameron/miniconda3/envs/moose/libmesh/include/libmesh/libmesh_common.h:36:10: fatal error: cstdlib: No such file or directory
   36 | #include <cstdlib>
      |          ^~~~~~~~~
compilation terminated.
make: *** [/home/cameron/projects/moose/framework/build.mk:152: /home/cameron/projects/babbler/src/kernels/DarcyPressure.x86_64-conda-linux-gnu.opt.lo] Error 1
```

## Impact

I cannot proceed with the tutorial. Any help solving this would be greatly appreciated! I have been stuck on it for days.

**Comment by GiudGiud** [comment]
Hello

We use the GitHub discussions to handle compilation issues now (unless it's really a problem with our build, but usually it s not). 
Can you print your environment variables with env and report it here?
Could be a compiler issue, could be a problem with the paths, let's try to rule these out.

Guillaume

**Comment by czadeh** [comment]
Hi Guillaume,

Thanks for letting me know about the discussions section.

I used `conda activate moose

printenv`

which returns

`SHELL=/bin/bash
DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
SESSION_MANAGER=local/cameron-MintDesk:@/tmp/.ICE-unix/1043,unix/cameron-MintDesk:/tmp/.ICE-unix/1043
QT_ACCESSIBILITY=1
COLORTERM=truecolor
GCC_RANLIB=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-gcc-ranlib
XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
CONDA_EXE=/home/cameron/miniconda3/bin/conda
_CE_M=
build_alias=x86_64-conda-linux-gnu
CMAKE_ARGS=-DCMAKE_LINKER=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-strip
LANGUAGE=en_US
GPROF=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-gprof
MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
STRINGS=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-strings
CPP=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-cpp
CINNAMON_VERSION=4.8.6
DESKTOP_SESSION=cinnamon
SSH_AGENT_PID=1116
FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include
GTK_MODULES=gail:atk-bridge
XDG_SEAT=seat0
PWD=/home/cameron
GSETTINGS_SCHEMA_DIR=/home/cameron/miniconda3/envs/moose/share/glib-2.0/schemas
LOGNAME=cameron
XDG_SESSION_DESKTOP=cinnamon
QT_QPA_PLATFORMTHEME=qt5ct
XDG_SESSION_TYPE=x11
CONDA_PREFIX=/home/cameron/miniconda3/envs/moose
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
MOOSE_NO_CODESIGN=true
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CXX=mpicxx
CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include
XAUTHORITY=/home/cameron/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/cameron
DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GDM_LANG=en_US
LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/cameron/miniconda3/envs/moose/lib -Wl,-rpath-link,/home/cameron/miniconda3/envs/moose/lib -L/home/cameron/miniconda3/envs/moose/lib
HOME=/home/cameron
LANG=en_US.UTF-8
DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=X-Cinnamon
VTE_VERSION=6003
CXX_FOR_BUILD=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-c++
ELFEDIT=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-elfedit
CONDA_PROMPT_MODIFIER=(moose) 
CMAKE_PREFIX_PATH=/home/cameron/miniconda3/envs/moose:/home/cameron/miniconda3/envs/moose/x86_64-conda-linux-gnu/sysroot/usr
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/edc74e72_33c5_44a6_9aa5_5c6748b1d928
CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/cameron/miniconda3/envs/moose/include
LD=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-ld
LIBMESH_DIR=/home/cameron/miniconda3/envs/moose/libmesh
READELF=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-readelf
GXX=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-g++
PETSC_DIR=/home/cameron/miniconda3/envs/moose
GJS_DEBUG_OUTPUT=stderr
GCC_AR=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-gcc-ar
LESSCLOSE=/usr/bin/lesspipe %s %s
ADDR2LINE=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-addr2line
XDG_SESSION_CLASS=user
TERM=xterm-256color
_CE_CONDA=
GCC_NM=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-gcc-nm
SIZE=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-size
GTK_OVERLAY_SCROLLING=1
F77=mpif77
HOST=x86_64-conda-linux-gnu
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
LESSOPEN=| /usr/bin/lesspipe %s
CC_FOR_BUILD=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-cc
USER=cameron
GNOME_TERMINAL_SERVICE=:1.81
CONDA_SHLVL=2
AR=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-ar
AS=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-as
DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/cameron/miniconda3/envs/moose/include
F95=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-f95
F90=mpif90
host_alias=x86_64-conda-linux-gnu
DISPLAY=:0
SHLVL=1
NM=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-nm
GCC=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-gcc
DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include
VTKLIB_DIR=/home/cameron/miniconda3/envs/moose/libmesh-vtk/lib
XDG_VTNR=7
XDG_SESSION_ID=c1
LD_GOLD=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-ld.gold
CONDA_PYTHON_EXE=/home/cameron/miniconda3/bin/python
XDG_RUNTIME_DIR=/run/user/1000
GFORTRAN=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-gfortran
CONDA_DEFAULT_ENV=moose
OBJCOPY=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-objcopy
MPIHOME=/home/cameron/miniconda3/envs/moose
FC=mpif90
STRIP=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-strip
GTK3_MODULES=xapp-gtk3-module
XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/cameron/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
OBJDUMP=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-objdump
PATH=/home/cameron/projects/moose/python/peacock:/home/cameron/miniconda3/envs/moose/bin:/home/cameron/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
VTKINCLUDE_DIR=/home/cameron/miniconda3/envs/moose/libmesh-vtk/include/vtk-6.3
CC=mpicc
GDMSESSION=cinnamon
CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/cameron/miniconda3/envs/moose/include
CXXFILT=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-c++filt
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
BUILD=x86_64-conda-linux-gnu
CONDA_PREFIX_1=/home/cameron/miniconda3
RANLIB=/home/cameron/miniconda3/envs/moose/bin/x86_64-conda-linux-gnu-ranlib
CONDA_BUILD_SYSROOT=/home/cameron/miniconda3/envs/moose/x86_64-conda-linux-gnu/sysroot
_=/usr/bin/printenv
`

-Cameron

**Comment by GiudGiud** [comment]
Cant find anything wrong. 
What does `which mpicxx` return?
Which platform is this?

**Comment by czadeh** [comment]
My operating system is Linux Mint 20.1 Ulyssa 64 bit.

> What does which mpicxx return

`/home/cameron/miniconda3/envs/moose/bin/mpicxx`

I don't know if this is related, but when I run `./scripts/update_and_rebuild_petsc.sh` it gives me an error once it attempts to install Mumps and recommends I see configure.log


[configure.log](https://github.com/idaholab/moose/files/6643244/configure.log)


Line 25824 says `/home/cameron/miniconda3/envs/moose/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lmpiseq`

**Comment by GiudGiud** [comment]
I'd try to locate these two libraries/headers on the machine and see why the conda gcc cannot find them. 
@milljm will know what is actually the problem though

**Comment by georgeNakayama** [comment]
I had the same issue when going over the Laplace Young example in the workshop. It seems that after changing the 
`#include < cstdlib >` to `#include "stdlib.h"` in libmesh_common.h, the issue went away. 

However, I encounter another compiling error saying that `complex: No such file or directory` for the line `#include <complex>` in libmesh_common.h. Now I am trying to change `#include <complex>` to `#include <complex.h>` to see if this fixes the problem.

**Comment by GiudGiud** [comment]
Hello. You seem to be missing headers in your environment as well. It's unlikely you can fix it by finding alternate headers (from C std lib to C++ std lib). Let's ping @milljm for help here.

**Comment by pratyush16** [comment]
Hi. I had this same error and found that it happened because I was using the lowercase ".c" extension for my kernel file. Changing this to an uppercase ".C" so it compiles in C++ mode fixes the issue.

**Comment by czadeh** [comment]
> Hi. I had this same error and found that it happened because I was using the lowercase ".c" extension for my kernel file. Changing this to an uppercase ".C" so it compiles in C++ mode fixes the issue.

Thank you, this was the problem for me. As soon as I changed the kernel file to uppercase .C everything worked correctly.

**Comment by roystgnr** [comment]
> Thank you, this was the problem for me. As soon as I changed the kernel file to uppercase .C everything worked correctly.

Glad this worked!

Closing this issue; if I'm wrong and you're still having other problems please reopen.
