### ISSUE TITLE
Moose basic create application using docker is failed

### ISSUE THREAD

**Issue by karthigesut** [idaholab/moose#18105]
Hi,

I am using moose with docker. I tried to create application by using following steps in [Website](https://mooseframework.inl.gov/getting_started/new_users.html#create-an-app). When I run
```
./run_tests -j4
```
I am getting error message like "failed to import pyhit - try running make hit in $MOOSE_DIR/test"

How can I solve this issue?

**Comment by ClydeHuibregtse** [comment]
I also have this problem and it doesn't fail if I install from source - I think there may be a defect with the distributed docker iamge(s)

**Comment by loganharbour** [comment]
I'm working on fixing this up in #18925. Should get it in today - sorry for the troubles!
