### ISSUE TITLE
test:ics/random_ic_distribution_test.generate fails periodically

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#18130]
## Bug Description
`test:ics/random_ic_distribution_test.generate` fails periodically during threaded testing. See https://civet.inl.gov/job/762644/ for example

## Steps to Reproduce
See https://civet.inl.gov/job/762644/

## Impact
Developers occasionally get failures on work that is unrelated to this failing test.

**Comment by lindsayad** [comment]
@aeslaughter I believe this is your test?

**Comment by aeslaughter** [comment]
I will see if I can get this fixed.
