### ISSUE TITLE
Input file ${} replacements can fail in unexpected ways

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#18181]
## Bug Description
I get unrelated failures when the ${} replacements in the input file fail. Usually the error is reported at the next substitution, but latest failure I saw was a little different where an unrelated 0 ended up in a checkedRangeParam and got caught there. 

## Steps to Reproduce
Just use `${mu}` somewhere and forget to define mu, then use any other `${}` substitution

## Impact
Clearer errors when ${} replacements fail

**Comment by rwcarlsen** [comment]
We need some reproductions of particular failures in order to start attacking this.  Please share any example you run in to.

**Comment by GiudGiud** [comment]
That's a simple one. As you'll see it fails much after the misdefined parameter (missing quote)
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 10
  ny = 10
[]

[Variables]
  [u]
  []
[]

a = '2'
b = '1
c = PJFNK

[Kernels]
  [diff1]
    type = CoefDiffusion
    variable = u
    coef = ${a}
  []
  [diff2]
    type = CoefDiffusion
    variable = u
    coef = ${b}
  []
[]

[BCs]
  [left]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0
  []
  [right]
    type = DirichletBC
    variable = u
    boundary = right
    value = 1
  []
[]

[Executioner]
  type = Steady
  solve_type = ${c}
  petsc_options_iname = '-pc_type -pc_hypre_type'
  petsc_options_value = 'hypre boomeramg'
[]

[Outputs]
  exodus = true
[]

**Comment by GiudGiud** [comment]
Navier Stokes version. I did not define mu and rho, it's complaining about me not defining c, which I did!
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 10
  ny = 10
[]

[Variables]
  [u]
  []
[]

a = '2'
b = '1'
c = PJFNK
advected_interp_method = 'average'
velocity_interp_method = 'rc'

[FVKernels]
  [mass]
    type = INSFVMassAdvection
    variable = pressure
    advected_interp_method = ${advected_interp_method}
    velocity_interp_method = ${velocity_interp_method}
    vel = 'velocity'
    pressure = pressure
    u = u
    v = v
    mu = ${mu}
    rho = ${rho}
  []
[]

[BCs]
  [left]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0
  []
  [right]
    type = DirichletBC
    variable = u
    boundary = right
    value = 1
  []
[]

[Executioner]
  type = Steady
  solve_type = ${c}
  petsc_options_iname = '-pc_type -pc_hypre_type'
  petsc_options_value = 'hypre boomeramg'
[]

[Outputs]
  exodus = true
[]

**Comment by dschwen** [comment]
The first example is a runaway string. I get 

```
*** ERROR ***
/home/schwd/Programs/moose-parse-errors/test/guid1.i:48: expected '=' after parameter name '-pc_type', got '-'
```

which is when the next `'` occurs in the input. Instead of a starting quote this is taken as the terminal quote of the runaway string. The error is expected and is the best we can do.

This example is not related to brace expansion.

**Comment by dschwen** [comment]
The second example is not complaining about a missing `c`. It parses fine. I'm closing this issue.
