### ISSUE TITLE
A UO which an Auxkernel depend on should only be put in PRE-AUX for the Auxkernel execute_on 

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#18189]
## Bug Description

Currently, once a postprocessor/UO is added to the pre_aux group, it will be executed as such for all execute_on, even if the auxkernel depending on it is only executed e.g. on final

## Steps to Reproduce

See [here](https://github.com/vincentlaboure/moose/commit/ef30590b03f958d39e8d030c1ca69d9bf9cf82fa) for an example exhibiting the issue

## Impact

This can unnecessarily mess up the UO execution order.

**Comment by vincentlaboure** [comment]
Tag @jthano

**Comment by jthano** [comment]
@vincentlaboure I was wondering if you had run into this problem with some specific input you have which could be turned into a test to make sure the code in my MR fixes your issue and also that the issue remains fixed in the future

**Comment by vincentlaboure** [comment]
Yes, I do but it is a griffin test, which is on my (griffin) PR

**Comment by jthano** [comment]
Okay I'll take a look there
