### ISSUE TITLE
Wall Function BC

### ISSUE THREAD

**Issue by freiler** [idaholab/moose#18272]
## Reason
This feature implements wall functions boundary conditions for high Reynolds numbers turbulence modeling.

## Design
WallFunctionBC is a boundary condition for the momentum equation which imposes a shear stress at the wall boundary, calculated based upon the centroid velocity and the distance to the wall.

## Impact
The boundary condition allows the use of coarser meshes for turbulence modeling.

**Comment by GiudGiud** [comment]
Closed by #18272
