### ISSUE TITLE
Eigenvalue may give a solution that has a minus sign

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#18365]
## Reason
Because eigenvalue problem is casted as finding solution of a nonlinear problem `F(x) = Ax - Bx/|Bx| = 0`, and `|Bx|` is a norm of `x` meaning that both `x` and `-x` have the same norm, thus both `x` and `-x` are the solution of this nonlinear problem. Note that neither are wrong. I've seen in some calculations `Eigenvalue` executioner gives negative solutions which is typically undesired.

## Design
I do not have a good solution for this situation but hope this can be fixed so that the solution can look more physical. Tag @fdkong 

## Impact
Make users feel better by giving more physical-looking solutions.

**Comment by YaqiWang** [comment]
Note that normalization post solve can fix this but not all calculations have normalization.

**Comment by YaqiWang** [comment]
@lindsayad Just to let you know that I think we can close this with the custom normalization. The reason is that when the normalization is not a norm but for example an integration. The normalization will force the solution to have a fixed sign, which is also typically the desired the sign (k-effective = \int(\Sigma_f\phi)\dx >0).

**Comment by lindsayad** [comment]
Ok sounds good. Closing this for the reason given by @YaqiWang

**Comment by lindsayad** [comment]
relevant pull request was https://github.com/idaholab/moose/pull/25204
