### ISSUE TITLE
Truss plastic solid relies on material property name for computation, with no option for suffix

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#18371]
## Bug Description
This is problematic because I need a suffix for the material property output, so that it doesnt conflict with the aux variable names. But also I dont want to remove the materialAux because I dont want the computation of aux variables to rely on the material property output, because the kernel should not rely on that. 

So this is kind of insolvable without adding an option for a custom name for each material property in `StressDivergenceTensorsTruss`
Current temporary solution is to allow warnings in the test

I think eventually this will force a re-gold, whether we want to keep the material property output or not.

## Steps to Reproduce
Add a suffix to the material property output in the truss tests, watch them fail

## Impact
More work for me in #18182

**Comment by GiudGiud** [comment]
ah actually they relied on the name of the material property, which is fair. Closing

**Comment by lindsayad** [comment]
Why is this now closed?
