### ISSUE TITLE
Enable taking derivatives w.r.t. coupled material propertied in DerivativeParsedMaterials

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#18402]
## Reason
A usecase for this has come up in a project where KKS phase concentrations are converted from non-linear variables to material properties.

## Design
Let the user supply a list of additional symbols to take derivatives w.r.t.

## Impact
Added capability.

Ping @xueyang94

**Comment by jiangwen84** [comment]
@dschwen  this is really cool! 👍
