### ISSUE TITLE
3D Porous media Incompressible Finite Volume

### ISSUE THREAD

**Issue by liangyu-psi** [idaholab/moose#18410]
## Reason
This new feature is nice. But it seems only suitable for 2D calculation.

## Design
It can be developed to 3D version.

## Impact
Stronger demand for 3D calculations. It can be used to wider objects.

**Comment by GiudGiud** [comment]
It is 3D already.

**Comment by liangyu-psi** [comment]
Thanks for your information. From the equations, it seems that the constant physical properties are used. 
Could it be updated to the version whose physical properties changing with temperature?

**Comment by liangyu-psi** [comment]
@GiudGiud  Hi, Giud!
Thanks for your information. From the equations, it seems that the constant physical properties are used.
Could it be updated to the version whose physical properties changing with temperature?

**Comment by GiudGiud** [comment]
We will in the near future. For now this capability is only in Pronghorn
You can request access to this application here:
https://inl.gov/ncrc/

**Comment by liangyu-psi** [comment]
@GiudGiud That's great!
May I have one more question?
When I use a simple cubit 3D mesh. This module works.
When I apply a unstructured mesh. Error happens. And the error is : matrix A is singular!
Does it mean this module just suitable for structured mesh? Maybe there something wrong with my unstructured case.
Hope to receive your professional reply.

**Comment by GiudGiud** [comment]
Is it a tetrahedral mesh?
If so you need to turn two_term_boundary_expansion off for every variable. 

This module works better with hex meshes as we don't have skewness correction

**Comment by liangyu-psi** [comment]
Yes, it's tetrahedral mesh. In other words, unstructured grids can be used. But, the convergence is not guaranteed in this situation? 
How about Polyhedral mesh? Should I use the same method?

**Comment by GiudGiud** [comment]
We can't do general polyhedral. The best mesh for this module right now is hexahedrons. Note that you can make an unstructured hex mesh. It does not need to be regular/structured. 

tet meshes have issues with the two term boundary expansion.

**Comment by liangyu-psi** [comment]
@GiudGiud 
Thanks for your tips. I will try an unstructured hexahedral mesh.

**Comment by GiudGiud** [comment]
Closing this. 
Support for tetrahedral mesh is much better now, even with two terms boundary expansion.
Still not support for general polyhedral, and recommandation is still that hexahedral is best.
