### ISSUE TITLE
Add utility function to return a vector of pairs from two vector input parameters

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#18456]
## Reason
We frequently use the paradigm of requiring two vectors of equal length in our input files to define a list of corresponding pairs. This leads to a pattern of checking vectors for equal length and erroring out otherwise, and to iterate over the vectors with conventional indexed for loops.
We should provide a utility function 

```
std::vector<pair<T1,T2> getParamPairs<T1,T2>(const std::string & param1, const std::string & param2);
```

That takes two parameters of type `std::vector<T1>` and `std::vector<T2>`, performs the error checking, and splices them into a single vector of pairs, that can be conveniently iterated over with a ranged for loop.

## Design
Add helper function template to `MooseObject`.

## Impact
Convenience API, reduce code duplication.

**Comment by YaqiWang** [comment]
We had supports for parameters in type of `std::map<T1, T2>`, only with limited types of T1 and T2.

**Comment by dschwen** [comment]
> We had supports for parameters in type of `std::map<T1, T2>`, only with limited types of T1 and T2.

I know, but a map is not a vector of pairs, and the goal here is not to revolutionize how parameter pairs are represented in the input file, but to make it easier to work with the status quo as a developer.
