### ISSUE TITLE
Prevent duplicate variable names

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#18465]
## Reason
MOOSE currently allows variables to have the same name as long as they're both auxvariables or both variables:

```
[Variables]
  [u]
  []
  [u]
  []
[]
```

When an `ExternalProblem` is adding variables automatically via the `ExternalProblem::addExternalVariables` method, those variables are hidden from the user, and it becomes more probable that the user might accidentally define variables with the same name in the input file.

## Design
Replace the check between types with a higher-level check that a variable with the same name doesn't already exist. It doesn't make sense to allow variables with the same name, but different types, to exist, anyways.

## Impact
Prevent user errors in input setup.

**Comment by GiudGiud** [comment]
This will error now from the functor checks added in the subproblem
```
      mooseError("Functor '",
                 name,
                 "' is being added with return type '",
                 MooseUtils::prettyCppType<T>(),
                 "' but it has already been defined or requested with return type '",
                 existing_wrapper_base->returnType(),
                 "'.");
```

this syntax is still allowed
```
[Variables]
  [u]
  []
  [u]
  []
[]
```
but both blocks are merged by the parser, and only one variable is created
