### ISSUE TITLE
Ability to prescribe radial mesh positions in AnnularMeshGenerator

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#18486]
## Reason
I have a need to create a mesh of an annulus where I directly prescribe the locations of the rings of nodes. The AnnularMeshGenerator can create a mesh that largely looks like what I want, but it doesn't currently allow such a fine-grained level of control.

## Design
Add an option to AnnularMeshGenerator to specify a list of the radial positions of the rings of nodes.

## Impact
This would just add a new feature, and should not affect any existing functionality.

**Comment by GiudGiud** [comment]
@bwspenc out of curiosity for one of my applications, do those meshes conserve the volume/area of the circle of the prescribed radius
