### ISSUE TITLE
Convergence Issues

### ISSUE THREAD

**Issue by edwardXZ06** [idaholab/moose#18500]
## Bug Description
I have used current UMAT interface to run a bug free simple hyperelastic umat file, yet the convergence perform really bad no matter I use Newton or PJFNK. 
Does this mean for the nonlinear problem, we shall specify the Jacobian ourselves, considering this interface has not been built to work with the AD?

**Comment by dschwen** [comment]
Can you share the UMAT source with us? Are you setting the `DDSDDE` parameter (which is required to compute the Jacobian)?

**Comment by dschwen** [comment]
I'm converting this over to a discussion. If it turns out there is an actual bug in the implementation we can move it back.
