### ISSUE TITLE
AD scalar kernels

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#18535]
## Reason
Scalar equations may involve Jacobians that are difficult to compute by hand. Also, when scalar equations are coupled to field equations, Jacobian contributions with respect to field variables are not easily implemented.

## Design
This would implement AD scalar kernels, allowing Jacobians to be computed via automatic differentiation for scalar equations.

## Impact
This will add new capability.

**Comment by joshuahansel** [comment]
@andrsd @lindsayad

**Comment by lindsayad** [comment]
Is this something you guys are planning to work on, or are you hoping that I will do it?

**Comment by joshuahansel** [comment]
It's something that I'm willing to attempt, fail at, and then ask you for help.

**Comment by lindsayad** [comment]
Haha, sounds good
