### ISSUE TITLE
Use https://conda.software.inl.gov/public

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#18569]
## Reason
Change our instructions to begin pointing users to our new Conda repository presence.

## Design
Update Getting Started instructions to have users use the public INL Conda repository. Include a transitional set of instructions for those already using the older method (delete that channel from their config).

## Impact
Possible confusion during the transition phase.

**Comment by WilkAndy** [comment]
Hi @milljm .  could you please confirm the instructions at https://mooseframework.inl.gov/getting_started/installation/index.html work?   I have a "high value customer" who wants to install MOOSE - he's not a computer person - and i don't want him to run into difficulties.

**Comment by WilkAndy** [comment]
Hi @milljm , just wonder if you can confirm the above question?  It doesn't matter what method this new user uses to install MOOSE, but i just want to make sure the instructions are correct.

**Comment by milljm** [comment]
The current instructions will work, but it might be best to swap out:

```pre
conda config --add channels idaholab
```
for the new server location:
```pre
conda config --add channels https://conda.software.inl.gov/public
```

Both will work for some time still.
