### ISSUE TITLE
GapHeatTransfer creates heat in the gap for CYLINDER and SPHERE

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#18585]
## Bug Description

In `GapHeatTransfer`, the heat flux across the gap at a given node/qp is computed and then identically applied to both sides of the gap. This is not correct in non-plate geometries because both sides do not have the same length.

Something like this in could be done in `GapHeatTransfer::computeQpResidual()`:

```
% for cylinders:
if (_inner_surface)
  _edge_multiplier *= 2*r1/(r1+r2)
else
  _edge_multiplier *= 2*r2/(r1+r2)

% for spheres:
if (_inner_surface)
  _edge_multiplier *= (2*r1/(r1+r2))^2
else
  _edge_multiplier *= (2*r2/(r1+r2))^2
```

As @jiangwen84 pointed out, r1 and r2 designate the __local__ inner and outer radii of the gap, respectively (local in case there is deformation).

## Steps to Reproduce

[This branch](https://github.com/vincentlaboure/moose/tree/gapheattransfer_heat_balance) contains two examples showing 10% discrepancy with `r2/r1 = 1.1`. 

## Impact

If the ratio of outer to inner radii is close to 1, the impact should be limited.

However, even for a standard BISON case with cylinders `r2 = 4.18 mm`,  `r1 = 4.1 mm`, that's already a 2% discrepancy.
For cases with much larger gaps (e.g. in HTRs where radiation happens through the cooling channel), it can reach 20% or more.

In any case, this prevents from achieving global heat balance.

Tag @jortensi

**Comment by bwspenc** [comment]
Your proposed solution seems fairly reasonable to me. This only applies to cylinders and spheres, and we have special branches in the code for them anyway. Actually, now that I think of it, are you using the cylinder option? I wonder if that already takes care of that.

**Comment by bwspenc** [comment]
What is the dimensionality of your model?

**Comment by vincentlaboure** [comment]
@bwspenc Yes, I am using `gap_geometry_type = 'CYLINDER'` for these examples.

I was able to reproduce the problem for:
- 2-D XY
- 3-D XYZ
- 2-D RZ

**Comment by bwspenc** [comment]
Are you setting `cylinder_axis_point_1` and `cylinder_axis_point_2`?

**Comment by bwspenc** [comment]
They default to '0 1 0' and '0 0 0', which is what you would typically want for 2D axisymmetry.

**Comment by bwspenc** [comment]
I just saw that you pointed to a branch with the models. Looks like you are setting those correctly.

**Comment by novasr** [comment]
We take into account the difference in length for conduction and we have regression tests that show it; see moose/modules/heat_conduction/test/tests/gap_heat_transfer_htonly/cyl2D_xz.i. However, that correction is only applied to h_conduction, not h_radiation (see GapConductance.C). If I apply that correction (or set emissivity to zero) I get a very small error:

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+--------------------+
| time           | Tcore_avg      | Tcore_max      | Tcore_min      | Trpv_avg       | Trpv_max       | Trpv_min       | flux_1         | flux_2         | flux_3         | heat_balance   | outer_temp     | ptot           | rpv_convective_out |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+--------------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |       0.000000e+00 |
|   1.000000e+00 |   5.629721e+03 |   6.352191e+03 |   4.922467e+03 |   4.564344e+03 |   4.892465e+03 |   4.280465e+03 |  -6.206914e+05 |   6.204457e+05 |   6.346683e+05 |   2.841740e-07 |   4.268142e+03 |   6.283185e+05 |       6.283187e+05 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+--------------------+

vs.

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+--------------------+
| time           | Tcore_avg      | Tcore_max      | Tcore_min      | Trpv_avg       | Trpv_max       | Trpv_min       | heat_balance   | ptot           | rpv_convective_out |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+--------------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |       0.000000e+00 |
|   1.000000e+00 |   5.668040e+03 |   6.387852e+03 |   5.033842e+03 |   4.604919e+03 |   4.880009e+03 |   4.371365e+03 |   9.997259e-03 |   6.283185e+05 |       6.346000e+05 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+--------------------+

A caveat is that applying the length correction to h_radiation slows convergence and I need a finer mesh to converge. Maybe there's a better way?

**Comment by hugary1995** [comment]
> A caveat is that applying the length correction to h_radiation slows convergence and I need a finer mesh to converge. Maybe there's a better way?

So I guess it's "harder to get the solution" vs "easier to get an approximation" type of decision then... Maybe there should be a knob to turn this correction on and off for gap radiation?

**Comment by vincentlaboure** [comment]
@novasr Good to hear. Can you detail how you apply the correction to h_radiation?

> So I guess it's "harder to get the solution" vs "easier to get an approximation" type of decision then... Maybe there should be a knob to turn this correction on and off for gap radiation?

I guess it depends: it could be that convergence is only affected when radiation matters, in which case you probably don't want to add fictitious energy just to make the problem easier to converge. In my opinion, even a crude approximation should preserve heat balance.

**Comment by novasr** [comment]
This is my hack in GapConductance.C

Real
GapConductance::h_radiation()
{
  /*
   Gap conductance due to radiation is based on the diffusion approximation:

      qr = sigma*Fe*(Tf^4 - Tc^4) ~ hr(Tf - Tc)
         where sigma is the Stefan-Boltzmann constant, Fe is an emissivity function, Tf and Tc
         are the fuel and clad absolute temperatures, respectively, and hr is the radiant gap
         conductance. Solving for hr,

      hr = sigma*Fe*(Tf^4 - Tc^4) / (Tf - Tc)
         which can be factored to give:

      hr = sigma*Fe*(Tf^2 + Tc^2) * (Tf + Tc)

   Approximating the fuel-clad gap as infinite parallel planes, the emissivity function is given by:

      Fe = 1 / (1/ef + 1/ec - 1)
  */

  if (_emissivity == 0.0)
    return 0.0;

  const Real temp_func =
      (_temp[_qp] * _temp[_qp] + _gap_temp * _gap_temp) * (_temp[_qp] + _gap_temp);
  const Real adjusted_length = gapLength(_gap_geometry_type, _radius, _r1, _r2, _max_gap);
  return _stefan_boltzmann * temp_func / _emissivity * gapAttenuation(adjusted_length, _min_gap, _min_gap_order);
}

Maybe that's clumsy? Also noticed:

void
GapConductance::computeQpConductance()
{
  if (_has_info)
  {
    _gap_conductance[_qp] = h_conduction() + h_radiation();
    _gap_conductance_dT[_qp] = dh_conduction();
  }
  else
  {
    _gap_conductance[_qp] = 0;
    _gap_conductance_dT[_qp] = 0;
  }
}

Why don't we use     _gap_conductance_dT[_qp] = dh_conduction() + dh_radiation();?

**Comment by vincentlaboure** [comment]
Thanks, I'll give it a try.

**Comment by vincentlaboure** [comment]
@novasr After testing it, I do not think this is the appropriate fix. The reason it preserves energy is that `gapAttenuation` returns a value inversely proportional to the radius. However, the constant can be quite wrong: for that particular example, `gapAttenuation()` is ~5; for fuel pins (much smaller radius) it can reach >1000 while the correction should go to 1 as the ratio of radii goes to zero. This is most likely the reason why convergence degrades so much.

The following change (which also preserves global balance) makes more sense to me:

```
Real
GapConductance::h_radiation()
{
  Real adjusted_length;

  if (gap_geom == GapConductance::CYLINDER)
    adjusted_length = 0.5 * (_r1+_r2) / _radius;
  else if (gap_geom == GapConductance::SPHERE)
    adjusted_length = 0.25 * (_r1+_r2) * (_r1+_r2) / _radius/ _radius;
  else
    adjusted_length = 1.0;

  return _stefan_boltzmann * temp_func / _emissivity * adjusted_length;
}
```

and same thing in `dh_radiation` (added to  `_gap_conductance_dT`, as you pointed out).

I don't know  a slight modification is needed with deformation (or if `r1`, `_r2`, `_radius` are locally changed).

**Comment by novasr** [comment]
That was just a demo. Should/could the adjustment be applied just once after the individual hs are calculated?

**Comment by recuero** [comment]
@vincentlaboure From the description of the issue, it appears that weak enforcement of the constraints would help, along the lines of what @hugary1995 said. We should be able to create a mortar object that captures the same physics for future use.

Does the solution you propose in https://github.com/idaholab/moose/issues/18585#issuecomment-900654812 eliminates the error in your solution?

**Comment by vincentlaboure** [comment]
It does (only tested for cylinders though) but this case doesn't have any deformation. One advantage is that for small gaps, the additional term converges to 1 and should therefore minimally affect convergence.

**Comment by recuero** [comment]
Yeah, that makes sense to me, in that case surfaces have the same area approximately. Will need testing, but, according to how the code is designed, the solution you propose for spheres should work too. 
If the cylinder gets deformed in a non-cylindrical way, the fix may not be very accurate any more, but definitely an improvement as far as I can see.

**Comment by elementx54** [comment]
Is anyone actively fixing this?

**Comment by vincentlaboure** [comment]
Thank you for taking care of this @recuero!

**Comment by recuero** [comment]
No problem, you did the hard work!
