### ISSUE TITLE
add build+run instructions to JOSS paper

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#18610]
## Reason

Reviewers would like this: see https://github.com/openjournals/joss-reviews/issues/3314

## Design

Add something to `modules/geochemistry/paper.md` along the lines of:

To build `geochemistry` and run the examples:

1. Download and install the entire MOOSE package.  Instructions are at https://mooseframework.inl.gov/getting_started/installation/index.html .  Even if you're interested only in geochemistry (without transport, solid mechanics, etc), MOOSE comes as a complete package, so needs to be installed in its entirety.  Depending on your computer setup, this can be straightfoward (on a personal Mac computer) or complicated (on an administered supercomputer).
2. During the installation of MOOSE in part 1, only the "framework" will have been compiled.  To compile all the physics modules, including the `geochemistry` module, use the following instructions run from the command line:
```
cd ~/projects/moose/modules
make -j 4
cd ~/projects/moose/modules/geochemistry
make -j 4
```
3. Check that the geochemistry module is correctly compiled using the following instructions:
```
cd ~/projects/moose/modules/geochemistry
./run_tests
```
Virtually all the tests should run and pass.  Some may be "skipped" due to your computer setup (for instance, not enough threads).
4. Now you're ready to use the geochemistry module.  For example, to run the Weber-Tensleep GeoTES example from the command line:
```
cd ~/projects/moose/modules/combined/examples/geochem-porous_flow/geotes_weber_tensleep
../../../combined-opt -i exchanger.i
```

## Impact

Ease of installation and running of `geochemistry`.

**Comment by WilkAndy** [comment]
Also, need to address the following comments (from https://github.com/openjournals/joss-reviews/issues/3314#issuecomment-903193062)

1. When I plot the results of the reactive transport example, the mesh (and resolution) seems to be different from the figure in the manuscript. Is that expected?

2. Why were these two examples highlighted in the manuscript? The code has many documented examples (https://mooseframework.inl.gov/modules/geochemistry/tests_and_examples/index.html). Are these specially interesting?

3. Overall, the main issue with the examples is the reliance almost exclusively on 1 source (Bethke 2007) and comparison to a single proprietary code, GWB. The examples are generally described sufficiently in the documentation but I feel that I would have benefited from having the book and GWB to fully follow everything.

I plan to add the following:

```
# Tests and examples

The geochemistry module's [code coverage](https://mooseframework.inl.gov/docs/coverage/geochemistry/index.html) currently exceeds 96%.  Many of the more complicated benchmark tests and examples are [comprehensively documented](https://mooseframework.inl.gov/modules/geochemistry/tests_and_examples/index.html) and the sections below present one benchmark study and one example by way of illustration.
```

```
(These results are derived using a higher resolution than the example included in the test suite, since the latter must be small enough to rapidly pass MOOSE's automatic regression testing.)
```

**Comment by WilkAndy** [comment]
In https://github.com/openjournals/joss-reviews/issues/3314 , @volpatto would like further changes.

**Comment by loganharbour** [comment]
@WilkAndy can this be closed?

**Comment by WilkAndy** [comment]
Thank you @loganharbour - closing now
