### ISSUE TITLE
Git Submodule Status Still Returns Negative Hashes After Init

### ISSUE THREAD

**Issue by herter4171** [idaholab/moose#18616]
## Bug Description
I'm guessing this is just a new Git thing we'll have to account for.  We started having issues with KP-SAM, because `git submodule init moose` was kicking back a negative "commit hash" like it would before `git submodule init moose`.  As you can see below, this also occurs for us with MOOSE and its submodules.

```
[ec2-user@ip-172-31-13-201 moose]$ git submodule status
-def87c9916e53ad08034f93db8fd82fb42578a85 large_media
-ffab5c914090ad625645faa1bb4251d6b46f1c26 libmesh
-880d209961346e912b7f043c3872310738b1a095 moosetools
-09da24df01e50defd94bc4f7396f866a808ecea5 petsc
[ec2-user@ip-172-31-13-201 moose]$ git submodule init
Submodule 'large_media' (https://github.com/idaholab/large_media) registered for path 'large_media'
Submodule 'libmesh' (https://github.com/libMesh/libmesh) registered for path 'libmesh'
Submodule 'moosetools' (https://github.com/idaholab/moosetools) registered for path 'moosetools'
Submodule 'petsc' (https://gitlab.com/petsc/petsc.git) registered for path 'petsc'
[ec2-user@ip-172-31-13-201 moose]$ git submodule status
-def87c9916e53ad08034f93db8fd82fb42578a85 large_media
-ffab5c914090ad625645faa1bb4251d6b46f1c26 libmesh
-880d209961346e912b7f043c3872310738b1a095 moosetools
-09da24df01e50defd94bc4f7396f866a808ecea5 petsc
```

## Steps to Reproduce
Currently testing on Amazon Linux 2 (`yum` package manager) with Git 2.32.0.  
1. Start with a fresh clone of MOOSE
1. Run `git submodule status` to see the negative "hashes"
1. Run `git submodule init` to init submodules
1. Run `git submodule status` to see that commit "hashes" remain negative

## Impact
We recently updated our Jenkins nodes to have the setup given in the last section, so without this in place, our build will start breaking.  I will furnish a PR ASAP.

**Comment by loganharbour** [comment]
I believe you just want `git submodule update --init`

**Comment by herter4171** [comment]
@loganharbour, I don't want to pull in the files where `git submodule init` needs replacement, but `git ls-files -s $1 | awk '{print $2}'` does what I want by just giving me the hash for directory `$1`.  Submodules have to be added in the build order to take advantage of layer caching with Docker.  Otherwise, a change to the LibMesh checkout would mean rebuilding MPICH and PETSc, too.

Before I can raise a PR for this, I'm having trouble getting the tests to run, and I'm guessing it's something simple that doesn't warrant a new issue.  There seems to be an infinite loop of `make hit` seemingly being successful and being told it can't be imported.  The image build makes all targets in `test`, so it should be available.  Any idea what I'm doing wrong?

```
dev@a1f470d10ce7:/opt/moose/test$ ./run_tests -j `nproc`
Using HIT from /opt/moose/moosetools/contrib/hitBuilding and linking hit...
failed to import pyhit - try running "make hit" in the $MOOSE_DIR/test directory.

dev@a1f470d10ce7:/opt/moose/test$ make hit
Using HIT from /opt/moose/moosetools/contrib/hitBuilding and linking hit...

dev@a1f470d10ce7:/opt/moose/test$ ./run_tests -j `nproc`Using HIT from /opt/moose/moosetools/contrib/hit
Building and linking hit...failed to import pyhit - try running "make hit" in the $MOOSE_DIR/test directory.
```
