### ISSUE TITLE
Fix improper usages of LIBMESH_DIM throughout the mechanics code

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#18623]
## Bug Description
We widely use the various tensor objects (RankTwoTensor, RankFourTensor, etc.) for mechanics calculations that would require the size of these tensors to be 3. However, those objects are sized to LIBMESH_DIM, rather than 3. Somewhere along the line, an erroneous assumption was made that that tensor dimension should be tied to the model dimension, rather than to the size of the three-dimensional Cartesian coordinate system.

If someone were to actually set LIBMESH_DIM to 2, the code should be able to run 2D simulations, but none of our mechanics code would work because it would incorrectly size the tensors to be 2x2, 2x2x2x2, etc., when they should be 3x3, 3x3x3x3, etc., regardless of the model dimensionality.

I'm not sure what to replace LIBMESH_DIM with here. I would personally replace them with the number 3, but if we are trying to avoid using magic numbers in the code, maybe we need some replacement like THREE.

## Steps to Reproduce
I haven't tried this, but if someone were to set LIBMESH_DIM to 2, none of the 2D or 1D tensor_mechanics tests would run correctly.

## Impact
Because we're never setting LIBMESH_DIM to anything other than 3, everything works fine, but we should stop using this pattern now before it spreads any further.

**Comment by bwspenc** [comment]
@dschwen I'm interested in your thoughts on this.

**Comment by bwspenc** [comment]
I guess the main issue/question is whether the core tensor objects (which are in MOOSE) should be sized to the maximum model dimension or to the maximum size of the Cartesian coordinate system. Those are also tied to the size of the RealVectorValue, which is sized to the model dimension size (LIBMESH_DIM). I guess to change this, we'd need to use something other than RealVectorValue for our size 3 vectors, or switch the convention for sizing RealVectorValue. @roystgnr, any thoughts on that?

**Comment by dschwen** [comment]
I think "model dimension" is a bit misleading. We should probably have a static assert to make sure LIBMESH_DIM is 3 and be done with it. I don't think anyone has ever made a serious attempt at building moose with a 2D libmesh, and I'm pretty certain that would not work currently. Would it really be worth a serious effort? IDK

**Comment by dschwen** [comment]
The neat thing about using LIBMESH_DIM is that it is a bit more mnemonic than just putting `3` everywhere.

**Comment by bwspenc** [comment]
I don't know -- it just makes me grumpy every time I see LIBMESH_DIM instead of 3 because it's wrong.

**Comment by roystgnr** [comment]
We're definitely not resizing `RealVectorValue` - IIRC nearly all of the performance improvement when `LIBMESH_DIM<2` comes from simply automatically doing fewer computations with that and its related classes.

But, I could absolutely see a case for turning `libMesh::TypeVector<T>` and related classes into `<T,N>`, though, with a default `N=LIBMESH_DIM` template argument, but with everything from 1 to 3 instantiated so as to support other use cases too.

Even that I don't think is worth the work, though.  I'd say switch your LIBMESH_DIM misuses to THREE_D (or some other better mnemonic), put in a static assert to scream whenever those aren't equal, and then consider mixed support if/when someone really wants it.

**Comment by bwspenc** [comment]
@dschwen There are still about 75 instances of LIBMESH_DIM being used in TensorMechanics. I assume that most, if not all of those should be replaced by `Moose::dim`, right?
