### ISSUE TITLE
Have unused parameters show red in peacock

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#1862]
Currently in peacock, when there is an unused parameter in an input block, it shows up as white at the bottom of the list. It would be nice if you could have it show up in red.

**Comment by tonkmr** [comment]
@permcody I still think this would be a useful addition to Peacock

**Comment by permcody** [comment]
@brianmoose or @aeslaughter - Do we do something better with the new peacock? i.e. If you add a parameter "foo = bar" to an input file, what happens?

**Comment by brianmoose** [comment]
Yes, these sorts of parameters are currently showing cyan in the new peacock.

**Comment by permcody** [comment]
Excellent, closing. Fixed in new peacock.
