### ISSUE TITLE
SimpleFluidProperties updated

### ISSUE THREAD

**Issue by lee7632** [idaholab/moose#18638]
## Reason
Pronghorn can not use the current SimpleFluidProperties class when derivatives of fluid properties are called. This issue may be solved with the AD properties. However, for now, necessary derivatives are implemented.

## Design
The functions are added as follows:
- cv_from_p_T with derivatives 
- c_from_v_e with derivatives
- rho_from_p_T with derivatives 
- T_from_v_e with derivatives
- p_from_v_e with derivatives 

## Impact
Incompressible fluid properties can be used by this SimpleFluidProperties class in Pronghorn. 

@GiudGiud @joe61vette

**Comment by GiudGiud** [comment]
Implementing the routines with derivatives automatically adds the AD version of these properties. 
What are you using SimpleFluidProperties for btw? Just for testing?

**Comment by lee7632** [comment]
@GiudGiud I used SimpleFluidProperties for estimating the pressure drop with incompressible fluid cases, so basically for the fluid with constant material properties.

**Comment by lee7632** [comment]
@pbalest

**Comment by GiudGiud** [comment]
Closing as resolved by #18642
