### ISSUE TITLE
Capped turbulent mixing length 

### ISSUE THREAD

**Issue by freiler** [idaholab/moose#18663]
## Reason
Allows for an enhancement in turbulence modeling using a zero-equation model for the turbulent viscosity.

## Design
The original Prandtl's mixing length model assumes a linear growth for the mixing length as the distance to the nearest wall is increased. The capped mixing length model modifies the mixing length calculation such that the linear growth occurs within the boundary layer, and caps the value to a constant for the bulk region.

## Impact
Better turbulence modeling.

**Comment by GiudGiud** [comment]
Closed by #18666
