### ISSUE TITLE
regenerating *.i file from *_outfile.e file 

### ISSUE THREAD

**Issue by DomenicoCFD** [idaholab/moose#18788]
Hi All,

I would like to regenerate the input file of MOOSE if only the _outfile.e is given. This is because I would expect to modify the input file and therefore I may well loose the track of all the input that I provided in MOOSE for a particular _outfile.e MOOSE result file. 

A similar feature does exist in ANSYS so eventually MOOSE does have a similar thing.

I would really appreciate your help on this.

Kind Regards,

**Comment by dschwen** [comment]
The input file is actually stored in the exodus output as a data block. You can reveal some of it on the command line using `strings my_out.e`. Note that this is a reconstructed input with all default parameters inserted by MOOSE.
