### ISSUE TITLE
Make live print section activated with a given time delay

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#18818]
## Reason
I am having a user object whose `finalize` function calls an external Fortran function that can be quite heavy. The function also can be verbose with some line print-outs about its progress with a control parameter. When the verbose is off and the function is heavy, MOOSE live-print will be activated with this
```
  TIME_SECTION("computeUserObjects", 1, "Computing User Objects");
```
in `FEProblemBase::computeUserObjectsInternal`, which shows the cpu-time, memory usage at the end nicely with the dots showing the dynamics.

But when the verbose is on and the function is heavy, the dots are mingled with the line print-outs in the Fortran function and mess up the screen. I can add a new section in `finalize` like
```
  TIME_SECTION("FortranCall", 3, "Calling Fortran", false);
```
which creates a new section with dots turned off. The only drawback of this is that when the function is heavy, some line print-outs from Fortran come out before the header of the section. When the function is light, all line print-outs will come out properly because the live section will not be activated.

## Design
So I suggest that we have a capability to control how long to activate a live print. Currently all live print sections use five seconds. If this capability is in place, I can activate the section based on the verbose parameter with 0 time delay. This looks to me a useful feature.

## Impact
A new feature for the live print.

**Comment by YaqiWang** [comment]
I think MOOSE itself shows this issue. For example, if I do
```
moose/test/tests/kernels/2d_diffusion]> ../../../moose_test-opt -i 2d_diffusion_test.i -r 8
```
I got
```
    870 Linear |R| = 2.277650e-09
    871 Linear |R| = 2.250697e-09
 2 Nonlinear |R| = 2.250697e-09
 Solve Converged!
Executing
  Finished Solving                                                                       [ 32.14 s] [  154 MB]
Finished Executing                                                                       [ 34.13 s] [  204 MB]
```
at the end. Note section header `Executing` comes out after the convergence history. I think this is a bit confusing but I also do not have good suggestions on this. Always printing `Executing` apparently not a solution. Users may have to disable the live print to have a clean screen output and only turn it on for performance debugging purpose. I may just close this issue and suggest users to not turn on live print unless they can understand the intermingled screen outputs.

**Comment by YaqiWang** [comment]
```
[CSAPI]...Solving CSAPI FSP.............................................................................................
[CSAPI]...Group    10...................................................................................................
Executing
  Performing Initial Setup
    Computing User Objects      Finalizing CSAPI
[CSAPI]...Group    11...................................................................................................
[CSAPI]...Group    12...................................................................................................
[CSAPI]...Group    13...................................................................................................
[CSAPI]...Group    14...................................................................................................
[CSAPI]...Group    15...................................................................................................
[CSAPI]...Group    16...................................................................................................
[CSAPI]...Group    17...................................................................................................
[CSAPI]...Group    18...................................................................................................
[CSAPI]...Group    19...................................................................................................
[CSAPI]...Group    20...................................................................................................
[CSAPI]...Group    21...................................................................................................
[CSAPI]...Group    22...................................................................................................
[CSAPI]...Group    23...................................................................................................
[CSAPI]...Group    24...................................................................................................
[CSAPI]...Group    25...................................................................................................
[CSAPI]...Group    26...................................................................................................
[CSAPI]...Group    27...................................................................................................
[CSAPI]...Group    28...................................................................................................
[CSAPI]...Group    29...................................................................................................
[CSAPI]...Group    30...................................................................................................
[CSAPI]...Group    31...................................................................................................
[CSAPI]...Group    32...................................................................................................
[CSAPI]...Group    33...................................................................................................
[CSAPI]...Group    34...................................................................................................
[CSAPI]...Group    35...................................................................................................
      Finished Finalizing CSAPI                                                          [887.03 s] [    5 MB]
    Finished Computing User Objects                                                      [887.87 s] [    5 MB]
  Finished Performing Initial Setup                                                      [891.88 s] [   11 MB]
```
It will be idea for the first two lines after
```
    Computing User Objects      Finalizing CSAPI
```
but that seems impossible.

**Comment by friedmud** [comment]
After talking to @YaqiWang , there are a few updates to the way live print works that are needed:

1. If anything prints in-between when the section started and when Perf Graph Live thinks something should print - then the full context (everything on the stack above the current section that hasn't been printed) should not be printed.  This will take care of the first example here
2. PGL should only print if _nothing_ else has printed within the last time period.  If there is output coming from elsewhere then that should be good enough for the user.  This will handle cases that look like the second case here that come from MOOSE.
3. If there are not going to be any dots printed... that should imply to not print the beginning message too.  That will cover the last case here.
