### ISSUE TITLE
3D Porous media Incompressible Finite Volume/Robustness/Convergence

### ISSUE THREAD

**Issue by liangyu-psi** [idaholab/moose#18811]
#18410 Hello every expert, **PLEASE HELP ME!** I am desperately by the problem I faced.

I am trying to use the new feature of MOOSE which is **PINS module**. In my last issue #18410, I knew this module could do 3D simulation. So I try to modify the input file **"2d-rc-heated.i"** given by MOOSE into 3D version. The new input file and mesh all attached. The mesh is a hexagonal assembly. Because the physical properties used in "2d-rc-heated.i" are almost all 1, I change this properties into real sodium properties.

Then, I try so many solvers, however, this example still didn't converge. It only converge when I set the properties to 1. Under normal circumstances, this problem should not occur when using constant physical properties. I'm not sure if it is the problem with my settings or the convergence of this module is not that well.

I am a newbie in moose, and I would like to ask every expert about any way to make this calculation converge.

Thanks for your help!

[example.zip](https://github.com/idaholab/moose/files/7153864/example.zip)

**Comment by GiudGiud** [comment]
Umm we use the discussions forum for these issues now. Sorry we completely missed this. 
Hope it worked out.
