### ISSUE TITLE
CombinerGenerator clobbers boundary names

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#18820]
## Reason
```
[Mesh]
  [generated1]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 4
    ny = 10
    xmin = -0.6
    xmax = -0.1
    ymax = 5
    boundary_name_prefix = pillar1
  []
  [generated2]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 4
    ny = 10
    xmin = 0.1
    xmax = 0.6
    ymax = 5
    boundary_name_prefix = pillar2
    boundary_id_offset = 4
  []
  [combine]
    type = CombinerGenerator
    inputs = 'generated1 generated2'
  []
[]
```

Users should expect the boundaries `pillar2_top`, `pillar2_bottom`,`pillar2_left`, and `pillar2_right` with IDs 4-8, but they get unnamed boundaries on the second pillar.

## Design
1. Add an error message when combining meshes that have naming conflicts for the same IDs (suggesting the use`boundary_id_offset` for example)
2. Make sure the names on the second mesh's are added to boundary info correctly.

## Impact
Added capability

**Comment by dschwen** [comment]
Never mind `Mesh CollectionGenerator` does it the right way.

**Comment by gambka** [comment]
I came across this issue looking for something else. I'm using `CombinerGenerator` in a recent input and I think it now does the right thing.  I'm not quite sure why both `CombinerGenerator` and `MeshCollectionGenerator` exists though. I think this issue can be closed.
