### ISSUE TITLE
Unhelpful error message with wrong material name in TensorMechanics/Master

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#18842]
## Bug Description
If I put `generate_output = 'vonmises'` in my `[Modules/TensorMechanics/Master/all]` block, I get this not very helpful error message:

```
*** ERROR ***
Unable to add output Material
```
I was able to guess that I should have asked for `vonmises_stress` instead, but it would not be obvious to the user what block that message was coming from, or if they figured that out, what material output in a potentially long list of outputs was causing the problem. 

## Steps to Reproduce
Put  `generate_output = 'vonmises'` in a `[Modules/TensorMechanics/Master/all]` block.

## Impact
This is an annoyance

**Comment by dschwen** [comment]
I thought I just added a proper error for this!

**Comment by dschwen** [comment]
The fix is in https://github.com/dschwen/moose/commit/d53b1f82543d1b34ae9eb86af94530a648a1948c which is part of an open PR.
