### ISSUE TITLE
Small error in water viscosity calculation

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#18877]
## Bug Description
There is an error in the implementation of water viscosity in `Water97FluidProperties`, where someone (me) didn't implement part of the viscosity calculation properly.

## Steps to Reproduce
Any water viscosity calculation can be off by a small amount.

## Impact
The difference is relatively minor (correcting it didn't cause any diffs in test suite).

**Comment by WilkAndy** [comment]
This bug looks like some hours of puzzlement!

a

**Comment by cpgr** [comment]
I was comparing the viscosity with another package and saw that viscosity was off slightly even though they used the same EOS, whereas density was identical. It turns out I didn't read the equation for viscosity correctly in the IAPWS docs, so had basically missed some terms. Thankfully it didn't take hours!
