### ISSUE TITLE
Allow ElementExtremeValue and NodalExtremeValue to use proxies

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#18936]
## Reason
It is a useful operation to be able to apply a max/min postprocessor to variable `x`, and then evaluate another variable at the same position in space. 

## Design
We can add a `proxy_variable` to `ElementExtremeValue` and `NodalExtremeValue` so that we can perform this operation. Then, the max/min values are taken as the `variable` at the location where the `proxy_variable` reaches the specified max/min.

## Impact
New feature.

**Comment by dschwen** [comment]
There is a design issue here, where if the minimal value is found on multiple QPs / nodes, the chosen proxy value will depend on parallel partitioning. One of your tests fails exactly only on 9 MPI ranks for that reason (see #21968). I'm working on a fix.

**Comment by aprilnovak** [comment]
Good catch! Sorry about that - thank you for tackling a fix.
