### ISSUE TITLE
Make tests pass on M1 Apple Silicon

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#18954]
## Reason
We have 17 failing framework tests and >50 failing modules tests. Let's get started chipping away at this failures. It could very well be that these failures are caused by bugs in the code that happen not to break the code on x64. 

## Design

Go over tests and fix issues. I'll be looking at the parsed material failures first.

## Impact
Crossplatform compatibility.

**Comment by dschwen** [comment]
Observation: JIT compilation of parsed materials works in `dbg` mode!

**Comment by cticenhour** [comment]
Closed via #22458. See https://civet.inl.gov/job/1215826/ for reference of passing MOOSE and modules tests.
