### ISSUE TITLE
Diffusion in line element

### ISSUE THREAD

**Issue by jain651** [idaholab/moose#19027]
## Bug Description

Diffusion process in line element does not account for the area of the element. Thus, the line element representing different area will have the same profile of the diffused variable. Even if the material properties are scaled based on the cross-sectional area of the line element, the results differs from the corresponding 3-dimensional simulation.

## Steps to Reproduce

Please see attached commit which demonstrate the problem. 

## Impact

Lack of specific diffusion kernel for line element produces incorrect results.

**Comment by jain651** [comment]
The scaling of the material properties will not be consistent with already existing material model, e.g., `LinearElasticTruss` in `TensorMechanics`. In  `LinearElasticTruss`, we define area as in `AuxVariables` block and utilize in `LineElementMaster` action block. This is typical scenario while modeling a reinforced concrete structure. 

May be I should have submitted this issue as a feature enhancement. I am not sure though.

**Comment by WilkAndy** [comment]
> 
> 
> The scaling of the material properties will not be consistent with existing material model, e.g., `LinearElasticTruss` in `TensorMechanics`. In `LinearElasticTruss`, we define area as in `AuxVariables` block and utilize in `LineElementMaster` action block. This is typical scenario while modeling a reinforced concrete structure.
> 
> May be I should have submitted this issue as a feature enhancement. I am not sure though.

I think you need to give more details explaining what you want.  When i see "diffusion in line element" i think of the diffusion equation defined on a line segment.  Ie, \dot{u} = k\nabla^2 u, defined on 0<=x<=L.  That is obviously not what you're talking about here!
