### ISSUE TITLE
Add the ability to install examples or other directories

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#19022]
## Reason
Binary-only users for applications benefit from having access to non-source content other than the contents of `test/tests`.

## Design
This would allow application developers to specify their own directories that can be installed in addition to `test/tests`.  Add a makefile variable that apps can set in their own makefiles that contains a list of zero or more additional directories to be treated like `test/tests` during the install process - i.e. copied wholesale into `[PREFIX]/share/[appname]/[dirname]`.

## Impact
This will add new capability and shouldn't affect existing capability.

**Comment by joshuahansel** [comment]
@rwcarlsen Feel free to beef up the issue description - I'm pretty ignorant on this topic.

@lindsayad: @permcody suggested I ask you to tag this issue in the MOOSE TA support task.

**Comment by lindsayad** [comment]
done!
