### ISSUE TITLE
Deprecate `save_in`

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#19035]
## Reason
The new tagging system makes `save_in` superfluous. Let's remove it.

## Design
Deprecate parameters and fix input files. Open followup issue to remove deprecated code.

## Impact
Code cleanup.

**Comment by YaqiWang** [comment]
I can tell you that this will break Griffin IQS capability. We possibly can use tagging for Griffin. We did not use tagging before because in multiphysics, we do not need to save residual for every variable, but that is probably a minor saving for us. Tag @zachmprince .

**Comment by lindsayad** [comment]
I'm going to consider this as a subset of #10372 and close it
