### ISSUE TITLE
Use reverse nearest-point mapping to transfer data (UO) from sub-apps

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#19056]
## Reason

For cases with many sub-apps, it is currently difficult to transfer data back in a conservative manner (e.g. transfer a LayeredAverage from each sub-app into their corresponding block).

## Design

I created 2 examples illustrating one of the main needs we have (more details below). I think both issues could be solved with the solution @GiudGiud suggested: using a reverse mapping to determine which element should be filled by which sub-app. Other solutions are possible but likely impose (potentially a lot) more burden on the users (e.g. element ID assigning), especially for large models.

Example 1: circular cluster array with one (3-D) sub-app per ring of assemblies
 
![Screen Shot 2021-09-14 at 9 36 51 AM](https://user-images.githubusercontent.com/17411984/136829579-983f479d-762f-4ae0-8fe2-d8fefb81257c.png)
 
Transfers from the primary to the sub-apps can be done with NearestRadiusLayeredAverage/MultiAppUserObjectTransfer.
The goal is to transfer data back from each sub-app and apply it to the green region of the corresponding ring (3rd dimension not shown on the picture but the fields to be transferred have an axial dependency).
Ideally we should be able to transfer that data back from the sub-apps using a single MultiAppUserObjectTransfer (with perhaps, if necessary, one or two options to inform the transfer which UO is to be used to obtain the mapping) that would take one LayeredAverage per sub-app and write them into an auxiliary variable in the primary app.
 
 
Example 2: hexagonal lattice with one (1-D) sub-app per assembly

![Screen Shot 2021-09-14 at 9 43 34 AM](https://user-images.githubusercontent.com/17411984/136829608-bd757a0b-8c68-4ac1-ac3a-8116c8250515.png)
 

(1-D sub-apps scaled by 1.5x in the z-direction on the picture to be able to visualize them – in reality they have the same axial length as the primary app)
 
Similarly, transfers from the primary to the sub-apps is not a problem.
MultiAppInterpolationTransfer could transfer data back but has a lot of issues near equidistant surfaces. On the other hand, a reverse mapping (as described above) should be able to fulfill that need, too.

## Impact

For cases with many sub-apps, it will greatly improve the ability to transfer data back in a conservative manner.

Input files available upon request.

Tag @fdkong @YaqiWang @jortensi @nicolasmartin3

**Comment by fdkong** [comment]
I do not fully understand this issue. But I have done this kind of similar thing for the Fusion project that I am working on.

What I did was that restrict each subapp to a particular block of the master app. And the transfer is done from one subapp to one mesh block (boundary) of the master app. That is, there is one to one map (both direction) between subapp and mesh block (boundary).

**Comment by vincentlaboure** [comment]
> @vincentlaboure
> 
> `Example 1: circular cluster array with one (3-D) sub-app per ring of assemblies`
> 
> What is the subapp region? Is it a quarter (the red ring and inside gray) of a small cylinder?

Yes.

> What I did was that restrict each subapp to a particular block of the master app. And the transfer is done from one subapp to one mesh block (boundary) of the master app. That is, there is one to one map (both direction) between subapp and mesh block (boundary).

So you are using one `MultiApp` per sub-app? If so, that's what I ended up doing in the meantime for example 1 but this is not efficient because each MultiApp executes sequentially.

More importantly, the main issue is when we have many sub-apps (think of example 2 with hundreds of hexagons and sub-apps). Adding hundreds of `MultiApp` and `Transfers` (as well as adding hundreds of block IDs in the master mesh) is not a practical solution. With this issue addressed, this could be done with 1 MultiApp (with many instantiations), 1 Transfer (and no need to add block IDs).

Does that make sense?

**Comment by vincentlaboure** [comment]
Note also that @lindsayad started to work on this (so you may want to coordinate with him if you are planning to work on it too)

**Comment by fdkong** [comment]
> So you are using one MultiApp per sub-app (i.e. 5 MultiApp blocks in example 1)? If so, that's what I ended up doing in the meantime for example 1 but this is not efficient because each MultiApp executes sequentially.

In my case, I have one multiApp with 1000 subapps.   Why do you need 5 MultiApp blocks? You have a different physics per a quarter? In other words, you have five input files, each per subapp? 

>More importantly, the main issue by doing so is when we have many sub-apps (think of example 2 with hundreds of hexagons and sub-apps). Adding hundreds of MultiApp and Transfers (as well as adding hundreds of block IDs in the master mesh) is not a practical solution. With this issue addressed, this could be done with 1 MultiApp (with many instantiations), 1 Transfer (and no need to add block IDs).

I only have one transfer for all the 1000 subapps. What I did was that I constructed  a map between mesh boundaries and subapps. Each subapp will send data to its corresponding mesh boundary.  In my case, I had 1000 boundary sides that were constructed automatically using Cubit and MOOES mesh generators

**Comment by vincentlaboure** [comment]
Another question for @fdkong: is your approach relying on bounding boxes? (because in the two examples shown above, this is not possible)

**Comment by fdkong** [comment]
OK, finally, I understood what we need here. I make a summary here in case we need to look into that in the future.

Example 1:

subapp

![subapp](https://user-images.githubusercontent.com/10508374/153309341-571be8d1-7cc7-45ec-84d4-bbfe6a8416f0.jpeg)

master:

![master](https://user-images.githubusercontent.com/10508374/153309370-fe9b4613-8d02-4c02-a142-ce6892fe8f21.jpeg)

Two things must be done to transfer data correctly and reliably between sub-apps and the main application.  
1) Trivial coordinate transformation needs when transferring data from sub-app to the main application because sub-app handles only part of a small cylinder.
2)  Explicitly pair mesh blocks in the main application with sub-apps need to be done. The bounding box search will work for the simple geometry such as the one shown above. In general, if the geometry is going to be crazy, the bounding box might miss a target.

I have done step 2) in a customized transfer (nearest node transfer ) for my project, but I did not do anything on 1) since I did not need it.   

Example 2 only needs  2).

**Comment by vincentlaboure** [comment]
Do you think it's difficult to do as follows?

1. use a `NearestPointLayeredAverage` to determine a bijective mapping from any one element on the master mesh to a given sub-app (assuming that the `points_file` for the nearest point object and the `positions_file` of the `MultiApp` match)
2. Use that mapping to perform the transfers in either direction

The advantage that I see is that there is no meshing operation needed.

**Comment by fdkong** [comment]
In your mesh, you already mark these blocks, and I do not see extra work .. I might be misunderstanding something here.

**Comment by vincentlaboure** [comment]
I could also be misunderstanding what do you mean by 'mark these blocks'. What I mean to say is that each of the regions corresponding to a sub-app may not have its own unique block ID (i.e. there could be less block IDs than the number of sub-apps).

Would that be an issue with your option? Could you show at least a snippet of input file to make sure we are on the same page?

**Comment by fdkong** [comment]
Yes, my approach requires a block ID per subapp

**Comment by friedmud** [comment]
What's needed here is to have a `NearestSubAppUserObjectTransfer`.  When transferring from the sub to the master you would loop over the elements and find the nearest sub-app to query the `UserObjectTransfer` from.

**Comment by fdkong** [comment]
In this case, we need to assume that the mesh in subapp is relatively small, and so we can gather all elements without using too much memory.  1D should be small anyway.

**Comment by fdkong** [comment]
"loop over the elements" can be done in parallel as well. So it might be fine ...

**Comment by vincentlaboure** [comment]
> In this case, we need to assume that the mesh in subapp is relatively small, and so we can gather all elements without using too much memory. 1D should be small anyway.

I think the element loop would be done on the master app not the sub-app (for each master element, find the nearest sub-app **origin** and grab the corresponding sub-app UO to transfer the data). This mapping 'master elem -> UO' could be constructed only once if we set `fixed_mesh=true`.

**Comment by friedmud** [comment]
Yes - @vincentlaboure has this right - the element loop I was talking about would be over the master elements

**Comment by fdkong** [comment]
It is clear to me now. I was over worried on this. It seems that we use replicated meshes anyway 

```
      // Only works with a serialized mesh to transfer to!
      mooseAssert(to_sys.get_mesh().is_serial(),
                  "MultiAppUserObjectTransfer only works with ReplicatedMesh!");
```

It should work even when the master has a distributed mesh to me. 

`find the nearest sub-app origin`

"Straight" pipes should work. Curved (bend) pipes are not going to work in general.

**Comment by vincentlaboure** [comment]
It should still work as long as you want the whole (curved) pipe to be associated with the same master 'column'. This is because the search does not know anything about the sub-app geometry, only its origin indicated in the `MultiApps/*/positions_file`. Or am I misunderstanding your need @fdkong ?
