### ISSUE TITLE
keep_solution_during_restore should be able to also keep the auxiliary system

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#19078]
## Bug Description

For some complicated setups, keep_solution_during_restore can fail, which seems to be related to the auxiliary system not being restored.

## Steps to Reproduce

[This simple sabertooth example](https://hpcgitlab.inl.gov/idaholab/sabertooth/-/issues/23) can reproduce the issue.

## Impact

This can make the computation of a steady state solution painfully and unnecessarily slow.

Tag @fdkong @jortensi @nicolasmartin3

**Comment by GiudGiud** [comment]
Tagging myself. This will be part of the checkpoint rework effort.

**Comment by YaqiWang** [comment]
@loganharbour can this be closed with the latest update in checkpoint restart?

**Comment by loganharbour** [comment]
I think so - we now only load what we can, so it shouldn't error. That sounds satisfied, right? 

We still have the outstanding issue (if desired) of loading data into other names/vectors (i.e., non direct mapping) but I don't think this issue pertains to that.

**Comment by loganharbour** [comment]
I think so - we now only load what we can, so it shouldn't error. That sounds satisfied, right? 

We still have the outstanding issue (if desired) of loading data into other names/vectors (i.e., non direct mapping) but I don't think this issue pertains to that.

**Comment by vincentlaboure** [comment]
> can this be closed with the latest update in checkpoint restart?

I am not sure to understand how this is related to checkpoint restart. Is the claim that that the recent checkpoint work solved this issue?

**Comment by loganharbour** [comment]
I might need more of an explanation on this one. I actually think that they're not related now

**Comment by GiudGiud** [comment]
I ll take a look over the next few weeks. There's a VTB model with a workaround but I would be down not to have that
