### ISSUE TITLE
PiecewiseBilinear function can not read input data correctly 

### ISSUE THREAD

**Issue by RLiu2020** [idaholab/moose#19173]
## Bug Description

PiecewiseBilinear function can not read input data correctly 
## Steps to Reproduce

modify PiecewiseBilinear code and the format of input file
## Impact

This bug prevents from completing simulation

**Comment by dschwen** [comment]
This issue does not contain sufficient details.

**Comment by loganharbour** [comment]
@dschwen I think this can be closed?
