### ISSUE TITLE
Crank-Nicolson totally wrong if any PDE in the set missing a time derivative term

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#19228]
## Bug Description
If a PDE does not have a time derivative (say the mass equation for incompressible Navier-Stokes), then you will end up solving, for that sub-vector of dofs, the equation: residual + residual_old = 0. In my personal experience this yields solutions that look like this in time:
<img width="1313" alt="Screen Shot 2021-10-27 at 1 01 36 PM" src="https://user-images.githubusercontent.com/10248304/139148430-1a5f6c82-d6aa-4aaa-a905-647f2138f3c0.png">

## Steps to Reproduce
Solve a system of equations in which at least one equation does not have a time derivative. Your solution is in for a literally bumpy ride

## Impact
Makes users distrust MOOSE

**Comment by GiudGiud** [comment]
Likely related, when using the new TimeDerivativeAux with no time derivatives (transient but solving steady states), the results are also really weird.
- 1 process: some noise derivatives (1e-9) in the final time step, uneven spatially
- multiple processes: inconsistent noise, 0s sometimes.
So the _dot fields are not great in the absence of time derivative kernels.
