### ISSUE TITLE
RunApp and other Tests may incorrectly report passing

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#19257]
## Bug Description

@aprilnovak reported on Slack that the `RunApp` Tester is erroneously passing with bad syntax. I was able to replicate after updating MOOSE to a current version. The issue occurred here:
https://github.com/idaholab/moose/commit/aff9b15ea46e179575c26d5699ec418eb55be6ae

The problem is that the testExitCode logic was incorrectly moved up the Tester hierarchy meaning anything above or at the same level as FileTester would just not run critical exit code testing logic.

## Steps to Reproduce

Create a bad test and run it with `RunApp`.

## Impact

Very Critical! We need to make sure that new tests are added for coverage of this Gap

**Comment by loganharbour** [comment]
Closed by #19258
