### ISSUE TITLE
Mortar-based gap heat transfer

### ISSUE THREAD

**Issue by recuero** [idaholab/moose#19286]
## Reason
Extend the benefits of mortar constraints to more advanced gap heat transfer physics, including radiation and conductance.

## Design
Follow #19229 but include modifications to allow for derived user objects to use cached geometry information from the mortar constraint. This will allow the creation of new user objects or their expansion with minimal or null intervention in the constraint.

## Impact
Added capability.

**Comment by loganharbour** [comment]
@recuero is this done?

**Comment by recuero** [comment]
Mostly done, I was keeping it open because wanted to add 3D tests. But we could open another issue if needed.

**Comment by recuero** [comment]
Closed due to #20090. As a related topic, we should think of creating a mortar thermal contact action.
