### ISSUE TITLE
Optimization for fixed Jacobian with NEWTON solve_type

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#19309]
## Reason
When Jacobian is fixed and fully assembled, we do not need slow residual evaluations, which is especially important for eigenvalue problems. Possibly even the Jacobian is not fixed, residual evaluation can be completely skipped in NEWTON solve option.

## Design
Currently the way of handling fixed Jacobian is just to skip the Jacobian evaluations after the first. My understanding is that this is fine for PJFNK solve because it does not assume the Jacobian is exact. Even in this case, letting PETSc handle it properly seems a better implementation. For linear problems with NEWTON solve option, the code can be further optimized. This can make the performance for those problems particularly in neutronics with Griffin much better (potentially 10 times faster) and close to the performance of stand-alone single physics codes to meet users' expectations. Tag @jortensi 

## Impact
Optimization for certain calculations which may require minor user interface changes.

**Comment by loganharbour** [comment]
@YaqiWang does this relate to #18527?

**Comment by YaqiWang** [comment]
Yes.
