### ISSUE TITLE
Adding Triangulation Mesh Generator

### ISSUE THREAD

**Issue by aaronoaks** [idaholab/moose#19372]
## Reason
`TriangulatedMeshGenerator` creates a meshgenreator functionality for triangulating an outer boundary region surrounding an existing meshgenerator mesh.

## Design
This meshgenerator provides an interface to the 3rd party triangulation library poly2tri (https://github.com/jhasse/poly2tri). The outer boundary nodes of an input meshgenerator are extracted as the inner boundary of the triangulated region, and input parameters are used to construct a circular outer boundary of the triangulated region. These nodes are provided to the poly2tri library for triangulation, and the resulting triangles are added to the input mesh.

## Impact
This enhancement will add meshgenerator triangulation functionality. The 3rd party poly2tri library will be added as contrib.

**Comment by loganharbour** [comment]
Base API added in libMesh: https://github.com/libMesh/libmesh/pull/3095
