### ISSUE TITLE
No slip tris INSFV test doesn't look good

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#19403]
## Bug Description

This looks like some of the fractal art @grmnptr has shown me before

<img width="454" alt="Screen Shot 2021-11-15 at 6 28 01 PM" src="https://user-images.githubusercontent.com/10248304/141884774-a428365c-4955-46d5-96c2-54d08762708b.png">

## Steps to Reproduce
Just look at the `moose/modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/cylindrical/gold/no-slip-tris_out.e` gold file. Who made that test anyway?! 😅 

## Impact
Some more evidence that we've got some wonky stuff going on with triangles in our NSFV code

**Comment by lindsayad** [comment]
Maybe this is simply to be expected. This is from a pretty macrosopically good looking channel flow case that shows the same "checkerboard" from cell to cell

<img width="1301" alt="Screen Shot 2021-11-15 at 6 42 25 PM" src="https://user-images.githubusercontent.com/10248304/141886215-d0eaf6e7-4843-4c2f-92c1-b5f9e1886c05.png">

**Comment by lindsayad** [comment]
@grmnptr in the elbow result that you just showed, do you see the fractal pattern when you zoom in like the figures above show?

**Comment by lindsayad** [comment]
I think this result is normal. If it's not, we can reopen

**Comment by grmnptr** [comment]
Oh sorry about not replying to this issue. Yes, the elbow case showed the same behavior. It is due to the fact that the centers of the neighboring triangles are not aligned. I agree that this looks normal. I wonder if the choice of the non-orthogonal correction method influences this.
