### ISSUE TITLE
Need to convert SolveObject to Executor

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#19416]
## Reason
To make the new system with Executor more reliable for application to use, we will need to convert `SolveObject`s in MOOSE framework to `Executor`s.

## Design
I think `Executor` should have its own inheritance instead of deriving from `Executioner`. We also need to allow programmatically create executors. I will make an attempt starting from `FEProblemSolve` then other iterative solve objects.

## Impact
In order to proceed for more sophisticated solvers in Griffin. This will be an internal change, so impact to applications or user interface should not be expected.

**Comment by YaqiWang** [comment]
I made a little attempt on this but realized there are design issues. We possibly can separate Executor and Executioner and have a function like this
```
  template <typename T>
  T &
  addExecutor(const std::string & type)
  {
    auto params = _factory.getValidParams(type);
    // _pars, i.e. executioner's valid parameters contains valid parameters of this executor
    params.applyParameters(_pars);
    _app.addExecutor(type, "_"+type, params);
    return dynamic_cast<T&>(_app.getExecutor("_"+type));
  }
```
in `Executioner` for programmatically adding executors, but currently executors takes inner executors only from input, we do not have the capability like `_fixed_point_solve->setInnerSolve(_feproblem_solve);` in `SolveObject` unless add `Executor::setInnerExecutor`.

**Comment by lindsayad** [comment]
I think this has been subsumed into #20123
