### ISSUE TITLE
Change Linux/Mac installation description on website.

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#19452]
## Reason
The website does not state that you have to deactivate/reactivate your conda environment so that it can activate the environment variables (LIBMESH_DIR, etc). Furthermore, as it turns out, mamba has activate/init functions enabling a fully-mamba based installation guide. This would also give an alternative to the close the terminal and open a new approach.

## Design
Modify conda.md, install_conda_moose.md. 

## Impact
I believe that this would help beginners through the installation process.

**Comment by milljm** [comment]
I believe the latest PR #21769 addresses this issue.
