### ISSUE TITLE
Sibling (MultiApp to MultiApp) Transfers

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#19451]
## Reason
Allowing for multiapp to multiapp direct transfers avoids having a variable on the mesh in the main app to temporarily store the result.

## Design
Think it through in every transfer since we d want that to be a general capability

Need a `to_multiapp` and `from_multiapp`

## Impact
Shorter input files with multiapps
-1/3 of the memory cost currently used for those operations

**Comment by friedmud** [comment]
AKA sibling or peer transfers (for searchability)

**Comment by friedmud** [comment]
Design note: should be entirely initiated and housed in the master app (i.e. the siblings still shouldn't know that it is happening)

**Comment by lindsayad** [comment]
It would be nice to have a reference to the PR on this issue. And should this now be closed?

**Comment by GiudGiud** [comment]
@fdkong will implement more of the transfers with siblings. My PR only does copy, postprocessor stuff and a new API

**Comment by fdkong** [comment]
My PR is right here that will implement this feature 

https://github.com/idaholab/moose/pull/17417

**Comment by lindsayad** [comment]
exciting stuff!
