### ISSUE TITLE
Compute off-diagonal terms of the Jacobian in CoupledVarNeumannBC

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#19468]
### Discussed in https://github.com/idaholab/moose/discussions/19465

<div type='discussions-op-text'>

<sup>Originally posted by **aaelmeli** November 23, 2021</sup>
Hi

I recently encountered a problem where I have two Linear Systems that are coupled only on the boundaries.  The `CoupledVarNeumannBC`  object was used to achieve the coupling. The issue is, `CoupledVarNeumannBC` does not have a method that provides the Jacobian. This means that, whenever a direct linear solver is used, it will not show any coupling because the contribution of the `CoupledVarNeumannBC`  to the off-diagonal terms in the Jacobian is zero. This enforces using a nonlinear solver where the Jacobian can be approximated numerically using for example FD. This issue was under discussion in #19365 where @GiudGiud had fruitful thoughts. The issue is, for some coupled PDEs, like the one in #19365, this would result in slow convergence or even divergence.

So, I am re-posting the following question here to have better visibility in case anyone encountered a similar problem.

The question is, Is it possible to implement a function that calculates the Jacobian terms of the `CoupledVarNeumannBC` object? Any thoughts on the implementation?
</div>

The initial implementation in https://github.com/idaholab/moose/pull/13503 was for auxes, but if a user uses this with a nonlinear variable, then their Jacobian will be wrong. So we will add the requisite `computeQpOffDiagJacobian override` implementation

**Comment by GiudGiud** [comment]
@lindsayad are you tackling this?

**Comment by lindsayad** [comment]
I would do it tomorrow because I am working on slides today (when not reviewing tensor calculus 😆 and debating you). If you wanted to do it today, then go for it

**Comment by YaqiWang** [comment]
Even the coupled variable is an aux var, when it is evaluated from a nonlinear variable on linear, the Jacobian will be wrong as well. Are you planing to address it as well?

**Comment by lindsayad** [comment]
No I am not. If the coupled variable is an aux variable I will not be adding anything to the Jacobian, so if the user has made an aux variable that is dependent on nonlinear dofs then that information will be lost. This same concern applies for all residual objects and I'm not going to do anything special just for this one object.

**Comment by GiudGiud** [comment]
For future readers, AuxVariables are the wrong object to couple in nonlinear variables. We would support this through the material property system.
