### ISSUE TITLE
Specify which variables are to be autoscaled

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#19572]
## Reason
Autoscaling is awesome...most of the time. Sometimes, a variable's residual is way off during a given timestep, such that manual scaling is more appropriate. Being able to choose which variables are available for automatic scaling, and others are only manually scaled, will allow flexibility.

## Design
An executioner option like `autoscaled_variables = 'temp disp_x disp_y` or something similar.

## Impact
Flexibility in autoscaling.

**Comment by tophmatthews** [comment]
I've been thinking about this again @lindsayad ... poking around in `NonlinearSystemBase::computeScaling()` it doesn't look too difficult, but I'm having a hard time seeing the full picture to make sure nothing is missed...

**Comment by lindsayad** [comment]
I don't think it would be very difficult
