### ISSUE TITLE
Add new ID generators and VPP based on parsed extra ID - ExtraIDIntegralVectorPostprocessor, ParsedExtraIDMeshGenerator and DepletionIDGenerator

### ISSUE THREAD

**Issue by yjung-anl** [idaholab/moose#19611]
## Reason

In the PR of  `Reactor module Reporting ID` capabilities (issue #19217  PR #19218), reviewers suggested to move some functionalities in this PR can be moved to the framework side because they could be general objects, not restricted to reactor applications.

A vector postprocessor named `IntegralReportingIDVPP`, which is to integrate a variable based on parsed  reporting IDs, is one of the functionalities to be included to the framework. This vector postprocssor is renamed as `ExtraIDIntegralVectorPostprocessor` and is updated as a general vector postprocessor. This object will be located in the MOOSE framework.

`DepletionIDGenerator` object generates and assigns depletion IDs (`extra IDs`) on a mesh by finding unique combinations of reporting and material IDs. This object will be located in the `reactor` module.

`ParsedExtraIDMeshGenerator` is a generalized version of `DepletionIDGenerator`, which generates a new set of `extra IDs` determined by parsing existing `extra IDs`. It can be utilized for reactor and non-reactor applications. This object will be located in the moose framework. 

## Design

`ExtraIDIntegralVectorPostprocessor`, `DepletionIDGenerator`  and `ParsedExtraIDMeshGenerator` are commonly based on the parsing algorithm of extra IDs: 
* Take a set of `extra element IDs` as an input parameters
* Compute a variable integral or assign a new set of extra ID based on the parsed `extra element IDs`. 

## Impact

New ID generators and VPP based on parsed `extra ID` will be available in the MOOSE framework and the reactor module.

**Comment by GiudGiud** [comment]
should this be closed @yjung-anl
