### ISSUE TITLE
Adding coupledArrayValues in Coupleable

### ISSUE THREAD

**Issue by yjung-anl** [idaholab/moose#19677]
## Reason

Currently, `Coupleable` class currently does not support `coupledArrayValues`, `coupledValues` for array variable version. 

## Design

Add `coupledArrayValues` function in `Coupleable` class by referring the existing `coupledValues`.  

## Impact

If `coupledArrayValues` becomes available, `std::vector<const ArrayVariableValue *>` can be easily set up.

**Comment by loganharbour** [comment]
Closedin #19678
