### ISSUE TITLE
Mortar mechanical contact for dynamics

### ISSUE THREAD

**Issue by recuero** [idaholab/moose#19671]
## Reason

- Extend the benefits of mortar mechanical contact (better convergence, contact patch fulfillment, spatial smoothness) to dynamics. 
- Create a wear model based on frictional energy to enable modeling of 

## Design

- [x] Stabilize normal and frictional mortar mechanical contact constraints via additional dependence on normal gap velocities and accelerations. 
- [x] Avoid spurious contact force oscillations by introducing dissipation into the Newmark-beta integration scheme, see [1] and #18419.  
- [x] Add computation of worn depth, e.g. as in Archard's law
- [x] Couple wear with some material removal mechanisms, such as element death. This was done by introducing a physics-driven interpenetration, which is valid for relatively wear depths 

## Impact

- More accurate contact modeling in dynamics
- Ability to model wear due to friction

## Reference
[1] Deuflhard et al, 2008, "A contact-stabilized Newmark method for dynamical contact problems", International Journal for Numerical Methods in Engineering; 73:1274--1290

**Comment by lindsayad** [comment]
Should we just fold #18419 into this issue or do you see them as distinct?

**Comment by recuero** [comment]
Closed that one and added the time integrator as a task within this issue.
