### ISSUE TITLE
Same issue of stateful mat prop with DG #11766

### ISSUE THREAD

**Issue by AhmedAlmetwally** [idaholab/moose#19735]
## Bug Description
We are trying to couple the DG and CG schemes for diffusion problems to enforce mass conservation. We started with adding a DG kernel to the diffusion CG kernel and ran the same input file of issue #11766 and got the following error:

```
Assertion `i < _size' failed

Access out of bounds in MooseArray (i: 0 size: 0)

at /Users/aalmetwally/projects/moose/framework/build/header_symlinks/MooseArray.h, line 276

Stack frames: 16

0: 0   libmesh_dbg.0.dylib                 0x000000010b6d8232 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 626

1: 1   libporous_flow-dbg.0.dylib          0x0000000100281b4d MooseArray<double>::operator[](unsigned int) const + 941

2: 2   libporous_flow-dbg.0.dylib          0x000000010037d586 PorousFlow1PhaseFullySaturated::buildQpPPSS() + 38

3: 3   libporous_flow-dbg.0.dylib          0x0000000100391858 PorousFlow1PhaseFullySaturated::initQpStatefulProperties() + 40

4: 4   libmoose-dbg.0.dylib                0x0000000103bfcdae MaterialBase::initStatefulProperties(unsigned int) + 94

5: 5   libporous_flow-dbg.0.dylib          0x0000000100390d8b PorousFlowMaterial::initStatefulProperties(unsigned int) + 107

6: 6   libmoose-dbg.0.dylib                0x0000000103d25487 MaterialPropertyStorage::initStatefulProps(MaterialData&, std::__1::vector<std::__1::shared_ptr<MaterialBase>, std::__1::allocator<std::__1::shared_ptr<MaterialBase> > > const&, unsigned int, libMesh::Elem const&, unsigned int) + 199

7: 7   libmoose-dbg.0.dylib                0x0000000104a01305 ComputeMaterialsObjectThread::onInternalSide(libMesh::Elem const*, unsigned int) + 1285

8: 8   libmoose-dbg.0.dylib                0x000000010408c4d4 ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool) + 1412

9: 9   libmoose-dbg.0.dylib                0x00000001042326f1 FEProblemBase::initialSetup() + 21329

10: 10  libmoose-dbg.0.dylib                0x0000000103b503ef Transient::init() + 2415

11: 11  libmoose-dbg.0.dylib                0x0000000105251516 MooseApp::executeExecutioner() + 1350

12: 12  libmoose-dbg.0.dylib                0x000000010524b44f MooseApp::run() + 8415

13: 13  porous_flow-dbg                     0x000000010000cfb5 main + 149

14: 14  libdyld.dylib                       0x00007fff20438f3d start + 1

15: 15  ???                                 0x0000000000000003 0x0 + 3

[0] /Users/aalmetwally/projects/moose/framework/build/header_symlinks/MooseArray.h, line 276, compiled Dec 10 2021 at 11:50:32

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0

[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1

:

system msg for write_line failure : Bad file descriptor

Process 14528 exited with status = 1 (0x00000001) 
```

## Steps to Reproduce

```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 2
  ny = 2
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 1
  elem_type = QUAD4
[]

[Variables]
  [./u]
    order = FIRST
    family = MONOMIAL
    [./InitialCondition]
      type = ConstantIC
      value = 1
    [../]
  [../]
[]

[Functions]
  [./forcing_fn]
    type = ParsedFunction
    value = 2*pow(e,-x-(y*y))*(1-2*y*y)
  [../]
  [./exact_fn]
    type = ParsedGradFunction
    value = pow(e,-x-(y*y))
    grad_x = -pow(e,-x-(y*y))
    grad_y = -2*y*pow(e,-x-(y*y))
  [../]
[]

[Kernels]
  [./diff]
    type = Diffusion
    variable = u
  [../]
  [./abs]          # u * v
    type = Reaction
    variable = u
  [../]
  [./forcing]
    type = BodyForce
    variable = u
    function = forcing_fn
  [../]
[]

[DGKernels]
  [./dg_diff]
    type = DGDiffusion
    variable = u
    epsilon = -1
    sigma = 6
  [../]
[]

[BCs]
  [./all]
    type = DGFunctionDiffusionDirichletBC
    variable = u
    boundary = '0 1 2 3'
    function = exact_fn
    epsilon = -1
    sigma = 6
  [../]
[]

[Materials]
  [./stateful]
    type = StatefulMaterial
    initial_diffusivity = 1
    boundary = 'left'
  [../]
  [./general]
    type = GenericConstantMaterial
    block = '0'
    prop_names = 'dummy'
    prop_values = '1'
  [../]
[]

[Executioner]
  type = Steady
  solve_type = 'PJFNK'
  nl_rel_tol = 1e-10
[]

[Postprocessors]
  active = 'h dofs l2_err'
  [./h]
    type = AverageElementSize
  [../]
  [./dofs]
    type = NumDOFs
  [../]
  [./l2_err]
    type = ElementL2Error
    variable = u
    function = exact_fn
  [../]
[]

[Outputs]
  file_base = out
  exodus = true
  csv = true
[]
```

## Impact
Cannot run DG model through the porousFlow module @lynnmunday @lindsayad

**Comment by lindsayad** [comment]
Can you paste your input file with ``` formatting please? You can see that the '*' applied github markdown as opposed to indicating multiplication

**Comment by AhmedAlmetwally** [comment]
Do not understand your comment but here is the input file: @lindsayad @lynnmunday 

Also attached in .docx file to be uploadable to Github.
[input.docx](https://github.com/idaholab/moose/files/7765466/input.docx)

Thanks in advance!

'
[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 10
  ny = 1
  nz = 1
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 0.1
  zmin = 0
  zmax = 1
[]

[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
  PorousFlowDictator = dictator
  block = 0
[]

[UserObjects]
  [dictator]
    type = PorousFlowDictator
    porous_flow_vars = 'porepressure disp_x disp_y disp_z'
    number_fluid_phases = 1
    number_fluid_components = 1
  []
[]

[Variables]
  [disp_x]
  []
  [disp_y]
  []
  [disp_z]
  []
  [porepressure]
  []
[]

[BCs]
  [roller_xmin]
    type = DirichletBC
    variable = disp_x
    value = 0
    boundary = 'left'
  []
  [roller_ymin]
    type = DirichletBC
    variable = disp_y
    value = 0
    boundary = 'bottom'
  []
  [plane_strain]
    type = DirichletBC
    variable = disp_z
    value = 0
    boundary = 'back front'
  []
  [xmax_drained]
    type = DirichletBC
    variable = porepressure
    value = 0
    boundary = right
  []
  [top_velocity]
    type = FunctionDirichletBC
    variable = disp_y
    function = top_velocity
    boundary = top
  []
[]

[Functions]
  [top_velocity]
    type = PiecewiseLinear
    x = '0 0.002 0.006   0.014   0.03    0.046   0.062   0.078   0.094   0.11    0.126   0.142   0.158   0.174   0.19 0.206 0.222 0.238 0.254 0.27 0.286 0.302 0.318 0.334 0.35 0.366 0.382 0.398 0.414 0.43 0.446 0.462 0.478 0.494 0.51 0.526 0.542 0.558 0.574 0.59 0.606 0.622 0.638 0.654 0.67 0.686 0.702'
    y = '-0.041824842    -0.042730269    -0.043412712    -0.04428867     -0.045509181    -0.04645965     -0.047268246 -0.047974749      -0.048597109     -0.0491467  -0.049632388     -0.050061697      -0.050441198     -0.050776675     -0.051073238      -0.0513354 -0.051567152      -0.051772022     -0.051953128 -0.052113227 -0.052254754 -0.052379865 -0.052490464 -0.052588233 -0.052674662 -0.052751065 -0.052818606 -0.052878312 -0.052931093 -0.052977751 -0.053018997 -0.053055459 -0.053087691 -0.053116185 -0.053141373 -0.05316364 -0.053183324 -0.053200724 -0.053216106 -0.053229704 -0.053241725 -0.053252351 -0.053261745 -0.053270049 -0.053277389 -0.053283879 -0.053289615'
  []
[]

[AuxVariables]
  [stress_yy]
    order = CONSTANT
    family = MONOMIAL
  []
  [tot_force]
    order = CONSTANT
    family = MONOMIAL
  []
[]

[AuxKernels]
  [stress_yy]
    type = RankTwoAux
    rank_two_tensor = stress
    variable = stress_yy
    index_i = 1
    index_j = 1
  []
  [tot_force]
    type = ParsedAux
    args = 'stress_yy porepressure'
    execute_on = timestep_end
    variable = tot_force
    function = '-stress_yy+0.6*porepressure'
  []
[]

[Kernels]
  [./diff]
    type = Diffusion
    variable = porepressure
  [../]
  [grad_stress_x]
    type = StressDivergenceTensors
    variable = disp_x
    component = 0
  []
  [grad_stress_y]
    type = StressDivergenceTensors
    variable = disp_y
    component = 1
  []
  [grad_stress_z]
    type = StressDivergenceTensors
    variable = disp_z
    component = 2
  []
  [poro_x]
    type = PorousFlowEffectiveStressCoupling
    biot_coefficient = 0.6
    variable = disp_x
    component = 0
  []
  [poro_y]
    type = PorousFlowEffectiveStressCoupling
    biot_coefficient = 0.6
    variable = disp_y
    component = 1
  []
  [poro_z]
    type = PorousFlowEffectiveStressCoupling
    biot_coefficient = 0.6
    component = 2
    variable = disp_z
  []
  [mass0]
    type = PorousFlowFullySaturatedMassTimeDerivative
    biot_coefficient = 0.6
    multiply_by_density = false
    coupling_type = HydroMechanical
    variable = porepressure
  []
  [flux]
    type = PorousFlowFullySaturatedDarcyBase
    multiply_by_density = false
    variable = porepressure
    gravity = '0 0 0'
  []
[]
[DGKernels]
  [./dg_diff]
    type = DGDiffusion
    variable = porepressure
    epsilon = -1
    sigma = 6
  [../]
[]


[Modules]
  [FluidProperties]
    [simple_fluid]
      type = SimpleFluidProperties
      bulk_modulus = 8
      density0 = 1
      thermal_expansion = 0
      viscosity = 1
    []
  []
[]

[Materials]
  [temperature]
    type = PorousFlowTemperature
  []
  [elasticity_tensor]
    type = ComputeElasticityTensor
    C_ijkl = '0.5 0.75'
    # bulk modulus is lambda + 2*mu/3 = 0.5 + 2*0.75/3 = 1
    fill_method = symmetric_isotropic
  []
  [strain]
    type = ComputeSmallStrain
  []
  [stress]
    type = ComputeLinearElasticStress
  []
  [eff_fluid_pressure_qp]
    type = PorousFlowEffectiveFluidPressure
  []
  [vol_strain]
    type = PorousFlowVolumetricStrain
  []
  [ppss]
    type = PorousFlow1PhaseFullySaturated
    porepressure = porepressure
  []
  [massfrac]
    type = PorousFlowMassFraction
  []
  [simple_fluid_qp]
    type = PorousFlowSingleComponentFluid
    fp = simple_fluid
    phase = 0
  []
  [porosity]
    type = PorousFlowPorosityConst # only the initial value of this is ever used
    porosity = 0.1
  []
  [biot_modulus]
    type = PorousFlowConstantBiotModulus
    biot_coefficient = 0.6
    solid_bulk_compliance = 1
    fluid_bulk_modulus = 8
  []
  [permeability]
    type = PorousFlowPermeabilityConst
    permeability = '1.5 0 0   0 1.5 0   0 0 1.5'
  []
[]

[Postprocessors]
  [p0]
    type = PointValue
    outputs = csv
    point = '0.0 0 0'
    variable = porepressure
  []
  [p1]
    type = PointValue
    outputs = csv
    point = '0.1 0 0'
    variable = porepressure
  []
  [p2]
    type = PointValue
    outputs = csv
    point = '0.2 0 0'
    variable = porepressure
  []
  [p3]
    type = PointValue
    outputs = csv
    point = '0.3 0 0'
    variable = porepressure
  []
  [p4]
    type = PointValue
    outputs = csv
    point = '0.4 0 0'
    variable = porepressure
  []
  [p5]
    type = PointValue
    outputs = csv
    point = '0.5 0 0'
    variable = porepressure
  []
  [p6]
    type = PointValue
    outputs = csv
    point = '0.6 0 0'
    variable = porepressure
  []
  [p7]
    type = PointValue
    outputs = csv
    point = '0.7 0 0'
    variable = porepressure
  []
  [p8]
    type = PointValue
    outputs = csv
    point = '0.8 0 0'
    variable = porepressure
  []
  [p9]
    type = PointValue
    outputs = csv
    point = '0.9 0 0'
    variable = porepressure
  []
  [p99]
    type = PointValue
    outputs = csv
    point = '1 0 0'
    variable = porepressure
  []
  [xdisp]
    type = PointValue
    outputs = csv
    point = '1 0.1 0'
    variable = disp_x
  []
  [ydisp]
    type = PointValue
    outputs = csv
    point = '1 0.1 0'
    variable = disp_y
  []
  [total_downwards_force]
     type = ElementAverageValue
     outputs = csv
     variable = tot_force
  []
  [dt]
    type = FunctionValuePostprocessor
    outputs = console
    function = if(0.15*t<0.01,0.15*t,0.01)
  []
[]

[Preconditioning]
  [andy]
    type = SMP
    full = true
    petsc_options_iname = '-ksp_type -pc_type -sub_pc_type -snes_atol -snes_rtol -snes_max_it'
    petsc_options_value = 'gmres asm lu 1E-14 1E-10 10000'
  []
[]

[Executioner]
  type = Transient
  solve_type = Newton
  start_time = 0
  end_time = 0.7
  [TimeStepper]
    type = PostprocessorDT
    postprocessor = dt
    dt = 0.001
  []
[]

[Outputs]
  execute_on = 'timestep_end'
  file_base = mandel_fully_saturated_volume
  [csv]
    interval = 3
    type = CSV
  []
[]


'

**Comment by lindsayad** [comment]
Hi I believe that #19918 will fix your issue. So in this method that you are trying, it makes sense to use a continuous basis (implicitly you are using first order Lagrange) with the DG method? Classical DG of course should use a discontinuous basis

**Comment by hugary1995** [comment]
Isn't the DGDiffusion residual always zero in this case?

**Comment by lindsayad** [comment]
The contribution from jump terms will be zero, but there are terms in `DGDiffusion` that don't depend on jumps
