### ISSUE TITLE
Need a DomainUserObject

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#19995]
## Reason
We need a new type of user object, with temporary name `DomainUserObject` (better name suggestions are welcome). This new user object is defined still on subdomains, but it can contain operations on elements and all sides (including boundary sides, internal sides and internal boundary sides). We want this `DomainUserObject` because we have needs to gather information in one place based on elemental and side quantities. Without this user object, we would need four separate user objects: one elemental user object, one internal side user object, one side user object and one general user object. It is quite tedious to manage these four user objects together, such as valid parameters, the same execute_on, etc.

## Design
Adding this `DomainUserObject` can possibly be done with existing warehouse capabilities. Changes in `ComputeUserObjectsThread.C` are also expected. Currently we do not need to handle operations on nodes. Griffin developers can possible help on this. Tag @jthano.

## Impact
A new capability.

**Comment by jthano** [comment]
What I did not like about any idea discussed was the lack of control for when the various references are used. In the element UO, or side UO, the references are always set to something valid before execute is called. But with a domainUO, you could access _current_neighbor_volume from executeOnBoundary for example. Obviously we could just think a user shouldn't do that. I guess that was the solution
