### ISSUE TITLE
Explicitly specify index type for nanoflann objects

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#19999]
## Reason
Recent nanoflann versions change the default of the index type from `std::size_t` to `uint32_t`. This breaks our current code. 

## Design
Specify `std::size_t` explicitly using an additional template parameter.

## Impact
Prepare code for nanoflann update in libmesh.

**Comment by loganharbour** [comment]
Please add labels in the future

**Comment by dschwen** [comment]
> Please add labels in the future

Future Daniel here: They were already added in the past :-(
