### ISSUE TITLE
Fix inconsistencies in AD and nonAD SingleVariableReturnMappingSolution

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#20041]
## Reason
`ADSingleVariableReturnMappingSolution` and `SingleVariableReturnMappingSolution` diverge slightly in their implementation, making it difficult for inherited classes to have a single AD/non-AD class.

## Design
Make `ADSingleVariableReturnMappingSolution` and `SingleVariableReturnMappingSolution` consistant, and then converge them into one.

## Impact
More consistant code implementation.

**Comment by loganharbour** [comment]
Closed in #20042 @tophmatthews?

**Comment by tophmatthews** [comment]
No, mine is just a quick fix. I was hoping @dschwen could delegate this? I can pick it up eventually...

**Comment by tophmatthews** [comment]
Closed by #20997
