### ISSUE TITLE
Make the Newton eigensolver in SLEPc support custom normalization

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#20095]
## Reason
For lots of neutron transport calculations, we observed more nonlinear iterations with the current Newton eigensolver in SLEPc than with the old implementation of the Newton eigensolver in MOOSE even though they are using the same algorithm. The reason is that the implementation in SLEPc is using the numerical L2 norm of `Bx` as the inverse of the eigenvalue during the solve, while the old implementation relies on a postprocessor provided by the users, which typically is the total neutron production through the fission event related with `B` operator. This slower convergence issue is preventing us from switching to the new implementation with SLEPc. I realized that I mentioned this issue multiple times but never created an issue until now.

## Design
Because in SLEPc implementation, every linear iteration we call a residual evaluation, which not only can give `Ax`, `Bx` but also postprocessors evaluated during the residual evaluation. It makes sense to let SLEPc directly use a postprocessor value for the final residual as `Ax - Bx / pp` instead of `Ax - Bx / ||Bx||_2`. This can be used to solve #18365. I did not look into the code, thus not sure if this can be done simply in MOOSE or changes of SLEPc is necessary. It is noted that this issue is not significant for the latest `PJFNKMO` option because the residual evaluation is fast and we do not have a way to evaluate the postprocessor value based on `x` other than simple `||Bx||_2`.

## Impact
Less confusion to users for deciding which eigensolver to use and reduce our burden for maintaining two implementations.

**Comment by YaqiWang** [comment]
@oanaoana @friedmud I added a test that shows the slower convergence of our new implementation of the PJFNK eigenvalue executioner. I suspect it is the choice of evaluating `|Bx|` causing the issue. Please check out the above commit linked by Github. Thanks.

**Comment by oanaoana** [comment]
Replicating this issue I noted that the convergence rate may not be the only difference here, and accuracy itself differs.  For an imposed tolerance of 1e-10, the Eigenvalue/PJFNK executioner (based on the SLEPc implementation) takes 11 iterations and gives the eigenvalue 1.0063926406, while the NonlinearEigen executioner (native to MOOSE) takes 4 iterations and gives the eigenvalue 0.9936479661. Although the same _**tolerance 1e-10**_ is imposed the converged **_results differ by 0.012_**, which is significantly larger. 

If the only solver difference is the norm used for defining the tolerance, which I am not sure yet, it implies that the norm has an impact on the solution itself. Mathematically this makes sense to me, but I am unsure of the implication for the applications of these solvers. Is an error of 1e-2 acceptable? If so why is a tolerance of 1e-10 used when faster convergence can be achieved with a lower tolerance?

**Comment by oanaoana** [comment]
I need to create a function example for an alternative `pp` norm, as in @YaqiWang example above. Could you give me an expression that should work to see how the function should be setup, and what arguments it should take? It can be later tweaked or relaxed if not general enough.

**Comment by lindsayad** [comment]
I'm thinking the callback function would be of the form
```
PetscErrorCode callBack(Vec vec, PetscReal * norm);
```

**Comment by YaqiWang** [comment]
Try using this `fluxintegral` postprocessor like in `NonlinearEigen` with `bx_norm = fluxintegral`.

**Comment by YaqiWang** [comment]
Note that we probably want to make the value returned by the call-back function a by-product of the residual evaluation.

**Comment by lindsayad** [comment]
There should be a callback function in slepc that we can assign in MOOSE. And our implementation of that callback function can just return the already-computed norm per @YaqiWang's statement. Even though we will pre-compute the norm in MOOSE, I still think the callback function signature should look like 
```
PetscErrorCode callBack(Vec vec, PetscReal * norm);
```
We just won't use the `vec` parameter and we can directly assign our pre-computed norm to `norm`

**Comment by lindsayad** [comment]
We will want to add an API to set the postprocessor automatically to make life easier for @YaqiWang

**Comment by lindsayad** [comment]
Follow on completed in #26036
