### ISSUE TITLE
Remove "master" from MultiApp system

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#20124]
## Reason
There is no reason to call the "higher level" app the "master"... better terminology is the "parent" app.  We should change everything in the MultiApp system that mentions "master" including the documentation.

## Design
See above.

## Impact
May modify some documentation - but shouldn't do much more than that.

**Comment by brandon-biggs** [comment]
I'll take a look at this.

**Comment by GiudGiud** [comment]
Closed by #20986
