### ISSUE TITLE
NS finite_volume/wcns/boundary_conditions.dirichlet/using_velocity test fails occasionally

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#20133]
## Bug Description
See [this CIVET target failure](https://civet.inl.gov/job/941287/) for an example failure. This is at least the second time I've seen that test fail

## Steps to Reproduce
Run CIVET a bunch of times

## Impact
Gives false negatives on unrelated PR testing, holding up overall MOOSE development

**Comment by lindsayad** [comment]
@GiudGiud could also take care of this if he gets to it before me

**Comment by GiudGiud** [comment]
Weird. 6e-5 relative error on 6e-8 in one cell.
And cant see why a glorified dirichlet BC would fail on threads

**Comment by lindsayad** [comment]
I think the fact that it's threads only matters insofar as you may get different ordering of floating point operations. I ran helgrind on this test the last time that it failed and it was clean

**Comment by lindsayad** [comment]
I double-checked and no helgrind errors
