### ISSUE TITLE
Migrate (mortar) mechanical contact to use Eisenstat-Walker

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#20143]
## Reason
Oftentimes early in a contact solve, particularly for frictional, we can solve the linear system too tightly. Not only is this a waste of computational resources, it can actually make the solve worse and sometimes not converge. This is because early in a contact solve when we have not resolved our contact set, our function is very noisy, and oftentimes our finite difference approximation of the Jacobian action leads us in a bad direction. If you pass `-ksp_monitor_true_residual`, you can observe the behavior oftentimes that the true residual actually *increases* with increasing number of linear iterations.

By passing `-snes_ksp_ew` we do not take a lot of linear iterations early in the solve and consequently we do not proceed too far down a bad path. This is good for both robustness and for speed for PJFNK.

## Design
Pass `-snes_ksp_ew` in `petsc_options`

## Impact
Make (mortar) contact (tests) more robust

**Comment by lindsayad** [comment]
@recuero didn't you do a bunch of this?

**Comment by recuero** [comment]
I did. But mixed in bigger changes. As in #20620, I think there is an instance at least. I remember that, for some mortar mechanical contact tests, this change was detrimental to convergence as the tests were set up, so I didn't change a number of those.

**Comment by lindsayad** [comment]
Going to regard this as closed due to #20620 (EW applied where appropriate; it is not a catch-all)
