### ISSUE TITLE
No Error when specifying different background_block_ids but same background_block_names

### ISSUE THREAD

**Issue by olinwc** [idaholab/moose#20148]
## Bug Description

@eshemon @shikhar413 in the reactor module, when passing in two different `PolygonConcentricCircleMeshGenerator` blocks into `PatternedHexMeshGenerator` with different `background_block_ids` but the same `background_block_names` the mesh will be generated but will error out when opening in Paraview.

## Steps to Reproduce

Run the following input (named `error_check_1.i`) with

```
./reactor-opt -i error_check_1.i --mesh-only "error_check_1.e"
```

```
[Mesh]
  [hex_1]
    type = PolygonConcentricCircleMeshGenerator
    num_sides = 6
    num_sectors_per_side = '4 4 4 4 4 4'
    background_intervals = 2
    ring_radii = 4.0
    ring_intervals = 2
    ring_block_ids = '10 15'
    ring_block_names = 'center_tri center'
    background_block_ids = 20
    background_block_names = background
    polygon_size = 5.0
    preserve_volumes = on
  []
  [hex_2]
    type = PolygonConcentricCircleMeshGenerator
    num_sides = 6
    num_sectors_per_side = '4 4 4 4 4 4'
    background_intervals = 2
    ring_radii = 4.0
    ring_intervals = 2
    ring_block_ids = '10 15'
    ring_block_names = 'center_tri center'
    background_block_ids = 30
    background_block_names = background
    polygon_size = 5.0
    preserve_volumes = on
  []
  [pattern]
    type = PatternedHexMeshGenerator
    inputs = 'hex_1 hex_2'
    pattern_boundary = none
    pattern = '0 0;
              0 1 0;
               0 0'
  []
[]
```

Then try to open the mesh in Paraview

## Impact

Annoyance. It was an easy fix for me, but it seems bad if something runs without erroring out in moose but then errors out in Paraview.

**Comment by eshemon** [comment]
Thanks for reporting this! CC'ing @miaoyinb

**Comment by miaoyinb** [comment]
Thanks @eshemon and @olinwc. I will look into this.
