### ISSUE TITLE
MOOSE footprint

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#2016]
Well, re-looking what I did in one of the channel tests (one of the most complicated tests disabled by Andrew) is giving me headache. I have to dig into MOOSE again to figure out when the IC is evaluated, when the aux kernel setups are called, etc. Maybe we should have a debug option in [Debug] block, show_MOOSE_footprint. With this option turned on, MOOSE will make some extra screen print-outs telling me some events are executing, like residual evaluation, aux kernel compute, timestep setups, .... basically showing the 'footprint' of MOOSE. In this way, it will be much easier for me to check if my objects are doing their job at the correct points. I think this is a good idea, but not sure if you guys like it or not.

**Comment by permcody** [comment]
Closed by TimedPrint (#13604)
