### ISSUE TITLE
Face Variable Support

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#20191]
## Reason

The development and support of lower-dimensional variables “face variables” in support of high-fidelity reactor analysis in Griffin. 

## Design

This needs to be implemented in both the nonlinear and auxiliary systems.

## Impact

FY22 CRAB WP Task

**Comment by roystgnr** [comment]
Current status:

libMesh has face variables available, with FE type `SIDE_HIERARCHIC`, but not for all geometric element types and orders.  Currently we support face variables in 1D, in 2D, and on Hexes in 3D for p=0,1,2.

Support for cubic and higher face variables on Hexes is *supposed* to be working, but isn't passing tests; I probably have something wrong somewhere in the shape orientation code for those.

Support for face variables on Pyramids is partly done in a branch, but I had to put it down for more urgent tasks before I got it working.  Hopefully once I'm back at it, it won't take too much longer to finish.  Worst-case scenario: if I really get stuck here, I could just merge lower-order variables (IIRC p=0 is already working in the branch, and is all many of our users need ASAP) right away and fix up the higher-order shapes later.

Support for face variables on Prisms isn't started yet.  The underlying work (Tri7 HIERARCHIC support) is shared with Pyramids, though, so hopefully it won't take as much work as they have.

Support for invoking these variables in Moose isn't there yet, but that'll be a fairly tiny shim.  I'll work at that (plus a couple tests) next - it'll be easy and it'll enable Hex+2D work immediately, and if I'm missing something and it's not easy then it'll be best if we learn that immediately.

**Comment by roystgnr** [comment]
This has been working for a while for 2D+Hexes+Prisms, which AFAIK is everything Griffin needs.  The remaining lack of Pyramid support bothers me greatly on an emotional level, and I'll get around to completing that sooner or later, but it's not really worthy of keeping a MOOSE issue open.
