### ISSUE TITLE
Entry for THM in February 2022 news

### ISSUE THREAD

**Issue by cticenhour** [idaholab/moose#20221]
## Reason
THM was technically released to the public at the very end of January (#19916), but that newsletter has already gone out, so let's put an announcement out in the February 2022 news.

## Design
Short discussion of THM (features, usage, links to documentation, an image) to notify users and developers of the new capability.

## Impact
More newsletter content! 

---
@andrsd @joshuahansel @permcody This is the follow-up to my review on the THM PR, since we wanted to get that merged. Could one of you do this when you have time? Maybe we can just base the content on the highlight to make it easy.

**Comment by joshuahansel** [comment]
I will do this now.

**Comment by cticenhour** [comment]
Thank you!
