### ISSUE TITLE
Missing framework headers in thermal_hydraulics module

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#20259]
## Reason

All source and header files in the newly added thermal_hydraulics module are missing the standard header.

## Design

Add 

```
//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
```
to the header and source files that are missing the header. 

I believe there is a script in the framework to do this.

## Impact

Consistency

**Comment by loganharbour** [comment]
@andrsd @joshuahansel
