### ISSUE TITLE
Have MooseDocs parameter listing list if the parameter is controllable

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#20315]
## Reason
This lets users know if a parameter has been declared controllable.

## Design
This would change the `!param` MooseDocs command and related functionality to report if a parameter has been declared controllabe via `declareControllable`.

## Impact
More informative documentation.

**Comment by joshuahansel** [comment]
Note this may be related to https://github.com/idaholab/moose/issues/14388.

**Comment by crswong888** [comment]
@andrsd As long as that attribute can be determined from the syntax tree or anything else from the source that MooseDocs is already capable of reading, it should be easy.

If no one else, you may assign this ticket to me. Probably could knock out #14388 as well.

**Comment by loganharbour** [comment]
> As long as that attribute can be determined from the syntax tree  

it can

**Comment by joshuahansel** [comment]
I wouldn't worry about #14388 for the time being - it doesn't need to be considered for the completion of this task. I just mentioned it in case this ticket meets @YaqiWang's needs and thus he can close that ticket after this ticket is completed.
