### ISSUE TITLE
`finite_volume/ins/channel-flow.singular_two_term_expansion` is non-deterministic in threads

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#20326]
## Reason
`finite_volume/ins/channel-flow.singular_two_term_expansion` in navier stokes currently relies on libmeshdeprecation warnings, which are non-deterministic in threads due to the dependency on a static variable

## Design
For now, skip tests for threads. @lindsayad may have a better fix in the future and can edit accordingly.

## Impact
Makes testing more deterministic.

**Comment by GiudGiud** [comment]
have you seen failures for that test?

The test purpose is fulfilled without threads as far as I can tell

**Comment by loganharbour** [comment]
I've seen three failures today. @lindsayad and I already talked about this

**Comment by lindsayad** [comment]
Closed by libmesh/libmesh#3165
