### ISSUE TITLE
Error with conda update

### ISSUE THREAD

**Issue by aarograh** [idaholab/moose#20357]
## Bug Description
Error is reported by conda after executing `conda update`

## Steps to Reproduce
For our MOOSE application, we have a CI set up.  Several months ago, we tried to update the conda MOOSE environment and ran into issues.  The way the machine was set up overall was clunky and confusing, so I simply wiped everything and reset the conda MOOSE environment using the Getting Started instructions.  Everything worked fine at that point.

I am now trying to update again.  My understanding is that `conda update --all` after loading the MOOSE conda environment should update all the packages.  However, I get an error:

```
(moose) [gitlab-runner@gad ~]$ conda update --all
Collecting package metadata (current_repodata.json): - modprobe: FATAL: Module nvidia not found.                                                                                         failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.software.inl.gov/public/linux-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.software.inl.gov/public/linux-64'
```

Retrying does not help.  I also tried this:

```
(moose) [gitlab-runner@gad ~]$ conda config --add channels https://conda.software.inl.gov/public
Warning: 'https://conda.software.inl.gov/public' already in 'channels' list, moving to the top
```

Unsurprisingly, it did not resolve the above error.

Waiting awhile then trying again like the error instructs also fails.  It's unclear to me what the problem is.

## Impact
This prevents our automated testing of our application.  This means we have to rely on 1) manual testing, or 2) not merging anything.  1 is prone to bad code getting into the master branch and 2 obviously is not an option.

Please give me some guidance.  I'd like to avoid wiping and reinstalling the conda environment every time something changes with the MOOSE environment.

**Comment by loganharbour** [comment]
There's not a particularly interesting cause here: conda.software.inl.gov is down.

**Comment by loganharbour** [comment]
> Please give me some guidance. I'd like to avoid wiping and reinstalling the conda environment every time something changes with the MOOSE environment.

And to add to this, I would still suggest for the purposes of CI to init conda every time. You could keep a stateful conda install, but we've had some not-so-great experiences with trying to maintain a conda environment between CI runs.

**Comment by aarograh** [comment]
@loganharbour thanks for the info.  I didn't realize that domain was down, as I hit this error several months ago when that was NOT the issue (I was able to pull everything from the conda server fine on my personal machine but updating the CI machine gave the HTTP error).  I guess I should've checked that first.  I'll try again once that site is up.

Regarding the CI, by "init conda" do you mean reinstalling the environment?  That seems suboptimal.  We have our CI run `conda activate moose` as the first step.  So far that hasn't caused problems.  Perhaps I'm misunderstanding you though.

**Comment by loganharbour** [comment]
> Regarding the CI, by "init conda" do you mean reinstalling the environment?

Nope, this is exactly what I mean. Primarily because updating conda can cause... issues. If you haven't found any issues so far (spare for our services being down on occasion 😆) I'm glad to hear it! Just be prepared to randomly nuke the environment

**Comment by loganharbour** [comment]
Closing as `conda.software.inl.gov` is now available again.
