### ISSUE TITLE
Skip return mapping under purely volumetric loading

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#20363]
## Reason
The computation of the tangent operator involves a normalization of the deviatoric stress. If the norm is zero this results in a _nan_ , a case which is only protected by an assertion. 

## Design
Under volumetric loading we expect no creep or plastic deformation to occur. We should skip the return mapping entirely in this case and return a suitable tangent operator (possibly zero)

## Impact
More robust inelastic deformation solve.

**Comment by WilkAndy** [comment]
Presumably only for the few models (like J2) that don't depend on volumetric stress.

**Comment by dschwen** [comment]
> Presumably only for the few models (like J2) that don't depend on volumetric stress.

Hmm, maybe we should make this optional then. The change in compute tangent operator should always apply though.

**Comment by dschwen** [comment]
I could add a virtual member to the model class that indicates if it isa model that only used deviatoric stress.
