### ISSUE TITLE
Add options to exclude source files from unity build.

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#20403]
## Reason
In some cases when we try to link MOOSE with other libraries, we encounter namespace issues which can be resolved if we pay careful attention to the include order and disable unity build. This, however, slows down the compilation/development times considerably. 

## Design
I propose to alter `moose.mk` to filter out predefined source files while creating the unity source files. This function will be reusable for the applications as well.

## Impact
This will enable more flexible linking capabilities and more control over the unity-nonunity options.

**Comment by loganharbour** [comment]
This already exists:

```
app_non_unity_dirs = %/src/contrib/foobar
```

**Comment by grmnptr** [comment]
What if we want to add specific source files, not just directories?
