### ISSUE TITLE
Switch to GitHub Action's stale bot

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#20475]
## Reason
ProBot Stale Bot is no more.

## Design
Following the instructions here: https://github.com/marketplace/actions/close-stale-issues, configure idaholab/moose to use this new implementation of stale issue closures.

## Impact
Label issues older than 30 days as Stale, and then close them 1 day later.

**Comment by permcody** [comment]
Make sure we only label PRs, not all issues. Also, I might suggest that we give more than 1 day to close after being stale. Maybe 3 so we don't lose things on weekends. That might be a good compromise for when this action runs on a Friday.
