### ISSUE TITLE
Need better error if C++17 support is missing

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#20483]
## Reason
```
error: expected ';' after expression
  std::scoped_lock lock(NodalNormalsPreprocessor::_nodal_normals_mutex);
```

Is simply too cryptic for Joe User. Conda dependencies frequently get locked up and do not update to the latest version when running `conda update --all`. Something is happening, and they think the update was successful, but they are not all the way up to date. 

## Design
A simple check of the `CXXFLAGS` would go a long way. If the flags still contain `--std=c++14` a clear error message sould be printed to the screen, prompting the user to conda env remove and conda create teh moose env again.

## Impact
Avoid user confusion. @cticenhour

**Comment by loganharbour** [comment]
Should use `CXX_STANDARD` instead

**Comment by dschwen** [comment]
What is `CXX_STANDARD` ?

**Comment by loganharbour** [comment]
Look at my edit
