### ISSUE TITLE
Add PenaltyLimitBC

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#20560]
## Reason
Sometimes preventing a variable value beyond a certain value is preferable, such as a soft spring that prevents the mesh from going below a specified value.

## Design
Conditionally apply the BC computed by `PenaltyDirichletBC` based on if the variable value is above or below the specified value, but zero otherwise.

## Impact
More flexible BCs.

**Comment by loganharbour** [comment]
Is this still a need?
