### ISSUE TITLE
Issues running with lots of (840) subapps

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#20657]
## Reason
I was looking into a model set up by our users with lots of (840) subapps. I would say that this setup is not non-typical for multiscale simulations. The calculation reveals a few pretty serious issues:

1. `MultiApp::createApp` is extremely slow. I used Instrument to tally the run times: 24.7% of the total cpu time was spent in this functions, 10.2% of total cpu time in this function was spent in `DependencyResolver` called `addActionTasks` and 8.5% of the total cpu time was in `checkLegacyParamsAction::act`. I do not think the cpu times in these two functions are reasonable. Almost 20% time in `createApp` is not tolerable comparing 80% of time for real calculations of a not-so-small model.

2. I do not have a way to turn off the excessive screen output even I removed the entire `Outputs` blocks of the subapps. It would be nice that during the Picard iteration, the subapps keep minimum screen outputs like whether or not it is converged and in what condition it is converged, etc.

## Design
The input is available up request. The input can produce the first issue. For the second one, maybe we can let `Executor` to print the info at each solve and completely disable the outputs from the multiapp with a control parameter in `MultiApp`. There could be other solutions.

Edit: please check my branch below referring this issue, that can produce the issue with MOOSE test.

## Impact
Better user experience on running cases with lots of subapps.

**Comment by permcody** [comment]
Thanks Yaqi - Tagging @fdkong or @roystgnr if either of them have time. Otherwise, I'll put this on my own Todo list.

**Comment by YaqiWang** [comment]
@roystgnr the input requires some large data files, and is checked in our internal repo. Let me ask if I can give you access to that repo.

**Comment by roystgnr** [comment]
Does it *require* them?  If this is a performance rather than an accuracy issue you might be able to replace mesh input files with just something like a high resolution generated cube mesh and still hit the same problems at high n_elems.

**Comment by zachmprince** [comment]
Maybe we can generalize the batch restore system that's in STM. This basically creates a single app per processor and reuses them with backup/restore.

**Comment by YaqiWang** [comment]
Good thing now is that I can reproduce all in moose test in my branch now. I basically copied contents in `addActionTasks` of our app into moose test for inserting new tasks. Somehow, it makes dependency resolver unhappy. =

**Comment by fdkong** [comment]
Which branch you created?

**Comment by GiudGiud** [comment]
The checkLegacyParams action could be removed/switched off if it's enough of a priority. It's here to help developers transition away from these legacy params without hard-to-debug compile errors. 

In the mean time, make sure you are specifying the smallest app possible when creating subapps, that will reduce the cost of this action. 

To remove screen output the most effectively, you need to create an Outputs/console block and set its parameters. 
Also make sure to include these:
```
  # Reduce base output
  print_linear_converged_reason = false
  print_linear_residuals = false
  print_nonlinear_converged_reason = false
```

**Comment by loganharbour** [comment]
Are you getting dependency resolution from _within_ `checkLegacyParamsAction::act`? If so - that confuses me.

That method still exists to help users transition away from legacy parameters without a contexless compiler error. However, I'm fine with removing it soon. The intention was to keep it around for a month or two after no longer allowing legacy params (merged one month ago in #19440).

**Comment by fdkong** [comment]
checkLegacyParamsAction::act is very useful for sure. We should profile that before we make a decision whether or not we remove that

**Comment by permcody** [comment]
@YaqiWang - you said you reproduced this with just MOOSE. Can you push your inputs up to a branch or open a draft PR so that a few of us can get access?

**Comment by YaqiWang** [comment]
> @YaqiWang - you said you reproduced this with just MOOSE. Can you push your inputs up to a branch or open a draft PR so that a few of us can get access?

The inputs in my branch can be found above link posted by Github. I think my fork is public. You have difficult on opening that link?

**Comment by zachmprince** [comment]
See #15663 for issue regarding generalizing batch mode.

**Comment by YaqiWang** [comment]
This issue has been addressed by the two referring PRs. We can open new issues for possibly future optimizations.
