### ISSUE TITLE
Using SSH URL for cloned MOOSE in Docker image

### ISSUE THREAD

**Issue by herter4171** [idaholab/moose#20688]
## Bug Description

The MOOSE clone in the official Docker image has its remote set to `git@github.com:idaholab/moose.git`.  This is a problem for external use, because it requires an SSH key in the container to check out public submodules, e.g. `large_media` to build docs in downstream codes.  If the SSH URL really needs to be used internally, it seems wise to at least change it to HTTPS for what gets pushed to Docker Hub.

## Steps to Reproduce

Pull the image with no modifications, and
```
git submodule --update --init large_media
```

## Impact

I'm not a user of this image, so there's no urgency.  Just looking out.

**Comment by loganharbour** [comment]
This is funny - I guess the solution here is probably to just change the origin remote to use https. Should be easy enough.

**Comment by permcody** [comment]
I would suggest we change it.
