### ISSUE TITLE
Return NaN instead of error when NaN sampled in LinearInterpolation 

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#20831]
## Reason
In `LinearInterpolation`, when the sample point is a NaN value, an error is thrown that says "Unreachable". A simulation should be able to continue when a NaN value is sampled.

## Design
This would return a NaN value `LinearInterpolation` when the sample point is NaN, allowing the simulation to cut the time step size and continue.

## Impact
This should not affect existing results.

**Comment by dschwen** [comment]
Why not throw an exception then? That would instr nan into the residual
vector and cut the trimestep if applicable, and would print an error
Where trimestep cutting is not an option (eg. Initial conditions)

**Comment by joshuahansel** [comment]
Ok thanks for the suggestion - I didn't know that there was this exception handling behavior. Here's what is currently in `LInearInterpolation`:
```
  mooseError("Unreachable!");
  throw std::out_of_range("Unreachable");
  return 0;
```
The `mooseError` definitely needs to go, and it seems `std::out_of_range()` doesn't get handled the way we want - it stops the simulation and gives
```
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```
However, changing it to `MooseException` does the trick. Is this the recommended exception?
