### ISSUE TITLE
Add extra javascript abilities for dynamic webpage

### ISSUE THREAD

**Issue by vanwdani** [idaholab/moose#20936]
## Reason
The usage of actions greatly eases the burden of input file creation, but knowing how to best create them starting out can be difficult.  Tutorials can help, but an interactive method that "helps create" an action block would be best in aiding beginners.  To make this possible, a more dynamic method for the currently static webpages is necessary.    

## Design
Currently MooseDown has the ability to further implement javascript after some changes are made.  Once this is active, a javascript can be used to trigger on a specific page and show some interactive content.

## Impact
As planned, this will initially be used within Bison, but the functionality will exist for all herd animals to expand interactive documentation/webpages on Moose based software.

**Comment by vanwdani** [comment]
@dschwen

**Comment by dschwen** [comment]
The design would be to add an `extra-js` parameter in `config.yml` (analogous to `extra-css`)

```
Renderer:
    type: MooseDocs.base.MaterializeRenderer
    extra-css:
        - doc/content/js/action_wizard.js
```

That script would check the currently loaded page name against a list/dictionary of page specific functions that would get run on their respective pages. 

Such a function could add an interactive form and hook up all the events to implement for example a step by step wizard to build an input file / snippet based on responses a user gives to a series of questions.
