### ISSUE TITLE
Remove vertex-based interpolation from finite volume.

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#20953]
## Reason
Because it is not used, was not used and I wouldn't recommend anybody using it. It is provably at least first order accurate but even for simple cases it fails to reach second order. Also, its computation time is comparable of the skewness-corrected face interpolation which manages to reach second order accuracy. 

## Design
Delete source and tests.

## Impact
Easier code management, less confusion about face interpolation.

**Comment by GiudGiud** [comment]
Would it never be used for any physics? This is beyond the scope of Navier Stokes, this is our general finite volume capabilities in NS
