### ISSUE TITLE
Perf graph of main app prints dots during subapp

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#20967]
## Bug Description
This can happen when the subapp (ns0 here), takes a long time

```
    Taking Step.ns0:  1 Nonlinear |R| = 3.931408e-01
..ns0:  2 Nonlinear |R| = 2.680830e-02
..ns0:  3 Nonlinear |R| = 1.457946e-03
..ns0:  4 Nonlinear |R| = 1.638429e-05
..ns0:  5 Nonlinear |R| = 4.571870e-09
ns0:  Solve Converged!
ns0: Finished Solving     
```

## Steps to Reproduce
run the msfr/steady inputs in the VTB
the fluid solve takes long enough to get prints from the neutronics main app

## Impact
ugly prints
less user appreciation of the software

**Comment by loganharbour** [comment]
Come on; at least use full sentences 😆

**Comment by GiudGiud** [comment]
a picture is worth a thousand words!

**Comment by GiudGiud** [comment]
i guess I m so used to discussions posts with a screenshot I thought i was pasting a picture. 
anyway

**Comment by YaqiWang** [comment]
Screen output like this makes the code look like not on a production level...
