### ISSUE TITLE
Initialize built-in types using =

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#2097]
There's a general consensus among the MOOSE developers that we prefer to initialize built-in types using "=" rather than parentheses.  That is, prefer

Real value = 0.0;

over

Real value(0.0);

We fully understand the reasons why one would use parentheses, we just don't like it.

If you fix this issue somewhere, reference this ticket.

**Comment by permcody** [comment]
This really isn't an issue. We've fixed MOOSE to conform to the guidlines so we'll close this as an issue.
