### ISSUE TITLE
MooseArray Memory Ownership

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2098]
There is a fairly large memory ownership issue in MooseArray.

If MooseArray is holding its own data and then gets ShallowCopied into.... it will leak.

If MooseArray is holding its own data and never gets release() called on it... it will leak.

We need to figure out how to keep track of memory ownership with MooseArray and create a destructor that works properly.

For this to work well we need to implement a swap() function that swaps the data in two MooseArrays... that way the ownership can be swapped as well...

**Comment by permcody** [comment]
We haven't hit any issues with MooseArray in a long time. If we do, we can start using SharedPointers to solve these issues.

**Comment by permcody** [comment]
Closed by #12949
