### ISSUE TITLE
Subapp checkpoint gets deleted for subapp in fixed point iteration

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#20998]
## Bug Description
@muelcm noticed this.
the checkpoint files get created then deleted. increasing num_files or switching to transient executioner resolves this issue

## Steps to Reproduce
test/restart/ inputs may be used, just need to change the executioner to steady

## Impact
user friendliness
workaround is easy but should be fixed

**Comment by lindsayad** [comment]
Is this with the checkpoint output enabled in the subapp input file?

**Comment by lindsayad** [comment]
Based on your other issue https://github.com/idaholab/moose/issues/18958 I'm not sure how much support we have for subapp-based checkpoint output, e.g. checkpoint data not governed by the main app

**Comment by GiudGiud** [comment]
Damn I had diagnosed this issue two years ago.

This is why we need to change our work processes. The insane context switching and the reliance on leaving issues behind is not sustainable

**Comment by pbehne** [comment]
@GiudGiud, do you think that #28062 closes this issue? If not, I need more details on steps to reproduce.

**Comment by GiudGiud** [comment]
It probably does but we need to check. Maybe just make a PR with a similar test with fixed point iterations? Make sure the FP iteration count is > num_files. It can be imposed using fixed_point_min_its

**Comment by pbehne** [comment]
Good point, will carry on.
