### ISSUE TITLE
`subdomainSetup()` with threads is not being called when expected/needed

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#21018]
## Bug Description
In [ComputeThermalExpansionEigenstrainBase](https://github.com/idaholab/moose/blob/next/modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C#L49-L79) I'm using `subdomainSetup()` to resize a vector to `_fe_problem.getMaxQps()` elements. In threaded execution this vector has size zero in some threads (leading to [this _Test threads_ failure](https://moosebuild.hpc.inl.gov/job/453600/)) .

## Steps to Reproduce
Run any input that uses an object based on `ComputeThermalExpansionEigenstrainBaseTempl<is_ad>` threaded. 

Note: we are _not_ testing the tensor mechanics module with threads on PRs! Why?

## Impact
This will prolong the current `next` breakage.

**Comment by loganharbour** [comment]
> This will prolong the current next breakage.

![image](https://user-images.githubusercontent.com/22062133/168173042-285486b0-63a4-4e1f-ab59-b63d2bc1dda5.png)

**Comment by dschwen** [comment]
So far I see that in threaded execution on a thread other than 0 `subdomainSetup()` is _not_ called for a `*_face` material before `computeProperties()` is called.

**Comment by dschwen** [comment]
Possibly requires subdomain restricted materials to reproduce.

**Comment by dschwen** [comment]
Backtrace excerpt from when the face material is called without prior call of `subdomainSetup()`

```
3: ComputeThermalExpansionEigenstrainBaseTempl<false>::computeProperties()
4: void MaterialData::reinit<std::vector<std::shared_ptr<MaterialBase>, std::allocator<std::shared_ptr<MaterialBase> > > >(std::vector<std::shared_ptr<MaterialBase>, std::allocator<std::shared_ptr<MaterialBase> > > const&)
5: FEProblemBase::reinitMaterialsFace(unsigned short, unsigned int, bool, std::deque<MaterialBase*, std::allocator<MaterialBase*> > const*)
6: ComputeElemAuxBcsThread<AuxKernelTempl<double> >::operator()(libMesh::StoredRange<MooseMesh::const_bnd_elem_iterator, BndElement const*> const&)
```

**Comment by dschwen** [comment]
What even is `ComputeElemAuxBcsThread` and why does it not inherit from `ThreadedElementLoop` and why does it thus not have a `subdomainChanged()` member function?

**Comment by dschwen** [comment]
Ok, I have a hotfix

```
diff --git a/framework/src/loops/ComputeElemAuxBcsThread.C b/framework/src/loops/ComputeElemAuxBcsThread.C
index f9b13a5496..fe6d3b4389 100644
--- a/framework/src/loops/ComputeElemAuxBcsThread.C
+++ b/framework/src/loops/ComputeElemAuxBcsThread.C
@@ -59,6 +59,7 @@ ComputeElemAuxBcsThread<AuxKernelType>::operator()(const ConstBndElemRange & ran
     const Elem * elem = belem->_elem;
     unsigned short int side = belem->_side;
     BoundaryID boundary_id = belem->_bnd_id;
+    SubdomainID last_did = Elem::invalid_subdomain_id;
 
     // need to update the boundary ID in assembly
     _problem.setCurrentBoundaryID(boundary_id, _tid);
@@ -74,6 +75,12 @@ ComputeElemAuxBcsThread<AuxKernelType>::operator()(const ConstBndElemRange & ran
 
       if (iter != boundary_kernels.end() && !(iter->second.empty()))
       {
+        auto did = elem->subdomain_id();
+        if (did != last_did)
+        {
+          _problem.subdomainSetup(did, _tid);
+          last_did = did;
+        }
         _problem.setCurrentSubdomainID(elem, _tid);
         _problem.prepare(elem, _tid);
         _problem.reinitElemFace(elem, side, boundary_id, _tid);
```

I'll make a PR
