### ISSUE TITLE
Automatically find `include/ADRealMonolithic.h` for installed apps

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#21122]
## Reason
We currently require the environment variable `MOOSE_ADFPARSER_JIT_INCLUDE` to be set for installed apps. We can most likely find it based on the current executable path.

## Design
Use `MooseUtils::` to find the current executable path and check if the include file can be found relative to it at `app-opt/../include/moose/ADRealMonolithic.h`.

## Impact
Easier setup for installed apps supporting JIT compilation.

**Comment by loganharbour** [comment]
Thank you kindly

**Comment by dschwen** [comment]
how will we test this?

**Comment by dschwen** [comment]
Ok, pushed. Seems to work locally. Here is the code the AD parsed material produces with an executable installed to `/tmp/prefix`:

```
#define _USE_MATH_DEFINES
#include <cmath>
#include "/tmp/prefix/bin/../include/moose/ADRealMonolithic.h"
extern "C" void f_3e56f132302afbb3_dbg(ADReal * ret, const ADReal *params, const double *immed, const double eps) {
ADReal s[3];
s[0] = immed[0];
s[1] = params[0];
s[2] = s[1];
s[1] += s[2];
s[0] += s[1];
*ret = s[0]; }
```
