### ISSUE TITLE
Inconsistent symlink following behavior in checkpoint/restart

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#21134]
## Reason
MOOSE's "paths relative to the input file" logic, follows symlinks. I.e. if I have two directories `a` and `b` and

```
a/input.i
b/input.i -> ../a/input.i
```

the file in `b` is a symlink back to `a`. And I want to run two different simulation in those dirs (let's say with CLI args to modify parameters)...
If I'm using restart, MOOSE looks for `a/input_out_cp/*`  in both cases. Even though the `b` simulation CheckpointIO writes to `b/input_out_cp/*...`

## Design
One part of the code seems to apply `realPath` to follow symlinks, while the other does not. Symlinking inputs to different directories to make it easy to keep multiple outputs seems like a very reasonable thing to do. And at the very least the behavior should be consistent.

I propose _not_ following the symlinks.

## Impact
Consistent restart behavior w.r.t. symlinks.

**Comment by dschwen** [comment]
Ok, I think it is time to push for `std::filesystem`, @permcody .

This issue can be solved easily by replacing `MooseUtils::realPath(path)` with `std::filesystem::absolute(path)`. That's the right behavior IMO. It produces a full path that keeps symlinks intact. The current behavior is that of `std::filesystem::canonical(path)`, which follows symlinks.

I'll go ahead and put up a PR to make this small change and see if/where our minimal compiler targets fail...

**Comment by dschwen** [comment]
We're at gcc7 and clang5, right?

**Comment by dschwen** [comment]
Ok, in the framework tests I only get two failing tests, and both cases are non matching expected errors, where teh error message actually improved.

```
Failed to get real path for
->
Unable to open file "/home/schwd/Programs/moose-std-filesytsem/test/tests/misc/realpath_exception/not_exist.i". Check to make sure that it exists and that you have read permission.
```

and 

```
Failed to get real path for missing_input_file.i
->
Unable to open file "/home/schwd/Programs/moose-std-filesytsem/test/tests/misc/check_error/missing_input_file.i". Check to make sure that it exists and that you have read permission.
```

**Comment by loganharbour** [comment]
Ah yeah.... I see you're talking to yourself here about the problem I discussed in #21137
