### ISSUE TITLE
Setup master app with no mesh object

### ISSUE THREAD

**Issue by mooseframework** [idaholab/moose#2117]
In solving transient neutronics problems, the master app solves for global parameters at one state point and therefore does not have a mesh, materials, or field variables. It would be great to allow users to create an input file to solve a problem like this without creating a dummy mesh.

**Comment by permcody** [comment]
We have no plans to remove the requirement for a mesh for a simulation in MOOSE. Nearly all other systems can be turned off with a little work, but not the Mesh (or a single Variable). MOOSE does however contain an option for building a minimal working simulation with nothing in it:

See `--minimal`

**Comment by permcody** [comment]
We have no plans to support running a simulation without a mesh. We do support a minimal running simulation though that has no objects in it. See `--minimal` on the command line.
