### ISSUE TITLE
CoupledVarThresholdElementSubdomainModifier has problem at executing at TIMESTEP_END

### ISSUE THREAD

**Issue by jain651** [idaholab/moose#21181]
## Bug Description
`CoupledVarThresholdElementSubdomainModifier` does not provide variable output in exodus/csv file when used with `execute_on = 'TIMESTEP_END'` with some cases.  

## Steps to Reproduce
In the test file (`moose/modules/tensor_mechanics/test/tests/element_subdomain_modifier/thermo_mech_w_ele_subdomain_modifier.i`) no output (csv/exodus) with '`execute_on = 'TIMESTEP_END'` while there is non-zero output with `execute_on = 'TIMESTEP_BEGIN'`

## Impact
No results means no point in running a simulation like this.

**Comment by maxnezdyur** [comment]
If you get a chance can you run one of the input files that fails but with the option `apply_initial_conditions=false` set up in CoupledVarThresholdElementSubdomainModifier. I think `_fe_problem.restoreSolutions();` in **ElementSubdomainModifier.C** causes a problem when it runs at the end of a time-step for certain cases.

**Comment by jain651** [comment]
Yes, it worked. 

Thanks
