### ISSUE TITLE
Test for checking whether an input mesh is distributed is broken, making non-distributed MGs fail in obscure ways

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#21185]
## Bug Description
We don't support distributed mesh generation in many mesh generators. We do support a lot of operations that are independent from how the mesh is stored.
While there is a lot of infrastructure already in MOOSE for parallel algorithms, they have not been implemented for all mesh generation operations yet. It's part of future work as this would be a very strong advantage to the framework

But the way we check for this is not right
```
  if (typeid(_input).name() == typeid(std::unique_ptr<DistributedMesh>).name())
    mooseError("GenerateAllSideSetsByNormals only works with ReplicatedMesh.");
```
this doesnt work in the constructor (where it is placed). It needs to be placed in the generate() routine. Maybe it used to work in the mesh modifier system. The team at ANL did it right in the reactor module, we need to import that way to our mesh generators. 

## Steps to Reproduce
Run with `--distributed-mesh` with MGs that dont support distributed meshes

## Impact
Came up here https://github.com/idaholab/moose/discussions/21182

**Comment by GiudGiud** [comment]
actually we want to use this
```
  _mesh->errorIfDistributedMesh("AddAllSideSetsByNormals");
```

**Comment by GiudGiud** [comment]
```
fvbcs/fv_neumannbc.fv_neumann ................................................................ FAILED (ERRMSG)
vectorpostprocessors/side_value_sampler.external ............................................. FAILED (ERRMSG)
mesh_modifiers/modifier_depend_order.order/depend_order ...................................... FAILED (ERRMSG)
fvbcs/fv_neumannbc.fvbcs_internal ............................................ FAILED (EXPECTED ERROR MISSING)
vectorpostprocessors/side_value_sampler.internal ............................................. FAILED (ERRMSG)
fvbcs/fv_neumannbc.fvbcs_disconnected_from_variable .......................... FAILED (EXPECTED ERROR MISSING)
meshgenerators/fancy_extruder_generator.extruder_then_parsed_gen_sideset ..................... FAILED (ERRMSG)
```
this shows we need some of these replicated-only MGs to work for distributed meshes

**Comment by loganharbour** [comment]
Why are the commits above not referenced in a PR?!

**Comment by GiudGiud** [comment]
fixed by https://github.com/idaholab/moose/pull/21173 then adjusted by https://github.com/idaholab/moose/pull/21362
