### ISSUE TITLE
Improve workshop for 2022 training

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#21192]
## Reason
The workshop should be brought up to date with new content.

## Design
- [x] Remove use of peacock
- [x] Fix broken macros
- [x] Improve modules description with pretty images

## Impact
Better workshop experience.

**Comment by loganharbour** [comment]
Issues came across during the training:

- Use `MeshGenerator` syntax in the `Mesh` section

**Comment by GiudGiud** [comment]
Closing as addressed by #21221 and #24549
