### ISSUE TITLE
Update shebang to specify python3

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#21235]
## Reason
A recent discussion revealed issues when relying on `python` as the interpreter: https://github.com/idaholab/moose/discussions/21218

I believe it is time to specify python3, instead of python.

## Design
Modify all shebang headers in python scripts within the moose/python subdirectory.

## Impact
Be strict with our shebang header for python scripts.

**Comment by cticenhour** [comment]
Closed via #22368. All python shebangs in the framework have been converted to python3.
