### ISSUE TITLE
Add option to turn off enthalpy material in NSFVAction

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#21248]
## Reason
In case somebody defines the enthalpy within a fluid property, they might get errors from the PBBLF that they are trying to register something that already exists. 

## Design
Add an additional parameter which can disable the enthalpy material within the action. 

## Impact
More flexibility with the fluid properties.

**Comment by GiudGiud** [comment]
Just as a follow up, we can set `dont_create_materials` in the Physics classes to not create the enthalpy material.
Same goes for other systems
