### ISSUE TITLE
Navier Stokes FV module should not use cp * T as enthalpy

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#21245]
## Reason

If cp varies with temperature, `cp * T` does not closely approximate the specific enthalpy `h`.
The correct definition is `h = integral_0^T cp(tau) dtau`.

## Design

1. Ensure that all fluid properties provide `h(p, T)`
2. Provide an `h` functor and potentially `\dot{h}` functors.
3. Use the enthalpy functors instead.

This applies to specific internal energy as well. 

## Impact

Some test regolding might be necessary. Mild rework of a decent number of Navier-Stokes objects.

**Comment by snschune** [comment]
@GiudGiud I haven't followed up on this. Is this resolved?

**Comment by GiudGiud** [comment]
I have one PR resolving half of the issue but I need to address the review

I have a good idea for resolving the other half, I m yet to get to it

**Comment by lindsayad** [comment]
In #25574 we changed the kernels to take h and h_dot. So ultimately it is up the functor provider to implement a correct form for h. I'm going to mark this as closed
