### ISSUE TITLE
Allow ParsedMaterial to use functions and (x,y,z,t)

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#21288]
## Reason
Sometimes material properties can depend on space, time, and functions.

## Design
This would allow the parsed expression for `ParsedMaterial` to use x, y, z, and t (using `_q_point[_qp]` and `_t`), as well as functions, which can be supplied via a new parameter `functions`, or better yet, do as `ParsedFunction` does and bind functions and PPs with `vars` and `vals`.

## Impact
More flexibility and new optional parameters.

**Comment by GiudGiud** [comment]
Closing as we can now use extra symbols x y z t in ParsedMaterials as of  #26723
