### ISSUE TITLE
Make Lapack/Blas calls more cross-platform

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2128]
In PolynomialFit and ColumnMajorMatrix we are calling Blas/Lapack calls directly... and we are assuming an "underscore" pattern (right now assuming a single underscore).

This is not portable - in particular it does not work on BG/Q.

We should be doing something better here...

**Comment by jwpeterson** [comment]
Just a slight update on this...

We are currently being pretty smart about calling Lapack in ColumnMajorMatrix.C: we only use our `FORTRAN_CALL` fallback if PETSc is either not available or is too old.  The only other use of LAPACK in the framework that I see is a `dgels` call in PolynomialFit.C.  That would be nice to similarly protect, but PETSc only provides an interface to `?gelss` which solves the same problem as `?gels` but [is slower](https://books.google.com/books?id=AZlvEnr9gCgC&pg=PA69&lpg=PA69&dq=dgels+vs.+dgelss&source=bl&ots=kxqTaupCaW&sig=l_Nonk-kspNb9e6MRy4cp4fUXyo&hl=en&sa=X&ved=0CDUQ6AEwA2oVChMI-qLy0O7-xwIVDDo-Ch23Rgkp#v=onepage&q=dgels%20vs.%20dgelss&f=false), uses a different algorithm (SVD), and has a different interface.  

For this reason, I still think we should try to beef up our `FORTRAN_CALL` using autoconf, unfortunately I don't see any off-the-shelf autoconf tests available for doing this.

**Comment by permcody** [comment]
We have a this implemented here:
https://github.com/idaholab/moose/blob/devel/framework/include/base/Moose.h#L53-L57
