### ISSUE TITLE
Make various MeshModifiers work with ParallelMesh

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#2129]
The following MeshModifiers input files don't work in parallel with ParallelMesh enabled:

```
tests/mesh_modifiers/add_all_side_sets/less_simple.i
tests/mesh_modifiers/add_all_side_sets/simple.i
tests/mesh_modifiers/add_extra_nodeset/extra_nodeset_test.i
tests/mesh_modifiers/add_side_sets/cylinder_normals.i
tests/mesh_modifiers/add_side_sets/cylinder_normals_fixed.i
tests/mesh_modifiers/add_side_sets/cylinder_points.i
```

A typical cause for the error is calling an invalid function, such as n_sides(), on a RemoteElem, which looks like this:

```
[./include/libmesh/remote_elem.h, line 115, compiled Jul 30 2013 at 14:06:23
```

These could probably be fixed up, for example, flooding has to stop if it reaches a RemoteElem:

```
  if (elem == NULL || (_visited[side_id](0]).find(elem) != _visited[side_id].end()) || elem->is_remote())
    return;
```

Then there also needs to be some kind of communication step to sync up the MooseMesh::boundary_map object that is used by a lot of the MeshModifiers.

**Comment by permcody** [comment]
Most of the MeshModifiers work with ~~ParallelMesh~~ DistributedMesh now, the rest have been properly restricted. I'm going to close this blanket issue. We'll open new specific issues as needed.
