### ISSUE TITLE
Easier access of derivative information of hardening functions

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#21294]
## Reason

In the tensor_mechanics module, we need to provide hardening functions for an inelastic update. Currently, this is mostly done using `Function`, and the derivative of the hardening function w.r.t. the internal variable is obtained by abusing the usage of `Function::timeDerivative`, which is already a workaround which only works with single variable dependency. What if the hardening function depends on other material properties and variables? 

## Design

Either AD (which we already have but too slow) or 
I propose creating a compute = false version of `DerivativeParsedMaterial`.

## Impact

This will give us more flexibility in defining hardening functions (or really any coupled materials that are iterative in nature), plus we can get exact derivative information so that it will be possible to compute a perfect algorithmic Jacobian.

**Comment by dschwen** [comment]
Yeah, we need a compute false version of derivative parsed material anyways in #19981, and in fact we there get it by simply adding 

```
template <bool is_ad>
void
DerivativeParsedMaterialTempl<is_ad>::resetQpProperties()
{
}
```

**Comment by hugary1995** [comment]
Yeah that should do it. Neat.

**Comment by hugary1995** [comment]
I can't think of a way to hand-calculate the jacobian for a plasticity update with a nonlinear hardening function using the `timeDerivtive` hack, because we would need second order "time derivative" of the hardening function.

I can wait for #19981, or if you think it'll be a while until that's ready, I can create a separate PR that enables `compute=false` DerivativeParsedMaterial.

**Comment by dschwen** [comment]
> we would need second order "time derivative" of the hardening function.

How can that be? I would've thunk first derivative is always enough for a Jacobian. We can evaluate functions with `ADReal`s now, too.

**Comment by hugary1995** [comment]
To get a _perfect_ jacobian, we need to know the derivative of the return mapping jacobian w.r.t. the interval variable, if the hardening function is nonlinear.
