### ISSUE TITLE
Journal file conversion to exodus file

### ISSUE THREAD

**Issue by Vandenbg** [idaholab/moose#21305]
I am unable to find information about conversion between journal files and exodus files in the link below or other wise. Could someone please point me to the process somewhere?

I am not sure if you are referring to the journal file conversion to Exodus. But, in case you haven't come across it: https://mooseframework.inl.gov/modules/contact/BerkovichIndenterNodeFace.html
_Originally posted by @recuero in https://github.com/idaholab/moose/discussions/17387#discussioncomment-504893_

**Comment by recuero** [comment]
Please use MOOSE's discussion forum for this kind of inquiries: https://github.com/idaholab/moose/discussions

Journal files define a mesh using a meshing software (i.e. Cubit: https://cubit.sandia.gov/). That's the process needed to obtain an Exodus file.
