### ISSUE TITLE
Enable penalty-based mortar constraints 

### ISSUE THREAD

**Issue by recuero** [idaholab/moose#21329]
## Reason
For one thing, it's relatively low-hanging fruit. Adding penalty-based mortar constraints of already-existing physics would allow reducing the system size (no LMs) and the potential avoidance of numerical issues such as the saddle point structure of the system of equations (contact). Further, penalty constraints (e.g. equal value) may be useful when wanting to remove rigid body modes from quasistatic simulations without committing to an unphysical, hard constraint. On the other hand, penalty enforcement will have a lower quality than its LM-enforced counterpart and it introduces additional parameters that may become a nuisance to the user.

## Design
I'd think new penalty-based mortar objects will be created. That may be better than mixing the use/no use of LMs. Other than that, the existing framework appears general to be leveraged for this purpose.

## Impact
One more flavor of the mortar formulation available to the user. With its pros and cons.

To do:

- [x] Equal value "constraint"
- [ ] Normal contact "constraint"
- [ ] Frictional contact "constraint"

Maybe others, but these are the ones that make immediate sense to me.

**Comment by recuero** [comment]
For penalty normal and frictional contact, @lindsayad and I would like to investigate, design-wise, the best path forward to compute contact forces/pressures that can then be applied as generalized forces. Ultimately, we would want to use this penalty contributions within an augmented Lagrange loop, in a way similar to that employed by node-to-segment contact.

**Comment by lindsayad** [comment]
IIRC, one design idea that @recuero had was to make the penalty force an aux variable such that as much of the existing LM-based mortar mechanical contact classes could be re-used. I'll consider this now that I'm taking this up

**Comment by recuero** [comment]
Yes. Those Lagrange auxiliary variables could potentially be used to accumulate normal and tangential pressure values from an Augmented Lagrange loop too. You brought up the difficulty (with current design) of keeping derivative information if auxiliary variables were to be used to impose the generalized forces resulting from the mechanical contact constraints.
