### ISSUE TITLE
Nearest Node Transfer Seg Fault

### ISSUE THREAD

**Issue by folkthom** [idaholab/moose#21360]
## Bug Description
The nearest node transfer from a Tensor Mechanics sub-app to the main-app seg faults when the number of processors on the sub-app is forced to one.

## Steps to Reproduce
The input file is not open source at this time. However, the tensor mechanics sub-app solves for the radial displacements of a bottom core support plate given an inlet temperature. The radial displacements are transferred to the Griffin main-app to be applied to the 3-D mesh of the active core region.

## Impact
The interpolation transfer has been applied to substitute the nearest node transfer.

**Comment by GiudGiud** [comment]
I m thinking this is related to https://github.com/idaholab/moose/issues/12523

let's grow the bounding box like crazy and see if that fixes it

**Comment by GiudGiud** [comment]
Closed by #21490
