### ISSUE TITLE
FVFunctorDirichletBC as an equivalent to MatchedValueBC in FEM

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#21374]
## Reason

Coupling functors into boundary conditions is required if you want to apply a Dirichlet BC
that is transferred from a different app. The use case I have requires this capability for conjugate
heat transfer.

## Design

`FVDirichletBC` that takes a functor as parameter and results its value in `boundaryValue`.

## Impact

New capability.

**Comment by GiudGiud** [comment]
Closed by #21377
