### ISSUE TITLE
Incorrect stress and strain output in the shell elements

### ISSUE THREAD

**Issue by neuphris** [idaholab/moose#21384]
## Bug Description
The shell element gives us incorrect strain result due to an error in formulae for transforming the strain from the convected coordinate system to the cartesian coordinate system. Also, the rotation matrix is compute only once and old matrix is not stored due to which the rotation matrix of the last element is used to transform the stress/strain values which gives incorrect result when the mesh is not uniform.

## Steps to Reproduce
Several test cases were created to demonstrate the lack of accuracy in the existing code.

## Impact
This will give correct distribution of stress and strain in shell element.

**Comment by Edward-Eth** [comment]
Has the fix for this been pushed into master yet?

**Comment by bwspenc** [comment]
This was resolved by #28473
