### ISSUE TITLE
When creating a smoothed porosity, create a new functor with unique name

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#21455]
## Reason
Other physics/kernels should use the unsmoothed porosity. If it uses the smoothed porosity, the results are wrong

## Design
Do not replace the porosity functor with the smoothed version. Create a new unique smoothed porosity functor instead

## Impact
Better user experience and multiphysics results

**Comment by lindsayad** [comment]
@GiudGiud can't this be closed?

**Comment by GiudGiud** [comment]
Yeah it can

**Comment by GiudGiud** [comment]
closed by #21491
