### ISSUE TITLE
Lead and LeadBismuth function fluid properties 

### ISSUE THREAD

**Issue by CalfSteven** [idaholab/moose#21531]
## Reason
For future use in fast lead reactor simulation, sought by Argonne National Laboratory.

## Design
High-density metallic coolants, with low neutron absorption and very high thermal conductivity.  The end goal is to add this to the fluid properties library. 

## Impact
Will add more options in the fluid properties repertoire, allowing for the simulation of the coolants for more reactors.

**Comment by GiudGiud** [comment]
Closing as added by #21503
