### ISSUE TITLE
Cyclic dependency error when there are block restricted discrete materials

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#21537]
## Bug Description

Suppose there are two materials defined on two different blocks, and each of them retrieves a discrete material defined on their respective block. Then there is a cyclic dependency I don't quite understand yet.

## Steps to Reproduce

Here is the minimal input file to reproduce this:
```python
# The left subdomain has block id 0
# The right subdomain has block id 1
#
# newton_0 is a material defined on block 0
# newton_1 is a material defined on block 1
#
# However, the cyclic dependency error reports
#   Cyclic dependency detected in object ordering:
#   newton_0 -> newton_1
#   newton_1 -> newton_0

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 10
    ny = 1
  []
  [right]
    input = gen
    type = SubdomainBoundingBoxGenerator
    bottom_left = '0.5 0 0'
    top_right = '1 1 0'
    block_id = 1
  []
[]

[Problem]
  solve = false
[]

[Materials]
  [recompute_props_0]
    type = RecomputeMaterial
    block = 0
    f_name = 'f'
    f_prime_name = 'f_prime'
    p_name = 'p'
    compute = false # make this material "discrete"
  []
  [newton_0]
    type = NewtonMaterial
    block = 0
    f_name = 'f'
    f_prime_name = 'f_prime'
    p_name = 'p'
    material = 'recompute_props_0'
  []
  [recompute_props_1]
    type = RecomputeMaterial
    block = 1
    f_name = 'f'
    f_prime_name = 'f_prime'
    p_name = 'p'
    compute = false # make this material "discrete"
  []
  [newton_1]
    type = NewtonMaterial
    block = 1
    f_name = 'f'
    f_prime_name = 'f_prime'
    p_name = 'p'
    material = 'recompute_props_1'
  []
[]

[Executioner]
  type = Steady
[]
```

## Impact

False positive (?) cyclic dependency error.

**Comment by hugary1995** [comment]
@lindsayad Is it obvious to you why this would be happening? I feel like this is caused by the way I am inserting material dependencies from discrete materials (in a non-block-restricted manner), but I need to dig into the code to figure out.

**Comment by lindsayad** [comment]
I really don't like those parameter names. I have no clue what `p_name` means and `f_name` is only saved because of `f_prime_name`. Gotta save users typing all those characters! :frowning_face: 

This is the code:
```c++
  std::multimap<std::string, T> suppliers_map;
  for (auto & v : vector)
  {
    for (const auto & supplied_item : v->getSuppliedItems())
    {
      suppliers_map.emplace(supplied_item, v);
      graph.addNode(v);
    }
  }

  // build the dependency graph
  for (auto & v : vector)
  {
    for (const auto & requested_item : v->getRequestedItems())
    {
      const auto & [begin_it, end_it] = suppliers_map.equal_range(requested_item);
      if (begin_it == end_it)
        graph.addNode(v);
      else
        for (const auto & [supplier_name, supplier_object] : as_range(begin_it, end_it))
        {
          libmesh_ignore(supplier_name);
          if (supplier_object == v)
            // We allow an object to have a circular dependency within itself; e.g. we choose to
            // trust a developer knows what they are doing within a single object
            continue;
          graph.addEdge(supplier_object, v);
        }
    }
```
We allow circular dependency within a single material (considering here that the discrete material is "a part of" the non-discrete-material) specifically for your guys discrete materials use case. E.g.

A supplies: foo, bar
A requires: foo, bar

But you have:

A supplies: foo, bar
A requires: foo, bar
B supplies: foo, bar
B requires: foo, bar

So with our logic above you get an edge between A and B, *and* you get an edge between B and A

**Comment by lindsayad** [comment]
That code is in `DependencyResolverInterface.h` by the way if you want to take a look wholistically

**Comment by lindsayad** [comment]
There's not really anything we could about this in `DependencyResolverInterface`, but in the materials system you could perhaps do dependency resolution on a per-block basis

**Comment by hugary1995** [comment]
I had thought that we were already sorting (and checking cyclic dependency) on a per-block basis:
```cpp
template <typename T>
void
MooseObjectWarehouseBase<T>::sort(THREAD_ID tid /* = 0*/)
{
  checkThreadID(tid);

  for (auto & object_pair : _all_block_objects[tid])
    sortHelper(object_pair.second);

  for (auto & object_pair : _all_boundary_objects[tid])
    sortHelper(object_pair.second);

  sortHelper(_all_objects[tid]);

  // The active lists now must be update to reflect the order changes
  updateActive(tid);
}
```
for example
```cpp
  // All block restricted objects (THREAD_ID on outer vector)
  std::vector<std::map<SubdomainID, std::vector<std::shared_ptr<T>>>> _all_block_objects;
```

**Comment by hugary1995** [comment]
Ehhh, I say that without testing. Let me get a backtrace first...

**Comment by hugary1995** [comment]
Yeah, so the error comes from line 574 in MooseObjectWarehouseBase.h:
```cpp
sortHelper(_all_objects[tid]);
```
which is sorting _all_ objects, regardless whether the object is block-restricted.

I don't quite understand the logic behind this -- why would we want to resolve the dependencies of block-restricted objects together with non-block-restricted objects in the first place? I must be missing something.

**Comment by hugary1995** [comment]
What we are doing right now is probably too restrictive.

On the other hand, completely ignoring cyclic dependency when sorting `_all_objects` is probably too permissive.

**Comment by lindsayad** [comment]
You could try making `sort` virtual and then override in `MaterialsWarehouse` and don't sort `_all_objects`. I don't immediately see a place in the code where we rely on all the materials being sorted, but there could be other objects in which `_all_objects` being sorted is important

**Comment by hugary1995** [comment]
That's what I did, and I am testing now. If regression tests look reasonable I'll create a PR.

Instead of not sorting `_all_objects` at all, I added an option to tolerate cyclic dependency in the `DependencyResolver`.
