### ISSUE TITLE
Some improvements on XMLDiff for testing

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#21532]
## Reason
We sometimes ask the application to generate data in XML file format. The file may contain nodes/attributes in vector of numbers or words. But it seems currently the differ is expecting all to be numbers. Certain attributes can be skipped by the differ with `skip_attributes` option but no similar thing for nodes is available.

## Design
I am not familiar with the differ but hope my suggestions are reasonable.

I'd like to have

1. a new option `skip_nodes`.
2. a new option `text_attributes`, with which certain attributes are considered as a vector of words.
3. a new option `text_nodes`, with which certain nodes are considered as a vector of words.

I have a sample xml file like the following:

```
<ISOXML>
  <Multigroup_Cross_Section_Libraries Name="Created" NGroup="2">
    <Multigroup_Cross_Section_Library ID="1" Ver="1.0" Generator="INL" TimeCreated="Wed Feb 23 17:11:57 2022">
      <Tabulation>burnup</Tabulation>
      <burnup>0</burnup>
      <ReferenceGridIndex>1</ReferenceGridIndex>
      <AllReactions>Total Removal Transport Scattering nuFission FissionSpectrum</AllReactions>
      <TablewiseReactions>FissionSpectrum nuFission Scattering Transport Removal Total</TablewiseReactions>
      <LibrarywiseReactions/>
      <Table gridIndex="1">
        <Isotope Name="pseudo"/>
        <Tablewise>
          <Total>0.53618 1.3583</Total>
          <Removal>0.0268955 0.110673</Removal>
          <Transport>0.296732 1.0201</Transport>
          <Scattering profile="1">
            <Profile>
              1 2
              1 2
            </Profile>
            <Value>
                0.509284 0.00193035
                0.0169934 1.24763
            </Value>
          </Scattering>
          <nuFission>0.00745739 0.151201</nuFission>
          <FissionSpectrum>1 0</FissionSpectrum>
        </Tablewise>
      </Table>
    </Multigroup_Cross_Section_Library>
  </Multigroup_Cross_Section_Libraries>
</ISOXML>
```

I'd like to have
```
skip_attributes = 'Generator TimeCreated'
text_nodes = 'Tabulation AllReactions TablewiseReactions LibrarywiseReactions'
text_attributes = 'Name'
```
for this file.

## Impact
A new capability to make xml differ more flexible.

**Comment by loganharbour** [comment]
Might be a good idea here to combine JSON and XML diffing using the python `deepdiff` package. Would make for a very versatile and general diffing capability that is analogous to the file type, as long as we can convert the data to a dict.

**Comment by milljm** [comment]
I wasn't even thinking about using per-existing python packages. That's cool. I might not be the best person to work on this...

**Comment by GiudGiud** [comment]
@socratesgorilla would you have time to work on this?

**Comment by socratesgorilla** [comment]
Should yeah
