### ISSUE TITLE
Possibly missing a material reinit with Mortar + ScalarKernel

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#21689]
## Bug Description

I am attempting to use the Mortar constraint together with the homogenization system (essentially a scalar equation enforcing the domain integral of a variable gradient equal to a target value) in tensor_mechanics. 

I haven't been able to obtain the correct result so far, so I reproduced the issue using a very simple MOOSE-only example.
- The residual is incorrect: the result is different from that using a conventional PBC (hence without the lower D blocks) instead of the Mortar-based equal value constraint.
- The Jacobian is incorrect: with a direct solver, it doesn't converge in one nonlinear iteration.
- The result appears to be nondeterministic.

An interesting observation: if I assign the same material property over the entire domain (diffusivity = 1), then the Mortar result is correct. However if I assign different material properties on different blocks (diffusivity = 1 and 10), then the aforementioned issue occurs. This leads me to think that we are probably missing a material reinit somewhere, which only happens when there are lower D blocks in the mesh.

## Steps to Reproduce

I've set up a branch that contains all the test objects necessary to reproduce this issue, together with a working example (using PBC) and a non-working example (using Mortar penalty PBC).
https://github.com/hugary1995/moose/tree/mortar_homogenization_debug

## Impact

Getting this to work will be generally helpful, as we want to do homogenization problems on non-conforming meshes.

**Comment by lindsayad** [comment]
> * The Jacobian is incorrect: with a direct solver, it doesn't converge in one nonlinear iteration.

This doesn't mean anything. If a system is nonlinear, then there is no guarantee that the nonlinear solve will converge in one nonlinear iteration

**Comment by hugary1995** [comment]
You are right, but the system is linear. I forgot to mention.

**Comment by lindsayad** [comment]
Even then you may take multiple iterations if the nonlinear solve tolerance is tighter than the linear one

**Comment by lindsayad** [comment]
can we close this?

**Comment by hugary1995** [comment]
Yes!
