### ISSUE TITLE
Undetected missing gold file?

### ISSUE THREAD

**Issue by helen-brooks** [idaholab/moose#21710]
## Bug Description
There is a test which fails to pass in the heat conduction module due to a missing gold file.  I believe this goes undetected in CI because going of the official docker image (namely `idaholab/moose:8cce533ba2728d029ce57e5c27031641e12345b1 ` -  I realise this is already a bit out of date.)
I get a "skipped" message on the particular failing test:
```
root@a7e5e33d16bf:/opt/moose/modules/heat_conduction# ./run_tests --re gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar
test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar [Minimum AD size 100 needed, but MOOSE is c...] SKIP
```
Whereas running from my docker image:
```
helen@helen-Latitude-7400:~$ docker run -it helenbrooks/moose-ubuntu:8cce533ba2728d029ce57e5c27031641e12345b1
root@cd2f1230b0ed:/# cd /home/moose/
root@cd2f1230b0ed:/home/moose# cd modules/
root@cd2f1230b0ed:/home/moose/modules# ./run_tests --re gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar
```
produces the error
```
heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar: Finished Executing                                                                       [  9.43 s] [   69 MB]
heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar: File Not Found: /home/moose/modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gold/gap_heat_transfer_3D_mortar_out_NodalTemperature_0001.csv
heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar: ################################################################################
heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar: Tester failed, reason: MISSING GOLD FILE
heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar: 
heat_conduction/test:gap_heat_transfer_mortar.gap_heat_transfer_3d_mortar [FINI...] FAILED (MISSING GOLD FILE)
```

## Steps to Reproduce
MOOSE was built according to this Dockerfile:
https://github.com/aurora-multiphysics/aurora/blob/update_moose_dockerfile/docker/moose-ubuntu/Dockerfile

with the command 
docker build  -t helenbrooks/moose-ubuntu --build-arg moose_git_sha=8cce533ba2728d029ce57e5c27031641e12345b1 .

I've pushed the image to dockerhub, so you should be able to reproduce exactly. Command to pull is
```
docker pull helenbrooks/moose-ubuntu:8cce533ba2728d029ce57e5c27031641e12345b1
```

I reckon the key difference is the MOOSE configuration, 
```
RUN cd /home/moose/ && \
    ./configure --with-derivative-size=200 --with-ad-indexing-type=global
```
but I haven't tested this assumption.

## Impact
It's a bit annoying because I'm trying to rebuild and update my CI setup, but I can change the build configuration easily, I don't *need* to use that specific configuration (it was honestly just copy-pasted from a different script). But I figured you should know about the missing gold file.

**Comment by recuero** [comment]
Thanks for bringing this up.
