### ISSUE TITLE
Add ability to print a message to screen from the input file

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#21736]
## Reason
In some of my VTB cases, I would like to print to screen a few messages like:
- check out this more efficient way of doing this on another branch if you need more performance
- careful this model isnt validated for this reactor

## Design
Just a user object most likely

## Impact
Better usability

**Comment by MengnanLi91** [comment]
@GiudGiud Could you assign this one to me?

**Comment by MengnanLi91** [comment]
@GiudGiud Is this what you are looking for?
<img width="238" alt="Screenshot 2023-03-13 at 3 20 10 PM" src="https://user-images.githubusercontent.com/118846840/224834978-7a26fb21-856d-4eb0-8b07-bf114b51fe58.png">
Output:
<img width="341" alt="Screenshot 2023-03-13 at 3 18 13 PM" src="https://user-images.githubusercontent.com/118846840/224834719-84a68667-7b2c-441a-b0fa-a03ef60df3df.png">

**Comment by GiudGiud** [comment]
I like it!
