### ISSUE TITLE
Capability to renormalize variable sets that comprise a vector

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#21801]
## Reason
Micromagnetic problems require a constant renormalization of the magnetization director vector field. While the constitutive equations should keep the vector normalized, numerical time integration errors can lead to deviations. This is detrimental to the problem convergence.

## Design
Renormalize the solution vector at the end of each timestep. This could be done in a UserObject.

## Impact
Added capability

**Comment by mangerij** [comment]
Hi Daniel, is it possible that this can be merged to the framework? 

Olle and I are quite happy with this and I pushed a Ferret test (test/magnets/ringdown) that uses this and now I am getting fails because of course the CIVET does not use your branch.
