### ISSUE TITLE
SideSetsBetweenSubdomainsGenerator should prepare_for_use()

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#21861]
## Bug Description

I am creating a mesh and need to use `SideSetsBetweenSubdomainsGenerator`. Unfortunately, as pointed out by @miaoyinb, many of the generators I am using beforehand do not prepare the mesh for use.

The best way to resolve this (suggested by @miaoyinb) would be to add `mesh->prepare_for_use();` at the beginning of `SideSetsBetweenSubdomainsGenerator::generate()`

## Steps to Reproduce

An input with `FancyExtruderGenerator` followed by `SideSetsBetweenSubdomainsGenerator` should be able to reproduce this behavior.

## Impact

I can't assign the sidesets I need.

**Comment by miaoyinb** [comment]
I will fix this.
