### ISSUE TITLE
Add harmonic interpolation support for FV functions

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#21923]
## Reason
Harmonic interpolation for diffusion coefficients is a popular approach in the literature, considering that it ensures flux continuity on orthogonal grids. In practice, it yields better results for nonorthogonal grids as well. 

## Design
Add new interpolation options/methods to the utility classes and use those in FVDiffusion and similar framework-based classes.

## Impact
Will result in more accurate solutions for problems where the material properties are discontinuous in space.

**Comment by grmnptr** [comment]
I haven't seen anything about that. If I understand this correctly for the diffusion problem, this is something which preserves the continuity of diffusive flux on the face on 1D/orthogonal grids. This assumes that a central difference scheme is used on the face to compute the face-normal gradient. On non-orthogonal grids this is not true anymore, but until the nonorthogonality is at a reasonable level, this still yields better results due to the larger contribution from the orthogonal central difference scheme. I don't think we have these options for advection schemes, but we might be able to derive something similar along the same lines.

**Comment by GiudGiud** [comment]
Closed by #21928
