### ISSUE TITLE
Parse triple-indexed objects

### ISSUE THREAD

**Issue by miaoyinb** [idaholab/moose#21930]
## Reason
Triple indexed arrays have been found necessary to keep a clear input syntax for some classes such as #21854. 

## Design
First it will require update in `libMesh` to enable 3D vector as `print_helper()`'s argument. https://github.com/libMesh/libmesh/issues/3380

Then, `Parser.C` needs to be updated to cover triple-indexed arrays. (similar to https://github.com/idaholab/moose/pull/6459)

## Impact
Clearer input syntax.

**Comment by YaqiWang** [comment]
In extreme cases, I suggest to have your own parsing function inside the object. The parameter can be in type of a plain string.

**Comment by miaoyinb** [comment]
> In extreme cases, I suggest to have your own parsing function inside the object. The parameter can be in type of a plain string.

A triple indexed array is still not that complex. But I agree that your suggestion could be a good approach for future extreme scenarios.
