### ISSUE TITLE
Create new Component of some types fails under r7_moose/raven

### ISSUE THREAD

**Issue by mooseframework** [idaholab/moose#2193]
This came up because of trying to create 5161092ae3baa24764756d4eb96d13087bf6e47a_moose model from scratch using Peacock.

Steps to reproduce:

1) Run Peacock under 5161092ae3baa24764756d4eb96d13087bf6e47a_moose or raven without specifying an input file.
2) Create new item under "Component"
3) Set component type (Types observed to not fail are: FlowJunction, Inlet, Outlet, HeatStructure, PointKinetics, Reactor, SolidWall, SpecifiedDensityAndVelocityInlet, TDM, Turbine)

Crash on console:

Traceback (most recent call last):
  File "/Users/bobk/projects/trunk/peacock/gui/ParamTable.py", line 568, in item_clicked
    options_item = OptionsWidget(table_widget,row,param['), self.isVectorType(param['cpp_type']('options'].split%28'%29))
AttributeError: 'NoneType' object has no attribute 'split'

Also the rest of the parameter items don't get  populated.

I had good results by doing this in my local copy of ParamTable.py:

if param[ options_item = OptionsWidget(table_widget,row,param['options']('options']:).split(' '), self.isVectorType(param[  options_item = OptionsWidget(table_widget,row,'', self.isVectorType(param['cpp_type']('cpp_type']))
else:
)))

**Comment by permcody** [comment]
Old peacock is being deprecated. This issue isn't relevant.
