### ISSUE TITLE
Modify GrainTracker to make the minimum variable value accessible from the input file

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#21938]
## Reason
In grain tracker right now, the code resets variables to 0 when a grain is mapped from it to another variable. However, for the new nonlinear preconditioning approach I am adding for grain tracker, the minimum variable value needs to be set by the user in the input file. It could be -5, -6, etc. depending on how the problem is set up.

## Design
Current the minimum value is set to 0.0. It needs to be changes to be set by an option parameter. The default value should be set to 0.0, to recover the old behavior.

## Impact
This will add the capability to change the minimum value, but won't change any existing behavior, since the default will be set to 0.0.

**Comment by tonkmr** [comment]
@permcody heads up.

**Comment by tonkmr** [comment]
@permcody I am finally getting back to this, now that it is summer again. This capability is still very much needed in order for GrainTracker to work with the nonlinear preconditioning value.

**Comment by permcody** [comment]
Do you have anyone that can help you make changes? Just asking because I don't have much time, but I can definitely advise/mentor. I'll take a look though it should be very simple

**Comment by tonkmr** [comment]
I'll try to make the changes as part of my overall pull request for the new approach. I'll let you know if I have any questions. When I submit the PR, I'll tag you on it.
