### ISSUE TITLE
Diffing tests on 9 ranks

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#21968]
## Bug Description
Two tests fail only when using 9 MPI ranks (while passing with any other number of ranks up to 16).

```
[0.530s]     DIFF postprocessors/element_extreme_value.proxy_elemental_extreme FAILED (CSVDIFF)
[0.510s]     DIFF postprocessors/nodal_extreme_value.nodal_extreme_proxy FAILED (CSVDIFF)
```

## Steps to Reproduce
Enable the (extremely long) "Parallel sweep" test. Or check https://civet.inl.gov/job/1157523/

## Impact
Eliminate a potential rare MPI bug.

**Comment by recuero** [comment]
Should we have the ability to do parallel sweeps on modules too? Not necessarily suggesting that it should be added as a strong SQA requirement, but it may help us catch this type of pesky behavior, which may catastrophically manifest itself in practical applications with larger problems.
