### ISSUE TITLE
BlockDeletionGenerator produces segmentation fault with mixed-dimensional meshes

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#21983]
## Bug Description

BlockDeletionGenerator segfaults with mixed-dimensional meshes

## Steps to Reproduce

```
[Mesh]
  [twoquad]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 2
    xmax = 2
  []
  [subdomain]
    type = SubdomainBoundingBoxGenerator
    input = twoquad
    block_id = 1
    bottom_left = '1 0 0'
    top_right = '2 1 0'
  []
  [sideset]
    type = SideSetsBetweenSubdomainsGenerator
    input = subdomain
    primary_block = 0
    paired_block = 1
    new_boundary = bar
  []
  [edge_elem]
    type = LowerDBlockFromSidesetGenerator
    input = sideset
    sidesets = bar
    new_block_id = 2
  []
  [delete]
    type = BlockDeletionGenerator
    input = edge_elem
    block = 0
  []
[]
```

## Impact

I have a work-around, but would still like this bug to be fixed.  **I do not currently have time to fix this myself**

**Comment by WilkAndy** [comment]
@GiudGiud - maybe you'd like to work on this bug?

**Comment by GiudGiud** [comment]
Interesting I think we used the BlockDeletionGenerator in that exact same context to make a sidesetextrusiongenerator (from a lower D, not merged yet).

I'd love to fix this for you. Our schedules are pretty full until the end of the FY though so I'm just going to tag @permcody so he can schedule that

**Comment by WilkAndy** [comment]
Thank you @GiudGiud

**Comment by socratesgorilla** [comment]
I can take a stab at this @GiudGiud if you want to assign me

**Comment by socratesgorilla** [comment]
@WilkAndy Out of curiousity, what was your workaround to this problem?

**Comment by WilkAndy** [comment]
@socratesgorilla , the workaround was to use python to instruct my mesher to not to create the blocks that i wanted to delete.  Ie, not a MOOSE workaround.   Thanks for addressing this bug @socratesgorilla
