### ISSUE TITLE
VolumetricFlowRate fails on internal boundaries that are cut by domain boundaries

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#21991]
## Bug Description
the a coefficients are local to elements, but they are being retrieved from the other side. The side that owns the face info doesnt own the a coefficient it seems. 

this is the backtrace. Sorry for screenshot, linux wasnt letting me paste from my xterm

![image](https://user-images.githubusercontent.com/25037151/188021354-65cb35c1-861b-4ea8-bf8f-0717d8e1e349.png)

## Steps to Reproduce
MSFR VTB input with 6 processes. I couldnt get it on my mac but on the linux box I saw it at 6 and 56 processes

## Impact
Died simulation bad bad.
Reduced flexibility in how distributed our flow simulations can be
Makes NS module look bad when we're trying to make it good
Lost analyst time

**Comment by lindsayad** [comment]
I think I could probably fix this pretty quickly
