### ISSUE TITLE
Add a num failed time steps postprocessor

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#22017]
## Reason
When trying to optimize a timestepper to make a simulation look better, it'd be easier to directly see how many time steps failed

## Design
Very simple postprocessor, retrieving the number from the problem

## Impact
Easier time optimizing time steppers on stiff problems

**Comment by GiudGiud** [comment]
@socratesgorilla please let me know if you're interested on that one

**Comment by socratesgorilla** [comment]
Go ahead and assign I can work on this alongside the other time step stuff
