### ISSUE TITLE
Remove boundary ghost cells from FVM

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#22048]
## Reason
Even though it simplifies certain things, using boundary ghosting is not a valid option for 3D unstructured meshes and would potentially lead to wrong results.

## Design
- Remove boundary ghost cells from MooseMesh and FaceInfo
- Forbid the usage of interpolate() functions on the boundary
- Switch the boundary treatment to the standard one (mirroring instead of 180 degree rotation)

## Impact
Will increase the reliability of 3D Moose FV simulations on unstructured meshes.

**Comment by joshuahansel** [comment]
Would this be changing the mathematical formulation of the FV boundary conditions or just the implementation? I'm just curious which BC formulations you propose.
