### ISSUE TITLE
Add print_nonlinear_residuals option, to turn it off, in Outputs

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#22056]
## Reason
For some tough problems there can be a lot of nonlinear iterations. if this is expected, then it s not helpful to clobber the screen with hundreds of lines

## Design
New boolean in Outputs

## Impact
Less verbose simulations, slicker screens, happier users

**Comment by GiudGiud** [comment]
@socratesgorilla interested?

**Comment by socratesgorilla** [comment]
sure

**Comment by GiudGiud** [comment]
nice
