### ISSUE TITLE
Make action parameters also controllable

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#22068]
## Reason
It is desired to change certain parameters in an input file during the calculation. This can be achieved with controllable parameter capability. However, currently, only objects derived from `MooseObject` can have controllable parameters. A large portion of input syntax with `Action`s cannot have controllable parameters. A parameter in an action might be used for constructing bunch of moose objects, it will be up to action developers to connect the controllable parameter in an action with the parameters of all the depending moose objects, which has been a capability in the input parameter warehouse.

## Design
To achieve this, we will first need to make the parameters of various actions held by the `InputParameterWarehouse` like the moose objects but instead of the action itself, and change the constructor interface from
```
  Action(InputParameters parameters);
```
to
```
  Action(const InputParameters & parameters);
```
This will be a relative large change in interface and will affect all applications.

## Impact
A new capability.

**Comment by loganharbour** [comment]
I think this is a pretty significant change that needs to be discussed further
