### ISSUE TITLE
Improve error checking for missing block/sideset IDs

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#22117]
## Reason
Many mesh generators do not properly check if a user-specified block ID/Name or sideset ID/Name are actually present in the mesh before trying to do something. For example, `SideSetsBetweenSubdomainGenerator` doesn't actually check if the `primary_block` and `paired_block` exist in the mesh, and will silently just do nothing if either is missing. This is probably an error, and can mask issues in complicated meshes.

## Design
Add error checks for subdomain and sideset existence in mesh generators that rely on them.

## Impact
Better error checking.

**Comment by GiudGiud** [comment]
with #28550 we should be able to close this as all generators will have been fixed to address this
