### ISSUE TITLE
Truss element support

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#2212]
I tried to run a truss element where the mesh had three coordinates.  I used displacements = "disp_x disp_y disp_z" in the Mesh block.  I got an error message from SetupMeshAction: "Number of displacements and dimension of mesh MUST be the same!"  The mesh had three dimensions, but the code didn't recognize that.

I was able to get the problem to run with a trick.  I put a dummy hex element in the mesh.  The hex does nothing except make the code happy with three dimensions.  The truss elements worked properly in my simple test.

So, we need support for topologically 1D elements in 3D.

**Comment by permcody** [comment]
Believe it or not, this should finally be fixed in #12771. In a nutshell, we respect coordinates now, not element types when writing out any kind of mesh. The only exception is that we still always output 1D meshes as 3D for better visualization purposes.

**Comment by dschwen** [comment]
https://youtu.be/ria37d9mInY
