### ISSUE TITLE
Automatically Read Last Timestep For Initial From Timestep

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2215]
Andrew Wilkins asked if we could automatically read the last timestep from the file for use in initial_from_timestep.  His solution was to set initial_from_file_timestep = -1.... which I find reasonable.

**Comment by permcody** [comment]
This was completed a long time ago. https://github.com/idaholab/moose/pull/5754
```
initial_from_file_timestep = LATEST
```
