### ISSUE TITLE
Properly allow and document sideset names in SideSetsFromBoundingBoxGenerator

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#22230]
## Reason
It's one of the few generators still using Ids only, though some of the code is actually compatible with names

## Design
Fix up the parameters
Use the meshUtils conversion routines

## Impact
Better user experience

**Comment by GiudGiud** [comment]
@socratesgorilla want to take that one?

**Comment by socratesgorilla** [comment]
Sure tag me on this one

**Comment by GiudGiud** [comment]
Tied to https://github.com/idaholab/moose/issues/20976
