### ISSUE TITLE
Within given execute flag, execute some general UOs before elem/side/internal/interface uos

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#22255]
## Reason
Some general UOs depend on elem/side/internal/interface UOs and so should be executed after those. However, the reverse can also be true.

## Design
Look at the overall user object sorting and see what general UOs occur before the loop UOs.

## Impact
Better UO execution ordering

**Comment by GiudGiud** [comment]
This is solved by the execution groups capability for user objects
Closing as solved by #23473 

Please re-open if you disagree

**Comment by lindsayad** [comment]
Yea I think it accomplishes the title of the issue
