### ISSUE TITLE
Change MooseMesh::getBoundaryName

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#22298]
## Reason
It's really slow

## Design
Just query `_mesh_sideset_ids` data member instead of looping over the entire elem-side-bc data

## Impact
Improve user's experience. Make boundary integrity checks much faster

**Comment by YaqiWang** [comment]
This was impacting a model from @vincentlaboure that contains lots of boundary sides. The slowness happens inside `BoundaryElemIntegrityCheckThread` where this function is called.
