### ISSUE TITLE
Improve the error handling of `Transfers` input parameters

### ISSUE THREAD

**Issue by licharlot** [idaholab/moose#22308]
## Bug Description

In a `Transfers` object, if `from_multiapp = app_name` is used instead of `from_multi_app = app_name`, a segmentation fault is generated after the sub-app initialization.

## Steps to Reproduce

Run the attached input file, or use `from_multiapp = app_name` instead of `from_multi_app = app_name`

## Impact

The usual behavior when input parameters have a typo is an error or warning message during the input file processing. `from_multiapp` and `to_multiapp` were the keywords used in the deprecated `direction` input parameter, so this is likely that this typo will be made. The current behavior let the user think there is a problem in the sub-app. 

[input_files.zip](https://github.com/idaholab/moose/files/9716909/input_files.zip)

**Comment by GiudGiud** [comment]
That's probably my fault. I ll put up a patch

**Comment by cpgr** [comment]
Similarly, a typo of `to_multiapp` hits a pretty unhelpful assertion in `devel` or `dbg` modes:
```
Assertion `i < _current.size()' failed
Access out of bounds in MultiMooseEnum (i: 0 size: 0)
at /Users/gre462/Documents/MOOSE/projects/moose/framework/src/utils/MultiMooseEnum.C, line 170
```

**Comment by GiudGiud** [comment]
looks like I forgot to put up a patch
