### ISSUE TITLE
restart filenumber size fixed

### ISSUE THREAD

**Issue by mooseframework** [idaholab/moose#2231]
In XDAOutput, the restart files use a number.  This is hardcoded to a setw(4).  This means if the numbers increase past 9999, the filename will go from ..._9999 to ..._10000  so the numbers would look like 0000,0001,0002 ... 9998,9999,10000 

This would probably be better if XDAOutput allowed the width to be customized.

**Comment by permcody** [comment]
`FileOutput` has a `padding` parameter that handles this.
