### ISSUE TITLE
Userobjects test failing with threads

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#2240]
userobjects/layered_side_integral.flux_average is failing with treads. I am getting somewhat consistent failures with --n-threads=7 and occasional failures with 5

**Comment by permcody** [comment]
@aeslaughter - I saw this issue since i was poking around looking for threaded issues after the merge of https://github.com/idaholab/moose/commit/a4c5b5fe8502fa77d78ce21d4084f9f5f154d7a2 and I still can't repeat this error. Maybe you could try it once again and see if you can get it to fail.

**Comment by aeslaughter** [comment]
I can't get it to fail either.
