### ISSUE TITLE
Delay the recovery early return for steady-state executioners

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#22432]
## Reason
Currently `Eigenvalue::init` and `Steady::init` issue a message and do an early return when application is in recovery mode `if (_app.isRecovering())`. This prevents me from deriving an executioner for doing sequential steady-state calculations with recovery.

## Design
I think recovery mode is allowed even we are at steady-state. I also think we can possibly get rid of the check. But I do not want to go that far and just propose to delay the check in their `execute` function.

## Impact
Better modular design in executioners for allowing C++ inheritance.

**Comment by lindsayad** [comment]
Does it actually issue errors? I thought it only performed early returns

**Comment by lindsayad** [comment]
Which of the two executioners you mention are you deriving from? I guess you decided that you didn't just want to override `init`?

**Comment by YaqiWang** [comment]
> Which of the two executioners you mention are you deriving from? I guess you decided that you didn't just want to override `init`?

`Eigenvalue`. Overriding `init` is ugly and one function called by `Eigenvalue::init` is a private member function, thus I will need to change that even I do overriding `init`.
