### ISSUE TITLE
A new multiapp system based on elemental quadrature points

### ISSUE THREAD

**Issue by abarun22** [idaholab/moose#22490]
## Reason
This funtionality would serve as a multiapp framework that will create a sub-app at each of the spatial locations of the macro quadrature points

## Design
Quadrature point locations are collected and populated in "_positions" variable that provides refereces for the creation of individual multi-apps

## Impact
A specific "fillPositions" has been implemented for this purpose

**Comment by GiudGiud** [comment]
closing as addressed by https://github.com/idaholab/moose/pull/21340

Note that we can now also perform this using a MultiAppPositions and a positions object. This latter approach lets us work with both a FullSolveMultiapp and a TransientMultiApp
