### ISSUE TITLE
Parallelize Material Property Restart

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2251]
Currently the writing of stateful properties is serialized by processor ID.

Go to a system where every processor writes it's own file in this format:

name.msmp-RANK-TID

Where RANK is the MPI rank and TID is the thread ID (the -TID part should only be written if running with threads).

**Comment by permcody** [comment]
@friedmud - I believe this issue is now invalid with the new restart format. Please review and close if possible

**Comment by friedmud** [comment]
Yep.
