### ISSUE TITLE
Need to init submodules in Docker builds post-install

### ISSUE THREAD

**Issue by herter4171** [idaholab/moose#22559]
## Bug Description

For our container users, their MOTD has the commit hashes of the submodules, and they are also used for generating documents.  How we build the images by avoiding caching submodules in the layers effectively deinits the submodules, so I'll add a second init after they're installed.

## Steps to Reproduce

In a MOOSE container,
```
cd $MOOSE_DIR
git submodule status
```
## Impact
We need to be able to build docs, so I'll be submitting a PR shortly.

**Comment by loganharbour** [comment]
Hmm - I think this is somewhat intentional so that we have small images, no?

**Comment by herter4171** [comment]
It's just a `git submodule init`, so no pulling down files.
