### ISSUE TITLE
Error occurs when CZM used no-AD TensorMechanics object with Eigenstrain

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#22597]
## Description
Seg fault on declaring the derivative material property name, retrieving the name of a variable which doesnt exist because a constant value was passed instead of variable

## How to reproduce
Run the input in discussions

## Impact
Seg faults look bad and require a debugger

### Discussed in https://github.com/idaholab/moose/discussions/22576

<div type='discussions-op-text'>

<sup>Originally posted by **echo1115** November  2, 2022</sup>
Hi everyone,
I run the case in https://github.com/idaholab/moose/blob/dfa17cdbb0/modules/tensor_mechanics/test/tests/cohesive_zone_model/bilinear_mixed.i , but I used no-AD TensorMechanics object, and applied a ThermalExpansionEigenstrain. However, the case failed with the following message :
```
*** Info ***
TensorMechanics Action: selecting 'incremental finite strain' formulation.[39m

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 42920 RUNNING AT ga0408
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
Here is the modified input:
```
[Mesh]
  [msh]
    type = GeneratedMeshGenerator
    dim = 2
    xmax = 1
    ymax = 2
    nx = 1
    ny = 2
  []
  [block1]
    type = SubdomainBoundingBoxGenerator
    input = 'msh'
    bottom_left = '0 0 0'
    top_right = '1 1 0'
    block_id = 1
    block_name = 'block1'
  []
  [block2]
    type = SubdomainBoundingBoxGenerator
    input = 'block1'
    bottom_left = '0 1 0'
    top_right = '1 2 0'
    block_id = 2
    block_name = 'block2'
  []
  [split]
    type = BreakMeshByBlockGenerator
    input = block2
  []
  [top_node]
    type = ExtraNodesetGenerator
    coord = '0 2 0'
    input = split
    new_boundary = top_node
  []
  [bottom_node]
    type = ExtraNodesetGenerator
    coord = '0 0 0'
    input = top_node
    new_boundary = bottom_node
  []
[]

[GlobalParams]
  displacements = 'disp_x disp_y'
[]

[Modules]
  [TensorMechanics]
    [Master]
      generate_output = 'stress_yy'
      [all]
        strain = FINITE
        add_variables = true
        #use_automatic_differentiation = true
        decomposition_method = TaylorExpansion

        eigenstrain_names = 'thermal_eigen'
      []
    []
  []
[]

[BCs]
  [fix_x]
    type = DirichletBC
    preset = true
    value = 0.0
    boundary = bottom_node
    variable = disp_x
  []

  [fix_top]
    type = DirichletBC
    preset = true
    boundary = top
    variable = disp_x
    value = 0
  []

  [top]
    type = FunctionDirichletBC
    boundary = top
    variable = disp_y
    function = 'if(t<=0.3,t,if(t<=0.6,0.3-(t-0.3),0.6-t))'
    preset = true
  []

  [bottom]
    type = DirichletBC
    boundary = bottom
    variable = disp_y
    value = 0
    preset = true
  []
[]

[Modules/TensorMechanics/CohesiveZoneMaster]
  [czm_ik]
    boundary = 'interface'
  []
[]

[Materials]
  [stress]
    #type = ADComputeFiniteStrainElasticStress
    type = ComputeFiniteStrainElasticStress
  []
  [elasticity_tensor]
  #  type = ADComputeElasticityTensor
    type = ComputeElasticityTensor
    fill_method = symmetric9
    C_ijkl = '1.684e5 0.176e5 0.176e5 1.684e5 0.176e5 1.684e5 0.754e5 0.754e5 0.754e5'
  []
  [./thermal_expansion_strain]
    #type = ADComputeThermalExpansionEigenstrain
    type = ComputeThermalExpansionEigenstrain
    stress_free_temperature = 800
    thermal_expansion_coeff = 4.9e-6
    temperature = 800
    eigenstrain_name = 'thermal_eigen'
  [../]
  [czm]
    type = BiLinearMixedModeTraction
    boundary = 'interface'
    penalty_stiffness = 1e6
    GI_c = 1e3
    GII_c = 1e2
    normal_strength = 1e4
    shear_strength = 1e3
    displacements = 'disp_x disp_y'
    eta = 2.2
    viscosity = 1e-3
  []
[]

[Preconditioning]
  [smp]
    type = SMP
    full = true
  []
[]

[Executioner]
  type = Transient

  solve_type = 'NEWTON'
  line_search = none

  petsc_options_iname = '-pc_type'
  petsc_options_value = 'lu'

  automatic_scaling = true

  l_max_its = 2
  l_tol = 1e-14
  nl_max_its = 30
  nl_rel_tol = 1e-50
  nl_abs_tol = 1e-15
  start_time = 0.0
  dt = 0.1
  end_time = 1.0
  dtmin = 0.1
[]

[Outputs]
  exodus = true
[]

```
Acturally the ThermalExpansionEigenstrain is zero because the temperature  equals to  the stress_free_temperature.

The error message is the same in debug mode. Could anyone give me some help? Maybe @hugary1995 @jiangwen84 can give me some suggestions. Thanks in advance.
</div>

**Comment by hugary1995** [comment]
Do you have a patch ready? If so, I'm curious about the way you handle it.

**Comment by GiudGiud** [comment]
Semi-ready I have not tested it

**Comment by GiudGiud** [comment]
@hugary1995 this is present in numerous other files in tensor_mechanics.
We add a coupledVar, which could be a nullptr on getVar() then try to get the name for various purposes, often derivatives

Fortunately, I think a lot of these models are only called through actions. 

For rotation / displacement (variable usually, user would pass a number to trigger a problem)
computeIncrementalBeamStrain 
ADComputeIncrementalShellStrain

For mat prop derivatives
ComputePFFractureStressBase with variable c
ComputeCrystalPlasticityThermalEigenstrain with temperature variable
ComputeConcentrationDependentElasticityTensor with variable c
StressBasedChemicalPotential with variable c
ThermalFractureIntegral with variable temperature
ComputeCrackedStress with variable c
HyperElasticPhaseFieldIsoDamage with variable c

A few ideas:
- same fix for each of these, guard against nullptr on getVar
- make getVar() error instead of returning nullptr and call that resilient enough. Users would have to declare auxvariables instead of these constants
- change the parameter type to force an actual variable at parameter time

**Comment by hugary1995** [comment]
On the framework level, is the following usage supported?
```python
[foo]
  type = bar
  var = 0.123
[]
```
where `var` was added by `params.addCoupledVar("var", "doc string");`.

**Comment by GiudGiud** [comment]
yes

**Comment by GiudGiud** [comment]
what is not supported is these getVar() calls with those constants.

I think I want option 2 at this point.
What do you think?

**Comment by hugary1995** [comment]
So I guess if I call `coupledValue("var")`, the framework would automatically create a dummy `MooseVariable` behind the scenes. If that's the case, I'd prefer `getVar("var")` (when var is set to a plain number) to return the pointer to that dummy `MooseVariable`.

**Comment by GiudGiud** [comment]
But what if you are not calling coupledValue() before you do these getVar calls

For example here, these materials might only care about dMdT, never retrieve T

**Comment by hugary1995** [comment]
That's probably not something the framework would be responsible for. When a user calls `getVar`, he/she would expect to get the pointer to the variable -- that's all. What the user intends to do with that pointer is another story.

The real issue I see here is the discrepancy in two framework APIs:
- `coupledValue` is happy with a plain number from the input file
- `getVar` is not...

**Comment by GiudGiud** [comment]
coupledValue has internal logic to handle the constant input. 
It relies on getVar in the backend though.

Option 4:
- add a getVarName or a coupledName to get the name without relying on getVar(), and with the additional logic there.

Names are what is being retrieve in all the problematic calls 

I see that Option 2 would not really work because some of our logic relies on the nullptr from getVar(Helper)

**Comment by lindsayad** [comment]
I think `getVar` returning a `nullptr` when there is no variable is fine

**Comment by GiudGiud** [comment]
any preferences wrt to getting a name then

**Comment by lindsayad** [comment]
What name would you return when the variable doesn't exist? I don't get it

**Comment by GiudGiud** [comment]
probably just the number

**Comment by GiudGiud** [comment]
or "constant_<number>"

**Comment by lindsayad** [comment]
I feel like that could be misleading. Could that somehow lead to a user passing a string to the coupled variable parameter and us registering everything as fine even if the string doesn't correspond to an actual variable name?

**Comment by hugary1995** [comment]
I tend to agree with Alex now after giving it some more thought in the last few days. My take on this now is that the current behavior of `coupledValue` and `getVar` is fine when the supplied variable is a plain number. 

However, the current behavior creates confusion for the end users. Imagine a user (like in the OP) believes `coupled_var = 0.123` is a valid syntax in input files when it expects a variable, because it works in so many places, and all of a sudden `coupled_var = 0.123` no longer works only because behind the scenes the developer is trying to get the name of the coupled variable (e.g., for use in declaring a derivative material property).

So I believe it is the developer's responsibility to handle this special case. One way to do this is of course like what @GiudGiud is doing in the patch PR. But if we need to handle this "special case" in so many places, especially in the tensor mechanics module, I think there deserves to be a better way of handling this in the source code as well (without testing for nullptr).

**Comment by hugary1995** [comment]
In other words, I think a way of telling whether the coupled variable is inferred from a plain number will be useful. Again, using derivative material interface as an example, currently we have
```cpp
   _d_a_d_b(declarePropertyDerivative<Real>(getVar("a")->name(), getVar("b")->name()))
```
it could be better if we can do something like
```cpp
  _d_a_d_b(declarePropertyDerivative<Real>(getVarName("a"), getVarName("b")))
```
where `getVarName` can handle the plain number case behind the scenes.

**Comment by GiudGiud** [comment]
I dont think what Alex is saying will happen.
We would have something like:
coupledName(var_name)
{
if var_name is number:
  return constant + var_name
if getVar(var_name):
  return getVar() -> name()
mooseError("Variable" var_name "was passed as a parameter but does not exist.")
}
for this particular API.

And for the others we already do not allow non-number random strings which are not variables.

**Comment by GiudGiud** [comment]
getVarName = coupledName and I think we agree @hugary1995

**Comment by hugary1995** [comment]
FWIW, there is already `coupledNames` API: https://github.com/idaholab/moose/blob/next/framework/src/interfaces/Coupleable.C#L2143-L2148

It's a matter of extending it (to handle the nullptr case) IMHO. Probably add another `coupledName` API which additionally takes an index.

**Comment by lindsayad** [comment]
`declarePropertyDerivative` may be fine taking a made-up string, but what about other APIs accessible to developers? This could just be kicking the can down the road, e.g. you may get a seg-fault later when another API attempts to retrieve a variable given a made-up name. But I suppose we can just robustify whatever hypothetical API that is when we get there.

**Comment by GiudGiud** [comment]
Let's add `coupledName` for these for-sure-unique variable cases like derivatives.

Maybe we should just use the number if you are worried about using a made-up name. 
More APIs are resistant to being passed numbers

**Comment by GiudGiud** [comment]
I dont really like a dM_d800 property, but dM_dconstant_800 isnt that much cuter

**Comment by GiudGiud** [comment]
🚲 🛖

**Comment by GiudGiud** [comment]
I think we all agree we can't segfault on this anymore. 
I'll make a PR and catch all the existing potential seg-faulting getVar()->name()

**Comment by dschwen** [comment]
Seeing this discussion way too late as I'm probably directly or indirectly responsible for most of the getVar->name cases. My suggestion would be adding a `coupledName` API that returns a custom `CoupledVariableName` class that can evaluate as a string and additionally has a method to check if the "name" is a constant. 

That would allow me to overload the `declarePropertyDerivative` method etc. and replace all getVar-Name simply with coupledName

**Comment by lindsayad** [comment]
![image](https://user-images.githubusercontent.com/10248304/201176143-2c5d777c-9c6b-46c5-a037-df1cb541070a.png)
