### ISSUE TITLE
Register RadialAverageAux to MooseApp

### ISSUE THREAD

**Issue by FHilty** [idaholab/moose#22726]
## Reason
The user object `RadialAverage` performs a spatial averaging of a material property within a specified radius of each node. It was made to work with certain damage model kernels, however the basic functionality of it could be useful in other places. In my case i can use it help with overlap issues in Discrete Nucleation. To use the radial average map created by `RadialAverage` there is an auxkernel `RadialAverageAux` that can store the generated map in an auxvariable for use elsewhere. However, currently `RadialAverageAux` is not natively usable in the framework because registered to the `MooseTestApp`. 

## Design
Register `RadialAverageAux` to `MooseApp`.

## Impact
This change will allow broader application of the `RadialAverage` functionality without requiring the user to manually register `RadialAverageAux` to `MooseApp`.

**Comment by GiudGiud** [comment]
So actually @aprilnovak is adding the nearest point average user object.

This UO will be useable to set variables using the SpatialUserObjectAux 
So it can act as a RadialAverageAux, but it can do other things so we will prefer this other route

**Comment by FHilty** [comment]
Thats great! I look forward to trying it out.

**Comment by GiudGiud** [comment]
April's PR is merged. Please try out the nearest point average UO and the SpatialUserObjectAux for your needs
Closed by #18541
