### ISSUE TITLE
Improving user experience with stochastic tools module

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#22827]
## Reason

These are some suggestions from users to improve the experience when doing stochastic simulations with the stochastic tools module.

## Design

- [ ] Outputting sampler data along side quantity of interest results
- [ ] Make `Problem/verbose_multiapps=true` show relevant information when in batch mode
- [ ] Show status of sub-app sampling across processors
- [ ] Change file base for batched sub-apps in order to output to different files

## Impact

Better STM experience.

**Comment by YaqiWang** [comment]
Thanks @zachmprince.

Not sure if the third item is related. I had a case where the main processor finished running but other processors are not, then the main processor waited. It can be nice to let the main processor output on screen something about the status.

I want to have a simple way to pass a command-line parameters to the subapps of STM. Probably we already had something with our MultiApp system, but it is not as straight-forward as passing parameters running the input directly. This might just indicate myself not an experienced user of STM ;-)

**Comment by zachmprince** [comment]
> I want to have a simple way to pass a command-line parameters to the subapps of STM. Probably we already had something with our MultiApp system, but it is not as straight-forward as passing parameters running the input directly. This might just indicate myself not an experienced user of STM ;-)

@YaqiWang This can be done using `MultiApps/*/cli_args` syntax. You can see examples of this [here](https://github.com/idaholab/moose/tree/next/modules/stochastic_tools/test/tests/multiapps/user_cli_args).
