### ISSUE TITLE
Remove limiter and upwind members from SingleSidedFaceArg

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#22834]
## Reason
I don't think SSFs should take limiter or `elem_is_upwind` arguments because to me the purpose of the SSF is to only use data on one side of the face. If `elem_is_upwind` is false but you want to evaluate on the element side of the face, it feels wrong to use to downwind (neighbor side of the face) information.

## Design
Remove those members and update code

## Impact
More clarity and distinction around what a SSF is for

**Comment by lindsayad** [comment]
@grmnptr you recently touched this in 
```c++
template <typename OutputType>
typename MooseVariableFV<OutputType>::ValueType
MooseVariableFV<OutputType>::evaluate(const SingleSidedFaceArg & face,
                                      const unsigned int libmesh_dbg_var(state)) const
```
What are your thoughts on this?

**Comment by grmnptr** [comment]
I like the idea of not touching the cells on the information on the other side!
