### ISSUE TITLE
Add ParsedCurveGenerator

### ISSUE THREAD

**Issue by miaoyinb** [idaholab/moose#22848]
## Reason
It has been found needed to have a general curve mesh generator to enable meshing of some complex shapes. The mesh generator should be able to work with existing [FillBetweenPointVectorsTools](https://mooseframework.inl.gov/source/utils/FillBetweenPointVectorsTools.html) and [XYDelaunayGenerator](https://mooseframework.inl.gov/source/meshgenerators/XYDelaunayGenerator.html) to expand their meshing capabilities.

## Design
`ParsedCurveGenerator` will be added to generate a curve mesh that is defined by (x(t), y(t), z(t)) using the [Function Parser](http://warp.povusers.org/FunctionParser/) library that is already adopted by MOOSE.

`FillBetweenCurvesGenerator` will be added to work with the curves generated using the [FillBetweenPointVectorsTools](https://mooseframework.inl.gov/source/utils/FillBetweenPointVectorsTools.html).

The generated curves (if closed) should be naturally compatible with  [XYDelaunayGenerator](https://mooseframework.inl.gov/source/meshgenerators/XYDelaunayGenerator.html).

## Impact
Enable meshing of some complex geometry features. This has been found needed for some reactor designs.

**Comment by GiudGiud** [comment]
Does the curve need to be closed?
