### ISSUE TITLE
Rerun only failed tests

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2285]
It would be handy if I could invoke run_tests in a mode that only reran the tests that failed last time.

Maybe:

./run_tests --failed

?

**Comment by permcody** [comment]
Right, The way this would work would be to print out (to disk) the list of failed tests from every run in a `.failed_tests` file or something. Then you'd rerun the tests with some flag that would open that file and simply run the tests in that file.

```
./run_tests --fail or -f  # if we aren't already using -f for something
```

**Comment by milljm** [comment]
Sounds good to me. Perhaps I can refactor some of that PBS junk thats in there when we perform an os.walk. I take it, that _is_ where we will need to determine what tests to run (the failed ones, as opposed to all of them, as opposed to PBS, etc)?

Or maybe do something clever in checkRunnableBase...

**Comment by permcody** [comment]
I wouldn't try to make this work with PBS at all. What I would do is write to a local hidden file every time we report an unsuccessful test. If a user passes a new flag, we'll try to open that file and will only run tests that match those patterns. That's all there is to it.

**Comment by milljm** [comment]
Okay cool... easy peasy.
