### ISSUE TITLE
Navier-Stokes flow model and porous-medium flow model based on SAM implementation

### ISSUE THREAD

**Issue by lingzou** [idaholab/moose#22917]
## Reason

The SAM code has its own FEM implementation of Navier-Stokes flow model and porous-medium model. Based on the NEAMS discussions, these capabilities are generic enough such that they should be moved up to the moose submodule level, so all moose users will benefit with this additional option.

## Design

The SAM FEM implementation of Navier-Stokes flow model and porous-medium model based on the PSPG/SUPG stabilization scheme will be migrated from SAM to moose Navier-Stokes module.

## Impact

Provide additional option to users who would like to simulate Navier-Stokes flow and/or porous-medium flow.

**Comment by lindsayad** [comment]
marking this as closed by https://github.com/idaholab/moose/pull/22671
