### ISSUE TITLE
Restrict or allow evaluation of transfer locations outside of the domain of definition of an app

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#22926]
## Reason
UOTransfer currently will only check the bounding box for whether it s evaluation point is contained in an app or not. This is not quite sufficient, as an app s domain may not be rectangular. 
As a result, we can evaluate UOs out of bound. This can be problematic

But there are also legitimate uses for that, namely interpolating in areas surrounding subapps

## Design
Boolean and a point locator to check whether an app's mesh contains a point or not

## Impact
More flexibility in how we pass information between applications

**Comment by friedmud** [comment]
Definitely should be an option that can be turned off 👍

**Comment by GiudGiud** [comment]
General field transfers will have this option I already added it.

**Comment by GiudGiud** [comment]
Closing as implemented in #17417
