### ISSUE TITLE
Create FaceCenteredMapFunctor for face-centered fields

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#22970]
## Reason
In the segregated solvers of the NavierStokes module, we communicate between the pressure and velocity equations using the face fluxes/velocities. For this, we need a functor that can store values at face centers and reconstruct cell values based on those. 

## Design
Adding a FaceCenteredMapFunctor which is similar to the CellCenteredMapFunctor but overrides the evaluation methods differently.

## Impact
Enables Finite Volume fields which are face based. Makes the implementation of segregated solvers easier.

**Comment by GiudGiud** [comment]
Should we just have FunctorArgumentMap ?
Templated on the functor arguments
