### ISSUE TITLE
Add MooseEnum option documentation

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#23004]
## Reason
To enrich auto completion and documentation page generation, MooseEnum items should have individual documentation strings.

## Design
Add a map to `MooseEnumBase` that holds a doc string for each item. Add `myenum.addDocumentation("ITEM", "Doc string.");` and `myenum.addDocumentation({{"ITEM1", "Doc string1."}, {"ITEM1", "Doc string1."}});` methods.

Emit the doc strings in the JSON dump.

## Impact
Better self documentation.

**Comment by friedmud** [comment]
Ooooh - I like this idea!
