### ISSUE TITLE
Improve error messages in reactor module

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#23090]
## Reason
Many error messages in the reactor module tell you that something is wrong, but don't give any hint by which to address the error. One example:

```
*** ERROR ***
/home/anovak/cardinal/utils/meshes/fuel_pins/solid.i:14: (Mesh/pin/ring_block_ids):
    This parameter must have the appropriate size if it is provided.
```

This error message could be improve by either (i) telling you what the size should be (a number), or (ii) telling you what other input file parameter you're trying to match length to. This is just one example, but there's probably about 10 different errors I hit a lot (scripting meshes) that are hard to track down when using `${...}` syntax with vectors in input files.

## Design
Use more explicit error messages.

## Impact
Improved user experience.

**Comment by GiudGiud** [comment]
Reported by Ollin

Another issue is that the hex lattice errors on missing metadata without saying which input is problematic
```
Getting this error in HexIDPatternedMeshGenerator
In PatternedHexMeshGenerator hex_core: the unit hexagonal input mesh does not contain appropriate meta data required for generating an assembly.
Where I'm trying to put a hexagonal assembly generated using HexIDPatternedMeshGenerator  into a hexagonal core using HexIDPatternedMeshGenerator  alongside other assemblies which are PolygonConcentricCircleMeshGenerator aside from setting generate_core_metadata = true what else do I need to do to resolve this error?
```

**Comment by miaoyinb** [comment]
I will work on this. Thanks for reporting the issue.
