### ISSUE TITLE
Recover support in Peacock

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#2312]
We need a checkbox or some other way of turning on the recover flag in peacock.  Additionally the Visualizer will need to re-read the first Exodus file if adaptivity is on.

**Comment by permcody** [comment]
Ping @aeslaughter and @brianmoose. Not a big deal but this would be cool if this worked in the new Peacock.

**Comment by aeslaughter** [comment]
This shouldn't be difficult.

**Comment by aeslaughter** [comment]
We can do this, you can add arbitrary command line arguments to the executable.

**Comment by permcody** [comment]
What about the other half of this ticket? When you run a recover do you see the whole sim or just the recovered part? Does the visualizer work with and without adaptivity? There are several nuances to getting this correct.

**Comment by aeslaughter** [comment]
Recover appends the existing file, you would see the entire simulation.
Adaptivity has always worked in Peacock.

**Comment by brianmoose** [comment]
There is actually a "recover" checkbox on the execute tab that adds the --recover to the command line. I wasn't sure if anything else needs to be added.

**Comment by permcody** [comment]
Nothing else needs to be added. We should probably make sure we have unit
tests for simulations with and without adaptivity.
