### ISSUE TITLE
Incorporate SAM multi-D kernels into Navier-Stokes module

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#23121]
## Reason
We want to try to consolidate NEAMS thermal hydraulics development in common layers as upstream as possible, e.g. for example in the `navier_stokes` module

## Design
Move SAM multi-D kernels (and related objects such as bcs) into `navier_stokes`

## Impact
Create common layers for INL and ANL development. Let's all work in the same sandbox and create a united product as much as possible

**Comment by lindsayad** [comment]
@lingzou do you have any (open) issues in SAM related to your multi-D residual objects that you would want to port over into MOOSE given that we are getting ready to merge #22671?

**Comment by lingzou** [comment]
@lindsayad Thanks for moving the multi-D flow PR forward. No, we don't have anything currently waiting and need to postpone this PR. I will have some future polishing for the multi-D flow model, but mostly will be minor.

Thanks again for the help!

**Comment by lindsayad** [comment]
I didn’t mean for postponing the PR. Just like for example when we moved THM into MOOSE we brought over its entire issue tracker. Since SAM isn’t going away I don’t envision a large scale porting like that. Anyway if you don’t have any open issues in the SAM issue tracker related to the multi D code, then we can not worry about it
