### ISSUE TITLE
Add Material Properties for Uranium Monocarbide

### ISSUE THREAD

**Issue by AyaHegazy22** [idaholab/moose#23207]
## Reason
Adding the thermal material properties (temperature dependent) of Uranium Monocarbide in the solid_properties module.  
The Userobjects available in the Solid Properties module that provide thermal properties are:
[graphite](https://mooseframework.inl.gov/source/userobjects/ThermalGraphiteProperties.html)
[monolithic silicon carbide](https://mooseframework.inl.gov/source/userobjects/ThermalMonolithicSiCProperties.html)
[composite silicon carbide](https://mooseframework.inl.gov/source/userobjects/ThermalCompositeSiCProperties.html)
[stainless steel alloy 316](https://mooseframework.inl.gov/source/userobjects/ThermalSS316Properties.html)
[using functions](https://mooseframework.inl.gov/source/userobjects/ThermalFunctionSolidProperties.html)

## Design
A PR was implemented to add this material.
EDIT: a new solid properties user object
Adding more Userobjects in the Solid Properties module.

## Impact
EDIT:
Provides the properties to all downstream apps for nuclear thermal solid simulations

**Comment by cticenhour** [comment]
Please use the Issue Template when creating any MOOSE issue - this should have pre-populated your issue when you created a new one, so please do not delete it. You may copy and paste the GitHub markdown below and edit your issue by using the three dots at the top right of your issue comment. 

```
## Reason
<!--Why do you need this feature or what is the enhancement?-->

## Design
<!--A concise description (design) of the enhancement.--->

## Impact
<!--Will the enhancement change existing APIs or add something new?-->
