### ISSUE TITLE
RunTime is not a registered object

### ISSUE THREAD

**Issue by RWTHLHK** [idaholab/moose#23286]
## Bug Description
I am running phase-field module example " [Fe-Cr Phase Decomposition](https://mooseframework.inl.gov/modules/phase_field/Tutorial.html)". At the 2nd step, it always reports error RunTime is not a registered object even if I modified ALL-MODULES=yes in Makefile and recompiled the project.

## Steps to Reproduce
I used the same input file as the 2nd step "Make a faster model" (https://mooseframework.inl.gov/modules/phase_field/Tutorial/Step2.html)

## Impact
I am new uses of moose and I have to conduct phase-field simulation in my project. This really slows down my learning process.

**Comment by lindsayad** [comment]
@dschwen it looks like you fixed up the input file in cccee7fba7db89b81445fc152ffd270edbbffc56 and the corresponding documentation hasn't been updated

**Comment by dschwen** [comment]
I'll work on it.
