### ISSUE TITLE
Create RawFunctor(Interface)

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#23311]
## Reason
As an example, currently a user who wishes to use `TimeDerivativeAuxTempl` with an aux variable functor must use the `ADTimeDerivativeAux` variant. This can be very confusing to users who are are building input files that are otherwise totally devoid of AD. We can talk about the seeming silliness that an aux variable is an AD functor ... but that is probably a much more difficult issue to solve. An easier way to solve this is to create a new kind of functor and an interface that systems like `AuxKernels` can use that essentially takes the raw value of a functor. Thus AD functors could be used seamlessly in an aux kernel and there wouldn't be a need to have two different instatiations, e.g. `TimeDerivativeAux` for a non-AD functor, and `ADTimeDerivativeAux` for an AD-functor.

## Design
Create a `RawFunctor` type that is constructed with and stores another functor and whose evaluate methods just return the `raw_value` of the member functor. Also create a `RawFunctorInterface` that can store `RawFunctor` instantiations (we don't need to add them to the `SubProblem` as these are essentially raw-value wrappers of "real" functors) and that systems like `AuxKernel` will inherit from.

## Impact
Better user experience. Less confusion and less registered objects.

**Comment by lindsayad** [comment]
@dschwen @GiudGiud

**Comment by lindsayad** [comment]
There could also be a follow-on where we introduce another interface that can do the reverse, an `ADInterface` for use by AD objects which can promote non-AD functors to AD functors. Then we could remove `ADParsedFunction`

**Comment by GiudGiud** [comment]
I don't know about the name "Raw" but the idea is great.
Then we can control a bit which objects use this interface, namely PPs and AuxKernels (maybe even non-AD kernels) but not ADKernels.

**Comment by lindsayad** [comment]
Do you have a different name idea? I do think I should have said `RawValueFunctor` as that explicitly describes what it's doing, but I doubt you'd like that variation much better?

**Comment by GiudGiud** [comment]
Straight? Single? Direct? Plain?  (value) these arent great
maybe just RealFunctorInterface. Or NonADFunctorInterface to be blunt
