### ISSUE TITLE
Screen printouts from mesh generators like PatternedHexMeshGenerator can be excessive

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#23336]
## Reason
Running a case with `PatternedHexMeshGenerator` with 10 rings of assemblies results into a massive amount of screen outputs from mesh stitcher. They should be turned off by default.

## Design
libMesh mesh stitch function allows calling it with an argument `verbose`. The mesh generator needs to call it with this argument properly to avoid excessive screen messages. This may be the case for other `Patterned` mesh generators.

## Impact
Better user experience and no impact to calculations.

**Comment by GiudGiud** [comment]
I ll fix it it's ridiculous indeed

**Comment by GiudGiud** [comment]
Closing as fixed by #23518
