### ISSUE TITLE
Add a Web Server to MOOSE

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#23359]
## Reason
MOOSE already does everything else... why not also serve webpages?

But really: this is to allow external programs (specifically external controllers) to interact with running MOOSE calculations.

## Design
Create a Control that has a built in webserver that speaks JSON and allows us to interact with a running MOOSE calculation every timestep.

## Impact
New

**Comment by GiudGiud** [comment]
does this freeze the MOOSE execution while waiting for the updated data?

**Comment by dschwen** [comment]
Add a thread for the server

**Comment by friedmud** [comment]
> does this freeze the MOOSE execution while waiting for the updated data?

The server doesn't freeze MOOSE (I have it running on a thread like @dschwen says)... but in order for this to work for it's intended purpose the Control pauses to wait for input every time the Control runs.

It couldn't be any other way - the people that need this need to pull data and modify parameters every time step.

If you go run the example though: it runs fast and smooth.  If your external controller is fast then it's not an issue.

**Comment by Lin-INL** [comment]
Do we have any updates on this capability? Are we still planning to implement this web-based tool? It seems that the pull request has been closed already. This web-based tool can be a good mock-up unit for smoothly testing and interfacing with digital engineering platform and control systems...

**Comment by friedmud** [comment]
@loganharbour has been working on it - I suspect that other priorities came up by the end of the year!
