### ISSUE TITLE
ElementSubdomainModifier should not modify SubdomainIDs during the element loop

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#23371]
## Reason
`ElementSubdomainModifier` is currently changing `element->subdomain_id()` in `execute()`. This will cause UOs in the same execution stage operating on the same element (or face of the same element), see a subdomain ID that is inconsistent with the current subdomain set in `onSubdomainChange`. This will trip [this assertion](https://github.com/idaholab/moose/blob/198b8ca429115454bf7e56c78ec5004492136d1a/framework/src/base/Assembly.C#L1895-L1896) for example.

## Design
Store all subdomain id reassignments in a list first and only apply them to the elements in finalize.

## Impact
More robust capability. Ping @dewenyushu

**Comment by dewenyushu** [comment]
Nice finding!

**Comment by hugary1995** [comment]
Caching is _a_ fix. The ultimate fix in my opinion is to set up a dependency graph for runtime mesh modifiers (including this element subdomain modifier), pretty much like the current `MeshGenerator`s.

**Comment by dschwen** [comment]
Yeah, multiple options here

- A runtime mesh modifier system that runs independently of UOs
- Multiple UO loops
- A custom `execute_on` for a second UO loop :-p

I was going for the lowest hanging fruit.

**Comment by hugary1995** [comment]
Several things we frequently use at hand could be unified in to the runtime mesh modifier system, such as XFEM and CZM. I know I'm dreaming right now, but if we are heading towards that direction, I'd be happy to help.

**Comment by dschwen** [comment]
I like that idea. The scope is not small though and would require some funding. Maybe we can propose a workpackage that could cover this activity for next FY?

**Comment by hugary1995** [comment]
Sure, let's talk before FY24 planning.
