### ISSUE TITLE
Options for automatically adding extra element ids to Exodus and MOOSE problem

### ISSUE THREAD

**Issue by shikhar413** [idaholab/moose#23386]
## Reason
Currently, the `--mesh-only` option does not output extra element ids to the output mesh, which is useful to have for mesh visualization purposes before running the full MOOSE simulation. In addition, to add these extra element id's many additional lines are needed in the input file since a separate Aux Variable and Aux Kernel are needed for each extra ID of interest. Having a way to automate this would be useful to the user and could be used in downstream MOOSE codes / applications

## Design
The command line options should be modified so that the output mesh can be generated with extra element id's without relying on many additional setup steps. In addition, the `output_extra_element_ids` and `show_extra_element_ids` parameters should be defined in the input Exodus block, similar to `output_material_properties` and `show_material_properties`

## Impact

Useful for the user to visualize extra element id's on the mesh in a quick manner, and also automatically add the relevant aux variables and aux kernels as an action so that the input file can be defined minimally

**Comment by GiudGiud** [comment]
Closed as implemented by [#23387](https://github.com/idaholab/moose/pull/23387)
