### ISSUE TITLE
Rework reference residual

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#23398]
## Reason
`ReferenceResidualProblem` is a nice way to have better control over convergence criteria rather than the vanilla moose. It's used extensively in mechanics problems, but could be adapted for other types of problems with drastically different variable values or residuals, e.g. cluster dynamics.

For example, for a single particle problem with two springs, one attached to a wall and one being pulled:

![image](https://user-images.githubusercontent.com/7014706/218540179-8285a1fa-009d-416d-9bd4-1d3e29520dff.png)

Static equilibrium is set by the balancing of the forces of two springs on the particle, with equal but opposite signs, with the displacement of the particle as the free variable. Absolute tolerance would work well here as a convergence option, with the tolerance set to maybe 1e-6 times the force of _one_ of the springs on the particle. Where absolute tolerance will not work well is when drastically different forces are acting for different variables. For example, if two more weak springs are placed in the y direction like so:

![image](https://user-images.githubusercontent.com/7014706/218541454-3cbcff34-93d7-4aa1-ac96-a971d875bdc8.png)

Each variable would have to be checked individually to their own absolute tolerance. This would work okay if the forces were always about the same in a transient simulation, so a single variable specific absolute tolerance would be applicable for all times.

This is where `ReferenceResidualProblem` has been nice: Currently, the user provides `extra_vector_tags` into the kernels of the system to save the contributions of each piece of physics to the residual, hence building the "reference residual" vector. The convergence criteria is then performed in `ReferenceResidualProblem::checkNonlinearConvergence`, which is similar to `FEProblemBase::checkNonlinearConvergence`, albeit the "relative convergence" is defined as the difference between the L2 norms of the reference and residual vectors.

The "reference residual" is typically built by applying `extra_vector_tags` to everything but the boundary conditions. This works well for traditional mechanics problems (like above), but makes it difficult to apply to problems without BCs, e.g. free body expansion or even other physics problems without boundary conditions like rate theory problems. For example, the reference residual would be identical to the actual residual for:

![image](https://user-images.githubusercontent.com/7014706/218542765-24daeb01-d147-4b65-a0e9-578aa1fff3d4.png)

In such a simple case, you could simply exclude one force in each direction to build an appropriate reference residual, but things are not always so simple, for example:

![image](https://user-images.githubusercontent.com/7014706/218565907-12a11f81-bdad-4261-b602-b1c9ca5e3049.png)

@bwspenc suggested another way to build the "reference residual" would be to sum the absolute value of all contributions to the residual at each dof. This would give a rough "order of magnitude" reference residual to compare against agnostic of the problem, forces, etc.

## Design
Probably lots of ways to solve this...

One such way is to create a new "tag" that is the reference residual. This tag acts exactly the same as residual tags, albeit it sums up the absolute value of all dof contributions to the residual.

At the same time, `ReferenceResidualProblem` has diverged from `FEProblem`, and is missing some of the capabilities such as ping pong checking. By wrapping the reference residual check into a virtual object, `ReferenceResidualProblem` could naturally take advantage of these features and not diverge down the line in capabilities.

## Impact
More consistant application of reference residual problem.

**Comment by dschwen** [comment]
Rework?

**Comment by tophmatthews** [comment]
I'll add more details later, just wanted to get @bwspenc (and yours) eyes on this.

**Comment by tophmatthews** [comment]
Alright, am ready for discussion/review on how this is being approached @bwspenc @dschwen . I bet there's a better way to do it, but maybe this gets the process started?

**Comment by tophmatthews** [comment]
Here's one question: If you are comparing the L2 norms across the dof of the reference to the actual residual, won't the reference residual be dominated by an area of heavy action? @bwspenc made a fair point that it will help prevent problem qp's from stopping the simulation, but I fear it might mask non-convergence in areas where major forces aren't happening
