### ISSUE TITLE
SideSetsFromBoundingBoxGenerator new boundary name bug

### ISSUE THREAD

**Issue by pbehne** [idaholab/moose#23466]
## Bug Description
The SideSetsFromBoundingBoxGenerator defines new sidesets using currently-defined sideset IDs inside or outside of a bounding box. Two of the input parameters are "boundaries_old" (vector of BoundaryName), which contains the names of the boundaries from which to generate sidesets, and "boundary_new" (BoundaryName), which will be the name of the newly generated sideset.

The issue is that the SideSetsFromBoundingBoxGenerator does not seem to apply the value of "boundary_new" to the newly generated sideset. Instead, it names the new boundary according to the newly generated boundary id.

## Steps to Reproduce
See following example:

```
[Mesh]
  [gmg]
    type = GeneratedMeshGenerator
    dim = 2
    nx = 5
    ny = 5
  []

  [extra_side]
    type = SideSetsFromBoundingBoxGenerator
    input = 'gmg'
    block_id = 1
    bottom_left = '0.0 0.9 0'
    top_right = '1.0 1.1 0'
    boundaries_old = 'top'
    boundary_new = 'new_top' # New boundary does not have this name
    #boundary_new = 4 # This works, but have to know boundary id to be generated ahead of time
  []

  [2_sides_same]
    type = RenameBoundaryGenerator
    input = 'extra_side'
    old_boundary = 'new_top' # Does not work if "boundary_new" in extra_side is set to "new_top"
    #old_boundary = 4 # Works not matter what "boundary_new" in extra_side is set to
    new_boundary = 'left'
  []
[]

[Outputs]
  exodus = true
[]
```

Running this produces the following error when trying to access 'new_top' in the RenameBoundaryGenerator:

`*** ERROR ***
(Mesh/2_sides_same/old_boundary):
    The following boundaries were requested to be renamed, but do not exist: new_top `

If we visualize the 'extra_side' mesh in Peacock, we see that the new boundary generated is named '4' instead of 'new_top':

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/31858053/219720436-037453c1-02ec-46e2-8341-f5ae3c54495f.png">

## Impact
The impact is that sidesets generated by the SideSetsFromBoundingBoxGenerator are named according to the generated boundary id and not the 'boundary_new' parameter. To use the newly generated sideset, users will need to know in advance what this boundary id is. If the new boundary id and the value of 'boundary_new' do not coincide and the user latter attempts to access the new sideset by the value of 'boundary_new', the program will crash.

**Comment by socratesgorilla** [comment]
The issue comes from the boundary names just being markers that lead to the boundary id, but all the actual mesh logic is done upon the ids. The generator used to process only ids(you can see this in the deprecated params), but now allows the names that lead to the ids instead. If it doesn't find an existing boundary name it simply creates a new boundary id. 

@GiudGiud could you assign, i'll look into this and try to figure out the aliasing
