### ISSUE TITLE
Add user object priorities and multiple UO loops

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#23470]
## Reason
DAG is not here yet, it has been worked on (on and off) for years, I don't know when it will materialize. I have production simulations that have heavy UO interdependence (Side UO depending on an Element UO having executed, and a RayTracing study depending on both having executed). `execute_on` hackery with `TIMESTEP_BEGIN` and `TIMESTEP_END` only works for the simplest dependency cases.

## Design
Add an `execution_priority`  parameter to the UO base class. Make the warehouse aware of it and allow querying for a specific `execution_priority` value. Default this parameter to `0`. Create a list of all unique supplied execution priorities and sort it descending numerically. Iterate over the list and do all the usual compute user objects stuff, but only for the current priority value. By default this will not change behavior and will add very little overhead. If a custom execution priority is selected this could result in multiple loops over the mesh, but that's what's needed to resolve these complex dependencies.

## Impact
Add sorely needed capability.

**Comment by joshuahansel** [comment]
I like the idea of being able to provide more control of execution order. I don't know exactly what the current state of dependency resolution for UOs looks like. If it's possible, I'd probably prefer an approach like done in `FunctionValuePostprocessor` with the `indirect_dependencies` parameter: specifying the dependencies you want and then having MOOSE figure out the execution priority and thus figure out if there need to be multiple loops, etc.

**Comment by dschwen** [comment]
The `indirect_dependencies` approach will be a bit slicker, but also a lot more complicated to implement... I guess. One reason is that dependencies need to be resolved for each execute_on flag independently.

**Comment by joshuahansel** [comment]
What does the situation look like right now? Is it like this: the UOs are in the groups
- elemental
- side
- internal side
- interface
and dependency resolution is performed within each group only, i.e., there are no cross-group dependencies? And those dependency nodes are populated automatically via `getUserObject` and such?

**Comment by dschwen** [comment]
Yeah, pretty much, except you have a single loop for all of the ones you listed and anotehr loop for nodal UOs and then you have ThreadedGeneralUOs and GeneralUOs.

**Comment by dschwen** [comment]
Josh, yes, all of those are currently problems, but the execution order groups will allow the user to work around them. However things are tricky, because some UOs depend on additional stuff to be run, eg. an update of element ranges based on changed subdomains. I'll try to do that update explicitly from the UO.

**Comment by joshuahansel** [comment]
> but the execution order groups will allow the user to work around them

Ok, I was thinking that the `dependencies =` approach would have some deficiencies, which you just confirmed: we'd have to do `dependencies = some_uo:finalize` or something 🤮
