### ISSUE TITLE
Signal handler testing is somewhat brittle.

### ISSUE THREAD

**Issue by socratesgorilla** [idaholab/moose#23545]
## Bug Description
Due to the nature of having to test sending a kill signal from an external process, the current implementation of the testing has failed already on an unrelated merge to `next` . Safeguards/enhancements should be made to prevent this.

## Impact
Prevents merging, so an annoyance with high impact.

**Comment by GiudGiud** [comment]
Tied to #23203

**Comment by lindsayad** [comment]
closing in favor of #24252
