### ISSUE TITLE
Allow the user to specify not (yet) existing subdomain IDs as valid

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#23557]
## Reason
With dynamic subdomain changes needed for AM or element death simulations, we often run into the limitation that the set of valid subdomains is the set of subdomains existing on the initial mesh. However at t=0 no element might be in the deleted subdomain. 

We currently circumvent this by having a free floating element unconnected to the mesh, with the needed subdomain id.

## Design

I propose a new parameter

```
Mesh/add_subdomain_id = 9999
```

that lets the user specify a list of IDs that are assumed to be valid. That will permit the user to set up block restrictions for this yet non-existing subdomain in their inputs.

## Impact
Simplified capability.

Ping @bwspenc

**Comment by GiudGiud** [comment]
We've been going the other way for this, to reduce user input error we have banned more and more ids and names that are not in the initial mesh.

A system to allow pre-declaring future stuff makes a lot of sense though
