### ISSUE TITLE
New Positions system for distributing subsystem calculations and other needs

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#23587]
## Reason
We currently have two ways of specifying positions for multiapps, positions argument in the input file, or positions_file
We now have a new need for specifying positions to a Transfer (nearest node) for some specific but generalizable need (#23585).
It's high time we generalize this for compactness of the inputs

## Design
A Positions block and a number of way of specifying positions defined by the objects
```
[Positions]
  [my_positions]
    type = ...
  []
[]
```
- [x] from the input file (positions = '1 1 1; 1 2 4' ..). (type = InputPositions)
- [x] from the mesh: block centroids (type = MeshSubdomainCentroidPositions), sideset centroids
- [x] (block restricted) element centroids
- [ ] (boundary restricted) nodes
- [x] from a positions file (type = FilePositions)
- [x] from a custom Positions object, for example to handle custom element IDs
- [x] from the MultiApp positions (type = MultiAppPositions, option to use or not the coordinate transforms)
- [x] from the MultiApp mesh centroids (option in MultiApp position to use the centroids instead)
- [ ] regular Cartesian, cylindrical and spherical grids (to do that, it may be smarter to just create an extra mesh, in addition to the main simulation one, and use the other positions objects on that extra mesh)
- [x] from a Reporter (type = ReporterPositions)
- [ ] combining (concatenating, subtracting, distributing one set on the over (P_final_ij = P_pos1_i + P_pos2_j ) several Positions object (type = CompositionPositions)
- [ ] from ray tracing ray current positions (type = RayPositions)
- [ ] from THM components (type = ComponentPositions)
- [ ] from Mesh metadata

## Outstanding questions

Should the distance metrics also lie here too? Eg should we able to just query the "nearest position" or "nearest position index" from this system ?
L2, L_inf, custom?
yes for now, not a parameter yet just L2

Should there be a way to group positions? Instead of having a 1D vector, we would have a 2D, 3D ... etc vector to indicate the groups (for example: assemblies, pins, pellets)
yes

Should there be a way to output the Positions to the mesh (for debugging) ?

Should this be block restricted? Boundary-restricted? Should this be updated on meshChanged() ? Probably yes to both right

Should this be a reporter? We might as well since it would be supported and there's not too much automated output from Reporters.
yes

This is a pretty simple concept / system. We could think of exactly the same thing for BoundingBoxes. Should we be doing that everywhere?
*Answer* : https://github.com/idaholab/moose/issues/23587#issuecomment-1453779457

## Impact
Bigger and better distributed simulations with small compact inputs

@lindsayad @loganharbour @vincentlaboure @pbalest @aprilnovak @friedmud @YaqiWang @snschune 
for comments on the design and the naming. 

Please think about pebbles and pins at first, then the general world of applications

**Comment by friedmud** [comment]
I like it.  Let's not worry about BoundingBoxes until they're needed.

Need to be careful about this kind of thing - too much indirection can make the input file tough to read... but, as we said yesterday, not implementing this system can lead to really long input files (and errors) as well.  It's a trade off.

Are you planning on doing the base system - or are you too underwater and need one of us to get it put up?

**Comment by GiudGiud** [comment]
I can take care of it.
It would just be nice to settle as much details as possible before making it

**Comment by GiudGiud** [comment]
Got feedback from @jortensi and we need an "initial" positions capability. 

Eg start from a file, then let things evolve as we displace the mesh.

**Comment by GiudGiud** [comment]
@pak1sol

**Comment by yukkiezy** [comment]
> @yukkiezy
> 
> my apologies for not tagging you sooner here. It was an oversight on my part

Nice to see the New Positions system. I will follow that. Looking forward to the new features.

**Comment by GiudGiud** [comment]
System has been added with a lot of initial capability. 
Issue can be referenced for additional ones, as needed
