### ISSUE TITLE
MonotoneCubicInterpolation should check that it is provided with enough data points

### ISSUE THREAD

**Issue by smpark7** [idaholab/moose#23622]
## Bug Description
`MonotoneCubicInterpolation` requires at least three data points, but it currently does not check for that. On the other hand, `SplineInterpolationBase` has a check for whether it is provided with at least two data points. The only way to track this down is through gdb.

## Steps to Reproduce
Provide `MonotoneCubicInterpolation` with only one or two data points. 

## Impact
Potential annoyance for users who accidentally provide wrong data.

**Comment by GiudGiud** [comment]
@smpark7 thanks for reporting this. I ll make a patch
