### ISSUE TITLE
Make vector and field variables compatible across an interface when using interface kernels

### ISSUE THREAD

**Issue by Eilloo** [idaholab/moose#23680]
## Reason
In some cases, you might have a vector variable on one side of an interface which interacts with, say three separate field variables representing x, y, and z component on the other. An example is in the FSI module: A number of the INS kernels require fluid velocity to be a vector variable; however, tensor mechanics kernels treat solid velocity, displacement, etc. as separate field variables such as disp_x, disp_y, etc. See discussion [#23658](https://github.com/idaholab/moose/discussions/23658).

## Design
I imagine something along the lines of: 
The user would specify a vector variable on one side, and, say 'neighbourVariable_x', 'neighbourVariable_y', etc. The number of neighbour components should match the dimension of the problem. For 'PenaltyCoupled' interface kernels, the 'primary_coupled_variable' would also be a vector, with corresponding 'secondary_coupled_variable_x', etc.
There might be a neater design than this, but this describes a basic functionality.

## Impact
This might require new interface kernels; however, it would be great if there's a way to update existing kernels to accept different variable types in this way and keep everything in one place!

**Comment by Eilloo** [comment]
@lindsayad, tagging you as per the linked discussion :)

**Comment by lindsayad** [comment]
great, thanks @Eilloo !
