### ISSUE TITLE
Ensure accumulation of the absolute value works for all residual contributions

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#23738]
## Reason
This is a follow up from #23398 and #23399 which works for non AD `Kernel`, but needs to be  extended to `ADKernel`. There are other objects that contribute to the residual that need to be checked as well.

## Design

The math to accumulate the absolute value is via `TaggingInterface::accumulateTaggedLocalResidual`. Anything that calls `computeResidual` should call `accumulateTaggedLocalResidual`. This needs to be verified and tests added.

Here are the objects in the framework:

Needs `accumulateTaggedLocalResidual` and test
- [ ] ADIntegratedBC
- [ ] ADNodalBC
- [ ] ArrayNodalBC
- [ ] NodalBC
- [ ] NodalNormalBC
- [ ] VectorNodalBC
- [ ] ElemElemConstraint
- [ ] NodeElemConstraint
- [ ] NodeFaceConstraint
- [ ] KernelGrad
- [ ] VectorKernel
- [ ] NodalKernel
- [ ] TimeNodalKernel
- [ ] AverageValueConstraint
- [ ] NodalEqualValueConstraint
- [ ] NullScalarKernel

Need tests:
- [ ] ArrayIntegratedBC
- [ ] LowerDIntegratedBC
- [ ] IntegratedBC
- [ ] LowerDIntegratedBC
- [ ] VectorIntegratedBC
- [ ] DiracKernel
- [ ] FVElementalKernel
- [ ] FVFluxKernel
- [ ] ADInterfaceKernel
- [ ] InterfaceKernel
- [ ] ADKernelStabilized
- [ ] ADKernelValue
- [ ] ArrayKernel
- [x] Kernel
- [ ] KernelValue
- [ ] ODEKernel
- [ ] ODETimeKernel
- [x] TimeKernel
- [ ] VectorTimeKernel
- [ ] ADScalarKernel

Things that should be fixed via _assembly.processResiduals
- [ ] MortarScalarBase
- [ ] FVScalarLagrangeMultiplierConstraint
- [ ] ADKernel
- [ ] ADKernelGrad
- [ ] ADKernelScalar
- [ ] ADNodalKernel

Things covered elsewhere:
- [ ] ADMortarScalarBase - via `ADMortarConstraint`
- [ ] MortarConstraintBase - via daughter classes
- [ ] ArrayDGLowerDKernel - via `ArrayDGKernel`
- [ ] DGKernelBase - via daughter classes
- [ ] DGLowerDKernel - via `DGKernel`
- [x] ConservativeAdvection - via Kernel
- [x] KernelScalar - via Kernel
- [x] ADTimeKernel - via ADKernelValue

## Impact
Extends the application of the new `ReferenceResidualProblem` utilization.

**Comment by lindsayad** [comment]
Thanks @tophmatthews!

**Comment by tophmatthews** [comment]
Coverged by #24206
