### ISSUE TITLE
Ouptuts/file_base for a multiapp that has multiple subapps should yell at you

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#23743]
## Bug Description
If we set multiple subapps to write with a file_base, we have them all write to the same file
This doesnt work for people who want one output per subapp

## Steps to Reproduce
Create 2 subapps and use the Outputs/file_base parameter in the subapps

## Impact
User confusion

**Comment by GiudGiud** [comment]
Tied to #24177 
I guess I did not get a crash when I raised this issue

**Comment by joshuahansel** [comment]
I ran into this too. No crash, just very ambiguous sub-app output file.

**Comment by GiudGiud** [comment]
let me try to fix it

**Comment by GiudGiud** [comment]
https://github.com/idaholab/moose/pull/25874 should solve it
