### ISSUE TITLE
Generalize and clean up FV constraints

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#23745]
## Reason

For coupling Navier Stokes module and/or Pronghorn with SAM, the following capability is needed:

1. Couple a postprocessor as value for `phi0` for constaints.
2. Pin face pressure in Navier-Stokes.

## Design

1. Move `phi0` from the child classes to the base class.
2. Make the parameter a postprocessor value.
3. Propagate change to Navier-Stokes action.
4. Add a class that does what `FVIntegralValueConstraint` does but for elements along sidesets. 

## Impact

Will not break anything

**Comment by snschune** [comment]
If your inflow/outflow boundaries don't change, things are fine and you just assign the regular BCs in Pronghorn that get fed by PPs. If your inflow become outflow or vice versa, then you have two options.
1. Switch BCs on the fly.
2. All velocity boundaries.
I'm trying 2., but that leaves pressure undetermined. That's what I want to use the constraint for.

**Comment by GiudGiud** [comment]
This will pin the pressure in the entire loop. I think this helps convergence quite a bit, but nullifies the effect of the pressurizer in the 1d loop on the 2D part of the system.

Might not matter though, it would be good to have all velocity working

**Comment by lindsayad** [comment]
It appears that if you constrain the pressure in an average sense on the outlet boundary, then you can't hold a fully-developed velocity profile (top of the 2D color plot is the outflow boundary where I've added the line plot across the outlet)

![Screenshot from 2023-03-20 16-25-57](https://user-images.githubusercontent.com/10248304/226487276-fd5e2e80-5799-4f28-b91d-2dbe6734201b.png)

**Comment by lindsayad** [comment]
This was with application of the Lagrange multiplier to the primal equation (pressure equation) only on the outlet boundary. I'll try next with what I said I'd do on the phone @snschune, in which I apply the LM uniformly throughout the volumetric domain to the pressure residuals but only add to the constraint equation (LM residuals) on the boundary

**Comment by lindsayad** [comment]
Oopsie I had made a mistake and the flow kernels were not running on the boundary. Much better now

![Screenshot from 2023-03-21 09-29-35](https://user-images.githubusercontent.com/10248304/226676692-336708b7-7bd2-42a3-8ae2-7992fa2ae674.png)
