### ISSUE TITLE
Steady-State detection potentially converging artificially fast with check_aux = true

### ISSUE THREAD

**Issue by lewisgross1296** [idaholab/moose#23840]
## Reason
When running steady-state Cardinal simulations, it is often necessary to include `check_aux = true` since our wrapped sub-apps (OpenMC and Nek) do not add nonlinear variables. If there are other `AuxVariables` included, say for debugging purposes or to compute important auxiliary quantities that may not change much between iterations (e.g. `ProcessorIDAux`), then these will be included in the L2 norm that helps evaluate convergence. Depending on the number of these, the change in L2 norm from variables the user cares about could be dwarfed and consequentially, the simulation _thinks_ it is at steady-state while certain variables are still converging to steady-state.

## Design
The enhancement would allow the user to specify explicitly which variables they'd want to be included in the steady detection. Something along the lines of `aux_to_check = 'temp heat_source'` could be put in the `[Executioner]` block when `check_aux = true` is enabled. It could default to all `AuxVariables` to mimic the existing behavior and keep others from having to change their input files due to this change.

## Impact
This feature will allow users to explicitly specify which variables they'd like to have steady-state detection check. It will also prevent users from thinking their simulation has achieved steady-state when it may not have, in the case they have other `AuxVariables` in their simulation that are not changing much between iterations.

**Comment by lewisgross1296** [comment]
Did a quick read thru of that thread. I'm not entirely whether this is a separate issue or if this is resolved by the changing of the steady-state detection mentioned. If you need some test steady state simulations, the ones I was referring to above are from this [repo](https://github.com/lewisgross1296/1Dslab_multiphysic_analytical_benchmark). Though I might need to update some input syntax, since Cardinal has evolved a bit since then.

**Comment by pbehne** [comment]
I can look into this issue.

**Comment by lindsayad** [comment]
I am going to mark this as closed by #27172. Can reopen if needed
