### ISSUE TITLE
Multiple thermal pairs with mortar gap heat transfer action

### ISSUE THREAD

**Issue by recuero** [idaholab/moose#23869]
## Bug Description
A user wants to leverage the `MortarGapHeatTransfer` action for multiple thermal pairs. An error message prevents the simulation from running:

```
*** ERROR ***
The following error occurred in the object "cap_hat_ModularGapConductanceConstraint", of type "ModularGapConductanceConstraint".The requested UserObject with the name "gap_flux_model_conduction_object_cap_hat_0" was not found.
```
Obviously we shouldn't be creating user objects if we can't pass their proper names to the constraints.

## Steps to Reproduce
Run the mortar gap heat transfer action with multiple thermal pairs employing the same physics (e.g. conduction or radiation).

## Impact
It prevents users from leveraging the automatic setups created by the action.

**Comment by lindsayad** [comment]
> multiple thermal pairs.

What does this mean? Does it mean multiple primary-secondary interfaces?

**Comment by recuero** [comment]
Yeah
