### ISSUE TITLE
Recovery failing in debug mode with parallel mesh

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2390]
Several of the parallel mesh tests when run in debug mode output an error like:

```
utils/random.test_par_mesh: Warning:  This MeshOutput subclass only supports meshes which have been serialized!
utils/random.test_par_mesh: Assertion `(neigh_family_member->neighbor(nn) == this) || (neigh_family_member->neighbor(nn) == remote_elem) || ((this->refinement_flag() == JUST_REFINED) && (this->parent() != NULL) && (neigh_family_member->neighbor(nn) == this->parent()))' failed.
utils/random.test_par_mesh: [src/geom/elem.C, line 1101, compiled Jan 17 2014 at 14:26:14
utils/random.test_par_mesh: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
utils/random.test_par_mesh: Assertion `!(elem->neighbor(n))' failed.
utils/random.test_par_mesh: (1]) src/parallel/parallel_elem.C, line 417, compiled Jan 17 2014 at 14:26:24
utils/random.test_par_mesh: application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

What is interesting is that this is _after_ the first solve after recovery - and only happens upon trying to do serialized output.  I suspect that this is an overzealous assert and that everything is actually ok (the tests pass if this assert is not there).

Therefore - I'm relegating this one to a lesser priority - but it's still something that should get looked at...

**Comment by permcody** [comment]
@roystgnr - might be a duplicate. I think you just fixed this.

**Comment by roystgnr** [comment]
The fixes for these *specific* bugs went in to https://github.com/libMesh/libmesh/pull/1291 and have already been pulled into MOOSE, so I'm closing this ticket.

The fixes for a few *other* recovery with parallel mesh bugs aren't all in yet (most significantly, https://github.com/libMesh/libmesh/pull/1390 is necessary for recovery on a distributed mesh with an h refinement hierarchy, and that won't be in MOOSE until the next libMesh update) but those are covered by #8410.
