### ISSUE TITLE
Solution invalidity reporter issue with mpi/threads

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#23926]
## Bug Description
Solution invalidity reporter appears to have some issues with mpi and/or threads as shown by failure in https://github.com/libMesh/libmesh/pull/3510

## Steps to Reproduce
Failure is stochastic. Thread sanitizer maybe will be able to show something 

## Impact

Mostly an annoyance for CI

**Comment by MengnanLi91** [comment]
@lindsayad Can you assign this to me?

**Comment by lindsayad** [comment]
yep!

**Comment by MengnanLi91** [comment]
Can not reproduce the error. I will get back to it when it shows up in CIVET again

**Comment by lindsayad** [comment]
Ok I found one: https://civet.inl.gov/job/1635235/
