### ISSUE TITLE
MOOSE Docs websites rendering drop-down menus on mobile

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#23930]
# How to reproduce
visit https://mangerij.github.io/ferret/index.html  on your phone. shows the issue on an iphone X

# Impact
Lower user experience. Less micro-working potential

### Discussed in https://github.com/idaholab/moose/discussions/23928

<div type='discussions-op-text'>

<sup>Originally posted by **mangerij** April  1, 2023</sup>
Hello,

Today, I made live Ferret's website https://mangerij.github.io/ferret/index.html and noticed that the drop-down menus do not render correctly (and are not able to be clicked) if one uses a mobile browser. I checked and this seems to be a MOOSE Docs wide issue since both the drop-down menu on the framework's website as well as other MOOSE-based apps (for example Raccoon, https://hugary1995.github.io/raccoon ) also have this issue. It does not seem to be an issue with the browser used on mobile. I checked Chrome, Firefox, and others and all of the drop-down menus cannot be expanded and clicked on. I figure I would just raise this issue - but it would be nice if there was a work-around...
</div>

**Comment by GiudGiud** [comment]
@milljm we changed this recently right? 
It seems to work fine for our site, but not for ferret. The colors are different too?

**Comment by milljm** [comment]
Closing. This issue was fixed in MOOSE at PR: #22922
