### ISSUE TITLE
Create another Conda package for Python pinning

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#23944]
## Reason
Python 3.12 is out, and it would seem Python 3.11 is now default on Conda. When one installs our `moose-libmesh` package without also installing a Python pinning `moose-tools` package, we now get an environment unable to build MOOSE, as described in Discussion: https://github.com/idaholab/moose/discussions/23831 

## Design
Investigate creating yet-another-package that depends on a version of Python we support. There's _gotta_ be a way. I am envisioning a very loose dependency. Something like:

```pre
moose-libmesh --> moose-python
```

Where `moose-python` will only contain `python <3.11` and perhaps `packaging`. This should still allow for combination install of `moose-libmesh` and `moose-tools`.

The reason for "yet another package" is to break away from the pinning that is created when building other packages (like `moose-libmesh`). e.g if we attempted to solve this issue _in_ `moose-libmesh`, we would need to build `moose-libmesh` as many times as we support versions of Python (x4).

We also do not want to force folks to install `moose-tools`. It was never meant as a requirement (but it certainly is becoming one). We might discuss this further. A simple fix would be throw a dependency of `moose-tools` in our `moose-libmesh` package.

## Impact
Folks who _only_ install `moose-libmesh` should be able to build / develop-in MOOSE.

**Comment by milljm** [comment]
I am realizing the anarchy this is going to cause on our versioner.py stuff... Creating something new that libMesh _depends_ on... is not trivial to our CI.

**Comment by cticenhour** [comment]
We should probably spend some time working out why 3.11/3.12 is failing the HIT build. I was intending to remove 3.7 this month as it was EOL and add 3.11.

**Comment by milljm** [comment]
Well regardless we need a away to control Python being instead I think. But yes, what I am finding out is not going to be pretty.
