### ISSUE TITLE
converting window file to run on linux

### ISSUE THREAD

**Issue by engrmessi** [idaholab/moose#23970]
My advisor sent me MOOSE script file to run on MOOSE, I get the following error 
" contains Windows(DOS) line endings which are not supported."
Please how do i fix this error

**Comment by lindsayad** [comment]
Please see https://github.com/idaholab/moose/discussions/22758 and https://github.com/idaholab/moose/discussions/16315. In short, run the `dos2unix` command on your file. If `dos2unix` is not installed, then on Ubuntu you can install it using `sudo apt install dos2unix`
