### ISSUE TITLE
How to tag some specific nodes and name them to add boundary conditions to them

### ISSUE THREAD

**Issue by 09liu** [idaholab/moose#23995]
## Reason
There is such a piece of code in AnnularMeshGenerator.C

  Real current_r = _rmax;
  for (unsigned angle_num = 0; angle_num < num_angular_nodes; ++angle_num)
  {
    const Real angle = _tmin + angle_num * dt;
    const Real x = current_r * std::cos(angle);
    const Real y = current_r * std::sin(angle);
    nodes[node_id] = mesh->add_point(Point(x, y, 0.0), node_id);
    node_id++;
  }

## Design
I would like to make new improvements based on this module. How to tag some specific nodes and name them to add boundary conditions to them in input card. For example, Nodes located near 0, pi/2, pi, 3*pi/2. 

## Impact
Add something new.

**Comment by lindsayad** [comment]
This is more appropriate for a Discussions post. You can use the `ExtraNodesetGenerator` to create new nodesets based on given node IDs or node coordinates

**Comment by 09liu** [comment]
> This is more appropriate for a Discussions post. You can use the to create new nodesets based on given node IDs or node coordinates`ExtraNodesetGenerator`

Thank you. I tried it and later found that this way can achieve the function I want.
    Real current_r = iclad_ri;
    // add nodes at rmax that aren't yet connected to any elements
    for (unsigned angle_num = 0; angle_num < num_angular_nodes; ++angle_num)
    {
      const Real angle = angle_num * dt;
      const Real x = current_r * std::cos(angle);
      const Real y = current_r * std::sin(angle);
      nodes1[node_id1] = mesh->add_point(Point(x, y, 0.0), node_id1);
      if (std::abs(angle) < 1e-8)
        boundary_info.add_node(node_id1, 1);
        boundary_info.nodeset_name(1) = "right";
      if (std::abs(angle - pi / 2.0) < 1e-8)
        boundary_info.add_node(node_id1, 2);
        boundary_info.nodeset_name(2) = "top";
      if (std::abs(angle - pi) < 1e-8)
        boundary_info.add_node(node_id1, 3);
        boundary_info.nodeset_name(3) = "left";
      if (std::abs(angle - 3.0 * pi / 2.0) < 1e-8)
        boundary_info.add_node(node_id1, 4);
        boundary_info.nodeset_name(4) = "bottom";
      node_id1++;
    }

**Comment by lindsayad** [comment]
So is your question resolved?

**Comment by 09liu** [comment]
> So is your question resolved?

Yes, I added these four specific nodes to the boundary successsfully.
