### ISSUE TITLE
`RenameBoundaryGenerator` fails for a distributed mesh problem

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#24068]
## Bug Description
Using `RenameBoundaryGenerator` in combination with `GeneratedMeshGenerator` when a nonzero `boundary_id_offset` is used, in a distributed mesh, results in a boundary-does-not-exist error (see below).

## Steps to Reproduce
Run the attached input file with 2 processors and `--distributed-mesh`: 
[rename_boundary_failure.txt](https://github.com/idaholab/moose/files/11233477/rename_boundary_failure.txt)
and observe the error
```
The following boundaries were requested to be renamed, but do not exist: left right bottom top 
```

## Impact
This prevents some users from using mesh generators if they need a distributed mesh.

**Comment by joshuahansel** [comment]
At this point, I believe that the following from `GeneratedMeshGenerator` to be to blame:
```
  // Copy, since we're modifying the container mid-iteration
  const auto mesh_boundary_ids = boundary_info.get_boundary_ids();
  for (auto rit = mesh_boundary_ids.rbegin(); rit != mesh_boundary_ids.rend(); ++rit)
  {
    const std::string old_sideset_name = boundary_info.sideset_name(*rit);
    const std::string old_nodeset_name = boundary_info.nodeset_name(*rit);

    MeshTools::Modification::change_boundary_id(*mesh, *rit, *rit + _boundary_id_offset);

    boundary_info.sideset_name(*rit + _boundary_id_offset) =
        _boundary_name_prefix + old_sideset_name;
    boundary_info.nodeset_name(*rit + _boundary_id_offset) =
        _boundary_name_prefix + old_nodeset_name;
  }
```
This appears to be where the boundary ID gets offset, but I don't think it's doing it quite right.

Processor is getting the old, not offset, boundary IDs for the given name. Ultimately this gets called:
```
boundary_id_type BoundaryInfo::get_id_by_name(std::string_view name) const
{
  // Search sidesets
  for (const auto & [ss_id, ss_name] : _ss_id_to_name)
    if (ss_name == name)
      return ss_id;

  // Search nodesets
  for (const auto & [ns_id, ns_name] : _ns_id_to_name)
    if (ns_name == name)
      return ns_id;

  // Search edgesets
  for (const auto & [es_id, es_name] : _es_id_to_name)
    if (es_name == name)
      return es_id;

  // If we made it here without returning, we don't have a sideset,
  // nodeset, or edgeset by the requested name, so return invalid_id
  return invalid_id;
}
```
so I think maybe these maps `_ss_id_to_name`, `_ns_id_to_name`, and `_es_id_to_name` aren't getting updated properly in `GeneratedMeshGenerator`? @roystgnr Maybe we need to use `BoundaryInfo::renumber_id` in `GeneratedMeshGenerator`?

**Comment by roystgnr** [comment]
I don't yet understand this, but I can reproduce it.  Let me get in there with the debugger.

**Comment by roystgnr** [comment]
Ah.  I'm starting to understand this.  Processor 1 owns 0 elements, with 0 boundaries.  Anything trying to update ids-to-names by iterating through boundary ids and working on their associated names is going to be disappointed when there are no ids to iterate through.  We need to be iterating through `get_global_boundary_ids()` output instead.

**Comment by roystgnr** [comment]
What the hell is test/tests/meshgenerators/generated_mesh_generator/tests doing, with `mesh_mode = 'REPLICATED'` on nearly every test?  I was about to add a new test case, but let's see if one of the existing ones would have covered this...

**Comment by roystgnr** [comment]
Yup.  If I undo the fix I get `meshgenerators/generated_mesh_generator.offset` and `meshgenerators/generated_mesh_generator.prefix/id` to fail assertions, and I don't even have a full list of failures because `meshgenerators/generated_mesh_generator.both/id` is outright hanging.

Not sure how I missed this when I went through making stuff distributed-compatible years and years ago.
