### ISSUE TITLE
More Component abstraction

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24103]
## Reason
- [ ] Create a components module that has nothing to do with physics
- [ ] Make sure that all `thermal_hydraulics` module and SAM components can use the component basics in the new module

## Design
We will know the design is successful if there is no more need for `SAMComponent`, `AddSAMComponentAction`, and `SAMSimulation`

## Impact
A component system that we know is very generic

**Comment by GiudGiud** [comment]
Components could hold metadata, much like mesh generators do right now. 
In fact components could be able to use MGs to create their own meshes

**Comment by joshuahansel** [comment]
Extracting the components system into its own module only makes sense to me if we intend to use the components system for non-TH applications as well.

**Comment by GiudGiud** [comment]
I will try to pitch this to Reactor & Griffin team next time we meet. I think it's a great idea.

**Comment by lindsayad** [comment]
@joshuahansel sometimes you have to build it and then they will come

**Comment by joshuahansel** [comment]
To start off some discussion, what's the advantage of some app like Griffin using components?

**Comment by GiudGiud** [comment]
For shielding, it would be good to have a bunch of discontinuous meshes because that's all that s needed. They could be tied to components. That way you do not need to remesh the whole thing when you change one part. 

For transfers as well, keeping the data local to a component makes sure we dont send data that s unrelated

**Comment by joshuahansel** [comment]
Agreed, I think that any time where you have multiple physical pieces in your domain, components make a lot of sense.

**Comment by joshuahansel** [comment]
Closing because I think the Physics/ActionComponents systems fill this role.
