### ISSUE TITLE
Convergence diagnostics in Executioner / Convergence criteria system

### ISSUE THREAD

**Issue by oanaoana** [idaholab/moose#24128]
## Reason

The user may wish to check the numerical reliability of the computations by monitoring certain standard metrics, such as convergence of various quantities.

## Design

As proposed by @joshuahansel the Executioner block should contain a `[Convergence]` block with subtypes of convergence criteria the user demands, for example:

- MMS
- grid convergence (uniform & non-uniform)
- control / parameter-based criteria

With looking at convergence based on:

- nonlinear / linear  residual
- postprocessor or VPP value
- weighted nonlinear residuals (with / without scaling, using the sum of the absolute residuals as the scaling factor)
- true residual

## Impact
Enhance reliability and user confidence
Provide additional diagnostic and monitoring capabilities.
Facilitate debugging

**Comment by GiudGiud** [comment]
#21600 should be considered when working on this. We should stop setting these criteria in stone at the beginning of the simulation

**Comment by joshuahansel** [comment]
Addressed in #28848
