### ISSUE TITLE
NavierStokesFV requires initialize_variables_from_mesh_file=true to properly restart from checkpoint

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#24144]
## Bug Description

NavierStokesFV requires `initialize_variables_from_mesh_file=true` to properly restart from checkpoint but the docstring for that parameter mentions that it is only for Exodus format.

In addition, the user may not be aware of that parameter so it would be best to set that parameter automatically to true when restart is detected.

## Steps to Reproduce

See [here](https://github.com/idaholab/moose/compare/next...vincentlaboure:moose:nv_cp_restart) to reproduce.

## Impact

At a minimum, this is not user friendly. 

Tag @lindsayad

**Comment by lindsayad** [comment]
thanks for the report. Will look at it soon!
