### ISSUE TITLE
ChromiumOxidation is not registered object

### ISSUE THREAD

**Issue by haqfariha** [idaholab/moose#24143]
I am new user and gonna work in oxidation mechanism in moose environment. I tried the example there but getting this error messege. How can I register this kernel?

**Comment by lindsayad** [comment]
This would be more appropriate for a Discussions post. What example are you referring to? Do you have a URL?

**Comment by haqfariha** [comment]
Thank you. I will post my problem in the discussion forum. The in-built test problem my trying is-
https://mooseframework.inl.gov/bison/source/materials/ChromiumOxidation.html#chromiumoxidation

**Comment by lindsayad** [comment]
Discussion has moved to https://github.com/idaholab/moose/discussions/24149
