### ISSUE TITLE
Add augmented Lagrange method for penalty mortar contact

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#24168]
## Reason
Augmented Lagrangian permits tight enforcement for constraints without the condition number of the system blowing up. We use it successfully in Node on Face and would like to have the capability available for Mortar contact as well.

## Design
The existing `AugmentedLagrangianContactProblem` class will be extended to also iterate over UserObjects derived from `PenaltyWeightedGapUserObject` and `PenaltyFrictionUserObject`. We might want to add a common interface class that specifies a function to check for AL convergence (penetration depth vs. a user specified tolerance) and a method to trigger a multiplier update.

## Impact
Added capability.

**Comment by lindsayad** [comment]
@dschwen is this done?

**Comment by lindsayad** [comment]
I believe this has been completed in https://github.com/idaholab/moose/pull/24349. Can reopen if not
