### ISSUE TITLE
Adding additional metadata to represent a fully heterogeneous fast reactor core with RGMB mesh generators 

### ISSUE THREAD

**Issue by shikhar413** [idaholab/moose#24198]
## Reason

A activity that is underway within Griffin is to streamline the cross section generation procedure for fast reactors with MCC-3 and Griffin. Typically, this requires a heterogeneous hexagonal full-core mesh to be defined by the user, and the eventual goal is to represent this geometry in a number of equivalent geometries such as an R-Z core configuration, a duct heterogeneous configuration, or an assembly homogenized configuration, with minimal user intervention for use with MCC-3 or Griffin in any intermediate calculations. In order to accomplish this task, RGMB mesh generators are currently being looked at as the tool to represent the fully heterogeneous mesh, with the eventual goal of storing metadata on the mesh that can be used to construct any equivalent geometry that requires some sort of homogenization procedure. 

## Design

While RGMB does already define some metadata on the mesh, this data is used purely for the generation of the full-core mesh, and is not sufficient to "reconstruct" or "represent" the fully heterogeneous mesh purely from mesh metdata. Instead, the following metadata is proposed to be added to RGMB. 

*At the core-level:*
core_assembly_types: Asembly_type_ids of each assembly within the core
core_lattice: lattice configuration of assemblies
core_peripheral_ring_radii: Radii of all peripheral ring locations
core_peripheral_ring_region_ids: Region IDs of all peripheral ring locations

*At the assembly-level*
assembly_pitch: Pitch of assembly
assembly_n_ rings: Number of rings in pin lattice
assembly_input_pins: pin_type_ids of pin for each ring (Here, a single pin type is assumed for each ring in the pin lattice)
assembly_background_region_id: Region ID of assembly background
assembly_duct_halfpitches: Half pitches designating location of assembly duct regions (Optional)
assembly_duct_region_ids: Region IDs associated with assembly duct region (Optional)
Note: each assembly quantity label would also be tagged with its type ID, i.e. if the assembly had type_id of 1, then the metadata label names would be "assembly_1_pitch", "assembly_1_n_rings", etc.

*At the pin-level*
pin_pitch: Pitch of pincell region
pin_ring_radii: Radii of each pin ring
pin_ring_region_ids: Region IDs of each radial ring within the pin cell region
pin_background_region_id: Region ID associated with pin background region
pin_duct_halfpitches: Half pitches designating location of pin duct regions (Optional)
pin_duct_region_ids: Region IDs associated with pin duct region (Optional)
Note: each pin quantity label would also be tagged with its type ID, i.e. if the pin had type_id of 1, then the metadata label names would be "pin_1_pitch", "pin_1_ring_radii", etc.

We could add a flag to ReactorMeshParams to define this additional metadata for instances where users don’t want this additional data to be defined on the mesh. With this metadata defined and propagated through the mesh generation stage, theoretically Griffin or whatever analysis tool will be able to “represent” the fully heterogeneous mesh even if the current mesh generator has some homogenized configuration.

While initially there was some discussion about creating a new set of mesh generators in Griffin that would inherit the RGMB mesh generators to accomplish this task, the Griffin team decided it makes sense to add this capability directly to the core RGMB mesh generators, so that it would be available for any application (not just Griffin), to get core-related geometry information directly from the mesh metadata.

## Impact

Shouldn't disrupt the core functionality of RGMB mesh generators, just defining more metadata onto the mesh.

Tagging @jortensi @YaqiWang @eshemon @GiudGiud @pak1sol @yjung-anl for input

**Comment by GiudGiud** [comment]
From the NEAMS-TH side we are thinking of generalizing the Components system, originally developed for THM/SAM but from which the physics has been abstracted away, to be able to:
- store meta data
- use mesh generators
- select physics to turn on
- create non linear systems to solve these physics

so this could be an alternative to storing all this meta data on the mesh. The significant advantage is that there can be several different component each holding their data, instead of a single mesh unifying all the data held, with data getters that traverse trees of MGs looking for metadata.
However this is not in the same state of readiness as mesh metadata. And it's not exclusive to this work, if the data is defined on the mesh it could easily be moved onto a Component.

**Comment by shikhar413** [comment]
Thanks for the background on the Components effort @GiudGiud. Sounds like we can proceed with defining additional metadata on the mesh for now and migrate the functionality to Components system once it’s in a more mature state?

**Comment by eshemon** [comment]
Could this metadata also be used for MC mesh generation, e.g. Shift? Trying to find Kalin's username on github and failing... can anyone tag her?

**Comment by GiudGiud** [comment]
> Thanks for the background on the Components effort @GiudGiud. Sounds like we can proceed with defining additional metadata on the mesh for now and migrate the functionality to Components system once it’s in a more mature state?

Either that or take over! Depends on your horizon there.

**Comment by GiudGiud** [comment]
@kkiesling

**Comment by shikhar413** [comment]
Yeah I was thinking about it and I actually think it could. The above metadata should define all the surfaces needed to build the MC geometry as well, though @kkiesling can confirm

**Comment by kkiesling** [comment]
> geometry

Yes! All this metadata would be _perfect_ for building an MC geometry. I can't think at the moment of any piece of data missing that would be necessary. I think this captures all the surfaces.

**Comment by tarapandya** [comment]
@jessmatt

**Comment by tarapandya** [comment]
@tarapandya

**Comment by shikhar413** [comment]
As per the discussion with @GiudGiud @kkiesling and @loganharbour, the idea of prefixing the metadata with the level (pin, assembly, core) and type id is being nixed, and metadata will only be defined at the level at which is defined and will not be propagated up to the level of the final mesh generator. The implication of this is that the user will now be responsible for querying the metadata at the appropriate level and will have to traversing through mesh generator names to find the metadata names defined at that scope.

Also, many of these metadata listed here have dual purposes - one for actually building the reactor geometry and one for representing the full-core reactor geometry exclusively through metadata. Since we are removing the prefix to distinguish metadata that serves the latter purpose, the line between these two purposes will be blurred and I am proposing we build all of these metadata with RGMB all the time, instead of having a trigger with `generate_rgmb_metadata` in `ReactorMeshParams`, since there aren't very many additional metadata that are used only for the second purpose and not the first.

* At the core-level, the following metadata will be available:
  * input_assembly_names:
  * assembly_lattice
  * peripheral_ring_radius
  * peripheral_ring_region_id

* At the assembly-level, the following metadata will be available (this includes assemblies defined using `AssemblyMeshGenerator` and single pin assemblies defined with `PinMeshGenerator` and setting `PinMeshGenerator/use_as_assembly` as true)
  * assembly_type
  * pitch
  * is_homogenized
  * single_pin_as_assembly
  * background_region_id
  * duct_halfpitches
  * duct_region_ids
  * If single_pin_as_assembly is true, the following metadata will also be available
    * ring_radii
    * ring_region_ids
  * If single_pin_as_assembly is false, the following metadata will instead be defined
    * input_pin_names
    * pin_lattice

* At the pin-level, the following metadata will be available (applies to meshes defined with `PinMeshGenerator` and setting `PinMeshGenerator/use_as_assembly` to false
  * pin_type
  * pitch
  * ring_radii
  * ring_region_ids
  * background_region_id
  * duct_halfpitches
  * duct_region_ids
