### ISSUE TITLE
auxkernels/element_var.test failing occasionally threaded

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#2420]
I can get auxkernels/element_var.test to fail with --n-threads=7 about 1 or 10 runs. I also saw it with --n-threads=3.

A bit of the Exodiff:

auxkernels/element_var.test: Global variables:
auxkernels/element_var.test: Nodal variables:
auxkernels/element_var.test: Element variables:
auxkernels/element_var.test:   --------- Time step 5, 4.0000000e-02 ~ 4.0000000e-02, rel diff:  0.00000e+00 ---------
auxkernels/element_var.test: Global variables:
auxkernels/element_var.test: Nodal variables:
auxkernels/element_var.test: Element variables:
auxkernels/element_var.test:   --------- Time step 6, 5.0000000e-02 ~ 5.0000000e-02, rel diff:  0.00000e+00 ---------
auxkernels/element_var.test: Global variables:
auxkernels/element_var.test: Nodal variables:
auxkernels/element_var.test: Element variables:
auxkernels/element_var.test:   --------- Time step 7, 6.0000000e-02 ~ 6.0000000e-02, rel diff:  0.00000e+00 ---------
auxkernels/element_var.test: Global variables:
auxkernels/element_var.test:    elem_56      rel diff:  4.1497038e-01 ~  1.1369144e-01 = 7.26025e-01 (FAILED)
auxkernels/element_var.test: Nodal variables:
auxkernels/element_var.test: Element variables:

**Comment by permcody** [comment]
Closing - Moving issues regarding sporadic threaded fails to #6436.
