### ISSUE TITLE
Check for split status when executing mesh generators could crash

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#24219]
## Bug Description
The `_mesh.isSplit()` check in `ExecuteMeshGenerators` added in https://github.com/idaholab/moose/pull/24033 could crash when `_mesh` is not set.

## Steps to Reproduce
Run moose test with the following:

```
some_blocks = 'a
               b'

[Postprocessors]
  [monolith_temp_avg]
    type = ElementAverageValue
    variable = temp
    block = ${some_blocks}
  []
[]
```

## Impact
Will not report a useful error.

**Comment by lindsayad** [comment]
@ttruster (and @roystgnr) from #24140 we should check `isSplit()` in the periodic BC action ... and probably for some other physics as well
