### ISSUE TITLE
Build block-block connectivity when the mesh is constructed

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#2424]
So that we can check if two blocks are connected through SIDEs. We can use the existing CSR (compresed sparse row) format to store the connectivity. Then the user can easily check if two blocks are connected by calling something like:
`bool isConnected(SubdomainID block1, SubdomainID block2) const;`

Thanks.

**Comment by YaqiWang** [comment]
On top of this, we can build block-sideset connectivity, i.e. `std::map<BlockID, std::vector<BoundaryID> >` and `std::map<BoundaryID, std::vector<BlockID> >`. If you think this is good, I can work on this. Once this is in place, we can remove some of the code in Yak.

**Comment by friedmud** [comment]
Seems like a good idea.

**Comment by YaqiWang** [comment]
We have this `MooseMesh::getBlockConnectedBlocks` and `MooseMesh::getSubdomainInterfaceBoundaryIds`. So this issue can be closed.
