### ISSUE TITLE
FD: finite-difference Jacobian calculation at the kernel-element level.

### ISSUE THREAD

**Issue by karpeev** [idaholab/moose#2426]
Develop a capability to compute a finite-difference-based Jacobian solely from the residual statements in kernels. For each kernel each element residual will be difference to produce an approximate element Jacobian, which is then accumulated into the global Jacobian as usual.  FDKernel is the proposed base class for all such kernels.  

This will, among other things, help the development of the 7-equation model in RELAP-7.

**Comment by friedmud** [comment]
This basic functionality was merged years ago - but is very limited.  I don't think we need to go any further than that though.
