### ISSUE TITLE
Add integral post processing and spatial field postprocessimg (aux) for advection fluxes

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#24289]
## Reason
We have postprocessors for a general basic version of the diffusive flux. 
we could use the same for a general version of the adjective (carried by a velocity field) flux 

## Design
A boundary integral postprocessor called SideAdvectiveFlux
An auxkernel calls AdvectiveFluxAux

## Impact
More base capability for “first draft” like simulations.
Obviously any specialized simulation with a custom numerical field will need to adjust the scheme to compute either the adverting field or the advected quantity in the specific manner of the simulation of interest

**Comment by MengnanLi91** [comment]
@GiudGiud Can you assign this to me?

**Comment by GiudGiud** [comment]
This has been started already on a discussion thread lemme link to it

**Comment by GiudGiud** [comment]
See the code they posted
It does most of the work, except for the documentation and some error checking

https://github.com/idaholab/moose/discussions/24132

**Comment by MengnanLi91** [comment]
So the goal here is to add a general version of the adjective (carried by a velocity field) flux in the framework?  In the discussion, the user seems add a 1D AdvectiveFluxAux kernel and fix his problem

**Comment by GiudGiud** [comment]
Should have been more than 1D but yes we want general

**Comment by grmnptr** [comment]
Hello! This is an interesting issue! Can we even output fields on surfaces? The flux is a surface quantity as far as I know.

**Comment by GiudGiud** [comment]
Not currently!
There's volumetric fluxes too, especially in FE

**Comment by grmnptr** [comment]
The solution they proposed only works for continuous FE where the solution is continuous on the sides. That way computing the nodal values will give you the right velocity solution over the face but you will have issues deciding what normal to use at a node. In general I would not recommend outputting the flux as a volumetric quantity and then interpolating it onto faces using Paraview. Also this would not work for FV. The proper solution for this would include the introduction of surface fields in MOOSE. I might be missing something though.

**Comment by GiudGiud** [comment]
I think returning the surface flux at the element centroid would be fine. You will just have to sum all the contributions.
For FV it s pretty well defined.

_normals[_qp] is already the face normal

**Comment by grmnptr** [comment]
Oh you want to create the whole integral( div(u advected_quantity)) term at the centroid?

**Comment by grmnptr** [comment]
Or average the face contributions to the cell center?

**Comment by lindsayad** [comment]
> surface fields in MOOSE

We have face variables through @roystgnr's recent work

**Comment by MengnanLi91** [comment]
> > surface fields in MOOSE
> 
> We have face variables through @roystgnr's recent work

Has it been merged?

**Comment by lindsayad** [comment]
Oh yea it's been around for at least a year I think

**Comment by grmnptr** [comment]
Could you link the PR here, please?

**Comment by lindsayad** [comment]
https://github.com/idaholab/moose/pull/20249 and https://github.com/idaholab/moose/pull/22324 are good ones

**Comment by roystgnr** [comment]
Bear in mind that we don't have any way to restrict face variables to sidesets, the way we can restrict volume variables to subdomains.  If you add a face variable, you get a value on every face of every element in the subdomains on which it's defined.  This is exactly what DPG and other interelement-flux-related discretizations want, but for fluxes that only live on a domain boundary our only option is still to construct lower dimensional elements on that boundary.

**Comment by GiudGiud** [comment]
@MengnanLi91 make sure to leverage the functor system for this btw.
It will enable a lot of flexibility in what is advecting and what is advected
