### ISSUE TITLE
Always use undisplaced reference points for neighbor reinit for displaced interface kernels

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24301]
## Reason
1. We've already done the hard work of inverting the physical element face points to create the neighbor face reference points. We don't need to do the work twice
2. For czm simulations the physical element face points won't even lie on the neighbor face so the inversion will fail

## Design
always use undisplaced reference points

## Impact
Much increased robustness for CZM simulations and slightly improved performance

**Comment by lindsayad** [comment]
@jiangwen84 I've created this for your issue

**Comment by jiangwen84** [comment]
> @jiangwen84 I've created this for your issue

thanks.
