### ISSUE TITLE
`std::vector<RealVectorValue>` input parameters are not retrieved correctly

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#24337]
## Bug Description
Input parameters of type `std::vector<RealVectorValue>` are not parsed/retrieved correctly. `std::vector<Point>`, however, works as expected.

## Steps to Reproduce
For example, if a user supplies their param as
```
myparam = '5 6 7'
```
then in the code, `getParam<std::vector<RealVectorValue>>("myparam")` gives the following result: {(5,0,0), (6,0,0), (7,0,0)} instead of the expected {(5,6,7)}.

## Impact
Incorrect results, but there is a workaround by using `std::vector<Point>` instead since there is an implicit conversion between `Point` and `RealVectorValue`.

**Comment by grmnptr** [comment]
I haven't forgotten this! Will do, thanks!
