### ISSUE TITLE
Make residual and jacobian together the default when running NSFVAction simulations

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24352]
## Reason
In the cases I've tried below, `residual_and_jacobian_together = true` is faster which makes sense since we do AD even for our residual evaluations
- mixing length
- steady channel flow
- transient channel flow

## Design
Set the executioner option through the action

## Impact
Speed up NSFVAction simulations

**Comment by lindsayad** [comment]
FYI @GiudGiud @grmnptr @snschune @tanoret @oanaoana

**Comment by grmnptr** [comment]
Cool, what was the experienced speedup?

**Comment by lindsayad** [comment]
Doing the channel flow transient:

Separate sim:
- `NonlinearSystemBase::computeResidualInternal`: 7.32s
- `NonlinearSystemBase::computeJacobianInternal`: 6.16s
- Sum: 13.48s

Together sim:
- `NonlinearSystemBase::computeResidualAndJacobianInternal`: 9.32s

So a 31% speedup in the assembly time in this case

**Comment by grmnptr** [comment]
That pretty cool!

**Comment by oanaoana** [comment]
Just to be sure, is the intention to make `residual_and_jacobian_together = true` default in NS applications? As is it seems that adding the option in the executioner block in the .i file already yields some speedup.

**Comment by lindsayad** [comment]
Yes. We want to make that the default so that if users don't specify that option in the `Executioner` block, then under the hood we will still compute the residual and Jacobian together for NS
