### ISSUE TITLE
Inconsistent handling for optional input parameters without a default value

### ISSUE THREAD

**Issue by lingzou** [idaholab/moose#24455]
## Reason

In MOOSE, an optional input parameter could be provided without default values, e.g.,

`params.addParam<Real>("dummy_real", "a dummy real number");`

When handling such an input parameter, it is typical to check if it is valid before accessing it, e.g., the following to avoid runtime error:

`_dummy_real(isParamValid("dummy_real")` <- Wrong, runtime error: The parameter "dummy_real" is being retrieved before being set.

The correct example is:
`_dummy_real(isParamValid("dummy_real") ? getParam<Real>("dummy_real") : 0.0)`

However, if the input parameter is a std::vector, e.g., 
```
params.addParam<std::vector<unsigned int>>("dummy_vec", "dummy_vec");
_dummy_vec(getParam<std::vector<unsigned int>>("dummy_vec"))
```
MOOSE won't send out a runtime error, but of course, `_dummy_vec` is an empty vector. This is inconsistent with the first case. This probably should not be categorized as a bug, would still be nice to make things consistent.

## Design

For the second case described above for std::vector input parameter, if no default value provided, should be handled the same way as other cases such as a real number.

## Impact

Inconsistent code design; causing confusion in module/application development.

**Comment by MengnanLi91** [comment]
@GiudGiud @lindsayad @friedmud @dschwen @permcody @loganharbour I added a runtime error for empty vector check in my PR #25245 but it breaks tons of test cases because of the new error messages. Any suggestions on how to fix those failed tests? I can simply add a default value. Or treat them differently based on objects? @loganharbour suggests to start a discussion on this issue.

**Comment by loganharbour** [comment]
For context - if you add a parameter for anything _but_ a `std::vector` without a value and call `getParam` on it, you will get a "retrieved before being set" error. We did this on purpose - but why? It's not consistent

**Comment by GiudGiud** [comment]
I think adding a default is fine where it makes sense, and for others you ll want to fix the broken logic
Hit up the respective SMEs if in doubt. Or git blame to find someone

This "retrieved before being set" is the right behavior

**Comment by loganharbour** [comment]
> This "retrieved before being set" is the right behavior

I would agree with you, but clearly someone else didn't:

https://github.com/idaholab/moose/blob/4745680f95115b9006f77d2d5244a0dcaf7eb9ca/framework/include/utils/InputParameters.h#L746

And that's the important conversation here

**Comment by GiudGiud** [comment]
@permcody did you do this and why

**Comment by permcody** [comment]
I can't recall of a specific reason for this other than making an assumption that an empty vector was harmless... I'm supportive of making the behavior consistent.

**Comment by dschwen** [comment]
We are relying on this behavior heavily (as the failing tests show). I'm fine with changing it, as long as fixes for all apps are part of the "service package" ;-)
