### ISSUE TITLE
Make ALE melt pool simulations run

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24462]
## Reason
Users would like to be able to reproduce the ALE simulations in our MOOSE gallery

## Design
Update to new MOOSE objects and work on solver options

## Impact
Demonstrate capability for users

**Comment by lindsayad** [comment]
@cticenhour I'm actually going to migrate pretty much all the laser welding capability upstream, so I've transferred this issue. As a side effect this will still improve malamute coverage

**Comment by cticenhour** [comment]
That sounds good. If necessary, let me know where I can assist.
