### ISSUE TITLE
Need a way to differentiate between "Transient" executioners and "Power Method" executioners

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2452]
Right now we are using a single flag in Problem called transient which is being used for both types. This causes issues when an error or condition needs to be checked against one or the other. See

yak/src/common/materials/Adjoint_FsrcMaterial.C

@YaqiWang

**Comment by permcody** [comment]
This issue has been solved through the introduction of a new intermediate base class called `EigenExecutionerBase` and derived types.
