### ISSUE TITLE
See how large a problem we can solve with NS using field split

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24548]
## Reason
We have HPC people who are wanting to see if they can use NS (Pronghorn) to solve a problem with 70 million cells. The mesh is complex. To start we will see how big a simple channel problem we can solve using field split.

## Design
Take a 3D channel and see how big we can go.

## Impact
Test what we're capable of doing in NS

**Comment by lindsayad** [comment]
Note-taking on a medium sized 3D channel flow problem to anticipate what FSP options to use for the big kahuna

| Re | dofs | cpu | factorization type | schur precondition | solve time |
| ---| --- | --- | --- | --- | --- |
| 1 |  655360 | 32 | full | a11 | 50.525  |
| 1 |  655360 | 32 | lower | a11 |  39.341 |
| 1 |  655360 | 32 | upper | a11 |  37.435 |
| 1 |  655360 | 32 | diag | a11 |  66.413 |
| 1 |  655360 | 32 | full | selfp | 47.303 |
| 1 |  655360 | 32 | lower | selfp | 37.095 |
| 1 |  655360 | 32 | upper | selfp | 35.902 |
| 1 |  655360 | 32 | diag | selfp | 61.088 |

Conclusions:

- `selfp` performs slightly better than `a11` for all factorization types
- `lower` and `upper` factorizations perform better than `full` which performs better than `diag`. `upper` seems to have a slight edge on `lower`

**Comment by lindsayad** [comment]
I want to investigate whether we are solving a symmetric form with respect to A01 and A10 and if not, then whether switching to a symmetric form improves convergence

**Comment by lindsayad** [comment]
My general experience:
- Jacobi for the Schur takes more iterations than something like ASM+(I)LU but it is less expensive so it often wins
- Apparently boomeramg works better on high Re problems when L is large compared to ASM+(I)LU but ASM+(I)LU works better on high Re problems for small mu

**Comment by grmnptr** [comment]
How many nonlinear iterations did it take to solve your problem (asking to compare with SIMPLE which needs 400 to solve a problem with similar size)?

**Comment by lindsayad** [comment]
I don't remember exactly. Somewhere between 3 and 6 although the 248 second solve reporting was with a problem with Reynolds ~1.

**Comment by lindsayad** [comment]
With identical solve options with Q2Q1 taylor-hood elements with 5768003 dofs, with Re=1 and distributed mesh, the solve time is 170.904s. The appreciable difference between Q2Q1 performance and the hybrid CG-DG performance is due to the time in A block solves. hypre boomeramg was taking about 3-4 iterations for Q2Q1 and ~10 iterations with hybrid CG-DG

**Comment by lindsayad** [comment]
Copying from slack notes: according to @grmnptr OpenFOAM solves a 3 million dof problem in 273 seconds on a single process

**Comment by lindsayad** [comment]
Solving Q2Q1 with Re=1 with 3 million dofs with a single process gives a solve time of 742 seconds, so a factor of 2.7 slower

**Comment by lindsayad** [comment]
I do not know the setup of the OpenFOAM case 
- was it channel flow or a cavity or something else?
- were the trivial initial guesses used?
- was GPU acceleration used for the OpenFOAM case? (probably not)
- etc.
so likely we are not at an apples to apples comparison

**Comment by lindsayad** [comment]
Using Q2Q1 elements, I was able to solve a 70 million dof problem (70,034,582 to be exact; n=2789 elements, 2 dimensions) using 3,504 procs on sawtooth in 278.778 seconds with Re=1. Reading the title post again, the prospective users wanted to do 70 million *cells*, so assuming that's 3D, that would be 280 million dofs. Time to request another interactive session!

**Comment by lindsayad** [comment]
Going up to 280 million dofs on sawtooth I got crashes and messages possibly related to MPI. I am not too motivated at the moment to dig into that. So at the moment, my record is 70 million. I don't really see this as a MOOSE *issue* at the moment, so I'm closing. We can always re-open if someone wants to
