### ISSUE TITLE
Need explicit template instantiation for StrainEnergyDensityTempl 

### ISSUE THREAD

**Issue by maxnezdyur** [idaholab/moose#24543]
## Reason

Need to instantiate the class for linking when inheriting or will have `symbol not found in flat namespace (__ZN24StrainEnergyDensityTemplILb0EE12initialSetupEv)` problems.
## Design

Add the explicit template instantiation.
## Impact

Allows inheritance of the class.

**Comment by GiudGiud** [comment]
Closed as completed by https://github.com/idaholab/moose/pull/24544
