### ISSUE TITLE
MQMQA pair support in Thermochimica API

### ISSUE THREAD

**Issue by parikshitbajpai** [idaholab/moose#24552]
## Reason
Quadruplets are the "species" in MQMQA and as such their values are returned by Thermochimica when looking for mole fractions for example. However, users might be more interested in the pairs which are more obvious as species for multiphysics applications. This would throw an error because the pair would not be found in list of species. We want the users to be able to get the moles of pairs by specifying them like they would for other phases.

## Design
I will add a check for phase type and if the phase is MQMQA type, I will check for pairs instead of quadruplets.

## Impact
Hopefully users will not see any _species not found_ errors even when they specify pairs instead of quadruplets.

**Comment by parikshitbajpai** [comment]
@mtnwalker if you need any other features or have noticed any other bugs please add them here.

**Comment by mtnwalker** [comment]
One comment: it would be great to query total moles of elements in MSFL and in ideal_gas in addition to end members or species. Also naming convention for chemical potential instead of cp (heat capacity) may be confusing for some users - could try new naming convention. Thanks!
