### ISSUE TITLE
Remove MooseGhostPointNeighbors

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24573]
## Reason
ElementPointNeighborLayers is older and does the same thing

## Design
`git rm`

## Impact
Should be none

**Comment by brandall25** [comment]
@lindsayad Hi! - Mind if I do this? I know it's trivial, but I am trying to familiarize myself with contributing to open source.

**Comment by lindsayad** [comment]
yes I did!

**Comment by lindsayad** [comment]
Fixed the issue title
