### ISSUE TITLE
Segfault when using refined meshes with mortar contact

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#24638]
## Bug Description
Trying to use RefineSidesetGenerator together with penalty mortar contact (refining the contact area). Segfault. And in dbg
```
No index 18446744073709551615 in ghosted vector.
Vector contains [0,33618)
And empty ghost array.
```
Tagging @lindsayad 

## Steps to Reproduce
```
cd $MOOSE_DIR/modules/contact/test/tests/pdass_problems
../../../contact-opt -i cylinder_friction_penalty.i Mesh/refine/type=RefineSidesetGenerator Mesh/refine/boundaries=3 Mesh/refine/input=input_file Mesh/refine/refinement=1 Mesh/secondary/input=refine
```

## Impact
Prevents users from refining meshes along contact sidesets.

**Comment by dschwen** [comment]
Oh, interesting, when using the Lagrange Multiplier version on that file I get a different error

```
../../../contact-opt -i cylinder_friction.i Mesh/refine/type=RefineSidesetGenerator Mesh/refine/boundaries=3 Mesh/refine/input=input_file Mesh/refine/refinement=1 Mesh/secondary/input=refine
```

yields

```
*** ERROR ***
'cont_press' of type 'NodalValueSampler' depends on variable(s) 'frictionless_normal_lm'. However, that variable does not appear to be defined on (all of) boundary ''.
```

**Comment by dschwen** [comment]
Note that using the `BoundaryMarker` to perform initial refinement woks fine! This is slightly annoying as that marker existed before the redundant `RefineSidesetGenerator` was added. @GiudGiud maybe you can figure out what is missing in `RefineSidesetGenerator`.

**Comment by GiudGiud** [comment]
maybe just a `isnt_prepared` called. Would be my guess

**Comment by GiudGiud** [comment]
I like that you are using RefineSidesetGenerator now :)

**Comment by lindsayad** [comment]
It's the ordering. Refinement generators must go after the lower-d block generator. I need to add error checking in the lower-d generators to give the user an informative error

**Comment by lindsayad** [comment]
How about this message?
> *** ERROR ***
> The following error occurred in the object "secondary", of type "LowerDBlockFromSidesetGenerator".
> 
> Only active, level 0 elements can be made interior parents of new level 0 lower-d elements. Make sure that LowerDBlockFromSidesetGenerators are run before any refinement generators

**Comment by dschwen** [comment]
Yeah. The second sentence is probably the most helpful part for the average user.
