### ISSUE TITLE
"Zigzagging" side sets in ExodusII 2.5D mesh output

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24631]
### Discussed in https://github.com/idaholab/moose/discussions/24630

<div type='discussions-op-text'>

<sup>Originally posted by **ln53** June  8, 2023</sup>
I've been generating disjoint 2D meshes in 3D space using Gmsh. After the mesh has been processed by MOOSE (and opened in ParaView), the side sets (which should be straight along the edges) are in the pictured "zigzag" or "stitched" pattern.

- This happens using Gmsh physical groups to specify sidesets, as well as ParsedGenerateSideset, SideSetsFromNormalsGenerator, and various other side set generators.
- It only seems to happen when there are multiple disjoint meshes in 3D  - individual 2D meshes or disjoint & coplanar 2D meshes both behave as expected.
- MWE image and code under dropdowns below.

<img width="646" alt="image" src="https://github.com/idaholab/moose/assets/84389483/3aee6071-144c-451d-b1a8-f859a2c5f648">

<details>
<summary> Mesh generation with Gmsh Python API </summary>

```
import gmsh
occ = gmsh.model.occ
gmsh.initialize()

occ.addRectangle(0, 0, 0, 1, 1)
occ.addRectangle(0, 0, 0.5, 1, 1)
occ.synchronize()

gmsh.model.addPhysicalGroup(1, [1], name="MWE_Sideset")
gmsh.option.setNumber("Mesh.MeshSizeMax", 0.1)
gmsh.option.setNumber("Mesh.SaveAll", 1)
gmsh.model.mesh.generate()
gmsh.write("MWE.msh")
```

</details>

<details>
<summary> MOOSE input file mesh block </summary>

```
[Mesh]
  [mesh]
    type = FileMeshGenerator
    file = 'MWE.msh'
  []
  #   [sideset2]
  #     type = SideSetsFromNormalsGenerator
  #     input = mesh
  #     normals = '1 0 0'
  #     new_boundary = 'MWE_Sideset2'
  #   []
  #   [sideset3]
  #     type = ParsedGenerateSideset
  #     input = mesh
  #     combinatorial_geometry = 'x = 0 & z = 0'
  #     new_sideset_name = 'MWE_Sideset3'
  #   []
[]
```

</details></div>

**Comment by roystgnr** [comment]
I can reproduce this, and with a pure libMesh code; the problem's got to be at that level.  The `get_boundary_info().add_side` code in `gmsh_io.C` looks utterly straight-forward, but I'll get in there in gdb and see if I can figure out what's going on.

**Comment by roystgnr** [comment]
I'm horribly confused by this.  When I `ncdump` the output exodus file, I see that all the sideset entries are on side 3.  When I look at the corresponding triangles, they're numbered counter-clockwise with "lower right node", "upper node", "lower left node" ordering.  When I look at the ExodusII docs, they agree with libMesh convention (except for the 1-based vs 0-based counting), so side 3 should be between those lower nodes.  So the file looks perfectly correct.  But Paraview is showing me the same jaggies it's showing you.

**Comment by roystgnr** [comment]
Linking https://github.com/idaholab/moose/discussions/24630#discussioncomment-6302640 so it doesn't get missed from this side of things.

We don't have a problem with gmsh 2.5D input; we have a problem with ExodusII 2.5D output.  "The same mesh visualizes differently in Paraview when you just change num_dim from 2 to 3" would be pretty damning ... except that the *definition of ExodusII triangle data* changes when you just change num_dim from 2 to 3 ( https://sandialabs.github.io/seacas-docs/html/element_types.html#tri ), and we need to change our definitions accordingly.
