### ISSUE TITLE
Enable Geometry User Objects for blocks

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#24645]
## Reason

When refining lower dimensional subdomains, such as secondary surface meshes for mortar contact, it would be convenient to apply a Geometry User Object to the lower D _block_ rather than a sideset.

Geometry User Objects will "snap" a selected set of nodes to a user defined geometry. For example `GeometrySphere` can be used to place new nodes added by mesh refinement to the surface of a perfect sphere/circle.

## Design
In `GeometryBase::meshChanged()` we need to iterate over selected subdomain nodes in addition to boundary nodes.

## Impact
Added capability

**Comment by dschwen** [comment]
Actually lower-D subdomains are automatically refined and snapped along with their corresponding sidesets...

**Comment by GiudGiud** [comment]
It would be good to generalize this:
- have some Geometry block that represents exact geometries or CAD ones
- have that same ability of snapping for any of these, detecting the nearest exact surface maybe
