### ISSUE TITLE
Enable output based on function times

### ISSUE THREAD

**Issue by joseph-silberman** [idaholab/moose#24694]
## Reason
This can force output times more efficiently for the user. 

## Design
Used piecewise base function domain to define sync_times in outputs. 

## Impact
Something new

**Comment by lindsayad** [comment]
Hi, thank you for opening an issue and associated pull request. Really appreciate your contributions! In the future, if you could try to put something a little more descriptive in the "Impact", that would be appreciated. Something new can have a very wide range of impacts
