### ISSUE TITLE
Jintegral test file not adding information of symmetry to Jintegral block

### ISSUE THREAD

**Issue by BoZeng1997** [idaholab/moose#24748]
## Problem Description
In test file moose/modules/tensor_mechanics/test/tests/j_integral/j_integral_2d.i, the symmetry plane was not provided. The J integral converges to only half of the analytical value.

Analytical value provided in the input deck
```
#The analytic solution for J1 is 2.434.
```
The current `J1` converges to `1.166`. If `DomainIntegral/symmetry_plane=1` is provided the result will be `2.42`

**Comment by lindsayad** [comment]
@bwspenc @dschwen @jiangwen84 could one of you guys look into or comment on this at some point?

**Comment by recuero** [comment]
Closed via #24833
