### ISSUE TITLE
Mesh adaptivity not suppoerted for FV problems with variables restricted to subdomains

### ISSUE THREAD

**Issue by pbehne** [idaholab/moose#24792]
## Bug Description
When running a finite volume problem with a variable constrained to a subdomain, mesh adaptivity does not seem to be supported.

## Steps to Reproduce
Run the attached adaptivity_ex_FV.txt. An assertion is hit:

`Assertion `this->hasBlocks(elem->subdomain_id())' failed
The variable should be defined on the element's subdomain! This typically occurs when the user wants to evaluate the elements right next to the boundary of two variables (block boundary). The subdomain which is queried: 0 the subdomain of the element 1
at /Users/behnpa/projects/moose/framework/src/variables/MooseVariableFV.C, line 459`

A similar working example is provided for finite element in adaptivity_ex_FE.txt.

## Impact
Mesh adaptivity cannot be used for FV problems with variables restricted to subdomains.

[adaptivity_ex_FE.txt](https://github.com/idaholab/moose/files/11837957/adaptivity_ex_FE.txt)
[adaptivity_ex_FV.txt](https://github.com/idaholab/moose/files/11837958/adaptivity_ex_FV.txt)

**Comment by GiudGiud** [comment]
```
    block = '0 1'
    refinement = '3 3 1'
```
doesnt seem right. 
Can you try with only adaptivity, no RefineBlockGenerator

**Comment by pbehne** [comment]
I get the same assertion without the RefineBlockGenerator.

**Comment by GiudGiud** [comment]
Problem seems solved when moving from the GradientJumpIndicator to ValueJumpIndicator

**Comment by GiudGiud** [comment]
I ll put up a patch
