### ISSUE TITLE
Rely on the Times system to provide custom execution or control schedules

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#24816]
## Reason
Following the coming introduction of Times from #24696 (soon) it seems natural that we decide whether we do execution based on whether the simulation time is present within the Times object.

This could be a simpler system than using Controls
This could be an alternative to waiting for Executors

## Design
Modify SetupInterface to accept more complexity
Add new exec flag like EXEC_ON_`<name_of_times>`_BEGIN

or execute_on_times = TimesObjectName ???

## Impact
Waiting for a customer on this maybe
But seems like it was expressed for multiapps custom execution schedules

@YaqiWang we could do DepletionTimes or BranchCaseTimes to select when to perform these calculations if you want
@aprilnovak if you wanted to pick when to run some multiapps on the time scale

**Comment by GiudGiud** [comment]
@MengnanLi91

**Comment by GiudGiud** [comment]
if we do that btw, we ll need to modify all the checks on "my object execute_on is the same as this other one I rely on" to incorporate the times.

We should have an API in the SetupInterface to do this.

**Comment by MengnanLi91** [comment]
> if we do that btw, we ll need to modify all the checks on "my object execute_on is the same as this other one I rely on" to incorporate the times.
> 
> We should have an API in the SetupInterface to do this.

Do you mean I need to check dependency of the object? I didn't see such API in the SetupInterface

**Comment by GiudGiud** [comment]
Ok I got something very close to that, with the TimesEnableControl. We could debatedly close this
