### ISSUE TITLE
Add FunctorInterface::getFunctorByName

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#24841]
## Reason

People may iterate over a parameter retrieved as a `std::vector<MooseFunctorName>`. `getFunctorByName` would be handy in this case

## Design
Add `getFunctorByName`. `getFunctor` can call it after deducing the property name

## Impact
More flexibility for developers

**Comment by lindsayad** [comment]
@AlbertJP7's work inspired this issue

**Comment by MengnanLi91** [comment]
I can work on this

**Comment by lindsayad** [comment]
Yep! Thank you!
