### ISSUE TITLE
Files in TriBITS appear as deleted when using make clobberall

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#24870]
## Reason

Files inside of the TriBITS submodule inside of the wasp submodule are removed when doing make clobberall. These files are tracked by git and then result in the submodule being modified when using `git status`. This is an annoyance.

## Design

Remove the following files from being tracked by git in the TriBITS submodule:

```
test/core/ProcessEnabledTpls/tpls/HeadersAndLibsTpl/lib/libhaltpl1.a
test/core/ProcessEnabledTpls/tpls/HeadersAndLibsTpl/lib/libhaltpl1.so
test/core/ProcessEnabledTpls/tpls/HeadersAndLibsTpl/lib/libhaltpl2.a
test/core/ProcessEnabledTpls/tpls/HeadersAndLibsTpl/lib/libhaltpl2.so
```

## Impact

Fixes an annoyance.

**Comment by gambka** [comment]
@loganharbour

**Comment by loganharbour** [comment]
Closed in https://github.com/idaholab/moose/pull/26102 with a WASP update that cleaned up extraneous files.
