### ISSUE TITLE
reduce memory usage of nucleation model implementation in raccoon

### ISSUE THREAD

**Issue by BoZeng1997** [idaholab/moose#24903]
Two nucleation models for phase-field fracture are memory consuming. Either in how the material object is coded, or how the model is implemented in input deck level (or both).

## source code
https://github.com/BoZeng1997/raccoon/blob/c24df81ba4ef97f1b3490821daa631d961e3e68d/src/materials/KLRNucleationMicroForce.C
https://github.com/BoZeng1997/raccoon/blob/c24df81ba4ef97f1b3490821daa631d961e3e68d/include/materials/KLRNucleationMicroForce.h

## how the model is implemented
https://github.com/BoZeng1997/raccoon/tree/c24df81ba4ef97f1b3490821daa631d961e3e68d/tutorials/surfing_boundary_problem
The current implementation is for sure not the best way. It requires dispx dispy dispz to be transfered to the subapp. Then the subapp would compute stress tensor invariant I1 and J2. One way to improve it a little bit is by computing I1 and J2 in the mainapp then transfer it to subapp. I am waiting to see if there is even better way of improvement.

**Comment by BoZeng1997** [comment]
Please take a look at it when you have time @permcody . Thanks.

**Comment by lindsayad** [comment]
Is this really a MOOSE issue? @hugary1995

**Comment by BoZeng1997** [comment]
No. I asked Cody about it after the moose training. He suggested that I should open a ticket for him to look at the code when I am ready. I do not think this is a moose issue.

**Comment by lindsayad** [comment]
Let's wait for @hugary1995 to weigh in and then we may transfer this

**Comment by hugary1995** [comment]
how memory consuming is this? Do you have perf logs?

**Comment by hugary1995** [comment]
anyhow, I agree this isn't a moose issue.

**Comment by lindsayad** [comment]
Oh I forgot I can't transfer out of the organization. @BoZeng1997 can you close this and open an issue or discussion on raccoon?
