### ISSUE TITLE
Update BCs in scalar transport to take in Mat. Prop. 

### ISSUE THREAD

**Issue by simopier** [idaholab/moose#24915]
## Reason
The current implementation of the BCs in the scalar transport module only take Reals as coefficients. To be more flexible, it needs to accept material properties that can vary. 

## Design
The current implementation is updated to accept material properties rather than Real constants. 

## Impact
This will make these capabilities (BCs) more flexible. I see no negative impact.

**Comment by simopier** [comment]
@lindsayad , I'm on it.

**Comment by lindsayad** [comment]
Awesome, thanks @simopier !
