### ISSUE TITLE
Compute `sln_diff` on the fly

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#24931]
## Reason
`Transient::relativeSolutionDifferenceNorm()` computes a difference with an unnecessary allocation.

## Design
Compute `sln_diff` in `Transient::relativeSolutionDifferenceNorm()` on the fly.

## Impact
Better memory usage.

**Comment by zachmprince** [comment]
Seems like we can do this without creating a vector at all. Just compute `||u-u_old||` in a custom loop. Or if libmesh/petsc has something already...
