### ISSUE TITLE
Adaptive h-refinement takes a huge amount of memories with many auxiliary variables

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#25007]
## Bug Description

When many auxiliary variables are defined (e.g., an array variable with 1000s of components), adaptive h-refinement on part of the domain takes way more memory than uniform refinement everywhere (even though these variables are not defined in the blocks that are being refined).

## Steps to Reproduce

The behavior can be produced with [this MWE](https://github.com/vincentlaboure/moose/commit/edbdd950d5a358674866dea16debeed48952610f), by varying `Mesh/uniform_refine` and `Adaptivity/initial_steps`:

- Mesh/uniform_refine = 0, Adaptivity/initial_steps=0

```
Postprocessor Values:
+----------------+----------------+
| time           | total_memory   |
+----------------+----------------+
|   0.000000e+00 |   9.652634e+07 |
|   1.000000e+00 |   1.125007e+08 |
+----------------+----------------+
```

- Mesh/uniform_refine = 1, Adaptivity/initial_steps=0

```
Postprocessor Values:
+----------------+----------------+
| time           | total_memory   |
+----------------+----------------+
|   0.000000e+00 |   1.060659e+08 |
|   1.000000e+00 |   1.499464e+08 |
+----------------+----------------+
```

- Mesh/uniform_refine = 0, Adaptivity/initial_steps=1

```
Postprocessor Values:
+----------------+----------------+
| time           | total_memory   |
+----------------+----------------+
|   0.000000e+00 |   1.403163e+09 |
|   1.000000e+00 |   1.394131e+09 |
+----------------+----------------+
```

- Mesh/uniform_refine = 0, Adaptivity/initial_steps=2
```
Postprocessor Values:
+----------------+----------------+
| time           | total_memory   |
+----------------+----------------+
|   0.000000e+00 |   1.443676e+09 |
|   1.000000e+00 |   1.441067e+09 |
+----------------+----------------+
```

## Impact

On a practical problem, this makes 1 level of h-refinement on a block amounting to ~10% of the total elements more than one order of magnitude more memory intensive than 1 level of uniform refinement.

**Comment by lindsayad** [comment]
@roystgnr I don't know if you'd want to look into this. It's probably something dumb we're doing in MOOSE. Otherwise I will get to this at some point

**Comment by roystgnr** [comment]
I'm actually the one who asked Vincent to come up with the MWE.  :-)  I'm cleaning up a libMesh branch right now but I'll be looking at this once that's in PR-ready shape.

**Comment by roystgnr** [comment]
Well, I'll be trying to look at this, at least.  I'm a lot more comfortable with debugging CPU-time performance issues ... which does sometimes fix memory issues, but only incidentally and rarely.  If this turns out to only show up as a memory-use issue, what's our best way to get a handle on that?  memory_logger.py?

**Comment by roystgnr** [comment]
The first reason was indeed "we don't bother disabling vector projections during initial adaptivity" ... but the underlying problem there is "we *can't* disable all vector projections during initial adaptivity".  Adaptivity Markers in MOOSE create an auxilliary variable to copy their output into (kinda redundant for the 99% of cases with just one marker, but the flexibility for the remaining cases is cool) ... and that marker output then *doesn't* get overwritten after mesh refinement, so it has to be projected if we want it afterward.  I'm betting that 99% of the time we don't want it afterward, but I hate yanking away a feature from people, not to mention all the exodiffs that break if the marker gets zeroed after refinement.

The long-term fix here is to project only certain variables and not others ... but right now libMesh only lets projection be disabled on a vector-by-vector basis.  The projection code is 95% set up to enable/disable projection variable-by-variable, but I'll need to add an interface for that.

I'm looking into the deeper problems now too.  Even if we disable unnecessary projections we really shouldn't be so slow when they're necessary.

**Comment by GiudGiud** [comment]
@lindsayad this is fixed right?

**Comment by roystgnr** [comment]
IMHO this will be fixed with the libMesh submodule update this week.  The fixes linked here didn't make it in to the late-July update.
