### ISSUE TITLE
Add an option to Parsed generation of sidesets to only include external ones

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#25082]
## Reason
When adding a boundary, if the surface is curved it s sometimes exceedingly difficult to get the outside of the surface without grabbing one or more sides
We can make due currently if we re lucky enough to be able to rely on subdomain and neighbor subdomains. But if there's no neighbor subdomains (truly external face) then there's nothing in ParsedGenerateSideset

## Design
Simple additional boolean to disable adding internal ones

## Impact
Easier MOOSE meshing
More usability

**Comment by dschwen** [comment]
Something along the lines of https://github.com/idaholab/moose/pull/23468/files , but for `ParsedGenerateSideset`. :+1:

**Comment by GiudGiud** [comment]
Exactly!
