### ISSUE TITLE
Requesting a VectorPostprocessor that outputs material properties for _all_elements

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#25093]
## Reason
Right now, [MaterialVectorPostprocessor](https://mooseframework.inl.gov/source/vectorpostprocessors/MaterialVectorPostprocessor.html) requires a list of elements to query. Would prefer an option to apply to _all_ elements.

## Design
Add option to MaterialVectorPostprocessor ~~or make it all elements by default.~~
OR
Create a new ElementMaterialVPP that does it for block-restricted elements

## Impact
New capability.

**Comment by jessecarterMOOSE** [comment]
Would also be nice if output included qp coordinates too. I _might_ take a crack at this.

**Comment by GiudGiud** [comment]
Edited the request
