### ISSUE TITLE
Create cylindrical gap heat flux functor material

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#25113]
## Reason
Applications with heat transfer across a cylindrical gap could use to compute heat flux.

## Design
This would implement a FunctorMaterial that computes a gap heat flux across a cylindrical gap with simple models.

## Impact
New object.

**Comment by lindsayad** [comment]
We currently have `FunctorGapFluxModelConduction` and `FunctorGapFluxModelRadiation`

**Comment by joshuahansel** [comment]
Thanks, it looks close to what I need but not quite. Those appear to take the gap distance from the mesh, whereas I'd like a varying gap distance with a fixed mesh.

**Comment by joshuahansel** [comment]
I'm doing 2D-to-3D coupling, just for context.
