### ISSUE TITLE
Make periodic BCs work with split mesh

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#25158]
Discussion is linked to below. I asked the user if this worked if all the algebraic objects in the simulation (like those that add the periodic bcs) were present, but it doesn't. This surprises me. Are the geometric ghosting functors for these objects not getting added?

### Discussed in https://github.com/idaholab/moose/discussions/25131

<div type='discussions-op-text'>

<sup>Originally posted by **Eilloo** August  8, 2023</sup>
Hi all,

Should periodic BCs work with a split mesh?
I have a case where I am loading in a mesh file which is periodic, and translational BCs are accepted as expected when the mesh is replicated, and also if distributed without pre-splitting the mesh.
However, if I pre-split the mesh, I get the following error:
`Periodic boundary neighbor not found`
Is this behaviour expected, and is there any way to apply periodic BCs to large meshes which need splitting?

Thanks!</div>

**Comment by GiudGiud** [comment]
Tied to #17923

**Comment by lindsayad** [comment]
Usually I make fun of other people for opening duplicate issues. This time it was me. I'm closing this in favor of #17923
