### ISSUE TITLE
DomainIntegral allowing user to suppress VPP output

### ISSUE THREAD

**Issue by BoZeng1997** [idaholab/moose#25162]
## Reason
DomainIntegral Action currently generates one csv file for each integration ring at each time step. It produces a lot of redundant files when the user only want the result from the Postprosessor output. We should add an option for user to suppress the VectorPostProsessor output.

## Design
a boolean option to turn on or off all the vpp output.

## Impact
This new option will not influence any existed function or change any existed result. It only make the directory cleaner without a long list of csv.

**Comment by lindsayad** [comment]
Thank you for the issue report! If you can try to fill out all three sections of the issue template in the future, that would be much appreciated.
