### ISSUE TITLE
Documentation lists incorrect module name for DireWolf

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#25210]
## Bug Description
This page https://mooseframework.inl.gov/ncrc/applications/ncrc_hpc_direwolf.html lists `direwolf` as the module that should be loaded, but it's actually `dire_wolf`.

## Steps to Reproduce
See above.

## Impact
User confusion.

**Comment by joshuahansel** [comment]
@milljm I see that the template field for `ncrc_hpc.md.template` called `ApplicationLower` is set to `direwolf`. I'm wondering if it just needs to be changed to `dire_wolf` or if there are other places where `ApplicationLower` is used where it shouldn't be `dire_wolf`, in which case I guess we-d need to make another field.

**Comment by milljm** [comment]
The script rotating/generating the modules is actually supposed to strip out all non alphanumeric characters (dire_wolf = direwolf, relap-7 = relap7)... What is in the documentation is supposed to be correct.

```bash
echo $APP_NAME | tr -dc '[:alnum:]\n\r'
```

But I see we're not doing that properly on the HPC side. Thanks for catching this!

**Comment by milljm** [comment]
I fixed the issue where it was broken (outside of MOOSE documentation control)
