### ISSUE TITLE
skip remaining tests causing failures in conda build moose

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#25293]
## Reason
By enabling all-tests in modules for Conda MOOSE package, we have some additional test failures.

## Design
Figure out the tests which are failing, mark them as skip.

## Impact
Allow CI to pass

**Comment by lindsayad** [comment]
Known reasons why tests can't run out-of-tree. I will allow these to be checked-off when they are no longer problems
- [ ] NS MMS tests which hard-code paths to executables
- [ ] They use JIT (need to bore down on this)

**Comment by milljm** [comment]
Something to add: All arches are passing JIT tests, except Apple Silicon.
