### ISSUE TITLE
DebugResidualAux seg fault with CONSTANT MONOMIAL

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#2545]
Below is a sample input file.  It will produce a segmentation fault.  If you comment out the this_gives_seg_faults AuxVariable and its AuxKernel you won't see the seg fault.

# illustrates problem of calculating residual of CONSTANT MONOMIAL variable
[Mesh]
  type = GeneratedMesh
  dim = 3
  zmin = -1
  zmax = 1
  nz = 1
  xmin = -1
  xmax = 1
  nx = 1
  ymin = -1
  ymax = 1
  ny = 1
[]

[Variables]
  [./conc]
    family = MONOMIAL
    order = CONSTANT
  [../]
[]

[ICs]
  [./c]
    type = ConstantIC
    value = 1
    variable = conc
  [../]
[]

[Kernels]
  [./c_dot]
    type = TimeDerivative
    variable = conc
  [../]
[]

# Comment the res_conc, and you won't see the seg fault
[AuxVariables]
  [./this_gives_seg_faults]
    family = MONOMIAL
    order = CONSTANT
  [../]
[]

[AuxKernels]
  [./this_gives_seg_faults_AuxK]
    type = DebugResidualAux
    debug_variable = conc
    variable = this_gives_seg_faults
    execute_on = timestep
  [../]
[]

[Preconditioning]
  active = 'usual'
  [./usual]
    type = SMP
    full = true
    petsc_options = '-snes_converged_reason'
    petsc_options_iname = '-ksp_type -pc_type -snes_atol -snes_rtol -snes_max_it -ksp_max_it'
    petsc_options_value = 'bcgs bjacobi 1E-3 1E-15 10 1000'
  [../]
[]

[Executioner]
  type = Transient
  end_time = 1
  dt = 1
  solve_type = NEWTON
[]

[Output]
  file_base = some_output
  output_initial = true
  interval = 1
  exodus = true
  perf_log = true
  linear_residuals = false
  postprocessor_csv = false
[]

**Comment by permcody** [comment]
Fixed in 7188a4664013bf4d9a1f2ccb329d890855e08e6b
