### ISSUE TITLE
Fix libMesh bootstrap applying a re-patch

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#25456]
## Reason
With latest `moose-dev` or rather, with updated Autotools (automake 1.16.5), we seem to run into a snag while attempting to build libMesh using our `update_and_rebuild_libmesh.sh`.

## Design
Remove the needed bootstrapping portion that is applying a patch.

```pre
Reversed (or previously applied) patch detected!  Assume -R? [y] n
Apply anyway? [n]
```

## Impact
No halts during the use of `update_and_rebuild_libmesh.sh`

**Comment by roystgnr** [comment]
Edited the title to put the blame on me where it belongs.
