### ISSUE TITLE
Add circumcenter calculation to MathUtils

### ISSUE THREAD

**Issue by sourabhkadambi** [idaholab/moose#25482]
## Reason
Method needed to calculate centers (e.g. centroid, circumcenter) given points forming a triangle (2D) or tetrahedron (3D).

## Design
Add member functions to MathUtils. Calculation of centers will be based on Barycentric coordinates and converted to Cartesian.

## Impact
Add new math functions.

**Comment by lindsayad** [comment]
I assume this is for arbitrary points? Because `Elem` objects have `vertex_average()` and `true_centroid()` methods

**Comment by sourabhkadambi** [comment]
> I assume this is for arbitrary points? Because `Elem` objects have `vertex_average()` and `true_centroid()` methods

What about circumcenters? That's the main center calculation I want to add to aid in void center placement within a voronoi structure #25289

**Comment by lindsayad** [comment]
There is a [quasicircumcenter](https://mooseframework.inl.gov/docs/doxygen/libmesh/classlibMesh_1_1Elem.html#a0f98c4d3a56318ef78b96f94e1791b43) routine implemented for 1D and 2D elements. Not yet for 3D

**Comment by dschwen** [comment]
It's for arbitrary points
