### ISSUE TITLE
Tests Failing after Matplotlib Update

### ISSUE THREAD

**Issue by brady-respec** [idaholab/moose#25509]
## Bug Description

Matplotlib 3.8 (https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html) looks to made an API change that is causing tests to fail (see my error message and the API change that was made recently).

Failed Test Image:

![image](https://github.com/idaholab/moose/assets/64555622/2791cb34-8ec3-4e3d-ac8e-373d1d386161)

Matplotlib 3.8 API Change from September 13, 2023

![image](https://github.com/idaholab/moose/assets/64555622/92e2e3a1-9475-463c-ba12-4a4e07484e04)

## Steps to Reproduce

I started from a new environment, cloned Moose, compiled Moose, then ran the tests. 28 tests failed, many of which (or all?, I didn't scroll through the entire log) had the same error message.

Failed Tests:

![image](https://github.com/idaholab/moose/assets/64555622/cc8c34fa-87c5-447a-886e-f0f65ed36554)

## Impact

It doesn't affect my work but I imagine it's not good that tests are failing as a result of this. Should be an easy fix.

**Comment by brady-respec** [comment]
Changing "tick.label.set_fontsize(fontsize)" to "tick.label1.set_fontsize(fontsize)" on line 44 of "moose/python/mms/ConvergencePlot.py" fixes the issue for me and all the tests pass. 

I'm not quite sure how you guys handle dependencies or if that change would break compatibility with older versions of matplotlib.

**Comment by milljm** [comment]
I have a change that is 'bumping' the versions in our Conda packages. If `matplotlib` happens to be one of them I can incorporate this change into that PR.

Cheers!
