### ISSUE TITLE
Speed up calculations containing DiracKernels

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#2555]
Simulations involving DiracKernels can be slow.

My simulations contain millions of elements and thousands of DiracKernel points.  If i just addPoint(Point) then each time step takes ages.  But if i cache the Elem returned by that function in the first time step, and then addPoint(Elem, Point) in subsequent time steps, i get huge improvements in speed.  

Currently i've got a flag in my DiracKernels - mesh_adaptivity = true/false - and if false then i use the caching approach.  It might be nice if MOOSE were to automatically do this.

a

**Comment by permcody** [comment]
Closed by #3172

**Comment by WilkAndy** [comment]
Thanks for closing this DiracKernel issue, @permcody
