### ISSUE TITLE
Need to remove moose app command-line options from the list of petsc options

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#25577]
## Reason
If we add `-options_view` option on command line, which will print PETSc option table entries at the end of simulation when `PetscFinalize` is called, we will see `-i foo.i` in the list, which is not one of petsc options. If we add `-options_left` on command-line, this will generate a false warning saying that `there are options you set that were not used` from PETsc.

## Design
When passing command-line to PETSc, we possibly should remove those options from MOOSE application, i.e. options declared in `MooseApp`. Otherwise, we may see this false warning if the `-options_left` is turned on programmatically. (I do not know how this option is turned on in MOOSE.) Tag @lindsayad 

## Impact
No impact to calculations but rather a possible false warning that annoys users.

**Comment by roystgnr** [comment]
Not sure about the MOOSE interface here, but at least as a first step I'll see about adding libMesh (and lower) level APIs to expose the sets of options that we accept in the libraries; then we can search those for options before passing them in.

This would be easy if it was just a matter of tossing all our fixed-string option names into a static set ... but we do construct some strings at runtime, in both MOOSE and libMesh, so we'll need a dynamic set.  Logan points out that we can just insert into that set at runtime.  That seems reasonable on the libMesh side (if someone specifies an option that we could have tested but *didn't* test, that's probably still worth warning about), and it would give us an API to use from the MOOSE side as well.

**Comment by pbehne** [comment]
I can work on this.

**Comment by lindsayad** [comment]
That's awesome. Make sure to leverage to work that @roystgnr leveraged in libMesh
