### ISSUE TITLE
Nodal Block Restricted Variables IC Issue

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2564]
A nodal block restricted variable can have issues on the "block interface" with initial conditions in parallel.

The conjecture is that this happens when you have a node that is owned by an element NOT in the block and on another processor.  In this case the node will not receive any value for its IC.

We've had similar issues with Nodal AuxKernels... and we fixed that up by doing nodal loops instead of element loops.  I'm not sure that the same can be done here because of the difficulties in projecting arbitrary shape function families (like 3rd order Hermite).

Some investigation needs to be done here - but this is a real bug.

**Comment by permcody** [comment]
Should be closed by #14469
