### ISSUE TITLE
Implement explicit dynamics, node-face normal contact

### ISSUE THREAD

**Issue by recuero** [idaholab/moose#25666]
## Reason
We have a number of formulations for mechanical contact: node-on-face, mortar; also various forms of enforcement: constraint/kinematic/Lagrange multiplier, penalty, and augmented Lagrange. But no contact mechanics formulation is available for explicit dynamics simulations.

To further exercise and equip MOOSE's explicit dynamics capabilities, we propose adding an explicit, transient node-face contact formulation that would preliminarily enable the study of impacts.

## Design
I am initially thinking of an object inheriting from `NodeFaceConstraint` which approximates the contact forces with an uncoupled iterative algorithm.

## Impact
Added feature.

**Comment by lindsayad** [comment]
Why are you starting with node-face as opposed to mortar?

**Comment by recuero** [comment]
Because of its simplicity. There are known node-face algorithms* that I think we can implement entirely in the constraint system within one object. Node-face has the advantage that no intermediate mesh needs to be built, which might make a difference performance-wise.

When we implement the mortar counterpart we will compare their performance.

*These algorithms might be extensible to our weighted-quantity based mortar formulation, but the variable coupling introduced by mortar may be a hurdle when iterating to obtain a solution since uncoupling the system (i.e. solving on a node basis) depends on successfully obtained an equivalent masses and wave speeds.
