### ISSUE TITLE
Remove cleaning of wasp with `make clobberall`

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#25717]
## Reason
`make clobberall` removes wasp libraries, see https://github.com/idaholab/moose/discussions/25710.

## Design
Don't remove wasp libraries with `make clobberall`

## Impact
Keeps consistent behavior for what `make clobberall` removes.

**Comment by permcody** [comment]
The current behavior is consistent. We DO delete all dependency object files and libraries with `clobber` or `clobberall`. We DO NOT remove dependencies with `clean`. See the logic where we remove specific directories from `os.walk` in our [clobber.py](https://github.com/idaholab/moose/blob/723a2b6ba9a9919726fe2654f8c9b85cd2c8f808/scripts/clobber.py#L86-L89) script.

**Comment by YaqiWang** [comment]
Because `make clobberall` relies on wasp, wasp can be an exception. Otherwise we get warnings during `make clobber` and cannot call it again after. We can add a separate rule like `cleanwasp`.

**Comment by permcody** [comment]
I'm fine with somebody improving this script. I don't plan to myself since I don't build dependencies.

**Comment by lindsayad** [comment]
> The current behavior is consistent. We DO delete all dependency object files and libraries with `clobber` or `clobberall`.

IMO Not consistent. We don't touch libmesh, petsc, etc. with `clobberall`
