### ISSUE TITLE
Create Switchable Boundaries in Finite Volume Navier Stokes

### ISSUE THREAD

**Issue by tanoret** [idaholab/moose#25803]
## Reason
For domain overlapping coupling approach, we need to switch velocity-inlet and pressure-outlet conditions during runtime.

## Design
Add two boundary conditions to switch between velocity-inlet and pressure-outlet. We need a velocity-inlet boundary condition and pressure-outlet boundary condition that can be activated/deactivated on demand.

## Impact
This enhancement will support domain-overlapping coupling approach between MOOSE Navier Stokes and the systems codes

**Comment by lindsayad** [comment]
Is this relatable to #24259 and #24446 ?

**Comment by tanoret** [comment]
> Is this relatable to #24259 and #24446 ?

Sort of... I am adding new velocity/pressure boundary conditions that can be switched during runtime. The goal is to be able to switch velocity-inet -> pressure-outlet and vice versa for the domain overlapping coupling
