### ISSUE TITLE
Don't set displacements without being asked

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#25804]
## Bug Description
I am looking at the input in #25778. If I apply the displacements in the mesh block, then I get errors from the heat conduction kernel, which is not block restricted, about how it's using coupled displacements which are on a subset of the mesh blocks. There is no `displacements` parameter in `GlobalParams` nor in the "offending" kernel block. Who is the offender then? Well it was me in fd20b9545679b91f853c5e1cd0b560dd77bb0921 . I probably did this for automatically coupling displacement variables into kernels for getting Jacobians right on displaced meshes ... but now we are seeing some bad side effects. @GiudGiud should keep this in mind when he is looking into https://github.com/idaholab/moose/issues/25800. Definitely don't want to blindly forward couplings from materials when it is possible a material (and variables it might use) may have a subset of the block restriction that the kernel does. (Think a thermal conductivity which is variable-dependent on one block and constant on another).

## Steps to Reproduce
Turn the displacements on in the `Mesh` block in the input in #25778.

## Impact
Users get errors for something they didn't even do.

**Comment by GiudGiud** [comment]
We need to be explicit about these things. i think the header of the simulation should say if the displaced mesh is in use.

And maybe have an info log with the objects that are not using it? Or a Debug option?

**Comment by lindsayad** [comment]
> We need to be explicit about these things. i think the header of the simulation should say if the displaced mesh is in use.

I think that's a good idea.

> And maybe have an info log with the objects that are not using it? Or a Debug option?

Might as well print the undisplaced/displaced status of everything. For mechanics, except maybe for finite strain, I believe all residual objects are supposed to run on the undisplaced mesh so in such a case it would be more helpful to indicate the status of objects incorrectly running on the displaced mesh.
