### ISSUE TITLE
No more `mamba update --all`

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#25854]
## Reason
Telling Conda to update everything doesn't work, when the packages we depend on are pinned to older versions in conda-forge (and conda-forge marches on faster than we allow in our /public channel).

## Design
Instruct folks to instead update the specific package tying everything together: `moose-dev`. That is:

```bash
mamba update moose-dev
```

## Impact
Prevent our Conda moose-packages from stalling out when a user wants to update the moose-packages

**Comment by lindsayad** [comment]
we hates it... it burns us 😆

**Comment by milljm** [comment]
![laugh](https://github.com/idaholab/moose/assets/6414286/df44e8f3-ed40-45de-ae12-6e3dd85800a1)
