### ISSUE TITLE
Create an elemental thermochimica user object

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#25877]
## Reason
For FV variables we need to loop over elements. This will require a new version of the ThermochimicaNodalData object. We'll solve this through templating.

## Design
Template on the loop type.

## Impact
Added capability.

**Comment by lindsayad** [comment]
are you becoming a finite volume developer?

**Comment by dschwen** [comment]
> are you becoming a finite volume developer?

Whatever pays the bills!
