### ISSUE TITLE
You could project the elemental variable, which represents the gradient projection, onto a nodal variable and then use that in the `MatchedValueBC`, so two projections

### ISSUE THREAD

**Issue by jin0123456** [idaholab/moose#25908]
You could project the elemental variable, which represents the gradient projection, onto a nodal variable and then use that in the `MatchedValueBC`, so two projections

_Originally posted by @lindsayad in https://github.com/idaholab/moose/discussions/25894#discussioncomment-7427110_

**Comment by lindsayad** [comment]
This is a post in a discussion thread
