### ISSUE TITLE
Unnecessary warning issued in mesh-only mode

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#26002]
## Reason
Running a moose test with `--mesh-only`, we will see something like
```
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
There are 2 unused database options. They are:
Option left: name:--mesh-only (no value) source: command line
Option left: name:-i value: generated_mesh_generator.i source: command line
```
at the end of the run. This is first reported by @NamjaeChoi on Slack.

## Design
This warning is from `-options_left` option that is set by PETSc by default. The function `processPetscPairs` in `PetscSupport.C` changes the default, but I think it is only called when `FEProblemSolve` is built through executioner, which is not the case in mesh-only mode. My suggested design is to move the part in the function for changing the default behavior into `MooseApp` so that it will be called in all cases including mesh-only mode.

## Impact
No impact to simulations but can make user experience better.

**Comment by YaqiWang** [comment]
Forgot mentioning that these command-line options are valid parameters of MooseApp and should be filtered out for the PETSc check (#25577). Doing that can also fix this warning.

**Comment by pbehne** [comment]
I can work on this.
