### ISSUE TITLE
Improve Doxygen code standards

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#2601]

**Comment by aeslaughter** [comment]
@permcody states:

> We do need to standardize. I propose that we start making use of some of the more advanced features of Doxygen:

>There is an http://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_inherit_docs that can be used to tell Doxygen to inherit documentation of virtual members. This really seems like a good idea. There's no reason for developers to waste time redefining things like computeResidual and computeJacobian all the way down their inheritance chains.

>I think we do need to comment all new methods introduced in classes. As far as class variables go, that may be a good idea too... Let's see if we can get the method documentation standardized first. One step at a time.

**Comment by dschwen** [comment]
Yes, please. I'm all for foxygen comments, unless they are redundant (I thought the inheritance thing was on by default).
We should also lead by example. Some apps and modules are obviously deficient and should be brought up to speed...

**Comment by permcody** [comment]
![image](https://cloud.githubusercontent.com/assets/3036960/13852501/ead4c598-ec27-11e5-97d1-c776c85a713c.png)

**Comment by friedmud** [comment]
"Slightly" off-topic... but Foxygen is the name of a band I've been
listening to lately: https://open.spotify.com/artist/55LHFEtIplWhsfyWZUwkf4

:-)

**Comment by andrsd** [comment]
You should also try "Galerkin Method" :wink:

**Comment by aeslaughter** [comment]
We have decided that Doxygen comments are for developers only, this is no longer an issue.
