### ISSUE TITLE
QUAD8 and QUAD9 Elements

### ISSUE THREAD

**Issue by Alirezarei** [idaholab/moose#26026]
## Bug Description
There is a bug using QUAD8 or QUAD9 elements. When I use QUAD4 elements everything is fine, but for QUAD8 and QUAD9 elements the contour plots in Paraview explodes! Meaning that the mesh gets disrupted and expands to fill the whole screen. This issue is raised in the new update that I've done two days ago. I have another system with the old version and that one is OK with all the element types.

## Steps to Reproduce
The input file is attached. Please do not publish the input file.

## Impact
It is preventing me from seeing the results. QUAD8 elements are way more efficient for my application and I have to use them because of computational power limitation.

[Quad8_Bug.txt](https://github.com/idaholab/moose/files/13322275/Quad8_Bug.txt)

**Comment by lindsayad** [comment]
> This issue is raised in the new update that I've done two days ago. I have another system with the old version and that one is OK with all the element types.

What did you update? Can you give the old and new versions of what you updated?

**Comment by Alirezarei** [comment]
Thanks for your quick response, Alex. I updated MOOSE based on the instructions given in the following link.
https://mooseframework.inl.gov/getting_started/new_users.html

**Comment by Alirezarei** [comment]
Also, I get the following error when I want to update MOOSE. I don't know what it is or if it is related to the above mentioned issue.

(moose) icar@Precision:~/projects/composites$ cd ~/projects/moose
(moose) icar@Precision:~/projects/moose$ git fetch origin
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 41 (delta 22), reused 25 (delta 18), pack-reused 0
Unpacking objects: 100% (41/41), 91.52 KiB | 1.83 MiB/s, done.
From https://github.com/idaholab/moose
   7b18119f1d..72056f3a66  next   	-> origin/next
(moose) icar@Precision:~/projects/moose$ git rebase origin/master
First, rewinding head to replay your work on top of it...
error: Updating the following directories would lose untracked files in them:
    modules/heat_conduction/src

Aborting
fatal: Could not detach HEAD

**Comment by lindsayad** [comment]
> There is a bug using QUAD8 or QUAD9 elements. When I use QUAD4 elements everything is fine, but for QUAD8 and QUAD9 elements the contour plots in Paraview explodes! Meaning that the mesh gets disrupted and expands to fill the whole screen.

Can you describe exactly what the order of filter application is in Paraview is to get the "expands to fill the whole screen" issue? Also what is your Paraview version?

**Comment by Alirezarei** [comment]
After opening the output file (Exodus .e file) in Paraview, I choose displacement and temperature results to be shown. Next, using the VCR controls, I play the contour plots and then the mesh starts to get distorted and fills the whole screen. I have three different versions of Paraview (5.7.0; 5.11.0-RC1; 5.11.2) and checked the output using all of them. Unfortunately, the problem persists in all the versions of Paraview. I have attached the animation of what happens.
[bug_anim.zip](https://github.com/idaholab/moose/files/13340944/bug_anim.zip)

**Comment by lindsayad** [comment]
I can't open an avi file. What do you contour by?

**Comment by lindsayad** [comment]
Are your solve histories the same between the old and new versions? I am not having any issues with the most recent PETSc and libMesh which would have been updated in your conda environment

<img width="1200" alt="Screenshot 2023-11-13 at 12 54 55 PM" src="https://github.com/idaholab/moose/assets/10248304/84bd6b00-3676-4226-b6ff-0b61477ffa21">

**Comment by Alirezarei** [comment]
Thank you so much for your time Alex. With your help I was able to resolve the issue. I reinstalled MOOSE and did all the updates again. Now it is working perfectly.

**Comment by lindsayad** [comment]
That's great to hear!
