### ISSUE TITLE
Allow the MultiAppCopyTransfer to transfer vectors between subapps

### ISSUE THREAD

**Issue by EdwardPalmer99** [idaholab/moose#26045]
## Reason
It would be useful to be able to transfer vectors between subapps.

## Design
Remove lines 185-186 in file <i>MultiAppDofCopyTransfer.C</i>
`   
 if (to_var.fieldType() == Moose::VarFieldType::VAR_FIELD_VECTOR)
      mooseError("Unable to transfer vector variables.");
`
## Impact
This will enable MonomialVec and LagrangeVec vector variables to be transferred between subapps provided that their meshes are identical.

**Comment by lindsayad** [comment]
It may not be as optimized but have you tried `MultiAppGeneralFieldNearestLocationTransfer`?

**Comment by EdwardPalmer99** [comment]
> It may not be as optimized but have you tried `MultiAppGeneralFieldNearestLocationTransfer`?

Yes I have. That doesn't appear to work.

**Comment by EdwardPalmer99** [comment]
> Do you get an error? Or wrong results?

Incorrect results. I think it was only transferring a single component of the vector.

**Comment by lindsayad** [comment]
Hmm, if you have a minimal example input showing this, it would be good for us to get that fixed

**Comment by EdwardPalmer99** [comment]
[MultiAppGeneralFieldNearestLocationTransferTest.zip](https://github.com/idaholab/moose/files/13377658/MultiAppGeneralFieldNearestLocationTransferTest.zip)

**Comment by EdwardPalmer99** [comment]
The attached zip is a simple test of MultiAppGeneralFieldNearestLocationTransfer test. It shows that only the x-component of the Lagrange vector appears to have been correctly transferred. The transfer was successful using the MultiAppCopyTransfer transfer with the modification described above.

**Comment by lindsayad** [comment]
Thanks!

**Comment by lindsayad** [comment]
I've opened https://github.com/idaholab/moose/issues/26084 for the general transfer enhancements

**Comment by EdwardPalmer99** [comment]
> I've opened #26084 for the general transfer enhancements

Thanks!

**Comment by GiudGiud** [comment]
@EdwardPalmer99 Alex also merged a change that lets you use CopyTransfer in case you did not see it.

For the other transfers this is a larger task
