### ISSUE TITLE
Peacock plugin "xcb" issue

### ISSUE THREAD

**Issue by smithht** [idaholab/moose#26057]
Hi,

I have been experiencing the same issue described in the discussion below. I am running Ubuntu on WSL using Windows 11. I am using the built in WSLg, instead of VcXsrv. xeyes works great. When I run peacock, I recieve: 

>qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

>Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

I tried executing `sudo apt install libxcb-*` in the base environment, but that did not resolve my issue. I have also tried uninstalling and reinstalling those libraries. I still get an issue about the "xcb" plugin not initializing. Thanks for your help.

### Discussed in https://github.com/idaholab/moose/discussions/25886

<div type='discussions-op-text'>

<sup>Originally posted by **DanielChou0916** October 28, 2023</sup>
Hello
I have an issue with using Peacock on WSL in the Windows system.
After the installation process, I was trying to run the example file.
`mamba activate moose`
`cd ~/projects/moose/tutorials/darcy_thermo_mech/step01_diffusion/problems`
`~/projects/moose/python/peacock/peacock -i step1.i`
However, I received the message:

> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

When I try this:
`../darcy_thermo_mech-opt -i step1.i`
Everything is fine, it returns 'Solve Converged!'
The xeyes works well, and I also enabled the ''Disable access control'' when using VcXsrv, so I'm not sure what's going on :(
Does anyone have a similar experience?

</div>

**Comment by lindsayad** [comment]
@milljm have you run across this?

**Comment by milljm** [comment]
The issue always seems to be different with each iteration of WSL/Ubuntu we encounter... I am not sure what the fix is... I am still waiting for INL to hand me a Windows machine with WSL available on it, in order to test.

In the meantime, can you try the following:

```bash
mamba activate base
mamba create -n paraview paraview
mamba activate paraview
paraview
```
If Paraview launches (can take a whole couple of minutes before it responds), then while in that same Conda environment, try to launch Peacock. These two applications utilize _almost_ the same dependencies. We might be missing one perhaps, with the `moose-peacock` Conda package.

**Comment by smithht** [comment]
Thanks for the suggestion, @milljm . I got peacock running after executing : 
`sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev` in the base environment. The missing dependency must've been in there somewhere.

**Comment by milljm** [comment]
> Thanks for the suggestion, @milljm . I got peacock running after executing : `sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev` in the base environment. The missing dependency must've been in there somewhere.

Always something! I am glad you figured it out!

Well... like the last discussion, I will go ahead and add this to the list :)
