### ISSUE TITLE
Component initialization of flow areas with ICs triggers the restart+IC check during restart simulations

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#26155]
## Bug Description
Flow channels use an IC, for example a constantIC, to initialize the area. However ICs are banned by default during restart simulations. 
This brings about an error message that can be bypassed by setting a boolean to the problem
This boolean `allow_initial_conditions_with_restart`

## Steps to Reproduce
Do a restart in a simulation with a THM component that has a flow area being initialized with an IC

```
  [core]

    [coolant_channel]
      type = FlowChannel1Phase
```

I m pretty worried that this has only been picked up now after 3 months of ICs being banned during restart simulations. 

## Impact
Inconvenience

**Comment by joshuahansel** [comment]
@GiudGiud @jortensi just ran into this. I'll address it now.
