### ISSUE TITLE
output_file parameter for Console has issue with multiple processors

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#26174]
## Reason
This parameter makes the console output into a file. When multiple processors are used, all processors will write to contents to the same file, which may corrupt the file. It also blows up the file when there are thousands of processors.

## Design
We possibly should default the writing happens only on head processor. We may give users an option to do the output on multiple processors, but the outputs need to be either sequentialized with one file or outputted into different files based on the processor ID.

## Impact
Fix the bad behavior of this input parameter and make it usable with multiple processors.

**Comment by permcody** [comment]
This is a solved problem _always_ has been. 
`--keep-cout --redirect-stdout`. Is that not acceptable here? I recommend we close this as "won't fix".

**Comment by YaqiWang** [comment]
It is a different but valid solution. The issue here is that this `output_file` parameter can have bad behavior.

**Comment by permcody** [comment]
I talked to Patrick about this. I'm on board with making this more clear and not relying on libMesh behaviors.

**Comment by pbehne** [comment]
@lindsayad, shouldn't this issue be closed?

**Comment by lindsayad** [comment]
:+1: this is closed by #26936
