### ISSUE TITLE
Reporters for postprocessing other reporters

### ISSUE THREAD

**Issue by lynnmunday** [idaholab/moose#26198]
## Reason
I need some new reporters that can postprocess reporter data for optimization simulations.  I need a reporer to row sum a reporter containing a vector of vectors. I need another reporter to compute the L2 difference between two vectors.

## Design
Create new reporters to consume existing reporters and compute new quantities.

**Comment by GiudGiud** [comment]
Let's make sure they are general as possible please. Re-implementing basic math just because the data format is not what we like is not sustainable. This is the kind of stuff we could use a Python API for

**Comment by lynnmunday** [comment]
I agree but I don't know how to make it general.  I can't use python to post-process this, I need to row sum a vector so that it can be used by something else during the simulation.

**Comment by GiudGiud** [comment]
@loganharbour or @aeslaughter are most familiar with reporters and where we should go with them.
