### ISSUE TITLE
addCommandLineParam<MooseEnum> doesn't work as intended

### ISSUE THREAD

**Issue by pak1sol** [idaholab/moose#26194]
## Bug Description
When a MooseEnum type variable is used in `params.addCommandLineParam<MooseEnum>`, it seems that the command line argument cannot be properly recognized; always the default value is used no matter what value is typed in via the command line argument. Only `params.addCommandLineParam<std::string>` works as intended.

## Steps to Reproduce
For a code snippet below,
```
params.addCommandLineParam<MooseEnum>("mooseenum_test", "--mooseenum-test", mooseenumTest(), "description");
...
MooseEnum test = getParam<MooseEnum>("mooseenum_test");
```
where
```
MooseEnum
mooseenumTest()
{
  return MooseEnum("a b c", "a");
}
```
Running below gives me `a` in the `test` variable. No matter what value is given in the command argument, always the default value is written to `test`.
```
xxx-opt --mooseenum-test b
```
The way to get it to work as intended is to accept the variable using the string as below.
```
params.addCommandLineParam<std::string>("mooseenum_test", "--mooseenum-test", mooseenumTest(), "description");
...
std::string test = getParam<std::string>("mooseenum_test");
```

**Comment by pak1sol** [comment]
@YaqiWang @permcody

**Comment by lindsayad** [comment]
@pak1sol can you see whether https://github.com/idaholab/moose/pull/26764 takes care of your needs?

**Comment by pak1sol** [comment]
> @pak1sol can you see whether #26764 takes care of your needs?

Yes, it does! Thank you!
