### ISSUE TITLE
Clean up sideset generation and factor out commonalities in a base class

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#26252]
## Reason
Sideset generators are multiplying and there's a lot of options on when to add or not add a sideset that should be factored out
- include external only sides
- replace existing sidesets
- skip if an existing sideset already includes this side
- only include if an existing sideset includes this side
- only include if a side is touching a subdomain
- normal of the side

This would be a much stronger design than what we have, where each derived class is slowly adding more options (especially ParsedgenerateSideset) to include what the others were doing. 

## Design
Base class hosting the critieria for adding sidesets and the parameters
Derived classes turning on what they support and deleting what they dont

## Impact
Cleaner code
More capabilities

**Comment by GiudGiud** [comment]
Looks like there already is a SidesetsGeneratorBase. It just needs to be expanded.

**Comment by pbehne** [comment]
I can do this.

**Comment by GiudGiud** [comment]
Awesome!
