### ISSUE TITLE
A failing test in Yak after the last libMesh update

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#2628]
After the update r25189, I saw a failing test in Yak.

I checked the output of the failing test with ncdump. The test is solving diffusion equation on part of the mesh. The boundary condition on the boundary  between the part and the rest are integrated BC.

 I found few things:
1. With the update, there is node_num_map. But it is sequentially ordered from 1, so it should not matter;
2. All values on the nodes which are interior of the part of the mesh are the same;
3. All values on the nodes which are on the boundary between the part and the rest are reduced by factor of 2.

It seems to me the setup and solving are ok. There could be an issue in the postprocessing. I believe the old values are the correct ones.

I also noticed the input dumped by MOOSE in info_records are duplicated in the [variables].

**Comment by permcody** [comment]
Old ticket - closing
