### ISSUE TITLE
fixed_point_rel_tol set but unused when disable_fixed_point_residual_norm_check=true in fixed point iterations

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#26285]
## Reason
User may set `fixed_point_rel_tol` and `fixed_point_abs_tol` in the input without realizing that they are inactive when the other parameter `disable_fixed_point_residual_norm_check` is set to true. This creates unexpected behavior for users.

## Design
We should add a warning in such cases. Ideally, those warnings or even errors should be issued through a capability requested in https://github.com/idaholab/moose/issues/19103. I am afraid that there could be lots of this kind of input defects. For now, at least we need to add this warning.

## Impact
Avoid wrong usages of parameters with fixed point iterations.

**Comment by pbehne** [comment]
I can do this.
