### ISSUE TITLE
Get reference of grain growth model parameters

### ISSUE THREAD

**Issue by Hejie-Guo** [idaholab/moose#26421]
Hello, 

I am a freshman of moose. I try to use moose to do some grain growth simulations. For some examples that moose provided, moose use parameters from a copper material provided by a reference "Schoenfelder 1997", but i did not get that reference from google. Can anybody tell me what is the title of this reference. In addition, it will be appreciated that if anybody tell me a way to get these grain growth model parameters of some spicific materials, e.g. silicon or some ferroelectric materials.

The following parameters is provided by moose.
![image](https://github.com/idaholab/moose/assets/61571563/c77cc4ed-e63e-4b02-b783-e2d83900dd33)

**Comment by lindsayad** [comment]
Hi, I believe the article you are looking for is https://link.springer.com/article/10.1023/A:1008663804495

**Comment by Hejie-Guo** [comment]
> Hi, I believe the article you are looking for is https://link.springer.com/article/10.1023/A:1008663804495

Thank you very much for your help!
