### ISSUE TITLE
JOSS Review THM - Link to documentation is not working

### ISSUE THREAD

**Issue by atismer** [idaholab/moose#26422]
The link to the documentation within 

https://github.com/idaholab/moose/blob/next/modules/thermal_hydraulics/README.md

does not work.

JOSS Review Thread: https://github.com/openjournals/joss-reviews/issues/6146

**Comment by GiudGiud** [comment]
@joshuahansel

This link is internal to INL. We'll point it somewhere else. I ll make a PR now

**Comment by joshuahansel** [comment]
I have confirmed that the new link given in #26426 works, but I'll let @atismer confirm and close this issue.

**Comment by atismer** [comment]
Perfect. Link works.
