### ISSUE TITLE
Building MOOSE with older PETSc triggers unused-variable warnings

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#26448]
## Bug Description
When using PETSc older than 3.14.0, we have to disable some functionality in the stochastic_tools module, but we don't currently disable the variables used for that functionality, and so we get unused-variable warnings for them.

## Steps to Reproduce

Configure libMesh with a pre-3.14.0 PETSc version to see the warnings; configure with `--enable-werror` as well to see the warnings prevent compilation.

See https://civet.inl.gov/job/1970494/ for an example.

## Impact
This is currently preventing modules regression testing in the "Test MOOSE min clang" recipe in libMesh CI.

**Comment by roystgnr** [comment]
Never mind; I see Alex fixed this yesterday; the fix just hasn't made it from next to devel yet.

**Comment by lindsayad** [comment]
Fixed by #26436
