### ISSUE TITLE
Create user object to dynamically update boundaries based on changing subdomain IDs

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#26455]
## Reason
We currently update moving boundaries in the `ElementSubdomainModifier` user object. The logic for `moving_boundary_name` and `complement_moving_boundary_name` is painfully complicated and cannot deal properly with multiple coincident boundaries.

## Design
Rip out the moving boundary logic and add a separate UO that performs the boundary updates in a second pass.

## Impact
Simplified logic, improved capability.

**Comment by GiudGiud** [comment]
What's the context here? Do we have time and funding to make a category of MGs work during the simulation instead of re-creating the MG capability as UOs? I can go either way

Should the code in MGs be moved (when relevant) to utils?
