### ISSUE TITLE
unrecognized variables when using output file to initialize variables

### ISSUE THREAD

**Issue by DanielYankura** [idaholab/moose#26580]
## Bug Description

I am currently working with the k-epsilon turbulence model. I have a solution for a case where the turbulence was very relaxed, but I wanted to use the output from that case as the new initial conditions for a case where turbulence is less relaxed. vel_x copied over just fine however, I get errors for every other variable saying "Unrecognized variable __ in variables to copy". If I initialize vel_y, vel_z, and pressure instead of copying them, it will then give me the same error for my TKE and TKED variables.

## Steps to Reproduce

I ran test_pipe.i, renamed the output file to test_pipe_input.e, and in the mesh block in test_pipe_read_in.i I set file = test_pipe_input.e
When I then run test_pipe_read_in.i I get the error mentioned above.
[test pipe files.zip](https://github.com/idaholab/moose/files/13969179/test.pipe.files.zip)

## Impact

I will likely need this feature to work in order for me to do tests with less turbulence relaxation.

**Comment by GiudGiud** [comment]
This is a problem coming from multi-system + exodus restart from my limited investigation
