### ISSUE TITLE
Incorrect results for general field transfer test

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#26605]
## Bug Description
The test `transfers/general_field/user_object/subdomain.2d_overlay/projection_needed_receiving` is producing the following solution:
<img width="2253" alt="Screenshot 2024-01-19 at 8 10 07 AM" src="https://github.com/idaholab/moose/assets/23108676/b309ee91-2cf4-4c38-97b7-5f8c88139d4c">
Here, the right side corresponds to the current gold results. The large 5x5 domain is the main application, and the 3 small 5x5 domains correspond to 3 sub-applications. These are supposed to have the solution transferred from a certain block of the main application - the lower left corner (3 horizontal by 2 vertical), with a -1 value being used as an extrapolation constant outside of the domain.

The left side of the image corresponds to the same test run but moving the `to_main` block to the top of the `AuxVariables` block in `sub.i`. This input file ordering should have no effect on the solution, so this is a second red flag for the test. This was discovered in https://github.com/idaholab/moose/issues/26164.

## Steps to Reproduce
Run the above test and observe the results.

## Impact
This is a significant bug that may be producing incorrect results in user models.

**Comment by pbehne** [comment]
I can look into this.

**Comment by GiudGiud** [comment]
Awesome

**Comment by pbehne** [comment]
I was able to reproduce the issue with a simplified input (see attached).

In `sub.txt` the result of the transfer depends on what order `unused_auxvariable` and `from_main_elem` appear in the `AuxVariables` block.

I traced the issue to [this](location) in `MultiAppGeneralFieldTransfer`. After the projection, the variable `f` contains 32 points when `from_main_elem` is listed first in the input and 72 points when `unused_auxvariable` is listed first. I checked the variable naming and numbering leading up to the creation of the `GenericProjector`, and this all looks good to me.

@roystgnr, please let me know what you can find!

[main.txt](https://github.com/idaholab/moose/files/14795815/main.txt)
[sub.txt](https://github.com/idaholab/moose/files/14795817/sub.txt)

**Comment by GiudGiud** [comment]
the this link is not working btw

**Comment by pbehne** [comment]
> the this link is not working btw

Updated with https://github.com/idaholab/moose/blob/devel/framework/src/transfers/MultiAppGeneralFieldTransfer.C#L756. Thanks!

**Comment by roystgnr** [comment]
I see the bug.

In `FEMContext::find_hardest_fe_type()`, where we're figuring out how much quadrature we're going to need later, we do a check that loops over all variables in `_active_vars` if that restriction has been provided (as it is in this case, where it's {1} when we're projecting onto variable 1) or over all variables in the system otherwise ... but we only do that loop *after* initializing the return value based on variable 0.  This should be a quick fix, if fixing it doesn't trip any regression tests...

**Comment by GiudGiud** [comment]
>  if fixing it doesn't trip any regression tests...

it will trip the moose test for the transfer unfortunately

**Comment by pbehne** [comment]
It should be pretty straightforward to re-gold any obvious failures, right?

**Comment by GiudGiud** [comment]
yeah. Though for CI I think we ll first need to skip them?

**Comment by pbehne** [comment]
In my experience, I just commit and push the new gold files and it works. However, I can definitely see it being more complicated as the patch is being made in libmesh and not with within MOOSE itself.

**Comment by joshuahansel** [comment]
> yeah. Though for CI I think we ll first need to skip them?

I don't understand the problem. Is this for libmesh CI or something? For MOOSE CI, you'd just re-gold whenever you update the libmesh submodule, right?

**Comment by GiudGiud** [comment]
I think so for libmesh CI
