### ISSUE TITLE
Eigenvalue executioner normalization tolerance

### ISSUE THREAD

**Issue by smpark7** [idaholab/moose#26721]
## Bug Description
I'm running a transient thermal-hydraulics main app and eigensolver neutronics sub app with the neutron flux set to normalize to a fixed power output.

These input files ran without issues with the `NonlinearEigen` executioner, but now with the new `Eigenvalue` executioner, they randomly fail at the normalization step with the following error message:
`Can not scale eigenvector to the required factor 1e+07 please check if postprocessor is defined on only eigen variables`

By random, I mean different simulations fail at different timesteps. Some simulations are able to run to completion.

I think it's due to the use of absoluteFuzzyEqual on line 462 in `Eigenvalue.C` with a default fixed tolerance of 1e-16 as opposed to using a relative tolerance of 1e-10 in `EigenExecutionerBase.C` for `NonlinearEigen`.

## Steps to Reproduce
Set a high normalization factor for an EigenProblem and run it multiple times.

## Impact
Random failures of EigenProblems with large normalization factors.

**Comment by YaqiWang** [comment]
So it should be relative fuzzy equal?

**Comment by smpark7** [comment]
Yes I believe so

**Comment by smpark7** [comment]
I'll recompile with relativeFuzzyEqual and see if it fixes the issue

**Comment by YaqiWang** [comment]
Should be a quick fix then. Typically the dependency of the normalization postprocessor on the scaling factor is linear, thus we only need to go through that loop once.

**Comment by smpark7** [comment]
My (limited) testing yielded about 10% failure rate with absoluteFuzzyEqual and no failures with relativeFuzzyEqual. I set the normalization factor to be 1e10. I ran each config only twenty times so it's not quite definitive evidence.
