### ISSUE TITLE
Add common functor name parameter description

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#26737]
## Reason
Many users do not know what a functor is, so they do not know what can be done with parameters of type `MooseFunctorName`.

## Design
Store a common description string somewhere. Maybe as a public static method in `FunctorInterface`?:
```
static std::string getFunctorDescription() const
{
return "A functor is any of the following: a variable name, a functor material property name, a function name, a post-processor name, or a constant.";
}
```
And then use it like this:
```
params.addRequiredParam<MooseFunctorName>("functor", "The functor to impose. " + getFunctorDescription());
```
Or this instead:
```
params.addRequiredParam<MooseFunctorName>("functor", addFunctorDescription("The functor to impose"));
```
which could be smarter with the ending period/space.

## Impact
Better user experience. Greater usage of functor parameters.

**Comment by GiudGiud** [comment]
I m not sure if this will be possible, because a moosefunctorName is a string in the backend, but using templating would be better

So modifying the addParam template to include this extra text only when the parameter is MooseFunctorName or std::vector of MooseFunctorName

**Comment by GiudGiud** [comment]
Yup a template specialization sounds right. I was actually thinking we could use a compile time std::same_if in the regular template. 

It doesn't hurt to have it everywhere.

**Comment by lindsayad** [comment]
I think pursuing @GiudGiud's idea is a good idea 😄 . It would be less painful for you @joshuahansel. Also anyone who develops new objects after your PR adding `getFunctorDescription` everywhere wouldn't have to think to add `getFunctorDescription`. Definitely best from a Don't Repeat Yourself standpoint. If at some point someone raises a complaint about the uniformity, then I think we could consider a change
