### ISSUE TITLE
Rename BoundaryFluxPP

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#26755]
## Bug Description
It's specific to RDG. The name is way too general for what it can do. 

## Steps to Reproduce
Use it, see it not work on anything but RDG. 

## Impact
Confuse users, waste user support resources
See https://github.com/idaholab/moose/discussions/26745

**Comment by lindsayad** [comment]
Does this come from a discussion?

**Comment by GiudGiud** [comment]
yup

**Comment by lindsayad** [comment]
can you ref it here? it's annoying that github doesn't automaticially cross reference discussions
