### ISSUE TITLE
Add `MooseEnum` support to command line parameters

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#26763]
## Reason
It would be useful to be able to add a command line parameter that supports `MooseEnum`.

## Design
Modify `InputParameters` and `CommandLine` to support

```
params.addCommandLineParameter<MooseEnum>(...)
```

## Impact
New capability

**Comment by YaqiWang** [comment]
This issue is duplicating https://github.com/idaholab/moose/issues/26194.

**Comment by loganharbour** [comment]
Thanks @YaqiWang!
