### ISSUE TITLE
Consider a FunctionAbuseAux or a FunctionVariableArgumentAux or something similar that lets us apply functions to variables

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#26784]
## Reason
People legitimately constantly try to use Functions with variables. Some modules objects even do that, though less and less with the rework of the heatconductionMaterial

It's confusing in a way that your average function should only depend on x y z t (some depend on PPs) when many users want f(T). There are also great options for loading CSVs with variables so users love that.

Maybe it would be less confusing is to have an auxkernel that computes an auxvariable and uses some expression to do that. The ParsedAux does that in its own limited (parsed) way. It s well within the role of an auxkernel, though it does involve the abuse of a function

## Design
A FunctionAux uses x y z t, a FunctionWithVariableArgumentsAux could have
```
x = var1
y = var2
z = var3
t = var4
```
and return `f(x,y,z,t) = f(var1, var2, var3, var4)` (t usually flipped but oh well)
and default to 0 for missing arguments? or x y z t if not specified. Or no default

## Impact
Maybe helpful for users?
https://github.com/idaholab/moose/discussions/26752#discussioncomment-8424134

**Comment by lindsayad** [comment]
I feel like `ParsedMaterial` and `DerivativeParsedMaterial` already cover this

**Comment by GiudGiud** [comment]
I dont see how? Can we specify `f(T, x)` in a parsed expression? with f a moose function?

**Comment by lindsayad** [comment]
Looking more closely at your OP I see that you mean you want to generally be able to use function classes with variables, not just the one `Parsed` sub-class of function, so I retract my previous post.

I would like a title like `FunctionAbuseAux` since if the variable is a nonlinear variable, the user is not getting any derivative information

I think @dschwen should weigh-in on this topic

**Comment by GiudGiud** [comment]
Addressed by https://github.com/idaholab/moose/pull/27081
