### ISSUE TITLE
Improper reporting ID assignment in PatternedHexMeshGenerator

### ISSUE THREAD

**Issue by NamjaeChoi** [idaholab/moose#26862]
## Bug Description
Reporting ID assignment in `PatternedHexMeshGenerator` is not functioning as intended.

If `assign_type = cell`, multiple contiguous IDs are mixed in a single pin:

<img width="661" alt="Screenshot 2024-02-21 at 1 18 03 PM" src="https://github.com/idaholab/moose/assets/116297520/784fe7cf-a437-470c-832d-f4da00d97b8f">

If `assign_type = pattern`, a very weird ID pattern is generated:

<img width="661" alt="Screenshot 2024-02-21 at 1 18 53 PM" src="https://github.com/idaholab/moose/assets/116297520/7a49739a-4428-4eeb-9b28-a7b652ef72f7">

## Steps to Reproduce
Observe `local_pin_id` in the following mesh input.

```
pin_radius = 1
hp_radius = 1.1
gap_thickness = 0.05
pin_pitch = 3.4
asy_pitch = 32

[Mesh]
  [fuel_inner]
    type = PolygonConcentricCircleMeshGenerator
    num_sides = 6
    num_sectors_per_side = '2 2 2 2 2 2'
    background_intervals = 1
    background_block_ids = '6'
    polygon_size = ${fparse pin_pitch / 2}
    polygon_size_style = 'apothem'
    ring_id_name = 'ring_id'
    ring_id_assign_type = ring_wise
    ring_radii = '${pin_radius} ${fparse pin_radius + gap_thickness}'
    ring_intervals = '3 1'
    ring_block_ids = '1 2 3'
  []
  [hp_inner]
    type = PolygonConcentricCircleMeshGenerator
    num_sides = 6
    num_sectors_per_side = '2 2 2 2 2 2'
    background_intervals = 1
    background_block_ids = '6'
    polygon_size = ${fparse pin_pitch / 2}
    polygon_size_style = apothem
    ring_radii = '${hp_radius} ${fparse hp_radius + gap_thickness}'
    ring_intervals = '1 1'
    ring_block_ids = '4 5'
  []
  [assembly_inner]
    type = PatternedHexMeshGenerator
    inputs = 'fuel_inner hp_inner'
    background_intervals = 1
    background_block_id = 6
    hexagon_size = ${fparse asy_pitch / 2}
    hexagon_size_style = apothem
    id_name = 'local_pin_id'
    assign_type = cell
    pattern = '0 0 0 0 0 0;
              0 1 0 1 0 1 0;
             0 0 0 0 0 0 0 0;
            0 1 0 1 0 1 0 1 0;
           0 0 0 0 0 0 0 0 0 0;
          0 1 0 1 0 1 0 1 0 1 0;
           0 0 0 0 0 0 0 0 0 0;
            0 1 0 1 0 1 0 1 0;
             0 0 0 0 0 0 0 0;
              0 1 0 1 0 1 0;
               0 0 0 0 0 0'
  []
[]
```

## Impact
Cannot generate reporter ID properly.

**Comment by yjung-anl** [comment]
In the current implementation, the background block ID numbers for pins and assembly should be differ.
That is because the code differentiates the background regions of pins and assembly based on the block IDs in the ID assignment.
I think it would be better to update to allow using the same block IDs for pins and assembly.

**Comment by yjung-anl** [comment]
![image](https://github.com/idaholab/moose/assets/73304529/3a9a9306-257d-4ae4-8288-1bd4bf2d3f52)
