### ISSUE TITLE
Adding additional references to the grain growth documentation page in the phase field module

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#26890]
## Reason
Professor LQ Chen reached out and correctly pointed out that currently we reference the Moelans [2008] paper for our grain growth model, but that that paper actually pulled the model from his earlier publications. 

## Design
He has asked that we reference two of his papers as well: 
Chen, L.Q. And W. Yang, Computer-Simulation Of The Domain Dynamics Of A Quenched System With A Large Number Of Nonconserved Order Parameters - The Grain-Growth Kinetics. Physical Review B, 1994. 50(21): P. 15752-15756.
 Chen, L.Q., A Novel Computer-Simulation Technique For Modeling Grain-Growth. Scripta Metallurgica Et Materialia, 1995. 32(1): P. 115-120.

## Impact
This is a very minor change. It is only adding two references to a documentation page. There will be no impacts on anything else.

**Comment by laagesen** [comment]
Thanks for bringing this up @tonkmr, we will get it added to the doco
