### ISSUE TITLE
Mass lumping

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#2689]
MOOSE would be significantly improved if mass lumping were possible.

I explain what i mean by mass lumping in modules/richards/doc/theory.pdf, section 7.4

Shortly i'll add a simple diffusion-equation example demonstrating that MOOSE yields incorrect results without mass lumping.

In my opinion the lack of mass lumping is a serious defect in MOOSE, and i'm certain it has highly negative consequences for many simulations involving the nonlinear heat equation, which surely appears in many different applications.  Not only does MOOSE yield incorrect results, but convergence can be severely impacted as variables go into physically-impossible regions (negative temperature, for instance).

I know this is a big task, but one that shouldn't be neglected!

**Comment by andrsd** [comment]
@WilkAndy Can you look at https://github.com/andrsd/moose/tree/coupled-nodal-du-dot ? I implemented mass lumping and seems to fix this problem you had with the input posted above. I am not going to open an PR yet. I'd like you to test it out.

**Comment by WilkAndy** [comment]
Thanks @andrsd , upon quick inspection this looks good, but i'd like to do some more testing.  I doubt i'll have time to do this till next tuesday.   ok?

**Comment by andrsd** [comment]
More testing is always a good thing. Take your time. We do not need it as much as you do ;-) and I am busy with something else - I did this in my "free" time ;-D
