### ISSUE TITLE
Add an animation for the laser welding simulation

### ISSUE THREAD

**Issue by hugary1995** [idaholab/moose#26925]
## Reason

The element subdomain modifiers have existed for a while, but we haven't had any animations showcasing its capabilities.

## Design

Add an animation of a simulation that relies on the element subdomain modifiers.

## Impact

Tell people MOOSE can do this!

**Comment by hugary1995** [comment]
sorry, I just filled out the issue template. Once we have #25125 we will be able to force people to fill out these fields.

**Comment by jiangwen84** [comment]
@hugary1995  This looks nice. We should probably also create a page on the MALAMUTE website to show those animations!

**Comment by lindsayad** [comment]
thanks @hugary1995 !

**Comment by GiudGiud** [comment]
dammit Gary!
