### ISSUE TITLE
Compute Jacobian/Residual on a subset of the entire mesh.

### ISSUE THREAD

**Issue by maxnezdyur** [idaholab/moose#27135]
### Motivation

For hyper reduced ROM, a subset of jacobian and residual entries need to be computed but the rest are not needed. Need the ability to tell MOOSE to only compute the J/R on those elements and nodes. This includes not computing material properties on these elements either.

### Design

Possible ways: 
1) Mesh Divisions system and block restricting the kernels. 
2) Add ability directly into MooseMesh
For example:
``` 
void
MooseMesh::setActiveLocalElementRange(ConstElemRange * range)
{
  if (!range)
    _active_local_elem_range = nullptr;
  else
    _active_local_elem_range = std::make_unique<ConstElemRange>(*range);
}
void
MooseMesh::setLocalNodeRange(ConstNodeRange * range)
{
  if (!range)
    _local_node_range = nullptr;
  else
    _local_node_range = std::make_unique<ConstNodeRange>(*range);
}
```

### Impact

Increases the speed up of ROM. Using the MooseMesh example, the speed-up of my ROM solve(ignoring mesh generation and outputting) went from 10 -> 670.

**Comment by maxnezdyur** [comment]
@GiudGiud

**Comment by GiudGiud** [comment]
@grmnptr @lindsayad

**Comment by lindsayad** [comment]
I'm supportive of something like those APIs. However, I think they should live on the problem or the system since this is an intrinsically algebraic scheme, not a geometric one so the mesh doesn't need to know anything about it. And I would steer clear of the words "active" which is about mesh adaptivity and "local" which is about element processor IDs

**Comment by maxnezdyur** [comment]
The above is probably the minimal work needed for system to work. Looking at the Jacobian portion, in `NonlinearSystemBase::computeJacobianInternal`, we use `ConstNodeRange & range = *_mesh.getLocalNodeRange();` and  `ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();` to determine which nodes and elements to compute the jacobian entries for. Which is why the words active and local were needed. Since we only compute jacobian entries on the active children of a AMR mesh and the processor has to own the element. Would you prefer an API like:
``` 
  /**
   * Form a Jacobian matrix using the specified ranges.
   */
  virtual void computeJacobianRange(const NumericVector<Number> & soln,
                               SparseMatrix<Number> & jacobian,
                               const unsigned int nl_sys_num,
                           ConstNodeRange node_range,
                          ConstElemRange element_range);

```
The only problem, would be a bit of code copying since the `computeJacobianInternal` would be the same except with taking a supplied range instead of the getting it from the mesh.

**Comment by lindsayad** [comment]
You can modify the code in the relevant system routines. For instance instead of calling `ConstElemRange & elem_range = *_mesh.getActiveLocalElementRange();`, it might call `ConstElemRange & elem_range = _fe_problem.getAlgebraicElementRange()`
