### ISSUE TITLE
No error thrown if RenameBoundaryGenerator and surface number over 2^15

### ISSUE THREAD

**Issue by pferney05** [idaholab/moose#27175]
### Bug Description

The surface id are limited to 2^15. It would be nice to have an error thrown when we rename with higher values instead of the code randomly ceiling our input values. That took me 1 hour to debug my geometry because of that.

### Steps to Reproduce

run that :

`[Mesh]`
`  [refl0]`
`    type = CartesianMeshGenerator`
`    dim = 2`
`    dx = ' 4.0 3.0 2.0'`
`    dy = ' 2.0 3.0 4.0'`
`    ix = ' 4 3 2'`
`    iy = ' 2 3 4'`
`    subdomain_id = '102 101 100 102 101 101 102 102 102 '`
`  []`
`  [refl0_pre]`
`    type = RenameBoundaryGenerator`
`    input = refl0`
`    old_boundary = '0 1 2 3'`
`    new_boundary = '40000 40001 40002 40003'`
`  []`

### Impact

User can debug more quickly.

**Comment by pbehne** [comment]
If assigned to this, I can work on it between other issues.

**Comment by lindsayad** [comment]
@pferney05 what institution are you with? I'm just trying to determine what project to throw this in
