### ISSUE TITLE
Create error that represents a known defect

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#27170]
### Motivation

Many of the reported defects that are known could and should trigger errors instead of producing undesirable behavior with zero exit codes.

### Design

Add a `mooseDefect()` method that is similar to `mooseError()`, but requires an issue number (in the function call) in addition to the message.

### Impact

Will improve communication of defective code paths and undesired behavior.

**Comment by GiudGiud** [comment]
@lindsayad fyi this was the output of that meeting

**Comment by GiudGiud** [comment]
Simulation completes successfully with the wrong results. The problem has been identified and there is an issue, but the faulty region of the code has not been protected with an error statement.

**Comment by loganharbour** [comment]
Okay, now that https://github.com/idaholab/moose/pull/26945 is in I'll get to this.

**Comment by lindsayad** [comment]
I might change "valid" to "non-zero"
