### ISSUE TITLE
Do not disable backups in `FullSolveMultiApp`

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#27223]
### Motivation

The parameter `no_backup_and_restore` in `FullSolveMultiApp` causes issues when you actually need to have something backed up at the end of the solve. For example, you have a steady state solve with `Outputs/checkpoint=true` and want to restart that state into a transient, even though you don't want to use the state within inner iterations.

 Or, if you're doing picard within timesteps, your solve is killed, and you want to recover at the end of that timestep on a new run.

### Design

Replace `no_backup_and_restore` with `no_restore`. Keep the behavior same where you don't do the restore, but always do the backup.

### Impact

Minor parameter change. Will require changing a few tests, but the behavior should be the same.

**Comment by loganharbour** [comment]
FYI @NamjaeChoi; looking for your thoughts @YaqiWang. This resolves the issue Namjae found.

**Comment by NamjaeChoi** [comment]
Thank you for looking into this issue!

**Comment by NamjaeChoi** [comment]
Should close #27178 upon resolution.
