### ISSUE TITLE
Time derivatives inaccurate in postprocessing for linear implicit solves

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#27233]
### Bug Description

Reported by @nmnobre, if you perform a solve with `solve_type = LINEAR` and attempt to postprocess the time derivatives, you will most likely see inaccurate results (unless you get lucky and use the on-the-fly functor calcs)

### Steps to Reproduce

Run test in https://github.com/idaholab/moose/pull/27197/commits/b48f5e4916637ed1eff3d9f37c66a0545c884ab0

### Impact

Bad results. Users shan't like bad results

**Comment by loganharbour** [comment]
Is this closed? Just came across this when fixing mockingbird

**Comment by lindsayad** [comment]
Yes, closed by https://github.com/idaholab/moose/pull/27231
