### ISSUE TITLE
Enhancements to automatic wall time checkpoints

### ISSUE THREAD

**Issue by pbehne** [idaholab/moose#27240]
Following the initial implementation of automatic wall time checkpoints in #26588, users have requested enhancements to the feature. These include:

- [x] Adding an easy way to turn off automatic checkpointing
- [x] Output to console when writing auto checkpoint
- [x] New integration test to verify that subApps are not auto-checkpointed
- [x] New regression test for minimum wall time (where checkpoint write time exceeds wall time interval)
- [x] Adjust default wall time interval based on community feedback
- [x] Ensure that XDR support is enabled before creating auto-checkpoints, create an info message if it is not (since it will deviate from a normal run).

**Comment by pbehne** [comment]
@lindsayad, I can work on this, please assign me.

**Comment by pbehne** [comment]
#26682 seems related. PR #27268 changes the checkpoint/mesh system to use ascii (.cpa) format instead of binary format (.cpr). @GiudGiud, feel free to weigh in while the PR is open. Maybe we close multiple issues.

**Comment by GiudGiud** [comment]
Seems like a good idea to me.
