### ISSUE TITLE
The `residual_and_jacobian_together = true` conflicts with `DiracKernels`

### ISSUE THREAD

**Issue by dewenyushu** [idaholab/moose#27258]
### Bug Description

The `residual_and_jacobian_together = true` option in the `Executioner` would overwrite DiracKernels' contributions to the system thus causes solve failure without a warning or error.  

### Steps to Reproduce

The issue can be reproduced by running the following:

```
[Mesh]
  type = GeneratedMesh
  dim = 1
  nx = 10
[]

[Variables]
  active = 'u'
  [./u]
    order = FIRST
    family = LAGRANGE
  [../]
  [./v]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./diff]
    type = Diffusion
    variable = u
  [../]
[]

[DiracKernels]
  [./point_source1]
    type = ConstantPointSource
    variable = u
    value = 1.0
    point = '0.2 0 0'
  [../]
  [./point_source2]
    type = ConstantPointSource
    variable = u
    value = -0.5
    point = '0.7 0 0'
  [../]
[]

[BCs]
  [./left]
    type = DirichletBC
    variable = u
    boundary = left
    value = 0
  [../]
  [./right]
    type = DirichletBC
    variable = u
    boundary = right
    value = 1
  [../]
[]

[Executioner]
  type = Steady

  solve_type = 'PJFNK'
  ###### Note: change this back to `false` and it will converge
  residual_and_jacobian_together = true

[]

[Outputs]
  file_base = 1d_out
  exodus = true
[]

```

### Impact

Setting `residual_and_jacobian_together = true` should not affect numerical outcomes or convergence patterns when used alongside `DiracKernels`. Alternatively, users should expect an error while having this setting in their inputs. Resolving this issue would improve the code robustness.

**Comment by maxnezdyur** [comment]
For tracking, duplicate issue: #26938

**Comment by lindsayad** [comment]
We'll keep issue discussion consolidated on #26938
