### ISSUE TITLE
Modal Analysis Example

### ISSUE THREAD

**Issue by maxnezdyur** [idaholab/moose#27295]
### Motivation

I need the ability to perform a modal analysis of a linear elastic objects. For a simple test I wanted to recreate the results here.
https://comet-fenics.readthedocs.io/en/latest/demo/modal_analysis_dynamics/cantilever_modal.html

In the input file provided, when viewing the mode deformations the results seem to match the examples but the eigenvalues are off. 
When changing the coefficient for the ADCoefReaction it does not change the eigenvalues (this should be similar to changing density). Also as I refine the mesh, the eigenvalues change dramatically with mesh refinement. For example if I increase the number of elements by a factor of 2 my eigenvalues all decrease by a factor of 2. 

### Design

```
index = 0
[Mesh]
  type = GeneratedMesh
  elem_type = HEX8
  dim = 3
  xmin = 0
  xmax = 20
  nx = 100
  ymin = 0
  ymax = 1.
  ny = 10
  zmin = 0
  zmax = 0.5
  nz = 10
[]
[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

[Variables]
  [disp_x]
  []
  [disp_y]
  []
  [disp_z]
  []
[]

[Kernels]
  [reaction_x]
    type = ADCoefReaction
    variable = disp_x
    extra_vector_tags = 'eigen'
    coefficient = 1e-3
  []
  [reaction_y]
    type = ADCoefReaction
    variable = disp_y
    extra_vector_tags = 'eigen'
    coefficient = 1e-3
  []
  [reaction_z]
    type = ADCoefReaction
    variable = disp_z
    extra_vector_tags = 'eigen'
    coefficient = 1e-3
  []
  [sdx]
    type = TotalLagrangianStressDivergence
    variable = disp_x
    component = 0
  []
  [sdy]
    type = TotalLagrangianStressDivergence
    variable = disp_y
    component = 1
  []
  [sdz]
    type = TotalLagrangianStressDivergence
    variable = disp_z
    component = 2
  []
[]

[BCs]
  [dirichlet_x]
    type = DirichletBC
    variable = disp_x
    value = 0
    boundary = 'left'
  []
  [dirichlet_y]
    type = DirichletBC
    variable = disp_y
    value = 0
    boundary = 'left'
  []
  [dirichlet_z]
    type = DirichletBC
    variable = disp_z
    value = 0
    boundary = 'left'
  []
  [dirichlet_x_e]
    type = EigenDirichletBC
    variable = disp_x
    boundary = 'left'
  []
  [dirichlet_y_e]
    type = EigenDirichletBC
    variable = disp_y
    boundary = 'left'
  []
  [dirichlet_z_e]
    type = EigenDirichletBC
    variable = disp_z
    boundary = 'left'
  []
[]

[Materials]
  [elastic_tensor]
    type = ComputeIsotropicElasticityTensor
    youngs_modulus = 1e5
    poissons_ratio = 0.0
  []
  [compute_stress]
    type = ComputeLagrangianLinearElasticStress
    large_kinematics = false
  []
  [compute_strain]
    type = ComputeLagrangianStrain
  []

[]
[Executioner]
  type = Eigenvalue
  solve_type = KRYLOVSCHUR
  which_eigen_pairs = SMALLEST_MAGNITUDE
  eigen_problem_type = SLEPC_DEFAULT
  n_eigen_pairs = 10
  n_basis_vectors = 30
  petsc_options = '-eps_view'
  petsc_options_iname = '-pc_type -st_type -eps_target '
  petsc_options_value = 'lu sinvert 0'
[]

[VectorPostprocessors]
  [eigen]
    type = Eigenvalues
    execute_on = TIMESTEP_END
  []
[]

[Problem]
  type = EigenProblem
  active_eigen_index = ${index}
[]

[Outputs]
  console = true
  exodus = true
  csv = true
  execute_on = 'timestep_end'
[]
```

### Impact

This is would be a great addition to MOOSE, since modal analysis is use frequently in a lot of fields.

This is an example of the fourth mode that matches the resource linked above.
https://github.com/idaholab/moose/assets/22859100/6bf71125-6475-4d27-948f-e4b7608419e5

**Comment by maxnezdyur** [comment]
@lindsayad Thanks for looking into this!

**Comment by maxnezdyur** [comment]
On thing I forgot to mention is that for the DirichletBC in the header I added 
`  virtual Real computeQpJacobian() override { return 1.0e6; }`
What this does it shift the previous 1 eigenvalues cause by the BC. Since we don't condense the system this is an easy stopgap. All the problems mentioned above happen even if I don't add the line .

**Comment by maxnezdyur** [comment]
Problem is fixed with not using `eigen_problem_type = SLEPC_DEFAULT`.

**Comment by lindsayad** [comment]
I'm going to reopen this since it signals a very easy way to catch users unaware. We should error out if a user attempts to run a standard eigenvalue problem with eigen residual objects present

**Comment by ravi-srs** [comment]
Hi All,
Is there a possibility to use glued contact in modal analysis?
    primary = 411
    secondary = 421
    model = glued
    formulation = penalty
  
I get error:
*** ERROR ***
Need a system matrix

Modal analysis runs fine when contacts are disabled.
