### ISSUE TITLE
Correct minimum requirements

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#27449]
### Motivation

There are many cases where we still reference GCC 7.5 as a valid minimum compiler. This is not the case anymore due to the std::filesystem requirements that require >= GCC 8.0.

### Design

Update minimum requirements and make them more obvious.

### Impact

Will reduce strain for users with installation.

**Comment by loganharbour** [comment]
I think that we should probably just add the minimum requirements to the main splash page on https://mooseframework.inl.gov/getting_started/installation/index.html. What do you think @milljm ?

**Comment by milljm** [comment]
According to this: https://gcc.gnu.org/projects/cxx-status.html#cxx17 I am suggestion we call on GCC 9.x as the minimum. However, @lvkas521424 mentioned that they needed to install 10.x?

Asking the question; what should the new minimum be?

**Comment by lvkas521424** [comment]
I use gcc10. x because we happen to deploy this version on the server. As a developer primarily focused on Fortran language, I personally believe that the lower the version, the better. After all, many of our program's kernels are still f77.

**Comment by loganharbour** [comment]
> I personally believe that the lower the version, the better

Unfortunately this isn't possible when trying to enable the use of modern features with c++. We use the lowest version that we can to still support the majority of the c++17 features, which is GCC 9.
