### ISSUE TITLE
Documentation missing for `coupled_variables` in `ParsedMaterial`

### ISSUE THREAD

**Issue by aprilnovak** [idaholab/moose#27527]
### Motivation

A doc string is missing for `coupled_variables` in `ParsedMaterial`: https://mooseframework.inl.gov/source/materials/ParsedMaterial.html

### Design

Add a doc string.

### Impact

Enhanced user experience.

**Comment by GiudGiud** [comment]
So this is on deprecation of a coupled_var. I ll see if I can patch addDeprecatedCoupledVar

**Comment by aprilnovak** [comment]
Oh sorry, I didn't realize it was for something deprecated -- probably not a huge deal to ignore this issue then :)

**Comment by GiudGiud** [comment]
It's the new name that is missing the docstring, so it's a big deal.
 I already found the fix, we will be good here soon
