### ISSUE TITLE
Functional expansion tools module is not properly registering its objects in downstream apps

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#27637]
### Bug Description

FET objects could not be used by apps compiled with the FET module

### Steps to Reproduce

Create or use an app
Add FET to the Makefile
Watch it not register FET objects by either running an input with FET objects or looking at the syntax dump

### Impact

Users needed to rely on combined executable

**Comment by lindsayad** [comment]
Is somebody actually trying to use the module?!

**Comment by GiudGiud** [comment]
yes! at MIT a student looking at openmc-moose coupling

**Comment by GiudGiud** [comment]
but goes to show how much it's used

**Comment by lindsayad** [comment]
indeed. This is one of the earliest projects I assisted on when I joined the MOOSE team. Hasn't been touched by anyone since

**Comment by GiudGiud** [comment]
yeah there s a ton left to do there. 
I dont think Zernike are actually what we want to represent these fields on the fuel pins, and there's plenty to do for other fuel types (TRISO, lightbridge, msrs ...)

**Comment by lindsayad** [comment]
it would be awesome to see more development/use

**Comment by GiudGiud** [comment]
might be able to write a CINR from the joint appointment maybe
@bforget
