### ISSUE TITLE
Data Driven Mesh Generation feature unavailable for other applications

### ISSUE THREAD

**Issue by olinwc** [idaholab/moose#27977]
### Bug Description

I am running `RadiationTransportApp` and hit the error

```
This application does not support data-driven mesh generation.

This generation is an advanced feature and must be enabled on the application via the 'allow_data_driven_mesh_generation' parameter.
```

Looks like the capability can either just be allowed for all applications or `RadiationTransportApp` also needs to be able to use data driven mesh generation.

### Steps to Reproduce

Run the `equivalent_core_mesh` tests using the `RadiationTransportApp`

### Impact

An annoyance since the inputs do work using Griffin.

**Comment by lindsayad** [comment]
Do the directions given by the error not work?

**Comment by olinwc** [comment]
@GiudGiud recommended opening this issue but it looks like we can change radiation transport app to get rid of the error.

**Comment by GiudGiud** [comment]
I did not recall it was with an input params. This can be closed
