### ISSUE TITLE
MultiMooseEnum could have better documentation

### ISSUE THREAD

**Issue by pbehne** [idaholab/moose#28134]
While working on an issue that utilizes (in the wrong way) objects of type `MultiMooseEnum`, I lost a bit of time because I didn't fully understand what these enums are and how they are used. The biggest point of confusion for me is the difference between `_item` (all possible values the variable can take) and `_current` (the subset of `_item` that the variable is actually set to). The documentation of each method for this class that affects one of `_item` and `_current` could be improved to differentiate which variable is affected.

Hopefully this will prevent others from making the same assumptions/mistakes that I made in the future.

**Comment by GiudGiud** [comment]
Fully agreed!
