### ISSUE TITLE
PropertyReadFile allows a CSV file for property_file_name

### ISSUE THREAD

**Issue by caolwec** [idaholab/moose#28190]
### Motivation

This request is motivated by a need to possibly read many files in our moose application to our microreactor simulation.

### Design

I would like to suggest a change to the PropertyReadFile for more convenience? - The 'prop_file_name' is for a list of property file names now, it would be better in case there are many property files if it allows a CSV file where all the property files names are listed in a column.

### Impact

This is a suggested function enhancement not expected to impact existing code features or functions

**Comment by GiudGiud** [comment]
@caolwec this was added last week btw. 
Please let me know if there are any issues
