### ISSUE TITLE
Add dimensionality reduction example for 2D meltpool simulation to combined module

### ISSUE THREAD

**Issue by grmnptr** [idaholab/moose#28200]
### Motivation

We need an interesting problem as an example for dimansionality reduction, this could be a good stepping stone for testing dimensionality reduction techniques (combined with ROMs). 

### Design

Add example to combined module.

### Impact

Useful presentation of current workflow and good starting point with other dimensionality reduction and reduced-order modeling techniques.

**Comment by lindsayad** [comment]
which melt pool sim?

**Comment by grmnptr** [comment]
2D FE from the NS module. I'll change the material to 316L, alter some laser parameters and modify the domain for longer scans.

**Comment by lindsayad** [comment]
Sounds awesome!
