### ISSUE TITLE
Handle material properties in a better way for EigenKernel

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#2821]
I create this issue to remind us that currently we rely on the developers to correctly implement their material properties used by EigenKernel, showed in one of the tests under test/tests/executioners/eig_executioners/ne_mat.i. We could create two versions of a material when its parameter 'implicit' is valid. Then the implicit version couples all current values, while the explicit version couples all old values. Because they could be active at the same time, they should operate on different material properties with different names. Then in the EigenKernel, when _is_implicit is true, we use the implicit version of properties, otherwise use the other version.

**Comment by YaqiWang** [comment]
@fdkong I guess this super old issue can be closed with our new eigen solver.

**Comment by YaqiWang** [comment]
@fdkong I want to ask you about this again. Today's @dschwen post on Slack reminded me about this one.

**Comment by fdkong** [comment]
We do not have this issue with new eigenvalue system. if I understand correctly

**Comment by YaqiWang** [comment]
That is my thought too since we are using tagging for A and B. When doing power iteration, B (or eigen kernels) are working on a tagged vector being set to the current solution, thus material properties used by B are based on that tagged vector. If what I said is correct, we can close this issue. @fdkong

**Comment by fdkong** [comment]
Yes, you are right. New implementation is cleaner on this
