### ISSUE TITLE
Enable Terminators to simply issue warning/info without aborting/failing current time step

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#28273]
### Motivation

I would like to issue a warning if a particular postprocessor meets a certain criteria.
Currently, a Terminator with `error_level = warning` either aborts (`fail_mode = HARD`) or fails the current time step (`fail_mode = SOFT`). If we added another option (`fail_mode = NONE`), the Terminator could fully satisfy this need.

### Design

Add the `fail_mode = NONE` option which would bypass `terminateSolve` or `failStep`.

### Impact

Ability for Terminators to simply issue warning/info without aborting/failing current time step.

**Comment by vincentlaboure** [comment]
@GiudGiud

**Comment by GiudGiud** [comment]
I should have time next week.

**Comment by vincentlaboure** [comment]
Thanks again for the quick turnaround, @GiudGiud!
