### ISSUE TITLE
Add Debug/show_block_restriction

### ISSUE THREAD

**Issue by grunerjmeier** [idaholab/moose#28290]
Moose currently lacks of the option to check which variables are active on which subdomains.

please see #28250

**Comment by lindsayad** [comment]
@grunerjmeier I was trying to fix some formatting in the OP but I accidentally lost the discussion you were referencing 😢 Can you re-tag it please if you remember what it was. Sorry!

**Comment by grunerjmeier** [comment]
@lindsayad, I'm not sure I understand. You mean #28250? (I had a typo in the initial post in this discussion. Now fixed.)

Here is the comment of GiudGiud in this discussion:
https://github.com/idaholab/moose/discussions/28250#discussioncomment-10220127

**Comment by lindsayad** [comment]
perfect, thanks!
