### ISSUE TITLE
addCoupledVar and CoupledGenericValues improperly handle a list of coupled variables

### ISSUE THREAD

**Issue by ke7kto** [idaholab/moose#28318]
### Bug Description

In  `MooseObject::validParams()` function definitions, `params.addCoupledVar` and associated `params.addRequiredCoupledVar` do not properly add a list of coupled variables at runtime. The code, however, will compile successfully.

This may be mitigated by a `params.addCoupledVars` method if the functionality is not supposed to be supported, but it isn't clear to me that the information necessary is available during object creation.

### Steps to Reproduce

Create a custom kernel that accepts a vector of coupled variables. Compile and run an input file providing multiple coupled variables.

[src_kernels_LinearCombination_C.txt](https://github.com/user-attachments/files/16511915/src_kernels_LinearCombination_C.txt)
[include_kernels_LinearCombination_h.txt](https://github.com/user-attachments/files/16511924/include_kernels_LinearCombination_h.txt)
[linear_combination_i.txt](https://github.com/user-attachments/files/16511936/linear_combination_i.txt)

### Impact

Prevents writing generalized classes that depend on a number of coupled variables unknown at compile time.

### [Optional] Diagnostics

Shouldn't be relevant, but default (gcc-based) Ubuntu 22.04 LTS build from source, no conda involved

adriaan@INL615786:~/source/moose/scripts$ ./diagnostics.sh 

##################################################################################################
Influential Environment Variables

CONDA_CHANNEL=https://conda.software.inl.gov/public
CONDA_EXE=/home/adriaan/miniforge/bin/conda
CONDA_PYTHON_EXE=/home/adriaan/miniforge/bin/python
CONDA_SHLVL=0
CURL_CA_BUNDLE=
LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/cuda/include:/usr/lib/cuda/lib64:
MOOSE_DIR=/home/adriaan/source/moose
MOOSE_JOBS=6
PATH=/home/adriaan/miniforge/condabin:/home/adriaan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/cuda-11.2/bin:/usr/local/bin
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
SSL_CERT_FILE=

##################################################################################################
Compiler(s) (CC CXX FC F77 F90):

CC		not set
CXX		not set
FC		not set
F77		not set
F90		not set

FAIL: One or more compiler environment variables not set

##################################################################################################
Python Sanity Checks

Verify `/usr/bin/env python3 --version` (reporting as: Python 3.10.12),
matches versions for: `which python3 && which python`

OK

##################################################################################################
Python Modules (TestHarness, run-ability)

OK

**Comment by ke7kto** [comment]
Also, there's a typo in the description of [InputParameters.h](../tree/next/framework/include/utils/InputParameters.h#L489), should be 'an error' instead of 'and error'

**Comment by ke7kto** [comment]
I believe this is due to the [implementation in line 260 of InputParameters.C](../tree/next/framework/src/utils/InputParameters.C#L260) `_coupled_vars.insert(name);` where we should be looking at the values of the hit node specified by `name`, tokenizing, and iterating through the resultant vector adding each individual name separately.

**Comment by lindsayad** [comment]
So, I don't think this is a MOOSE issue. We have to pay attention to the backtraces for these kinds of errors. The error was coming from the call to `getVar`; no relation to `coupledGenericValues`. With this constructor your input runs fine for me

```c++
template <bool is_ad>                                                                                                     
LinearCombinationTempl<is_ad>::LinearCombinationTempl(const InputParameters & parameters)                                 
  : GenericKernel<is_ad>(parameters),                                                                                     
    _coupled_var_vals(this->template coupledGenericValues<is_ad>("coupled_vars")),                                        
    _linear_coefficients(this->template getParam<std::vector<Real>>("combination_coeffs"))                                
{                                                                                                                         
  const auto num_coupled_vars = _coupled_var_vals.size();                                                                 
  _var_ids.resize(num_coupled_vars);                                                                                      
  const auto n_coeffs = _linear_coefficients.size();                                                                      
  if (n_coeffs > num_coupled_vars)                                                                                        
    mooseError("Too many coefficients for the number of coupled vars");                                                   
  else if (n_coeffs < num_coupled_vars)                                                                                   
    _linear_coefficients.resize(num_coupled_vars, 1.0);                                                                   
  for (const auto i : index_range(_coupled_var_vals))                                                                     
    _var_ids[i] = getVar("coupled_vars", i)->number();                                                                    
}
```

**Comment by lindsayad** [comment]
Full implementation:
```c++
#include "LinearCombination.h"
#include "MooseVariableFE.h"
#include "SystemBase.h"

registerMooseObject("MooseApp", LinearCombination);
registerMooseObject("MooseApp", ADLinearCombination);

template <bool is_ad>
InputParameters
LinearCombinationTempl<is_ad>::validParams()
{
  InputParameters params = GenericKernel<is_ad>::validParams();

  params.addClassDescription("Implements a variable relationship as a linear "
                             "combination of other variables.");
  params.addCoupledVar("coupled_vars",
                       "The coupled variables which are combined using the combination "
                       "coefficients ");
  params.addParam<std::vector<GenericReal<is_ad>>>("combination_coeffs",
                                                   {
                                                       1.0,
                                                   },
                                                   "Coefficent multiplier for kernel summation.");
  return params;
}

template <bool is_ad>
LinearCombinationTempl<is_ad>::LinearCombinationTempl(const InputParameters & parameters)
  : GenericKernel<is_ad>(parameters),
    _coupled_var_vals(this->template coupledGenericValues<is_ad>("coupled_vars")),
    _linear_coefficients(this->template getParam<std::vector<Real>>("combination_coeffs"))
{
  const auto num_coupled_vars = _coupled_var_vals.size();
  _var_ids.resize(num_coupled_vars);
  const auto n_coeffs = _linear_coefficients.size();
  if (n_coeffs > num_coupled_vars)
    mooseError("Too many coefficients for the number of coupled vars");
  else if (n_coeffs < num_coupled_vars)
    _linear_coefficients.resize(num_coupled_vars, 1.0);
  for (const auto i : index_range(_coupled_var_vals))
    _var_ids[i] = getVar("coupled_vars", i)->number();
}

template <bool is_ad>
GenericReal<is_ad>
LinearCombinationTempl<is_ad>::computeQpResidual()
{
  GenericReal<is_ad> partial_sum = 0;
  for (const auto indice : index_range(_coupled_var_vals))
    partial_sum += (*(_coupled_var_vals[indice]))[_qp] * _linear_coefficients[indice];
  return _test[_i][_qp] * (_u[_qp] - partial_sum);
}

template <bool is_ad>
Real
LinearCombinationTempl<is_ad>::computeQpJacobian()
{
  // This function will never be called for the AD version. But because C++ does
  // not support an optional function declaration based on a template parameter,
  // we must keep this template for all cases.
  mooseAssert(!is_ad,
              "In ADLinearCombination, computeQpJacobian should not be called. "
              "Check computeJacobian implementation.");

  return -_test[_i][_qp] * _linear_coefficients[_var_ids[_i]];
}

template class LinearCombinationTempl<false>;
template class LinearCombinationTempl<true>;
```

**Comment by ke7kto** [comment]
Can confirm that it runs now. Thank you! I'll submit this and a few other objects in a PR once I have some tests verified.

**Comment by lindsayad** [comment]
great! I'm going to close this as resolved unless you disagree
