### ISSUE TITLE
Set verify_holes to false in RGMB FlexiblePatternGenerator mesh subgenerator calls

### ISSUE THREAD

**Issue by shikhar413** [idaholab/moose#28316]
### Bug Description

https://civet.inl.gov/job/2367026/ - reactor module test failure, likely due to the fact that verify_holes is set to true by default in the mesh subgenerator call

### Steps to Reproduce

See https://civet.inl.gov/job/2367026/

### Impact

Pass tests for devel branch

**Comment by GiudGiud** [comment]
closing as addressed by #28317
