### ISSUE TITLE
Postprocessors not updating for multi-system using SteadySolve2

### ISSUE THREAD

**Issue by travismui** [idaholab/moose#28331]
### Bug Description

While working with the [regression tests for multiple nonlinear systems](https://github.com/idaholab/moose/blob/next/test/tests/misc/multiple-nl-systems/test.i), I noticed that `Postprocessors` do not work correctly with the `SteadySolve2` executioner. When I add a few `Postprocessors` and ran the problem, they did not update their values at the end of the timestep/final, and remained at their initial values. If I include a flag to execute on initial, it will output correctly on initial. The solution still seems to be correct when checking the Exodus output, but I'm not getting the correct output in console or CSV. 

I'm not sure if the issue is specific to `SteadySolve2`, since I also did some testing with the `SteadyAndAdjoint` executioner and [test examples in the Optimization module ](https://github.com/idaholab/moose/tree/next/modules/optimization/test/tests/executioners/steady_and_adjoint)and those seem to behave correctly when using `Postprocessors`.

### Steps to Reproduce

Added the following `Postprocessors` to [`tests/misc/multiple-nl-systems/test.i`](https://github.com/idaholab/moose/blob/next/test/tests/misc/multiple-nl-systems/test.i) to verify behavior:

```
[Postprocessors]
  [u]
    type = ElementAverageValue
    variable = u
  []
  [v]
    type = ElementAverageValue
    variable = v
  []
  [constant]
    type = ConstantPostprocessor
    value = 1.234
  []
  [size]
    type = AverageElementSize
  []
  [size_init]
    type = AverageElementSize
    execute_on = 'initial timestep_end'
  []
  [residual]
    type = Residual
  []
  [function]
    type = FunctionValuePostprocessor
    function = test
  []
[]

[Reporters]
  [nodal]
    type = NodalVariableStatistics
    coupled_var = u
#   execute_on = 'initial timestep_end final'
  []
[]

[Functions]
  [test]
    type = ParsedFunction
    expression = 0.1
  []
[]
```

This is the expected output, using [`fully-coupled.i`](https://github.com/idaholab/moose/blob/next/test/tests/misc/multiple-nl-systems/fully-coupled.i) as the reference test case:
```
 0 Nonlinear |R| = 2.829016e+01
      0 Linear |R| = 2.829016e+01
      1 Linear |R| = 1.308028e-14
 1 Nonlinear |R| = 1.851777e-14
 Solve Converged!

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | constant       | function       | residual       | size           | size_init      | u              | v              |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   1.234000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   5.000000e-02 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   1.234000e+00 |   1.000000e-01 |   1.851777e-14 |   5.000000e-02 |   5.000000e-02 |   5.000000e-01 |   5.415625e-01 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+


Reporter Values:
+----------------+----------------+----------------+----------------+--------------------+
| time           | nodal/average  | nodal/max      | nodal/min      | nodal/number_nodes |
+----------------+----------------+----------------+----------------+--------------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |                  0 |
|   1.000000e+00 |   5.000000e-01 |   1.000000e+00 |   0.000000e+00 |                 21 |
+----------------+----------------+----------------+----------------+--------------------+

```

However, when I execute the `SteadySolve2` problem, I get the following output, notice that nothing is updated on `FINAL`:
```

  0 SNES Function norm 1.296148139682e+02 
  1 SNES Function norm 1.072074261333e-13 
 Nonlinear system 0 solve converged!
  0 SNES Function norm 2.831811147481e+01 
  1 SNES Function norm 1.944729220985e-14 
 Nonlinear system 1 solve converged!

Postprocessor Values:
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
| time           | constant       | function       | residual       | size           | size_init      | u              | v              |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
|   0.000000e+00 |   1.234000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   5.000000e-02 |   0.000000e+00 |   0.000000e+00 |
|   1.000000e+00 |   1.234000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   5.000000e-02 |   0.000000e+00 |   0.000000e+00 |
+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+


Reporter Values:
+----------------+----------------+----------------+----------------+--------------------+
| time           | nodal/average  | nodal/max      | nodal/min      | nodal/number_nodes |
+----------------+----------------+----------------+----------------+--------------------+
|   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |                  0 |
|   1.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |                  0 |
+----------------+----------------+----------------+----------------+--------------------+
```

### Impact

If the issue is limited to `SteadySolve2`, then the impact is minor since I'm just using this as an example case to build my own multi-system executioner. However, if the issue is elsewhere in the framework then it would be a roadblock to my development. Coverage on this could be improved since there are a lack of tests using multiple nonlinear systems and including `Postprocessors` (most are `Exodiff` based on a quick search).

**Comment by GiudGiud** [comment]
the steadySolve2 is a test object. It likely does not have all the execute_on calls one needs

To fix this we should first compare steady and steadySolve2 and see if there are any missing calls in the latter
I ll be out for medical stuff the rest of the week but once I m back I m happy to take a look

**Comment by travismui** [comment]
Thanks @GiudGiud! Just to jot down some notes, when I took a first look and compared `Steady` with `SteadySolve2`, the main differences I noted were:
- Dropped `MultiApp`-related calls
- Missing a call to `_problem.advanceState()` just after `preExecute()`, I added this in but did not seem to help
- Skips integrity check and also setting user-custom time

**Comment by lindsayad** [comment]
@travismui please see #28359
