### ISSUE TITLE
Add documentation for using containeriezd modules on INL HPC

### ISSUE THREAD

**Issue by loganharbour** [idaholab/moose#28584]
### Motivation

With the release of container development modules (`moose-dev-openmpi`) on HPC, we need to document them.

### Design

Document how to use the containerized development modules on INL HPC.

### Impact

New documentation, better user experience.

**Comment by milljm** [comment]
Note to self. When this gets merged, re-visit: https://github.com/idaholab/moose/issues/27731, to add pieces that this PR was to replace in mine.
