### ISSUE TITLE
Typo in docs, possiblly carried through to BISON in source code

### ISSUE THREAD

**Issue by lewisgross1296** [idaholab/moose#28604]
### Bug Description

According to the [ChromiumThermal](https://mooseframework.inl.gov/bison/source/materials/ChromiumThermal.html) Page, the thermal conductivity function is given by below

![ChromiumThermal](https://github.com/user-attachments/assets/d91717af-7979-4031-89ae-08b71b468cf0)
I was trying to produce the plot and noticed that it went negative at a certain point. I went to the literature and noticed that the first term coefficient has a wrong exponent. Here is the formula from the source
![reference_thermal_conductivity](https://github.com/user-attachments/assets/109878c0-6497-435d-9fc5-31d73e7be115)

### Steps to Reproduce

I don't have BISON access so I can't check, but this is either only an issue in docs, or if the same formula is implemented in BISON, it would produce a negative thermal conductivity above ~740 K.

### Impact

Anyone who just uses this formula would have a wrong thermal conductivity value. If this formula is implemented as is in BISON, then it's giving the wrong value there too.

**Comment by GiudGiud** [comment]
@gambka

**Comment by gambka** [comment]
We have a contact us page on our documentation site that you can contact one of us directly if you don't have access. Thanks for reporting. It looks to be a typo in the docs.

**Comment by gambka** [comment]
This is being addressed through a BISON issue [here](https://github.inl.gov/ncrc/bison/issues/6173)

**Comment by GiudGiud** [comment]
Closing as addressed by https://github.inl.gov/ncrc/bison/pull/6174

Thank you for reporting @lewisgross1296
