### ISSUE TITLE
MPI Change: Add influential file. Correct a small permissions issue in mpi.def container

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#28643]
### Motivation

There was a new file added to apptainer/mpi.def that was mistakenly not added to the influential files.

There is a sourced file that has incorrect permissions. While they work at present, they should be world-readable.

Edit:
Using this PR to include changes from a reverted PR #28283 (with fixes). Otherwise, this would be too many rapid changes in such a low lever Conda package.

### Design

Track the `01-fix-exec.sh` influential file.
Fix permissions on said file during %post.

### Impact

The versioner.yaml file will correctly track all related Apptainer files.
The source file will have correct permissions.

**Comment by milljm** [comment]
When https://github.com/idaholab/moose/pull/28587 is read, incorporate that into this (for a more worth while reason to bump petsc).

**Comment by lindsayad** [comment]
So for Mac, we will want to add this to `LDFLAGS`: `-Wl,-ld_classic -Wl,-commons,use_dylibs`. Additionally on Mac, when configuring mpich we will want to pass `--with-device=ch4:ofi`. Refs https://gitlab.com/petsc/petsc/-/issues/1569

**Comment by milljm** [comment]
Due to the setback and reverting of #28399, I'll be making another attempt getting everything rolled into this PR...

**Comment by loganharbour** [comment]
> Additionally on Mac, when configuring mpich we will want to pass --with-device=ch4:ofi

We take what we can get with conda mpich:

```
./configure --prefix=$PREFIX \
            --disable-dependency-tracking \
            --enable-cxx \
            --enable-fortran \
            --enable-f08 \
            --with-wrapper-dl-type=none \
            --disable-opencl \
            --with-device=ch4 \
            || cat config.log
```

from https://github.com/conda-forge/mpich-feedstock/blob/d187d6d38143e3f03d0eb8a9cb0b16d23175594e/recipe/build-mpi.sh#L94C1-L102C30
