### ISSUE TITLE
`coupledValuePreviousNL(var)` does not work correctly for aux variables

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#28807]
### Bug Description

`Coupleable::coupledValuePreviousNL(var, comp)` does not give the previous nonlinear iteration's value for aux variables (it does give the correct value for solution variables). It appears to be getting the previous time step values instead.

### Steps to Reproduce

See https://github.com/idaholab/moose/pull/28806. The test in that PR makes an aux. variable that should be equal to the nonlinear variable in the test, but using a post-processor that calls `Coupleable::coupledValuePreviousNL(var, comp)` produces different results.

### Impact

Incorrect and unreported behavior.

**Comment by GiudGiud** [comment]
Did you request the previous value? There s an api on the problem for that. I wonder if this api in Coupleable is forgetting to call it

I m using it in the turbulence physics in initialize if you want to check

**Comment by joshuahansel** [comment]
Yeah I'm requesting it - an error is thrown if you don't request it (I'd like to make that automatic at some point if possible). And the solution variables are retrieved just fine - it's only the aux variables that have the issue.

**Comment by lindsayad** [comment]
I'm not surprised this doesn't work well. When this was written, people were almost certainly just thinking about the nonlinear solution values in the previous Newton iterate
