### ISSUE TITLE
Need more YAML tests to maintain peacock support

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#2881]
Right now we have one YAML test that simply looks for output.  Our YAML dump logic is rather complex and easy to break.  We need several more tests to inspect various kinds of parameters that peacock expects.  We might also want to make sure that we aren't getting extra output.  This should all be possible by doing several different regular expression tests.

**Comment by permcody** [comment]
@brianmoose - this ticket may not be an issue anymore. We do (or will do) peacock testing right?

**Comment by brianmoose** [comment]
We do have peacock testing that would definitely exercise the YAML dump.
There isn't anything that checks for extra output or that certain parameter information matches exactly.
I was checking on a diff of the whole YAML dump but that changed too much with people adding/removing parameters, descriptions, etc. I suppose I can add something back in for something that doesn't change much.

**Comment by brianmoose** [comment]
Now that we can do python unit tests in the TestHarness, we could easily add a python test
that parses the YAML into a python dict and checks for some keys. We do that for JSON output.
This also catches extraneous output (as seen by the PETSc debug problem).
But if YAML is potentially going away....

**Comment by permcody** [comment]
YAML is going away after old peacock dies. I wouldn't worry about this.

**Comment by aeslaughter** [comment]
YAML is no longer used for Peacock
