### ISSUE TITLE
Correct saline submodule

### ISSUE THREAD

**Issue by freiler** [idaholab/moose#28828]
### Motivation

History in the saline repository was rewritten such that the commit that modules/fluid_properties/contrib/saline points to is no longer valid.

### Design

Use the new updated hash [691e39cc4380135d5f75a376247ba29b49a78e9a](https://code.ornl.gov/neams/saline/-/commit/691e39cc4380135d5f75a376247ba29b49a78e9a), which is the rewritten version of the current hash used.

### Impact

Makes saline work again.

**Comment by lindsayad** [comment]
I wonder if this is why my saline was broken for so long. People always told me I was crazy
