### ISSUE TITLE
DAGs to depend on DAGs

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#28947]
### Motivation

We lost the ability for a test in a test-spec file to depend on another test in a _separate_ test-spec file, when we switched to using self-contained DAG of testers. These objects only know about their own contents.

I think it would be relatively simple if we allowed the DAG object to depend on another DAG object. This would bring back the afore mentioned ability. So basically, we need to support a DAG of DAGs.
 
Maybe if I apply a recursive algorithm... (star trek pun).

### Design

Who knows what this is going to look like. Recursively speaking, it should require little change if done right. I think the real trick will be in identifying when or not when to depend on a test within the DAG, and when to switch to searching out of the DAG.

At the time when we switched to DAGs, this wasn't possible because we were launching tests immediately upon DAG creation (thinking this was most efficient). Now that we wait until the entire DAG list is built, this should be possible.

### Impact

Tests may depend on unrelated tests in other test spec files.

**Comment by loganharbour** [comment]
I really don't like this either. mainly because I don't want to support depending on files out of a test spec's folder

**Comment by milljm** [comment]
Closing then...

**Comment by vanwdani** [comment]
Looks like this will need to be a BISON call then...

**Comment by loganharbour** [comment]
I was a bit direct above, but to be clear the above was a post of concern and not a hard no. I talked to Cody about this some too. We've made many choices to not support this in the past because it opens the door for a lot of mistakes for the user. 

I think that we just need to have a larger conversation of what we're trying to support here and what issues we're trying to resolve, which aren't shared in the issue above

**Comment by milljm** [comment]
Well, if we're not going to support DAG of DAGs in-harness, there is nothing stopping folks from doing it out-of-harness:
```bash
tests=('/path/to/simple_diffusion/tests' '/path/to/completely/unrelated/tests')
for test_spec_file in "${tests[@]}"; do
    ./run_tests "$test_spec_file" --slurm --pbs --whatever || exit 1
    ./do_something_with_the_results_file.py "${test_spec_file}"
done
```
_one unrelated test group made to depend on the success of another._

Since this is all shell work, anything is possible really.
