### ISSUE TITLE
Add support for multi-system to physics classes

### ISSUE THREAD

**Issue by GiudGiud** [idaholab/moose#29019]
### Motivation

It is known that equations that are not two-way coupled, (either uncoupled, or one-way coupled) are solved much more efficiently using a multi-system approach than a single system approach

### Design

Add logic to enable multi-system coupling in the action

### Impact

Faster solves
More flexibility

**Comment by lindsayad** [comment]
I'd also be curious how a multiplicative field-split does for these one-way coupling cases

**Comment by GiudGiud** [comment]
For sure. It could perform just as well. It's just conceptually easier to do multi-system
