### ISSUE TITLE
Utilize new MeshTools::Modifcation::transform()

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#2944]
Roy is adding a new function to MeshTools::Modification called `transform()`.  We need to utilize it in a new MeshModifier.

The libMesh PR is here: https://github.com/libMesh/libmesh/pull/232

**Comment by permcody** [comment]
https://github.com/idaholab/moose/blob/next/framework/src/meshgenerators/TransformGenerator.C#L55-L56
