### ISSUE TITLE
Peacock issues

### ISSUE THREAD

**Issue by peredm** [idaholab/moose#2946]
While going through a peacock tutorial with the bison team, we came across a few errors:
1.) sidesets and nodesets do not appear on higher order element meshes (input tab).
2.) when you right click and try to edit comment, it doesn't do anything.
3.) when I run a input file, while it is executing, I get a bunch of attribute errors.

**Comment by brianmoose** [comment]
Since this almost 4 years old and applies to the old peacock, I am going to close this. If any of these are still a problem with the new peacock, new issues can be opened.
