### ISSUE TITLE
We need doxygen for modules on mooseframework.org

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#2986]
This is still missing, needs to be put up there very soon!

**Comment by brianmoose** [comment]
We have doxygen for modules. Anything else needs to be done?

**Comment by permcody** [comment]
I think this is OK for now. At some point we might decided to split the documentation up per module but I have a feeling that most people will just use the combined module anyway so they don't have to hunt things down.  We'll open a different ticket if that concern becomes an issue.

**Comment by dschwen** [comment]
Yeah: #5824!
