### ISSUE TITLE
Assemble all sub-matrices on diagonal in one function call

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3024]
I would like to have a function call like
```
FEProblem::computeBlockDiagonalJacobian(NonlinearImplicitSystem& sys, const NumericVector<Number>& soln, std::vector<SparseMatrix<Number>  >& jocobians);
```
to assemble all diagonal block jobobians each corresponding to a primal variable. The call needs to be properly parallelized with multiple processors and threads.

Btw PBP can benefit from this.

Thanks.

**Comment by YaqiWang** [comment]
We should be able to close this issue now. I will let @permcody  or @friedmud do it.

**Comment by permcody** [comment]
Thanks @YaqiWang for cleaning up - closing
