### ISSUE TITLE
NodalKernel

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#3029]
It's new System time!  I'm sure this will be the last one :smile: 

We need the equivalent of NodalBC for Kernels.  This will enable fully-implicit, fully-coupled, spatially separated ODEs (ie, an ODE at every node).  I think @YaqiWang will use this as well as anyone doing chemistry related things....

When we do this we need to make sure we get the Jacobians correct (that's one of the big downfalls of doing this using the Auxiliary system)... and as long as we're doing that we should make the Jacobians work properly for NodalBC....

**Comment by dschwen** [comment]
I'm not seeing why

> u_dot = u + v

couldn't simply be coded up as a regular kernel.

**Comment by friedmud** [comment]
Because Kernels are evaluated at quadrature points and their residuals are
integrated over elements.

You wouldn't be solving for u_dot. You would be solving for a projection of
u_dot into the Lagrange basis. Sometimes that can work... but it's actually
unstable.... and generally doesn't represent the actual system of equations
you're trying to solve...

Derek

**Comment by friedmud** [comment]
One more use...

https://groups.google.com/forum/#!topic/moose-users/cthPGyKPPCE
