### ISSUE TITLE
MeshModifier to delete all elements within a block?

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#3080]
Would this be easy to do?  I'd like to do it at some stage but i don't actually know how to do it, can anyone give me some clues or examples?

**Comment by permcody** [comment]
@WilkAndy  - Are you still interested in this ticket? Looks pretty old at this point.

**Comment by WilkAndy** [comment]
Yes, this is old.  Yes, i am still interested in this.  It is one of the big stumbling blocks why we can't use MOOSE easily for mining scenarios (where material actually gets removed).

**Comment by permcody** [comment]
Well I guess since we never chatted about it last year, I can give you a little more guidance here. The element deletion order _is_ important but you certainly don't need to rewrite that logic. It's already there and/or I can help you get it right. What you see in that commit is that I loop over the elements that need to be deleted in any order and shove them all into the `DependencyResolver`. There's another loop over `DependencyResolver` that actually performs the deletes.

What you need to do is tell the deleter what elements to delete. I can help you with this if you want.

**Comment by WilkAndy** [comment]
Thanks Cody.  I'll have another look at this when i get time (maybe a couple of weeks).

a

**Comment by permcody** [comment]
Well now there are at least two users wanting this so I will probably resurrect.

**Comment by WilkAndy** [comment]
@permcody, this is my student's summer project (@professorhoover).  I'd be very grateful if you could help him with it.  Obviously he's a complete novice in moose, but he learns quickly and has done a fair amount of coding before.

a

**Comment by permcody** [comment]
Lucky for him the code is already there (see hash above). Just get it working again!

**Comment by WilkAndy** [comment]
I hope you understand it will be slow going initially.  @ProfessorHoover has a lot to learn.  After he understand your code, i'd like guidance on is the overall aims and architecture of this project.  For instance, i had imagined a Function that defines "inside" and "outside".  It can be time-dependent.  Each timestep it gets evaluated, marks elements to be deleted, and they get deleted.  Is this a good idea?  Is it general enough?  Do we use the Marker system?  Any other ideas?

a

**Comment by ProfessorHoover** [comment]
Hi Cody,
I've gotten your ElementDeleter code to compile in the modern codebase. Next I'll try to work out how it works and update it to function.
Andrew

**Comment by andrsd** [comment]
1) MeshModifiers are executed once before the simulation starts.
2) If you want to change your mesh in-between time steps, that is whole another beast and it would be a lot of work, since you have to reinitialize the whole system and "project" the previous time step as an initial condition for the next time step. Unless you'd use some trick to 'turn off' elements (not delete them physically), but I have no idea how that would work, since there might be a boundary terms popping up at the new boundaries and you'd have to "build" the boundary conditions on the fly.

**Comment by friedmud** [comment]
It will be difficult... but it is worth doing (if someone wants to take the
time to make it work).

I propose that MeshModifiers work like everything else and take
`execute_on`...

Derek

**Comment by WilkAndy** [comment]
Yes, i'd like to be able to delete elementsat the end of time steps.  I'm not sure whether deleting them forever, or deactivating them is better, so would like your considered thoughts on this.  In my old code we had the deletion functionality and we re-jigged all the DOF maps and so on.  However, occasionally i would have liked to have added elements back in, or having elements reactive for certain physics, and deleted according to other physics.  What do you think?

a

**Comment by friedmud** [comment]
It's definitely possible with libMesh to _actually_ delete elements in the
middle of this simulation.  It will do the right thing.  Afterall: libMesh
was designed for mesh adaptivity (where elements are deleted all the time).

It's just a matter of getting all of the calls in order and making sure all
of the MOOSE plumbing gets updated.  It shouldn't be too bad.

Derek

**Comment by ProfessorHoover** [comment]
I'm having trouble getting the element deleter to work. Could someone please walk me through the original code to help me understand it better? I think I get the general idea, but I'm not having much luck getting it actually working.

**Comment by permcody** [comment]
I'll take a look at this code to see if I can spot something. I'll report back.

**Comment by permcody** [comment]
@ProfessorHoover - Well I'm glad I took a look at this. We figured out that we **have** to call `contract` on the mesh after removing elements or the node numbering and elements are totally hosed. I don't recall having to do this a few years ago but maybe I just got lucky with the few tests we had at the time. Anyway, this code seems to be working better and works fine in parallel now.

TODO: The next steps will be to implement a few children classes from this new base class that define how to delete elements. Maybe you want a block deleter, we'll probably want a function deleter. Finally, if we are deleting elements on the surface of the mesh, we probably want to do something smart with the boundary conditions. That's what I was originally doing with the `DependencyResolver`. It wasn't that the elements had to be deleted in a certain order, it's that they had to be deleted in a certain order if we wanted to "suck in" the existing boundary conditions.

Anyway, I'm happy to keep working on this but I didn't want to steel all your thunder. Here's my updated branch:
https://github.com/permcody/moose/tree/element_deleter

**Comment by WilkAndy** [comment]
My perspective is:

(1) BlockDeleter is a useful meshmodifier - it runs at the start of the simulation and allows me to delete chunks of the mesh.  i will never want to do something smart with the BCs, and my BCs are always so complicated that i don't know how you'd ever predict what i want to do.  I would have created sidesets within the mesh already, and after block deletion these may now reside on the outside of the mesh.

(2) I eventually want FunctionDeleter (or similar name), as you mention, @permcody .   I want this to run more like a MeshAdaptivity Class - viz, every timestep.  Again, i don't want to muck around with any sidesets: if they should exist in the final mesh (eg, they are on the boundary of an undeleted element), then they must be there; but if they shouldn't exist (eg, all the elements attached to the sideset face have been deleted) then they should be deleted.

a

**Comment by WilkAndy** [comment]
Thanks @permcody for your help here.  It all looks nice - we just have to override shouldDelete.  What happens to nodesets and sidesets?   Previously we called mesh->boundary_info->remove(stuff)  (or similar).  Won't we have to do this now??

a

**Comment by permcody** [comment]
Well this is just a quick and dirty work up that doesn't deal with side
sets or node sets at all. We'll add that later. It's not difficult just
didn't want to take away all of your student's fun!

**Comment by WilkAndy** [comment]
Haha, ok,

a

**Comment by WilkAndy** [comment]
@permcody, why can't we just have:

 for (it = deletable_elems.begin() ; it != deletable_elems.end(); ++it)
  {
    mesh.boundary_info->remove(*it);
    mesh.delete_elem(*it);
  }

to get rid of the sidesets connected to the deleted elements?

a

**Comment by WilkAndy** [comment]
Yet another comment from me!  To delete nodes from nodesets can't we just replace

   // No connected elements, then delete it!                                                                                          
    if (!connected_elem)
      mesh.delete_node(node);

in your code with

   // No connected elements, then delete it!                                                                                          
    if (!connected_elem)
{
      mesh.delete_node(node);
      mesh.boundary_info->remove(node);
}

?  Sorry if i'm being incredibly ignorant - i haven't looked at moose for a couple of weeks.

a

**Comment by friedmud** [comment]
There is already code in libMesh to remove orphaned nodes when elements
they're connected to are deleted.

For SerialMesh it's here:

https://github.com/libMesh/libmesh/blob/master/src/mesh/serial_mesh.C#L742

It gets called from contract() here:

https://github.com/libMesh/libmesh/blob/master/src/mesh/unstructured_mesh.C#L751

You guys need to just figure out how to get libMesh to do your bidding at
the right time...

Derek

**Comment by permcody** [comment]
Cool, I was actually thinking about that last night. I figured libMesh
probably does take care of that.

**Comment by WilkAndy** [comment]
Thanks everyone for working on this.  It turned out pretty easy, heh?!  Is 11 tests a bit extreme?  I can prune them down if needed,

a
