### ISSUE TITLE
Improve the FullSolveMultiApp to support quasi-steady transient simulations

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3089]
Possibly there are two physics forming a coupled system. The transient of one physics is so fast comparing with they other physics, so that at any time it reaches steady state instantaneously, i.e. its time derivative is zero. In this case, if this fast physics is modeled with a MultiApp, it will use the Steady executioner. We then have no choice but the FullSolveMultiApp at least for now. The current implementation in FullSolveMultiApp is not ready for this kinds of simulations. For example, `ex->init()` is called inside `solveStep()`; `auto_advance` is not allowed, and so on. We should have an improved version of it so that it can be used for fast physics along a transient physics. I believe those improvements should be quite strait-forward.

This also creates a related question: if we had to create steps to do a steady solve for the quasi-steady physics, we would not want to use the steps to constrain the time step of the master physics. It seems to me that we should use the FullSolveMultiApp to wrap the fast physics even it is using Transient executioner. I do not know how this will go.

Comments are welcome.

**Comment by YaqiWang** [comment]
I think after @snschune 's change of moving executioner init into multiapp init. This full solve app is almost doing what i want except one thing: it has _solved flag and using it. I would remove it and change the name from FullSolveMultiApp to SteadyMultiApp for consistency with TransientMultiApp.

**Comment by permcody** [comment]
That sounds reasonable from the perspective of an outside user. I do want to hear from @friedmud though since he may have different intentions.

**Comment by friedmud** [comment]
The intention here is that it could be either Steady or Transient... but
it's going to solve all the way to the end in one go. That's why it's
called "FullSolve"...

**Comment by YaqiWang** [comment]
@idaholab/atomistic-developers Do you want me close this issue?

**Comment by aeslaughter** [comment]
@YaqiWang I am closing this issue as it seems like something not intended for FullSolveMultiApp. That being said I implemented something similar in #8465 that does repeated complete solves in a custom MultiApp, with a small amount of code. So, I am sure you can get something going.
