### ISSUE TITLE
Ability to pass Functions to ParsedFunction

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#3102]
At present we can pass real numbers and postprocessors to ParsedFunction in the vars+vals combination.  It would to fantastic if we could also pass functions, so as to be able to have functions-of-functions.  I imagine the interface exactly the same as it is for reals and postprocessors, eg

```
type = ParsedFunction
value = a*p+f
vars = 'a p f'
vals = '1.1 my_postprocessor my_function'
```

**Comment by hsheldon** [comment]
I would like this functionality too.

**Comment by WilkAndy** [comment]
This has been done by some thoughtful person.
