### ISSUE TITLE
Oversampling on 3rd order Hermite elements produces non-deterministic results

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#3105]
I'm trying to drill down to the issue with MARMOT's FMM_prob.surfen_test
The test randomly fails on my machine (i.e. the result is non-deterministic). 

The files diff only in timestep zero. There is no diff if output oversampling id turned off. The IC that is used in this case (a class derived from SmoothCircleIC) sets the gradient on the elements (using ::gradient()). I replaced that routine with one that returns a constant (0,0,0) gradient and the outputs still diff.

![Screenshot of a typical diff](http://i.imgur.com/6K1dYyR.png) Screenshot of a typical diff (note the diagonal pattern)

**Comment by dschwen** [comment]
Cannot reproduce this anymore. Test does not fail randomly.

**Comment by permcody** [comment]
I wish we would have recorded what we fixed. I think I remember when we figured this one out....
