### ISSUE TITLE
Use Python Markdown and QtWebKit to render Object Descriptions

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#3117]
I've been trying to figure out the best way to do Object descriptions for MOOSE-based objects for a long time... and I think I have it:

The Descriptions themselves should be added to `InputParameters` using `addClassDescription()`.  They should be formatted using Markdown... just like on our Wiki... including the use of `$$ .. $$` to signify equations in Latex.

For Peacock what we'll do is use Python Markdown to parse the Descriptions and generate HTML that we'll render using QtWebKit ( https://deptinfo-ensip.univ-poitiers.fr/ENS/pyside-docs/PySide/QtWebKit/ ) with Mathjax ( http://www.mathjax.org ) hanging around to render the equations (just like we do on the Wiki).

The great part about doing it this way is that our input file webpages will also be able to have this generated HTML with Mathjax rendering in them!

Now... to find time (or someone) to actually do this...

**Comment by permcody** [comment]
We have a new system that supersedes this request. The MooseDocs system.
