### ISSUE TITLE
A strange issue on getting material property block names

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3141]
I created a branch in my fork of moose, 'get_material_issue'. In that branch, I added an few source files and an input under test/tests/actions/aux_material/add_aux_material.i. 

`_problem->getMaterialPropertyBlockNames` returns different vector of the block names on which the material property is defined, before and after adding the aux material. The line causing trouble is in AuxConstantMaterial.C:37.

@aeslaughter This is the test case I created for you.

Thanks.

**Comment by YaqiWang** [comment]
I will ask the same question as @aeslaughter did.

**Comment by YaqiWang** [comment]
@andrsd This is a super old issue. We should close it if it has been fixed.

**Comment by aeslaughter** [comment]
I am assuming this is finished since there is a commit with the issue.

**Comment by permcody** [comment]
Closed by #3158

**Comment by permcody** [comment]
@aeslaughter - be careful how you close these. "Assuming" would not stand up to an audit. I found the issue that does close it easily enough.
