### ISSUE TITLE
simulation hangs when trying to output at a sync time

### ISSUE THREAD

**Issue by amjokisaari** [idaholab/moose#3162]
In some cases, a simulation will reach a sync time, at which point it's supposed to output.  However, the simulation hangs somewhere after the _problem.adaptMesh() call is output to screen and does not proceed.

I have an input file, a mesh file, and the checkpoint files to demonstrate this bug.  It runs on 16 processors.  This simulation was running on Fission when the issue occurred.

**Comment by permcody** [comment]
Yikes, I just ran across this old ticket... I bet you don't have those files anymore do you?

**Comment by amjokisaari** [comment]
I have no idea... I actually don't even know if this is still an issue.  
I guess close the ticket and if it crops up again, go from there?

**Comment by permcody** [comment]
Closing for now. Will investigate later if this crops up again.
