### ISSUE TITLE
A problem on using SolutionUserObject

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3198]
Javier created a mesh in which there is an elemental variable. We then use SolutionUserObject to load it and assign it to an aux variable. The aux variable is then outputted. Then we opened the input mesh and the generated output using paraview. The elemental variables in the two files are apparently different. The variable in the generated file is scrambled. We will send the mesh and the input to you.

**Comment by permcody** [comment]
Old ticket - Closing
