### ISSUE TITLE
SolutionUserObject is not supporting parallel mesh

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3201]
I looked into the code. It says that the reason is libmesh ExodusII_IO::copy_nodal_solution() does't work in parallel and another reason seems also related with nodal variables. So my question is: can we safely change Line 379
`_fe_problem.mesh().errorIfParallelDistribution("SolutionUserObject");`
into
`if (_nodal_vars.size()>0) _fe_problem.mesh().errorIfParallelDistribution("SolutionUserObject");`?

So at lease the SolutionUserObject can support elemental variables with parallel mesh. We currently use an elemental variable to store the material IDs and want to load it as an aux variable. Thanks.

**Comment by lindsayad** [comment]
@snschune @YaqiWang Are you envisioning loading from `Nemesis` parallel output or are you thinking of using `Checkpoint` in some way?

**Comment by YaqiWang** [comment]
Check point should be fine. We do not have to distribute the mesh for solution user object. Actually I think we possible cannot. Another question is that: Is is possible just load the solution on a subdomain or even on a side set?

**Comment by permcody** [comment]
Good question. It's nice to support both to some extent. They each have pros/cons.

Nemesis: Can directly visualize, however, we can't easily create this format with external splitting tools. There used to be tools distributed with Seacas, but they are difficult to build, distribute.

Checkpoint: Very compact, new splitting support in libMesh and possibly soon in MOOSE. Can't directly visualize is the only downside.

**Comment by permcody** [comment]
@YaqiWang - If we can't already just load the solution in one part of the mesh, it wouldn't be hard to add that.

**Comment by YaqiWang** [comment]
That is great. We plan to have one big calculation to provide the boundary condition for another calculation, which is going to just use the solution on a small side set. Keeping the solution of the big calculation everywhere would be a huge waste of memory especially with lots of processors. It will be really nice if we can have the capability.

**Comment by permcody** [comment]
Well that's a different problem. We'll still have to read the mesh format into memory to load the data out of it. Perhaps a better question is, can we delete that solution after it's used? If it's a parallel solution it should be negligible. If it's a serial format and every processor reads the whole thing, that's another problem.

**Comment by YaqiWang** [comment]
About visualizing, we can output both files but only use Checkpoint to construct solution user object. So visualizing should not be a problem to us.

The mesh for the solution user object is completely different from the mesh where the calculation is done using the solution user object. We expect every processor is using the solution user object without distribution of its mesh.

**Comment by YaqiWang** [comment]
I feel this issue can be closed particularly due to https://github.com/idaholab/moose/commit/5f6d5a1b48ecff601faf7022490dd4c7fe8b292f. We do not have to make SolutionUserObject use distributed mesh.

**Comment by permcody** [comment]
Not sure if we should close it even if you have a good workaround. At the very least we should probably make sure it fails gracefully where appropriate before closing. Turning it to minor priority.

**Comment by YaqiWang** [comment]
Right now SolutionUserObject is hard-coded to use replicated mesh. We did not give user options on using distributed. Maybe we do not want to.

**Comment by friedmud** [comment]
It would be nice - but I think it would be hard to add.  The difficulty is that there is no guarantee that the current problem has the same mesh - or the same partitioning.  So you're looking at needing to do a parallel "transfer" to evaluate it.

I think a good approach for now is to use checkpoint files a "restart" in a MultiApp to load a distributed solution into a MultiApp - then you can use Transfers to transfer the fields to your current app and couple to those.

We could even make a special MultiApp that is built for this purpose... a `SolutionMultiApp` or something... it's only job would be to read in Checkpoint files for the solution.  I don't know how much work that would be to get going but at least we wouldn't have to reimplement the parallel transfer parts...

**Comment by YaqiWang** [comment]
Closing this because the implementation effort overweights the benefit significantly plus `SolutionUserObject` can run with distributed mesh now although itself is using the replicated mesh.
