### ISSUE TITLE
VectorPostprocessor output options

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#3230]
I recently started using a VectorPostprocessor to output data along a line.  I'm really happy to have this capability, and I think we'll use it a lot.  I'd like to start a discussion about options for outputting this data.

Currently, we get a new file each time step for each VectorPostprocessor.  Each of those files has 5 columns: id, variable, x, y, z.

Comments on this:

1) The name 'id' isn't very intuitive.  It's the distance from the start point.  Could we name it something else?

2) I'd like the option to have a single file for each VectorPostprocessor.  That file would have a column for the position, and a column for the value of the variable at each time step.  We'd have to append a new column at each step, which is a bit of a pain.  I believe that to do this, at each new step, we'd need to read in each line of the old file, append the new data to each line, write that to a temp file, and then when every line is written, close the files and move the temp file to overwrite the csv file.

**Comment by permcody** [comment]
We've settled on the VectorPostprocessor Format. It works well and I don't see it changing anytime soon. Closing this ticket.

**Comment by bwspenc** [comment]
@permcody I don't think we ever added an option to name the column anything other than 'id'.
