### ISSUE TITLE
Cache Element Volumes

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#324]
Need to cache these for speed of computing averages.

Should update these whenver Moose::meshChanged() is called.

Should be provided in Kernel as _current_elem_volume

**Comment by friedmud** [comment]
Element volume calculations are not a bottleneck.

**Comment by andrsd** [comment]
Also, now when we cache `ElementFEShapeData`, we store `JxW` and use it for element volume calculation. So, some simple optimization has been achieved. Moreover, we have a flag `_current_elem_volume_computed` so we do not recompute the volume over and over if needed...
