### ISSUE TITLE
Input no longer placed in exodus output file

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#3294]
Recently, the exodus output file would include information about the SVN revision number, PETSc version, and build timestamp.  It also would include an approximation to the input file.  This is useful for seeing what version of the code and what input options produced the output file.  However, it looks like that is no longer happening.  I'd like to have that restored.

This information can be extracted from an exodus output file by running blot or grope and then 'list qa'.

**Comment by permcody** [comment]
Input definitely exists in the output file. Still it cannot currently be used for rerunning a simulation, although it can be used to reconstruct an input file that can be used. We don't have a lot of push to make this work so I'm closing this ticket.
