### ISSUE TITLE
Look for "Table Join" utility for Python postprocessor

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#3379]
@bwspenc commited a utility to read CSV files and join them together.  There's a lot explicit logic in there that might exist in a higher-level module.  Investigate shortening up this script.

**Comment by permcody** [comment]
The answer is pandas data frames!

**Comment by bwspenc** [comment]
Now that we have the `contains_complete_history` option in VectorPostprocessors, we aren't even using that script anymore. I'd be fine getting rid of it.

**Comment by permcody** [comment]
Great - not needed anymore!
