### ISSUE TITLE
Investigate "Interpolate scalars" (VTK?) option for peacock

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#3408]
Peacock and Paraview render the same file rather differently, with paraview looking quite a bit better:

[Peacock](https://drive.google.com/file/d/0B9BK7pg8se_iTFYycVVyak41Qm8/edit?usp=sharing)

[Paraview](https://drive.google.com/file/d/0B9BK7pg8se_iMkNOQ1Z1amg0MHc/edit?usp=sharing)

David pointed out this ["interpolate scalars"](https://drive.google.com/file/d/0B9BK7pg8se_idnlOT0RFaEFSa0E/edit?usp=sharing) option in Paraview which is on by default.  If you uncheck that option, the paraview rendering looks a lot more like peacock.  If this option maps to something relatively simple in the VTK API, we should probably try turning it on by default...

**Comment by aeslaughter** [comment]
We are doing this in chigger/peacock

```
        self._vtkmapper.InterpolateScalarsBeforeMappingOn()
```
