### ISSUE TITLE
If clip option is toggled before execute, rendering fails

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#3409]
If you toggle the "clip" option, then hit execute, and then go back to the visualize tab, you get a [grey mesh](https://drive.google.com/file/d/0B9BK7pg8se_iS1FkbG1KQ24xMnM/edit?usp=sharing), and the following error is printed to the screen:

```
Traceback (most recent call last):
  File "/Users/petejw/projects/moose_git/gui/vtk/ExodusResultRenderWidget.py", line 1183, in _finalRead
    self._updateData()
  File "/Users/petejw/projects/moose_git/gui/vtk/ExodusResultRenderWidget.py", line 1123, in _updateData
    _clippingToggled(True)
NameError: global name '_clippingToggled' is not defined
```

**Comment by friedmud** [comment]
Hopefully @aeslaughter and @brianmoose will get this all fixed up in the next Peacock.

Please close this ticket when you do...

**Comment by permcody** [comment]
I have verified that this particular operations works properly in the new peacock.
