### ISSUE TITLE
 read elemental solution from the Exodus

### ISSUE THREAD

**Issue by jortensi** [idaholab/moose#3410]
MAMMOTH uses an elemental solution to assign cross sections to the various regions in our models. This is done to avoid the use of blocks (subdomainIDs) which for a full core model could be as large as 10,000. Currently, we cannot load the elemental solutions from the Exodus file with ParallelMesh. We also have mesh files that are very large due to the size of the problems that we are trying to solve. The use of parallel mesh helps us keep the amount of memory used per computational node manageable.

**Comment by YaqiWang** [comment]
This appears to be fixed. We will open new issues if there are any in the future.

**Comment by permcody** [comment]
Closing as complete.
