### ISSUE TITLE
Adding Dirac and mechanical constraint versions of contact tests

### ISSUE THREAD

**Issue by novasr** [idaholab/moose#3418]
We have many contacts tests based on the Dirac formulation of contact.  We should have mechanical constraint versions of those tests too.  In the case where we have a contact test using only the mechanical constraint formulation, we should add a Dirac version of that test.

**Comment by permcody** [comment]
@bwspenc, @novasr - This is a really old ticket. I think it's resolved as far as testing goes. Perhaps one of you can verify and close it?

**Comment by bwspenc** [comment]
I'm going to close this because we have another issue: #7283 for deprecating DiracKernel-based mechanical contact.  Moving all of the tests over to the Constraint system is part of that issue.
