### ISSUE TITLE
Default gnuplot output type not supported with our version of gnuplot

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#3441]
By default, gnuplot output from MOOSE asks for a png terminal.  The version of gnuplot that is supplied with the MOOSE environment package doesn't support the png terminal, so I can't run gnuplot on the .gp file that MOOSE generates with the default options.

I'm not sure why our gnuplot doesn't support png.  I'm guessing it's just a compile option that we don't have set.  We should either add png support to our gnuplot or use a different terminal type by default.

**Comment by permcody** [comment]
We don't really rely on GNUplot anymore for plotting capabilities. We've moved over to Python and Matplotlib. This ticket is old and not useful.
