### ISSUE TITLE
A material is used only by kernels but being called on sides

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3502]
The problem can be show on one of my branches: volume_material. The branch contains an input file which is almost identical with `moose/test/tests/materials/generic_constant_material/generic_constant_material_test.i` except that I am using a modified material `VolumeMaterial` from `GenericConstantMaterial`. In the test, the material is used only by the diffusion kernels, but its property evaluation is called on sides. I believe this is an undesired behavior. Please investigate.

**Comment by friedmud** [comment]
I'm rasing the priority on this.  It's related to #3273 which @aeslaughter is working on I believe.

We need to get better about only computing material properties when they're needed...

**Comment by YaqiWang** [comment]
This appears having been fixed. I verified the input. I am not sure which PR fixed this though.
