### ISSUE TITLE
LibMesh Abaqus reader does not support multiple *NODE sections

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#3587]
If there are multiple *NODE sections in an Abaqus file, the nodes from earlier *NODE sections are overwritten by nodes from the latter ones.

This screenshot demonstrates the [problem](https://drive.google.com/file/d/0B9BK7pg8se_iczRFdVNGTFR3cXc/edit?usp=sharing).

[Here](https://drive.google.com/file/d/0B9BK7pg8se_ieFV3MzRSNHVZTDQ/edit?usp=sharing) is a mesh which demonstrates the issue.

**Comment by permcody** [comment]
Not a MOOSE issue. Closed by https://github.com/libMesh/libmesh/pull/305
