### ISSUE TITLE
Peacock Copy and Paste Tree items

### ISSUE THREAD

**Issue by micahjohnson150** [idaholab/moose#3681]
It would be nice if I could copy and paste a tree item in peacock. For example I would make a Dirichlet boundary condition and I could copy/paste it, so I could quickly similar items that perhaps have a lot of repeat information.

**Comment by aeslaughter** [comment]
@brianmoose Did you do this?

**Comment by brianmoose** [comment]
There is a "clone" option that copies a block to a new name. Might be nice to have a shortcut for it or something as you currently right click and select "clone".
There is no "copy" then "paste" though, although we could conceivably add that. Highlight an item, hit the usual copy key sequence, then the usual paste sequence would do the clone that is already in place.

**Comment by friedmud** [comment]
Even "clone" is going to be awesome!  I know I'll use it a ton.  It's one
of the main reasons I still edit input files with a text editor most of the
time.

**Comment by aeslaughter** [comment]
This is in Peacock2.
