### ISSUE TITLE
cluster_launcher unable to accept a mem argument

### ISSUE THREAD

**Issue by micahjohnson150** [idaholab/moose#3740]
Tried to use cluster_launcher on Bechler using the following in a job_list file:

[Jobs]
  [./PHI_INITIAL]
    type = PBSJob
    chunks = 2
    mpi_procs = 20
    moose_application = ~/Projects/pika/pika-opt
    input_file = phi_initial.i
    walltime = 02:00:00
    cli_args = '-log_summary'
    [../]
[]

I get the following error:

qsub: Job has no memory requested.
 Please specify the total amount of memory needed
 (e.g., -l select=1:ncpus=32:mpiprocs=32:mem=100gb).

cluster_launcher does not have an memory argument.

**Comment by permcody** [comment]
Cluster launcher was deprecated and removed. Closing this issue.
