### ISSUE TITLE
DG with Material

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#3785]
When I use DG method with Material, there were two issues:
1. Currently we will have 3 material which are evaluated on volume, elements sides and neighboring element sides, which was submitted by Yaqi Wang  #1704. Sometimes, even mostly, kenel material and dgkernel material are different formulation. So,  Two materials should be defined per block, like CellMaterial, FaceMaterial. In CellMaterial, to avoid unnecessary copy, 'if(!_bnd)' statement was used to insure material property is calculated only in Kernel . Again,  'if(_bnd)'  in FaceMaterial. It is not clear code as described by Yaqi Wang.
2. To compute material property, couple variables is very convenient. FaceMaterial usually require both value and neighbor value of side. But, Material is derived class of Coupleable, the coupledNeighborValue feature can't be used in FaceMaterial.

**Comment by friedmud** [comment]
I think this can be closed.  Let us know if there is somethi that still needs doing in the framework here.
