### ISSUE TITLE
Allow FiniteStrainPlasticBase to cut model's timestep

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#3789]
When the returnmap fails, the model's timestep should be cut.  This should be easy after PR #3776 is merged, and issue #3777 is completed.  Instead of

```
if (!return_successful)
{
  debug stuff;
  mooseError("Exiting");
}
```

only do this if the debug flag is set appropriately.  Otherwise signal to moose to cut the timestep.

**Comment by friedmud** [comment]
#3777 is almost finished... you should be able to do this soon

**Comment by WilkAndy** [comment]
Great, thanks for that.

**Comment by WilkAndy** [comment]
@permcody , @friedmud , you can see in the above branch i've attempted to cut the timestep during a residual calculation.  When you run the test file, you get the "Impossible" error that was obtained by @Hadrien89 when he did the same thing in Redback.

This "Impossible" from line3314 in FeProblem::computeResidual

void
FEProblem::computeResidual(NonlinearImplicitSystem &/*sys*/, const NumericVector<Number> & soln, NumericVector<Number> & residual)
{
  try
  {
    computeResidualType(soln, residual, _kernel_type);
  }
  catch(MooseException & e)
  {
    mooseError("Impossible");
    // Blank on purpose because this error should have already been dealt with
  }
}


I don't know what we're doing differently than ExceptionKernel.  Do you think you could investigate ?

**Comment by permcody** [comment]
Yeah - this is important. I'll see if one of us can take a look. It'll probably be next week. Maybe @jwpeterson?

**Comment by WilkAndy** [comment]
Just giving you a nudge...

a

**Comment by WilkAndy** [comment]
Related to this, it would be really neat if when libmesh detected a negative jacobian the timestep could be cut.  negative jacobians seem to be happening for me quite a bit recently, boohoo.

**Comment by jwpeterson** [comment]
> Related to this, it would be really neat if when libmesh detected a negative jacobian the timestep could be cut.

We'd need to have a try/catch around wherever the Elems are reinit'd, probably somewhere in the Assembly object, but this is an interesting idea.

**Comment by WilkAndy** [comment]
Please do it - it'd make my life much easier!

**Comment by friedmud** [comment]
It looks like it wouldn't be too hard.  libMesh does throw an exception for a negative Jacobian... just need to catch it and rethrow it as a `MooseException`

**Comment by WilkAndy** [comment]
Oh that's really good news.  You can imagine the disappointment when i've waited days for a big job to complete only to encounter a negative jacobian, and then have to screw around with time steps (or something else) to get the simulation to pass over the negative-jacobian state.

**Comment by WilkAndy** [comment]
Giving you a nudge on this!

**Comment by WilkAndy** [comment]
Hey everyone (@jwpeterson, @permcody, @friedmud), do you think we could escalate the priority on this "Impossible" error?  We're currently experiencing quite a few problems in our simulations that would disappear if we could cut the timestep during a solve.

**Comment by permcody** [comment]
Andy,

I'll get this added for you.

Cody

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a

**Comment by WilkAndy** [comment]
Fixed by #8059

**Comment by bwspenc** [comment]
So, it seems like we have a really similar issue.  @backmari is running a model with plasticity (solid_mechanics, in our case) that dies when it inverts elements. @WilkAndy, you mentioned in this thread that you want to recover from negative Jacobian errors. We don't have that capability, even with this commit, right?  If I understand this correctly, this gives us the ability for a material with stateful properties to throw an exception without getting a segfault, and there's probably still more work to be done. Those negative Jacobians are occurring before the material gets called anyway, so the material wouldn't do anything to catch those.

**Comment by WilkAndy** [comment]
Everything you say is true, @bwspenc .  The cutting dt works fine for me now (so far) which is what this issue was originally about, but the negative Jacobian is a real pain in the bum.  I'd like it if libmesh could signal to moose to cut dt when something screwy happened with the Jacobian.

**Comment by bwspenc** [comment]
@WilkAndy Thanks.  So how are you cutting dt?  I assume it's something you're doing in your material model.

**Comment by WilkAndy** [comment]
Yea, in my Material I have something like

```
  if (bad)
    throw MooseException("bad thing");
```
