### ISSUE TITLE
AddExtraNodeset needs option to execute after uniform_refinement

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#3790]
I was trying to add nodeset on a single node, but needed to start with a coarse mesh and then perform uniform refinement. This caused the nodeset to be placed on a node in the original mesh, which was far away from the desired location.

**Comment by aeslaughter** [comment]
This is not an issue, the solution for this is to utilize the node location rather than id.

**Comment by friedmud** [comment]
A while ago we thought about adding a UniformRefinementMeshModifier...
whatever happened to that idea?  That would allow the MeshModifier
dependency system to put these things in the right order...

**Comment by permcody** [comment]
That's not a bad idea, but I'd rather not add it until it's really needed to avoid having two ways to do *almost* the same thing. Yes, I see the extra utility of being able to mix refinement steps with modification steps.
