### ISSUE TITLE
_console flush will not be available before Console is constructed

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#3942]
If you have an action that will be fired before the `AddOutputAction` and trying to use _console to do some outputs, you will notice that those outputs will not be flushed even you indeed put std::endl or std::flush in the outputs. The behavior will be different from directly using std::cout.

The issue can be seen by adding one line like
`std::cout << " something " << std::endl`
after the if statement in `ActionWarehouse::executeActionsWithAction()` and turn `Debug::show_actions` on in the input.

I guess the simplest solution would be:
--flush the screen in OutputWarehouse even no Console is available but do not clear the buffer;
--flush the buffer to the file in the constructor if Console is redirected;
--then clear the buffer in the AddOutputAction;

**Comment by permcody** [comment]
@YaqiWang - Old issue but I think we've handled all the flushing correctly at this point.

**Comment by YaqiWang** [comment]
We talked about adding an app header to print some information which can be printed out before action system starts. How that goes?

**Comment by aeslaughter** [comment]
@YaqiWang, we did talk about adding a header routine. I will open an issue for that and try to get that done today.
