### ISSUE TITLE
MultiAppNearestNodeTransfer doesn't work for transferring _from_ an elemental variable

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4002]
While that "kind of" makes sense... it does support transfer _to_ elemental variables so it should also support transferring _from_ them.

In the meantime it could at least give a good error if you try to do this!  Currently it segfaults!

**Comment by GiudGiud** [comment]
This is tested and supported, see transfers/multiapp_nearest_node_transfer/to_sub_parent test:
```
[Transfers]
 ...
  [to_sub_elemental_to_nodal]
    type = MultiAppNearestNodeTransfer
    to_multi_app = sub
    source_variable = u_elemental
    variable = elemental_source_from_parent_nodal
  []
  [to_sub_elemental_to_elemental]
    type = MultiAppNearestNodeTransfer
    to_multi_app = sub
    source_variable = u_elemental
    variable = elemental_source_from_parent_elemental
  []
[]

```
