### ISSUE TITLE
Figure out why our Makefiles are so slow

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#4068]
It takes about 4 seconds to run "make clean" in an app when there is nothing to do.  
```
$ /usr/bin/time -p make clean
real         4.10
user         3.24
sys          0.80
```
And if you put a print statement in the clean target, you can see that the actual cleaning takes almost no time, while "getting ready to clean" takes all the time.  The output of `make -d -n clean` is also pretty illuminating/worrying, but there is a ton of stuff going on, so it will take some effort to figure out which part(s) are slow.

**Comment by aeslaughter** [comment]
Is this complete now?

**Comment by jwpeterson** [comment]
Seems to be unchanged or even a bit worse.  Just tested make clean in Bison.

With files to be removed:
```
$ /usr/bin/time -p make clean
real        10.89
user         9.92
sys          0.80
```

With no files to be removed, the best time I saw was:
```
$ /usr/bin/time -p make clean
real         5.61
user         5.06
sys          0.60
```

So I'd say 98d5eec didn't make much difference. The game has also changed slightly since this ticket was opened... we now use more recursion in the app Makefiles, etc.

**Comment by permcody** [comment]
I really don't see anything we can do about this with our Makefile system. We have Makefiles included from Makefiles which is rather elegant from a maintenance perspective and it all rides on top of libMesh which has it's own rules and complexity. I would vote that we close this ticket. I don't believe we are doing "extra" work or that it could be cleaned up without significantly revamping or otherwise nice system.

**Comment by WilkAndy** [comment]
Awesome, so next time i come to IdahoFalls it looks like i owe you a beer.  I look forward to it :-)

a

**Comment by jwpeterson** [comment]
> it all rides on top of libMesh which has it's own rules and complexity.

We no longer include any Makefiles from libmesh in MOOSE.

> I would vote that we close this ticket.

Fine with me!

> Awesome, so next time i come to IdahoFalls it looks like i owe you a beer. I look forward to it :-)

I think you mean we owe you a beer since the "we can't do anything about it" part of your prediction came true.
