### ISSUE TITLE
Non-unique property names defined in different materials but on the same block should issue a warning.

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#4081]
Property names should be unique. I created a test case "test/tests/UniqueMatProp/unique_property_name.i" that has two materials with different names, but they contain a property with the same name. 

Shouldn't this create at least a warning or even throw an error?

**Comment by permcody** [comment]
@aeslaughter - please check this ticket

**Comment by aeslaughter** [comment]
I think this will be fixed with my new warning, I will take care of it.

**Comment by permcody** [comment]
@aeslaughter - I believe this has been fixed, but I can't seem to find the test, ticket or PR to reference. I'm not searching for the right things here. Maybe you can find it and reference here?

**Comment by aeslaughter** [comment]
We are testing this here: https://github.com/idaholab/moose/blob/devel/test/tests/materials/declare_overlap/tests
