### ISSUE TITLE
Test harness fails on systems where system Python is 3.X

### ISSUE THREAD

**Issue by jasonmhite** [idaholab/moose#4169]
The test harness script uses `/usr/bin/env python` as its shebang line, but it is Python 2.X dependent. If you run it on a system where `python` points to `python3`, it fails.

This is easy to fix, just pointing to `/usr/bin/env python2` resolves it. This should exist if Python 2.X is installed.

I think this also causes the build to fail, because the script to generate `MooseRevision.h` has the same issue, but fails silently. A quick grep shows that there a couple other places too.

I have a quick fix for at least the build harness. You should be able to do the same for the other scripts, but I don't know my way around well enough to mess with them.

**Comment by cticenhour** [comment]
MOOSE fully supports Python 3.X
