### ISSUE TITLE
fortran things not working in water_steam_eos

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4178]
I've just starting "moosing" on another cluster and I get the linker error:

Linking Executable /home/wil04q/projects/moose/modules/combined/modules-opt...
/home/wil04q/projects/moose/modules/water_steam_eos/lib/libwater_steam_eos-opt.so: undefined reference to `_gfortran_transfer_integer'
/home/wil04q/projects/moose/modules/water_steam_eos/lib/libwater_steam_eos-opt.so: undefined reference to `_gfortran_transfer_real'
/home/wil04q/projects/moose/modules/water_steam_eos/lib/libwater_steam_eos-opt.so: undefined reference to `_gfortran_st_write'
/home/wil04q/projects/moose/modules/water_steam_eos/lib/libwater_steam_eos-opt.so: undefined reference to `_gfortran_transfer_character'
/home/wil04q/projects/moose/modules/water_steam_eos/lib/libwater_steam_eos-opt.so: undefined reference to `_gfortran_st_write_done'
/home/wil04q/projects/moose/modules/water_steam_eos/lib/libwater_steam_eos-opt.so: undefined reference to `_gfortran_stop_numeric'
collect2: ld returned 1 exit status

Someone, please close this ticket if this is inconvenient to fix.  It may be just because of my old gcc:

~/projects/moose/modules/tensor_mechanics> /apps/openmpi/1.4.5-gnu/bin/mpicxx --version
g++ (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]
Copyright (C) 2008 Free Software Foundation, Inc.
:~/projects/moose/modules/tensor_mechanics> gfortran --version
GNU Fortran (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]
Copyright (C) 2008 Free Software Foundation, Inc.

**Comment by permcody** [comment]
This module will be replaced eventually.
