### ISSUE TITLE
SIGSTOP from "make -j 5 test"?

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#4201]
Accidentally trying to run "make test" in parallel, I discovered it constantly being interrupted, every few dozen tests, by:

"[2]+  Stopped                 make -j 5 test"

If I run "fg" fast enough the tests still seem to be completing; miss it and they die from timeouts.

I can't see where this could be coming from; the test framework seems to use SIGKILL on timed-out tests but nothing seems to be sending SIGSTOP.  This is obviously not an urgent problem ("make test" works fine in serial), just unexpected behavior.

**Comment by permcody** [comment]
@roystgnr - What OS where you using when you ran into this issue?

**Comment by roystgnr** [comment]
Sorry, that reply must have been buried in my inbox.  Ubuntu 14.10 is where I'm (still, unless I set MOOSE_JOBS to 1 or use "./run_tests -j 5" manually) seeing the problem.

**Comment by permcody** [comment]
Well I just logged into one of our build boxes (Ubuntu 14.04 clients that work on moosebuild jobs) and tried that command. It ran fine - sigh... I don't understand how that rule is getting screwed up on your system.

**Comment by friedmud** [comment]
Another report of this on Suse: https://groups.google.com/forum/m/#!topic/moose-users/s174Ob0FaLw

**Comment by permcody** [comment]
@friedmud - we have no problem replicating this on OpenSuSE. Jason has a box here and it does it every time we go over -j 5.

**Comment by friedmud** [comment]
Wow - WTH?

**Comment by permcody** [comment]
We simply use subprocess.Popen() to start jobs and then we don't check on them immediately giving us multiprocess capability in the TestHarness without having to use forks, threads or any other library. We launch jobs continuously and call "poll" on all of the launched jobs too clean up as we go. It's all rather straight forward. I don't even know how to Google what this problem could be, my attempts so far have yielded absolutely nothing.

**Comment by permcody** [comment]
Oh, one more clarification. Despite Roy's original report, we have eliminated `make` as a source of problems. We can replicate this issue with just `./run_tests -j 5`

**Comment by friedmud** [comment]
Is it possible it's some sort of ulimit kind of thing that's keeping you
from making too many processes too quickly or something?

**Comment by permcody** [comment]
That's a reasonable idea to test...  Maybe I'll try scaling the tests and
see if the problem shows up. I know that Jason put a while(true) bash
statement around run_tests and got it to blaze through them all even though
it was constantly stopping.

**Comment by permcody** [comment]
This sigstop issue is coming from the gdb backtrace logic in libMesh. @jwpeterson is investigating the issue a little more closely.

**Comment by jwpeterson** [comment]
I definitely believe it could be the gdb backtrace... it wasn't really designed to be super fast, since the assumption is that you are crashing anyway.  And if the test harness decides to run 24 expect_err tests at the same time, I could see it being *really* slow, but I guess I don't understand what this has to do with SIGSTOP.

**Comment by jwpeterson** [comment]
This should hopefully be fixed with the latest libmesh update.
