### ISSUE TITLE
Segmentation fault 11 during contact

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#4302]
I first ran into this issue when helping a user with a seg fault.  I ran their case through LLDB and the debugger stopped on line 155 of SlaveConstraint.C

const Node \* node = pinfo->_node;

I then looked at the mesh being used and although the side sets used for the master and slave surfaces in the contact block had unique side set IDs they both contained the same surface ID.  (i.e. the master and slave surface was the same surface).  When I corrected the surfaces in one of the side sets the problem ran to completion. 

This problem was rather large so I tried recreating this seg fault on a smaller problem.  From what I can see, the segfault is not observed if the surface is flat, but is observed if the surface is curved.  The problem I am using is the ring_contact test in moose/modules/combined/tests/ring_contact/.  If I modify the mesh such that side set IDs 2 and 3 both contain surface ID 2 and run the problem, it solves.  If I modify the mesh such that side set IDS 2 and 3 both contain surface ID 3 I obtain a segfault.  Running through the debugger results in the code stopping  on the same line as above (155 of SlaveConstraint.C)

Does anyone have any idea why this scenario would seg fault in certain cases and not others?

**Comment by permcody** [comment]
@gambka - This looks like an old ticket and can probably be closed. Please verify and close if appropriate.
