### ISSUE TITLE
Creating training materials on wiki

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4343]
Use this ticket for changes to PresentationBuilder while migrating training materials to the wiki
- [x] Using contents with a SlideSet that is a single slide causes an error.
- [x] When converting adapt.i to html build.py gives a key error when processing image 147. Html file is not generated.
- [x] When building UserObject slides the 4th slide "Using a UserObject" is not getting the background image correctly.

**Comment by aeslaughter** [comment]
TODO:
- [ ] Using contents with a SlideSet that is a single slide causes an error.

**Comment by grimtk** [comment]
When converting adapt.i to html build.py gives a key error when processing image 147. Html file is not generated.

**Comment by grimtk** [comment]
When building UserObject slides the 4th slide "Using a UserObject" is not getting the background image correctly.
