### ISSUE TITLE
getMaterialProperty Refactor

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4414]
This ticket is for the work to refactor getMaterialProperty[Old[er]].
# Design
- Remove all duplicate logic for getMaterialProperty
- Implement callback mechanism for where special handling is necessary (i.e. `MaterialPropertyInterface` vs `Material`)
- Properly implement `isMatPropRequested()`
- Properly implement dependency resolution
  - take into account test cases with old or older properties

Refs/supersedes #4333, #4324, #4323

**Comment by aeslaughter** [comment]
This should also make getMaterialProperty become:
```cpp
const MaterialProperty<T> & getMaterialProperty(...) const;
```

**Comment by permcody** [comment]
@aeslaughter - @dschwen Apparently we have a gold mine of tickets for mat property everything. This one may not be completely done. but you have both worked in this area now.

**Comment by dschwen** [comment]
If any further refactoring is needed I suggest opening a new ticket.
