### ISSUE TITLE
Can we output some simulation information earlier?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4454]
I have some customed actions which output some important information. But these information come out earlier than the framework information to the console. Can we output some simulation information a bit earlier with the following patch?

```
diff --git a/framework/src/outputs/Console.C b/framework/src/outputs/Console.C
index 9938789..84ecfee 100644
--- a/framework/src/outputs/Console.C
+++ b/framework/src/outputs/Console.C
@@ -149,6 +149,26 @@ Console::Console(const std::string & name, InputParameters parameters) :
         Moose::_color_console = false;
     }
   }
+  // Framework information
+  std::stringstream oss;
+  if (_app.getSystemInfo() != NULL)
+    oss << _app.getSystemInfo()->getInfo();
+
+  if (_problem_ptr->legacyUoAuxComputation() || _problem_ptr->legacyUoInitialization())
+  {
+    oss << "LEGACY MODES ENABLED:\n";
+    if (_problem_ptr->legacyUoAuxComputation())
+      oss << "  Computing EXEC_RESIDUAL AuxKernel types when any UserObject type is executed.\n";
+    if (_problem_ptr->legacyUoInitialization())
+      oss << "  Computing all UserObjects during initial setup.\n";
+  }
+
+  oss << std::left << '\n'
+      << "Parallelism:\n"
+      << std::setw(_field_width) << "  Num Processors: " << static_cast<std::size_t>(n_processors()) << '\n'
+      << std::setw(_field_width) << "  Num Threads: " << static_cast<std::size_t>(n_threads()) << '\n'
+      << '\n';
+  write(oss.str());
 }
 
 Console::~Console()
@@ -547,25 +567,6 @@ Console::outputSystemInformation()
 
   std::stringstream oss;
 
-  // Framework information
-  if (_app.getSystemInfo() != NULL)
-    oss << _app.getSystemInfo()->getInfo();
-
-  if (_problem_ptr->legacyUoAuxComputation() || _problem_ptr->legacyUoInitialization())
-  {
-    oss << "LEGACY MODES ENABLED:\n";
-    if (_problem_ptr->legacyUoAuxComputation())
-      oss << "  Computing EXEC_RESIDUAL AuxKernel types when any UserObject type is executed.\n";
-    if (_problem_ptr->legacyUoInitialization())
-      oss << "  Computing all UserObjects during initial setup.\n";
-  }
-
-  oss << std::left << '\n'
-      << "Parallelism:\n"
-      << std::setw(_field_width) << "  Num Processors: " << static_cast<std::size_t>(n_processors()) << '\n'
-      << std::setw(_field_width) << "  Num Threads: " << static_cast<std::size_t>(n_threads()) << '\n'
-      << '\n';
-
   MooseMesh & moose_mesh = _problem_ptr->mesh();
   MeshBase & mesh = moose_mesh.getMesh();
   oss << "Mesh: " << '\n'
```

It will make my screen output much cleaner and logically making sense.

Thanks.

**Comment by aeslaughter** [comment]
Somehow I missed this entire conversation. But, all of the system information stuff is produced in the `Console::outputSystemInformation` method. With a few minor tweaks to Console you can create your own Console object (e.g., YakConsole) that can adds to this information. 

The only catch is that you will not be able to add to this information before the YakConsole object is constructed unless, as mentioned, we come up with a buffering system for the system information you want to add, which isn't too unreasonable.

**Comment by permcody** [comment]
@aeslaughter  - Let's use this ticket per our discussion to output the application header information early.

I propose that we add a call to `FEProblem::initialSetup()` to output header information at the very top after all the Actions have been executed but before any initial setup is done to the simulation. We'll then call the normal output at the bottom of `FEProblem::initialSetup()` for the remaining output. That should help with this ticket as well as some of the Multiapp output ordering issues.

**Comment by YaqiWang** [comment]
Are we having this header capability now? This seems to me a really low hanging fruit.

**Comment by aeslaughter** [comment]
Yes the header capability is in place, there is a virtual method "header"
in MooseApp.

**Comment by YaqiWang** [comment]
I tried, but the header comes out after outputs to `_console` in action, which is not what we meant to do. See the first few lines in `FEProblem::initialSetup()`.

**Comment by aeslaughter** [comment]
Can you send me an input file that demonstrates the behavior? I will see
what I can do to get things in the correct order.

**Comment by YaqiWang** [comment]
You can checkout my branch `header_ordering`, and then run yak/tests/actions/diffusion_cfem/diff_cfem.i.
