### ISSUE TITLE
Simple BISON test fails with threading

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#4457]
The phase_transition_zircaloy test in BISON fails with threading (sometimes passes, sometimes fails).  The test uses a BISON material model but is fairly standard otherwise.  It uses MOOSE Postprocessors.  I'm not sure what to look at to sort it out.

**Comment by permcody** [comment]
Currently working on refactoring the test harness to make launching jobs through a queueing system easier, more reliable and with support for prereqs and other necessary features. I'll get to this when I complete the current task.

**Comment by permcody** [comment]
I'd like to take a look at this issue.
https://github.com/libMesh/libmesh/pull/842 fixed a lot of threading issues everywhere. It's quite possible that the test that spawned this issue may work properly now. I did some quick grepping but didn't locate it. Do you know where this test is located?

**Comment by jasondhales** [comment]
tests/phase_transition_zircaloy/.  I didn't find it at first either.

**Comment by permcody** [comment]
@jasondhales - I ran this test about a hundred times on different numbers of threads from 1 - 15 without a single exodiff. I believe this issue like many of the other threading issues can finally be closed.
Close by https://github.com/libMesh/libmesh/pull/842
