### ISSUE TITLE
Aux System serialized solution not resized when mesh refined

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4490]
Not sure how this has slipped through this long - but if you're using the serialized solution vector from the Aux system with mesh refinement (even uniform refinement) the serialized solution vector doesn't get resized leading to a segfault.

Working on a good test and fix for this now...

**Comment by friedmud** [comment]
@mellis13 uncovered this with some MultiApp work he's doing...

**Comment by friedmud** [comment]
Wow!  Looks like we don't have any tests or any code using `serializedSolution()` at all?

On the one hand that's really awesome (because we shouldn't be depending on it) - on the other hand it means we're not testing it all...

**Comment by friedmud** [comment]
Looks like Transfers that use serialized solutions are doing their own localizations - which kinda sucks...

**Comment by friedmud** [comment]
On the other hand that's not that bad because that way the serialization only happens for the Transfer and not anywhere else...

Anyway - we need some tests of `serializedSolution()`

**Comment by mellis13** [comment]
I really opened up a can of worms here... sorry MOOSE team!
