### ISSUE TITLE
Peacock stumbles when parsing an input file with multiple directives per line

### ISSUE THREAD

**Issue by dasmy** [idaholab/moose#4491]
When reading an input file that does not contain a line break or comment after each directive, it completely messes up the parsed syntax tree. However, such files are read and parsed correctly by moose itself
For example,  reading

        [Variables]
          [./xxx] # my fancy variable comment
            x = 3 # and a parameter comment
          [../]
          [./aaa] a = 1 [../] 
          [./bbb] b = 2 [../]   [./ccc] c = 3 [../]
          [./ddd] d = 4 [./eee] e = 5 [../] [../]   [./fff] f = 6 [../]
        
          [./ggg]
            g = 7  [../]
        []
results in
![screen shot 2015-01-07 at 11 22 38](https://cloud.githubusercontent.com/assets/5322274/5644367/138c4572-9663-11e4-9ebe-c1af734aaff0.png)

Especially in recurring definitions with only few parameters like variables, almost identical kernels, etc. I am using the one-line notation quite often since it avoids too much scrolling and shows differences between the entries and possible typos much more obvious, e.g. in

    [Kernels]
      [./stressdiv_dispx] type=CardiacKirchhoffStressDivergence  variable=dispx  component=0  displacements='dispx dispy dispz' [../]
      [./stressdiv_dispy] type=CardiacKirchhoffStressDivergence  variable=dispy  component=1  displacements='dispx dispy dispz' [../]
      [./stressdiv_dispz] type=CardiacKirchhoffStressDivergence  variable=dispz  component=2  displacements='dispx dispy dispz' [../]
    []

Therefore, I would like to see this issue fixed.

**Comment by dasmy** [comment]
I actually do have a fix for this (https://github.com/dasmy/moose/commit/0495c3adde28230f98be5da65ccf666aea4e1a66), which - for the example input file above results in 
![screen shot 2015-01-07 at 11 24 27](https://cloud.githubusercontent.com/assets/5322274/5644754/5d8799fc-9667-11e4-9f89-fc74b81cd477.png)
i.e. the desired behaviour.
Apart from this, in my eyes it simplifies the parsing code and avoids code duplication for comment-parsing.
The primary change is in the regular expressions which do not match to the end of line but only to the end of the current directive. After interpreting it, parsing is continued for the remainder of the current line.

Do you also want to see this modification?
Does it make sense to file a pull-request?
If yes, do you see a way of adding an appropriate regression test or can these changes go without?

**Comment by permcody** [comment]
Please submit a PR. Right now we don't have any regression tests for the Python Parser unfortunately but we will someday. For now, one of us will test your branch by opening several different files and making sure everything works correctly in the GUI. If there is a regression due to your fix, we'll deal with it at that time.
