### ISSUE TITLE
Execution of initialSetup in transfers

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#4498]
It seems like initialSetup for transfers is never executed. More specifically, when 
_transfer(EXECUTE_ON)[0].initialSetup() is executed in FEProblem _all_objects is empty and 
the loop is never entered.

**Comment by permcody** [comment]
Should be a simple fix.

**Comment by snschune** [comment]
Will you track it down or should I?

**Comment by permcody** [comment]
Either way. We should be calling initialSetup on each system in FEProblem::initialSetup(). If it's not there it should just be added. The question is where exactly does it go? Probably after Multiapps. I won't get to this until next week at the earliest.

**Comment by snschune** [comment]
Ok, I'll do it then. 

I am not quite sure I understand your explanation of the problem, though. In FEProblem::initialSetup, TransferWarehouse::initialSetup() is called. The problem is that at this point TransferWarehouse::_all_objects is empty. However, I made sure that  TransferWarehouse::addTransfer is called prior to initialSetup and that _all_objects has the correct length and gets the correct transfers by just printing activity in TransferWarehouse::addTransfer.

**Comment by permcody** [comment]
_all_objects should not be empty when initialSetup() is called. Something
else seems fishy here.

**Comment by snschune** [comment]
So _transfers is empty but _to_multi_app_transfers and _from_multi_app_transfers are not. 
So the bug is in FEProblem::addTransfer, where _transfer.addTransfer is not called. 

I do not understand the logic of the if statement, though:
```
  if (multi_app_transfer.get())
  {
    std::vector<ExecFlagType> transfer_exec_flags = multi_app_transfer->execFlags();
    const std::vector<ExecFlagType> & multiapp_exec_flags = multi_app_transfer->getMultiApp()->execFlags();

    if (transfer_exec_flags.empty())
      transfer_exec_flags.assign(multiapp_exec_flags.begin(), multiapp_exec_flags.end());
    else if (transfer_exec_flags != multiapp_exec_flags)
      mooseDoOnce(mooseWarning("MultiAppTransfer execute_on flags do not match associated Multiapp execute_on flags"));

    for (unsigned int i=0; i<transfer_exec_flags.size(); ++i)
      if (multi_app_transfer->direction() == MultiAppTransfer::TO_MULTIAPP)
        _to_multi_app_transfers(transfer_exec_flags[i])[0].addTransfer(multi_app_transfer);
      else
        _from_multi_app_transfers(transfer_exec_flags[i])[0].addTransfer(multi_app_transfer);
  }
  else
  {
    const std::vector<ExecFlagType> & exec_flags = transfer->execFlags();
    for (unsigned int i=0; i<exec_flags.size(); ++i)
      _transfers(exec_flags[i])[0].addTransfer(transfer);
  }
```

Probably change it to:
```
  if (multi_app_transfer.get())
  {
    std::vector<ExecFlagType> transfer_exec_flags = multi_app_transfer->execFlags();
    const std::vector<ExecFlagType> & multiapp_exec_flags = multi_app_transfer->getMultiApp()->execFlags();

    if (transfer_exec_flags.empty())
      transfer_exec_flags.assign(multiapp_exec_flags.begin(), multiapp_exec_flags.end());
    else if (transfer_exec_flags != multiapp_exec_flags)
      mooseDoOnce(mooseWarning("MultiAppTransfer execute_on flags do not match associated Multiapp execute_on flags"));

    for (unsigned int i=0; i<transfer_exec_flags.size(); ++i)
      if (multi_app_transfer->direction() == MultiAppTransfer::TO_MULTIAPP)
        _to_multi_app_transfers(transfer_exec_flags[i])[0].addTransfer(multi_app_transfer);
      else
        _from_multi_app_transfers(transfer_exec_flags[i])[0].addTransfer(multi_app_transfer);

    const std::vector<ExecFlagType> & exec_flags = transfer->execFlags();
    for (unsigned int i=0; i<exec_flags.size(); ++i)
      _transfers(exec_flags[i])[0].addTransfer(transfer);
  }
  else
    mooseError("Some meaningful error message");
```

**Comment by snschune** [comment]
So in the modifications above I made sure that MultiAppTransfers are added to _transfers. 
The problem is not that it fails a whole bunch of tests - all those that call 
```
variableIntegrityCheck(_to_var_name);
```
in initialSetup.

**Comment by YaqiWang** [comment]
Should those calls be protected by the transfer direction?

**Comment by snschune** [comment]
@YaqiWang : I am not sure. The name suggests that  it should contain all MultiAppTransfers (from & to) + all Transfers. why would initialSetup only be called on one and not the other?

**Comment by permcody** [comment]
InitialSetup should definitely be called on all transfers. The idea is that it should be called on all MooseObjects.

**Comment by permcody** [comment]
Sorry guys, still haven't looked at this but I think I understand. There are `Transfers` and then there are `MultiappTransfers` which is a specialization of a Transfer. We probably fill up different containers in the warehouse depending on the type of transfer. We should still call initialSetup() on all of them but that probably explains why the generic "Transfers" container is empty. All of your transfers are of the Multiapp kind.

**Comment by snschune** [comment]
So there are two options then. 

1. When calling _transfer.initialSetup() also call  _from/to_multi_app_transfers. Leave the addTransfer
    as it is.

2. Add MultiAppTransfers to _transfers. Since MultiAppTransfer inherits from Transfer, it is a Transfer 
   itself and should be added to _transfers. 

Either way, the variableIntegrityCheck(); will fail.

**Comment by permcody** [comment]
Maybe, I'm not sure without looking at it if there are any other impacts for either option...

**Comment by friedmud** [comment]
I think either option will work.

I've been thinking about removing the idea of having Transfers that aren't MultiApp Transfers... in the beginning I thought we would have lots of types of Transfers... but the MultiApp system has proved to be more useful than I originally thought and most people just want to do that...

**Comment by permcody** [comment]
@snschune - I believe this ticket has been resolved. Can you comment and close if appropriate? I'm trying to cruise through several Multiapps/Transfers tickets for the upcoming tiger team.

**Comment by snschune** [comment]
Issue resolved.
