### ISSUE TITLE
Create Darcy Tutorial

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4522]

**Comment by friedmud** [comment]
Steps we need:

1.  Introduce problem
1.  Setup geometry and solve Diffusion axisymmetric
  a. Slides discussing Diffuions Kernel structure
1.  Custom Kernel inherited from Diffusion `DarcyPressure`
  a.  Directly pass in parameters
1.  Replace parameters with Material
  a.  `permeability` and `viscosity`
  b. 
1.  Introduce Aux System
  a.  Compute velocity (average per element)
1.  Heat conduction only on same geometry
1.  Transient Heat Conduction
  a.  Add time talk about Executioners
1.

**Comment by WilkAndy** [comment]
I'm not sure what exactly you're doing here, but it looks good to me.  Occasionally people ask me "Can MOOSE solve Darcy's equation", and when i say it's basically just diffusion I get confused looks.  A description of how to translate Darcy parameters (permeability, viscosity, etc) to diffusion parameters (diffusivity) might be appropriate.  Also, i wonder whether you're planning to let the viscosity depend on temperature - that's very physical and surely moose would be good at doing this.

Sorry if i've completely misunderstood your plans!

**Comment by friedmud** [comment]
The idea here is to create a more "hands on" and "engineering relevant" set of training slides... instead of the normal MOOSE Workshop stuff that is all very abstract.

In the end it will couple Darcy, Heat Conduction and Solid Mechanics.... possibly with microstructure solves (via MutliApps) for microstructure informed thermal conductivity.

As for temperature dependent viscosity... that's a great idea!  Do you have a good reference for a fairly simple correlation for water?

**Comment by WilkAndy** [comment]
I would love to be involved in this mini project, but am not sure how much time I will have.  Anyway, ask me to do things - i can only say "sorry, no".

If you're doing TensorMechanics, then i don't *think* axisymmetric is possible at the moment.

Regarding the viscosity of water - TOUGH2 has very accurate measurements of this, and perhaps it's already somewhere in MOOSE from @rpodgorney.  Those are necessarily quite complex correlations of viscosity with temperature and pressure, and I don't see anything wrong with using something super accurate, but if you want something simpler, have a look at Section 8.2 of http://en.wikipedia.org/wiki/Viscosity#Viscosity_of_water , and you'll see something small and pretty accurate.

**Comment by aeslaughter** [comment]
We created it, so I am closing this. For changes needed to the workshop see #5307
