### ISSUE TITLE
Error in Material::hasMaterialProperty

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#4523]
```Material::hasMaterialProperty``` returns true even if material does not have the 
material property.

**Comment by permcody** [comment]
Is this after making calls to getMaterialProperty()?

**Comment by snschune** [comment]
There will be an example shortly.

**Comment by snschune** [comment]
So the Material ```sigma_total``` does not have property ```multi1```. But when I print the output
of ```hasMaterialProperty``` in the executioner, it returns ```true```.

**Comment by permcody** [comment]
`hasMaterialProperty()` doesn't care about who publishes the property, it's just an interface that lets the user know if a material property is available. It is one of our oldest interfaces that predates having multiple materials, block and boundary restrictions and several other interfaces. It certainly needs to be updated in several ways to be useful. It should be very easy to fix it for this case (i.e. which materials publish which properties). More work will be needed to fix for block/boundary restrictions.

Thanks for the example code.

**Comment by snschune** [comment]
So for me that is not necessarily critical. I'll go through MaterialData->getProperty<T>(name) now to get a reference to the desired material property. That is better anyway because it beats the problem
of having the same property defined in different materials on different blocks (At least I hope so).

**Comment by snschune** [comment]
Issue resolved.
