### ISSUE TITLE
Scalar Variable Memory Optimization

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4529]
This ticket is a follow on to the #4174. There have been reports of excessive memory usage when several scalar variables are added to a system.

@andrsd do you have an example that you can provide?

**Comment by andrsd** [comment]
Excessive memory usage was referring (AFAIK) to the allocation of entries in the Jacobian matrix. Let's say we have a problem with no scalar variables of a size 1000x1000. Now we add a first order scalar variable with that has support over the whole domain. That will add a dense row (1001 entries) and a dense column to the system. However, if the scalar variable is needed only, let's say, at one node, we wasted 999 entries in the matrix. We can reduce these by restricting the scalar variable to a subdomain - which @roystgnr already implemented in libMesh. But, I think, we do not have enough tests in our test suite (IIRC). In the ideal world, we should be able to restrict the scalar variable to nodes. How difficult that is, I can not tell.

We typically see this in RELAP-7, but those problem are way to complicated to bring them into MOOSE. I put a simple 1D example into our test suite that uses mortar method to connect 2 disjoint 1d meshes. It is simple enough to test stuff. On the other hand it only has one field variable, thus we have only 1 scalar variable. However, we could add one or more variables and to the same thing to have more scalar variables active, if needed.

Does that answer your question?

**Comment by rui-hu** [comment]
Searched online on the scalar variable use in MOOSE and LIbMesh, and found this post. I'm curious to know if there are any updates on this issue. 

I'm also encountering a problem with my application (SAM, a spin-off of RELAP-7), i.e., the problem initialization became very slow if a large number of scalar variables was used. Checking the performance log, the majority of the time was used in eq.init(). Tacking down the problem, I found most of the time were actually spent in LibMesh::DofMap::build_sparsity().

**Comment by andrsd** [comment]
What is large? I have about 34 in a problem I am running currently and all sets up pretty fast....

**Comment by rui-hu** [comment]
For a problem with 42 Scalar with order = TWENTYFIRST, and 6 Scalar with order = FIRST;
 eq.init()  takes  30.8403   seconds, 72% of total running time.

**Comment by permcody** [comment]
This ticket has been resolved for a long time at the libMesh level. The fix was to store Scalar DOFs on only a single processor in a parallel run instead of all ranks.
