### ISSUE TITLE
Create a public repository for storing documentation images

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4552]
Adding/moving/changing images on the wiki is horrible. If we add a public repo that had the images we could utilize traditional markdown format for inserting images, so when the image is change or page is moved there is nothing to do.

**Comment by aeslaughter** [comment]
I think we should move the workshop from the papers into a separate repo, we can go through export control to get everything approved and make it public.

**Comment by permcody** [comment]
That's fine with me, but at the same time we won't be the only ones that want to use this documentation capability. The BISON team has already asked about building their manual the same way. Can we support both if we have a public repo?

**Comment by aeslaughter** [comment]
The wiki will always support images like it does not, using a repo is just much easier. BISON needs the internal wiki.
