### ISSUE TITLE
cluster_launcher not setting ncpus properly

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4555]
When trying to use `cluster_launcher` on Falcon I'm getting this:

```
qsub: You cannot specify more mpiprocs than ncpus
You specified: 10:ncpus=0:mpiprocs=20
```

I don't get it.  I've tried specifying `total_mpi_procs` or `mpi_procs`: neither seems to make this work.  I do also have `chunks` set.

I'm just going to edit the PBS file by hand for now...

**Comment by permcody** [comment]
Interesting...  I have several changes to the cluster launcher in a branch on my system to support the new TestHarness PBS model. I'll see if I've fixed this or if it's still an existing issue.

**Comment by permcody** [comment]
Looked at this for two seconds, I don't readily see a place where this can fail:

```
    # Error check
    if params.isValid('mpi_procs') and params.isValid('total_mpi_procs'):
      print "ERROR: 'mpi_procs' and 'total_mpi_procs' are exclusive.  Only specify one!"
      sys.exit(1)

    # Do a few PBS job size calculations
    if params.isValid('mpi_procs'):
      params['mpi_procs_per_chunk'] = params['mpi_procs']
    elif params.isValid('total_mpi_procs'):
      params['mpi_procs_per_chunk'] = str(int(params['total_mpi_procs']) / int(params['chunks']))  # Need some more error checking here
    else:
      print "ERROR: You must specify either 'mpi_procs' or 'total_mpi_procs'"
      sys.exit(1)
    if params.isValid('threads'):
      threads = int(params['threads'])
    else:
      threads = 1
    params['ncpus_per_chunk'] = str(int(params['mpi_procs_per_chunk']) * threads)
```

Again, if you have an old file laying around that replicates this that'll help for whoever takes a crack at it.

**Comment by permcody** [comment]
@milljm is working on several things related to pbs and the cluster launcher. We haven't had any issues with this. I could have him try to reproduce on falcon but it appears to work for us. Jason, can you try a few different combos of parameters to see if you can reproduce this error when you get a chance?
