### ISSUE TITLE
thermal contact gap conductance xyz, rz, and r spherical options based on coordinate system type

### ISSUE THREAD

**Issue by novasr** [idaholab/moose#4562]
Modified GapConductance.C/.h such that the conductance corresponding to the coordinate system (defined in the Problem block) is returned.

In a prior commit, I updated GapConductance to return the RZ conductance if the parameter 'cylindrical_gap = true' was included in the ThermalContact block. I placed the regression test in modules/heat_conduction/tests/heat_conduction/2d_quadrature_gap_heat_transfer/. Upon further inspection, I found that there are similar tests in modules/combined/tests/gap_heat_transfer_htonly/. For this commit, I'm removing the test in 2d_quadratrue_gap_heat_transfer/ and I'm modifying the tests in gap_heat_transfer_htonly/.

It seems like if a test is in the combined directory, those tests should use more that one set of physics. However, the tests in gap_heat_transfer_htonly/ only use one physics (heat equation). Maybe we should reconsider the location of some tests.

**Comment by permcody** [comment]
If you find tests that really only use one module feel free to move them. Just make sure you run the tests to make sure that they really don't have some extra class in there that you didn't expect.
