### ISSUE TITLE
Element variable is currently not able to be restarted with a distributed mesh

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4571]
I am sure the restart will not work with nemesis neither. @permcody This is not what we have expected.

test/tests/restart/restart/elem_part2.i is a test for serial mesh. The file mentioned inside that only SerialMesh is supported added by @jwpeterson .

We need this capability because our mesh could be huge, with millions of elements. We need distributed mesh and element variable restart both.

**Comment by YaqiWang** [comment]
Is this working with Roy ' recent work?

**Comment by permcody** [comment]
We are testing distributed-mesh with recover in the test suite so I'm going to say yes in general. If there's a specific test that doesn't work we can take a look.

**Comment by YaqiWang** [comment]
I will double check. Will let you know if it is working or not.

**Comment by YaqiWang** [comment]
This is working fine now.
