### ISSUE TITLE
Improving file naming in Exodus-Output if `sequence=true`

### ISSUE THREAD

**Issue by dasmy** [idaholab/moose#4572]
This is some kind of feature request/possible improvement for usability.

When setting an `[Exodus]` block's parameter `sequence=true`, it creates a series of files `filebase.e-sXXX` that sequentially numbered for each output step.
This is especially convenient for performing step-wise (or selective) postprocessing with some third party tools.
However, opening the full time-series in ParaView is complicated since its FileSeries reader expects the numbering to be part of the files base name instead of its extension.
(I think the same applies to VisIt, but I don't have an installation to test it now.)

Thus:
  * Every file of the series is shown separately in the File-Open dialog.
  * If all files are selected and opened at once, they are not loaded as a time series but as individual objects that are shown at the same time.
  * Formally, the file suffix is modified, which might prevent programs to identify the correct filetype.

These issues make using MOOSE's sequential output with ParaView a bit inconvenient.
 
This can be resolved by using a file naming scheme that looks like `filebase-sXXX.e`.
An appropriate patch is trivial (see below) and might also apply to the Nemesis output.
However, it might break compatibility with some user's scripts.
This is why I propose a discussion about if and how this behaviour should be changed.

Maybe it is appropriate to introduce a parameter that allows switching between both naming schemes and defaults to the current behaviour?

Patch for changing the naming scheme (Without parameter and I did not run the testsuite, yet):

    diff --git a/framework/src/outputs/Exodus.C b/framework/src/outputs/Exodus.C
    index 0986364..a2fdd42 100644
    --- a/framework/src/outputs/Exodus.C
    +++ b/framework/src/outputs/Exodus.C
    @@ -275,9 +275,8 @@ Exodus::output(const ExecFlagType & type)
     std::string
     Exodus::filename()
     {
    -  // Append the .e extension on the base file name
       std::ostringstream output;
    -  output << _file_base + ".e";
    +  output << _file_base;
     
       // Add the -s00x extension to the file's base name
       if (_file_num > 1)
    @@ -288,6 +287,9 @@ Exodus::filename()
                << std::right
                << _file_num;
     
    +  // Append the .e extension on the file name
    +  output << ".e";
    +
       // Return the filename
       return output.str();
     }
     
If we agree on some approach, I can prepare a pull request for it.

**Comment by friedmud** [comment]
Our current numbering is the "official" way to provide a time series to Paraview for Exodus files... we didn't make it up :-)

When opening them you should just select the first file and it will automatically open all of them.  I'll double check that this is working properly when I get into the office this morning...

**Comment by dasmy** [comment]
Ooops - I did not know that this is the "official" naming scheme. :blush:
Sorry for the mess.

I just tried and ParaView does indeed open the file sequence when opening the first file.
Presumably, the original problem I had wis this was related to #4573. I will remove that patch again from my MOOSE installation and see if it still works for Steady problems and `output_on=nonlinear`.

**Comment by friedmud** [comment]
Ok - cool.  No problem at all.  It was definitely possible that Paraview changed or something else changed so that this didn't work anymore...

Let us know if we can close this...

**Comment by dasmy** [comment]
Yes, you can (close it) :smile:
Thank you.

The fact that this did not work for my original setup was indeed due to #4573:
If I remove the patch given in #4573 from my MOOSE tree and use a steady-state executioner, ParaView still opens the full sequence of files as can be seen in its "Information"-Tab.
However, it cannot play an animation since it assumes that all files belong to the same timestep... :unamused:
