### ISSUE TITLE
Need to make LineMaterialSamplers restrictable by block

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#4595]
I need to be able to specify "block = " in the classes that derive from LineMaterialSamplerBase to sample the material properties only in the elements in the specified blocks.

**Comment by permcody** [comment]
Are you working this ticket? If so, try to use the BlockRestrictable class if possible.

**Comment by bwspenc** [comment]
Yes, I am working on this (I guess that's obvious), and I did use BlockRestrictable. I'd appreciate feedback on whether I'm using it the right way.
