### ISSUE TITLE
Build control logic into MOOSE

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4604]
- [x] Improve handling of InputParameters, we do all sorts of copying

...

- [x] Profit

**Comment by aeslaughter** [comment]
Basic design: have a complete C++ path for using control logic then create a module that does the python stuff using the C++ object interface. i.e., You should be able to create custom control logic objects, fill out some virtual function(s), just like anything else in MOOSE.

Then, an object will be setup to tap into the python function that Raven desires.

**Comment by aeslaughter** [comment]
There have been some talk with @permcody and @jwpeterson of changing the basic class inheritance structure to:
```
MyObject(InputParameters & parameters);
```

We know this is a crazy idea and changes all code, everywhere. But, we should discuss here...

**Comment by aeslaughter** [comment]
There was also discussion of creating an InputParameterWarehouse, thus the objects would only contain references to the associated InputParameter warehouse. This would allow the control logic to easily swap out parameters without needing to gain access to each of the object pointers. This seems to be the correct way to go, at least with respect to the control logic implementation.

**Comment by friedmud** [comment]
I like _all_ of these ideas: but maybe the stuff about changing the constructors and the warehouse should each be separate tickets?

**Comment by friedmud** [comment]
BTW: I am for removing the `name` parameter.  There's no reason to pack so much stuff into InputParameters... and _not_ the name.  It's kinda weird the way it is now... and I don't know why we've left it this way for so long.

Talk about a CRAZY update to everyone that's forked Stork though!

Derek

**Comment by permcody** [comment]
I'm calling in sick the day Andrew merges this...

**Comment by aeslaughter** [comment]
I already created 79 pull requests a few days ago, no big deal. We should also be able to have a deprecated constructor for top-level objects Kernel,...

**Comment by friedmud** [comment]
Wait - you're right!  I didn't think about the fact that we could have a
deprecated constructor!  All it needs to do is stuff the name into the
InputParams (if it's not already there)...

Why don't we implement this immediately?

**Comment by permcody** [comment]
Well that part maybe, but the reference thing is a bit trickier... We should be able to deprecate that one as well but somebody has to hold onto the InputParameter references. We are talking about building a warehouse for them so that the control logic system can easily grab them by name, system, or whatever else it might need.

**Comment by aeslaughter** [comment]
I am starting with the warehouse, see #4606

**Comment by aeslaughter** [comment]
The basis system has been implemented, further improvements will be in new issues.
