### ISSUE TITLE
Create InputParameterWarehouse

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4606]
see #4604 for the reason.

**Comment by friedmud** [comment]
The big change here is that the InputParameters are going to have to be a `const` reference.

Further, in order for the control logic stuff to work people are going to have to pull const references out of `params`.  OMG the patch...

**Comment by permcody** [comment]
That's the key, we can get away with copies of local params in some of the applications that don't want or need to work with the ControlLogic portion so it won't be incompatible. Eventually though we'll want all the core applications compliant.

**Comment by friedmud** [comment]
We should change our examples and guidelines to storing parameter values as const references...

**Comment by aeslaughter** [comment]
While we are changing syntax, should we move all objects to use 'registerObject' in Moose.C and eliminate the aliases. I vote for a single function, as it is now the aliases are not even consistent, so I think make it more confusing (i.e., registerAux for AuxKernels)

**Comment by friedmud** [comment]
When I've brought this up in the past @permcody always shot me down by saying that having the different names helps keep Application.C files organized... and after seeing the abomination that is most people's applications... I gotta agree.  With the different function names it naturally leads to grouping the registration of similar objects in the same place: which is really good for readability.

That's a REALLY poor technical argument though...

**Comment by permcody** [comment]
I still like the old syntax for the grouping reason. Furthermore, I don't think that you should introduce unnecessary changes for your already gigantic change you are making.

**Comment by aeslaughter** [comment]
I guess we leave it then.

**Comment by aeslaughter** [comment]
I will add 'regsiterAuxKernel' so at least the naming is consistent.

**Comment by friedmud** [comment]
Hah - I agree with that... I screw that one up fairly often myself.  Let's change the documentation too... and slowly phase-out the old syntax :-)

**Comment by friedmud** [comment]
What's the situation with threads here?  Are we still going to get an `InputParameters` copy per thread... or are all threads going to be referencing one `InputParameters` object?

If it's the latter then we might have problems doing things like what's mentioned in #4649

**Comment by permcody** [comment]
It's a good question. Right now we have no intention of letting objects
modify the parameters with the exception of the control system. If that's
the case we probably won't need thread copies in most places. Still we need
to hammer this out before Andrew gets any further down the design path.

**Comment by aeslaughter** [comment]
My current design has a single warehouse with all threaded object referencing the single copy. As @permcody mentioned we don't plan on modifying the parameters after construction.

However, we probably are going to need copies for threaded objects. For example, `NonlinearSystem::addKernel` calls `Factory::create` on each thread. `Factory::create` is what populates the `InputParametersWarehouse`, so there is a race condition to see who adds it to the warehouse first.

**Comment by permcody** [comment]
You just need to put in logic so that only thread zero creates InputParameters. The other issue you need to think about is how to handle control logic execution. If you plan to use `ThreadedElementLoop` and `ThreadedNodalLoop` You'll have to do something when you set new values in the InputParameters.

**Comment by friedmud** [comment]
There is no race condition.  `addKernel` is not called from within any threaded regions...

**Comment by aeslaughter** [comment]
Oh, your right. I saw the loop over tid and assumed it was threading, but this is just making the objects for each thread. So, that being said the InputParameterWarehouse just needs to populate on tid=0, like Cody said.

**Comment by aeslaughter** [comment]
After talking with @friedmud and thinking about it a bit, I believe we might need "tid" copies of the parameters. Because we store thread specific data in the parameters: "tid", "_material_data", and probably more.

**Comment by permcody** [comment]
True, but none of those are technically InputParameters and if we are really concerned about memory usage in InputParameters (which is still an open debate) we might want to continue brainstorming for more solutions. We generally only use those special thread specific parameters when constructing the threaded loops. Can we pass them in another way? I can be convinced to go either way, just thinking...

**Comment by aeslaughter** [comment]
I was thinking that MooseObject might be able to know its tid somehow, maybe by how it is created. It could have a `tid()` method. Then, I believe the objects that need it (Kernels, BCs) could go find MaterialData via FEProblem on construction.

**Comment by aeslaughter** [comment]
This leads to another thing that @friedmud and I discussed, creation of objects in a threaded loop. They would then be able to get the tid.

**Comment by friedmud** [comment]
Let's not change this for now. I'm not at all worried about tid copies of
input parameters (most people don't use threads anyway)... and it helps
with threaded data locality (something I was telling Andrew about yesterday)

**Comment by aeslaughter** [comment]
We need to figure out how to roll out the changes to the MooseObject constructors. 

Here is what I was thinking, but there is probably some reason this will not work.
1. Create deprecated constructors with name and InputParameters
1. Have a new set of set of macros for building objects in the Factory that use the new syntax.
1. Go through the apps and move things to the new constructor.
