### ISSUE TITLE
A strange error calling MooseMesh::getSubdomainID()

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4615]
I have a mesh containing mortar faces, which are named blocks with d-1 dimension. I can use their names in Mesh::MortarInterfaces. But when I try to use the same names in Variables. I got an error saying that those blocks does not exist in mesh. The erroring getSubdomainID() is called later than the one in addMortarInterface()!!

**Comment by YaqiWang** [comment]
I guess I found the reason: `MooseMesh::addMortarInterface()` will rename the mortar block. This drove me crazy. I think the line `setSubdomainName(iface->_id, name);` should be removed.

**Comment by andrsd** [comment]
Most likely, you are using the system wrong. Can you share an input file?

**Comment by YaqiWang** [comment]
The input is checked in one of my branches:
git@github.com:YaqiWang/moose.git mortar_test_4615

**Comment by YaqiWang** [comment]
See my ci 5c382ed.

**Comment by andrsd** [comment]
With the current implementation, the block that will be used for mortar interface should not have a name, just a number. Then the block will be named the same as your input file sub-block. This will be useful when the mortar interface will be generated for you (which we need to implement). The `subdomain` parameter will then go away. People will be referring to this block by its "mortar" name.

If you have a name in your mesh fie, then name the mortar interface the same and that call you want to remove will not harm things. The only relevant fix I see here is to check that the new mortar name does not exists and if so, throw an error. Removing that call is not right, since it would be added beck in when we implement the creation of the mortar interface.

Makes sense?

**Comment by YaqiWang** [comment]
Make sense. I see the point. It is nice to have the mortar interface created on the fly.

This is still a little confusing though. The user created the mesh and expect to use the blocks in the mesh. But then the blocks could be renamed. Can we issue a warning saying this had happened?

**Comment by andrsd** [comment]
If we were able to detect that the block already has a name, then we would not call `setSubdomainName` on it. That would be fine.

**Comment by YaqiWang** [comment]
Another strange thing...

If we change
```
[Variables]
  [./u1]
    order = FIRST
    family = LAGRANGE
    block = '1'
  [../]
  [./u2]
    order = FIRST
    family = LAGRANGE
    block = '2'
  [../]

  [./lm]
    order = FIRST
    family = LAGRANGE

####Note: this is the problematic line
#    block = interface_diff0_diff1
    block = middle
  [../]
[]
```

to

```
[Variables]
  [./lm]
    order = FIRST
    family = LAGRANGE

####Note: this is the problematic line
#    block = interface_diff0_diff1
    block = middle
  [../]

  [./u1]
    order = FIRST
    family = LAGRANGE
    block = '1'
  [../]
  [./u2]
    order = FIRST
    family = LAGRANGE
    block = '2'
  [../]
[]
```

The solve will diverge!!!

**Comment by permcody** [comment]
Have you tried "--show-input" to make sure the input file looks sane when
it gets read in? What about just using a number for the block to eliminate
that as an issue? If both of those turn out ok, then yes, that does indeed
appear to be a bug.

**Comment by YaqiWang** [comment]
Actually the same strange thing happens with conforming.i, one of MOOSE test under tests/mortar/2d. If you switch the order of mortar variable and normal variable, the solution diverges.

**Comment by permcody** [comment]
OK, so that's the key here, you see this behavior when using the Mortar
system.

**Comment by YaqiWang** [comment]
I think it is related with mortar implementation. But I can not think why this is happening...

**Comment by andrsd** [comment]
Moving the `lm` variable would result in a matrix like:
```
+---+---+
| 0 | M |
+---+---|
| D | K |
+---+---+
```
while the original one would be:
```
+---+---+
| K | D |
+---+---|
| M | 0 |
+---+---+
```
and that is the form you find in books. So, I am wondering if there is something more behind the mortar solve...

**Comment by andrsd** [comment]
Also, we are using `SMP` here, while better choice would be a split, because we can precondition `K` better then the whole matrix. However, that work has not been done yet.

**Comment by YaqiWang** [comment]
I saw this kind of matrix before with hybrid FEM. But hybrid FEM introduce mortar faces on all internal sides. Then we can paint all elements with minimum number of colors and iterate on these colors with quantities defined on internal sides (combination of mortar variable and the trace of normal variables). This iteration is called red-black iteration in my field. This does not help here because our mortar face is small subset of all internal faces of the mesh. Iterating on mortar face values will probably not efficient. Plus it will be pain to implement red-black iteration.

Because I am using action to add variables anyway and I know what variables I am adding, I can add mortar variables after all normal variables are added. 

I am thinking we possibly can split M, D into two parts corresponding to master and slave. Assuming master has exact number of dofs of the mortar variable, the matrix corresponding to master can possibly be inverted. The inversion can be done with some sort of lumping. Then we can merge M, D into K (Jacobian) and create a modified one, which hopefully all traditional preconditioning techniques can still work fine. If we decided to do this, this would be done by us because we can figure out the master-slave split and do lumping easily with the mesh.

**Comment by permcody** [comment]
Depending on order can eventually get in you in trouble. A more robust solution would be to add a new task in Moose.C for adding mortar variables at the right time.

**Comment by YaqiWang** [comment]
I push in a simple solution. I am sure you will not like it, but it works. ;-)

**Comment by YaqiWang** [comment]
FaceFaceConstraint is not prepared for using block-diagonal preconditioning because M, D is evaluated in computeJacobian(). This will cause the test fail in debug mode. I do not know if we need split computeJacobian(). We need to have something like onMortarElement() in our threaded loops for the residual and jacobian evaluation. I will close this issue if everybody agrees. We can discuss mortar off-line. Thanks.

**Comment by andrsd** [comment]
It's fine with me

**Comment by YaqiWang** [comment]
I will open new issues for fixing anything.
