### ISSUE TITLE
add MooseVariableMap

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4624]
I need a map object that allows quick value lookup for a given Moose Variable number. Naive as I am I previously thought I could just make an ```std::vector``` (as Moose Variable numbers are unsigned ints), but I hadn't thought about AuxVariables, which get assigned numbers of MAX_UINT-n.

Using an ```std::map``` has been a solution, but the performance overhead is prohibitive, as this lookup is performed for every ```computeQpOffDiagJacobian``` call. The map lookup takes way more time than the rest of the Jacobian evaluation (profiled).

To fix this I went back to a direct ```std::vector``` lookup, but I map NL vars to even numbers (starting at 0) and AuxVars to odd numbers (starting at 1). This way The lookup table is at most 50% empty and the lookup times are reduced by an order of magnitude.

I'd like to make this "map" type available as an Interface that can be inherited from. This map would then also be used in the existing ```JvarMapInterface``` instead of ```std::map``` (or the LIBMESH_FASTED_...MAP)

**Comment by permcody** [comment]
What about an unordered map? If it's a general purpose map does it need to be thread safe? Just posing a few questions before we start creating our own containers. I'd prefer to start with a built in one first and move to our own if performance issues can be demonstrated.

**Comment by dschwen** [comment]
```std::unordered_map``` map is _significantly_ slower (about a factor of two) than ```std::map``` in this scenario. This map would only be populated at construction time, and yes, I'll have to make sure it is thread safe (but I think it naturally is, as the underlying container is just a ```std::vector```).

This container is optimized for read performance.

**Comment by jwpeterson** [comment]
On Fri, Jan 30, 2015 at 9:10 AM, Daniel Schwen <notifications@github.com>
wrote:

> std::unordered_map map is *significantly* slower (about a factor of two)
> than std::map in this scenario.
>
How is that possible?  Hash collisions?

-- 
John

**Comment by permcody** [comment]
We have a HashMap.h/.C file in utils. You might want to see what we've done with that as a model for the new map.

**Comment by dschwen** [comment]
@jwpeterson at low n the cost is dominated by the prefactor. I guess the hashing function costs more than descending two branches in a tree.

**Comment by jwpeterson** [comment]
On Fri, Jan 30, 2015 at 9:50 AM, Daniel Schwen <notifications@github.com>
wrote:

> @jwpeterson <https://github.com/jwpeterson> at low n the cost is
> dominated by the prefactor. I guess the hashing function costs more than
> descending two branches in a tree.
>

You should run with more variables to prevent this "low n" problem....

-- 
John

**Comment by dschwen** [comment]
@permcody , yeah, I saw ```HashMap``` and was wondering why it is not used in MooseRand, FEProblem, and RandomData (those use LIBMESH_BEST_UNORDERED_MAP directly).

**Comment by permcody** [comment]
Two possible reasons (but should be revisited):
1) HashMap is newer than many of those other locations
2) I believe all of those other locations do not require thread-safe
containers

**Comment by jwpeterson** [comment]
> @jwpeterson at low n the cost is dominated by the prefactor. I guess the hashing function costs more than descending two branches in a tree.

I tentatively call bullshit on this.  Here are my results for N=2,
```
trials  map        unordered_map
1e7     0.020468   0.008823
1e8     0.206009   0.087002
1e9     2.03364    0.87374
```

N=4
```
trials  map        unordered_map
1e7     0.023999   0.008939
1e8     0.253776   0.087305
1e9     2.58945    0.874538
```

and N=8:
```
trials     map        unordered_map
1e7      0.029995   0.008864
1e8      0.278569   0.089192
1e9      2.7546       0.869616
```

`unordered_map` is faster in all cases.


Here's the code:
```
// Where does the performance flip over for lookups in std::map vs. std::unordered_map?
#include <iostream>
#include <unordered_map> // Requires a C++11 compiler.
#include <map>
#include <sys/time.h> // gettimeofday

double elapsed(const timeval& tstart, const timeval& tstop)
{
return
  static_cast<double>(tstop.tv_sec  - tstart.tv_sec) +
  static_cast<double>(tstop.tv_usec - tstart.tv_usec)*1.e-6;
}

int main()
{
  // Timing objects
  timeval tstart, tstop;

  const unsigned N = 8;

  // The test objects
  std::map<unsigned, unsigned> m;
  std::unordered_map<unsigned, unsigned> um;

  for (unsigned i=0; i<N; ++i)
    {
      m.insert(std::make_pair(i,i));
      um.insert(std::make_pair(i,i));
    }

  // When N is small, you have to do a lot of trials to get a measurable timing
  const unsigned n_trials = static_cast<unsigned>(1e9);

  // .)
  gettimeofday (&tstart, NULL);
  for (unsigned trial=0; trial<n_trials; ++trial)
    m.find(N/2);
  gettimeofday (&tstop, NULL);
  std::cout << "map::find() with a single key known to be in the map: " << elapsed(tstart, tstop) << std::endl;

  // .)
  gettimeofday (&tstart, NULL);
  for (unsigned trial=0; trial<n_trials; ++trial)
    um.find(N/2);
  gettimeofday (&tstop, NULL);
  std::cout << "unordered_map::find() with a single key known to be in the map: " << elapsed(tstart, tstop) << std::endl;


  return 0;
}
```

And here's the Makefile:
```
# Known to work with GCC 4.7.2, 4.8.3
# Known not to work with clang version 3.3
all:
	g++ -O3 -std=c++11 map_vs_hash.C -o map_vs_hash
```

**Comment by jwpeterson** [comment]
I added a dummy assignment to trick the clang compiler into not optimizing away the `find()` calls and updated my test code in the previous comment.  I'm in agreement with @dschwen that the `unordered_map` implementation on clang sucks balls and should probably never be used for any reason.

Timing results for tests 1, 2 using GCC 4.7.2
```
N=2
trials  map        unordered_map
1e7     0.021486   0.009544
1e8     0.204574   0.087322
1e9     2.06997    0.882264

N=4
trials  map        unordered_map
1e7     0.025415   0.008919
1e8     0.247556   0.087307
1e9     2.53414    0.888939

N=8
trials  map        unordered_map
1e7     0.0316     0.008918
1e8     0.323231   0.087703
1e9     3.19828    0.877453
```

Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
```
N=2
trials  map        unordered_map
1e7     0.020183   0.020938
1e8     0.200522   0.203564
1e9     2.07317    2.03433

N=4
trials  map        unordered_map
1e7     0.018783   0.183929
1e8     0.194118   1.81535
1e9     1.87946    18.2131

N=8
trials  map        unordered_map
1e7     0.035385   0.18762
1e8     0.343814   1.8182
1e9     3.10882    18.229
```

**Comment by dschwen** [comment]
So... you're uncalling bullshit?

**Comment by permcody** [comment]
Try inserting 100 and 1000 values into the map.  I want to see the whole picture.

**Comment by jwpeterson** [comment]
> So... you're uncalling bullshit?

"A tentatively called bullshit does not need to be uncalled."  See Section 4, paragraph 9, sentence 3 of the bullshit caller's code.

**Comment by jwpeterson** [comment]
> Try inserting 100 and 1000 values into the map. I want to see the whole picture.

Here's the results for containers with up to N=128 entries.  These numbers are all for 1e9 calls to find(), since running fewer trials didn't really provide any additional information.  The asymptotic performance for `unordered_map` seems to be about right (constant) for both compilers, it's just that clang is roughly 20x slower than GCC.  

There's also something weird going on with clang's `std::map` implementation when going from N=64 to 128 entries... this does appear to be real, I reran the tests several times to confirm it.

GCC 4.7.2
```
N     map        unordered_map
2     2.06997    0.882264
4     2.53414    0.888939
8     3.19828    0.877453
16    3.83513    0.876052
32    3.82357    0.877334
64    4.38807    0.877624
128   4.94558    0.880401
```

Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
```
N     map        unordered_map
2     2.07317    2.03433
4     1.87946    18.2131
8     3.10882    18.229
16    3.80371    18.4432
32    3.80869    18.4188
64    4.44196    18.3647
128   8.17782    18.388
```

**Comment by jwpeterson** [comment]
Here's a summary of the results.  The brain damage seems to be restricted to the clang compiler on OSX... GCC works everywhere and Clang on Linux works fine in all the cases I checked. 

               | Linux       | OSX
------------ | ------------ | -------------
**Clang 3.3.1** | :white_check_mark: | ?  
**Clang 3.5.0** | ? | :x:  
**Clang 3.5.1** | :white_check_mark:  | ?  
**Apple Clang** | n/a | :x:
**GCC 4.6.3** | :white_check_mark: | ?
**GCC 4.7.2** | ? | :white_check_mark: 
**GCC 4.9.1** | ? | :white_check_mark: 

:white_check_mark: = good `unordered_map` behavior
:x: = bad `unordered_map` behavior

**Comment by permcody** [comment]
This weakens the case for adding a new container to MOOSE then. I'm not sure I want to add something just to get around a platform specific bug that might even go away. Any performance run will be on a cluster, right?

**Comment by jwpeterson** [comment]
Yeah, it just sucks that clang+OSX is a really important use case for us... I am curious to see if there is any improvement in 3.5.1, I'll update the comment when Jason gets that compiler built.

**Comment by jwpeterson** [comment]
> I am curious to see if there is any improvement in 3.5.1, I'll update the comment when Jason gets that compiler built.

Nope, still broken in clang 3.5.1

**Comment by dschwen** [comment]
@permcody , the ```std::map``` vs. ```std::unordered_map``` is really tangential! The proposed container has a much better performance than ```std::map``` for this application.

**Comment by dschwen** [comment]
With g++:

proposed container 0.272s
baseline 0.272s
std::map 0.649s
std::unordered_map 1.733s

The base line is performing a function call with a return value (that is summed up to avoid deadcode elimination).
