### ISSUE TITLE
Slide System Enhancements

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4632]
Need a few small enhancements to the slide system

- [x] Ability to "white list" slides instead of "black listing" them
- [x] Ability to automatically "pull in" linked wiki pages
- [x] Images need to size themselves correctly and/or be size in the wiki content itself. This is important if we start pulling in wiki content from other pages.

**Comment by aeslaughter** [comment]
The SlideSet object includes "active" and "inactive" and they can work together. "active" creates a list of active slides, if empty, all slides are included. Then "inactive" slides are removed. See SlideSet::activeSlides
