### ISSUE TITLE
Remove accidental inserts into a map with bracket operators

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4640]
I think I've hit one too many of these @friedmud! We need to go through MOOSE and either get rid of all statements that access an item from a map assuming it exists when it might not or assert that the accessed item is sane.

I'm currently working out an issue that's seg faulting in prolong|restrictStatefulProps due to one of these accidental insertions.

**Comment by friedmud** [comment]
Why call me out?! You're the one that loves autovivication!!  :smile:

**Comment by permcody** [comment]
I don't know what that is, but it is true that I do think autovivification is the bomb!

**Comment by permcody** [comment]
I'll close this ticket. I haven't seen any of these for awhile so hopefully most of these have been removed.
