### ISSUE TITLE
Dynamic Multiapp support

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4643]
It would be handy to use dynamic linking work with MultiApps. To do this we'll need to have a function that can register an application when dl_open is called so that we can just run it without explicitly compiling it in.

# Design
- When an unknown application name is encountered in the `app_type` variable the system will attempt to locate a module dynamically to find the application.
- Locating the dynamic libraries will be done with a variable named MOOSE_LIB_PATH. Users will set this variable with colon delimited paths where application libs can be found.
- Additionally we will support a new parameter in the Multiapp section in the input file where an input file specific path can be set.
```
append_moose_dir_path = <some_path>
```
- Dependent libraries will automatically be loaded by searching the library's "*.la" file for dependency_libs.

**Comment by friedmud** [comment]
Yes. This and then later: dynamic plugins for Kernels, BCs, etc.

That way they can ship a precompiled version of BISON... but users can
still input their own material models...

**Comment by permcody** [comment]
Note: #4660 has a minor issue that needs to be fixed. If you compile the phase_field module by itself the *.la file does not get populated with the dependency on tensor_mechanics. This is due to the fact that modules.mk populates DEPEND_MODULES but the phase_field individual makefile does not. This is here to remind me to fix that before this ticket is complete.

**Comment by permcody** [comment]
@idaholab/moose-developers - I am continuing work on this PR, if you have comments on the current design, please make them known.

**Comment by hornekyle** [comment]
This sounds like a great idea.

**Comment by friedmud** [comment]
This is more than a good idea... it's awesome... and @permcody 's implementation is freaking sweet.

We are going to use the hell out of this....

**Comment by permcody** [comment]
Andrew Dykhius reported an issue with finding the library for hognose-dev. Investigate issues with dashes in the name.

**Comment by permcody** [comment]
As reported by Andrew the issue had nothing to do with the name :smile: 
Instead the problem was that he didn't have the patch to add the extern'ed C method wrapping the static method. @friedmud inquired about just demangling the name instead. I thought of that approach but didn't think it would be very robust at the time since it involved not only the name of the application but also required demangling to work reliably. Since I've already started down the path of using unique names for the method, demangling may not be out of reach.

**Comment by permcody** [comment]
@friedmud - turns out that there is no "mangle" function in the cxx_abi library that libMesh loads for demangling. A little searching on the web turned up no useful information. I ran into this which seemed to support my findings: http://comments.gmane.org/gmane.comp.lang.c%2B%2B.abi/249

Without a "mangle" function, I don't have a good way of asking the loaded library for the proper name to lookup. We'd have to loop over all symbols in the entire library demangling each of them and test against my unmangled static name to see if there was a match. While this might work, it's probably not any better than creating several extern'd functions for every application that are just always there.

**Comment by roystgnr** [comment]
AFAIK the only sure way to get a C++-mangled name is to ask the C++ compiler for it: http://stackoverflow.com/questions/12400105/getting-mangled-name-from-demangled-name
(although, on linux the C++ ABI is standardized enough that you shouldn't have to ask the *same* compiler, just *some* compiler)

This doesn't work so well if you don't know the demangled name until run time and you're not certain you'll have access to the compiler at that point.

**Comment by permcody** [comment]
Thanks for the information.

Well I don't think I'm ready to run the compiler inside of a MOOSE executable anytime soon especially in a parallel run! We'll stick to extern functions which I don't need any ABI trickery to use.

**Comment by roystgnr** [comment]
Gah - you should not be thanking me for misinformation.

I forgot that the Linux C++ ABI actually *changed* with C++11, because the old GCC ABI employed copy-on-write strings and lists with no explicit size storage, and those are disallowed by the C++11 standard.  https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Not only can mixing ABIs cause link-time failures, but I think it could screw up the name mangling strategy I linked above, if you were to try to ask for the mangled name of a function that has a string or a list among its arguments but you're not asking a compiler using the same ABI settings you built with.  I think "avoid ABI trickery" is looking like a better and better decision.
