### ISSUE TITLE
MultiFunctionAuxKernel

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4650]
new AuxKernel.  This takes arguments: (1)  the SolutionUO; (2) a list of Functions.  If, on any element, the SolutionUO=n, then I use function n to give the result.

a

**Comment by friedmud** [comment]
I don't believe that this belongs in MOOSE.  This is pretty specialized... and really belongs in your own application.

**Comment by WilkAndy** [comment]
OK, thanks @friedmud , i'll shove it into the richards module since that's where it is useful (defining permeability changes).  Or did you mean not to put it into modules?  i don't have my own application.

a

**Comment by friedmud** [comment]
Right - I don't even really think it should go into Richards... but maybe I'll be overruled.

It really is past time for you to have your own Application to put this kind of stuff though ;-)

**Comment by WilkAndy** [comment]
I take your point re my own Application.  In this case, however, i would like it to be part of Richards, if possible.  MOOSE is being used for a big project (http://www.bioregionalassessments.gov.au) in which they require complete open-sourcedness of the software and data.  If I use my own Application it makes things one-step more complicated.

**Comment by andrsd** [comment]
On Mon, Feb 9, 2015 at 6:17 PM, Andy Wilkins <notifications@github.com>
wrote:

> I take your point re my own Application. In this case, however, i would
> like it to be part of Richards, if possible. MOOSE is being used for a big
> project (http://www.bioregionalassessments.gov.au) in which they require
> complete open-sourcedness of the software and data. If I use my own
> Application it makes things one-step more complicated.
>
​You can host your application on github (it will be open sourced). Then
 you bring MOOSE in as a git submodule and maintain the right version of
it. Is the submodule that big of a burden?​ This is what we do for our
internal apps at INL.

**Comment by friedmud** [comment]
Indeed: if you follow these instructions then you end up with an open
sourced application :-)

http://mooseframework.com/create-an-app/

**Comment by WilkAndy** [comment]
OK, i'll give it a try,

a

**Comment by WilkAndy** [comment]
I created a "ba_hun" (stupid name, i know!) stork fork.  Let's see how it goes,

a

**Comment by permcody** [comment]
Great, we'll get recipes setup to Test it. @milljm will you take a crack at this? It'll be more like Pika's recipe but make sure you inspect it for any changes that we might have made to some of the very latest internal recipes.

**Comment by friedmud** [comment]
This is a great move Andy!

One thing this gives you is a place to prototype ideas... and then the stable ideas that you think others are interested in can be moved into MOOSE...

I think you're going to like this arrangement!
