### ISSUE TITLE
Current implementation does not support multiple FaceFaceConstraint

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4656]
`FaceFaceConstraint::ComputeJacobian` combines the evaluation of diagonal and two off-diagonal blocks of Jacobian. This accidentally changes the `_current_elem`, which makes the rest of face-to-face constraints in a wrong state. Also `reinit()` is missing for calling `computingJacobian`, which makes the mapping from mortar element to the master and slave sides of elements wrong.

**Comment by andrsd** [comment]
I am closing this in favor of #4960 which addresses my comments from 10453521f75284aa6ca0b08c2dfcd98cae935538
