### ISSUE TITLE
TensorMechanics:  _elasticity_tensor[_qp] = _Cijkl 

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4657]
```FiniteStrainCrystalPlasticity``` and ```SimpleEigenStrainMaterial``` both set

```
  _elasticity_tensor[_qp] = _Cijkl;
```

the latter ignoring the Euler angles. It seems to me that both classes should rather call ```TensorMechanicsMaterial::computeQpElasticityTensor()``` to obtain a correctly rotated elasticity tensor and avoid code duplication. @cpritam @tonkmr

**Comment by cpritam** [comment]
I agree that using TensorMechanicsMaterial::compute can be used to avoid code duplication. 
In FiniteStrainCrystalPlasticity.C the elasticity tensor however is rotated before being used and the rotation tensor in RotationTensor.C is transpose to the one used in FiniteStrainCrystalPlasticity.C.

**Comment by permcody** [comment]
@amjokisaari might want to chime in on this

**Comment by dschwen** [comment]
these classes are deprecated and will be removed anyways
