### ISSUE TITLE
TestHarness RunException test should automatically set max_parallel to 1

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4668]
Yes - Do it.

**Comment by friedmud** [comment]
Can it be overridden?  What if you're trying to test a parallel exception?

**Comment by permcody** [comment]
Yes, I'll make sure we can override. My intention is to get rid of all the spurious failures we see with "expect_err" types of tests. Even "expect_out" is OK. We just can't cross the error streams.

**Comment by permcody** [comment]
So @milljm looked into this and we ARE setting max_parallel = 1 already. The problem now is that we have several expect_out tests that use the RunApp tester but those aren't being set to max_parallel = 1. Since our mooseWarning() macro writes to stderr those tests can and often do fail when run in parallel as well.

There are a few possible fixes but I'm not sure which one I like the best:
 - Restrict RunApp tests that use expect_out to max_parallel = 1 automatically (can be overridden)
 - Output mooseWarning to stdout

**Comment by permcody** [comment]
@milljm, @brianmoose 

Let's get back to this ticket and get it closed. This issue was opened in February of last year and it's still plaguing us from time to time. The underlying problem is that error messages written to the terminal from MOOSE are interleaved when running in parallel. As you can see from the conversation above, we already tried to fix this but have failed for a variety of reasons.

With the latest libMesh update we now have the ability to suppress the stderr stream from all non-zero ranks (--drop-cerr). The normal operation of MOOSE is to drop stdout from all non-zero ranks but keep stderr from all non-zero ranks. This is nice because if you only throw an error message on one rank, it's going to come to the screen. The problem is that we often throw errors on all ranks, especially when we test. 

I'm thinking that we should default to suppressing stderr from all non-zero ranks in the TestHarness. However, there's always going to be somebody who doesn't want that so we really need an option "keep-cerr" added to the `Tester.py` class so that users can optionally keep error for when they actually want to test throwing an error on one non-master rank.

Once we do that we should remove the max_parallel restriction from all of our tests that have it because of this problem (i.e. RunException tests). I was thinking this might require a recipe update to CIVET, but now I don't think so. I think it's all TestHarness and Tester stuff.

**Comment by permcody** [comment]
We definitely don't want to do this anymore. It's unecessary due to the way we save output in #8080.
