### ISSUE TITLE
Remove "nose" emulation behavior from TestHarness

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4676]
Right now all "tests", "examples", "assessments" have to be located in a path that contains the word "[Tt]ests". This simply isn't necessary anymore and should be removed.

Tagging @gardnerru and @bwspenc 

The workaround is to create a soft link from the "tests" directory to one of the other directories in your repo. Remove soft links from BISON and BISON-CASL when this ticket is complete.

**Comment by friedmud** [comment]
:+1:
