### ISSUE TITLE
Wiki Enhancements

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4678]
Just a few things I would like to change about our wiki, if possible. Just writing them here so I don't forget.

- [ ] Add the ability to control the size and position of outside images (i.e., from our github/presentations repo)
- [ ] Image settings should be supported inside of the image block for both traditional and django-wiki style images:
```
    ![My caption](image.png align:right width:50 height:72px)
    [image:32 align:right width:50px]
```
- [ ] Add the ability for links to idaholab/moose code to get injected directly into the wiki in a scrollable box in similar fashion to the presentation builder, including the ability to just extract functions.
- [ ] Add smart navigation, so that when navigating inside the tutorials and a link to wiki/MooseSystems/Materials is present that it is easy to return to the tutorial.
- [ ] Code blocks should be able to be indented under bullet items

**Comment by aeslaughter** [comment]
I was looking at cldoc (a clang based Doxygen replacement, https://jessevdk.github.io/cldoc/documenting.html) and found something that may further unify our documentation. As discussed in the "Writing external documentation" section it allows you to link in external markdown documentation, so we can have detailed class descriptions on our wiki (i.e., the Convetion kernel can show the math and such on the wiki) and this doco will auto-magically get pulled into the source code documentation.

Just living the dream where we have a streamlined and complete documentation for MOOSE and modules.

**Comment by friedmud** [comment]
That does sound awesome...

**Comment by aeslaughter** [comment]
Handling this in #6699
