### ISSUE TITLE
MooseParsedFunctionBase parameter vals needs error checking

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4682]
The length of the ```vals``` vector should be identical to the length of the ```vars``` vector in ```MooseParsedFunctionBase```. There is no scenario in which a variable is declared without some value (either numeric constant or postprocessor name), as we can only pass in the values for x,y,z,t at eval time.

The absence of error checking makes the ```vars``` parameter confusing and lets errors slip where users erroneously assume they can couple to non-linear variables.

**Comment by dschwen** [comment]
@aeslaughter what is the purpose of the ```verifyVars``` and ```verifyVals``` methods? Do we need runtime checks for this? The parameters are defined in ```validParams``` if this method isn't called to initialize parameters in classes derived from ```MooseParsedFunctionBase``` that seems like a programming error, which should just throw the default error (no parameter yadayada found).

**Comment by aeslaughter** [comment]
I don't know, it was a long time ago.

**Comment by permcody** [comment]
See #4683
