### ISSUE TITLE
Assembling internal side Jacobian 

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#4693]
Currently contributions of DGKernels to the Jacobian are assembled in computeInternalFaceJacobian 
which calls ```dg->computeOffDiagJacobian(jvar)```. In ```DGKernel::computeOffDiagJacobian```, it is checked
if the current variable is equal to ```jvar```. If so ,then ```computeJacobian()``` is called.

This is dangerous when ```computeOffDiagJacobian``` is overridden by a class inheriting from 
DGKernel because the user has to ensure that in his class ```computeOffDiagJacobian``` calls ```computeJacobian``` if appropriate.

**Comment by andrsd** [comment]
Just out of curiosity, why do you override `computeOffDiagJacobian`? Applications typically override the `-Qp-` method.

**Comment by YaqiWang** [comment]
We need to evaluate something belongs to the side but not qps. It is a kind of like precomputeResidual() in Kernel. We might add one similar in DGKernel. But our use could be too specific so we may not want to modify MOOSE to have an empty call all the time.

**Comment by andrsd** [comment]
```
void
MyDGKernel::computeOffDiagJacobian(unsigned int jvar)
{
  doMyThing();
  DGKernel::computeOffDiagJacobian(jvar)
}
```
does not work?

**Comment by snschune** [comment]
That would work. Our concern is rather that a user overrides ```computeOffDiagJacobian``` and does
not realize that ```DGKernel::computeOffDiagJacobian(jvar)``` needs to be called to ensure that ```computeJacobian```. The current behavior is not quite intuitive and we spent quite some time debugging the issue.

**Comment by andrsd** [comment]
1. If you are overriding something you are not really supposed to, then you have to understand how things work ;-)
2. If we are going to move the decision `jvar == ivar` one level up, then we have to change it in all other systems like kernels, BCs, etc. not just DGKernels...

I do not have a problem with (2), but then the patch should do the other systems as well. What do @permcody and @friedmud think?

**Comment by permcody** [comment]
I'm not sure how I feel about 2 yet. As far as 1 goes, we could generate a warning for the user by clearing a warning flag in the base version of the method. Presumably when somebody who "doesn't understand how things work ;-)" attempted to override that function they wouldn't clear that flag which we could later check and throw and error due to it's uncleared value.

**Comment by jwpeterson** [comment]
Closing this, as the original issue was fixed in Yak, and it was decided in the PR not to update all the relevant MOOSE systems.
