### ISSUE TITLE
MeshModifier idea

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4699]
Would a MeshModifier that changes one blockID to another blockID be of interest and appropriate for inclusion in the framework?

I use VTK to build my meshes and annoyingly it doesn't have sidesets.  So i create a heap of blocks and then use SideSetsFromNormals or SideSetsBetweenBlocks.  But then i have a billion blocks (well, in reality, only thousands) that are otherwise useless.  I want to change them back to their "original" block numbers that they would have had, had I been able to use sidesets.

Comments?

**Comment by friedmud** [comment]
2 things:

1.  Get a new mesh format.  Why struggle with something so simple?  ExodusII is free, open source and has good documentation: http://sourceforge.net/projects/exodusii/

2.  Yeah: a mesh modifier that switches block numbers is fine for inclusion in MOOSE.

**Comment by aeslaughter** [comment]
Andy,

Althought I have never done it, according to this thread for paraview I do
believe it is possible to store side information in VTK format:
http://public.kitware.com/pipermail/paraview/2009-October/014045.html.

-Andrew

**Comment by WilkAndy** [comment]
Thanks @aeslaughter.

Just in case someone reads this thread in the future:   Yes, you could store sideset info in a vtkAbstractDataArray (it might be somewhat clunky, and there is a bug in vtkStringArray/zlib-compression meaning the sideset info can't be too large), but you still can't write out that info to a .e file using vtkExodusIIWriter.   Ignoring the not-too-large bug just mentioned, in principal libmesh could read this info from a .vtk file and create sidesets.  That is beyond my skill to code, and i don't have the time to do it now.

**Comment by friedmud** [comment]
Seriously... Why don't you just write ExodusII files using the Exodus library?  It will literally save you thousands of hours screwing with all of this.

In the time it took you to write the mesh modifier you could have changed your mesh generation code to write Exodus...
