### ISSUE TITLE
Add parsed function ODE kernel

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4708]
A kernel derived from ```ODEKernel``` that supports a parsed function and uses automatic differentiation to compute the jacobian values would be nice to have and easy to implement. I'll take a look at that when I have time.

**Comment by tonkmr** [comment]
@permcody you labeled this as Modules, but it will go into framework, not modules.

**Comment by dschwen** [comment]
This is fulfilled by #4784.
