### ISSUE TITLE
Dynamic object registration support "plugins"

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4712]
We need to be able to extend the available build-able objects in a pre-compiled application to run coupled simulations where a particular object doesn't belong in either application until they are coupled together.

Another use case for this would be to distribute a pre-built binary and header files and dynamically register new objects.

# Design
 - Create a new entry point in the application `void AnimalName__registerObjects(Factory *)`
 - In a Multiapp setting we'll normally pass the parent Factory to the subapp instead of instantiating a separate Factory object. This will have the effect of registering all objects in a single Factory.
 - We'll be able to turn off inheriting the factory through a new parameter in the `Multiapp` block: `inherit_factory`?
 - The same mechanism will be used for the plug-in architecture outside of the Multiapp system.
```
[Problem]
  register_objects = 'OtherAnimal1App OtherAnimal2App'
[]
```

I plan on implementing this tomorrow (2/25) so that @andrsd can make use of it in a large sprint problem. If you have comments or feedback on the design please let me know.

tagging @friedmud

**Comment by friedmud** [comment]
Acknowledging that I have read this and I'm thinking about it. Your basic
plan here sounds like a decent first take. Let's see what it turns out
like...

**Comment by permcody** [comment]
I just pushed the first commit to upstream. It enables the shared factory capability. It not nearly as clean as I had hoped but it's unavoidable. Previously the MooseApp was the root of all objects so the Factory was designed to expect a constructed MooseApp instance. I had to undo that so we could create a Factory first and pass that into an app during construction. 

The other thing that's slightly ugly is the "swapping" that we have to do in the Factory now to build MooseObjects that contain references to the correct MooseApp. You'll see this where we create a MultiApp. It's not terrible in that we set a pointer, setup the MuliApp, the set the pointer back. It should only be needed in this one location.

As it stands, it should be ready for case @andrsd needed (i.e. running a dynamic Rattlesnake sub app that knows how to create objects only available in MammothApp).

Tasks to be completed
 [ ] add the extern "C" registerObjects() and associateSyntax() entry points
 [ ] undo the required dereferencing of the factory pointer in application construction to avoid application breakage if possible
 [ ] figure out how to handle multiple registration errors or avoid multiple registration of objects
 [ ] Support new syntax to register objects from other applications in a non-multiapp setting
 [ ] Support syntax to disable sharing factories

**Comment by permcody** [comment]
Per my phone conversation with @friedmud and @andrsd, I'm going to modify this slightly. The big change is that I'm not planning on a shared factory anymore. Instead, we'll leave the existing factory in MooseApp and allow it to register objects from additional applications. We agreed to use a new `[Application]` or perhaps `[App]` block in the input file for loading additional objects.

**Comment by friedmud** [comment]
`[Application]` feels better to me.  Matches up better with `[Problem]`

**Comment by permcody** [comment]
@friedmud I'd like to discuss this once more with you. In completing this PR I decided that I'm not really crazy about having a [Problem] and [Application] block. It feels like the contents of each are somewhat arbitrary on where they might go. I realize that they map to objects inside of MOOSE but the parameters in these blocks control "global" behavior. I think that from a user perspective we might consider consolidating those two blocks into one. Thoughts?

**Comment by friedmud** [comment]
I like the idea of them being separate - but I do see what you mean as far
as user intuition.

However, the Application block shouldn't be interacted with much: it really
only becomes important once you're doing MultiApp stuff.  I can envision us
adding more capability / options there in the future.

I also kind of envisioned the Application block allowing you to override
any command-line options you could pass on the command-line.  The
command-line options are already set up as validParams() for the
Application object... so it kind of makes sense.

I'm not hugely married to this design though... so we can just chuck more
stuff into Problem for now if you want and we can see how it goes ;-)

**Comment by permcody** [comment]
I'm just suggesting that we consider unifying all global parameters. Does the average user understand that there's an Application and inside of it, there's a Problem and inside of that an ES and so on? Even in our CoupledProblem cases we still only have one Problem per Application. I'm not sure I care as a user or a developer. I just want to mess with global "stuff" like turning off kernel checks or setting command line parameters. I don't want to think about whether that global parameter is associated with the Problem or the Application. Even in a Multiapp case we still have one problem per application.

**Comment by friedmud** [comment]
Well - we were *supposed* to have more than one Problem per run all the
time (with the way David envisioned it... and I was on board).  But then
MultiApps happened and that appears to be somewhat more straightforward to
use... so user visible MultiProblem never really caught on (note: we DO
actually use more than one Problem all the time: DisplacedProblem).

I don't know if we'll revisit that model in the future (every now and again
I think of a good use-case... but I never get to the point of implementing
anything).

But yeah: I see your point.  Users won't generally think about the
hierarchy of Application/Problem.  Currently the [Problem] block is just
where you go when you want to flip global switches ;-)

**Comment by YaqiWang** [comment]
I want to add some of my comments, which will be somewhat out of the scope of this issue.

In general, we could do fully-coupled calculations with MultiApp. We can extend the residual evaluation in a way that transfers happen first so that all apps have the needed projected solutions from other apps, and all apps call its own residual evaluation and form the global residual. Cross-app Jacobian will be almost impossible though but we typically do block-diagonal preconditioning anyway.

I can think of the use case of multiple FEProblem is multimesh, where each FEProblem holds a different mesh. We kind of move multimesh implementation out side of FEProblem with MultiApp. MultiApp appears more flexible than multiple FEProblems. Maybe it is also the way of doing multimesh.

**Comment by friedmud** [comment]
I agree Yaqi... I'm now thinking along those lines myself.
