### ISSUE TITLE
Header update

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4729]
As @tonkmr pointed out yesterday we don't have headers in any of the modules. I think we probably should have headers in all project files. @idaholab/moose-developers comments?

**Comment by YaqiWang** [comment]
Should the header changed a little according to the project name?

**Comment by permcody** [comment]
Depends on what you mean. If we apply the existing copyright header, I'd say no. We could entertain creating a different header that doesn't apply a copyright to the modules. Perhaps something that just says these "modules" are part of the MOOSE project. I'm not exactly sure what the right course of action is here.
