### ISSUE TITLE
Logic bug in FiniteStrainMultiPlasticity::applyKuhnTucker()

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4731]
Clang SA detected a logic bug in applyKuhnTucker(). It's possible that `surface_to_turn_off` will never be set based on your conditional statement. You later use that value to index into a vector. This should be fixed.

**Comment by permcody** [comment]
Also check out MultiPlasticityLinearSystem::eliminateLinearDependence()
Used variable `info` on line 163.  Looks important but isn't used.

**Comment by WilkAndy** [comment]
Thanks @permcody.  I don't see the logic bug, but can probably re-write so the SA doesn't complain.  I'll take appropriate action for "info"

**Comment by permcody** [comment]
It can't remember if it's simply not used at all or if there is a case
where it can be used before being set. The latter case can happen when you
set a value in an if statement. What happens if you don't go into that if
statement?
