### ISSUE TITLE
MultiApp copy transfer

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#4736]
There are many scenarios of interest where the master and sub app both have the same mesh.  We have found that the interpolation transfers can be slow, memory intensive, and error-prone.  If the mesh is really the same, it makes more sense to just copy values between the two meshes.

I took a stab at writing a copy transfer a while back, and I'll submit a pull request shortly.  That implementation only works for the case where the master and sub app have the same parallel decomposition.  I don't have the time right now to sort that out, so as I see it, we could either put in a check to have it error out if the parallel decompositions differ or if someone could help me get the parallel stuff sorted out, I'd welcome the help.  We have multiple use cases for this even with the parallel limitation (master and single sub-app), so I think the code is still useful as-is.

**Comment by friedmud** [comment]
This is related to #1835 close that one when this one is completed.

What still needs to be done here is making this work with different parallel decompositions.  That's a job for @smharper this summer.

**Comment by permcody** [comment]
Done:
https://github.com/idaholab/moose/blob/devel/framework/src/transfers/MultiAppCopyTransfer.C
