### ISSUE TITLE
Postprocessor is outputted multiple times in exodus

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4751]
When a postprocessor is executed on multiple places, for example, linear and timestep_end, I noticed exodus output contains duplicated outputs of the postprocessor. This seems to me not the correct behavior. Also when I have multiple execute_on, even I set `outputs` to console, it still shows up in exodus.

**Comment by aeslaughter** [comment]
@YaqiWang, can you include your Outputs blocks that are producing the behavior.

**Comment by YaqiWang** [comment]
@aeslaughter This can be easily produced by modifying one of moose tests, like, tests/postprocessors/element_integral/element_integral_test.i:
turn exodus on, add execute_on = 'timestep_begin timestep_end' in the postprocessor. Do a ncdump you will see the duplication.

If you then add outputs=console, you will see exodus still contains the postprocessor.

**Comment by aeslaughter** [comment]
In the first part, I expect it to be duplicated: "timestep_begin
timestep_end' is indicating to output the postprocessor twice on the same
time step.

Setting outputs=console, should however disable it from the exodus file, I
will look at that.

**Comment by YaqiWang** [comment]
Then output_on=linear does not make sense to exodus output, because exodus only store solutions at time steps.

**Comment by aeslaughter** [comment]
Yes, but when using 'output_on = linear' the timestep is modified, for
output purposes:
http://mooseframework.org/wiki/MooseSystems/Outputs/#non-linearlinear-residual-output

**Comment by YaqiWang** [comment]
Oh, I see. The only thing left now seems to be that some output_on is not filtered by outputs.
Btw, the same variable name on the same time step multiple times seems a potential issue although it currently allowed by exodus. Maybe we suffix the name with `_begin` or shift the time a little?

**Comment by aeslaughter** [comment]
@YaqiWang Do you need to see the output or the postprocessors at the beginning and end of a timestep?

Also, I know the problem with 'outputs = console', I will hopefully get to that later today.

**Comment by YaqiWang** [comment]
@aeslaughter I do not. You current implementation however allows that ;-)
