### ISSUE TITLE
Add Grain Tracker

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4759]
Move some files around. Vague commit message on purpose, because HEY LOOK OVER THERE! SHINY!

**Comment by permcody** [comment]
Do we have everything we need to make the graintracker tests work in the phase field module?

**Comment by dschwen** [comment]
@permcody I have just now enabled one test. The EBSDReader test uses ReconVarIC, which we have not moved yet, so it stays disabled for now.

**Comment by dschwen** [comment]
This is done.
