### ISSUE TITLE
Icing: defaults for coupledScalarValue

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4762]
I can do the following:

  params.addCoupledVar("p0", 0, "doco");
 _p0(coupledValue("p0"))

But not the following:

  params.addCoupledVar("p0", 0, "doco");
_p0(coupledScalarValue("p0"))

The code for the latter compiles OK, but gives a runtime error (Trying to get a non-existent variable 'p0').

I think this is beyond my moose-skill to do, so would prefer if someone else did it.  I know it's just "icing" (i guess you guys call that "frosting"), but it'd be nice to have.

a

**Comment by andrsd** [comment]
You have to have a scalar variable called 'p0'
And I call it 'poleva' ;-)

**Comment by andrsd** [comment]
Oh, you are requesting default values for scalar var... Well, you can work around the issue using the old way: using `isCoupled` and ternary operator.

**Comment by WilkAndy** [comment]
Yep, i'm doing it with the ternary right now,

a
