### ISSUE TITLE
Time derivative method for functions

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#4769]
I'd like to be able to get time derivatives of MOOSE functions.  Currently, the Piecewise functions have a timeDerivative() method.  @dschwen tells me that we could easily expose an interface to the MooseParsedFunction to do the same thing as well.

It seems like the right thing to do is to add a method to the base class.  The problem is that not every function would implement it.  There's a similar issue for the gradient.  The base class defines a gradient() method, but not every derived class defines it.  Rather than just getting a zero, sometimes you really need to know whether these things have been implemented.

I propose that we add the timeDerivative() method to the Function base class, and also add methods like hasTimeDerivative() and hasGradient() that you could call to see whether they're implemented.  The base class would have a version of timeDerivative() that returns zero, just like the gradient() method.  I'm open to suggestions if anyone has a better plan.

**Comment by dschwen** [comment]
Sounds good to me. I had already implemented ```MooseParsedFunctionWrapper::evaluateDot(Real t, const Point & p)``` a while ago, but it was never used, as the ```timeDerivative``` method in the base class was still missing. So adding ```timeDerivative``` to ```MooseParsedFunction``` would be trivial.

**Comment by YaqiWang** [comment]
The `timeDerivative()` in the base class can invalidate the time derivative so `hasTimeDerivative()` will return false if the method is not overwritten.

**Comment by dschwen** [comment]
@YaqiWang I don't see how that would be possible. I think you'll have to overwrite ```timeDerivative()``` and ```hasTimeDerivative()``` in pairs. It is not much overhead, as ```hasTimeDerivative()``` is trivial enough to be implemented inline.

**Comment by YaqiWang** [comment]
That is something we want to avoid. A developer might forget to overwrite both. Let us have a flag `_has_valide_time_derivative` in the base, and it is set to true during construction. The only place change it to false is in timeDerivative() of the base class. Then when the derived class overwrite timeDerivative(), `_has_valide_time_derivative` will remain true unless the developer defeats it on purpose. Not sure if this is a good idea or not.

**Comment by dschwen** [comment]
The existence of a valid ```timeDerivative``` may have to get checked before the method is ever called. While I see some appeal in your suggestion it just introduces a different error source: not calling ```timeDerivative``` before testing for it.

I'd default ```hasTimeDerivative``` to ```false```. If the developer forgets to overwrite ```hasTimeDerivative``` his new time derivative will simply not work. And classes that rely on it will throw an error. This seems much easier to detect than the broken test that will return true if ```timeDerivative``` has not yet been called.

**Comment by bwspenc** [comment]
@YaqiWang If you set ```_has_valid_time_derivative``` when you call ```timeDerivative()```, this would only work correctly if ```timeDerivative()``` got called before ```hasTimeDerivative()```.  The way I was planning to use this, I would call ```hasTimeDerivative()``` during the initialization or construction phase, and throw an error if the user tried to use a function that doesn't have a time derivative, so that wouldn't work.

**Comment by bwspenc** [comment]
I don't think it's too onerous to require the developer of the function to implement these methods in pairs.  That's something that would be exposed very quickly doing some basic testing.

**Comment by dschwen** [comment]
The propoesed data member to store this information ```_has_valid_time_derivative``` cannot be _const_ and must be writable by all derived classes, even though it _conceptually_ holds a constant (static!) property. This does not seem elegant to me.

**Comment by YaqiWang** [comment]
How about this? `bool getTimeDerivative(Real & td) const`

**Comment by dschwen** [comment]
No. This is a straight forward problem with a straight forward solution. We
conceptually need a way to test a capability of an object. We don't want to
test over and over again each time we get the time derivative.

**Comment by YaqiWang** [comment]
You do not have to test the returned value though. We could have a mooseAssert to be safe.

**Comment by dschwen** [comment]
An interface should be designed to reflect the concepts behind it. Using
non const references to get two return values out of a function that only
needs to return one value is ugly.

**Comment by YaqiWang** [comment]
Maybe we just need to leave a mooseError in the base class and fix all the failing tests because of it.

**Comment by aeslaughter** [comment]
Ben, If you are planning on producing an error when a function without time
derivative is used, then the base class should contain an error in
timeDerivative(). The object should just use it, it will error if it is not
defined.

**Comment by dschwen** [comment]
A non-existing time derivative is not always a fatal error! Some objects may be fine with a return value of 0.0. But I'll leave it to @bwspenc to comment on that.

**Comment by bwspenc** [comment]
@aeslaughter I'm fine with that, but that wouldn't be consistent with the current behavior of the ```gradient()``` method, which returns 0 if one isn't defined.  I don't know why it does it that way -- probably because the gradients are usually used in computing Jacobian entries, and it's not fatal if those terms aren't included.

**Comment by YaqiWang** [comment]
I added mooseError in `Function::gradient()`, three tests are failing:

```
variables/fe_monomial_const.test_monomial_constant_1d........................................ FAILED (ERRMSG)
variables/fe_monomial_const.test_monomial_constant_2d........................................ FAILED (ERRMSG)
variables/fe_monomial_const.test_monomial_constant_3d........................................ FAILED (ERRMSG)
```

**Comment by friedmud** [comment]
What are we trying to optimize here?  The only reason to have a `hasTimeDerivitive()` is for optimization.  Someone needs to produce a profiling run that shows that simply returning `0` from a base class implementation of `timeDerivative()` is taking up a significant chunk of application time before we decide to add something like `hasTimeDerivative()`

**Comment by bwspenc** [comment]
I'm not trying to optimize. I just want to check to see whether the method is implemented so I can do something else rather than die with an error when I call it and it doesn't work.

**Comment by bwspenc** [comment]
...and I don't think just returning 0 if it's not implemented is acceptable because you have no way of knowing whether the derivative is really zero, or the method hasn't been implemented for the function you're using.

**Comment by friedmud** [comment]
The MOOSE way is to return 0.  That's how we handle this all throughout the library.

Interestingly: I've been learning Apple's new programming language called Swift ( https://www.apple.com/swift/ ) and it has a built in mechanism to deal with this: Optionals ( http://blog.teamtreehouse.com/understanding-optionals-swift ).  It allows for type safety, no pointers... but still returning `NULL`  (called `nil` in Swift) to indicate that something was invalid.

So in this case the `timeDerivative()` function would return a `Double?` (yes, you really use a question mark like that!).  It would either have its value or it would be `nil`... to indicate the two possible states.

It can kind of be a pain in the butt: you have to "dereference" (called "unwrapping" in Swift) the Optional using a `!` to get the value... but the end result is good.  They also introduced some interesting syntax that works like this:

```
if let td_val = function.timeDeritivative()
{
  derivative += td_val;
}
```

It's a combined variable declaration _and_ if statement that implicitly unwraps the variable so you can use it like normal (ie without a `!`) inside the if body.

Anyway: That's fairly off-topic... BUT we don't have anything like that in C++ (the closest would be to return a pointer that could be NULL... but _GROSS_!)... so for now just return 0.  :-)

**Comment by dschwen** [comment]
This thread is irrecoverably detailed.

**Comment by permcody** [comment]
You know Java and C# box types too. Maybe you've been in the C++ shell for
too long.

**Comment by friedmud** [comment]
Honestly didn't know about it - but cool!

Like I said: I'm torn on the whole idea (adds a TON of error checking and
"dereferencing" code all over the damn place) but it certainly has its
uses...

Derek

**Comment by bwspenc** [comment]
I hate to belabor this, but "the MOOSE way" of returning a zero won't cut it.  I'm relying on the derivative to calculate some physics, not just for Jacobian entries.  The user needs to have a way of knowing that the function that they're using can't be used with the physics they're trying to model.  I'm OK with just removing the ```haveTimeDerivative()``` method in my pull request if it's too un-MOOSE-y, but having the ```timeDerivative()``` method throw a mooseError, like I have it coded.  I don't really care how this is implemented as long as I can error out if I'm trying to use something that's not implemented.

Alternatively, the base class could do finite differencing to get the derivative...

**Comment by friedmud** [comment]
The thing is... you've added this to catch an error but now you've introduced a new one:  you have to implement these in pairs (and keep them synced up).  There is no right answer here... but why not just let it return zero.  If you get zero back from `timeDerivative()` you could print out a warning or even stop depending on what you're trying to do.

0 in this case is just as good as "didn't implement it" because you are depending on it not being zero (presumably that's why you want to check on it).  Whether they implemented it and it _is_ zero or they didn't implement and it's zero the fact of the matter is that you still have to deal with a zero time derivative.

In fact, checking for 0 is better than checking `hasTimeDerivative()` because they might have returned true from that function and _still_ not implemented `timeDerivative()`!!!  Throwing off your whole scheme!  Further, think about someone inheriting from a Function that has implemented `hasTimeDerivative()` to be `true` and they don't implement anything to do with time derivatives and now they are telling the world false information.

I don't think that `hasTimeDerivative()` is the silver bullet you're looking for here.  The only thing you can know is that 0 did or did not come back from `timeDerivative()`.... and then you need to make a decision about what to do next.

**Comment by aeslaughter** [comment]
I side with Ben on this, because in some cases zero is a valid answer so it
would falsely halt your program if you are using zero to check against. I
will propose another option, make timeDerivative() a pure virtual. This
would then force the derived class to define the behavior, which could
return 0, -99999, or throw an error. But, the user would know what it was
doing because they coded it. This may be what we should do for all the
function methods: value(), gradient(),...

**Comment by friedmud** [comment]
Absolutely hell no to the pure virtuals.

I do like your idea of suggesting something so onerous that I have to alternative other than relent :-)

However, I still don't agree.  In all other cases returning zero is just fine (even if it's "real" or not) it's only in Ben's case here where he's saying that not having a time derivative is not ok...

But whatever.  Just don't force everyone to implement tons of functions that return zero...

You guys are WAY over optimizing a corner case... and now you're willing to destroy a perfectly good, working, interface that has worked fine for years?

Always remember: code for the 99% use case... you can't create "perfect" software and trying to do so usually just creates software that no one wants to use...

I'm out.

**Comment by andrsd** [comment]
By definition, everything that inherits from `Function` is a time-dependent function (go look at the header file). Is the concern here is that the function may not be smooth in time and therefore would not have derivative defined at some point?  Otherwise, the derivative always exists and for some functions it is zero.

**Comment by bwspenc** [comment]
@andrsd The concern is that currently, only 3 of those functions (which happen to be the ones I care about) have an easy way to implement ```timeDerivative()```, and I don't have the time to implement that for every class that derives from Function.  You're absolutely correct that every Function out there ought to be able to calculate the time derivative.  I just wanted the code to error out if you try to use it and it isn't implemented.

**Comment by YaqiWang** [comment]
If a developer implemented a function, let us say `t`, in `value()`, but did not implement `timeDerivative()`. Currently a user will get zero when calling `timeDerivative()`, which is wrong and a potential bug. Adding a mooseError in `Function` does not enforce developers to implement `timeDerivative()` but will catch an error of using it (it is not always be used). Or as I suggested, change the interface to `bool getTimeDerivative(***, Real & timederivative) const`, and return false in `Function`.

**Comment by andrsd** [comment]
@bwspenc If the other classes do not have `timeDerivative` they do not even call it, thus returning zero in the base class is not going to harm anything. Right?

**Comment by andrsd** [comment]
@YaqiWang If somebody does not implement their class properly, it is their own damn fault, not ours. It is like trying to fix the wrong physics in the application code on MOOSE level...

**Comment by YaqiWang** [comment]
@andrsd No, it is our fault, because we allows them to do so.

**Comment by andrsd** [comment]
@aeslaughter Doing pure virtual on `timeDerivative` might break a lot of code we do not know about. So we could change the interface and let others deal with it, or we can enhance the interface and not break their code by returning 0.

**Comment by andrsd** [comment]
@YaqiWang I do not agree with your. It is the same as somebody implements a residual statement, but they do not implement their Jacobians and then they complain about poor convergence. The error is clearly on the application level, not in MOOSE.

**Comment by YaqiWang** [comment]
That is why we need to be clear on our boundary. For Jacobian evaluation, we state that it does not have to be and sometimes cannot be exact and the consequence is warned. But here it is so simple to add a mooseError.

**Comment by andrsd** [comment]
@YaqiWang The boundary is drawn by the fact that everything that inherits from `Function` __is__ time-dependent.

**Comment by YaqiWang** [comment]
We have few options on `Function::timeDerivative` here summarizing:
1) make it pure virtual;
2) add mooseError in it;
3) change its interface;
4) add Function::hasTimeDerivative.

We can vote on these. Multiple votes are ok. What do you think?
