### ISSUE TITLE
Create auxkernel that calculates the VonMises value of a RankTwoTensor

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#4774]
We can currently output one component of a RankTwoTensor, but we can't output the VonMises form (typically used with a stress).

**Comment by WilkAndy** [comment]
If you want, you could add the eigenvalues too (principal stresses) - they're often quite useful.

**Comment by cpritam** [comment]
That's a good suggestion. I will add them to the scalar types.

Pritam
