### ISSUE TITLE
MooseVariable is not copyable

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#4785]
Just helped @a-f-dykhuis debug a piece of code he's putting into MOOSE.  He happened to accidentally pass a MooseVariable _by copy_... and of course that was causing memory corruptions when he was trying to use it.

We should make the copy constructor for MooseVariable private.

**Comment by jwpeterson** [comment]
@a-f-dykhuis = Andrew F'in Dykhuis

**Comment by dschwen** [comment]
Hold on, I thought it has to be copyable to be used in STL containers? I vaguely remembered trying to make the copy CTOR private when I made it private for material properties but I ran into that specific problem.

**Comment by permcody** [comment]
https://github.com/idaholab/moose/pull/3226

**Comment by friedmud** [comment]
Closing because of #3226
