### ISSUE TITLE
porepressure, etc, coupling in TensorMechanics

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4792]
I imagine @tonkmr , @pou036 , and Yidong (don't know his github username!) will be interested in this.

For quite a while, when people ask me "can moose do poroelasticity?" i've been answering "No, but it's no big deal to put it in".  Andy: it's time to actually DO SOME CODING!

This will generalise the temperature coupling that already exists.

**Comment by WilkAndy** [comment]
Hi @pou036 , @tonkmr, @cpritam , @dschwen .

**Thomas**, could you please look at the "Extension: coupling with porepressure" section of 
http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/TensorMechanicsBasics/
just to check this is what you want.

** Everyone** When I opened this issue, i was going to derive off StressDivergenceTensors, adding the porepressure bit into the kernel.  However, after doing the above doco, I'm not totally convinced we need that since users could just add their own "div(P)" in the input file, hence zero coding, and keeping MOOSE lean-and-mean.  The disadvantage of this is that it requires some knowledge from the user.   What do you think?

a

**Comment by bwspenc** [comment]
I discussed this a while back with Mitch, Hai, and Yidong, and I personally like the idea of adding another kernel to add the pore pressure term to the PDE rather than mixing it in with the StressDivergence kernels.

**Comment by WilkAndy** [comment]
@bwspenc , so you mean we should write another Kernel in tensor_mechanics/kernels that adds in the porepressure term?

**Comment by bwspenc** [comment]
That's what I think.  It actually wouldn't even be specific to tensor_mechanics (it would work with solid_mechanics too) but if it makes the most sense to put it there, that's fine.  It would actually be a set of 3 kernels for the 3 directions, along with an action to set them up, just like we have for mechanics.  That's a little messy, but I think it clarifies things to have it in a separate kernel, since it is a separate term in the PDE.  The thing I really like about it is that there is actually no code at all that needs to be touched in the mechanics materials or kernels.

**Comment by WilkAndy** [comment]
Good, thanks @bwspenc .   That's what i was thinking too.  At least the Jacobians will be easy - heheheh, they often seam to give me headaches.

Any comments from anyone else?  I hope to do this within a week, sorry for the slowness - i just don't have heaps of time, unfortunately.

**Comment by WilkAndy** [comment]
oops, embarrassment - i should have written "grad(P)" in a comment above instead of "div(P)" !  Sorry for any confusion.

**Comment by pou036** [comment]
I agree with @bwspenc<https://github.com/bwspenc> that a new kernel is the way to go, but I don’t understand why you’d need 3 (for 3 directions), unless you have other usages than pore pressure (isotropic) in mind
We have done that in redback (in a single kernel, that needs to be broken down): https://github.com/pou036/redback/blob/master/src/kernels/RedbackStressDivergenceTensors.C

**Comment by WilkAndy** [comment]
@pou036 , i think @bwspenc was just meaning that we need to pick out a direction.  Not necessarily 3 kernels, but one kernel with a direction specification, like the "component" in StressDivergenceTensors.

Anyway, now you're at work - is the stuff at
http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/TensorMechanicsBasics/
what you're after?

**Comment by pou036** [comment]
Thanks Andy, your documentation is indeed what we’re doing in Redback, using the effective stress for the existing kernel. We still need to access P in the material though, so an appropriate AuxVariable is required as you’re pointing out.

**Comment by WilkAndy** [comment]
Great, thanks for looking at that, @pou036 .

**Comment by WilkAndy** [comment]
Just to let you guys know - i am actually working on this .... slowly.  If anyone else takes this on, please tell me so i don't waste my time!
