### ISSUE TITLE
Get a UserObject from a TimeStepper

### ISSUE THREAD

**Issue by giopastor** [idaholab/moose#4796]
I am trying to introduce time stepping controlled by physics criteria from material models. The minimum time step from material models is calculated by a UserObject. I would need an interface to be added that allows UserObjects to be retrieved inside a TimeStepper.
Thank you for your help,
giovanni

**Comment by permcody** [comment]
Giovanni, I believe you solved this issue using Postprocessors instead? Is that correct?

**Comment by permcody** [comment]
Tagging @giopastor
