### ISSUE TITLE
deprecate or enhance AreaPostprocessor

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#4799]
I want to calculate the integral of a function over a sideset.  Therefore i want to either deprecate AreaPostprocessor and create a new FunctionIntegral, or to enhance AreaPostprocessor so that it takes an optional Function argument:

params.addParam<FunctionName>("function", 1.0, "doco")

FunctionIntegral::computeQpIntegral()
{
  return _func.value(_t, _q_point[_qp]);
}

Comments?

**Comment by friedmud** [comment]
Please don't modify AreaPostprocessor - it does exactly what it's supposed to do and doesn't need to do anything different.

If you would like to create FunctionIntegral that inherits from SideIntegralPostprocessor... go for it

**Comment by friedmud** [comment]
Actually - I suppose that would be FunctionSideIntegral
