### ISSUE TITLE
Small petsc option issues

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#4816]
I happened to notice that `PetscOptionsGetAll()` will return all options used by solver and `-i inputfile.i`, which is not a petsc option. Also all options set in `petsc_options` in the input file appear to be capitalized. This is minor, so I am not sure if your guys consider it as an issue.

**Comment by permcody** [comment]
We are aware of this issue. In fact I've worked to make the command line options better but PETSc still doesn't behave the way we'd like. Closing this in favor of #727 and #4816.

**Comment by YaqiWang** [comment]
I see. I remembered petsc support a prefix for all its options, we probably need to use it with the problem name for all our runs. Not sure how complicated this will be. Also it would be nice to print out all used options including those not specified in the command line.

**Comment by permcody** [comment]
That's what that PR was about. Turns out PETSc won't show you unused
options until you have called solve. There are reasons for this, but it
makes it difficult to warn the user during our normal sanity checks.

**Comment by YaqiWang** [comment]
Maybe we should ask PETSc for a list of unrecognized or non-native options giving the prefix and a list of options passed in. After solve, we then can ask PETSc for unused options. Just giving some suggestions.

**Comment by permcody** [comment]
After the first solve? After the last solve? What if your solve takes
several minutes? We do need to add it, just wish there was a cleaner way.

**Comment by YaqiWang** [comment]
Theoretically it should be after the last solve because we are not assuming every solve are the same. But unrecognized options can capture most of input errors.
