### ISSUE TITLE
Add GrainTracker example to phase field module

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#4827]
Now that the grain tracker is in the module, we need to add the example problem as well

**Comment by permcody** [comment]
Agreed, There are a couple in the marmot/problems/GrainMapper folder that
are fairly good. They just need to have their materials switched out. Maybe
you have something else in mind.

**Comment by tonkmr** [comment]
There is a 2D one in MARMOT examples that I am just going to move over.
