### ISSUE TITLE
Peacock temp input generation bug

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4838]
When running the input file

```
moose/modules/phase_field/examples/multiphase/DerivativeMultiPhaseMaterial.i
```

from peacock, MOOSE throws the following error:

```
Error: the following unidentified entries were found in your input file:
Variables/eta3/InitialCondition/sqrt(x^2+y^2);if(r>7,1,0)
```

The issue seems to be that the temp input that peacock writes out does not contain quotes around the function expression in the variable initial conditions:

```
function = r:=sqrt(x^2+y^2);if(r>7,1,0)
```

**Comment by friedmud** [comment]
Hmmm - it does that because there is only one item... so it normally wouldn't need the quotes.

Why are they necessary for the function?

This seems like more of a GetPot problem to me.  There is only one item there so there shouldn't be an issue reading it in...

**Comment by dschwen** [comment]
> Why are they necessary for the function?

I don't know, you tell me ;-). It looks to me like the parser does not like the ```=``` sign in the expression.

**Comment by permcody** [comment]
I'm sure that's probably it. Without quotes the equals sign makes the
parser think there's another name/value pair.

**Comment by friedmud** [comment]
@permcody what do you think the fix is then?  Should we try to fix GetPot?  It's obviously parsing incorrectly here... and I can't see putting something in our documentation like:  "oh, you normally only need single quotes for lists of multiple items... but if you're passing something that has an = sign in it then you also need single quotes"...

**Comment by permcody** [comment]
I think Getpot is working correctly. If you ignore whitespace the tokenizer
will pass back what looks like "A = B = C" in this case.

That's a syntax error. If you use an equals sign as your delimiter then
this is the way it should work. I think either escaping or quoting is
necessary to resolve this ambiguity, unless you pay attention to spacing
(yuck).

**Comment by dschwen** [comment]
A first step would be to have peacock add quotes to single items containing
equal signs.

**Comment by permcody** [comment]
While that would work we'd have spurious quotes added at dozens of spots
even in a simple input file. I would suggest that we only add quotes to
values containing special characters.

**Comment by dschwen** [comment]
Which is basically what I said ;-)

**Comment by permcody** [comment]
Oh you did! I read something completely different.

**Comment by friedmud** [comment]
I disagree @permcody

The tokenizer should see:

```
name = value
```

Regardless of what is in "value".  GetPot already uses white space to know when it's finished reading one value and is ready to read the next name like so:

```
name = value name2 = value
```

Which is valid and defines two different variables. As opposed to:

```
name = valuename2 = value
```

Which is obviously invalid.  The difference between the two is the SPACE.  Therefore I see no reason why this situation should not work:

```
name = junk=stuff
```

GetPot should see a "name" then the equals and then keep eating chars until it hits a space... building up the "value".

**Comment by dschwen** [comment]
Yeah, I agree with Derek. Ultimately getpot should be fixed to address this inconsistency.

**Comment by permcody** [comment]
It depends on whether we collapse whitespace or ignore it. Derek is correct
in the former case. I thought Getpot completely ignored it.

**Comment by dschwen** [comment]
Huh? Getpot cannot _completely ignore_ whitespace, otherwise we'd always have to use quotes! I think the main point is that getpot treats an ```=``` differently than other non-whitespace chars.

**Comment by permcody** [comment]
True, it doesn't completely ignore whitespace, but it uses a "tokenizer" parser so it'll be somewhat tricky to fix since the tokenizer doesn't know anything about the parser state.
