### ISSUE TITLE
Diffusion equation with Diffusivity as a function of concentration

### ISSUE THREAD

**Issue by amitjn7042** [idaholab/moose#4845]
I am new to MOOSE and finding it difficult to get familiar. I got stuck to a problem, please help me out if you can. 

I am simulating a transient diffusion problem in MOOSE. The diffusivity in the equation is a function of concentration. How do I need to proceed? 

Thanks, 
Amit Jain

**Comment by friedmud** [comment]
Let's continue the discussion on the mailing list... But just for historical purposes I'll post my mailing list answer here as well:

The simplest way to get into MOOSE is to look in the "examples" directory in your MOOSE checkout (or you can look here https://github.com/idaholab/moose/tree/devel/examples )

In this particular case look at ex08_materials. It's a complete convection-diffusion application with a custom diffusion Kernel (called ExampleDiffusion) that accepts a material property that is computed in the ExampleMaterial Material object.

You may also want to view the wiki page for the Example: http://mooseframework.org/wiki/MooseExamples/Example_08/

And the Materials section in the workshop slides starts in slide 141: http://mooseframework.org/static/media/uploads/docs/main.pdf

The basic idea here is that a Kernel represents a term in a PDE you want to solve and a Material class computed coefficients for the Kernel. This allows for a separation of responsibility that allows for maximum code reuse (you can swap out how a material property is computed without changing the Kernel).
