### ISSUE TITLE
pressure_pulse.pp_fu_lumped_22 fails on Intel

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#4846]
I don't want @WilkAndy to necessarily waste his time trying to fix this without having access to Intel compilers, but still wanted to make a note of it as it seems to be our only (?) modules test that fails with Intel compilers.  Seems to be a tolerance thing rather than an actual error.  See [here](https://www.moosebuild.org/view_result/14374) for example.

```
pressure_pulse.pp_fu_lumped_22: Time Step 10, time = 10000
pressure_pulse.pp_fu_lumped_22:                 dt = 1000
pressure_pulse.pp_fu_lumped_22:  0 Nonlinear |R| = 2.077447e-05
pressure_pulse.pp_fu_lumped_22:       0 Linear |R| = 2.077447e-05
pressure_pulse.pp_fu_lumped_22:       1 Linear |R| = 2.508942e-17
pressure_pulse.pp_fu_lumped_22:  1 Nonlinear |R| = 2.077403e-05
pressure_pulse.pp_fu_lumped_22:       0 Linear |R| = 2.077403e-05
pressure_pulse.pp_fu_lumped_22:       1 Linear |R| = 1.336533e-15
pressure_pulse.pp_fu_lumped_22:  2 Nonlinear |R| = 1.501341e-05
pressure_pulse.pp_fu_lumped_22:       0 Linear |R| = 1.501341e-05
pressure_pulse.pp_fu_lumped_22:       1 Linear |R| = 1.463401e-25
pressure_pulse.pp_fu_lumped_22:  3 Nonlinear |R| = 1.599461e-13
pressure_pulse.pp_fu_lumped_22:       0 Linear |R| = 1.599461e-13
pressure_pulse.pp_fu_lumped_22:       1 Linear |R| = 3.091506e-17
pressure_pulse.pp_fu_lumped_22:       2 Linear |R| = 2.878011e-17
pressure_pulse.pp_fu_lumped_22:       3 Linear |R| = 5.941703e-18
pressure_pulse.pp_fu_lumped_22:       4 Linear |R| = 9.839383e-20
pressure_pulse.pp_fu_lumped_22:  Solve Did NOT Converge!
```

I'm actually not sure why the -snes_atol of 1e-10  which you set manually:
```
    petsc_options_iname = '-ksp_type -pc_type -snes_atol -snes_rtol -snes_max_it'
    petsc_options_value = 'bcgs bjacobi 1E-10 1E-10 100'
```
doesn't trigger.  Might indicate a bug in one of our custom PETSc convergence tests...

Here's the exodiff:
```
pressure_pulse.pp_fu_lumped_22:   --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, rel diff:  0.00000e+00 ---------
pressure_pulse.pp_fu_lumped_22: Nodal variables:
pressure_pulse.pp_fu_lumped_22:   --------- Time step 2, 1.0000000e+04 ~ 1.0000000e+04, rel diff:  0.00000e+00 ---------
pressure_pulse.pp_fu_lumped_22: Nodal variables:
pressure_pulse.pp_fu_lumped_22:    pgas         rel diff:  2.6019303e+06 ~  2.6025956e+06 = 2.55658e-04 (node 2)
pressure_pulse.pp_fu_lumped_22:    pwater       rel diff:  2.6019303e+06 ~  2.6025956e+06 = 2.55648e-04 (node 2)
```

**Comment by WilkAndy** [comment]
I typically put very low -snes_atol values to get rid of these diffs.... sigh.   I don't understand why petsc isn't saying "converging" though!   I'm quite busy at the moment, but will try to look at it at some stage soon.

**Comment by WilkAndy** [comment]
OK, the -snes_atol = 1E-13 for this example.  So your 1E-10 must come from an alliterative (old?) version, @jwpeterson .   I'm investigating the nonconvergence now.   Strange that the linear residuals are quite a lot larger in the intel case - i would have thought the BCGS would be pretty standard over architectures.

**Comment by WilkAndy** [comment]
Hi @jwpeterson,

Sorry to bug you, but would you please tell me what happens with the following options:

    petsc_options = '-snes_monitor -snes_linesearch_monitor'
    petsc_options_iname = '-ksp_type -pc_type -snes_atol -snes_rtol -snes_max_it -ksp_atol -ksp_rtol -ksp_max_it'
    petsc_options_value = 'bcgs bjacobi 1E-13 1E-13 100 1E-20 1E-50 20'

**Comment by jwpeterson** [comment]
> OK, the -snes_atol = 1E-13 for this example. So your 1E-10 must come from an alliterative (old?) version,

Huh, I must have looked at the wrong input file, my bad.  Not sure how that could have happened with filenames like:
```
pp_fu_lumped_22.i
pp_lumped_02.i
pp_lumped_22.i
```

;-)

**Comment by jwpeterson** [comment]
> Sorry to bug you, but would you please tell me what happens with the following options:

Sure.  Let me get my Intel build up to date and I will try them.

**Comment by jwpeterson** [comment]
Welp, once I finally got my Intel build going on one of our other Linux boxes, this test actually passed with *both* the original options and the updated options you suggested.

Since Moosebuild's [history](https://www.moosebuild.org/view_branch/4) shows failures have occurred for this test for the linux-intel target on hpcbuild2, 3, and 5, I think it would be simplest if you just commit these new options, and I'll keep an eye on the linux-intel target over time to see if it fixes itself.

**Comment by WilkAndy** [comment]
Will do,

a

**Comment by jwpeterson** [comment]
FYI, that looks like it [worked](https://www.moosebuild.org/view_result/14478), the `linux-intel` target passed.

**Comment by WilkAndy** [comment]
Thanks @jwpeterson .  It must be a boring, never-ending task getting people to change their tests for different architectures/compilers, so thanks for helping me with this one.

a
