### ISSUE TITLE
Move PenetrationInfo::_contact_force into an aux variable.

### ISSUE THREAD

**Issue by shanestafford** [idaholab/moose#4850]
The contact force is stateful data that is used in the MechanicalContactConstraint. It should be moved into an aux variable so it can make use of automatic ghosting and restarts.

**Comment by shanestafford** [comment]
The above version causes issues on some of the assessment cases, so I'm working on a version that uses AuxKernels to save/read the contact forces.

**Comment by friedmud** [comment]
What do you mean by "save/read"? Can you elaborate?

**Comment by shanestafford** [comment]
PenetrationInfo::_contact_force is copied into PenetrationInfo::_contact_force_old at the beginning of each time step. There was concern that these PenetrationInfos could have incorrect states if slave nodes move off process due to displacement.

By save/read, I mean that the AuxKernel copies the previous contact forces from the aux variables into PenetrationInfo::_contact_force_old at the beginning of the time step (in timestepSetup) and then writes the new contact forces from PenetrationInfo::_contact_force into the aux vars (via computeValue) at the end of the time step. If any ghosting is needed, or if residuals for slave nodes move onto other processes, it should now be handled automatically by the aux variable system.

**Comment by friedmud** [comment]
Ok - that sounds good.  Just making sure there wasn't some file I/O or
something else going on!

Syncing this stuff through the Aux system is something we've talked about
for a while... and I think it's a good idea.

Bonus: it enables _viewing_ of the state of the contact information over
time as a field!

Derek

**Comment by shanestafford** [comment]
I'm going to leave this open just a little while longer to take a look at the restartable data in PenetrationInfo and PenetrationLocator, which can probably be removed now.
