### ISSUE TITLE
Generating meshes using Cubit with Python scripts

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#486]
Idea: have a base class that can run a python script. Then application can inherit from this base class, add params, etc.

Users can do in their input files:
[ [GenerationCubit](Mesh]
)
     Type = Pellet
     param1 = value1
     param2 = value2
  [../]

**Comment by jwpeterson** [comment]
I think it has since been decreed that we are not going to be calling Python from C++.  Also this ticket is fairly old and no one's been clamoring for the feature..
