### ISSUE TITLE
Multiapp Initialization and header sanity

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4877]
I believe that we should settle on a way to display information to the users when running a Multiapp simulation:

- Currently Headers are output in post-order depth first search
- Execution Order however is post-order breadth first search

We should output the headers in execution order or *pre-order* breadth first search (my pick). While execution order has the obvious advantage of indicating the execution order it still creates an odd order to display information to the user. It reports information about *this* simulation very last and shows the user information about the lowest leaves very first. If additional levels are tacked onto the bottom they also start coming out first which just doesn't feel intuitive. I feel that the best order to display header information in a top down fashion. See samples below:

```
post-order depth first search (current implementation)
sub0_sub0
sub0_sub1
sub0
sub1_sub0
sub1_sub1
sub1
master
```

```
pre-order breadth first search (my favorite)
master
sub0
sub1
sub0_sub0
sub0_sub1
sub1_sub0
sub1_sub1
```

```
post-order breadth first search (execution order - another alternative)
sub0_sub0
sub0_sub1
sub1_sub0
sub1_sub1
sub0
sub1
master
```

@idaholab/moose-developers please comment

**Comment by andrsd** [comment]
+1 to pre-order breadth first search - it is the most logical one in my
book.

**Comment by aeslaughter** [comment]
I don't care all that much, I just want to see the output in the order that
things are happening.
