### ISSUE TITLE
Peacock bug in writing peacock_run_tmp.i

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4880]
Below is an sdiff of my input file and peacock_run_tmp.i

Peacock is removing the active = '' line effectively turning on adaptivity.

```
[Executioner]                           [Executioner]
  active = ''                             <
                                  <
  type = Transient                        type = Transient
  dt = 4.0                            dt = 4.0
  num_steps = 5                           num_steps = 5
                                  <
  [./Adaptivity]                          [./Adaptivity]
    refine_fraction = .40                       refine_fraction = .40
    coarsen_fraction = .02                      coarsen_fraction = .02
    max_h_level = 3                         max_h_level = 3
    error_estimator = KellyErrorEstimator               error_estimator = KellyErrorEstimator
  [../]                               [../]
[]                              []
```

**Comment by brianmoose** [comment]
This is actually an issue with the python `ParseGetPot`. It doesn't match parameter values with empty '' so peacock never even sees it.

**Comment by brianmoose** [comment]
So this would still be an issue with the new peacock.

**Comment by permcody** [comment]
@brianmoose, @rwcarlsen - This can probably be closed. May need to verify.

**Comment by permcody** [comment]
@brianmoose, @rwcarlsen - This can probably be closed. May need to verify.

**Comment by brianmoose** [comment]
This seems to be fixed. The new hit parser handles parsing `active = ''` fine
and there have been recent changes to peacock to handle the `active` parameter.
I tried putting `active=''` on a block and peacock correctly does not include any children.
I did find a problem with peacock and the active parameter. That PR will close this.
