### ISSUE TITLE
Recover not working with default options

### ISSUE THREAD

**Issue by shanestafford** [idaholab/moose#4893]
The recover tests pass, but a test of the feature shows that it does not work as expected when run outside of the test harness. In time_integrators/implicit-euler with the ie.i input file:

###### Adding a checkpoints block to Outputs with default options (no options specified) works as promised, producing 2 rolling checkpoints.

    $ ls ie_checkpoints_cp/
    0002.rd-0     0002_mesh.cpr 0003.xdr.0000 0004.xdr      0005.rd-0     0005_mesh.cpr
    0002.xdr      0003.rd-0     0003_mesh.cpr 0004.xdr.0000 0005.xdr
    0002.xdr.0000 0003.xdr      0004.rd-0     0004_mesh.cpr 0005.xdr.0000

###### Changing num_steps to 10 and running with --recover produces an error:

    $ modules-dbg -i ie.i --recover
    *** ERROR ***
    Unable to find suitable recovery file!

###### Telling MOOSE where to find the checkpoints squelches the error, but the time stepper starts the simulation from the beginning:

    $ modules-dbg -i ie.i --recover=ie_checkpoints_cp/0005
     
    [snipped header]
    
    Time Step  0, time = 0
                    dt = 0

    Postprocessor Values:
    +----------------+----------------+
    | time           | l2_err         |
    +----------------+----------------+
    |   0.000000e+00 |   0.000000e+00 |
    +----------------+----------------+
    
    Time Step  1, time = 0.25
                    dt = 0.25
     0 Nonlinear |R| = 3.062746e+00
     1 Nonlinear |R| = 1.908510e-05
     2 Nonlinear |R| = 1.058361e-10
     Solve Converged!
    
    ...etc

**Comment by aeslaughter** [comment]
I just ran this on devel, it worked fine.

cd ~/projects/moose/test/tests/time_integrators/implicit-euler

~/projects/moose/test/moose_test-oprof -i ie.i --half-transient
Outputs/checkpoint=true

~/projects/moose/test/moose_test-oprof -i ie.i --recover

**Comment by permcody** [comment]
Confirmed - it appears that changing any time related input parameters with "recover" is NOT supposed to work. You can run 10 total steps if you use the `--half-transient` option and recover from timestep 5. Yet another difference between restart and recover.

**Comment by aeslaughter** [comment]
Ok, changing the num_steps to 10 doesn't work, but I am not sure that it
should. Running an input file with different parameters with --recover is
not the intent of the system.

This however does work:

~/projects/moose/test/moose_test-oprof -i ie.i --half-transient
Outputs/checkpoint=true Executioner/num_steps=10

~/projects/moose/test/moose_test-oprof -i ie.i Executioner/num_steps=10
--recover

**Comment by friedmud** [comment]
Yes: this is intended behavior.  Remember that "recover" is for doing that:
recovering from an aborted run.

"Restart" should be used when you want to continue an earlier solve.

You really shouldn't be changing anything when using "recover"... but in
reality you can get away with some things ;-)

**Comment by shanestafford** [comment]
I thought recover was supposed to work if, say, a run has crashed in the
middle. If you do this test and hit ctr-C in the middle, it still does not
work when attempting to recover.

**Comment by permcody** [comment]
Yes it should recover if it crashes, however in practice we find that we
generally need two checkpoint files for that case because the final one may
be corrupted if you use Ctrl-C to kill it.

**Comment by aeslaughter** [comment]
CTRL-C works for me.

Time Step 20, time = 5

                dt = 0.25

 0 Nonlinear |R| = 3.062746e+00

 1 Nonlinear |R| = 1.912170e-05

^C

slauae@slaughter:~/projects/moose/test/tests/time_integrators/implicit-euler
(devel)$ ~/projects/moose/test/moose_test-oprof -i ie.i
Executioner/num_steps=30 --recover


Using ie_out_cp/0020 for recovery.



Time Step 21, time = 5.25

                dt = 0.25

 0 Nonlinear |R| = 3.062746e+00

 1 Nonlinear |R| = 1.903475e-05

 2 Nonlinear |R| = 1.044608e-10

 Solve Converged!


Postprocessor Values:

+----------------+----------------+

| time           | l2_err         |

+----------------+----------------+

**Comment by shanestafford** [comment]
I must be doing something wrong. Can't get it to work even if I delete the last checkpoints (in case they are corrupted).

**Comment by shanestafford** [comment]
Time Step 11, time = 2.75
                dt = 0.25
 0 Nonlinear |R| = 3.062746e+00
 1 Nonlinear |R| = 1.906271e-05
^C
~/repos/debug/bison/moose/test/tests/time_integrators/implicit-euler [(cfcf20d...) **]$ ~/repos/debug/bison/moose/test/moose_test-dbg -i ie.i Executioner/num_steps=30 --recover


*** ERROR ***
Unable to find suitable recovery file!

**Comment by aeslaughter** [comment]
Shane I was able to reproduce the problem you are having with a dbg build.
@permcody you need to get on the debugging version of the checkpoint files.

**Comment by aeslaughter** [comment]
Ok, I lied it works fine with debug, I failed to enable checkpoint files when I tried it.

**Comment by shanestafford** [comment]
I narrowed it down to the difference between this:
    [Outputs]
      checkpoint = true
    []
and this:
    [Outputs]
      [./checkpoints]
        type = Checkpoint
      [../]
    []
The former works with recover and restart while the latter only works with restart.
