### ISSUE TITLE
Peacock UI has too much whitespace

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4907]
Peacock is pretty much unusable on small displays due to the large UI margins and whitespace. The minimum window height is > 900px.

**Comment by dschwen** [comment]
At this point (e1103a5) the Peacock Visualization tab looks like this:
![peacock_compacter](https://cloud.githubusercontent.com/assets/202302/7056443/df00680e-de08-11e4-9e02-29c79ff8421f.png)

**Comment by dschwen** [comment]
I'm thinking about removing the "Time" groupbox. It should be clear what the buttons mean (play button always progresses through time and it says "Timestep" right there). This would add some vertical space for the viewport.

Under the view heading I'd like to replace the "Black" checkbox with a dropdown (with "Gradient", "Black", "White"). We frequently need a white bg for presentations. 

The division between the left option pane and the viewport/timecontrols should probably be made draggable.

The whitespace in the xyz labels in the scale line needs tuning.

The strech factors in the Clip line should be adjusted to give more stretch to the slider.

We might want to think about adding icons to the Open/Save/Reset buttons to make them stand out a bit.

**Comment by permcody** [comment]
Cool - I like these changes. If you figure out how to display the
simulation "time" somewhere that would be worth several bonus points! I
haven't decided what if any value those points have, but hey, bonus
points!!!

**Comment by dschwen** [comment]
Added a white BG option (note how this changes the fonts as well) and I'm experimenting with using QDoubleSpinBox for numbers (looks busy, but has spinners to quickly adjust values :-/ )

![peacock_white](https://cloud.githubusercontent.com/assets/202302/7057423/ca59fa32-de12-11e4-8f76-9ddb8bfa3838.png)

**Comment by dschwen** [comment]
I added a splitter between the viewport/timecontrols and the settings (which also allows the settings to be fully collapsed). The settings now scale horizontally in a sane way. I will make all number inputs double spinners (like the scale inputs above). That would clear my todo list and I would make this a PR. Comments are appreciated.

**Comment by dschwen** [comment]
#4914 does not close this ticket, it only "addresses" it. I still have a branch that contains work to make the other tabs look similar.

**Comment by jwpeterson** [comment]
> #4914 does not close this ticket, it only "addresses" it. I still have a branch that contains work to make the other tabs look similar.

I kind of thought addresses == closes too.

**Comment by permcody** [comment]
I think in Trac terminology, John may be correct. Oh well it's reopened
nonetheless.

**Comment by dschwen** [comment]
So what should I use instead?

**Comment by jwpeterson** [comment]
On Wed, Apr 15, 2015 at 11:25 AM, Daniel Schwen <notifications@github.com>
wrote:

> So what should I use instead?
>

Ansprechen #4907

-- 
John

**Comment by permcody** [comment]
refs #4907
