### ISSUE TITLE
Make initial_from_file_var more robust

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4911]
Right now this old syntax to copy values from the input file only works if the variable names match. Either an error should be produced or it should support copying from one variable name to another.

See https://groups.google.com/forum/#!msg/moose-users/zyRDzJTM3_s/mFnJKMwjKl4J

**Comment by YaqiWang** [comment]
I like this syntax because it is so simple and straightforward. If libmesh maintains a ID mapping from its own node or element ID to exodus natural ID, we can read exodus file after the solution vector has been initialized.

**Comment by permcody** [comment]
Yes - this will just make it easier. You can already read from one variable name into another through the SolutionUserObject.
