### ISSUE TITLE
Update HeatConductionMaterial and SolidModel

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#4913]
HeatConductionMaterial:

1) Add the derivative term for when a thermal_conductivity_function is specified.
2) Add a check to determine whether temperature is negative.  If negative set the temperature to zero.
3) Remove the const of the thermal_conductivity_function and specific_heat_function.

SolidModel:

1) Remove the const of the youngs_modulus_function and the poissons_ratio_function

Reason for removing the const:

I want to be able to set the young's modulus, poisson ratio, thermal conductivity and specific heat functions in material models that derive from HeatConductionMaterial and SolidModel.  To modify these I need them to be not const.

**Comment by andrsd** [comment]
> 1) Remove the const of the youngs_modulus_function and the poissons_ratio_function
> 
> Reason for removing the const:
> 
> I want to be able to set the young's modulus, poisson ratio, thermal conductivity and specific heat functions in material models that derive from HeatConductionMaterial and SolidModel. To modify these I need them to be not const.

I do not understand this. Either you are using the function and you call `value()` on it or you call something else and store the values accordingly, because there is obviously some logic in place.  Or is you intent to switch the functions on the fly?

**Comment by gambka** [comment]
In the material model I'm developing we have data for Young's Modulus, Poisson's Ratio, Thermal Condcutivity, Specific Heat and Coefficient of Thermal Expansion in a piecewise linear format as a function of temperature.  I do not want to have the user having to specify these functions in the input file as they never change.  I want to have the user only specify the material alloy in the input file and the code sets the correct functions for these parameters based upon the alloy selected.

The base class already has the ability to accept functions of temperature for these parameters.  The CTE const was removed from SolidModel and ConstitutiveModel here #4817 .

**Comment by andrsd** [comment]
Could you have a GeneralUserObject that would load these functions and than your material would pick the values from this user object by calling the appropriate function on it? Then your material would not accept functions, but the user object name (this is somewhat similar to what we do in RELAP-7).

**Comment by permcody** [comment]
Kyle,

Are you coordinating with Mike on any of this? Mike and Daniel have been
doing a lot of work in Tensor Mechanics to handle various ways of
specifying material properties in various combinations. If we do everything
again from scratch in Solid Mechanics, we're duplicating some work. This is
especially important now as we start to merge these efforts into a single
module.

Cody

**Comment by bwspenc** [comment]
@andrsd, it seems like having a GeneralUserObject that provided the values of the function would require pretty extensive changes to our code structure.  We did what Kyle wants to do already with the CTE function, and it works very well with minimal impact to the code base.  You just have to live with the function pointer not being const.

**Comment by bwspenc** [comment]
@permcody We will need to do something similar when we move to TensorMechanics, but I think this is pretty minor.  This doesn't really have anything to do with what they are doing in TensorMechanics with separating the stress and strain calculation into different material models.  We need this code working now in the system that we are using, which is SolidMechanics.

**Comment by andrsd** [comment]
@bwspenc Ok.

Also, as @permcody said, if there is a plan in merging solid mechanics with tensor mechanics, it may not be worth to spend time on re-designing the internals.

So, we are looking forward for the PR... ;-)
