### ISSUE TITLE
Create MooseParameterBase

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4922]
We have definitions of getParam and getParamHelper in at least three spots: MooseObject, MooseApp, and Action. I think it is time for another base class.

**Comment by permcody** [comment]
No - those are connivence functions that shorten `_pars.getParam()` to `getParam()`. I'd rather remove the convenience functions before adding another base class. You're actually proposing to add a new class to add accessors to a class that already has accessors.

**Comment by aeslaughter** [comment]
I just want to remove code duplication, we are not supposed to do that, it is our commandments. http://mooseframework.org/wiki/CodeStandards/#code-commandments

**Comment by permcody** [comment]
Going 100% pure CS best practices is usually a bad idea. We have global variables and other nasties in the code. It's fine... I appreciate you wanting to clean things up but adding more objects might remove a few lines of straightforward code and replace it with more levels of objects that users have to dig through. Now I have to wonder what a ParameterBase class is.
