### ISSUE TITLE
Missing dependency resolution for auxiliary scalar variables

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#4923]
When we call `FEProblem::computeUserObjectsInternal(type)` and the legacy flag is off, we do not compute axes at all. Auxes of the same type should be computed instead.

The legacy behavior, IIRC, computed the LINEAR axes no matter what the type was, which is correct.

**Comment by YaqiWang** [comment]
wow, are we sure about this?

I also remembered FEProblem::initialSetup() will only evaluate UO, AuxKernels on initial when legacy flag is false, which I think is wrong. We need to make all at the right state after initialization. Execute_on initial simply means the object will stay constant during the simulation.

**Comment by aeslaughter** [comment]
Could this be related to this:
https://github.com/idaholab/moose/commit/b19c738fa044eecb2454c75b6c27b8e87c70cd8a

**Comment by andrsd** [comment]
> wow, are we sure about this?

Just look at the code in the `FEProblem::computeUserObjectsInternal(type)` method.

> I also remembered FEProblem::initialSetup() will only evaluate UO, AuxKernels on initial when legacy flag is false, which I think is wrong. We need to make all at the right state after initialization. Execute_on initial simply means the object will stay constant during the simulation.

That would be the other legacy flag - that is unrelated to this problem.

**Comment by andrsd** [comment]
@aeslaughter No, that is unrelated as far as I can tell.

The bug was introduced by e1311adddd1ad9f659b256409e31dc5d285545bb

**Comment by YaqiWang** [comment]
I thought we always combine UO and AuxKernel evaluation of the same execute_on with three steps: UO-preaux, aux, UO-postaux. Did I miss something?

**Comment by permcody** [comment]
Yaqi is right, we do UO, aux, then UO again which is why we don't compute
aux during UO at all.

**Comment by andrsd** [comment]
@permcody We do this since Oct 2, 2014 ;-)

Anyway, I see this problem with RELAP-7 when I do not want to run in legacy mode. Maybe I need to set our UOs explicitly with POST_AUX flag, so our auxes are properly updated...

**Comment by YaqiWang** [comment]
We really need to document this somewhere. I cannot remember which one, either auxkernel or userobject, will detect the dependency and spin UO into pre or post group. I sometimes have to add an artificial or dummy dependency to make UO run on post.

**Comment by andrsd** [comment]
I need to investigate what is going on in RELAP-7. There is some weird dependency between aux scalar vars and post processor values there. When I narrow it down, I'll report back...

**Comment by permcody** [comment]
Post is default
Pre is triggered when an aux couples to a UO

**Comment by YaqiWang** [comment]
My previous post is not accurate. I have to add the dummy dependency into an auxkernel to make a UO in the preaux group.

**Comment by permcody** [comment]
Do you have an alternative design idea?

**Comment by YaqiWang** [comment]
The situation is: aux->uo1->uo2 but no aux depends on uo2 directly. I am ok right now to make aux also depends on uo2. Not sure how hard it would be to make moose detect such a dependency. I agree this could be dangerous to moose app developers. Maybe when a uo1 is spined int preaux, we can also put its dependent uos into preaux.

**Comment by permcody** [comment]
Multilevel dependency resolution is like Fusion. It's always just a few
years off. It seems to be dropping further back on the priority list since
we have so many important priorities these days. Thanks for the reminder.

**Comment by andrsd** [comment]
So, it turned out that the reason why RELAP-7 was not converging in that one test was caused by missing dependency resolution for auxiliary scalar variables.  Changing the order of objects to the right one fixed the convergence issue...
