### ISSUE TITLE
New segfault

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#4926]
As of late last week, running bison/examples/triso_particle_2D-RZ/triso2D_accident.i results in an immediate segfault in oprof.  Other example problems still run.  In dbg,

Assertion `_active_semilocal_node_range' failed
_active_semilocal_node_range has not been created yet!
at /Users/halejd/gitProjects/test_bison/moose/framework/src/mesh/MooseMesh.C, line 679
Stack frames: 11
0: 0   libmesh_dbg.0.dylib                 0x0000000103789672 libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 82
1: 1   libmoose-dbg.0.dylib                0x00000001024d6c90 MooseMesh::getActiveSemiLocalNodeRange() + 288
2: 2   libmoose-dbg.0.dylib                0x0000000101ed8c6a DisplacedProblem::updateMesh(libMesh::NumericVector<double> const&, libMesh::NumericVector<double> const&) + 234
3: 3   libmoose-dbg.0.dylib                0x0000000101f24604 FEProblem::computeUserObjectsInternal(ExecFlagType, UserObjectWarehouse::GROUP) + 1044
4: 4   libmoose-dbg.0.dylib                0x0000000101f29a7d FEProblem::computeUserObjects(ExecFlagType, UserObjectWarehouse::GROUP) + 349
5: 5   libmoose-dbg.0.dylib                0x0000000101f0145e FEProblem::initialSetup() + 5102
6: 6   libmoose-dbg.0.dylib                0x00000001022f364c Transient::init() + 2828
7: 7   libmoose-dbg.0.dylib                0x0000000102142de0 MooseApp::executeExecutioner() + 160
8: 8   libmoose-dbg.0.dylib                0x000000010214459c MooseApp::run() + 60
9: 9   bison-dbg                           0x000000010097b546 main + 2598
10: 10  libdyld.dylib                       0x00007fff8da0b5c9 start + 1
[0] /Users/halejd/gitProjects/test_bison/moose/framework/src/mesh/MooseMesh.C, line 679, compiled Apr 12 2015 at 22:27:09

**Comment by permcody** [comment]
I suspect it's this change:
https://github.com/idaholab/moose/commit/b19c738fa044eecb2454c75b6c27b8e87c70cd8a

This change finally cleans up the initialSetup() for everyone who is not
using the legacy flags. I'll take a look at that test case and see if I can
see what's going wrong. Eventually, I'd really like to see BISON get away
from those flags. Right now nearly 40 tests fail or exodiff when turning
off the legacy flags.

Thanks for the report.

**Comment by andrsd** [comment]
I see the same issue in RELAP-7 with MOOSE c58e8e7e2e2950ddf0c67763eac568bf038f7306. When using 5503fb4, it goes away. We end up with different initial condition values on the displaced problem, but we actually have the correct values there.

**Comment by permcody** [comment]
Cool - I dare you to click merge then!

**Comment by permcody** [comment]
I double-dog dare you

**Comment by andrsd** [comment]
I meant: ...with the fix, we end up with the correct values.

**Comment by andrsd** [comment]
> I meant: ...with the fix, we end up with the correct values.

I was wrong here. The initial condition values of aux variables are not correct with this patch. However, I think the patch is still correct, we just need to sync the auxiliary variable solution vector of the displaced problem with the reference one.
