### ISSUE TITLE
A material with  hundred of bloks

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#4929]
I'm working on heat condution with moose. In heat conduciotn problem,  hundred of bloks  are consisted of one material. We must  specify block number list in parameter file by hand, as following 
```
[Materials]
  [./material]
    type = HeatConductionMaterial
    temperature = temp
    block = '0 1 2 ......'
  [../]
[]
```
It is not gentlest and fussy, espacially when the modal contains a lot of bloks! Is there more gentlest solution to deal with it,  or some suggestion ?

**Comment by permcody** [comment]
Since we currently don't support range syntax in the input file your best bet right now would be to create custom Actions to create these objects programatically. There are other tickets that have requested range syntax but it's not high enough priority for us to work on that at this time.

**Comment by lw4992** [comment]
Get it. Thanks you. 
Another way, does exodus file support block set containing some blocks? If so, is it possible to write material blcok like this?
```
[Materials]
  [./material]
    type = HeatConductionMaterial
    temperature = temp
    block_set = steel
  [../]
[]
```

**Comment by permcody** [comment]
No, however depending on what you are trying to accomplish you might
consider a different approach altogether. Instead of creating hundred of
materials you might stick to just one and make your material class handle
the mapping in some fashion instead (i.e. maybe your blocks are structured
so you can determine what material you are in based on the position in your
domain).

Cody

**Comment by YaqiWang** [comment]
Be warned that based on our experience, hundreds of blocks or even thousands in a mesh is not a good idea. Instead, you can create an auxiliary variable, which hold the material ID of all elements. Then you can create a material holding all materials and coupling this variable in. You will be able to evaluate the correct properties based on both.
