### ISSUE TITLE
ParsedAux needs a std::vector for _func_params

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#4943]
There might be a reason for not using a std::vector. I don't even see where _func_params is used in this object, is it even needed?

**Comment by dschwen** [comment]
Per our discussion, it is needed via ```FunctionParserUtils```. I'll change this to ```std::vector``` and pass ```&_func_params[0]``` as the pointer for Function Parser.

**Comment by dschwen** [comment]
Ok, I have a patch for this, but I'd like to get #4982 merged first

**Comment by permcody** [comment]
Ok - might be awhile, yak isn't working with MOOSE head so merging won't
necessarily translate to an update to Marmot

**Comment by dschwen** [comment]
I don't care about marmot. Those are all MOOSE changes.

**Comment by permcody** [comment]
"I don't care about marmot" - I guess your motivation enhancement meeting didn't go well?

**Comment by dschwen** [comment]
I'm motivated enough to reload github every 10min to check if my PR has been merged yet...
