### ISSUE TITLE
VectorOfProcessors broken in parallel

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#4945]
VectorOfPostprocessors is supposed to generate a line in the CSV file for each postprocessor, but in parallel, it generates num_procs lines for each postprocessor.  This behavior can be seen if the ```max_parallel = 1``` lines are removed from ```modules/solid_mechanics/tests/j_integral_vtest/tests```.

**Comment by permcody** [comment]
The more the merrier?? :smile:

**Comment by bwspenc** [comment]
I guess.  At least the numbers are there, just way more than I really wanted.

I'll try to look into this, by the way.

**Comment by bwspenc** [comment]
I finally got around to looking into this.  The issue isn't actually with VectorOfPostprocessors -- it's with CrackDataSampler.  I have a fix for it.
