### ISSUE TITLE
Make current node_id available in InitialConditions when possible 

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#4951]
I'm working on an IC where we need to project element information to nodal information inside of the IC. In order to do this I'm creating a data structure of node_id -> value. The problem is that the initial condition system is based on points not nodes (and therefore ids which make great map keys are not available). I think of adding a `_current_node_id` to the `InitialCondition` system would be a logical extension of the current functionality. It would set the `_current_node_id` when it was actually asking for the value at a node, and set it to `DofObject::invalid_id` when it was at some other point (when evaluating at a point within an element for a higher order shape function).

@idaholab/moose-developers feel free to comment

**Comment by andrsd** [comment]
IMO, we should expose `_current_node`, the same way we do it for `_current_elem`. We already do this in `AuxKernel`s by the way.
We do not really expose IDs anywhere in MOOSE, AFAIK...

**Comment by jwpeterson** [comment]
> IMO, we should expose _current_node,

Yeah, that is more MOOSE-like.  Where were you during the design discussion 10 minutes ago? ;0)

**Comment by permcody** [comment]
Just to be clear we'd have `Point & p` as a parameter and `Node * _current_node` as a member. That felt a little weird but it is more MOOSE-like. I'll fix that up.

**Comment by andrsd** [comment]
The parameter we have to pass in is because of the IC projection for hermite elements (they are done via  finite differencing). Also `_current_node` has sense only for nodal variables. The same way as in `AuxKernel`s: `_current_elem` for elemental ones, `_current_node` for nodal ones. We might add something like `isNodal()` which we have in `AuxKernel`s as well.
