### ISSUE TITLE
coupledScalarValue cannot be coupled with a constant

### ISSUE THREAD

**Issue by xianmingbai** [idaholab/moose#4971]
Supposedly a coupled variable can be passed with either a variable or a constant. But for coupledScalar and coupledScalarValue, I only can couple it with a scalar variable, but not a constant. 

You may add some codes to process default value for coupledScalarValue.

**Comment by permcody** [comment]
True, we can add that for you.

**Comment by permcody** [comment]
Marking as duplicate - #4762.
