### ISSUE TITLE
update_and_rebuild_libmesh.sh (c|sh)ould detect the use of ccache

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#4976]
./scripts/update_and_rebuild_libmesh.sh could easily detect if ```ccache``` is being used (per our instructions on the wiki), for example using a construct as

```
echo $CXX | cut -d ' ' -f1 | grep '^ccache$' > /dev/null
if [ $? == 0 ]; then echo ccache detected; fi
```

We could append the ```---disable-timestamps``` option to libmesh automatically in that case.

**Comment by andrsd** [comment]
:+1:

**Comment by permcody** [comment]
I guess David gives this a thumbs up. I was going to suggest a slightly less direct approach about creating yet another environment variable to just add to the list but I don't see any issues with this.

**Comment by andrsd** [comment]
With another environment variable, one would have to make sure it is in sync with current `$CXX`. Thus, inspecting `$CXX` seems like a better approach, IMO.
