### ISSUE TITLE
Output System Improvements

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5011]
A few things need improving in the Output warehouse (@permcody please edit as needed) 
1. The map wrapper stuff in AdvancedOutputUtils should use a regular map indexed with a Enum
2. At each timestep the OutputWarehouse should build vectors of output pointers for the various virtual calls that are needed, this would allow AdvancedOutput to become a bit cleaner.
3. The Petsc callbacks in PetscOutput can be moved to the OutputWarehouse so they have access to the machinery needed, mainly the screen buffer.
4. Create the output buffer in the Console object, which requires:
   1. Output object creation to be early
   2. _console will need to redirect to the various buffers depending on what is available, but this should be able to be handled via the OutputWarehouse using vectors of objects (see 2 above)

**Comment by permcody** [comment]
1. You may not even need a map at all with the refactor. You will have lists (vectors) of pointers and you'll just execute everything in the lists.

I believe everything else here sounds good.

**Comment by aeslaughter** [comment]
Probably not needed since this has been sitting for 6 years
