### ISSUE TITLE
Need InputParameters set CoupledVariables

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#5040]
In my kernel, some variables were coupled, like
```
InputParameters validParams<MultiKernel>()
{
	  InputParameters params = validParams<Kernel>();
	  params.addRequiredCoupledVar("variables", "Multi variables");
	  return params;
}
```
Now, I want to creat an action to set these coupled variables. There is seem no API in InputParameters class to do it.  I think it is an unseful feature, can guys give me some help?

**Comment by permcody** [comment]
I understand the source of your confusion, the API _is_ there but it comes from libMesh and we don't currently build our Doxygen pages with their sources available so you don't see it in the help pages. `InputParameters` inherits from `Parameters` so you can use any of the methods available there. So to set any values programmatically in your object simply use the set method:

`params.set<type>("name") = value`

The types that you use for coupled values are any of the following from MooseTypes.h:
VariableName
NonlinearVariableName
AuxVariableName

For your reference:
http://libmesh.github.io/doxygen/classlibMesh_1_1Parameters.html
