### ISSUE TITLE
scrape GitHub cloning traffic

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#5049]
Devise ways to obtain cloning traffic of our GitHub repository using a script.

**Comment by permcody** [comment]
So is this closed or are we continuing to work this ticket?

**Comment by jwpeterson** [comment]
I think it's working. The stats are currently being uploaded to:
```
http://mooseframework.org/static/media/uploads/files/github_traffic.log
```
We would just need one other script that grabs this data and makes the plots...
