### ISSUE TITLE
Skip bounding box checking in MultiAppUserObjectTransfer

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#5056]
When we want to transfer variable values from 2D heat structure (RZ) from RELAP-7 onto 3D mesh in rattlesnake, we cannot do it, since the meshes are not aligned and the bounding box check fails and no values are transferred. If the meshes are aligned in one direction, but not in others, the layered average user object gets the right data and layers and is capable of the correct transfer. However we need the ability to disable the bounding box for that case.

**Comment by friedmud** [comment]
Whoa - can you explain a little more?

**Comment by andrsd** [comment]
The ability we need is to take a temperature field from a 2D mesh (in RZ coords) and transfer it onto 3D mesh (it is not a full cylinder, but only a 1/4 of it).

The 2D mesh has no thickness (obviously, the BB reports 3 coords, but the z- one is the same) and this transfer checks whether an element/node from 3D mesh lives is this 2D bounding box. That does not really go together. So, we have 2 options:

1) RELAP-7 will report different bounding box in a way that will match the 3D one, making that check pass and ultimately transfer the values. But, I am not sure how exactly to do this. We have 1D pipes, 2D heat structures and all these might be where ever in the 3D space, so getting the BB right might be a little more involved.

2) An user option to disable the BB check, which I understand is both hacky and dangerous. I went with this, because it is sort of urgent now.

**Comment by permcody** [comment]
Instead of disabling the BB check can we make it "coordinate aware"?
Perhaps we can do the correct math in MOOSE or even at the libMesh layer to
handle the RZ -> 3D transform. This could be a very nice capability for us
in the framework.

**Comment by andrsd** [comment]
> Perhaps we can do the correct math in MOOSE or even at the libMesh layer to
> handle the RZ -> 3D transform.

RELAP-7 handles different coord systems on its own, so in MOOSE all looks like XYZ. It is because the component meshes are generated on the fly and the RZ meshes are not aligned with axis as MOOSE requires. When we have an arbitrarily positioned RZ problems, I can drop that custom RZ stuff in RELAP.

Then we will have another problem to deal with and that is, the transfer needs to some how take the bounding box from the displaced version and actually use the displaced mesh. Currently we do not have to deal with since our non-displaced mesh is at the same position as the displaced one (we only have one component for this thing).

**Comment by YaqiWang** [comment]
Can we use the find nearest node transfer? Now we just need to interpret distance as (x,y,z)->(sqrt(x*x+y*y),z) and find the closest one.

**Comment by andrsd** [comment]
That looks like a better way than the layered average UO...

**Comment by permcody** [comment]
Be careful here - while that will work from a transfer point of view, I'm
not sure if it'll work in your physics. @friedmud may need to explain as to
why this may or may not work,  but IIRC I tried using a direct field
transfer (NearestNode) for the BISON coupled flux boundary condition before
moving to a layered average. That wasn't valid because it was the same
field that I transferred "into" the subapp so there was essentially no
delta between what was going out and what was being reported as the
reference temperature in the flux calculation.

**Comment by andrsd** [comment]
@YaqiWang proposes that the nodes on a circle (in that 3D mesh) will have the same distance to the 2D (RZ) mesh. Thus the nearest node transfer will pick out the right node. The trick is in measuring the distance with a "different norm".

**Comment by YaqiWang** [comment]
Yes, that is what in my mind. And we can retain the shape of the solution on the mesh easily. The physics should be correct. But this is for our urgent need because of the requirement on the mesh. Otherwise, we will have to do cross mesh projection.

**Comment by friedmud** [comment]
I have a lot to say about this.  I've been in meetings all day so I haven't been able to respond... and I'm currently on a bus.

I'll type some stuff up tonight amand we can iterate on it.

**Comment by andrsd** [comment]
I am closing this, because we created a special transfer in mammoth for this..
