### ISSUE TITLE
AuxKernel on boundaries with elemental variable is not correctly implemented

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5061]
If an AuxKernel is boundary restrictable, and if the auxiliary variable is high-order elemental, the current implementation is problematic.

Constant monomial is ok although it also has the problem that two sides connecting the same element will cause the value of the element to be set twice. Ultimately, we need variables defined on side sets to fix this. But at least for now, we should let high-order elemental aux kernel do the evaluation correctly.

Or maybe we should forbid elemental aux kernels on boundary completely by add something in AuxKernel constructor like:

```
if ((!_var.isNodal()) && _bnd) mooseError("cannot add AuxKernel on boundary for elemental variable");
```

**Comment by friedmud** [comment]
What is it doing now?  How is it wrong?

Elemental Aux on sides is really useful... and it's used in a lot of places.  You're on thinking of your application again ;-)

**Comment by andrsd** [comment]
When we looked at it with @YaqiWang, we thought there was a problem with projecting the side values, so that the resulting local solution was incorrectly set. I looked at the code again today and it seems fine. What was it @YaqiWang that we saw was wrong?

**Comment by YaqiWang** [comment]
When the AuxKernel is on boundary, i.e. boundary restrictable, member variable `_bnd` will be true and quadrature rules on the side will be used. I am actually not quite sure what the test function will be: by looking at DGKernel `_test(_var.phiFace())`, it seems that AuxKernel is not using the test function defined on side, so it is still using the volumetric test function. But I cannot find a place where the test functions are evaluated on the side quadrature points instead of the volumetric quadrature points. If the test function was indeed evaluated on the side quadrature points, the assembled mass matrix will be rank deficient, the rank will be the number of degrees of freedom on the side, but the size will be the  number of test functions, i.e. the number of degrees of freedom on the element, so we could not do a normal solve to get the solution coefficients on element (we need to perform a pseudo-inverse). In conclusion, the coefficient evaluation in AuxKernel is problematic when it is boundary restrictable and high-order elemental.

This is separate from the definition of side variable. When two sides are connecting with the same element, we cannot use a volumetric solution vector to store the solution defined over sides.

**Comment by YaqiWang** [comment]
BTW, I just followed the libMesh svd subroutine, created a wrapper, pseudoSolve, for lapack gelss. If we decided not just throwing an error message, it could be used.

**Comment by YaqiWang** [comment]
We can warn users or error out if more than one sides are connected to the same elements on a boundary. We can ask mesh to return this information and add a check in aux kernel constructor. I think this should be a good solution for this long-standing issue.

**Comment by YaqiWang** [comment]
Multiple setting node initial values reminds me this. This needs to be fixed. It is a big framework hole in my opinion. We should throw an error if the same element is visited more  than once in a boundary restricted aux kernel. Users would know the issue and then can create more aux kernels and variables with split boundaries. This can be done at the construction time.

**Comment by lindsayad** [comment]
It seems like if we are rank-deficient that we should error? Since we are solving a rank deficient system, the solution will not be unique. @MengnanLi91 I believe this is why you are having an issue with first monomials in your boundary restricted aux
