### ISSUE TITLE
Add clobberall target

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5079]
This will make clobbering behave more like cleaning, with ```clobber``` operating from ```$(CURDIR)``` and ```clobberall``` iterating over all dependent app dirs.

**Comment by jwpeterson** [comment]
BTW, @dschwen reports that the speed of make clobber is nearly doubled by not making the `-exec rm` system calls...

-delete:
```
real        0m10.515s
```

-exec rm:
```
real        0m18.253s
```
