### ISSUE TITLE
ExpressionBuilder EBTerm constructor should take a std::string

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5096]
and not a `char *`. Assign to me.

**Comment by dschwen** [comment]
Ugh, I pretty much cannot do that because it creates ambiguous conversion paths. I could fix this using the ```explicit``` keyword, but that is a C++11 extension.

**Comment by jwpeterson** [comment]
On Thu, May 21, 2015 at 10:10 AM, Daniel Schwen <notifications@github.com>
wrote:

> Ugh, I pretty much cannot do that because it creates ambiguous conversion
> paths. I could fix this using the explicit keyword, but that is a C++11
> extension.
>
Really?  I thought explicit keyword has been around for a while, at least
as far as constructors are concerned.  We have a bunch of them in libmesh.

-- 
John

**Comment by dschwen** [comment]
Not for cast operators (conversion functions)!

**Comment by jwpeterson** [comment]
Thought you were talking about
```
EBTerm(const char *symbol) : root(new EBSymbolNode(symbol)) {}
```

**Comment by dschwen** [comment]
Yes, I am. Just look at e43fe60.

**Comment by jwpeterson** [comment]
I saw e43fe60.  All I am saying is that you can mark that constructor explicit in C++03.

**Comment by dschwen** [comment]
The issue is that EBFunction can be cast into an EBTerm two different ways:

1) EBFunction -> std::string -> EBTerm(std::string) ctor
2) EBFunction::operator EBTerm(EBFunction)
