### ISSUE TITLE
Receiver default value 

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5106]
Currently, the current value of postprocessor `Receiver` is set by its default parameter. But the old and older values are not set. Users could accidentally use them, which could contain uninitialized values. Should we set the default value for all of the three copies?

**Comment by YaqiWang** [comment]
Just realized there is no older value for postprocessors. How come we do not have it?

**Comment by andrsd** [comment]
No body asked for it until now ;-)
