### ISSUE TITLE
Create a new method to copy postprocessor data backward

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5111]
I am thinking maybe we should do this in FEProblem:
```
for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _pps_data[tid]->copyValuesBack();
```
This is something like copySolutionBackward().

The reason why I came up with this thinking is because that in a Yak executioner, I need to do it and solution copy without calling all other stuff in `FEProblem::advanceState()`, otherwise I will have to set old postprocessor values in several places.

Overall, I think this is a reasonable request.

**Comment by aeslaughter** [comment]
This should be trival to implement, we just need to wrap this in a public
function.

```
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
    _pps_data[tid]->copyValuesBack();
```

If @permcody is alright with this, I will add it tomorrow.

**Comment by permcody** [comment]
Wrapping this in a public function is not a good idea. For one you can't
call this from a parallel region which eliminates most user code. Secondly
we need to make sure that copying solutions back doesn't create other
unwanted side effects in the state of FEProblem.

Yes, I do want to hear more from Yaqi about the usage but the availability
of this function should be properly protected and limited if we decide it's
the right path forward.

Cody

**Comment by YaqiWang** [comment]
I looked into `advanceState()` one more time. I think the only thing I do not quite like there is
```
for (THREAD_ID tid = 0; tid < libMesh::n_threads(); ++tid)
    _materials[tid].timestepSetup();
```
In my executioner, I am doing some iteration using the old values. I do not want to call any timestep related stuff. Maybe we can separate it out into `FEProblem::timestepSetup()`? Then I can use `advanceState()`.

But keep in mind though, `FEProblem` has `copySolutionBackwards()`, which is against @permcody 's argument.

**Comment by aeslaughter** [comment]
I thought about that parallel stuff after I said it would be easy, perhaps
we do this in the Executioner itself.

**Comment by friedmud** [comment]
Uncovering this method is not the right idea.

@YaqiWang I'm not criticizing... I honestly want to know: can you explain a little more why you can't have timestepSetup() called at the time where you're advancing the state?

You might very well be correct and we should remove that from advanceState()

**Comment by permcody** [comment]
I would vote that we fix up the advaceState() call we should probably be calling timestepSetup along with all the other timestepSetup methods at the beginning of the timestep. I haven't talked to Yaqi yet, but I'm going to guess that he has a need to advance state during his power iterations.

**Comment by friedmud** [comment]
Yeah: that's my vote too until we get more information.

We need people to be calling `advanceState()` and not the stuff `advanceState()` calls... that method does change as we add new systems to the code which would cause subtle bugs if people weren't calling `advanceState()`....

**Comment by YaqiWang** [comment]
I have a iteration in an executioner, which is doing source iteration (lagging scattering source one iteration behind, guaranteed converge although could be slow when scattering ratio is close to one). In this iteration, we need to copy the solution backwards. But I do not want to have any timestep related operations. They could potentially create some undesired effect, for instance when doing source iteration at every time step in a transient. We have seen this kind of side effect in our depletion executioner where power iteration could be wrapped.

**Comment by permcody** [comment]
@YaqiWang - I'm going to remove the `timestepSetup` from `advanceState`. You said that will solve your problem. I'll test against the apps to see if there are any issues.
