### ISSUE TITLE
SolutionFunction to transfer from 2D axisymmetric to 3D cartesian models

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#5120]
We need the ability to transfer scalar and vector fields from another model in the way that SolutionFunction works, but from a 2D axisymmetric model to a 3D model.

I've developed the code for this, and will submit a pull request shortly.

**Comment by permcody** [comment]
Wow nice, We should probably make a transfer out of this so it can be done in a MultiApp simulation.

**Comment by bwspenc** [comment]
@permcody I was thinking the same thing about a transfer.  My immediate need was for a SolutionFunction, but it should be pretty easy to make a transfer based on this.
