### ISSUE TITLE
Tolerate Failure

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5126]
The MultiApp system needs to be more resilient to solve failure.  Right now it can really only deal with failure if everything is moving together.  In the case of Subcycling or Picard any failure completely messes up the system.

I propose a new system that piggybacks on the capabilities of the Restart/Recover system.  I'm calling it "Backup" and "Restore".  This system will be able to take snapshots ("Backups") of the complete system _in memory_ (meaning no files are written) during the solve.  In the case of failure those "Backups" can be "Restored" so the solve can be restarted with different parameters (for instance, a smaller timestep).

This will work using the current "stream saving" capability of the Restart/Recovery system... but instead of saving to files it's going to save to an in memory buffer.

This is going to get incredibly complicated with arbitrary levels of MultiApps using different amounts of Picard/Subcycling.  Imagine this case:

Normal->Picard->Subcycling->Picard

Backups will need to get saved at all levels that represent the entire state of the tree below that node.

To handle this, this capability is going to go right into the `MooseApp` itself.  A `MooseApp` will have a method on it called `backup()`.  That method will return a pointer to a `Backup` object that is a complete self-contained snapshot of the `MooseApp`... including _all_ sub-apps (ie - it will include a serialized `Backup` object for each sub-app under the `MooseApp`).

Then a `MooseApp` will also have a `restore()` method as well... that takes a pointer to a `Backup` object and restores its state.

In this way a `MultiApp` object that is managing multiple `MooseApp` instances can actually backup... execute... destroy... rebuild... restore...

We'll see...

**Comment by permcody** [comment]
closed by #5140
