### ISSUE TITLE
Don't add excessive zeros for coupling entries for MechanicalContactConstraint

### ISSUE THREAD

**Issue by shanestafford** [idaholab/moose#5134]
Now that the PETSc bug is fixed, we can reduce memory by skipping findImplicitGeometryCouplingEntries for MechanicalContactConstraint. Once this is done, using patch_update_strategy=auto on big memory runs should give great results without crashes.

This is a one line change in MechanicalContactConstraint, but it needs to wait until petsc-3.5.4 is being used by the BISON cases (which should happen in the next few days).

**Comment by shanestafford** [comment]
@bwspenc and @friedmud I think we decided to not skip findImplicitGeometricCouplingEntries, but to instead try to be smarter about it. Also, we are already using patch_update_strategy=auto with the newer PETSc and it works great.

So I'm closing this until we come up with a (possibly long-term) plan to reduce the predicted nonzero entries, if we ever end up needing to reduce memory more aggressively than the auto patch strategy already provides.

**Comment by friedmud** [comment]
Thanks for the update @shanestafford !  Glad to hear that it's currently working for you!
