### ISSUE TITLE
Type property is always empty in the YAML dump and class descriptions are not dumped

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5135]
When running any moose app with the ```---yaml``` switch the resulting syntax tree has a type property in each node that is always empty (```SyntaxTree::TreeNode::print``` never fills in the ```type``` variable and always passes an empty string to ```YAMLFormatter::printBlockOpen```).
Is the YAML formatter used for any other purpose? It does not look like ```YAMLFormatter::printBlockOpen``` is called from any other place. I wonder if we can just remove the ```type:``` line from the YAML output.
Furthermore only parameter descriptions are dumped in the yaml. For class level YAML blocks the description field is always empty, even if ```addClassDescription``` was used to provide a class description.

**Comment by permcody** [comment]
Yaml is only used for Peacock. If you find a bug that when fixed, doesn't
break peacock, feel free to submit a PR if you have time. Otherwise one of
us will get to it.

Cody

**Comment by friedmud** [comment]
Personally... I would rather remove YAML and just output JSON.  Would make it infinitely easier to parse...

**Comment by dschwen** [comment]
I'd be fine with that solution, even though there are yaml modules for node.js which make parsing the syntax data very easy from Atom :-).
90d32a1 is an attempt to fix the YAML issues in the mean time. I will test this more thoroughly with peacock.
