### ISSUE TITLE
Create a SharedMeshMultiApp

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5147]
- Create a MultiApp that uses the Mesh from the master
- Remove coupled problem, as this will replace the need

**Comment by YaqiWang** [comment]
Hopefully I can borrow the same idea for the application wrapper in yak used by NDA. Duplicating mesh is silly when it is absolutely unnecessary.

**Comment by permcody** [comment]
@aeslaughter - I don't think we are going to implement this ticket as described. I believe you found a workaround for your needs. Can this be closed?

**Comment by aeslaughter** [comment]
Yes, sharing the mesh was not possible as far as I can tell. I was able to transfer marker information and get the concept working.
