### ISSUE TITLE
FDP and PBP tests are not converging in a single iteration

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5153]
The FDB and PBP Precondition tests do not converge in a single iteration. Our current tests erroneously miss the fact that the final solution is not fully converged when they exit due to a missing error message.

**Comment by fdkong** [comment]
@permcody, why FDP and PBP are supposed to converge within one iteration? I do not understand this. Could you explain more?

**Comment by permcody** [comment]
I honestly don't remember why I said this. I think what I was thinking was that it should converge in a single nonlinear iteration due to the fact that the problem was very simple and the preconditioner was very good. However, it just wasn't and worse, it was actually failing prior to the fix I merged in here from another developer. I'm OK with removing or updating this ticket as appropriate. What does the convergence look like now?
