### ISSUE TITLE
Boundary points list  is corret when reading curved mesh from gmsh?

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#5169]
A second-order curved mesh of cylinder generated by gmsh looks like 

![1](https://cloud.githubusercontent.com/assets/7278509/7963788/123f1138-0a47-11e5-9271-9d407eaf1bdc.png)

Then I read it to moose using `--mesh-only`, the output exodus mesh became 
![2](https://cloud.githubusercontent.com/assets/7278509/7963773/ff597b62-0a46-11e5-93ef-44d0d0fd6354.png)

It seems like boundary points did NOT match original gmsh be. Is it correct? Is it possible that mistaking the order of boudary points(EDGE3)?

**Comment by jwpeterson** [comment]
On Wed, Jun 3, 2015 at 9:32 AM, LIU Wei <notifications@github.com> wrote:

> A second-order curved mesh of cylinder generated by gmsh looks like
>
> [image: 1]
> <https://cloud.githubusercontent.com/assets/7278509/7963788/123f1138-0a47-11e5-9271-9d407eaf1bdc.png>
>
> Then I read it to moose using --mesh-only, the output exodus mesh became
> [image: 2]
> <https://cloud.githubusercontent.com/assets/7278509/7963773/ff597b62-0a46-11e5-93ef-44d0d0fd6354.png>
>
> It seems like boundary points did NOT match original gmsh be. Is it
> correct? Is it possible that mistaking the order of boudary points(EDGE3)?
>



Looks like this could be a bug in the Gmsh reader for EDGE3 elements.
Please send me (jwpeterson@gmail.com) your mesh file directly or share it
as a google doc.

--
John

**Comment by lw4992** [comment]
The mesh file has sent to you, please check it.

**Comment by jwpeterson** [comment]
Looks like we assume an identity mapping between libmesh and gmsh's node numbering in the `EDGE3`, which is consistent with [Section 9.3.1 of the gmsh docs](http://geuz.org/gmsh/doc/texinfo/gmsh.html) so there must be some other issue...  I'll look further into it.

**Comment by jwpeterson** [comment]
What program are you using to display the meshes?  

Note that paraview seems to have an issue with displaying curved boundary sets correctly independently of Gmsh.  For example, on [this mesh](https://drive.google.com/file/d/0B9BK7pg8se_iMld6SEpSMjhYVHc/view?usp=sharing), paraview displays the curved boundarie sets [like this](https://drive.google.com/file/d/0B9BK7pg8se_iZEtKT0VHS2t6X1U/view?usp=sharing), even though I know they are correct within MOOSE.

**Comment by lw4992** [comment]
I used Ensight 10.1 to display the mesh, previously. Now, paraview's results of the same curve mesh as follows:
![1](https://cloud.githubusercontent.com/assets/7278509/8037910/f9f08018-0e32-11e5-8776-6d8f9848dbc3.png)

![2](https://cloud.githubusercontent.com/assets/7278509/8037885/dfa5f788-0e32-11e5-8f82-8fdcc576cfb5.png)

They are same with yours.
Next, I would run some case on the assumption that the curved mesh is correct, then, check the  solution is right or not.

**Comment by jwpeterson** [comment]
> Next, I would run some case on the assumption that the curved mesh is correct, then, check the solution is right or not.

OK, thanks for following up.

**Comment by jwpeterson** [comment]
Pretty sure this was a problem with Ensight, please re-open if there is a problem with MOOSE's gmsh reader.
