### ISSUE TITLE
Time/Step average Postprocessor

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5183]
I need a Postprocessor that returns a running average of a slave Postprocessor. I'm implementing a simple average over the last n steps as well as a timestep weighted average over a time window.
Assign to me.

**Comment by permcody** [comment]
What the heck happened to this? Looks like you indeed implemented it but never opened a PR? Is this something you still want, or should we close.

**Comment by dschwen** [comment]
Oh, let me check...

**Comment by dschwen** [comment]
Should have been closed by #9871
