### ISSUE TITLE
Moose compiling warnings

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5190]
An annoying warnings has been recently created:
xxxxxx/moose/framework/include/base/FEProblem.h:87:45: warning: comma at end of enumerator list [-Wpedantic]
   MOOSE_DIVERGED_NULL                   = -2,

**Comment by permcody** [comment]
@jwpeterson do you think you may need to change the reason list? Is that why you commented out and instead of removed?

**Comment by jwpeterson** [comment]
Not sure, that part was from @friedmud's original patch and I didn't look at it that closely.
