### ISSUE TITLE
Multiphase barrier function with cross terms (phase_field)

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5192]
For additional flexibility we will need a version of `MultiBarrierFunctionMaterial` that allows to specify barrier heights _W_ for each phase transition.
I suggest the material to be named `CrossTermBarrierFunctionMaterial`. MBFM is a good place to start. The `_prop_dg2` property will have to be a vector of vectors, the Simple form would be something like

```
sum_i( sum_j W_ij * n_i^2*n_j^2 )) with i>j
```

We should probably limit the user to supplying an upper triagonal matrix without the diagonal.
@jbair34 needs this and should probably implement this.

**Comment by permcody** [comment]
Ticket was implemented and merged in #5457.
