### ISSUE TITLE
Use addClassDescription for all our user facing classes

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5195]
We should more consistently use `addClassDescription` in our `validParams` functions. The class descriptions are now dumped out in the YAML data and will be used in the atom autocomplete plugin (and potentially in peacock).
I was surprised how few classes actually use this self-documentation feature.

Ping @cpritam, @tonkmr

**Comment by dschwen** [comment]
First batch. Should probably get reviewed by the class authors to check if the descriptions make sense.

**Comment by friedmud** [comment]
I agree with this... BUT... I always wanted to be able to put Latex in these descriptions (it would go perfectly with the idea that many of the classes represent mathematical operators).

What do you think about that?

On the website we can use MathJax to render these... can you do the same in Atom?  I thought a while ago about a way I could get Latex to render in Peacock as well...

**Comment by dschwen** [comment]
Yeah, I thought about this. As a first iteration we could present the raw
latex source (equations enclosed in $ pairs). MathJax should be possible
(atom is built on chrome) if the autocomplete system let's me return a dom
element as a description. I'll look into it.

**Comment by permcody** [comment]
We are actively doing this in our push to get documentation into the system and the transition to Moose Docs. This ticket is old and nobody is referencing it anymore. We are handling these enhancement by enforcing that documentation passes on new classes.
