### ISSUE TITLE
Add Postprocessor to output a MooseFunction value

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5197]
It would would nice to have a Postprocessor to output a MooseFunction value. This would ignore the fact that MooseFunctions can have a spatial dependence, but it would be useful for function that only depend on time or other Postprocessors. The latter would allow us to combine Postprocessor values in a flexible way (rather than implement more postprocessors like ```DifferencePostprocessor```).

@jhbradley might want to take a stab at that

**Comment by friedmud** [comment]
:+1:

**Comment by permcody** [comment]
Resolved then existing postprocess was later removed.
