### ISSUE TITLE
CrystalPlasticityRotationOutAux should be an output object

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5200]
`CrystalPlasticityRotationOutAux` is an AuxKernel that writes to a file in `computeValue` (computes no value). This looks like system-abuse to me ;-) @cpritam. @aeslaughter, it outputs a _text file_ with a full `RankTwoTensor` for every qp. Is there a more MOOSEy way to do this? This looks like a debug hack. Is it still needed?

**Comment by permcody** [comment]
Yuck... I vote that we remove this object. I'm happy to put the PR in to do that.

**Comment by aeslaughter** [comment]
I vote for removal.

**Comment by cpritam** [comment]
Me too. It was a rather dirty way to do some verification of the code. Had a discussion with Daniel to modify it but never happened.

**Comment by sapitts** [comment]
Is there a way that we could keep this functionality for a (mesh) block and run it only once at the start of the simulation?  It's nice to be able to double check my Euler Angles, but I do run the simulation for one timestep and then kill the simulation and comment out the rotation aux objects before running the simulation for real

**Comment by aeslaughter** [comment]
@sapitts Can you use: MaterialVectorPostprocessor

**Comment by sapitts** [comment]
@aeslaughter MaterialVectorPostprocessor is only for Reals, correct?  But in any case I can get this same information with RankTwoAux on `update_rot`; nevermind me!

**Comment by dschwen** [comment]
Yikes, that thing is still there. It at the very least needs checks that deal with threading and MPI!

**Comment by dschwen** [comment]
We have automatic material property output for `RankTwoTensor` now. I'm making aPR to remove this thing.
