### ISSUE TITLE
Plasticity uses string to MooseEnum comparisons in time critical places

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5211]
@WilkAndy I can fix this. MooseEnums should be compared using their integer index values instead. This is very noticeable in a profiling run.

**Comment by WilkAndy** [comment]
oh, thanks.  It's something i wasn't aware of.  Could you include me on the PR so i can learn for the future?

a

**Comment by dschwen** [comment]
In a hardening test simulation this results in a 10% speedup. Code readability is not impacted!

**Comment by WilkAndy** [comment]
Holy dooley, 10% is absolutely crazy.  i would have thought all the complicated return-map stuff would take "infinitely" longer than a string comparison.  Thanks heaps, @dschwen .

a
