### ISSUE TITLE
Allow MultiMooseEnums to be constructed from MooseEnums

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5214]
A few classes in MOOSE provide static methods to get ```MooseEnum``` values for constructing input parameter sets. I have a case where I want to allow users to provide a vector of such ```MooseEnum```s, and for that I need to be able to construct a ```MultiMooseEnum``` from the result returned by said static functions.

Assign to me.

**Comment by permcody** [comment]
While I don't have any problem with you adding a new constructor, would it be easier to just return the MultiMooseEnum from the static method directly? We do this in `SetupInterface` for instance.

**Comment by dschwen** [comment]
Not really. Such an enum is for example the fill method for a single ```RankFourTensor``` this is conceptually a single value. Only in special classes need to build arrays of tensors we need to be able to construct a ```MultiMooseEnum```.
