### ISSUE TITLE
Executioner Refactor

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5229]
Time to refactor the `Executioner` system.  We currently have 3 main branches of Executioners:  Steady, Transient and Eigenvalue.  We need to try to unify their needs and consolidate a lot of code to help us with coupling Apps.

After some discussion with the team and with @YaqiWang we are going to pursue a main execution loop that looks like:

```
for steps:
  for cycle:
    for picard:
      for stage:
        doStuff()
```

By mixing and matching differing amounts of iterations during each phase most (all?!) of our different needs for `Executioners` will be satisfied.

Here is an explanation of each phase:
- steps: The main "step" through the simulation.  In `Transient` this is a time step.  In `Steady` there will only be one step.  A steady state Eigenvalue solve will only have one step, while a transient Eigenvalue solve will have multiple.
- cycle: Mainly used for mesh adaptivity cycles.  The `Steady` executioner will use this for multiple solve->adapt->solve->adapt cycles.  This can also be used in `Transient` Executioner to allow for multiple solve->adapt cycles per timestep (something we've never been able to do before)
- picard: Used for Picard iteration... mainly for use with MultiApps
- stage: In an Eigenvalue solve this might be power iterations.  Also useful in high order time integration.

At the beginning of each phase there will be a virtual function call for `begin*()`  (where `*` is Cycle, Picard, etc.) and an equivalent `end*()` at the end of each phase.

The beginning of a Step will automatically do a `backup()` ( #5126 ) when any of cycle, picard or stage are going to have more than one iteration.  That will allow complete recovery using `restore()` in the event of failure (and help with Picard iteration).  For now, that capability will be turned off with mesh adaptivity until the Backup system works properly.

Here are a few cases highlighting how the new system will work:
- pure steady: All of the phases will only have _1_ iteration
- steady with adaptivity: n iterations for cycles, _1_ for everything else
- transient: n iterations for steps, _1_ for everything else
- eigenvalue: n iterations for stages, _1_ for everything else
- transient eigenvalue: n iterations for stages, m iterations for steps, _1_ for everything else
- transient eigenvalue picard: n iterations for stages, m iterations for steps, p iterations for picard, 1 cycle

**Comment by friedmud** [comment]
I'm marking things with `ExecutionerTODO` as I go so I can remember to come back and fix things...

**Comment by friedmud** [comment]
After more discussion with @permcody ....

We need to add `EXECUTE_*_BEGIN` and `EXECUTE_*_END` for each phase.

Also... we are going to use new exceptions to be able to bail out of all of the loops at once.

**Comment by smharper** [comment]
What about a scheme more like this,
```
while(_solve_not_finished)
  beforeSolve();
  Solve();
  afterSolve();
```
where `beforeSolve()` sets variables to tell `Solve` whether it is entering a new step, cycle, etc.  I think that approach would be a lot more flexible.  One advantage of this scheme is that you can effectively have an arbitrarily deep nested layer of loops.  A related advantage to that is that simple solves like pure steady-state solves don't need to have all of those loops you show above.

It would also give you the freedom to add more loops and change their size on the fly.  For example, maybe you want to code a system that normally runs a simple transient solve but then sometimes adds a loop for eigenvalue if certain conditions are met.  Or maybe you are running a transient solve that usually uses backward-Euler, but then switches to RK4 for some time steps.

Of course, the downside to this is that `beforeSolve()`, `Solve()`, and `afterSolve()` would probably be big subprograms with a lot of logic in them.  But that has it's advantages as well.  I bet that some random scientist trying to learn MOOSE and make their own executioner for a complex problem would spend a lot of time trying to figure out if their various computations fit into `stages` vs. `cycles`, and in which step their multiapp is called, etc.  And then maybe they'll decide they really need another loop, and they'll hack it into that structure in some awful way.  With that simple structure I showed, I think they could worry less about how to make their code fit, and more about their physics.

What do you think?  Would it be too difficult to make MOOSE work with such a loose structure?

**Comment by friedmud** [comment]
@smharper thats essentially what we have now... and it's a damn mess.  Way too much code duplication across all of the various Executioners... And a nightmare to update every time we make an internal API change to MOOSE.  Not too mention things like ensuring that recover works properly and that all other systems like TimeIntegrators and TimeSteppers are integrated properly with every Execution.

No, looseness like this has put us in a damn mess.  The way out is more rigor.

I already have this going and it is looking good.

**Comment by friedmud** [comment]
Don't forget all of the craziness about execute_on and output_on.  Ensuring that works properly with every executioner out there is a damn nightmare with the current system.

**Comment by aeslaughter** [comment]
@friedmud I was thinking about this over the weekend and wanted to share my vision for this re-factor, although I think what you were doing is the same. The main think I want to be able to do is answer the question: "Where is EXEC_TIMESTEP_BEGIN"? The answer being a virtual function on the executioner.


```
class ExecutionerBase
{
public:
  ExecutionerBase();


  virtual void run();

protected:

  virtual void stepBegin() = 0;
  virtual void stepEnd() = 0;
  virtual bool stepComplete() = 0;

  virtual void cycleBegin() = 0;
  virtual void cycleEnd() = 0;
  virtual bool cycleComplete() = 0;


  virtual void picardBegin() = 0;
  virtual void picardEnd() = 0;
  virtual bool picardComplete() = 0;

  virtual void stageBegin() = 0;
  virtual void stageEnd() = 0;
  virtual void stageComplete() = 0;

  virtual void solve() = 0;

  ExecFlagType _current_execute_flag;
};

ExecutionerBase::run()
{
  // Run all initial setup functions
  _problem->initialSetup();

  while (!stepComplete())
  {
    _current_execute_flag = EXEC_STEP_BEGIN;
    stepBegin();

    while (!cycleComplete())
    {
      _current_execute_flag = EXEC_CYCLE_BEGIN;
      cycleBegin();

      while (!picardComplete())
      {
        _current_execute_flag = EXEC_PICARD_BEGIN;
        picardBegin();

        while (!stageComplete())
        {
          _current_execute_flag = EXEC_STAGE_BEGIN;
          stageBegin();

          solve();

          _current_execute_flag = EXEC_STAGE_END;
          stageEnd();
        }

        _current_execute_flag = EXEC_PICARD_END;
        picaredEnd();
      }

      _current_execute_flag = EXEC_CYCLE_END;
      cycleEnd();
      }

    _current_execute_flag = EXEC_STEP_END;
    stepEnd();
  }
}



// TRANSIENT EXECUTIONER
class Transient : public ExecutionerBase
{
public:
  Transient();


protected:

  virtual void setup(const ExecFlagType & flag);
  virtual void execute(const ExecFlagType & flag);


  /**
   * All of the begin/end methods look like this.
   */
  virtual void stepBegin()
  {
    setup(EXEC_STEP_BEGIN);
    execute(EXEC_STEP_BEGIN);
  }

  /**
   * Also do all the necessary stuff in the complete methods to keep the loop running
   */
  virtual void stepComplete(){ // Do right stuff here. }

};


Transient::setup(const ExecFlagType & flag)
{
  _problem.setupUserObjects(flag, PRE_AUX);

  _problem.setupAuxKernels(flag);

  // ... Go through all systems
}


Transient::execute(const ExecFlagType & flag)
{
  _problem.computeUserObjects(flag, PRE_AUX);

  _problem.computeAuxKernels(flag);

  // ... Go through all systems
}
```

**Comment by friedmud** [comment]
Yeah: that's similar to where I was headed.  The issue is that millions of things will diff when you do this.  It's fixable... but it's daunting.  There are tiny little dependencies that have crept in over the years that scream and shout when you try to change this.

**Comment by rwcarlsen** [comment]
What about something like this:

```c++
#include <map>
#include <vector>
#include <string>

#define EXEC_LEV(name) addLevelBegin(#name, [this]{return name##Begin();}); \
                       addLevelEnd(#name, [this]{return name##End();});

class Exeker {
 public: 
  Exeker() : _curr_level(0) {};

  typedef std::function< bool() > LevelFunc;

  void addLevelBegin(std::string name, LevelFunc begin) {
    createLevel(name);
    _begin_funcs[_level_index[name]] = begin;
  }

  void addLevelEnd(std::string name, LevelFunc end) {
    createLevel(name);
    _end_funcs[_level_index[name]] = end;
  }

  void run() {
    execLevel(0);
  }

  int iter(int level) {
    return _level_counts[level];
  }

  int iter() {
    return _level_counts[_curr_level];
  }

 private:
  void createLevel(std::string name) {
    if (_level_index.count(name) > 0) {
      return;
    }
    int i = _level_names.size();
    _level_names.push_back(name);
    _level_counts.push_back(0);
    _level_index[name] = i;
    _begin_funcs.push_back([]{return false;});
    _end_funcs.push_back([]{return false;});
  }

  void execLevel(int level) {
    if (level >= _level_names.size()) {
      return;
    }
    _curr_level = level;

    bool done = false;
    while (!done) {
      _level_counts[level]++;
      done = _begin_funcs[level]() || done;
      execLevel(level + 1);
      _curr_level = level;
      done = _end_funcs[level]() || done;
    }

    // reset level counts
    for (int i = level; i < _level_counts.size(); i++) {
      _level_counts[i] = 0;
    }
  }

  int _curr_level;
  std::vector<int> _level_counts;
  std::map<std::string, int> _level_index;
  std::vector<std::string> _level_names;
  std::vector<LevelFunc> _begin_funcs;
  std::vector<LevelFunc> _end_funcs;
};

```

For arbitrary custom-named levels of nesting.  Used something like this:

```c++

#include <iostream>

#include "exeker.h"

class MyExeker: public Exeker {
 public:
  int foo_max;
  int bar_max;

  MyExeker() {
    EXEC_LEV(foo);
    EXEC_LEV(bar);
  }

 private:
  bool fooBegin() {
    std::cout << "foo "<< iter() << " begin\n";
    return iter() >= foo_max;
  };

  bool fooEnd() {
    std::cout << "foo end\n";
    return false;
  };

  bool barBegin() {
    std::cout << "   bar " << iter() << " begin\n";
    return iter() >= bar_max;
  };

  bool barEnd() {
    std::cout << "   bar end\n";
    return false;
  };
};

int main(int argc, char** argv) {
  MyExeker exec;
  exec.foo_max = 3;
  exec.bar_max = 2;
  exec.run();
  
  return 0;
}
```

- just an idea.

**Comment by friedmud** [comment]
Hmmmm....

In general we try to avoid using Macros.  They are fairly non-obvious to
non-experts... and debugging can be tricky.

That said, Executioners are definitely a more "expert" system anyway.

I'll have to think about it some more.

**Comment by rwcarlsen** [comment]
Macros aren't really necessary here, they just hide a bit of simple lambda
stuff.

**Comment by friedmud** [comment]
What about just going to a full object-oriented structure?  Something like having an `ExecutionerLoop` class... with virtual functions allowing you to override what happens at the beginning/end of the loop... and then make it so that you can compose multiple loop objects.  That way an application can mix and match the loops they want and the order they want them in?

That way we could have several "built-in" types of loops (Picard, Eigen, AdaptiveCycles, TimeSteps, etc.) and applications can pick and choose which ones they want... and the order they want them in.

BTW: You are right about the macros.  I apologize for zeroing in on that.  I was looking at it on my phone and misunderstood what was up.

**Comment by aeslaughter** [comment]
@friedmud That is an interesting idea, you could then add/remove/re-order loops in the input file.

```
[Executioner]
   type = Transient
   loops = 'picard eigen adaptive'
[../]

**Comment by friedmud** [comment]
Yep.

**Comment by rwcarlsen** [comment]
What degree/sort of communication will/should be necessary between loop iterations (other than iteration count(s) and being able to break out of loops early)?

**Comment by rwcarlsen** [comment]
#6925 and #6913 have some valuable info/discussion related to this.

**Comment by rwcarlsen** [comment]
#3487 has some relevant discussion to this.

**Comment by lindsayad** [comment]
closing in favor of https://github.com/idaholab/moose/issues/20123 and https://github.com/idaholab/moose/issues/18180
