### ISSUE TITLE
Remove FunctionValuePostprocessor

### ISSUE THREAD

**Issue by jhbradley** [idaholab/moose#5248]
Well this is embarrassing (sorry for the extra work guys)! The postprocessor PlotFunction, written before FunctionValuePostprocessor, is its equivalent. FunctionValuePostprocessor can therefore be removed.

**Comment by dschwen** [comment]
I don't like the name ```PlotFunction```. That postprocessor does not plot anything. It outputs function values. Looking at the documentation it obviously predates the capability to use postprocessor values in parsed functions. If we remove ```FunctionValuePostprocessor``` I suggest we rename ```PlotFunction``` to ```FunctionValuePostprocessor``` (and keep PlotFunctiona s a deprecated registration).
```PlotFunction``` allows the user to specify a point in space, which can be handy, though.

**Comment by friedmud** [comment]
I _knew_ that we already had this... but even I couldn't find it when I merged that PR!  PlotFunction is definitely non-obvious.  I vote for keeping the new name... but merging over capability from the old object.

**Comment by permcody** [comment]
closed by #5573
