### ISSUE TITLE
Strange interactions with MOOSE console output and less

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#5254]
I've been using 'less' for a very long time to follow the console output from MOOSE and other codes.  I typically do this:

modules-opt -i myfile.i > out&
less out

Within less, I then follow the output by typing 'F'.  It works kind of like 'tail -f', except that you can ctrl-C and get out of the follow mode, and then go through the rest of the file.  It even interprets the color control characters when run with the -R option.

Recently, when doing this, less has started behaving very erratically when following a MOOSE output file when the job finishes. Tons of strange characters flash on the screen, sometimes causing strange behavior of the terminal program depending on what is used.  Has the console output stream been modified to include special control characters at the end of the run that may be causing this behavior?

**Comment by permcody** [comment]
I tried this in MOOSE test and it worked ok. I can't think of anything that
we've done to cause this but it should be easy enough to figure out, we'll
just need to look at your file in a hex editor to see what other ascii
codes are in there besides the EOL and/or EOF characters. Is this only
happening in BISON or Grizzly?

**Comment by bwspenc** [comment]
I've seen it on several models, but I guess they were all BISON.  I'll see if I can replicate this on a MOOSE run.

**Comment by friedmud** [comment]
Were you doing something with MultiApps?  Because the "Waiting for other processors to finish" line uses some funky control characters to do an in-place update of the number of processors that are still working....

**Comment by permcody** [comment]
Not that funky, we use the standard ASCII "carriage return" character
instead of "line feed" but we see those in Windows files all the time
without too much trouble.

**Comment by friedmud** [comment]
You really want to debate the use of the word "funky"?  If you're piping the stream to a file (or to less or whatever) then it doesn't matter exactly _what_ character it is... it's going to create a mess!  :smile:

**Comment by bwspenc** [comment]
This is just a standard run, no multiapps.
What's wrong with piping the output stream to a file? I'm not aware of an alternative.

**Comment by bwspenc** [comment]
I just did a little more investigation.  I hit this issue with MOOSE or BISON jobs, but I have to be running them in parallel, so it's likely something related to mpich.  I'm on Mavericks and running mpich-3.1.4.  If I run less in a different terminal, no problem.  If I redirect the error stream to another file and run , also no problem:
```
mpiexec -n 2 ~/gitproj/githerd/moose/modules/combined/modules-opt -i single_point_2d.i > out 2> err&
```
This makes me think that mpich must be sending something to the error stream that's messing with less, but the err file is empty.  Anyway, this seems to be an mpich issue rather than a MOOSE issue.

**Comment by permcody** [comment]
Something still seems fishy. Redirecting to stderr makes this not fail but
that file is empty (zero bytes)? I'll see if I can repeat.

**Comment by mangerij** [comment]
We also have a similar issue on our cluster except that the strange symbol shows up as an ESC in the console output. 

If you think it has something to do with mpich; we have this issue with mvapich2/2.0a-ics-slurm. An also a previous version --mpich/3.0.4-ics (i think) gave something a little different where instead of the ESC , it looked like  

0 Nonlinear |R| = [32m1.197130e-08[39m
      0 Linear |R| = [32m1.197130e-08[39m
    0 KSP Residual norm 1.197129773925e-08 
      1 Linear |R| = [32m7.594908e-09[39m

and so on for the output file. 

![screenshot from 2015-07-16 12 02 52](https://cloud.githubusercontent.com/assets/7597716/8729873/4fa1670a-2bb3-11e5-9ba7-c27003fedb7e.png)

**Comment by permcody** [comment]
Those are normal terminal color codes. You can either turn them off in your
MOOSE run with "--no-color" or you can use a tool that understands the
codes like recent versions of "less".

Cody

**Comment by permcody** [comment]
@bwspenc - Just tried this again this morning and it seems to be working for me with mpich - no odd characters.

**Comment by permcody** [comment]
Closing - unable to repeat.
