### ISSUE TITLE
PenaltyDirichletBC

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#5268]
I swear that there was a discussion on the users list recently about adding a penalty Dirichlet BC, but I can't find it now.  This would be really useful to us for restraining rigid body modes in our solid mechanics models, but using a pretty weak spring to do that.

I have an implementation of this that I'll push shortly.

**Comment by andrsd** [comment]
`PenaltyDirichletBC` currently sits in `tests/src/bcs/`. You may want to check its implementation, possibly merge and move to `framework/`.

**Comment by bwspenc** [comment]
Thanks for pointing that out @andrsd .  That would explain the strange compile errors I was seeing in the automated testing.  Yes, that is something that I think is useful enough to move over.
