### ISSUE TITLE
Andy: fix comments in your test-suite input files

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#5270]
Heather reports:

I have run into a problem where Peacock does something odd with some of the comments in the input file when it creates its own input file. For example, in initial_stress/gravity.i, this block:
  [./elasticity_tensor]

```
type = ComputeElasticityTensor

block = 0

fill_method = symmetric_isotropic

C_ijkl = '0.4 0.4' # young’s  = 1, poisson = 0.25
```

  [../]

Ends up like this:

  [./elasticity_tensor]

```
type = ComputeElasticityTensor

block = 0

fill_method = symmetric_isotropic

C_ijkl = '0.4 0.4' # young'

s = 1,

poisson = 0.25
```

  [../]

Which then obviously results in an error message when trying to run the simulation in Peacock. The problem goes away if I get rid of the equals signs from the comment.

**Comment by permcody** [comment]
Interesting bug... Thanks for the report

**Comment by friedmud** [comment]
I'm going to raise the priority on this.  We don't need input file parsing bugs...

**Comment by WilkAndy** [comment]
This is ok as far as i'm concerned.  @permcody , @friedmud - does peacock need to be changed, or can the issue be closed?

**Comment by WilkAndy** [comment]
(Pushed the wrong button.)

**Comment by friedmud** [comment]
It's not really Peacock, it's the python input file parser (which is
technically separate). This should probably be fixed at some point so leave
the ticket open.
