### ISSUE TITLE
ElementIntegralVariableUserObject et al. use _subproblem.getVariable

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5273]
We should use the methods from ```Coupleable``` instead.
I'm already changing this.

**Comment by andrsd** [comment]
The idea behind `Coupleable` is to bring variable values, gradients and 2nd derivatives into user space (as well as their old and older values). We did not really want users to get the reference to `MooseVariable` and mess with it.

However, we need the variable reference for things like `_u`. You might see this pattern in other systems like Kernels, BCs. So, what is your design here? Or should I wait for the actual patch?

**Comment by andrsd** [comment]
Just to be clear, we can get rid of `_var` and call something else to set `_u`, et al., but we would also need to add `_var_num` (or something) - that information is used in kernels, BCs (not really needed in user objects right now). `Coupleable` kind of provides the values if it is called with the right params...

**Comment by dschwen** [comment]
Yeah, just wait for the patch.

**Comment by dschwen** [comment]
Does b30dc48 clarify things @andrsd?

**Comment by andrsd** [comment]
It does and looks good.

**Comment by friedmud** [comment]
This was originally like this because of how this tree used to not inherit from `Coupleable` at all.  That changed a few years ago... but this stuff was still hanging around.

The fix looks good to me.

**Comment by dschwen** [comment]
There is a similar issue in ```ScalarL2Error``` which in this case does not inherit from ```ScalarCoupleable```.
