### ISSUE TITLE
Input displacement vector customizable to coordinate system

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#5277]
As part of moving the capabilities of solid mechanics to tensor mechanics, we'd like to have the user input a displacement vector which can change dependent on the coordinate system selected, such that 
``` disp_vector = 'disp_x disp_y disp_z ``` for a Cartesian system or ``` disp_vector = 'disp_r disp_z' ``` for an axisymmetric geometry in cylinderical coordinates.  

This input vector could look similar to input vectors used in the mesh block.  
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  displacements = 'disp_x disp_y'
[]
```
If possible the same input displacement vector would be used in the Materials, Kernels, and Variables block, lending towards use as a global variable in the input file. 

A similar input vector of variables is already implemented in phasefield's [TotalFreeEnergyBase](https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/auxkernels/TotalFreeEnergyBase.C) s
```
  for (unsigned int i = 0; i < _nvars; ++i)
  {
    _vars[i]      = &coupledValue("interfacial_vars", i)
    _grad_vars[i] = &coupledGradient("interfacial_vars", i);
  }
```

The use of an input displacement vector would allow the user to specify the variables used in a manner consistent with the simulation coordinate system:  Users working in a cylindrical or spherical coordinate system could specify ```disp_r``` instead of the current ```disp_x```.  Such a system could also reduced the size of input files.

Within the Material(s) and Kernel we would switch / override the calculation of the strain tensor, deformation gradient, residual, and Jacobians dependent on the coordinate system and provided variables; see [Gradient of a rank two tensor in cylindrical coordinates](https://en.wikipedia.org/wiki/Tensors_in_curvilinear_coordinates#Gradient_of_a_second-order_tensor_field) for additional contributions.  The code should check for agreement between the input variables and the selected coordinate system, eg.
```
if ( (disp_vector[0] != 'disp_r' && disp_vector[1] != 'disp_z') && (_assembly.coordSystem() != Moose::COORD_RZ)
  mooseError("Incorrect match between provided displacements and coordinate system")
```

Pinging @bwspenc @tonkmr @dschwen for corrections/ clarifications to this issue.

This issue is similar to #886 from a while back, @friedmud @permcody do you have any advice about how to proceed?  It would be great if we could automatically set the disp variables (or velocity as mentioned in #886 ) based on the coordinate system and mesh dimension.

**Comment by dschwen** [comment]
I don't think we want to hardcode variable names (i.e. check if the variable is called ```disp_r``` vs. ```disp_x``` in the axialsymmetric case). Maybe some person wants to use ```pos_x``` or whatever.
I agree that we should use the same parameter name as the mesh to be able to use global params for it. :+1:

**Comment by bwspenc** [comment]
The variables themselves should still be named 'disp_x', etc. because those are the names the postprocessing programs recognize to displace the mesh. The discussion was whether we should have parameters where the user sets 'disp_r = disp_x'.

**Comment by dschwen** [comment]
This is not the right place to enforce that variable naming. The user can
choose arbitrary names in the mesh block, so why restrict it in one
specific material. We cannot possibly know what our users may want to do.
They may have their own standard and analysis tools.

**Comment by sapitts** [comment]
Ben,  are you concerned about the variables within the Variables block of the input file, e.g.
```
[Variables]
  [./disp_x]
  [../]
[] 
```
I agree that it is important to maintain the Paraview functionality that many users employ while giving other users the freedom to select whatever variable names they choose in the material block. That said, I'm not sure how to accomplish this smoothly, but I'll update as I explore the error possibilities.  Any advice about how to set Paraview's expectations for ``` disp_x```, ect as the default?

**Comment by bwspenc** [comment]
I agree completely with Daniel. We don't want to impose any restrictions on the names of those variables, although typically there would never be any good reason for them to be anything other than 'disp_x disp_y disp_z'.

**Comment by mangerij** [comment]
So in theory, one should be able to use

[GlobalParams]
  displacements = 'disp_x disp_y disp_z'
[]

and this would encompass the new changes and we would have unused flags from the parser wherever  

disp_x = disp_x 
disp_y = disp_y 
disp_z = disp_z

is called. I'm not getting that. I'm getting an error from ComputeStrainBase.C

*** ERROR ***
The displacement variables for the Compute*Strain Materials must be provided in a string: displacements = 'disp_x disp_y'

[1] /home/john/projects/moose/modules/tensor_mechanics/src/materials/ComputeStrainBase.C, line 35, compiled Jul 15 2015 at 19:38:18

when I try to run an input file that just does the stress divergence problem.
