### ISSUE TITLE
Failure: Restart with Adaptivity in parallel

### ISSUE THREAD

**Issue by cpritam** [idaholab/moose#5278]
I am running a simulation with adaptivity in the executioner block and I use the following in my output block for restart:

[./restart]
    type = Checkpoint
    num_files = 2
    suffix = 1
 [../]

The run fails with the following error:

**\* ERROR ***
Can't output Elems with invalid ids!^[[39m

[260] /home/chakp/project_git_fission/moose/framework/src/restart/DataIO.C, line 95, compiled Jun 16 2015 at 10:16:19
[cli_260]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 260

The simulation continues without restart.
I have tried the same restart option in another simulation without adaptivity and it works.

**Comment by permcody** [comment]
We definitely support adaptivity in checkpoint files. We routinely verify this with our "recover" target which includes several adaptivity targets. Closing - not reproducible.
