### ISSUE TITLE
"Empty" Material block required in FEProblem

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#5306]
Currently if someone wants to just implement materials properties on one block and keep all other blocks empty or devoid of material properties, they can't. The error printed is

*** ERROR ***
The following blocks from your input mesh do not contain an active material: 1 
When ANY mesh block contains a Material object, all blocks must contain a Material object.

I know the way around this is to use GenericConstantMaterial and just set things to zero and make sure no active kernels on that empty block need material properties. 

Is this an entirely necessary error?

**Comment by permcody** [comment]
No, it was there in the past to avoid mistakes but it's probably not necessary anymore as long as kernels complain properly when they aren't feed properties they need. We'll take a look at removing this check and/or disabling it.

Thanks for the report.
