### ISSUE TITLE
MOOSE Workshop Enhancements

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5307]
- [ ] Step10, k_eff in the master application doesn't seem to be getting its value from sub app.
- [ ] The UserObjects section should be discussed before PP, just put in as another section in Step 8.
- [ ] We call coupledValue, coupledGradient and store them as non-const references, they really need to be const.
- [ ] In Step 7, we couple the two equations via the velocity. To do this we compute the velocity in three different places (computeQpResidual, computeQpJacobian) as well as in the AuxKernel. We need to abstract this into a UserObject that the various objects use. At a minimum, the Convection kernel should have a helper method for the velocity.
- [ ] In Step 6, the DarcyPressure kernel relies on velocity, which is computed from the gradient of the pressure, so having a constant pressure doesn't do much for testing the convection portion.
- [x] We need to add InitialConditions to one of the steps of the tutorial
- [x] DircacExample needs to be updated, it uses `getParam<std::vector<Real> >(...)` to populate a `Point`
- [x] Possibly reiterate the JFNK "update" slide on the PJFNK slide in the preconditioning section.
- [x] Need to better explain the difference between the _linear_ and _nonlinear_ iterations during the Numerical Implementation slides, and fix up the Krylov-subspace description stuff.  Several people were confused about this.
- [x] Fix bullet count (5 vs. 4) on Preconditioning Matrix vs. Process
- [x] Remove `-pc_hypre_boomeramg_strong_threshold` from slide, MOOSE now handles this automatically.
- [x] We might need to describe the process of computing the integral over the entire domain as the sum of element integrals.  We talk about quadrature, but quadrature doesn't make sense unless you are talking about element integrals.  I think we can still omit the details of the map between the reference and physical elements, i.e. the "J" part of "JxW", but make this part more clear.

**Comment by jwpeterson** [comment]
I'll fix the DiracKernel example...

**Comment by aeslaughter** [comment]
Step 10 (#5730) will have ICs

**Comment by permcody** [comment]
Closing this ticket due to age. Some of the issues may still be relevant but it's very old and many other changes have occurred since 2015. Let's capture new issues found in a new ticket.
