### ISSUE TITLE
Create AuxKernel to output material properties of type std::vector<RealGradient>

### ISSUE THREAD

**Issue by SudiptaBiswas** [idaholab/moose#5308]
Create AuxKernel to output components of material properties for 'MaterialProperty<std::vector<RealGradient> >'

**Comment by aeslaughter** [comment]
Make sure you look at the other classes that are doing this sort of thing, this should use the same system: `MaterialRealVectorValueAux` is a good place to start.

**Comment by dschwen** [comment]
It might even be worth deriving a base class ```MaterialVectorValueAuxBase``` for ```std::vector``` types from which we derive ```MaterialRealVectorValueAux``` and ```MaterialRealGradientVectorValueAux```. We could use a function ```virtual Real computeComponent(const T & element)``` which fetches the element from the vector.

**Comment by SudiptaBiswas** [comment]
MaterialRealVectorValueAux derives from MaterialAuxBase which takes templates Real, RealVectorValue, RealTensorValue and DenseMatrix<Real>. We might have to modify MaterialAuxBase in order to implement RealGradientVectorValue. Even if we derive MaterialVectorValueAuxBase from AuxKernel, we would probably like to get rid of the duplicacy from MaterialAuxBase.

**Comment by SudiptaBiswas** [comment]
Please have a look if ea2a8cb & 9d0d245 make sense. I can modify MaterialAuxBase and MaterialStdVectorAux classes accordingly.

**Comment by dschwen** [comment]
Wait a minute, @aeslaughter, why don't we inherit a ```MaterialStdVectorAuxbase``` from ```MaterialAuxBase``` using templated inheritance. I.e.:

```
template <class T>
class MaterialStdVectorAuxbase : public MaterialAuxBase<std::vector<T> >
{...
```
In that class we can add an additional input parameter for the component and provide a new virtual method to retrieve a value from a given element of the vector. That way we don;t have to factor out a new common base class and have a more logical inheritance structure (IMO).
