### ISSUE TITLE
Retrieving a material property in a BC does not trigger an error if it's not supplied

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5309]
Reported by Alex Lindsay. 

@dschwen made the following comment:
This can be replicated by removing the material k3bnd in
moose/test/tests/materials/boundary_material/bnd_coupling_vol.i
…

**Comment by lindsayad** [comment]
Any hints on how this might be fixed? It seems mysterious that an IntegratedBC can get material properties from a material object defined on a block, but then won't complain when the properties it's requesting don't exist. It seems like it should either be able to do neither or both. 

Is there a reason that checkBoundaryMatProps() is commented out in FEProblem::checkProblemIntegrity?

**Comment by permcody** [comment]
There's some interplay between block/boundary restrictable and these materials check. I looked at it for a few minutes but wanted to vomit because we basically have two different systems checking material properties implemented. One was built by me a long time ago but @dschwen built another along side mine. They are both doing part of the work so it's a big mess now. It's on my to do list to clean them both up and get back to a single unified system for checking properties. I'm not sure when I'll get to it...

**Comment by dschwen** [comment]
Hmm, I did? I guess I must have. The uses are slightly different. One system (yours) is for state validation (making the simulation fail if data has been requested that is not available) mine is for implementing "optional" material properties. But I agree that those are almost the same and should have a unified code base. If I recall correctly though my _system_ was rather small and just populated a lookup map. I don't think I touched the validation system much.

**Comment by lindsayad** [comment]
Can we set up a paypal account so I can donate $20 to the first person who fixes this?? :-)

**Comment by permcody** [comment]
That's a great idea. We vote on tickets with our money... Hmm...

**Comment by lindsayad** [comment]
@permcody I can fix this by

1) uncommenting checkBoundaryMatProps() in FEProblem::checkProblemIntegrity()
2) Replacing MaterialPropertyInterface(parameters) with MaterialPropertyInterface(parameters, boundaryIDs()) in the IntegratedBC constructor

Admittedly, I now have to define another material in my input file, a la:

[Materials]
  [./jac_block]
    block = '0'
    type = JacMat
    mean_en = p
    em = w
  [../]
  [./jac_boundary]
    boundary = 'left right'
    type = JacMat
    mean_en = p
    em = w
  [../]
[]

but now I get the checks that I need. Is this good enough for the framework?

**Comment by permcody** [comment]
Which is probably why that check isn't in there. My guess is that this
would fail a few a LOT of tests. This really needs to be fixed but I want
to spend more time then just hacking something together for the current
problem we are thinking about. I think we'd like block restricted materials
to work for exterior boundaries too (the normal case). However, we have to
be careful about interior boundaries. You don't necessarily want materials
defined where they butt up against one and other in the interior.

**Comment by lindsayad** [comment]
Yea, you're right. I was taking way too simple a view and not thinking about what this would break. Yes, sure enough 8 tests failed when I tried to run this.

**Comment by permcody** [comment]
That's just moose_test. We have dozens of live applications...

**Comment by permcody** [comment]
@aeslaughter - you might check this again...

**Comment by lindsayad** [comment]
Maybe not a lot of people use materials in their integratedBCs, but I'm still getting bitten by this. Luckily with Valgrind's help, I'm now tracking down uninitialized materials in my BCs.
