### ISSUE TITLE
play with simple Contact/BoundaryConstraints

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#5310]
Currently MOOSE has fairly sophisticated Contact capability, and also the ability to constrain two (or more) DOFs to be equal.  My problem with the Contact system is that it doesn't calculate OffDiag jacobian contributions, which i believe are important in my situation.  I need something simpler:

if (disp_z_master_node - disp_z_slave_node > d) enforce disp_z_master = disp_z_slave_node + d

where "d" is given by the user.  I plan on using a penalty formulation and introduce appropriate DiracKernels.

**Comment by WilkAndy** [comment]
I reckon i can do something very similar to EqualValueNodalConstraint here.

**Comment by WilkAndy** [comment]
Mmmm, i wonder if EqualValueNodalConstraint is going to work in parallel.

**Comment by bwspenc** [comment]
EqualValueBoundaryConstraint, which was originally based on EqualValueNodalConstraint, works in parallel. I think the EqualValueNodalConstraint doesn't. If it doesn't, look at the EqualValueBoundaryConstraint code to fix it. 

If you want off-diagonal Jacobian entries for contact-type constraints, the Constraint system permits that. We're moving everything over to that system and it works far better than DiracKernel. The class for mechanical contact under that system is MechanicalContactConstraint. We typically use it with the system=constraint parameter in the Contact action.

**Comment by WilkAndy** [comment]
Oh great, thanks for all that info @bwspenc ,

a

**Comment by WilkAndy** [comment]
Closing this.  I have implemented something quite simple but quite functional in my closed-source moose app that we have voted not to release publicly.
