### ISSUE TITLE
DiracKernel incorrectly calculates diagonal and off-diagonal Jacobian entries

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#5316]
boohoo.

@jwpeterson , i'm using your tests/dirackernels/nonlinear_source/nonlinear_source.i .  I use -snes_type=test to check the Jacobian, and the entries are exactly double what they should be !!   (This also occurs in my RichardsBorehole, and that is how i discovered this problem.)

However, the Jacobian is correctly calculated if the DiracKernel only has one variable associated with it.

See #668 , #739 , #3400, #3442 , #3444 , etc

nonlinear.i altered to use snes_type = test

[Mesh]
  type = GeneratedMesh
  dim = 2
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 1
  nx = 2
  ny = 2
  elem_type = QUAD4
  #uniform_refine = 1
[]

[Variables]
  [./u]
    order = FIRST
    family = LAGRANGE
  [../]

  [./v]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./ddt_u]
    type = TimeDerivative
    variable = u
  [../]

  [./diff_u]
    type = Diffusion
    variable = u
  [../]

  [./ddt_v]
    type = TimeDerivative
    variable = v
  [../]

  [./diff_v]
    type = Diffusion
    variable = v
  [../]
[]

[DiracKernels]
  [./nonlinear_source]
    type = NonlinearSource
    variable = u
    coupled_var = v
    scale_factor = 1000
    point = '0.2 0.3 0'
  [../]
[]

[BCs]
  [./left_u]
    type = DirichletBC
    variable = u
    boundary = 3
    value = 0
  [../]

  [./right_u]
    type = DirichletBC
    variable = u
    boundary = 1
    value = 1
  [../]

  [./left_v]
    type = DirichletBC
    variable = v
    boundary = 3
    value = 1
  [../]

  [./right_v]
    type = DirichletBC
    variable = v
    boundary = 1
    value = 0
  [../]
[]

[Preconditioning]
  [./precond]
    type = SMP
    # 'full = true' is required for computeOffDiagJacobian() to get
    # called.  If you comment this out, you should see that this test
    # requires more linear and nonlinear iterations.
    full = true
    petsc_options = '-snes_test_display'
    petsc_options_iname = '-snes_type'
    petsc_options_value = 'test'
  [../]
[]

[Executioner]
  type = Transient
  solve_type = 'NEWTON'
  num_steps = 5
  dt = 1
  l_max_its = 100
  nl_max_its = 6
  dtmin = 1.e-3
  nl_abs_tol = 1.e-13
[]

[Postprocessors]
  # A PointValue postprocessor at the Dirac point location
  [./point_value]
    type = PointValue
    variable = u
    point = '0.2 0.3 0'
  [../]
[]

[Outputs]
  output_initial = true
  exodus = true
  print_linear_residuals = true
  print_perf_log = true
[]

**Comment by jwpeterson** [comment]
On Sun, Jun 28, 2015 at 6:13 PM, Andy Wilkins <notifications@github.com>
wrote:

> boohoo.
>
> @jwpeterson <https://github.com/jwpeterson> , i'm using your
> tests/dirackernels/nonlinear_source/nonlinear_source.i . I use
> -snes_type=test to check the Jacobian, and the entries are exactly double
> what they should be !! (This also occurs in my RichardsBorehole, and that
> is how i discovered this problem.)
>
> However, the Jacobian is correctly calculated if the DiracKernel only has
> one variable associated with it.
>
Interesting, I'm guessing something about the logic around line 1912 of
NonlinearSystem.C is the culprit.

I'll look into it, sorry for the trouble.

-- 
John

**Comment by WilkAndy** [comment]
Awesome, thanks @jwpeterson .   The double-counting comes because the Jacobian functions are being called twice.

Thanks for giving me a line number - i'll try to figure out what you did - nice education for me, but i won't be able to fix it :-)

a

**Comment by WilkAndy** [comment]
Hey @jwpeterson , while you're looking at this, can you tell me how my RichardsBorehole.C can inform the DiracKernel that there are coupledVariables?  In the constructor of NonlinearSource.C you have

    _coupled_var(coupledValue("coupled_var")),
    _coupled_var_num(coupled("coupled_var")),

which i suppose tells DiracKernel that you need the off-diagonal Jacobian entries wrt the coupled_var.

However, in my RichardsBorehole.C I don't have any "coupled_var" mentioned explicitly: those variables appear in certain functions that are calculated in a Material, and in certain UserObjects that are supplied to RichardsBorehole.C .   RichardsBorehole knows about those variables (they are defined through the richardsVarNames_UO UserObject) so i could just create a number of dummy _coupled_var in the same way as in NonlinearSource.C, but that seems really hacky.

I want to directly push onto the "stack of dependent variables" the variables defined in richardsVarNames_UO.   But i don't know how to do that.

a

**Comment by WilkAndy** [comment]
Possibly something like the following answers my question above:

  for (unsigned int i=0; i<coupled_vars.size(); i++)
    addMooseVariableDependency(coupled_vars[i]);

**Comment by WilkAndy** [comment]
How's this going @jwpeterson ?  Is it a huge piece of work ?

a

**Comment by jwpeterson** [comment]
On Thu, Jul 2, 2015 at 6:23 AM, Andy Wilkins <notifications@github.com>
wrote:

> How's this going @jwpeterson <https://github.com/jwpeterson> ? Is it a
> huge piece of work ?
>

Sorry, been working on something else that was due this week.  I will take
a look today.

-- 
John

**Comment by jwpeterson** [comment]
This should be fixed now, please let me know if it's not @WilkAndy.

**Comment by WilkAndy** [comment]
It appears to work as planned, thanks @jwpeterson ,

a
