### ISSUE TITLE
When run from an application directory, "make clobber" deletes stuff from libmesh submodule

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#5320]
Specifically, it deletes a bunch of static libraries that libmesh uses to do Tecplot binary output.  Running `git  status` after `make clobber` from a specific app (RELAP-7) shows:

```
deleted:    contrib/tecplot/binary/lib/alphaev56-unknown-linux-gnu/tecio.a
deleted:    contrib/tecplot/binary/lib/alphaev67-unknown-linux-gnu/tecio.a
deleted:    contrib/tecplot/binary/lib/i386-apple-darwin10.4.0/tecio.a
deleted:    contrib/tecplot/binary/lib/i386-apple-darwin9.6.0/tecio.a
deleted:    contrib/tecplot/binary/lib/i386-apple-darwin9.7.0/tecio.a
deleted:    contrib/tecplot/binary/lib/i386-apple-darwin9.8.0/tecio.a
deleted:    contrib/tecplot/binary/lib/i686-apple-darwin8.10.1/tecio.a
deleted:    contrib/tecplot/binary/lib/i686-pc-linux-gnu/tecio.a
deleted:    contrib/tecplot/binary/lib/ia64-unknown-linux-gnu/tecio.a
deleted:    contrib/tecplot/binary/lib/mips-sgi-irix6.5/tecio.a
deleted:    contrib/tecplot/binary/lib/powerpc-apple-darwin7.9.0/tecio.a
deleted:    contrib/tecplot/binary/lib/powerpc-ibm-aix5.1.0.0/tecio.a
deleted:    contrib/tecplot/binary/lib/sparc-sun-solaris2.7/tecio.a
deleted:    contrib/tecplot/binary/lib/x86_64-apple-darwin10.6.0/tecio.a
deleted:    contrib/tecplot/binary/lib/x86_64-apple-darwin10.7.0/tecio.a
deleted:    contrib/tecplot/binary/lib/x86_64-unknown-linux-gnu/tecio.a
```

I don't really understand why this is happening, since we supposedly already prune `$(CURDIR)/moose` and to me that seems like it would include `$(CURDIR)/moose/libmesh`... 

There is also a general warning message when you run `make clobber` on Linux which may be related to this issue, and should be cleaned up anyway:
```
find: The -delete action atomatically turns on -depth, but -prune does nothing when -depth is in effect.  If you want to carry on anyway, just explicitly use the -depth option.
```

**Comment by permcody** [comment]
@jwpeterson - same problem with -prune?

**Comment by jwpeterson** [comment]
This is a different issue: `-delete` turns on `-depth`, but turning on `-depth` means `-prune` does nothing... so this is a bad interaction between `-depth` and `-prune` as far as I can tell.

We could change the "make clobber" target back to using `xargs rm -rf` but we found that -delete was much faster in general.

**Comment by dschwen** [comment]
I just realized that clobber is a no-op on Linux!

**Comment by permcody** [comment]
I just cloned a new repo just to test this. I didn't destroy my machine so I'm closing this for now.
