### ISSUE TITLE
Remove KernelBase

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5330]
I just saw the inheritance diagram for `Kernel` in the MOOSE paper... it looks ridiculous with `KernelBase` on there as well.

We never actually needed `KernelBase` and it can be safely removed.  We just need to do that.

**Comment by YaqiWang** [comment]
Wait, `KernelBase` is actually used by both `Kernel` and `EigenKernel`...

**Comment by permcody** [comment]
Right, KernelBase IS used

**Comment by friedmud** [comment]
I thought we said that that was no longer needed though.  That we could do away with KernelBase....

**Comment by permcody** [comment]
Well we certainly could collapse it back into a single class but I recall
at the time that we had to add a few nasty things at the Kernel level that
weren't used by any Kernels (only EigenKernels).

**Comment by friedmud** [comment]
But then I think we removed those.  Let me take a look.

**Comment by permcody** [comment]
Typical @friedmud - "Let me look or do something comment". I don't see KernelBase going away. Closing

**Comment by friedmud** [comment]
:-). Not going away anytime soon anyway...
