### ISSUE TITLE
Name collision with "Convection" kernel in examples

### ISSUE THREAD

**Issue by smharper** [idaholab/moose#5333]
When a new user builds Stork, they probably have all of the modules included.  This means they have the modules' `Convection` kernel defined in their namespace.  If they then try to compile code from the examples that have a `Convection` kernel, they'll encounter an unhelpful error.  There is also a collision with the `GaussContForcing` kernel.

**Comment by friedmud** [comment]
One more thing on this.  Was the documentation that referred to `Convection` updated to say `ExampleConvection` on the Wiki??

**Comment by smharper** [comment]
I've updated the wiki now.

**Comment by friedmud** [comment]
Thanks Sterling!
