### ISSUE TITLE
Need a new mesh modifier to select multiple nodesets using a bounding box

### ISSUE THREAD

**Issue by amburan** [idaholab/moose#5340]
I would like to create a nodeset containing multiple nodesets at one go. The existing class AddExtraNodeSet is only capable of selecting one node at a time using the coordinates or node id. This is not convenient since I have to type many nodal coordinates. I propose to create a new class called BoundingBoxNodeSet which allows using a bounding box and selects multiple nodes without specifying the individual location of the nodes or node ids. This code would be very similar to SubdomainBoundingBox

**Comment by friedmud** [comment]
Sounds good to me! :+1:

**Comment by aeslaughter** [comment]
Thanks @amburan, that is just want I had in mind. Let me know if you need implementing or with the github/git stuff.

**Comment by amburan** [comment]
Great. Yes, it would be very helpful if you could guide me with the git stuff. I have the files staged for commit to my local. 
![screenshot from 2015-07-05 22 32 07](https://cloud.githubusercontent.com/assets/2464422/8515726/c60489be-2365-11e5-9acf-dca0d9cc56e3.png)

**Comment by aeslaughter** [comment]
Start here: http://www.mooseframework.org/wiki/Contributing/, if that
doesn't help then get a hold of me directly via google chat.
