### ISSUE TITLE
EigenExecutionerBase in recover 

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#5356]
@friedmud In Mammoth we often want to solve problems in a quasi static manner: Rattlesnake solves an eigenvalue problem, while everyone else solves transient problems. Execution time can be very long and
most of the things we are interested in happen at the very end of the calculation.

Therefore, we would need to be able to use the recover capability with executioners derived from `EigenExecutionerBase`.  Can you give me an idea of how difficult this would be, since recover 
only works with transient calculations. 

What makes things worse is that EigenSolves abuse the Moose's transient mode in that time is used
as an 'outer' iteration index.

**Comment by friedmud** [comment]
Firstly, I'm hoping that #5229 clears a lot of this up... but that's still a ways off from being finished.

However, recover doesn't depend on `Transient`.  If you look in `Transient` there are only a couple of things related to recovery in there.

The only real thing that you need to do is to make sure that you have declared all of your stateful data using `declareRestartableData()` and then write out checkpoint files...

**Comment by aeslaughter** [comment]
I think the problem is that we only allow output (i.e., checkpoint) at the end of the timestep, which is when the complete solve is done. We may need to add the ability to output and eigen iterations.

**Comment by friedmud** [comment]
They can make up their own "steps" and output whenever they like....

**Comment by snschune** [comment]
@friedmud #5229 will fix a lot of problems, but it won't be completed within the next two weeks, will it?
 Is recoverable data written in ```_problem.onTimestepEnd()``` ? Can we postpone writing checkpoint files to after eigensolve's completion? There should not be a lot of restartable data to be declared, as a matter of fact I think it's only ```_eigenvalue```.

**Comment by snschune** [comment]
@friedmud didn't see your response, I guess that is what we want: Output at the eigensolve's completion.
