### ISSUE TITLE
Remove PETSc #ifdef gaurds

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5358]
As @permcody stated, we only use PETSc and don't use MOOSE without it, so why keep this stuff around.

**Comment by friedmud** [comment]
I don't know.  Why remove them?  Maybe in the future we might want to support a stripped down nonlinear solver.

I'm not 100% against it either... mostly I just don't know why we would remove something that's currently not hurting anyone ;-)

**Comment by jwpeterson** [comment]
I agree with Derek, there's no reason to remove them.  If we ever need to put them back in for some reason, we're already half way or more there.

**Comment by aeslaughter** [comment]
I also say leave them, I guess @permcody is out voted.
