### ISSUE TITLE
Split validParams does not inherit from MooseObject

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5359]
Is there a reason for this? If not, I am changing it.

```
template<>
InputParameters validParams<Split>()
{
  InputParameters params = emptyInputParameters();
```

**Comment by friedmud** [comment]
I suspect this is leftover from the beginning of `Split`... in the beginning it probably didn't inherit from `MooseObject`.  It does now, so this should be fixed....

**Comment by aeslaughter** [comment]
I will handle in my InputParameter stuff.
