### ISSUE TITLE
Performance log will not be printed

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5377]
If the master app has `print_perf_log = true` and sub app does not provide `Outputs` block. Should this be considered as an issue?

**Comment by permcody** [comment]
Possibly, but the Perf Log capability needs a full overhaul to be MultiApp aware. Right now, it's not very useful at all so the problem is much bigger than this. It's on my list to redo it anyway, I don't know what the priority is.

**Comment by YaqiWang** [comment]
@permcody this is also related with multiapp output, sorry for not noticing it when you were working on the other issues.
