### ISSUE TITLE
restartable_data checks

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#5392]
Where is  ```RestartableTypesChecker::execute``` executed.

**Comment by friedmud** [comment]
It's a `UserObject` just like any other.  So it gets executed when you say it does.  If you're specifically looking for how it's used in a test look here: https://github.com/idaholab/moose/blob/devel/test/tests/restart/restartable_types/restartable_types2.i

**Comment by permcody** [comment]
Haha - just found out that this object wasn't actually doing anything because of the new (none legacy) behavior!  It was silently not checking anything!

I just showed Sebastian how to fix it - see #2221.
