### ISSUE TITLE
New idea for arrays of variables

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5401]
It's time to get serious about having arrays of variables (i.e. grain_0, grain_1, grain_x....).  Several different researchers have hacked their own solution so it's time to do this properly.

Lately it's been an issue as shown in #5383 and #5384 

This is my solution from #5384

I think we should promote these "variable arrays" to be first class citizens.  There are enough people that want this functionality that we should stop hacking around at it... and make it right.

How about something like this:

```
[Variables]
  [./grain]
    array = 4
  [../]
[]
```

That would automatically create an ArrayVariable that has 4 entries (i.e. it would create 4 actual variables called grain_0, grain_1, grain_2 and grain_3). (NOTE: I don't want to use the word VECTOR here at all because we might actually support Vector variables (supported by vector shape functions) at some point in the future)

Then the input parameter would still be a normal `addCoupledVar()` thing.  BUT: To get the array of variables you would call:

``` c++
const VariableValueArray & coupledValueArray(const std::string & name)
```

The only tricky part is... what do we use for the type of `VariableValueArray`?  Traditionally, we used `std::vector<VariableValue *>` but that requires dereferencing which is ugly... and if we hide the fact that there is a pointer behind a type def... it won't be clear that you NEED to dereference when you're using a `VariableValueArray`.

I propose that we use `std::vector<VariableValueProxy>`... where a `VariableValueProxy` is a `MooseArrayProxy<Real>` and a `MooseArrayProxy` is basically a forwarding object to the "real" `MooseArray`.  Essentially, we hide the dereference behind a class.

In this way we can stop doing the whole "vector coupling" thing all together.

**Comment by lindsayad** [comment]
Yes!
