### ISSUE TITLE
Error in pbs_submit.sh with module change

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#5423]
./run_tests --pbs on Falcon results in a failure like the following:

########################### Notice ##############################
The modules being provided through the use of this script have
been removed. Instead, please use:

	module load use.moose moose-dev-gcc

########################### Notice ##############################
The modules being provided through the use of this script have
been removed. Instead, please use:

	module load use.moose moose-dev-gcc

[mpiexec@r5i4n5] HYDU_process_mfile_token (utils/args/args.c:296): token -np not supported at this time
[mpiexec@r5i4n5] HYDU_parse_hostfile (utils/args/args.c:343): unable to process token
[mpiexec@r5i4n5] mfile_fn (ui/mpich/utils.c:336): error parsing hostfile
[mpiexec@r5i4n5] match_arg (utils/args/args.c:152): match handler returned error
[mpiexec@r5i4n5] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@r5i4n5] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@r5i4n5] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@r5i4n5] main (ui/mpich/mpiexec.c:153): error parsing parameters

Part of the problem may be that on Falcon, we now need to module load use.moose moose-dev-gcc, but the pbs_submit.sh file only has module load moose-dev-gcc.

**Comment by milljm** [comment]
Somewhere in one of your bash profiles, you are still attempting to load the old moose modules. You now need to use:

module load use.moose moose-dev-gcc

(as the message is stating). I am able to confirm loading the use.moose moose-dev-gcc modules is working:

milljm@falcon1:~/projects/moose/test> module load pbs
milljm@falcon1:~/projects/moose/test> module load use.moose moose-dev-gcc
milljm@falcon1:~/projects/moose/test> ./run_tests --pbs
geomsearch/3d_moving_penetration_smoothing.pl_test4qnstt............................................ LAUNCHED
geomsearch/fake_block_to_boundary.test.............................................................. LAUNCHED
geomsearch/quadrature_penetration_locator.1d_qpl.................................................... LAUNCHED
geomsearch/3d_moving_penetration.pl_test3tt......................................................... LAUNCHED
geomsearch/penetration_locator.parallel_test........................................................ LAUNCHED
geomsearch/1d_penetration_locator.test.............................................................. LAUNCHED

**Comment by jasondhales** [comment]
The pbs_submit.sh script doesn't load use.moose:

falcon1> cat pbs_submit.sh
#!/bin/bash
#PBS -N triso2_00_002
#PBS -l select=1:ncpus=4:mpiprocs=4
#PBS -l place=free
#PBS -l walltime=00:25:00




#PBS -j oe

source /etc/profile.d/modules.sh
*module load moose-dev-gcc*

cd $PBS_O_WORKDIR

JOB_NUM=${PBS_JOBID%\.*}


export MV2_ENABLE_AFFINITY=0

mpiexec /home/halejd/gitProjects/bison/bison-opt -i triso2D_accident.i
 --n-threads=1

On Thu, Jul 23, 2015 at 8:28 AM, Jason Miller <notifications@github.com>
wrote:

> Somewhere in one of your bash profiles, you are still attempting to load
> the old moose modules. You now need to use:
>
> module load use.moose moose-dev-gcc
>
> (as the message is stating). I am able to confirm loading the use.moose
> moose-dev-gcc modules is working:
>
> milljm@falcon1:~/projects/moose/test> module load pbs
> milljm@falcon1:~/projects/moose/test> module load use.moose moose-dev-gcc
> milljm@falcon1:~/projects/moose/test> ./run_tests --pbs
> geomsearch/3d_moving_penetration_smoothing.pl_test4qnstt............................................
> LAUNCHED
> geomsearch/fake_block_to_boundary.test..............................................................
> LAUNCHED
> geomsearch/quadrature_penetration_locator.1d_qpl....................................................
> LAUNCHED
> geomsearch/3d_moving_penetration.pl_test3tt.........................................................
> LAUNCHED
> geomsearch/penetration_locator.parallel_test........................................................
> LAUNCHED
> geomsearch/1d_penetration_locator.test..............................................................
> LAUNCHED
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5423#issuecomment-124123901>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by milljm** [comment]
It looks like there is a problem while launching the job though:

multiapps/picard.rel_tol..................................................................... FAILED (ERRMSG)
Lmod has detected the following error: These module(s) exist but cannot be
multiapps/picard.rel_tol: loaded as requested: "moose-dev-gcc"
multiapps/picard.rel_tol: 
multiapps/picard.rel_tol:    Try: "module spider moose-dev-gcc" to see how to load the module(s).
multiapps/picard.rel_tol: 
multiapps/picard.rel_tol: 
multiapps/picard.rel_tol: /var/spool/PBS/mom_priv/jobs/102135.service2.SC: line 22: mpiexec: command not found


It seems loading two modules is a problem of some kind? I'll look into it!

**Comment by milljm** [comment]
Oh ok. I don't think we should be attempting to load any module automatically in the script to be honest (what if you wanted to use the petsc-3.5.4 module that is also available). I think what we should do is have people enter the modules they want to load in their bash profile, so that the TestHarness just uses what ever is available?

What do you think?

**Comment by milljm** [comment]
So I have a PR in place, but if we merge it, it will force everyone that wishes to use cluster_launcher to modify their bash profile to load the modules they wish to use.

**Comment by jasondhales** [comment]
If the TestHarness could use whatever modules are active when the tests
fire off, that would be ideal.


On Thu, Jul 23, 2015 at 8:49 AM, Jason Miller <notifications@github.com>
wrote:

> Oh ok. I don't think we should be attempting to load any module
> automatically in the script to be honest (what if you wanted to use the
> petsc-3.5.4 module that is also available). I think what we should do is
> have people enter the modules they want to load in their bash profile, so
> that the TestHarness just uses what ever is available?
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5423#issuecomment-124129942>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by friedmud** [comment]
Hmmm.... I kind of like that idea... just inspect the current environment
and try to replicate it on the other side.

I seem to remember that there was an option for doing something like that
right in PBS. Maybe we should look into that...

**Comment by milljm** [comment]
Sounds like something I need ask Cormac how to do :) They would know... If it turns out PBS can not do this for us, it may get tricky as we start to parse a users currently loaded modules for correctness. Or, do we just assume the user knows what they are doing and just launch with those modules they have loaded...

**Comment by milljm** [comment]
Looks possible... I'll investigate.

From Cormac:

-V      Declares that all environment variables and  shell  functions  in  the  user's

               login  environment where qsub is run are to be exported to the job.  The job's

               Variable_List attribute is appended with all of  these  environment  variables

               and their values.

**Comment by jasondhales** [comment]
I like that.  Seems perfect.

On Thu, Jul 23, 2015 at 12:53 PM, Jason Miller <notifications@github.com>
wrote:

> Looks possible... I'll investigate.
>
> From Cormac:
>
> -V Declares that all environment variables and shell functions in the
> user's
>
>            login  environment where qsub is run are to be exported to the job.  The job's
>
>            Variable_List attribute is appended with all of  these  environment  variables
>
>            and their values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5423#issuecomment-124209992>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by permcody** [comment]
@milljm, @jasondhales is this ticket sufficiently handled? May we close?

**Comment by jasondhales** [comment]
Yes

On Wed, Jul 29, 2015 at 10:41 AM, Cody Permann <notifications@github.com>
wrote:

> @milljm <https://github.com/milljm>, @jasondhales
> <https://github.com/jasondhales> is this ticket sufficiently handled? May
> we close?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5423#issuecomment-126012706>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293
