### ISSUE TITLE
PFCRFF_split test failing

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#5427]
@dschwen , I keep getting:

phase_field:phase_field_crystal/PFCRFF_split.PFCRFF_split_test: Unable to locate library for "PhaseFieldApp".
phase_field:phase_field_crystal/PFCRFF_split.PFCRFF_split_test: We attempted to locate the library "libphase_field-opt.la" in the following paths:
phase_field:phase_field_crystal/PFCRFF_split.PFCRFF_split_test: 	
phase_field:phase_field_crystal/PFCRFF_split.PFCRFF_split_test: 
phase_field:phase_field_crystal/PFCRFF_split.PFCRFF_split_test: Make sure you have compiled the library and either set the "library_path" variable in your input file or exported "MOOSE_LIBRARY_PATH".

I'm not aware of anything crazy that i've done to phase_field.  Feel free to close this issue if it's obviously my fault, and/or you could instruct me how to fix the problem.

andy

**Comment by dschwen** [comment]
#5419 should have fixed that.

**Comment by WilkAndy** [comment]
Thanks @dschwen .  i thought i was up-to-date but evidently not.  I'll rebase and try again, and if all is well i'll close this issue.

**Comment by WilkAndy** [comment]
Thanks @dschwen , you were right.
