### ISSUE TITLE
Create user object to read Euler angle files

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#5438]
We need a user object that reads in Euler angle files and stores them in the same way as EBSDReader. Then, we need to change all code that reads in Euler angles to get the angles from a user object instead. That way, they will be compatible with Euler angle files and with EBSDReader.

**Comment by mangerij** [comment]
What is EBSDReader?

**Comment by tonkmr** [comment]
EBSD Reader is a capability to read in data from Electron Back Scatter Diffraction and use it to set the initial condition for phase field simulations. I am about to write a documentation page about it on the wiki.

**Comment by mangerij** [comment]
Very cool!

**Comment by tonkmr** [comment]
Here is the link:

http://mooseframework.org/wiki/PhysicsModules/PhaseField/EBSDReader/

I will write more in the next few minutes
