### ISSUE TITLE
Possible issue with the new constructor signatures

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5439]
The new constructor signature creates a trap for users developing their own objects. If a new object is created with the constructor signature

```
FooBar(const InputParameters params);
```

(note the absence of the ```&``` reference!) A copy of the params is created. This seems to cause a crash in the executable (for a Material class this happens during the setup_material_outputs task). However the code compiles fine.

I suggest we explore the option of making the copy constructor of ```InputParameters``` private to make this a compile-time error. @aeslaughter

**Comment by aeslaughter** [comment]
I will look into it, but it won't be until next week, I will be on vacation.

**Comment by permcody** [comment]
I completely agree. You'll want to remove assignment as well but maybe
not += hmm...

**Comment by friedmud** [comment]
Ummm... we use assignment all the time, right?

```
InputParameters params = Parent::validParams()
```

What's your plan for that?

**Comment by dschwen** [comment]
Yeah I know, I was hoping we could get by with only touching the copy constructor.

**Comment by permcody** [comment]
I can still see several places where parameters are being copied. For starters most of the `add<Foo>` methods in `FEProblem` so we can't remove the copy constructor just yet...

**Comment by friedmud** [comment]
A less drastic option is to make it protected/private and add friends (like for FEProblem).

**Comment by permcody** [comment]
Well, we probably don't want to be making copies of it anywhere. I
shouldn't be necessary.

**Comment by dschwen** [comment]
```
InputParameters params = Parent::validParams()
```

Is actually using the copy constructor (as @jwpeterson pointed out). So this might be tricky without forcing massive changes to how ```validParams``` operates. You cannot add a function template as a friend, can you? ;-)
