### ISSUE TITLE
Add test for unnecessary executable permissions on files to pre-test script 

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#5441]
Could we add a test to the pre-test scripts that checks for executable bits on files that shouldn't have it?  Maybe only allow it for .sh and .py files or something.  I'm specifically interested in the pre-test script for the applications, and I'm not really sure where that lives.

**Comment by permcody** [comment]
Yes and this belongs in the moose_build repo where @brianmoose is working. I'll move it for you.
