### ISSUE TITLE
Save-in variables are not evaluated at initial

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5459]
We are currently using the kernel save-in capability to add the residual contribution of kernels into variables. These save-in variables will be set when residual is evaluated. But at `FEProblem::initialSetup()`, there is no residual evaluation, so these variables are never set there.
These variables act like aux variables executed on linear. Can we do a pseudo residual evaluation at initial to set these variables?

I propose to call `computeResidualL2Norm()` in the `FEProblem::initialSetup()`, which returns a value possibly useful to some other places and make it not a completely waste of time. This function will also implicitly set the save-in variables.

**Comment by permcody** [comment]
This shouldn't be too bad to fix. We are doing a residual evaluation before the solve (initial residual). It may not be in `initialSetup()` but it's early.

**Comment by friedmud** [comment]
What is your goal here?  You want something that ONLY does save_in on initial?

**Comment by YaqiWang** [comment]
We use save-in to avoid evaluating a complicated postprocessor, which will need both boundary and volumetric integrals. This postprocessor needs to be evaluated at initial, which requires the save-in variables be evaluated on initial.

**Comment by friedmud** [comment]
I understand that... but I'm asking if it's ok if save_in continues to save_in later... or if you need to "turn off" save_in after initial...

**Comment by YaqiWang** [comment]
No, we do not need it to be turned off. Actually we want it to be functioning all the time.

**Comment by friedmud** [comment]
Ok - so the requirement here is that we need save_in to happen before initial postprocessors.  Gotcha

**Comment by YaqiWang** [comment]
I kinds of need this pretty urgently to make our custom transient executioner work. Do you want me send an ugly PR to start?

**Comment by permcody** [comment]
Well I'm not sure I ever want to see a so called "ugly" PR but we need to
start somewhere. We'll give you feedback once you send us a proposal.

**Comment by YaqiWang** [comment]
The lack of dependency resolution from the save-in variables to user objects and/or aux kernels will make the implementation awkward. Plus this is a rarely required feature, we decided to let application handle this and just provide necessary means for applications to do this. We will leave this issue open a while see if anybody else want this.

**Comment by YaqiWang** [comment]
I am closing this issue because we had a solution on application side and no general interest show up.
