### ISSUE TITLE
Make code coverage work with clang

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#5468]
We add `-lgcov` to `libmesh_LDFLAGS` for generating code coverage. However, clang does not have this library and actually does not need this flag at all.  Add a proper if-statement in our build scripts.

**Comment by permcody** [comment]
This wouldn't be Low Difficulty if we were using CMake!

**Comment by dschwen** [comment]
> This wouldn't be Low Difficulty if we were using CMake!

Wouldn't you use use a module for that, which alredy implements support for various compilers?
https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake

**Comment by permcody** [comment]
BZZZ, the correct answer is don't use Cmake.

**Comment by dschwen** [comment]
Sorry, I will report for further brain washing first thing tomorrow!
