### ISSUE TITLE
Extend EBSDReader to allow for additional data input

### ISSUE THREAD

**Issue by frombs** [idaholab/moose#5473]
High resolution electron backscatter diffraction (HR-EBSED) is an advanced characterization technique that allows for the estimation of dislocation density and elastic strain at each point in the EBSD mesh.  EBSDReader needs to be updated to allow for these additional properties to be stored and accessed.  This is needed for an upcoming milestone for the NEET project.

**Comment by dschwen** [comment]
Hey @frombs please check out my branch and let me know if this solves your problem.

**Comment by frombs** [comment]
@dschwen, thanks for the quick solution.  It looks like I will need to add "custom_columns=2" in my input file to include the 2 additional columns of data.  Is this correct?  Also, what is the best way to initialize the new properties?  In the past, I have used "ReconAuxVarIC" and "ReconAucVarICAction" which are still in Marmot.  Does these files need to include the "custom_columns" option as well? @tonkmr, do you have an opinion?

**Comment by dschwen** [comment]
Oh, I see, yes, we need to add this the ReconAuxVarIC/ReconAucVarICAction. I'll do that. We should probably move those over to moose sometime. ReconVarIC* is already there.
