### ISSUE TITLE
computeQpProperties should be virtual

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5478]
But some classes omit the ```virtual```. I'll fix this.

**Comment by jwpeterson** [comment]
You know this keyword is completely optional in derived classes, right?

**Comment by dschwen** [comment]
Yeah, it does not change functionality, but I think it improves readability, as users won't have to defer to the parent classes to see that the function is virtual. We are also consistently specifying it explicitly, except for six classes.

**Comment by dschwen** [comment]
I also changed the access qualifier from public to protected for the derived ```computeProperties``` for no good reason. I'll fix this because at best it doesn't matter, but at worst it could confuse people taking the code as an example.
