### ISSUE TITLE
Migration of radial return mapping from solid to tensor mechanics

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#5481]
Modeling of plasticity in continuum mechanics requires the use of a return mapping algorithm to correct the step stress increment back to the yield surface.  Currently there are two implementations of a return mapping algorithm in Tensor Mechanics:  ComputeMultiPlasticityStress, for complex non-associative surfaces with extensive debugging capabilities, and FiniteStrainHyperElasticViscoPlastic, for viscoplastic time-dependent problems.

In contrast to these two classes, the return mapping method currently implemented in Solid Mechanics employes a radial return mapping logarithm for a smooth von Mises yield surface for time-independent plasticity.  The Solid Mechanics algorithm is based on the computational method outline in Dunne and Petrinic in Introduction to Computational Plasticity which iterates on the increment of effective plastic strain.

The intent for this first pass migration is to move over the return mapping algorithm for J2 plasticity with linear strain hardening.

**Comment by cpritam** [comment]
A general question. @sapitts Why aren't you creating a general return mapping and making the radial return as a special case with associated simplifications?

**Comment by sapitts** [comment]
@cpritam , @bwspenc just came by to point out this oversight on my part too.  I'd like to get this commit in to hash out the names and to address Andrew's request for a physical discrete material.  It makes sense for you, Ben, Jason Hales, and I to sit down and find some commonalities between the radial mapping, the HEVP, and the smeared cracking and then for me to create the general return mapping class.  Thanks for the comment

**Comment by cpritam** [comment]
@sapitts - HEVP uses a different integration scheme and can be difficult to stich with the radial return algorithm. However, for incremental plasticity, keeping the algorithm general can also help to add rate dependent models.

**Comment by bwspenc** [comment]
@cpritam As @sapitts said, we discussed this, and I agree -- the base class needs to be more general.  It needs to support not just return mapping models, but any type of model so that we can compose together a set of models.  We can add in a base class later, but I'd really like to settle in a set of names that will work in a more general setting before we merge this commit so that we're not changing input file syntax later.

**Comment by sapitts** [comment]
@bwspenc with the new compute flag that Andrew created, is it important for all the return mapping materials to both a) be called to iterate by return mapping, and b) run successfully as a standalone material?  Or is it enough to have a plasticity material which only runs when called by the return mapping code?

**Comment by bwspenc** [comment]
@sapitts Sorry, still digging through old email and noticed your question.  Maybe you've resolved it by now.  I'd say that it would be nice if they could be run standalone, but if that doesn't work, it's not necessary.
