### ISSUE TITLE
Ordering of MeshModifiers Using Dependencies

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5529]
(As mentioned on the mailing list: https://groups.google.com/forum/#!topic/moose-users/fbc45K5fgtY )

With multiple `MeshModifer`s we need to have dependencies.  For instance, if you are trying to create a new block using `OrientedSubdomainBoundingBox` and then you want to create a sideset around that using `SidesetAroundSubdomain` you really need those to fire in that order...

I propose using our dependency resolution system to handle this.  We would add a new parameter to `MeshModifiers` called `depends_on` that would take a list of names of other `MeshModifers` that `MeshModifier` depends on... then we could execute them in the right order.

For instance:

```
[MeshModifiers]
  [./create_block]
    type = OrientedSubdomainBoundingBox
  [../]

  [./create_sideset]
    type = SidesetAroundSubdomain
    depends_on = 'create_block'
  [../]
[]
````

**Comment by andrsd** [comment]
I'd rather add some kind of information that the modifier is of a block or side type, then process the block ones and then process the side ones. That, however, assumes that side modifiers need only an existing block and that block modifiers are never dependent on sides. Is that true or not?

**Comment by friedmud** [comment]
Might work for side/block (might! I'm sure someone can come up with a `BlocksByExtrudingSidesets` MeshModifier) but definitely not for others.

For instance, how about a MeshModifier that deletes elements.  You might want to delete all elements along a sideset and then create a new sideset there.  OR you might want to lay down a sideset and then delete elements along it.  OR you might want to do both (create sideset, delete elements touching that sideset, then create a new sideset).

The point is MeshModifiers can do _anything_... and there's no way for us to figure out what order users want them to fire in...

**Comment by andrsd** [comment]
Yeah. After I posted my comment, I looked at the ones we already have and saw that it would not solve the whole problem... ;-( For example, if we had 3 `Transform` modifiers, we still would not know which order they should be applied in. And `Transform` is neither block nor side modifier...

**Comment by permcody** [comment]
The Transform modify takes a MultiMooseEnum which is ordered. At least
multiple transforms happen in the desired order but nothing else. I think
Derek's solution is reasonable to solve this problem.
