### ISSUE TITLE
MultiAppPostprocessorTransfer fails in parallel

### ISSUE THREAD

**Issue by smharper** [idaholab/moose#5530]
If one sub app is distributed across multiple procs, then `reduction_type = average` or `reduction_type = sum` will return -inf.

The error is in MultiAppPostprocessorTransfer.C.  If a proc is not the root proc for an app, then it will add `-std::numeric_limits<Real>::max();` into the reduction.

**Comment by smharper** [comment]
I think we should consider adding a `-p 3` job to our test suite.  I think it will catch a lot of multiapp bugs that only show up when n_procs > n_apps or when there is an unbalance number of apps per proc.  It would have caught this issue, for example.

**Comment by permcody** [comment]
I like the idea of having an odd number of processors for our tests. Will add it to the TODO list.
