### ISSUE TITLE
./run_tests --pbs is broken

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#5533]
Tests will not run on Falcon with the --pbs option.  The jobs are not submitted, and the script returns "FAILED (QSTAT INVALID RESULT)" for each test.

Is it possible to test the --pbs option automatically somehow and avoid this in the future?

**Comment by jasondhales** [comment]
Can someone sort out the code so that we don't have to set MOOSE_DIR?  In my case I have MOOSE as a submodule.  It seems like the testing code should use the MOOSE in the submodule automatically.  It used to do that.

**Comment by permcody** [comment]
Did you get this fixed? Just got back and I may be able to take a look if you are still having issues.

**Comment by milljm** [comment]
The cluster_launcher.py script was moved from framework/scripts to moose/scripts. Apparently there were some hard coded paths in there. The work-around right now is to have your MOOSE_DIR environment variable set.

I'll start looking into getting it fixed.
