### ISSUE TITLE
Rayleigh_HHT

### ISSUE THREAD

**Issue by sveerara** [idaholab/moose#5537]
Rayleigh damping and HHT time integration capabilities added in Solid Mechanics kernels StressDivergence.C and SolidMechInertialForce.C

**Comment by dschwen** [comment]
Hi @sveerara !  Who are you? We might want to talk about working on solid_mechanics. We have planned to replace this module with tensor_mechanics in the long run.

**Comment by sveerara** [comment]
Hi Daniel,

I am Swetha. I recently joined INL as a postdoc. Jason Hales mentioned that
the solid mechanics module will be replaced with tensor mechanics. So I
have made similar changes to the Tensor Mechanics module as well.

Thanks,
Swetha

**Comment by jwpeterson** [comment]
May not want to close this yet, there is another outstanding PR to add this functionality to the tensor_mechanics module as well...

**Comment by permcody** [comment]
Oops - thought we had a separate issue for that. I'll reopen.

**Comment by permcody** [comment]
So no can this issue be closed?
