### ISSUE TITLE
More selective restoration of MultiApps

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5554]
As discussed on the user list ( https://groups.google.com/forum/#!topic/moose-users/A7gAENsLfsU ) it would be nice to be more selective about when we restore a `MultiApp` during Picard iterations.

I propose adding a `needsRestoration()` method to MultiApp that signals whether or not a MultiApp MUST be restored each iteration.  It will default to `return true;` but MultiApps can selectively return false for efficiency.

**Comment by GiudGiud** [comment]
>  It will default to return true; but MultiApps can selectively return false for efficiency.

it actually defaults to false for TransientMultiApp
```
+bool
+TransientMultiApp::needsRestoration()
+{
+  return _sub_cycling || _catch_up || _auto_advance || _tolerate_failure || _detect_steady_state;
+}
```
any idea why we don't restore outside of these conditions?

**Comment by GiudGiud** [comment]
I looked at the moose-users discussion and got more info there
Some things to consider for why we may want to change how it works:

If we don't restore, we are starting from the time step n+1 solution to solve n-> n+1 again.

This is wrong if we have states (this can be material properties, or it can be any PP executed on timestep_begin)
It's wrong if we have transfers between subapps (executed post the missed restore but before the solve, a 'timestep_begin' becomes a 'timestep_end')
