### ISSUE TITLE
Add version stamp into csv file

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5561]
We usually have some sample problems, which is useful but too large to be regression test problems. We keep them in our code. But due to the change made in the code, those problems can be broken. When sometime later, we re-run these problems and noticed they were broken. It is painful to fix them. We planned to create a pseudo golden file, such as a small csv file but not the full exodus file (could be large). It would be better to stamp the csv file with the current code version number. So can we write this number in Framework Information as well as the application version number into the csv file? Or maybe you can come up a better solution for us. Thanks.

**Comment by friedmud** [comment]
We should really run these as "heavy tests".  The BISON guys have theirs scripted to run every night.

With new testing resources coming online and new capability in MooseBuild I think we should start incorporating these kinds of things into the testing system more.

**Comment by friedmud** [comment]
To address your actual Issue here: I vote against this.  CSV files should be clean so you can easily read them into any software (like excel, Marian, etc) adding a header greatly complicated things.

If you commit a "good" file then it will have a Git hash in Git that is the version of the code it was run with... so just check that out.

**Comment by YaqiWang** [comment]
Oh I do not know exodus has this info. Then we may just use exodus file for now.

**Comment by dschwen** [comment]
Can we force dumping a copy of the console output into a file through an
input parameter? I know you could use > but something the user wouldn't
have to remember and that worked reliably in parallel would be nice. That
file would contain a record of the git hash of the application.

**Comment by YaqiWang** [comment]
Seems Console can do the job but never tried. I also figured the standard output file maybe a good thing to keep.
