### ISSUE TITLE
Assembly::cacheJacobianBlock triggers DenseMatrix assert

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5574]
A `libMesh::DenseMatrix` is accessed out of bounds trough `operator ()` in `Assembly::cacheJacobianBlock`. The Dense matrix is generated by `Assembly::jacobianBlock` and is indexed via a vector of DOF IDs. At the beginning of `Assembly::cacheJacobianBlock` the sizes of the passed in DOF vectors (for the i and j variables) matches the size of the matrix exactly. But the DOF vectors are passed to `_dof_map.constrain_element_matrix(jac_block, di, dj, false)` (Assembly.C:1186), which results in a **growth** of the `di` and `dj` DOF vectors resulting in accessing the matrix out of bounds.

**Comment by dschwen** [comment]
I added two commits to output DOF vector sizes and jacobian block matrix size as well as a small input file to reproduce this issue.

**Comment by andrsd** [comment]
I thought that the `DenseMatrix` gets resized as well when calling `constrain_element_matrix`.  If that's not the case, I wonder how `SparseMatrix::add_matrix` handles the different sizes of the `DenseMatrix` and the DoF vectors. 

BTW: the growth of the di, dj vectors is caused when constraints are available (for example adaptivity is on).

Maybe @roystgnr can help us here...

**Comment by dschwen** [comment]
be4d2e1 is now stripped down so far it only uses framework classes. I doubt this can be reduced further. If the Preconditioning block is removed the error disappears (as it is triggered on the a,b off-diagonal block) if the Periodic boundarues are removed the error disappears as well.

**Comment by andrsd** [comment]
Periodic BCs will introduce constraints, so you have to have that on (or adaptivity).

**Comment by dschwen** [comment]
The error happens exactly when you have PBCs on one variable and not on the other but force the construction of an off-diagonal Jacobian block between them (using SMP with full=true).

That setup might not make a whole lot of sense in the first place, but it should at least throw a sensible error (and not result in out of bounds accesses in debug)!

**Comment by dschwen** [comment]
I'm closing this. The test input does not trigger an assertion anymore.
