### ISSUE TITLE
Call initialSetup() of constitutive models in SolidModel.

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#5580]
Add a for loop in the initialSetup() of SolidModel that loops over all constitutive models and calls their respective initialSetup().

The reason for doing this because it is desired to perform some checks on initialSetup in material models created using createConstitutiveModel.

**Comment by permcody** [comment]
Will those methods be called twice after this modification or while you put a state variable in the object to track if initialSetup() has already been called?

**Comment by gambka** [comment]
The initialSetup() methods should not be called twice for the constitutive models.  In the materials I'm working with, just including an initialSetup() method will result in it in never being called.  I think this is because these constitutive models are being generated using createConsutitiveModel in another material that inherits from SolidModel. 

According to Andrew this results in MOOSE not being aware of these constitutive models and therefore the initialSetup() method is never called.  Currently in SolidModel there is logic to collect on the constitutive models but there is nothing to call the initialSetup() method of the constitutive models created using createConsitutiveModel.  I have put a pull request with the small code change that results in initialSetup() being called in these models.  A test in modules is currently failing with a negative Jacobian error that I'm currently investigating.
