### ISSUE TITLE
Some tests are failing coverage checks but moose_build is missing them

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5589]
There are two issues here. First the recipe is failing to report failed tests which should be a quick recipe update. Second, there are a few issues with actual MOOSE tests under the coverage configuration that need to be resolved.

**Comment by permcody** [comment]
@brianmoose - This may not be an issue anymore. For background, the old coverage step didn't check the `run_tests` exit code and certain coverage tests were always failing. You've re-written that step altogether so this issue as it was doesn't exist anymore. I've looked at the coverage steps and don't see any errors. I didn't specify the "other issues" which is terrible for a ticket description. I think I'll close this one and reopen a new ticket in CIVET if bad things happen in the future.

**Comment by brianmoose** [comment]
In the moose coverage recipe it still doesn't check the exit status of
run_tests. There was a comment in there "Run tests, but do not error out.
We will get _some_ coverage anyway".
Do you wan to enable the exit code check?

**Comment by permcody** [comment]
Yes, if not they tend to pile up failures. At the very least we should
shade the box orange so we can see when there's something wrong.
