### ISSUE TITLE
Issue with end_time using Transient executioner

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#5590]
The attached input file should take 2000 time steps (`end_time = 2`, `dt = 1e-3`), but it takes 2001 steps ending with:

```
Time Step 2001, time = 2
                dt = 1.09468e-13
 0 Nonlinear |R| = 6.289954e-01
 1 Nonlinear |R| = 5.745930e+09
 Solve Converged!
```

Input file to reproduce:

```
[GlobalParams]
  implicit = false
[]

[Mesh]
  type = GeneratedMesh
  dim = 1
  nx =  100
  xmin =  0.
  xmax = 10.
[]

[Variables]
  [./u]
    order = FIRST
    family = LAGRANGE
    [./InitialCondition]
      type = FunctionIC
      function = ic_func
    [../]
  [../]
[]

[Functions]
  [./ic_func]
    axis = 0
    type = PiecewiseLinear
    x = ' 0.  5.   5.00001 10.'
    y = ' 3.  3.   1.       1.'
  [../]
[]

[Kernels]
  [./time]
    type = TimeDerivative
    variable = u
    implicit=true
  [../]

  [./advection]
    type = Convection
    variable = u
    x = 1.
    y = 0.
    z = 0.
  [../]

  [./diffusion]
    type = CoefDiffusion
    variable = u
    coef = 0.02
  [../]
[]

[BCs]
  [./left_u]
    type = DirichletBC
    variable = u
    boundary = left
    value = 3.
  [../]

  [./right_u]
    type = DirichletBC
    variable = u
    boundary = right
    value = 1.
  [../]
[]

[Executioner]
  type = Transient
  scheme = 'explicit-euler'
  solve_type = 'LINEAR'
  l_tol = 1.e-10
  dt = 1.e-3

  nl_rel_tol = 1e-12
  nl_abs_tol = 1e-6
  nl_max_its = 1

  end_time = 2.
[]

[Outputs]
  output_initial = true
  file_base = out_explicit
  exodus = true
[]
```

**Comment by permcody** [comment]
This is just normal round off error. We have a parameter `timestep_tolerance` in `Transient` for dealing with this. Just set it to 1e-13 or lower for this case, it has a very tight default tolerance.

**Comment by permcody** [comment]
Did you get this to work? I still don't think this is a bug.

**Comment by andrsd** [comment]
I did not do anything about this. I can lower the priority to minor, because I want to revisit the code before closing...

**Comment by permcody** [comment]
Ok fair enough, I did verify that adjusting the tolerance to just below 1e-13 does indeed give you the right behavior. Dang floating point arithmetic!

**Comment by permcody** [comment]
Not an issue, this is related to floating point roundoff.

**Comment by YaqiWang** [comment]
This is actually quite annoying. We have multiple reports from multiple rattlesnake users. It is not very friendly to ask users to put an extra parameter to make the behavior right. Can we do something?

**Comment by YaqiWang** [comment]
From Mark DeHart: The default tolerance is obviously too small.  Real world physics happen in seconds, not micro-seconds.  10e-8 ought to be a good default.  I agree with this. I do not know who and why 1e-13 was come up with, but changing it to 1e-8 sounds a reasonable request to me.

**Comment by YaqiWang** [comment]
Will do.
