### ISSUE TITLE
Peacock sometimes doesn't render MeshModifiers in the InputFile view

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5593]
Despite all the screwy logic we've put in to run --mesh-only when needed it's still not correct if you start with an exodus file AND have mesh modifiers enabled.

@friedmud - I know you said we should _always_ use MeshModifierRender but I think one of the neutronics guys ran into an issue where Peacock was very slow because they had huge meshes. We can hack in one more case for now or just leave it. Not many people run into this but it was annoying for me to build a new test case...

**Comment by friedmud** [comment]
I would rather detect when the mesh is large and just not show any mesh if it's over a certain size... or have a checkbox next to the mesh view to turn it on and off (so you can turn it off if your stuff is big, etc.)

**Comment by permcody** [comment]
That's a good suggestion.

**Comment by permcody** [comment]
This ticket is specific to the old peacock. It doesn't apply to the current version.
