### ISSUE TITLE
Clean-up Outputs syntax

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5603]
- Make the default `output_on = 'initial timestep_end'`
- Remove the output toggles and make people use 'output_on'

This cleanup is in preparation for #5229

**Comment by aeslaughter** [comment]
- Should we default the console to output linear residuals, we set the print flag nearly everywhere
- Removing the toggles requires a stork patch
@friedmud @permcody

**Comment by friedmud** [comment]
I think I'm ok with enabling linear iterations by default.

Our defaults should really reflect the thing most people want to do.

In fact, I've received quite a few questions lately about why ILU is our default preconditioner.  Which is really a good question.  I wonder if we should default to Hypre...

Anyway... that's off topic... but yes... I think we should evolve our defaults over time as we see what our users do and 99% of the time they have linear residuals coming out (and should!)

**Comment by permcody** [comment]
Thinking out loud. If there's an API in PETSc (haven't checked) to get the
active preconditioner, we could just print it out as part of our
information. I don't think we should try to just print it out on our own on
the MOOSE side. Who knows when PETSc will change things and there are only
a billion CLI options that we might have to inspect to get PC options
correctly reported back to the user.

Cody

**Comment by aeslaughter** [comment]
We also set `print_perf_log=true` in nearly every test, if I recall the main reason for this is test timing and not user driven. If this is the case then run_tests should set this flag, not the input file.

**Comment by friedmud** [comment]
That's a good point Andrew.  I would be for adding this to run_tests and
removing it from the input files.

Derek

**Comment by aeslaughter** [comment]
@permcody @friedmud 

Should the default be to output initial condition for transient solve and not for steady?

**Comment by YaqiWang** [comment]
I think Steady and eigen executioners should not output initial by default. It actually may confuse users because they may be expect only one solution but now get two in the output.

**Comment by aeslaughter** [comment]
I tend to agree with Yaqi, except sometimes Steady solves do have initial conditions and then those would be turned off by default thus, by not all information is provided.

**Comment by permcody** [comment]
I think this is good. My vote would be to turn off initial conditions for steady solves (and I suppose Eigen solves too). Even if they exists, they are rarely impactful on the final steady solution. In those cases, they could be turned on.

**Comment by friedmud** [comment]
I don't like having inconsistency.

The "initial condition" is important in steady state solves too... it's the initial guess and sometimes plays a LARGE roll in convergence.

What about people who do only one timestep using a Transient Executioner?  They're going to get "two" timesteps worth of output as well.

All that needs to be done is have clear documentation: "The initial values are always output as timestep 0".  Just add it to the documentation and let's make sure everyone knows it... then no one will be confused.

**Comment by aeslaughter** [comment]
I am with @friedmud, consistency is important.

**Comment by permcody** [comment]
Ok - I don't have any strong convictions one way or the other. Go for it.

**Comment by aeslaughter** [comment]
This is ready if anyone wants to pull the trigger.
