### ISSUE TITLE
Bug with MeshModifier dependencies

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#5627]
I think commit e8ddc5a may have broken, or at least changed, something with `tests/mesh_modifiers/rename_block/rename1.i`.  Unfortunately exodiff on most systems is not detecting the difference for some reason.

`ncdump gold/rename1_out.e` reports:
```
eb_prop1 = 2, 4 ;
eb_names =
  "simply_two",
  "" ;
```

While `ncdump rename1_out.e` says:
```
eb_prop1 = 2, 3 ;
eb_names =
  "two_was_zero",
  "three" ;
```

Based on the names, I think the current output is actually correct and the file should be regolded, but I am concerned why exodiff only reports this difference on my workstation -- the test passes on @aeslaughter's machine and the build boxes...

**Comment by jwpeterson** [comment]
I also get a different result on Linux vs. OSX (also not detected by exodiff):

`ncdump rename1_out.e`
```
eb_prop1 = 1, 2 ;
eb_names =
  "one",
  "two_was_zero" ;
```

@WilkAndy, I believe this is your test, and it does not say what the expected result of the long sequence of renaming modifiers is supposed to be... do you recall anything about this test?

**Comment by jwpeterson** [comment]
Turns out it's a simple 9 step process (if we go by the order of MeshModifiers laid out in the input file):

* Step 1:
Subdomain Bounding box creates a small subdomain 1 in the bottom corner.

* Step 2:
Subdomains renumbered:
0->2
1->3

* Step 3:
"ename_no_effect" does nothing.

* Step 4:
Subdomains renamed:
'2' -> 'two_was_zero'

* Step 5:
Subdomains renamed:
'two_was_zero' -> 'simply_two'

* Step 6:
Subdomains renamed:
'3' -> 'three'

* Step 7: Subdomain gets new ID
Subdomain 'three' gets block ID 4 (but keeps name 'three' --  or does this unset the name as in the gold?)

* Step 8:
"another_no_effect" should do nothing

* Step 9:
'should_no_do_anything" should do nothing


So, I think the final output *should* be:
```
eb_prop1 = 2, 4;
eb_names = "simply_two", "three";
```

or possibly:
```
eb_prop1 = 2, 4;
eb_names = "simply_two", "";
```

Which is not currently the output on either OSX or Linux...

**Comment by jwpeterson** [comment]
And, just to clarify a bit more, this MeshModifier: 
```
  [./three_to_4]
    type = RenameBlock
    old_block_name = 'three'
    new_block_id = 4
  [../]
```
creates a new, unnamed block with ID 4, so its name should be the empty string in the Exodus file.  In other words, the gold file is correct, and the outputs on both Linux and OSX are wrong (and don't agree with each other).

**Comment by jwpeterson** [comment]
Here's the order of MeshModifiers, as produced by the dependency resolver.  Neither is correct, nor do they match one another.  @permcody, did you use `MooseRandom` to determine the ordering? :smile: 

OSX order:
```
should_not_do_anything
three_to_4
rename_blockID_3
rename_block2
rename
ename_no_effect
sbb0
re_id
another_no_effect
```

Linux order:
```
rename_block2
re_id
sbb0
ename_no_effect
rename
rename_blockID_3
three_to_4
another_no_effect
should_not_do_anything
```

**Comment by jwpeterson** [comment]
I furthermore don't see how the dependency resolution is supposed to even work in this case, since the *only* thing that determines the dependencies in this example is the ordering of the MeshModifiers in the input file.

**Comment by permcody** [comment]
The order used to be mostly or hopefully determined by input file order.
However after I added dependency resolution, it would now be determined by
pointer value of the actual objects (somewhat predictable, but not reliable
and sensitive to OS, etc.). The right solution is to add the "depends_on"
parameter to ensure they run in the desired order.

**Comment by jwpeterson** [comment]
OK, didn't know about depends_on, I will try to fix this test using that.

**Comment by WilkAndy** [comment]
yes, thanks guys - the tests assume the modifiers are applied in the input-file order.  actually, when i wrote the tests i thought that's what happened for all moose objects, but that's definitely wrong now,

a

________________________________________

**Comment by permcody** [comment]
That's not a bad assumption but since we don't control the full stack of
tools and operating systems can sometimes doing things in a different order
we prefer to control these kinds of things explicitly. Ironically by me
adding explicit control it broke your otherwise working test.
