### ISSUE TITLE
ElasticEnergy should provide derivatives w.r.t. strain

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5631]
And the ```CahnHilliard``` and split CH kernels should use those in their residual and Jacobian terms. @laagesen could start looking at this. We'll need to figure out a clean way to integrate this with the ```DerivativeMaterialInterface```.

**Comment by dschwen** [comment]
We will have to provide ```dtotal_strain/ddisp_x``` etc. and/or ```delastic_strain/ddisp_x``` etc. This should probably be done at ```ComputeStrainBase``` level. In there we need to re-evaluate the fetching of _old_ properties (@sapitts you fetch them when the problem is transient, but they are **not** needed for small strain formulations. We can probably use input parameter magic to avoid stateful properties in small strain cases - but I'll open a separate issue for that).
It looks to me like this will require second derivatives of the displacement variables (```coupledSecond```). The strain derivative will be a tensor property that will be used by the elastic energy material to add the missing _scalar_ derivatives of the free energy **w.r.t. the displacements**.
Ping @tonkmr

**Comment by dschwen** [comment]
Solution (example in 3d without loss of generality):

* create nine variables that contain the components of the gradients of the three displacement variables (```g_xx```, ```g_xy```, ... ```g_zz```).
* create nine kernels to set the values of the variables (```R = g_ij - _grad_disp[i](j)```)
* strain is now a function of these g_ij variables! create material to supply the derivatives of strain w.r.t. g_ij (this is ultra simple matrices look like below)

```
(1 0 0)  (0   0 1/2)  (0 0 0)
(0 0 0)  (0   0 0  )  (0 0 0)
(0 0 0)  (1/2 0 0  )  (0 0 1)
etc.
```

* create an action to add the variables, kernels, and the material.
* Now we can use all existing components such as ```ElasticEnergy``` material (if we add g)ij as coupled variables to them!)

**Comment by dschwen** [comment]
@laagesen we need to implement the off diagonal Jacobian for the ```GradientComponent``` Kernel (w.r.t. the displacement variable). Do you feel up to it?

**Comment by laagesen** [comment]
Sure I can give it a go.

**Comment by SudiptaBiswas** [comment]
Does PR #5677 only work with non-split CH? What about the split-version?

**Comment by SudiptaBiswas** [comment]
DisplacementGradientAction does not converge with splitCH kernels.

**Comment by dschwen** [comment]
No and neither should it. It is only for the non split case.

**Comment by SudiptaBiswas** [comment]
Elastic energy goes UP for the split version as well. Is that something yet to come?

**Comment by dschwen** [comment]
I believe this is fully resolved. We do need to add documentation for this on the wiki though @laagesen, remind me if I forget :-).
