### ISSUE TITLE
PoroMechanics should use a displacements variable vector as well

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5637]
@WilkAndy, it would be cool if the PoroMechanics action would also accept the new
```
displacements = 'disp_x disp_y disp_z'
```
parameter style. In TensorMechanics we have deprecated the old
```
disp_x = disp_x
disp_y = disp_y
disp_z = disp_z
```
style. This makes it easier to support RZ coordinate systems etc.

**Comment by WilkAndy** [comment]
i totally agree.  i'm away for a week, and might have time after that -  it's not a lot of work but i'm not really working on this stuff much at the moment,

a

________________________________________
