### ISSUE TITLE
Error if variable not found for MultiAppPostprocessorInterpolationTransfer

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5639]
If you specify `variable = stuff` in a `MultiAppPostprocessorInterpolationTransfer` and `stuff` doesn't exist... you currently get a segfault in an optimized binary!

In debug you end up getting a fairly cryptic libMesh error.

This should really give you a nice MooseError... even in optimized mode.

**Comment by permcody** [comment]
`variable` isn't a valid parameter for `MultiAppPostprocessorTransfer`

**Comment by friedmud** [comment]
Sorry... mean `MultiAppPostprocessorInterpolationTransfer`... I'll edit the title
