### ISSUE TITLE
ComputeStrainBase should only request stateful material properties in needed

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5642]
The stateful displacement and displacement gradient properties should only be set up if absolutely necessary. We can introduce a (private) bool input parameter that gets set by derived classes. Or add an additional constructor parameter.
I prefer the input parameter way (```stateful_displacements```). We can default it to ```false``` and call ```params.set<bool>("stateful_displacements") = true``` in derived classes if necessary.

@tonkmr I vaguely remember that we had some discussions about this. Why did we not chose this solution from the start? Is there a catch?

**Comment by friedmud** [comment]
What cases are there where the "old" value can't be declared in the derived class instead?

**Comment by dschwen** [comment]
Yeah, I was wondering about this as well. I had long talks with Mike about this and I kind of forgot why we ended up with this solution in the first place. I think we wanted to avoid the code duplication as we have to declare and fetch the old gradients in two different derived classes. I have a patch to at least move the old displacement (not the gradient) into the one derived class where it is needed.

**Comment by friedmud** [comment]
I see (about the code duplication) another option (though it may be too heavy handed in this case) is to have an intermediate base class that declares the stateful stuff... so anyone that needs that would inherit from THAT class instead.

The InputParameters option isn't bad either.., just doesn't quite feel as clean.

**Comment by dschwen** [comment]
We have a conditional in the code; it checks if ```_fe_problem.isTransient()```. Is that even necessary? Shouldn't the stateful material system automatically refuse to generate state data if the solve is not transient?

**Comment by friedmud** [comment]
I wonder if @YaqiWang has some Executioners that are NOT transient but depend on stateful material properties.

What is "transient" is going to be tough to define in my new Executioner system... so we'll definitely have to revisit that whole thing soon...
