### ISSUE TITLE
PBS option to append string to output file names

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#5649]
We'd like to be able to use "./run_tests --pbs" where it appends a string to all output file names.  Something like "./run_tests --pbs fred --pbs_out_tag my_string" would result in the typical Exodus output file being named <baseNameFromInputFile>_my_string.e.

**Comment by aeslaughter** [comment]
This should be able to be accomplished via the python by appending
"Outputs/file_base='my_new_file_base_name'" to the executable being run.

This would require that there was no Exodus sub-block that also sets
file_base in the input file.

**Comment by permcody** [comment]
Actually we chatted about this already. We may or may not handle this at the MOOSE level. We really need to save these files on a central server for comparison over time. Whether that happens in moose_build (civet), moose or run_tests is to be decided.

**Comment by jasondhales** [comment]
The "Outputs/file_base='new_name'" works great when running a single
problem, but we want to add a unique tag to the output file names of all
tests run with run_tests.

On Tue, Sep 1, 2015 at 1:37 PM, Cody Permann <notifications@github.com>
wrote:

> Actually we chatted about this already. We may or may not handle this at
> the MOOSE level. We really need to save these files on a central server for
> comparison over time. Whether that happens in moose_build (civet), moose or
> run_tests is to be decided.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5649#issuecomment-136836200>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by permcody** [comment]
@jasondhales - I'd like to get this resolved for you. Either I don't recall or we didn't capture quite enough information in this ticket, but how do you plan to use this tag again? I believe you wanted to track information over time which is why I said something about storing it on a central server. That really is important but as a first step we can at least start making unique names. Thinking about this some more, the `ClusterLauncher` (which is used by the `--pbs` options) is already setup to do this now. If you launch the same script multiple times in the same directory the `ClusterLauncher` you get the next serial number appended to your directory.

i.e. `test_01_001 test_01_002 test_01_003` etc.

The trick would be not to clean any of these files up.

**Comment by jasondhales** [comment]
Yes, that is one option, and we are currently storing them that way.  That
keeps the directory structure around, and we don't really need that.  What
would be better is to collect all the results files (csv files) in one
place.  If they had unique names (test name plus date) plus some way to
pull out the results files only and not other csv files, we'd have what we
need.

We could go into every assessment case input file and set the base name to
be something we could extract easily (e.g., <test_name>_EXTRACT_ME).  Then,
after the run, we could extract the relevant files and add their date stamp
to the file name.  Then we could delete the test directories.

Seems like that would work.  Other ideas?

On Thu, Oct 1, 2015 at 8:48 AM, Cody Permann <notifications@github.com>
wrote:

> @jasondhales <https://github.com/jasondhales> - I'd like to get this
> resolved for you. Either I don't recall or we didn't capture quite enough
> information in this ticket, but how do you plan to use this tag again? I
> believe you wanted to track information over time which is why I said
> something about storing it on a central server. That really is important
> but as a first step we can at least start making unique names. Thinking
> about this some more, the ClusterLauncher (which is used by the --pbs
> options) is already setup to do this now. If you launch the same script
> multiple times in the same directory the ClusterLauncher you get the next
> serial number appended to your directory.
>
> i.e. test_01_001 test_01_002 test_01_003 etc.
>
> The trick would be not to clean any of these files up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5649#issuecomment-144750322>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by permcody** [comment]
I was thinking about this some more and another general problem with this whole idea is that with "--pbs" the TestHarness may not be the last thing that touches those output files. It's conceivable that you launch all the jobs with a cron job and then never re-run script with the status option to check them. If you failed to perform that step after _every_ job had completed you may miss some of this rename and extract logic which feels kind of hackish.

It really would be nice if we could just have MOOSE handle the name substitution for you based on a parameter value like this:

`
[Outputs]
  [./csv]
    type = CSV
    file_base = case1_EXTRACT_$DATE$
  [../]
[]
`

This design would ensure that the file gets created correctly right through MOOSE. I'm actively trying to design just such a parameter substitution system in MOOSE right now for #4840 so this fits right into that scheme.  Your cleanup script would still need to extract and store these completed files from the run somewhere but you could do that with your idea that you just proposed above.

Thoughts?

@YaqiWang - Please see this discussion, it is also relevant to the other issue we are currently discussing. I'd like to get this design right from the start.

**Comment by jasondhales** [comment]
Seems like the parameter substitution idea would be useful in several
ways.  I vote to have this available on the command line.  Something like
./myapp-opt -i input.i --sub="DATE=20151001".  Then the parser would
replace zero or more instances of DATE with 20151001.

On Thu, Oct 1, 2015 at 10:55 AM, Cody Permann <notifications@github.com>
wrote:

> I was thinking about this some more and another general problem with this
> whole idea is that with "--pbs" the TestHarness may not be the last thing
> that touches those output files. It's conceivable that you launch all the
> jobs with a cron job and then never re-run script with the status option to
> check them. If you failed to perform that step after *every* job had
> completed you may miss some of this rename and extract logic which feels
> kind of hackish.
>
> It really would be nice if we could just have MOOSE handle the name
> substitution for you based on a parameter value like this:
>
>
> [Outputs]
> [./csv]
> type = CSV
> file_base = case1_EXTRACT_$DATE$
> [../]
> []
>
> This design would ensure that the file gets created correctly right
> through MOOSE. I'm actively trying to design just such a parameter
> substitution system in MOOSE right now for #4840
> <https://github.com/idaholab/moose/issues/4840> so this fits right into
> that scheme. Your cleanup script would still need to extract and store
> these completed files from the run somewhere but you could do that with
> your idea that you just proposed above.
>
> Thoughts?
>
> @YaqiWang <https://github.com/YaqiWang> - Please see this discussion, it
> is also relevant to the other issue we are currently discussing. I'd like
> to get this design right from the start.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5649#issuecomment-144785662>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by permcody** [comment]
In my design I'm thinking they'll be a base class callback that is called first to do simple replacement of reserved strings (DATE) or simple substitutions that don't need user intervention. However there will also be a user-overridable callback for more complicated parameter generation. Whatever the system, CLI overrides should definitely be incorporated.
