### ISSUE TITLE
Spurious warning about checkpoint system deleting material checkpoints

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5653]
@friedmud removed the material checkpoint files during the tiger team (don't have the commit handy). There is a warning about files not being deleted in Checkpoint.C

**Comment by friedmud** [comment]
How did this make it through the testing system?

**Comment by permcody** [comment]
I'll investigate, If I had to guess I'm going to say that we may not be passing --error with our checkpoint tests. I'll see if I can fix that up too

**Comment by permcody** [comment]
Wow - We are NOT passing `--error` when running `run_tests`. I could have sworn we put that in, but I guess I'm just remembering adding `--error-unused` which is completely different. I also did some work to make --error work better with the parser but it never got added to the `TestHarness`. This really all needs to be fixed up. It looks like we have seven tests complaining in moose_test when I pass the new argument.
