### ISSUE TITLE
Add Automatic Differentiation To MOOSE

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5658]
It's that time.

MOOSE needs programmatic automatic differentiation that's built right in.

This is going to start small (just in Kernels) and then grow out from there.

I'm using @roystgnr 's MetaPhysicL package ( https://github.com/roystgnr/MetaPhysicL ) to do the heavy lifting.

First implementation will be a little rough... but will get the job done.

Look for a PR tonight... I already have this working.

**Comment by friedmud** [comment]
TODO:
 - [x] Add MetaPhysicL package to MOOSE contrib
 - [x] Create ADKernel base class that only has `computeQpResidual` and compute the Jacobian automatically (for diagonal block)
 - [ ] Allow coupling to AD values
 - [ ] Implement off-diagonal Jacobian computation
 - [ ] Implement AD for gradients and add ADDiffusion
 - [ ] Test derivatives of Material properties
 - [ ] Deal with Stateful properties (they need to have their derivative information cleared
 - [ ] Undo the 100 DoF per element restriction (needs sparse derivative computation)
 - [ ] AD for neighbor and coupled neighbor (DG)
 - [ ] AD for scalar
 - [ ] AD for nodal
 - [ ] AD in BCs
 - [ ] Stretch: AD for Aux? (propogate derivatives through Auxiliary computation?
 - [ ] Stretch: AD for Postprocessors (propogate derivatives through PP computation??!!?!!).  Will require n_dofs long derivative information.

**Comment by lw4992** [comment]
Cool!

**Comment by friedmud** [comment]
Just leaving a note here while I'm thinking about it.  To enable computing _only_ the residual what we're going to need to be able to do is template `ADKernel` on `ScalarType`... where `ScalarType` is either `ADReal` or `Real`.  This is, again, why it's going to be important to be able to retrieve material properties either way.

Once it's templated then we can make an instantiation of it both ways - so that we can compute it with `Real` when we're just computing the residual.

I'm not 100% sure yet if we might not have to be able to do the same thing for Material.

This somewhat goes against my entire viewpoint on templating in a finite-element code... I don't typically like to do this... but I'm also not sure I see another way.  Maybe something will present itself.

Years ago I played with trying to turn off the derivative calculation in `DualNumber` when we were computing the residual - and while it worked... it didn't give much speedup because it put an `if` in every arithmetic computation!  But maybe there is something there... maybe there is a better way...

**Comment by friedmud** [comment]
Ok - Materials that do AD should derive from `ADMaterial` and if they declare material properties that will use AD types they should call `declareADMaterialProperty<ScalarType>()`.  The reason this is templated on `ScalarType` is so that we can make instances of `ADMaterial`s that are both AD and non-AD and we can make template specializations of `declareADMaterialProperty<>()` so that when `ScalarType` is `Real` all it does is call `declareMaterialProperty()`.

The specialization of `declareADMaterialProperty<ADReal>(MatPropType)` will attempt to grab a function called `convertToNonAD<MatPropType>()`.  That function is similar in a lot of ways to `dataStore()` and `dataLoad()`... it's a free templated function that you are required to override in order to be able to declare an AD type material property.  It's function is to take a computed AD type material property and produce a non-AD type material property.

**Comment by lindsayad** [comment]
I think we've cleared most of the checklist in https://github.com/idaholab/moose/issues/5658#issuecomment-137300832, so I'm going to mark this as closed. Some unchecked items have been discussed in detail, like AD aux, and we have decided not to pursue it (at least for now). For remaining unchecked items, we can create different issues to zero in on them.
