### ISSUE TITLE
Implement Real-Time Updater for Eclipse Integrated Computational Environment

### ISSUE THREAD

**Issue by amccaskey** [idaholab/moose#5663]
An outstanding feature request from the MOOSE Dev Team and MOOSE application developers/users is for real-time updating, in ICE, of Postprocessor data. As MOOSE simulations are running, a simple XY plot of user-specified Postprocessor data should be updating in real time with information provided by the executing simulation.

**Comment by dschwen** [comment]
This sounds like more of an ice issue than a mouse issue. You could already tail the PP output files (like the CSV output) and display the data in real time.

**Comment by amccaskey** [comment]
Hey Daniel, you could do that, but that seems like more of a work-around. We'd like something a little more direct because ICE needs to be able to get data back for both local and remote executions. We're targeting communication over a web socket, since the ICE Core is an HTTP server. 

Through discussions with Cody and Andrew, we decided to develop a new Output subclass that uses ICE C++ Updater library (https://github.com/eclipse/ice/tree/master/native/org.eclipse.ice.updater). This is now implemented in https://github.com/amccaskey/moose. 

We've added an updated ICE Updater (moose-ified) to framework/contrib, and provided a new ICEUpdater AdvancedOutput<Output> subclass that has an Updater instance and uses it to connect to ICE and HTTP Post updates messages.

**Comment by amccaskey** [comment]
Just to keep this public, I wanted to provide a discussion of the way we're testing this: 

Basically, we wrote a new python script in python > TestHarness > testers that subclasses RunApp. Its implementation of getCommand starts a web server that listens at localhost:8080/ice/update for posts, and checks that it found the correct number of posts. We added a test case with an input file that uses the ICEUpdater for moose_test. 

For the web server we used web.py http://webpy.org/ which seems to be freely available.

I'm interested in any feedback or alternatives for testing this.

**Comment by dschwen** [comment]
Interesting. Does this support specifying a custom update URL so that you
can stream updates over reverse ssh tunnels?

**Comment by amccaskey** [comment]
That's a good question. With this implementation, you can specify a custom URL for the HTTP Post but it does nothing for reverse ssh tunnels. 

However, you should be able to set up reverse ssh tunnels in ICE through our integration with the Eclipse Parallel Tools Platform, I just haven't tried it yet.

**Comment by permcody** [comment]
I'm in support of this. My only suggest is that we try to avoid adding additional dependencies where possible. I suggest using https://docs.python.org/2/library/simplehttpserver.html as the test server which is already part of the Python 2.x distribution.

**Comment by amccaskey** [comment]
I think that sounds good. I'll look into SimpleHTTPServer and see if I can get it to receive posts at the localhost:8080/ice/update URL that the ICEUpdater is using.

**Comment by amccaskey** [comment]
I removed the dependence on web.py, should be ready for the pull request. I would just ask that you guys double check me on correctly integrating framework/contrib/iceupdater into the build.

**Comment by permcody** [comment]
Go ahead and open your PR, we'll review it.

**Comment by jwpeterson** [comment]
Closing this as the original PR was merged, but feel free to reference it in future work.
