### ISSUE TITLE
Control Logic Improvments

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5680]
- [x] Add --controllable-dump execution method to show all possible controls as well as a --show-controls that shows in the information record the parameters being controlled
- [x] Use a set method rather than the vector pointer stuff
- [ ] Add ability to use scripting language to control MOOSE
- [x] Update object naming to support input file and generic "_moose_base" defining of control parameters
  (see #5662)
- [x] Add ability to tag objects in the input file for grouping in control logic access
- [x] Add ability to tag parameters so that parameters with different names can be accessed via a single tag.
- [x] ~~Remove the n_thread copies of InputParameters, this will involve injecting thread id into MooseObject (likely with a method, `setThreadID`, that is called by factory::create())~~
- [x] Move Control objects into there own system and warehouse
- [x] Re-factor MOOSE warehouses to allow for the Control system to activate/deactivate objects in a generic fashion.
- [ ] Remove TimePeriods (TransientInterface::isActive) in favor of Control based toggles
- [ ] Cache parameters for subsequent calls to `setControllableValue`

**Comment by dschwen** [comment]
![anim 0106](https://cloud.githubusercontent.com/assets/202302/9821141/b55cb1fa-5875-11e5-9bdb-ee7c4f31f291.png)

**Comment by aeslaughter** [comment]
All of the check marks are not implemented, but there hasn't been a major need for them either. When there is we should open tickets for those items.
