### ISSUE TITLE
File parameters defined as std::string instead of FileName

### ISSUE THREAD

**Issue by amccaskey** [idaholab/moose#5715]
I noticed a few places in the code where a parameter like 'data_file' is added to InputParameters as a std::string (seems to be the case in a lot of the Function classes for example). There's nothing wrong with that, but it would make it much easier on ICE's side if it was declared as a FileName (MooseTypes.h) derived string type. As of the other day, ICE now has support for taking FileName and MeshFileName types from the YAML and displaying them in the Properties Tab as drop-down cells with a file browse button (no more showing the file parameters in the Tree on the MOOSE Workflow Form Page). 

I think it would be good to go through and change these file parameter std::strings to FileName types (which should be possible without changing the rest of the code since FileName is a string subclass, but correct me if I'm wrong). I don't mind assigning this to me.

**Comment by permcody** [comment]
Yes, those changes can be made without any other changes. If you feel so inclined go ahead, otherwise one of us will take care of it next week.
