### ISSUE TITLE
Remove old-style [./InitialCondition] block

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5718]
This was deprecated before I started, it is time for it to go. This will help me further separate input file syntax from action and object creation.

**Comment by dschwen** [comment]
Oh, noooooo. I love that syntax :-(

**Comment by permcody** [comment]
Yeah but it is a difficult syntax to maintain. I suggest that we talk about augmenting our shortcut syntax if necessary. We already have a way to set constant initial conditions right inside of the variable block, maybe we can support a few others like functions... The rest should go in the new style [ICs] block unless you have other compelling reasons to keep the old one around.

**Comment by aeslaughter** [comment]
One possible "fix" would be to require "variable" to be a defined parameter
in the [./InitialCondition] block. This would allow us to avoid parsing the
action name name to look for the variable name, which is what I am wanting
to remove, since it relies on input file syntax to work correctly.

**Comment by permcody** [comment]
"fix" in quotation marks... That's more of a hack. Even if I had the nested lookup finished, this still wouldn't help us here.

**Comment by aeslaughter** [comment]
I want to remove it and I am working on it. But, my "fix" would meet my needs. If you look at AddICAction.C, my fix would remove all lines except 42 (so it must be one answer), which eliminates all the parsing stuff of the action name.

**Comment by dschwen** [comment]
Ok, well, my rationale for liking the syntax is that every variable has _at most one_ initial condition, contrary to BCs, Kernels, etc., of which many can apply to a single variable. Also having the shortcut initial_condition _and_ and IC in the ICs block is an easy mistake to make (or you may have some variables with the IC as a shortcut and some with an IC at a very different location in the input file in the ICs block). 
So putting it into the variable block seems like the obvious choice. Too bad that it creates a parsing problem :-(

**Comment by aeslaughter** [comment]
This is staying for now.

**Comment by friedmud** [comment]
I would definitely be for making the default IC be FunctionIC and having `initial_condition` be of type `FunctionName`.

Then you can put a constant, a function of x,y,z,t OR pass in the name of a real function you've defined below...

Making `initial_condition` more useful might obviate the need for people to go to the `ICs` block as often...

**Comment by dschwen** [comment]
:+1:
