### ISSUE TITLE
Add marker that refines/coarsenes the entire simulation cell at given times

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5722]
We have a PF simulation that runs into convergence issues with fine grids at early times. With a marker that would trigger refinement at a set time we could fast track the microstructure evolution and obtain a refined solution at later times.
This would possibly have to insert sync times.

**Comment by friedmud** [comment]
This is the perfect use for Control Logic... use it to activate a Marker at
certain times....

**Comment by aeslaughter** [comment]
This seems like it could be done in the control logic system:
1. Create the Marker you want to enable.
2. Make the "marker" input syntax controllable in the Adaptivity block
3. Make a Control object that changes the marker given some criteria (e.g., time).

In the nearish future, the Marker objects will also be able to remain inactive until the switch is thrown to save computation time, but that feature is not done yet.

**Comment by dschwen** [comment]
Yeah, CL came to mind. Will there ever be a command line client that connects to a running MOOSE sim (i.e. via sockets) that will allow us to change stuff interactively? There are so many more potential applications (like adjusting the simulation end_time or num_steps interactively after eyeball analysis of the intermediate outputs).

**Comment by friedmud** [comment]
Officially: No

Unofficially: Do whatever you want ;-)

That type of stuff is a NIGHTMARE for reproducibility.  I should know... I
did just that for a lot of my master's thesis!

You can always continue a simulation using recover/restart if it didn't run
long enough.

Of course... you can rig something like this up yourself right now.  Just
have your TimeStepper or Executioner or whatever you want check a file for
the number of time steps to do... then just change that file while the
simulation is running ;-)

**Comment by GiudGiud** [comment]
Closing as Uniform Marker + Control Logic can do this.
see https://mooseframework.inl.gov/source/markers/UniformMarker.html
https://mooseframework.inl.gov/source/controls/ConditionalEnableControl.html
If we want more we can plug in the Times system with Control Logic or use the web server
