### ISSUE TITLE
Cleanup KKS model classes

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5728]
The KKS model classes in phase field need some cleanup. Some dead code needs to be removed and the equations need to be double checked (and verified with the Jacobian checker).

**Comment by dschwen** [comment]
Off-diagonal Jacobians of the ```KKSACBulkC```, ```KKSACBulkF``` kernel pair are buggy.

**Comment by dschwen** [comment]
On-diagonal Jacobian contribution from ```KKSACBulkC``` is inexact (~5% L2 error in the UO2 randomized IC test case)

**Comment by laagesen** [comment]
On-diagonal contribution from `KKSACBulkC` is coming from term ` + _prop_dh[_qp]  * A2` that should be zero (partial derivative vs. total derivative). Removing it.

**Comment by laagesen** [comment]
Currently the off-diagonal Jacobian contributions from `KKSACBulkC` and `KKSACBulkF` return negligible errors when the 2 kernels are activated independently. However when both kernels are activated together, errors are detected.

**Comment by laagesen** [comment]
Pushed updated input file to `marmot-problems/problems/UO2Xe_KKS/test.i`

**Comment by laagesen** [comment]
Was missing a negative sign in `KKSACBulkF`. Correcting it has eliminated `slightly off` warnings when checking with only the `KKSACBulkF` kernel on. Still getting error when both `KKSACBulkF` and `KKSACBulkC` are activated, but I think it might be due a a very small difference between the `computeQpOffDiagJacobian` calculation (magnitude 0.000000) compared with the finite difference calculation (magnitude 0.000004) which looks large in percentage (100%) but is very small in difference of magnitudes. Need to confirm this is the case.

**Comment by dschwen** [comment]
@laagesen I believe there may still be work to do on this issue, if you remember the conversation we had about simplifying the residuals. One should simplify down to a diffusion equation if I recall correctly.

**Comment by laagesen** [comment]
I think this one can be closed now. I will open a new issue to work on 3 or
more phases in KKS.
