### ISSUE TITLE
Calling getRandomReal() w/o calling setRandomResetFrequency causes Seg. Fault.

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5734]
We just need to capture this problem with an error.

**Comment by dschwen** [comment]
An assertion seems more appropriate here, as the error is not triggered by user input but by a developer screwup.

**Comment by aeslaughter** [comment]
I disagree, I am creating an AuxKernel, as a user would, that calls
getRandomReal(). If I don't call the set method, I get a seg. fault.

**Comment by friedmud** [comment]
I agree with @aeslaughter

**Comment by dschwen** [comment]
So we add a check that is run at every call of ```getRandomReal()```?! If I'm writing code and get a segfault I run in ```dbg``` mode. This sort of check needs to run exactly _once_ and then you _fix_ the bug. It does not need to run millions of times during a simulation.

**Comment by permcody** [comment]
Well we don't have necessarily need a check. We could just set a default.

**Comment by aeslaughter** [comment]
I think a default is the way to go, in most cases the user never needs to
know anything about this setup.

**Comment by permcody** [comment]
There is already an assertion in place so if you just build debug mode you'd get a helpful error:
https://github.com/idaholab/moose/blob/devel/framework/src/utils/RandomInterface.C#L73-L96

If a majority wants another branch EVERY time the random method is called, we can certainly change this method.

**Comment by aeslaughter** [comment]
I don't want a call in getRandomReal(), if you all think the assert is
enough then we can close this. Personally, I would like the constructor to
random interface set a value.

**Comment by permcody** [comment]
That's not an option. That would mean we build generators for every active
bc, kernel, postprocessor and anything else that inherits from random
interface. It's a demand system so when you make that call it actually
allocates and starts updating the independent generators at every dof.
There needs to be some way you tell the system you want to use random
numbers in this object. If you think of something that will work, I'm open
to ideas.

Cody

**Comment by aeslaughter** [comment]
Good enough for me.

**Comment by friedmud** [comment]
I don't really have any great ideas... but I guess the most "MOOSE-like" thing to do is have a default.

I really don't like that it's so easy to get a segfault.  I would rather have a default and then have people change it when they realize it's not doing exactly what they want...

Maybe make the default "timestep"?  I think that makes the most sense...

**Comment by permcody** [comment]
We can't have a default. The call actually allocates the random data
object.The segfault comes from there being no generator on the other side
making numbers. If I were to create a single global generator that gets
replaced when you make the call that might be on possible way to handle
avoiding a segfault. Of course you won't get all the nice parallel
properties of the system either.

**Comment by friedmud** [comment]
I see.  Well damn.  Whatever then.  We did the best we could ;-)

**Comment by permcody** [comment]
"You tried your best and failed miserably. The lesson is, never try"

- Homer Simpson
