### ISSUE TITLE
Feature request for Time Integrator Aux

### ISSUE THREAD

**Issue by gleicher27** [idaholab/moose#5737]
I noticed that both FastNeutronFluenceAux in BISON and VariableTimeIntegrator in yak essentially do the same thing. This feature seems useful enough that MOOSE should provide at least a base class. 
If it doesn't have it already.

**Comment by friedmud** [comment]
:+1:

**Comment by gleicher27** [comment]
Yaqi says their is something for this in place for MOOSE, but he does not like it ???
Hmmm...I haven't found it yet (Derek, Cody, and Yaqi if you could chime in....)

**Comment by permcody** [comment]
I don't know of any existing AuxKernel that performs that calculation in MOOSE. You'll have to ask @YaqiWang

**Comment by YaqiWang** [comment]
No I do not know any in MOOSE for this. What we want here is to create an var integrator perform the following: u(x, t) = u(x, t_0) + \int_{t_0}^t f(x,t') v(x, t') dt', where f(x,t) is a moose function.

**Comment by YaqiWang** [comment]
This might be complicated then we thought because `v` could be obtained with various time integrators. We should use those solutions at intermediate steps to more accurately do this integration.

**Comment by gleicher27** [comment]
At the heart this looks like for BISON:

Real
FastNeutronFluenceAux::computeValue()
{
  return _u_old[_qp] + 0.5*_dt*(_fast_neutron_flux[_qp] + _fast_neutron_flux_old[_qp]);
}

And then for YAK:
Real
VariableTimeIntegrator::computeValue()
{
  return _u_old[_qp] + (_cvar[_qp] + _cvar_old[_qp]) * _dt / 2.0 * _coef;
}

**Comment by gleicher27** [comment]
Well, part of it should maybe depend upon the time scheme that is currently asked as well, so that at least the same consistency is given ?
