### ISSUE TITLE
ICEUpdater bugs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5741]
It appears that the ICEUpdater has a few bugs which need to be resolved:

- [ ] Fails to run in parallel at all, (here's the start of a potential solution: https://github.com/permcody/moose/commit/552b1b98656c3827ceb1b496a772a077a140799f
- [ ] Reports the following error in serial sometimes `Number of Posts was 5, but should have been 4`

That's all I can nail down for sure right now. It appears to work at least as often with threads enabled as without so that case may be ok.

Tagging @amccaskey

**Comment by amccaskey** [comment]
I'll take a look at this and push a fix soon to my fork.

**Comment by permcody** [comment]
I was hoping there would be some weird problem in the TestHarness piece but I don't believe that's the case. I have a PR open now that cleans up some of the unecessary overrides in the new `ICEUpdateTester.py` but it still fails on my system in serial about 10% of the time even with these fixes.

```for i in `seq 1 20`; do ./run_tests --re=outputs -j24;  done ```

**Comment by amccaskey** [comment]
@permcody I modified the way the Updater constructs the post message to hopefully fix bug number 2 in your initial post. 

Basically, it was constructing the transmission message for all possible posts it had in its queue, then it would push the post to the server. Now, it will construct the transmission to be posted to the server for only post in the queue at a time. This should get rid of any variability in the timing of posts (and thus the number of posts) to the server.

As for bug 1, I incorporated your change to check if this is the master rank before executing the ICEUpdater methods. Everything seems return OK on tests for 

``` for i in `seq 1 20`; do ./run_tests --re=iceupdater -p24; done ```

Let me know if you find anything different when you build and test amccaskey/moose/iceupdaterBugs_5741 1fc043da76283f5681f1fd3ec852ed52bfae0b84

**Comment by permcody** [comment]
Let's get a PR in for this, we'll see what the test systems do with it.

**Comment by permcody** [comment]
ICE currently is disabled so lowering the priority

**Comment by permcody** [comment]
Closed by #6220
