### ISSUE TITLE
initial_from_file_timestep should be able to grab "end"

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#5748]
If end(ie the last timestep) is tried in the restart system, the following error is thrown.

`ERROR: Input value for variable GlobalParams/initial_from_file_timestep is of the wrong type.
       value = end expected type = i`

Would this be easy to change?

**Comment by permcody** [comment]
Yes, We've already solved this problem with the `block` and `boundary` parameters in MOOSE. We just changed the type to string and then attempt to convert them to integers. If they successfully convert without leaving left over characters, we know they are actually integers and we can treat them as suck. If they don't convert, then we can attempt to treat them as a string and do something different. This is a good idea and I think it's been proposed before, but I'll leave this new version open as a reminder.

**Comment by friedmud** [comment]
:+1:
