### ISSUE TITLE
'output_final = true' doesn't output final

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#5756]
Try the following.  The final step (0.1 s) is not written out to the console or the Exodus file.

[Mesh]
  type = GeneratedMesh
  dim = 2
  xmin = 0
  xmax = 1
  ymin = 0
  ymax = 1
  nx = 10
  ny = 10
  elem_type = QUAD4
  # This test uses ElementalVariableValue postprocessors on specific
  # elements, if you use ParallelMesh the elements get renumbered.
  distribution = serial
[]

[Functions]
  [./ffn]
    type = ParsedFunction
    value = -4
  [../]

  [./exactfn]
    type = ParsedFunction
    value = x*x+y*y
  [../]

  [./aux_exact_fn]
    type = ParsedFunction
    value = t*(x*x+y*y)
  [../]
[]

[Variables]
  [./u]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./td]
    type = TimeDerivative
    variable = u
  [../]

  [./diff]
    type = Diffusion
    variable = u
  [../]

  #Coupling of nonlinear to Aux
  [./force]
    type = UserForcingFunction
    variable = u
    function = ffn
  [../]
[]

[AuxVariables]
  [./aux_u]
    order = CONSTANT
    family = MONOMIAL
  [../]
[]

[AuxKernels]
  [./a]
    type = FunctionAux
    variable = aux_u
    function = aux_exact_fn
  [../]
[]

[BCs]
  [./left]
    type = FunctionDirichletBC
    variable = u
    boundary = '0 1 2 3'
    function = exactfn
  [../]
[]

[Postprocessors]
  [./elem_56]
    type = ElementalVariableValue
    variable = u
    elementid = 56
  [../]

  [./aux_elem_99]
    type = ElementalVariableValue
    variable = aux_u
    elementid = 99
  [../]
[]

[Executioner]
  type = Transient

  # Preconditioned JFNK (default)
  solve_type = 'PJFNK'

  dt = 0.01
  start_time = 0
  num_steps = 10
[]

[Outputs]
  interval = 3
  output_final = true
  show = 'aux_u'
  #show = 'u'
  exodus = true
  file_base = out
[]

**Comment by aeslaughter** [comment]
'output_final' isn't used anymore, you should be seeing warnings. Try using `execute_on = 'initial timestep_end final'`, if this doesn't work I will take a look.

**Comment by jasondhales** [comment]
I don't see a warning.

That line puts the final result in the Exodus file, but the console does
not show the final step.

On Wed, Sep 30, 2015 at 9:47 AM, Andrew E Slaughter <
notifications@github.com> wrote:

> 'output_final' isn't used anymore, you should be seeing warnings. Try
> using execute_on = 'initial timestep_end final', if this doesn't work I
> will take a look.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idaholab/moose/issues/5756#issuecomment-144453524>.
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293
