### ISSUE TITLE
Variable dependent mobility in Allen-Cahn kernel is buggy

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5758]
Ping @tonkmr 

Variable dependent _L_ mobilities in the ```ACParsed``` kernel cause the system to evolve unphysically (such as increasing the total free energy!). This may explain a good portion of the stuff observed in #5595

**Comment by dschwen** [comment]
d80f982 adds a minimal input file that demonstrated the bug. A plot of the free energy is shown below.

![acmobilitybug](https://cloud.githubusercontent.com/assets/202302/10200661/ee8845d6-6764-11e5-8b3c-b02fdb87f7a5.png)

**Comment by dschwen** [comment]
The issue seems to be in ```ACInterface```. The behavior looks ok with ```kappa = 0```.

**Comment by dschwen** [comment]
Got it. The weak form is _wrong_ in this kernel. The derivation leads to 

![eq1](http://quicklatex.com/cache3/62/ql_ece4c7227aa39f8c856a291a6c3fd362_l3.png)

but the kernel implements

![eq2](http://quicklatex.com/cache3/7f/ql_0b22298433d98ee568d98ef4f5d3b97f_l3.png)

I.e. the weak form was derived under the assumption that _L_ and _kappa_ are constants and can be pulled out of the gradient term. This looks like an oversight that must have happened at the introduction of variable dependent mobilities. 

I will fix this and I will check the weak forms of the other PF kernels for similar issues.

**Comment by a-f-dykhuis** [comment]
Now I see what you're talking about. I do have a variable kappa.

**Comment by a-f-dykhuis** [comment]
FYI - Running it with constant L and kappa does lead to oxide growth (with massaging of other numbers to compensate).

**Comment by tonkmr** [comment]
The Allen-Cahn equation is \dot{eta} = - L dF/deta. So, there is no gradient term that acts on L. Once you sub in the value for F you get 

R = \dot{eta} + L df_loc/deta - L kappa grad^2 eta

So, there is no gradient on kappa either. In weak form, the interface term becomes

L kappa (grad eta, grad phi)

**Comment by dschwen** [comment]
Product rule integration will give the term above. The current residual is
clearly wrong.

**Comment by tonkmr** [comment]
I see what you are saying, it comes when we lower the order of the derivative on the variable using the divergence theorem. I think this same issue will pop up when we add support for variable kappa in the split form of the Cahn-Hilliard equation.

In addition to the kernels, all of the documentation on the wiki is wrong as well.

**Comment by dschwen** [comment]
Yes. The docs are definitely wrong. I'm already working on a fix that will
include variable kappas. I will fix the docs as well.

**Comment by dschwen** [comment]
The fix is working. Kappa dependence needs even more terms (additional terms emerge from the variational derivative). But I'm getting there.

![acmobilitybug_fixed](https://cloud.githubusercontent.com/assets/202302/10212809/cfe26e06-67c1-11e5-8093-57dc41064eca.png)

**Comment by dschwen** [comment]
Opening a new issue for the variable kappa dependence as it does not fit the subject of this issue.
