### ISSUE TITLE
Give major libMesh changes more thorough testing

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#5760]
The typical MooseBuild tests are sufficient for most libMesh updates, but for major changes or for changes to features where we don't have enough test coverage, it would be nice to have more.

@jwpeterson suggests "...the easiest way would probably be to put in a PR to MOOSE that contains a libmesh update to the hash with your changes.  That will run the moose_pr_app_tests which will hit most of our important apps."

I'll try that now with https://github.com/libMesh/libmesh/pull/667

I'd like to leave this issue open for future reference from subsequent such PRs, rather than opening a new issue for each.

**Comment by permcody** [comment]
That's a good solution for now. MOOSE build is currently being redesigned and we should be able to accommodate more of these types of requests when we rollout the new version.

**Comment by brianmoose** [comment]
CIVET now allows for optional recipes that can be attached (manually) to a PR.
If you let me know what kind of tests you want to run I can add them.

**Comment by brianmoose** [comment]
I added a mirror of the MOOSE App tests that you can attach to LibMesh PRs.
Let me know if you want anything else.

**Comment by permcody** [comment]
Bump on this ticket. We now have the ability to run more targets on demand, but I want to move towards running more targets all the time. We'll do this as we get more hardware, better drives.

**Comment by permcody** [comment]
Closing this ticket. We have the ability to turn on any test on demand. No longer need to submit MOOSE PRs to test against MOOSE - closing.

**Comment by roystgnr** [comment]
Yeah, this is settled IMHO.  Ironically, I *do* have another request today - could we add the Mac Test target to the optional libMesh PR tests?

**Comment by brianmoose** [comment]
The MOOSE "Mac Test"? Or do you want the libmesh "Test" on a Mac? They seem to test different things....

**Comment by roystgnr** [comment]
I'd been thinking of the former, but actually I'd love to have both.

**Comment by brianmoose** [comment]
OK, both of those have been added: "MOOSE Mac Test" and "Test Mac"

**Comment by brianmoose** [comment]
By the way, we only have one mac test box, so be patient.
