### ISSUE TITLE
Add interface block mesh modifier

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#5765]
This comes out of the discussion here: https://groups.google.com/forum/#!topic/moose-users/011fudvdHng

Ideally, I would like to be able to generate the same qualitative characteristics of the mesh 2blk-conf.e (used in Moose test input file conforming_two_var.i) using GeneratedMesh and MeshModifiers. The proposed mesh modifier would be capable of inserting an interface element block, disconnecting subdomains, and adding a sideset to each disconnected subdomain.

From Yaqi, it sounds like such a thing is possible. He pasted code describing such a class called SplitConformingMeshForMortar which inherited from MeshModifier.

**Comment by permcody** [comment]
Yes, until the simulation actually starts you can mesh around with the Mesh quite a bit, removing and deleting elements, sidesets and/or nodesets. There are lots of tools right in libMesh for making all of these things occur, it's just a matter of digging in and creating all the correct logic.

**Comment by GiudGiud** [comment]
Mesh modifier at the time were mesh generators now. 
inserting an interface element block -> lowerDFromSidesetMG
disconnecting subdomains -> breakMeshByBlock 
adding a sideset to each disconnected subdomain -> either BMBBMG or pre-insert using SidesetsBetweenSubdomainsgenerator (better)
All needs covered, closing
