### ISSUE TITLE
Jacobian analyzer script fix for El Crapitan

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5774]
It seems that ```/usr/bin/env``` in El Capitan unsets the ```DYLD_LIBRARY_PATH``` variable (this is an issue for peacock as well @permcody).

The fix is to specify the python interpreter directly (better ideas appreciated).

**Comment by dschwen** [comment]
This is the issue: https://forums.developer.apple.com/message/31148

**Comment by jwpeterson** [comment]
> On Oct 2, 2015, at 5:56 PM, Daniel Schwen <notifications@github.com> wrote:
> 
> This is the issue: https://forums.developer.apple.com/message/31148
> 

More like El Crapitan.

**Comment by dschwen** [comment]
This is actually big. We should find a way to ditch ```DYLD_LIBRARY_PATH``` entirely. Why are the library paths not compiled in for some libs? Atom auto completion doesn't work anymore either.

**Comment by friedmud** [comment]
With Python there is no binary to compile a path into (such is the case for Peacock).

Have you been able to find other people running into this issue with El Capitan?

**Comment by dschwen** [comment]
Well, I confirmed that the DYLD_LIBRARY_PATH is passed through in Yosemite and not in El Capitan. The rpath needs to be set in the moose executables of course! That way we wouldn't have to rely on DYLD_LIBRARY_PATH anymore at all (isn't it _evil_ anyways? ;-)

**Comment by dschwen** [comment]
B.t.w. the testing harness does not work either (if that conclusion hasn't been obvious from the previous posts).

**Comment by dschwen** [comment]
```install_name_tool``` can be used on macs to fix this (i.e. set an absolute path for every library in the executable).

For example:
```
install_name_tool -change libiomp5.dylib /opt/moose/openmp/lib/libiomp5.dylib phase_field-opt
```

This has to be done for every library that doe not have a full path.
I'm working on  a small script to do this as a quick fix.

**Comment by friedmud** [comment]
@dschwen before you go crazy on this... let's investigate a little more.  DYLD_LIBRARY_PATH is a _real_ thing... it's a thing we're supposed to be able to rely on.  It's not something we made up - or something we're using incorrectly.

We need to get to the root of why DYLD_LIBRARY_PATH is not passing through /usr/bin/env.  It could be a security setting  - or maybe some other way we need to invoke /usr/bin/env.  The answer is NOT to eradicate our use of DYLD_LIBARY_PATH or create a quagmire of scripts to try to embed rpaths everywhere.

Just hold up for a minute... let's fix the real issue... they can't have completely broken DYLD_LIBRARY_PATH in El Capitan...

**Comment by friedmud** [comment]
Can you describe the issue a little bit more?  Is it an issue that only surrounds /usr/bin/env?  Or are you seeing DYLD_LIBRARY_PATH getting dropped in other places?

**Comment by friedmud** [comment]
It's definitely an issue that other people are seeing: https://forums.developer.apple.com/message/31148

**Comment by dschwen** [comment]
Christ, I know what ```DYLD_LIBRARY_PATH``` is! Or ```LD_LIBRARY_PATH``` on Linux. Of course it is not something you made up. But its use is _discouraged_. And now OSX has changed the behavior for _this_ environment variable _specifically_ when the environment is passed to child processes. 

The variable is dropped **for every child process** (for some reason not for children of the shell though!). I'm not creating a _quagmire of scripts_, I'm **testing** a fix here. And that fix will of course **not** be implemented by a hacky script, but by fixing the build system of MOOSE.

Again: we should **not** rely on ```DYLD_LIBRARY_PATH``` in the first place. **That** is the ugly hack. And I _did_ post that very link you just reposed already above.

**Comment by dschwen** [comment]
Ok, I can confirm that using the script in f380e6c I can get a MOOSE installation and compiled MOOSE executables that run fine without a ```DYLD_LIBRARY_PATH``` set. It requires running the script on the vtk libs and the PETSc libs.

**Comment by friedmud** [comment]
After doing some catching up on this issue... this is a complete mess.  It's being done for security... but really messes up a lot of stuff.

It sounds like I offended you, and I certainly didn't mean to.  I'm glad you're looking into this, I was just preaching caution about heavy handed reactions.  I'm specifically referring to your statement of

> We should find a way to ditch DYLD_LIBRARY_PATH entirely

Yes, for binaries we can embed rpaths (we've done a lot of that in the past already).  But what about for Python?  Custom python installations (like miniconda) rely on DYLD_LIBRARY_PATH working.  How is that supposed to work in the future?

Sometimes Apple pisses me off... and this is definitely one of those times.  Unix systems should be able to rely on LD_LIBRARY_PATH working...

**Comment by dschwen** [comment]
No, python programs are _not_ the problem. We just need to get all binaries in shape to _not_ require DYLD_LIBRARY_PATH (sorry, but it looks like this is the only option).

**Comment by dschwen** [comment]
As I said above, I have this all running on my El Capitan system now.

**Comment by dschwen** [comment]
The real solution will be to fix the Make files to set all rpaths to fully qualified filenames for the linked libraries _at build time_.

**Comment by andrsd** [comment]
This will also have some implications on how @milljm builds the MOOSE package...

**Comment by milljm** [comment]
PETSc fails to build due to this issue.

**Comment by andrsd** [comment]
@dschwen Do you use TBB? On my machine, the binary relies on the `DYLD_` variable.

**Comment by dschwen** [comment]
With the new El Capitan MOOSE Environment package this is not an issue anymore.
