### ISSUE TITLE
JacobianAnalyzer script might fail to find valid executable

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5780]
As reported here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/Khh6QA5eIAQ/wiLEjxwGCwAJ

**Comment by dschwen** [comment]
According to Maria the following command is dispatched by the analyzer

```
Running
../../../hart/ -i ../../../hart/test_mech_sub.i Problem/solve=false BCs/active= Outputs/analyzerdofmap/type=DOFMap Outputs/active=analyzerdofmap Outputs/file_base=../../../hart/test_mech_sub_analyzerdofmap
```

The detected executable is ```../../../hart/```, which is just a path, not an executable. The script searches from the current path **up**, so if ```../../../hart``` is not a parent of the current directory (i.e. if it is not equivalent to ```../..``` this cannot work anyways. 

I cannot reproduce this on my machine and I always get an executable not found message. I'll probably add another check to make sure we found a _file_ that is _executable_.

**Comment by permcody** [comment]
Let's close this. We'll reopen as necessary.
