### ISSUE TITLE
Request: restart_file_base should support "END"

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5792]
We recently implemented this for initial conditions #5754, and plan to do it for `SolutionUserObject` as well #5786. We should probably add it for restart file base as well. It's one of those annoying things you have to check each time you do restart on the "Part 2" run.

**Comment by andrsd** [comment]
For ICs, we have the solution in a single file and we pick a time step from it.
In this setup, each time step is in its own file. So, do you plan to do `ls` and pick the largest number? That is something I do in my scripts when I use restart. The danger here is that if my re-run of the initial phase has fewer time steps, this will use the older restart feel with the higher number (I have to remember to `rm` those older files).

**Comment by permcody** [comment]
I'm not forcing you to use "end", I just want to make it possible. Yes, I would retrieve all of the checkpoint files and pick the largest number. I've certainly run into the case you mentioned where the oldest one is stale. If we wanted to be really clever we could check the timestamps and print warnings when the largest wasn't the newest or something. I also considered deleting checkpoints when you run a new non restart or recover simulation. While that might work, it might also unintentionally delete a good run that may have taken hours or days to get so I don't think I want to go there.

**Comment by andrsd** [comment]
> I'm not forcing you to use "end"

I understand that `END` is optional ;-)

> If we wanted to be really clever we could check the timestamps

So, may be we could have a tag called "LATEST" that would pick the one with the most recent timestamp?

I agree, we should be be deleting file (i.e. doing cleanup for people).

**Comment by friedmud** [comment]
LATEST isn't a bad idea for restart.  That's what we already do for recovery by default: https://github.com/idaholab/moose/blob/devel/framework/src/actions/SetupRecoverFileBaseAction.C#L66

What if we just "demote" `restart_file_base`.  Maybe we make a `restart_from` that just points at the directory itself and then it defaults to getting the newest file in the same way `--recover` does...

**Comment by permcody** [comment]
I'll work on this.

While I like the idea of just pointing to the directory, I'm not so sure I want to support both syntaxes. It'll just lead to confusion. If we weren't already down this path, I might consider it. Let's go with END and LATEST for now and see how users respond.

**Comment by friedmud** [comment]
Three options: END, LATEST, FINAL

We need to pick one... the "execute_on" options already use FINAL...

**Comment by permcody** [comment]
Well, we already used END for ICs that read a timestep from a file and I have a PR in for doing the same in SolutionUserObject #5842. END makes sense for those two cases. This one with the restart is where things get tricky because of stale files hanging around that might be older but have a higher number. "LATEST" makes better sense for that case.
