### ISSUE TITLE
Interleaving of Error Messages

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#5801]
As discussed here https://groups.google.com/forum/#!topic/moose-users/TZCkZOYJICo certain error messages should be printed on rank0 to avoid error message interleaving.  

The example I presented was interleaving of the:

Solve failed and timestep already at dtmin, cannot continue! 

Error message.  I have also experienced the interleaving on the unused parameter in your input file error as well.

**Comment by jwpeterson** [comment]
We decided to add a `mooseConsoleError()` macro to handle this issue.  It will be the same as `mooseError()` but print to the `_console` instead.  Both macros should be implemented in terms of a common third macro since `mooseError()` is non-trivial.

**Comment by permcody** [comment]
We really need to revive this issue. It still pops up in CIVET to this date. It's tricky because we need to potentially propagate errors from non-root ranks or threads in case the error doesn't occur globally. Another idea might be to use `--redirect-stdout` and `--keep-cout` as appropriate to search for these error messages. hmm.

**Comment by permcody** [comment]
A new option has been added to libMesh to allow us to redirect stderr streams as well as the stdout stream we already redirect. We are taking advantage of this in #8080 and it should solve other problems as well.

**Comment by permcody** [comment]
This issue has been completely resolved by using the newer "--redirect-stdout" CLI option with "--keep-cout". This will save the output (and error) streams to separate files. This is exactly what the TestHarness does now too so we can safely run exception and warning tests in parallel.
