### ISSUE TITLE
Bug in restart/recover somewhere when adding a [Problem] block

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5808]
I've been attempting to track down a really nasty bug that shows up if you introduce a `[Problem]` block in the restart problem. I've traced it to the line in `FEProblem::initialSetup()` where the resurrector is used to load data. I've looked to make sure that restart is true and the method is actually being called but have yet to see where the issue is.  The problem is that _dt is set not initialized when the `[Problem]` block is present, even if it's empty.

```
// _dt is always zero here
  if (_app.isUltimateMaster() && (_app.isRestarting() || _app.isRecovering()))
    _resurrector->restartRestartableData();
// if [Problem] is present _dt is still zero, otherwise it'll have the correct value
```

@friedmud, Do you have any idea why this is the case? It's easy to replicate. I used this test to replicate the problem: https://github.com/idaholab/moose/blob/devel/test/tests/restart/kernel_restartable/kernel_restartable_second.i
Simply add an empty `[Problem]` block and you'll see the problem.

**Comment by permcody** [comment]
BTW - This problem persists with your current Multiapp restart branch.

**Comment by friedmud** [comment]
Ok - I'll check it out tonight

**Comment by permcody** [comment]
Lol - So I have an input file patch to the sifgrs test file that works with your https://github.com/idaholab/moose/pull/5733 branch but only if I set the flag  `use_legacy_uo_initialization = false` for that test. However, that currently can't be done because adding a [Problem] block in order to disable the legacy flag triggers this issue's bug #5808.

**Comment by permcody** [comment]
Still looking for this bug because if we can fix, we can merge #5733 without additional hacks or mods. I suspect that adding the `[Problem]` block is triggering some object or Action a little earlier affecting the restartable data in some unintuitive way.

**Comment by friedmud** [comment]
WTH.  I don't get it.  Still looking....

**Comment by friedmud** [comment]
Ok - the issue is the naming of the FEProblem.  It forms part of the basis of the unique name of restartable data.  The default name is *blank* without a `[Problem]`.  With a `[Problem]` block it defaults to `Problem`.

If you were to have the `[Problem]` block in both the first and second input files you would be fine.  Adding it in the second one changes the name... and so the data doesn't match up.

I'm working on a "fix" now for this common case though... because this is pretty easy to trigger.

**Comment by permcody** [comment]
Interesting.
