### ISSUE TITLE
Spherical mesh issues

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5821]
I'm at the CHiMaD workshop at Northwestern right now. One benchmark problem is solbing the PF equations of the surface of a sphere. This revealed a few issues. The mesh is 2D in 3D space.

* Exodus output (@aeslaughter) flattens the mesh to a pancake. Is that output module dropping the z component when outputting a mesh from a 2D problem? Tecplot output is reported to work.
* Mesh refinement seems to screw up the normals of the refined elements (we see that wen rendering the output in Tecplot).

**Comment by YaqiWang** [comment]
This is like a d-1-dimension block in d-dimensional mesh in mortar method. Can we make the mesh still 3D but all element in it are 2D? We have something similar in radiation transport where 2D unit sphere need to be meshes if we want to do FEM on it. Mesh refinement is special and there has to be some extra work to do to project and prolong the solution.

**Comment by jwpeterson** [comment]
> Exodus output (@aeslaughter) flattens the mesh to a pancake. Is that output module dropping the z component when outputting a mesh from a 2D problem? Tecplot output is reported to work.

The issue here is that MOOSE by default uses the mesh_dimension (which in this case is 2) instead of the spatial dimension for Exodus output.
 
Exodus.C line 139:
```
  // Utilize the spatial dimensions
  if (_es_ptr->get_mesh().mesh_dimension() != 1)
    _exodus_io_ptr->use_mesh_dimension_instead_of_spatial_dimension(true);
```

The fix would be to just make this a Param in the Exodus.C object.

> Mesh refinement seems to screw up the normals of the refined elements (we see that wen rendering the output in Tecplot).

Can you elaborate on this?  The normals can't be screwed up unless the elements themselves are screwed up, and I'm pretty sure @permcody just showed me a problem with working refinement...

**Comment by dschwen** [comment]
Refinement would only be an issue if you want to constrain all refined nodes to the surface of the sphere, right? That would be nice though.

**Comment by dschwen** [comment]
Ok, I guess we can make it an optional parameter. I'll put in a PR for that.
Here is a screenshot the Olle Heinonen just sent me. 

![mesh](https://cloud.githubusercontent.com/assets/202302/10489050/19f8d85a-7261-11e5-9d88-5d4ecb5f6365.png)

It looks like the original elements (outlined in the blue regions) have normals and get shaded by Tecplot, while the refined elements (everything else) is shaded flat (i.e. has no normals?).

**Comment by jwpeterson** [comment]
I think this is a Tecplot+adaptivity issue. Try opening a non-flattened file in Paraview and it should look fine...

**Comment by permcody** [comment]
Yes, it is flat but it looks fine in paraview (Exodus output)

**Comment by dschwen** [comment]
The flatness is a separate issue. @permcody are you saying that paraview shows it as a sphere?

**Comment by permcody** [comment]
No, but there really isn't distortion either from the "front on" view. it's
just a projection in 2D space but good luck rotating it :)

**Comment by YaqiWang** [comment]
If the initial mesh is fine enough and we do not have to put all newly added node on sphere, things will be easy. But if you want to go crazy, you can try implement the exact refinement on sphere...

**Comment by dschwen** [comment]
I cannot reproduce this without tecplot and this seems to go nowhere.
