### ISSUE TITLE
Add Picard iteration for steady-state executioners?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5823]
We have Picard iteration for Transient, should we add the similar thing in Steady, NonlinearEigen and InversePowerMethod? We need this for Rattlesnake. But if you are against this, I can make derived class in Rattlesnake. Thanks.

**Comment by friedmud** [comment]
Well... the ultimate answer to this is over here: https://github.com/idaholab/moose/issues/5229

I have some work done on it here (and more on my laptop that isn't pushed): https://github.com/friedmud/moose/tree/executioner_refactor_5229?files=1

BUT: it's going to be a while before that works (and before I have time to work on it).

I would say: implement what you need in Rattlesnake for now...

**Comment by YaqiWang** [comment]
I had implemented this in Rattlesnake. So this is no longer an issue for me. I still suggest it in MOOSE though.
