### ISSUE TITLE
Executioner not recognized

### ISSUE THREAD

**Issue by twh5306** [idaholab/moose#5836]
I was making some edits to the Parsed_SplitCH file in phase fields, and saved my changes.  When I went to load my edited version in peacock, peacock didn't recognize the executioner.  I opened the file in Atom, and the executioner is still there (totally unchanged from the one in the original file).  It ran separately in terminal just fine, so I think this is a bug in peacock

**Comment by permcody** [comment]
Possibly, or it could be a syntax error. Peacock's parser is actually more
picky than MOOSE's parser so if you leave off a closing brace or anything
like that Peacock will fail to read the file but MOOSE will even though
there's a syntax error. Make sure you carefully check all your opening and
closing brackets, quotes and anything else you may have changed.

**Comment by dschwen** [comment]
Could you commit the input file? If you put the issue number in the commit message it will show up right here in this issue conversation.

**Comment by twh5306** [comment]
it is the exact same format and syntax as the original file version, which loads properly.  I have the two files open side by side in atom.  executioners are exactly the same

**Comment by twh5306** [comment]
input file to follow

**Comment by twh5306** [comment]
#
# Example problem showing how to use the DerivativeParsedMaterial with SplitCHParsed.
# The free energy is identical to that from SplitCHMath, f_bulk = 1/4*(1-c)^2*(1+c)^2.
#

[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 150
  ny = 150
  xmax = 60
  ymax = 60
  elem_type = QUAD4
[]

[Variables]
  [./c]
  [../]
  [./chem_pot]
  [../]
[]

[AuxVariables]
  [./local_energy]
    order = CONSTANT
    family = MONOMIAL
  [../]
[]

[ICs]
  [./cIC]
    type = RandomIC
    variable = c
    max = 0.55
    min = 0.45
  [../]
[]

[Kernels]
  [./c_dot]
    type = CoupledTimeDerivative
    variable = chem_pot
    v = c
  [../]
  [./c_res]
    type = SplitCHParsed
    variable = c
    f_name = fbulk
    kappa_name = kappa_c
    w = chem_pot
  [../]
  [./chem_pot_res]
    type = SplitCHWRes
    variable = chem_pot
    mob_name = M
  [../]
[]

[AuxKernels]
  [./local_energy]
    type = TotalFreeEnergy
    variable = local_energy
    f_name = fbulk
    interfacial_vars = c
    kappa_names = kappa_c
    execute_on = timestep_end
  [../]
[]

[BCs]
  [./Periodic]
    [./all]
      auto_direction = 'x y'
    [../]
  [../]
[]

[Materials]
  [./mat]
    type = GenericConstantMaterial
    prop_names = 'M kappa_c'
    prop_values = '1.0 0.5'
    block = 0
  [../]
  [./free_energy]
    type = DerivativeParsedMaterial
    block = 0
    f_name = fbulk
    args = c
    constant_names = W
    constant_expressions = 1.0/2^2
    function = W*(c)^2*(1-c)^2
    outputs = exodus
  [../]
[]

[Postprocessors]
  [./top]
    type = SideIntegralVariablePostprocessor
    variable = c
    boundary = top
  [../]
  [./total_free_energy]
    type = ElementIntegralVariablePostprocessor
    variable = local_energy
  [../]
  [./total c]
    type = ElementAverageTimeDerivative
    variable = c
  [../]
[]

[Preconditioning]
  [./cw_coupling]
    type = SMP
    full = true
  [../]
[]

[Executioner]
  # petsc_options_iname = '-pc_type -pc_hypre_type -ksp_gmres_restart'
  # petsc_options_value = 'hypre boomeramg 31'
  type = Transient
  scheme = bdf2
  dt = 2.0
  solve_type = NEWTON
  petsc_options_iname = '-pc_type -ksp_grmres_restart -sub_ksp_type -sub_pc_type -pc_asm_overlap'
  petsc_options_value = 'asm         31   preonly   lu      1'
  l_max_its = 30
  l_tol = 1e-4
  nl_max_its = 20
  nl_rel_tol = 1e-9
  end_time = 20.0
[]

[Outputs]
  exodus = true
[]

**Comment by twh5306** [comment]
wouldn't let me attach a file, so above is the code

**Comment by andrsd** [comment]
> wouldn't let me attach a file, so above is the code

That's why @dschwen wanted you to commit the file in some branch and push it into your fork with referencing this issue number ;-)

**Comment by dschwen** [comment]
having it committed would also generate a diff view which might spotting the problems easier...

**Comment by dschwen** [comment]
Ha, got it! There is a space in the ```[./total c]``` postprocessor subblock name!

**Comment by twh5306** [comment]
I had no idea that could have been causing the problem, thanks for the catch!!
