### ISSUE TITLE
HeatConductionTimeDerivative

### ISSUE THREAD

**Issue by bakeba** [idaholab/moose#5852]
Density and specific heat cannot take on general names.

**Comment by permcody** [comment]
True, most of our kernels don't allow that. We only recently added that capability to supply names of material properties through the input file. Are you planning on making this change? Is there someone running into an issue? This is an old class so I'm a little hesitant to change it unless there is a specific need.

**Comment by bakeba** [comment]
Andrew said he would change it really quickly if I submitted it as an
issue. So, I did.

Benjamin Baker
PhD Nuclear Science & Engineering
Idaho National Laboratory
phone: 208.526.1078
email: benjamin.baker@inl.gov

**Comment by aeslaughter** [comment]
The companion class "HeatConduction" already does this, it only makes sense
that the time derivative class would support his as well. I am doing it now.
