### ISSUE TITLE
getMaterialProperty does not fail gracefully if requesting a non-existing property

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5859]
Demonstrated in 9aa75d598. This is quite a doozey!

**Comment by dschwen** [comment]
@jwpeterson the reason seems to be that the offending Kernel `HeatConductionTimeDerivative` does not call `getMaterialProperty` in the constructor. That means those property names never get added to the list of properties to check in `SubProblem::checkMatProps`!

**Comment by jwpeterson** [comment]
Hmm, so can we just move what's currently done in `initialSetup` to the constructor?

**Comment by dschwen** [comment]
Yeah, can and did. But it leaves the underlying issue...

**Comment by friedmud** [comment]
The only "underlying issue" I see here is that we should either print a warning... or just error if you try to call any of the `get()` functions after `initialSetup()`.

They are always meant to be called during the constructors... anything else is wrong.

**Comment by YaqiWang** [comment]
Maybe not. For example, if you have a postprocessor requires two material props for the summation, one defined on block 0 another on block 1. Then you do not want to call get during construction because moose will error out. But you also do not want to separate postprocessors and sum them up later. You can call get in `initialSetup()` and inquire the availability of the prop on blocks. I have this kind of thing in Yak...

**Comment by permcody** [comment]
Right, not all of our methods are lazy enough so it may not be possible to call all get methods in the constructor. I think it's worth looking at each case we encounter though to see how we could improve the framework so that it IS possible.

**Comment by dschwen** [comment]
Hmm, I think we should at least warn about this. Currently it is just too easy for users to shoot themselves in the foot. I'll push two commits with a suggested change in a few secs.

**Comment by permcody** [comment]
Hmm, these look like simple reasonable fixes. Are you planning to open a PR for these fixes?

**Comment by dschwen** [comment]
Whoops, I totally forgot about those commits. Yeah. Let me dig them up and re-examine.
