### ISSUE TITLE
User object initialSetup() will be called multiple times on initial

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5863]
if it is executed on multiple occurrence, like `initial timestep_end`. I do not think this is desired behavior. This issue could be invalid because users can protect their code with a flag `initialized`. But this behavior may not be expected by user.

**Comment by permcody** [comment]
The other thing we do is only call initialSetup on thread zero's copy of the object. Nobody has ever complained about that but I wonder if it could cause issues with what people expect.

**Comment by YaqiWang** [comment]
I guess we may just to make user object return which warehouse it belongs to, linear, nonlinear and so on. Thread ID is a valid member variable. And we document it. Then it will be up to the app developer to do what he want to do.

**Comment by permcody** [comment]
No, that's not something objects should know about. Either the warehouses or the ExecStore can be modified to handle this under the hood.

**Comment by permcody** [comment]
@aeslaughter - I believe you said this isn't an issue anymore with the new Warehouse design. If so, let's have @YaqiWang test this in Yak by removing his Boolean hack.

**Comment by aeslaughter** [comment]
This will not be an issue when I get to the UserObjectWarehouse, which
should be next week.

**Comment by permcody** [comment]
@aeslaughter - I believe this issue is closed. Can you confirm?

@YaqiWang - Perhaps you should remove the Boolean workaround from your Yak UO.

**Comment by YaqiWang** [comment]
I remembered  I was protecting `initialSetup()` inside by a `if (_initialized)`. It does not hurt, but I will remove them after get confirmation from Andrew.

**Comment by permcody** [comment]
It doesn't hurt. I think the right thing to do would be to put in a test
object that throws if initialSetup() is called more than once. Then you can
be assured that you don't have to protect the call yourself in your library.

**Comment by aeslaughter** [comment]
I am working on it now, it is getting close. I have one parallel error I am
trying to track down now.

**Comment by YaqiWang** [comment]
I believe this has been fixed after the warehouse refactoring. We can reopen it if not.
