### ISSUE TITLE
Measure Interface energy in phase field models

### ISSUE THREAD

**Issue by jbair34** [idaholab/moose#5867]
A simple 1D simulation should be created for the phase field module examples folder which is able to accurately determine the interface energy between two phases.

**Comment by jbair34** [comment]
@dschwen should review and approve this example.

**Comment by dschwen** [comment]
Jake, you have a libmesh submodule update commit in this PR. Can you please remove it?

**Comment by dschwen** [comment]
Jake, you have a libmesh submodule update commit in this PR. Can you please remove it?

**Comment by dschwen** [comment]
Jake, you have a libmesh submodule update commit in this PR. Can you please remove it?

**Comment by dschwen** [comment]
Jake, you have a libmesh submodule update commit in this PR. Can you please remove it?

**Comment by dschwen** [comment]
Jake, you have a libmesh submodule update commit in this PR. Can you please remove it?

**Comment by dschwen** [comment]
Jake, you have a libmesh submodule update commit in this PR. Can you please remove it?

**Comment by dschwen** [comment]
Please squash into one commit and open a PR

**Comment by permcody** [comment]
closed in #5870
