### ISSUE TITLE
Remove threaded copies of InputParameters

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#5869]
Ideally, since InputParameters are now stored in `MooseObject` objects as a `const` reference the need for threaded copies of parameters is not necessary. In practice, this is more challenging and raises a few serious questions.

For this conversation, lets consider `Indicators`, which are created by `FEProblem::addIndicator` as follows:

```
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    parameters.set<MaterialData *>("_material_data") = _material_data[tid];
    parameters.set<MaterialData *>("_material_data") = _bnd_material_data[tid];
    parameters.set<MaterialData *>("_neighbor_material_data") = _neighbor_material_data[tid];

    MooseSharedPointer<Indicator> indicator = MooseSharedNamespace::static_pointer_cast<Indicator>(_factory.create(indicator_name, name, parameters, tid));

    std::vector<SubdomainID> block_ids;
    _indicators[tid].addIndicator(indicator, block_ids);
  }
```

Notice, that there are thread dependent values of parameters. My initial design idea for this case was to create an interface class, `MaterialDataInterface` for internal use. Note, `MaterialPropertyInterface` will not work because it isn't always a part of the inheritance chain (maybe it should be, but that is a different problem). For now, lets assume that we need to create some sort of interface so that the above code will then look like this:

```
  for (THREAD_ID tid = 0; tid < libMesh::n_threads(); tid++)
  {
    MooseSharedPointer<Indicator> indicator = MooseSharedNamespace::static_pointer_cast<Indicator>(_factory.create(indicator_name, name, parameters, tid));

   indicator.setMaterialData(_material_data[tid], _bnd_material_data[tid], _neighbor_material_data[tid]);
   
   std::vector<SubdomainID> block_ids;
   _indicators[tid].addIndicator(indicator, block_ids);
  }
```

This is where the questions are raised:

**What should this type of class be named?**
Should the interface class (`MaterialDataInterface`) have some sort of different naming since it is basically an internal MOOSE developer class: for example, `MaterialDataInternalInterface`? This would distinguish this sort of "internal" type interface from the interfaces that provide methods that the user typically interacts with.

**More importantly, where should the error checks occur?**
The more import question is, where do we perform the checks on the `MaterialData*` pointers that are being set? Generally speaking, this check should be done in `initialSetup`, but this the requires that users creating objects call `Indicator::initialSetup` in there own classes, which I have never liked even though I did this in the `Output` objects. 

I have always thought that `SetupInterface` should have a `mooseSetup` method that is private. This method would be called by its friend `FEProblem` on all objects, prior to `initialSetup`. This would allow us to keep all other `SetupInterface` methods empty in core MOOSE. It is my opinion that the setup methods should be empty for all framework level MOOSE objects so users don't need to worry about calling base class methods. The other options is that we change the documentation to **always** call `BaseClass::initialSetup`, `BaseClass::timestepSetup` regardless if they are empty.

**Comment by aeslaughter** [comment]
@permcody @friedmud @jwpeterson @brianmoose @andrsd please look and discuss this.

**Comment by permcody** [comment]
Just checking... Can we still store references to material properties in our objects if you set the `MaterialDataInterface` after construction?

I'm not too picky about the name, are you sure we even need a new class? Why not just add existing methods to the `MaterialPropertyInteface`? I mean, it seems you always need them both or none of them, unless you have a case where you need one and not the other, I don't see the need for a new class.

The setup calls may be a mess and we may need to work on that a bit. I agree that users should *not* have to call base class methods when they override a method.

**Comment by friedmud** [comment]
Meh - all sounds too complicated for marginal gain.  Just keep threaded copies.

Remember: basically -4% of people run threaded anyway... no reason to try to optimize this to death.

**Comment by aeslaughter** [comment]
@permcody 
"Note, MaterialPropertyInterface will not work because it isn't always a part of the inheritance chain (maybe it should be, but that is a different problem)."

**Comment by permcody** [comment]
Right but when would you need you MaterialDataInterface when MaterialPropertyInterface is _not_ there?

**Comment by aeslaughter** [comment]
I would try to use MaterialPropertyInterface, if we do this.
