### ISSUE TITLE
Which PiecewiseLinear file is causing the error

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#5880]
I have a bunch of PiecewiseLinear functions in my input file and at run time I'm getting the 

x-values are not strictly increasing error.

Is there a way to print out the name of the function that the error is occurring in?  If not could this capability be added?

**Comment by permcody** [comment]
Currently no, but it wouldn't be difficult to add so I'll add a few notes for whoever gets to it first.

The `LinearInterpolation` class is where this error comes from. It's a utility class so it's meant to be useable outside of MOOSE theoretically. For the most part it is with the exception of the call to `mooseError`. I propose that we make this into a true utility by removing the mooseError and actually throwing an out of range error or something similar like we've started doing in other utility classes. Inside of the `Piecewise` classes (which are derived from `MooseObject`) we can then catch those errors and print the names of the offending objects as requested in this issue. We also have the ability to properly deal with these errors in moose_unit.

**Comment by gambka** [comment]
In addition, if we are checking all the values in the various PiecewiseLinear functions would it be much more difficult to go further and say what line or what value is leading to the error?

**Comment by permcody** [comment]
That part would be very easy.
