### ISSUE TITLE
Promote Transient::lastSolveConverged() to Executioner?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5884]
Then we can get rid of line 101 in `FullSolveMultiApp.C`. This is the right thing to do IMO. It also reminds developers that the custom executioners need to provide this. I propose this for my `ApplicationWrapper` for making the query of the convergence of the last solve easier. I might miss some bigger pictures like exception handling though.

**Comment by permcody** [comment]
This doesn't sound unreasonable.

**Comment by friedmud** [comment]
Seems ok to me
