### ISSUE TITLE
NodesetWithinDistance

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5895]
Need a new MeshModifer that adds a nodeset to all nodes within a certain distance of a given point.  Syntax should look like:

```
[./nodeset]
  type = NodesetWithinDistance
  point = '0.2 0.3 0.1'
  distance = 2.7
  nodeset_id = 4
  nodeset_name = 'frog'
[../]
```

This would cause all nodes within `2.7` of the point to get added to the nodeset 4 named 'frog'.

**Comment by GiudGiud** [comment]
This will be covered by ParsedGenerateNodeset
see https://github.com/idaholab/moose/pull/28873
