### ISSUE TITLE
Extend Kim-Kim-Suzuki phase-field models to 3 or more phases

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#5903]
Build on existing KKS system for 2 phases, extend to 3 or more phases.

**Comment by dschwen** [comment]
Depends on #6240

**Comment by laagesen** [comment]
Will use the `CoefReaction` kernel to add the (Lagrange multiplier) * (Allen Cahn Mobility) term to the Allen-Cahn equation. Then need to create new kernels to calculate Lagrange multiplier as sum of variational derivative components for each order parameter.

**Comment by dschwen** [comment]
`CoefReaction` is in moose test, which is not accessible to the application. We should move it. Actually I added a `CoupledReaction` kernel to phase field last week. Maybe we can just add a MaterialProperty to that (I think the coupled version is what you need anyways!)

**Comment by laagesen** [comment]
Thanks I will take a look at `CoupledReaction`.

**Comment by laagesen** [comment]
Will create a new `CoefCoupledReaction` kernel to add Lagrange multiplier to the Allen-Cahn equation- see #6265.

**Comment by laagesen** [comment]
Ended up changing the name of kernel to add Lagrange multiplier to `MatReaction` in #6265.

**Comment by laagesen** [comment]
Closed by #6247, #6936, #7152, #7191, #7299, #7365, #7406, #7421, and #7802.
