### ISSUE TITLE
Move _currently_computing_jacobian flag into FEProblem

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#5909]
Following the discussion in #5888 and talking to @permcody we think we need to move the ```_currently_computing_jacobian flag``` into ```FEProblem```. The reason is that the Jacobian stuff for UserObjects bypasses NonLinearSystem and is run directly from FEProblem, so the flag never gets set for UserObjects.

I'll make the getter in NonLinearSystem pull the flag from FEProblem to maintain compatibility for now.

**Comment by dschwen** [comment]
Ugh, the flag is actually in ```SystemBase```. Since the getter function ```currentlyComputingJacobian()``` is not used anywhere, and since ```SystemBase``` seems like an inappropriate place anyways (would Auxiliary systems care about Jacobians?) I'm just ripping it out and transplanting it into FEProblem.

Another issue is that the flag was potentially not unset if an Exception was thrown! This should not be possible anymore in the new version.

**Comment by dschwen** [comment]
Ping @friedmud for comments

**Comment by friedmud** [comment]
+1

**Comment by SudiptaBiswas** [comment]
This makes _currently_computing_jacobian = true available for UserObjects. However, _phi & _phi.size() still yields zero in execute, which was the motivation behind moving this flag to FEProblem.

**Comment by dschwen** [comment]
That means we may need another change. But this one was certainly needed as
well. I'll look into it tomorrow.

**Comment by friedmud** [comment]
Ummm.  Wait.  What the heck are you trying to do?  phi should not be available in a UserObject at all... (they don't produce Jacobians).

What are you trying to do?

**Comment by dschwen** [comment]
@friedmud we are trying to assemble Jacobian information in a UserObject that integrates an expression across the simulation domain. It produces a single value (not a value per QP) so the effort should be manageable. We planned to set up a vector of size total ndofs and populate that with the Jacobian contribution whenever the Jacobian is being needed (otherwise we just compute the integral). 
It looked to me as if the necessary element init was being performed in FEProblem where the UOs are executes (there is a switch statement that does different initialization for LINEAR and NONLINEAR execs).

**Comment by dschwen** [comment]
There is another potential execution path via ```FEProblem::execute``` which could trigger UserObject execution in NONLINEAR _without_ having the flag set.

**Comment by dschwen** [comment]
And I wonder if we could not just make ```currentlyComputingJacobian()``` return 
```
_current_execute_on_flag == EXEC_NONLINEAR
```

Are there potential Jacobian calculations in other exec flag states? Are we ever _not_ calculating the Jacobian if the exec flag is NONLINEAR?

**Comment by permcody** [comment]
That's a good question. This is a behavior of the solver so I'm not sure if
there are any modes in which this isn't true.

**Comment by SudiptaBiswas** [comment]
I can see the flag is being set properly in UO for every non-linear iteration. The problem is even if the flag is set, _phi is not populated in UO.

**Comment by dschwen** [comment]
Ok, there is a plan.

**Comment by friedmud** [comment]
Please don't do this.  The UO system is not meant for that currently.  Don't try to bolt on your own Jacobian calculation like this.  If this is a capability you need then let's put in a request for it and talk it over and design it properly.  I have some ideas about how to do it well...
