### ISSUE TITLE
wisdom of letting our configure test automatically find things

### ISSUE THREAD

**Issue by gabkdlly** [idaholab/moose#5933]
[On the mailing list](https://groups.google.com/d/msg/moose-users/ZpVB7dOPI6U/geJTpmYCBgAJ) @jwpeterson  says the following:

> We'll need to think more carefully about the wisdom of letting our configure test automatically find things in /usr/lib, thereby bringing in that directory to the library search when the user might not want it...

Since this point is not addressed in the rest of the thread ( which after all is about a specific user's problem ), I thought it appropriate to raise as an issue, so as to illicit more comments.

**Comment by jwpeterson** [comment]
This should hopefully be addressed by the path reordering in libMesh/libmesh@648deeda9bbc16c3fea9dc73c2675da63bc4ca99.  This commit has not yet made it into the version of libmesh used by MOOSE, but it will during the next libmesh update.

Do you currently have a linking issue?  If so, you might want to try the latest libmesh master with your copy of MOOSE and see if that fixes things...

**Comment by gabkdlly** [comment]
So I navigated to the libmesh directory, and did the following:
```
git checkout master
./configure
make
```
This seems to not throw the linking errors that I was having before, so it seems your hunch was correct.  Thanks for the help !

**Comment by jwpeterson** [comment]
If you ran *exactly* those commands I think you are going to have a different problem: you just did an in-tree build and MOOSE is expecting to find an installed libmesh in $MOOSE_DIR/libmesh/installed.

**Comment by jwpeterson** [comment]
Run the update_and_rebuild_libmesh.sh script to get a libmesh build installed in the right place...

**Comment by gabkdlly** [comment]
That is a good point, but running the script updates the libmesh submodule to the latest stable release ( if I read the script correctly ).  But, I am fine with waiting until this change gets pushed to the stable release of Moose, since I am not using Moose in any production environment, just for my own learning.  Thanks !

**Comment by jwpeterson** [comment]
> That is a good point, but running the script updates the libmesh submodule to the latest stable release ( if I read the script correctly ).

It updates your libmesh to the latest submodule hash in MOOSE, not the latest version of libmesh in general.  This is safe to do (and necessary) because we've verified that MOOSE works with this version of libmesh.
