### ISSUE TITLE
Bugs seen when running a Cubit 14.0 generated mesh through MOOSE

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#5952]
We are seeing several new and incorrect sidesets being generated when running a mesh through MOOSE. It seems that `--mesh-only` is sufficient to see this issue.

See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/RO-1uNMzYxA/34lhYhhGBAAJ for the full discussion and sample mesh files.

**Comment by jwpeterson** [comment]
This could be related to a known problem with Cubit-14 writing TRI3 elements incorrectly in 3D.  This might be fixable by exporting the file as 2D in cubit, i.e.

```
export genesis "foo.e" dimension 2
```

You can see the issue if you ncdump one of the files, e.g.:

```
 elem_ss1 = 229, 280, 288, 329, 332, 469, 482, 486, 490, 497, 501, 505, 509, 
    514, 519, 526, 535, 540, 543, 547 ;
 side_ss1 = 3, 5, 3, 3, 5, 5, 3, 3, 3, 5, 5, 5, 3, 5, 3, 3, 3, 5, 5, 5 ;
```

That is, the sidesets are on side "5" of a TRI3 element, which is clearly nonsensical until you realize that Cubit is treating them as TRISHELL elements, which have 5 sides.

There was a [thread](http://sourceforge.net/p/libmesh/mailman/libmesh-devel/thread/CAJ-bnT7g-SOXXAnmhELhcQPGJLmmwqvro7jM0_J3fEBsVkn3uw%40mail.gmail.com/#msg32673256) about this on the libmesh-devel mailing list a while back:

**Comment by permcody** [comment]
I believe we've solved this issue. Don't we read these shell elements correctly now?

**Comment by jwpeterson** [comment]
Yes, this has been fixed for a while now.
