### ISSUE TITLE
A general postprocessor combining the parsed functions and function postprocessors

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5954]
I know currently we can use `MooseParsedFunction` to take postprocessors and do the evaluations by the expression and then we have `FunctionValuePostprocessor` to retrieve them back as postprocessors. It will be nicer to have a direct postprocessor to combine these two steps into one with a name like `MooseParsedPostprocessor`. This will make some of my inputs more strait-foward. Not sure if this is a reasonable request.

**Comment by permcody** [comment]
Just to be clear, you want a Postprocessor that takes an expression that contains another postprocessor?

**Comment by dschwen** [comment]
Yeah, more parsed stuff! ;-)

**Comment by YaqiWang** [comment]
Yes. It still allows general expressions with x,y,z,t.

**Comment by dschwen** [comment]
Using x,y,z does not make sense with a PostProcessor though.

**Comment by permcody** [comment]
I think we need to work on natural speech recognition next...

```
"(?:OK Google Now...)|(?:Hey Siri...) Please solve transient nonlinear heat conduction on a square domain domain with the following boundary conditions..."
```

**Comment by YaqiWang** [comment]
It will be our ultimate goal, is not it? Part of artificial intelligence, hehe.
