### ISSUE TITLE
IntegratedBC getMaterialProperty

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#5957]
Moose doesn't complain when an IntegratedBC requests a material property that doesn't exist. Found this problem through FPE exceptions in my debugger.

**Comment by dschwen** [comment]
Have you seen #5941? Could that be the issue?

**Comment by lindsayad** [comment]
No, I don't think so. These getMaterialProperty calls that are failing are in the IntegratedBC constructor

**Comment by friedmud** [comment]
@lindsayad Can you provide an input file that shows this?  It should definitely be caught...

**Comment by lindsayad** [comment]
I had a nagging thought in my head that I had encountered this before and sure enough I had.

Here's the users discussion thread:
https://groups.google.com/forum/#!searchin/moose-users/IntegratedBC$20material$20property/moose-users/s-hmCwVh_9w/fhJySbOqiioJ

And the resulting ticket #5309 that Cody opened: 
https://github.com/idaholab/moose/issues/5309

@dschwen It looks like you were able to reproduce this with one of the existing tests. If you want me to write up another, I can. I'm going to close this since we already have a ticket
