### ISSUE TITLE
Darcy Tutorial Steps crash

### ISSUE THREAD

**Issue by itgreenquist** [idaholab/moose#5966]
Steps 9 and 10 of the Darcy Thermo Mechanics tutorial crash when you run the included input files.

**Comment by permcody** [comment]
CIVET isn't reporting any failures:
https://www.moosebuild.org/job/3905/

I'm running them right now on my laptop and they appear to be working. Are you running the tests or the problems?

**Comment by itgreenquist** [comment]
I was running the problems. The tests have always passed just fine. It looks like it was a problem on my local machine because I just tried rebuilding the executable files and now everything is running fine.
