### ISSUE TITLE
Lower Dimensional Element Block From Sideset

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#5967]
A MeshModifier that can turn a Sideset into a lower dimensional element block would be a VERY useful utitlity...

**Comment by mlesueur** [comment]
Indeed. I needed lower dimensional blocks in a .msh mesh. But Gmsh can't handle them, and we don't have this meshmodifier. So atm in Moose Gmsh reader, there is a hack that allows us to do it, but it is not a clean solution.
This would solve the problem and for any mesh format!
