### ISSUE TITLE
Switch ordering of user object evaluation

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#5972]
Currently user object evaluation is ordered as: elemental, side, internal side (these three are actually evaluated together just finalized sequentially), nodal, general. We had a situation where an elemental UO wants to gather information provided by a side UO and pass them to materials. I admit that we can by-pass this situation by creating a general UO depending the elemental UO and the side UO, passing both UO to the materials or we make the side UO depend on the elemental UO. The first way will result into an extra UO, the second way will complicate the interface between UO and material, while the third way will make the code implementation kind of counter-intuitive. It is desirable to find a better way to resolve the situation.

So can we switch the ordering of user object evaluation so that the order is based on the dimensionality of the UO on, i.e. nodal, internal side, side, elemental, general? If so, we can rely on this ordering for our problem. I guess the question should be: does anybody actually rely on the ordering of elemental=>side=>internal side=>nodal? If not, are you willing to switch the ordering and formally document it? Thanks!

**Comment by permcody** [comment]
Fair question. I think a lot of people rely on General last but we haven't really focused on the intermediate dependencies. I'm open to this idea as long as it doesn't impact existing codes.

**Comment by YaqiWang** [comment]
I modified my message a little. The element UO is not depending side UO but just want to gather information from side UO and pass them to other objects like kernels, materials, etc.

**Comment by YaqiWang** [comment]
I guess I am too ambitious on this. If I change to the ordering I proposed, I saw the following framework tests are failing:
```
bcs/nodal_normals.circle_tris............................................................... FAILED (EXODIFF)
bcs/nodal_normals.circle_quads.............................................................. FAILED (EXODIFF)
bcs/nodal_normals.cylinder_hexes_1st_2nd.................................................... FAILED (EXODIFF)
bcs/nodal_normals.cylinder_hexes_2nd........................................................ FAILED (EXODIFF)
bcs/nodal_normals.cylinder_hexes............................................................ FAILED (EXODIFF)
geomsearch/2d_moving_penetration.pl_test4qnns............................................... FAILED (EXODIFF)
geomsearch/2d_moving_penetration.pl_test3qnns............................................... FAILED (EXODIFF)
geomsearch/3d_moving_penetration_smoothing.pl_test3nns...................................... FAILED (EXODIFF)
geomsearch/3d_moving_penetration_smoothing.pl_test3nnstt.................................... FAILED (EXODIFF)
geomsearch/3d_moving_penetration_smoothing.pl_test4nns...................................... FAILED (EXODIFF)
geomsearch/3d_moving_penetration_smoothing.pl_test4nnstt.................................... FAILED (EXODIFF)
```
Modules are fine. If I do the ordering `side=>internal side=>elemental=>nodal`, both framework and modules are fine. Yak is working fine for both ordering like modules.

**Comment by YaqiWang** [comment]
If we use aux kernels instead of some element and side user objects, we should be able to remove the dependency from element UO to nodal UO. I guess the reason we do not user aux kernels is that on each node, we do not loop through its attaching elements, or the other way on elements we do not loop through element nodes.

This remind me that I once wanted to evaluate the number of connecting elements belonging to a particular subdomain for all nodes. I donot know how you convert an elemental variable to a nodal variable, but it seems to me the similar loop is required.

**Comment by permcody** [comment]
You can always build your own loops, even within your AuxKernel. However it seems like a UO would be better suited for that kind of work. As far as iterating through the mesh data structure via node, element, edges etc. The methods are all available on the Mesh to make that happen. Finally to covert from an elemental value to a nodal value you just need to do a projection. That's very easy for a constant monomial element type.
