### ISSUE TITLE
Behavior of timestep=-1 in SolutionUserObject silently changed

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#5980]
Commit df1352aa3da3ef30490db8cd3f81d5c24d4190dc changed the behavior of the "timestep" parameter in SolutionUserObject.  Previously, we had to use "timestep=-1" to tell it to interpolate.  Now it interpolates if we don't put anything for "timestep", and tries to grab the -1 timestep if we ask for -1.

I think that the new behavior is an improvement, but we shouldn't just change behavior like this without an error or warning if you were using it the old way.  There are quite a few models out there that do it the old way that fail when they try to read the data at time -1.  Can timestep -1 even exist in an exodus file?  If it can, the model would run and produce different results.  If it doesn't exist, you get an error in the libmesh mesh reading code.

**Comment by permcody** [comment]
You're right. I don't know why I would have removed this without a deprecated warning or something. I can certainly add one in now.

**Comment by bwspenc** [comment]
I think that correct way to handle this is to generate an error if the user asks for timestep -1.  The error message should indicate that the user should remove that parameter to get the old interpolation behavior.  I just looked in the Exodus documentation, and it doesn't look like Exodus support negative time steps, so nobody will actually be wanting the -1 timestep (and that wouldn't have worked before either).  You can have negative times, but that's different.
