### ISSUE TITLE
line_search did not turn off when `line_search = none`

### ISSUE THREAD

**Issue by lw4992** [idaholab/moose#5984]
I track call stack when setting `line_search=none` in Executioner block, `FEProblem::computeResidual` was called once more to apply  `SNESLineSearchApply`. 

```
Stack frames: 21
0: libMesh::print_trace(std::ostream&)
1: FEProblem::computeResidual(libMesh::NonlinearImplicitSystem&, libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&)
2: Moose::compute_residual(libMesh::NumericVector<double> const&, libMesh::NumericVector<double>&, libMesh::NonlinearImplicitSystem&)
3: __libmesh_petsc_snes_residual
4: SNESComputeFunction
5: /home/lw4992/lib/moose/petsc/lib/libpetsc.so.3.6(+0x819100) [0x7f5571f7a100]
6: SNESLineSearchApply
7: SNESSolve_NEWTONLS
8: SNESSolve
9: libMesh::PetscNonlinearSolver<double>::solve(libMesh::SparseMatrix<double>&, libMesh::NumericVector<double>&, libMesh::NumericVector<double>&, double, unsigned int)
10: libMesh::NonlinearImplicitSystem::solve()
11: NonlinearSystem::solve()
12: FEProblem::solve()
13: TimeStepper::step()
14: Transient::solveStep(double)
15: Transient::takeStep(double)
16: Transient::execute()
17: MooseApp::executeExecutioner()
18: ./parakeet-opt() [0x4055a3]
19: __libc_start_main
20: ./parakeet-opt() [0x405616]
[0] /home/lw4992/projects/parakeet/src/problems/CFDProblem.C, line 125, compiled Nov 19 2015 at 10:01:52
```

Actually, The backgroud is that I MUST reduce the calling times of  `FEProblem::computeResidual`, it is too expansive for me. 

For common convergence history as following, Moose will call `FEProblem::computeResidual` three times. 

```
Time Step  1, time = 0.01
                dt = 0.01
 0 Nonlinear |R| = 2.900842e+00
      0 Linear |R| = 2.900842e+00
      1 Linear |R| = 1.408017e-03
      2 Linear |R| = 2.179453e-06
 1 Nonlinear |R| = 2.202657e-04
 Solve Converged!
```

If having any way to reduce the calling time to 1, it is very helpfull for me.

**Comment by permcody** [comment]
Well the number of times computeResidual() it is called is related to how
which solver mode you are using. If you are using PJFNK (what MOOSE is all
about), then yes you'll get at least n+1 calls where n is the number of
linear residuals in your solve. That's the finite differencing that's
happening to approximate your Jacobian matrix. If you have a complete and
accurate Jacobian ( which means you probably aren't running a very complex
Multiphysics Problem) then you can use a different solve type such as
NEWTON which only calls the compute residual once per Nonlinear solve.

We'll have to take a look at the line search behavior and get back to you.

**Comment by lw4992** [comment]
The Jacobian matrix can be computed quite accuracy in my case, and can be frozen, so,  NEWTON model is the best choise, computeResidual() is my dominant cost.

**Comment by permcody** [comment]
Great, Please report back if this works for you.

**Comment by lw4992** [comment]
Jacobian matrix had done two months ago, it worked quite well, even be frozen. My current ENERMY is computeResidual(), it is too cost. If calling times of computeResidual() can be reduced to 1 as before 3, the efficiency can be improve 2~3 times, since the Jacobian matrix was frozen.

**Comment by friedmud** [comment]
I believe the extra residual evaluation at the end of a nonlinear solve is
due to preconditioning needing to be undone.  Maybe it has something to do
with right vs. left preconditioning?

Maybe Jed Brown will illuminate us.  (If I speak the name "Jed Brown" 3
times in a mirror while turning around each time will he appear and grace
us with his limitless PETSc knowledge? :-)

Derek

**Comment by dschwen** [comment]
PETSc should be rewritten in C++ and GPU accelerated. There, that should do
it ;-)

**Comment by permcody** [comment]
@fdkong - Just going through old tickets and stumbled on this one. I'm not even sure there's an issue here, but it pre-date you starting at the lab. Do you see anything here that we should look at? Maybe we should just close and justify.

**Comment by lindsayad** [comment]
There is no issue here. Even when "not performing a line search", you still do a function evaluation at the end of the linear solve to:

1. Determine whether you are converged
2. If you are not, then you use this function evaluation as the RHS for your next linear solve

`line_search = none` just means you take the full Newton step every time
