### ISSUE TITLE
Run debug tests in parallel

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#5992]
@roystgnr asked about this in libMesh/libmesh#719.  Seems like a reasonable idea to me, we'll just need to see if it unduly affects the overall time required for tests.  Maybe this issue should actually be on the civet project for @brianmoose...

**Comment by permcody** [comment]
:+1:

**Comment by brianmoose** [comment]
I added the extra paralllel test to the debug pr recipe

**Comment by permcody** [comment]
Did you create a new step or just change the existing step?

**Comment by brianmoose** [comment]
Yeah, I created a new step. Now the debug version does the same steps as the non debug one.

**Comment by permcody** [comment]
Sounds good
