### ISSUE TITLE
Warning messages do not appear in console output files

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#5994]
When outputting console output to a text file using `output_file = true`, warning messages do not get written to the file.

**Comment by permcody** [comment]
Notes: To fix we need to make sure that both STDERR and STDOUT make it to the file. Also, we should probably automatically disable the color strings at least for the file if that's not too much of a burden.

**Comment by permcody** [comment]
@rwcarlsen - let's take a look at this with your new PR to update the warn/error printing. This might still be an issue but maybe not.

**Comment by rwcarlsen** [comment]
This will be fixed for stdout generating calls to moose[Bla] inside any MooseObject.  stderr writes though have never had infrastructure to control how they are handled - just straight to std::cerr basically.

**Comment by rwcarlsen** [comment]
Fixed by #8411
