### ISSUE TITLE
Append date to output files

### ISSUE THREAD

**Issue by gardnerru** [idaholab/moose#6001]
I would like an option to append the date to the outputted file's name from a simulation (ie. input_out_11252010.csv). Im not sure what make more sense, the date completed or the date started.

**Comment by aeslaughter** [comment]
It will be the date/time when the simulation was started, we need to know the filename so we can write to it along the way, so we can't use the end time.

**Comment by permcody** [comment]
Russell, We have support for GetPot's DBEs (Dollar Bracket Expressions) so
this is now possible. I'm on the road today so I'll try to get you an
example when I can.
