### ISSUE TITLE
Valgrind errors in modules

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#6003]
Using uninitialized variable in tensor_mechanics/src/userobjects/ElementPropertyReadFile.C
Memory leak in phase_field/src/materials/DerivativeParsedMaterialHelper.C
Memory leak in phase_field/src/auxkernels/TestEBSDAux.C
Using uninitialized variable in superlu_dist in petsc.

**Comment by brianmoose** [comment]
The errors in superlu_dist seem to be fixed in petsc 3.6.2

**Comment by YaqiWang** [comment]
@brianmoose Can you help me use valgrind to check yak? I can do the fix. Best.

**Comment by brianmoose** [comment]
I created a recipe for yak master to run the tests with valgrind.

**Comment by permcody** [comment]
@brianmoose are there more errors remaining?

**Comment by brianmoose** [comment]
The above are fixed (besides petsc) but there might be more. The nightly tests don't do everything because they reach max fails.

**Comment by dschwen** [comment]
I'll do the smart pointer stuff for the EBSDAccessFunctors

**Comment by jwpeterson** [comment]
What, it's already done in https://github.com/idaholab/moose/pull/6010

**Comment by dschwen** [comment]
Ugh, I was looking for this and did not find it. I thought you mentioned that was merged already and figured you must have meant something else.

**Comment by jwpeterson** [comment]
On Thu, Dec 3, 2015 at 12:46 PM, Daniel Schwen <notifications@github.com>
wrote:

> Ugh, I was looking for this and did not find it. I thought you mentioned
> that was merged already and figured you must have meant something else.
>

Well, it can be merged if you want.  @permcody already +1'd it.

-- 
John

**Comment by brianmoose** [comment]
Jason updated the build boxes with pets 3.6.3 and now everything passes.
