### ISSUE TITLE
Ability to turn off "map" option for Exodiff

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6011]
A test might want to disable to `map` option for Exodiff.

An example is that the `map` option fails if two elements are perfectly on top of each other (which you might be trying to do on purpose....

**Comment by permcody** [comment]
Is it time for exodiff_args?

**Comment by permcody** [comment]
See my comment on the PR - we have "exodiff_opts" available already.

**Comment by friedmud** [comment]
See my comment on the PR: that's not sufficient because mapping is hard
coded to be ON in Python

**Comment by permcody** [comment]
Yeah I see
