### ISSUE TITLE
Add Variable Jump Indicator

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#6013]
We have a gradient jump indicator (approximately a measure of the variable laplacian), but no variable jump indicator (approximately a measure of the variable gradient). This might be useful for convection dominated problems where steep gradients can often lead to oscillations in the solution variable. It is straightforward to create this in one's own application, but it might be nice to just have it already exist in the framework.

**Comment by jwpeterson** [comment]
Variable jump doesn't make sense for continuous Galerkin, so I assume you are talking about DG?

**Comment by lindsayad** [comment]
You're right haha. I guess what I had in mind was a way to refine h_i of 
element_i based on the difference between u at node_i and u at 
node_{i+1}. Is such a thing feasible?

**Comment by jwpeterson** [comment]
It's feasible, but I don't think it makes for a mathematically rigorous or theoretically justifiable error indicator... but that doesn't mean it wouldn't be useful for a particular application, though.

**Comment by friedmud** [comment]
I don't know about what you're proposing here... but a `ValueJumpIndicator`
(jump in variable value across element edges for discontinuous basis
functions) would be useful for DG and other purposes and should be added to
MOOSE.

**Comment by lindsayad** [comment]
Closed by #10474
