### ISSUE TITLE
Add ability to set input file parameters from master app

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#6023]
I want to do this:

```
[MultiApps]
  [./sub]
    type = TransientMultiApp
    cli_args = Executioner/start_time=0.3
    ...
```

The motivation is as follows. I update the MultiApp to use the new warehouse structure, which includes the ability to enable/disable objects with time. Thus, we can now delay the start of a multiapp so the start_time in the multiapp must be set to match when it starts (or at least be an option). Currently, you need to to this in the subapp input file, but it may be nice to be able to do this from the master input file.

**Comment by friedmud** [comment]
I'm not sure about the particular motivation (that sounds like it should be automatic)... But the basic idea doesn't sound bad.

**Comment by YaqiWang** [comment]
I want this to run multiple multiapps using the same input file but just varying in one parameter.  I know I can override the multiapp parameters from command line, but I will have to remember the command line syntax.  This resides in the master input file and can be handy. Anybody is interested in working on this?

**Comment by permcody** [comment]
No plans to work on this, but I want to make sure that whoever does is well aware of the existing capability of overriding one or more sub-app parameters right from the CLI, so we don't invent a completely separate and disjoint system to make this work.

**Comment by friedmud** [comment]
I like this - and I’m with Cody that it should piggy back on the existing
capability.

**Comment by aeslaughter** [comment]
This was accomplished via the MultiAppCommandLine control in #12594.
