### ISSUE TITLE
Need way to apply out of plane pressure to 2D generalized plane strain model

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6024]
In the 2D generalized plane strain formulation in solid mechanics, we have a kernel to take the out of plane stress and assemble it to the residual corresponding to the out of plane strain variable.  We need something similar to that to be able to apply a prescribed pressure in that direction.  This would be very similar to the standard pressure BC we apply to surfaces in solid mechanics, but it would be a Kernel instead of a BC since it needs to integrate over a 2D volume.

**Comment by permcody** [comment]
@bwspenc - based on comments in #6025, perhaps this issue should be closed?

**Comment by bwspenc** [comment]
I'm closing this, and creating a new issue to add an option to prescribe a body force with a postprocessor.  That will meet the needs of this issue.

**Comment by bwspenc** [comment]
I went ahead and implemented an option to prescribe a BodyForce with a Postprocessor. I'm reopening this issue, however, because I think it's better to have a custom kernel for this purpose. The sign convention of BodyForce is the opposite of what we need for this purpose, and it doesn't use the displaced mesh by default, so I think its use will be error-prone. I have a commit that I'll submit shortly to close this issue.
