### ISSUE TITLE
Residuals & Strongly Coupled Physics

### ISSUE THREAD

**Issue by bakeba** [idaholab/moose#6036]
I was wondering if there is any way to print out the residuals for individual physics when using strongly coupled physic equations. I have a case where I have two coupled physics variables and in order to obtain the converged solution for both variables I have to perform many tests by changing the scaling for one of the variables and the source_abs_tol in the executioner. I also use source_rel_tol =-50 so that the abs_tol is the only thing I need to worry about changing in the executioner. I'm just wondering if there is a faster way to do this by looking at the individual variable's residuals instead of the joined residual. 

Thanks,
Ben

**Comment by dschwen** [comment]
Hey Ben, use
```
[Debug]
  show_var_residual_norms = true
[]
```
And let's keep support questions on the mailing list and use the issue tracker for feature requests and bug reports.

**Comment by bakeba** [comment]
Sorry about that. I wasn't sure how to submit the question.

Benjamin Baker
PhD Nuclear Science & Engineering
Idaho National Laboratory
phone: 208.526-5350
email: benjamin.baker@inl.gov

**Comment by dschwen** [comment]
The mailing list is 
moose-users@googlegroups.com
https://groups.google.com/group/moose-users
Cheers,
Daniel
