### ISSUE TITLE
DGKernel has wrong shape functions on Moose::Element side for computeOffDiagJacobian

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#6041]
Currently in the ComputeFullJacobianThread::computeInternalFaceJacobian() method, we have this line:

        dg->subProblem().prepareFaceShapes(dg->variable().number(), _tid);

I believe it should be:

        dg->subProblem().prepareFaceShapes(jvar, _tid);

**Comment by friedmud** [comment]
That _does_ look odd.  @andrsd can you comment on this?

**Comment by andrsd** [comment]
This is a correct fix :+1:

**Comment by permcody** [comment]
Closed in #5943
