### ISSUE TITLE
Remove ksp_grmres_restart (typo) from enumerated PetSC options

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#6048]

**Comment by laagesen** [comment]
Needs to get fixed in several input files too.

**Comment by dschwen** [comment]
Just FYI, I assembled the lists of "commonly used PETSc options" using a shell script that scraped all options from all input files under moose. I blame somebody else for that typo.... who wants to dig through the git history? ;-)

On a more serious note, it would be nice to have an (optional) check for unconsumed PETSc options.

**Comment by jwpeterson** [comment]
> Just FYI, I assembled the lists of "commonly used PETSc options" using a shell script that scraped all options from all input files under moose. I blame somebody else for that typo.... who wants to dig through the git history? ;-)

Sorry @dschwen, that typo is all your own, `git log -Sksp_grmres_restart` doesn't return any commits in the PETSc repo.

**Comment by jwpeterson** [comment]
@tonkmr seems to have originated it in Marmot, see commit d6a70310d3356df7.

**Comment by dschwen** [comment]
9 9 9! d6a70310d3356df7e50e2a65a291ff1c174c1ea0 in the marmot repository! That is from 2010!

**Comment by dschwen** [comment]
Beat me by 10 seconds

**Comment by jwpeterson** [comment]
Not 9 seconds?

**Comment by tonkmr** [comment]
I neither confirm nor deny the source of this error

--
Michael R Tonks
Assistant Professor of Nuclear and Mechanical Engineering
Pennsylvania State University
233 Reber Building
University Park, PA 16802
michael.tonks@psu.edu
814-863-1323
