### ISSUE TITLE
Can MOOSE provide some guidelines on scaling variables for multiphysics simulations

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6069]
Variables of difference physics could have significantly different magnitude. If we do not scale them properly, we may not converge the solution tightly as we would think with a quite small tolerance. Currently the scaling is up to users with trial and error approach. So my question is that can we make MOOSE automatically scale variables when users want to? I do not have an answer for this and am not sure if this is proper as well to ask framework developers for this kind of help.

**Comment by mangerij** [comment]
Is there a way of using the new control system to do this iteratively?

For example, if the first few time steps are failing then scale variables ect?

**Comment by mangerij** [comment]
I also thought along the same lines, you could take a certain problem, then use the control system to iteratively scan through the PETSc options in a smart way to find the optimum solve options. You could optimize against solve time or accuracy. These are just ideas ...

**Comment by YaqiWang** [comment]
Interesting. How do we get the reference solution?

Is there any rule of thumb we can use to get a decent scaling?

**Comment by mangerij** [comment]
The only thing I can offer is my own personal experience:

If you have a large group of coefficients, and if they are all around order one you don't need to use the internal scaling of residuals or at least I didn't have to for our problem but I suppose radically different physics offers a particular challenge. I only ever know about scaling residual components and that never made any sense to me. I'm just glad the SI unit system nanonewton, attocoloumb, and nanometer are useful for our app... so far

**Comment by permcody** [comment]
Doesn't report an issue or a requested enhancement. Closing.

**Comment by YaqiWang** [comment]
Looks like lots of people are interested in the answer of this question (#12601). If MOOSE can provide a robust solution of automatic scaling for multiphysics simulations, it can help users significantly.
