### ISSUE TITLE
TransientInterface is the base class of Material but its valid parameters is not inherited

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6071]
As title. I think this is a bug.

**Comment by permcody** [comment]
While this may be a bug, did you actually run into a problem here? The only parameter in TransientInterface is `implicit`.

**Comment by YaqiWang** [comment]
I noticed this in one of my materials when trying to call `getParam<bool>("implicit")` . You can reproduce it by comment out line 24 of `yak/src/common/materials/SsrcMaterial.C`.
