### ISSUE TITLE
Remove Export Control

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6093]
MOOSE is freely available and therefore does not fall under export control.

Paragraph (b) of 734.3 under Title 15, Subtitle B, Chapter VII, Subchapter C of the Code of Federal Regulations states that itesm that are already published (as described in 734.7) do not fall under EAR99 (MOOSE's previous designation).

**Comment by friedmud** [comment]
Yay!

**Comment by hereiam-at-mit-dot-edu** [comment]
Hooray! Thanks, everyone!
