### ISSUE TITLE
Make values of last Newton iterate available via `Coupleble` interface

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#6101]
# Motivation

The motivation comes from RELAP-7. While we do have an implicit solve, because our 7-eqn model is a system of stiff equations, we have a lot of "material properties" that are very complicated functions. Those are generating Jacobian terms, which we really do not want to derive and finite differencing them may not be a way, since they are quite often non-smooth.
# Implementation

This is definitely possible via PETSc - we had it in MOOSE before, but it was removed, since no app was actually using it.

What should be the name of the function, i.e. `coupledOldNewton`, `coupledOldNIter`, `coupledNLValue`? What do you guys think?
# Discussion

The major question to ask is why not use `coupledOld`? The answer I heard was: When `dt` is huge (i.e. 1e6 secs), we do not want to feed one week old values of those material properties into our equations.

**Comment by friedmud** [comment]
Essentially, what you're attempting to do is turn your solve into a Picard solve.  While that may be a feasible thing to do... it is probably going to take MANY more iterations to converge than you want.

That said, I'm not completely against this idea... it would be interesting to try out.

One thing I wonder though: since you're doing this for Material Properties... Are you going to need the last Newton iteration's stateful properties as well?

**Comment by andrsd** [comment]
> it is probably going to take MANY more iterations to converge than you want.

That's one of the things I am afraid of.

> Are you going to need the last Newton iteration's stateful properties as well?

No. I just need old values of primary and aux variables to compute these quantities (some are material properties in MOOSE sense, some are other aux-variables).

> it would be interesting to try out.

I guess I'll try to implement something and based on the result we can discuss if we want that in the framework or not.

**Comment by andrsd** [comment]
Initial implementation is available in [andrsd/newton-iter](https://github.com/andrsd/moose/tree/newton-iter). I did not do any testing in RELAP-7 yet, I am just putting it here so people can look at it.
