### ISSUE TITLE
Function Deleter

### ISSUE THREAD

**Issue by ProfessorHoover** [idaholab/moose#6109]
This issue is for tracking the function deleter based off the block deleter from #3080.
It will accept a function for the area to remove from the mesh.

**Comment by permcody** [comment]
@WilkAndy - I haven't heard anything from @ProfessorHoover in a long time... Do we expect him to complete any tickets?

**Comment by WilkAndy** [comment]
No, he won't be contributing.  You may close this issue if you like.  It is a feature that i'd like, but i won't have time to work on it for.... goodness knows how long!

**Comment by WilkAndy** [comment]
I think this issue should be closed, @permcody .   If someone wants this functionality they probably won't be trawling back through thousands of issues just to find this one.

**Comment by permcody** [comment]
Closing as unfinished...
