### ISSUE TITLE
execute_on = final?

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6112]
@aeslaughter could we get a `final` option for the `execute_on` to have a UserObject execute once the simulation ends?

**Comment by aeslaughter** [comment]
Probably, what kind of priority is this?

**Comment by friedmud** [comment]
@aeslaughter @dschwen I believe this capability is in - can we close this?

**Comment by permcody** [comment]
I don't think this works for Steady but it also doesn't really matter since TIMESTEP_END is effectively the same thing. One of these days we need to drop Steady.

**Comment by YaqiWang** [comment]
I know eigenvalue executioners do not have this as well. We can have a small PR to fix Steady and them.

**Comment by friedmud** [comment]
In the PR I'm working on now I added the ability to output on final in steady executioner: https://github.com/idaholab/moose/pull/11552/files#diff-b7456ec2f6a5afb0c1eecc7b7477452fR113
