### ISSUE TITLE
no_exodiff_map test asserts in dbg mode in parallel

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#6123]
Reproduce with:
```
mpiexec -np 2 ../../../moose_test-dbg -i no_exodiff_map.i
```

It's likely this test has never worked in debug in parallel... We didn't see this failure on the original PR testing because we don't test in parallel in dbg mode.  Libmesh PR tests, on the other hand, do test that way, so you can see a failure over on libMesh/libmesh#766.

The test "works" in parallel in opt mode, so we need to figure out if the assert is just overzealous, or if there is something more serious going on there.

**Comment by jwpeterson** [comment]
This seems to be fixed by the commits in libMesh/libmesh#719, so it can be closed if we're ever able to do a libmesh update...

**Comment by permcody** [comment]
Fixed in the Jan 19, 2016 libMesh update. We will begin testing a parallel debug target in the nightly master branch. This should be promoted to PR testing when the new test cluster is available.

**Comment by friedmud** [comment]
Should we leave this open for now so we can remember to reenable the test?

**Comment by permcody** [comment]
The test isn't disabled. We just didn't have a parallel debug
configuration. Brian is adding that now so it will get tested going forward.
