### ISSUE TITLE
Derivatives w.r.t. auxvars in DerivativeSumMaterial

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#6124]
DerivativeSumMaterial does not compute derivatives w.r.t. auxiliary variables. This is in contrast to DerivativeParsedMaterial which calculates derivatives for both nonlinear and aux variables.

The application is for taking the derivative of the free energy for use in point defect reactions modeling (not necessarily phase-field). For example, in dealing with vacancies, the nonlinear variable would be the concentration of vacancies, cvac, while site conservation says the concentration of lattice atoms would be 1-cvac, for which I have been using ParsedAux.

The driving force is the difference in chemical potentials, which in turn can be taken from the derivative of the free energy.

Obviously this is a simplified example. In reality, I have many variables, some to be solved for and some derived, for which I have been using DerivativeParsedMaterials within an action to create their own contribution to the free energy, and was planning on using DerivativeSumMaterial to combine them all together.

**Comment by dschwen** [comment]
Ok, @tophmatthews, yo'll have to spell this out in more detail. At what point to you want to take a derivative w.r.t. an Auxvariable? Do you want to do dF/d(1-cvac)?! How is that supposed to work? Bear in mind that any chain rule derivatives involving AuxVariables are currently not possible (and won't be, most likely). However, what _is_ possible are chain rule derivatives involving Material properties.

**Comment by tophmatthews** [comment]
No, I want to take the derivative with respect to the auxvariable. I want to avoid writing out the free energy in one go, but piece it together using DerivativeSumMaterial. As an example, the value of the auxvariable MIGHT be defined by 1-cvac, but I want the derivative of the free energy with respect to the auxvariable.

G = Hvac * cvac +Hu * cu + kb * T * (cvac * ln(cvac) + cu * ln(cu))
mu_cvac - mu_cu = dG/dcvac - dG/dcu = Hvac - Hu + kb * T * (ln(cvac) * ln(cu))

This is just an early example. Things will get more complicated later.

In the attached example, I want DerivativeParsedMaterial (Fc) and DerivativeSumMaterial (F) to do the same thing.

My work around is to input the entire free energy function using DerivativeParsedMaterial, which is non-modular and prone to errors.

[bugtest2.txt](https://github.com/idaholab/moose/files/80262/bugtest2.txt)

**Comment by tophmatthews** [comment]
I calculate the mu values separately using:

&getMaterialPropertyDerivative<Real>("f_name", *_example_names[i]);

**Comment by dschwen** [comment]
if `cu = 1-cvac` then `dG/dcu` is not giving you what you think it does, because `cvac = 1-cu`. You cannot get the correct chain rule derivative doing this!

**Comment by tophmatthews** [comment]
Quite obviously.

I'm not sure I understand your reluctance, but the discussion has lead me to another way around this that may be more elegant.

**Comment by dschwen** [comment]
This is not reluctance. I just want to make sure I understand _what_ you want, and _if_ making the requested change actually _solves_ your problem. So out of curiosity, which way have you chosen now?

**Comment by dschwen** [comment]
I'm reopening this. I actually remembered where derivatives w.r.t. AuxVariables are necessary, and that is when computing gradients of functions, where the dependent AuxVar has a gradient!

It _needs_ to be added to DerivativeSumMaterial.

**Comment by tophmatthews** [comment]
Cool!

To respond to your previous question, your questions made me realize I could pass the definition of the auxvariable directly to the free energy equation. I was doing some complicated linking with ParsedAux's AND DerivativeParsedMaterial's to capture the chain rule...totally unnecessary! So now I don't need this (at this point that is...I think...) Thanks for your help though! I'm looking forward to even more improvements using parsed equations.

**Comment by dschwen** [comment]
Yeah, do you know about the sub-term stuff in the parsed materials? Your function could be

```
'c2 := 1 - c1; E1*c1 + E2*c2'
```

This would give the correct derivatives w.r.t. to c1 and allows you to structure parsed function expressions more cleanly. Also look at `ExpressionBuilder`, which can be used to construct free energy expressions in .C files 

http://mooseframework.org/wiki/PhysicsModules/PhaseField/DevelopingModels/ExpressionBuilder/
