### ISSUE TITLE
Deprecate old TensorMechanics classes

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6125]
Stuff like `FiniteStrainElasticMaterial` and `LinearElasticMaterial` should not be used anymore. Let's officially deprecate them and purge them from our examples!

**Comment by mangerij** [comment]
We still inherit from LinearElasticMaterial in our LinearFerroelectricMaterial

I just made ferret public again if you want to take a look:

https://bitbucket.org/mesoscience/ferret

**Comment by mangerij** [comment]
I meant to write also, I'm not sure how to code it so it will run without inheriting from that class

**Comment by dschwen** [comment]
@mangerij , what does that material actually do? The new way of doing TM is to have the monolithic old classes split up into multiple modular classes that each have a specific task. I.e. instead of computing _both_ stress _and_ strain in one class, we have separate classes for both quantities.

**Comment by dschwen** [comment]
Side note: ferret would benefit from the pretests (style enforcement) and from fixing indentation. The code is hard to read on bitbucket as it is.

**Comment by mangerij** [comment]
I have been using the ComputeLinearElasticStress and similar classes in addition to this LinearFerroelectricMaterial.C file.

This material takes the elasticity tensor and contracts with a "electrostrictive" tensor to introduce a low-order coupling between ferroelectric and elastic order parameters. 

I think this file is a computational bottleneck in our code, you'll see at Ln 58, we call computeProperties() at every quadrature point for this contraction. I don't want this at the moment(this tensor should be same throughout the block) but for some reason this is all I could get to compile.

**Comment by dschwen** [comment]
Electrostriction is (or causes) a stress? I think I need to look at this in more detail once I'm back from travel, but it should be easy to port this to the new system. If you compute a new elasticity tensor then you could derive from `ComputeElasticityTensor` (there should be examples where tensors are precomputes to avoid the same computation at each qp. If you need to modify the stress then you need to inherit from `ComputeStressBase` (or a derived class, such as the linear stress variant).

**Comment by dschwen** [comment]
Time to act on this and at least add the mooseDeprecated macro (if not the registerDeprecated)

**Comment by permcody** [comment]
Closed by 398dfa26cff835a5091b7c39804e246be527e4d6
