### ISSUE TITLE
Add MeshModifier that biases the grid

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#6129]
Originally discussed over in libMesh/libmesh#767, I think we have decided to implement this as a `MeshModifier` in MOOSE since the need is MOOSE-application specific.  The current design idea discussed with @jasondhales is for the user to (initially) provide a `bias_x` parameter in the range `0.5 <= bias_x <= 2` which determines whether the elements shrink or grow in the x-direction.

**Comment by YaqiWang** [comment]
I was thinking moving nodes as well. If we can move a nodes based on a function `Point f(Point & p)`, that will solve my problem as well, including making the mesh unevenly distributed in the extruded direction generated by the mesh extruder. We can name this modifier as `DisplaceNodes`. What do you think?

**Comment by friedmud** [comment]
Heh - could it be time to revive my old Masters thesis code?

https://github.com/libMesh/libmesh/blob/fe4edd569634ef972494070c14cfccdb75083f5a/src/mesh/mesh_smoother_vsmoother.C

(Note: I didn't write most of that code... just adapted it to libMesh ;-)

**Comment by friedmud** [comment]
In case you don't want to read the whole thing: it allows you to specify a scalar value per element that essentially represents how important that element is (i.e. an "error indicator")... it will then attempt to move the mesh to best capture the "error".

This is knows as "r"-adaptivity (mesh redistribution adaptivity).  You get better solutions without adding any DoFs!

Handy... but the code is absolutely heinous ;-)

**Comment by jasondhales** [comment]
So, what's the next step?  We could fairly easily (now that @jwpeterson has given an example) do something similar in SmearedPelletMesh.  Or, do we need to wait for the mesh modifier version?

**Comment by jwpeterson** [comment]
Well, I currently don't think a MeshModifier (based on `MeshTools::redistribute()`) makes sense for this specific task for a couple of reasons (see below).  I'm happy to help more with implementing the biasing in SmearedPelletMesh, just let me know... 

---

1. You need to know all the stuff that `GeneratedMesh` already knows (`nx`, `xmin`, `xmax`, etc.) in order to define the "function" which maps the original node positions into the biased node positions.  So, in order to avoid having the user define all this stuff twice you would need to share parameters from the `GeneratedMesh` block with the `MeshModifier`, hence making the `MeshModifier` explicitly depend on `GeneratedMesh`.

1. The "function" which maps the node positions isn't a continuous function of x, y, and z (at least, I couldn't figure out how to make it into one). Instead, it only applies specifically to the node positions of the original mesh... Also I don't even know what it means to bias the node positions of a "non-rectangular" i.e. non-generated mesh.

**Comment by friedmud** [comment]
Just a heads up about your # 1:  ai think all of that information is already captured on the MooseMesh to help with auto direction periodic BCs...

**Comment by jasondhales** [comment]
I made changes to the SmearedPelletMesh in Bison, and they have been merged.  Seems to be working great.  Thanks, @jwpeterson, for all the help.

**Comment by jwpeterson** [comment]
> Thanks, @jwpeterson, for all the help.

You're welcome, glad it's working.



> Just a heads up about your # 1: ai think all of that information is already captured on the MooseMesh to help with auto direction periodic BCs...

Looks like `MooseMesh has `dimensionWidth(component)`, but I'd also need the number of elements in the x, y, and z directions.  What might also work, as @permcody pointed out, is that the `MeshModifier` could simply try to `dynamic_cast` the `Mesh` it receives to a `GeneratedMesh`, and we could provide accessors for the needed parameters... something to keep in mind if the need for a more generic  `MeshModifier` version of this is needed in the future.
