### ISSUE TITLE
Thermal contact (without quadrature option) gives incorrect results in parallel

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6135]
The node/face option (quadrature=false) in thermal contact does not work correctly in parallel.  Heat is transferred only between faces when the two faces are on the same processor.  This can be seen if the following regression test is run with two processors:
modules/combined/tests/generalized_plane_strain_tm_contact
To run this test in parallel, use the commented-out superlu petsc options instead of the ones that are currently active in the test.  The test consists of two small blocks.  In 2-way parallel, they end up on different processors, and the thermal field is wrong in the block on the right.

**Comment by friedmud** [comment]
That can't be the only trigger.  We've been running thermal contact tests since the beginning in parallel.  The two blocks _always_ end up on two different processors because they are disconnected.

Something else is going on here.  Could be a regression.

**Comment by bwspenc** [comment]
I have looked at this on a larger model, and the only region where heat is correctly transferred is where the meshes on both sides of the interface are on the same processor.  I'm pretty sure that when I originally set this test up, this worked in parallel, so yes, this probably is a regression.

**Comment by bwspenc** [comment]
I found the problem.  Someone had added an option to skip off-processor slave nodes, which is being used by MechanicalContactConstraint.  The test case uses thermal and mechanical contact, and since they share the same PenetrationLocator, the off-processor slave nodes are not allocated.  This means that the DiracKernel that is used for thermal contact never gets applied to the master side if the slave side is off-processor.  Whoops!  That option appears to be purely for optimization.  I'm working on a fix.
