### ISSUE TITLE
Fix strain rate in tensor mechanics

### ISSUE THREAD

**Issue by cpritam** [idaholab/moose#6143]
In all incremental strain calculation classes in the TensorMechanics module, the strain_rate tensor is calculated according to:

```
_strain_rate[_qp] = _strain_increment[_qp] / _t_step;
```

`_t_step` is actually an integer, the number of the time step.

It should rather be

```
_strain_rate[_qp] = _strain_increment[_qp] / _dt;
```

**Comment by permcody** [comment]
Reported here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/gwAdMUbd3eM/lsW3WAlQCwAJ
