### ISSUE TITLE
Expanded options for cylindrical/spherical gap geometry

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6161]
We currently have an option for thermal contact to make appropriate modifications to the gap conductance when it is known that the gap is cylindrical or spherical. This allows gap conductance to be used with large gaps on these types of geometry.

The current implementation only allows these options to be used with axisymmetric or spherical coordinate system models.  They are also applicable to higher dimensionality models when they have this type of geometry.  Add options to allow the user to ask for these formulations in those cases.

**Comment by permcody** [comment]
I see this failed to build with BISON, does this PR require an application patch or is that just an unintentional error?

**Comment by permcody** [comment]
Closed by #6164

**Comment by bwspenc** [comment]
I kept this open because @novasr is working on some additional tests for this. I believe they are close to being ready.
