### ISSUE TITLE
Naming of InputParameters::paramSetByUser()

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6174]
Every other method to query things about the parameter in InputParameters starts with "is", but this one doesn't.  For consistency with function names like isParamValid(), isParamSetByAddParam(), etc, it should be renamed to isParamSetByUser().

**Comment by permcody** [comment]
:+1: 

I would like to continue supporting the old interface for awhile so the new name should be added alongside the old one. The old one should then be deprecated.

**Comment by bwspenc** [comment]
@permcody I'm fine with that, but not really sure that's necessary because this is pretty new, and is only used in a few places.  I'll do a pull request in just a second that removes it to see if it breaks any of the apps we test.

**Comment by permcody** [comment]
OK - I'll play along. We're an open-source framework though. We don't like to screw around with our users too much :smile:
