### ISSUE TITLE
PBS on HPC issues 

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#6182]
PBS options in the TestHarness do not seem to work when being used outside the users home directory... odd.

**Comment by milljm** [comment]
This is still not working the way we want it. Also, the 'odd' part turned out to be an environment issue. Where I was inadvertently setting MOOSE_DIR= in my bash_profile. My version of MOOSE was obviously not the same Bison was testing against. My bad.

**Comment by permcody** [comment]
What me to tag it closed:PEBKAC?

**Comment by jwpeterson** [comment]
> What me to tag it

What me?  What you!

**Comment by permcody** [comment]
Doh!

**Comment by permcody** [comment]
closed by #6185
