### ISSUE TITLE
ParallelMesh regressions on OS X

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6190]
It appears that we have picked up regressions with parallel mesh on OS X. I haven't looked to see when we picked these up because none of routinely run full dbg mode on our Mac. It does appear that both unique-id and parallel-mesh are required to replicate errors though. Here's a typical message:

```
utils/random.test_par_mesh: Working Directory: /Users/permcj/projects/moose/test/tests/utils/random
utils/random.test_par_mesh: Running command: mpiexec -host localhost -n 2 /Users/permcj/projects/moose/test/moose_test-dbg --n-threads=1 -i random.i Mesh/distribution=PARALLEL Outputs/file_base=parallel_mesh_out --error-unused --no-gdb-backtrace
utils/random.test_par_mesh: 
utils/random.test_par_mesh: Assertion `this->comm().semiverify(obj ? &uniqueid : __null)' failed.
utils/random.test_par_mesh: 
utils/random.test_par_mesh: Assertion `this->comm().semiverify(obj ? &uniqueid : __null)' failed.
utils/random.test_par_mesh: 
utils/random.test_par_mesh: [0] src/mesh/parallel_mesh.C, line 904, compiled nodate at notime
utils/random.test_par_mesh: [1] src/mesh/parallel_mesh.C, line 904, compiled nodate at notime
```

**Comment by permcody** [comment]
@roystgnr - A user just reported this error and I wanted to run it by you. I haven't been able to replicate a pure libMesh test case yet but it appears that we hit this assert in several fairly simple tests cases in MOOSE provided all of the following are true:

 - On OS X (still confirming this, but our test boxes are not hitting this error and they should be)
 - Using Parallel Mesh
 - Unique IDs enabled
 - Executing in parallel

Unfortunately, we have zero OS X boxes available for testing in our enclave right now :frowning: If you have any quick ideas or you see something that jars your memory let me know and I'll give it a try. I'll report back if I come up with a libMesh case or am able to replicate this on Linux.

**Comment by roystgnr** [comment]
Are they using BoundaryInfo::sync() by any chance?  I just caught a failure in that case last week:

https://github.com/libMesh/libmesh/pull/774

Hmm... no, nothing about boundary meshes in random.i - in fact that looks like it's just doing a plain build_square??  No way should that be failing.

A stack trace would be very helpful here - that assert is the "unique_id out of sync" error, but without knowing *where* it went out of sync I'm clueless.

**Comment by permcody** [comment]
I was able to replicate on test/tests/kernels/simple_diffusion (arguably our most basic test) by passing `--parallel-mesh` and running it in parallel. Here's the stack trace from one of the processors.

```
Stack frames: 20
0: 0   libmesh_dbg.0.dylib                 0x000000010c6d6eaf libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 2287
1: 1   libmesh_dbg.0.dylib                 0x000000010c6da2e3 libMesh::write_traceout() + 2595
2: 2   libmesh_dbg.0.dylib                 0x000000010c687d4d libMesh::libmesh_terminate_handler() + 13
3: 3   libc++abi.dylib                     0x00007fff89a3f19e _ZSt11__terminatePFvvE + 8
4: 4   libc++abi.dylib                     0x00007fff89a3ec12 _ZN10__cxxabiv1L22exception_cleanup_funcE19_Unwind_Reason_CodeP17_Unwind_Exception + 0
5: 5   libmesh_dbg.0.dylib                 0x000000010ce92dc7 void libMesh::ParallelMesh::libmesh_assert_valid_parallel_object_ids<libMesh::Elem>(libMesh::mapvector<libMesh::Elem*, unsigned int> const&) const + 3607
6: 6   libmesh_dbg.0.dylib                 0x000000010ce8d025 libMesh::ParallelMesh::libmesh_assert_valid_parallel_ids() const + 37
7: 7   libmesh_dbg.0.dylib                 0x000000010ce9104d libMesh::ParallelMesh::delete_remote_elements() + 2605
8: 8   libmesh_dbg.0.dylib                 0x000000010cc06de7 libMesh::MeshBase::prepare_for_use(bool, bool) + 2007
9: 9   libmesh_dbg.0.dylib                 0x000000010ccbd1b3 libMesh::MeshTools::Generation::build_cube(libMesh::UnstructuredMesh&, unsigned int, unsigned int, unsigned int, double, double, double, double, double, double, libMesh::ElemType, bool) + 49603
10: 10  libmesh_dbg.0.dylib                 0x000000010ccbd38a libMesh::MeshTools::Generation::build_square(libMesh::UnstructuredMesh&, unsigned int, unsigned int, double, double, double, double, libMesh::ElemType, bool) + 122
11: 11  libmoose-dbg.0.dylib                0x000000010b258e79 GeneratedMesh::buildMesh() + 2089
12: 12  libmoose-dbg.0.dylib                0x000000010b28546d MooseMesh::init() + 11293
13: 13  libmoose-dbg.0.dylib                0x000000010a96908b SetupMeshAction::act() + 1211
14: 14  libmoose-dbg.0.dylib                0x000000010a8b93d6 ActionWarehouse::executeActionsWithAction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 1510
15: 15  libmoose-dbg.0.dylib                0x000000010a8b8d7d ActionWarehouse::executeAllActions() + 525
16: 16  libmoose-dbg.0.dylib                0x000000010aed6965 MooseApp::runInputFile() + 1013
17: 17  libmoose-dbg.0.dylib                0x000000010aed9c6f MooseApp::run() + 47
18: 18  moose_test-dbg                      0x000000010a1d716f main + 303
19: 19  libdyld.dylib                       0x00007fff853185ad start + 1
```

**Comment by permcody** [comment]
I guess I don't run full debug mode all that often on my local machine but this is still an issue. An issue that seems to only pop up on Macs? Maybe if I get time I'll attempt a bisect since this really is occurring on just a vanilla generated Mesh.

**Comment by permcody** [comment]
I'm happy to report that this regression has disappeared. Unfortunately we still aren't doing proper testing with DistributedMesh so we aren't out of the woods for avoiding this in the future. We are working towards better parallel coverage though.
