### ISSUE TITLE
Cluster Launcher copying files it shouldn't be

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#6222]
When the Cluster Launcher is run via the TestHarness, we need a away to keep the cluster launcher from copying previously created pbs_***.cluster files.

**Comment by permcody** [comment]
I believe there's already code in there somewhere that filters out certain files. You might just need to add this pattern to the list. I might also just be full of :hankey:

**Comment by milljm** [comment]
I found that ClusterLauncher was filtering out the specific 'job_file', but even those are serialized by the TestHarness. So I am going about adding a 'no_copy_pattern' param. In the TestHarness's case, the pattern will be '.cluster'.

If there is something like that already in there... I aint finding it! :frowning:

**Comment by permcody** [comment]
I'm not sure I understand this comment. So the cluster launcher **does** filter out the job_file but you are saying those are "serialized by the TestHarness". What does that mean. If foo.cluster is the jobfile for a run then it shouldn't be copied right?

**Comment by milljm** [comment]
Right, foo_001.cluster does not get copied. But run the same ./run_tests --pbs command again, and now we get a:

foo_002.cluster file that does not get copied. However, the foo_001.cluster _does_ end up getting copied.

**Comment by permcody** [comment]
I see, OK then this PR is good however I think you should just follow the comment I just made and just improve the existing parameter instead of adding a new one.

**Comment by milljm** [comment]
I am not sure how I can take 'job_file' which is the file an end-user passes:

  ./cluster_launcher.py <could be named anything>

and use the value of 'job_file' to possibly filter out older <could be named anything> job_files.
I guess what I could do, is to specifically filter out TestHarness created *.cluster files instead?

**Comment by milljm** [comment]
This has been merged for over a year. No one has had a problem with it :) closing.
