### ISSUE TITLE
Simplify SoretDiffusion usage

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6239]
The kernel is quite neat as it can be used in a coupled and direct form. I'd like to add logic to make the coupled `c` variable optional (it is not technically needed in the direct application of the kernel).

By the way @tonkmr, do you have a reference for the functional form? I looked a bit and only found different expressions for the Soret diffusion ¯\\\_(ツ)\_/¯

**Comment by permcody** [comment]
Is that a unicode character? I'm not familiar with that little dude.

**Comment by dschwen** [comment]
It is a shrug.

**Comment by permcody** [comment]
Well I'm not that big of a geek that I can't read your ascii body language...

**Comment by jwpeterson** [comment]
OK, now try to figure out this one:

```
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`·¸ 
........../'/.../..../......./¨¯\ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........''...\.......... _.·´ 
............\..............( 
..............\.............\...
```

**Comment by dschwen** [comment]
I am going to have to report this unprofessional behavior to HR.
