### ISSUE TITLE
Derive new class from DerivativeMultiPhaseBase...

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6240]
...that allows for switching functions that are functions of multiple (all) order parameters.

The current class `DerivativeMultiPhaseMaterial` assumes that each switching function `h_i(eta_i)` is only function of one order parameter. This is insufficient for more complex switching functions (used for suppressing third phases along interfaces or renormalizing switching functions that obviate constraints).

**Comment by laagesen** [comment]
@dschwen, do you want to close this issue? For the three-phase KKS model it's been addressed with `SwitchingFunction3PhaseMaterial`. For more than three phases, the `SwitchingFunctionMultiPhaseMaterial` as used in the grand potential module should address this.

**Comment by permcody** [comment]
Closing - Issue appears to be sufficiently addressed.
