### ISSUE TITLE
SolidMechanics tests failing on my computer

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6243]
To @jasondhales and @cpritam - i thought you might like to know the following.  They're not a big deal....

@jasondhales, the test cracking.exponential is failing on my computer.  It's something to do with the

custom_cmp = cracking_exponential.exodiff

in the tests file.  When i comment that out the test passes, but otherwise it fails.

@cpritam , the test rate_dep_smear_crack.sent_test is failing on my computer.  I think you probably need to set the abs_zero to 1E-7 or something.  The test is failing due to things like:

resid_y  rel diff:  1.6298145e-09 ~  1.0710210e-08 = 8.47826e-01 (node 280)

Hopefully this is an OK change to make.

**Comment by permcody** [comment]
Andy,

Before we lower the floor, it might be worthwhile to tighten the tolerances
in those tests. Past experience has shown us that these tests are more
stable when we tighten tolerances on the solve rather than loosening them
on the comparisons. Could you try a tighter tolerance on one or both of
those tests. Also, in the case of Jason's test, those exodiff comparison
files are usually necessary to filter out variables that are not
interesting to us or that might not compare well across platform. You can
open up that "cmp" file to take a look at what it's doing. It's ASCII and
fairly easy to understand what it's doing.

**Comment by WilkAndy** [comment]
Tighter tolerances don't work in the cracking.exponential test.  They're very tight at the moment, and i can lower by 1-2 orders of magnitude (depending on which actual tolerance you tighten) before i get no convergence, and the tightening doesn't make the test pass.  However, i note in the cracking_exponential.exodiff there is "floor=1e-3" for the diagonal stress components, but not for the off-diagonal ones.  When i put "floor=1e-6" for the off-diag ones the test passes.

Tighter tolerances work in the rate_dep_smear_crack.sent_test test, but it requires re-golding as the failures were due to residuals being different, and with tighter tolerances of course they're going to be different.  Viz:

rate_dep_smear_crack.sent_test:   --------- Time step 2, 5.0000000e-02 ~ 5.0000000e-02, rel diff:  0.00000e+00 ---------
rate_dep_smear_crack.sent_test: Global variables:
rate_dep_smear_crack.sent_test: Nodal variables:
rate_dep_smear_crack.sent_test:    resid_x  rel diff:  1.0891199e-08 ~ -8.5219654e-10 = 1.07825e+00 (node 257)
rate_dep_smear_crack.sent_test:    resid_y  rel diff:  1.1612428e-08 ~ -2.2700988e-09 = 1.19549e+00 (node 284)
rate_dep_smear_crack.sent_test: Element variables:
rate_dep_smear_crack.sent_test:   --------- Time step 3, 1.0000000e-01 ~ 1.0000000e-01, rel diff:  0.00000e+00 ---------
rate_dep_smear_crack.sent_test: Global variables:
rate_dep_smear_crack.sent_test: Nodal variables:
rate_dep_smear_crack.sent_test:    resid_x  rel diff: -1.0535587e-08 ~  2.2355380e-09 = 1.21219e+00 (node 34)
rate_dep_smear_crack.sent_test:    resid_y  rel diff:  1.2747478e-08 ~ -4.1909516e-09 = 1.32877e+00 (node 309)

The "left" file is the current gold.  The "right" file is the new one.

**Comment by cpritam** [comment]
@WilkAndy I'm good with regolding the rate_dep_smear_crack.sent_test. May be Jason can comment on the cracking exponential test.
