### ISSUE TITLE
Compilation now broken if OpenMP and Pthreads are enabled

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6257]
This used to work because OpenMP simply took precedence over Pthreads. https://github.com/permcody/moose/commit/2a8507ee32fc190b21e795a6c476a23e101da1d5#diff-60f1cb2a8a6926ee7419b85c4733edc9R92 breaks this now.

 `<queue>` is not included if OpenMP is enabled, but regardless of OpenMP the `_ids` queue is declared.

**Comment by permcody** [comment]
Guess it helps to have compile targets for all configurations. Nice catch

**Comment by dschwen** [comment]
Given that enabling _both_ Pthreads and OpenMP is both the libMesh configure default as well as the setting in `update_and_rebuild_libmesh.sh` I'd say this will break MOOSE for pretty much everyone who is not a MOOSE developer with a customized libMesh build ;-)

**Comment by permcody** [comment]
Ok it's bad but not quite that bad. Most people have TBB enabled which takes precedence over all three thread models. Still, thanks for the fix.

**Comment by dschwen** [comment]
Right TBB. That reduces exposure of the bug a lot! Didn't think of that. I
have that disabled explicitly.

**Comment by permcody** [comment]
Which means you are running OpenMP. I've tasked John with looking into
making thread models selectable at runtime. This all needs to be cleaned up
a lot.

**Comment by dschwen** [comment]
Yes, I knew about running OpenMP. Anyhow sorry. I didn't mean to blow this
out of proportions.

**Comment by permcody** [comment]
[image: pasted1]

**Comment by dschwen** [comment]
Ha-ha, or rather [image: pasted 2] !!

**Comment by permcody** [comment]
Sorry you'll have to click here instead: http://www.ew.com/sites/default/files/styles/tout_image_gallery_612/public/i/2014/09/26/JUMP-TO-CONCLUSIONS-MAT.jpg

**Comment by permcody** [comment]
Thanks INL - I absolutely cannot attach images to PRs when I'm at work. It
ruins a lot of my fun. :(
