### ISSUE TITLE
make clobber doesn't work for me

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6258]
I get:

find: The -delete action atomatically turns on -depth, but -prune does nothing when -depth is in effect.  If you want to carry on anyway, just explicitly use the -depth option.

I think make clobber has to start with

        $(shell find $(CURDIR) -depth

a

**Comment by permcody** [comment]
Right - that would be the issue. "find" is kind of a pain in the @$$. We'll continue looking for a portable way of doing this properly. I might end up writing a damn python script instead.

**Comment by permcody** [comment]
Most of the devs us `git clean -xfd` instead. It really cleans everything including uncommitted work so be careful.

**Comment by dschwen** [comment]
We may be able to replace find with git clean -n and egrep

**Comment by permcody** [comment]
Interesting idea... Hmm
