### ISSUE TITLE
ICEUpdater doesn't work with C++11 disabled and static linkage

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6261]
See the error messages in this discussion:
https://groups.google.com/d/msgid/moose-users/51c1d986-1569-43b2-8624-168ac4d08afd%40googlegroups.com?utm_medium=email&utm_source=footer

TODO: The Updater class doesn't exist at all if C++11 is disabled. The ifdefs in that class need to declare the class and methods so that if static linkage is used the linker can find something to link to. I might be able to get to this, but I'm swamped now and for the foreseeable future.

Tag @amccaskey

**Comment by friedmud** [comment]
Ummm - why not just ifdef the whole thing (header and C) so there are no linkage problems at all.  I guess I'm missing something...

**Comment by permcody** [comment]
We'd have to ifdef the actual registration calls as well, but yes,
definitely possible.

**Comment by friedmud** [comment]
Yes, that's what I'm advocating.  We already do that for other stuff (like DTK).

If it's "disabled" then it shouldn't be registered... We don't want to see it in Peacock or in `--dump`... that would give you the impression that it's there and working... when it's really not.

**Comment by permcody** [comment]
I can't seem to replicate this problem. I tried several static builds with and without C++11 and everything worked for me. I contacted Erich and he's found other ways of getting around his problem. Closing this ticket.
