### ISSUE TITLE
Add CoupledCoefReaction kernel

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#6265]
This will derive from `CoupledReaction`. Will add a residual contribution of `-L*v` where the coefficient `L` is a material property and `v` is the coupled variable. This is needed for #5903.

**Comment by dschwen** [comment]
Let's call it `CoupledCoefReaction` though

**Comment by laagesen** [comment]
Ok will do

**Comment by laagesen** [comment]
Created test based on Allen-Cahn dynamics, comparing with results from `AllenCahn.i` test. Matches for constant mobility.
