### ISSUE TITLE
Clobber is overeager

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6274]
It deletes a bit too much...

**Comment by bwspenc** [comment]
"a bit"... like the whole moose submodule and the .git directory...

**Comment by permcody** [comment]
So then it removes more bugs than it causes. What's the problem?

**Comment by jwpeterson** [comment]
@dschwen do you even test, bro?

**Comment by dschwen** [comment]
I outsource testing to Canada

**Comment by milljm** [comment]
Yep. I can confirm this. Turns your repo into not a repo.

**Comment by aeslaughter** [comment]
I suggest `make clobber` does the following:

git stash -u
git clean -fxd
git stash pop

**Comment by gardnerru** [comment]
Kyle tested it, he is Canadian

**Comment by jwpeterson** [comment]
> suggest `make clobber` does the following:
> 
> git stash -u
> git clean -fxd
> git stash pop

Will this still remove untracked files?

Maybe even less intrusive: if "git status" returns any untracked or changed files, then print "Please commit your work before cleaning." Otherwise it would just run "git clean -fxd".

**Comment by dschwen** [comment]
This will stash untracked files, clean and pop untracked files out of the stash.

The problem is: will it stash _ignored_ files? We don't want that for the object files, but the users may want this for simulation results they have hanging around in their tree!

**Comment by aeslaughter** [comment]
the -u stashes untracked files, but not so sure about ignored files.

**Comment by jwpeterson** [comment]
It does not stash ignored files.

**Comment by jwpeterson** [comment]
Otherwise your stash would be huge!

**Comment by jwpeterson** [comment]
> Otherwise your stash would be huge!

![magnum-pi-007](https://cloud.githubusercontent.com/assets/1775907/12833901/d40576f6-cb60-11e5-83fa-6d70dcabd643.jpg)

**Comment by dschwen** [comment]
Ok, I think 076dfde is on the right track. I needed to bracket the prune and turn an `-or` into an `-and`. I'll test this now. Wish me luck (or don't).

**Comment by gambka** [comment]
After some additional outsourcing of testing to Canada, make clobber is still appears to be overeager and removing my .git directory and moose submodule in a freshly cloned and updated repository.

It also removes my .git directory in bison if I clone moose beside bison.

**Comment by permcody** [comment]
Before we jump to any conclusions, are we absolutely sure you have the current version of the script?

**Comment by gambka** [comment]
I checked the git log in the submodule and it contains the following commit:

commit c9793c42a664bb75659b963a9b4bfde8a0240510
Merge: 83f3f82 eadc5c0
Author: Cody Permann <codypermann@gmail.com>
Date:   Thu Feb 11 08:12:28 2016 -0700

    Merge pull request #6278 from dschwen/clobber_6274
    
    Revise clobber target

I also opened framework/moose.mk and compared the portion of the script to what was modified in the merge request and they appeared the same.  I have a fully up to date test repo that I can clobber if you want to come see what happens and verify for yourself that it is up to date.

**Comment by permcody** [comment]
Nah, I trust you. That means that it's time to do this with Python...

**Comment by dschwen** [comment]
WTH. How can this be?!

**Comment by WilkAndy** [comment]
This "make clobber" doesn't work for me.   I need the "-depth" argument:

$(shell find $(CURDIR) -depth \( -path $(CURDIR)/moose ...

(The problem is different versions of "find" - we've been over this before.)

**Comment by permcody** [comment]
Yep, I told the guys it's time to write a python script for this. It should
be very easy to do and work across platforms.
