### ISSUE TITLE
Add Regression test to assure initialSetup() is only called once per object

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6296]
Under the previous warehouse, `initialSetup()` may have been called multiple times. This "should" be fixed now... It'd be nice to keep it that way.

**Comment by aeslaughter** [comment]
This is on my sticky note to add, I am working on this stuff now.

**Comment by permcody** [comment]
@aeslaughter - I believe you added a test for this correct?

**Comment by aeslaughter** [comment]
Somewhere in #5680
