### ISSUE TITLE
Restarting subapp and all subapps underneath but not the ultimate master

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#6297]
@friedmud @YaqiWang @permcody
We have a FullSolveMultiapp executed on initial and the master picks up from this result, but 
depending on the scenario the setup of the master transient can vary. This is related to the SPRINT scenario. 

We would like to restart the subapp (and all apps underneath it) while the ultimate master does not restart. This would make it possible to ensure consistent behavior via the transfers we already have in place. One problem is scaling of the solution and providing the eigenvalue to the transient solve - this is currently all implemented in the transfers.

**Comment by friedmud** [comment]
Yeah.  It is definitely possible.  But it will be a lot of work to get all of the little things right.  90% of it will work immediately... but that last 10% will suck.
