### ISSUE TITLE
CSV diff seems not comparing numbers with inf, nan correctly

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6298]
If a user create a test with CSV diff and have divided-by-zero when creating the csv files (which will make the csv file contains inf), the test will not report error.

**Comment by dschwen** [comment]
What is _correctly_ comparing with NaN? In C++ every comparison with NaN is _always_ false. Is that what you want? This would _always_ fail a test with NaN in the gold file.

**Comment by permcody** [comment]
We probably don't want NaNs in the output file, maybe it should always be false.

**Comment by YaqiWang** [comment]
Same as inf. I guess the differ sees inf, nan as strings and skips the comparison. Maybe we should do string comparison if an entry cannot be converted to a number.

**Comment by dschwen** [comment]
Hm, I thought python's `float("nan")` _does_ return a nan...yep, just checked it. It does the right thing for int as well.

**Comment by YaqiWang** [comment]
I should mention that if you have access to yak, you can see this with one test. Let me know if you want the test name.

**Comment by YaqiWang** [comment]
I think this issue is critical. There are chances that the code is running wrongly producing inf by dividing zero. Then the test will not catch the error. It could have significant impact. Thanks.
