### ISSUE TITLE
App revision number isn't being updated

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6307]
The make process is not correctly updating the app revision number. If someone builds an app, then pulls down a newer version and rebuilds, the revision number reported by the app is the one from the revision of the original build, rather than the new one. If they do 'git clean -dxf' and then rebuild, the new revision is reported.

**Comment by bwspenc** [comment]
The script that writes this in framework/scripts/get_repo_revision.py seems fine. It just isn't getting run unless app/include/base/AppRevision.h is missing. From what I can see in app.mk, it seems like the script should get run every time anything is touched because app_objects depends on app_HEADER, which is what runs the script. It must be something wrong in that Makefile, but I'm not seeing it.

**Comment by bwspenc** [comment]
@acasagran

**Comment by bwspenc** [comment]
Oh, I get it... Make is not running the app_HEADER target because it's looking at the timestamp of AppRevision.h and seeing that it hasn't changed. We need to force it to run that target regardless of the timestamp.

**Comment by permcody** [comment]
If the target isn't marked PHONY and the file it depends on exists AND is
older, it won't get rerun. That's probably what's happening here. If we
mark it PHONY though, it'll rerun every time we type make which is annoying
too. I think we can run a git command though and figure out if something is
new...

**Comment by permcody** [comment]
Right, I think we can make it even smarter by running a git command inside of make and checking if something has changed. I've messed around with this before when we were mirroring applications in SVN and GIT and it worked quite well. I think that's better than regenerating that file every time we run make.

**Comment by bwspenc** [comment]
The script is set up to only actually modify the file if the revision has changed (so you don't force a rebuild of everything if it hasn't).  I think the fix is to add this line:
.PHONY: $(app_HEADER)
I'm trying it right now.

**Comment by permcody** [comment]
Ugh... This is kind of a nasty problem. I've thought about this quite a bit and I'm convinced that we DO need a phony target that at the very least inspects the file and rewrites it when appropriate. We may be able to get away with normal make rules for the cascade of files that need to be rebuilt from there (i.e. source files that include the Revision file).

**Comment by permcody** [comment]
OK more ideas:

I really don't want to force people to recompile tons of stuff every time they switch branches. I think we'll need to introduce a flag in the Makefile to either turn versioning on or not. For many people, we'll just default it to off and generate a static file that just sits there until it gets cleaned up. For other (maybe BISON developers), it'll rebuild that file EVERY time you rebase, or even just change branches. That's the only way to make sure it's correct at all times.

**Comment by bwspenc** [comment]
The script is set up so that if it gets run and the revision hasn't changed, it doesn't touch the file, so nothing gets re-compiled. The trick here is to have nothing except the end executables themselves depend on the phony targets. If anything else depends on the phony target, it will always get rebuilt.

As far as forcing a recompile of everything goes -- hardly anything actually depends on the AppRevision.h file with the version. Only one .C file #includes it (the one that prints out the version info). If this is done right, there will be almost no impact.

**Comment by brianmoose** [comment]
We could also have `app_HEADER` depend on `.git/HEAD` and `.git/index`. These change
on commits, branch change, etc.
I put in a quick implementation of it and it seems to do the correct thing.
Thoughts?

**Comment by permcody** [comment]
I really like that. That's try that for now and if somebody complains we'll try something different. Put up your PR.
