### ISSUE TITLE
Make sure examples run

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6324]
I need to systematically go over all examples we have and make sure they still run. At the training the first example I executed failed...

**Comment by brianmoose** [comment]
See #6269 
I just put in a PR #6323

**Comment by dschwen** [comment]
Yeah, that's fine. I should clarify that I'm talking about modules
examples. Those aren't even run by the test harness yet.

**Comment by permcody** [comment]
Examples are now running and part of CIVET.
