### ISSUE TITLE
Look into issue with second derivatives in IntegratedBCs

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#6327]
@jiangwen84 [reported](https://groups.google.com/d/msg/moose-users/_2Q6l6IloDE/4BMQbH-HDgAJ) an issue with accessing second derivatives from an IntegratedBC object.  

Off-list, we already confirmed that the second derivatives are being computed correctly in libmesh, but there is some issue with both the solution (accessed by `second()`) and test function (accessed by `secondTest()`) second derivative values in IntegratedBCs.

A possible hint to what is going wrong is that the values in `_var.secondPhiFace()` seem to be correct, i.e. the `MooseVariable` has computed the values correctly, so it's possible that it's just the Interface which is doing the wrong thing.  On the other hand, `_var.secondSln()` seems to have incorrect values, so it's not just a matter of accessing stuff on `MooseVariable` directly to fix the issue.

**Comment by jiangwen84** [comment]
@jwpeterson Thanks for looking into this issue.

I checked the MooseVariable computed values, the test function and trial function obtained through _assembly.secondPhiFace() and _var.secondPhiFace(), respectively. They both are correct on the quadrature points on the boundary. 

Then I looked at the Jacobian, showing that 4.0988e-06 = ||J - Jfd||//J|| 4.32052  = ||J - Jfd||). I do not quite understand why it is not correct if the shape functions and trial functions are correct. So it could be 
the incorrect _var.secondSln() and maybe other issues, like assembly, or even the finite difference Jacobian calculation.

**Comment by jwpeterson** [comment]
There is definitely at least one real issue here, and that is that the second derivatives obtained by initializing one's `VariableTestSecond` reference with either `_var.secondPhiFace()` or `secondTest()` (aka the interface method) do not agree, with the former apparently providing correct values and the latter providing incorrect ones.

The differences are not small, either.  I added the following lines of code to your computeQpJacobian(),
```
Real normdiff = (_second_test[_i][_qp] - _second_test_from_interface[_i][_qp]).norm();
if (normdiff > 1.e-12)
  Moose::out << "test_xx - test_interface_xx = " << normdiff << std::endl;
```

and it prints:
```
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.44601
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 2.65227
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
test_xx - test_interface_xx = 1.1352
...
```


---

As far as second derivative values of the *solution* are concerned, I am not convinced there is anything wrong with those, although this test may not be sufficient to show the issue if there is one, since Laplacian(u) = 0 for the simple test case you sent me.

I printed out the solution second derivative values and verified they are 0, and I also ran your input file through @dschwen's [Jacobian debugging script](http://mooseframework.org/wiki/JacobianDebugging/) with test functions obtained from `_var.secondPhiFace()` and it prints:
```
No errors detected. :-)
```

So I'm not sure what issue PETSc is actually detecting here.  BTW, the actual output from `-snes_check_jacobian` is all jumbled up and difficult to actually read (see below).  @aeslaughter is this related to `_console` or something?

```
 0 Nonlinear |R| = 1.732051e+00
      Testing hand-coded Jacobian, if the ratio is O(1.e-8), the hand-coded Jacobian is probably correct.
      Run with -snes_check_jacobian_view [viewer][:filename][:format] to show difference of hand-coded and finite difference Jacobian.
    0.580818 = ||J - Jfd||//J|| 4.32049  = ||J - Jfd||
      0 Linear |R| = 1.732051e+00
      1 Linear |R| = 1.944476e-15
 1 Nonlinear |R| = 1.567408e-15
```

**Comment by jiangwen84** [comment]
I find that the second derivatives obtained by interface secondTest() actually references to some values which are calculated on the quadrature points inside the volume, but not the boundary.

**Comment by andrsd** [comment]
> BTW, the actual output from -snes_check_jacobian is all jumbled up and difficult to actually read (see below).

This is standard PETSc output for `-snes_check_jacobian`. If you want to see the matrices add `-snes_check_jacobian_view`. If you want the other output, it is `-snes_type test -snes_test_display`.

**Comment by jwpeterson** [comment]
@andrds pointed out a typo in the input file:
```
diff --git a/test/tests/bcs/second_deriv/test_lap_bc.i b/test/tests/bcs/second_deriv/test_lap_bc.i
index 0a9d474..e250737 100644
--- a/test/tests/bcs/second_deriv/test_lap_bc.i
+++ b/test/tests/bcs/second_deriv/test_lap_bc.i
@@ -57,7 +57,7 @@
 
   petsc_options_iname = '-pc_type'
   petsc_options_value = 'lu'
-  petsc_options = '-snes_check_jacobian -sens_check_jacobian_view'
+  petsc_options = '-snes_check_jacobian -snes_check_jacobian_view'
 []
 
 [Outputs]
```

**Comment by jwpeterson** [comment]
If you spell that option correctly, these are the differences between the hand-coded and finite-difference Jacobian:

```
    Finite difference Jacobian
Mat Object: 1 MPI processes
  type: seqaij
row 0: (0, 1) 
row 1: (0, 0.503632)  (1, 1.11474)  (2, -0.022151)  (3, 0.0334046)  (4, -0.56282)  (5, -0.037037)  (6, 0.710969)  (7, 0.185185)  (8, -1.92593) 
row 2: (0, -0.107479)  (1, 0.503632)  (2, 1.25563)  (3, -0.022151)  (4, 0.326068)  (5, -0.703704)  (6, -0.17792)  (7, 0.851852)  (8, -1.92593) 
row 3: (3, 1) 
row 4: (0, -0.037037)  (1, -0.037037)  (2, 0.185185)  (3, 0.185185)  (4, 1.62963)  (5, -0.592593)  (6, -0.148148)  (7, -0.592593)  (8, -0.592593) 
row 5: (0, 1.23675)  (1, 2.34786)  (2, 1.57806)  (3, 0.466952)  (4, -1.36239)  (5, 0.296296)  (6, 0.177208)  (7, 1.18519)  (8, -5.92593) 
row 6: (0, 0.185185)  (1, 0.185185)  (2, -0.037037)  (3, -0.037037)  (4, -0.148148)  (5, -0.592593)  (6, 1.62963)  (7, -0.592593)  (8, -0.592593) 
row 7: (7, 1) 
row 8: (0, -0.592593)  (1, -0.592593)  (2, -0.592593)  (3, -0.592593)  (4, -0.592593)  (5, -0.592593)  (6, -0.592593)  (7, -0.592593)  (8, 4.74074) 
    Hand-coded Jacobian
Mat Object:() 1 MPI processes
  type: seqaij
row 0: (0, 1)  (1, 0)  (2, 0)  (3, 0)  (4, 0)  (5, 0)  (6, 0)  (7, 0)  (8, 0) 
row 1: (0, 0.12963)  (1, 1.07407)  (2, 0.12963)  (3, -0.148148)  (4, -0.481481)  (5, -0.481481)  (6, 0.407407)  (7, 0.407407)  (8, -1.03704) 
row 2: (0, -0.148148)  (1, 0.12963)  (2, 1.07407)  (3, 0.12963)  (4, 0.407407)  (5, -0.481481)  (6, -0.481481)  (7, 0.407407)  (8, -1.03704) 
row 3: (0, 0)  (1, 0)  (2, 0)  (3, 1)  (4, 0)  (5, 0)  (6, 0)  (7, 0)  (8, 0) 
row 4: (0, -0.037037)  (1, -0.037037)  (2, 0.185185)  (3, 0.185185)  (4, 1.62963)  (5, -0.592593)  (6, -0.148148)  (7, -0.592593)  (8, -0.592593) 
row 5: (0, 0.407407)  (1, 1.51852)  (2, 1.51852)  (3, 0.407407)  (4, -1.03704)  (5, -0.148148)  (6, -1.03704)  (7, 0.740741)  (8, -2.37037) 
row 6: (0, 0.185185)  (1, 0.185185)  (2, -0.037037)  (3, -0.037037)  (4, -0.148148)  (5, -0.592593)  (6, 1.62963)  (7, -0.592593)  (8, -0.592593) 
row 7: (0, 0)  (1, 0)  (2, 0)  (3, 0)  (4, 0)  (5, 0)  (6, 0)  (7, 1)  (8, 0) 
row 8: (0, -0.592593)  (1, -0.592593)  (2, -0.592593)  (3, -0.592593)  (4, -0.592593)  (5, -0.592593)  (6, -0.592593)  (7, -0.592593)  (8, 4.74074) 
    Hand-coded minus finite difference Jacobian
Mat Object: 1 MPI processes
  type: seqaij
row 0: (0, 2.22045e-16)  (1, 0)  (2, 0)  (3, 0)  (4, 0)  (5, 0)  (6, 0)  (7, 0)  (8, 0) 
row 1: (0, -0.374003)  (1, -0.0406695)  (2, 0.151781)  (3, -0.181553)  (4, 0.081339)  (5, -0.444444)  (6, -0.303561)  (7, 0.222222)  (8, 0.888889) 
row 2: (0, -0.0406695)  (1, -0.374003)  (2, -0.181553)  (3, 0.151781)  (4, 0.081339)  (5, 0.222222)  (6, -0.303561)  (7, -0.444444)  (8, 0.888889) 
row 3: (0, 0)  (1, 0)  (2, 0)  (3, 2.22045e-16)  (4, 0)  (5, 0)  (6, 0)  (7, 0)  (8, 0) 
row 4: (0, -1.38778e-17)  (1, -2.77556e-17)  (2, -2.77556e-17)  (3, 2.77556e-17)  (4, 2.22045e-16)  (5, 0)  (6, 0)  (7, -1.11022e-16)  (8, 0) 
row 5: (0, -0.829345)  (1, -0.829345)  (2, -0.0595443)  (3, -0.0595443)  (4, 0.325356)  (5, -0.444444)  (6, -1.21424)  (7, -0.444444)  (8, 3.55556) 
row 6: (0, 2.77556e-17)  (1, -2.77556e-17)  (2, -3.46945e-17)  (3, -3.46945e-17)  (4, 0)  (5, 0)  (6, 2.22045e-16)  (7, 0)  (8, 0) 
row 7: (0, 0)  (1, 0)  (2, 0)  (3, 0)  (4, 0)  (5, 0)  (6, 0)  (7, 2.22045e-16)  (8, 0) 
row 8: (0, 1.11022e-16)  (1, 1.11022e-16)  (2, 1.11022e-16)  (3, 1.11022e-16)  (4, -1.11022e-16)  (5, 0)  (6, 0)  (7, 0)  (8, 0) 
    0.580818 = ||J - Jfd||//J|| 4.32049  = ||J - Jfd||
```

**Comment by dschwen** [comment]
Wait a minute... are you saying the Jacobian analyzer reports `no errors` but you see a diff in the matrix output?

**Comment by jwpeterson** [comment]
> On Feb 15, 2016, at 4:27 PM, Daniel Schwen <notifications@github.com> wrote:
> 
> Wait a minute... are you saying the Jacobian analyzer reports no errors but you see a diff in the matrix output?
> 

That's exactly what I'm saying.

**Comment by dschwen** [comment]
:hankey:

**Comment by dschwen** [comment]
(its chocolate yoghurt)

**Comment by jwpeterson** [comment]
@jiangwen84 Could the issue be that the residual we are finite-differencing is almost identically zero for this very simple test problem (u=1), and this leads to a lot of round-off error in the finite difference calculation?  

You can play around with different values of `-snes_test_err` on the command line, and it makes almost no difference in `-snes_check_jacobian` output... this isn't normal and suggests something might be wrong with the test problem.

Can you help me come up with a different (but still simple) test problem, maybe Laplacian(u) = f with a made-up boundary condition involving the Laplacian to see if this finite differencing issue goes away?

I do agree that there is still an issue with calling `secondTest()` in IntegratedBCs, but haven't figured out exactly the right fix for that yet...

**Comment by jiangwen84** [comment]
@jwpeterson That is a good point. I will figure out a 'meaningful' solution for the test problem and give it a shot.

**Comment by jiangwen84** [comment]
@jwpeterson I manufactured a solution u = x^2 + y^2 and solve the Lap u = f with f = 4. For the left, top and bottom boundary, I added Dirichlet BC with analytical solution. For the right boundary, I added a penalty term to enforce Lap u = 2 on that boundary. 

To compile the code, I have to comment out the ```norm()``` you put in the ```TestLapBC``` as the compiler cannot find the definition for it. 

I tested the code and the jacobian is still not correct. Could you take a look at my new input file and the source file, to see if there is anything wrong with them? Thanks!

**Comment by jwpeterson** [comment]
> To compile the code, I have to comment out the norm() you put in the TestLapBC as the compiler cannot find the definition for it.

Oops, yes sorry `norm()` is the new name, you need to use `size()` for the version of libmesh MOOSE is currently using.



> I tested the code and the jacobian is still not correct. Could you take a look at my new input file and the source file, to see if there is anything wrong with them? Thanks!

Damn, I was hoping this would work.  Yeah, I will take a look.

**Comment by jwpeterson** [comment]
One issue: the forcing function Kernel is not active in the input file you pushed in 6e0bf29 (see active line):
```
[Kernels]
  active = 'diff'

  [./diff]
    type = Diffusion
    variable = u
  [../]
  [./ffn]
    type = UserForcingFunction
    variable = u
    function = force_fn
  [../]
[]
```

However, when I activated it, the solver does not converge, I think possibly because the penalty that you picked is too small?

Anyway, I changed the problem slightly (see 60fa053) so that we can avoid the penalty term altogether and now it converges with the forcing function turned on, but there is still the same issue with the FD Jacobian not matching the hand-coded one.

Note: if I replace the computeQpResidual()/computeQpJacobian() with the simplified versions:
```
r += -2 * _test[_i][_qp];
```
and
```
r += 0.;
```
respectively, the Jacobians match, and printing `_second_u` shows it is correct:
```
_second_u[1]=
(xx,xy,xz)=(       4, -1.83611e-17,        0)
(yx,yy,yz)=(-1.83611e-17,        4,        0)
(zx,zy,zz)=(       0,        0,        0)
```
i.e. u,xx = u,yy = 2 as we expect for the manufactured solution.

So, my current thought is that the correct values of `_second_u` are making it into the BC, but that somehow this "fake" BC we are inventing somehow messes up the problem from a mathematical standpoint.  I need to think about it a bit more...

**Comment by jwpeterson** [comment]
No, sorry, wait!
```
_second_u[1]=
(xx,xy,xz)=(       4, -1.83611e-17,        0)
(yx,yy,yz)=(-1.83611e-17,        4,        0)
(zx,zy,zz)=(       0,        0,        0)
```
is *not* correct, the diagonal entries should be 2 and 2.

So then there *is* something wrong with the values of `_second_u` in BCs after all...

**Comment by jwpeterson** [comment]
I also verified that the `_second_u` values are *correct* in the Diffusion Kernel by adding a print statement there (see 3027c0a)
```
Diffusion: _second_u[0]=
(xx,xy,xz)=(       2, -5.23391e-16,        0)
(yx,yy,yz)=(-5.23391e-16,        2,        0)
(zx,zy,zz)=(       0,        0,        0)
```
so this problem seems to be limited to the BoundaryCondition...

**Comment by jiangwen84** [comment]
I also ran the new test and get the same answer. Basically the ```_second_u``` on the boundary is not correct although the solution seems to be correct. 

Could it be related to the ```interface``` method issue?

**Comment by jwpeterson** [comment]
> Could it be related to the interface method issue?

Not sure.  One thing I don't quite understand about `MooseVariable` is that it has some `Face` methods, e.g. `phiFace()`, `gradPhiFace()`, `secondPhiFace()`, etc. but no corresponding functions for the solution like `slnFace()` or `secondSlnFace()`.  Not sure if that's an omission or if it's just supposed to work that way.

At the moment I am writing a small libmesh code just to double-check that the second derivatives of the solution are correct on the face at the libmesh level.  I know you said you checked this already but I just want to be sure...

**Comment by andrsd** [comment]
> but no corresponding functions for the solution like slnFace() or secondSlnFace(). Not sure if that's an omission or if it's just supposed to work that way.

In `MooseVariable`, `_u` (where we keep the solution) is used both for volumetric and face values. That's why there is no `slnFace()`. Similarly for gradients and second derivatives...

**Comment by permcody** [comment]
Also, how 'bout those those FORTRAN naming conventions?

**Comment by jwpeterson** [comment]
So, for what it's worth, I agree with your assessment that the second derivative values on the boundary are correct in libmesh.  I created this [gist](https://gist.github.com/jwpeterson/41deb2381ac524124e19) which is a modified version of ex4 set up to solve the same u=x^2 + y^2 problem.  The test code prints:

```
qface_point[0]=(x,y,z)=(       1, -0.57735,        0)
second_u[qp=0]=
(xx,xy,xz)=(       2, 9.96137e-11,        0)
(yx,yy,yz)=(9.96137e-11,        2,        0)
(zx,zy,zz)=(       0,        0,        0)
lap_u=4

qface_point[1]=(x,y,z)=(       1,  0.57735,        0)
second_u[qp=1]=
(xx,xy,xz)=(       2, -9.96137e-11,        0)
(yx,yy,yz)=(-9.96137e-11,        2,        0)
(zx,zy,zz)=(       0,        0,        0)
lap_u=4
```

So I think we still need to focus on finding where the second derivative values are getting computed incorrectly in MOOSE...

**Comment by jwpeterson** [comment]
As of 60d50d6, I have implemented a "manual" reconstruction of the `_second_u` in `computeQpResidual()` by summing `u[i] * _second_test[i][_qp]` at each quadrature point.  This gives the correct values for second_u, and, most importantly, passes the `-snes_check_jacobian` test.

It's not a solution to the problem, but it does prove that all the "ingredients" are available for computing second derivatives on the face, we just have to get MooseVariable to use them correctly.

**Comment by jiangwen84** [comment]
:+1:  :+1: :+1:  

-:)

**Comment by jwpeterson** [comment]
OK, @andrsd figured out that we were not properly zeroing `_second_u` on element faces in Steady simulations (Transient was fine), hence the doubled values we were seeing.  This is fixed in e0ceccf, and another, related fix in 18f1065.  So you managed to trigger a *very* specific issue with the `TestLapBC` code!

I'm going to clean up this branch and open a PR, including the new test, momentarily.  @jiangwen84 and @andrsd, thanks for your help in tracking down the issue.

**Comment by jiangwen84** [comment]
That is so great! @jwpeterson @andrsd  Thank you! :100:

**Comment by friedmud** [comment]
Great sleuthing everyone!  Glad this got sorted out! :+1:

**Comment by jiangwen84** [comment]
@jwpeterson Do we still want to fix the interface(```secondTest()''') issue?

**Comment by jwpeterson** [comment]
Yes, that's included in this branch.
