### ISSUE TITLE
Add testing for newlines in input files

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#6332]
Recently two new input files have been merged into MOOSE (which means they passed all of the existing tests and checks) that now come up as modified in my submodule whenever I run the delete_trailing_whitespace.sh script:

test/tests/dgkernels/dg_block_restrict/dg_block_restrict.i
test/tests/interfacekernels/1d_interface/coupled_value_coupled_flux.i

Would it be possible to add to the testing system a pre-check for newlines at the end of input files to prevent this in the future since the delete_trailing_whitespace.sh script should add these for the developer?

**Comment by jwpeterson** [comment]
Just to clarify, these files say
```
\ No newline at end of file
```
in `git diff`, and we'd like the pre-check to catch these for us, since they are fixed by delete_trailing_whitespace.sh.

**Comment by gambka** [comment]
That is correct.

**Comment by permcody** [comment]
@brianmoose - Can this issue be closed?

**Comment by brianmoose** [comment]
This has been turned on now. It checks all files, not just input files.
