### ISSUE TITLE
Image Subdomain Test Fails

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6348]
mesh_modifiers/image_subdomain.2d fails to complete when run in debug parallel. This test isn't all that big so this should be investigated.

**Comment by aeslaughter** [comment]
I started to look at this, I have a branch on my workstation. The reader seems to be spinning its wheels in VTK, I will get after it next week to see if I can figure it out.

**Comment by permcody** [comment]
No rush, just wanted to capture it in a ticket since it's our only fail on the parallel debug build. If you'll get to it soon, I'll just leave it alone rather than committing a 'skip'.
