### ISSUE TITLE
Still construction order dependence for DerivativeSumMaterial

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6360]
The dependency system is not dealing correctly with `DerivativeSumMaterials` blocks preceding the material blocks that define the free energies used in the sum.

**Comment by dschwen** [comment]
This also affects `ParsedMaterial`... 

Ping @aeslaughter (something to consider tomorrow).

**Comment by permcody** [comment]
@dschwen - Please check if this is an issue after your changes resulting from our conversation this morning.

**Comment by dschwen** [comment]
I think #6567 will fix this (in particular this commit: ea62ce2)
