### ISSUE TITLE
Possible issue with TBB on Linux (CentOS)

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6371]
We've had a couple users report crashing in the first threaded loop in MOOSE since we started cleaning up the threaded code. We need to look at this:

User "mauro13":
> I'm running on CentoOS (release 6.2) with gcc (4.4.6 20110731 (Red Hat 4.4.6-3) as compiler. MPI
> implementation is mpiexec (OpenRTE) 1.6.4.

See: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/SJbCMEY1zD0/zK6_CfsAFwAJ

@milljm - Can you help me get a CentOS box to test on? We just need to run GCC + MPI + CentOS and see if we can replicate. I hope specific versions don't matter. If you want to do it yourself, just try running with `--n-threads=2`

**Comment by friedmud** [comment]
This was fixed in https://github.com/libMesh/libmesh/pull/842 it can be closed when libMesh is updated.

**Comment by permcody** [comment]
Fixed in https://github.com/libMesh/libmesh/pull/842
