### ISSUE TITLE
Add FindValueOnLineSample VectorPostprocessor

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#6389]
### Description of the enhancement or error report
Add a `FindValueOnLineSample` VectorPostprocessor that will take a `LineValueSampler` and return a vector (along the line) that gives the position where a user-specified value is found. User controls accuracy by controlling number of points in the LineValueSampler. Will also add an option to do interpolation to get the distance between the points bracketing the user-specified value.

### Rationale for the enhancement or information for reproducing the error
No current capability exists to find interpolated distance along a line.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Depends on `LineValueSampler` so interface changes to that may causes changes to `FindValueOnLine`.

**Comment by dschwen** [comment]
I would make this a postprocessor that does a bisection search.

**Comment by laagesen** [comment]
Sounds good.
