### ISSUE TITLE
Untested objects in HEVP

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6395]
### Description of the enhancement or error report
- `HEVPLinearHardening` (@cpritam)
- `TensorMechanicsHardeningCutExponential` and `MultiPlasticityDebugger` (@WilkAndy) 

have zero test coverage

### Rationale for the enhancement or information for reproducing the error
Need test coverage

**Comment by WilkAndy** [comment]
# **MY BOLDFACE IS BIGGER THAN YOURS**

Heheheh, thanks for the notification.  i'll write a test for that soon.

a

**Comment by WilkAndy** [comment]
Oh!  I just realised the boldface comes from the new templates.  I thought you were shouting at me, @dschwen !

a

**Comment by permcody** [comment]
Lol

**Comment by dschwen** [comment]
Ha ha ha!

**Comment by permcody** [comment]
@dschwen - Can this ticket be closed now due to #6450?

**Comment by WilkAndy** [comment]
Sorry, this cannot be closed yet as i haven't done my test.

**Comment by permcody** [comment]
All HVEP UserObjects are tested. Thanks all!

http://mooseframework.org/docs/coverage/tensor_mechanics/tensor_mechanics_coverage/src/userobjects/index.html
