### ISSUE TITLE
BCs should call computeJacobian

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6407]
### Description of the enhancement or error report

My Richards Test Coverage report suggests that computeQpJacobian and computeQpOffDiagJacobian are not being called.  Shouldn't BCs contribute to the Jacobian?

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Awesomely increased convergence rates (i wish).

**Comment by WilkAndy** [comment]
Actually, hold on, i think it might be a coding mistake on my behalf.  I think BCs call computeJacobianBlock instead (which i also have in the BCs), and i've accidently also include a computeJacobian function which is never called.

**Comment by WilkAndy** [comment]
Could someone tell me when BCs call computeJacobian and when the call computeJacobianBlock?

**Comment by YaqiWang** [comment]
I think it is better to not overwrite `computeJacobian` and `computeJacobianBlock` in your BC. Instead, just implement `computeQpJacobian` and `computeQpOffDiagJacobian`. To check when `computeJacobian` and `computeJacobianBlock`, I will use grep linux command to find where they are used, (possibly in threaded computing classes). And keep doing the search to figure out the call tree. Or you can add `libMesh::print_trace();` in your `computeJacobian` and run the executable to see the call tree when the execution hit the `print_trace()`.

**Comment by WilkAndy** [comment]
Thanks Yaqi.  I was hoping someone would save me the pain of grepping.  It seems there is ComputeJacobianThread.C and ComputeFullJacobianThread that both have a computeFaceJacobian method that calls the BC computeJacobian or computeJacobianBlock, respectively.  But why my tests should only use the latter (Full and Block) versions, i'm not sure.

**Comment by WilkAndy** [comment]
# **I was wrong about Jacobians not being calculated for BCs !!**

(I love this BOLDFACE, heheheh.)

So this issue can be closed, but it would be good if someone could first answer my question above.

**Comment by WilkAndy** [comment]
To answer my own question:

computeJacobian appears to be called if there is no Preconditioning block
otherwise
computeJacobianBlock is used.

Probably it's slightly different than this, but at least i know how to activate computeJacobian now.

**Comment by friedmud** [comment]
Just in case someone runs into this later: it depends on which TYPE of
preconditioner is being used. The default block-diagonal preconditioner
knows that it only needs the block diagonal: so only computeJacobian is
called while other preconditioners may need off-diagonal blocks so they
call the more generic computeJacobianBlock.

In either case: neither of those functions should be overridden normally.
Override computeQpJacobian and computeQpOffDiagJacobian
