### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6414]
### Description of the enhancement or error report
Add an .editor config http://editorconfig.org/ to the project

### Rationale for the enhancement or information for reproducing the error
This is a neat way to specify editor configuration options regarding whitespace etc. for many many editors.

### Identified impact
This will help or contributors to comply with our code formatting standards.

**Comment by permcody** [comment]
This looks pretty cool!

**Comment by friedmud** [comment]
This is interesting.  Has anyone tried the Emacs plugin yet?

I'm getting ready to jettison my current Emacs stuff anyway... it's not C++11 friendly (curly brace vector initialization drives it CRAZY).  So I'll give this a whirl...
