### ISSUE TITLE
HexPolycrstalIC doesn't work with Intel compilers

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6427]
### Description of the enhancement or error report

It looks like there is some variation in the initial condition when using Intel compilers

### Rationale for the enhancement or information for reproducing the error

Use Intel compilers (rod) on the HexPolycrystalIC test to reproduce:
https://moosebuild.org/job/11656/

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

None

**Comment by dschwen** [comment]
Yeah, I just touched that. I'll take a look.

**Comment by dschwen** [comment]
Looks like some mesh nodes now exactly coincide with the sharp grain boundaries :-/

**Comment by permcody** [comment]
Yeah, I don't know of a robust way of dealing with this. I guess if the resize works great, otherwise we'll just run this kind of test on GCC and CLANG.

**Comment by dschwen** [comment]
I already tried it on Intel and it doesn't diff.
