### ISSUE TITLE
Test mohr_coulomb.planar_hard4 failed after rebasing

### ISSUE THREAD

**Issue by cpritam** [idaholab/moose#6428]
### Description of the enhancement or error report

test mohr_coulomb.planar_hard4 failed after rebasing
### Rationale for the enhancement or information for reproducing the error

mohr_coulomb.planar_hard4: Time Step  4, time = 8
mohr_coulomb.planar_hard4:                 dt = 2
mohr_coulomb.planar_hard4:  0 Nonlinear |R| = 0.000000e+00
mohr_coulomb.planar_hard4:  Solve Converged!
mohr_coulomb.planar_hard4: 
mohr_coulomb.planar_hard4: Postprocessor Values:
mohr_coulomb.planar_hard4: +----------------+----------------+----------------+------------------------------------+----------------+----------------+----------------+----------------+
mohr_coulomb.planar_hard4: | time           | Coh_analytic   | Coh_moose      | cohesion_difference_should_be_zero | f0             | f1             | f2             | f3             |
mohr_coulomb.planar_hard4: +----------------+----------------+----------------+------------------------------------+----------------+----------------+----------------+----------------+
mohr_coulomb.planar_hard4: |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |                       0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
mohr_coulomb.planar_hard4: |   2.000000e+00 |   1.155603e+01 |   1.155603e+01 |                       0.000000e+00 |  -4.869005e+00 |  -4.869005e+00 |  -5.514024e+00 |   1.759502e-08 |
mohr_coulomb.planar_hard4: |   4.000000e+00 |   1.314390e+01 |   1.314390e+01 |                       0.000000e+00 |  -3.092692e+00 |  -3.092692e+00 |  -3.502395e+00 |   2.406695e-08 |
mohr_coulomb.planar_hard4: |   6.000000e+00 |   1.443956e+01 |   1.443956e+01 |                       0.000000e+00 |  -1.121581e+00 |  -1.121581e+00 |  -1.270162e+00 |   1.094143e-08 |
mohr_coulomb.planar_hard4: |   8.000000e+00 |   1.556462e+01 |   1.556462e+01 |                       0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
mohr_coulomb.planar_hard4: +----------------+----------------+----------------+------------------------------------+----------------+----------------+----------------+----------------+
mohr_coulomb.planar_hard4: +----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
mohr_coulomb.planar_hard4: | time           | f4             | f5             | internal       | s_xx           | s_xy           | s_xz           | s_yy           | s_yz           |
mohr_coulomb.planar_hard4: +----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
mohr_coulomb.planar_hard4: |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |   0.000000e+00 |
mohr_coulomb.planar_hard4: |   2.000000e+00 |  -5.514024e+00 |   1.759502e-08 |   1.691327e-06 |   3.340627e+00 |   3.469447e-18 |   6.001462e-19 |   3.340627e+00 |   1.380320e-17 |
mohr_coulomb.planar_hard4: |   4.000000e+00 |  -3.502395e+00 |   2.406695e-08 |   3.774461e-06 |   6.991818e+00 |   2.255141e-17 |  -1.905976e-19 |   6.991818e+00 |   1.810689e-17 |
mohr_coulomb.planar_hard4: |   6.000000e+00 |  -1.270162e+00 |   1.094143e-08 |   5.869076e-06 |   1.065211e+01 |  -1.040834e-17 |   8.169205e-19 |   1.065211e+01 |  -1.786297e-17 |
mohr_coulomb.planar_hard4: |   8.000000e+00 |   0.000000e+00 |   0.000000e+00 |   8.129725e-06 |   1.306027e+01 |   1.622509e-16 |   7.703824e-34 |   1.306027e+01 |  -2.890981e-37 |
mohr_coulomb.planar_hard4: +----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+----------------+
mohr_coulomb.planar_hard4: +----------------+----------------+----------------------+
mohr_coulomb.planar_hard4: | time           | s_zz           | yfcns_should_be_zero |
mohr_coulomb.planar_hard4: +----------------+----------------+----------------------+
mohr_coulomb.planar_hard4: |   0.000000e+00 |   0.000000e+00 |         0.000000e+00 |
mohr_coulomb.planar_hard4: |   2.000000e+00 |   8.854651e+00 |         0.000000e+00 |
mohr_coulomb.planar_hard4: |   4.000000e+00 |   1.049421e+01 |         0.000000e+00 |
mohr_coulomb.planar_hard4: |   6.000000e+00 |   1.192227e+01 |         0.000000e+00 |
mohr_coulomb.planar_hard4: |   8.000000e+00 |   1.306027e+01 |         0.000000e+00 |
mohr_coulomb.planar_hard4: +----------------+----------------+----------------------+
mohr_coulomb.planar_hard4: 
mohr_coulomb.planar_hard4: 
mohr_coulomb.planar_hard4: Time Step  5, time = 10
mohr_coulomb.planar_hard4:                 dt = 2
mohr_coulomb.planar_hard4:  *\* On entry to DGETRF parameter number  4 had an illegal value
mohr_coulomb.planar_hard4: Running CSVDiffer.py
mohr_coulomb.planar_hard4: In planar_hard4.csv: Columns with header 's_xx' aren't the same length
mohr_coulomb.planar_hard4: 
mohr_coulomb.planar_hard4................................................................... FAILED (CSVDIFF) (reprint)
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by cpritam** [comment]
@WilkAndy

**Comment by WilkAndy** [comment]
OK, this is failing in the DGETRF routine which is a PETSc/LAPACK/BLAS thing.  This is called in RankFourTensor::maxtrixInversion (DGETRF does the LU factorization), and the fourth parameter is the rank of the matrix.

First off, i'm not sure why this doesn't just give an error code back, and then our matrixInversion routine would do the correct thing (return with the error code and we'd handle it correctly).  But ignoring that, i presume that i'm passing a rank-zero matrix for inversion, and i didn't realize this was a possibility previously.  i'm just guessing here!

I've made a modification for that case which is both mathematically correct for this "corner case" and all the tests pass on my system.

If the modification still fails, do you think you could do a trace so i can see exactly where things are failing?  Presently i'm just guessing its in the ComputeMultiPlasticiStress::consistentTangentOperator function.

**Comment by permcody** [comment]
We really need a better way for you to debug. Would you be interested in an
RSA token to login? We may be able to get you on to a similarly configured
system.

**Comment by WilkAndy** [comment]
I don't really want an RSA token.  it's just something else to look after and lose.  I guess if these errors happened every day it'd be different, but presently it's only every month or so.

**Comment by permcody** [comment]
Issue resolved by https://github.com/WilkAndy/moose/commit/7834ab8e237d0fb3fbdc84a053341b685a69be91
