### ISSUE TITLE
Richards sinks.s_fu_04 is failing

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6429]
### Description of the enhancement or error report

sinks.s_fu_04 is failing reliably on our test systems after all those merges
See https://moosebuild.org/job/11657/

### Rationale for the enhancement or information for reproducing the error

Run on a Linux system to reproduce

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Preventing some updates to the test coverage

@WilkAndy

**Comment by WilkAndy** [comment]
Thanks @permcody - i'll look into s_fu_04 now,

a

**Comment by WilkAndy** [comment]
Perhaps someone will have to help me with this.  CIVET says:

sinks.s_fu_04: Running CSVDiffer.py
sinks.s_fu_04: In s_fu_04.csv: Columns with header 'area_right' aren't the same length

I had a look at the stdout on CIVET and it is virtually identical to the stdout on my system.  It looks like somehow the master version of gold/s_fu_04.csv has some crazy formatting?  I'm a bit stuck.

**Comment by permcody** [comment]
Wait is that not your test? Your just seeing the somewhat sparse message
from the CSVDiffer. My guess is you're missing a time step or you have an
extra now. The tool is a bit tight lipped about which case :/

**Comment by WilkAndy** [comment]
OK, but i'm not sure which timestep is missing.  Probably the first or last, but how do i know?  On my system i get exactly gold/s_fu_04.csv.  How can i figure out what your system is giving (the stdout is identical)?

a

**Comment by permcody** [comment]
Don't know. I'll have to look tomorrow

**Comment by WilkAndy** [comment]
Thanks @permcody .  it is friday here now, so it'll be about 24*3 hours before i get to this,

a

**Comment by permcody** [comment]
closed by #6439

**Comment by WilkAndy** [comment]
Thanks @permcody ,

a
