### ISSUE TITLE
Improve unit test for RankFourTensor

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6441]
### Description of the enhancement or error report

Test coverage on `RankFourTensor` could be better.
### Rationale for the enhancement or information for reproducing the error

Add a few more unit tests to improve coverage.

**Comment by WilkAndy** [comment]
@dschwen .  I wonder at the same time if you'd like to put the matrixInversion method into another class.  It's rather odd having it in RankFourTensor since it inverts an arbitrary matrix.
