### ISSUE TITLE
Parse double-indexed objects 

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#6442]
This is useful for general double indexed objects being read from input. For example we use cross section sets that interpolate based on multiple variables. Some Materials can hold multiple cross section sets (index 1) and each  cross section set can have its own set of variables (e.g. burnup, temperature etc.). 

1. first separator is space, second one is comma.
2. Example  `material_variables = 'var11,var12,var13 var21,var22 var31,var32,var33,var34'`
3. This would mean that material 1 is interpolated using variables var11, var12 and var13, material 2 is interpolated using var21 and var22 and so on.

**Comment by YaqiWang** [comment]
https://github.com/idaholab/moose/blob/devel/framework/src/preconditioners/SingleMatrixPreconditioner.C#L30 is actually a use case for this. If in place, this new capability can cleanup this code,
otherwise `std::vector<NonlinearVariableName>` type is actually wrong (each element in the input is a comma-separated variable names) in parameter list and misleading to users when they see the syntax dump.

**Comment by dschwen** [comment]
@YaqiWang if you want to open that can of worms than we need to support this type of input parameters in the InputParameters and Parser systems! Just declare the input parameter as `std::vector<std::vector<T> > >` should make MOOSE do the right thing automatically (and provide a more useful type hint for the syntax dump).

**Comment by permcody** [comment]
Not quite automatically, There's no magic way to read that data in the right stride from Getpot. Also adding a delimiter to force the correct stride may need additional processing. I believe this could be supported but a new specialization in Parser.C will be needed at a minimum.

**Comment by dschwen** [comment]
Yes, of course a specialization will be needed, sorry if that was not clear. Such a specialization would standardize the syntax for such 2D input vectors.

**Comment by friedmud** [comment]
I'm not sure I like this particular syntax though.  Why not use something a little more standard... like Matlab-ish syntax or something:

```
two_dee = 'a b c; d e f; g h i'
```

**Comment by permcody** [comment]
Specifically are you wanting to change the delimiter or spacing? It looks
like @snschune didn't provide a thorough example here. I don't see the
space he mentions?

Yes, I'll look into various syntaxes.

**Comment by snschune** [comment]
We'd need a `Parser::setDoubleIndexParameter` that takes an argument `InputParameters::Parameter<std::vector<T> >* param` . Then we'd need to have a double
loop calling `GetPot::get_value_no_default` twice. Once to get the space separated items,
then to get the comma separated items. Or am I completely off here?

**Comment by friedmud** [comment]
@snschune We should decide on one way to do 2D arrays.  Input syntax needs to be consistent across MOOSE applications.  We don't need options for everything

**Comment by permcody** [comment]
No that's probably correct, or close to it. As @friedmud says, the implementation shouldn't be bad, we just need to agree on the syntax.

**Comment by snschune** [comment]
I like @friedmud syntax better than the one we use in yak. To clarify I suggested this syntax with \s = space:
`var11,var12,var13 \s var21,var22 \s var31,var32,var33`

**Comment by YaqiWang** [comment]
Actually I like the matlab-ish syntax @friedmud mentioned better too. Space is still used as a delimiter for the last dimension. The additional dimension is using `;`.

**Comment by permcody** [comment]
Closed by #6459
