### ISSUE TITLE
XFEMFuncs.C is ridiculous

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#6443]
#### Description of the enhancement or error report

About 80% of this file is copy-pasted from libmesh, plus there are things like `i4vec_zero` that just... shouldn't be needed for anything.

**Comment by permcody** [comment]
We definitely need to get rid of copy and pasted code!

Contributed stuff should be moved to `contrib`.

**Comment by jwpeterson** [comment]
OK, actually not that much is copy-pasted from libmesh, but I still think there is a lot of code duplication going on here that should be cleaned up.

**Comment by bwspenc** [comment]
@jwpeterson I agree completely, but I propose we close this because there are already other issues in the system to address this:

Issue #6421 is to get rid of the copy/pasted code from libmesh.  It's not actually a complete copy/paste, which is why it's here, but we do need to get rid of it.

Issue #6419 is to improve the rest of the code in this file.

**Comment by jwpeterson** [comment]
Ok!

**Comment by permcody** [comment]
@jwpeterson - Both of the PRs mentioned in this PR have been merged. Does this ticket still need to be opened?

**Comment by bwspenc** [comment]
I don't think we've resolved all of the problems that @jwpeterson brought up yet, but the other two issues do cover this.

**Comment by jwpeterson** [comment]
There are still huge parts of this file that are just copy-pasted from libmesh.  This entire function, for example:
```
void dunavant_rule2(const Real* wts, const Real* a, const Real* b, const unsigned int* permutation_ids, unsigned int n_wts, std::vector<Point> &points, std::vector<Real> &weights)
```
This contains duplicated code:
```
void stdQuadr2D(unsigned int nen, unsigned int iord, std::vector<std::vector<Real> > &sg2)
```
This actually duplicates code for setting FEM basis function values:
```
void shapeFunc2D(unsigned int nen, std::vector<Real> &ss, std::vector<Point> &xl,
                 std::vector<std::vector<Real> > &shp, Real &xsj, bool natl_flg)
```
All of these functions are just... why?
```
double r8vec_norm(int n, double a[])
{
//    John Burkardt geometry.cpp
  double v = 0.0;
  for (int i = 0; i < n; ++i)
    v = v + a[i] * a[i];
  v = std::sqrt(v);
  return v;
}

void r8vec_copy(int n, double a1[], double a2[])
{
//    John Burkardt geometry.cpp
  for (int i = 0; i < n; ++i)
    a2[i] = a1[i];
  return;
}

bool r8vec_eq (int n, double a1[], double a2[])
{
//    John Burkardt geometry.cpp
  for (int i = 0; i < n; ++i)
    if ( a1[i] != a2[i] )
      return false;
  return true;
}

double r8vec_dot_product(int n, double a1[], double a2[])
{
//    John Burkardt geometry.cpp
  double value = 0.0;
  for (int i = 0; i < n; ++i)
    value += a1[i] * a2[i];
  return value;
}

bool line_exp_is_degenerate_nd(int dim_num, double p1[], double p2[])
{
//    John Burkardt geometry.cpp
  bool value;
  value = r8vec_eq(dim_num, p1, p2);
  return value;
}
```

**Comment by bwspenc** [comment]
@jwpeterson I agree, but this issue is a duplicate of  #6421.

**Comment by jwpeterson** [comment]
You are right, sorry, should have read back through all the Issue comments.
