### ISSUE TITLE
Fix memory errors in XFEM

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6446]
### Description of the enhancement or error report
Fix memory issues revealed in Valgrind testing

### Rationale for the enhancement or information for reproducing the error
Valgrind reports memory leaks and unitialized memory reads. This may be the cause of a reported failure on a developer's Mac.

### Identified impact
Changes to XFEM-calling code in Assembly.C, and XFEM module code.

**Comment by bwspenc** [comment]
There are no issues related to XFEM tests in last night's Valgrind testing, so I'm closing this issue.  All remaining issues are timeouts in unrelated tests.

**Comment by bwspenc** [comment]
I'm reopening this issue because a couple of new memory issues have crept into the XFEM code.

**Comment by permcody** [comment]
@bwspenc - All memory errors are gone. This can probably be closed again.
