### ISSUE TITLE
Improve XFEM test coverage

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6453]
### Description of the enhancement or error report

Improve XFEM test coverage
### Rationale for the enhancement or information for reproducing the error

Test coverage isn't high enough
### Identified impact

Add tests and remove unneeded code in xfem module

**Comment by WilkAndy** [comment]
Hi @bwspenc .  I'm not entirely sure what this XFEM is, but i believe it could be quite useful in my porous-flow+solid-mechanics stuff.  Are you planning on putting doco on moose framework.org anytime soon?

**Comment by bwspenc** [comment]
@WilkAndy Yes, I am planning to write this up soon.  I'm waiting for the dust to settle on this initial merge and make sure the issues are sorted out with that before I send out an announcement.

**Comment by permcody** [comment]
XFEM coverage is now at 85%. I'm closing this ticket...
