### ISSUE TITLE
The anisotropic interface kernels and examples need to be improved

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#6463]
### Description of the enhancement or error report
The ACInterfaceKobayashi kernels have errors in the jacobian. Also, the snow examples have a mesh that is too coarse, severely impacting the solution.

### Rationale for the enhancement or information for reproducing the error
The incorrect Jacobian hurts convergence such that very small time steps are needed. The coarse mesh induces branching independent of the anisotropy.

### Identified impact
This model is our first anisotropic interface model and needs to be as correct as possible, as it will serve as an example for future development in this area.

**Comment by dschwen** [comment]
Sounds good, go for it. @aeslaughter did change the example very recently to make it mesh adaptive. It'd be great if the Jacobian got some love though.

**Comment by aeslaughter** [comment]
I didn't change the example, I just added another input file that uses
adaptivity. If it needs to be finer, go crazy just increase the refinement
level.

**Comment by tonkmr** [comment]
Having a coarse mesh in the phase field method can invalidate your results, show I made only one example, snow.i, that uses mesh adaptivity by default.

**Comment by dschwen** [comment]
:+1:
