### ISSUE TITLE
Get rid of all usage of strings of 9s in XFEM

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6478]
### Description of the enhancement or error report

There are multiple places in the XFEM code where unsigned ints are set to constants that are strings of 9s.
### Rationale for the enhancement or information for reproducing the error

Eliminate all of these to reduce the potential for errors
### Identified impact

Multiple classes in XFEM module

**Comment by friedmud** [comment]
lol

**Comment by bwspenc** [comment]
@friedmud We were just copying you!

**Comment by friedmud** [comment]
"Imitation is the sincerest form of flattery" may not apply when it comes
to poor coding habits! ;-)

**Comment by permcody** [comment]
3.5 years later and XFEM is still full of 9s! Haha

**Comment by bwspenc** [comment]
Yeah, I know...
