### ISSUE TITLE
Extend InputParameters::defaultCoupledValue

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#6480]
`InputParameters::defaultCoupledValue` is used when parsing `std::vector<VariableName>`, but 
would not handle multiple assigned default values correctly, e.g.   `example = '1.0 3.0 1.1'`.
Currently it overrides the default with the last parsed element. In the example above all variables
would be set to `1.1`.

**Comment by YaqiWang** [comment]
This might open another can, for example, how about '1.0 real_var_name 1.1'?

**Comment by permcody** [comment]
I'm not sure I want to support that although we could rather easily. You
might be able to convince me but it seems like we should either do all or
nothing here.

**Comment by snschune** [comment]
@permcody I hoped you'd reduce the priority to low...:).

**Comment by permcody** [comment]
Why did you strip out the template?!? Are you not NQA-1 trained?

**Comment by permcody** [comment]
"normal" is the new low. When was the last time any of your tickets got worked on?
