### ISSUE TITLE
Migrate Solid Mechanics postprocessors into Tensor Mechanics module

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#6484]
### Description of the enhancement
Several post processors exist in solid mechanics but not in tensor mechanics;  these post processors will be replicated in tensor mechanics.

### Rationale for the enhancement
As part of the migration to a single continuum mechanics module, these postprocessors need to be moved into tensor mechanics.

### Identified impact
Tests within modules will be updated (combined) / duplicated (solid mechanics) to use the Tensor Mechanics version of the postprocessors.  The postprocessors in solid mechanics will be left to avoid breaking apps; however, perhaps a deprecated flag ought to be added to the solid mechanics postprocessors?

**Comment by friedmud** [comment]
I vote for deprecation. You need to leave the existing tests in place as
long as that code remains in the code base too.

**Comment by sapitts** [comment]
I'm looking at the [mass postprocessor ](https://github.com/idaholab/moose/blob/devel/modules/solid_mechanics/src/postprocessors/Mass.C)as a starting place which has tests in combined and misc.  Should I duplicate all of the tests in combined and misc to have one set of tests for the SM version and a second set of the same tests for the new TM version?

**Comment by permcody** [comment]
I'm not a big fan of any of this duplication but I recognize the need so we
can make some concessions here.

As far as testing goes if these are really duplicates, (barring the slight
name change so that they can coexist in the combined module) you should be
able to reuse the same tests while hitting both code paths by simply
creating addition "test specifications" and supplying the appropriate
--cli-args parameters to substitute in the "new" object where appropriate.

If none of that made any sense just stop by and I'll show you how.

**Comment by sapitts** [comment]
Can I change entire blocks with the the cli_args command, or does the input block name (e.g. Problem) need to be conserved when reusing the tests?

Case in point:  the tests in combined/evoling_mass_density use a solid mechanics action for the kernel, and I'd like to make sure that the tensor mechanics test for the postprocessor uses the only tensor mechanics kernels, materials, ect when testing the new post processor.  Thanks for the help!

**Comment by permcody** [comment]
No, cli_args won't work here. It only impacts information read from the input file. I don't believe that the SolidMechanics Action has any parameters that control what types of objects are built, therefore you can't impact what happens there. I think you'd have to add parameters (optional) to the Action Parameters itself to make this work like you'd like.

**Comment by sapitts** [comment]
@backmari I'm working migrating the TorqueReaction postprocessor into tensor mechanics (our goal is to port all of the capability of solid mechanics into tensor mechanics and then remove solid mechanics), and I am running into some trouble with my hand calculations to verify the model behavior in tensor mechanics.  Would you help with these couple of questions please?
- Does  the TorqueReaction postprocessor make assumptions about the orientation of the force vector with respect to the axis of rotation direction?  
 - Is the code to calculate the projection of the position vector and vector r (lines 48 - 53) to find a vector r normal to the axis of rotation direction vector, and, if so, are there limitations on the allowable values of the axis of rotation direction?

I'd be glad to email with you off-line if you do not mind; my email is pitts.stephanie-at-gmail.com. 
it will be easier to send a pdf with equations and pictures to explain my difficulties. 
Thanks for the help!
