### ISSUE TITLE
Kernel for chemical potential in Cahn Hilliard equation

### ISSUE THREAD

**Issue by cpritam** [idaholab/moose#6487]
### Description of the enhancement or error report

Solve chemical potential in a weak sense
Allow chemical potential to be functions of material state (stress, etc.)
### Rationale for the enhancement or information for reproducing the error

To be used in modeling of diffusional creep at meso-scale
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None.

**Comment by permcody** [comment]
Closed by #6499
