### ISSUE TITLE
correct some mortar tests 

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#6488]
### Description of the enhancement or error report
some mortar tests are not running correctly. 

### Rationale for the enhancement or information for reproducing the error
There are two issues for some mortar tests.

1. For a well-posed interface problem, two interfacial conditions are needed, the jump in the field ```[[u]] = i``` and the jump in the flux ```[[\grad u \dot n]] = j```. For the weak form, integration by part will give a jump term ```\int [[\grad u \dot n]] * <test_function>``` on the interface. With the given value ```j```, this term becomes ```\int j * <test_function>``` and goes to the RHS. No bc kernel is needed on the interface.

1. Mortar method uses ```Lagrange multiplier```. For this mixed formulation the discrete spaces for the discretization of the primal variable and the multipliers have to fulfill the inf-sup condition in order the resulting numerical scheme to be stable. Empirically the multiplier should use lower order shape function than primal variable's one. For one mortar test in which both primal variable and the multiplier use second lagrange shape function, the solve does not converge. If I change to the multiplier shape function to first order, the solve converges pretty well.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
only test files are modified

**Comment by permcody** [comment]
@jiangwen84 - Thanks for the clear issue and explanation.
