### ISSUE TITLE
Continuously fixing compiling warnings with this issue

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6490]
### Description of the enhancement or error report
Occasionally we introduce compiling warnings in the debug mode, which can only be seen with `METHOD=dbg make`.

### Rationale for the enhancement or information for reproducing the error
Users can report warnings here. Then moose developers can reproduce the warning with the debug make.

### Identified impact
Typically the warnings are trivial. But sometimes they could be indicating a serious bug.

**Comment by YaqiWang** [comment]
/Users/wangy2/projects/moose/framework/include/vectorpostprocessors/PointSamplerBase.h:43:16: warning: 'PointSamplerBase::threadJoin' hides overloaded virtual function [-Woverloaded-virtual]

  virtual void threadJoin(const SamplerBase & y);

               ^

/Users/wangy2/projects/moose/framework/include/userobject/GeneralUserObject.h:57:16: note: hidden overloaded virtual function 'GeneralUserObject::threadJoin' declared here: type mismatch at 1st parameter ('const UserObject &' vs 'const SamplerBase &')

  virtual void threadJoin(const UserObject &) /*final*/;

               ^

In file included from /Users/wangy2/projects/moose/framework/src/base/Moose.C:221:

In file included from /Users/wangy2/projects/moose/framework/include/vectorpostprocessors/LineMaterialRealSampler.h:19:

/Users/wangy2/projects/moose/framework/include/vectorpostprocessors/LineMaterialSamplerBase.h:87:16: warning: 'LineMaterialSamplerBase<double>::threadJoin' hides overloaded virtual function [-Woverloaded-virtual]

  virtual void threadJoin(const SamplerBase & sb);

               ^

/Users/wangy2/projects/moose/framework/include/vectorpostprocessors/LineMaterialRealSampler.h:32:10: note: in instantiation of template class 'LineMaterialSamplerBase<double>' requested here

  public LineMaterialSamplerBase<Real>

         ^

/Users/wangy2/projects/moose/framework/include/userobject/GeneralUserObject.h:57:16: note: hidden overloaded virtual function 'GeneralUserObject::threadJoin' declared here: type mismatch at 1st parameter ('const UserObject &' vs 'const SamplerBase &')

  virtual void threadJoin(const UserObject &) /*final*/;

**Comment by YaqiWang** [comment]
In file included from /Users/wangy2/projects/moose/framework/src/outputs/ICEUpdater.C:18:

/Users/wangy2/projects/moose/framework/contrib/ice_updater/include/Updater.h:432:25: warning: unused parameter 'stream' [-Wunused-parameter]

  Updater(std::istream &stream) { mooseError("Updater requires --enable-cxx11 parameter to update_and_build_libmesh.sh."); }

                        ^

1 warning generated.

**Comment by YaqiWang** [comment]
The previous warnings are produced with a832410804fa749c43cb63d065fcf931ffdd2567.

**Comment by dschwen** [comment]
We have #1777 for this

**Comment by YaqiWang** [comment]
@permcody wanted a new one closer to the top. Possibly a good idea.

**Comment by permcody** [comment]
We do, but it's fine to open a new one to deal with a specific issue. Especially since he's only reporting and not fixing at the moment.
