### ISSUE TITLE
Move RankTwoTensor and RankFourTensor into framework

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6497]
### Description of the enhancement or error report

I think it is time that `RankTwoTensor` and `RankFourTensor` become first class citizen of the MOOSE framework. We need these classes in _both_ phase field and tensor mechanics. At the same time we should move the functionality of `ElasticityTensorR4` into `RankFourTensor` and jettison that class entirely.

### Rationale for the enhancement or information for reproducing the error

Moving these classes into framework would allow us to remove the awkward dependence of the phase field module on the tensor mechanics module and it would allow us to support built in tensor output (perhaps more useful for rank two than rank four...).

Having `RankTwoTensor` in framework would make it more natural to use it to replace `RealTensorValue` in phase field (for mobilities for example). We are starting to encounter cases where having the tensor operators and methods form `RankTwoTensor` would make for much cleaner code.

Removing `ElasticityTensorR4` will also allow us to have single utility classes that cover both `RankFourTensor` as well as `ElasticityTensorR4` (like the Composite tensor materials).

### Identified impact

Biggest impact would result from deprecating `ElasticityTensorR4`. External application may be affected by this change (and the transition from `RealTensorValue` to `RankTwoTensor`).

**Comment by permcody** [comment]
I'm supportive of this as long as everything you mention here follows on. I don't want to move them and then have everything else stay as is.

**Comment by tonkmr** [comment]
I am very much in favor of moving the tensors into MOOSE. 

I'm less sure about getting rid of ElasticityTensorR4 (the horrible name was because solid_mechanics already had an ElasticityTensor). The reason we created ElasticityTensorR4 was because we had the dream of someday making smart tensors that didn't require us to store 81 components of a tensor that actually only has 3 or 2 unique components. If that dream is dead, then I am in favor of getting rid of it.

**Comment by mangerij** [comment]
I like this idea. We'll have to watch this closely with Ferret since we also have heavy dependence on tensor mechanics and ElasticityTensor.

**Comment by permcody** [comment]
We need to get testing up on moosebuild.org for Ferret. Seems like I talked
to Brian about this and there was a specific reason we hadn't done it yet.
Let's take a look at this again next week and get it added!

**Comment by brianmoose** [comment]
We already test against Ferret in "App Tests". Is there something more we need?

**Comment by permcody** [comment]
Yes, Ferret should follow our process. Otherwise if it fails it could just
be Ferret having broken code. I'll talk to John and see if he's willing to
go the whole devel/master route like the rest of our applications do.

**Comment by dschwen** [comment]
@mangerij I'll put in a PR for Ferret remove any use of `ElasticityTensorR4`. I'd like to remove it completely from MOOSE. 

I'll go ahead with moving `RankTwoTensor` and `RankFourTensor` into framework.

**Comment by mangerij** [comment]
Thanks for that. Sorry about not merging the old PR. I'll just automatically merge them when I see them.
