### ISSUE TITLE
FEProblem::prepareMaterials() is segfaulting

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6509]
### Description of the enhancement or error report
`FEProblem::prepareMaterials()` can segfault.

### Rationale for the enhancement or information for reproducing the error
If you run `constraints/nodal_constraint` a few million times, eventually it will segfault in `FEProblem::prepareMaterials()`.

The issue appears to be that `MooseMesh::cacheInfo()` isn't quite right and `getSubdomainBoundaryIDs()` returns invalid stuff.

**Comment by friedmud** [comment]
This could have been avoided if more stuff was `const` (yes, I know, it's me saying that) so I'm going to fix up some of that in `MooseMesh` while I'm here...

**Comment by permcody** [comment]
Let's get this PR in. I'd really like our build page to get to green and stay that way.

@friedmud, if you don't have time to fix, I'll address @jwpeterson's comments.

**Comment by friedmud** [comment]
Sorry guys - forgot about this PR... and wasn't available yesterday.  Thanks for fixing this up!
