### ISSUE TITLE
Extra Ghosting Layers

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6515]
### Description of the enhancement or error report

I need the ability to ghost extra "layers" of elements beyond the normal _1_ that we always do.
### Identified impact

Current plan is just to add one more option to the `Mesh` block: `ghost_layers = 4` to get more ghosting.

**Comment by permcody** [comment]
This was added awhile ago:
https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L132-L141
