### ISSUE TITLE
Robust Coulomb contact enforcement

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6524]
### Description of the enhancement or error report

Develop improved algorithms for enforcement of Coulomb contact
### Rationale for the enhancement or information for reproducing the error

The current implementation of Coulomb contact enforcement using both the penalty and kinematic formulations still has some serious robustness and performance issues, and the syntax is messy for the kinematic option because it requires many parameters related to contact slip calculation to be defined in the FrictionalContactProblem.  Penalty enforcement is not sufficiently robust.  If the penalty factor is set high enough to minimize errors, convergence is very difficult.
### Identified impact

Develop a new method for kinematic enforcement of Coulomb contact that does not rely on the outer loop on the solver that is currently used. This will significantly simply input, and will hopefully lead to faster convergence on problems of interest.

Also, improve preconditioning and robustness of nonlinear iterations for penalty-based enforcement of Coulomb contact.

**Comment by permcody** [comment]
Ticket is closed by several merged commits. Enhancements should be done using new tickets.
