### ISSUE TITLE
Cannot output XDA and XDR simultaneously

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6525]
### Description of the enhancement or error report
If you set `xda = true` and `xdr = true` in an `Outputs` block in an input file you get this:

```bash
*** ERROR ***
An output file with the name, out_0000, already exists.

[2] /Users/gastdr/projects/moose/framework/src/outputs/OutputWarehouse.C, line 140, compiled nodate at notime
```

**Comment by aeslaughter** [comment]
This is a symptom of xdr/xda which creates folders or files with out
extensions or something non-traditional.

You can get around this by creating two blocks:

[Outputs]
  [./xda]
    type = XDA
  [../]
  [./xdr]
    type = XDR
  [../]
[]

**Comment by friedmud** [comment]
What do you mean?  They have extensions on them: `.xda` and `.xdr` and no
folders.

**Comment by aeslaughter** [comment]
I will have to look into, I recall there being something strange. I might
be thinking of checkpoints.
