### ISSUE TITLE
`generalized_plane_strain_tm_contact` not reliable

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#6530]
### Description of the enhancement or error report
The `generalized_plane_strain_tm_contact` has unreliable results for the `react_z` variable depending on how the test is execute.

### Rationale for the enhancement or information for reproducing the error

Serial
```text
 mpiexec -host localhost -n 1 /ssd/slauae/projects/moose/modules/combined/modules-oprof --n-threads=1 -i generalized_plane_strain_tm_contact_field.i --no-gdb-backtrace

|   1.200000e+00 |   1.271633e-02 |   1.271633e-02 |  -7.582365e-06 |
```

MPI 2
```text
mpiexec -host localhost -n 2 /ssd/slauae/projects/moose/modules/combined/modules-oprof --n-threads=1 -i generalized_plane_strain_tm_contact_field.i --no-gdb-backtrace

|   1.200000e+00 |   1.271633e-02 |   1.271633e-02 |   1.232027e-05 |
```

MPI 2 w/o `--no-gdb-backtrace`
```text
mpiexec -host localhost -n 2 /ssd/slauae/projects/moose/modules/combined/modules-oprof --n-threads=1 -i generalized_plane_strain_tm_contact_field.i

|   1.200000e+00 |   1.271633e-02 |   1.271633e-02 |  -2.381195e-06 |
```

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This test likely just needs to be improved, at the very least the `react_z` variable removed from the exodiff.

**Comment by permcody** [comment]
@aeslaughter - I believe that we are unable to reproduce this now? Is that correct?
