### ISSUE TITLE
DiscreteMaterial Discussion

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6533]
### Description of the enhancement or error report
The new `DiscreteMaterial` System has generated a lot of discussion... I would like to capture that _here_ so we can decide if there are any actionable issues...

**Comment by friedmud** [comment]
Ok - I'll start: how are Stateful material properties handled with DiscreteMaterials?  Especially since they have no block restriction.  Is storage automatically set aside for element/side/boundary stateful properties?

**Comment by aeslaughter** [comment]
Storage happens based on MaterialBase, so DiscreteMaterials and Materials act exactly the same with respect to storage.

There was some problems when moving from block to block when DiscreteMaterial did not have computeQpProperties called because the data stored in MaterialData was not updated so there was garbage values. 

Since, we cannot "reset" material properties automatically I had to add the `resetQpProperties` method that will set them to some sane state prior to calling the compute methods.

**Comment by YaqiWang** [comment]
I am guessing the DesreteMaterial is actually just storing some by-product of the iteration with the master material calling it. It could be never stateful. Just my cents.

Why cannot we make the DiscreteMaterial bock/boundary restrictable as the master material? They could be on the same blocks, right?

**Comment by aeslaughter** [comment]
@YaqiWang Which master material, what if more than one object uses the DiscreteMaterial.

I am not sure why there is some much discussion regarding the Block/Boundary stuff. There is nothing to restrict, the DiscreteMaterial isn't executed by MOOSE, so it can't be restricted.

If your DiscreteMaterial declares materials (`declareProperty`) then those properties will be updated on the block/boundary/side/face of whatever object is calling `computeQpProperties`. So, if it called by a boundary restricted object and a block restricted object then the declared properties will be computed by the `DiscreteMaterial`.

**Comment by aeslaughter** [comment]
Like I said in the email, I want the BISON team to start using the system to see how it shakes out.

**Comment by friedmud** [comment]
I guess I just don't like the idea that a Material has a handle to another
Material.  We've always maintained that that was not the right design for
the original SolidMechanics system... and I don't understand why we're now
endorsing that behavior.

The issue with block/boundary restriction is that you've tied these
Materials together too strongly now.  Instead of a Material just requiring
a material property (and letting it get computed by whatever object
declared it) you now have to specify _which_ Material is also doing the
computation... and then you have to explicitly tell that Material to
recompute.

I was really hoping for something where Materials still just required each
other's Material _properties_.  And you wouldn't ask a Material to
recompute it's properties... but instead you would ask MOOSE to recompute a
_property_ and MOOSE would dispatch to the correct Material for that block
/ boundary.  That goes against the original idea of the Material system:
that only _properties_ should be depended on: NOT Materials themselves.
That way, how a property is computed can change across the domain without
the other objects being the wiser.

Also: without block restriction... how do you have two DiscreteMaterials
that both declare the same properties?  It would look like they both define
the same properties over the whole mesh... wouldn't that be an error?

In addition: what if both of those DiscreteMaterials are called to
recompute that same property on the same element?

Here's what I was hoping for:

You would have Material A that depended on "sub_property"

You would have Material B that computed "sub_property" and Material C that
computed "sub_property"

Material A would be defined over the whole mesh.  Material B would be on
subdomain 1 and Material C on subdomain 2.  While on subdomain 1 Material A
would automatically get fed "sub_property" as computed by Material B (and
could ask for "sub_property" to be recomputed which would cause MOOSE to
tell Material B to recompute).  On subdomain 2 the same would happen... but
with Material C computing "sub_property" instead.

In your current system you would have to define multiple Material A blocks
(one for each subdomain) to tell it to explicitly use B or C on each
block.  In addition... B and C would have a "collision" of sorts in that
they are both defined over the whole mesh and declaring the same property.
With the current system there is no way to do any sort of intelligent error
handling of material property name collisions...

**Comment by aeslaughter** [comment]
Well, that is much closer to my original design that nobody liked on a
branch I just deleted, b/c I thought I was done with it. However, there is
actually very little difference in the compute methods between this an that
branch.

Also, all the block/boundary consistency checks include
`DiscreteMaterials`. So, I don't think it would be possible to declare the
same property in two different `DiscreteMaterials`, I will need to add some
tests for this.

One possible way to maybe make this safer is to not allow
`DiscreteMaterial` to declare properties but only recompute them, so they
would have get methods that return writable references.

I am just a grunt, I was asked to put this stuff in for the BISON team.
@permcody thought of the

**Comment by friedmud** [comment]
> One possible way to maybe make this safer is to not allow
`DiscreteMaterial` to declare properties but only recompute them, so they
would have get methods that return writable references.

You just described `DiscreteUserObjects`  :wink:

**Comment by aeslaughter** [comment]
`DiscreteUserObjects` do not have a writable reference to the
MaterialProperty.

It would also be simple to add block/boundary compatibility checks on the
`getDiscreteMaterial` call and allow `DiscreteMaterial` objects to be
block/boundary restricted. I will do this tomorrow, it should be difficult.

**Comment by friedmud** [comment]
But, like you say, that's incompatible with the current design.  What
happens when there is a mismatch between the blocks the "master" Material
is defined on and the blocks the DiscreteMaterial is defined on?

**Comment by YaqiWang** [comment]
How about we get rid of the DiscreteMaterial completely but just allow cyclic dependency of materials? Moose will iterate all materials in the cycle and check the convergence. This might sound too crazy...

**Comment by friedmud** [comment]
@YaqiWang good thinking... but there's no way MOOSE can do this automatically... Materials might need to iterate between each other in ways MOOSE cannot determine just from the dependency graph...

**Comment by YaqiWang** [comment]
@friedmud That is true. How about we let user set a parameter in there material and indicating the dependency to other material properties are soft, meaning the cycle can be broken there and the depending properties can be evaluated after. Then MOOSE can start the loop from the material which has the soft dependency. I think we need to be cautious on creating new system something like DescreteMaterial.

**Comment by friedmud** [comment]
@YaqiWang MOOSE _cannot_ do the cycling... at all.  Say you have 3 Materials: A, B, C.  A depends on both B and C.

Here are some options:

- A might need to cycle with B for a while then cycle with C.
- A might need to cycle back and forth with B and C
- A might need to cycle with C until convergence then get an update from B and cycle with C again
- etc., etc.

There is no way to encode this information to allow MOOSE to do the cycling.  The cycling absolutely must be driven inside of the Material.

The question is _what are_ B and C.  Are they Materials or UserObjects?  If they are Materials then does A tell them to recompute directly... or is A just using their properties and asking MOOSE to recompute the properties (removing a direct dependency between the objects).

No matter how you look at it... MOOSE cannot cycle.

**Comment by YaqiWang** [comment]
Then how about `Material` provide an interface like `recomputeProperty(property_name)`. Calling that will result into recompute the material declaring it on the element. We can do this on element level, i.e. that function finds the correct material and then calls `computeProperties()`. We do not have to pass the updated parameters to the material, instead just let the material to be recomputed get the material properties. It will be much easier to break cycles then telling how to do the iteration (for example `getMaterialPropertyWithoutDependency()`). This will require users to ensure ordering properties to be recomputed and check the convergence. Hopefully my suggestions are constructive. Thanks.

**Comment by aeslaughter** [comment]
@YaqiWang You are basically described the syntax we had on the previous
attempt to do this. The problem with it is that the `recomputeProperty`
method cannot simply recompute a single property it must recompute all the
properties that the material is responsible for. Thus, you are at the
current design, get the material you want to compute and call
`computeProperties`.

I am nearly done with working out the block/boundary checks, so stay tuned.
