### ISSUE TITLE
Need an optional parameter for run_tests

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6582]
### Description of the enhancement or error report
We need an optional parameter for `run_tests` script like `--error`, which treat messages of deprecated parameters as an error. Maybe `--error-deprecated`? This will make us easily remove all the deprecated usages in the code and input files as tests.

### Rationale for the enhancement or information for reproducing the error
N/A

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Application developers and users will benefit from this for not letting those messages hang around.

**Comment by permcody** [comment]
I'm curious, does `--error` not work for you or do you have too many other tests with valid warnings in them?

Just so you know, we do have an allow_warnings flag to help out with this case.

**Comment by YaqiWang** [comment]
Oh, so the deprecation message is also a warning?

**Comment by permcody** [comment]
Should be. Have you tried it?

**Comment by YaqiWang** [comment]
Will try it out tomorrow. Either way, I think `allowed_warning="a sample warning message"` for particular tests is useful.

**Comment by YaqiWang** [comment]
Yes, confirmed the deprecation message is a warning and works with `--error`. I will close this issue.
