### ISSUE TITLE
Cleanup initializer lists in modules

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6603]
### Description of the enhancement or error report

Homogenize the code standard.
### Rationale for the enhancement or information for reproducing the error

Having different code styles through out modules is confusing. Users will use those as (wrong) examples and we will see the deprecated style pop up again and again in PRs.
### Identified impact

Makes things more prettier.

**Comment by permcody** [comment]
All formatting is now controlled automatically by clang-format. Closing as irrelevant.
