### ISSUE TITLE
reinit shape functions at physical points within neighbor element

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#6607]
### Description of the enhancement or error report
This will add and fix some functions to allow users to reinit shape functions at physical points within neighbor element.  

### Rationale for the enhancement or information for reproducing the error
I tried to reinit shape functions at physical points within neighbor element for XFEM constraint problem. From doing this, I observed some inconsistency of several functions in the framework. 

1. In ```Assembly.C```, if you want to use ```reinitNeighborAtPhysical```, you have to pass in the neighbor side even though the physical points are not necessarily on the side.

2. In ```MooseVariable.C```, the codes of ```computeNeighborValuesFace``` and ```computeNeighborValues``` are identical because only the 'shape functions on the face' are calculated and stored.

3. ```MooseVariable.C``` only provides ```phiFaceNeighbor()...``` functions even though they can return the shape functions at the points within the element. It is a bit confusing.     

I understand that the existing functions are designed for more general purpose which I probably did not realize. Here I just tried to modify some functions based on my best knowledge. My code change very likely violates some of your design purpose and just let me know.  

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Have impact to all neighbor reinit related codes, such as DG, constraint, Interface. I made my code change be able to pass all the regression test.

**Comment by jiangwen84** [comment]
@jwpeterson Can you take a look at my commit? This is my first try :-)

**Comment by jiangwen84** [comment]
@jwpeterson If you have some time, would you mind to look at my code? Thanks!

**Comment by jwpeterson** [comment]
Hi @jiangwen84, I got back from vacation and looked at the PRs first so I didn't see your issue until right now.  I will take a look...

**Comment by jwpeterson** [comment]
This looks reasonable to me.  I'm a little bit confused by the naming of `Assembly::reinitNeighbor()` and the new function `Assembly::reinitFENeighbor()` being so similar.

`Assembly::reinitNeighbor()` uses a quadrature rule from `_holder_qrule_neighbor` while `Assembly::reinitFENeighbor()` just uses reference_points passed in directly... I think?  Also, if you can come up with a simple test that uses this (maybe an XFEM test?) then it shouldn't be too hard to turn it into a PR.  

Also, I'm sure @andrsd will have some comments on this, I believe it is his design originally.

**Comment by jiangwen84** [comment]
Thanks John! I agree with what you said and probably want to wait for David's more comments on this. Meanwhile I will think about the test files.

**Comment by andrsd** [comment]
The important fact to understand is that all the `neighbor` stuff was designed for a face of a neighbor element. Typically, we are on a edge and we deal with `(current elem, its side)` and `(current elem's neighbor, its side)`.  We never designed for values in the interior of the neighbor.

I will go look at your code, now... Just wanted to make you guys aware of the design.

**Comment by jiangwen84** [comment]
I understand that for most of cases, we only need to deal with the neighbor faces instead of interior points. However, in XFEM, we are on two overlapping elements and a interface goes through elements. To integrate along the interface, we want to reinit element and its neighbor element's shape functions at the quadrature points on the interface and these quadrature points will be within the elements.

**Comment by andrsd** [comment]
I see. Thanks for the clarification.
