### ISSUE TITLE
Integer data is being incorrectly rounded from DP fields?

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#6621]
libMesh tries to preserve numeric data during refinement and coarsening, but this entails solving local projection problems, which can add epsilon error to the fields being projected.  If those fields are used to store integers, but their data is cast back to integer rather than being rounded-to-nearest back to integer, then the data will be corrupted (static casts will truncate 1.9999999999999999 to 1).  This bug exists at
https://github.com/idaholab/moose/blob/devel/framework/src/base/FlagElementsThread.C#L60
and I fear similar bugs may exist elsewhere; C-style casts are basically impossible to grep for.

Corrupted marker flags seem to affect one MOOSE unit test, as discussed here: https://github.com/libMesh/libmesh/pull/871#issuecomment-199457373

Fixing this problem should affect no interfaces, but may cause false-positive "regressions" when AMR gold standards generated with the buggy code no longer match runs with corrected code.

**Comment by friedmud** [comment]
Hmmm - I see what you're saying now.

**Comment by friedmud** [comment]
What's the fix?  Actually do proper rounding?  I don't suppose there's any way to tell your projection stuff to NOT interpolate certain variables... and instead just copy their value?

**Comment by roystgnr** [comment]
"Actually do proper rounding" is the fix I'm working on in MOOSE.

And "copy as many values as possible" is actually how I noticed the bug!  libMesh has for ages past done a projection problem when refining an element, because what else are ya gonna do?  I got a decent optimization from copying values in the special-but-common case of constant monomial FE.

But we should fix it in MOOSE regardless of the upcoming improvement in libMesh.  Belt-and-suspenders.

**Comment by roystgnr** [comment]
Okay, to clarify: "Actually do proper rounding in the one case I found where we weren't" is the fix I'm working on in MOOSE.  I'd really appreciate more eyes checking to see if there's anywhere else in the code that's using casting where rounding would be safer.

**Comment by friedmud** [comment]
So, you're saying that it _was_ doing (bad) rounding but _now_ it's doing copying?  If that's the case then we don't need proper rounding... we just need to regold.

**Comment by roystgnr** [comment]
MOOSE is doing truncating, but should be doing truncating for correctness.  We'll need to regold along with this change.

libMesh is doing projection solves (which entail roundoff error), and always will be doing projection solves in general cases, but should be doing copying in special cases for speed and accuracy.

I'd like to make the former change first before proceeding with the latter, so that I can isolate the anti-regressions produced by proper rounding from any actual-regressions produced by my other attempts at optimization.

**Comment by friedmud** [comment]
I really don't want to do rounding - way too much of a pain to track down every place where that is done in the code.

I would rather rely on the projection system always copying Constant Monomials...

**Comment by roystgnr** [comment]
I've got to put in a PR to regold regardless.  I could generate the new golds by running against the slightly-complicated changes in my libMesh optimization branch, but then they won't pass unless I also include the libMesh updates, and then neither the new golds nor the updates will have gotten a real test.  Or I could generate the new golds by making a non-complicated one-line change in MOOSE, everything will pass, everything in the libMesh updates will become independently testable, and MOOSE will be more robust against any future O(epsilon) changes in projection code.

I'm actually happy with *removing* the rounding later if you want, but if so then we need to at least stick in ```libmesh_assert_equal_to(truncated_value, rounded(value))``` instead.  This is an insanely annoying bug to track down to its root.

**Comment by friedmud** [comment]
One reason I don't like the rounding is that it can cover up real mistakes.  These are supposed to be integer fields... we really don't ever want them rounded (or projected, if possible... but obviously that's what was happening previously)

Do what you want though... my voice is only one.  The rest of the guys can weigh in here too...

**Comment by roystgnr** [comment]
"Supposed to be integer fields" is tricky, because under the hood they're just not integer fields, and it's hard to keep in mind that rounding error is utterly unavoidable on fields with type==A but is utterly impermissible with type==B.

A hypothetical example in favor of "be more robust in MOOSE" over "assert exactitude from libMesh": what do you expect to happen after a little hp refinement?  In the long run we should create a CONSTANTMONOMIAL type (possibly with a less horrid name) which would be "immune" to p refinement, and use that in MOOSE to store integer flag variables.  But what would happen with a MONOMIAL even after my optimization is applied is that the constant monomial would p-refine into a higher order monomial, it would no longer trigger the "we can just copy dofs for this special case" logic, it would fall back on the projection code path, and some integers would again potentially get turned from N into N-epsilon in libMesh and from N-epsilon into N-1 in MOOSE.

My preference has gone from weakly favoring "turn that rounding into an assert after libMesh is updated" into strongly favoring "turn that rounding into an assert only after CONSTANTMONOMIAL is added and employed".  I'd been wanting to add that anyway to let you guys p refine efficiently, and it'd be a reasonable place to enforce a lack of rounding error too.

**Comment by friedmud** [comment]
Ummm... we're never going to do p refinement on one of these integer fields.

I wouldn't mind a FEType that is called `INTEGER`...

**Comment by roystgnr** [comment]
Right now we don't have any way to *avoid* doing p refinement simultaneously on every single variable associated with a mesh, because p_level() (like h level()) is an attribute of Elem.  If you want to p refine your solution, you're going to p refine every other variable as well, until/unless we change that.

INTEGER sounds about as self-documenting as it gets, doesn't it?  And the very name lends itself to asserts anywhere and everywhere....

**Comment by friedmud** [comment]
Ah!  True!

INTEGER would be nice!

**Comment by permcody** [comment]
This immediate issue has been fixed. There is a bigger underlying design improvement here that should be addressed elsewhere.
