### ISSUE TITLE
Document several framework classes

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6636]
### Description of the enhancement or error report

We still have a lot of base and common classes in MOOSE without documentation. We need to start fixing this up.
### Rationale for the enhancement or information for reproducing the error

This is a necessary step to improve our software quality and quality practices
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

None

**Comment by aeslaughter** [comment]
see #9638
