### ISSUE TITLE
run_tests does not clear the files to be tested before running a test

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6641]
### Description of the enhancement or error report
I noticed that one of my test on my local machine passed the test. But actually it should not because it did not produce the expected csv file. But there is a leftover in the folder of that file, which made the test script happy.

### Rationale for the enhancement or information for reproducing the error
If we have a fresh build, this issue will possibly not show up. But if two tests happen to generate the same output file and suddenly the second test stops generating the output, test script will not capture it. So I am suggesting before the test starts to delete the expected files.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
If the change had the impact on the tests, it would be detecting a bug.

**Comment by permcody** [comment]
Actually it DOES clean up:
https://github.com/idaholab/moose/blob/devel/python/TestHarness/testers/CSVDiff.py#L20-L26

We'll need to take a look at your specific case to see what's different about it.

**Comment by YaqiWang** [comment]
I think I can reproduce this for you. But let us do it tomorrow.

**Comment by YaqiWang** [comment]
@permcody I confirmed this again. What I did is:
1. check out yak devel, make and run tests, all pass;
2. check out my developing branch, which breaks several tests with CSVDIFF, make and run tests, ALL tests pass!
3. do `git clean <those test folder> -xfd` and re-run the tests, I saw all of those tests are failing with error `File does not exist!`, which is correct because my changes disabled the CSV output.

I was puzzled after I saw 2 before and thought we did not put tests for those affected source codes. Then I realized we do have tests, just those tests do not work as expected in this case.

**Comment by permcody** [comment]
OK - We'll try to replicate. Just as a quick check can you put in that print statement in the `CSVDiff` object? Is there anything unusual about your `tests` file or the input file itself to modify the `file_base` maybe to add a folder or something?

**Comment by YaqiWang** [comment]
@permcody I know nothing about python, can you tell me exactly what to do in CSVDiff.py?
