### ISSUE TITLE
Add a scaling factor to ParsedFunction

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#6652]
### Description of the enhancement or error report
Add a scaling factor that is multiplied by the value returned by a ParsedFunction evaluation.  The default value is 1.0.

### Rationale for the enhancement or information for reproducing the error
Required for sensitivity analyses where a ParsedFunction is created internally to a material model or in an action as it would provide an ability to assign uncertainty in the value being returned from the function/correlation from an external code.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Adds a new scaling parameter to ParsedFunction that defaults to 1.0.

**Comment by dschwen** [comment]
what about just putting a `c*(...)` around your function? The $c could be a getpot variable, which would make it easy to change.

**Comment by gambka** [comment]
I haven't used getpot variables so it could work but I will give more details to discuss what the best course of action would be. 

In a material model that inherits from SolidModel there is a MOOSE Enum that allows a user to select a variety of alloys.  Based upon the alloy selected either a PiecewiseLinear or ParsedFunction for the Young's Modulus and Poisson's Ratio is created.  This function is then assigned to the youngs_modulus_function and poissons_ratio_function parameters in the SolidModel base class and then SolidModel takes care of the rest.  The material model also checks if the user has set these parameters in the input file and will use the functions in the input file if specified.

Based upon the correlations from the experimental data I didn't want to rely on the user having to input these in the input file.  However, I am assuming there is uncertainty in these correlations for sensitivity analyses that I am doing.  If I choose the alloys that have PiecewiseLinear functions for Young's Modulus and Poisson's Ratio there is already a scale_factor for these function types that I can access but there currently isn't the option like this for ParsedFunction.

Since the value for ParsedFunction is required to be a string and the scale factor is input as a Real I thought the easiest method would be to add a factor that multiplies the ParsedFunction value.  This would provide consistency with the other function types (i.e., PiecewiseLinear and ConstantFunction). 

If the getpot variables will work or there is a better approach I can try those too.

**Comment by dschwen** [comment]
The getpot variable would have been a good option if you were to construct the function from the input file. As you are building the function from a _"pseudo-action"_ you might as well use 

```
Moose::stringify(factor) + "*(" + function_expression + ")"
```

to build your scaled function inside the SolidModel. This is just a suggestion because it is my personal preference to keep these core classes such as ParsedFunction as simple as possible. Others may very well disagree :-)

**Comment by gambka** [comment]
I agree with you if I can do it in the derived class it is preferred over modifying the core classes.  I'll use the suggestion above and will close the issue.

**Comment by andrsd** [comment]
> Others may very well disagree :-)

We had something similar for postprocessors recently and decided _not_ to do it either...

**Comment by YaqiWang** [comment]
Hehe, that is from me. At the end, a new general postprocessor `ScaleProcessor` was created.
