### ISSUE TITLE
Add Superellipsoid initial condition

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#6655]
### Description of the enhancement or error report
Add initial conditions files to make superellipsoids. A superellipsoid is similar to a regular ellipsoid but can be described by the equation `(x/a)^n + (y/b)^n + (z/c)^n = 1` (n=2 for a regular ellipsoid).

### Rationale for the enhancement or information for reproducing the error
Superellipsoids can be used to produce roughly cubic (or square-like in 2D) shapes with rounded corners, which can be used to approximate, for example, the shapes of gamma-prime precipitates in Nickel-base superalloys for initial conditions in phase-field simulations.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Should be stand alone addition to initial conditions. Similar to `SmoothCircle` initial conditions, there will be a base class and derived classes that supply a list of centers, and `a`, `b`, `c` and `n` for each superellipsoid.

**Comment by dschwen** [comment]
good luck figuring out how to make a smooth interface of uniform width for arbitraty `n` :-)
