### ISSUE TITLE
Optimization of reinitElemPhys()

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6675]
### Description of the enhancement or error report

In my new MOOSE-based application I need to call `FEProblem::reinitElemPhys()` BILLIONS of times.  Since that's a fairly infrequently used code path a few "hot spots" are showing up in the timing.  Need to fix those...
### Rationale for the enhancement or information for reproducing the error

`reinitElemPhys()` is currently quite slow.
### Identified impact

Shouldn't change any API's... just normal optimization

**Comment by permcody** [comment]
Closed by #6948
