### ISSUE TITLE
A multi-threading solution user object issue

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6682]
### Description of the enhancement or error report
I noticed this issue in one of Yak tests, which I tried to run with multiple threads. I used the solution user object reading a xda output and then add a `SolutionFunction` with the user object. When I used this function as the reference solution, I noticed my solution error with it changes with number of threads.

### Rationale for the enhancement or information for reproducing the error
After asking @permcody , I created a moose test which I will send in a PR for and reproducing the issue. You will see the PR referring this issue shortly.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This seems a multi-threading bug.

**Comment by YaqiWang** [comment]
Just to let you know: if I add lock around the code in `SolutionUserObject.C::evalMeshFunction()` Line 635-644, the issue is gone. `libMesh::MeshFunction::operator()` is not thread safe probably.

**Comment by permcody** [comment]
MeshFunction uses the point locator which I'm fairly certain is not thread safe. Thanks for taking a look at this. We'll probably just put a very localized lock in there for the foreseeable future.

**Comment by dschwen** [comment]
I encountered a PointLocator issue before. `PointLocator` **is** thread safe, **except** for the first construction. Let me find the example of how I fixed it. I think you need to fetch one point locator for your mesh **outside** of the threaded region first. Subsequent fetches will create threadsafe subpointlocators. @jwpeterson knows this

**Comment by dschwen** [comment]
Yes, in magpie I have this:

```
  // trigger the creation of a master PointLocatior outside the threaded region
  _mesh.getMesh().sub_point_locator();
```

and then this inside the threaded loop:

```
  // fetch a point locator
  _pl = _mesh.getMesh().sub_point_locator();
```

**Comment by aeslaughter** [comment]
Does it do this: #2283

**Comment by YaqiWang** [comment]
Can someone more experienced than me fix this really quick based on Daniel's suggestion?

**Comment by permcody** [comment]
Maybe, we are super busy and your PR is open so one of use will try to get
to it!

**Comment by permcody** [comment]
@jwpeterson or @friedmud - perhaps you can comment on this. I looked at it briefly and can break it down as follows:

We have an ElementalPostprocessor (epps) being used to retrieve information from a SolutionUserObject (sou). When running with threads that means that we'll have several "eeps" trying to retrieve information from the "sou" simultaneously. I originally said that this was probably a point locator thread issue but it's slightly more complicated than that. The "sou" itself is a GeneralUserObject so we don't create multiple copies of it so what it's doing with MeshFunction -> PointLocators really isn't the problem. It's the fact that that some of it's methods are being accessed by multiple threads and likely passing them down to the MeshFunction uncontrolled. 

The simple fix is to simply lock the methods accessed by the external API. I think a more robust fix would be to create several MeshFunction or something along those lines (one for each thread). I'm thinking the former option is probably best until timing becomes an issue. Any other thoughts?

**Comment by jwpeterson** [comment]
> passing them down to the MeshFunction uncontrolled.

Not sure what you mean by this exactly, but adding locks is definitely the best short term solution to get something working.

**Comment by friedmud** [comment]
Locks for now... I suppose we could make a MeshFuction per thread that are
all backed by the same data.

One thing we don't want to do is have n_threads copies of the solution...
