### ISSUE TITLE
ComputeStrainBase interface is inconsistent

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6688]
### Description of the enhancement or error report

The class makes `computeProperties()` pure virtual. All other classes in plug and play tensor mechanics require the user to implement **per quadrature point** methods.
### Rationale for the enhancement or information for reproducing the error

Inconsistent interfaces are bad
### Identified impact

Might break applications if `computeQpProperties()` is made pure virtual. Fix is simple.

**Comment by sapitts** [comment]
Looks like this has been merged and computeStrainBase only uses `computeQpProperties`; if this is the case, may I update the wiki [Tensor Mechanics intro page](http://mooseframework.com/wiki/PhysicsModules/TensorMechanics/PlugAndPlayMechanicsApproach/) under the heading Strain to reflect the change?

**Comment by permcody** [comment]
Closed by #6691.
