### ISSUE TITLE
.tex files have trailing whitespace

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#6689]
### Description of the enhancement or error report
We currently don't check for trailing whitespace on .tex files, only *.[Chi] and *.py files.
There are .tex files in MOOSE and apps with trailing whitespace.

### Rationale for the enhancement or information for reproducing the error
We don't want .tex files with trailing whitespace.

### Identified impact
We can add .tex files to the "delete_trailing_whitespace.sh" and add a check in CIVET.

**Comment by permcody** [comment]
closed by #6690
