### ISSUE TITLE
Remove block = 0 in phase field where no block restriction is intended

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6697]
### Description of the enhancement or error report
`block = 0` if block 0 is the only block in the simulation is now equivalent to not having a block restriction. We can therefore remove this parameter.

### Rationale for the enhancement or information for reproducing the error
Parameter is superfluous now and just clutters the phase field tests and examples.

### Identified impact
No functional change

**Comment by permcody** [comment]
What are the chances??? I was looking at this old ticket the very second you opened the PR!

**Comment by dschwen** [comment]
Ha, yeah, I saw you going over old tickets and decided to look at my own tickets (trying to avoid the word "issues").
