### ISSUE TITLE
Remove ElasticityTensorR4

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6698]
### Description of the enhancement or error report

This class just complicated things. In its place RankFourTensor should be used and the new members should be moved into a namespace.
### Rationale for the enhancement or information for reproducing the error

Classes templated on ElasticityTensorR4 cannot use RankFourTensor and vice versa. This leads to unnecessary code duplication.
### Identified impact

Deprecate and phase out use of ElasticityTensorR4 first. This may have impact on external applications.

**Comment by permcody** [comment]
Remove here: 398dfa26cff835a5091b7c39804e246be527e4d6

Closing...
