### ISSUE TITLE
Change access qualifiers in PolycrystalKernelAction

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6717]
### Description of the enhancement or error report
Someone needlessly made stuff private! Grrr!

### Rationale for the enhancement or information for reproducing the error
Makes it impossible to derive from this class to reduce code duplication.

### Identified impact
No user facing impact. Allows me to derive an action in Marmot from this, thereby reducing the amount of copy pasta.

**Comment by permcody** [comment]
I wouldn't be upset about this. In general we have too many loosey goosey interfaces. It's easy to change if you decide it needs to be more open in the future.

**Comment by dschwen** [comment]
There is nothing loosey goosey about `protected`. This is just a simple lack of understanding what the difference between `private` and `protected` is.

**Comment by permcody** [comment]
I disagree to a point. I know that some of my classes have data structures
that are rather sensitive. They might track state and really need to be
used in a very specific way in order to be valid at all times. If you open
them up to even protected, it may be difficult to guarantee that state
depending on the interface.

There is definitely a place for private even classes that aren't finalized.
I realize that that's not the case here.

**Comment by dschwen** [comment]
That is _exactly_ my point! If these are internal data structures that track state, then make them `private`  add `protected` accessors! Making stuff unnecessarily private is not _better_. It discourages code reuse and lets to copy-paste-inheritance.

**Comment by andrsd** [comment]
I agree with @dschwen that we have way too many things that are `private` and should be actually `protected`. That prevents further specialization of some leaf classes we provide to application space. I am not talking about the internal classes here...

**Comment by permcody** [comment]
We have a mix of both. We also have too many `public` APIs that should be `protected`. We just have to fix things as we find them.

**Comment by andrsd** [comment]
> We have a mix of both. We also have too many public APIs that should be protected.

That is true too. The problem I see with `protected` vs `private` is that we show that in examples and tutorials and people copy and paste it in their applications.
The problem with `public` vs `protected` is that people use it and they should not ;-) You know who I am talking about ;-)))
