### ISSUE TITLE
Add single axis rotation constructor to RotationTensor

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6721]
### Description of the enhancement or error report
Add constructor that takes an axis identifier and an angle to construct a `RotationTensor` that represents a rotation around a specified axis.

### Rationale for the enhancement or information for reproducing the error
Will make the class easier to use

### Identified impact
Will encourage use of `RotationTensor` in applications

**Comment by mangerij** [comment]
Euler rotations in tensor mech should remain unchanged I hope. that is a
specific set of axes and angles ( Bunge notation I think).

**Comment by dschwen** [comment]
Nobody wants to change Euler rotations

**Comment by dschwen** [comment]
@mangerij check out  d553237, this merely adds another way to initialize a rotation matrix!
