### ISSUE TITLE
Design issue in UserObject

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6723]
### Description of the enhancement or error report
The `UserObject` constructor currently construct `_tid`, `_assembly` and `_coord_sys`, which should not belong to `GeneralUserObject`. Although there will be code duplication, but they should be moved to next level of inheritance.

### Rationale for the enhancement or information for reproducing the error
GeneralUserObject is only on master thread, and those member variables are valid only for threaded user objects.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
There should not be impact unless somebody is screwing up his general user object.

**Comment by aeslaughter** [comment]
How is `_tid` in a `GeneralUserObject`, it is not wrong, it will always be zero?

**Comment by YaqiWang** [comment]
Nothing wrong, just do not want to see anything like `THREAD_ID _tid`. When app developers want to call a threaded related functions in FEProblem, they need to be aware they are always on master in a general user object. `_tid` can confuse them, where they are indeed just using 0.

**Comment by YaqiWang** [comment]
BTW, I used `_tid` before in the constructor of general user objects to prevent multiple full construction with multi-threading. Thanks for the new design, I can remove those protection now. I recently fixed a multi-threading bug caused by the unawareness of the `_tid=0` fact, so I think not constructing `_tid`, `_assembly` and `_coord_sys` can have us not make such a mistake at the first place.

**Comment by aeslaughter** [comment]
The new design should allow you to simply use `_tid`, is uses the correct value regardless is an object is threaded or not. This allows all objects to be consistent with syntax.

But, if others disagree we can change it.

**Comment by friedmud** [comment]
It's fine how it is.

@YaqiWang I actually have an application where I want _threaded_ GeneralUserObjects!  How about that??

I'm working on another solution... I'm not really going to do that.  I just bring it up to point out that there are multiple competing views here :-)

I vote for closing this one...

**Comment by permcody** [comment]
Yeah, I don't think we're going to de-thread this. We were trying to brainstorm ways of helping users not screw up though. If you have a threaded object (AuxVariable) accessing the contents of a non-threaded object (GeneralUserObject). You're asking for trouble. That's exactly what we are doing in a lot of cases. Since most of the time it's read-only, it's probably fine but we just have to think about how people are actually using this and help them not shot themselves in the foot. I vote to close this issue as well.

**Comment by aeslaughter** [comment]
That makes three of of us.

**Comment by friedmud** [comment]
@permcody No.  That's the whole reason that UserObjects come through as `const`.  They are, by definition, read only.  Not "most of the time"... ALL of the time.

**Comment by permcody** [comment]
Even if they are const, so was libMesh::PetscVector(). :wink: 

I'm not sure if there are any guarantees about read-only thread safety in all possible std::containers. You'd think so, but I haven't actually looked.

**Comment by friedmud** [comment]
Well... if a user does `const_cast` a UserObject... that's their own damn problem!  :-)

What do you mean?  I don't see how const containers can't be thread safe...

**Comment by permcody** [comment]
They probably are fine but prior to C++11 there just isn't any mention of
threads or thread safety in the standard. That's all I'm saying. I'm not
arguing to de-thread. Just trying to understand why Yaqi got so screwed up
on this yesterday. How can we better design our interfaces to "prevent"
that?

**Comment by friedmud** [comment]
That's what I'm already saying: they are already well designed to prevent
this... they return a const reference.

I don't even understand how this was a problem.
