### ISSUE TITLE
Phase Field Rigid Body Motion Does Not Scale

### ISSUE THREAD

**Issue by itgreenquist** [idaholab/moose#6725]
### Description of the Problem

The phase field tools for modeling rigid body motion currently do not support large simulations. There are no actions to create multiple AuxVariables or the sets of kernels needed for rigid body motion. The user objects that calculate grain force and velocity are not compatible with graintracker.
### Rationale for the Enhancement

The phase field tools for modeling rigid body motion are only useful if they can be scaled to model large systems. However, the current tools require that every variable, auxvariable, kernel, and auxkernel be entered into the input file manually, making creating simulations or modifying them very time consuming. Additionally, the object ComputeGrainCenterUserObject does not work if multiple grains are modeled with the same variable. This means that large simulations will require too much memory to be convenient, and adds to the problem of writing input files since even more variables will be needed.
### Enhancements to be completed
- [x] Create an action that generate multiple auxvariables using op_num and var_name_base as inputs
- [x] Create actions that generate multiples of the kernels needed for rigid body motion simulations
- [ ] Modify ComputeGrainCenterUserObject so that it can pull grain data from graintracker rather than from the order parameters
- [ ] Create tests for actions
- [ ] Create example input file of larger scale simulation

**Comment by dschwen** [comment]
Sounds good. My preference would be to create *one* action that creates
both the variables and kernels though.

**Comment by itgreenquist** [comment]
This discussion has mostly moved to other issues so I am closing this one.
