### ISSUE TITLE
New module to hold the truss element classes

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#6744]
### Description of the enhancement or error report

created a new module, structural_mechanics, for the truss element classes, and possibly some other types of structural elements, such as beam and shell elements.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by jwpeterson** [comment]
@hchen139 are you working with anyone at INL?

We already have solid_mechanics and tensor_mechanics modules, I'd be very skeptical about adding a 3rd type of "mechanics" module.  Also, if you are planning to add new types of Elements, those would most likely go in libmesh...

**Comment by hchen139** [comment]
I'm working with Ben at INL. @bwspenc 
The reason for this new module is to migrate classes originally reside in solid_mechanics to tensor_mechanics. And it looks like it's better not to leave the truss element classes in tensor_mechanics.

**Comment by bwspenc** [comment]
@jwpeterson This idea was at my suggestion, but I just discussed this with @dschwen, and we've agreed that it makes the most sense to put this in tensor_mechanics.  We were thinking that it didn't belong in tensor_mechanics because it doesn't involve tensors, but I think we're all good with that.  I propose we close this issue and create a new issue for moving it over to tensor_mechanics (and convert it to be like the plug and play materials in tensor_mechanics).

**Comment by permcody** [comment]
I thought the original plan was to eventually merge solid and tensor
mechanics into a single module and make the final name "solid mechanics".
Is this not the plan?

**Comment by dschwen** [comment]
@permcody this is still the plan, and it is another reason why we should integrate this stuff in the mechanics module directly rather than create a new module.

**Comment by bwspenc** [comment]
@permcody Yes, we're all in agreement on the plan.  This code is being restructured to match better with tensor_mechanics, and will be merged in there.  Down the road, we'll rename tensor_mechanics to solid_mechanics.  I think that once we get all of the functionality we need in tensor_mechanics to do what we're doing now in solid_mecahnics, we should do the name switch.  solid_mechanics->solid_mechanics_deprecated (or something like that), tensor_mechanics->solid_mechanics.
