### ISSUE TITLE
Remove entire PhaseField module

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6746]
### Description of the enhancement or error report

PhaseField really needs to be removed immediately (i can do it in the next 5 mins if you like).

### Rationale for the enhancement or information for reproducing the error

It will have potential naming conflicts with the new PorousFlow module, since they both have the acronym "PF".  See, for example, #6740.  Obviously we cannot change that acronym, so PhaseField's just got to go.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Probably not much impact.  I mean, who uses PhaseField anyway?  I'm pretty certain that PorousFlow will be a superior replacement.

**Comment by dschwen** [comment]
Go for it, that thing is nothing but trouble anyways. MOOSE is too small for two PFs.

**Comment by jwpeterson** [comment]
:+1:

**Comment by permcody** [comment]
How about renaming one of them? Fazefield?

**Comment by permcody** [comment]
After talking with the Marmot team, we decided that this may have an adverse impact on their work activities. Closing for now, but open to ideas in the future 😉
