### ISSUE TITLE
Moose::stringify<Real> truncates early

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6749]
### Description of the enhancement or error report
Moose::stringify seems to have different behavior than the C++11 `std::to_string` function w.r.t. outputted precision of stringified floating point numbers. We should either Yank up the precision to give the same results as to_string or at least provide an optional precision argument.

### Rationale for the enhancement or information for reproducing the error
Truncation is evil when building parsed function strings for example.

### Identified impact
May require test regolding if any tests are relying on the reduced precision.

Ping @tophmatthews

**Comment by tophmatthews** [comment]
I found it truncated at the fifth decimal, no biggy but made it hard to compare to legacy codes.

I am currently getting around it by,

```std::string
PointDefectDependentAction::stringToReal(const Real & t, const int p)
{
  std::ostringstream os;
  os.precision(p);
  os << t;
  return os.str();
}```

but a native MOOSE method would be great!

**Comment by dschwen** [comment]
There has been talk about using `to_string` in stringify if C++11 support is enabled. So I think it would be necessary to have both variants exhibit the same behavior.

**Comment by jwpeterson** [comment]
`std::to_string(double)` is required by the standard to produce the same output as `std::sprintf(buf, "%f", value)` and you can't control it.

To make Moose::stringify do the same thing, you'd have to template it (?) and use `std::fixed`, `std::setprecision(6)` I believe...

[see also comment in my commit](https://github.com/libMesh/libmesh/commit/4553f993b5e65001d6770eea070a0b2905ade315#diff-f58535af462594356b93435159ec3274R1294)

**Comment by dschwen** [comment]
Yeah, a template specialization of stringify is needed.
