### ISSUE TITLE
Move AEH heat conduction homogenization stuff out of the solid_mechanics module and into heat_conduction

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#6750]
### Description of the enhancement or error report
The heat conduction homogenization stuff in solid_mechanics needs to be moved to heat_conduction:

HomogenizationHeatConduction kernel 
HomogenizedThermalConductivity postprocessor

### Rationale for the enhancement or information for reproducing the error

It is for heat conduction and doesn't have anything to do with mechanics.

### Identified impact
solid_mechanics and heat_conduction modules. MARMOT will have access to it again, which it doesn't right now. Possibly other external users.

**Comment by tonkmr** [comment]
@dschwen could you do this? It seems like something you could do very quickly.

**Comment by dschwen** [comment]
Sure

**Comment by tonkmr** [comment]
Thanks!

**Comment by dschwen** [comment]
How about we normalize the the names while we are at it and rename the kernel to `HomogenizedHeatConduction`?

**Comment by tonkmr** [comment]
Sounds good to me.
