### ISSUE TITLE
Add capability for enforcement of constraints across XFEM interfaces

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6752]
### Description of the enhancement or error report

Add an ability to enforce constraints on solution variables across XFEM interfaces.
### Rationale for the enhancement or information for reproducing the error

There are many potential applications: mechanical contact, thermal contact, introducing the discontinuity in just one field of a solution with multiple fields.
### Identified impact

This will require the addition of support for element to element constraints in MOOSE, as well as the implementation of XFEM-specific derived classes for enforcement of the constraints across XFEM interfaces.

**Comment by permcody** [comment]
Closed by #6756
