### ISSUE TITLE
phase_field module: Warning with acting variable or duplicates in the arg input for CahnHillard

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#6753]
### Description of the enhancement or error report
In the phase_field module, the `args` input is the union of the mobilities arguments and the free energy arguments. However, including the acting variable in the `args` list results in the variable contributing twice in the residual calculation. A warning should inform the user of this, or better yet, the `args` list checked for duplicates and trimmed. Also, the input parameter description should be updated to reflect the true meaning of `args`

### Rationale for the enhancement or information for reproducing the error
This can be reproduced by adding an args parameter to the test `modules/phase_field/tests/phase_field_kernels/CahnHillard.i` by
```
../../phase_field-opt -i CahnHilliard.i Kernels/CHSolid/args='cv'
```
This will cause non-convergence, not necessarily a different answer, but it's the easiest example to give.
### Identified impact
I'm not sure of any other impacts, rather than preventing users from banging their heads over why their answers change like myself :)

**Comment by tophmatthews** [comment]
ping @dschwen

**Comment by dschwen** [comment]
So, this is not always a problem, only in kernels that iterate over the specified derivatives to build a gradient for example.

**Comment by tophmatthews** [comment]
Yup, it causes issues with CahnHilliard, but not AllenCahn

**Comment by dschwen** [comment]
But it should cause an issue with `ACInterface`!

**Comment by dschwen** [comment]
I've started adding checks in 6213dcd, but I really wonder why MOOSE puts the kernel variable into the `_coupled_variables` vector in the first place. I vaguely remember that I _do_ rely on this behavior in some classes, but I'm not sure it makes sense.
