### ISSUE TITLE
Porous flow contains a checked in test output (not in gold)

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6755]
### Description of the enhancement or error report
modules/porous_flow/tests/kernels/simple_diffusion/simple_diffusion_out.e
Should not have been checked in

### Rationale for the enhancement or information for reproducing the error
Running tests will make your repo dirty,

### Identified impact
None. This looks like an accidental check-in. Ping @WilkAndy 

I'm removing this in #6754

**Comment by WilkAndy** [comment]
I'm pretty sure this came from stork make_new_module - i'll submit an issue there.

a

**Comment by WilkAndy** [comment]
Hang on, what am i talking about?!?!  Of course it was me who accidentally committed this file.  Thanks for the removal, @dschwen 

a
