### ISSUE TITLE
When users specify blocks and no coordinate system, MOOSE would not let them run their simulation

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#6765]
### Description of the enhancement or error report

When users specify blocks and no coordinate system, MOOSE stops with an error.

### Rationale for the enhancement or information for reproducing the error

This setup should be interpreted as "use the default coordinate system on all of my blocks" and not as an error.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Will make MOOSE smarter!

**Comment by andrsd** [comment]
Actually, does `MultiMooseEnum` allow duplicate values? I thought it does not... Just making sure.

**Comment by andrsd** [comment]
I need to change this issue, I did not properly understand `MultiMooseEnum`.

**Comment by YaqiWang** [comment]
I think it should be standard vector. It is more strait-forward and avoids any potential broken code if MultiMooseEnum changes. Right?

**Comment by andrsd** [comment]
`MultiMooseEnum` is already a vector.

**Comment by YaqiWang** [comment]
Even it is, vector is a simpler version and standard.

**Comment by dschwen** [comment]
You mean a vector of MooseEnums? MultiMooseEnum was introduced exactly to replace that.

**Comment by YaqiWang** [comment]
Yes. I thought as David before that MultiMooseEnum does not allow duplicated enums. Is std::vector more strait-forward?
