### ISSUE TITLE
unitialised Variables (and AuxVars) in initQpStatefulProperties

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6774]
### Description of the enhancement or error report

See the PR #6763.  It works for quite a few of my cases, but as Yaqi predicted, it doesn't work in general.  We really need this to work

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by aeslaughter** [comment]
What are the cases that need to be supported? If you provide me with some simple, MOOSE only input files, I can see what I can do to make what you need work. Or, at the worst, make a proper error message.

**Comment by WilkAndy** [comment]
Of course @aeslaughter .  sorry.  Hopefully we can get a good example out to you today.

a

**Comment by WilkAndy** [comment]
OK @aeslaughter .  Here's an example

modules/porous_flow/tests/pressure_pulse/pressure_pulse_1d_2phase.i

fails.  It fails because of

modules/porous_flow/src/materials/PorousFlowMassFraction.C

However, if you build it with yaqi_hacky = true (see line 35 of that .C file), the test will run.

**Comment by permcody** [comment]
I can't believe that's an actual option....

You might be disappointed though to learn that it doesn't rhyme :)

**Comment by aeslaughter** [comment]
Thanks @WilkAndy, I will take a look at this next week.

**Comment by dschwen** [comment]
How about `yaqi_crutchy`?

**Comment by aeslaughter** [comment]
@WilkAndy I am running this file with and without this flag and it fails the same way:

```

*** ERROR ***
Solve failed and timestep already at or below dtmin, cannot continue!

Stack frames: 8
0: 0   libmesh_oprof.0.dylib               0x00000001103b488d libMesh::print_trace(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 1533
1: 1   libmoose-oprof.0.dylib              0x000000010fba918a TimeStepper::computeFailedDT() + 618
2: 2   libmoose-oprof.0.dylib              0x000000010fba81bd TimeStepper::computeStep() + 109
3: 3   libmoose-oprof.0.dylib              0x000000010f9980c8 Transient::execute() + 72
4: 4   libmoose-oprof.0.dylib              0x000000010f8ff0e6 MooseApp::run() + 118
5: 5   porous_flow-oprof                   0x000000010f2e3522 main + 114
6: 6   libdyld.dylib                       0x00007fff8bf865ad start + 1
7: 7   ???                                 0x0000000000000003 0x0 + 3
[0] /Users/slauae/projects/moose/framework/src/timesteppers/TimeStepper.C, line 220, compiled nodate at notime
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
Command failed to execute
```
I will probably try to make something much simpler, the scenario is (@YaqiWang can you confirm):

1. Have an AuxVariable
2. A material that uses the AuxVariable in `initQpStatefulProperties`
3. Have an AuxKernel that modifies the AuxVariable on "execute_on = initial"

The problem is then that the material has the incorrect value b/c the AuxVariable change, correct?

**Comment by aeslaughter** [comment]
@WilkAndy I made a branch trying to figure out the problem, as I understand it, and everything works like I would expect. So, can you take a look and see what I am missing?

https://github.com/aeslaughter/moose/tree/initQpStateful-6774
/Users/slauae/projects/moose/test/tests/materials/aux_stateful_depend/aux_stateful_depend.i

**Comment by WilkAndy** [comment]
OK, this is a tiny bit convoluted, so i'll try to explain.

(1) I made a silly mistake in that input file (modules/porous_flow/tests/pressure_pulse/pressure_pulse_1d_2phase.i) because i used PETSc options that cause non-convergence when you use your version of PETSc.  I keep forgetting to change these things, sorry.  So that caused confusion.  I have attached an updated version.
[pressure_pulse_1d_2phase.txt](https://github.com/idaholab/moose/files/285750/pressure_pulse_1d_2phase.txt)


(2) You need to compile and run in debug mode.  In opt mode moose appears to run fine and produces the correct answer.  In debug mode, when PorousFlowMassFraction.C is compiled with yaqi_hacky=false (you've got to hardcode the .C file), I get:

Framework Information:
MOOSE version:           git commit e2a7261 on 2016-05-24
PETSc Version:           3.4.4
Current Time:            Fri May 27 14:27:55 2016
Executable Timestamp:    Fri May 27 14:24:30 2016

Parallelism:
  Num Processors:          1
  Num Threads:             1

Mesh:
  Distribution:            serial
  Mesh Dimension:          1
  Spatial Dimension:       1
  Nodes:
    Total:                 11
    Local:                 11
  Elems:
    Total:                 10
    Local:                 10
  Num Subdomains:          1
  Num Partitions:          1

Nonlinear System:
  Num DOFs:                22
  Num Local DOFs:          22
  Variables:               { "ppwater" "ppgas" }
  Finite Element Types:    "LAGRANGE"
  Approximation Orders:    "FIRST"

Auxiliary System:
  Num DOFs:                22
  Num Local DOFs:          22
  Variables:               { "massfrac_ph0_sp0" "massfrac_ph1_sp0" }
  Finite Element Types:    "LAGRANGE"
  Approximation Orders:    "FIRST"

Execution Information:
  Executioner:             Transient
  TimeStepper:             ConstantDT
  Solver Mode:             NEWTON
  Preconditioner:          asm





Assertion `i < _size' failed
Access out of bounds in MooseArray (i: 0 size: 0)
at /apps/geomodel/moose/projects_andy/moose/framework/include/utils/MooseArray.h, line 289
Detaching after fork from child process 1151.
Stack frames: 18
0: libMesh::print_trace(std::ostream&)
1: MooseArray<double>::operator[](unsigned int) const
2: PorousFlowMassFraction::build_mass_frac(unsigned int)
3: PorousFlowMassFraction::initQpStatefulProperties()
4: Material::initStatefulProperties(unsigned int)
5: MaterialPropertyStorage::initStatefulProps(MaterialData&, std::__debug::vector<std::shared_ptr<Material>, std::allocator<std::shared_ptr<Material> > > const&, unsigned int, libMesh::Elem const&, unsigned int)
6: ComputeMaterialsObjectThread::onElement(libMesh::Elem const*)
7: ThreadedElementLoopBase<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> >::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, bool)
8: void* libMesh::Threads::run_body<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeMaterialsObjectThread>(void*)
9: /apps/geomodel/moose/projects_andy/moose/framework/libmoose-dbg.so.0(+0x1d68d58) [0x7ffff5edbd58]
10: void libMesh::Threads::parallel_reduce<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, ComputeMaterialsObjectThread>(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&, ComputeMaterialsObjectThread&)
11: FEProblem::initialSetup()
12: Transient::init()
13: MooseApp::executeExecutioner()
14: MooseApp::run()
15: main
16: __libc_start_main
17: /apps/geomodel/moose/projects_andy/moose/modules/porous_flow/porous_flow-dbg() [0x422c59]
[0] /apps/geomodel/moose/projects_andy/moose/framework/include/utils/MooseArray.h, line 289, compiled May 27 2016 at 14:11:37

**Comment by aeslaughter** [comment]
Do you know anything about this statement in `MooseVariable::prepare()`?
```
  // FIXME: remove this when the Richard's module is migrated to use the new NodalCoupleable interface.
```

**Comment by andrsd** [comment]
Yes, the if-statement should go completely away, see `prepareNeighbor()` for the structure.
