### ISSUE TITLE
Use std::make_shared

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6775]
### Description of the enhancement or error report

When we gain the ability to use C++11 we need to use `std::make_shared()` every time we construct an object.
### Rationale for the enhancement or information for reproducing the error

It is not only faster... but it's exception safe: http://stackoverflow.com/a/20895705
### Identified impact

Should only impact internal code - no user facing API modifications

**Comment by permcody** [comment]
Thanks for marking this minor. When we do pull the switch on C++11, I'd rather not sprinkle it through the code overnight just in case we find ourselves backtracking somewhere. This definitely will need to happen though eventually.

**Comment by friedmud** [comment]
Yeah - just putting this stuff in as I think about it. All minor for sure
(the code works now) just stuff to do eventually :-)

**Comment by permcody** [comment]
Closing this - I've gone through MOOSE in several places and put this in as I've switched over to smart pointers along with `libmesh_make_unique`. It's good advice, but we no longer need a ticket open for this task.
