### ISSUE TITLE
Add a singleton based plugin system to FEProblem

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6777]
### Description of the enhancement or error report

`FEProblem` is becoming a monolithic hub for everything _global_ in a MOOSE simulation. Every feature that needs some kind of global manger code adds to FEProblem.h and (FEProblem.C). Frequent additions trigger massive recompiles. Adding more and more code makes the class harder and harder to maintain.

Module (and app) developers that want to register global manager code need to make changes in framework. It would be nice if developers could accomplish this within their own codebase.

So here is my latest crackpot idea: **GlobalManagers**. This new _minisystem_ will allow users to register objects in `FEProblem` (and obtain references to them). These objects or _managers_ contain all the code and member variables that were previously tacked onto `FEProblem`. I'm working on a PR where I demonstrate the capability by using it to move all of the `RandomInterface` related code out of FEProblem and into its own manager class. I have plans to add a manager class that provides meta data on derivative parsed materials, which will drastically simplify their use.

More concrete, I propose adding a method `FEProblem::getGlobal<T>()` that returns a reference to a `T` object (which is derived from `GlobalManager`). There is no _name_ here. The call creates or returns a singleton instance of the given class. The call in the `RandomInterface` initializer list looks like this

```
    _ri_manager(problem.getGlobal<RandomInterfaceManager>()),
```

### Rationale for the enhancement or information for reproducing the error

Empower developers to do stuff which they previously needed to modify `FEProblem` for, without having to modify `FEProblem`.

### Identified impact

Will allow us to move code out of `FEProblem`, easier maintenance, more developer flexibility.

P.S.: Yea, I know that it is totally possible to inherit from FEProblem. But if I need functionality in the phase_field module and create a `PhaseFieldFEProblem` and I need stuff in tensor_mechanics and create a `TensorMechanicsFEProblem` and now want to run a coupled simulation... I suddenly need to create yet another `FEProblem` derived class that combines functionality from both. 
With the system described above the needed functionality is hooked into `FEProblem` dynamically and the user does not have to jump through any hoops.

**Comment by aeslaughter** [comment]
I think the action system was intended for this purpose, perhaps we need to
improve upon what the Action can do rather than create a similar system.

**Comment by dschwen** [comment]
?! How does the Action system help with _any_ of this?

**Comment by andrsd** [comment]
One thing to keep in mind is that not all is in `FEProblem`, some stuff is strictly in `NonlinearSystem` and some stuff is sin `AuxiliarySystem`.  This may not be a big problem is `FEProblem` get some proxy Object in your proposed `GlobalManager` system.

Or are you planing on changing just some of stuff in `FEProblem` (i.e. not all of our systems)?

**Comment by dschwen** [comment]
Good question. I hoped that I could move the XFEM stuff from framework easily into its module. But XFEM hooks into Assembly and Transient as well. To achieve this quite a few hooks would have to be added to the GM system. We'd have to weigh the cost vs. the payoff here. The initial idea was to reduce the feature creep in FEProblem, and this, I think, can already be achieved with this approach.

**Comment by andrsd** [comment]
I agree that `FEProblem` is becoming a monster and it would be really cool to have each system contained in some kind of object/interface.  However, that will probably not help with the XFEM stuff ;-( Also, hooking into `Assembly` should not be a big problem, it is in `FEProblem`. Hooking onto `Transient` is probably a bigger problem (just guessing).

**Comment by dschwen** [comment]
It is not really a problem to _do_ it (I'd just loop over teh list of global objects and call a hook on each one). I just don't want to do that in any function that is per-element (like `reinitFE` for example, which contains some XFEM stuff).

I think it is totally fine to do this at any of the points defined in SetupInterface though.

**Comment by permcody** [comment]
I like the idea but I'm a little skeptical since as you've already identified. Global stuff is spread between several object in MOOSE already. I'm open to ideas though.

**Comment by dschwen** [comment]
Ok, let me explain what I really want this for: When using any classes that use the DerivativeMaterialInterface the user has to explicitly specify all the variables the materials uses in the object can depend on. This is to ensure that all the necessary derivatives are pulled in. The current Material system does not allow me to infer the dependent variables. I'd like to use the new `getGlobal` method to hook in a global object that can manage an internal table of dependent variables for derivative materials. With the design in the associated PR I can do that from the PF module without having to put more stuff into FEProblem or without entirely rewriting the material system ;-).

In my derivative material interface I can fetch a reference to my global manager, which manages a map of variable dependencies. All derivative materials would be able to communicate through this global object and register/query the variable dependencies through it.

**Comment by andrsd** [comment]
So, this is more "yet another system in MOOSE" rather than refactoring our systems in FEProblem...

**Comment by permcody** [comment]
I'm part way through adding the ability to detect all dependencies automatically throughout MOOSE. We may not need this system once my work is through. Notice how I started changing all of the interface constructors to take the `this` pointer. Once that's in all of the coupling interfaces you should be able to figure these dependencies out.

**Comment by dschwen** [comment]
You see right through me. But seriously, I hope this can be used to modularize FEProblem. Let me brood over this and see what else it will allow me to rip out of FEProblem.

**Comment by friedmud** [comment]
I will just register a general vote against this. Users will hang
themselves quicky by having global state and modifying it in unsafe ways.
Here are just a few things most people would mess up:

1. Threading. Some data needs to have threaded copies, some doesn't.
2. Restart
3. Solve failure (data needs to be rolled back gracefully)
4. Picard (needs to handle solve() multiple times in the same step
5. Adaptivity. Users will immediately attempt to store datastructures by
element ID and immediately fail to take into account adaptivity.

NO.

We have existing mechanisms for this stuff that advanced people can use to
get their work done.

Now: I'm all for breaking out FEProblem into multiple smaller objects that
wrap up parts of what FEProblem does: what I'm against is making it a
pluggable system.

I am willing to be proven wrong though...

**Comment by dschwen** [comment]
Yeah, I'm aware of the foot shooting abilities this adds. Those exist in FEProblem as well though! But I'll let this simmer a bit more. A different approach might be better.

**Comment by friedmud** [comment]
@dschwen They do exist in FEProblem... but it's sufficiently hairy enough that people generally stay out and find other ways to solve their problems ;-)

That said - we shouldn't really be reliant on "security through obscurity"... so, like I said, I'm willing to be convinced that there could be an API here that would help users and try to steer them away from screwing _everything_ up...
