### ISSUE TITLE
Add submodule dependency check for tests

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#6781]
Tests are skipped if required submodules are not initialized. 
This is required for MAMMOTH because we do not require all submodules to
be present anymore.

Similar capability depending on libmesh compile options exist already. 
I'd suggest add a parameter in `Tester` called `required_apps` and then check it against the
submodules that are initialized. Would it be enough to check if the submodule dir exists and
is non-empty?

**Comment by dschwen** [comment]
This could be added by testing if specific objects are registered.

**Comment by jwpeterson** [comment]
> Would it be enough to check if the submodule dir exists and
> is non-empty?

I think you want to run `git submodule status` to see if submodules are there and initialized.

**Comment by snschune** [comment]
> I think you want to run git submodule status to see if submodules are there and initialized.

That'd be one way to do it. 
However, I just thought that someone might not initialize the submodule but set the App_PATH environment variable. @dschwen's approach would cover that.

**Comment by jwpeterson** [comment]
> However, I just thought that someone might not initialize the submodule but set the App_PATH environment variable. @dschwen's approach would cover that.

Oh, you mean like `$RATTLESNAKE_DIR`, etc.  Good point.

**Comment by snschune** [comment]
Yes. How do you check if "specific objects are registered"?

**Comment by dschwen** [comment]
This would require a test harness PR. The test harness could run the app at the start and dump all registered objects. Then a new directive used in the `tests` file could list one or more object names that could be checked against the compiled list.

**Comment by permcody** [comment]
That's not a terrible idea.

**Comment by brianmoose** [comment]
This is similar to #7774
@dschwen  What kind of syntax would you want for specifying objects? Full path? Or just the name? Or either?

For example,
`Adaptivity/Indicators/*/<types>/AnalyticalIndicator`
or just `AnalyticalIndicator`?

**Comment by dschwen** [comment]
Since object names have to be unique in MOOSE the latter syntax (quite a bit simpler) should probably suffice. There would be a corner case with a hypothetical app that only adds action syntax, but we can burn that bridge when we get there.
