### ISSUE TITLE
RankTwoScalarAux and MaterialTensorCalculator as Materials?

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#6787]
### Description of the enhancement or error report
The calculations of scalar quantities from the stress tensor (e.g. von Mises stress, hydrostatic stress), are currently implemented as AuxKernels which prevents the calculation of these scalar properties at the quadrature points.  

### Rationale for the enhancement or information for reproducing the error
The implementation of the scalar 'stress calculator' as a material will cause code duplication.  To avoid the code duplication among the materials and auxkernels, a new namespace, one for each *_mechanics module, will be created to hold the equations and the auxkernels and materials will return the values.

Additionally, @bwspenc and @dschwen have discussed converting these two aux kernels into materials to reduce the dependence of XFEM on solid mechanics and to ease the transition of XFEM from solid mechanics to tensor mechanics.

### Identified impact
- Update the materials which use either AuxKernel to use the Material
- Update many input files to reflect the change from AuxKernel to Material
- Clarification for users on when to use the AuxKernel version and when to use the Material version

**Comment by sapitts** [comment]
@dschwen In the phase field module aukernels and materials, I could only find a material dependence on the tensor mechanics template [CompositeTensorBase](https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/include/materials/CompositeTensorBase.h); is this template similar what you had mind for the ```MaterialTensorCalculator``` and ```RankTwoScalarAux```, or is there another template in phase field to which you would refer me?

**Comment by dschwen** [comment]
DerivatriveMaterialInterface is a better example
