### ISSUE TITLE
Add Timestepper that takes the time points out of an exodus file

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6795]
### Description of the enhancement or error report
We already have `TimeSequenceStepper`. I could either factor out a BASE CLASS or add the exodus functionality to it. 

### Rationale for the enhancement or information for reproducing the error
This would be neato to compare inputs with slightly different physics in a convenient way (i.e. run one simulation, change the physics slightly, and run the second simulation at the timesteps of the first).

### Identified impact
Added capability

**Comment by permcody** [comment]
Where are you going to be using this? It seems like a pretty specialized stepper. I'm not completely convinced it belongs in the framework.

**Comment by dschwen** [comment]
I'm using it for comparing successive runs of phase field and tensor mechanics problems.
