### ISSUE TITLE
Geometric search not reinitialized when mesh changes

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6799]
### Description of the enhancement or error report

When the mesh changes due to adaptivity or xfem, the geometric search data is updated rather than reinitialized, so newly-created nodes on the slave surface are not included in the contact search.
### Rationale for the enhancement or information for reproducing the error

This is needed for using adaptvity or xfem in conjunction with contact.
### Identified impact

Minor change to DisplacedProblem.C

**Comment by roystgnr** [comment]
This is going to be a slightly more involved fix than just #6801 alone.  It looks like not only do we need to make sure that the appropriate data is reinitialized, we need to make sure it's reiniitalized in the right order...  I've finally got your example case from #6801 completing in dbg mode, after one more substantive change, but the libMesh::ReferenceCounter code is yelling at me when it closes about 17 leaked Elem objects, and although it looks okay in the eyeball norm, exodiff sees errors of more than 5% (relative to global peak, not just local node value) in contact_pressure and 1.5% in displacement.

**Comment by roystgnr** [comment]
This will turn into a separate issue, I'm sure, but that reference count is insane regardless of the leak.

We have a mesh that, when refined and counting non-active elements, has 146 elements.  We have it in displaced and reference versions, so that's 292 elements.  So where and why are we creating over TWENTY EIGHT THOUSAND elements?

**Comment by roystgnr** [comment]
Wait, 293 elements - our RemoteElem stub counts as one.

**Comment by roystgnr** [comment]
Ah, here we go.  Our side_ptr shim element creations also count as Elem creations, and we do a ton of those when building topology.  So the huge creation count is justified, if nowhere near optimized.

**Comment by bwspenc** [comment]
@roystgnr It doesn't surprise me too much that the solution diffs a little bit.  There have been a few fundamental changes to the mechanical models since I created that solution.  If it is able to run in debug and appears to be enforcing contact on the refined nodes, we are likely in pretty good shape.

**Comment by roystgnr** [comment]
Is that right?  Great!

In that case, I'll make a new PR if/when I figure out this memory leak.

**Comment by roystgnr** [comment]
With a newly generated gold standard, I mean.
