### ISSUE TITLE
Need to be able to compute variable values on faces based on its current shape function expansion coefficients

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6803]
### Description of the enhancement or error report

In an elemental aux, I need to loop through all the sides of the current elements and do some evaluation. I tested that it works with only one piece missing. I need to be able to compute variable values on faces based on its current shape function expansion coefficients in the variable (not the coefficients grabbed from the solution vector). Otherwise, the quantities on face quadrature points will not reflect the latest available values of the variables.
### Rationale for the enhancement or information for reproducing the error

See the description.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This is a new feature. Comments are welcome.

**Comment by permcody** [comment]
"... based on its current shape function expansion coefficients in the variable (not the coefficients grabbed from the solution vector)" - Hmm... Isn't this sensitive to the order in which you compute the elements? What do you mean by "in the variable"?

**Comment by friedmud** [comment]
I'm confused by this as well.  Can you explain a bit more @YaqiWang ?

**Comment by permcody** [comment]
@YaqiWang - Is this ticket related to what you are working on today (Sept 5, 2017)?

**Comment by YaqiWang** [comment]
Not related. This issue is rooted from the fact that we do not have boundary restricted variables.  I do not know when we are going to have it in libMesh. But I feel we can close it now.
