### ISSUE TITLE
Fix PrintMaterials test

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6822]
### Description of the enhancement or error report

The actions/meta_action/print_materials test fails occasionally. After looking at the source code it becomes apparent as to why. The order in which the information is written to the output file is based on the set order of the pointers! This is very wrong. This test seems like a bad idea.

```
    for (std::set<const AddMaterialAction *>::iterator it = actions.begin();
         it != actions.end(); ++it)
      os << i++ << "," << map_type[(*it)->getMooseObjectType()] << std::endl;
    os.close();
```

### Rationale for the enhancement or information for reproducing the error

Run it thousands of times and it _might_ fail.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Just this test

**Comment by YaqiWang** [comment]
I guess it is created by me. How about sort it based on the action name? The test is there for testing the action getters.
