### ISSUE TITLE
ExodusTimeSequenceStepper Should Only Read on Processor 0

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6826]
### Description of the enhancement or error report
The newly created `ExodusTimeSequenceStepper` ( #6797 ) currently reads the Exodus file on all processors... it should really only read on processor 0 and broadcast.

### Rationale for the enhancement or information for reproducing the error
Will really speed up parallel runs that use that capability.

### Identified impact
Internal changes to an object.

**Comment by dschwen** [comment]
Uhm, is there an interface for parallel communication after construction... I guess I could do it in initial setup, but the _big_ deal is actually threading (object construction is serial on each compute node, but MPI parallel already!). So I need to figure out how to do the threaded construction right. 

This is very similar to what I did in #6773 which does the expensive parts of object construction only in thread 0 and has all other threads copy the results from the thread 0 instance.

**Comment by dschwen** [comment]
Wait.. are timesteppers even threaded.. I should check that first

**Comment by friedmud** [comment]
They are not threaded.

_communicator.broadcast() should work perfectly on a std::vector...

**Comment by dschwen** [comment]
Ok, if there is no threading the MPI stuff becomes trivial.

**Comment by dschwen** [comment]
Ah well, segfaults. Next week.

**Comment by friedmud** [comment]
I believe you have to size the vector on all processors first...

**Comment by permcody** [comment]
Depends, there are versions that require that and versions that don't. The
ones that resize first are more efficient.

**Comment by dschwen** [comment]
Guess I'll just use `allgather` then...

**Comment by permcody** [comment]
Umm, there's definitely a broadcast version. Allgather isn't technically
the right operation (even though it would work).

**Comment by dschwen** [comment]
Yeah, yeah, I didn't see that magic broadcast, so I'm now just doing two broadcasts. One for size and one for the vector content.
