### ISSUE TITLE
XFEM leaking from a shared pointer

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6832]
### Description of the enhancement or error report

Yeah, you read that right. 

### Rationale for the enhancement or information for reproducing the error

Error is showing up in modules heavy valgrind

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Minor, but should be fixed

tagging @bwspenc and @jiangwen84

https://www.moosebuild.org/job/19335/

**Comment by bwspenc** [comment]
@permcody my guess is that this has something to do with the fact that _problem is a reference to a shared pointer in the Action base class. When we pass that into the constructor of the XFEM class in XFEMAction.C, a copy of the shared pointer gets created because the constructor takes a MooseSharedPointer<FEProblem> rather than a MooseSharedPointer<FEProblem> &. @jiangwen84 originally had it coded the second way, but changed it  based on review comments. It seems like either way would be OK based on my understanding of shared pointers, but maybe something weird is happening when a new shared pointer is created from a reference to one. @jiangwen84 is going to test out some ideas on a machine where he can run valgrind.

**Comment by friedmud** [comment]
@bwspenc that seems unlikely... the only "bad" thing that can happen by passing a shared pointer by reference is that it doesn't increase the "reference count" of the shared pointer... so if all other copies of that shared pointer get destroyed at some point then the object being pointed to would be destroyed and the object holding a reference would now have a dangling pointer.  That's unlikely to cause a problem with `_problem`

That said: we should prefer to pass shared pointers by _copy_ (just like a regular pointer!) unless we have a specific reason not to (the only reason would really be for optimization... like in the inner part of a tight loop where you don't want the pointer reference count to have to increase/decrease millions of times as you go through the loop)

**Comment by bwspenc** [comment]
@friedmud I agree that this seems unlikely.  I'm just struggling a bit to figure out what might be wrong based on the output from valgrind and looking at the code.

This may have nothing to do with the issue at hand, but based on what you are saying about preferring to copy the shared pointers, it seems that all of those member variables of type MooseSharedPointer<SomeType> & in Action should not be references.  Is that right? Performance definitely isn't an issue with these: there's only a handful of them and they point to things like FEProblem.

**Comment by friedmud** [comment]
@bwspenc I would agree... except if they come from InputParameters... then our convention is to _always_ snag by reference... no reason to change that for this (I don't think... =-)

**Comment by permcody** [comment]
Yuck - those probably should be just pointers. I think they were references to pointers in the past and that didn't change when we switched over. Daniel and I had a spat just last week over new code that had references to smart pointers in it. I argued against the reference part and said we should just use these things like pointers. If we think we are optimizing something by using references instead of just copying the smart pointer we aren't thinking correctly :)

**Comment by friedmud** [comment]
@permcody I agree... except in the corner case of in the middle of performance sensitive loops.

I use smart pointers all over my new application... for everything (don't have a single `new` in the entire code)... and smart pointer reference counting _does_ show up in Instruments if I don't take care to use references when passing smart pointers around inside loops that are called millions of times.

So: I would vote for the default being "pass smart pointers by copy"... with an exception for performance sensitive areas.

**Comment by friedmud** [comment]
One more thing on this: If you're going to pass smart pointers around by reference... you're basically _undoing_ their smartness!

**Comment by permcody** [comment]
BTW - I looked at this briefly and it's not the shared pointer that's leaking. It's something inside of the object held by a shared pointer. (i.e. it's normally missing deletes)

**Comment by jiangwen84** [comment]
I am running valgrind on rod (``` valgrind  --leak-check=full --tool=memcheck --dsymutil=yes --track-origins=yes -v ~/projects/moose_rod/modules/combined/modules-dbg -i diffusion.i --no-gdb-backtrace```) but I did not get the same leak information as shown on Civet. Could you tell me what is the correct way to run valgrind to detect memory leak?

**Comment by brianmoose** [comment]
Civet compiles the "oprof" versions of libmesh and MOOSE for valgrind. Then runs "./run_tests --oprof --valgrind".

**Comment by permcody** [comment]
@jiangwen84 - Let's try to get this fixed as soon as possible. Please stop by if you continue to run into problems locating the problem.

**Comment by permcody** [comment]
@jiangwen84 - I have been unable to plug the XFEM leaks. I have tried several variations of changing those shared pointers to reference and so on. It appears your destructors are getting called so I really don't think that's the problem. I suspect that there you are overwriting a bare pointer somewhere and that's what's getting lost. This may take some time to track down. 

Let me know if you need resources to find the leaks, it's going to take some digging.

**Comment by jiangwen84** [comment]
@permcody  Thanks for looking into this problem.

I made some changes to the XFEM. Before I made the changes, I got ```Memory leak detected!
Compile in DEBUG mode with --enable-reference-counting
for more information```. With the changes, the error is gone. 

I am not sure if this causes the memory leak that is detected by valgrind. I was not able to use valgrind to reproduce the error on my local machine.

**Comment by permcody** [comment]
The libMesh memory leak only finds objects that inherit from the libMesh "reference counting class". It won't detect bare pointer problems. Do you have access to a Linux machine? That's where you'll need to work on this. I used "rod" and was able to obtain similar errors.

**Comment by permcody** [comment]
@bwspenc or @jiangwen84 
The original leak was fixed thank you but then as we discovered last week. It was immediately replaced by a new memory problem which is plaguing our nightly Valgrind Tests. Can we please take care of this soon? Thanks

**Comment by jiangwen84** [comment]
@permcody , I and Ben are on travel this week and I will fix that next week. Thanks.

**Comment by permcody** [comment]
Closed by #7128
