### ISSUE TITLE
New Adaptivity system segfault

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6835]
### Description of the enhancement or error report
Initial Adaptivity in the new adaptivity system triggers a call to `computeProperties` for a material which uses a UserObject. However, this happens before `initialize` has been called on the UserObject.

In initialize I'm setting up a data structure, which needs `_fe_problem.getMaxQps()`. Is it possible to initialize UserObjects before initial adaptivity?

As a "side note": no material properties are needed by the adaptivity calculation, sooo.... why are materials called anyways? I guess there are hypothetical Indicators that might use material properties in the future...
 
### Rationale for the enhancement or information for reproducing the error
Stuff's broken. Add [Adaptivity] to any input file with `DiscreteNucleation`.

### Identified impact
Fixing this would make me happy.

**Comment by friedmud** [comment]
It's more than possible to have an error indicator that uses a material property... think `FluxJumpIndicator`... but I agree this is being a bit overzealous.

The Indicator / Marker systems are some of the last systems to get the "dependency" treatment.  I don't believe that they use any of the infrastructure for turning off variables / Materials that aren't involved in their calculations.  This makes the new Adaptivity system REALLY slow (and causes problems like this one).

**Comment by dschwen** [comment]
> It's more than possible to have an error indicator that uses a material property

So, it's like... Uber-possible?

Anyhow, can't user object initialization just be done earlier?

**Comment by friedmud** [comment]
What if the UserObject needs to know the final number of elements for the
starting mesh?  ;-)

**Comment by dschwen** [comment]
Who would write such a crazy user object?!

**Comment by dschwen** [comment]
Either way, the current way is basically using _uninitialized_ objects. That just sounds wrong.

**Comment by dschwen** [comment]
Gee, I mixed up initialize and initialSetup here 😊. I think I can avoid the issue by initializing the missing parts in the constructor.
