### ISSUE TITLE
--with-metis Causing Build Failure

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6836]
### Description of the enhancement or error report
It's being reported that `--with-metis=PETSc` is causing build failures: https://groups.google.com/forum/#!topic/moose-users/oUSC6UHrC4c

### Rationale for the enhancement or information for reproducing the error
Looks like it probably has to do with older installations of PETSc - or manually compiled versions of PETSc (i.e., not using our package).

### Identified impact
Compile failure

**Comment by friedmud** [comment]
The change came from here: #6791

**Comment by permcody** [comment]
Solved in #6837
