### ISSUE TITLE
New FE Neighbor reinit code leaks

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6839]
### Description of the enhancement or error report

PR #6824 is causing a memory leak in MOOSE

### Rationale for the enhancement or information for reproducing the error

Valgrind tests are failing across the board
https://www.moosebuild.org/job/19529/

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Everything! This is a fixed size leak, but a leak nonetheless.

ping @jiangwen84

**Comment by jiangwen84** [comment]
@permcody  thanks for pointing this out. I will submit a PR to fix it. :-)
