### ISSUE TITLE
Peacock error for single entry MooseEnums

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6844]
### Description of the enhancement or error report

Peacock throws an error:

```
  File "/Users/schwd/Programs/moose/gui/gui/ParamTable.py", line 605, in item_clicked
    options = param['options'].split(' ') if param['options'] != None else ''
AttributeError: 'int' object has no attribute 'split'
```

when trying to open the parameter view for an object that has a `MooseEnum` parameter with only one single value.
### Rationale for the enhancement or information for reproducing the error

It is exotic, but still an error. Single entry `MooseEnum`s should not cause code to crap out.
### Identified impact

Low. I don't think single entry `MooseEnum`s are used anywhere. I stumbled upon this in the development phase of a new class.

**Comment by permcody** [comment]
This issue doesn't affect the new Peacock. Closing.
