### ISSUE TITLE
Initial contribution to PorousFlow module

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6845]
This will be a major commit from our code sprint.  The work is still unpolished, but the functionality is there and it is becoming increasingly difficult to work in this "mega branch" that we have.  It'll be easier once this is merged and we can follow the standard incremental approach with issues+PRs on idaholab/moose.

**Comment by WilkAndy** [comment]
@cpgr - i'm going to close this issue, ok?  we're past the "initial porous flow" contribution now.

**Comment by cpgr** [comment]
👍
