### ISSUE TITLE
Make a moose warnings always warnings

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6846]
### Description of the enhancement or error report
If command line option `--error` is used, all warnings issued by `mooseWarning(msg)` will be treated as errors. If one test has a warning, which can be ignored safely, it still will be treated as an error with `--error`. If we do not supply `--error`, other potential warnings will not be caught by the test harness. So I am suggesting another interface `mooseWarning(msg, always_allowed)`. I could create a new function in my application, but think this could be an reasonable enhancement in framework.

### Rationale for the enhancement or information for reproducing the error
Refer to the above.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New feature. No impact to existing codes.

**Comment by dschwen** [comment]
That would be a `mooseInfo` rather than a `mooseWarning`. I would find it confusing if we overloaded the semantics of _warnings_.

**Comment by YaqiWang** [comment]
I agree, how about this:

```
#define mooseInfo(msg)                                                  \
  do                                                                    \
  {                                                                     \
    static bool did_this_already = false;                               \
    if (!did_this_already)                                              \
    {                                                                   \
      did_this_already = true;                                          \
      {                                                                 \
        std::ostringstream _warn_oss_;                                  \
                                                                        \
        _warn_oss_                                                      \
          << (Moose::_color_console ? YELLOW : "")                      \
          << "\n\n*** Info ***\n"                                       \
          << msg                                                        \
          << "\nat " << __FILE__ << ", line " << __LINE__               \
          << (Moose::_color_console ? DEFAULT : "")                     \
          << "\n\n";                                                    \
        Moose::err << _warn_oss_.str() << std::flush;                   \
      }                                                                 \
    }                                                                   \
  } while (0)
```
It always be an info and always be outputted once.

**Comment by permcody** [comment]
@YaqiWang - I think if you design your tests correctly this really shouldn't be an issue in practice. You said you are concerned about the case where you set `allow_warnings` on a test because you have an expected warning but are concerned that other unexpected warnings will sneak through. While this is indeed possible it seems like you could use the `absent_out` parameter or just create additional tests to verify that you are hitting one warning and not another. I'd rather not add this macro unless there are good compelling reasons to do so. I'm willing to put this up for a vote.

**Comment by YaqiWang** [comment]
How do we cast the vote here? I can quickly send in a PR if people think it is good. Otherwise I can put this under my app.

**Comment by permcody** [comment]
I still argue that's it's unecessary. 
@idaholab/moose-developers - please comment

**Comment by andrsd** [comment]
I am fine with `mooseInfo`.

**Comment by jwpeterson** [comment]
I think there's a compelling reason to have a macro that prints something only once that is not necessarily a warning.  In fact it should probably *not* be used for warnings, so `mooseInfo` is a good name.  You could possibly even implement it in terms of the `libmesh_do_once` macro, which handles all the `static bool` stuff for you...

**Comment by aeslaughter** [comment]
This idea goes along with this #3808, which will be easier to implement
after I do #5011 and what is talked about here
<https://github.com/idaholab/moose/pull/6354#issuecomment-186004480>.
