### ISSUE TITLE
Thermal strain calculation descrepancy between Tensor and Solid Mechanics

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#6848]
### Description of the enhancement or error report
In a purely thermal loading elasticity problem (fixed displacements on one end, loaded with a thermal gradient on two other sides), tensor mechanics and solid mechanics do not give the same solutions for displacements, ect:
*Solid Mechanics:*
```
      the value of the strain increment before thermal additions is
      increment_strain (0,0) -0
      increment_strain (1,1) -0
      increment_strain (2,2) -0
      increment_strain (0,1) -0
      increment_strain (0,2) -0
      increment_strain (1,2) -0
  where the temperature is 0.788675
      and the old temperature is 0.5
 and after the thermal strains is removed:
      increment_strain (0,0) -0.0057735
      increment_strain (1,1) -0.0057735
      increment_strain (2,2) -0.0057735
      increment_strain (0,1) -0
      increment_strain (0,2) -0
      increment_strain (1,2) -0
```

*Tensor Mechanics:*
```
the value of the strain increment before thermal additions is
      increment_strain (0,0) 0
      increment_strain (1,1) 0
      increment_strain (2,2) 0
      increment_strain (0,1) 0
      increment_strain (0,2) 0
      increment_strain (1,2) 0
  where the temperature is 0.788675
      and the old temperature is 0
 and after the thermal strains is removed:
      increment_strain (0,0) -0.0157735
      increment_strain (1,1) -0.0157735
      increment_strain (2,2) -0.0157735
      increment_strain (0,1) 0
      increment_strain (0,2) 0
      increment_strain (1,2) 0
```

### Rationale for the enhancement or information for reproducing the error
Tensor mechanics does not include a `stress_free_temperature` term, which solid mechanics uses as an initial temperature for the first time step only.  Tensor mechanics does include a reference temperature term, ```temperature_ref``` but does not handle this term in the same manner as solid mechanics.

In solid mechanics, the thermal strain is calculated as
```
    if (_t_step == 1 && _has_stress_free_temp)
      inc_thermal_strain = (current_temp - stress_free_temperature) * alpha;
    else
      inc_thermal_strain = (current_temp - temperature_old) * alpha;
```
Where as in finite strain tensor mechanics, the thermal strain is always calculated as
```
    _strain_increment[_qp].addIa(-_thermal_expansion_coeff * (_T[_qp] - _T_old[_qp]));
```
and in small strain tensor mechanics, the thermal strain is calculated as
```
  _mechanical_strain[_qp].addIa(-_thermal_expansion_coeff*( _T[_qp] - _T0 ));
```
where ```_T0``` by default is 273 in tensor mechanics while in solid mechanics ```stress_free_temperature``` is 0. by default.

### Identified impact
The stress free temperature term should be implemented into the finite strain tensor mechanics so that the simple thermal loading problem solutions agree; the total strain form of the small strain in tensor mechanics will need to be verified.

It also seems prudent to discuss the forced use of Kelvin for temperature units in tensor mechanics with the default:  @bwspenc @dschwen how do you feel about changing the default from 273 to 0 so that we don't force the use of units of Kelvin by default?

**Comment by dschwen** [comment]
This can all be done with CompositeEigenstrain now.

**Comment by sapitts** [comment]
@dschwen, I've taken a look at CompositeEigenstrain, and that class, for lack of better words, appears to do 'too much.'  In particular, needing to define a separate identity tensor in the input file so that I can multiply said identity tensor by ```alpha * delta_temperature``` seems excessive.  The required weight param could handle the thermal expansion alpha, yet I'd prefer to have the term thermal_expansion directly in the input file for clarity.  ComputeVariableBaseEigenStrain and ComputeVariableEigenStrain also require a tensor name as input.  I'm working with the idea of creating a new class, similar to ComputeVariableBaseEigenStrain, that inherits from ComputeStressFreeStrainBase to run the simple thermal expansion calculation, and I'd appreciate your insights on the potential problems with this approach.

On the topic of ComputeStressFreeStrainBase, could we set this class up to automatically determine if the incremental form is used or not, e.g. with a ```hasMaterialProperty<RankTwoTensor>(_base_name + "strain_increment"))``` check to set the bool incremental_form in the constructor?  This check would slightly mitigate the need for users to set as many parameters in the input file, usw.

Tagging @jasondhales since he will use the thermal strain calculation to hook into matpro in Bison.

**Comment by dschwen** [comment]
Yeah, I agree, a more focussed capability than CompositeEigenstrain could be useful. Let's talk next week (I'm on travel). hasMaterialProperty is problematic and cannot be used in material constructors (it makes them construction order dependent!).
