### ISSUE TITLE
Let app.mk accept a list of excluded source files

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6867]
### Description of the enhancement or error report
This is needed in case users want to override the default rule on compiling the source file for a particular source file and do not want to have the default rule conflicts with the added rule.

### Rationale for the enhancement or information for reproducing the error
This could be useful for optional compiling.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New feature not impact to existing system.

**Comment by permcody** [comment]
Closed by #6868
