### ISSUE TITLE
NumDofs only reports combined systems DOFs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6870]
### Description of the enhancement or error report

Right now the NumDOFs Postprocessor only reports all DOFS (both Aux and NL). It really should report NL for a wide variety of problems. I'm proposing adding an option to report NL, AUX or ALL.

### Rationale for the enhancement or information for reproducing the error

Scaling should be based on NL Dofs not ALL

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact, NumDOFs will retain the same behavior for backwards compatibility.

**Comment by friedmud** [comment]
Depends on what you're scaling! AuxDofs might contribute a LOT to the
overall solve time...

**Comment by permcody** [comment]
It might, now we have options. The old behavior is the default.

**Comment by friedmud** [comment]
Don't get me wrong... I like the new capability! Just pointing out that you
may want to consider timing the Aux system as well for scaling studies.
