### ISSUE TITLE
Improve robustness of return mapping iterations

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#6873]
### Description of the enhancement or error report

The return mapping iterations in all of the creep and plasticity models have been a longstanding source of problems. There are many cases in which the residual in the material solve oscillates between two values and convergence is not achieved in the maximum number of iterations.
### Rationale for the enhancement or information for reproducing the error

Many BISON problems fail due to reaching the maximum creep iterations.
### Identified impact

All models in solid_mechanics that derive from ReturnMappingModel, other older models, return mapping models in tensor_mechanics

**Comment by tophmatthews** [comment]
Whats the status on the tensor mechanics move? I have some things that depend heavily on creep, and I wonder if this may help.

**Comment by bwspenc** [comment]
@tophmatthews It's in progress as we speak. I'm optimistically hoping we're less than a week away on it.

**Comment by tophmatthews** [comment]
You guys are quick! Nice job Stephanie

**Comment by permcody** [comment]
@sapitts, @bwspenc, Here's an old ticket with several merged PRs. Should it be closed?

**Comment by sapitts** [comment]
@permcody I've got one lingering issue in BISON with a restart examples problem that started with the return mapping in tensor mechanics to fix before this issue can be completely closed.

**Comment by dschwen** [comment]
Arguably the robustness has been improved. I'm closing the two year old ticket. If there are still issues please open a more specific ticket.
