### ISSUE TITLE
PorousFlowTask: combine CapillaryPressureVG and EffectiveSaturationVG

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6878]
For discussion with @cpgr (and, do you think you could do this if you think it's a good idea, @cpgr ?).  Some ideas:

(1) I think these two utils should be combined into PorousFlowVG.

(2) I think the self functions should be a function of capillary pressure: at the moment they are functions of pore pressure (= - cap pressure) - see comments in the .h file

(3) There should be an inverse of the effectionSaturation(s, sat_r, sat_s) function.  The inverse will provide saturation as a function of effective saturation.

(4) The self, dseff, d2seff should have the same interface as the capillaryPressure(...) functions, with p0 and pc_max.

(5) Of course there won't be exact inverses (e.g., for pc>pc_max)

Any other ideas?

a

**Comment by cpgr** [comment]
I think combining them is a good idea. I'll clean this to make the interface consistent

**Comment by WilkAndy** [comment]
Possibly it would be easiest to wait till the PR is been accepted.  I think @dschwen has thoroughly read the code and is probably just waiting till monday to merge the PR.

**Comment by WilkAndy** [comment]
Hey, also, i wonder whether it'd be good to put the VG relative permeabilities in here too.  I know they're not capillary pressures, but they are related and they're often used together and they appeared in VG's original paper as a set.  What do you reckon?

**Comment by WilkAndy** [comment]
@cpgr - are you keen to do this?

**Comment by cpgr** [comment]
Yep, but just been flat out on other projects so haven't had a chance

**Comment by WilkAndy** [comment]
yea, same here,

a

**Comment by WilkAndy** [comment]
This is done by #8074
