### ISSUE TITLE
Add docs on Adaptive Mesh Refinement

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6907]
### Description of the enhancement or error report

No docs on AMR can be found on the wiki through a search for "AMR" or "adaptive".

People struggle with this feature.

**Comment by dschwen** [comment]
I'm adding documentation tickets as hackathon participants report the issues they had with MOOSE.

**Comment by friedmud** [comment]
Maybe search for "adaptivity"?

http://mooseframework.org/wiki/MooseTraining/Adaptivity/

**Comment by dschwen** [comment]
Or add more keywords to make the existing docs more discoverable...
