### ISSUE TITLE
Extra adaptivity happening at end of simulation

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6913]
### Description of the enhancement or error report

It turns out that when you have adaptivity turned on. The simulation finishes with an adaptive step instead of quitting after a final solve. This can be rather expensive and is wasteful.
### Rationale for the enhancement or information for reproducing the error

Small harmless bug but can be expensive
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This shouldn't impact applications because we don't do anything with the adapted mesh.

**Comment by jessecarterMOOSE** [comment]
+1 to this. Ending with an adaptivity step may be useful if you plan to do restart, but in those cases you would just have to remember to apply some initial adaptivity.

**Comment by permcody** [comment]
Right, we aren't saving the mesh or doing anything with the adapted
solution to the best of my knowledge. We just need to terminate slightly
earlier.

**Comment by lindsayad** [comment]
This was reportedly closed by #12930 (which accidentally referenced the original PR meant to address this issue that didn't get merged, and not the actual issue itself)
