### ISSUE TITLE
Verify and Test ActionWarehouse::getActions<T>()

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#6921]
### Description of the enhancement or error report

If we remove the existing (and broken) PrintMaterials test. We may need a new test for this method.
### Rationale for the enhancement or information for reproducing the error

The existing test is broken (sorts on pointers which is unreliable).
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Rattlesnake could be impacted if this method changes without a test in MooseTest.

**Comment by YaqiWang** [comment]
I should be against the PR and take this issue more seriously. Now I am getting the consequence. A proper fix is submitted in #7906.

**Comment by permcody** [comment]
Closed by #7906.
