### ISSUE TITLE
Several modules tests failing with PETSc 3.7.0

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#6924]
The following modules tests are failing for me with the new version of PETSc:
```
xfem:single_var_constraint_2d.stationary_jump_fluxjump...................................... FAILED (EXODIFF)
xfem:single_var_constraint_3d.stationary_jump_fluxjump_3d................................... FAILED (EXODIFF)
richards:buckley_leverett.bl20.............................................................. FAILED (EXODIFF)
combined:poro_mechanics.selected_qp.......................................................... FAILED (ERRMSG)
combined:contact_verification/patch_tests/cyl_1.mu_0_2_kin................................... FAILED (ERRMSG)
richards:gravity_head_2.gh01................................................................ FAILED (CSVDIFF)
richards:gravity_head_2.gh02................................................................ FAILED (CSVDIFF)
richards:gravity_head_2.gh04................................................................ FAILED (CSVDIFF)
richards:gravity_head_2.gh_fu_02............................................................ FAILED (CSVDIFF)
combined:contact_verification/patch_tests/brick_3.glued_kin................................... FAILED (CRASH)
combined:contact_verification/patch_tests/brick_3.mu_0_2_kin.................................. FAILED (CRASH)
combined:generalized_plane_strain_tm_contact.generalized_plane_strain_tm_contact_field........ FAILED (CRASH)
```

I think some of these are failing because PETSc's NaN handling during residual computations changed somehow (or at least the way we interact with it changed).  For example, all of the Richards ones listed now fail with something like this:
```
richards:gravity_head_2.gh01:
  0 Nonlinear |R| = 9.708939e-02
       0 Linear |R| = 9.708939e-02
       1 Linear |R| = -nan
 Aborting as solve did not converge
```

On the other ones, I have less of an idea what's going on, for example, combined:contact_verification/patch_tests/brick_3.glued_kin just segfaults.

So I really need the test creators' help tracking down the issue... Tagging @bwspenc for xfem tests, @WilkAndy for Richards and poro_mechanics, @acasagran for contact_verification, @dscwhen for possible help with the plane strain one.  I have output

**Comment by jwpeterson** [comment]
I have output from opt runs if you would like that, working on getting dbg output now...

**Comment by jwpeterson** [comment]
One plan is to have Jason release a new package with PETSc 3.7.0 in it as a (non-default) module... that might help you guys in taking a look at the tests which are failing.

**Comment by bwspenc** [comment]
It doesn't surprise me that those xfem tests fail. They failed for me just yesterday when I made a change that shouldn't have affected anything. They introduce a flux jump across the interface, and the behavior depends completely on which element gets picked to be on a certain side of the interface. It turns out that we need more infrastructure to support that particular form of the constraint. I can submit a PR to skip them, or if it's easier, you can just skip them.
If we can have a package that makes it easy to test with PETSc 3.7.0, that will make it a lot easier to sort out the issue with the contact tests.

**Comment by WilkAndy** [comment]
Thanks @jwpeterson  - i'll look at the richards ones and the poro-mechanics.  exactly this thing has occurred previously (with linear=nan) because of my use of bjacobi+bcgs.  when i change to asm+gmres (or something similar - can't remember exactly), the problem went away.

**Comment by WilkAndy** [comment]
@jwpeterson - do you think you could run the heavy tests - some of them might fail too.  If you could spend time trying to track down what the root cause is of course i'd be very appreciative.  While it is probably not my fault there's always a niggling fear that my code is buggy.

**Comment by WilkAndy** [comment]
By the way, i'd quite like another mac package with PETSc 3.7.0.  Or some script i could run that would magically update PETSc.

**Comment by acasagran** [comment]
John,

I looked at the contact tests that are failing. It seems they start
iterating and one even converges a few steps, but then they start cutting
back the time step size and eventually die when dt < dt_min. They all use
SuperLU, so it may be something with a new version of it in 3.7.0?

Al

On Sat, May 7, 2016 at 10:09 PM, Andy Wilkins <notifications@github.com>
wrote:

> By the way, i'd quite like another mac package with PETSc 3.7.0. Or some
> script i could run that would magically update PETSc.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_6924-23issuecomment-2D217690273&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=7dl5mmxY7tEur-NcOi1JvXVPPFVUTuo7dvlJihuaL_U&m=-EZIw1T88B4mDAgpN5g3-2EieQesfqAGzrQKsA-Fhho&s=GzVBWISYj-s7pJEeOYzpFPBSLYavAg2bLck28RDYckk&e=>
>



-- 
Al Casagranda
Fuels Modeling and Simulation
Idaho National Laboratory
P.O. Box 1625
Idaho Falls, ID  83415-3840
208-526-7424

**Comment by jwpeterson** [comment]
Just a small update on this: all the failures seem to be related to having SuperLU.  I built a PETSc 3.7.0 without that, and all of the modules tests passed for me...

**Comment by permcody** [comment]
@fdkong - This ticket may be of interest to you. I don't know if the issues reported here are still accurate or if some of them have been fixed.
