### ISSUE TITLE
MooseError contains a legacy workaround that hurts ccache performance

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6930]
### Description of the enhancement or error report
Remove code that should have been remove with the merge of libmesh/libmesh#415

### Rationale for the enhancement or information for reproducing the error
The old code introduces `__TIME__` and `__DATE__` macros, even if they had been disabled at libmesh configure time.

### Identified impact
Should speed up compile times by improving ccache utilization.

**Comment by dschwen** [comment]
@permcody, just to clarify `__LIBMESH_TIME__` is defined _nowhere_ in libmesh (maybe the name of that macro changed?). As a consequence `__TIME__` was used in `MooseError`, which invalidates ccache.

**Comment by jwpeterson** [comment]
> On May 10, 2016, at 11:11 AM, Daniel Schwen <notifications@github.com> wrote:
> 
> @permcody, just to clarify __LIBMESH_TIME__ is defined nowhere in libmesh (maybe the name of that macro changed?). As a consequence __TIME__ was used in MooseError, which invalidates ccache.
> 

It changed to LIBMESH_TIME since double leading underscore tokens are technically reserved for the C/C++ library implementers.
