### ISSUE TITLE
PorousFlow base level 2 material

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6938]
@dschwen points out that

if (_phase_num >= _dictator_UO.numPhases())

is called a lot in the level2 materials.  He suggests having a base class that holds _phase_num and does the check once.  Let's do this once the backlog is merged, @cpgr .

**Comment by cpgr** [comment]
Could probably implement this in the constructor for PorousFlowFluidPropertiesBase that all of the fluid materials inherit from already? This is where _phase_num is read in from the input file

**Comment by cpgr** [comment]
But it is also called in rel perm materials, so probably want a base class for the base class for all of these materials!

**Comment by WilkAndy** [comment]
Yes, i think you're right, @cpgr (base class for base class).  I don't want to do this right now because once everything is merged it'll be clearer exactly where to do it, and also we'll be able to more easily re-factor when we've got our test suite merged.

**Comment by cpgr** [comment]
Agree - lets leave it until then

**Comment by dschwen** [comment]
:+1:

**Comment by WilkAndy** [comment]
Also

If PorousFlowFluidPropertiesBase inherited from the base class I suggested above you could also have a string member _phase that contains the stringified phase number. That would get rid of the twenty Moose::stringify calls.

**Comment by cpgr** [comment]
Have you started this @WilkAndy? If not, I'll do it now

**Comment by WilkAndy** [comment]
No, i haven't started.  i'm working on something else (not porous flow) presently,

a

**Comment by cpgr** [comment]
I've finished this, but will wait until #7010 is merged before I submit a PR so that I don't reintroduce the UO in the dictator name

**Comment by WilkAndy** [comment]
Hey, that's cool, thanks @cpgr .   I'm really enjoying this collaboration.
