### ISSUE TITLE
PorousFlow rename internal parameter _dicatator_UO to _dictator

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6939]
Suggested by @dschwen.  This will be easier to do when the backlog of PRs is merged.

**Comment by dschwen** [comment]
Actually I was talking about the name of the input parameter.

**Comment by WilkAndy** [comment]
OK.  Especially relevant here as there is only ONE dictator!   And even if there were other dictators, surely they must all be UserObjects.

Col Gaddafi: Hey guys I don't want to be a Problem anymore.
NATO: We're Actions and we say you're a Problem, and we're going to Postprocess you with our Materials and our AuxKernels.  Gaddafi << ProcessTerminate
Terminator and PorousFlowDictator: Nothing will destroy us because we're UserObjects.  std::cout << EvilLaughter

I think i'm going crazy.
