### ISSUE TITLE
Enable checking that number of nodes equals number of quadpoints

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6940]
### Description of the enhancement or error report

Most of our PorousFlow Materials and Kernels assume that for each element the number of quadpoints equals the number of nodes.  The Materials, for instance, store nodal information in data structures referenced by _qp, and the Kernels use those, implicitly or explicitly using _i = _qp.

Currently we don't check this assumption.  If possible i'd like to make the check in our PorousFlowDictator GeneralUserObject since all PorousFlow simulations must have that UserObject.

@permcody mentioned that at the start of each simulation there is a loop over the mesh to size various things (MaxQps), and at the same time stuff could be stored to facilitate this check.

### Identified impact

It makes our code more robust.

**Comment by WilkAndy** [comment]
I get the feeling this is just going to languish here for a while.

**Comment by permcody** [comment]
Yeah it is, I'm swamped. Do you want to take a crack at it? I can guide you through. Basically we just need to store off another member or members for the other information you need (max nodes?). We already have this MaxQps loop. MIght as well make it do double-duty. That's really all there is to it.

**Comment by WilkAndy** [comment]
This issue has become redundant.

In PR #7362 I have added a PorousFlowNodeNumber Material that must be used with all PorousFlow simulations.  It checks that number quadpoints >= number nodes, for all elements with _bnd = false.  If that check is satisfied, then there are enough quadpoints in the element to store the nodal information, and all Kernels will work fine.

For _bnd=true elements, the PorousFlow Materials still store nodal information at quadpoints, and the PorousFlowNodeNumber Material dictates which nodal info gets stored at which quadpoint (it is the nearest node to the quadpoint).  That is then used by BCs.
