### ISSUE TITLE
Stress Divergence kernel used_displaced_mesh default

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#6947]
### Description of the enhancement or error report ###
For most continuum mechanics calculations, the divergence of the stress equation  ( \nabla \sigma = 0 ) should be performed on the displaced mesh / in the current configuration.  Despite this expectation, the default setting in the Tensor Mechanics Stress Divergence kernel is 
``` params.set<bool>("use_displaced_mesh") = false; ```

### Information for reproducing the error
This default setting to use the undeformed mesh will give incorrect results for the majority of tensor mechanics problems.  @jasondhales has noted that the error is large enough to fail exodiff when pressure boundary conditions are applied but not displacement boundary conditions when compared to analogous solid mechanics problems.

### Identified impact
For the majority of the mechanics calculations, this change will simplify input files; however, the default change may adversely impact some phase field calculations, and the default change will impact crystal plasticity simulations which rely on the PK1 stress.  @tonkmr and @cpritam, please weigh in.

**Comment by mangerij** [comment]
Is there any word on why this was ever put in? 

I would have thought that the default was using the displaced mesh. I'm a bit confused, wouldn't this have immediately broken some tests?

FYI it changed [here](https://github.com/cpritam/moose/commit/6887ecb4ec8cbe26755f03095f969f5f1b6648f8).

**Comment by YaqiWang** [comment]
wow, I just noticed this. In solid_mechanics module, this kernel is indeed working on the displaced mesh by default.

**Comment by sapitts** [comment]
I believe Pritam is back from travel this week; hopefully he can weigh in on why the original change was made and what precautions I should take in changing the use_displaced_mesh flag back to true.

**Comment by cpritam** [comment]
For consistency, any test with small strain definition should have
use_displaced_mesh = false and anything with large deformation (includes
crystal plasticity) should have it true. The default settings are different
between stress divergence kernel and pressure bc, which to avoid confusion,
should atleast be same.

**Comment by sapitts** [comment]
I've talked with @jiangwen84 about the pressure bc and the need to keep the default `use_displaced_mesh = true` so that the pressure follows the surface.  

Is there a way to set the 'use_displaced_mesh' option based on whether incremental or small strains are used @dschwen ?

**Comment by jasondhales** [comment]
It seems like the default should be to use the displaced mesh.  At least in
Bison, the vast majority of analyses involve significant displacement and
the need for the pressure bc to work properly in those conditions.  If a
problem is truly small strain, it shouldn't matter, but of course a user
could switch to using the undisplaced mesh if desired.

On Wed, May 25, 2016 at 10:56 AM, Stephanie Pitts <notifications@github.com>
wrote:

> I've talked with @jiangwen84
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jiangwen84&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=cqXvGbX-7b94Z6fBUIS3stlC4MvE-cc8uJIzR4pfcdI&s=iKz64I1_jZsdJ8gBagPRYgJqgmDA38y7InVKK12JN6Q&e=>
> about the pressure bc and the need to keep the default use_displaced_mesh
> = true so that the pressure follows the surface.
>
> Is there a way to set the 'use_displaced_mesh' option based on whether
> incremental or small strains are used @dschwen
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dschwen&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=cqXvGbX-7b94Z6fBUIS3stlC4MvE-cc8uJIzR4pfcdI&s=YcAlVt8JmfaV-69yC6EyIjC9sQl9VS1BbMJ0ywrOI20&e=>
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_6947-23issuecomment-2D221635535&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=cqXvGbX-7b94Z6fBUIS3stlC4MvE-cc8uJIzR4pfcdI&s=I8ZM47VuLvhkjtz_raQSihf2eiAGUN5FOC5aPmBM8ls&e=>
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by friedmud** [comment]
Maybe just throw an error if you're doing small strain with the displaced
mesh?
