### ISSUE TITLE
VectorPostprocessor for texture analysis of grain systems.

### ISSUE THREAD

**Issue by jhbradley** [idaholab/moose#6952]
### Description of the enhancement or error report
In order to do texture analysis on grain boundary networks produced in simulations, it is necessary to know the Euler angles and grain number at each grid coordinate.

### Rationale for the enhancement or information for reproducing the error
There is currently no Postprocessor that can pull this information out of the phase field simulations.

### Identified impact
None.

**Comment by dschwen** [comment]
So why not use AuxVariables for that?

**Comment by jhbradley** [comment]
The vpp provides a simple way to match grid coordinates to the grain number, etc., with the csv output which makes it easy to use to create an input file for 3rd party analysis software. Take a look when I push my initial commit to see if you think it would be better to bypass the vpp altogether and just do it with AuxVars.

**Comment by permcody** [comment]
@jhbradley - you also mentioned that you needed fixed width cells for your 3rd party reader. AuxVars won't handle that well.

**Comment by jhbradley** [comment]
That is correct. The coordinates in the output need to be uniformly spaced, almost identical to an EBSDReader input file.

**Comment by dschwen** [comment]
So this is for a third party software? Dream3D? This is useful information (one reason such a discussion should not be held in three different places, but _only right here_)

**Comment by jhbradley** [comment]
Right. DREAM.3D.

**Comment by dschwen** [comment]
Then I suggest a VPP that takes an EBSDReader user object as a parameter to obtain the underlying grid. We could even think about writing a DREAM.3D output module.

**Comment by jhbradley** [comment]
The VPP is already written, so what do you say if I push it and we can talk about modifications?

**Comment by dschwen** [comment]
Yes, **of course** push it!

**Comment by jhbradley** [comment]
The code is up if you want to take a look at it @permcody and @dschwen  before I go as far as making a test.

**Comment by jhbradley** [comment]
I accidentally pushed the above changes to the branch textureVpp_6952 instead of textureVPP_6952. Let me know if there is some reason for me to correct that and push it to the branch it was on previously.

**Comment by dschwen** [comment]
If you push to the wrong branch it does not show up in the PR. You should really have set the push default to "simple". That avoids these mishaps!

**Comment by jhbradley** [comment]
It has been fixed.

**Comment by jhbradley** [comment]
Reopen issue to add a test for the new VPP.
