### ISSUE TITLE
A bug in Density?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6954]
### Description of the enhancement or error report
Looks like there is a bug in `Density` on line 39. `disp_r` is coupled in only in RZ geometry, which should be coupled in both RZ and SphericalR.
https://github.com/idaholab/moose/blob/devel/modules/misc/src/Density.C#L39

### Rationale for the enhancement or information for reproducing the error
Need original developer @jasondhales to confirm this.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact at this moment which means the code is not fully covered by the regression.

**Comment by jasondhales** [comment]
Yes, that looks like a bug.  _disp_r should be set to
coupledValue("disp_r") for either RZ or spherical.  Want me to fix it?

On Tue, May 10, 2016 at 4:30 PM, Yaqi <notifications@github.com> wrote:

> Description of the enhancement or error report
>
> Looks like there is a bug in Density on line 39. disp_r is coupled in
> only in RZ geometry, which should be coupled in both RZ and SphericalR.
> https://github.com/idaholab/moose/blob/devel/modules/misc/src/Density.C#L39
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_blob_devel_modules_misc_src_Density.C-23L39&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=ehMtUPUdZrpIlwhYjBGpUD78GnL-d7MZHye2vSTk-o0&s=kBJFbd8-t9Va_fx3JXd-pGvDjepRSAN2u0s0xnhTugA&e=>
> Rationale for the enhancement or information for reproducing the error
>
> Need original developer @jasondhales
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasondhales&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=ehMtUPUdZrpIlwhYjBGpUD78GnL-d7MZHye2vSTk-o0&s=-8o9oRhgmuHb_KtWSLd0s07naLHxzkdMZYRzLYOZMTc&e=>
> to confirm this.
> Identified impact
>
> (i.e. Internal object changes, limited interface changes, public API
> change, or a list of specific applications impacted)
> N/A
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_6954&d=BQMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=ehMtUPUdZrpIlwhYjBGpUD78GnL-d7MZHye2vSTk-o0&s=C6Xy5tp8hFzIm7a3-GE9QU0if4o6MPpqbOvAt24eW5s&e=>
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by YaqiWang** [comment]
Yes. Thanks!
