### ISSUE TITLE
Moose modules does not compile with 64-bit

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#6959]
### Description of the enhancement or error report
If libMesh is configured with `--with-dof_id_bytes=8`, you will see errors during compiling modules.

### Rationale for the enhancement or information for reproducing the error
This prevents us from compiling mammoth with 64-bit.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Applications need 64-bit.

**Comment by permcody** [comment]
Which module?

**Comment by jwpeterson** [comment]
This might be pretty easy to fix, if you post the error messages here?

**Comment by YaqiWang** [comment]
Sorry, I do not know. Ben Baker did the compiling, we just know somewhere `dof_id_type` should be used but now `unsigned int`.

**Comment by friedmud** [comment]
This support is going to be important for me in the near future as well...
along with subdomain IDs needing to be larger than shorts. Perhaps we need
a test target that exercises these extended types...
