### ISSUE TITLE
Reassign Subdomain Mesh Modifier

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6965]
### Description of the enhancement or error report
Need a `MeshModifier` for reassigning subdomain IDs

### Rationale for the enhancement or information for reproducing the error
Would be useful

### Identified impact
Another `MeshModifier`

**Comment by permcody** [comment]
If you are just looking for something quick and dirty you can use the
libMesh utility to do this for you. It's one of the binaries that's built
when you compile libMesh.

**Comment by friedmud** [comment]
Already done: https://github.com/idaholab/moose/blob/devel/framework/src/meshmodifiers/RenameBlock.C
