### ISSUE TITLE
C++11 Lambda Spacing

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#6967]
### Description of the enhancement or error report
We need to decide how we're going to space lambda functions.  I propose this (from my recent failed PR: #6966 ):

```C++
Threads::parallel_for(elem_range,
                      [&](const ElemRange & elem_range)
                      {
                        auto block_map_end = _block_map.end();

                        for (auto & elem : elem_range)
                        {
                          auto & sid = elem->subdomain_id();

                          auto entry = _block_map.find(sid);

                          if (entry != block_map_end)
                            sid = entry->second;
                        }
                      });
```

### Rationale for the enhancement or information for reproducing the error
The lambda is an argument to `parallel_for` therefore it should be spaced over just like any other argument.  Also: Emacs will automatically space things out this way... so that's useful.

### Identified impact
None since we don't have any of these in MOOSE yet ;-)

**Comment by jwpeterson** [comment]
This is currently being discussed in #6993.
