### ISSUE TITLE
Remove disp_x, disp_y, disp_z from TensorMechanicsMaterial

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6973]
### Description of the enhancement or error report

TensorMechanicsMaterial still has disp_x, disp_y and disp_z in it.  Quite a long time ago we purged the rest of TensorMechanics in favour of the vector "displacements".  I'd like to do this for TensorMechanicsMaterial too.

### Rationale for the enhancement or information for reproducing the error

Makes TensorMechanics tidier.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This is what concerns me.  Within the tensor_mechanics module there are only a few classes that inherit from TensorMechanicsMaterial, but what about external apps?  I don't really want to bother doing this only to find an external app fails.

**Comment by dschwen** [comment]
Tensor mechanics should be even tidier if we just removed
TensorMechanicsMaterial. I think the only thing still using it is the
Cosserat stuff, for all other things we moved on to the plug and play
system.

**Comment by WilkAndy** [comment]
Well i am planning to remove that dependence from Cosserat in the next round of refactoring (i'll be working on cosserat quite a lot in the coming months).  BUT, FiniteStrainMaterial inherits from TensorMechanicsMaterial, and FiniteStrainCrystalPlasticity, FiniteStrainPlasticBase and 2 others inherit from that.  So it looks like TensorMechanicsMaterial is quite integral to the whole system (?)

**Comment by WilkAndy** [comment]
Any comments, @sapitts , @tonkmr ?

**Comment by sapitts** [comment]
@cpritam and @jiangwen84 did a bunch of work recently on the crystal plasticity code; would either of you like to weigh in on the pros/cons of removing TensorMechanicsMaterial and FiniteStrainMaterial?  For once, I'm with Daniel on removing TensorMechanicsMaterial -- we've already got so many options in tensor mechanics that allowing an old 'non plug-and-play' class to hang around will only create more user confusion.  

There was some traffic in the last few months about crystal plasticity on the moose-users list, and I'm not sure how to manage the deprecation of the crystal plasticity code.  If I can get approval, I'd be glad to work with Pritam and Wen on migrating the crystal plasticity code from FiniteStrainMaterial to the Compute\*Strain and Compute\*Stress materials.

**Comment by jiangwen84** [comment]
@sapitts Thanks. I think the ```FiniteStrainUObasedCP``` should be fine because it derives from ```ComputeStressBase``` and maybe we should do something for ```FiniteStrainCrystalPlasticity``` and ```FiniteStrainCPSlipRateRes```. What do you think @cpritam ?

**Comment by cpritam** [comment]
It shouldn't be a big change in the code. Deformation gradient and
elasticity tensor now have to be fetched from the corresponding materials.
There are a bunch of tests that have to be changed, both in MOOSE and
Grizzly.

**Comment by WilkAndy** [comment]
The effects of removing TensorMechanicsMaterial are:

(1) a re-write of Cosserat stuff is necessary. 

(2) LinearElasticMaterial will no longer work.  It is used in /modules/tensor_mechanics/tests/linear_elastic/tween.i
 
(3) FiniteStrainMaterial will no longer work.  It is not used in any tests, but means the following won't work:

(4) FiniteStrainCrystalPlasticity - used in lots of tests in modules/tensor_mechanics/tests/crystal_plasticity

(5) FiniteStrainCPSlipRateRes - used in tests in modules/tensor_mechanics/tests/cp_slip_rate_integ

(6) FiniteStrainElasticMaterial won't work.  It is used in quite a few tests

(7) ElementPropertyReadFileTest won't work.  It is used in modules/tensor_mechanics/tests/elem_prop_read_user_object

(8) FiniteStrainPlasticMaterial won't work.  It is used in modules/tensor_mechanics/tests/auxkernels/ranktwoscalaraux.i  modules/tensor_mechanics/tests/auxkernels/principalstress.i  modules/tensor_mechanics/tests/j2_plasticity/tensor_mechanics_j2plasticity.i

(9) FiniteStrainRatePlasticMaterial won't work.  It is used in modules/tensor_mechanics/tests/rate_plasticity/tensor_mechanics_rate_plasticity.i

(10) FiniteStrainPlasticBase won't work.  It is a base-class and not used directly in any tests

(11) FiniteStrainMohrCoulomb won't work.  It is used in modules/tensor_mechanics/tests/mohr_coulomb/small_deform1.i

I'm going to work on (1), (10) and (11) over the next week.  I don't think i created any of the remainder, so am a bit hesitant just to delete everything!!

**Comment by dschwen** [comment]
2) tween.i is just left as an example for a before and after when
transitioning to the new system. It is not run by the test harness.
LinearElasticMaterial is used nowhere else and I wrote a wiki page
explaining how to replace its usage.

**Comment by WilkAndy** [comment]
ah, now i understand the "tween" name.  i've been intrigued for some time....

**Comment by sapitts** [comment]
I'll work on (6) and (8) next week.

**Comment by WilkAndy** [comment]
- [ ] a re-write of Cosserat stuff is necessary.

- [ ] LinearElasticMaterial will no longer work. It is used in /modules/tensor_mechanics/tests/linear_elastic/tween.i

- [ ] FiniteStrainMaterial will no longer work. It is not used in any tests, but means the following won't work:

- [ ] FiniteStrainCrystalPlasticity - used in lots of tests in modules/tensor_mechanics/tests/crystal_plasticity

- [ ] FiniteStrainCPSlipRateRes - used in tests in modules/tensor_mechanics/tests/cp_slip_rate_integ

- [ ] FiniteStrainElasticMaterial won't work. It is used in quite a few tests

- [ ] ElementPropertyReadFileTest won't work. It is used in modules/tensor_mechanics/tests/elem_prop_read_user_object

- [ ] FiniteStrainPlasticMaterial won't work. It is used in modules/tensor_mechanics/tests/auxkernels/ranktwoscalaraux.i modules/tensor_mechanics/tests/auxkernels/principalstress.i modules/tensor_mechanics/tests/j2_plasticity/tensor_mechanics_j2plasticity.i

- [ ] FiniteStrainRatePlasticMaterial won't work. It is used in modules/tensor_mechanics/tests/rate_plasticity/tensor_mechanics_rate_plasticity.i

- [ ] FiniteStrainPlasticBase won't work. It is a base-class and not used directly in any tests

- [ ] FiniteStrainMohrCoulomb won't work. It is used in modules/tensor_mechanics/tests/mohr_coulomb/small_deform1.i

**Comment by WilkAndy** [comment]
I've done all i can here.  If i do any more it'll be deleting other people's stuff which is probably not a good idea!

**Comment by sapitts** [comment]
@WilkAndy would you check off FiniteStrainElasticMaterial and ElementPropertyReadFileTest from your list please?  Thanks!

**Comment by WilkAndy** [comment]
Just ticked them off, thanks @sapitts  :-)

a

**Comment by WilkAndy** [comment]
@cpritam and @jiangwen84 - are you keen to take on the remainder of the stuff mentioned above, or should i close this issue?

**Comment by cpritam** [comment]
I'll work on some of them. Don't close it now.

Pritam

**Comment by WilkAndy** [comment]
That's great, thanks @cpritam 

a

**Comment by cpritam** [comment]
Addressed items 4,5, 8 and 9 couple of weeks back.

**Comment by WilkAndy** [comment]
Awesome, thanks @cpritam,

andy
