### ISSUE TITLE
Wrong param name in PorousFlowJoiner 

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#6984]
### Description of the enhancement or error report

PorousFlowJoiner.C is trying to get a parameter that is not input

### Rationale for the enhancement or information for reproducing the error

Fixes a simple error

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Makes PorousFlowJoiner work

**Comment by WilkAndy** [comment]
Ha, i just discovered that too.  Is it ok if it goes in my PR in a few hours?

**Comment by cpgr** [comment]
I was just about to tag you in this. No worries, I noticed it trying to run a dirac kernel test.

**Comment by WilkAndy** [comment]
OK.  By the way - why don't you commit the tests involving Dirac Kernels along with your DiracKernels.

**Comment by cpgr** [comment]
That is the plan

**Comment by WilkAndy** [comment]
Cool.  I've done all the other tests, except for poroelasticity which i need to thoroughly check the gold files - that will take a few hours.  Oh and cpgr_test which i think was not ever a real test, and tests/kernels which also i don't think were ever real tests.

a

**Comment by WilkAndy** [comment]
This issue is fixed, @cpgr
