### ISSUE TITLE
Change component_index to fluid_component_index in PorousFlow

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#6986]
### Description of the enhancement or error report

Some Kernels etc have input "component_index".  This can actually lead to subtle bugs because "component_index" is used elsewhere to mean "spatial component index", and we inherit from stuff that has "component_index" already.  We should change to "fluid_component_index".  

Tagging @cpgr

**Comment by cpgr** [comment]
👍

**Comment by WilkAndy** [comment]
Unless you disagree, @cpgr , i'm going to make it simply fluid_component

**Comment by cpgr** [comment]
No worries
