### ISSUE TITLE
Allow specifying --enable-cxx11 when rebuilding libmesh

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#6995]
### Description of the enhancement or error report
Allow the user to specify `--enable-cxx11` to `scripts/update_and_rebuild_libmesh.sh`. 

### Rationale for the enhancement or information for reproducing the error
Currently `--disable-cxx11` is hardcoded in the script. It needs to be deactivated if `--enable-cxx11` is passed in.

### Identified impact
Will allow us to change application recipies in Civet to allow using C++11 _now_.

**Comment by jwpeterson** [comment]
We decided we didn't need this, users can always enable C++11 by passing --enable-cxx11 to their update_and_rebuild_libmesh.sh scripts.
