### ISSUE TITLE
Implement the handling of deprecated tests

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#6999]
We want to start handling deprecated tests more efficiently using the TestHarness

**Comment by sapitts** [comment]
@milljm Should I wait for your PR from this issue before I rebase and repush my failing deprecated parameter PR?  Thanks for working on this change!

**Comment by permcody** [comment]
He's handing it off to me to finish. I'm going to start on it now.

You don't have to wait if you want to get your code in.

**Comment by sapitts** [comment]
Awesome, thank you both.
