### ISSUE TITLE
Constraint Jacobian Sparsity Patterns

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7000]
### Description of the enhancement or error report

Constraints tie dofs together that are not geometrically connected in the mesh.  Because of this we need to augment the Jacobian sparsity pattern to tell PETSc where these new non-zeros are.  For some of our constraints we've tried to infer the dof couplings based on which boundaries are involved (see: https://github.com/idaholab/moose/blob/devel/framework/src/base/NonlinearSystem.C#L1457 ).  However, some Constraints (such as EqualValueBoundaryConstraint) don't work out well this way.

I propose that we move Jacobian Sparsity Augmentation into the Constraints themselves via a virtual function.  We can re-implement the current stuff in the base-classes and anything that's not captured can be specialized in derived classes.

I don't yet know what the interface for that function should look like... but most likely the function will take a `std::map<dof_id_type, std::vector<dof_id_type> > & graph` to fill in with the dof linkages
### Rationale for the enhancement or information for reproducing the error

Not filling in the correct sparsity pattern leads to poor performance during the first Jacobian fill due to re-allocations in PETSc.
### Identified impact

This will grow the interfaces in Constraint... but that's a fairly advanced system anyway - I don't expect this to actually impact users (if we do it right).

One nice side-effect is it will remove some (somewhat involved) code from `NonlinearSystem`...

**Comment by friedmud** [comment]
Pinging @bwspenc @jessecarterMOOSE

**Comment by bwspenc** [comment]
@friedmud This is great. Do you have any time to work on this? I'm pretty tied up with other things for a few weeks.

**Comment by friedmud** [comment]
I will have some time to work on it this week.  But probably not today (in the middle of something else)

**Comment by bwspenc** [comment]
@friedmud That would be great.  If you can create the interface to the Constraints to augment the sparsity, I can take care of the code in EqualValueBoundaryConstraint.

**Comment by dschwen** [comment]
Ugh, I guess I can take a stab at `EqualGradientConstraint`, but I don't know how the sparsity pattern should look for coupled in gradient components...

**Comment by permcody** [comment]
@friedmud - We only use "critical" status for things that cause failure or require an immediate fix. People basically ignore priorities...

**Comment by friedmud** [comment]
@permcody right.  @jessecarterMOOSE reported it on the list... I assume it's holding up his work... that's why I reached for `critical`.  Since it's assigned to me anyway this was really just a reminder to get it done...

**Comment by permcody** [comment]
The priority stuff comes from NQA-1. They require a high level for things that are holding up "operational" work. Generally there shouldn't be any open that are not being worked on. When the assessors come and see priority levels. They like to see how many of the top ones are open. In the past we actually had a better system IMO with the "blocker" level. That really did mean, drop everything and work on that ticket. However when we went to three levels we had several "critical" tickets that were open for months/years... It looked bad during the assessment.

**Comment by friedmud** [comment]
Hah - ok ;-)

**Comment by jessecarterMOOSE** [comment]
Just wanted to say that I appreciate the attention, but it's not _that_ important. We're still in the learning stages over here as far as mechanical models are concerned. We came across this issue while we were just throwing big problems at MOOSE that we already had laying around.

**Comment by lindsayad** [comment]
Sparsity patterns for constraints on displaced meshes are still an issue. However, our mechanism for handling this in 2023 is `RelationshipManagers/GhostingFunctors`. The unresolved concern is how to allocate sparsity patterns when the sparsity pattern changes every nonlinear iteration, which is covered in #7901 and a related (closed) pull request #9509. I'm going to close this in favor of #7901
