### ISSUE TITLE
Compute strain on 1D spherical coordinates in tensor mechanics module is missing?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7003]
### Description of the enhancement or error report
Look like. If not, feel free to close this issue.

### Rationale for the enhancement or information for reproducing the error
It prevents from calculating with spherical coordinates with tensor mechanics.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New feature added.

**Comment by sapitts** [comment]
The spherical strain classes in tensor mechanics follow the Compute/*Strain naming convention:
- [ComputeRSphericalFiniteStrain](https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/src/materials/ComputeRSphericalFiniteStrain.C)
- [ComputeRSphericalIncrementalStrain](https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/src/materials/ComputeRSphericalIncrementalStrain.C)
- [ComputeRSphericalSmallStrain](https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/src/materials/ComputeRSphericalSmallStrain.C)

Test cases for each of these strain classes are available in ```tensor_mechanics/tests/1D_spherical```.  Please let me know if you have any questions/ concerns about these classes.

**Comment by YaqiWang** [comment]
oh, thanks.
