### ISSUE TITLE
Bug in SideSetsAroundSubdomain

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7011]
### Description of the enhancement or error report

The depends_on flag doesn't appear to work for SideSetsAroundSubdomain

### Rationale for the enhancement or information for reproducing the error

Here's an input file:

[buggy.txt](https://github.com/idaholab/moose/files/269424/buggy.txt)

**Comment by permcody** [comment]
Well that doesn't make any sense! Thanks for the bug report.
