### ISSUE TITLE
Create basic tutorial for the tensor mechanics kernel

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#7014]
### Description of the enhancement or error report
We need a basic tutorial for the tensor mechanics kernel. It will cover

- The basic elements of a tensor mechanics input file
- Visualizing tensor fields
- 2D axisymmetric RZ problems
- Small strain elasticity, finite strain elasticity, and finite strain J2 plasticity
- Extruding a 2D mesh to be a 3D mesh
- Running 3D tensor mechanics problems in cartesian coordinates

### Rationale for the enhancement or information for reproducing the error
New users need a clear demonstration of how to use the basic parts of the tensor mechanics kernel

### Identified impact
The tutorial will help new users quickly become familiar with the tensor mechanics module

**Comment by mangerij** [comment]
The cantilever problem could be useful.

**Comment by tonkmr** [comment]
For the first tutorial, I am doing a uniaxial tension problem with the stress-strain curve
