### ISSUE TITLE
Auto-removing labels; notifying others to review PRs

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#7025]
@friedmud: 
Hah - @moosebuild removed the Do Not Merge label... are we sure we want @moosebuild doing that?

@permcody:
We are debating this now. I think we want moose-build to do something but we haven't decided exactly what that should be. It makes sense for "Please address comments" and maybe even "Under Construction", but maybe it shouldn't drop them universally.

If you have input, please share. I'm starting to think we should have two classes of labels. Those that will be removed by MOOSE (due to a push or successful tests) and those that should not.

@aeslaughter:
Personally, I don't want civet adding or removing labels. For me there are
far too many scenarios to consider.

I also think that perhaps we should spend time improving the Civet
dashboard to show the information we are interested in (I am not sure what
that informatin is) rather than rely on github labels (especially since we
are the only ones that can add or remove them). Perhaps we can setup and
document a small set of keywords that anyone can place in comments (e.g.,
WIP) that would trigger items on the Civet dashboard to indicate to us the
status of the PR. Just ideas.

@permcody:
Well I'm open to ideas. How can I avoid having to ask fellow team members
to go and look at PRs and review them. I feel I'm handling a
disproportionally large amount of them. On Tuesday I finished up a PR that
@sapitts was waiting on. Waited for it to be tested (it passed). Marked it
as ready to merge, tagged the whole team, and still waited for 24 hours
before prompting somebody to merge it. This current system isn't working.
It's also hard to tell what's been reviewed and what hasn't if the labels
never change. I think the best idea so far is to have two classes of label.
Those that are removed and those that are not.

**Comment by jwpeterson** [comment]
My issue with this is really information overload... since I get email every time someone comments on *any* PR in MOOSE, specific requests to review get buried.  If there was a way to only receive emails when someone tags something "Review requested" or "Ready to Merge", that would help a lot.  Maybe I just need to update my notification settings on GitHub...

**Comment by dschwen** [comment]
It would be helpful if `PR: Contains libMesh Update` was added automatically. That does not sound controversial at all.

**Comment by jwpeterson** [comment]
> It would be helpful if PR: Contains libMesh Update was added automatically. That does not sound controversial at all.

This is controversial because people sometimes do libmesh updates by accident, and I would not want those PRs prematurely labeled.

**Comment by dschwen** [comment]
Huh?! The accidental update is the _primary_ application for this label!

**Comment by jwpeterson** [comment]
> Huh?! The accidental update is the primary application for this label!

We already have a box on Civet that turns orange for the purpose of detecting accidental updates, but I guess most people don't look at Civet.

**Comment by dschwen** [comment]
Yeah, labels could help consolidate this kind of information in a single place: the github page where the merge button is.

**Comment by WilkAndy** [comment]
Seems like you guys need to hire another bod

**Comment by WilkAndy** [comment]
Do you guys want to make "negative" labels available to people like me?  Eg "Do not merge", "Work in progress".

**Comment by jwpeterson** [comment]
> On May 23, 2016, at 9:56 PM, Andy Wilkins <notifications@github.com> wrote:
> 
> Do you guys want to make "negative" labels available to people like me? Eg "Do not merge", "Work in progress".
> 

Unfortunately only people with repo write access can assign labels, and it's all or nothing as far as I know...

**Comment by WilkAndy** [comment]
ok

**Comment by permcody** [comment]
We've removed most of the PR labels at this point. CIVET is able to remove the [TODO] labels automatically so that reviewers can re-review an existing PR. We will run this away and make adjustments in the future as needed.
