### ISSUE TITLE
METHOD=dbg make errors in unit tests

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7050]
Can someone (@bwspenc ?) remove the debug compilation errors from unit/src/ElementFragmentAlgorithmTest ?  There are heaps of them, and they're all along the lines of:

/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C: In member function âvoid ElementFragmentAlgorithmTest::ElementFragmentAlgorithmTest6a()â:
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1190:24: error: zero-size array âtnâ
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1202:24: error: zero-size array âceâ
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1208:24: error: zero-size array âpeâ
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C: In member function âvoid ElementFragmentAlgorithmTest::ElementFragmentAlgorithmTest6b()â:
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1289:24: error: zero-size array âtnâ
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1342:25: error: zero-size array âtn2â
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1354:25: error: zero-size array âce2â
/apps/geomodel/moose/projects_andy/moose/unit/src/ElementFragmentAlgorithmTest.C:1360:25: error: zero-size array âpe2â

Or perhaps it's just my old compiler that's stupidly complaining?

**Comment by permcody** [comment]
Yuck - It looks like we need to C++11-ize our use of CPP unit. We'll get
around to this soon. Thanks for the heads up.

**Comment by bwspenc** [comment]
I'll take care of this.

**Comment by WilkAndy** [comment]
Thanks @bwspenc ,

a

**Comment by jwpeterson** [comment]
AFAICT this has nothing to do with CPPUnit or requiring C++11.  You are simply not allowed to declare [zero-sized arrays](http://stackoverflow.com/questions/9722632/what-happens-if-i-define-a-0-size-array-in-c-c) like this:
```
unsigned int tn[] = {};
```
I don't mind introducing C++11, but in the unlikely event we decide to pull it all back out, this is one more thing to remember...

**Comment by bwspenc** [comment]
@jwpeterson I realize that.  I just figured I'd clean those up while I was in there because I never liked how we had to initialize those vectors using arrays. If we do need to back this commit out, we can just remove those empty arrays because they didn't do anything for us anyway.
