### ISSUE TITLE
Add -std=c++11 for all MOOSE compile rules

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7057]
### Description of the enhancement or error report

We should use the -std flag in all of our compile rules to prevent C++14 syntax from sneaking in. 

### Rationale for the enhancement or information for reproducing the error

Now that we are using C++11, it would be trivially easy to commit C++14 syntax which is essentially just an extension of C++11. If we are going to support minimum compilers, this is probably the easiest way to do it (as long as it actually works!).

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact, ensure C++11 compatibility.

**Comment by permcody** [comment]
@idaholab/moose-developers - any comments?

**Comment by andrsd** [comment]
Is this not coming from libMesh's configure?

**Comment by permcody** [comment]
Good point, I think it is. I guess what we need to do is make sure we are using the right option and that it's properly enforcing c++11 and not allowing stray c++14 in to the mix.

**Comment by friedmud** [comment]
I'm all for restricting to C++11 for now.  Makes sense to me.

**Comment by permcody** [comment]
There are some really handy functions that got left out of c++11 that we
will want soon. There are equivalents though that we can wrap so that we
don't have to go without. "make_unique" is one of those!

**Comment by permcody** [comment]
I verified that the flag coming from libMesh `-std=gnu+=11` is indeed is restricting us to C++11. I didn't compile my code with `make_unique` in it despite that existing in my clang implementation.
