### ISSUE TITLE
Need a way to track multiplicity of Dirac Points

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7060]
### Description of the enhancement or error report
If a similar Point (within `libMesh::TOLERANCE`) is passed to `addPoint` in a DiracKernel it is silently dropped.

### Rationale for the enhancement or information for reproducing the error
A multiplicity field for each Point should be incremented if a similar point is passed in. The value should be available to `DiracKernel::computeQpResidual()`

Workarounds such as maps indexed by Points do _not_ work, as the Points being looked up are not necessarily _exactly_ the same (only within the tolerance). Reimplementing the tolerance check in user code is not a good solution either (any changes in the framework tolerance check would make the behaviors inconsistent and the residuals wrong).

### Identified impact
This will make implementing residuals easier.

**Comment by friedmud** [comment]
I'm in support of this
