### ISSUE TITLE
MooseVariable and MooseVariableBase are both declaring _scaling_factor

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7065]
### Description of the enhancement or error report
The derived class `MooseVariable` is declaring `_scaling_factor`, which is already a protected member variable in its base class `MooseVariableBase`.

### Rationale for the enhancement or information for reproducing the error
The `_scaling_factor` in `MooseVariable` is never set or used. It is probably a residual of some refactoring before.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact, just need to remove this never used variable.

**Comment by andrsd** [comment]
@YaqiWang Are you going to to work on this?

**Comment by YaqiWang** [comment]
Sorry, no. I will mention in the future in the issue if I decided to pick it up.

**Comment by andrsd** [comment]
Ok, I will fix this then. Thanks for reporting it.
