### ISSUE TITLE
New valgrind failures coming to a mechanics module near you!

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7071]
### Description of the enhancement or error report

New tests in both mechanics modules are leaking

### Rationale for the enhancement or information for reproducing the error

Run with Valgrind. Both of these look really easy to fix.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Both mechanics modules.

Ping @backmari, maybe @sapitts 
https://www.moosebuild.org/job/25078/

**Comment by dschwen** [comment]
That's an easy fix. Make `_interp_yield_stress` a shared pointer!

**Comment by permcody** [comment]
Now you're screwing with me...

**Comment by dschwen** [comment]
A leak in some new mechanics crap 
was to be fixed with shared pointer wrap
@permcody wanted it to be unique
because that's his new pointer chique.
I'll ignore the advice from that chap.

**Comment by backmari** [comment]
Thanks for fixing this @dschwen. I'm proud my memory leak could inspire so much poetry!
