### ISSUE TITLE
Reevaluate slow tests

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7073]
### Description of the enhancement or error report

This ticket is here to start catching a list of tests that fail due to timeouts. I'd like people to start tallying these up when they invalidate a target due to timeout. This will help us evaluate whether some tests need to be made smaller, or timeout increased, etc.

```
solid_mechanics:rate_dep_smear_crack.sent_test -> 4
combined:contact_verification/patch_tests/brick_3.glued_pen -> 5
restart/pointer_restart_errors.pointer_load_error2 -> 1
phase_field:MultiSmoothCircleIC.multi_test -> 1
time_steppers/time_adaptive.text -> 3
```
### Possibly broken tests

```
restart/pointer_restart_errors.pointer_load_error2 -> 1
```
### Problems in parallel with error messages

```
auxkernels/solution_aux.output_error -> 1
```
### Tests that timed out

```
bcs/periodic.testLevel1 -> 2
multiapps/picard_sub_cycling.test -> 2
```

**Comment by permcody** [comment]
Tag @idaholab/moose-team

**Comment by acasagran** [comment]
test timed out in parallel with n = 2 (PR #7159)

time_steppers/time_adaptive.test -> 2

**Comment by permcody** [comment]
@cpritam and @acasagran - We've been keeping score for awhile and I think we have a pretty good list now of tests that time out quite regularly.

@cpritam will you take a look at revising `solid_mechanics:rate_dep_smear_crack.sent_test`
@acasagran will you take a look at revising `combined:contact_verification/patch_tests/brick_3.glued_pen -> 5`

Thanks!

**Comment by permcody** [comment]
Most of these tests have been cleaned up.  I'll close this ticket now and watch for other problems.
