### ISSUE TITLE
A strange error in Jacobian analyzer

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7086]
### Description of the enhancement or error report
If I put `petsc_options = '-mat_view'` in the input and run `analyzejacobian.py`, I got bunch of false errors like `(1,1) On-diagonal Jacobian is wrong (off by 2194371010.2 %)`. However, if I remove the PETSc option, those errors are gone, which should be.

### Rationale for the enhancement or information for reproducing the error
The same behavior can be produced by adding the option in one of basic moose tests `test/tests/kernels/2d_diffusion/2d_diffusion_test.i`.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Make developers happy.

**Comment by dschwen** [comment]
Well, the Jacobian analyzer screen scrapes PETSc debug output. If you mess with the output too much (by adding additional PETSc options) it gets harder hand harder to extract the data it needs.

**Comment by YaqiWang** [comment]
Oh, I see. Add a better pattern match or feel free to close this.

**Comment by permcody** [comment]
Let's close this.
