### ISSUE TITLE
Add cache for semilocal elements to FeatureFloodCount

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7096]
### Description of the enhancement or error report
Currently FFC uses `ELEM::is_semilocal`, which does a bunch of `find_point` calls. Those are expensive (and apparently a bit dangerous with higher order elements and displaced meshe). I'd like to add a cache (set) containing all semilocal element IDs that is built whenever the mesh changes (or on initialize of the FFC).

### Rationale for the enhancement or information for reproducing the error
Replace the slow and error prone call to `is_semilocal` with a fast std::set::find call.

We observe segfaults and assertions in debug related to `contains_vertex_of` where shared vertices are not correctly detected as mutually contained in the elements.

### Identified impact
Fix use of FFC with Riso AN3 Bison assessment case.

**Comment by permcody** [comment]
> (and apparently a bit dangerous with higher order elements and displaced meshe)

What's a meshe? Is that French for mesh?

**Comment by dschwen** [comment]
It is the latin plural of mesh. But you wouldn't know...
