### ISSUE TITLE
Fix Patrick's input file

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7099]
Tagging @pt6 .  Where actually is your input file, @pt6 ?

**Comment by WilkAndy** [comment]
To submit your issue into moose, you go to this site, hit "New issue" and enter a description.  I'll close this issue soon as it's not related to developing moose really - it's too specific to you.  I just wanted you to see how to do it.

**Comment by pt6** [comment]
My input file should be [here](https://github.com/pt6/MAN/blob/master/Aniso_RoundPpt400CEnriched.i). I'll do that, thanks for the guidance.

**Comment by WilkAndy** [comment]
Good, thanks @pt6 .  I'll close this.  I'll get your input file and try to run it.  See you on gitter, hopefully.

a
