### ISSUE TITLE
Abaqus Umat test

### ISSUE THREAD

**Issue by ramirezbrf** [idaholab/moose#7103]
I tried to run the umat_linear_strain_hardening test but it gives the following error msg:
"Cannot open library: ../../plugins/linear_strain_hardening-opt.plugin: cannot open shared object file: No such file or directory"
I open AbaqusUmatMaterial.C and found that in line 19, that plugin parameter is define as "The path to the compiled dynamic library for the plugin you want to use", so I created a dynamic shared library called linear_strain_hardening.so by using: 
ifort -shared -fpic -o linear_strain_hardening.so -linear_strain_hardening.f
But this wouldn't solve the error. I would like to know if there is an special procedure to create the dynamic library? 
Thanks

**Comment by permcody** [comment]
There shouldn't be anything special to do but of course we are interacting with the Fortran compiler here so there are plenty of things that can go wrong. First off did you see if the `.plugin` file is being built? We have rules in our Makefile for turning Fortran files into .plugin files instead of the normal object file suffix. The reason is we didn't want to fight all of the different suffixes you can get going platform to platform. If those files aren't being built, that's the first thing we need to look at. Do you have any compile error when you build the solid mechanics module?

**Comment by ramirezbrf** [comment]
Hi,
Answering  your question "First off did you see if the .plugin file is
being built?"
No, there isn't any.
With regard of your second question, "Do you have any compile error when
you build the solid mechanics module?", I convey this question to Gary
Myers. He did not know because the person who performed the installation is
out for the day, but he told me that from the report of the installation it
looks like the solid_mechanics:umat_linear_strain_hardening test was
skipped (LIBRARY_MODE!=DYNAMIC). He is can not say if there is a compile
error or if it was never intended to be build because the library mode.

**Comment by permcody** [comment]
So we build dynamic by default which probably means your installer
purposely enabled a static build. We need to figure out why that choice was
made and hopefully go back to a dynamic binary. If this isn't possible we
could probably come up with a scheme where you could still get your UMATs
running but we'd have to link them statically to the Abaqus material which
would mean we'd have to recompile that material each time they changed.

**Comment by jessecarterMOOSE** [comment]
Yes we build statically. I do not know why but that is the default on our systems. @ramirezbrf you'll have to talk to Ross about that.

**Comment by ramirezbrf** [comment]
Since we are going to have the need to use  our UMATS with MOOSE, we should
have the capability to build our UMATS into shared dynamic libraries (I
don't think that having to remaking them every time they are modified is a
big deal). I was wondering if there is an example make file that we can use.

**Comment by permcody** [comment]
We already handle this all for you. You shouldn't need to modify any
Makefiles. I assume that someone on your side did though since you have
static libraries. If you take a look at our build rules here:
https://github.com/idaholab/moose/blob/devel/framework/build.mk#L284-L295

You'll see that we already look for Fortran files in the "plugin" directory
and compile them dynamically. We then load those object files dynamically
from the AbaqusMaterial class.

Cody

**Comment by friedmud** [comment]
If I remember correctly: they actually hardcode their COMPILERS/environment
to only do static linking. You need to get ahold of one of your admins and
ask them how to undo that...

**Comment by ramirezbrf** [comment]
I was able to generate the dynamic shared library by using:
ifort -shared -fpic -o linear_strain_hardening-opt.plugin
linear_strain_hardening.f

**Comment by ramirezbrf** [comment]
Thanks Derek, Not only I would like to fix the issue with the fortran sample code in the plugin folder, but also I would like to be able to compile our umats  without installing MOOSE every time. This is why, I would like to know which is the instruction built ,with the line below, to compile the fortran code.
@$(libmesh_F77) $(libmesh_FFLAGS) -shared -fPIC $(app_INCLUDES) $(libmesh_INCLUDE) $< -o $@
so far, it seems to me something like the following
mpif90 -g -O2 -fopenmp -shared -fPIC -o inear_strain_hardening-opt.plugin
linear_strain_hardening.f
could you let me know if this is correct?
Thanks

**Comment by permcody** [comment]
That looks correct. The Fortran flags might change a little bit from
compiler to compiler but what you have should work.

**Comment by ramirezbrf** [comment]
I got mixed results.
The example only runs for the example case of cube of
nx=1
ny=1
nz=1.
 If I change nx, ny or nz to any other number the example runs but do not
converge. Any ideas why?

**Comment by permcody** [comment]
Are you talking about the existing test? It has never been robust, it
doesn't pass Valgrind. I suspect it's just very poorly written code. I'd
like to see it go away but it's useful to see how the interface works.

**Comment by ramirezbrf** [comment]
Yes, this is the existing test. Do you think that the problem is with the Fortran code? or with the way the fortran code is called from the c++ code?. This is a very important feature for us. Do you have any recommendation to make it more robust?

**Comment by permcody** [comment]
I'm fairly certain it's the UMAT we have. It was contributed by a Sumer
student. If you have a really simple example or could make on that would be
awesome. Them we could re-enable the test and keep it running.

**Comment by ramirezbrf** [comment]
I have resolve the issue by using
ifort -g -O2 -openmp -autodouble -shared -fPIC -o inear_strain_hardening-opt.plugin linear_strain_hardening.f
Now, I am trying to use the AbaqusUmatMaterial interface implementation with an isotropic thermal expansion fortran code. the main issue with the current implementation of the UMAT interface implementation is that it does not use temperature, _TEMP is not assigned a value. I have make a copy of AbaqusUmatMaterial and rename it to AbaqusUmatMaterial_temp_depend. After changing the file with the right name 
.h file
#ifndef ABAQUSUMATMATERIALTEMPDEPEND_H
#define ABAQUSUMATMATERIALTEMPDEPEND_H
...
#endif
.c file
line 216
_TEMP=_temperature[_qp];
_DTEMP=_temperature[_qp]-_temperature_old[_qp];

and register it in SolidMechanicsApp.c
#include " AbaqusUmatMaterial_temp_depend.h"
..
registerMaterial(AbaqusUmatMaterial_temp_depend);
Finally, I've  modified the input file by adding
[AuxVariables]
  [./temp]
     order = FIRST
     family = LAGRANGE
  [../]
[]
[Functions]
  [./temp_func]
     type = PiecewiseLinear
     xy_data = '0 100
                      1   150'
  [../]
[]
[AuxKernels]
[./temp]
type = FunctionAux
variable = temp
block = 0
function = temp_func
[../]
[]
[Material]
[./constant]
type = AbaqusUmatMaterial_temp_depend
formulation = linear
block = 0
youngs_modulus  = 14700000
poissons_ratio = .3
disp_x = disp_x
disp_y=disp_y
disp_z=disp_z
temp=temp
mechanical_constants = '1470000 0.3 100 16700000 0.3 200 0.00000057 100'
plugin = ../../plugins/IsoTempDep_Fortran
num_state_vars = 12
[../]
[]
The modified test  runs but I would like to debug the interface to see if it is correct.
I have a couple of questions:
1- Is this implementation seems  consistent with the MOOSE/solid_mechanics?
2- how do I get print statements from the AbaqusUmatMaterial_temp_depend.c into the .log?
I have tried std::cout but it does not work.

**Comment by jessecarterMOOSE** [comment]
Can't comment on the consistency, but have you tried to run in serial? By default, MOOSE sends all stdout to /dev/null except for cpu 0.

**Comment by permcody** [comment]
That interface looks "right" to me. MOOSE just needs you to produce
Material properties, it doesn't care how. You're setting inputs there based
on current and old values and that looks fine too.

As far as getting output, Jesse is right, we only save output from rank 0
by default. You can save all ranks to files by using --redirect-stdout or
--keep-cout (depending on if you want separate files, or everything on one
screen respectively).

Cody

**Comment by ramirezbrf** [comment]
Thanks Jesse.

**Comment by ramirezbrf** [comment]
Thanks Cody

**Comment by permcody** [comment]
Closing - This ticket is more of a discussion than an issue or enhancement.
