### ISSUE TITLE
InterfaceOrientationMaterial not accepting input parameters

### ISSUE THREAD

**Issue by pt6** [idaholab/moose#7108]
Hello,

When trying to define parameters in [this material](http://mooseframework.org/docs/doxygen/modules/InterfaceOrientationMaterial_8C_source.html), I'm running into the issue of the material not recognizing the input parameters listed in the source code. If I only define "block" and "c", the input file will run witht the default parameters. However, when I define an input parameter like I do in [this input file](https://github.com/pt6/MAN/blob/master/Aniso_RoundPpt400CEnriched.i), I get the error "input parameter not used". Furthermore, most of these input parameters do not appear when I open the material in Peacock. 

Atom seems to recognize the input parameters. I've recompiled MOOSE and it tested fine. I'm using Terminal on a Mac desktop running El Capitan. Someone mentioned that there were Windows Newlines in my input file which may be the issue, but I was unable to find or remove them.

Any thoughts on what the issue with the material or my input file might be? Forgive me if I'm misusing Github or not following the MO for working through these types of things. 

Many thanks,
Patrick Shower

**Comment by dschwen** [comment]
Read the many replies you already got! The parameter is called op not c!

**Comment by pt6** [comment]
Maybe I'm doing something else wrong then, becasue I tried that. 

Based on what people told me, I replaced the parameter "c" in the input file with "op". When I tried to run that, it told me that "c" was a required input parameter and "op" was unused. 

Andrew said that the input file worked for him after he made that replacement, but it didn't for me.

**Comment by dschwen** [comment]
Patrick, your comments contain too little information to work with. You mix
up various classes here and do not mention which ones give you the errors.
We need a copy paste of the error message _with context_. We need you to
point us to git paths that have the _actual_ file that yoy ran that gave
you teh error.
We are just running in circles here.

**Comment by pt6** [comment]
I'm sorry I was unclear. I'm terrible at speaking out of context, and I guess that leaked into my communications here. I'll try to use more accurate wording and fewer pronouns.

When I run [this input file](https://github.com/pt6/MAN/blob/master/Aniso_RoundPpt400CEnriched.i), I get this error:
*** ERROR ***
The following required parameters are missing:
aniso_material/c
	Doc String: "variable"

After getting that error, I add a line in the aniso_material sub-block to define the missing parameter. I.e this sub block:

![screen shot 2016-05-31 at 11 44 16 am](https://cloud.githubusercontent.com/assets/17414694/15680866/2f5f55ec-2725-11e6-82dc-2a473fd0708a.png)

becomes this sub block:


![screen shot 2016-05-31 at 11 42 58 am](https://cloud.githubusercontent.com/assets/17414694/15680833/1713e430-2725-11e6-8510-fe08a5ec75a7.png)

When I run the revised input file, I get this error message:


*** ERROR ***
The following parameters were unused in your input file:
Materials/aniso_material/eps_bar
Materials/aniso_material/mode_number
Materials/aniso_material/op


Karim thinks that it has to do with an error in one of the blocks that comes before the Materials block in the input file. I'm looking into that now. 

As a side note, Jay-Jay Billings is in my Ph.D. program (not sure you know him, but he tweets about MOOSE with some frequency). I should see about getting more help from him when I have questions.

**Comment by dschwen** [comment]
Yeah, I've met Jay-Jay. Anyhow. Please try to follow up on my requests
thoroughly. I need to see a complete input commited to your repo. Please do
not attach text as screenshots (it does not work well on mobile and it it
not searchable).

**Comment by pt6** [comment]
This is the committed input file in my repository:
https://github.com/pt6/MAN/blob/master/Aniso_RoundPpt400CEnriched.i

I tried to hyperlink the input file to my last comment, maybe it doesn't show up the same on mobile devices.

The text that I attached as a screenshot just showed my InterfaceOrientationMaterial sub-block (from the linked input file) before and after I added a line. 

**Before:**

  [./aniso_material]
    type = InterfaceOrientationMaterial
    block = 0
    mode_number = 2
    eps_bar = 0.02
    op = eta
  [../]

**After**

  [./aniso_material]
    type = InterfaceOrientationMaterial
    block = 0
    mode_number = 2
    eps_bar = 0.02
    op = eta
    c = c
  [../]


Did everything else come accross alright on my last comment? Can you see the error messages? Thank you for you patience, let me know if there's anything I'm missing that I need to add here.

**Comment by dschwen** [comment]
That file runs without any errors. Make sure you go back to the MOOSE devel
branch if you made any changes to the source code of those materials.

**Comment by pt6** [comment]
Well that's interesting. I wouldn't even know how to edit the source code. As far as I know I haven't touched it. I'm sorry for asking you to spell things out, but how would I go back to the devel branch?

**Comment by pt6** [comment]
I updated MOOSE as a whole and tested this morning, if that's relevant.
