### ISSUE TITLE
transient multiapp with sub_cycling and IterativeAdaptiveDT has incorrect initial time step when multiple apps are on same mpi process

### ISSUE THREAD

**Issue by rppawlo** [idaholab/moose#7115]
### Description of the enhancement or error report
In CASL, we are driving MOOSE/Bison via a TransientMultiApp. When sub_cycling is enabled, if we have more than one app per MPI process, only the first app has the correct initial time step for the IterationAdaptiveDT time stepper. All other apps on the same process have a small time step (0.0 plus a safety padding added by moose on the order of 1e-14). I have not been able to figure out why the first app does get the correct step while the others don't. Below is a suggested fix:

https://github.com/idaholab/moose/blob/devel/framework/src/timesteppers/IterationAdaptiveDT.C#L45-46

The code is:
```
    _dt_old(declareRestartableData<Real>("dt_old", 0.0)),
    _input_dt(getParam<Real>("dt")),
```

When computing a dt, the first line of the computeDT() function on line 137 ignores the _input_dt set in the ctor above: 
```
Real dt = _dt_old;
```
The function then calls the computeAdaptiveDT(dt) if the adaptive time step option is set with dt effectively being zero. We were able to fix this by changing the ctor to:
```
    _dt_old(declareRestartableData<Real>("dt_old", getParam<Real>("dt"))),
    _input_dt(getParam<Real>("dt")),
```

I'm not sure if this is the best fix, but it works for us.

### Rationale for the enhancement or information for reproducing the error

Without this fix, we are forced to run with enough MPI processes such that Bison gets one pin per MPI process.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This impacts all CASL coupled uses cases that use sub_cycling.

**Comment by friedmud** [comment]
Thanks @rppawlo I'll take a look

**Comment by dschwen** [comment]
Out of curiosity, what is the drawback of running with _enough_ MPI processes? If you distribute the processes to the same number of cores you oversubscribe the same way. (this is independent of the fact that you uncovered a bug, of course)

**Comment by friedmud** [comment]
@dschwen no: if you oversubscribe MPI processes then they will fight each other for processor time while they execute.  If you have more sub-apps than MPI then MOOSE executes the sub-apps each MPI in sequence (so only one is ever running on a processor at a time).

**Comment by rppawlo** [comment]
@dschwen To add on to what @friedmud  mentioned, we are running Bison/MOOSE coupled to external neutronics and CFD/Sunchannel. Our test machines only have 64 cores. There are some system level heavy tests that we want run nightly that exceeds 64 cores if we have to give Bison a pin per core. Additionally, we are trying to load balance across all three physics (each physics has its own block of mpi processes distinct from one another) and there is a scalability bottleneck in one of the other apps at the moment. So moose processes can sit idle while waiting for one of the other apps to finish if it has one core per app.

**Comment by dschwen** [comment]
Ok, gotcha, makes sense. So in addition to fighting for CPU time they will probably mess up each others CPU caches may be IO bound etc.

**Comment by friedmud** [comment]
Ok - I can replicate this behavior with a small modification to the `multiapps/sub_cycling` test.

Working on it...

**Comment by friedmud** [comment]
BTW: here's what it looks like:

![sub_cycle_fail](https://cloud.githubusercontent.com/assets/870705/15689020/0351002e-274b-11e6-8a6c-caf8d7862781.png)

**Comment by friedmud** [comment]
BTW: It works fine with `ConstantDT`...

**Comment by rppawlo** [comment]
Thanks @friedmud and @permcody !
