### ISSUE TITLE
Make steady state relative norm available to the outside

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#7118]
### Description of the enhancement or error report

In CFD, people are interested in plotting the relative solution norm as they progress towards steady state.

### Rationale for the enhancement or information for reproducing the error

Currently, we compute the value, but it is not accessible for the external classes.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Better plots!

**Comment by andrsd** [comment]
Tagging @yidongxiainl

**Comment by friedmud** [comment]
This will be done as a `Postprocessor`, right?

**Comment by andrsd** [comment]
Yes, a new postprocessor.
