### ISSUE TITLE
Add new convergence enum

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7119]
### Description of the enhancement or error report
Looks like there has been a new convergence enum added to PETSc: `KSP_DIVERGED_PCSETUP_FAILED`

Support for it was just added to libMesh: https://github.com/libMesh/libmesh/pull/976#event-677565619

We need to make sure to add it to our convergence related functions like `PetscSupport::petscConverged()` and our enums like `FEProblem::MooseLinearConvergenceReason`

### Rationale for the enhancement or information for reproducing the error
Keep up to date with PETSc

### Identified impact
Should keep us up to date with the PETSc API.

**Comment by permcody** [comment]
@fdkong - perhaps you could handle this ticket
