### ISSUE TITLE
Thermal expansion is accidentally removed in ComputeRSphericalSmallStrain

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7125]
### Description of the enhancement or error report
I think  thermal expansion capability in ComputeRSphericalSmallStrain is accidentally removed in 130e90456c69ae2100e217930a5aefc3f60fea36, which I am using and no test covering it :-(

### Rationale for the enhancement or information for reproducing the error
The fix should be let the class overwrite `computeQpProperties`.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact because of no test.

**Comment by dschwen** [comment]
I don't think this was accidental. @sapitts introduced a thermal Eigenstrain material that handles this.

**Comment by YaqiWang** [comment]
It should be kept as `ComputeSmallStrain`.

**Comment by sapitts** [comment]
Okay, I'll add in a deprecation message to the RSpherical--I had thought that the code was new enough that it would not impact anyone to completely remove the explicit thermal strain handling in the RSpherical code.  In the mean time, the input file syntax for the new thermal eigenstain material is
```yaml
 [./thermal_strains]
    type = ComputeThermalExpansionEigenStrains
    Temperature = temp
    thermal_expansion_coefficient = 1.0e-4
    stress_free_reference_temperature = 300
  [../]
```
and is described on the wiki Intro to [Tensor Mechanics page](http://mooseframework.org/wiki/PhysicsModules/TensorMechanics/PlugAndPlayMechanicsApproach/).

**Comment by dschwen** [comment]
Yaqi is probably the only one who used that. I'm not sure that's worth
putting this back in as deprecated.

**Comment by YaqiWang** [comment]
Thanks @sapitts The new syntax is good and I will use it. It just took me quite a scratch on figuring this out.

**Comment by sapitts** [comment]
@YaqiWang if the new ComputeThermalExpansionEigenStrain is working for you, can we close this issue?

**Comment by YaqiWang** [comment]
Absolutely! Thanks for providing me the small piece of input.
