### ISSUE TITLE
Improve petsc interface

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7130]
Tagging @fdkong
### Description of the enhancement or error report

At present i think that we can view all of petsc's options.  However, it would be great if we could:
1. see what options are actually passed from moose to petsc
2. have petsc crash or complain if the arguments passed are invalid
3. be able to view the petsc options that petsc is actually using
4. be able to list these things easily using myapp-opt --petsc_options (or whatever)
5. myapp-opt -h not listing a whole lot of wierdo petsc stuff before the moose stuff.

Perhaps all these are possible right now, but in the past i have been confused about what options petsc was receiving and using.
### Rationale for the enhancement or information for reproducing the error

Improve usability of moose in real-life applications (and decrease Andy's confusion)
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

changes the output of moose in the obvious way.

**Comment by permcody** [comment]
See #727 -

Yes Fande may be able to help us with this super old ticket.

**Comment by WilkAndy** [comment]
OK, great - i'm looking forward to it being resolved.

**Comment by permcody** [comment]
Closing since this is duplicate. Unfortunately there still is really no good way to do everything you ask here and there may never be a good way _before_ the simulation. This is key. Yes we can probably tell you after your simulation has completed whether or not all the options were used but not before. See the discussion on #727.

**Comment by WilkAndy** [comment]
PETSc options: it's not absolutely necessary to know before the simulation starts.  How about after the first time step?  That's not so elegant, BUT it's waaaay better than simulating for a few weeks only to find that things were not right!  Of course I don't understand the complications involved, but I'm quite disappointed that PETSc apparently has such a poor user interface.  It doesn't give me much confidence in the code as a whole.

**Comment by andrsd** [comment]
If I understood correctly what the problem on PETSc side was, it was something along those lines.  As PETSc constructs its objects, those options are being used and marked as used. So at the end you have the list of passed and used options so you can tell which were and which were not used. 

In general PETSc code, you can be constructing and destructing all you want during the executions, therefore you have to wait until the end of execution.  This would not be an issue for MOOSE, because we do not really rebuild PETSc objects on the fly. But, I am not sure there is a function we could call after the first step is solved. At that time we would be almost sure (there might be a corner case) about what was used and what was not...

**Comment by permcody** [comment]
We talked about this and it's a fairly reasonable thing to try assuming you
don't change options after some number of solves which CAN happen. It's
just a weird time to print information (after the first solve) but if
that's what you want, that's what you want. Let's talk about this when you
get here.

**Comment by WilkAndy** [comment]
Thanks for your comments, @andrsd and @permcody .  It looks like we'll be able to get *something* implemented.  Yes, let's talk about this when I arrive in less than 2 weeks!!  I'm super looking forward to it.

**Comment by fdkong** [comment]
> PETSc options: it's not absolutely necessary to know before the simulation starts. How about after the first time step? 

@WilkAndy, it looks like a nice idea. I definitely could make this work after one time step. After a solve, we will know what options are used or not.

>That's not so elegant, BUT it's waaaay better than simulating for a few weeks only to find that things were not right! Of course I don't understand the complications involved, but I'm quite disappointed that PETSc apparently has such a poor user interface. It doesn't give me much confidence in the code as a whole.

PETSc highly depends on the options to construct different combinations of solvers.  The same option could be different in different contexts by applying a bunch of prefixes.  The number of options is hug, and we do not store them in a database.  There is why we do not know that the options passed by users are valid or not.

**Comment by WilkAndy** [comment]
Cool beans, that sounds promising, thanks @fdkong !

**Comment by fdkong** [comment]
> If I understood correctly what the problem on PETSc side was, it was something along those lines. As PETSc constructs its objects, those options are being used and marked as used. So at the end you have the list of passed and used options so you can tell which were and which were not used.
> 
> In general PETSc code, you can be constructing and destructing all you want during the executions, therefore you have to wait until the end of execution. This would not be an issue for MOOSE, because we do not really rebuild PETSc objects on the fly. But, I am not sure there is a function we could call after the first step is solved. 

`PetscOptionsLeft(PetscOptions options)` prints to screen any options that were set and never used.

>At that time we would be almost sure (there might be a corner case) about what was used and what was not...

**Comment by permcody** [comment]
Yeah we know about that option but that doesn't work here. It'll print all
options to libmesh and MOOSE too which are valid. We have to use the PETSc
API to get those options and then subtract off the options that MOOSE and
libmesh use.

I already have a branch that does all of this. It's several years old but
still tagged on the original ticket. I guess we just have to run the
routine that's in there after the first time step.
