### ISSUE TITLE
Merge petsc_option and Executioner stuff?

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7131]
Tagging @fdkong

### Description of the enhancement or error report

At the moment i think we can specify petsc options (solver tolerances, etc) in the Preconditioner and/or the Executioner block.  I don't understand why this is.  Wouldn't it be simpler to just have one way of setting these things?

### Rationale for the enhancement or information for reproducing the error

Less confusing and cleaner for users.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Probably half the test suite will fail if either the "Executioner" or "Precondidtioning" method is turned off.  Bummer.

**Comment by friedmud** [comment]
Nah - it's like this on purpose... They are both useful.  The Executioner block is useful because not everyone needs complicated preconditioning.  The Preconditioning blocks are useful for when you need more advanced preconditioning and/or want to be able to swap out sets of PETSc options easily.

**Comment by WilkAndy** [comment]
I'm not convinced, @friedmud .  Couldn't we get rid of the preconditioner block entirely?  which block takes precedence , or does moose crash if you supply two values for a single petsc parameter?

**Comment by permcody** [comment]
Petsc options in the preconditioner block override the options in the executioner block if it's active.
This would be a huge change and a lot of our users are blissfully ignorant of the preconditioner block. However, others use it extensively.

**Comment by friedmud** [comment]
The preconditioner block is about MUCH more than just PETSc options... it
lets you choose how to build your preconditioning matrix... and even allows
individual moose-based applications the ability to plug in their own way of
applying preconditioners.

There is no getting rid of the Preconditioning blocks.

If you don't want to use them just ignore them!

**Comment by YaqiWang** [comment]
I think maybe we should check petsc options more carefully. For example, options related with libmesh nonlinear solvers are only allowed in Executioner block. On the other hand, options related with preconditioning are only allowed in Preconditioning block. This list can be easily broken by PETSc changes, but it worth a try considering we have Fande in the team now. As a previous newbie MOOSE user, I can see Andy's point: having two places in the input providing the same parameters are indeed confusing. Also allowing multiple preconditioning blocks can make this worse.

**Comment by permcody** [comment]
Sounds easy but "checking" Petsc options is actually quite difficult. As we've established in the past, you can't check them until you've solved something. So we can only tell you after the fact that something isn't right.

**Comment by YaqiWang** [comment]
That is not what I mean Cody. I was thinking to maintain a list of petsc options, like -snes_mf_operator, gmres restart number, etc, with a `MultiMooseEnum`. Only the options in the enum are allowed. We can have two enums, one for solver, one for preconditioner. Just a thought.

**Comment by friedmud** [comment]
It's fine the way it is... putting arbitrary restrictions on the options
you can use in one or the other would make it MORE confusing... not less.

Just find the way you like to specify options and stick to it.
