### ISSUE TITLE
Handling of Block, Boundary, and non-restricted objects in warehouses needs improvment.

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#7139]
### Description of the enhancement or error report

In general, as was the case with most of the old warehouses, in MOOSE is that objects that are **not block** restricted are added to the block restricted lists of objects on every subdomain. However, this can cause confusion and the handling of these lists is inconsistent within the compute objects and calls, including the setting of active variables.
### Rationale for the enhancement or information for reproducing the error

There should be three object lists: block, boundary, global. They should not contain the same objects, with the exception of an object that is both block and boundary restricted. Doing this will allow the various compute methods and MooseVariable dependency calls to be made consistent and hopefully generalized into a single function.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This will impact the internals of MOOSE and should have minimal affects on user facing API

**Comment by friedmud** [comment]
I vote for 4 lists: block, boundary, global, all

Sometimes you really do need to loop over "all"... and it would suck to have to build that on the fly.

**Comment by aeslaughter** [comment]
@friedmud You are correct.

**Comment by friedmud** [comment]
Actually - I'm going to push back on this change just a bit... this is going to slow things down.

The "normal" activity we want to do is get the list of Kernels (or whatever object) need to be evaluated on this block.  If we have to build that list on the fly (by combining multiple lists) that is going to be slow as hell... vs what we have now where the list is built up front and we are just getting a reference to it.

**Comment by aeslaughter** [comment]
The lists would **not** be updated on the fly, the lists are updated when
the object is added to the warehouse, as they are now. This part of the
change is trival with the current design.

The only change would be that non-block restricted stuff would be stored in
a separate list. This type of storage was used in a few warehouses in the
past, and I have some hacked up ComputeThread objects to make this work now.

The reason for doing this would be to make the getActive... calls be more
accurate and allow for MooseVariableDependency calls to be more consistent
as well (I am working on a related PR for this at the moment).

Also, there would be three distinct compute loops (global, boundary,
block), which again some compute objects have/had. This would also allow
for the block loop for certain objects to only loop over blocks that
contain objects being computed rather than every block, everytime, even if
you have nothing block restricted.

**Comment by friedmud** [comment]
@aeslaughter ugh... we're going to have to have multiple compute loops everywhere?  That REALLY sucks...

So we're going to have to duplicate this: https://github.com/idaholab/moose/blob/devel/framework/src/base/ComputeResidualThread.C#L105

And we're going to have to remember to do that _everywhere_?

Why?

All I want are all of the active objects on this block... I don't want to have to remember that "oh yeah, I also need to check to see if there are global active objects on this block"

If you want to have lists of objects that are block restricted... why not add those lists and add accessor members for that?  `getBlockRestrictedObjects(subdomain_id block)` sounds good...

**Comment by friedmud** [comment]
Also: if we were to go with your suggestion (multiple compute loops) the next time we add "another" designation for things we have to remember to go through the whole code and add another `for` loop to every compute function...

Doing it that way is just not the right design... it's exposing the storage internals through the API and not providing a good high-level interface.

**Comment by permcody** [comment]
I'm with @friedmud. The Warehouses need to be smarter not the compute loops. I just want to loop over all the right stuff in the compute loops. I realize there are issues with that, but it should be something that can be handled in the Warehouse.

**Comment by aeslaughter** [comment]
TheWarehouse had removed this need, see #14263
