### ISSUE TITLE
Idiot "resist" MooseEnum comparisons

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7141]
### Description of the enhancement or error report

Make MooseEnum throw an error if it's compared against a string that doesn't exist in the enum

### Rationale for the enhancement or information for reproducing the error

See the discussion:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/smUuQt3pnPA/2EFRVCKVBAAJ

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact, improved user diagnostics

**Comment by andrsd** [comment]
What about `allow_out_of_range` in the c-tor? If it is set to `false` we should bomb out, right? So if somebody has it set to `true`, we cannot check for "typos"... Am I missing something?

**Comment by permcody** [comment]
We won't be able to do anything for `allow_out_of_range` enums forget those. This is for the case where in user code you compare against a string that can never be true. We wouldn't know that during the constructor only by seeing the `rhs` in the `operator==` method.

**Comment by jessecarterMOOSE** [comment]
So it's still not idiot "proof"? :smile:

When does the test happen for `allow_out_of_range`?

For instance, where does the error get thrown? at (1) or (2) or both?
```
MooseEnum choice("this that", "this");
params.addParam<MooseEnum>("choice", choice, "Time to choose");

MooseEnum chosen = getParam<MooseEnum>("choice"); // <-- (1) check user input here

if (chosen == "other") // <--- (2) check developer input here (against original Enum??)
```

**Comment by permcody** [comment]
`allow_out_of_range` is more of a peacock trick. It's for when we want to have several common options available to the user (in a drop-down box) but we'll allow any option the user supplies presumably because we'll check it later. I think we only have two or three of these in the whole framework. It's really not the normal case.

**Comment by permcody** [comment]
So we already check user imput - just try it!
This ticket is to add the developer check in `operator==`.

**Comment by jessecarterMOOSE** [comment]
An alternate choice for (2) would be assigning a value to a member variable in the constructor via a ternary operator.
```
_chosen(getParam<MooseEnum>("choice")),
_v((_chosen == "other") ? _u : coupledValue("v")) // (2) Hmm... can you couple a variable to itself like that?
```

**Comment by permcody** [comment]
Why would you couple a variable into itself? Normally people want access to a zero vector if something isn't coupled in. Also, this isn't really related to MooseEnum at that point.

**Comment by permcody** [comment]
I fired that comment off without thinking about it. You aren't "coupling a value into itself", you are initializing a reference that you'll use later. From that perspective you can do whatever you'd like including bringing in the same variable that you are acting on but there's no need to do that since you _already_ have access to this variable as `_u`.

**Comment by jessecarterMOOSE** [comment]
I know this is an aside, but...
I'm modeling a phase change A -> B and trying to use the same kernel to model the change in A and change in B. The rate is proportional to A. The loss of A depends on the value of A (so I'm using _u), and since the gain in B is the same magnitude as loss of A, I bring in A as a coupledValue.

I could break this out into two kernels but then there'd be lots of code duplication. I suppose this is the reason for "base" kernels?

**Comment by friedmud** [comment]
This is off-topic... but you can couple a variable into a Kernel that's assigned to that variable... I even have code that does it.  The reason to do it is if you have a _very_ generic Kernel that's operating on MANY variables (especially if you're using vector coupling) and you just want to treat all of the terms the same way (even the terms arising from "this" variable).

**Comment by jessecarterMOOSE** [comment]
This is also a tangent --> b
