### ISSUE TITLE
Add derived Kernel class that provides additional gradients with respect to the undisplaced mesh even when operating on the displaced mesh

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7144]
### Description of the enhancement or error report
@cpritam is working on the Jacobian of the stress divergence kernel. The kernel operates on the displaced mesh, but the expression for the Jacobian contains terms such as the gradient of the shape function on the _undisplaced_ mesh. We have figured out how to access this. An intermediate base class could be used to encapsulate this functionality if other Kernels end up needing the capability.

### Rationale for the enhancement or information for reproducing the error
Make code cleaner, provide additional capability.

### Identified impact
Improve code that calculates the stress divergence Jacobian.

**Comment by permcody** [comment]
s/base class/BASE CLASS/

**Comment by friedmud** [comment]
This is a good idea.  Anyone trying to do anything like an ALE method will want this too...

**Comment by dschwen** [comment]
Any name suggestions? I'm having a hard time as you can see by the length
of the issue title :-)

**Comment by friedmud** [comment]
How about `ALEKernel`?

**Comment by dschwen** [comment]
Hmm, yeah. It is short. Ok, I'll go with that.

**Comment by andrsd** [comment]
> How about ALEKernel?

I want a `PilsnerKernel`... 🍺 😃

**Comment by tonkmr** [comment]
I just noticed that this doesn't reference the original issue #7028 that Pritam is working on. Now it does.
