### ISSUE TITLE
Steady State Parameter Names

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7145]
### Description of the enhancement or error report

The current Executioner parameter names for steady state detection are not the best and could use a good overhaul.  They are currently:

```
trans_ss_check
ss_check_tol
ss_tmin
```

A few observations:
- Why does one of them start with `trans`?  It's inconsistent and it separates it from the others in Peacock (I always forget that I have to set it)
- What does `ss` mean?  Why not `steady_state`
- Are we just "checking" it?
- What does `ss_tmin` even mean?

I suggest:

```
steady_state_detection
steady_state_tolerance
steady_state_start_time
```
### Rationale for the enhancement or information for reproducing the error

It's inconsistent currently... and hard to deduce for anyone new (or really anyone) what the options are for and hard to remember their name.
### Identified impact

The old members can be deprecated for a while... they are used quite a bit so we can have a lengthy deprecation period.  Since it's just changing the names it's not a problem to have both co-existing for a while.

**Comment by tophmatthews** [comment]
+1
I always forget to set ```trans_ss_check``` since it doesn't start with ```ss``
