### ISSUE TITLE
Make splines monotonic

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7158]
### Description of the enhancement or error report

Currently the SpineFunction fits cubic splines to data points.  However, the splines can be non-monotonic even if the data is monotonic.  Sometimes we need to ensure monotonicity, for physical reasons and to ensure good convergence of moose.  Assuming monotonic data, splines can be made monotonic by inserting extra data points between the original data points.  This is a pretty standard approach - i don't have the reference on the top of my head, sorry.

Pinging @dschwen and @andrsd because they have worked on SplineInterpolation.
### Rationale for the enhancement or information for reproducing the error

Mentioned above.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Nothing bad.  The "ensure_monotonic" will be a flag in SplineFunction, defaults to false.

**Comment by lindsayad** [comment]
@WilkAndy Do you have examples or literature which illustrates convergence issues arising from non-monotonic splines?

**Comment by WilkAndy** [comment]
Not from literature, only from my head.  In fluid-flow simulations there are various functions that can be measured experimentally, which could be represented by a spline interpolation from the experimental data (these functions are "relative permeability" and "capillary suction").  Physically these must be monotonic functions.  Numerically you get crappy convergence if you don't ensure monotonicity, because there is more than one solution!  The solver jumps around from one solution to another and takes a long time to converge.  Does this make sense?

**Comment by lindsayad** [comment]
Yes that makes perfect sense. I think I'm battling this issue myself, 
although the problem is the data I'm interpolating from is itself not 
monotonic. (It should be but I'm generating the data with a Monte Carlo 
method). Thanks Andy

**Comment by WilkAndy** [comment]
Ah, what a bummer for you.  It would be easy to ensure the data is monotonic, but in order to ensure the data produces a monotonic spline you may as well just implement the monotonic constraint in moose, hint, hint, nudge, nudge!

**Comment by lindsayad** [comment]
Haha it's possible that I'll get around to it.

**Comment by lindsayad** [comment]
How does something like this look Andy? Blue curve is traditional cubic spline. Red curve is monotone cubic interpolator. This algorithm does not enforce continuity of the second derivative. Is that something you need? I know for my own work I generally only care that the first derivative is continuous.

![montone_cubic_interpolator](https://cloud.githubusercontent.com/assets/10248304/20937844/3ef07a4a-bbae-11e6-8e01-6a44e5763a0d.png)

**Comment by WilkAndy** [comment]
I think that i only need continuity of first derivative too.  But i did think it was possible to ensure C2 continuity by placing two extra points in between each of your original data points?  I could easily be remembering wrong!

**Comment by lindsayad** [comment]
It is definitely possible...but the algorithm I used for the above was very neat and clean to implement. If you really want C2 continuity, I can do some more research...but I would be happy to stop here...haha

**Comment by WilkAndy** [comment]
i must say that i'm thrilled that you did this work.  It's definitely something that makes moose more of an "engineering tool" instead of just a "scientific tool".  I would stop here for now, but does your implementation provide methods to get the first and second derivatives?  I'd need at least the former for my Jacobians.  Also, does your implementation enable some sort of inspection of the resulting curve, eg, a csv file output?  This is so people can try to debug what's going wrong if they encounter problems.

**Comment by lindsayad** [comment]
I haven't written the sampleDerivative method yet, but it will certainly be there. And then within the interpolation intervals we can also have a sample2ndDerivative method. For inspection, I can look at what's done for SplineInterpolation and LinearInterpolation and mimic the same here. This will be a separate class from SplineInterpolation since the algorithm is fundamentally different (and without the C2 continuity it's not really a spline anyway)

**Comment by WilkAndy** [comment]
Sounds great, thank you.  I can't wait to see it merged into moose.

**Comment by lindsayad** [comment]
@WilkAndy If you can think of a good test for this, that would be awesome.

**Comment by lindsayad** [comment]
Unless you have something else in mind, I'll probably just do something like for `linear_interp_mat`

**Comment by WilkAndy** [comment]
Re tests...  I think i'd do the following:

 - do an explicit example where the data is monotonic and you know the answer, eg sample y=ax^3+bx^2+cx+d.  Check the derivatives too.

 - do an explicit example like you have above where you know the answer.  output the derivative and a finite-difference version of the derivative and check they're the same.  same for 2nd derivative.  check the derivative is > 0  (or is it >=0, i'm not sure).  

 - do an example with random monotonic input, calculate the derivative and demonstrate it's always positive.

Or did you mean that you wanted me to actually write a test instead of just proposing a test?

**Comment by lindsayad** [comment]
I've added a test corresponding to the figure I showed above. Don't you think that one check of y, y', and y'' with a "difficult" data set should be sufficient? It seems like three tests may be kind of redundant. I'm open though.

With respect to your second bullet and a comparison to finite differencing...are you suggesting using like a second order finite differencing scheme? Because the derivatives in general should be second order with respect to the independent variable (it being a cubic interpolation for y). In this fitting algorithm, it should be said that the derivatives are actually initialized using a second order accurate differencing scheme. And subsequently these derivatives are modified if they don't fall within the region of monotonicity. So in general I guess I wouldn't expect the derivatives to be equivalent to a second order differencing scheme, since that's my starting point and I modify them from there.

I could be missing your point though.

**Comment by WilkAndy** [comment]
Oh, wrt finite differencing: i just meant for moose to explicitly calculate (y(x+eps)-y(x))/eps for some small eps and compare with your y' output.

Yea, perhaps 3 tests are redundant.

**Comment by lindsayad** [comment]
Mmm...but that would only work for a data set that is a polynomial of degree <= 3 and monotonic right? Because a monotonic cubic curve wouldn't exactly reproduce an exponential for example (and thus it's derivatives wouldn't match either). So your first bullet point test might be good for this.

**Comment by lindsayad** [comment]
I've created PR #8193 in case you want to start playing around with this at all.

**Comment by WilkAndy** [comment]
Cool, thanks!

**Comment by lindsayad** [comment]
With @WilkAndy's permission, this could be marked closed by #8193.

**Comment by WilkAndy** [comment]
Thanks @lindsayad .  Closing this now.  I can always re-open in the very unlikely situation that i encounter some strange situation where your contribution doesn't work.

So, did the monotonicity fix your convergence problems?

**Comment by lindsayad** [comment]
It did. However, I now have an unrelated issue :-) Such is the nature of 
research.

**Comment by WilkAndy** [comment]
Cool that the monotonicity worked.
