### ISSUE TITLE
Automatic differentiation error

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7160]
### Description of the enhancement or error report
As described in libmesh/libmesh#998 the `DerivativeParsedMaterial` returns a zero derivative where it shouldn't. I'm in the process of tracking down this bug and will attach a simple input to reproduce this here.

### Rationale for the enhancement or information for reproducing the error
Fix wrong stuff.

### Identified impact
Make stuff right.

**Comment by dschwen** [comment]
If you are interested in reproducing this then rebuild lib mesh with `--enable-fparser-debugging`. The derivatives look fine if the `disable_fpoptimizer = true` option isn specified in the `DerivativeParsedMaterial`.

**Comment by permcody** [comment]
closed by #7376
