### ISSUE TITLE
ComputeVariableEigenstrain needs a test

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#7166]
### Description of the enhancement or error report

I can't seem to figure out how to set a eigenstrain that depends on a variable 

### Rationale for the enhancement or information for reproducing the error

Would help users get it working

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Better documentation

**Comment by dschwen** [comment]
The six tests and examples using `ComputeVariableEigenstrain` we already have are not enough?

**Comment by mangerij** [comment]
I guess I didn't see those. Would have assumed they would be in `tensor_mechancis/tests` 

Ok...

**Comment by dschwen** [comment]
The class was written with coupled phase field / mechanic applications in mind and the tests are using ICs from the phase field module. The combined module contains a lot of things, so I wouldn't make any assumption when looking for tests. It really is simple to find the tests. Either do a 

```
git grep `type = ComputeVariableEigenstrain`
```

Or use Shift+Cmd+F in atom and search for `ComputeVariableEigenstrain` in `*.i` files.

**Comment by mangerij** [comment]
Yeah thanks, I was just using the search function restricted to tensor mechanics and phase field... Didn't think to use atom

Thanks!
