### ISSUE TITLE
Add override keyword to examples, tutorials, framework and more...

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7171]
### Description of the enhancement or error report

I think the override keyword is a really nice feature in C++11 that we should go ahead and start using. It probably could have prevented a few errors in the past if people had been able to use it back then. The big benefit is knowing when new documentation needs to be added or not. I don't really like when people copy a base class and keep the same documentation for all of the virtual methods. We can start cleaning up that unless doco when we see the keyword override.
### Rationale for the enhancement or information for reproducing the error

Enhancement
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact

**Comment by WilkAndy** [comment]
OK, i think i get it.  There is a LOT of repeated header-file documentation in the TensorMechanics UserObjects.  Shall i simply add 'override' and then remove the repeated doco?

@permcody et al, perhaps you could write a monthly "C++11 enhancement" post to moose-users with stuff like this in it: explaining how to use a particular C++11 feature in MOOSE code.  You don't want to go overboard and post something every day, but i think every month I could stomach learning and applying something new!

**Comment by permcody** [comment]
On Tue, Aug 2, 2016 at 11:45 PM Andy Wilkins <notifications@github.com>
wrote:

> OK, i think i get it. There is a LOT of repeated header-file documentation
> in the TensorMechanics UserObjects. Shall i simply add 'override' and then
> remove the repeated doco?
>
This is my intention. Unless the headers are useful, they should be deleted
since they can be "inherited" from the base class.


> @permcody <https://github.com/permcody> et al, perhaps you could write a
> monthly "C++11 enhancement" post to moose-users with stuff like this in it:
> explaining how to use a particular C++11 feature in MOOSE code. You don't
> want to go overboard and post something every day, but i think every month
> I could stomach learning and applying something new!
>

Yeah this is a good suggestion. We are still working out how this override
documentation should really work. Not everyone is onboard with me deleting
all these repeated comments. Yeah... I don't know why either :)

**Comment by friedmud** [comment]
Instead of posts to moose-users... these things would make excellent blog
posts on the website...

**Comment by permcody** [comment]
We've done this through the whole framework but we can't enforce it. I'll close this for now until we figure out a way of enforcing this in the future. Maybe one of the compilers will allow us to do this someday.

**Comment by friedmud** [comment]
I have to say though: by doing what we've done it does make it fairly
"viral".  Since I usually copy an object and modify it to do something else
the `override`s are copied along... and then I _do_ get errors if I
introduce a new virtual function override and don't specify  `override`.  I
think that it has enough critical mass that the level of "overrideness"
will stay pretty constant in the framework.
