### ISSUE TITLE
Need a way to "perturb" initial_from_file_var

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#7185]
### Description of the enhancement or error report

Say we load in initial_from_file_var = u for the initial condition, I need a way of letting the initial condition be u + du where du is some user defined value (possibly random). 

### Rationale for the enhancement or information for reproducing the error

Would help Ferret do hysteresis loops for polar materials and would be nice to have in framework

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Just a new initial condition

**Comment by permcody** [comment]
You might want to do this with `SolutionUserObject`. I don't think that object is quite ready for random perturbations either but it'll be easier to mess with that over messing with `initial_from_file_var`.

**Comment by mangerij** [comment]
Thanks Cody,

This will be Ferret's first UserObject :+1: Or should this go to the framework? It's pretty general...

**Comment by dschwen** [comment]
With solution user object you can use a linear combination function and a
parsed function with a random term to augment the solution function

**Comment by mangerij** [comment]
While this would have been a good reason to dig into the code, there is a far simpler solution since we are using a diffusive method

Initialize an AuxVariable \delta P with RandomIC

Create a new Kernel class for "fluctuations" that acts on the variables that need to be perturbed using \delta P.

Evolve a new governing equation

dP_k/dt = - \gamma dF/dP_k + \deltaP_k 

where the last term is a "noise" term

**Comment by permcody** [comment]
Looks like we found a solution here. Closing this ticket.
