### ISSUE TITLE
Initial MultiApp failures should not be allowed

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7213]
### Description of the enhancement or error report
Currently we have a TODO at line 575 of `FEProblem.C`. It is basically allowing the multiapp on initial to fail to converge. When this does happen, transfer from multiapp to master will be skipped. This is pretty bad decision IMO.

### Rationale for the enhancement or information for reproducing the error
Users could see some really odd behavior because of this if he or she set the tolerance of his or her initial full solve multiapp too tight.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Should not have impact otherwise make bugs in the inputs show up.

**Comment by permcody** [comment]
I guess that's why it's marked TOOD!

**Comment by friedmud** [comment]
Hmmm... I'm sure there's some reason for it... but see if you can fix it ;-)

**Comment by YaqiWang** [comment]
In the `Transient`, failures is allowed which will set `lastSolveConverged()` to false. I guess it will trigger cutting the time step size. Let us see if anything is broken by this...
