### ISSUE TITLE
Time is not the current in the first Picard iteration before solveStep() is called

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7218]
### Description of the enhancement or error report
We have an aux kernel executed on linear require some setup on timestep_begin. Then we had a seg fault and figured out that it is due to `_picard_initial_norm = _problem.computeResidualL2Norm();` at the beginning of the Picard iteration when Picard iteration is on. Because that function call happens before the `timestepSetup()` is called. By checking the code further, we found that function call happens even before the current time is updated (which is in the beginning of `solveStep()`). So I think the initial residual evaluation for the Picard iteration should be moved a little down or the time step setup  a little up.

### Rationale for the enhancement or information for reproducing the error
If a material property depends on the time and is used by residual evaluation, the evaluated initial residual norm could be off quite a bit.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Do not know at this point. But this seems to me something needs to be fixed.

**Comment by friedmud** [comment]
Oh man - this was just changed recently...

**Comment by friedmud** [comment]
This is most likely caused by changes made here: https://github.com/idaholab/moose/pull/7133

**Comment by andrsd** [comment]
It is not. #7133 did not touch that code, it improved solution difference norm, not residual L2 norm.

**Comment by YaqiWang** [comment]
@permcody this could have been fixed, right?

**Comment by permcody** [comment]
Yes, #7480.
