### ISSUE TITLE
Remove active = in examples

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#7227]
### Description of the enhancement or error report

I don't think this is necessary in the example files. Any new user may copy over an input file and not change active lists and get an error.

### Rationale for the enhancement or information for reproducing the error

A number of times this has confused new users. It is an unnecessary piece of code for small input files and is only useful in debugging. Why have it?

I think one of the first things that should be clear to a new user is that the Parser will read all of the blocks you point in the input file. I'm open for a discussion but this has come up a few times when helping people get started with MOOSE.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Example input files become simpler.

**Comment by friedmud** [comment]
Fine by me... we should keep it in a frw places though where we show how to use it.

**Comment by andrsd** [comment]
I'd say, have at least one test that is exercising this feature, the rest of examples/tests do not need it. I use `active = ' '` from time to time to disable all objects within a block when debugging...

We were also using this when we were putting together input files for mammoth runs...

**Comment by mangerij** [comment]
Maybe leave it in /ex21_debugging/ and mention a blurb on the slides.

**Comment by friedmud** [comment]
I know there is at least one example where it is used on purpose. I think
it's the BCs example... It shows how you can swap out BCs by changing
active.

Leave it in that one.

Derek
