### ISSUE TITLE
Drop ComputeGrainCenterUserObject Refactor Volume and Centers Calcs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7233]
### Description of the enhancement or error report

The ComputeGrainCenterUserObject in the phase_field module doesn't work when n_grains > n_ops and overlaps in functionality "mostly" provided by the GrainTracker already.  Implement a better interface for centers and volumes in the GrainTracker and remove this object.

### Rationale for the enhancement or information for reproducing the error

Object only works for a limited set of small test problems.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

None.

Tagging @SudiptaBiswas and @itgreenquist

**Comment by SudiptaBiswas** [comment]
Yeah, we probably did not think about grain tracker when we developed this. Obtaining grain center and volume from grain tracker sounds great. I might have to rebuild the grain rigid-body motion tests & examples.

**Comment by permcody** [comment]
Do either of you have a desired interface?

```
const std::vector<Real> & getGrainVolumes() const
// or
Real getGrainVolume(unsigned int grain_num) const;
```

Note that you have to be careful with the former interface. Many of those grain volumes would be zero for grains that have disappeared (but you still need to know that). It's trickier to return the centers though for grains that have disappeared. The origin isn't a good choice since there might be a grain at the origin. Perhaps I need another method that you query first?

```
bool isGrainActive(unsigned int grain_num) const;
```

Also tagging @dschwen

**Comment by SudiptaBiswas** [comment]
The later looks neat it me. I am trying to think how this will impact associated rigid body motion objects. We have forces applied to the grain center, once a grain disappears the forces should disappear too. This might require a revisit to all other associated objects.

**Comment by SudiptaBiswas** [comment]
I am thinking can we not drop the userobject immediately? Can we keep it as a simple version for n_grains=n_ops case for now just to avoid breaking any associated objects? I will revisit those once I am done with my current PR.

**Comment by permcody** [comment]
The right way to do this is to deprecate the other object and let it hang around for awhile once the new object is ready. My intention is to add the API to the GrainTrackerInterface so that this still works for the simple case so actually this code may be moved to the FauxGrainTracker before everything is said and done.

**Comment by tonkmr** [comment]
One probable use case for the sintering stuff is to have multiple particles that are polycrystalline. That would mean that a rigid body particle would be composed of multiple grains. In that case, we would need grain tracker to look at individual grains but the rigid body stuff would need to deal with the larger particles.

I think we would leave ourselves open for this use case if we used FeatureFloodCount to get the volumes and centers. Then we could have grain tracker on for the grains and have a separate FeatureFloodCount to track particles. @permcody, do you think this could work?

**Comment by permcody** [comment]
It certainly could work. I'd love to see it used for something like that.

**Comment by itgreenquist** [comment]
I like the idea with FeatureFloodCount. My only worry would be with the problem I have been having with user objects changing the order of execution.

As for the interface I think that `bool isGrainActive(unsigned int grain_num) const;` looks like a really good option. I could see it being useful in a lot of situations.

Thanks for working on this.

**Comment by permcody** [comment]
On Thu, Jun 23, 2016 at 10:30 AM itgreenquist <notifications@github.com>
wrote:

> I like the idea with FeatureFloodCount. My only worry would be with the
> problem I have been having with user objects changing the order of
> execution.
>
> This isn't a problem, really.


> As for the interface I think that bool isGrainActive(unsigned int
> grain_num) const; looks like a really good option. I could see it being
> useful in a lot of situations.
>

Expect to see that soon

**Comment by permcody** [comment]
I haven't forgotten about this. I've been out of work unexpectedly the last two weeks. I'm working on this today.

**Comment by permcody** [comment]
I have the GrainTracker volume calculation refactors (the centroid will be trivial to add shortly). The code is much simpler and removes the need to duplicate code in the GrainTracker so it's a big win!

I have a design question though:
In refactoring, I noted that the logic to calculate the "Total boundary intersecting volume" was normalizing that value based on the volume of the domain:
https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/postprocessors/FeatureFloodCount.C#L865
Actually even this code is correct because it only worked for rectangular domains:
https://github.com/idaholab/moose/blob/devel/modules/phase_field/src/postprocessors/FeatureFloodCount.C#L854-L858

I further noted that there is an object called `NodalVolumeFraction` that takes volumes from the `FeatureFloodCount` object and normalizes them based on the actual domain volume (calculated by a separate postprocessor). It seems like a much better design. I think the right design would be to calculate "unnormalized" volumes and let the user decide what to do with them. Thoughts?

Ping @tonkmr, @dschwen, @laagesen

**Comment by laagesen** [comment]
I have not used this Object before, so take my input with a grain of salt, but I agree, I think I would rather have the raw volume reported rather than volume fraction.
