### ISSUE TITLE
Problem with complex numbers

### ISSUE THREAD

**Issue by torquil** [idaholab/moose#7251]
My Moose programs no longer compile, giving the following build error:

```
MOOSE Compiling C++ (in opt mode) /home/tmac/moose/framework/src/timeintegrators/TimeIntegrator.C...
/home/tmac/moose/framework/src/timeintegrators/TimeIntegrator.C: In constructor ‘TimeIntegrator::TimeIntegrator(const InputParameters&)’:
/home/tmac/moose/framework/src/timeintegrators/TimeIntegrator.C:35:28: error: invalid initialization of reference of type ‘libMesh::Real& {aka double&}’ from expression of type ‘libMesh::Number {aka std::complex<double>}’
     _du_dot_du(_sys.duDotDu()),
                            ^
```

I'm using the newest git version of moose, together with a preinstalled libmesh which supports complex numbers.

Best regards,
Torquil Macdonald Sørensen

**Comment by andrsd** [comment]
I do not think we ever compiled/ran with complex numbers on the library level.
If your PDE requires solution in complex numbers, you will probably need to split it into real and complex part (and have MOOSE built with real numbers). Just compiling with complex numbers would allow you to solve your PDE correctly.

**Comment by torquil** [comment]
I'm not using complex numbers in my Moose apps, but I would like Moose to use the preinstalled libmesh, which must support complex numbers for other reasons.

In libmesh there seems to be types libMesh::Real and libMesh::Number. Moose seems to use both in its source code, as seen in the above error message, where they get mixed up. Isn't libMesh::Number meant for code that should work for both real and complex numbers?

If Moose fails when libMesh::Number is std::complex<double>, shouldn't it then only use libMesh::Real instead of libMesh::Number everywhere?

In any case it would be very nice if Moose would work with a libmesh which supports complex numbers, even if Moose itself doesn't.

**Comment by friedmud** [comment]
Yep - you're correct... we've used Number and Real interchangeably in many
places... some of that was "on purpose" (many of those places are where we
_should_ allow complex numbers and it would be nice for them to work at
some point in the future)... but mostly it was just sloppily done (and I
can say that as I'm sure to be one of the largest offenders).

One thing that I don't know is if libMesh can do a "mixed" solve like this
at all.  As far as I know the solution vectors are always templated on
Number...

**Comment by torquil** [comment]
Thanks. But if it is not possible for Moose to use the preinstalled libmesh which supports complex numbers, how can I force Moose to use the libmesh which is "bundled" along with it instead?

I have built it using the script update_and_rebuild_libmesh.sh, and it is located in moose/libmesh/installed/lib, but framwork/libmoose-opt.so and any apps I create are linked against the preinstalled libmesh, not the one "bundled" with Moose.

If I uninstall the preinstalled libmesh, everything works fine, because then it using libmesh from moose/libmesh/installed/lib. How can I force Moose use that libmesh even when a preinstalled libmesh is present in a directory included in LD_LIBRARY_PATH?

**Comment by friedmud** [comment]
You could try setting LIBMESH_DIR to point to the libmesh installation
directory you want MOOSE to use.

But - if you've hardcoded something into your LD_LIBRARY_PATH that might
take precedence no matter what you do... that's not MOOSE's fault really...
the operating system manages that.

That said - we do use "rpath" to tie MOOSE-based executables to the dynamic
libraries they use... so LD_LIBRARY_PATH shouldn't really have an effect...
or at least I know it works that way on OSX.

Derek

**Comment by torquil** [comment]
Thanks, I have found a workaround which involves not having a preinstalled libmesh inside a directory mentioned in LD_LIBRARY_PATH. RPATH should take presedence over LD_LIBRARY_PATH, but apparently it is RUNPATH which is used by the GCC/LD when the -rpath argument is used, not RPATH. LD_LIBRARY_PATH takes presedence over RUNPATH, so that was why it did not work.

But I now have two libmesh installations (with and without complex number support), none of which are in the LD_LIBRARY_PATH. By using LIBMESH_DIR I can now make my programs use the one they need. Hopefully, MOOSE will be able to use the complex-enabled libmesh in the future so that I don't need both any longer.

Thanks for all you help!

**Comment by friedmud** [comment]
Glad you got it working!
