### ISSUE TITLE
Memory_logger.py could have an option for where the plot legend is positioned

### ISSUE THREAD

**Issue by amjokisaari** [idaholab/moose#7257]
The memory_logger.py script is fantastic. It's --plot output sets the legend to "upper left", which covers the resulting data line, usually.  

Having an input option of where the legend should be positioned will allow the user to make more beautiful and useful plots depending on their specific data sets.

An additional input option will be needed, perhaps with a default, and sane error messages if a correct option is not provided.

**Comment by milljm** [comment]
Merged
