### ISSUE TITLE
Add a fieldSplit preconditioner

### ISSUE THREAD

**Issue by fdkong** [idaholab/moose#7261]
### FieldSplit preconditioner

The basic idea of fieldSplit preconditioner is to decouple the system into several subproblems such that each subproblem can be effectively solved using existing preconditioners such as ASM, AMG, ILU, etc. The decomposition could be based on physics or others.

There already exists an incomplete implementation in MOOSE, but there are some issues:
(1) The preconditioner is constructed in an independent block [Splits]. The fieldSplit should be one subclass of the moose preconditioner.
(2) PETSc options for subproblems can not be correctly handled.
(3) DMMoose gets reconstructed during each Newton iteration. It is not efficient. DMMoose should be rebuilt only when we have to, for example, underlying nonlinear systems changed.

**Comment by mangerij** [comment]
When you fix (3), it would be nice to add a comparative plot or two to the wiki to show how this can speed up some coupled problems.
