### ISSUE TITLE
Add Dihedral Angles Calculation to Phase Field Module

### ISSUE THREAD

**Issue by jarinfrench** [idaholab/moose#7262]
### Description of the enhancement or error report

This would calculate the dihedral angles of a grain boundary at a triple junction.  I'm not sure if this would be better as a VectorPostprocessor or a UserObject.
### Rationale for the enhancement or information for reproducing the error

This would help in testing and validating the model for triple junction behavior and evolution.
### Identified impact

None

**Comment by jarinfrench** [comment]
I'm a little bit stuck with [lines 77-79](https://github.com/jarinfrench/moose/blob/b8bc6e78f7c44859c393dded92b12bc6b8ea01ad/modules/phase_field/src/userobjects/ComputeDihedralAnglesUserObject.C#L77-L79) not working.  I've tried a few different things, but I've mostly followed what was done in Marmot's AnisoGBEnergyUserObject with regards to using the gradient of the order parameters.  Including the dereference operator gave the error that the compiler didn't know what it was dereferencing. @dschwen and @karim86 do you have any thoughts?  There's still a way to go before this is finished, but at the moment I'm just trying to get the basic idea down.

**Comment by jarinfrench** [comment]
I just got it to compile... I had some parenthesis in the wrong spot.

**Comment by dschwen** [comment]
@jarinfrench what are you trying to do here? Storing angle sets per element? How are you accessing this data? Are you even sure that you can get meaningful angles from looking at the gradients in _one_ single element? 

It seems to me that a better approach would be to make this a UO that computes the angles for three specific grains rather than the entire cell.

**Comment by jarinfrench** [comment]
The goal is to do exactly that, but I'm having some difficulties in understanding how everything works together.  I've discovered that what I've been doing isn't going to work, so I'm working on getting the skeleton of a different method outlined.

How would I go about computing the angles for grains as opposed to cells?

I'll push the skeleton once I finish it, but it's mostly going to be comments.
