### ISSUE TITLE
Fix issue with Dirac point double counting in parallel.

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#7264]
### Description of the enhancement or error report
We have a long-standing issue where Dirac points can be double-counted in parallel if the Dirac point falls exactly on a processor boundary.  This is pretty easy to reproduce using the test in test/tests/dirackernels/multiplicity/multiplicity.i. 

See also #7149

### Rationale for the enhancement or information for reproducing the error
Run test/tests/dirackernels/multiplicity/multiplicity.i in parallel on two procs and four procs, you should get different answers.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Everything that uses DiracKernels in parallel.

**Comment by dschwen** [comment]
Hmm, I'm not entirely sure this is _a long-standing issue_. The test was added by me just a few weeks ago. It is possible that my change to the Dirac system, that allows points to be added multiple times with a resulting prefactor in the dirac contribution, is messed up in parallel now. I will not notice this issue, as I'm only using the add point method that takes an element as an argument.

I'll look at this issue (but I may not get to it before the TT).

**Comment by jwpeterson** [comment]
By adding a print statement, I believe I have confirmed that my suspicion about the PointLocator reporting the Point being found in different Elems on different processors is indeed the issue:

```
Point (x,y,z)=(     0.7,      0.5,        0) found in Elem: 69 on proc 0
```

```
Point (x,y,z)=(     0.7,      0.5,        0) found in Elem: 47 on proc 1
```

So the fix should be the one we discussed, i.e. doing an extra communication step to "pick" which element "wins" in this situation...
