### ISSUE TITLE
Catch return value in AddPeriodicBCAction::autoTranslationBoundaries()

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#7268]
### Description of the enhancement or error report
I noticed that `AddPeriodicBCAction::autoTranslationBoundaries()` calls ` _mesh->detectOrthogonalDimRanges()` but doesn't catch its return value.  

### Rationale for the enhancement or information for reproducing the error
If this function returns false, the user's `auto_direction='x y'` is not going to work.  We have a [Cubit journal file](https://drive.google.com/file/d/0B9BK7pg8se_iOFkzcDhmQzJ1STQ/view?usp=sharing) that generates a Mesh which does not seem to work with `auto_direction`, this could possibly be used to reproduce the error.

### Identified impact
If it turns out that `detectOrthogonalDimRanges()` is buggy, then we can fix it.  Would impact anyone using Periodic BCs and `auto_direction`.

**Comment by jwpeterson** [comment]
I tracked down the problem to `MooseMesh::getPairedBoundaryMapping()`, which returns (2,2) in the `auto_dirs` case for Dina's test mesh.  The periodic boundaries should actually be 3/4 and 5/6 on this Mesh however.  Still tracking down why this happens exactly.

**Comment by mangerij** [comment]
When you mention affect anyone using PeriodicBCs AND auto_direction, does that mean       manually setting the translation might also be buggy? If so how? 

I've long suspected one of our "standard" test cases has _something_ wrong and this is a situation where we have a 3D mesh and only periodicity along 2 dimensions.  This is also the case where using `auto_direction = 'x y' `doesn't work but manually placing the translational boundaries ends up solving.

**Comment by jwpeterson** [comment]
> When you mention affect anyone using PeriodicBCs AND auto_direction, does that mean manually setting the translation might also be buggy? If so how?

No, manually setting the translation vectors worked fine before, and should still work fine.

You might try your suspect case after my branch is merged and see if it starts working with `auto_direction`.

**Comment by mangerij** [comment]
OK, I thought that was the case.

I think my problem is a multitude of issues that really isn't on the high priority to debug at the moment -- the `auto_direction `issue is probably just convenience for me. But this will definitely save me some time!

**Comment by permcody** [comment]
This task is complete, right @jwpeterson?

**Comment by jwpeterson** [comment]
Yes.
