### ISSUE TITLE
ignore .jitcache directories

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#7273]
### Description of the enhancement or error report
I started seeing directories named `.jitcache` when I run `git status` after running the tests in the `combined` module.

### Rationale for the enhancement or information for reproducing the error
These are the directories I'm seeing:
```	CHSplitFlux/.jitcache/
	DiffuseCreep/.jitcache/
	GBDependentTensors/.jitcache/
	eigenstrain/.jitcache/
	elasticitytensor/.jitcache/
	multiphase_mechanics/.jitcache/
```
I assume this has something to do with use of parsed functions.  

### Identified impact
The fix here is probably to just add `.jitcache` to a `.gitignore` file.

**Comment by bwspenc** [comment]
@dschwen thoughts?

**Comment by dschwen** [comment]
I actually meant to drop that dir and just use .jitdir
Are you sure those are new?
