### ISSUE TITLE
Remove DiracKernel-based mechanical contact enforcement 

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#7283]
### Description of the enhancement or error report

We've been using contact enforcement based on the `Constraint` system long enough to confirm that it works better than the original implementation based on `DiracKernel` in every case we've looked at.  I think it's time to start the process of removing the old implementation.
### Rationale for the enhancement or information for reproducing the error

Keeping two systems around increases confusion for users and requires maintenance of more code.
### Identified impact

Remove all code related to `DiracKernel`-based mechanical contact enforcement.

**Comment by friedmud** [comment]
Noooooo!!!!!!!!  I made that!  ;-)

Just kidding... give it the boot!

**Comment by bwspenc** [comment]
We have a command `system = Dirac | Constraint` in the Contact action, and the current default is to use the `Dirac` system.  Here's the sequence of changes I'd propose:

1. Make the `Dirac` option deprecated. Generate warnings for models where `system` hasn't been specified and where `system=Dirac` has been specified.
2. Remove all code for `Dirac` enforcement after the deprecation period. At that time, keep the `system` command around, but make it deprecated (just so we don't break models that specify `system=Constraint` currently).
3. Remove the `system` command after its deprecation period.

**Comment by bwspenc** [comment]
@friedmud we'll give it a proper burial. If it's any consolation, just think of how many bazillions of times `SlaveConstraint::computeQpResidual()` has been called.

**Comment by friedmud** [comment]
Sounds like a good plan.

On the plus side: I invented the DiracKernel system specifically for this purpose... so at least that has other uses ;-)

**Comment by bwspenc** [comment]
@friedmud While I'm at it, I'm thinking of also deprecating `GluedContactConstraint` and `MultiDContactConstraint`. What do you think?

If I remember right, `GluedContactConstraint` was created just as a way to test `SparsityBasedContactConstraint`, which I think we should get rid of now since we have better ways of getting the connectivity.

`MultiDContactConstraint` is yours.  It uses the Constraint system to enforce glued contact. It's a heck of  a lot simpler than MechanicalContactConstraint, so it's useful as an example of how to use the Constraint system, but we don't use it in production. Maybe it makes sense to use it as the basis for a tutorial and move it with the other tutorials?

**Comment by friedmud** [comment]
I'd say it's up to you.  Sometimes it's useful to have simple "examples"
but sometimes it just adds maintenance and confusion...

**Comment by bwspenc** [comment]
Reopening because we still need to remove the deprecated `system` parameter in `ContactAction`.
