### ISSUE TITLE
Rewrite MultiSmoothCircleIC minimum spacing algorithm

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7296]
### Description of the enhancement or error report
The current algorithm looks clunky and uses variables to carry state across loops that should not be used (e.g. the current minimum distance is arbitrarily assigned values just to make certain comparisons fail or pass)

### Rationale for the enhancement or information for reproducing the error
Code can be made cleaner and more readable.

### Identified impact
Easier maintenance.

**Comment by dschwen** [comment]
ffe2922 has a first stab at it. It is shorter, uses fewer local variables (I eliminated 3!) and does not discard a viable center location if it happens to be found during the last try!

To break out of nested loops I'm using `goto` here. The jump distances are extremely short and documented using comments. I think the gains outweigh the potential reservations some people may have against the `goto` keyword :-)

**Comment by permcody** [comment]
Cool! This should probably be factored out into a PF utility so it can be used with the other IC types as well.
