### ISSUE TITLE
snesimpl

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7312]
### Description of the enhancement or error report

I can't compile PetscSupport.C   I need the following include line:

#include <petsc-private/snesimpl.h>

instead of

#include <petsc/private/snesimpl.h>

I have petsc/3.4.4

Tagging @fdkong

**Comment by WilkAndy** [comment]
Hmmm, that didn't come out well.  I need petsc-private/snesimpl.h instead of petsc/private/snesimpl.h

**Comment by permcody** [comment]
Yikes, we shouldn't be using any private files. Fande can you take a look
at that and remove them?

**Comment by andrsd** [comment]
AFAIK this is related to a PETSc version. Those private header files were moved, so some kind of `#ifdef` need to be fixed somewhere...

**Comment by fdkong** [comment]
I am trying to remove this private file.
