### ISSUE TITLE
Command-line edits for multiApp use

### ISSUE THREAD

**Issue by taoyiliang** [idaholab/moose#7315]
### Description of the enhancement or error report
Using command-line edits for input files when there are multiple apps involved results in the same edits being propagated to multiple input files instead of just the main one.

### Rationale for the enhancement or information for reproducing the error
The example is using multiApp MAMMOTH, which uses RATTLESNAKE as the main app and BISON as a secondary app.  The input files for each are `mammoth.i` and `bison.i`, respectively.  The run command I am using is
```
~/projects/mammoth/mammoth-opt -i mammoth.i Output/csv=true Output/file_base=example
```
When I run this, however, both MAMMOTH/RATTLESNAKE and BISON write to `example.csv`, resulting in a corrupted CSV file.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
My recommendation is that the command-line input interface be considered.  In early June this behavior was not observed, so it may be the result of recent changes.  I imagine this impacts all multiApps, but explicitly affects MAMMOTH.

**Comment by friedmud** [comment]
There is already a way to do this:

https://github.com/idaholab/moose/tree/devel/test/tests/parser/cli_multiapp_all
https://github.com/idaholab/moose/tree/devel/test/tests/parser/cli_multiapp_group
https://github.com/idaholab/moose/tree/devel/test/tests/parser/cli_multiapp_single

(look in the `tests` files for the syntax)

Let us know if that works for you...

**Comment by taoyiliang** [comment]
Experimenting by setting the `file_base` in the two inputs to `debug_mammoth` and `debug_bison` respectively.

Results of things I tried....

The nominal case,
```
~/projects/mammoth/mammoth-opt -i mammoth.i Outputs/file_base=debug_changed
```
results in a single output file, `debug_changed.csv`, which appears to have been written over twice and ending with the output from `mammoth.i`.

Adding a colon, as per the `cli_multiapp_all` example,
```
~/projects/mammoth/mammoth-opt -i mammoth.i :Outputs/file_base=debug_changed
```
resulted in two output CSV files, `debug_changed.csv` and `debug_bison.csv`, being created, which is the desired result.

It appears there is a way to do what I'm looking for; the surprising ~~issue~~feature for me was the default global propagation if no colon is used.  If that's the intended behavior, then I don't think there's an issue here, just a lesson learned.

**Comment by permcody** [comment]
The reason the default is to apply it everywhere is for backwards compatibility.
