### ISSUE TITLE
Run module examples with --check-input

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7319]
### Description of the enhancement or error report

We are not testing our example files currently and this leads to frequently broken examples. Many of our examples are quite heavy, _but_ it might be feasible to test them with the `--check-input` switch. We could even do that on PRs!
### Rationale for the enhancement or information for reproducing the error

Our examples should always run. Those may be the first runs a new MOOSE user launches (and thus the _first impression_ a user gets of MOOSE).
### Identified impact

More testing, may require a bit more resources on the test boxes.

**Comment by brianmoose** [comment]
Why don't we use the test harness for these? Each examples directory can have a "tests" file, type would just be "RunApp". If they are heavy them mark them as such and they will run at night. 
Otherwise they get tested along with everything else.

**Comment by dschwen** [comment]
Great idea! I can just use `cli_args = '--check-input'`

**Comment by dschwen** [comment]
Man, awesome, this works out of the box!!! Just drop in a tests file and boom its tested!

**Comment by permcody** [comment]
This is now being done. We are working on cleanup up the status messages from the point of view of the TestHarness. This ticket can be closed.
