### ISSUE TITLE
Solution to Solution Transfer

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#7342]
### Description
I am proposing creating a transfer that can transfer nonlinear variables between the master an sub-apps.

### Rationale
Solving the level set equation typically includes a re-initialization step that adjust the current solution to meet some criteria (i.e., signed distance). I am planning on doing this re-initialization by running a multiapp that does the adjustment and then passes the solution back to the master. That is the following will be done:

1. Solve the level set equation.
1. Pass the solution to a multiapp to re-initialize the solution.
1. Pass the solution from the multiapp back to the master and go to 1.

### Identified impact
I was able to get this working with a few lines changed in `MultiAppCopyTransfer` so I am thinking that this could just go into MOOSE rather than the level set module I am working on. Should this code:

1. Modify `MultiAppCopyTransfer` allowing the solution to solution copying (I vote for this b/c it will end up being less code since I also remove a bunch of duplicate code in the original class).
2. Create a base class and children objects that do the Nonlinear->AuxVariable and Nonlinear->Nonlinear transfers.
3. Do neither and create a transfer in the level set module.

**Comment by friedmud** [comment]
While I'm not against many of these solutions... why don't you just modify the solution directly (like in a GeneralUserObject)? Having a full copy of the mesh and solution vectors just to do this modification seems like a bit much... but maybe I don't know the details...

**Comment by aeslaughter** [comment]
The reinitialization is PDE that is solved to steady state, so I need to solve two problems on two different time scales. I suppose I could create a GeneralUserObject that creates a Problem, BCs, Kernels, etc. but that seems to be exactly what MultiApps are supposed to do.

**Comment by aeslaughter** [comment]
@idaholab/moose-developers can a few of you comment on this so I can figure out what direction I should go.
