### ISSUE TITLE
Improving LayeredIntegral

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#7346]
### Description of the enhancement or error report

Currently there are two things that bother me about LayeredIntegral:
1. The element centroid is used to determine which layer an element
   contributes to. This could be inaccurate if the element size is significant w.r.t. the layer size and 
   layers don't line up with mesh boundaries. 
2. The interpolation schemes inherently only use the average of each layer instead of realizing that
   you should accumulate modal information (slope/curvature) on each layer to reconstruct a linear/quadratic shape. When using the average, the resulting trace is discontinuous at the layer bounds which is unphysical for target applications e.g. linear power density (except maybe if there are pellet boundaries or a crack or something similar).  
### Rationale for the enhancement or information for reproducing the error

I would like to implement the following two changes:
1. Move the `getLayer(pt);` check into `computeQpIntegral` and use `_q_points` for this check.
   This is also related to @YaqiWang request for computing partial integrals, so XFEM could be used here, too. 
2. Add more sophisticated interpolation methods (discontinuous && continuous, different orders?). 
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
1. Using `getLayer(pt);` in  `computeQpIntegral` might slow down execution. 
2. More options to chose from when selecting the interpolation type.

**Comment by friedmud** [comment]
Wait - we should talk more about these changes. @mellis13  has been doing extensive work along these lines and I think that what he's done could guide the discussion.  Can we get together for a conference call early next week about it?  I don't want to see two parallel efforts on this...

**Comment by snschune** [comment]
I wasn't planning on doing work on this right away :). I'd be happy to benefit from @mellis13 experience.

**Comment by mellis13** [comment]
I'm happy to help out on this.

**Comment by snschune** [comment]
Should I send a meeting invite? How does Monday look like for you guys?

**Comment by mellis13** [comment]
Monday after 4 PM ET works for me.

**Comment by friedmud** [comment]
That time on Monday works for me as well.

Derek

**Comment by friedmud** [comment]
We had a conference call about this yesterday.

It was determined that @mellis13 and myself will try to move over some of the work he's done on more exact integration for `LayeredIntegral`s into MOOSE.

As for more sophisticated interpolation methods... that gets tricky.  We explained yesterday that @mellis13 has put a lot of working into doing something similar and it GREATLY complicates things.  For now, we're going to delay working on that.

I'm currently looking at @mellis13 's code to see how to improve `LayeredIntegral`
