### ISSUE TITLE
Inverse logic for checks in TestHarness

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7359]
### Description of the enhancement or error report

It'd be nice to be able to specify inverse logic for some of the tests in the TestHarness instead of enumerating all of the allowed targets.

```
method = 'OPT OPROF DEVEL ...'
method = ''!DBG'
```

### Rationale for the enhancement or information for reproducing the error

More options, better maintainability for tests over time

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

All test suites

**Comment by andrsd** [comment]
When people say:
```
method = '!DBG OPT'
```
They will get:
```
Multiple Negation Unsupported
```

This is misleading, it is not really multiple negation...
