### ISSUE TITLE
METHOD / METHODS in update_and_rebuild_libmesh

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7368]
### Description of the enhancement or error report
What exactly is going on in `update_and_rebuild_libmesh.sh` with regards to `METHOD` and `METHODS`?

Specifically, what is this?
 
https://github.com/idaholab/moose/blame/devel/scripts/update_and_rebuild_libmesh.sh#L39

Of course I have `METHOD` and `METHODS` both set... and of course they are set to different things (setting `METHOD="opt dbg oprof"` doesn't make any sense at all).

Normally you would have `METHODS` set to all the ways you might want to build and then you would set `METHOD` to the one you are currently using right now.  This is the way I work 100% of the time (but I usually don't use `update_and_rebuild_libmesh.sh`).  But this currently generates an error from `update_and_rebuild_libmesh.sh`!

In fact, I actually noticed a bit of what I just thought was brain damage in a post to moose-users the other day that is because of this.  Check out this post from Hans:

https://groups.google.com/d/msg/moose-users/0C-kOiUiTQk/lWGdxkFsAQAJ

When I saw it I was like "Why the heck is he unsetting METHOD before running `update_and_rebuild_libmesh.sh`???  Must just be some leftover brain damage"... but it's actually not!  It's actually required by the brain damage that's in `update_and_rebuild_libmesh.sh`!

I'm sure there's already been a discussion about this that I wasn't around for.  It looks like @jwpeterson changed this back in April.  What is the rationale for the way it's currently coded?  If there isn't one then this check needs to be removed as it's not right!

### Rationale for the enhancement or information for reproducing the error
Set both `METHOD` and `METHODS` in your environment and make them not the same.

### Identified impact
Removal of brain damage 😉

**Comment by jwpeterson** [comment]
IIRC @bwspenc requested that setting METHOD in the environment would override the default METHODS in update_and_rebuild_libmesh.sh.  If someone had *both* set in their environment, I didn't know which one should take precedence... but we can define one to have highr precedence than the other if you want...

**Comment by friedmud** [comment]
They do two different things (and have different value types... `METHOD` is only a single value where `METHODS` is a vector).  There shouldn't be a "precedence" at all.

Now, what I can see is that if you have `METHOD` set and you DON'T have `METHODS` set then it could be reasonable to set `METHODS=METHOD` like you do here: https://github.com/idaholab/moose/blame/devel/scripts/update_and_rebuild_libmesh.sh#L48

I suspect that's what @bwspenc was after.

**Comment by bwspenc** [comment]
Sorry for not responding sooner.  I've been out of the country with spotty internet. Yes, @friedmud this fix is in line with what I was after.
