### ISSUE TITLE
Compilation bugs in PetscDMMoose

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7369]
Tagging @fdkong 

Line 990 should be:
 DMMooseJacobian(DM dm, Vec x, Mat jac, Mat pc, MatStructure * msflag)
(no underscore on _dm)

Line 1080 should be:
  ierr = DMMooseJacobian(dm, x, *jac, *pc, flag);
(no underscore on _dm)

Line 1180 should be:
DMCreateMatrix_Moose(DM dm, const MatType type, Mat * A)
(no underscore on _dm)

line 2080 should be:
 ierr = PetscNewLog(dm, DM_Moose, &dmm);
(no underscore on _dm)

Sorry, i don't have time to go through all the git stuff myself right now...

**Comment by fdkong** [comment]
Are you using pretty old PETSc?

**Comment by WilkAndy** [comment]
Thanks @fdkong - works perfectly now.  Yea, i deliberately use an ancient PETSc just so i can pick up bugs.  Just kidding - my old PETSc is rather annoying, but unavoidable.
