### ISSUE TITLE
New Grain Tracker interface for better kernels/bcs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7373]
### Description of the enhancement or error report

@dschwen has requested (see #7367) a new GrainTracker interface method for retrieving the list of GrainIDs associated with all order parameters. This is support of more advanced PF simulations.

### Rationale for the enhancement or information for reproducing the error

New enhancement

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact to existing kernels at this time

**Comment by permcody** [comment]
Question: What value do you want in the vector for inactive ops at the given element, zero?

**Comment by permcody** [comment]
Note: The existing method `getElementalValues` already returns this information in a `std::vector` of `std::pair` where each pair has the grain id and the order parameter. I'm happy to add this new method since it's probably easier (and perhaps faster) in your kernels.

**Comment by dschwen** [comment]
How about libMesh::invalid_uint?

**Comment by permcody** [comment]
If you want `libMesh::invalid_uint` that's fine. I figured you might actually use these as an index though and if it's a huge number and you are careless that can really be annoying. Your choice.
