### ISSUE TITLE
recent "bug" in GrainTracker

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7399]
### Description of the enhancement or error report

I can't compile GrainTracker, @permcody, in its current form using my current compiler flags:

/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C: In member function ‘virtual void GrainTracker::finalize()’:
/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C:130:53: error: ‘class std::map<unsigned int, std::vector<unsigned int> >’ has no member named ‘emplace’
/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C:130:127: error: unable to deduce ‘auto’ from ‘<expression error>’

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
No member named "emplace" and something wrong with "auto"? How are you not running into problems compiling the rest of MOOSE? Those are normal C++11 features. What compiler are you using again?

**Comment by WilkAndy** [comment]
Sorry, my previous stuff was incorrectly formatted.  The rest of moose compiles (eg, the compiler can handle emplace_back), but this one line does work.  Compiler information is below

```
 MOOSE Compiling C++ (in opt mode) /apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C...
/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C: In member function ‘virtual void GrainTracker::finalize()’:
/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C:130:53: error: ‘class std::map<unsigned int, std::vector<unsigned int> >’ has no member named ‘emplace’
/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.C:130:127: error: unable to deduce ‘auto’ from ‘<expression error>’
make: *** [/apps/geomodel/moose/projects_andy/moose/modules/phase_field/src/postprocessors/GrainTracker.x86_64-unknown-linux-gnu.opt.lo] Error 1
wil04q@cemvmc:/apps/geomodel/moose/projects_andy/moose/modules> mpicc --version
gcc (GCC) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by permcody** [comment]
That's below the minimum
http://mooseframework.org/getting-started/

**Comment by WilkAndy** [comment]
Oh bummer.  It takes a long time to get things upgraded on my cluster - i've been in a queue for exactly 2 months now.  Hopefully soon i'll get an upgrade.  Until then i'll just comment out the offending lines.

**Comment by permcody** [comment]
Tell them it's an emergency or something!

**Comment by WilkAndy** [comment]
I feel sorry for them.  They're all good-quality people, but are completely snowed under with work.  There's a common misconception amongst managers that if you double a person's workload they'll produce double the work.  Unfortunately that's not true unless the original workload is under about 40% in my experience.
