### ISSUE TITLE
Migrate Transient Steady-state checking to use a postprocessor.

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#7403]
### Description
The steady-state checking performed by the Transient executioner should be able to support a postprocessor value for performing the check.

### Rationale 
Typically, the level set equation is solved with a reinitialization step. This step is a separate solve that is continued to steady-state, the criteria on which steady-state is achieved may vary depending on the reinitialization being performed. Therefore

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

There will be minimal impact to users. I plan on implementing this by moving the current check (`...currentSolution()->l2_norm()`) to a postprocessor. If the current option is used (`trans_ss_check`) the postprocessor would be created automatically. Should the output be hidden to keep behavior the same? And, should this option be deprecated in favor of requiring the user to add the PP to the input file (I think I would like this, it is more clear to the user what the steady-state check will be, an L2-norm)?

Another option would be created to use a PP: `trass_ss_postprocessor`.

**Comment by permcody** [comment]
I like the idea of moving it to a post processor. We have that `Terminator` post processor as well that can also terminate a solve early. I like the idea of supporting backward compatibility for a little while but am also fine moving away from it in the future. Hopefully we can boil down early termination to a single new intermediate post processor BASE CLASS or something to clean it all up.

**Comment by aeslaughter** [comment]
@permcody Are you proposing that [Terminators] become a new system, if so that would make MOOSE way cooler.

**Comment by permcody** [comment]
Not a whole new system. I'm suggesting that you create a simple intermediate base class that you can use from the Executioner. Perhaps a Postprocessor with one more virtual to request the stop.

**Comment by andrsd** [comment]
In RELAP-7, we terminate execution using the control logic system...

**Comment by aeslaughter** [comment]
I feel that is should look like this:

[Executioner]
   ... blah blah blah ...
  [./Terminator]
    type = SolutionL2Norm
    tol = 1e-8
  [../]
[]

The `Terminator` class would just inherit from the UserObject chain and add `bool terminate()` method.

**Comment by aeslaughter** [comment]
Actually, the Terminator should inherit from the Postprocessor set of objects. That way we can use PPs in either location.

**Comment by aeslaughter** [comment]
Should all Postprocessors be Terminators?

```
bool
terminate()
{
   return getValue() < _tol;
}
```

**Comment by aeslaughter** [comment]
@idaholab/moose-team Does anyone else have an opinion on this?

**Comment by friedmud** [comment]
I like it the way it is now.

Any `Postprocessor` can be used as a Terminator currently... and there's no reason for a whole system for this.

Also: the built-in steady state checking is super useful.  I don't want to have to define a whole Postprocessor / etc. just to do normal steady state checking.

In summary: it's fine the way it is.  People wanting simple steady state checking can turn it on right in the Executioner block... people with more advanced needs can create whatever set of Postprocessors they want and use it as a Terminator.

**Comment by aeslaughter** [comment]
Well crap, I didn't know (or didn't remember) we could do this already.

However, I would like to see the syntax for using the Terminator streamlined to something like I show here: https://github.com/idaholab/moose/issues/7403#issuecomment-235330602

**Comment by friedmud** [comment]
@aeslaughter The thing is... a Terminator might just be one one thing... and what should `execute_on` be?  Right now you can use multiple Postprocessors and tie them back together using a `GeneralPostprocessor` (or a `FunctionValuePostprocessor`) to produce the final outcome.  Each of those `Postprocessors` could have different `execute_on`, etc.

Really don't see the need for different syntax here.

**Comment by aeslaughter** [comment]
@friedmud You are probably correct, I just made a new UserObject for my levelset stuff that calls terminate itself, so I don't have a need for a PP. It now works like I want.
