### ISSUE TITLE
Add test harness test to run an arbitrary command

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7410]
### Description of the enhancement or error report
Woooo, scary! But the ability to run an arbitrary command (or at least another python script in the same directory) would allow us to generate data files on the fly (for example big EBSD data files with thousands of lines could be generated with a few lines of python).
Using `prereq` those scripts could be launched before the tests that need their output data.

### Rationale for the enhancement or information for reproducing the error
Simplify automatic test data generation.

### Identified impact
Fewer commits of large datafiles.

**Comment by permcody** [comment]
We already have this capability. Take a look

**Comment by dschwen** [comment]
Ugh, great... I guess

**Comment by dschwen** [comment]
What's that tester called?

**Comment by permcody** [comment]
It's not a tester. It's built into the RunApp Tester (I think) Ben put it
in for something similar so I don't know off hand.

**Comment by dschwen** [comment]
`post_command`? That is not a great design. Why not have a separate command tester. Then you can chain it however you want (pre or post) using prereq.

**Comment by dschwen** [comment]
Why did @bwspenc even add this. It is used in neither bison nor grizzly.

**Comment by bwspenc** [comment]
@dschwen, as explained in issue #2573, we added it to do some postprocessing on our assessment cases automatically after we ran them, but as you noted, we haven't gotten around to adding that to any of our tests, and it's been a couple of years now.  That's a little embarrassing, but I think it's still a useful option.  That sounds a little different from what you want anyway.

**Comment by permcody** [comment]
Perhaps we can replace post_command with a different design.

**Comment by bwspenc** [comment]
Sure, I guess when this tester that runs another app gets implemented, we can just chain it.  We could remove post_command and convert that test of it over to use this new tester.  That's fine with me.

**Comment by dschwen** [comment]
Yeah, that's the plan. Separate tester that can be chained using prereq.
That way I can also run it before a test.
