### ISSUE TITLE
InterfaceKernel needs to indicate if the current element is on the master side of the side set

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7422]
### Description of the enhancement or error report
The internal side set is specified by a list of elements and a list of their local side Ids. In MOOSE, the internal side is visited based on the natural ordering of elements, i.e. visiting elements first then loop through the element sides, skip the side when it has been visited. With this visiting algorithm, a side in a internal side set could be visited either the current element is the master element of the side in the side set or the master element neighbor. We should create an indicator in `InterfaceKernel` to tell if the current element is the master element or not, something like `_is_current_elem_master`.

### Rationale for the enhancement or information for reproducing the error
The depending interface kernels might relies on the definition of master element.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact because this is a new capability.

**Comment by friedmud** [comment]
❓ 

The master is always _this_ element.  Just define your sideset so that it's with respect to the master elements.

The `InterfaceKernel` won't ever be triggered from the slave side because the slave side doesn't even know about the boundary.

**Comment by YaqiWang** [comment]
The definition of sideset is completely independent. Users could choose a master element, which will not be the current element (current element is the one based on the element ordering). For example, in our `SideSetsBetweenSubdomains`, we can freely switch the master blocks and the paired blocks.

**Comment by YaqiWang** [comment]
After looking into the code, my understanding is possibly wrong. Let me double check before closing this issue.

**Comment by YaqiWang** [comment]
I confirmed what I said in the description is wrong. The current element and the master element are consistent always. The relevant code is in
https://github.com/idaholab/moose/blob/devel/framework/include/base/ThreadedElementLoopBase.h#L175 
https://github.com/idaholab/moose/blob/devel/framework/src/base/ComputeResidualThread.C#L188

So I am closing this. Sorry for scaring you.
