### ISSUE TITLE
Cluster Launcher Improvements

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7423]
### Description of the enhancement or error report

A number of simple things can be done to `cluster_launcher.py` to make it more useful:
1.  Automatically run parameter studies by varying an input parameter
2.  Automatically run scaling studies
### Rationale for the enhancement or information for reproducing the error

Make cluster launcher more useful.
### Identified impact

This system is used by some of the testing system so care will need to be taken that none of that is messed up.

**Comment by YaqiWang** [comment]
Will somebody work on this? I currently have to have my own script to create a `job_list` first and then call the launcher. If the launcher can accept something like `Mesh/uniform_refine=0:8` or `somesyntax=true|false`, it will be great.

**Comment by permcody** [comment]
If only I had the time... I'm super busy too. Maybe I'll see if @brianmoose wants to work on it 😄

**Comment by friedmud** [comment]
I ended up just rolling my own scripts for all of my current studies.  It
was easier than modifying Cluster Launcher.

It's hard to say if it's worth putting time/effort into a generic tool for
this.  Everyone wants something different... and in many cases ~15 lines of
Python gets the job done in exactly the way you want it done (that's the
case for me).

It's not always about how you run... it's also about what the output looks
like (what it's named... whether it goes into sub-directories, etc.).  It
all depends on how you're going to postprocess (which, BTW... I've been
doing by reading VectorPostprocessor output into Pandas Dataframes using
iPython notebook running directly on Falcon... works beautifully).

Doing this generically might just create a HUGE mess that no one would want
to use...

**Comment by YaqiWang** [comment]
Is this also somehow related with RAVEN? I am ok to close this. I have to admit that sometimes I have to change the job_list a little to put different wall times, number of nodes, etc.

**Comment by friedmud** [comment]
Not related to RAVEN for me.

Yeah: I have a script now where I can put in different combinations of
MPI/threads AND the approximate runtime for each combination... for bigger
jobs it's critical to make sure you're runtimes are close to reality.

**Comment by permcody** [comment]
cluster launcher was recently removed due to bit rot... It'll have to be reimagined, rewritten in the future.

**Comment by friedmud** [comment]
Bummer - I was actually using it a bit this weekend.... but it's not
critical!
