### ISSUE TITLE
Add VectorPostprocessorInterface to AuxKernel

### ISSUE THREAD

**Issue by hynok** [idaholab/moose#7427]
### Description of the enhancement or error report

AuxKernel  doesn't inherit from VectorPostprocessorInterface.

### Rationale for the enhancement or information for reproducing the error

Couple the VectorPostprocessorInterface values to an Auxkernel.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications 

- impacted)

No impact. 
@friedmud

**Comment by WilkAndy** [comment]
Good job on your first issue, @hynok !  In general you might include an example, or provide more detail, but as this problem has been discussed on moose-users it's probably not necessary in this case.  I try to remember that people in the future may read the issue to gain understanding of the problem and solution, and so try to provide a good amount of info, but I probably don't always get it right!

**Comment by friedmud** [comment]
Looks good to me - thanks @hynok!
