### ISSUE TITLE
A test recipe for applications is needed

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7431]
### Description of the enhancement or error report

An application could depend on MOOSE and/or other applications, which are treated as submodules. For most of applications, when MOOSE changes, our test robot will test the applications against the change and push the changes in the application submodule. But there are applications, for some reason, not updating the submodules automatically when MOOSE and/or the depending  applications changes. In such a case, it is desired to test the applications against the last MOOSE and/or the depending  applications automatically, so that the developers can be informed quickly if any inconsistency issues has been introduced. The test does not need to happen for every change in the upstream. Possibly a nightly test recipe is sufficient.
### Rationale for the enhancement or information for reproducing the error

To detect errors faster and make the fix easier.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Increase the efficiency of code maintenance.

**Comment by dschwen** [comment]
I wonder what the reason for not updating is. These application should probably just be added to the app tests and given the _allowable failure_ status. I guess if you do not add them to the submodule update recipe you will get testing without submodule updates.

**Comment by YaqiWang** [comment]
I am not against auto testing and merging. The only thing I can think of is the number of applications could be grewing large and any MOOSE change to be merged into master will be significantly delayed. On the other hand, the application with this recipe is not blocking the merge and required to be tested neither. It is like another way of thinking: my application is independent and I am responsible to make changes in my application when upstream is changed, but I want to know if I need to change as fast as I can. There could be software quantity issues for doing this I am not aware of.

**Comment by permcody** [comment]
Maybe.... I think we should try to get it to update.

**Comment by YaqiWang** [comment]
Because MAMMOTH app test has been in place, this issue can be closed. What we did now is to still test changes for the app but don't push the changes into app's submodule. We only do it when an app patch is required.
