### ISSUE TITLE
Get to bottom of sprint problem

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#7448]
### Description of the enhancement or error report
Get to the bottom of what's going on with Picard in the sprint problem.

### Rationale for the enhancement or information for reproducing the error
Talk to @YaqiWang and get to the bottom of it.

### Identified impact
*YUGE*

**Comment by permcody** [comment]
I'm going to close this particular ticket since it's rather open ended. We fixed many of the picard iteration and norm problems. Please open new tickets as needed.
