### ISSUE TITLE
Additional recipes for Nuc Apps

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7449]
### Description of the enhancement or error report

We need recover, threaded and parallel testing for the apps involved in the sprint 

### Rationale for the enhancement or information for reproducing the error

We need applications to run robustly for the sprint

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by brianmoose** [comment]
I added those steps to the recipes.
