### ISSUE TITLE
Add material to calculate stresses, strains, elastic energy analytically for inclusions

### ISSUE THREAD

**Issue by laagesen** [idaholab/moose#7452]
### Description of the enhancement or error report
This material will calculate stresses, strains, and elastic energies analytically for elliptical inclusions (precipitates) in a 2D, plane strain configuration. Inside the precipitate, the Eshelby solution is used. Outside the precipitate, the stresses and strains are calculated as described by X Jin et al., J. Elast., 114, 1-18 (2014).

### Rationale for the enhancement or information for reproducing the error
This will allow the stresses, strains and elastic energies from simulation to be compared to the analytical solution. The elastic energy will also be used to calculate the excess elastic energy in the KKS phase-field model coupled with elasticity.

### Identified impact
Should be none.

**Comment by mangerij** [comment]
Very cool. I'll have to look at this paper. We're doing some "inclusion" based stuff right now too.
