### ISSUE TITLE
Restart Fails with conditional Statements t_step==0 in Solid/Tensor Mechanics

### ISSUE THREAD

**Issue by mll36** [idaholab/moose#7457]
### Description of the enhancement or error report
Conditional statements looking for t_step == 0 or 1 cause restart to fail, since restarts resets the time step to 0 and applies the condition incorrectly on restart.  This issue causes on restart stresses and thus displacements to increase on first time step beyond what is expected. MOOSE also needs tests to verify that restarts work correctly.

### Rationale for the enhancement or information for reproducing the error
Correct statement should also check to see if restart with _tstep == 0 && !_app.isRestarting().

### Identified impact
Affects restarts for MOOSE and BISON

@sapitts @permcody

**Comment by permcody** [comment]
Closed by #7466, #7456
