### ISSUE TITLE
Clean up parameter names

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7488]
### Description of the enhancement or error report

Use `grain_tracker` consistently etc.
### Rationale for the enhancement or information for reproducing the error

Use same name for the same thing = less confusing
### Identified impact

Will break input files

**Comment by permcody** [comment]
I think we've got all of these. You can probably close this ticket.

**Comment by permcody** [comment]
We've cleaned up the specific parameter names mentioned in this ticket. Closing.
