### ISSUE TITLE
Re-enable max growth of time steps in FunctionDT

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#7497]
### Description of the enhancement or error report

I want to uncomment the lines 

```
  if (_cutback_occurred && (local_dt > _dt * _growth_factor))
    local_dt = _dt * _growth_factor;
```

in `FunctionDT.C`.

https://github.com/idaholab/moose/blob/devel/framework/src/timesteppers/FunctionDT.C#L105-L106
### Rationale for the enhancement or information for reproducing the error

I am running a Bison problem that gets into problems converging the nonlinear problem.
It cuts down the time step and achieves convergence after some steps cutting dt. That works fine and I am happy with it. However, after achieving convergence it would crank up the timestep to what the function dictates and then run through some cycles to get the timestep down again. 
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Uncommenting the lines does not break any tests. I am not seeing what exactly the problem with these lines is. 

pinging @andrsd

**Comment by snschune** [comment]
`IterationAdaptiveDT` has this capability. So I would either remove `growth_factor` from `FunctionDT` or re-enable it. Any opinions on this?

**Comment by andrsd** [comment]
Let me dig through the code to see why we commented it out...

**Comment by andrsd** [comment]
So, the reason why I commented it out was that when solve failed, the code would remove time knots when it was not supposed to. However, there was a recent fix that moved the knot removal code into `postStep` (it was in `acceptStep()`). So, it might be safe to uncomment these lines...
