### ISSUE TITLE
update update_and_rebuild_libmesh.sh to include new HDF5 method name

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#7506]
### Description of the enhancement or error report

This is a bit of a second-hand bug report but I figure I should let someone know.

Apparently, according to our HPC, somewhere in the version history of HDF5 a method name was changed. The newest NetCDF releases accounted for this change, but the MOOSE framework distributes an older version which requres

`sed -i -e 's/H5Pset_fapl_mpiposix/H5Pset_fapl_mpio/g' contrib/netcdf/4.3.1/libsrc4/nc4file.c `

after line 72 in the `update_and_rebuild_libmesh.sh` script to compile. Related:

http://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2014/msg00188.html

### Rationale for the enhancement or information for reproducing the error

We're compiling with `hdf5/1.8.17-gcc-mpi` and if you don't include this, the libMesh compile fails.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Reduce need to hack the build libMesh script for newer netCDF

**Comment by permcody** [comment]
Tag @jwpeterson

**Comment by jwpeterson** [comment]
This isn't really something we want to add to update_and_rebuild_libmesh.sh in general, as it would break people using older HDF5s... the right solution is to update the version of NetCDF that is distributed with libmesh, but this hasn't been a high priority for us because HDF5 hasn't been used in MOOSE much... Along those lines, are you actually using HDF5 for something in your app?

**Comment by mangerij** [comment]
No we are not. 

I'm not sure why the HPC support needed to add this -- they reworked their file system and the packages/libraries that were installed before allowed me to just follow the SingleUserCluster instructions on the MOOSE page. They disappeared in the rework. 

They've been guiding me on a recompile on UConn's cluster for some months now and this was what was needed. I'll just proceed with adding that line for the immediate future.

**Comment by dschwen** [comment]
Why don't you just run `./scripts/update_and_rebuild_libmesh.sh --disable-hdf5` then?

**Comment by mangerij** [comment]
That's probably the best solution then. I didn't know if this was something to report or not.
