### ISSUE TITLE
VectorPostprocessors - CSV output at the end of last time step

### ISSUE THREAD

**Issue by zahom** [idaholab/moose#7511]
### Description of the enhancement or error report
Need to have an option in VectorPostprocessors to get output csv files at the end of the run (last time step).

### Rationale for the enhancement or information for reproducing the error
Many times we are interested in the final result rather than at every time step.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by friedmud** [comment]
Should already work... just use the execute_on=final option in the CSV
output block

**Comment by WilkAndy** [comment]
Perhaps you don't have execute_on = timestep_end in your VectorPostprocessor ?

**Comment by permcody** [comment]
I believe 'execute_on=final' is only supported for Outputs. Perhaps Andrew
can shed some light on this?

**Comment by zahom** [comment]
These are the last two blocks of my input file:

[VectorPostprocessors]
  [./clad_dia]
    type = LineValueSampler
    *execute_on = final*
    variable = disp_x
    start_point = '0.0084 0.0001 0'
    end_point = '0.0084 0.1133 0'
    num_points = 300  # Randomly picked for the time being
    sort_by = id
  [../]
[]

[Outputs]
  exodus = true
  print_linear_residuals = true
  print_perf_log = true
  [./outfile_1]
    type = CSV
    file_base = output_vec_fn
  [../]
  [./outfile_2]
    type=CSV
    file_base = output_all_fn
    execute_vector_postprocessors = 0
  [../]
[]


AND THIS IS THE ERROR, I AM GETTING:

*** ERROR ***
Invalid option "FINAL" in MultiMooseEnum.  Valid options (not
case-sensitive) are "none initial linear nonlinear timestep_end
timestep_begin custom".

Thanks,

- Mudasar

On Tue, Aug 9, 2016 at 7:57 AM, Cody Permann <notifications@github.com>
wrote:

> I believe 'execute_on=final' is only supported for Outputs. Perhaps Andrew
> can shed some light on this?
>
> On Mon, Aug 8, 2016 at 11:46 PM Andy Wilkins <notifications@github.com>
> wrote:
>
> > Perhaps you don't have execute_on = timestep_end in your
> > VectorPostprocessor ?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/idaholab/moose/issues/7511#issuecomment-238459527>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-
> auth/AC5XIAXeo0eo9XN4OOWuTLsx_QGeLZ31ks5qeBRDgaJpZM4Jfgbl>
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_7511-23issuecomment-2D238560839&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=gD1jY_tzGB7QG5snjD122xz4uN2s8tB6VtGFUTq6C1g&m=IUNWviGpNHpigovNHlIVKr1QBEAdKM4ZIU0eeahYAV8&s=cgcdLi5S5ZlONw8hQ3OHQ1U8jTnTxwLZ95ZWXjpMos8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM0a2uGHjeZ8ZHdowsG3AsSw-2DyghOaqTks5qeIc7gaJpZM4Jfgbl&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=gD1jY_tzGB7QG5snjD122xz4uN2s8tB6VtGFUTq6C1g&m=IUNWviGpNHpigovNHlIVKr1QBEAdKM4ZIU0eeahYAV8&s=1qr-wGq523mUIegwVXd2OaVdSuuIHSO-Qj41YjsuCQU&e=>
> .
>



-- 
*Mudasar Zahoor, PhD*
Computational Scientist
Fuels Modeling & Simulation
*Idaho National Laboratory*
T: (208) 526 2616
F: (208) 526 2390

**Comment by permcody** [comment]
Tagging @aeslaughter

**Comment by friedmud** [comment]
Put the `execute_on` in the CSV output block like so:

[./outfile_1]
type = CSV
file_base = output_vec_fn
execute_on = final
[../]

**Comment by aeslaughter** [comment]
@friedmud has this correct, I was thinking you wanted to execute the postprocessor on final, which is not supported.

**Comment by zahom** [comment]
Thanks Gentlemen! It worked with Derek's suggestion.

Best,

- MZ

On Tue, Aug 9, 2016 at 1:49 PM, Andrew E Slaughter <notifications@github.com
> wrote:

> @friedmud
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_friedmud&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=gD1jY_tzGB7QG5snjD122xz4uN2s8tB6VtGFUTq6C1g&m=BuWb3_C400JAjM37Dj_DkwGlmKkiUho7KFqC_4zNXLU&s=HiMnn-DJ74lc_QWCeceW_iKrG8CUsyhSVI6ShYFwogc&e=>
> has this correct, I was thinking you wanted to execute the postprocessor on
> final, which is not supported.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_7511-23issuecomment-2D238669792&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=gD1jY_tzGB7QG5snjD122xz4uN2s8tB6VtGFUTq6C1g&m=BuWb3_C400JAjM37Dj_DkwGlmKkiUho7KFqC_4zNXLU&s=UlITGetdSgC4RwIit5xo4lNpk_blBzOk8usGoRl4kF4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM0a2n1p2NaP8ODL2kCOMoQIXNbI-2D6G-5Fks5qeNnQgaJpZM4Jfgbl&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=gD1jY_tzGB7QG5snjD122xz4uN2s8tB6VtGFUTq6C1g&m=BuWb3_C400JAjM37Dj_DkwGlmKkiUho7KFqC_4zNXLU&s=_hajr7so9wUYWzSYGZkGazeu7bMDwItHk__CLXFxx1Y&e=>
> .
>



-- 
*Mudasar Zahoor, PhD*
Computational Scientist
Fuels Modeling & Simulation
*Idaho National Laboratory*
T: (208) 526 2616
F: (208) 526 2390

**Comment by zahom** [comment]
Perfect!!

Thanks!
