### ISSUE TITLE
Refactoring towards memory reduction in FeatureFloodCount/GrainTracker

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7519]
### Description of the enhancement or error report

When running a large 3D grain growth simulation (180^3 elements) on 1600 ranks. I noticed a drastic increase in resident memory (~5 GB -> ~6GB) right after the parallel allgather operation and deserialization. While this may not matter in the larger scheme of the already enormous amount of memory a 3D phase-field simulation takes, it certainly doesn't help. It would be nice if the FeatureFloodCount/GrainTracker could use a little less memory.

### Rationale for the enhancement or information for reproducing the error

Better CPU utilization on large runs

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Hopefully no impact, just performance and memory optimization

**Comment by friedmud** [comment]
Bummer.

**Comment by permcody** [comment]
Why bummer? This isn't that bad. I probably wouldn't bother since the solve itself uses more memory than the global replicated data structures. However, I am working on a CS PHD so this is actually a good task, academic or practical. Instead of a allgather, it'll be an gather with the root process doing all the work. Then there will be a few more communications to notify the other processes of what ids to use and also comminication when remapping occurs. All excellent CS things!

I'll implement the MPI_SCATTER operation too.

**Comment by friedmud** [comment]
Meh - just kind of a bummer because you have to take your nice datastructure and flatten it for efficiency ;-)

Certainly not the end of the world...

**Comment by permcody** [comment]
I think it's actually easier to understand this way

**Comment by permcody** [comment]
Closed after several refactoring PRs
