### ISSUE TITLE
Post-processor for outputting residual norm for individual nonlinear variable

### ISSUE THREAD

**Issue by yidongxiainl** [idaholab/moose#7523]
### Description of the enhancement or error report

Below is an example to show that people would like to save the residual norm for each individual nonlinear variable, e.g., rho, momx, momy, rhoe, after each time step. A new post-processor is needed to achieve this.

Time Step 82609, time = 3.79817
                dt = 4.59777e-05
 0 Nonlinear |R| = 4.495244e-02
      0 Linear |R| = 4.495244e-02
      1 Linear |R| = 2.802480e-05
 1 Nonlinear |R| = 3.263639e-03
 Solve Converged!

Outlier Variable Residual Norms:
  **rho: 1.008155e-04
  momx: 1.292807e-03
  momy: 2.671458e-04
  rhoe: 2.983029e-03**
Steady-State Relative Differential Norm: 3.05503e-05
### Rationale for the enhancement or information for reproducing the error

This feature is of particular importance to monitor and diagnose the convergence quality of a computational fluid dynamics (CFD) solver. **Indeed, in most of peer-reviewer journal articles for CFD algorithm development and assessment, the plot of individual variable residual norm vs. time step is mandatory to show the performance of the developed CFD code.**
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by yidongxiainl** [comment]
@andrsd Does the description look clear enough?

**Comment by GiudGiud** [comment]
This is solved by this postprocessor
https://mooseframework.inl.gov/source/outputs/VariableResidualNormsDebugOutput.html
