### ISSUE TITLE
including a markdown page with links does not work

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#7526]
When including markdown pages which within themselves contain markdown links, the link does not get rendered. Example:

file_A.md:

```
  Go to the following link: !{content/file_B.md}
```

file_B.md:

```
  [link name](http://some.location.com/)
```

file_A.md renders with literal text`[link name](http://some.location.com/)` instead of a markdown link.

I would like to make use of 'include markdown links', so that I only have to maintain one file containing a list of moose-environment package versions available for download.

**Comment by aeslaughter** [comment]
@milljm Didn't we get this working?
