### ISSUE TITLE
Develop an AxisymmetricCenterlineAverage Postprocessor

### ISSUE THREAD

**Issue by gambka** [idaholab/moose#7528]
### Description of the enhancement or error report
The new postprocessor will calculate the average value of a variable along axis of symmetry in an axisymmetric simulation. 

### Rationale for the enhancement or information for reproducing the error
Need the ability to output the average value of a variable along the centerline of an axisymmetric model.  

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New feature.

**Comment by permcody** [comment]
I'm really surprised we don't have this. Really?

**Comment by gambka** [comment]
I haven't found something that does this. If this capability exists and someone could point me to it that would be great.  SideAverageValue does not work because it divides by the _volume which goes to zero as R-->0 and you get Nan's.  The AverageNodalVariableValue works but only if you have an evenly spaced mesh.
