### ISSUE TITLE
Contact doesn't behave correctly after a failed solve

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#7544]
### Description of the enhancement or error report

If a solve with mechanical contact fails and is attempted again with a smaller step size, the solution in that second step can be incorrect.
### Rationale for the enhancement or information for reproducing the error

Stateful data in the penetration info object is not correctly managed. This includes `contact_force`, `accumulated_slip`, `frictional_energy`, and `mech_status`, as well as the coordinates of the contact point. This is mostly an issue for frictional contact. We have run a large set of the contact verification tests in a way that forces them to fail and cut back the step, and then compared them with runs that use the smaller step to begin with, and their solutions don't match.
### Identified impact

Changes to `MechanicalContactConstraint.C`

**Comment by permcody** [comment]
Closed by #7545
