### ISSUE TITLE
EBSDReader needs to provide average feature info for specific phases to GrainTracker

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#7566]
### Description of the enhancement or error report

In EBSDReader, we need to be able to GetAvgData for a single phase when necessary, and GrainTracker needs to sync with EBSD features from only single phase.
### Rationale for the enhancement or information for reproducing the error

Currently, when GrainTracker pulls in average grain info from EBSDReader it pulls it in for all phases. This problematic when we are only using GrainTracker to represent features from one specific phase.
### Identified impact

This will resolve current issues when EBSDReader is used with GrainTracker see in #7401.

**Comment by dschwen** [comment]
I have already discussed this with @permcody . EBSDReader already has those interfaces. It is just a matter of GrainTracker using them.

**Comment by tonkmr** [comment]
Sounds great. Should I modify this issue to be about GrainTracker rather than EBSDReader?

**Comment by dschwen** [comment]
I think so. When @permcody gets to it I can sit down with him to make sure EBSDReader really provides everything he needs and how he needs it.

**Comment by permcody** [comment]
Let's chat about this next week.

**Comment by tonkmr** [comment]
The urgency to get this fixed is pretty high. I think that @frombs needs this done as soon as possible.

**Comment by permcody** [comment]
Wait - I thought you needed the other ticket fixed #7401. I'm happy to work on this too. Let me chat with @dschwen.

**Comment by tonkmr** [comment]
I believe that addressing this issue will fix the problem with #7401. There, we have two phases, the grains and the voids. So, GrainTracker is correctly tracking only the grains, but the data being passed to it by EBSDReader contains information about both phases. GrainTracker needs to only use the feature information from EBSDReader corresponding to the grain phase.

**Comment by permcody** [comment]
This work was completed long ago. There are now several tests that verify we can read individual phases from EBSD files into the GrainTracker. See https://github.com/idaholab/moose/blob/devel/modules/phase_field/test/tests/reconstruction/2phase_reconstruction4.i#L30 and similar tests in that directory.
