### ISSUE TITLE
Execute bits set when they shouldn't be

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#7571]
### Description of the enhancement or error report
There are a ton of files scattered throughout MOOSE that have the execute bits set when they shouldn't.

### Rationale for the enhancement or information for reproducing the error
That's bad. Most important, it's irritating for those of us who use colorized ls.

### Identified impact
Remove the execute bits on those files.

**Comment by permcody** [comment]
I'm not sure if there's any reason for anything other than the python and bash scripts to be executable. After these are cleared we should probably add additional pre-checks to prevent additional bad bits from being set.

**Comment by bwspenc** [comment]
@permcody After my commit, the only files in moose with execute permissions are ones with `.py`, `.sh`, and `.js` extensions, as well as files with no extensions like `run_tests`. Do `.js` files need to have the execute bit set?

**Comment by permcody** [comment]
They are technically scripts, but I'm fairly certain that the don't need the execute bit set. I could be wrong though so no need to change those right now.
