### ISSUE TITLE
Use std::cbrt(...) over std::pow(..., 1.0/3.0)

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7579]
### Description of the enhancement or error report
`std::cbrt(...) ` is the math function for the cube root. It is significantly faster than the equivalent `std::pow(..., 1.0/3.0)` 

### Rationale for the enhancement or information for reproducing the error
Why use pow if we have a dedicated cube root?

### Identified impact
Performance

**Comment by mangerij** [comment]
How much faster? 

Is there any way to benchmark this type of stuff? 

I have this issue sitting around in Ferret:

 https://bitbucket.org/mesoscience/ferret/issues/1/is-std-pow-causing-a-slow-down 

where I checked using std::pow and without and found some speed up without -- but i didn't vary the degrees of freedom or check really large number of processors. 

![1860807086-testtimings](https://cloud.githubusercontent.com/assets/7597716/17912141/79221560-6957-11e6-8c6a-ed9ef2c03f5d.png)
