### ISSUE TITLE
Need 2D test for block restricted DGKernels

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7603]
### Description of the enhancement or error report
Needed to protect multi-dimensional implementations of multiscale transport. `DGAdvenction` currently in test can be moved into framework.

### Rationale for the enhancement or information for reproducing the error
Our multiscale capability needs this.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None just more test and code shuffling.

**Comment by lindsayad** [comment]
What about #6042 and #5943? In that PR I made `DGKernel` inherit from `BlockRestrictable`. There should be a test that illustrates this capability in `/tests/dgkernels/dg_block_restrict`.

**Comment by YaqiWang** [comment]
Oh, great. Then I just need a test with 2 subdomains, where DG diffusion is solved only on 1 subdomain to make sure the solution is identical with a mesh just containing the subdomain.

**Comment by YaqiWang** [comment]
@lindsayad We probably can also promote `DGConvection` into MOOSE framework. I did not realized you have implemented it and thought MOOSE should have another DGKernel for convection for a long time.

**Comment by YaqiWang** [comment]
I will work on a PR to close this issue then. Thanks.

**Comment by lindsayad** [comment]
You're welcome. Please let me know if there are any issues.
