### ISSUE TITLE
Sign wrong in INSMomentumNoBCBC.C

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#7622]
@jwpeterson Shouldn't the sign [here](https://github.com/idaholab/moose/blob/devel/modules/navier_stokes/src/bcs/INSMomentumNoBCBC.C#L98) be negative? The volume term becomes positive upon integration by parts; the corresponding surface term should be the opposite sign. Otherwise I think the do nothing BC is saying `-_test * _normals * _sigma = + _test * _normals * _sigma`. Changing the sign allows what should be a flow through solution to go from non-converging to yielding very nice results:

Pressure:

![nobc_sign_fixed_p](https://cloud.githubusercontent.com/assets/10248304/17951256/66c85c10-6a26-11e6-8c66-9ca7c79546a3.png)

Axial velocity: 

![nobc_sign_fixed_v](https://cloud.githubusercontent.com/assets/10248304/17951259/6ff4cdb4-6a26-11e6-90fd-3f5c1c5e2593.png)

Note that here I am specifying an inlet profile for the axial velocity and do nothing boundary conditions at the outlet **without** specifying any conditions on the pressure. It should be noted that I only get these nice profiles when I don't integrate the pressure by parts. If I do integrate by parts, then I get oscillations in my radial velocity near the axis of symmetry, and an absolute maximum in the axial velocity near the outlet which makes no sense. I am still quite troubled why I can't get the simulation to look correct with integration_by_parts = true...but that's not the thrust of this issue.

Might this incorrect sign be the reason why pressure conditions had to be imposed in Martin's open_bc case?

**Comment by jwpeterson** [comment]
> @jwpeterson Shouldn't the sign here be negative?

I think you are right.

```
\rho du/dt - \div \sigma = 0 
->
(\rho du/dt, v)_{\Omega} + (\sigma, grad(v))_{\Omega} - (n \cdot \sigma \cot v)_{\Gamma} = 0
```

>  Might this incorrect sign be the reason why pressure conditions had to be imposed in Martin's open_bc case?

I don't know, can you try fixing the sign and updating that test?

**Comment by lindsayad** [comment]
Yea I'll look at that tomorrow.

**Comment by lindsayad** [comment]
So changing the BC's in the open_bc test to this:

  [./x_inlet]
    type = FunctionDirichletBC
    variable = vel_x
    boundary = 'left'
    function = 'inlet_func'
  [../]
  [./x_oulet]
    type = INSMomentumNoBCBC
    boundary = right
    variable = vel_x
    u = vel_x
    v = vel_y
    p = p
    component = 0
  [../]
  [./y_oulet]
    type = INSMomentumNoBCBC
    variable = vel_y
    boundary = right
    u = vel_x
    v = vel_y
    p = p
    component = 1
  [../]
  # [./inlet_p]
  #   type = DirichletBC
  #   variable = p
  #   boundary = left
  #   value = 1.0
  # [../]
  # [./outlet_p]
  #   type = DirichletBC
  #   variable = p
  #   boundary = right
  #   value = 0.0
  # [../]

gives us the result we would expect with an inlet profile of `-4 * (x - 0.5)^2 + 1`:

v_x
![vel_x_open_bc](https://cloud.githubusercontent.com/assets/10248304/17984461/d8baa340-6ad6-11e6-9535-d8ff9cda1aa4.png)

p
![p_open_bc](https://cloud.githubusercontent.com/assets/10248304/17984473/e697939c-6ad6-11e6-9009-01b9b77edd7d.png)

and v_y = 0 everywhere. I would say this is a good thing!

**Comment by lindsayad** [comment]
This works equally well whether the pressure is integrated by parts or not :+1:

**Comment by jwpeterson** [comment]
OK, cool.  Do you mind making a PR for this?

**Comment by lindsayad** [comment]
Yes, I can do that.

**Comment by mlesueur** [comment]
@lindsayad Hi Alex, are you working on the test [open_bc_pressure_BC.i](https://github.com/idaholab/moose/blob/devel/modules/navier_stokes/tests/ins/open_bc/open_bc_pressure_BC.i)?
This test has been set up to show the use of not integrating P by parts, which is the possibility of having a pressure-driven flow. This was not possible if you try to do it in the [open_bc.i](https://github.com/idaholab/moose/blob/devel/modules/navier_stokes/tests/ins/lid_driven/open_bc.i). It will converge to the wrong solution if you switch in the _inlet_ BC the variable u to the variable p.
So i think your changes should be applied to the open_bc.i file instead.

Also, even though I can understand the error that was in the old src file, I don't understand what it is changing... The old file was already converging (to the wrong solution ?) and even though the pressure pin was set, unchecking it didn't make a difference.
Actually I still don't understand the INSMomentumNoBCBC functionality, because not putting any BC at the outlet works fine for me, but I will talk about this on the [NS post](https://groups.google.com/forum/#!topic/moose-users/gI4ClxLn_78) that you recently opened

One last thing, i suppose that this open_bc test's purpose was to benchmark NS with the Poiseuille law, am I correct ?
In this case, Poiseuille was derived:
- for a pressure-driven flow
- in a semi-infinite domain in the x direction

Therefore Periodic Boundary Condition should be applied for velocity and the inlet should be pressure. I have done this test on my own and it works perfectly well.

Cheers,

Martin

**Comment by mlesueur** [comment]
Hey Alex,
I was just wondering what were the results with the old, wrong formulation of the do-nothing BC. The test was still converging with the wrong fomulation, wasn't it ?

**Comment by jwpeterson** [comment]
@mlesueur I'm not sure exactly what you are asking.  @lindsayad mentioned that, with the wrong sign, the new test would not converge.

By the way, I think the outlet velocity field is more correct with the new velocity-driven inlet + the nobcbc outlet (image:top), compared to the pressure-driven inlet + Dirichlet pressure outlet (image:bottom).  You can see that the flow turns outward unrealistically at the outlet in the latter case, so I definitely think we should revisit this test.

![combined](https://cloud.githubusercontent.com/assets/1775907/18057334/c79da5f0-6dcc-11e6-86f1-0ba648e75d9e.png)

**Comment by lindsayad** [comment]
@mlesueur Sure, with the wrong sign we converged to a solution, but it was the wrong solution. No assumptions are made beyond those normally made for incompressible flow. We are specifying an inlet velocity profile that is **already** a solution to the INS equations for this simple geometry, and thus that profile should not change as we move from the inlet to the outlet. Any other solution would be wrong for the inlet conditions I am specifying. I think now we have demonstrated that we can generate nice flow-through profiles by specifying inlet velocity and without specifying inlet and outlet pressures. Now one can certainly still specify pressure conditions if they choose to; but that's not my preference.

**Comment by lindsayad** [comment]
@jwpeterson @mlesueur I should clarify that I was unable to get convergence with the wrong sign for INSMomentumNoBC on a RZ test problem I'm working on in my application. In the 2D XY test case, I can get convergence with the wrong sign, but the solution is wrong. 

Thanks for the nice graphic @jwpeterson !

**Comment by jwpeterson** [comment]
@lindsayad Are you sure we can use the same kernels in RZ (modulo the multiplication by r which is already done by MOOSE) for incompressible flow?  I know this works for simple PDEs like the Poisson equation, but it's been a long time since I looked at the RZ form of Navier-Stokes...

**Comment by jwpeterson** [comment]
Specifically the 1/r d(r*u_r)/dr terms in the mass and momentum equations as seen [here](http://ingforum.haninge.kth.se/armin/AR_2000/HL2008/NAVIER_STOKES_EQ.pdf)?

**Comment by lindsayad** [comment]
Well that's what I'm trying to explore. As you point out, certainly changes are required in INSMass because we are applying the divergence operator and that introduces an additional term (specifically the one you just mentioned). I believe I have accounted for that [here](https://github.com/lindsayad/moose/blob/RZ_mass_kernel/modules/navier_stokes/src/kernels/INSMass.C#L85). I think that we are safe in the volume terms for INSMomentum because we perform integration by parts, and the gradient operator looks the same between cartesian and cylindrical coordinates. I have been able to produce a successful test for RZ without integrating pressure by parts (I think); see [this directory](https://github.com/lindsayad/moltres/tree/master/tests/laminar_flow). However, as soon as I try `integrate_by_parts = true`, the solution is wrong. I think the problem is with getting the right boundary condition on the axis of symmetry, but I'm not 100% sure yet.

**Comment by lindsayad** [comment]
Actually what I'm kind of thinking is that that the translation, from \nabla p into \nabla \cdot \mathbb{1} p after which we can integrate by parts, is invalid because the components of the divergence operator do not match the components of the gradient operator in cylindrical coordinates. @jwpeterson Any thoughts on that?

**Comment by jwpeterson** [comment]
Yes, I think you should end up with an extra term there as you did in the mass equation.  Page 14 of this [thesis](http://sma.epfl.ch/~deparis/publications/PhD_thesis.pdf) has the axisymmetric weak form, specifically (1.4).  There also appears to be an extra term coming from the viscous stress tensor.  The notation is a bit weird in this, I'm also looking around online for confirmation of these equations...

**Comment by lindsayad** [comment]
I think I can verify at least that with my change in INSMass.C, if I do not integrate pressure by parts, I get the correct solution. For fully developed flow in a circular tube, the analytical solution is:

u_z(r) = -R^2 / (4\mu) * (dP/dz) * (1 - r^2/R^2)

If I specify an inlet velocity profile of U(r) = 1 - 4r^2, with \mu = 1 and R = 0.5, then to satisfy the analytical solution, dP/dz must equal -16. This is what I observe in the numerical solution:

![correct_pressure_drop](https://cloud.githubusercontent.com/assets/10248304/18060129/3592baa4-6de2-11e6-96f3-be099bcd028c.png)

**Comment by jwpeterson** [comment]
And what about the velocity contours?  If you are missing a "\mu 1/r u_r  *v_r" term from the viscous stress tensor integration by parts, I'd expect it to affect the accuracy of the velocity field near the origin...

**Comment by jwpeterson** [comment]
Oh, but of course `u_r==0` everywhere in this problem, so if you are missing that term you won't notice it anyway.

**Comment by lindsayad** [comment]
Well, actually that's not really a great test since u_r = 0 here, so \nabla \cdot \vec{u} looks the exact same between XYZ and RZ

**Comment by lindsayad** [comment]
@jwpeterson Ok, I think I devised a reasonably intelligent test; let me know if you see flaws. I made a cone domain, with R_outlet = 2 * R_inlet. Same inlet velocity profile (u_r = 0, u_z = 1 - 4 * r^2). Because of the cone geometry, there will need to be radial components of the velocity within the domain. To test the solution, I integrate the velocity profile at the outlet, and see whether it matches the analytical integral at the inlet. This tests whether mass balance is maintained. The velocity integral at the inlet is .0625. With the RZ formulation of INSMass, the outlet integral is within .01% of .0625. Meanwhile, with XYZ formulation of INSMass, the outlet integral is .11, 80% different. Can you think of a better sanity check?

**Comment by jwpeterson** [comment]
Seems reasonable.  Are you also planning to test the pressure-term-integrated-by-parts version with the same setup?  It should be the same fix as in the mass equation, just on the test function instead of the velocity field...

**Comment by lindsayad** [comment]
Yes, going to try testing that tomorrow

**Comment by lindsayad** [comment]
Alright, I made a change [here](https://github.com/lindsayad/moose/blob/RZ_mass_kernel/modules/navier_stokes/src/kernels/INSMomentum.C#L108) that makes it so `integrate_by_parts = true` exactly reproduces the results with `integrate_by_parts = false`. Sample results below:

u_r, integrate by parts:
![rz_cone_u_parts](https://cloud.githubusercontent.com/assets/10248304/18096874/5d04e304-6ea1-11e6-918d-a1872bf8926c.png)

u_r, don't integrate by parts
![rz_cone_u_no_parts](https://cloud.githubusercontent.com/assets/10248304/18096886/688ea8ea-6ea1-11e6-9006-d5ce2f277071.png)

u_z, integrate by parts
![rz_cone_v_parts](https://cloud.githubusercontent.com/assets/10248304/18096898/6ff08ca2-6ea1-11e6-859b-258d429764c7.png)

u_z, don't integrate by parts
![rz_cone_v_no_parts](https://cloud.githubusercontent.com/assets/10248304/18096914/7835d110-6ea1-11e6-9b2e-08bf14922bab.png)

**Comment by lindsayad** [comment]
Can we add this to the framework? I would definitely like to have it for the fluid flow simulations I'm doing. Let me know if I should make a PR

**Comment by jwpeterson** [comment]
Images look good to me.  

I'd definitely like to add the RZ stuff (including tests) to the navier_stokes module.  I'm still working through the equations as I'm not 100% convinced there isn't an extra term or two coming from the viscous stress tensor integration by parts.  I will hopefully post a PDF later today for you to look over...

I'm also not sure if if-statements in the existing kernels are the way to go for the long term.  Another possibility is to have kernels derived from INSMass and INSMomentum that simply call the parent class `computeQpResidual()` functions and then add the extra terms.  But this would not preclude your initial changes from being merged in.

**Comment by lindsayad** [comment]
See #7651 and #7652. As you say, the code might not be 100% desirable, so let me know if there are changes you want me to implement.

**Comment by mlesueur** [comment]
@lindsayad putting this NoBc BC on a pressure-driven flow (with no integration of the pressure by parts) makes the solution converge exactly to the Poiseuille solution, unlike the test [open_bc_pressure_BC](https://github.com/idaholab/moose/blob/devel/modules/navier_stokes/tests/ins/open_bc/open_bc_pressure_BC.i) that @jwpeterson was talking about.

I've tested different implementation that actually makes this test, [open_bc_pressure_BC](https://github.com/idaholab/moose/blob/devel/modules/navier_stokes/tests/ins/open_bc/open_bc_pressure_BC.i), converge to the Poiseuille solution.
Current BCs are:

- P=1 on the left
- P=0 on the right
- no-slip top and bottom

Adding these BCs makes the solution converge to Poiseuille:
- no-slip of y on right
- using Periodic BC in x direction (for velocity only to keep pressure gradient equal to 1)
- using NoBc BC for x and y on the right

convergence for Poiseuille is evaluated when comparing average x-velocity on the volume to the solution 0.83333...
I wanted to know if:

- second solution is the most general case
- third solution is applied to NS problems
- first solution is applied to this NS problem only (flow in a tube)

The second solution is quite expensive. Yours should be the most relevant in the NS module and in addition you said that it makes it better to add it directly to the residual.

@jwpeterson I think we can indeed revisit the tests of the pressure-driven flow by doing a test comparing a csv file for example ?
