### ISSUE TITLE
FEproblem::advanceState() issue

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7631]
### Description of the enhancement or error report
If I am understanding correctly, it copies current solution to old, old solution to older. The current solution remains unchanged. But it calls `shift` for stateful material property, i.e. `MaterialPropertyStorage::shift()`, which actually changed the current property. I do not understand this inconsistency.

### Rationale for the enhancement or information for reproducing the error
To me the current stateful properties should not be changed in `advanceState()`.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
I do not know the purpose of this design, so the impact is unknown to me.

**Comment by friedmud** [comment]
Two reasons why it's done:

1.  We don't require that MaterialProperties are copyable... So we can't copy them.

2.  Speed... all shift does is swaps pointers around which is crazy fast.

So: now my question to you: why is the current behavior a problem?

**Comment by YaqiWang** [comment]
It is not a problem. It is just something out of ordinary. One would think he starts the new time step solve with the previous solution as the initial guess. But with stateful material properties, this statement is no longer completely true. I noticed this because I just implemented a stateful material property. There should not be any reevaluations at the beginning of a new time step because the state does not change (I initiate reevaluations based on the state), but I saw reevaluations. I hope this will not cause any trouble. Now I know the reasons. Copy constructor almost available for all data types, right? Anyway, this issue is not blocking to me. I agree it will be minor. I am also fine if you have strong option to close it.

**Comment by permcody** [comment]
Well the copy constructor is available to every type but we simply have never required it to use a type as a Material property in MOOSE.

**Comment by friedmud** [comment]
@YaqiWang I don't quite understand what you mean by "re-evaluations". 

When the residual is computed the current value of MaterialProperties will always be "re-evaluated"...

**Comment by YaqiWang** [comment]
That is re-evaluations for my own data structure which depends on the values of the coupled variables. If these variable values are not changed, I do not need to re-evaluate my data, which sometimes can save a lot of cpu time.

**Comment by friedmud** [comment]
Detecting that (and not re-computing stateful properties) would be ridiculously complicated.

Realize that the current solution _can_ change between timesteps.  One simple way: turn on the predictor (but there are more).

No: we have to re-evaluate material properties when the residual is computed... no matter what.
