### ISSUE TITLE
An issue in analyzeJacobian.py

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7639]
### Description of the enhancement or error report
It gives me
 ```
(3,0) Off-diagonal Jacobian for variable 'a variable name' should just return  zero
```
after I add more print-out in the script I know
```
(3,0) Off-diagonal Jacobian for variable 'a variable name' should just return  zero 1.82071e-16 vs 0
```

### Rationale for the enhancement or information for reproducing the error
Looks like we can add two more command line arguments, `rel_tol` and `abs_tol` to make the check
https://github.com/idaholab/moose/blob/devel/python/jacobiandebug/analyzejacobian.py#L157
more robust.
Also
https://github.com/idaholab/moose/blob/devel/python/jacobiandebug/analyzejacobian.py#L145
does not need to have the hard-coded value.
Since this small issue is blocking me to put few tests into my application, I will send in a PR shortly.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
An enhancement should not impact anything.

**Comment by dschwen** [comment]
Any reason the Jacobian is not simply returning `0`? This is actually a test that checks if you accidentally implemented a calculation where there should be none. I was worried that the sparsity of the Jacobian could be affected by this.

**Comment by YaqiWang** [comment]
A reasonable question. My guess is that in my boundary condition I coupled in a vector of variables and not all of them are actually coupled because the coupling coefficients for some variables are very close to zero. I do not know why the discrepancy between hand-coded and finite-difference is from and possibly I do not need to worry about it.

My understanding is that when we create a sparsity pattern, we just use the mesh connectivity information, e.g. we set the pattern for a particular node based on the nodes connecting it. It is not guaranteed those jacobian entries are non-zero. @dschwen are you ok for me to send in a PR?

**Comment by dschwen** [comment]
Ok. Should we name it abs_zero like the exodiff parameter?

**Comment by YaqiWang** [comment]
Not sure. Is `abs_zero` for setting the threshold under which the elements will not be compared? To me, `abs_tol` is better paired with `rel_tol`.

**Comment by permcody** [comment]
I think `abs_zero` and `abs_tol` mean different things. `abs_zero` is a tolerance *always* associated with zero. `abs_tol` however is a tolerance that can be associated with just the difference between two non-zero numbers. Note that one is not necessarily equivalent to the other by just performing the difference.

**Comment by dschwen** [comment]
@permcody so for this comparison it _should_ be `abs_zero`, since it is a check to test whether the coded Jacobian value _is_ zero.

**Comment by YaqiWang** [comment]
But my code seems assuming `abs_tol`? I am not assuming `fd[i][j]` and `hc[i][j]` to be zero.

**Comment by dschwen** [comment]
Sorry @YaqiWang I didn't even see your commit until now! I think it is fine. Go ahead and make a PR for that, please.
