### ISSUE TITLE
remaining adaptivity steps should be skipped if mesh is unchanged

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#7647]
### Description of the enhancement or error report
Mesh adaptivity continues to run even when the mesh is unchanged.

### Rationale for the enhancement or information for reproducing the error
Skipping steps that do nothing will increase efficiency.

### Identified impact
Faster simulations!

Working up a very simple PR for this...

**Comment by dschwen** [comment]
Not number of elements, the mesh!

**Comment by jessecarterMOOSE** [comment]
Right you are.
