### ISSUE TITLE
Don't allow private parameters to be set from the input file.

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7655]
### Description of the enhancement or error report

This is a bad idea because they cannot be validated in any sane fashion, plus they do not have documentation strings. This is currently interfering with the NEAMS Workbench effort. I plan to deprecate this behavior moving forward.
### Rationale for the enhancement or information for reproducing the error

It appears that BISON Sifigrs is one of our biggest offenders.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact really, These parameters can be easily converted to regular parameters with all the proper attributes.

Ping @jasondhales, @sapitts

**Comment by jasondhales** [comment]
What is the purpose of private parameters?  I know we've used them in the
past in cases where a developer wants to be able to set something easily
but not allow a user to mess with it.

On Wed, Aug 31, 2016 at 10:24 AM, Cody Permann <notifications@github.com>
wrote:

> Description of the enhancement or error report
>
> This is a bad idea because they cannot be validated in any sane fashion,
> plus they do not have documentation strings. This is currently interfering
> with the NEAMS Workbench effort. I plan to deprecate this behavior moving
> forward.
> Rationale for the enhancement or information for reproducing the error
>
> It appears that BISON Sifigrs is one of our biggest offenders.
> Identified impact
>
> (i.e. Internal object changes, limited interface changes, public API
> change, or a list of specific applications impacted)
>
> No impact really, These parameters can be easily converted to regular
> parameters with all the proper attributes.
>
> Ping @jasondhales
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasondhales&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=jMNa8D_FTT7CKYBFUrO-G4sQQNyv50q442ENXQTZMPw&s=RlPAuYDzNML9izVTHiKvtO_dCRRDzztcinM1l1AwInw&e=>,
> @sapitts
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sapitts&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=jMNa8D_FTT7CKYBFUrO-G4sQQNyv50q442ENXQTZMPw&s=Bj4-VHgCAq-xA7jZ0NMD4lXiUcbzO3dLb-hJQEcClfQ&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_7655&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=jMNa8D_FTT7CKYBFUrO-G4sQQNyv50q442ENXQTZMPw&s=k2tBGLhpfe5FnxpeJK05DewbgCXN3uD-oG9hCGPXxP4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGTY3tHiKcR7S3dk7XO5g5V1KM145Qs8ks5qlarXgaJpZM4JxzdQ&d=CwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=jMNa8D_FTT7CKYBFUrO-G4sQQNyv50q442ENXQTZMPw&s=wXnNy5VtkU6NSrFNGtjWTSaImTTJe2Yb282Jsg4SRLk&e=>
> .
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by YaqiWang** [comment]
A question, if a parameter is suppressed, the parameter turns to private. But currently, user can still set the suppressed parameters as that provides a back door for advanced features. Should this be still allowed?

**Comment by friedmud** [comment]
Yeah - I personally like the ability to add private parameters to control
advanced functionality you don't want exposed to normal users.  But I won't
argue too much against the removal of this capability.

**Comment by dschwen** [comment]
Seems somewhat redundant to just adding an 'Advanced' parameter _group_.

**Comment by permcody** [comment]
I'm not proposing a removal of private paramaters. I'm just suggesting that we _REALLY_ don't allow them to be set from the input file ever. If there's a parameter for "advanced" functionality then make it a regular parameter, stick it in the advanced group, and document them. The private parameters are usually used as a crutch for passing things like problem pointers and other things that really can't be set from the input file.

**Comment by dschwen** [comment]
We could still set those from Actions though, right? This would allow us the design objects that absolutely have to be constructed using actions.

**Comment by friedmud** [comment]
@permcody I'm convinced

**Comment by jasondhales** [comment]
What does "stick it in the advanced group" imply?  Will it appear in a
--dump?  What does the advanced group buy us?

It sounds like we will lose the ability to have parameters that are hidden
from users.  Is that true?

On Wed, Aug 31, 2016 at 2:04 PM, Cody Permann <notifications@github.com>
wrote:

> I'm not proposing a removal of private paramaters. I'm just suggesting
> that we *REALLY* don't allow them to be set from the input file ever. If
> there's a parameter for "advanced" functionality then make it a regular
> parameter, stick it in the advanced group, and document them. The private
> parameters are usually used as a crutch for passing things like problem
> pointers and other things that really can't be set from the input file.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_moose_issues_7655-23issuecomment-2D243883546&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=_G1bS4ZoZOM5QZ1yoQXswIbJtHMo4KDGVZ5jPP2S1qU&s=caFVv1tUJZ1TXyUYm_bfyxs4YUhtdTzmvISPBXxGQIo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGTY3oUpxaOOkSGb3I-5Fu5WG1-5FJMZGo0lks5qld5BgaJpZM4JxzdQ&d=CwMFaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=Xc2bKK3glHdlneeCICPG9lfj75spmf8taZ0yfCJUiQA&m=_G1bS4ZoZOM5QZ1yoQXswIbJtHMo4KDGVZ5jPP2S1qU&s=PgBoUi-C2f_lZhVfccQoUjYdaBpVUoqvSAZ4JhzKm1w&e=>
> .
>



-- 
Jason D. Hales, PhD
Department Manager
Fuels Modeling & Simulation
Idaho National Laboratory
(208) 526-2293

**Comment by permcody** [comment]
@jasondhales - Each parameter can have an optional "group" associated with it. GUIs built from the meta-data dump are encouraged to "filter" parameters by group in some fashion. This is implemented In peacock by having a separate tab for each group. No, we won't lose that ability to hide parameters from users because private parameters can still be set by Actions (also @dschwen's question) or through the system programatically.

This issue is here because the Sifigrs object has a few private parameters that are routinely set from the input file and not any Action. Because they are private, there are no documentation strings for those parameters nor do they appear in any kind of valid syntax dump - yet they are still honored which looks mysterious and magical when looking at an input file.

**Comment by dschwen** [comment]
The "Advanced" group still would make it show up in the dump, but in a special named group. In peacock thos parameters would be in a separate tab and thus not immediately visible to the user.

**Comment by dschwen** [comment]
@jasondhales what would be the reason to hide parameters from the user? Who would use those parameters if not the user? If they are strictly for debugging and you don't want end users to ever see them you might want to set define for developers to enable them (and not even compile them in by default). Just hiding them is like the old security by obscurity concept. If you are just worried about parameter clutter then using parameter groups is the right solution in my opinion.

**Comment by jasondhales** [comment]
@dschwen hiding parameters from the user can be helpful for the developer/researcher.  There may be options the developer wants to explore more fully without telling the user about them.  The proposed alternative is essentially equivalent to providing a document string that says to the user that they should never, ever use the parameter.  I think an argument can be made that hiding those parameters entirely is less headache for the user.

That being said, I'm fine with the change.  It would be nice if --dump included the group, if any (and maybe it already does).

**Comment by permcody** [comment]
`--dump` doesn't include the group. That's a reasonable request. It'll help us dump the parameters in a more prioritized order too. That can be part of this ticket

**Comment by dschwen** [comment]
If `--dump` doesn't include the group how does peacock know about it?!

**Comment by permcody** [comment]
Peacock uses `--yaml` which does include the group. The dump command is human readable so it only includes the names/values and doc strings and none of the meta-data. We could easily put the group in as a comment so it's still mostly valid GetPot format.

**Comment by brianmoose** [comment]
closed by #8198
