### ISSUE TITLE
Verify that addCustomTypeParam info is dumped and works

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7658]
### Description of the enhancement or error report

The NEAMS Workbench needs to perform input file validation. It will need type info dumped for each subblock. We have a case where Burnup block has a type of "BurnupFunction" but the kernels that require that type are only looking for a type of "FunctionName". In code, that FunctionName type is being dynamically cast to "BurnupFunction" but that means that we cannot perform validation on those types currently.
### Rationale for the enhancement or information for reproducing the error

Take a look at any of the BISON input files that require BurnupFunction. Also, create an example in `moose/test`.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Enable validation on the NEAMS workbench

**Comment by brianmoose** [comment]
I am assuming you are referencing `addCustomTypeParam` because that is what you want these changed to?
I changed the `burnup_function` in one of the BISON kernels to add the `BurnupFunction` as the custom type and it did output correctly in the YAML dump. Is that what you had in mind (along with a test for this in MOOSE)?

**Comment by permcody** [comment]
Hmm, I'm not sure. I don't recall why we added `addCustomTypeParam` in the bigger picture. Personally, I'd like to see that method dropped but if it's there it needs to be used correctly.  Your solution gets us by but it seems like we could possibly be smarter.

**Comment by brianmoose** [comment]
BISON could use a `BurnupFunctionName` that inherits from `FunctionName`. Then
it would be `params.addParam<BurnupFunctionName>(...)`.
We would probably need to extend `FunctionInterface` to have a templated `getFunction` so that we would then retrieve the function with `getFunction<BurnupFunctionName>(name)`
Thoughts?

**Comment by permcody** [comment]
> BISON could use a BurnupFunctionName that inherits from FunctionName. Then
> it would be params.addParam<BurnupFunctionName>(...).

This part is fine, don't know if I love it, but it's reasonable as long as it occurs in BISON not in MOOSE.

> We would probably need to extend FunctionInterface to have a templated getFunction so that we > would then retrieve the function with getFunction<BurnupFunctionName>(name)
> Thoughts?

This part is **not** fine. We can't extend a MOOSE interface to support an application. It probably will work without this extension. Give it a shot.

**Comment by YaqiWang** [comment]
This `getFunction<BurnupFunctionName>(name)` looks too me quite useful. We can avoid dynamic cast later in applications. We have bunch of this ugly dynamic cast in Yak currently.

**Comment by permcody** [comment]
I guess I'd be curious what you are doing with these various sub class interfaces? A Function is supposed to be a (hopefully) invariant object of space and time. We also support some gradient methods. What additional things are you doing with a Function? Does a UserObject make more sense?

I'm not opposed to adding a templated "getter" but I need to be convinced that it's the right design from the framework point of view.

**Comment by YaqiWang** [comment]
We have something called transport function, which depends not only on space and time, but also on energy group (or band) index, streaming direction. We extended moose function with more methods. Some of our kernels need this transport function.

**Comment by YaqiWang** [comment]
BTW, user object system already supports this, which can be another argument of the templated getter.

**Comment by permcody** [comment]
Right, but all of the other systems do not because they have very well-defined interfaces (Postprocessors, VectorPostprocessors, Functions). You could implement one of your Functions as UserObject now and use that templated getter. This is especially true since you have expanded beyond the current Function interface.

**Comment by YaqiWang** [comment]
That is an alternative. `Function` is light and I can tolerate to duplicate few lines, although I do want to use Function block in the input to construct these function user objects. Transport functions are indeed special functions. So it makes more sense to derive it from `Function`. Anyway, this is not critical to me. Please not be distracted by me from the original issue raised by Brian.

**Comment by permcody** [comment]
Another alternative would be to create a "TransportFunctionInterface" in Yak. The objects that would need these types of Functions could inherit from this interface and retrieve the full intermediate level API.

**Comment by permcody** [comment]
@brandonlangley - Any issue with this ticket? We've verified it on our end but just want to make sure there's not any issues on your end.

**Comment by brianmoose** [comment]
@lefebvrera or @brandonlangley Any thoughts on this one?

**Comment by brandonlangley** [comment]
@permcody @brianmoose @lefebvrera 

The main thing that I remember about this issue was just that at the time of the input definition dump, burnup_function always has type FunctionName. i.e. in the YAML dump ...

```
    - name: burnup_function
      required: No
      default: !!str 
      cpp_type: FunctionName
```

In my translation into the schema we use for the validation of our parsed DOM hierarchy, I interpret this as having to exist in the set of declarator names of subblocks under the "Functions" block.

For example:

```
[Functions]
  [./power_profile]
    . . .
  [../]

  [./axial_peaking_factors]
    . . .
  [../]
  [./pressure_ramp]
    . . .
  [../]
  [./flux]
    . . .
  [../]
  [./clad_temp_bc]
    . . .
  [../]
  [./q]
    . . .
  [../]
[]
. . .
#some other context
    burnup_function = burnup
. . .
```


Where burnup_function has type "FunctionName" at the time of the dump, would mean that the value would have to be either "power_profile", "axial_peaking_factors", "pressure_ramp", "flux", "clad_temp_bc", "q"

It seems like all other types of FunctionName work correctly this way as existing as the name of a subblock of the Functions block (besides numerical constants or expressions), except for `burnup_function = burnup ` which occurs a lot in the inputs.  I believe that was the only issue with this ticket on our end.

**Comment by brianmoose** [comment]
So you have logic that says if cpp_type is FunctionName then look under the Functions block.
So if we changed the cpp_type to BurnupFunction using `addCustomTypeParam` would your existing logic try to find it under the Burnup block? I'm guessing you would have to add another rule.

It sounds like we need information in the dump on which blocks contain valid names for a type.
I know in peacock we have a hard coded mapping between types and which blocks hold valid values for that type. It seems error prone to me and doesn't handle new types.
@permcody Is this sort of information even producible with current MOOSE syntax information?

**Comment by permcody** [comment]
Yes! We can produce this information without hard mappings. If we require
hard mappings, we've failed. I'll be in later today.

**Comment by brandonlangley** [comment]
@brianmoose @permcody 

> So if we changed the cpp_type to BurnupFunction using addCustomTypeParam would your existing logic try to find it under the Burnup block?

No, I don't have that type of logic in there.  All of my logic for "Exists In" validation logic was grabbed from the atom.io autocomplete plugin:

https://atom.io/packages/autocomplete-moose

This source code:

https://github.com/dschwen/autocomplete-moose/blob/master/lib/provider.coffee

So, the exact logic I have when creating the schema that we use for validation and also for auto-complete in Workbench says:

```
IF type is 'NonlinearVariableName'   THEN value exists in 'Variables' sub-block names
IF type is 'AuxVariableName'         THEN value exists in 'AuxVariables' sub-block names
IF type is 'VariableName'            THEN value exists in 'Variables' OR 'AuxVariables' sub-block names
IF type is 'FunctionName'            THEN value exists in 'Functions' sub-block names (or a numerical constant is okay)
IF type is 'PostprocessorName'       THEN value exists in 'Postprocessors' sub-block names
IF type is 'UserObjectName'          THEN value exists in 'Postprocessors' OR 'UserObjects' sub-block names
IF type is 'VectorPostprocessorName' THEN value exists in 'VectorPostprocessors' sub-block names
```

**Comment by brianmoose** [comment]
There is a PR into BISON that changes all the `burnup_function` parameters to a custom type `BurnupFunctionName` and
also associates `Burnup/*` with `BurnupFunctionName`. This should allow the validator to programmatically find burnup functions under the Burnup block.
@permcody Is there anything else you think needs to be done for this issue?

**Comment by permcody** [comment]
Ticket has been completed.

**Comment by friedmud** [comment]
Way late to the party: just wanted to point out that the original reason for `addCudtomTypeParam` was for Peacock extensibility.  It would allow users to create custom input file parameters and associate objects with those types so they would show as valid options in the pick lists in Peacock.

**Comment by permcody** [comment]
@friedmud Thanks, I was struggling to remember the exact reason why we created them. I knew it had something to do with Peacock but couldn't remember what. Apparently nobody else did either because they remain unused.
