### ISSUE TITLE
BCs/Pressure has several parameters listed incorrectly in the yaml/dump

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7661]
### Description of the enhancement or error report

The Pressure block is in TensorMechanics and is just a block for supplying BCs. There is also a PressureAction for setting up pressure type bcs but as it stands, it should work for any bc type (probably needs to be restricted). The dump however is putting output from the "Pressure" BC in the top level block that are ignored!
### Rationale for the enhancement or information for reproducing the error

Run the modules dump or tensor mechanics dump to repeat.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by brianmoose** [comment]
They are using it in two different ways:
```
[BCs]
  [./Pressure]
    type=Pressure
  [../]
[]
```
and
```
[BCs]
  [./Pressure]
    [./foo]
    [../]
  [../]
[]
```

The output from dump/YAML merges the two.
Cody suggested that we could rename the first one to something like `[./my_Pressure]` in the dump. For the YAML we can put additional information in the output to be able to distinguish the two.

**Comment by brianmoose** [comment]
I looked at this again and I am not sure what the problem is. Probably just confusing myself.
The `--dump` for `BCs/Pressure`
```
  [./Pressure]
    alpha                        = 0                           # alpha parameter required for HHT time integration scheme
    boundary                     = (required)                  # The list of boundary IDs from the mesh where this boundary condition ...
                                                               # applies
    component                    = (required)                  # The component for the pressure
    control_tags                 =                             # Adds user-defined labels for accessing object parameters via control ...
                                                               # logic. ...
                                                               # Group: Advanced
    diag_save_in                 =                             # The name of auxiliary variables to save this BC's diagonal jacobian contributions ...
                                                               # to.  Everything about that variable must match everything about this ...
                                                               # variable (the type, what blocks it's on, etc.) ...
                                                               # Group: Advanced
    enable                       = 1                           # Set the enabled status of the MooseObject. ...
                                                               # Group: Advanced
    factor                       = 1                           # The magnitude to use in computing the pressure
    function                     =                             # The function that describes the pressure
    implicit                     = 1                           # Determines whether this object is calculated using an implicit or explicit ...
                                                               # form ...
                                                               # Group: Advanced
    postprocessor                =                             # Postprocessor that will supply the pressure value
    save_in                      =                             # The name of auxiliary variables to save this BC's residual contributions ...
                                                               # to.  Everything about that variable must match everything about this ...
                                                               # variable (the type, what blocks it's on, etc.) ...
                                                               # Group: Advanced
    seed                         = 0                           # The seed for the master random number generator ...
                                                               # Group: Advanced
    type                         = Pressure
    use_displaced_mesh           = 1                           # Whether or not this object should use the displaced mesh for computation. ...
                                                               # Note that in the case this is true but no displacements are provided ...
                                                               # in the Mesh block the undisplaced mesh will still be used. ...
                                                               # Group: Advanced
    variable                     = (required)                  # The name of the variable that this boundary condition applies to

    [./*]
      active                     = __all__                     # If specified only the blocks named will be visited and made active
      alpha                      = 0                           # alpha parameter for HHT time integration
      boundary                   = (required)                  # The list of boundary IDs from the mesh where the pressure will be applied
      disp_x                     = (required)                  # The x displacement
      disp_y                     =                             # The y displacement
      disp_z                     =                             # The z displacement
      factor                     = 1                           # The factor to use in computing the pressure
      function                   =                             # The function that describes the pressure
      postprocessor              =                             # The postprocessor that describes the pressure
      save_in_disp_x             =                             # The save_in variables for x displacement
      save_in_disp_y             =                             # The save_in variables for y displacement
      save_in_disp_z             =                             # The save_in variables for z displacement
    [../]
  [../]
```

The `Pressure/*` action syntax has all the correct parameters (no more or less) and the `Pressure` BC has all the correct parameters (no more or less). This is similar for the YAML dump.
What is the output supposed to be?
Is this more than an output issue?

**Comment by permcody** [comment]
Hmm, you're right, this looks just fine. I went back in the history and don't see any issues with this block either. I think I recall there being a problem with the Burnup block but I don't see the issue with this block.

@lefebvrera - Can you help us out here? We are looking at this ticket and I'm not seeing the issue here which probably means I just didn't give it a very good description. I'm pretty sure something was failing in the workbench semantic check but we're failing to find that again. Thanks in advance.

**Comment by lefebvrera** [comment]
@permcody, I don't remember the details. I know @brandonlangley identified the issues in capture the input definition requirements for Workbench integration. I have forward him this notice to have him provide clarification.

**Comment by brandonlangley** [comment]
@permcody 

The issue I was seeing is there there were 128 files total that ran through the test harness that have BCs/Pressure blocks that look similar to this:

tests/tensor_mechanics/creep_uo2/creep_uo2_rz_test_tm.i

```
[BCs]
  [./Pressure]
    [./u_top_pull]
      disp_x = disp_x
      disp_y = disp_y
      boundary = 4
      factor = -0.5e8
      function = top_pull
    [../]
  [../]
 . . .
[]
```

The dump that you pasted above shows that BCs/Pressure has a REQUIRED "boundary," "component," and "variable" parameter.  

None of these three variables are present in 128 inputs total that run through the test harness (obtained from ./run_tests --dry-run -v).
 
There is a wildcard underneath the /BCs/Pressure with other requirements such as a required "boundary" and a required "disp_x".  These requirements seems to be valid and consistent with the tested inputs.
 
However, there seems to never bee a "boundary" "component" or "variable" underneath the top /BCs/Pressure level (or in a GlobalParams block either) when the dump says those three are required to be there.

This is probably the the one input validation discrepancy that I am seeing most often in input files.

**Comment by dschwen** [comment]
I can confirm this. The required parameters (like `BCs/Pressure/variable`) show up in the moose-autocomplete results as well. `BCs/Pressure` is registered to `EmptyAction` and there should be _no_ parameters at that level.

**Comment by dschwen** [comment]
Ah, I think the reason is that we have a `[./Pressure]` syntax _and_ and actual `Pressure` BC object (which is what provides the parameters in the dump!).

**Comment by dschwen** [comment]
Yep, by doing 
```
  registerNamedObject(Pressure, "PressureBC");
```
instead of
```
  registerBoundaryCondition(Pressure);
```

In `moose/modules/tensor_mechanics/src/base/TensorMechanicsApp.C` the parameters disappear from the dump. (unfortunately the BC is used quite a lot outside of the action)

**Comment by permcody** [comment]
The solution isn't to change MOOSE, but to change the dump/yaml/json information fundamentally to differentiate between these allowed syntaxes. We understand why this is happening, now we are inventing new meta-data to help use create better dumps to avoid special case rules, and to make a format suitable for a validator.

**Comment by dschwen** [comment]
Ugh, me:
![poke](https://cloud.githubusercontent.com/assets/202302/23041336/e01e8af2-f451-11e6-84c4-d7ba4db46f47.jpeg)

**Comment by brianmoose** [comment]
What I am getting from @brandonlangley  is that their checker
is expecting something like
```
[BCs]
  [./Pressure]
    boundary = 0
    variable = x
    component = 0
    [./u_top_pull]
      disp_x = disp_x
      disp_y = disp_y
      boundary = 4
      factor = -0.5e8
      function = top_pull
    [../]
  [../]
 . . .
[]
```
Ie, the required parameters must exist under the Pressure block.
MOOSE doesn't see it like this though and the above wouldn't even work.
In peacock we tell the difference by looking at not only the dump but also the output of `--syntax`. 

So the goal of this PR is to make the dump output differentiate between these cases.
For example, having the allowed types for `BCs/*` separated out from `BCs` hard children.
Something like
```
- BCs
  - action
    - common_parameters: # Parameters from /BCs/*
       - boundary # required
       - variable # required
       ...
    - allowed_types
      - Pressure  # Pressure BC
        - parameters # Parameters from /BCs/Pressure
          - boundary # required
          - variable # required
          - component # required
          ...
         ...
      - DirichletBC
         ...
      ...
  - children
    - Pressure
      - action
        - common_parameters: # Parameters from /BCs/Pressure/*
           - boundary # required
           - disp_x  # required
    - Periodic
      ...
    - CavityPressure
      ...
```
Thoughts?

**Comment by permcody** [comment]
We can certainly change the output of the yaml (or soon to be JSON) dump to help the parser differentiate between these cases. That's fine with me. 

If I understand your proposal here, we'll have both BCs/* and BCs/Pressure listed for a case like this. Rule: "Exact matches are always preferred over wildcard maches" 

Then the validator would ignore the BCs/* block requirements whenever encountering a BCs/Pressure block using that validation rule instead. This works great for the Yaml/Json dumps, you'll still have a little bit of weirdness going on with the getpot dump though if we don't change the arbitrary string names that I choose when I created that class.

**Comment by brianmoose** [comment]
I would actually like to change it for `--dump` as well. Making the distinction between always present children and "types that you can add" seems to be important in all the formats.
For the `--dump` it might look like:
```
[BCs] 
  [./<AddBCAction_Pressure>]
    type                        = Pressure
    ...
  [..]
  [./Pressure]
    [./<PressureAction_Pressure>]
    [../]
  [../]
[]
```
Where the `<>` syntax indicates that it is a user defined name

**Comment by brandonlangley** [comment]
@permcody @brianmoose 

Sorry to comment on a closed case. I just want to make sure I understand exactly how this works from our two-step getpot parsing and validation perspective.

**_First_**, our getpot parser parses the input into a tree structure where every node in the tree has a **name**. This happens independent of the schema and just uses syntax rules for parsing the input into the tree.

Since, `[./blockname]` can be arbitrary, if there is a `type=somename` inside the block, then it overrides that block's name in the input tree.  If there is not a `type=somename` inside a block, then the name specified inside the `[./blockname]` is the name of the node in the tree. (These arbitary named blocks then match the star '*' context in your dump under a given context).

So, currently, our getpot parser would take both of the following ...

```
[BCs] 
  [./some_arbitary_name]
    type = Pressure
  [..]
[]
```
```
[BCs] 
  [./Pressure]
  [../]
[]
```
and create a tree in-memory that has a node named Pressure under BCs.

**_Second_**, that input tree is validated against the schema that we build. The schema and input tree have a one-to-one mapping of every node in the tree keyed off of the given **names**.

Should one of the above validate against a different piece of the` ./bison-opt --dump` than the other?  The dump still seems to have `boundary`, `variable`, and `component` all required under the Pressure context when none of the actual inputs seems to have any of these flags under `[BCs] [./Pressure]`

I feel like I am maybe misunderstanding something?

**Comment by brianmoose** [comment]
Yes, they should validate against different pieces of the dump. Your `some_arbitrary_name` should validate against `BCs/*/<types>/<Pressure>` while blocks under `BCs/Pressure` should validate against `BCs/Pressure/*`.

My `--dump` doesn't have `variable` and `component` under `BCs/Pressure/*` so maybe your bison is out of date? Do you have the `BCs/*/<types>/<Pressure>` in your `--dump`?

I guess I had envisioned some simple logic: If path matches a subblock (a hard path), then use that. Otherwise use "*". Your renaming of the block names doesn't seem to work with that though.

I guess I would ask, what would you like the dump information to look like to make your validation easier?

Note that the YAML dump has not been updated to show this separation as the changes required would break compatibility with existing tools that use the YAML dump. The Json dump (and `--dump`) are where all these new changes are going.
