### ISSUE TITLE
Auxkernel to provide easier access to fluid properties in the PorousFlow module

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#7673]
### Description of the enhancement or error report
Adds an auxkernel that allows easy access to important material properties in the PorousFlow module without the need to know the actual internal material property name. Also works for `std::vector<std::vector<property>>` such as mass fractions.

### Rationale for the enhancement or information for reproducing the error
Makes it easy to extract properties of interest from the many material properties

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Adds new capability

**Comment by permcody** [comment]
Completed in #7674 

@cpgr - If you have completed an issue, you can put the keyword "closes" before your ticket number to have Github close the ticket once your PR is merged.

**Comment by cpgr** [comment]
Thanks @permcody - I didn't know that.
