### ISSUE TITLE
PorousFlow module tests and documentation updates

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#7677]
### Description of the enhancement or error report
General issue for adding new tests that utilises the current capability to the PorousFlow module, and also for adding documentation regarding these tests.

### Rationale for the enhancement or information for reproducing the error
Some PorousFlow module tests have good documentation, while some do not.
Make the testing and documentation levels more consistent and thorough

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Only good things

**Comment by permcody** [comment]
Completed in #7678
