### ISSUE TITLE
Add diffusion and hydrodynamic dispersion to PorousFlow module

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#7679]
### Description of the enhancement or error report
Adds a kernel to include diffusion and dispersion of fluid components

### Rationale for the enhancement or information for reproducing the error
Adds more capability to the PorousFlow module

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None

**Comment by permcody** [comment]
Not sure if this one is done since you added another commit after the previous one was merged.

**Comment by cpgr** [comment]
I'm not sure what happened here? I did have to fix a few tests so that they would pass, but I squashed that commit and force pushed it back. Did something go wrong here?

**Comment by permcody** [comment]
Probably not, that commit might be available in another branch. Feel free to close this ticket if you are done with it then.
