### ISSUE TITLE
Use the glorious Utility::pow<> more!

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7702]
### Description of the enhancement or error report
We have a ton of unnecessary `std::pow` usage with fixed integer exponents. Those a a lot slower than the multiplications that are generated by the `Utility::pow` template. I don't think it hurts readability. I think we should use it more so that people become aware of it.

### Rationale for the enhancement or information for reproducing the error
Speedup in tight loops. It is 10 to 30 times faster.

### Identified impact
May result in deviations around machine precision. Small (model dependent) speedups.

**Comment by mangerij** [comment]
Cool, I tested this a while back, I think I saw something like a 8-10 times speed up with Ferret when I dumped std::pow() from the code too. 

Is there a reason why something in Utility is faster than something in the standard class?

**Comment by dschwen** [comment]
The template only works for positive integer powers. The compilers do not optimize for this as it will change the results minutely (maybe with `-Ofast` they will). `std::pow` just always goes through the same generic algorithm for arbitrary exponents.

**Comment by dschwen** [comment]
I have a PR open to replace `std::pow(*, 1.0/3.0)` with `std::cbrt(*)`, and I'll make one to replace `std::pow(*, 1.0/2.0)` with `std::sqrt(*)`. The cbrt PR however does break tests (which it totally should _not_!). This indicates some issues with the algorithms it is used in.
