### ISSUE TITLE
Use `std::sqrt` where possible

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7705]
### Description of the enhancement or error report
Use of `std::sqrt(...)` can be faster than `std::pow(... , 0.5)`. For 1e6 evaluations:

```
g++ -O2
std::pow 31ms
std::sqrt 6ms

clang++ -O2
std::pow 4ms
std::sqrt 4ms
```

Looks like clang's libc++ is smarter here.

### Rationale for the enhancement or information for reproducing the error
Faster in g++ and semantically more clear.

### Identified impact
Might yield slightly different results due to different truncation.

**Comment by dschwen** [comment]
FYI, `std::cbrt(...)` is 3x faster than `std::pow(..., 1.0/3.0)` on both compilers.

**Comment by friedmud** [comment]
Interesting.

I'm not surprised about GCC.
