### ISSUE TITLE
Handle "splitting" grains in EBSD and other polycrystal sims

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7712]
### Description of the enhancement or error report

With all of the GrainTracker enhancements we still can't handle the case of grains splitting after the first time step. The problem is illustrated in the current ebsd_reconstruction example.

![ebsd_bad](https://cloud.githubusercontent.com/assets/3036960/18412410/fd2e0a34-774a-11e6-89a4-ef0e7c053787.png)
 
The two circular grains on the left hand side near the top are actually part of the same grain. Since they are circular they shrink under normal evolution physics so they appear to split after the second time step. This is difficult to handle because the logic for matching up grains assumes a one to one mapping across time steps. This logic will need to be enhanced to allow multiple grains to map to a single previous grains under very special circumstances. There is definitely a fair amount of work here to differentiate this case from grains that don't share the same underlying "EBSD" id.

I propose that we split the current example up. I'd like a small test case that I can work on containing this split grain on a smaller domain (maybe ~30x30). So that we have a working example we should also crop the current example to remove this split grain. @frombs can you perhaps break this up?

### Rationale for the enhancement or information for reproducing the error

Run the current ebsd_reconstruction example.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This should only impact EBSD runs with these split grain types that drift apart. Split grains that start far apart and coalesce or start close and don't split already work properly.

Ping @tonkmr, @dschwen

**Comment by frombs** [comment]
@permcody - I have attached the two datasets you requested below.  The first is a 30x30 mesh with the split grain included.  The second is a 120x120 mesh that has been cropped to remove 3 of the 5 split grains located along the edge of the dataset.  There are still 2 split grains within the center region of the new dataset.  Is that okay?

[IN100_30x30_SplitGrain.txt](https://github.com/idaholab/moose/files/468770/IN100_30x30_SplitGrain.txt)
[IN100_120x120_SplitGrain.txt](https://github.com/idaholab/moose/files/468771/IN100_120x120_SplitGrain.txt)

**Comment by permcody** [comment]
Yeah most splits grains are ok. It's the ones that are really close that
separate at some point in the simulation that aren't handled. Thanks!
