### ISSUE TITLE
Code path to call of copyVars impossible

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#7773]
### Description of the enhancement or error report
In case you initialize variables from an exodus file as described here under variable initialization, 

http://www.mooseframework.com/wiki/Restart/

the following code should be executed in `FEProblem::initialSetup`

https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblem.C#L356

However, `_mesh.exReader()` is not implemented and returns `NULL`: 

https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L2225

### Rationale for the enhancement or information for reproducing the error
Is the restart variable feature not implemented or am I looking at the wrong code path?
I would need this for starting transient calculation from eigenvalue calculations in a reliable way
without duplication of memory. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
If I am looking at the right code path, implementing `MooseMesh::exReader()` should do the trick, otherwise no impact.

**Comment by snschune** [comment]
Oh never mind, it's implemented in `FileMesh`.

**Comment by permcody** [comment]
So do you just need to close this ticket? I'll pretend it never happened...

**Comment by snschune** [comment]
yeap

**Comment by snschune** [comment]
To conclude this, I don't use the `CopyNodalVarsAction` and simply tried calling `addVariableToCopy`, but missed that I also have to do `_app.setFileRestart() = true;`. 
In case of `_app.setFileRestart() == false`, `FileMesh` indeed doesn't define the exodus reader.
