### ISSUE TITLE
A parameter for tests to be passed into test harness

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7774]
### Description of the enhancement or error report
An application could depend on other applications in submodules optionally. Consequently, tests depending on the applications could also be optional. We will need a new parameter for each test, something like `depending_submodule`, which can be passed into test harness in order to make the test invoked conditionally with the availability of the submodules.

### Rationale for the enhancement or information for reproducing the error
MAMMOTH needs this capability. When this capability is in place, we'd like MAMMOTH also in the app test list.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New feature.

**Comment by YaqiWang** [comment]
Since MAMMOTH is important to us and we do not want to break it accidentally, I suggest to mark this issue with the critical tag.

**Comment by permcody** [comment]
That's not what "critical" is used for. Critical is actually being used as an NQA-1 designation. I agree this is important and will get to it soon.

**Comment by dschwen** [comment]
Wait a minute. I thought we had this discussion with @bwspenc already and the outcome was to probe for specific object names.

**Comment by permcody** [comment]
> probe for specific object names.
Does that mean that we have to keep a mapping of what objects belong to which modules/apps?
