### ISSUE TITLE
Cutting timestep Seg fault

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7783]
### Description of the enhancement or error report

Before I get carried away with including lots of details, is this expected behaviour from a Material throwing a mooseException in order to try to cut the timestep?

> ComputeMultiPlasticityStress: After reducing the stepsize to 0.5 with original strain increment with L2norm 0.00783296 the returnMap algorithm failed
> 
> A MooseException was raised during Auxiliary variable computation.
> The next solve will fail, the timestep will be reduced, and we will try again.
> 
> Nonlinear solve did not converge due to DIVERGED_FUNCTION_DOMAIN iterations 0
>  Solve Did NOT Converge!
> 
> Time Step  2, time = 0.0170454
>                 dt = 0.0056818
> Segmentation fault
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
Yeah. All of that looks normal. After the throw we stop computing stuff
because we don't know what might be valid or not. We set a flag to tell
Petsc to quit then the timestep gets cut. I'm not sure why you would have a
segfault.

**Comment by WilkAndy** [comment]
OK, good, thanks.  I'll investigate the segfault in more detail when i get time.

**Comment by WilkAndy** [comment]
Fixed by #8059
