### ISSUE TITLE
Change GrainAdvectionVelocity material to AuxKernel

### ISSUE THREAD

**Issue by SudiptaBiswas** [idaholab/moose#7797]
### Description of the enhancement or error report
`GrainAdvectionVelocity` material is no longer used by rigidbody motion kernles, it's only used for visualization purpose. An Auxkernel seems more reasonable for this. 

### Rationale for the enhancement or information for reproducing the error
`GrainAdvectionVelocity` often creates issue while communicating with `GrainTracker`.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Only rigid body motion tests and examples will be affected

**Comment by permcody** [comment]
I wouldn't worry about changing this right now. For one thing it'll certainly foul up my current PR which I'm hoping to get in pretty soon!

**Comment by SudiptaBiswas** [comment]
I have the object ready, I can wait till your PR is merged.
