### ISSUE TITLE
Don't output unprintable characters in YAML dump (or others) in MOOSE

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7806]
### Description of the enhancement or error report

Creating an input parameter type of "char" or "unsigned char" creates problems for Peacock due to the output dump. These characters generally come out as control characters which messes with the YAML parser. 
### Rationale for the enhancement or information for reproducing the error

Create one of these types of input parameter types in MOOSE. I assume that this would affect any single byte type with the exception of Boolean which we already handle properly.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

MOOSE syntax dumps and peacock reads

**Comment by brianmoose** [comment]
Should we change it in MOOSE to have cases for the `char` types like [here](https://github.com/idaholab/moose/blob/master/framework/src/outputs/formatters/YAMLFormatter.C#L152)?

Or change [parameters.h](https://github.com/libMesh/libmesh/blob/master/include/utils/parameters.h#L298) in libmesh to have template specialization for `void Parameters::Parameter<T>::print`? I don't think having a custom `print_helper` will work.
@jwpeterson Any preferences?

**Comment by jwpeterson** [comment]
I think a specialization of `Parameter<T>::print()` for `char` and `unsigned char` is the way to go.
