### ISSUE TITLE
Radial average  vector postprocessor

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7810]
### Description of the enhancement or error report
I need the ability to radially average variable field (spherically and potentially cylindrically). 

Where should this go @permcody ?

### Rationale for the enhancement or information for reproducing the error
Additional postprocessing capability (avoid writing out potentially HUGE exodus files)

**Comment by permcody** [comment]
This doesn't sound like a very general object to me. I'd say put it in your application or perhaps a module if you think it's applicable there. 

In terms of implementation, what's your plan here? Are you going to have a global set of points on which you will perform this averaging? The reason I ask is, given a radius it's highly likely that solution information you need on a given processor won't be available on that processor. That won't be a problem if every processor just sums the information it a global vector that's known to all processors. You are probably already aware of that restriction. I'm putting it out there just in case.
