### ISSUE TITLE
Show the skipped tests due to dependency at the bottom of the test report

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7814]
### Description of the enhancement or error report
Currently, if a test fail, it will be showed at the bottom of the test report. But if any tests depend on this failing test, which will be skipped due to dependency, are not showed at the bottom but instead float to the top of the test report.

### Rationale for the enhancement or information for reproducing the error
This will make developers see better how many tests are affected by a change in the code.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Nothing.

**Comment by permcody** [comment]
Interesting...

**Comment by permcody** [comment]
@YaqiWang - That's not what I see. The final result table is sorted on the result (which is a little odd I admit). This causes the skipped tests to float to the top instead of the bottom with the Failed tests. Can you confirm?

**Comment by YaqiWang** [comment]
Yes, I confirmed that it is floating to the top. (not hundred percent sure if they are exactly on top of the other skipped tests.)

**Comment by permcody** [comment]
Feel free to close or change this issue to fix the sorting if that's your issue.
