### ISSUE TITLE
GeneralizePlaneStrainUO won't work with threads

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7826]
### Description of the enhancement or error report

It appears that the `threadJoin` method is not implemented on this object. Since this is an elemental user object, that means this object will not work with threads.

### Rationale for the enhancement or information for reproducing the error

Object is incomplete

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Simulation using this object cannot run threaded.

@hchen139 - Please implement this method. Feel free to stop by the MOOSE cube if you have questions on how or what you need to do in that method. Thanks

**Comment by dschwen** [comment]
Neither is finalize! So this should not work with MPI either. My bad, I didn't notice this.

**Comment by permcody** [comment]
Daniel, I noticed one other UO missing `finalize` as I was skimming them really quickly. Actually there might even be more than that! I guess we need to go through all of these. Maybe @sapitts will volunteer!
