### ISSUE TITLE
Methods in Function are not const

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7830]
### Description of the enhancement or error report

Is this the intention? Seems to me calling `value()` of a function should never change the function itself.
### Rationale for the enhancement or information for reproducing the error

This prevents us using `const Function &` in our code.
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
If this is an issue, there will be a trivial interface change. Downstream apps should not be impact because they are probably using non-const function pointers or references.

**Comment by permcody** [comment]
Probably not intentional. MOOSE doesn't start with a strong emphasis on const-correctness. It's painful to add it on later but that's what we are doing nonetheless. This will probably be more difficult and far reaching to implement. You may just want to add a new version of `value()` that _is_ const. Then we can work on deprecating the old method and removing it over time.

**Comment by friedmud** [comment]
If I had to take a guess... I would say that this may have something to do with `SolutionFunction`....

**Comment by permcody** [comment]
`SolutionFunction` actually looks ok. Just looking at it for a minute tells me this is a huge undertaking. First there are actually four methods in the `Function` base class that are all evaluations and they probably should all be `const`. However, there are fingers to functions everywhere. It looks like `MooseParsedFunctionWrapper` updates state when you call the `gradient` method. I don't see why that's necessary but things like that would have to be fixed. I'm very supportive of this change but it'll be a big one unless we simply add const methods for now and deprecate old ones as we move forward.

**Comment by permcody** [comment]
closed by #13480
