### ISSUE TITLE
Create an output format better suited for documentation

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#7855]
The documentation code would be much better if I had a dump that included the following:
- [ ] Class Description and parameters (the description is currently missing in yaml for actions)
- [ ] The type of syntax (e.g., 'Kernels/*', 'Kernels/<type>', 'Kernels/MyAction', 'Kernels/MyObject'), this doesn't need to be a tree, just a flat list with the complete syntax would work.
- [ ] The location that the object/action/syntax is registered (e.g., in framework, in a module, or in your application.

**Comment by permcody** [comment]
I think I'll have @brianmoose work on this along with the other NEAMS Workbench tasks.

**Comment by aeslaughter** [comment]
After continue to work with things, this probably should be a tree. But, it would be useful if the node had some information about where it comes from. Right now I am passing a list of the parents (for "breadcrumbs"), e.g. `['Adapivity', 'Markers']`

**Comment by brianmoose** [comment]
@aeslaughter The new Json output should satisfy the requirements in the original comment. When you get time you can verify that it works for you and close this issue if it does.

**Comment by brianmoose** [comment]
This seems to be working for the documentation system.
@aeslaughter You can reopen this if you feel there is more to be done, or open additional issues for specific problems

**Comment by aeslaughter** [comment]
This is what I would like: #9408
