### ISSUE TITLE
Update modules tests which fail with Apple BLAS

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/moose#7859]
We are planning to start linking against the optimized BLAS provided by Apple (VecLib) in an upcoming version of the package.   This change, which should be fairly straightforward, causes the following tests to diff, so I'm in the process of fixing them:

- [x] combined:DiffuseCreep.stress (#7861)
- [x] combined:DiffuseCreep.stress_flux_n_gb_relax (#7861)
- [ ] solid_mechanics:rate_dep_smear_crack.iso_test
- [ ] solid_mechanics:cracking.exponential
- [ ] tensor_mechanics:smeared_cracking.single_element

**Comment by jwpeterson** [comment]
The three remaining tests above have a reputation reputation for being finicky: they are all currently disabled on Intel and/or have custom `rel_err` settings in their test files.  That being said, something truly strange is going on when I run them with the VecLib/Accelerate Framework BLAS: they produce non-repeatable results.  For example, running the following test
```
../../tensor_mechanics-opt -i cracking_exponential.i
```
three times on my system with the Accelerate framework BLAS produces the following three results:

Run 1:
```
Time Step 1200, time = 6
                dt = 0.005
 0 Nonlinear |R| = 3.643057e+07
      0 Linear |R| = 3.643057e+07
      1 Linear |R| = 6.850043e+06
      2 Linear |R| = 2.520373e+06
      3 Linear |R| = 7.285782e+05
      4 Linear |R| = 3.162782e+05
      5 Linear |R| = 5.451345e+04
      6 Linear |R| = 3.800283e+04
      7 Linear |R| = 1.455774e+03
      8 Linear |R| = 1.346831e-08
 1 Nonlinear |R| = 1.014895e-03
      0 Linear |R| = 1.014895e-03
      1 Linear |R| = 2.802037e-04
      2 Linear |R| = 1.623297e-04
      3 Linear |R| = 2.261531e-05
      4 Linear |R| = 3.506949e-06
      5 Linear |R| = 7.735604e-07
      6 Linear |R| = 1.399209e-07
      7 Linear |R| = 4.583905e-08
      8 Linear |R| = 1.247972e-19
 2 Nonlinear |R| = 1.044061e-08
 Solve Converged!
```

Run 2:
```
Time Step 1200, time = 6
                dt = 0.005
 0 Nonlinear |R| = 3.643057e+07
      0 Linear |R| = 3.643057e+07
      1 Linear |R| = 6.850043e+06
      2 Linear |R| = 2.520373e+06
      3 Linear |R| = 7.285782e+05
      4 Linear |R| = 3.162782e+05
      5 Linear |R| = 5.451345e+04
      6 Linear |R| = 3.800283e+04
      7 Linear |R| = 1.455774e+03
      8 Linear |R| = 4.196145e-09
 1 Nonlinear |R| = 1.048310e-03
      0 Linear |R| = 1.048310e-03
      1 Linear |R| = 3.238209e-04
      2 Linear |R| = 1.181294e-04
      3 Linear |R| = 3.578879e-05
      4 Linear |R| = 8.075950e-06
      5 Linear |R| = 1.611654e-06
      6 Linear |R| = 5.955744e-07
      7 Linear |R| = 1.719521e-07
      8 Linear |R| = 3.615054e-19
 2 Nonlinear |R| = 1.324196e-08
 Solve Converged!
```

Run 3:
```
Time Step 1200, time = 6
                dt = 0.005
 0 Nonlinear |R| = 2.337734e+07
      0 Linear |R| = 2.337734e+07
      1 Linear |R| = 6.450035e+06
      2 Linear |R| = 7.774112e+05
      3 Linear |R| = 1.220632e+05
      4 Linear |R| = 3.983160e+04
      5 Linear |R| = 1.822156e+04
      6 Linear |R| = 5.074055e+03
      7 Linear |R| = 3.668959e+02
      8 Linear |R| = 7.622727e-09
 1 Nonlinear |R| = 9.025449e-04
      0 Linear |R| = 9.025449e-04
      1 Linear |R| = 1.742259e-04
      2 Linear |R| = 4.544691e-05
      3 Linear |R| = 7.261236e-06
      4 Linear |R| = 1.917397e-06
      5 Linear |R| = 2.290504e-07
      6 Linear |R| = 4.280323e-09
      7 Linear |R| = 1.904502e-09
      8 Linear |R| = 1.945238e-19
 2 Nonlinear |R| = 1.727548e-08
 Solve Converged!
```

As you can see, the final residual is *slightly* different in each case, even though all three are below the required nonlinear tolerance.  These differences are apparently enough to cause large diffs in the gold file after 1200 timesteps:
```
  --------- Time step 1201, 6.0000000e+00 ~ 6.0000000e+00, rel diff:  0.00000e+00 ---------
Nodal variables:
   disp_y  rel diff:  9.3621811e-04 ~  1.3385069e-03 = 3.00550e-01 (node 7)
   disp_z  rel diff: -5.4385603e-04 ~ -5.7660613e-05 = 8.93978e-01 (node 1)
Element variables:
   stress_yy  rel diff:  7.4505806e-09 ~  1.7695129e-08 = 5.78947e-01 (block 1, elmt 1)
   stress_zz  rel diff:  3.8417056e-09 ~  1.5832484e-08 = 7.57353e-01 (block 1, elmt 1)
   stress_xy  rel diff:  3.3036217e+07 ~  4.5764806e+07 = 2.78131e-01 (block 1, elmt 1)
   stress_yz  rel diff: -9.8998148e+06 ~  4.2752958e+06 = 1.43186e+00 (block 1, elmt 1)
   stress_zx  rel diff: -2.0675248e+06 ~  1.1758970e+07 = 1.17583e+00 (block 1, elmt 1)
```
Note that this test is valgrind clean, and of course produces repeatable (all digits of the final nonlinear residual printed by MOOSE match) results with the Netlib BLAS that we are currently using.

It's possible there are bugs in the Accelerate Framework BLAS/LAPACK implementation.  I compiled and ran the test code from this [gist](https://gist.github.com/jvkersch/cb65d3c2ba6deca287d6) on my El Capitan system, and @milljm ran it on his new Sierra box. We both confirmed that the Apple BLAS give the *wrong* result while the Netlib BLAS work just fine.  Although this particular function  (`SDOT`) is most likely not used by MOOSE (it is a single-precision function), it makes me wonder what else might be wrong with their implementation...

So, for the time being we've decided to stick with the Netlib BLAS in the MOOSE package for OSX.  It is still possible for advanced users to compile their own PETSc and link to any BLAS they wish in order to get better performance, but for something to be in the package it needs to be a lot more solid than this.

**Comment by friedmud** [comment]
Sounds good - thanks for looking into this guys!
