### ISSUE TITLE
Create a method to deprecate action syntax

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#7871]
We moved away from the `[Bounds]` block for defining boundary restricted AuxKernels many moons ago, but it lives on. We need away for an object that is created within this block to trigger a deprecated warning.

**Comment by permcody** [comment]
Actually no, you are thinking of `[AuxBCs]`. 

[Bounds] is fine

![image](https://cloud.githubusercontent.com/assets/3036960/22311484/e1e6f89e-e310-11e6-8ef9-0cd619176d4e.png)

**Comment by permcody** [comment]
I'm pushing up a PR for the other part of this ticket, i.e. to allow deprecated syntax.
