### ISSUE TITLE
Output Correct Grain Indices for EBSD Datasets with Multiple Phases or Voids

### ISSUE THREAD

**Issue by frombs** [idaholab/moose#7876]
### Description of the enhancement or error report

The EulerAngleProvider2RGBAux.C aux kernel is used to output inverse pole figure color maps that represent the crystallographic texture of grains within a phase field simulation.  Currently, the code uses the "local_id" from GrainTracker.  For datasets that invoke a phase number within PolycrystalEBSD or that contain voids, the "local_id" will return incorrect RGB maps as shown below. 
 For these cases, we need to request the "global_id" from EBSDReader that requires inputs of both the phase and local_id in order to return the correct index.

Similarly, EBSDReaderAvgDataAux.C needs to be updated to request the correct grain index from EBSDReader so that output variables are based on the correct index.  This is a long standing issue (reference to indexing issue #7638 that contained tests with conflicting indexes).  Test "euler2rgb_no_grain_region.i" relies on both of these codes and needs to be updated.

### Rationale for the enhancement or information for reproducing the error

The image below illustrates the current color mapping errors:
![ipf_map_index_problem](https://cloud.githubusercontent.com/assets/8171022/19419957/10f7e5e2-939f-11e6-9d0e-2a3913697e37.png)
### Identified impact

Fix grain indexing for RGB maps and aux variables based on EBSD input files.

**Comment by permcody** [comment]
@dschwen - Is this correct? I know that `EulerAngleProvider2RGB` uses the "grain id" from the grain tracker which is either a "local id" or a "global id" depending on if a phase is being used in the associated reader. AFAIK - we don't the phase field objects to worry about feature id so I don't think this is the right fix. Instead the Euler Angle provider needs to handle the local/global id instead.
