### ISSUE TITLE
Remove MaterialPropertyInterface::getMaterialSharedPointerByName

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7881]
### Description of the enhancement or error report

I don't see the purpose for this method. Materials should always be created through the factory system and stored in the warehouse. This means that the lifetime is managed by another object and that management is never handed off to consumers through this interface.
### Rationale for the enhancement or information for reproducing the error

Unnecessary and confusing method
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Relatively new method. We can probably deprecate it and remove it almost immediately.

**Comment by permcody** [comment]
I saw a potential bug while looking at those code. The `getMaterial()` method is dereferencing a local MooseSharedPointer in the return statement. This is semantically incorrect because it could potentially delete the resource.

**Comment by rwcarlsen** [comment]
FEProblem owns the referenced Material objects - so it is effectively simulation-scoped lifetime.  The shared pointer deref issue can't be fixed without a very significant API breaking change.  But we can still remove the extra function (that seems to serve no particular purpose).

**Comment by rwcarlsen** [comment]
fixed by #8278 - feel free to reopen @permcody if you feel otherwise.
