### ISSUE TITLE
Difference between python ParseGetPot and C++ version

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#7882]
### Description of the enhancement or error report

There seems to be a difference between the python and C++ version of parsing input files.
### Rationale for the enhancement or information for reproducing the error

`test/tests/bcs/penalty_dirichlet_bc/function_penalty_dirichlet_bc_test.i`
currently is missing a closing block `[../]` in `Functions/solution` (this should get fixed too).
The C++ parser seems to handle it fine.
The python parser puts the rest of the input file underneath `Functions`, which makes an invalid input file.
This can be seen on both the old and new peacock.
### Identified impact

There should be consistency between the two parsers.

**Comment by permcody** [comment]
Yes - we've known this for a long time. Derek's parser (they python) one is just a bunch of regular expressions with zero comments. It works pretty well but it's practically impossible to maintain. Those guys at Oakridge have developed an actual parser (based on flex and bison) that handles our syntax. I really want that parser and I'm going to push them for it. I wouldn't worry about trying to fix up the python parser right now.

**Comment by friedmud** [comment]
But them you would need flex and bison.

I think we'll always want a Python parser for MOOSE (for one reason or
another). The one I made was never supposed to be a long-term solution. I
just needed something that would work for the original Peacock. It should
be rewritten.

**Comment by permcody** [comment]
Flex and Bison are available everywhere including Macs. We should at least
consider it. Don't worry, we won't switch for no reason. I just know that
their parser caught a few other things that our parser doesn't. It's also
super simple clean code.

**Comment by brianmoose** [comment]
Just going to add this onto this issue.

There are several input files in the tests and modules directories that have
`active=''` set but that doesn't get matched by ParseGetPot and passed along. It is simply dropped.

For example, `test/tests/variables/fe_monomial_const/monomial-const-2d.i`.
When peacock reads this in it loses the `active = ''` and so it can't write it back out again. Running this input file with `moose_test-opt` will crash where it runs fine if the `active` statement is there.

**Comment by permcody** [comment]
Tag @rwcarlsen - Ticket to close
