### ISSUE TITLE
Solve convergence can depend on input file ordering of Variables

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#7883]
### Description of the enhancement or error report

Depending on the order of the variables in the input file, it can either converge or fail.
### Rationale for the enhancement or information for reproducing the error

In `test/tests/mortar/2d/equalgradient.i` if `/Variables/u` is moved after `/Variables/lmy` the solve fails to converge.
### Identified impact

It would be nice if order didn't matter.

**Comment by permcody** [comment]
Whoa - this sounds like another bug!

**Comment by friedmud** [comment]
It could be - but it doesn't have to be. Matrix ordering can effect many
things about the solver... including preconditioning...

**Comment by dschwen** [comment]
In this particular example the `c` variable is in a Cahn-Hilliard type equation, while `lmy` is a lagrange multiplier on the mortar interface. They are very different subproblems.

**Comment by fdkong** [comment]
Options `-pc_type hypre  -snes_fd`  could the failed one run. I think this application has a near-singular system.

**Comment by rwcarlsen** [comment]
Even if this isn't a bug in the originally implied sense, it still hurts reproducibility.  Maybe some sort of sorting on input file params like this could be done to achieve identical treatment from run to run regardless of input file ordering?

**Comment by fdkong** [comment]
> Even if this isn't a bug in the originally implied sense, it still hurts reproducibility. Maybe some sort of sorting on input file params like this could be done to achieve identical treatment from run to run regardless of input file ordering?

Good idea. But we do not know how to sort the variables until finished the nonlinear solver

**Comment by rwcarlsen** [comment]
You could even just sort the input file sections before processing them.  As long as everything else moose does is deterministic - the issue would be resolved.

**Comment by dschwen** [comment]
> You could even just sort the input file sections before processing them

No! Then the next bug would be "convergence depends on variable names!". That'd be even more insane!

**Comment by rwcarlsen** [comment]
@dschwen makes a good point.  We should only care about reproducibility from an identical input file standpoint.  It is a slippery slope to try to do anything more.

**Comment by permcody** [comment]
Closing - We have no plans to try to reorder variables in the system.
