### ISSUE TITLE
Not change the problem time by the Steady executioner

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#789]
The problem time is changed by Steady executioner. This could cause confusion to some time-dependent material properties. It has done to me. I am guessing applying the following patch will work this around.

Index: src/executioners/Steady.C
===================================================================
--- src/executioners/Steady.C	(revision 7726)
+++ src/executioners/Steady.C	(working copy)
@@ -53,7 +53,7 @@
 
   // first step in any steady state solve is always 1 (preserving backwards compatibility)
   _time_step = 1;
-  _time = _time_step;                 // need to keep _time in sync with _time_step to get correct output
+  Real initial_time = _time;
 
 #ifdef LIBMESH_ENABLE_AMR
 
@@ -69,6 +69,7 @@
     _problem.solve();
     postSolve();
 
+    _time = _time_step;                 // need to keep _time in sync with _time_step to get correct output
     _problem.computePostprocessors();
     _problem.output();
     _problem.outputPostprocessors();
@@ -85,7 +86,7 @@
     }
 
     _time_step++;
-    _time = _time_step;                 // need to keep _time in sync with _time_step to get correct output
+    _time = initial_time;                 // need to keep _time in sync with _time_step to get correct output
   }
 #endif

Many thanks.

**Comment by permcody** [comment]
This ticket is outdated and being dealt with in #5229.
