### ISSUE TITLE
Enabling Time Stepper to Control Transient Output

### ISSUE THREAD

**Issue by zachmprince** [idaholab/moose#7893]
### Description of the enhancement or error report

This enhancement would entail creating a function in TimeStepper which outputs a Boolean that would tell Transient whether or not to output the solution.
### Rationale for the enhancement or information for reproducing the error

The reason for the enhancement is the ability to create a new time stepper similar to DT2, but better suited for neutronics calculations in Rattlesnake.
### Identified impact

There would only be a few lines of code changed.  A new function in TimeStepper called enableOutput that would always return true.  And a call for this function in Transient right before the solution is outputted.

**Comment by permcody** [comment]
Closing - This design has been voted against by several members of the MOOSE team (See #7896).
