### ISSUE TITLE
Semiverify error in libmesh on Yak

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7897]
### Description of the enhancement or error report
I am able to produce this error with a test on
```
[~/projects/gitlib/yak/tests/multiscale/cd_saaf_diff_diff]> mpirun -np 2 ../../../yak-dbg -i 2reg.i

************************************************************************************

                                     YakTest       

************************************************************************************


YAK version:             git commit 8948eab on 2016-04-28

Framework Information:
MOOSE version:           git commit a41a3fc on 2016-10-18
PETSc Version:           3.6.0
Current Time:            Tue Oct 18 16:01:37 2016
Executable Timestamp:    Tue Oct 18 16:00:32 2016

Parallelism:
  Num Processors:        2
  Num Threads:           1


 Adding side sets for CD-SAAF
   Mesh modifier: diff1-to-diff2_interface
   Mesh modifier: boundary-splitter
 Adding side sets is done for CD-SAAF
Assertion `mesh.comm().semiverify (elem ? &bcids : nullptr)' failed.

[0] ../src/mesh/mesh_tools.C, line 1373application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
, compiled Sep  7 2016 at 16:17:47
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

I am using Mac OS X Version 10.10.5, with the following modules
```
Currently Loaded Modulefiles:
  1) moose/.gcc_4.9.1                 3) moose/.cppunit-clang             5) moose/.mpich-3.1.4_clang         7) moose-dev-clang                  9) moose/.vtk6
  2) moose/.clang                     4) moose/.tbb                       6) moose/.mpich_petsc-3.6.0-clang   8) miniconda                       10) moose-tools
```

The error does not always show up. Roughly 1 out of 10 runs I can see this error. It looks like the error is related with the internal boundary or side sets. The boundary IDs for an internal side on two processors do not match. I really need this to be fixed so that my application can do calculations with internal side sets reliably. 

### Rationale for the enhancement or information for reproducing the error
This looks to me a bug somewhere I cannot track down.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Make Yak run reliably for multiscale calculations.

**Comment by YaqiWang** [comment]
@jwpeterson do you have any idea why this could go wrong and suggestions to me?

**Comment by jwpeterson** [comment]
Are you using `DistributedMesh`?  The error is due to boundary conditions not being the same across different processors, not sure why that would not be repeatable though unless the partitioning somehow changes between runs.  It looks like you are adding sidesets manually?

**Comment by YaqiWang** [comment]
I am using replicated mesh. Yes, I have two mesh modifiers, one is `SideSetsBetweenSubdomains` in moose, the other is my own modifier which just break boundaries (real boundaries) into pieces.

**Comment by YaqiWang** [comment]
This could be a bug in Yak. We added several mesh modifiers and they both adding new side sets, but they are not sequentialized. The side set ID could be mismatched if the ordering of the execution of these modifiers are different. I am currently setting the `depends_on` parameter for all of them to avoid this possibility. Let us see if it will fix the issue.

**Comment by YaqiWang** [comment]
It seems fixing the order does not fix the problem. Should there be a synchronization of all processors after all mesh modifiers finish the job?

**Comment by jwpeterson** [comment]
On Wed, Oct 19, 2016 at 12:29 PM, Yaqi <notifications@github.com> wrote:

> It seems fixing the order does not fix the problem. Should there be a
> synchronization of all processors after all mesh modifiers finish the job?
>

That shouldn't be necessary, provided that all processors have done the
same thing.

I think you should be able to guaranteed that they all do the same thing in
your case without extra communication...

-- 
John

**Comment by YaqiWang** [comment]
It seems that I am shooting on my own foot. I use the action warehouse to get pointers of all actions in a certain type, assuming the actions are in the same order, but they are not. Let me think what is the best of way of fixing this.

**Comment by jwpeterson** [comment]
Ah, yes, that would also explain differences between runs, since the memory address is more or less random.

**Comment by YaqiWang** [comment]
I confirmed this is caused the randomly ordered mesh modifier execution.
