### ISSUE TITLE
Interface for retrieving ids of new grains from GrainTracker

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7928]
### Description of the enhancement or error report

To avoid needing multiple GrainTrackers in a single simulation, we need to create an interface where the ids of newly created grains can be retrieve rather than using the existing callback.

### Rationale for the enhancement or information for reproducing the error

@SudiptaBiswas said she needs to just retrieve the ids of new grains instead of inheriting from the grain tracker. The current design requires the use of multiple grain trackers for some simulations.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Add a new interface.

@dschwen - I suggest that we remove the existing interface later after this new interface is added. I'd rather not have two methods (a callback, and an accessor) for the same thing if we can avoid it.

**Comment by SudiptaBiswas** [comment]
Thanks @permcody. This would help in #7921 for assigning euler angles to new grains without inheriting from GrainTracker/GrainDataTracker. `GrainTrackerElasticity` might need changes to accommodate this as well.
