### ISSUE TITLE
Logic error in ComputeThermalExpansionEigenStrain

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#7932]
### Description of the enhancement or error report
The if/else if/else in the constructor will never hit the else block since stress_free_reference_temperature has a default value.  The code will run with that default value if stress_free_reference_temperature and stress_free_temperature are not given in the input file.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by bwspenc** [comment]
Ugh, you're right!  Is the fix to just replace `isParamValid("stress_free_temperature")` with `isParamSetByUser("stress_free_temperature")`?
