### ISSUE TITLE
Lengthy (mechanics) tests slow down testing

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#7938]
### Description of the enhancement or error report

Identifying and speeding up the tests which require more than 2.0 seconds to run in opt should reduce the time to test new code when submitting PRs to MOOSE in three of the modules.  
### Rationale for the enhancement or information for reproducing the error

`./run_tests -j8 -t`
### Tests with run time lengths that should be reduced:

If you see a test which you wrote listed below, please modify the input file so that the relevant physics are still tested while remaining under the 2.0 second guideline.  Once the test run time is below the 2.0 second run time limit, please mark the test on list below as complete.  Pinging @bwspenc @acasagran @dschwen @WilkAndy @hchen139 @jiangwen84 @jasondhales 

**combined module**
- [x] combined:nodal_area.Hex272Proc................................................... [MIN_CPUS=2] OK [3.127s]
- [ ] combined:ACGrGrElasticDrivingForce.bicrystal....................................................... OK [2.136s]
- [ ] combined:cavity_pressure.test............................................................................. OK [2.221s]
- [ ] combined:cavity_pressure.test_init_temp............................................................... OK [2.232s]
- [ ] combined:catch_release.test............................................................................... OK [2.552s]
- [x] axisymmetric_2d3d_solution_function.axisymmetric_2d3d_solution_function_3dz_scale.....OK [3.063s]
- [x] axisymmetric_2d3d_solution_function.axisymmetric_2d3d_solution_function_3dy_scale.... OK [3.144s]
- [ ] combined:contact.pressurePenalty_test................................................................... OK [4.135s]
- [ ] combined:frictional_contact/sliding_elastic_blocks_2d.base..................................... OK [2.608s]
- [ ] combined:frictional_contact/single_point_2d.fcp...................................................... OK [3.629s]
- [ ] combined:gap_heat_transfer_htonly.sphere3D........................................................... OK [3.155s]
- [x] combined:fdp_geometric_coupling.test................................................................... OK [5.472s]
- [ ] combined:glued_contact.test............................................................................... OK [3.885s]
- [ ] combined:frictional_contact/sliding_elastic_blocks_2d.fcp....................................... OK [6.944s]
- [ ] combined:internal_volume.hex20............................................................................ OK [3.667s]
- [ ] combined:mechanical_contact_constraint/blocks_2d.constraint_blocks_2d_glued_penalty_2......... OK [2.463s]
- [ ] combined:glued_contact.test2.............................................................................. OK [6.873s]
- [x] combined:nodal_area.Hex20_3............................................................................... OK [2.189s]
- [x] combined:nodal_area.Hex20................................................................................. OK [2.405s]
- [ ] combined:phase_field_fracture.crack2d.................................................................. OK [2.164s]
- [ ] combined:PLC_LSH_combined.combined................................................................. OK [3.104s]
- [ ] combined:PLC_LSH_combined.combined2TM.......................................................... OK [3.436s]
- [x] combined:poro_mechanics.borehole........................................................................ OK [2.071s]
- [x] combined:nodal_area.Hex20_2............................................................................... OK [2.410s]
- [ ] combined:nodal_area.Hex27................................................................................. OK [4.995s]
- [ ] combined:phase_field_fracture_viscoplastic.crack2d............................................... OK [6.118s]
- [ ] combined:solid_mechanics/beam_pbp.test_beam_pbp............................................. OK [2.203s]
- [ ] combined:PLC_LSH_combined.combined2.............................................................. OK [3.181s]
- [ ] combined:simple_contact.3D_dirac.......................................................................... OK [3.941s]
- [ ] combined:simple_contact.3D................................................................................ OK [3.963s]
- [ ] combined:solid_mechanics/hoop_stress.test.......................................................... OK [2.758s]
- [ ] combined:ring_contact.test................................................................................ OK [4.509s]
- [ ] combined:simple_contact.3D_2.............................................................................. OK [6.307s]
- [ ] combined:solid_mechanics/j_integral_vtest.j_ellip................................................... OK [3.037s]
- [ ] combined:solid_mechanics/j_integral_vtest.J_ellip_cm.............................................. OK [3.026s]
- [ ] combined:solid_mechanics/j_integral_vtest.j_ellip_cfp............................................. OK [3.044s]
- [ ] combined:solid_mechanics/j_integral_vtest.J_ellip_cm_cfp....................................... OK [3.036s]

**tensor mechanics module**
- [ ] cp_slip_rate_integ.test_with_linesearch................................................................... OK [4.601s]
- [ ] cp_slip_rate_integ.test_substep........................................................................... OK [4.634s]
- [x] mohr_coulomb.random....................................................................................... OK [2.117s]
- [ ] radial_disp_aux.sphere_3d_cartesian....................................................................... OK [2.637s]
- [ ] line_material_rank_two_sampler.rank_two_scalar_sampler..................................... OK [2.562s]
- [ ] radial_disp_aux.cylinder_3d_cartesian..................................................................... OK [3.107s]
- [ ] smeared_cracking.single_edge_notch.................................................................... OK [3.388s]
- [ ] smeared_cracking.single_element............................................................. OK [6.539s]

**solid mechanics module**
- [ ] cracking.rz_exponential................................................................................... OK [3.548s]
- [ ] interaction_integral_benchmark.test....................................................................... OK [5.422s]
- [ ] rate_dep_smear_crack.sent_test............................................................................ OK [8.206s]
- [ ] rate_dep_smear_crack.iso_test............................................................... OK [0.574s]
- [ ] cracking.exponential........................................................................ OK [7.571s]

**Comment by WilkAndy** [comment]
Thanks for identifying these, @sapitts .   It's a boring chore, but MOOSE would slowly fall apart if we didn't constantly improve it like this.

**Comment by permcody** [comment]
I kind of think that MOOSE would fall apart without @sapitts in general!

**Comment by WilkAndy** [comment]
Hi @sapitts .  I sped-up my two tests.  I can't add a tick mark to your boxes above, so you'll have to do it for me.  The tests are
mohr_coulomb.random
combined:poro_mechanics.borehole

**Comment by sapitts** [comment]
Thank you @WilkAndy - checkmarks added!  (and this was really @bwspenc's idea)

**Comment by gambka** [comment]
When migrating tests over to  tensor mechanics from solid mechanics some of the tests listed above were found to now run within the 2.0 second limit.  The tests are:

combined:nodal_area.Hex272Proc
combined:nodal_area.Hex20_3
combined:nodal_area.Hex20_2
combined:nodal_area.Hex20

**Comment by gambka** [comment]
The following tests are just above the threshold now ~2.01 and are only running a single timestep so I do not see any modifications to be made to speed them up further:

axisymmetric_2d3d_solution_function.axisymmetric_2d3d_solution_function_3dz_scale
axisymmetric_2d3d_solution_function.axisymmetric_2d3d_solution_function_3dy_scale

**Comment by gambka** [comment]
The following test is now below the threshold. I'll be committing a PR shortly.

combined:fdp_geometric_coupling.test

**Comment by sapitts** [comment]
Closing this issue because it's quite out of date and the testing system has since developed better controls for timing
