### ISSUE TITLE
Need Replicated/Distributed options in TestHarness

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#7941]
### Description of the enhancement or error report

We are still using the old parallel/serial options for the mesh_mode in the TestHarness
### Rationale for the enhancement or information for reproducing the error

These are deprecated names and should be removed
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Test specification file

**Comment by permcody** [comment]
@milljm - You could finish this ticket. The reason it's not closed is that I want to remove the old options now that the new ones have been in there for awhile.

**Comment by milljm** [comment]
I am not sure I am following you. Are you asking me to perform the `mesh_mode = SERIAL` to `mesh_mode = REPLICATED` in all our test files?

**Comment by permcody** [comment]
I think that's what I'm asking. Basically we shouldn't see SERIAL/PARALLEL anywhere anymore. It's now REPLICATED/DISTRIBUTED.

**Comment by permcody** [comment]
closed by #7941
