### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#7952]
### Description of the enhancement or error report
Need to add `#include <array>` to ComputeCappedWeakPlaneStress.h.

### Rationale for the enhancement or information for reproducing the error
Compiling on Mac gives many errors.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
Yikes! Are you submitting this fix, or do you need one of us to do it?

**Comment by jasondhales** [comment]
I'll submit it.
