### ISSUE TITLE
Output at Executioner's sync times

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#7964]
### Description of the enhancement or error report
The Outputs system has an option to output at sync times (`sync_only=true`). The sync times it uses for that is provided as a list in the `sync_times` parameter in the Outputs. The Transient Executioner also has its own independent notion of sync times (`Transient::atSyncPoint()`, `Transient::syncTimes()`).  I'd like to unify this somehow, and be able to have the `sync_only` option in the Outputs system do an output when the Transient thinks it's a sync time.

In addition to that, what I'm really after is that I want to have the time steps forced by the `force_step_every_function_point` option in IterationAdaptiveDT be treated as sync points. That's a one-liner. 

### Rationale for the enhancement or information for reproducing the error
We have complex time histories of power functions in BISON, and heavily use the `force_step_every_function_point` option to force steps at the "knots" in those functions. We would like to only output at those time steps.  We could do that now by adding all of those points to the sync_points in the Outputs system, but that would be cumbersome and error-prone.

### Identified impact
This would involve changes to the ways the Outputs system interacts with the Executioner and Timestepper.

**Comment by bwspenc** [comment]
Pinging @rwcarlsen and @aeslaughter I'm curious what you think of this given your work in these areas.

**Comment by bwspenc** [comment]
Pinging @zahom.  He's involved in this.

**Comment by aeslaughter** [comment]
> The Outputs system has an option to output at sync times (sync_only=true). The sync times it uses for that is provided as a list in the sync_times parameter in the Outputs. The Transient Executioner also has its own independent notion of sync times (Transient::atSyncPoint(), Transient::syncTimes()). I'd like to unify this somehow, and be able to have the sync_only option in the Outputs system do an output when the Transient thinks it's a sync time.

You can do this, just move the 'sync_times' parameter from the execution and put it in the Outputs block. The executioner will run at these times and output will do the same. 

There is already a ticket to re-designing the sync_times in general: #3487

**Comment by friedmud** [comment]
It's tricky because sync_times doesn't necessarily being in Output
either.... and telling the user to use the Output block to impact the
execution of their simulation is a bit odd...

**Comment by bwspenc** [comment]
@aeslaughter We can't actually do this because we don't have a list of sync_times.  The Executioner is figuring them out on the fly from a piecewise linear function that defines the time history of a boundary condition.  The Executioner is the thing that knows that it's a sync time.  We could copy the list of x values in that function into sync_times, but those could get out of sync (excuse the pun).

**Comment by aeslaughter** [comment]
There should probably be an "execute_on" setting for this. EXEC_SYNC_TIME.
Then the Executioner just calls output_warehouse.output(EXEC_SYNC_TIME), if
your outputs have sync time execute_on set to "sync_time" then you get
output.

I will consider adding this when I add the ability to do arbitrary
execute_on re-factor.

**Comment by permcody** [comment]
If you are going to add that particular execute flag, it really should be
available to all objects. You might only compute an expensive user object
and aux kernel when you hit a sync time for the purpose of output for
instance.

**Comment by aeslaughter** [comment]
I agree, I was just commenting that I will do this when I do the other
thing. I thinking there will be a list of default execution flags to which
the user can add new flags, the "sync_time" would be a default option.
