### ISSUE TITLE
Unit tests are leaking...

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7977]
### Description of the enhancement or error report
...and complaining about it. 

### Rationale for the enhancement or information for reproducing the error
<s>At first glance I noticed a few `new` operators without smart pointers or `delete`s in `ColumnMajorMatrixTest`. </s>

### Identified impact
This looks unprofessional (even though it has little practical impact).

**Comment by dschwen** [comment]
The unit tests not working in dbg is super annoying if you want to do debugging on them... 😠

**Comment by YaqiWang** [comment]
I believe somebody is willing to offer a beer for fixing it. May be we should increase the price to give people more incentive.
