### ISSUE TITLE
Rework the TensorMechanicsAction

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7987]
### Description of the enhancement or error report
We'd like to add the capability to compose standard models in the TensorMechanicsAction to allow for more compact input files and to enforce consistency w.r.t. incremental forms and coordinate systems.

### Rationale for the enhancement or information for reproducing the error
Simpler and less error prone input files.

### Identified impact
Added capability.

**Comment by permcody** [comment]
@dschwen - Lots of merged PRs on this issue. Should it be closed?

**Comment by dschwen** [comment]
> @dschwen - Lots of merged PRs on this issue. Should it be closed?

Yes
