### ISSUE TITLE
MooseMesh::prepare() is not clearing _mesh_subdomains before initializing it

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#7989]
### Description of the enhancement or error report
This is not typically an issue. But when we have a `BlockDeleter` mesh modifier, `prepare()` will be called twice and `_mesh_subdomains` will still contain the subdomain just erased when the second time it is called.

### Rationale for the enhancement or information for reproducing the error
Later `MooseMesh::meshSubdomains()` will returns wrong list of subdomains.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Seems nobody is complaining on this at this moment.

**Comment by WilkAndy** [comment]
Thanks @YaqiWang .  A student and I created this meshmodifier, and i don't have a lot of knowledge concerning the mesh stuff in moose (it's basically just a complete mystery that somehow works!).  Obviously we missed something here.
