### ISSUE TITLE
PorousFlowTask: Implement "cut" and "shifted" versions of VG capilliarity

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7994]
These are in Richards presently, so this task is part of transferring Richards capability to PorousFlow.  The "shifted" capillary function sometimes has superior convergence properties over standard van-Genuchten.  Both have finite capillary pressure at zero saturation, which is probably more realistic than the standard van-Genuchten relationship.

Perhaps this could be done at the same time as #6878 , along with unit tests?

Notifying @cpgr .

**Comment by cpgr** [comment]
I have a branch that has combined the VG relationships along the lines of #6878, just haven't pushed it yet.

**Comment by WilkAndy** [comment]
Oh cool.

**Comment by WilkAndy** [comment]
#6878 is kind of a boring issue, so i'm glad you did it instead of me!

**Comment by WilkAndy** [comment]
Note to Andy: This is very low priority.  These are actually never used in any of the tests, and i don't think they're used in any of our real simulations either.  The idea is to have a finite capillary pressure at saturation=0.

What is important is to get the "cut" version of VG relative permeability.  That is used in the tests, as it offers far superior convergence around saturation=1, since it is smooth there.

**Comment by WilkAndy** [comment]
Closing this as i think it's not physically useful.  A much better way of enforcing a finite capillary pressure in simulations is to have a nonzero value of residual saturation.  The relative permeability then keeps saturation larger than zero, so we don't get infinite capillary pressure anyway.
