### ISSUE TITLE
ComputeIndicatorThread assumes add

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#8000]
It is assumed in ComputeIndicatorThread that the Auxiliary variable computed by an indicator should be added to the solution, so the values of indicators are always cumulative. I have a case where the indicator value is not cumulative so I need to perform an "insert" instead of an add. 

Currently, this is not directly possible but it would be nice if it was. I have a hack for my case that works for now.

**Comment by friedmud** [comment]
Well - you can't interleave "sets" and "adds" because it's a PETSc vector... so to support "setting" we would need a whole 'nother loop over elements to allow that.

**Comment by permcody** [comment]
I don't see this changing any time soon. Closing since a workaround to the issue exists.
