### ISSUE TITLE
ComputeIncrementalSmallStrain -> ComputeIncrementalStrain

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8025]
### Description of the enhancement or error report
Rename `ComputeIncrementalSmallStrain` to `ComputeIncrementalStrain`

### Rationale for the enhancement or information for reproducing the error
Consistency with `ComputeAxisymmetricRZIncrementalStrain` and `ComputeRSphericalIncrementalStrain`.

### Identified impact
Could affect external apps. Will use deprecated registration of the old name.

**Comment by WilkAndy** [comment]
This will affect me and my few users.  It's not a big deal of course - the deprecation message will handle any panics.
