### ISSUE TITLE
Check input tests are not colorized correctly and (OK) is misleading

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8037]
### Description of the enhancement or error report

We now have several check input tests in the modules directories under "examples" folders. The coloring isn't correct on those Tests in the TestHarness and we might want to print a different status instead of (OK) since we aren't running these tests.

### Rationale for the enhancement or information for reproducing the error

Execute the ./run_tests scripts in modules

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No errors, just misleading status and inconsistent formatting.

**Comment by permcody** [comment]
@milljm - another task for you.

**Comment by permcody** [comment]
Closed by #8160

**Comment by milljm** [comment]
Reopen because I am working on it again.
