### ISSUE TITLE
Investigate checkpoint data size for BISON runs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8042]
### Description of the enhancement or error report

We have a report from the CASL guys that the BISON checkpoint files are around ~10MB. This seems large and will be prohibitive for larger scale runs where we have thousands of Multiapps. 

### Rationale for the enhancement or information for reproducing the error

Take a look at representative 2D-RZ runs or files from the CASL team.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

The ability to run full scale runs will be impaired.

**Comment by permcody** [comment]
Restart file sizes confirmed. It looks like the bulk of this information is in the restart file. BISON uses several different stateful material properties which can be fairly expensive (e.g. we need a dozen storage locations for a single linear quad). Considering that some of these properties are tensors further exacerbates the problem. We pack these structures pretty efficiently (byte representations of numbers and strings, very little overhead in terms of sizes because ordering or properties is given by the order in the source.

There may be things we can do to be even more efficient but that would be a large undertaking and may not result in significant savings.

**Comment by YaqiWang** [comment]
There could be one solution that just save the primal variables. Then when we do restart, we still start from the starting time, but only load the primal variables instead of solving to the restart points, and we also evaluate all the properties, postprocessors, etc.

**Comment by permcody** [comment]
Yes, I was thinking we might be able to regenerate certain pieces of information given only solution information as well. This would certainly be a large task though and would probably bring new problems to the surface. Clearly it's way out of scope for what little CASL funding we have this year. I mostly wanted to figure out if those current sizes are real and necessary and I have concluded that they are indeed given the current design of the restart system.

**Comment by permcody** [comment]
Closing - we have a good handle of what's in the restart file. Some of this data could be regenerated on restart but as it stands, we need all of this data.
