### ISSUE TITLE
Declaring material property multiple times should give an error, not a warning

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#8043]
### Description of the enhancement or error report
If you declare a material property multiple times from different models, it gives a warning:
https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblem.C#L4297
It seems to me like this should be an error.

### Rationale for the enhancement or information for reproducing the error
I can't think of a reason why you'd want the model to keep running in this case.

### Identified impact
Call `mooseError()` instead of `mooseWarning()`

**Comment by rwcarlsen** [comment]
@permcody @friedmud - any reason not to do this?  It looks to cause a few BISON tests to fail FWIW - but those tests should probably be fixed anyway.

**Comment by permcody** [comment]
I think it should be an error. It's undefined at best. 
You have to be careful though because it's just fine as long as the properties don't overlap on subdomains.

**Comment by friedmud** [comment]
I agree with @permcody

**Comment by YaqiWang** [comment]
I agree too. Are we erroring out if two materials with the same name are added?

**Comment by rwcarlsen** [comment]
@YaqiWang - currently we just print a warning for duplicately declared material properties.  This proposes to switch that to an error.

**Comment by YaqiWang** [comment]
Sorry, my question is unrelated with this issue. I can easily try out with moose test.

**Comment by lindsayad** [comment]
This is a corner case, but I didn't realize until today that if you have the same property declared in different materials on different subdomains, and **you don't explicitly** compute the property in one of the materials, the previously calculated values from the other material will persist.

**Comment by permcody** [comment]
Oh yuck, I thought we had a subdomain coverage check for materials to prevent this case (FEProblemBase). I also seem to recall that this code has been so hacked that it's probably unrecognizable by now. I would consider this a bug. It's similar to the case of requesting a material on a single subdomain but not providing it. I'm pretty sure we do handle that (and there's a test). I'd suggest that we open a new ticket. It's not really related to this issue.

**Comment by rwcarlsen** [comment]
@lindsayad - could you be more specific - the property persists across what - a time step, a change of mesh element, etc.?  Does this problem involve statefuleness at all?  Also as @permcody - we should move this discussion to its own new issue.
