### ISSUE TITLE
UserObject that can compute Material properties in an element

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8046]
### Description of the enhancement or error report

A UserObject that accepts a vector of Material property names.  Then DiracKernels can query this UserObject to get the MaterialProperties.  It will return a Real MaterialProperty, or std::vector<Real> MaterialProperty, or std::vector<std::vector<Real>> MaterialProperty, etc, (whatever is appropriate for the desired MaterialProperty) for the current element, in a similar way to when a Kernel uses getMaterialProperty.  The DiracKernel can then evaluate that MaterialProperty at any of the quadpoints of the element.

Most importantly for me is that the UserObject instructs the Materials to evaluate at the quadpoints of the current element, and has a method for getting these values.  Viz, not at the quadpoint of the DiracKernel, but at the quadpoint of the current element that the Dirac point is inside.

This should work for stateful material properties.  Personally I don't actually need the Old values, but I do need values of stateful Material properties at the first time step.

### Rationale for the enhancement or information for reproducing the error

In PorousFlow we always use full upwinding and mass lumping.  This means that we evaluate our Material properties based on *nodal* values of the variables, and then just store those values at the quadpoints.

Therefore, in the current setup of MOOSE, when the DiracKernel instructs the Materials to recompute the Materials at its Dirac point, I don't have access to the Materials properties that have been computed for that element by a Kernel.  I need those Material properties (eg, 8 of them for a hexahedral element), not the one(s) computed via a DiracKernel (eg, 1 value only for a single Dirac point in a hex element).

The UserObject approach will allow my DiracKernel to access all the MaterialProperties it needs.  These will be evaluated at the nodes of the element, and stored in the quadpoints of the Material.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Ability to simulate boreholes in PorousFlow, which is an important thing for us!

Tagging @cpgr .

**Comment by permcody** [comment]
Andy after our call yesterday @aeslaughter thought of another possible way to solve this problem. It seems like you should consider building a new intermediate material base class. In that class you'd do your tricks to compute properties at the nodes regardless of the integration rule. Then it simply wouldn't matter whether your material was being called via a kernel, or a dirac kernel or whatever. The correct number of values and the locations where they are evaluated would be properly handled. All of your materials would then inherit from this material.

Over times the design of this intermediate base class could evolve, perhaps we could make it detect which kind of loop it was in (Dirac versus normal Kernel evaluation) and calculate at different points appropriately, etc. I'm not sure of all of the scenarios but this might even be a reasonable class to put into MOOSE. 

We'll keep brainstorming ideas here.

**Comment by aeslaughter** [comment]
@permcody is saying that your special material that needs to be called from a DiracKernel should override the `computeProperties` and create a new loop that does the right thing for the number of nodes.

It should also set 'compute=false' in the input file or in the params of your special material.

Finally, your DiracKernel should call `MaterialPropertyInterface::getMaterial(...)` and get reference to the actual Material object that you need to call compute on via `Material::computePropertiesAtQp(...)`.

Doing it this way should remove the need to do any intermediate objects and like @permcody stated, you could do something tricky to make the qp loop do different things depending on how it is being used, perhaps keying off the 'compute' flag.

**Comment by WilkAndy** [comment]
Thanks for those thoughts @aeslaughter and @permcody .   I'm back from holiday now and will begin coding on the Dirac+Material stuff in a few days.  I'm bound to have lots of questions!

**Comment by WilkAndy** [comment]
OK, I haven't actually DONE anything yet, but i have a question about the Material.  In computeProperties, how do i make sure that the Property is sized properly?  I'm used to just writing _property[_qp] = expression, after MOOSE magically sizes _property for me.  But now i want to size _property to be the number of nodes, not the number of quadpoints.

**Comment by aeslaughter** [comment]
The MaterialProperty class has a "resize
<http://www.mooseframework.org/docs/doxygen/moose/classMaterialProperty.html#aa021844bad3e6fc723cd054e3e9a6107>"
method.

**Comment by WilkAndy** [comment]
Aha, resize sounds pretty easy, thanks @aeslaughter
