### ISSUE TITLE
Add Probabilistic Risk analysis module (Stochastic Tools)

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8065]
### Description of the enhancement or error report

We need a new module for doing PRA. This is it!

### Rationale for the enhancement or information for reproducing the error

New requirements for analysis

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact, just new capability

**Comment by dschwen** [comment]
Who's Rick?

**Comment by permcody** [comment]
I had to make sure that you didn't edit that in there...

**Comment by amjokisaari** [comment]
@dschwen the question is not "who's Rick" but "which Rick."  Generally when we speak of Rick, we're referring to the [Rick of dimension C-137](https://en.wikipedia.org/wiki/Rick_and_Morty), only the greatest mad scientist of all time.
