### ISSUE TITLE
Time checker for PRA Stochastic Tools

### ISSUE THREAD

**Issue by runfastman** [idaholab/moose#8070]
### Description of the enhancement or error report
Add an object to map time stepping in moose to the time sampling used in state based simulation.

### Rationale for the enhancement or information for reproducing the error
Needed for State Based PRA simulation

### Identified impact
No impact on other areas, because this is new development and not used yet.

**Comment by permcody** [comment]
@runfastman - Don't forget to edit this ticket and put in extra information for the three required sections above.

**Comment by permcody** [comment]
This functionality is going into Redtail, closing this ticket.
