### ISSUE TITLE
New MOOSE docs website discussion

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8094]
This ticket is here to discuss the remaining enhancements/issues needed before the new MOOSE docs site goes live.

http://mooseframework.org/docs/moose_docs/site/

Tag @idaholab/moose-team

**Comment by milljm** [comment]
Some of these things we have already discussed. Just posting them here... because.

What do we do with Twitter widget?
Build status widget?
Also, on the previous site, we have something there for Google Analytics. Easily addable.

**Comment by fdkong** [comment]
Website looks pretty good. 

If possible, I would like to have (1) a brief user manual (not necessarily comprehensive, brief would be better) for users to go through for a feeling of big picture. PETSc has one at http://www.mcs.anl.gov/petsc/petsc-current/docs/manual.pdf. If we could have something similar, it would be great.

(2) An introduction to developers, and then everybody becomes famous suddenly :).

**Comment by permcody** [comment]
I think the website looks good but the menus are still too slow.

There may be some intermediate design we can come up with that doesn't have the whole menu on the left all the time. I'm not against "hamburger menus", but it seems like we can just load the immediate menu without having the whole tree available all the time. As long as you can get home or even use your bread crumbs we should be able to slim the menu to be more flat.

**Comment by friedmud** [comment]
I like the actual documentation.  Everything else is unnecessary.  Our current website is better.

Let's just use the new Documentation and link to it from our current website like we do with Doxygen.

To get specific about things I don't like about the new design:

  1.  It's SLOW.  Everything is slow.
    - It takes a long time (nearly 1 minute when I just timed it!) for the front page to completely load (including the background images).
    - The front page is slow to scroll and jittery
    - Clicking `Get Started` it takes ~5 seconds to bring up the next box
    - It also takes ~3 seconds for that box to go away when you hit Cancel.
    - Resizing is incredibly slow and jerky
    - Clicking the "burger menu" takes ~5 seconds to load
    - Using the burger menu is unusably slow.
      - I'm often not even sure if it registered my click.
      - After opening a few things scrolling slows to a crawl
    - Switching to a tab that contains the website is even slow!

  2.  The menu thing is completely unusuable.
    - It's unusably slow (See 1)
    - It takes up a HUGE amount of screen real estate
    - This design was deemed bad many years ago.  We fought the HTML frame wars in the late 90's... and frames lost.  (I know this isn't frames... but it is essentially the same thing)
    - There is no good way to jump to what I want.  I don't want to have to navigate a menu... I want to use a _website_ (like the whole thing) to find what I want.  Why compress so much information into a tiny bar on the left?
    - The menu means that I can't use "Command+f" to quickly search for stuff (like I can on the Doxygen "Classes" page)
    - There is too much wasted space.

The menu should completely go.  It's just unnecessary.  I think the current front page of the current Wiki is a better "landing point" for documentation.  It breaks things out into categories... and tries to get users to go down the "correct path".  The actual documentation is not great there (this new stuff is better)... but navigating it is better.

The breadcrumbs are all that's needed to move back and forth through the hierarchy.  Sites ditched these hierarchical menus YEARS ago... they're just not the right way to use the web.

Smaller things:

 - `Edit Markdown` on object's documentation pages should not be a big button at the top.  It should be a small link somewhere down at the bottom and be called something like `Edit This Documentation`
 - The buttons on object's documentation pages should be in this order: Doxygen, Header, Implementation
 - All fonts need to be decreased in size.  Even on my maxed out DPI setting on my laptop I can basically see nothing and have to scroll around too much.
 - Create a `Systems` _page_ that I can bookmark... and basically looks like this: http://mooseframework.org/wiki/MooseSystems/
 - Create an `Objects` _page_ that lists every object like this: http://mooseframework.org/docs/doxygen/moose/classes.html
   - Alternatively: the `Objects` page could list every object grouped by `System`.
   - The basic thing is this: there should be ONE page I can bookmark and go to and hit `Command+f` to jump directly to the documentation I'm looking for...

That's all for now.

Let's not try to reinvent the wheel here.  The current website is just fine as a front page... let's use it... and then link to the nice new documentation from there.

**Comment by milljm** [comment]
What I am excited for, is how accurate and potentially autonomous the new site will be. I spent less than a minute looking for an issue and found that the 'Staying Up to Date' page on our current wiki index (http://mooseframework.org/wiki/) is just... gone:

  http://mooseframework.org/wiki/StayingUpToDate

(we should probably fix that)

Basically anything with a version stamped on it, is also inaccurate.

I for one like this modern look.
A little CSS, and perhaps some other image optimizations, will make it shine.

**Comment by permcody** [comment]
Derek's getting at the mechanics of the new site. The way it's generated
and the content itself is great.

**Comment by aeslaughter** [comment]
I don't have the speed problems, even at home with my slow connection, with exception of the front page images, those are just too big.

I like the idea of having a page, similar to Doxygen that lists all the objects, then the entire menu becomes manageable and probably just be a simple top navigation menu like the current website. The systems page can include all the Kernels, etc. with the list of sub-objects broken up by module as well. Doing this would also simplify some of the site generation complexity. I don't think it will be a ton of work but certainly take a little time.

**Comment by permcody** [comment]
If those images are just too big, let's resize them for "web viewing" and see if that helps the main page. 

Let's explore the idea of a different navigation system. I tend to agree that having all of the navigation forced into a large menu does feel a little bit like old style frames design. This is really close and the content is good!

**Comment by friedmud** [comment]
ok - lets try something then: let's see what the website would look like without the menu at all:

1.  Let's create the Systems and Objects pages I was talking about.
2.  Take the remaining "top-level" links from the menu and put them as regular links in the top menu bar.
3.  Create a "Documentation" link in the top menu that goes to a page that has similar links on it to what's on the front page of the Wiki.
4.  Remove the "pop-up" box on the homepage for "Getting Started"... and have that be a regular link that goes to a webpage with breadcrumbs for drilling down through the getting started process.
5.  Our pages should load blazingly fast.  There should be absolutely no need for JavaScript at all.  We're doing static site generation... we should be able to generate every page exactly as it should look using regular HTML/CSS during that process.

**Comment by friedmud** [comment]
To be clear: by "top menu" and "top menu bar": I'm referring to the top stripe of color on the top of the website.  It's currently blank, unused, space... and it's the right place to put the main links for our website.

**Comment by aeslaughter** [comment]
:+1:
