### ISSUE TITLE
Small typos in warnings and comments

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8129]
### Description of the enhancement or error report
Small typos in warnings and comments. 

### Rationale for the enhancement or information for reproducing the error
Clarify warning and error messages, fix code comments.

### Identified impact
No functional changes

**Comment by permcody** [comment]
@dschwen - just looking through issues. Seems this one can be closed?

**Comment by permcody** [comment]
Immediate issue appears to be resolved, closing.
