### ISSUE TITLE
Remove or cleanup "dumpSampleFile" methods in interpolation utilities

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8145]
### Description of the enhancement or error report

We have a dumpSampleFile method in most of the utils that dump a GNUPlot file for debug plotting purposes. This method and the purpose for it is very old and can probably be handled in newer better ways. There's also a `static int` in these methods that could be problematic if used in a multiapp setting.

### Rationale for the enhancement or information for reproducing the error

Potential bugs with using non-const statics

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Mostly unused debugging output, minor.

**Comment by lindsayad** [comment]
I also discovered that the dumpSampleFile method for SplineInterpolation is the exact same as for LinearInterpolation...which it shouldn't be if the goal is to include function fits as the method doc string indicates

**Comment by permcody** [comment]
I think we are going to just drop these methods. Nobody is using them anymore. They are very old and have outlived their usefulness.

**Comment by lindsayad** [comment]
@WilkAndy was just asking for an interpolation inspection method in #7158. Seems like a plot dump in general could be helpful for debugging and just making sure that the interpolation is sane.

**Comment by permcody** [comment]
True, but we have moved beyond GNUplot. These classes should probably just
dump CSV files and they can be read in by a MatPlotLib script or something
instead.

**Comment by lindsayad** [comment]
Good plan

**Comment by WilkAndy** [comment]
Sounds good to me too.  Just make sure that the user can specify the resolution for the "x" axis - we don't just want to dump the original data points in this case.  Typically we want many more "x" points than in the original.

**Comment by permcody** [comment]
closed by #12888.
