### ISSUE TITLE
Meta-meta actions

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8154]
### Description of the enhancement or error report

@jasondhales would like an Action that can create an Action that creates objects. Wow!
This doesn't work well reliably right now because we use a `std::vector` data structure per each task and pushing back on that might invalidate the iterator that other objects are holding.

The alternative solution is to create additional tasks but I don't like that solution.

### Rationale for the enhancement or information for reproducing the error

If we change the data structure, this should work naturally.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Internal data structure changes, no external API modifications.

**Comment by dschwen** [comment]
That is only one single meta!

**Comment by YaqiWang** [comment]
Yak already has this. We have an `AddTransportSystemAction` Action registered on `meta_action` tast. And in that action we call `_action_factory.create()` and `ActionWarehouse::addActionBlock();`. Do we need more for doing this?

**Comment by permcody** [comment]
The problem is that it wasn't guaranteed to work since we were pushing back onto a standard vector while maintaining an iterator over that vector. I switched it to a list so it will always work.
