### ISSUE TITLE
Issues with restartable data declaration for member variables in users mesh class

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#8157]
### Description of the error report

User generated unconventional 'mesh' for peridynamic application has the problem of being unable to access its unconventional member variables during the recovery test. Declaration of these member variables as restartable data won't solve this issue due to the residence where the restartable date live.

One possible solution is to construct these restartable data in some other objects, such as user object, later on after the peridynamic mesh is generated, and then access those data via the user object rather than from the mesh. Is there a better way to achieve the same purpose? Many thanks for any suggestion.

**Comment by permcody** [comment]
One other suggestion is to create a new callback on `MooseMesh` that gets called during setup well after objects are constructed where you could declare restartable variables. Most objects have an initialSetup() callback but the Mesh doesn't, we've never needed something like that before. It would be pretty easy to add this if you want to explore that route.

Tagging @friedmud to see if he has any other ideas.

**Comment by friedmud** [comment]
I'm thinking about it. :-)

**Comment by hchen139** [comment]
It make more sense to construct all the mesh related data information in the mesh class which currently is the case. A callback on the MooseMesh is a preferred option than the user object. I think we would like to go this direction. @bwspenc

**Comment by bwspenc** [comment]
Based on my discussions with @hchen139 about this, I'm pretty sure that we could accomplish everything we need here if we had another callback that got called after the mesh gets initially set up (which happens in `init()` currently), as long as that also got called after a recover.  In my brief look at this, it looks like maybe just making the `prepare()` method on `MooseMesh` virtual would give us the ability to do what we need to do.

**Comment by permcody** [comment]
`prepare()` gets called early, before the FEProblem is created. I was thinking more like adding an `initialSetup()` method and calling that from `FEProblemBase::initialSetup()`.

**Comment by friedmud** [comment]
Yeah - I honestly don't have any great ideas here.  I'm open to any
solution that works for right now.  The things I've thought of are:

1.  Give Mesh it's own RestartableData store (and therefore it's own
restartable data output file)
2.  Disallow having state in the Mesh! (I would be interested to know what
_state_ you are actually storing in the mesh)
3.  Building on #2 require a UserObject to actually hold any stateful data
inside of a Mesh.

But none of those are great... so I'm open to whatever works.

**Comment by friedmud** [comment]
Also: This is a fairly rare thing... so I _don't_ think we need to engineer some complicated solution for it.  Let's just find _a_ solution and then we can go from there.

**Comment by hchen139** [comment]
@friedmud To answer your question on #2, thinking of a element in FEM as a material point in Peridynamics, so, for each material point, it should have a area (2D) / volume (3D) associated with it. Each material point connects with its neighbors via EDGE elements (this is the element used to implement peridynamics based on MOOSE framework). Thus, neighbor list information also needs to be stored. Some other data, such as its distance to the furthest neighbor, and the summation of area/volume if all the neighbors.
It's preferably to have all these data calculated and stored at the mesh level, and can be used during a restartable run.

**Comment by friedmud** [comment]
But why can't you recalculate it when you restart?

**Comment by friedmud** [comment]
The general rule is to never store something for restart that can be recalculated instead...

**Comment by hchen139** [comment]
It's convenient and time-saving to calculate these data during the mesh generation in the buildMesh() method while the EDGE elements are being created. But the buildMesh() method definitely not being called during the restart. So, under current framework, there is no way to recalculate these quantities in the mesh class.

**Comment by friedmud** [comment]
Hmmm - how much time are we talking about here?  How long does it take to build these meshes?

We could certainly allow you to specify that your Mesh type needs to "rebuild" the mesh instead of reading it from a file...

**Comment by hchen139** [comment]
The most time-consuming part in the mesh generation is the neighbor search. Currently, the neighbor search algorithm is a global search, _n^2_ number of iterations with _n_ being the number of material points in the simulation domain.

It would be the best if the mesh can be "rebuild" instead of storing and reading from a file. What do you think? @bwspenc

**Comment by bwspenc** [comment]
This is stuff is time consuming, but not _that_ big of a deal in the big scheme of things.  At the moment our main goal is to just figure out a way to pass the tests when recovering, not to optimize things.

It would work either way -- whether we rebuilt the mesh or recreated just this data that we need.  This is definitely stuff that can be recalculated one way or another (either while rebuilding the mesh or in a separate initialization phase), so I don't think we should get too carried away engineering some solution built around storing restartable data.

**Comment by friedmud** [comment]
Ok - let's try to get a hook in that will allow you to rebuild the data then.

`initialSetup()` sounds reasonable to me.

**Comment by permcody** [comment]
@hchen139 - Do you need assistance with this?

I suggest that you just add this new empty virtual to `MooseMesh` and call it near the top of `FEProblemBase::initialSetup()`. If that works, we'll review it to make sure that it works with distributed mesh and other edge cases but that's all we really need here.

**Comment by hchen139** [comment]
Thanks. @permcody.
@bwspenc will work on this.

**Comment by permcody** [comment]
@bwspenc - Is your need for `MooseMesh::initialSetup()` just for declaring restartable data? If so, that's good information. I'm looking through the Restartable interface and the problem is that we need a subproblem to actually use it. However, I don't think that restriction buys us a whole lot. The RestartableData is actually stored on the App object which is always available where as SubProblem (or any Problem) is not. It's just a mostly-unecessary complication. The reason it's there is so that we can more easily support multiple problem instances in a single application. If we relax that restriction, then this whole interface can be made to drop the need for SubProblem at all.

**Comment by hchen139** [comment]
Current problem is that even after defining all user defined mesh data in the initialSetup() method, these data still cannot be accessed during the recovery. So, FEProblemBase is the right place to call MooseMesh::initialSetup()? Are there any other places need to be taken care of? Thanks.

**Comment by permcody** [comment]
No, that's the right place if we go that direction. 

I was suggesting backing out of using `initialSetup()` and trying to make the `declareRestartableData` stuff work for Meshes.

**Comment by hchen139** [comment]
@permcody Thanks.
declareRestartableData will work much better than initialSetup() at least for our case. For now, I will work on using the initialSetup() method to define user specified mesh data.

**Comment by bwspenc** [comment]
If I remember correctly, there were two problems with going the route of restartable data:

1. We didn't have support for doing that on the mesh
2. There was a pretty large amount of data that would need to be written/read.

**Comment by permcody** [comment]
OK, We'll I think it's possible to solve #1. Clearly I can't do anything
about #2.

**Comment by hchen139** [comment]
@bwspenc What need to be declared as restartable data for the current peridynamic models are the nodal information, i.e. its volume, horizon size, neighbor list and element list. Storing these data shouldn't be a big issue comparing to reconstruct them since neighbor searching etc. needs to be recalled if using the initialSetup(). As long as no additional user specified elemental information needs to be stored, I don't think there will be any issue with the restartable data write and read due to its size.

**Comment by hchen139** [comment]
One more question about where to call the MooseMesh::initialSetup() method. As mentioned before, the current merged implementation, i.e. calling MooseMesh::initialSetup() in FEProblem::initialSetup(), didn't give me access to those user defined mesh data. Rather than doing this, I tried to call MooseMesh::initialSetup() in MooseMesh::init() just before the conventional restartable mesh data being retrieved, and I can have access to those data and all my tests passed for a recover test. BTW, I didn't call MooseMesh::initialSetup() in the FEProblem::initialSetup() at all.
Any explanation on this? Thanks.

**Comment by permcody** [comment]
Calling MooseMesh::initialSetup() from FEProblemBase::initialSetup() is
indeed the right place. The big question is where in that routine. We build
the Resurrector object in that routine to populate data. I think the
current location may be before that which is why you don't have access. We
might just need to move it to a later spot in that routine. Feel free to
move it around and see if you can find a place that works for all your
cases.
