### ISSUE TITLE
A multiapp output issue

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8162]
### Description of the enhancement or error report
When `Outputs/file_base` of master is given and `Outputs/file_base` is not in multiapp, even we say `Outputs/exodus=true` in multiapp, no exodus file is generated. If, however, we remove `Output/file_base` in master, we will see the exdous files with name `master_file_name+_out_+multiapp_name+.e`. This can be easily reproduced with `tests/multiapps/full_solve_multiapp`.

### Rationale for the enhancement or information for reproducing the error
Looks to me this is not an intended behavior. Currently I have to set `Output/file_base` in multiapp to make the multiapp output.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Should not have impact. 

UPDATE 01/10/2017 (permcody):
I'm able to repeat this provided that I supply the `Outputs/file_base` parameter on the CLI. This issue is not repeatable if you put the file_base in the master input file directly.

**Comment by permcody** [comment]
Are you planning to fix?

**Comment by YaqiWang** [comment]
No. I will say in the issue if I do.

**Comment by YaqiWang** [comment]
@permcody this could be a low-hanging fruit you can easily harvest. Since you are working on multiapp stuff now, can you take a look?

**Comment by permcody** [comment]
Sure - it might be related to the ticket I just tagged you on.

**Comment by permcody** [comment]
Fixed when #8297 is merged.

**Comment by YaqiWang** [comment]
If user gave a wrong subapp name in CLI, will moose error out or just ignore it?

**Comment by permcody** [comment]
It should produce a normal unused parameter warning (or error if --error is
used).

**Comment by permcody** [comment]
Closed by #8286
