### ISSUE TITLE
Constraint system for contact fails in 1D

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#8164]
### Description of the enhancement or error report
When you request the constraint system for mechanical contact with a 1D mesh, you get a PETSc error immediately:
[0]PETSC ERROR: nnz cannot be greater than row length: local row 4 value 6 rowlength 5

### Rationale for the enhancement or information for reproducing the error
This can be reproduced with the attached files and the combined module.
[one_d_contact.zip](https://github.com/idaholab/moose/files/627785/one_d_contact.zip)

### Identified impact
Having robust contact is needed for the 1D cases.

**Comment by YaqiWang** [comment]
We met this problem before. Basically realized the current system does not work in 1D. It would be nice that somewhere in the code a meaningful error message is thrown if the capability is missing.

**Comment by permcody** [comment]
@fdkong - do you know what's wrong here?

**Comment by fdkong** [comment]
Possibly something is wrong in the function SparsityArgument or other similar functions. I have fixed a bug before in the SparsityArgument().  Let me take a look  into it.

**Comment by YaqiWang** [comment]
My issue is actually slightly different because I am not using the nodal constraint, instead face constraints. What I am getting is
```
ERROR: Cannot reinit 0D LAGRANGE elements!
```
Should I create a new issue or let you guys working with this issue for fixing the other type of 1d constraints? I can provide you an input but I think you should probably create a moose test for 1d face constraints.

**Comment by fdkong** [comment]
> My issue is actually slightly different because I am not using the nodal constraint, instead face constraints. What I am getting is
> 
> ERROR: Cannot reinit 0D LAGRANGE elements!
> 
> Should I create a new issue or let you guys working with this issue for fixing the other type of 1d constraints? I can provide you an input but I think you should probably create a moose test for 1d face constraints.

If you could reproduce this based on moose, I will take a look at this.  It is nontrivial for people who is not familiar with the physics to reproduce the issue. 

I have been having hard time to reproduce some issues in moose-based applications  using the pure petsc code. It takes so much time.

**Comment by YaqiWang** [comment]
No physics is needed, you can just solve diffusion equation and put `EqualValueConstraint` on the interface. I am trying to generate a split mesh for you.

**Comment by fdkong** [comment]
> No physics is needed, you can just solve diffusion equation and put EqualValueConstraint on the interface. I am trying to generate a split mesh for you.

How about ?
(1) Create an issue 

(2) Send us a moose input file  and a mesh file
