### ISSUE TITLE
The run_tests script in the combined module has the wrong app_name

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#8178]
### Description of the enhancement or error report
The executable name in the combined module has changed from modules-opt to combined-opt, but the run_tests script was not updated. It still has app_name = 'modules'.

### Rationale for the enhancement or information for reproducing the error
The run_tests script doesn't work in the combined module.

### Identified impact
The script does not currently work

**Comment by tonkmr** [comment]
@permcody somehow changing the run_tests in combined got missed

**Comment by permcody** [comment]
Thanks for the report.
