### ISSUE TITLE
Meta actions should be executed with mesh-only option

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8186]
### Description of the enhancement or error report
Because meta actions are actions of actions, they may create actions required by mesh-only such as adding mesh modifiers.

### Rationale for the enhancement or information for reproducing the error
All mesh related actions need to be executed.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact because none is trying to use meta actions. Yak has meta actions for adding mesh modifiers but we do not have the test currently.

**Comment by YaqiWang** [comment]
@permcody If you agree on this, I will send in a small PR.

**Comment by permcody** [comment]
This is fine.
