### ISSUE TITLE
Cleanup Assembly constructor

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8190]
### Description of the enhancement or error report

Right now we pass a reference to a pointer to the CouplingMatrix in Assembly. It turns out that we only ever update this pointer one time before we init so it's just a bad design. Instead, a `const CouplingMatrix` reference or pointer can be passed into the `init()` method where it is actually set and used for the first and only time.

### Rationale for the enhancement or information for reproducing the error

This effectively removes another "global variable reference " from the MOOSE framework making maintenance easier. It'll also enable me to change these raw pointers which are created in various places in MOOSE whose ownership is transferred into the problem and used by Assembly. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Lots of good cleanup and semantic ownership will be cleaner.

This change will have to be handled in multiple commits. I'll have to add the new interface while supporting the old interface so that Yak won't break...

**Comment by andrsd** [comment]
Just FYI:

1. preconditioners can build their own `CouplingMatrix`. Then they call `FEProblem::setCouplingMatrix`.  

2. You can certainly move the ownership of coupling matrix into Assembly, but then a) each thread will have its own copy of it and b) when using displaced mesh, you get another copy of it.

This is why `CouplingMatrix sits in `FEProblem` and other parts have reference to it...

But, maybe I did not understand, what you wanted to do in this ticket...

**Comment by permcody** [comment]
Yes, I understand that. FEProblem will still own the CouplingMatrix (std::unique_ptr()). This interface to set the CouplingMatrix passes a raw pointer (so not passing ownership semantics). I have the final patch already made. it's nice and clean.

**Comment by permcody** [comment]
@andrsd - I pushed it up here: https://github.com/idaholab/moose/pull/8180/files

This will fail though because I have to patch Yak first to use the Interface that this removes. I just wanted to see if the final version breaks anything else. If only Yak fails, I'll restore the old interface to Assembly and commit these patches in an interleaved order so we don't have to do an integration branch.

**Comment by andrsd** [comment]
Ok. Looking at #8180, this all makes more sense...

**Comment by permcody** [comment]
Closed by #8180.
