### ISSUE TITLE
PorousFlow Task: Complete refactor of Materials

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8196]
Notifying @cpgr .  I know you're away, but this is a major refactor, so i want to record here my rationale and what i've done.  I've still got a niggling feeling this is not a perfectly wonderful refactor - that there must be a better thing to do!  Also i'm not sure my actual implementation is the best.  It looks nice because generally it splits our Material classes into smaller chunks, but that makes the number of lines of code increase.  Also, the number of Materials is now almost double in most input file - we really need to write some Actions i think!

The general idea is that we now have two types of Material: a standard MOOSE Material that evaluates stuff at the quadpoints; and a new type of Material that evaluates stuff at the nodes.

To enable this, i've created a new PorousFlowMaterial from which all our Materials derive.  It is simple: it just has a parameter _nodal_material that may be set by derived classes.  If this is false then the derived Material behave as normal, otherwise a resizing of the Material Properties to the number of nodes occurs, and a loop over the number of nodes is performed (rather than a loop over the number of qps).

Why do this?

As you know, we have to lump and upwind, so these "nodal Materials" are necessary.  However, DiracKernels reinitialise Materials every time they do a residual or jacobian calculation, and the number of quadpoints in an element is equal to the number of Dirac points in that element.  Oh dear, that means that the standard Materials won't be sized correctly!  These new "nodal Materials" will be sized correctly, however.

It also allows us to remove PorousFlowNodeNumber.

**Comment by permcody** [comment]
Ideally this will be first class support in MOOSE someday in the future. I don't know exactly when but someday.

**Comment by WilkAndy** [comment]
Yea, and i bet you do a much better job of it than me, @permcody .   The bummer with my implementation is that in many cases it requires 8 times more evaluations than something like a nodal aux (for hexahedral elements).  The advantage of using Materials is that i have access to the DerivativeMaterial stuff, and my code is cleaner (only Materials and not Materials-plus-something-else), and sometimes it's not just a straightforward evaluation of functions at nodes, but is instead an extrapolation from qp to nodes.   Perhaps other advantages that i can't think of just now.

**Comment by WilkAndy** [comment]
accidentally closed!
