### ISSUE TITLE
Accessor to MooseApp::_check_input

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8204]
### Description of the enhancement or error report
Need this accessor.

### Rationale for the enhancement or information for reproducing the error
Looks like executioner init runs to complete with `--check-input`. Some of the codes may not need to be run in this mode. This accessor can give a way to protect these codes.

BTW, `protected` in `MooseApp.h` is accidentally removed in this commit 760eb5417c723b8b51c38a9887f58228b8400bd1!

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None.

**Comment by friedmud** [comment]
If I remember correctly... that `protected` was removed intentionally.... but it's been a long time...

**Comment by YaqiWang** [comment]
Does not make sense: looks all members after `meshOnly` should be protected.

**Comment by permcody** [comment]
I agree with @YaqiWang. You probably removed it to make a few methods public but you also exposed a few member variables including a map of handles. I doubt you intended to make that public, and if you did, it's was probably not the best idea 😄. 

That's a different issue from this ticket though.

**Comment by permcody** [comment]
Well this whole ticket is hilarious. @friedmud did indeed expose a ton of members "accidentially" when he only needed access to two. @YaqiWang, who reported the issue is the one already using at least one of the newly exposed members directly.  sigh...

**Comment by YaqiWang** [comment]
Oh! I feel bad, hehe. But that is Sebastian's code. This actually demonstrated a failing review process and a self-recovery for a long run.
