### ISSUE TITLE
Control Logic simplifications

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/moose#8216]
### Description of the enhancement or error report
InputParameters::getControllableParameters() should be const.
Control::_input_parameter_warehouse should be protected instead of private

### Rationale for the enhancement or information for reproducing the error
getControllableParameters() being const would allow classes that only have access to a const version of InputParameters to use it.

_input_parameter_warehouse being protected would save child classes of Control from needing to use _app.getInputParameterWarehouse() to get a variable that already is in the parent Control class.

### Identified impact
Simplifies creating control logics.

**Comment by permcody** [comment]
Closed by #8230
