### ISSUE TITLE
Remove old "JouleHeating" kernel

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8226]
### Description of the enhancement or error report

There's an old, probably unused JouleHeating kernel in the misc module. It has been superseded by 
#8222 and should now be removed.

### Rationale for the enhancement or information for reproducing the error

We don't want two kernels with nearly the same name floating around in the modules.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Probably nobody with the exception of a test or two.

**Comment by dschwen** [comment]
Closed via #8222
