### ISSUE TITLE
Implementation of the compressible Euler equations in rDG module

### ISSUE THREAD

**Issue by yidongxiainl** [idaholab/moose#8228]
### Description of the enhancement or error report
 
Following the recent implementation of rDG base classes in rDG module, we propose to implement an rDG solution to the compressible Euler equations at subsonic, transonic and supersonic flow regimes.

Note that in this context, "rDG" typically means 2nd-order cell-centered finite volume methods, which can be regarded as a subset of modal DG methods, when the polynomial order = CONSTANT. 

### Rationale for the enhancement or information for reproducing the error

Already in the rDG module, there is an example of the advection equation. But for most people who desire to solve systems of equations using rDG, it will be a good starting point if they can follow an Euler code. That is because the compressible Euler equations are in part of more complex systems of equations like in plasma physics and magneto-hydrodynamics (MHD).

Note that this is already on the wish list of university faculties and graduate students who are eager to see the class of finite volume methods available in MOOSE, so that they can do plasma physics and MHD with Godunov-type approximate flux and accurate shock-capturing.   

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Yidong Xia will be working on this ticket.
David Andrs will provide technical support.

**Comment by lindsayad** [comment]
@yidongxiainl Will this implementation expand `rdg` to multiple spatial dimensions?

**Comment by yidongxiainl** [comment]
@lindsayad Definitely. I already have lots of multi-dimensional test cases in a working branch.

**Comment by lindsayad** [comment]
Awesome. Exciting stuff!

**Comment by yidongxiainl** [comment]
As I am getting close to the completion of this work, I would like to showcase some animated GIFs to demonstrate the performance of the rDG-based code for solving shockwaves and contact-discontinuities. The input and mesh files for these test problems are included in the test directory. I will also post a few static figures that compare rDG solutions with available analytical solution data. 

1. **Sod shock tube**

![anim_1d_sod_dens](https://cloud.githubusercontent.com/assets/10405052/22801756/6211f5d0-eecb-11e6-8628-d3c0a2007672.gif)

2. **Lax-Harten shock tube**

![anim_1d_lax_dens](https://cloud.githubusercontent.com/assets/10405052/22801793/853efa80-eecb-11e6-9ce2-a47c3f2bcdf6.gif)

3. **Double rarefaction wave**

![anim_1d_drwave_dens](https://cloud.githubusercontent.com/assets/10405052/22801851/bab0ecaa-eecb-11e6-8e6a-7aa41df6e332.gif)

4. **Forward step in Mach-3 flow**

![anim_2d_forward_step](https://cloud.githubusercontent.com/assets/10405052/22801975/3e81ad76-eecc-11e6-9b7c-778fbd0adf73.gif)

5. **Bow shock upstream of a blunt body in Mach-4 flow**

![anim_2d_bowshock_dens](https://cloud.githubusercontent.com/assets/10405052/22802018/786d0d64-eecc-11e6-94a4-49e9f318b73b.gif)

**Comment by yidongxiainl** [comment]
Below are the some static results compared with available analytical solution data

1. **Lax-Harten shock tube**

![fig_lax_dens](https://cloud.githubusercontent.com/assets/10405052/22802288/7d146104-eecd-11e6-982f-97029102c3e9.png)
![fig_lax_pres](https://cloud.githubusercontent.com/assets/10405052/22802297/854193f6-eecd-11e6-8de3-2b2ec627b5f6.png)

2. **Oblique shock**
    * **Mesh**
![2d_obliqueshock_mesh](https://cloud.githubusercontent.com/assets/10405052/22802453/2a33f4e4-eece-11e6-9d2e-b208189652ee.png)
    * **Density contours**
![2d_obliqueshock_expl_weno_dens](https://cloud.githubusercontent.com/assets/10405052/22802469/320756f2-eece-11e6-82f1-2999baddf4db.png)

    * **Density profiles along the horizontal line of y = 0.35**
![2d_obliqueshock_pres_profile](https://cloud.githubusercontent.com/assets/10405052/22802497/3f29671c-eece-11e6-8c4e-069d3ab538f8.png)

**Comment by yidongxiainl** [comment]
@lindsayad please see above a bunch of showcases, including the 2D problems.

**Comment by lindsayad** [comment]
Very cool! Thank you for posting!
