### ISSUE TITLE
Incomplete csv files outputted from multiapp when damper block is used

### ISSUE THREAD

**Issue by gardnerru** [idaholab/moose#8245]
This problem was reported to bison from the Casl camp. They use the multiapp system to fire off thousands of bison runs to simulate a quarter core of pins. They reported that the csv file outputted from the master file had a complete listing of data from the run, but all the subs did not. Example files were sent to me and I confirmed that the master csv had 31 timesteps worth of data and the sub only had 6. The outputted .e files were complete for both. 

After some hunting, the damper block was found to be the problem. They had the following originally:

[Dampers]
  [./limitT]
    type = MaxIncrement
    max_increment = 20.0
    variable = temp
  [../]
[]

It was found that if the damper was changed to 100, or the damper block was removed altogether the sub csv file had the same 31 data entries. (note: I did not find the minimum number that the damper could be. I assume that it is problem dependent).

I have adjusted the moose gap_heat_transfer_htonly test to replicate the problem. input files are included in inputs.zip. 

Thanks

[inputs.zip](https://github.com/idaholab/moose/files/662129/inputs.zip)

@novasr @aeslaughter

**Comment by friedmud** [comment]
This makes absolutely no sense!

Thanks for putting together a test...

**Comment by rwcarlsen** [comment]
@aeslaughter - are you working on this - if not were you able to make any headway?

**Comment by aeslaughter** [comment]
I have plans to work on it, but have not started.

**Comment by rwcarlsen** [comment]
I'd like to take a crack at it today if you don't mind.

**Comment by aeslaughter** [comment]
Go nuts, you will probably vomit when you look at the Outputs code. I have
reasons for the way it is, but I plan on re-organizing it sometime.

**Comment by rwcarlsen** [comment]
#8360 fixes the issue in ``inputz.zip``.  @gardnerru - if you have a chance, it would be great if you could you check if #8360 fixes the same problem in the larger simulations you first saw it in.

**Comment by gardnerru** [comment]
That seemed to do it, I have matching output .csv files now in the original problem. Thanks.
