### ISSUE TITLE
Actions created by Actions are only put on a single task

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8259]
### Description of the enhancement or error report
I'm creating an action from the meta_action task of another action. The created action is only called on one of the created action's registered tasks.
I've verified that the task it is run on is the **first** one it is registered under (with `registerAction`)!

### Rationale for the enhancement or information for reproducing the error
Can be reproduced by running `moose/modules/tensor_mechanics/tests/generalized_plane_strain/generalized_plane_strain_increment.i` on cb01455afe9a6d9db7f4bbcf0ac189d6d184370f

### Identified impact
Fixing this will enable expected functionality for meta Actions.

**Comment by dschwen** [comment]
Ping @permcody and @aeslaughter.

This is probably because in [ActionFactory::getValidParams()](https://github.com/idaholab/moose/blob/devel/framework/src/actions/ActionFactory.C#L85) the iterator that is used to fetch the parameters is pointing to the first entry in the _multimap_ that holds teh build info for the various tasks for a given action name.

The task is passed through as an input parameter of type `std::string`. This allows only a single task to be transmitted to `ActionFactory::create()`.

Seems to be a bigger design issue.

**Comment by YaqiWang** [comment]
That is weird. We used this feature alot and did not see the same issue. Did you use action factory to create the action and then call `ActionWarehouse::addActionBlock`?

**Comment by dschwen** [comment]
Yep:

```
      // Set the action parameters
      const std::string type = "GeneralizedPlaneStrainAction";
      auto action_params = _action_factory.getValidParams(type);
      action_params.set<bool>("_built_by_moose") = true;
      action_params.applyParameters(parameters());

      // Create and add the action to the warehouse
      auto action = MooseSharedNamespace::static_pointer_cast<MooseObjectAction>(_action_factory.create(type, name() + "_gps", action_params));
      _awh.addActionBlock(action);
```

Looking at the source code it is totally obvious that the action will be registered to a single task.

**Comment by YaqiWang** [comment]
We had two more lines:
```
  _action_pars.set<ActionWarehouse *>("awh") = &_awh;
  _action_pars.set<std::string>("registered_identifier") = "(AutoBuilt)";
```
hope this can give some clue although I did not check the source.

**Comment by YaqiWang** [comment]
Yes, I think if you set parameter `registered_identifier` to something, you will be able to hit case 3 in `addActionBlock`, which is desired.

**Comment by dschwen** [comment]
`  _action_pars.set<ActionWarehouse *>("awh") = &_awh;` should not be necessary. This is added and set in `ActionFactory::getValidParams()` as a private parameter.

**Comment by dschwen** [comment]
Yup, the `_action_pars.set<std::string>("registered_identifier") = "(AutoBuilt)";` did it!

**Comment by YaqiWang** [comment]
I did not test, if you do not set `awh`, it will be `NULL`, which could cause issues later in the action.

**Comment by dschwen** [comment]
No it will not be null. It is set by `_action_factory.getValidParams(type);` (which I'm initializing the InputParameters` with.

**Comment by YaqiWang** [comment]
Oh, good to know.
