### ISSUE TITLE
YAML dump should quote some strings.

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#8263]
### Description of the enhancement or error report
BISON has a group name for one of its parameters that looks like `Advanced: description`.
This breaks YAML parsing due to the : followed by a space. We need to quote this in the YAML output to allow it to parse.

### Rationale for the enhancement or information for reproducing the error
Output valid YAML so that it will parse.

### Identified impact
This would only potentially affect peacock but since a quoted string is valid YAML it shouldn't be a problem.

**Comment by friedmud** [comment]
We could also quit using YAML ;-)

That choice was made a long time ago by an intern.  I really think we should be outputting JSON.  But maybe that ship has passed...

**Comment by dschwen** [comment]
@brianmoose this could affect the Atom autocompletion module as well (but I'm using a module to parse YAML, so if the new output is valid it should be fine)

**Comment by brianmoose** [comment]
@dschwen Well, it currently throws an exception when trying to parse the YAML dump for BISON (when using the python YAML parser). It is probably broken with whatever YAML module you are using since the current output isn't valid YAML.

@friedmud I plan on implementing JSON output with the other changes I am going to make to the output formatters. JSON is orders of magnitude faster to parse in python than YAML.

**Comment by friedmud** [comment]
Cool - good to know.
