### ISSUE TITLE
GitHub API official

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#8285]
Remove the header which allowed for beta testing to previously non-official API calls (https://github.com/idaholab/moose/blob/devel/scripts/github_traffic.py#L17) now that the API is official.

**Comment by permcody** [comment]
@milljm - This ticket is vague and doesn't specify any issues or enhancements. Can you either modify it, or justify and close it as appropriate?

**Comment by milljm** [comment]
@permcody 
I think we should just close this :/   I can't even remember doing it, or what.

**Comment by permcody** [comment]
Closing - doesn't specify and issue or requested enhancement.
