### ISSUE TITLE
modules/combined executables should be consistent 

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#8289]
### Description of the enhancement or error report
Doing a make in `modules/combined` produces `combined-$METHOD`
while doing a make in `modules` produces `combined/modules-$METHOD`

### Rationale for the enhancement or information for reproducing the error

They should build the same executable.

**Comment by friedmud** [comment]
I agree... and I vote for `combined-$METHOD`

**Comment by permcody** [comment]
I swear people hated that since we run "modules" tests. I recently changed this and forgot about the combined Makefile. I can change it back but there were others that were opposed. @bwspenc?

**Comment by friedmud** [comment]
Wait - I thought we changed it _to_ `combined-$METHOD`.  It used to be `modules-$METHOD` no matter how you compiled it... and you always had to remember that it was named differently from the directory it's in (unlike every other module).

**Comment by dschwen** [comment]
Wait, we just renamed it from modules-opt to combined-opt. I like that. All other executables are named like the directories they are contained in.

**Comment by friedmud** [comment]
@dschwen jinx!  You owe me a Coke!

**Comment by permcody** [comment]
Crap, I guess you guys are right. I blame it on sleep deprivation.
Derek, I though you drank Dr. Pepper.

**Comment by friedmud** [comment]
"Jinx! Pinch, poke, you owe me a _Dr. Pepper_"

Just doesn't have the same ring to it ;-)

But maybe they didn't play that game in Idaho with all the Jockey Boxes laying around... 😉

**Comment by bwspenc** [comment]
At the risk of joining into the jinx thing -- I like the new combined-opt name too.  If it doesn't always name it this way, it should.

**Comment by permcody** [comment]
I'll fix this and make it "combined-opt".
