### ISSUE TITLE
Convert contact patch tests to Tensor Mechanics syntax

### ISSUE THREAD

**Issue by acasagran** [idaholab/moose#8295]
### Description of the enhancement or error report
Create tensor mechanics based versions of the contact patch tests.

### Rationale for the enhancement or information for reproducing the error
Verify that the solutions from tensor mechanics and solid mechanics match for contact problems.

### Identified impact
Duplicated tests until solid mechanics is deprecated.

**Comment by permcody** [comment]
@acasagran - Is this ticket complete?

**Comment by acasagran** [comment]
Yeah for the most part. If we need to do more work on tests, I'll generate a new issue.
