### ISSUE TITLE
SolutionTimeAdaptive test is not robust on loaded machines

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8318]
### Description of the enhancement or error report

I routinely have to invalidate jobs because of timeouts on test `time_steppers/time_adaptive`.

### Rationale for the enhancement or information for reproducing the error

This stepper uses walltime and is not robust on loaded testing systems. We need to work to make this test work under all conditions or disable testing for this test. Perhaps dt_min/dt_max?

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Less annoying false failures from the testing systems.

**Comment by WilkAndy** [comment]
Will we ever get something similar that is repeatable over all machines/compilers/library-versions/etc?  In my opinion, it'd be cool to have SolutionTimeAdaptive to use cpu-time rather than wallclock time, but i don't think that's going to help with your testing problem.

**Comment by permcody** [comment]
Yeah there are ways to make this test stable. Debuggers can do that for instance (cpu ticks). There are always a million things to do!

**Comment by friedmud** [comment]
Just turn it into a "files exist" test for now... to at least keep running
it...

**Comment by permcody** [comment]
The problem is that it sometimes takes 2 seconds and sometimes times out at
over 300 seconds. I think narrowing the band of min/max dt is what needs to
happen here.
