### ISSUE TITLE
Doc string for MooseMesh/dim is not accurate

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8327]
### Description of the enhancement or error report
It says that `This is completely ignored for ExodusII meshes!`, but actually not.
https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L191 causes the default spatial dimension of the mesh is 3 regardless of the actual dimension of the mesh. I discovered this with our custom mesh extruder with a 2D exodus mesh file where we check if the mesh dimension and the mesh spatial dimension are the same. Once we specify `Mesh/dim=2 or 1` in the input, the extruder will work fine.

### Rationale for the enhancement or information for reproducing the error
Something is not very right. I suspect we should use dim=1 to construct the default empty mesh.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
No impact except my particular mesh extruder.

**Comment by permcody** [comment]
We may need to look at the underlying cause of why this is breaking. At the very least, @andrsd's suggestion of just changing the default in the input parameters is probably better but I would prefer to understand what about the extruder is causing you issues. We have several extruder tests that work fine in the framework. Is it because we aren't performing the same check as you?

**Comment by YaqiWang** [comment]
The custom extruder relies on node coordinates of the extruded dimension to hold the information which layer the nodes on. Then it can adjust nodes to the right position for nonuniform extrusion. To do this, the mesh has to be exact 1D or 2D for extruding to 2D or 3D. Thus I have a check in the extruder to make sure the mesh dimension and spatial dimension are the same before for the mesh to be extruded.

**Comment by permcody** [comment]
I don't think this check makes sense. Why can't you have "exact" 2D elements in a 3D spatial dimension?

To be clear, I'm ok changing the default if all tests pass. I'm just not convinced that your check is necessarily correct.

**Comment by YaqiWang** [comment]
Right, even if spatial dimension is 3, the z coordinates could be all zero. But on the other hand, if spatial dimension is 2, z coordinates for sure are zero. I agree checking mesh dimension and spatial dimension is too conservative. Otherwise, I do not have a good way to make sure if the mesh is indeed 2D unless to go through all the nodes. I have no other good ways to protect the code.

**Comment by permcody** [comment]
A better check would be to loop through all elements and see if they are of some desired dimension. One could for instance have a 2D mesh in the xz plane and extrude it in the y direction. Your check wouldn't allow that to happen.

**Comment by YaqiWang** [comment]
That is right, but then you could have for example R7 mesh, all elements are 1D, but you cannot extrude them because they are embedded in 3D.

**Comment by permcody** [comment]
I still don't see why. You simply extrude the elements along some axis. Sure there are potential issues with any embedded 3D mesh if you try to extrude in some direction where the new elements would lie within one and other. There are however some pretty cool things you can do if you don't put so many restrictions on them. You don't even need elements to be all coplanar for instance. You could extrude a curved surface.

**Comment by YaqiWang** [comment]
You are right on this too. That is the reason I put that check in my custom extruder although I have chance to try moving that into MOOSE extruder. I need an extruder to extrude the mesh with non-uniform size of layers desperately. `MeshTools::Generation::build_extrusion()` does not allow non-unform extrusion. I guess I should change that function instead of the current hack in my extruder to adjust nodes after extrusion. The check is to make this hack sane.
