### ISSUE TITLE
Error message of parallel test on test boxes disappears

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8332]
### Description of the enhancement or error report
This is causing Yak devel failing due to one of the tests because that test is expecting an error message. Serial tests run fine.
You can check out https://moosebuild.inl.gov/job/50414/.
This is critical to us because this failing blocks any merges requests in Yak.

### Rationale for the enhancement or information for reproducing the error
I cannot reproduce this on my Mac. This appears only on our test boxes. I am not sure why MOOSE does not hit this issue.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Parallel tests expecting error messages.

**Comment by permcody** [comment]
I suspect interleaved output in the parallel run. Jason's recently merged
PR which I'm not sure has made it to master will fix this error.

**Comment by YaqiWang** [comment]
Can somebody take a look at this? @permcody @milljm  Yak MRs are piled up.

**Comment by permcody** [comment]
So far unable to replicate on my mac. I'll see if I can't get onto a test machine to try it out.

**Comment by permcody** [comment]
Found the problem... The PR that was merged is lacking an important option "--keep-cout" for your warning expect error tests. I'll make a PR and get it up there but it'll take some time to get filtered all the way through to yak.

**Comment by YaqiWang** [comment]
Thanks Cody.

**Comment by permcody** [comment]
https://github.com/idaholab/moose/pull/8340
