### ISSUE TITLE
Fixup tests that repeatedly fail

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8352]
### Description of the enhancement or error report

Reference this ticket as we fixup several tests that fail sporadically.

### Rationale for the enhancement or information for reproducing the error

Watch for tests that show up sometimes as failed on the test boxes but can be cleared through invalidation

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

More robust testing, no code impacts

**Comment by brianmoose** [comment]
misc/line_source.test seems to timeout fairly often on the nightly Parallel Debug test.
https://www.moosebuild.org/job/103825/

**Comment by permcody** [comment]
Ticket is vague. We need to be better about be specific or there's no hope of clearing out old tickets. We'll open a new ticket to deal with specific tests.
