### ISSUE TITLE
Test the TestHarness

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8373]
### Description of the enhancement or error report

Yes, it's finally time to do this!

### Rationale for the enhancement or information for reproducing the error

To avoid regressions with modifications to the TestHarness.

- Need to test that multiple exodiff file tests always diff if one diff.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Improved robustness

**Comment by permcody** [comment]
@aeslaughter - if you get me started, I'll keep going - Thanks!

**Comment by permcody** [comment]
See #8382

**Comment by permcody** [comment]
- Need to test that multiple exodiff file tests always diff if one diff.

**Comment by mangerij** [comment]
who tests the tests of the tests....

**Comment by permcody** [comment]
CIVET!

**Comment by permcody** [comment]
Closing as we have several tests now. We'll continue to add more with new functionality.
