### ISSUE TITLE
Fix Jacobian in tests' DGMatDiffusion

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#8408]
Jacobian is currently wrong as revealed by test cases comparing `SMP` and `FDP` and also running `-snes_test_display`.

**Comment by YaqiWang** [comment]
We probably should merge it into `DGDiffusion` and give the default property for diffusion coefficient to 1. This way the code duplication can be removed.

**Comment by lindsayad** [comment]
A fair plan
