### ISSUE TITLE
Generated spherical surface mesh

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8414]
### Description of the enhancement or error report
At the CHiMaD workshop interest was expressed to have a mesh class to generate a spherical surface mesh included in the phase field module. I implemented one in https://github.com/dschwen/CHiMaD_Hackathon

### Rationale for the enhancement or information for reproducing the error
The spherical surface is the one other domain on which phase field simulations are routinely run (vesicle surfaces)

### Identified impact
Adds a small object that makes running (and demoing) such simulations much easier.

**Comment by YaqiWang** [comment]
Just curious, how the diffusion operator on a sphere would be? Can we still use the diffusion kernel to model it correctly?

**Comment by WilkAndy** [comment]
At your link, i couldn't see a spherical mesh generator, @dschwen .   I'm interested in this because I'd like to make a cylindrical mesh, or "tube" mesh (cylinder with axial hole) using MOOSE instead of having to muck around with cubit/trelis.

**Comment by dschwen** [comment]
https://github.com/dschwen/CHiMaD_Hackathon/blob/master/src/mesh/SphereSurfaceMesh.C

**Comment by WilkAndy** [comment]
Aha, i see.  I don't know why i couldn't find that before.   The code doesn't look to "libmeshy", so hopefully i can do my disc/cylinder/annulus/tube.

**Comment by permcody** [comment]
Yes @WilkAndy, you can build very complicated meshes programmatically. We have others internally that build reactor cores. Let us know if you need guidance but Daniels example is a good start for you.

**Comment by jwpeterson** [comment]
Just wondering if you saw the existing `MeshTools::Generation::build_sphere()` routine in libmesh (src/mesh/mesh_generation.C).  Maybe it could be extended to have a "surface only" option in 3D?

**Comment by WilkAndy** [comment]
Wow, lots of good stuff in that mesh_generation.C .   I often wish i knew more about libmesh.

**Comment by dschwen** [comment]
@jwpeterson I did not see that routine. I think I can refactor my code to use the same AMR based construction process, which would shorten it a lot. I am using dodecahedron refinement rather than cube refinement, which results in more even meshes. And I'm using tri meshes.

**Comment by jwpeterson** [comment]
> which results in more even meshes.

More elements?

> And I'm using tri meshes.

Yeah.  I guess you could also split every quad face into 2 (or more) triangles in the existing AMR approach to end up with triangles on the surface.  Your method might give better quality surface meshes, not sure.

**Comment by dschwen** [comment]
> More elements?

No, the elements are more homogeneous in size and shape.

**Comment by jwpeterson** [comment]
Sorry, I read "more even" as "even more" for some reason...

**Comment by dschwen** [comment]
Revisiting this. I just realized that I did implement @jwpeterson's suggestion already but never followed up on the PR...
