### ISSUE TITLE
Inconsistency between the input file of Example1 in github and the one described in the tutorial

### ISSUE THREAD

**Issue by gweishar** [idaholab/moose#8429]
### Description of the enhancement or error report
I was following the tutorial of Example 1 and everything compiled fine with the file I created using the code on the webpage http://mooseframework.org/wiki/MooseExamples/Example_01/
But when I saw the results using paraview, the out.e file had 0 for the diffused variable on the whole mesh. The out.e file produced from within the example folder in the moose directory the mesh had the correct values for diffused variable.

Comparing the two files I found one key difference in the Outputs system definition.
In the tutorial on the website its defined as:

[Outputs]
  file_base = out
  screen = true
  exodus = true
[]

On the moose folder:
[Outputs]
  file_base = out
  execute_on = 'timestep_end'
  exodus = true
[]

I suggest that the tutorial on the website should be updated. I am creating the files from scratch by generating an app per example (I decided this was the best way to learn MOOSE and maybe others think the same).

Also I want to ask what is this execute_on parameter? 
In the Doxygen pages I didn't find any explanation as to what this does and what happens if we set to "timestep_end".

Thanks in advance,
Guilherme

**Comment by andrsd** [comment]
> Also I want to ask what is this execute_on parameter?

It says when the output is produced. Its default value is `initial timestep_end`, which means we will output your initial condition and the solution at each timestep after the solve.

Those zeroes you saw in paraview was the initial condition. If you clicked the right arrow in the VCR control it would show you the solution (as a "second time step").

**Comment by gweishar** [comment]
So by setting execute_on with timestep_end we will only produce the result for the last timestep.
Ok thank you very much andrsd, that was a clear explanation. I guess this not an issue.
But can I keep using this as a forum to ask questions? I just started learning how to work with Moose and when fundamental questions pop up it's good to ask them in a active location. The google groups are quite inactive the last few months it seems.

**Comment by permcody** [comment]
The google groups have dozens of posts each day. We'd prefer you use them
for questions.

**Comment by WilkAndy** [comment]
@gweishar , perhaps you're looking at the wrong user group.  Have a look at

https://groups.google.com/forum/#!forum/moose-users

There were 18 posts yesterday according to me.

**Comment by andrsd** [comment]
> So by setting execute_on with timestep_end we will only produce the result for the last timestep.

Yes, if your executioner is `Steady` as in example 1. For `Transient`, you get 1 for each time step that converged. If you wanted just the last one, you would say `execute_on = final`.
