### ISSUE TITLE
Limit Navier-Stokes kernels & variables to a subdomain

### ISSUE THREAD

**Issue by Chuban** [idaholab/moose#8433]
### Description of the enhancement or error report
The current Navier-Stokes actions apply the kernels and variables to the entire problem domain.  It should be possible to limit these actions to a specified subdomain(s).  This can be accomplished by making NSAction block restrictable and making the appropriate changes in AddNavierStokesVariablesAction and AddNavierStokesKernelsAction.

### Rationale for the enhancement or information for reproducing the error
I am running simulations that require fluid flow only in a subdomain of the problem and would like to avoid unnecessary calculations.

### Identified impact
An optional 'block' input will be added to the Navier-Stokes actions.

**Comment by andrsd** [comment]
Please note that if you make the variables subdomain restricted you do not have to block restrict the kernels. Unless your primary variables live in the whole domain and the PDE "exists" on a subdomain. But then you will need to provide subdomain restricted kernel for the rest of the domain.

Keep this in mind if you are going to work on this. It may make your life easier...

**Comment by Chuban** [comment]
@andrsd Thanks for the tip.  Restricting the variables works for my application.  There should be PR shortly.
