### ISSUE TITLE
Markdown extension to link to Githuib/Gitlab issues/PRs

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8435]
### Description of the enhancement or error report
A markdown shorthand to link to issues and PRs would be helpful especially when working on software quality docs. The extension could use the `repo_url` data in `moosedocs.yml`.

### Rationale for the enhancement or information for reproducing the error
Clear syntax to link to issues (robust w.r.t. repo migration).

### Identified impact
Added capability.

**Comment by aeslaughter** [comment]
I will do this if you make the search bar work.
