### ISSUE TITLE
VectorPP to output material props for an elem, vector of elems, or maybe block

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8436]
### Description of the enhancement or error report

We need a VPP to output material properties for an element, or vector of elements or a block as an additional debugging tool.

### Rationale for the enhancement or information for reproducing the error

This VPP should take a list of material properties and a list of elements and output all of that information through the VPP facility.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No capability for debugging

Tag @aeslaughter or @rwcarlsen - maybe one of you could take a crack at this?

**Comment by aeslaughter** [comment]
What is the time frame on this? If you need it soon I could try to knock this out later today.

**Comment by aeslaughter** [comment]
I envision the output as

mat_out_vpp.csv
```
elem_id, qp, prop0, prop1, prop2
52, 0, ...
52, 1, ...
52, 2, ...
101, 0, ...
101, 1, ...
...
```

**Comment by permcody** [comment]
Soon but don't kill yourself over it, just might be useful in the coming weeks. That output seems reasonable.

**Comment by permcody** [comment]
We'll have to have several vectors for more complex types (vectors, tensors)

**Comment by aeslaughter** [comment]
We also need to think about how the data will be plotted, the format I have wouldn't work very well for plotting. Maybe we need one file per element.

**Comment by friedmud** [comment]
I think it will be fine.  If you want it per element then you can just
create separate VPP blocks with one element each...

**Comment by andrsd** [comment]
What do you want to do about stateful material props?

**Comment by andrsd** [comment]
Never mind, I was thinking something else - `LineSampler`...

**Comment by YaqiWang** [comment]
Should we just accept a material name instead of names of properties? Also is VPP always on elements but not on sides?

**Comment by friedmud** [comment]
Yeah - material name.

**Comment by rwcarlsen** [comment]
I'll get a PR in tomorrow.
