### ISSUE TITLE
Rework stateful material tests

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8438]
### Description of the enhancement or error report

We should probably rework the stateful tests and definitely the stateful material example. Each of these uses the declare(old|older) syntax which we are moving away from.

### Rationale for the enhancement or information for reproducing the error

Moving towards demonstrating one way of doing something even though we'll continue to support multiple ways of doing that thing.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Clearer APIs for users, clearer understanding of the code.

**Comment by permcody** [comment]
I can see that the example has indeed been reworked. The tests however are a pretty big mess. All of the stateful tests should probably be re-evaluated and reworked.

**Comment by rwcarlsen** [comment]
I can take a look at these soon.

**Comment by permcody** [comment]
Closed by #8519.
