### ISSUE TITLE
Analyze and replace TBB concurrent map

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8450]
### Description of the enhancement or error report

We may have a serious problem with using TBB's concurrent map to store material properties. This issue was originally reported by @snschune and @YaqiWang. I have replicated the huge memory allocation in a pure MOOSE example similar in size to the one reported in Yak.

### Rationale for the enhancement or information for reproducing the error

We have been using TBB's concurrent container for several years but it looks like this map may be the problem... Perhaps, it's just our usage of the map but I'm not sure how are usage is incorrect.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Applications using stateful properties occupy a lot more memory then they should:

![concurrent_unordered](https://cloud.githubusercontent.com/assets/3036960/22535080/35eb5478-e8be-11e6-8488-6ed17222369d.png)

Note: The x-axis (time) for this log is not relevant. I hit Ctrl-C to terminate the test at a random time after the solve began. Only the y-axis is relevant.

The test file and minor changes to one of the existing materials used to replicate can be found here: https://github.com/permcody/moose/commit/df118b835f8d97b9c440dfe0d5143fe139b86ccd

**Comment by permcody** [comment]
@friedmud and I were talking about this and we don't think we need to use a thread-safe container to store these stateful properties. Right now we are using a threaded loop object to fill the container but it's just unnecessary. We could just use the unordered map with locks, or alternatively we could populate the map outside of the threaded region and make sure that additions to the map (prolong and restrict) are also outside of the threaded region.

@snschune - we should probably configure MOOSE without TBB and try you example again. If that solves the problem, we'll decide on a path forward.

**Comment by snschune** [comment]
> we should probably configure MOOSE without TBB and try you example again. If that solves the problem, we'll decide on a path forward.

Ok, we can do that tomorrow, unless you are going for it tonight. In that case let me know if you can access the test case.

**Comment by friedmud** [comment]
Just - wow.  We've had this punishing us on every dang run of BISON for the
last 7 years!  Unbelievable.

I think we should just stick to locking with unordered map until we get
some timing showing that that locking is slowing things down...

**Comment by permcody** [comment]
I still feel like something is wrong with the way we are using this map or something. How can it be this bad!?

**Comment by permcody** [comment]
Well I had debug printing turned on which is likely a huge factor in these
timings as I was spewing information per element as it went into the map
and also printing the entire data structure back out. I'd have to remove
and rerun before we can draw any conclusions about timing. I probably won't
do that while I'm on my laptop but I'll rerun these benchmarks when I
return to the lab.

**Comment by permcody** [comment]
OK - I redid the timing after removing all my debugging print statements. It looks like using the unordered map is indeed faster by about 20%

![unordered_vs_concurrent](https://cloud.githubusercontent.com/assets/3036960/22655999/2afd8704-ec4f-11e6-98a2-94b43c80518b.png)

**Comment by friedmud** [comment]
Cool - rip that thing out!

**Comment by permcody** [comment]
Note: I'm checking in a test called `many_stateful_props.i` on a smaller mesh so it runs quickly and consumes little memory. We can simply edit the input file to increase the mesh size (180x180) to replicate this old behavior should we need it again in the future. It'll be on the PR associated with this ticket.
