### ISSUE TITLE
Update Python Standard

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#8454]
We are developing a significant amount of python code to support MOOSE, updating the standard would make writing this code much nicer.

## 4 Spaces
I understand we have been using 2 spaces for years and the C++ is using 2, but python is different and considering the importance of whitespace in the language, 4 reduces the number of mistakes made. If we didn't modify the standard to account for lessons learned or to improve code we wouldn't be using C++11 or enforcing spacing between mathematical operators.

## Docstrings
Another large change would be to use proper python style docstrings, which allows python interpreter help to properly display comments for a class, member, or method.

## Enforce the Standard
I have started to develop a pylint configuration that will enforce our standard, whatever it might be to include additional things:

* Define all member variables in __init__
* Don't allow calling of "protected" methods from outside the class
* Require the use of documentation string
* Mandate the member and method naming conventions

The pylint configuration has plugins for atom, emacs, and vi so we should be able to have on the fly warnings with whatever editor you prefer.

I would like the @idaholab/moose-team to voice there opinions, let the rioting begin.

**Comment by rwcarlsen** [comment]
I strongly support all those recommendations.

**Comment by aeslaughter** [comment]
:+1:

**Comment by lindsayad** [comment]
How about python3 compatibility??

**Comment by friedmud** [comment]
I'm still against 4 spaces.  Every damn file in all of MOOSE: bash, C++, input files, python... everything is indented with _2_ spaces.  It's been this way since the beginning.

**Comment by andrsd** [comment]
If we used tabs, you could set your editor to as many spaces you wanted 😈

**Comment by rwcarlsen** [comment]
I actually really like tabs.  I would be in favor of switching to tabs for everything (c++, python, bash, etc.).  Makefiles only work with tabs anyway ;-)

**Comment by jwpeterson** [comment]
> If we used tabs, you could set your editor to as many spaces you wanted

![gas-on-fire](https://cloud.githubusercontent.com/assets/1775907/22559454/bceae3a8-e936-11e6-8a53-bb9830dfdfec.jpg)

**Comment by aeslaughter** [comment]
I like tab:

![](http://www.drinkwhat.com/wp-content/uploads/2011/01/Coca-Cola-Tab-Diet-Soda-Drink.jpg)

**Comment by friedmud** [comment]
<img width="650" alt="python_trump" src="https://cloud.githubusercontent.com/assets/870705/22560197/4a41ba5e-e939-11e6-8d47-8ab582f2bfe8.png">

**Comment by aeslaughter** [comment]
This is complete.
