### ISSUE TITLE
MooseVariableScalar fails on processors which can't see a SCALAR

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#8455]
### Description of the enhancement or error report

MooseVariableScalar::reinit() tries to read a SCALAR value from solution vectors.  It fails (with a segfault in opt mode or a PetscVector assertion failure in devel/dbg modes) in cases where the SCALAR dof index is not ghosted on the current processor.  This can happen in degenerate cases where the current processor has no elements, but could also happen in real runs if the current processor has no elements or neighbors which belong to the subdomain of a subdomain-restricted scalar variable.

### Rationale for the enhancement or information for reproducing the error

./run_tests -p 3 --re ics/function_scalar_ic.test

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

I'll have a 3-line fix PR shortly.  No API changes.

**Comment by roystgnr** [comment]
Fixed by #8456

**Comment by lindsayad** [comment]
Can someone tell me the purpose of subdomain restricted scalar variables? Why are we associating them with space at all? Is this an optimization?

**Comment by friedmud** [comment]
I believe that it's for Jacobian calculation (more specifically: to control
the sparsity of the Jacobian).  It subdomain restricts the dofs the scalar
variable can be coupled to.

Derek

**Comment by roystgnr** [comment]
Controls the sparsity of the full Jacobian, and also the size of the element Jacobians+residuals.
