### ISSUE TITLE
MooseApp::getOutputFileBase() is returning empty

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#8460]
### Description of the enhancement or error report
Noticed this when I try to use it to construct a file name in my action.

### Rationale for the enhancement or information for reproducing the error
Should simply return the file base of the current moose app.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
App using this interface function.

**Comment by rwcarlsen** [comment]
Can you be more specific? - what are you input file(s) and in what sort of code and when are you calling the function?  Perhaps you are calling it before it has been initialized.

**Comment by permcody** [comment]
The problem is that the name of that method is poor. It's used by the Multiapp to retrieve the prefix of it's immediate parent. It has nothing to do with the `Outputs/filebase`. I think the setter/getter methods for this prefix should be more appropriately named. 

Additionally, if you look at the code, it's only populated when a multiapp is created. It's a public API so we could probably do something smarter here...

**Comment by rwcarlsen** [comment]
Well - How about deprecating it and creating a new function named ``multiappPrefix``

**Comment by permcody** [comment]
Yes - let's deprecate and do something different. Yaqi was trying to do his own output from a GeneralUserObject which is bad and I don't really care to support that. The App filebase doesn't really make sense with the current Outputs system since you can put filebase under each subblock. However, he went for that method because the name indicates that it's probably the thing he wants.

**Comment by YaqiWang** [comment]
Sorry to revive this thread. Can we fix this? I am asking because I noticed bunch of output conflict when I run `./run_tests --pedantic` in Rattlesnake. Most of those conflict can be simply fixed if we create output files based on the file output base.

**Comment by permcody** [comment]
Would you mind fleshing out the detail a tiny bit more. I recall this issue and the ensuing PR and everything else. It would have been nice to fix it properly the first time. I still stand by my original comment that the name is misleading so it should be renamed for the internal use where it's currently being called. Adding a new method that returns a filebase seems very simple to me but there might be implications when dealing with multiapps.

**Comment by YaqiWang** [comment]
I actually did not look into where that `getOutputFileBase` is used in MOOSE. The naming suggests it is the same as in the input file `Outputs/file_base`. Because in every test, this `Output/file_base` must be different, if we can create some outputs based on it, naming conflict can be avoid in those tests even they are using the same input file but with different command line parameter overriding. If the currently function is used with a different interoperation, we should rename it as @permcody said. @permcody what do you mean *might be implications when dealing with multiapps*? Should this function just simply reflect `Outputs/file_base`?

**Comment by permcody** [comment]
>  @permcody what do you mean might be implications when dealing with multiapps? Should this function just simply reflect Outputs/file_base?

Multiapp defaults are more complicated and I thought that this is where this method was being used. If your multiapp doesn't have a file_base, you'll get output based on the master name, not the sub_app file name. This is usually very handy. I just wanted to make sure that changing the behavior of this function doesn't have any consequences for that case. I would hope that we have sufficient testing at this point though so you'll probably see an issue if there is one.

**Comment by YaqiWang** [comment]
Currently even I do `Outputs/file_base=bla`, this function is still returning empty. I might need to mention that I checked its returned value in an action with task `add_postprocessor`. In the case with multiapp, it sounds to me we need to maintain a flag to indicate if the default file_base is used or not.

**Comment by permcody** [comment]
Right, my original comment said that it didn't have anything to do with filebase. I still stand by that.

**Comment by YaqiWang** [comment]
Ok, since I really need this, I will work on this. I think I have a good idea on how this should be fixed now.
