### ISSUE TITLE
ElementDeleterBase doesn't handle deleted remote elements

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#8471]
### Description of the enhancement or error report

When an element deleter is run on a distributed mesh, deletions of elements may be performed but not communicated to processors whose ghost elements have remote_elem links to the deleted element; this leaves the mesh in a parallel-inconsistent state where ghost elements fail to recognize new domain boundaries, internal assertions fail, etc.

This blocks #1500

### Rationale for the enhancement or information for reproducing the error

```METHOD=devel ./run_tests -p 2 --distributed-mesh --re 'mesh_modifiers/block_deleter.BlockDeleterTest5'```

(and many others, but this is the clearest and simplest failure case)

### Identified impact

I think I can fix this entirely internally to ElementDeleterBase, with no API changes.

**Comment by WilkAndy** [comment]
Thanks for identifying and hopefully fixing this @roystgnr

**Comment by roystgnr** [comment]
This was fixed and should have been closed by #8656
