### ISSUE TITLE
Extra variables cause navier-stokes module to fail

### ISSUE THREAD

**Issue by Chuban** [idaholab/moose#8475]
### Description of the enhancement or error report
Adding extra variables to a domain containing NS kernels causes MOOSE to throw an error.  This occurs when computing off diagonal jacobian terms for variables not created by the module (see [NSKernel::mapVarNumber](https://github.com/idaholab/moose/blob/devel/modules/navier_stokes/src/kernels/NSKernel.C)).  This can be corrected by checking that the variable belongs to the NS module before attempting the mapping.  Variables not belonging to the NS module should cause a 0 to be inserted into the jacobian.

### Rationale for the enhancement or information for reproducing the error
Fluid flow simulations should be able to operate with additional variables in the domain, i.e. species concentration.  This is important for simulations involving reactions in a flow.

### Identified impact
This will not affect current applications.

**Comment by andrsd** [comment]
Do you happen to have an input file that would show this problem?

**Comment by Chuban** [comment]
Here you go.  Everything runs fine if 'test' and its kernel are disabled.
[extra_var_test.txt](https://github.com/idaholab/moose/files/755411/extra_var_test.txt)

**Comment by jwpeterson** [comment]
Hm, yeah, that `NSKernel::mapVarNumber()` is just not general enough to be used when there are other variables in the system.  It should not error in the final `else` clause, but just return an invalid index like `libMesh::invalid_uint`...

**Comment by jwpeterson** [comment]
Aaand then the Kernels which use this mapping, like `NSEnergyThermalFlux::computeJacobianHelper_value()`, should be updated to return 0 when encountering an invalid id... sorry this is not designed very well at the moment.

**Comment by andrsd** [comment]
If we add something like `NSKernel::isNSVariable()`, we can fix the jacobian methods like so:
```
if (isNSVariable(jvar))
{
  // original body of the method
}
else
  return 0;
```

**Comment by andrsd** [comment]
There is actually more problems, since the mapping relies on:
1. NS variables are listed first in the input file
2. they are listed in a particular order (denisty, momentum, energy)

**Comment by Chuban** [comment]
@andrsd I actually have something very close to your suggestion working.  Did I miss a potential problem?  The `isNSVariable()` function simply makes a comparison to `_rho_var_number` etc. and returns a bool.

**Comment by andrsd** [comment]
My second comment is not actually true, I misread the code.

Yes, `isNSVariable` would compare to `_rho_var_number` et al. and return true on success,  false otherwise.

**Comment by Chuban** [comment]
Ok.  I should have a PR ready in a day or two.
