### ISSUE TITLE
failed test when running test suite with timings

### ISSUE THREAD

**Issue by jessecarterMOOSE** [idaholab/moose#8493]
### Description of the enhancement or error report
Running the test suite with timing flag (`--timing`) causes the following test to fail:
`outputs/console.print_perf_log_disable..........................FAILED (OUTPUT NOT ABSENT)`

Discussion:
https://groups.google.com/forum/?hl=en#!topic/moose-users/iePrGXo7Va4

### Rationale for the enhancement or information for reproducing the error

`./run_tests --timing`

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

less bugs

**Comment by milljm** [comment]
Thought this might be a TestHarness thing... seems it may not be.
