### ISSUE TITLE
Adding second level action syntax with * requires "place holder"

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#8495]
### Description
When adding syntax like: "BCs/Periodic/*", you must be add a placeholder:
```
syntax.registerActionSyntax("EmptyAction", "BCs/Periodic", "no_action");  // placeholder
```
This seems like we should handle this automatically.

### Rationale
When writing syntax it seems silly to require developers to register "EmptyActions"

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
The code will be better.

**Comment by permcody** [comment]
We generally don't need empty actions. They are only required when there's a potential collision in the namespace:
e.g. `BCs/Periodic` can be matched to both `BCs/*` and `BCs/Periodic`

I know there's already logic in there to prefer exact matches over wildcard matches but it seems like that wasn't enough for all cases. There may be a solution to this problem, but I just haven't needed it.

**Comment by permcody** [comment]
OK - thinking about this a bit more, I had it right in the explanation above. If you **don't** register the empty action (in this case `BCs/Periodic`) then when that section is encountered in the input file like the one below, it'll match the `BCs/Periodic` block against `BCs/*` which it definitely should. That block as you know is tied to the BoundaryCondition action so it'll complain that it can't find a boundary condition in that block. There's no way to know that you don't intend for this block to take on a special case (i.e. nothing) without telling the parser about that special case.

```
[BCs]
   [Periodic]
        [./x]
             ...
        [../]
   [../]
[]
```

**Comment by aeslaughter** [comment]
If you always need to do this when adding nested * blocks, why don't we just do it automatically.

```
registerActionSyntax("MyAction", "Kernels/Foo/Bar/*", "some_task);
```

would be the same as

```
registerActionSyntax("EmptyAction", "Kernels/Foo", "no_action");
registerActionSyntax("EmptyAction", "Kernels/Foo/Bar", "no_action");
registerActionSyntax("MyAction", "Kernels/Foo/Bar/*", "some_task);
```

The adding of the "Kernels" would be skipped because an action already existed.

**Comment by dschwen** [comment]
No. See the adaptivity block,

**Comment by permcody** [comment]
Daniel's correct. You only need it to differentiate when there's a name clash (i.e. you've registered a "*" operator at the same level in the same spot).
