### ISSUE TITLE
Stateful property linking results in cyclic dependency error

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#8496]
### Description of the enhancement or error report

A cyclic dependency error occurs when materials depend on old values of other material properties:

 *** ERROR ***
> Cyclic dependency detected in object ordering:
> one -> two
> two -> one

### Rationale for the enhancement or information for reproducing the error
The attached ```StatefulDependent``` material property replicates this error through the ```test.i``` input file. Two materials are created, each with old values. Each material pulls in the old value of the coupled material through ```getMaterialPropertyOld```, but does not use ```getMaterialProperty```.

[stateful_dependent.zip](https://github.com/idaholab/moose/files/759003/stateful_dependent.zip)

### Identified impact
This is needed due to some swelling/porosity material property creation separation during the switch from solid to tensor mechanics in BISON.

**Comment by rwcarlsen** [comment]
Material::getMaterialPropertyByName and Old/Older variants all have this line:

```c++
  _requested_props.insert(prop_name);
```

which is used with the dependency resolver for material objects.  The MaterialPropertyInterface::getMaterialPropertyByName function does not cause any such dependency to be registered.  The code that does this was last changed about ~1 year ago.  We could remove those lines from the Old/Older variants - it might be that simple, or it might not...

**Comment by permcody** [comment]
I'd have to dig through the history but this issue was first reported about
5 years ago and fixed by me. Apparently it has broken again which is my
fault since I clearly didn't provide a test case at the time. This should
be the right fix.
