### ISSUE TITLE
PorousFlow task: remove declarePropertyOld where possible

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8513]
MOOSE now automatically promotes Material Properties to Stateful Properties if their old values are needed.  Therefore in most cases we don't need the variable that is initialised with declarePropertyOld.  Sometimes we actually do need a variable to hold the old value, so we won't be able to get rid of them all.

**Comment by YaqiWang** [comment]
@WilkAndy you can use getPropertyOld to replace declarePropertyOld. I am not sure if the auto promotion (to stateful property) has been in place.

**Comment by WilkAndy** [comment]
Yea, it is!  I just checked the auto promotion and it works if you provide an initQpStatefulProperties function.

**Comment by YaqiWang** [comment]
Oh, I see. But be cautious on the difference of initial condition (`initQpStatefulProperties`) and initial evaluation (`computeQpProperties` on initial) of stateful properties. You typically do not want to have both. We had a big discussion about this.

**Comment by WilkAndy** [comment]
Can you point to an example of a problem/conflict?

**Comment by YaqiWang** [comment]
Not examples in hand, but if you comment out lines in https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblemBase.C#L642 and run tests, you will probably see bunch.

**Comment by WilkAndy** [comment]
Hmmm, i don't understand what the problem is, sorry.  Is there a discussion somewhere on github?

**Comment by permcody** [comment]
Tag @rwcarlsen to assist you

**Comment by rwcarlsen** [comment]
@WilkAndy - @YaqiWang is referring to the distinction between initialization and initial conditions.  Stateful property initialization just gives the current, old, older properties all the same value via initQpStatefulProperties.  For setting up actual initial conditions - we don't really have a clean official way to do that (yet).  For most cases, where initQpStatefulProperties was working okay for you, you should be fine just removeing ``declareProperty[Old/Older]`` except in cases where you actually need to use that value - which you should just switch to ``getMaterialProperty[Old/Older]``.  If you run into issues relating to initialization/initial-conditions, then the issues @YaqiWang is bringing up come in to play, but otherwise, you shouldn't need to worry about it (for now).

**Comment by WilkAndy** [comment]
OK, thanks.  Unfortunately i don't understand, but we can talk next week (cool!).  I don't know the difference between "initialization" and "initial conditions".

**Comment by permcody** [comment]
Yeah, let's save that for when you are here. It's a little confusing.

**Comment by WilkAndy** [comment]
at present initQpStateful properties sets Old and Older = current.

**Comment by WilkAndy** [comment]
I have been able to remove some declarePropertyOld lines.   However, some removals lead to tests failing.  @rwcarlsen , is the auto-promotion supposed to work in every case?

**Comment by WilkAndy** [comment]
@rwcarlsen , perhaps i'm wrong, but i think here's a situation where the auto-promotion doesn't seem to work:

Kernel requires Old property A.

To calculate Old Property A, a Material needs (in its initQpStatefulProperties) Old Property B from another Material.

The other Material, in its initQpStatefulProperties, calculates Old Property B by using a value from a Variable (that possibly comes from an IC).

Is this type of recursion allowed?

a

**Comment by rwcarlsen** [comment]
For dependency on old/older properties is not included in dependency resolution - this allows depending on an old/older property to break cyclical dependency loops.  So during initQpStatefulProperties, old/older dependencies are *not* included in determining the initialization order of different materials.  So it is generally *not* safe to depend on other materials' old/older properties during initQpStatefulProperties.

The promotion will work fine - it is jut the evaluation order that won't be safe.

**Comment by WilkAndy** [comment]
@rwcarlsen , then how does the dependency-on-old stuff work now?   All my tests work fine, with the type of multiple dependencies on Old Properties of other Materials that I currently have.  But as soon as i remove the declarePropertiesOld, and rely on the auto-promotion, it all fails.

**Comment by WilkAndy** [comment]
I think I need some rules that control when i should use declareOld.  Eg, if in initQpStateful, a Property's value depends on a Variable or another Property, then declareOld is needed.  But if in initQpStateful, a Property's value is set to be a constant, or a user-input value, then declareOld is not needed.

**Comment by rwcarlsen** [comment]
``declare[Old/Older]`` will be going away in the not too far future hopefully - so the solution is not to keep using them.  Using (not old/older) properties to calculate values in initQpStateful is okay - depending on external old/older properties in initQpStateful is undefined behavior.

What kind of errors are you seeing specifically? - and could you provide an input file that reproduces them?

**Comment by WilkAndy** [comment]
Yes, i can provide an input file, maybe in about 2.5 hours when i start work  (currently its early morning and i'm looking after kids).   The errors are improperly initialised values which result in MOOSE producing incorrect physical behaviour (eg, fluid density is zero instead of a positive quantity).  They're not seg-fault or other computer-code type of errors.

**Comment by WilkAndy** [comment]
An example is at:

https://github.com/WilkAndy/moose/tree/old_removal_problem_8513

I removed the declarePropertyOld from porous_flow/src//materials/PorousFlowDensityConstBulk.C .   Many of the tests fail, for example

tests/gravity/grav02d.i

**However** this test does not fail in a repeatable way (at least for me) suggesting that something is going strange with setting the old property correctly.   Eg, sometimes i just get NaN for the residual, sometimes the linear solver gives NaN after an iteration, sometimes the test runs OK, etc.

**Comment by rwcarlsen** [comment]
After investigating, it appears that this is due to the fact that during initQpStatefulProperties calls you are retrieving values of other material properties that have not yet been initialized - and are sometimes returning garbage (or crashing).  During initQpStatefulProperties, MOOSE is correctly tracking material property interdependencies.  However, if code in your initQpStatefulProperties depends on a *not* stateful property of another material that has *not* implemented initQpStatefulProperties, the quadrature point vector of that material property will not be resized properly - resulting in the wrong/erratic behavior.

**Comment by rwcarlsen** [comment]
The problem actually occurs only if you use a *not* stateful property of another material in initQpStatefulProperties for which no stateful properties are used to promote that other material to a stateful material - causing stateful property initialization to be skipped - and you have important initialization in initQpProperties that can't be skipped (you do here).  An immediate solution for you is to force-promote materials to stateful that have important initialization code in initQpProperties that needs to run (i.e. via a ``getMaterialPropertyOld<...>(...)`` call).

In MOOSE - we could change the code to always call initQpStatefulProperties - even if the material isn't stateful - but then we should probably just rename it initQpProperties.

**Comment by rwcarlsen** [comment]
like this:

```diff
diff --git a/modules/porous_flow/src/materials/PorousFlowDensityConstBulk.C b/modules/porous_flow/src/materials/PorousFlowDensityConstBulk.C
index f9c52c2..3abacf7 100644
--- a/modules/porous_flow/src/materials/PorousFlowDensityConstBulk.C
+++ b/modules/porous_flow/src/materials/PorousFlowDensityConstBulk.C
@@ -26,6 +26,7 @@ PorousFlowDensityConstBulk::PorousFlowDensityConstBulk(const InputParameters & p
     _ddensity_dp(_nodal_material ? declarePropertyDerivative<Real>("PorousFlow_fluid_phase_density_nodal" + _phase, _pressure_variable_name) : declarePropertyDerivative<Real>("PorousFlow_fluid_phase_density_qp" + _phase, _pressure_variable_name)),
     _ddensity_dt(_nodal_material ? declarePropertyDerivative<Real>("PorousFlow_fluid_phase_density_nodal" + _phase, _temperature_variable_name) : declarePropertyDerivative<Real>("PorousFlow_fluid_phase_density_qp" + _phase, _temperature_variable_name))
 {
+  getMaterialPropertyOld<Real>("PorousFlow_fluid_phase_density_nodal" + _phase);
 }
```

**Comment by WilkAndy** [comment]
Hmm, i think the Stateful Properties are quite confusing.  I don't really like your explicit call to "getMaterialPropertyOld" - it's hard for me to remember what to do.  At the least MOOSE should produce an error when things aren't initialised properly.  But at the best it'd be great if MOOSE just magically worked!

I totally agree with the name "Stateful" - it's becoming redundant.

**Comment by rwcarlsen** [comment]
I put a PR in that should fix your problem without the hack.

**Comment by WilkAndy** [comment]
Cool, thanks @rwcarlsen ,

a
