### ISSUE TITLE
add stream flush to output

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8515]
### Description of the enhancement or error report

From moose-users:

When i run in debug mode and get an input-file parser error, MOOSE returns an error message and a stack trace.  Previously it returned the error message immediately, and i could hit Ctrl-C before the stack trace appeared.  Why would i do this?  Because the stack trace takes at least a minute to generate on my computer, which is obviously super annoying when developing.  However, with the latest version of moose, the error message only appears at the same time as the stack trace (ie, a minute after MOOSE finds the error).  Bummer: now either i make no mistakes (hahaha) or i have to wait for ages to regain control of my terminal.  Of course i can "kill -9 PID" but that's annoying too.

### Rationale for the enhancement or information for reproducing the error

Faster process termination for a failed run. Assists in reducing development time. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Smiles

**Comment by WilkAndy** [comment]
Thanks for the flush @rwcarlsen 

a

**Comment by dschwen** [comment]
Courtesy flush
