### ISSUE TITLE
Stiffened gas EOS needs function for coefficient of thermal expansion

### ISSUE THREAD

**Issue by joshuahansel** [idaholab/moose#8516]
### Description of the enhancement or error report
Currently stiffened gas EOS uses a user-provided constant for the volumetric coefficient of thermal expansion (beta). There is a definition of this coefficient: 1/V dV/dT)_p, and the components to this definition are already available. Specification of this coefficient is an over-specification and ignores the coefficient's dependence on thermodynamic state.

### Identified impact
This eliminates the user-specified parameter `beta` from `StiffenedGasFluidProperties`. Applications using the function `beta(p,T)` for stiffened gas EOS will likely diff in their exodiff tests; however, this function in general is rarely used (it appears to only be used once in Relap-7 - in computing Grashov number for a wall heat transfer coefficient correlation).

**Comment by permcody** [comment]
I might seem unecessary, but please don't delete sections from the template. All three are required by our NQA-1 process. (PLN-4005 in EDMS).

**Comment by joshuahansel** [comment]
Template section re-added.
