### ISSUE TITLE
error console output wrongly includes "main" app name prefix now

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#8527]
fix coming.

### Description of the enhancement or error report

The new changes to the new error functions accidentally introduced an unnecessary prefix "main" to error output lines.

### Rationale for the enhancement or information for reproducing the error

Run any test or app input file that generates an error - you'll see "main" prefixing each error.

### Identified impact

simple error printing implementation update - no API.  Just fixing a regression in console output.

**Comment by permcody** [comment]
Please don't delete the template. The three sections are required by our change control process as part of NQA-1. If an auditor finds a ticket without those sections, it can be a finding even if the change is minor. We need to get better about filling them out.
