### ISSUE TITLE
Verification Tests for Tensor Mechanics

### ISSUE THREAD

**Issue by jasondhales** [idaholab/moose#8536]
### Description of the enhancement or error report
Add more and more rigorous verification tests for tensor_mechanics.

### Rationale for the enhancement or information for reproducing the error
Insure code quality and allow for demonstration to interested parties.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None.

**Comment by permcody** [comment]
Closed by #8539.
