### ISSUE TITLE
a typo in the XFEM test file

### ISSUE THREAD

**Issue by kothah** [idaholab/moose#8546]
typo in boundary condition box crack_propagation_2d.i

**Comment by permcody** [comment]
@kothah - Do you work for or with the lab? If so, it's a good habit to start filling out the template. It's required for our NQA-1 process. If not, then one of the developers has to fill it out which could delay merging of your PR. If you have any questions about our process, please fill to contact me.

**Comment by kothah** [comment]
I don't work with the lab. I am just a moose user, but if I make any new issues I will try to follow the guidelines. Thanks.

**Comment by jwpeterson** [comment]
@kothah do you mind if I add your real name to our .mailmap file?  We try to maintain a list of contributor's real names so that proper credit can be given.  Thanks.

**Comment by kothah** [comment]
Well, I don't think it was significant contribution to get mentioned in the contributors list.
But in any case, my name is Hardik Kothari.

**Comment by jwpeterson** [comment]
> But in any case, my name is Hardik Kothari.

Thanks!
