### ISSUE TITLE
Explore using DiscreteMaterial in my recent "PQ" plasticity models

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8561]
### Description of the enhancement or error report

Change ComputeCapped* and PQPlasticModel to be DiscreteMaterials instead of Materials

### Rationale for the enhancement or information for reproducing the error

The current plastic models work fine, but now i'd like to create another model that combines most of the functionality of two of these models.  I can't make this new model inherit from both existing models because of diamond inheritance.  Essentially i want to "computeQpStress" in both existing models and combine the result in my new plastic model.  It seems like DiscreteMaterials are perfect to use in this scenario.

Tagging @sapitts in case she sees something obviously wrong with this idea.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

None expected - this is just a "small" refactor of existing functionality.

**Comment by WilkAndy** [comment]
Hi @bwspenc and @sapitts ,

I'm just starting to explore this "compute=false" stuff.  It'll be a long process for me as this is rather low priority at the moment.  Here are some questions:

(1) If there are multiple plasticity models inheriting from StressUpdateBase, eg HyperbolicViscoplasticityStressUpdate and IsotropicPlasticityStressUpdate, and they are all used in an input file, then how does the declareMaterial("plastic_strain") work out?  Both of the aforementioned declare that Paroperty.

(2) Isn't _Jacobian_mult supposed to be rotated in ComputeReturnMappingStress::computeQpStress , just like the stress and strain?

(3) What about the plastic strains being rotated (the ones mentioned in (1), for instance).  I don't see that happening anywhere.

I bet i'll have lots more questions, but that will do for now!

a

**Comment by bwspenc** [comment]
@WilkAndy sorry for taking so long to get to this -- I was out for a couple of days and am still catching up.   Yes, I think you would need to prepend something to the name, and it looks like you did something like that.  We do something kind of like that all over the place in tensor_mechanics with a thing we call "base_name".  Maybe we can just re-use that parameter for this purpose, although it's used for something a little different (multi-phase materials).  I think you're right about needing to rotate _Jacobian_mult and plastic strains.
