### ISSUE TITLE
"moosedocs.py generate" modifies files

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8573]
### Description of the enhancement or error report

i don't know if this is intended, or whether i did something wrong, but "moosedocs.py generate ; git status" yields a whole lot of local modifications:

On branch devel
Your branch is ahead of 'origin/devel' by 8101 commits.
  (use "git push" to publish your local commits)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   media/ap1000_bison.png
	modified:   media/ap1000_rattlesnake_relap.png
	modified:   media/atom_autocomplete.gif
	modified:   media/atom_fuzzyfinder.png
	modified:   media/atom_screenshot.png
etc
etc

Then "git checkout -- ." doesn't remove the modifications, so i had to do "git reset --hard".

**Comment by aeslaughter** [comment]
This is a problem with `git lfs` that we are all seeing, we don't quite know what is happening and what approach we should take to prevent it.

**Comment by aeslaughter** [comment]
@brianmoose @permcody This might be something to look at: https://git-annex.branchable.com/

**Comment by permcody** [comment]
Closing as this isn't a MOOSE issue.

**Comment by WilkAndy** [comment]
OK thanks, at least it's not just me that's doing something wrong!

a
