### ISSUE TITLE
Bug in Actions and Materials

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8575]
### Description of the enhancement or error report

I'll need help from @rwcarlsen (or someone) with this, and I can show you on my computer on Monday.

**Background** I have an input file that has the following Material definition

```
  [./vol_strain]
    type = PorousFlowVolumetricStrain
    displacements = 'disp_x disp_y disp_z'
    PorousFlowDictator = dictator
  [../]
```

I have an Action that includes:
```
  if (_current_task == "add_material")
  {
    std::string material_type = "PorousFlowVolumetricStrain";
    InputParameters params = _factory.getValidParams(material_type);

    std::string material_name = "PorousFlowUnsaturatedHM_VolumetricStrain";
    params.set<UserObjectName>("PorousFlowDictator") = "dictator";
    params.set<std::vector<VariableName>>("displacements") = _coupled_displacements;
    _problem->addMaterial(material_type, material_name, params);
  }
```

The PorousFlowVolumetricStrain provides the Property PorousFlow_volumetric_strain_rate_qp (and some other things).

**Problem:**

1.  Running the input file with this Action included in the input file gives the error "The following material properties are declared on block 0 by multiple materials:"  and then some rather junky (buggy?) diagnostic summary involving PorousFlow_volumetric_strain_rate_qp.   This is _expected_, except for the screwed-up diagnostic summary, and suggests that the Action works as planned, since both it and the input file are adding the identical Material

2.  Running the input file and commenting out the [./vol_strain] block gives the error "Material property 'PorousFlow_volumetric_strain_rate_qp', requested by 'PorousFlowUnsaturatedHM_MassVolumetricExpansion' is not defined on block 0".   This is _unexpected_.  It contradicts (1), and suggests the Action is not working as planned.

3.  Running the input file without the Action yields no error.  This is _expected_ and suggests that the input file is working as planned.

**Comment by YaqiWang** [comment]
Did you get any warnings on the screen in case 2? You could have naming conflict in the Action.

**Comment by WilkAndy** [comment]
No, i didn't get any such messages, thanks Yaqi.  My names are quite obscure!

**Comment by WilkAndy** [comment]
I've pushed the problematic stuff to

https://github.com/WilkAndy/moose/tree/pf_action_8574

The Action is

https://github.com/WilkAndy/moose/blob/pf_action_8574/modules/porous_flow/src/actions/PorousFlowUnsaturatedHM.C

The test file is

https://github.com/WilkAndy/moose/blob/pf_action_8574/modules/porous_flow/tests/poro_elasticity/pp_generation_action.i

**Comment by permcody** [comment]
It sounds like this has been narrowed down to a requirement that the material block parameter needs to be set for the Action case. There's also some interplay with the GlobalParams block.
@WilkAndy can you record what you know about the problem here so we can take a look. If there's indeed a problem with needing to set the block that should be fixed and I can have @aeslaughter at that. If it's something else, then we'll keep looking.

**Comment by WilkAndy** [comment]
There is an interesting interaction between GlobalParams and addKernel and addMaterial.

I have an input file with just one block (block = 0).  I can have ```block = 0``` in the GlobalParams block of the input file, or I can omit this line.

I have an action that adds a Material and adds a Kernel that uses the MaterialProperty.  I can test the "Material property not defined" problem by including, or not including  ```params.set<std::vector<SubdomainName>>("block") = {};``` just before the relevant addMaterial or addKernel lines in the Action.

Results:

```block = 0``` included in input file, "set-block" in Material and Kernel.  MOOSE runs OK.
```block = 0``` included in input file, "set-block" in Material but not in Kernel.  Material property not defined.
```block = 0``` included in input file, "set-block" not in Material but is in Kernel.  MOOSE runs OK.
```block = 0``` included in input file, "set-block" not in Material and not in Kernel.  Material property not defined.

```block = 0``` not included in input file, "set-block" in Material and Kernel.  MOOSE runs OK.
```block = 0``` not included in input file, "set-block" in Material but not in Kernel.  MOOSE runs OK.
```block = 0``` not included in input file, "set-block" not in Material but is in Kernel.  MOOSE runs OK.
```block = 0``` not included in input file, "set-block" not in Material and not in Kernel.  MOOSE runs OK.

I think @andrsd can possibly provide more information.  The above results aren't perhaps exactly what we thought we saw yesterday, but i just tested all those 8 cases and the above results are OK.

**Comment by aeslaughter** [comment]
I will take a look at this.

**Comment by rwcarlsen** [comment]
@WilkAndy - if you get a chance can you confirm that #8587 fixes all the problems you were seeing?
