### ISSUE TITLE
Postprocessors and AuxVariables "outputs" bug(?)

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8597]
### Description of the enhancement or error report

I have an AuxVariable:

```
 [./porosity]
    order = CONSTANT
    family = MONOMIAL
  [../]
```

I also have a Postprocessor with the same name

```
  [./porosity]
    type = PointValue
    outputs = 'csv'
    point = '0 0 0'
    variable = porosity
  [../]
```

The "outputs" limiter in the Postprocessor means that the AuxVariable doesn't get added to other output streams (eg, an exodus file).

I'm not sure if this is intended or not.  Please just close this issue if it's not a bug.

**Comment by permcody** [comment]
This seems unintuitive. @aeslaughter perhaps we need to look at the fully qualified names?

**Comment by aeslaughter** [comment]
I will need to come up with a solution for this, I recently hit this as well. There is a naming collision that just silently does something. Changing the name of the postprocessor should be a temporary fix.

**Comment by WilkAndy** [comment]
Heheheh, @aeslaughter , let's not leave this for another year, heheheh!
