### ISSUE TITLE
PorousFlow task: mentioned convergence criteria in theory manual

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8598]
### Description of the enhancement or error report

Add a section on nonlinear convergence criteria and scaling of variables

### Rationale for the enhancement or information for reproducing the error

For users

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
@WilkAndy - you mentioned that you do want to follow the NQA-1 process to me. These three bullets come straight out of the requirements specification. If you were to be audited under that process this ticket wouldn't pass. I haven't been enforcing it for you but just wanted you to be aware of where these sections come from.

**Comment by WilkAndy** [comment]
Aha, i get it, thanks @permcody,

a
