### ISSUE TITLE
Fixup Bad Test Specs

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8604]
### Description of the enhancement or error report

The repository contains several bad test specifications where tests either compete or could potentially compete for the same output files.

### Rationale for the enhancement or information for reproducing the error

This causes really difficult to find corruption issues due to race conditions.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Testing robustness

**Comment by permcody** [comment]
@WilkAndy: https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/tests/drucker_prager/tests#L74-L90

**Comment by permcody** [comment]
@WilkAndy:
https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/tests/mohr_coulomb/tests#L75-L91

Does this actually work properly if we were to run these tests concurrently? Does the CSV output remain the same when you change the mesh? Just curious. Perhaps you should make the heavy test have a prereq of the regular test if this is the case. There may be others besides these too - still sifting through the results:
https://www.moosebuild.org/job/70230/

**Comment by WilkAndy** [comment]
Yes, the CSV output remains the same in this case.  What about race conditions of writing/reading to the csv ?  I'm not sure if the heavy can have a pre-req, as the "light" will never be run when using "--heavy", correct?

**Comment by permcody** [comment]
Don't make any changes just yet. I need to think about this some more.

If we always run regular tests with heavy then we could make the heavy test
depend on the regular test.

**Comment by permcody** [comment]
The TestHarness can now detect these. See #8594

**Comment by permcody** [comment]
The TestHarness errors out if competing output files are detected based on the test specification. However, it's virtually impossible for me to completely prevent all nasty cases without full knowledge of all output files being written by a potentially unknown executable. Consider this case:

Test A (Exodiff) writes both "exodus" and "csv"
Test B (CSVdiff) writes both "exodus" and "csv"

As far as the TestHarness is concerned, this is fine. We only need to look at the Exodiff part of the test in A and the CSV part of the test in B. However, they both still have the potential to corrupt the other since they are writing multiple files that the TestHarness can't possibly know about. To avoid this, just don't write files you don't plan to read. :)

Closing as solved!
