### ISSUE TITLE
Accessor in FEProblem for MultiAppTransfers

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#8608]
### Description of the enhancement or error report
Accessor in `FEProblem` into `_to_multi_app_transfers` and `_from_multi_app_transfers`.
Is there any reason to not make these available? 

### Rationale for the enhancement or information for reproducing the error
You can get the MultiApps through `getMultiApp` but not the transfers.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
none except that you can now get `MultiAppTransfers`

**Comment by permcody** [comment]
I don't see any problem with this. What do you plan to use it for?

**Comment by snschune** [comment]
Originally for having a preconditioner that gets its action from a multiapp => `MultiAppPreconditioner`. I was getting the multiapp I wanted through `getMultiApp` but then
I also needed all transfers associated with the MultiApp. 

Because of other issues with this, @YaqiWang suggested to have a particular `MultiApp` that provides an `apply(x, y)` function. This turns out to be much less hassle.

**Comment by friedmud** [comment]
Seems ok to me.

**Comment by snschune** [comment]
This is currently not used anywhere so it reduces test coverage. Should I add a test?

**Comment by permcody** [comment]
I'm always going to say yes to that. Otherwise, we could change, edit or
delete your new addition at any time.

**Comment by rwcarlsen** [comment]
So is the transfers getter still wanted or are you going the alternate ``apply(...)`` route @snschune ?

**Comment by snschune** [comment]
I'll leave the getter and will just add a test. I have already implemented a `MultiAppPreconditioner` but it currently resides in Rattlesnake. I'll let you peek at the code probably next week and you can see if that is something of general interest.
