### ISSUE TITLE
Clean up usage of stateful properties in tensor_mechanics

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#8616]
### Description of the enhancement or error report
There are multiple instances where we need to clean up our usage of stateful materials in tensor_mechanics:

- The eigenstrain models currently have a parameter: `inremental_form`, which was originally used to control whether the eigenstrain tensor was declared stateful. With the recent re-working of how materials are made stateful, this is no longer necessary.
- The deformation gradient is made stateful for use with volumetric eigenstrain models.  These models can be reformulated to not need this.
- The elasticity tensor is made stateful (ouch!) when it can change over time.  We can re-work the formulation to make the elastic strain tensor stateful instead, which will have multiple benefits.

### Rationale for the enhancement or information for reproducing the error
This will simplify input and the code for these models and reduce the memory footprint.

### Identified impact
Changes to materials in tensor_mechanics.

**Comment by permcody** [comment]
@bwspenc - I see many merged PRs on this ticket, is it complete?

**Comment by bwspenc** [comment]
Almost, but not quite -- we still need to completely get rid of the `incremental_form` option.

**Comment by bwspenc** [comment]
Reopening to remove the incremental_form parameter, which has been deprecated for a long time.

**Comment by bwspenc** [comment]
Aargh!!! The deprecated incremental_form parameter found its way into `ADComputeEigenstrainBase`.  Reopening this issue to remove it from that class.
