### ISSUE TITLE
Add "SimpleFluid" to fluid_properties module

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8618]
### Description of the enhancement or error report

The "SimpleFluid" will have: constant bulk density; constant viscosity; and constant specific heat capacity. 

### Rationale for the enhancement or information for reproducing the error

In PorousFlow simulations it is useful to use such a SimpleFluid in situations where more complicated equations of state are not needed.  This is in many situations where water is the only fluid, where pressure and temperature do not vary very much.  It is also in all situations where standard  poromechanics is deemed to be relevant.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

PorousFlow will be enhanced.  At the moment PorousFlow allows users to use the equivalent of this SimpleFluid, but many Materials are needed (some to define density, some viscosity, etc).  It will simplify the input file of these types of simulations.  It will also allow users to easily switch between these simple fluid properties and the more realistic fluid properties already in the FluidProperties module.

**Comment by WilkAndy** [comment]
Tagging @andrsd , in case he wants to comment

**Comment by andrsd** [comment]
Sounds good @WilkAndy. Go for it...
