### ISSUE TITLE
Units in PorousFlow and FluidProperties

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8620]
@cpgr and @andrsd , could you please comment, and close the issue if it's not a bug, or hopefully fix it if it's a bug.

### Description of the enhancement or error report

SinglePhaseFluidPropertiesPT appears to measure internal energy (e) in kJ/kg, and specific enthalpy in kJ/kg.  Note the KILO-Joules.

PorousFlowSingleComponentFluid just pulls these in directly and assigns them to the MaterialProperties.

However, PorousFlow itself usually assumes that internal energy is in J/kg, see, eg, PorousFlowMatrixInternalEnergy (specific_heat_capacity is in J/kg/K).  Also all the documentation is in J, rather than kJ.

Users are free to choose whatever unit system they want in most parameters, but we should keep our internal things consistent.

Am I correct?  Should be change PorousFlowSingleComponentFluid by multiplying the relevant things by 1000?

### Rationale for the enhancement or information for reproducing the error

As above.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Users who are used to erroneous (?) behaviour may be suprised when/if we fix this "bug".

**Comment by andrsd** [comment]
I agree that all kJ/kg/K should be switched to J/kg/K. It is what the `SinglePhaseFluidProperties` (without PT) assumes, so we would be consistent.  I can see that the child classes are dividing by 1e3 to get kJ, so the fix might be simple. Let's see what @cpgr has to say, he might have some code that depends on kJ...

**Comment by cpgr** [comment]
We should make sure it is consistent. I haven't really needed any of the energies so was probably a bit lax about checking this. It should be a trivial fix as David notes.

**Comment by WilkAndy** [comment]
OK, would you like me to do this change to FluidProperties?   If so, i'll do it in combination with #8618 so that i don't get conflicts and because it'll be a convenient thing to do while i'm on a plane.

a

**Comment by cpgr** [comment]
Thanks Andy

**Comment by andrsd** [comment]
Works for me...
