### ISSUE TITLE
getPostprocessorValueOld 

### ISSUE THREAD

**Issue by zahom** [idaholab/moose#8630]
### Description of the enhancement or error report
Using 'getPostprocessorValueOld' gives the value of a variable for the current timestep and not the old timestep. 

### Rationale for the enhancement or information for reproducing the error
Please see the attached demo problem
[pstprocold.zip](https://github.com/idaholab/moose/files/800716/pstprocold.zip)
:

### Identified impact

**Comment by andrsd** [comment]
If you are expecting to see the current value of that postprocessor, you have to fix your input file like so:
```
  [./str_yy]
    type = ElementalVariableValue
    elementid = '31'
    variable = stress_yy
    execute_on = linear
  [../]
```

By default, PPSs are executed on `timestep_end`, which led you believe there is a bug in the code. But the code was not computing the PPS value when the residual was being formed, becuase you did not tell it to do so.

Therefore, I am closing this. If you still think there is a problem in the code, reopen this ticket.

**Comment by permcody** [comment]
David, he says he's getting the current value when he expects the old one.
I think you may have read this backwards

**Comment by zahom** [comment]
Thanks for the response. However, I want access to both current and old values.

**Comment by andrsd** [comment]
The current value is the one that is computed from the current solution vector, i.e. the PPS has to be executed on linear.  Make the suggested change and run your code. Then you will see that the old and current values are different in your output. So, yes, you have access to both, the current one and the old one...

**Comment by zahom** [comment]
So, I already have these lines in the ".C" file:
std::cout << "old_val = " << _str_yy_old << std::endl;
std::cout << "cur_val = " << _str_yy << std::endl;

I still get the same values for current and the old.

**Comment by andrsd** [comment]
One more thing I noticed, your `stress_yy` auxkernel is executed on timestep_end. That will cause a lag in the values. Remove that and you will be getting the right values...

**Comment by andrsd** [comment]
And BTW I am running your code (with no modifications) on my machine and I _do_ see different values. But, you need to get those `execute_on` flags right.

**Comment by zahom** [comment]
So, I put 'execute_on = linear' for both the PPS and the Aux Kernel. But, I still see the same values.

**Comment by andrsd** [comment]
So if I redirect the output to a file, I get the wrong behavior. If I let it to print to terminal, the values _are_ different. 

The code and input files are on [andrsd:issue/8630](https://github.com/andrsd/moose/tree/issue/8630)

**Comment by andrsd** [comment]
Nope, my mistake. I was looking just at the beginning of the output. They are the same at the beginning of the time step. That makes sense, because the current solution is not mush different when we start converging. But, at the end of the time step, they are certainly different.

**Comment by zahom** [comment]
Thanks! Works fine now.
