### ISSUE TITLE
Problem with output of L2_Lagrange variables to exodus files

### ISSUE THREAD

**Issue by vincentlaboure** [idaholab/moose#8635]
### Description of the enhancement or error report

It seems that the output of L2_LAGRANGE variables to exodus files does not behave as expected (after talking to @jwpeterson and @YaqiWang ). A similar problem appears for MONOMIALS with order higher than CONSTANT. 

Exodus files only support the output of elemental or nodal variables. In the case of discontinuous variables, the expected output is thus a constant value in each cell (like what is obtained with CONSTANT MONOMIAL).

### Rationale for the enhancement or information for reproducing the error

The attached input file (extension changed from .i to .txt to have github upload the file) reproduces the problem: the CONSTANT MONOMIAL, FIRST L2_LAGRANGE and FIRST MONOMIAL auxvariables should have the same output. Only the first one seems to behave as expected.

[dfem_test.txt](https://github.com/idaholab/moose/files/804214/dfem_test.txt)

### Identified impact

The output of discontinuous variables can present unphysical oscillations that aren't in the solution if they are plotted as nodal variables rather than elemental variables.

**Comment by andrsd** [comment]
Well, exodus by definition can store just a single value per cell. You cannot store a higher order solution there. And I am afraid even the visualizers (like paraview) cannot do higher order solutions (at least I do not know about any). Also, storing the solution into an exodus file is a libMesh things, MOOSE does not have this under control. So this is not really a MOOSE issue per say.

However, there are 2 ways we deal with these issues in MOOSE:

1. Project the discontinuous solution into continuous space with LAGRANGE variables. The input parameter name is `elemental_as_nodal` and it would go into the block with exodus output.

2. Oversampling the output. This was originally made for plotting CUBIC HERMITES, where the higher order solution is sampled into the LINEAR LAGRANGE space. I guess, this could work for elemental variables as well, where we would sample the higher order solution so you would end up with piecewise constant, but finer resolution solution.

Did you try (1) or (2) or both? Results?

**Comment by vincentlaboure** [comment]
Yes, I agree that storing and plotting high order discontinuous variables is not something easily supported and the idea behind this issue is certainly not to request it.

After discussing with @jwpeterson, my understanding is that the desired behavior is to have all discontinuous variables be output by default as CONSTANT MONOMIAL (if ```elemental_as_nodal``` is not set to true) to avoid adding features that may not exist in the solution.

That being said, you made me realize that this issue is more a libMesh issue than a MOOSE one.

**Comment by permcody** [comment]
Moved to https://github.com/libMesh/libmesh/issues/1420
