### ISSUE TITLE
Bad interaction between volumetric locking and XFEM

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#8636]
### Description of the enhancement or error report
We are getting very wrong results for fracture domain integrals with XFEM when `volumetric_locking_correction=true`.

### Rationale for the enhancement or information for reproducing the error
Simple 2D fracture problems give very erratic results for J Integrals, including with the wrong sign.  The problems go away if you set `volumetric_locking_correction=true`.  I have tracked this down to the fact that the volumetric locking code in the kernel uses `_current_element->volume()`, when it should be using `_current_element_volume`.  The latter has the xfem weights taken into account.

### Identified impact
Change the use of `_current_element->volume()` to `_current_element_volume` in the stress divergence kernels in solid_mechanics and tensor_mechanics.

**Comment by rwcarlsen** [comment]
Assigning @bwspenc for now.  Do you have a failing test case?

**Comment by bwspenc** [comment]
@rwcarlsen , yes, I'm working on this.  I have test cases -- all of the XFEM/mechanics test cases have issues and were incorrectly re-golded with the errors a while back.
