### ISSUE TITLE
perf_log prints twice when the ./run_tests -t option is used

### ISSUE THREAD

**Issue by gardnerru** [idaholab/moose#8638]
I noticed this while looking at the nightly testing that we do, but found it was repeatable without pbs and with a moose test. Doubt it impacts anything but decided to report anyway. Below is the results of my testing of this:

Note: I "skipped" all but one of the tests in the thermo_mech dir to make looking at the log file easier. 

test1 
Ran: ./run_tests -f test1 --re=thermo_mech with print_perf_log=false in [outputs]
Results: no perf_log in file

Test2
Ran: ./run_tests -f test2 --re=thermo_mech with print_perf_log=true in [outputs]
Results: 1 perf_log in the log file

Test3
Ran: ./run_tests -f test3 --re=thermo_mech -t with perf_log=false in [outputs]
Results: perf_log is printed twice in the log file

Test4
Ran: ./run_tests -f test4 --re=thermo_mech -t with perf_log=true in [outputs]
Results: perf_log is printed twice in the log file

Included are the log files.

[Archive.zip](https://github.com/idaholab/moose/files/807320/Archive.zip)

**Comment by permcody** [comment]
Thanks
