### ISSUE TITLE
convert tests in combined module to use tensor mechanics

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#8642]
### Description of the enhancement or error report
To convert tests in the combined directory to use tensor mechanics

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No identified impact

**Comment by permcody** [comment]
Please don't delete parts of the template. They are required sections for NQA-1 compliance.

**Comment by permcody** [comment]
Issue closed by referenced PRs
