### ISSUE TITLE
DependencyResolver<shared_ptr> does not sort reliably.

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#8659]
### Description of the enhancement or error report

When calling DependencyResolver<T>::getSortedValues() we expect to get a vector which is consistently sorted across processors.  If we do not, then e.g. in MooseApp::executeMeshModifiers() we will end up executing MeshModifiers in different orders on different processors, which is a disaster for any mesh modifier code that does parallel communication.

getSortedValues() does two levels of sorting: an outer level based on dependencies (which works reliably) and an inner level based on the ordering within _ordered_items[i].  For std::shared_ptr items, this ordering is based on memory allocation, which is surprisingly consistent across processors but which occasionally breaks horribly.

### Rationale for the enhancement or information for reproducing the error

Running BlockDeleterTest11 (which has lots of MeshModifiers) with --distributed-mesh (which makes half of those MeshModifiers require parallel communication) on many processors (to maximize the chance that one of them sorts out of the intended order and the likelihood that a mis-synced deleter will be querying about an element which was already deleted by a different deleter) in debug or devel mode (to cause those queries to fail assertions) usually (but not deterministically!) replicates the problem.

### Identified impact

The only direct use of DependencyResolver is for mesh modifiers, but DependencyResolverInterface uses std::stable_sort with a DependencyResolver as comparator and so should have the same bug.

That makes this a *very* intrusive issue, which is why I'm making a new issue rather than rolling out a fix under the #1500 banner.

I'd *like* to do the internal sort by name.  I'll try that shortly and see whether the compiler screams.

Using T::name() essentially requires assuming that every single DependencyResolver use is with a MooseObject subclass, and I can't tell that for certain; DependencyResolverInterface gets brought in *everywhere* via multiple inheritance, and trying to examine the results of "grep sort" in its subclasses is slow work.

Even if this compiles, I can imagine it changing regression test results, as it may change the result of sorts:  If you added object "ObjectTwo" and "ObjectThree" in that order, then previously the sort would (probably! not definitely!) put ObjectTwo first because it ends up at a lower memory address, and in the future the sort would always return ObjectThree first because of alphabetical order.

**Comment by roystgnr** [comment]
No, it won't possibly compile.  Right in Syntax.h is a DependencyResolver<std::string>, and you can't dereference a string and call a name method on it.

**Comment by roystgnr** [comment]
I suppose I can use a helper template object with partial specializations for std::string and std::shared_ptr...  less hackish suggestions would be appreciated though.

**Comment by permcody** [comment]
Oh my, I'm afraid this is my doing but sorting on pointers wasn't my intention.

I don't recall why I'm sorting the inner vector at all. It's probably just my naive choice of using `std::set` as the inner container. It might be easier to rework the DependencyResolver so that the inner holder is a `std::list` or some other unordered container which we don't have to worry about getting shuffled. This change could have bad asymptotic behavior for the algortihm itself but should be fine in practice. We could get fancy and use an indirect sort (also a utility in MOOSE) if we wanted to bring down the runtime bounds. This shouldn't require any changes to the external interface!

**Comment by permcody** [comment]
~~This shouldn't require any changes to the external interface!~~
The changes to the external interface will be minor. We are probably only using the version that exposes the inner set in one or two places if that.

**Comment by permcody** [comment]
Templating on pointer types isn't a terrible idea though. Would you assume you could get to `::name()` inside though for sorting? I haven't specialized a template for all pointer types in C++11 yet. I hope that's possible with type traits. That might be a fun exercise

**Comment by roystgnr** [comment]
What I ended up doing is specializing only on std::string and on std::shared_ptr (where I assumed the pointer target has a name() method), those being the only types in use in the library.  We'll see shortly whether any of the external apps have other use cases.

Switching to std::list might be a better idea in the long run, that's debateable, but just adding a comparator was easier for now.
