### ISSUE TITLE
Add stochastic distribution base class

### ISSUE THREAD

**Issue by wangcj05** [idaholab/moose#8660]
### Description of the enhancement or error report
Create base class for stochastic distributions

### Rationale for the enhancement or information for reproducing the error
This will be used for both MOOSE framework and Stochastic tools under MOOSE. Enable the users and developers to add their own custom distributions, and this is the first step to add the stochastic tools for MOOSE.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This will be an independent module, currently have no impact on others.

**Comment by permcody** [comment]
Closed by #8690
