### ISSUE TITLE
Add DGBC

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#869]
Yeah.  Really.

What we want is a DGKernel that is only run on a specified boundary_id.  That boundary_id will be an "internal sideset".  This will be useful for specifying boundary conditions between two blocks that are running different physics with different variables, but where the boundary conditions between the two blocks need to have access to eachother's values on either side of the block

**Comment by friedmud** [comment]
Just bumping this a bit since people are asking for it: https://groups.google.com/forum/#!topic/moose-users/iALxx76WhnU

**Comment by lindsayad** [comment]
Any progress on this issue? If not, I'm going to attempt to implement this. If successful (a pretty significant if), I can submit a PR

**Comment by permcody** [comment]
Nobody has had time to work on this. Please feel free to implement it, if
you have questions or need guidance, let us know.

**Comment by lindsayad** [comment]
If I have questions, should I post here, in moose-users, or elsewhere?

I'm curious whether there's a good reason for setting _boundary_id as a private parameter in DGKernel.C? I don't have much of a plan yet, but that seems like it might be a decent parameter for indicating whether you want a child of DGKernel restricted to a boundary (meaning an interfacial or global boundary as opposed to a boundary between elements with same materials/physics)

**Comment by permcody** [comment]
I'm not an expert on that class but I believe it's not an ID per se. It's more of a type in that context. It's used to indicate that we are on an internal boundary vs any actual boundary.

**Comment by lindsayad** [comment]
As far as I can tell for my purpose, the biggest conceptual difference 
between ComputeResidualThread::onBoundary and 
ComputeResidualThread::onInternalSide is that onBoundary takes an 
additional argument, bnd_id, that is used (among other things) to 
determine what IntegratedBCs are active on that bnd_id, e.g.:

   _sys.getBCWarehouse(_tid).activeIntegrated(bnd_id, bcs);

However, with onInternalSide, there is (currently) no way to pass an 
identifier that might be useful in saying where DGKernels are applied. 
Thus, any active DGKernels are applied on *all *internal sides.

Please let me know whether my summary is correct or not.
