### ISSUE TITLE
"test_subs" in modules makes reviewing results difficult

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8693]
### Description of the enhancement or error report

We use a `make` target in the modules directory to run tests. The reason we do this rather than run the combined module is to prevent people from putting tests under a module which include files from an unrelated, or module that we don't depend on in in that test folder. The problem is that it makes reviewing failed tests in modules a difficult task because there are _n_ summaries, one for each module.

I propose that we modify the run_tests scripts in `moose/modules` so that we can optionally run separate executables for each module. What that means is that we'll need a new target in the modules Makefile to build separate executables in each folder without running them combined with a new option in the TestHarness to pick up several different executables as it traverses the modules.  

### Rationale for the enhancement or information for reproducing the error

`make test_subs` in modules

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact, better output for code reviews

**Comment by permcody** [comment]
@milljm - Let's think about a way we can make the test harness run a separate executable as it walks the tree if we pass yet another option to the run_tests script. We can make assumptions to make this easier such as, only look for executables in the first level directory (e.g. `modules/phase_field`, but not `modules/phase_field/tests`). 

Also, for now assume that the executables are pre-built. We don't want the TestHarness running make commands. The run_tests script can, but not the TestHarness. 

@brianmoose may have some suggestions

**Comment by permcody** [comment]
Tag @milljm - I think this ticket is worth looking at too.

**Comment by milljm** [comment]
@permcody 
I am thinking that the TestHarness's buildAndRun method might accept a list of apps. Might be easier to implement than we think.

```python
    def buildAndRun(argv, app_name, moose_dir):
        if '--store-timing' in argv:
            harness = TestTimer(argv, app_name, moose_dir)
        else:
            harness = TestHarness(argv, app_name, moose_dir)

        harness.findAndRunTests()

        sys.exit(harness.error_code)
```

**Comment by milljm** [comment]
okay, this is a larger change than I initially thought it would be. The TestHarness initializes with a single executable, which is followed by the finding and running of tests from that executable's location, and then we exit.

I think findAndRunTests will need to be iterable. While we handle the runner joins and cleanup methods elsewhere. This is so we can keep the "final results table" tallying up everyones tests.

**Comment by permcody** [comment]
I'm afraid that this has gotten even worse since #7347 due to the addition of the new test directory. I'd really like to see a better solution to this problem. 

Tag @brianmoose or @milljm.

**Comment by brianmoose** [comment]
We could just add an option to the TestHarness to output the results in a parseable format (like JSON). Then `make test_subs` would just do what it does now but add the output flag. Then a separate script could read all of them in and print them in a pretty way. Not sure about text coloring though...

**Comment by permcody** [comment]
That's a solution.

**Comment by permcody** [comment]
I really hate the test subs output... Just my periodic complaining 😄 

Brian's idea isn't bad, but I also don't think it would be too terrible to handle multiple executables...
