### ISSUE TITLE
Remove CInterfacePosition

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8698]
### Description of the enhancement or error report
`CInterfacePosition` is an old postprocessor to determine an interface position. It inspects nodal values and returns a component of the node position that is closest to the chosen value.
We have `FindValueOnLine` which is a better way to find an interface position (with sub grid resolution)

### Rationale for the enhancement or information for reproducing the error
Confusing to have two objects for the same task, especially if one is a better suited.

### Identified impact
We'll deprecate and see...

Ping @tonkmr, are you emotionally attached to this? ;-)

**Comment by permcody** [comment]
I see this PP in the misc module. It's not deprecated. Is this the object you are referring to in this ticket or was there another that has already been removed?

**Comment by dschwen** [comment]
Yeah the pp in the misc module should be deprecated

**Comment by permcody** [comment]
Looks like I can skip deprecation. I can't locate any applications that are currently using this object. It's also not tested.
