### ISSUE TITLE
Create a function that can sample a field variable

### ISSUE THREAD

**Issue by novasr** [idaholab/moose#8713]
### Description of the enhancement or error report
This function linearly interpolates (in space) the data generated by a vector postprocessor. The purpose is to have a function take a field variable (aux or primary) as an argument.

### Rationale for the enhancement or information for reproducing the error
User requested using a field variable from another code as a source term. This field data will be in the form an aux variable.

### Identified impact
This function will eventually be used as input for the Bison class called BurnupFunction.

**Comment by dschwen** [comment]
Is the _other code_ a non-MOOSE code? I'm not sure a VPP is the best approach here. How is the other code coupled to Bison?

**Comment by andrsd** [comment]
@novasr You will need to put the template for the issue back, it is required by our SQA procedures...

**Comment by novasr** [comment]
@dschwen, take a look at the branch. I'll wait for your input before PR.

**Comment by novasr** [comment]
So... is this a non-starter? If so, I'll close this issue. @jasondhales what are your thoughts?

**Comment by jasondhales** [comment]
@novasr, did you put any code out for review?  Where is the branch you mentioned?

**Comment by dschwen** [comment]
You can see the changes [here](https://github.com/novasr/moose/pull/new/function_of_variable8713) @jasondhales.

**Comment by dschwen** [comment]
I wouldn't call this a non-starter at all. Looking at the code I think this is useful. If you hadn't sold this to me as "Function of a Variable" I would not have had such a sceptical initial reaction :-).
Functions of VPPs sound useful and flexible. You might want to think about allowing to specify a custom column pair for the VPP, and maybe implementing the derivative method of the function.

**Comment by jasondhales** [comment]
I like the idea of the user supplying the x and y variable names from the VPP.  What would the input look like?  How about `x_variable` and `y_variable` instead of just `variable`?

**Comment by dschwen** [comment]
I'd go with `x_column` and `y_column` as those are not really variables.

**Comment by novasr** [comment]
Thanks for input @dschwen and @jasondhales . I've just pushed an updated branch and I will open a PR.
