### ISSUE TITLE
Refactor headers to reduce dependencies

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#8730]
While working on #8674 I was frequently stymied by the amount of recompilation that a change to DependencyResolver.h would trigger, and I refactored several headers to replace header inclusions with forward declarations or base class header inclusions.

I didn't want to include that commit with #8674, because it was logically completely independent and because it could have generated false positive test failures, but generally reducing compilation time is a good thing, so I'm planning to put some header refactoring in a separate PR.

We should probably keep this issue open indefinitely for later such PRs, since redundant header dependencies are an ongoing problem which is nearly impossible to automatically test for.

### Rationale for the enhancement or information for reproducing the error

To reproduce:
1. Primal reproduction: Change a small header, run "make", and watch how many source file end up being rebuilt.

2. Dual reproduction: Examine the dependencies in AnyFile.lo.d and see how many include files end up being scarfed to rebuild a single source file.

### Identified impact

Although this kind of refactoring changes no official APIs, it's very easy to break downstream apps which do not directly include all the header files they should but instead implicitly rely on indirect header inclusion.  Fortunately such breakage is also very easy to fix.

**Comment by permcody** [comment]
👍 , I think a lot of people who write application code aren't very good at keeping down unecessary header includes because they either don't want to understand or fail to understand how this works. We've cleaned them out before. This is a good maintenance task.

**Comment by permcody** [comment]
Closed by referenced commits. This is an ongoing maintenance task but there's no need to leave this ticket open. Feel free to reference the closed ticket if you have more refactoring to perform in the future.

**Comment by roystgnr** [comment]
Going to have to make a couple changes along these lines soon; there are a few unnecessary libMesh header into-other-libMesh header inclusions that I want to remove, and doing so will require some MOOSE fixes first.

**Comment by roystgnr** [comment]
Reopening this one again; another libMesh refactoring is going to remove another unnecessary inclusion, and I've found at least one MOOSE file will need an explicit inclusion added to work around that.
