### ISSUE TITLE
Silence Option for Transfer Output to the Log 

### ISSUE THREAD

**Issue by elementx54** [idaholab/moose#8735]
### Description of the enhancement
Create a method to allow the user to silence transfer log messages and/or make them only available with debugging enabled.

### Rationale for the enhancement
Transfer functions create multiple lines of output in the log. This is wonderful for debugging purposes but for optimizing runs it bloats the log file and makes it difficult to see the output which might be helpful in seeing how the simulation is running. Giving the user flexibility in turning on or off the transfer messages increases the usability of the MOOSE Framework.

_Example:_
```
17 Linear |R| = 3.525662e-03
 
Starting Transfers on LINEAR To MultiApps
Beginning VariableValueSamplePostprocessorTransfer full_power_density
Finished VariableValueSamplePostprocessorTransfer full_power_density
Jobs complete: 1/48^MJobs complete: 2/48^MJobs complete: 3/48^MJobs
complete: 4/48^MJobs complete: 5/48^MJobs complete: 6/48^MJobs complete:
7/48^MJobs complete: 8/48^MJobs complete: 9/48^MJobs complete: 10/48^MJobs
complete: 11/48^MJobs complete: 12/48^MJobs complete: 13
/48^MJobs complete: 14/48^MJobs complete: 15/48^MJobs complete: 16/48^MJobs
complete: 17/48^MJobs complete: 18/48^MJobs complete: 19/48^MJobs complete:
20/48^MJobs complete: 21/48^MJobs complete: 22/48^MJobs complete:
23/48^MJobs complete: 24/48^MJobs complete: 25/48^MJob
s complete: 26/48^MJobs complete: 27/48^MJobs complete: 28/48^MJobs
complete: 29/48^MJobs complete: 30/48^MJobs complete: 31/48^MJobs complete:
32/48^MJobs complete: 33/48^MJobs complete: 34/48^MJobs complete:
35/48^MJobs complete: 36/48^MJobs complete: 37/48^MJobs comple
te: 38/48^MJobs complete: 39/48^MJobs complete: 40/48^MJobs complete:
41/48^MJobs complete: 42/48^MJobs complete: 43/48^MJobs complete:
44/48^MJobs complete: 45/48^MJobs complete: 46/48^MJobs complete:
47/48^MJobs complete: 48/48
Waiting For Transfers To Finish
Transfers on LINEAR Are Finished
 
 
Executing MultiApps on LINEAR
Solving MultiApp micro
Successfully Solved MultiApp micro.
Jobs complete: 1/48^MJobs complete: 2/48^MJobs complete: 3/48^MJobs
complete: 4/48^MJobs complete: 5/48^MJobs complete: 6/48^MJobs complete:
7/48^MJobs complete: 8/48^MJobs complete: 9/48^MJobs complete: 10/48^MJobs
complete: 11/48^MJobs complete: 12/48^MJobs complete: 13
/48^MJobs complete: 14/48^MJobs complete: 15/48^MJobs complete: 16/48^MJobs
complete: 17/48^MJobs complete: 18/48^MJobs complete: 19/48^MJobs complete:
20/48^MJobs complete: 21/48^MJobs complete: 22/48^MJobs complete:
23/48^MJobs complete: 24/48^MJobs complete: 25/48^MJob
s complete: 26/48^MJobs complete: 27/48^MJobs complete: 28/48^MJobs
complete: 29/48^MJobs complete: 30/48^MJobs complete: 31/48^MJobs complete:
32/48^MJobs complete: 33/48^MJobs complete: 34/48^MJobs complete:
35/48^MJobs complete: 36/48^MJobs complete: 37/48^MJobs comple
te: 38/48^MJobs complete: 39/48^MJobs complete: 40/48^MJobs complete:
41/48^MJobs complete: 42/48^MJobs complete: 43/48^MJobs complete:
44/48^MJobs complete: 45/48^MJobs complete: 46/48^MJobs complete:
47/48^MJobs complete: 48/48
Waiting For Other Processors To Finish
Finished Executing MultiApps on LINEAR
 
 
Starting Transfers on LINEAR From MultiApps
Beginning PostprocessorInterpolationTransfer temp_mod
Finished PostprocessorInterpolationTransfer temp_mod
Jobs complete: 1/48^MJobs complete: 2/48^MJobs complete: 3/48^MJobs
complete: 4/48^MJobs complete: 5/48^MJobs complete: 6/48^MJobs complete:
7/48^MJobs complete: 8/48^MJobs complete: 9/48^MJobs complete: 10/48^MJobs
complete: 11/48^MJobs complete: 12/48^MJobs complete: 13
/48^MJobs complete: 14/48^MJobs complete: 15/48^MJobs complete: 16/48^MJobs
complete: 17/48^MJobs complete: 18/48^MJobs complete: 19/48^MJobs complete:
20/48^MJobs complete: 21/48^MJobs complete: 22/48^MJobs complete:
23/48^MJobs complete: 24/48^MJobs complete: 25/48^MJob
s complete: 26/48^MJobs complete: 27/48^MJobs complete: 28/48^MJobs
complete: 29/48^MJobs complete: 30/48^MJobs complete: 31/48^MJobs complete:
32/48^MJobs complete: 33/48^MJobs complete: 34/48^MJobs complete:
35/48^MJobs complete: 36/48^MJobs complete: 37/48^MJobs comple
te: 38/48^MJobs complete: 39/48^MJobs complete: 40/48^MJobs complete:
41/48^MJobs complete: 42/48^MJobs complete: 43/48^MJobs complete:
44/48^MJobs complete: 45/48^MJobs complete: 46/48^MJobs complete:
47/48^MJobs complete: 48/48
Waiting For Transfers To Finish
Transfers LINEAR Are Finished
 
18 Linear |R| = 3.524058e-03
```
_would become_
```
17 Linear |R| = 3.525662e-03
18 Linear |R| = 3.524058e-03
```
_End of Example_

### Identified impact
I'm thinking since this only appears in the logs, nothing would be impacted. Perhaps `tests` where the gold file is a log output would be affected.

**Comment by elementx54** [comment]
Believe it or not, but I was going to attempt this pull request myself, notwithstanding my inexperience with the guts of the code. So before I begin, I'm open for some guidance. So far this is what I've found out.

### Location of Messages
The messages for the transfer are found in this function:
[FEProblemBase::execMultiApps](https://github.com/idaholab/moose/blob/b94bd4dc0faab3ba286a87df0c87114404baae66/framework/src/base/FEProblemBase.C#L2822)
Most are direct streams to `_console`. The "Jobs complete:" section comes from the call of the `MooseUtils::parallelBarrierNotify` function.

But this is not the only place, within the `execute()` function of each transfer are lines of code with direct streams to `_console`. Many of the transfer `*.C` files have this code specifying the beginning and ending of the transfer to output. Example: [MultiAppVariableValueSamplePostprocessorTransfer.C](https://github.com/idaholab/moose/blob/ef593750b83615b768aec2dc12adc1ca48e07b44/framework/src/transfers/MultiAppVariableValueSamplePostprocessorTransfer.C#L45)

### Solution Ideas
I would love for the option to turn off and on the transfer messages to be found in the `[Debug]` section of the input file. However, it might be nice to give the user way more flexibility than _all in_ or _all out_ by providing debug parameters in transfers and/or multiapps. Individual debug parameters would be easy enough to implement, but might not be acceptable.

I found the action system allows for the creation of Output objects. I'm not sure that is what I want since the current messages are output based on what the multiapp and transfers are doing at that very moment. Output objects seem to be output on their own separate from other objects, if I'm understanding it correctly. I'm thinking of making the Debug section set all the multiapps and transfers to have a debug parameter set to true. That still means making a debug parameter in the class all the multiapps inherit from and something similar for transfers. A `[GlobalParams]` could also complete the same purpose, which would allow for individual adjustment by the user as needed.

That being said, I'm leaning towards adding a debug parameter to [MultiApp.C](https://github.com/idaholab/moose/blob/devel/framework/src/multiapps/MultiApp.C) and having it available in FEProblemBase.C when everything is called. The addition of a transfer debug parameter to [Transfer.C](https://github.com/idaholab/moose/blob/devel/framework/src/transfers/Transfer.C) is similar to the multiapp parameter addition. I'm not sure how to make it available in the FEProblemBase.C; however, those files are included so just using a namespace to access them should be fine, which I'll probably try first.

### Summary
Add debug parameter to MultiApp.C and Transfer.C. Add "if" statement to check debug _true_ before output to `_console` lines; this involves changing things in many files in transfer's directory and FEProblemBase.C. The icing on the cake will be to add a Debug action to set all the debug parameters in the MultiApps and Transfers to _true_.

**Comment by permcody** [comment]
I don't think we need a flag in the input file to toggle this behavior. Very few people really need to see this. I'd be fine if you just put an `#ifndef NDEBUG` CPP macro around the actual printing inside the utility, that'd be fine with me. That'll leave printing on in "devel" and "dbg" modes. If somebody wants to add a flag later, we could do that by changing the API to `parallelBarrierWithNotify` so that it takes a verbosity flag. As you noted in your ticket, that could be read in through the [Debug] block and passed as needed to that method. Let's go with Option 1 for now. It's a two line "fix".

**Comment by permcody** [comment]
@elementx54 - Do you plan on doing anything with this ticket? Otherwise I'll close.

**Comment by elementx54** [comment]
Nope since the issue became bigger than I initially thought. However, it still isn't "fixed" as in anyone trying to do a transfer on each linear iteration will still see a large increase in log size. I found for my application that transferring that often made my problem unstable, so this issue doesn't bother me anymore.
