### ISSUE TITLE
Replace use of isnan with std::isnan

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8737]
### Description of the enhancement or error report
`std::isnan` is C++11 - we can use that now. `isnan` is... not really anything well defined.

### Rationale for the enhancement or information for reproducing the error
Compile errors with older toolchains

### Identified impact
Fixes stuff for obscure edge cases (ping @amjokisaari)

**Comment by permcody** [comment]
Late to the party but there is a well-defined `isnan` in libMesh. We were just missing an include here. Oh well, C++11 is supported now.

**Comment by dschwen** [comment]
There is `libmesh_isnan`, but why bother?
