### ISSUE TITLE
Add scale factor parameter to PiecewiseLinearInterpolationMaterial

### ISSUE THREAD

**Issue by backmari** [idaholab/moose#8752]
### Description of the enhancement or error report

I will add a scale factor parameter to PiecewiseLinearInterpolationMaterial.

### Rationale for the enhancement or information for reproducing the error

Allow easier scaling of material values

### Identified impact

No impact

ping @bwspenc

**Comment by andrsd** [comment]
@backmari Please, do not remove sections from the template, our SQA procedures require we have all three. Thanks.

**Comment by backmari** [comment]
@andrsd OK, no problem!
