### ISSUE TITLE
PorousFlow task: add C++ enum to PorousFlowPropertyAux

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8756]
### Description of the enhancement or error report

Use a C++ enum as well as a MooseEnum in PorousFlowPropertyAux to allow us to change "case 0:" to "case pressure:", etc

### Rationale for the enhancement or information for reproducing the error

Clearer code.  I will do this sometime soon, unless @cpgr wants to get there first.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Only PorousFlowPropertyAux.* will change internally.

**Comment by permcody** [comment]
You can find an example of that being done here:
https://github.com/idaholab/moose/blob/devel/framework/src/postprocessors/NumDOFs.C

**Comment by WilkAndy** [comment]
OK, in my constructors i used (the equivalent of)

```
_system_enum((SytemEnum)(int)parameters.get<MooseEnum>("system")),
```
instead of

```
_system_enum(parameters.get<MooseEnum>("system").getEnum<SystemEnum>()),
```

Is the latter preferred?

**Comment by cpgr** [comment]
You do enough @WilkAndy - I'll look after this one for you!

**Comment by permcody** [comment]
Yeah, we didn't like the two cast (c-style) version, it's pretty hackish. The later method uses a template argument which feels less 'icky'.

**Comment by WilkAndy** [comment]
OK, thanks @permcody 

a
