### ISSUE TITLE
You can't use arrow keys to apply picklist options in new Peacock

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8777]
### Description of the enhancement or error report

When selecting a pick list widget, it's handy when I can use the arrow keys to apply each option so I can quickly look through all the variables in a list and try them out.

### Rationale for the enhancement or information for reproducing the error

This isn't possible in the new Peacock. You have to use your pointer device and click on the object again and select a new option each time.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Minor usability feature

**Comment by brianmoose** [comment]
Do you want to be able to tab to all options? I noticed that tabbing through the options skips the checkboxes, combos, sliders, etc. Only widgets that have `StrongFocus` set are able to be tabbed to.

**Comment by permcody** [comment]
That's a pretty normal thing to be able to do, but lets face it, everyone has a mouse and nobody uses tab to go between widgets. I'd say do that if it's easy but I'm not worried about it.

**Comment by brianmoose** [comment]
The main reason not to is for the options that are rarely used. Tabbing through a bunch of rarely used options to get to the one you want can get annoying. That would require someone to decide which options are important and which aren't.
