### ISSUE TITLE
Avoid double listing of Postprocessors under UserObjects

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8792]
### Description of the enhancement or error report
Currently all Postprocessors have two .md files in the documentation system and are listed twice on the doc site, under Postprocessors and again under UserObjects. Please avoid that.

### Rationale for the enhancement or information for reproducing the error
Makes the docs more confusing, and introduces duplication (two .md doc files to be maintained)

### Identified impact
Improved documentation

**Comment by aeslaughter** [comment]
Hopefully, the new JSON dump will have the information that I need to make this happen. Not sure when I will get to it.
