### ISSUE TITLE
Peacock save image button appears to be nonfunctional

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8808]
### Description of the enhancement or error report

Unable to get the "Save PNG" button to work in Peacock.

### Rationale for the enhancement or information for reproducing the error

Although the button brings up the save file dialog. Nothing happens when I click "Save".

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Minor: Peacock usability

**Comment by brianmoose** [comment]
I could not reproduce this.
I confirmed that it works on the ExodusViewer and the 2 postprocessor tabs.
What are you doing differently?

**Comment by permcody** [comment]
So it appears to do nothing if you only type the first part of the name. In the editor the file type is set as `*.png` so I just typed "foo" in the box and hit save. Nothing happened. I finally tried again later and typed "foo.png" and it worked. I guess if you leave off the extension nothing happens?

**Comment by brianmoose** [comment]
Yeah, I can confirm. I do get an error on the terminal though saying the filename must end in .bmp, .png, .jpg, .tiff, .ps.
Do you want to automatically add the .png extension if no extension is present? Or just give an error dialog?

**Comment by permcody** [comment]
Either is fine with me. Just make sure that the user gets a message
(terminal doesn't count). I'd suggest that if they have files of type
selected, that you add that type automatically. That's generally what
happens with other applications (and the reason I didn't type the
extension).
