### ISSUE TITLE
Selecting new fields in peacock sometimes just doesn't work

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8809]
### Description of the enhancement or error report

Sometimes I select a new variable in the ExodusViewer tab and it just doesn't work. There's a long pause and then the first variable is selected instead.

### Rationale for the enhancement or information for reproducing the error

Run the grain_growth_2D_graintracker.i example. While the simulation is running, try selecting different fields. Also, I notice really long delays when switching tab after 15 or so time steps have completed. Really sluggish when the problem sizes are a little larger.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Medium: Peacock usability

**Comment by brianmoose** [comment]
I couldn't really reproduce this.
I let grain_growth_2D_graintracker.i for up to 100 time steps. Switching variables still worked fine. Switching tabs was also fine.
This was on a fresh start of peacock though. Did this happen to you after running a 1000 different times?

**Comment by permcody** [comment]
Try switching variables twice in a row? I'll demo this for you when I get back. The second time I switch it usually defaults to the first variable "bnds" instead. You don't have to let it run very long. Just a few timesteps is all. Again, I'll demo this when I get back.
