### ISSUE TITLE
PorousFlow: persistent variable compositional model

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#8818]
### Description of the enhancement or error report
Presently, the `porous_flow` module can't model cases where one phase disappears with multiple fluid components. For example, consider a two component, two phase (isothermal) model. When two phases are present, the primary variables are pressure and saturation. When only a single phase is present, the primary variables should be pressure and mass fraction of one of the fluid components.

There are two main ways to deal with this: (i) switch primary variables from (P,S) when there are two phases, to (P, X) when there is only a single phase, or (ii) use a persistent set of primary variables.

This issue deals with implementing (ii).

### Rationale for the enhancement or information for reproducing the error
Adds increased capability to the `porous_flow` module

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
New functionality

**Comment by WilkAndy** [comment]
This is majorly awesome work, Chris.  I didn't know you were working on it!

**Comment by cpgr** [comment]
Hehehe - I'd started it before the major `_nodal_material` refactor while I was overseas, and haven't had a chance to get it working with that change until this week when I had a couple of days free.

**Comment by cpgr** [comment]
This issue can be closed. Any new features related to this can get their own issue
