### ISSUE TITLE
Create new Moose App: Articuno

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8832]
Tagging @lindsayad and @aeslaughter 

Today i wondered what these "zapdos" and "moltres" animals were.  My kids are massively into pokemon.  Apparently a very appropriate name for @aeslaughter 's ice/snow moose app would be Articuno.

Heheheh, i think i've had too many beers.

**Comment by aeslaughter** [comment]
If I am going with video game characters, I would go with this: 

![](https://upload.wikimedia.org/wikipedia/en/a/a7/SubZeroMKXrender.png)

**Comment by lindsayad** [comment]
Hehehe, I'm very happy you brought this up @WilkAndy. I raised the same question with @aeslaughter in December. His app really should be named Articuno. I vote to reopen the issue :-)

**Comment by WilkAndy** [comment]
Wowsers, who is that guy above.  He looks pretty cool, i must admit.  But does his name mean "the arctic one" ?

**Comment by andrsd** [comment]
That is [Sub-Zero](https://en.wikipedia.org/wiki/Sub-Zero_(Mortal_Kombat)) from Mortal Kombat...
