### ISSUE TITLE
Initialize the StateVariableUO based on spatial coordinates in Crystal Plasticity 

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/moose#8843]
### Description of the enhancement or error report
We need to add this capability to allow users to initialize the state variable in crystal plasticity code based on the spatial coordinates. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Only affect crystal plasticity code in TensorMechanics module.

**Comment by permcody** [comment]
closed by #8846
