### ISSUE TITLE
Vector Variables

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#886]
Ok - it might be time to add vector variables.  Here's how I see this working out
1.  Input Syntax:

```
[ [./velocity](./Variables]
)
    type = Vector
    family = LAGRANGE
    order = FIRST
  [../]

```

That will implicitly create velocity_x, velocity_y and velocity_z depending on the dimension of the problem.

2)  Next up is Kernels.  We need a "VectorKernel".  It's computeQpResidual() function will take an argument of type TypeVector reference (ie computeQpResidual(TypeVector & res) ).  Inside computeQpResidual() it will be the Kerne's job to fill in that TypeVector with the residual for the x, y, z directions.

This Kernel will still have things like _phi, _grad_u... but those will be vectors/matrices as needed.

3)  Coupling

Coupling to vector variables will be handled in two ways:

3a) Using the old coupledValue() style functions you can couple directly to the individual components (like velocity_y).

3b) New coupling functions like coupledVectorValue(), coupledVectorGradient(), etc.

How will all of this be implemented under the hood?  I'm not exactly sure yet.  We could make a VectorMooseVariable class that's responsible for computing the values of these guys... but I'm not sure we need to.  We might just treat them as scalar variables under the hood... and just do the translation on the fly into the vector stuff.  I think we'll just have to see how it goes.

**Comment by lindsayad** [comment]
Closed by #10238
