### ISSUE TITLE
PorousFlow : create a dependency graph

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8870]
### Description of the enhancement or error report

Create a class (or namespace?) that holds dependency information,  Eg, the PorousFlowAdvectiveFlux Kernel depends on PorousFlowDarcyBase Kernel, and the PorousFlowMassFraction_nodal and PorousFlowRelativePermeability_nodal Materials.

### Rationale for the enhancement or information for reproducing the error

When using Actions we only want to add the minimal number of Materials, to minimise runtime computations.  Knowing what Kernels and AuxKernels that they have to add, the Actions will be able to query this dependency graph to see what Materials they have to add.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Increase speed of input files that utilise Actions.

**Comment by YaqiWang** [comment]
@WilkAndy can you achieve this by fusion kernels and materials? Not sure if you are aware that you can check the blocks where a material property is defined and add kernels only on those blocks. I feel that is very useful in actions. You possibly can also check the blocks of kernels in a certain type although I never used it before.

**Comment by WilkAndy** [comment]
I don't think i can do that, @YaqiWang .  My Action is supposed to add all required Kernels and **only** the required Materials on each block.  Given a particular Kernel, i have to know which Materials to add (those that are required by the Kernel).  For some Kernels this is easy, but for some Kernels there is a complicated chain of Materials required.  Of course it's not impossible to work out that chain (in fact it'd be much quicker to do it by hand than write this Dependency Graph stuff!) but i want something a bit more robust and maintainable.
