### ISSUE TITLE
Dump input file syntax equivalent to action-generated objects

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#8875]
### Description of the enhancement or error report
Add ability to dump the equivalent input file syntax for all objects added by a given action. Note that this is _not_ what `--show-input` does.

### Rationale for the enhancement or information for reproducing the error
For debugging and input refactoring purposes.

### Identified impact
Added capability.

**Comment by lindsayad** [comment]
@aeslaughter You mentioned that you could work on this. Could you work on it soon? Otherwise, I might take it up.

**Comment by aeslaughter** [comment]
@lindsayad What is soon mean to you?

**Comment by lindsayad** [comment]
Maybe a week or two

**Comment by aeslaughter** [comment]
I can handle it then.
