### ISSUE TITLE
Add generic effective strain method in SM and TM

### ISSUE THREAD

**Issue by acasagran** [idaholab/moose#8905]
### Description of the enhancement or error report
Create a new method to compute the effective strain. 

### Rationale for the enhancement or information for reproducing the error
In order to make the calculation of the scalar plastic or creep strain more consistent, adding a new method which will accept either the plastic or creep part of the strain tensor is a more flexible approach. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Adds new capability and improves code consistency.

**Comment by permcody** [comment]
Closed by referenced commits.
