### ISSUE TITLE
Saved State on Exodus viewer doesn't appear to work

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8916]
### Description of the enhancement or error report

If you switch between different open files, the state of the check boxes and other controls on the Exodus tab doesn't reflect what's actually shown. It appears that state is saved when you switch between variables, just not files.

### Rationale for the enhancement or information for reproducing the error

Try opening a second file and checking various boxes. Then switch back and forth between the two output files.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Peacock robustness

**Comment by brianmoose** [comment]
Yeah, some widgets seem to remember state between changing files, at least on the actual widget, but it is not reflected in the vtk window.

I can also reliably crash peacock by doing:
1. Start peacock with 2 exodus files on the command line
2. Enable "View Mesh" on the first file.
3. Switch to the second file
4. Enable "Wireframe"
5. Switch to the first file
Aborts with:
```
Traceback (most recent call last):
  File "/Users/algebk/projects/moose/python/peacock/ExodusViewer/plugins/MeshPlugin.py", line 166, in _callbackRepresentation
    self.mesh()
  File "/Users/algebk/projects/moose/python/peacock/ExodusViewer/plugins/MeshPlugin.py", line 96, in mesh
    filters = self._result.getOption('filters')
AttributeError: 'NoneType' object has no attribute 'getOption'
Abort trap: 6
```

Is saving state between switching files the desired behavior? Or just resetting to the default settings on a file switch?
At the bare minimum, the state of the various options should be reflected in the vtk window.

**Comment by aeslaughter** [comment]
@brianmoose Can you take a stab at fixing this? I thought I would get to it quickly but I am deep into doc tools for SQA stuff until next week.

I created some tools for save widget state, but they are not implemented correctly. When I did it I created a storage structure that had multiple levels, but I don't think I did it correctly. What I would do if I was fixing this up would be to used a single key to lookup state: widget.store('foo') and widget.load('foo'). For the Exodus tab I would create the name by combining the current filename and variable name to make a unique key for storing and loading. This shouldn't be too difficult to re-factor and hopefully get correct. 

> Is saving state between switching files the desired behavior? Or just resetting to the default settings on a file switch?

Yes, I want to be able to setup to look at something in one file, switch to another to look at something else, then return and restore my settings for the previous file. 

In the future I would also like Peacock to remember the widget settings for a file. So, if I am working on something, close peacock, then load the same file it should start from my previous state (at least optionally).
