### ISSUE TITLE
Get rid of apply in peacock editor windows

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8928]
### Description of the enhancement or error report

Why are you always applying, just go!

- [ ] To change a parameter you must first change it, then click apply. Let's make the close button also apply.
- [ ] See if you can make the editor window come to the front when you switch to the input tab (after leaving the editor open 

### Rationale for the enhancement or information for reproducing the error

No errors, just better peacock usability.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Peacock usability

**Comment by friedmud** [comment]
Ummm - no?  What if you change values and then you decide you don't like
the changes?

**Comment by permcody** [comment]
We decided not to get rid of apply. Instead it'll apply when closed now (which it didn't before). There is still a reset button on the editor window. I learned that you can leave the editor window open as you move between tabs. It doesn't have to be closed which was new to me.

**Comment by friedmud** [comment]
Ok - I'll reserve judgement until I try it :)

**Comment by friedmud** [comment]
Ok - I've tried it now.  It's almost right: `Close` should get renamed to `Apply and Close`... otherwise it's non-obvious that any changes you make will be applied.

**Comment by friedmud** [comment]
Also: move `Apply and Close` to the left.
