### ISSUE TITLE
Exodus Renderer doesn't work right when switching from 2D to 3D

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8929]
### Description of the enhancement or error report

If you run a 2D input file, then a 3D input file, the Exodus viewer stays stuck in 2D mode and you can't rotate the result.

### Rationale for the enhancement or information for reproducing the error

Run a 2D input file then a 3D input file in the same peacock session.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Peacock robustness

**Comment by brianmoose** [comment]
I couldn't reproduce this. I switched back and forth a few times between 2D and 3D and everything seemed to work fine (both in the mesh viewer on the input tab and the exodus viewer).
What else do I need to do to reproduce this?

**Comment by permcody** [comment]
I'll try again and see if I can reproduce, if not, I'll close this issue.

**Comment by aeslaughter** [comment]
@permcody Is this still a problem?

**Comment by permcody** [comment]
I'm unable to replicate, I guess this is why we need better instructions in the issue about how to replicate. I just tried it with a 2D and 3D simple diffusion file and it worked fine for me.
