### ISSUE TITLE
Temperature = temp does not work in GeneralizedPlaneStrainAction

### ISSUE THREAD

**Issue by hchen139** [idaholab/moose#8957]
### Description of the enhancement or error report

In GeneralizedPlaneStrainAction, addition of temperature kernel is determined by whether the temperature variable is provided and whether the provided temperature variable is a nonlinear variable. We should check any possible value of the temperature variable (temperature = value) as provided by the user rather than fixing the value to "temperature".

### Rationale for the enhancement or information for reproducing the error

Setting "temperature = temp" rather than "temperature = temperature" will not trigger the GeneralizedPlaneStrainAction to add temperature kernel.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No impact on current tests

**Comment by permcody** [comment]
@hchen139 - Feel free to use "closes" or "fixes" if your commit completely addresses an open issue. That way they don't stay open after the task is complete.
