### ISSUE TITLE
PorousFlow: deprecate basic fluid property materials

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#8962]
### Description of the enhancement or error report
The `porous_flow` module has several materials that provide basic fluid properties that duplicates those available in the `fluid_properties` module. These should be removed so that a single consistent interface for fluid property calculations is used.

### Rationale for the enhancement or information for reproducing the error
When we first started the `porous_flow` module, we added materials to give fluid properties like density, viscosity etc as there was no `fluid_properties` module. We have moved over a lot of these initial materials, but there are a few that are still around (PorousFlowDensityConstBulk, PorousFlowViscosityConst, PorousFlowIdealGas, etc). 

All of these properties are available in the `fluid_properties` module, so they should be eventually removed from `porous_flow`.Reasons for this include:

- reduction in code duplication
- easier testing of `fluid_properties` user objects (especially derivatives)
- Properties (like bulk modulus in SimpleFluidProperties) only needs to be entered once in an input file, rather than multiple times (for example, when using PorousFlowDensityConstBulk evaluated at nodes and qps, two PorousFlowDensityConstBulk materials are required)
- consistent interface to calculating fluid properties like density over all input files (which makes swapping fluids trivial)

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This will require changes to lots of tests, and eventually require any users to modify their input files to use the formulation in the `fluid_properties` module.

Pinging @WilkAndy for his thoughts

**Comment by WilkAndy** [comment]
Yea, i totally agree with this, and i can't think of anything off the top of my head that would not be covered by the FluidProperties stuff.  The input files will be a pain in the bum to change.

**Comment by cpgr** [comment]
Yeah, that part of this sucks.
