### ISSUE TITLE
Overzealous error checking in MonotonicCubicInterpolation?

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#8970]
### Description of the enhancement or error report
I'm trying to use MonotoneCubicInterpolation with a set of data that is monotonic in x, but not y.  I'm getting an error from one of the checks in errorCheck() because the y data is not monotonic.  It looks like this is supposed to implement the Fritsch & Carlson method (http://dx.doi.org/10.1137/0717021).

Unfortunately, I haven't yet been able access the original paper because our library doesn't subscribe to that journal, but as far as I can tell, that method is only supposed to enforce that the resulting interpolation is monotone on each interval, not over the entire domain.  For what it's worth, the MATLAB and numpy pchip interpolators work just fine with my non-monotonic data.

@lindsayad It looks like this is your code, so I'm guessing you might be able to provide some input here.

### Rationale for the enhancement or information for reproducing the error
These are the numbers I'm trying to use with it:
x=[0.01666 0.05 0.1 0.2]
y=[0.68676323  0.6739166   0.67589921  0.67554883]
If I comment out errorCheck(), it happily runs with this data.

### Identified impact
I'm not quite sure what the right thing to do here is, but I think that checkMonotone() should maybe just be applied to the x values and not the y values.

**Comment by permcody** [comment]
Google scholar can get you to this paper. Try this link:
http://www.ams.sunysb.edu/~jiao/teaching/ams527_spring13/lectures/SNA000238.pdf

**Comment by bwspenc** [comment]
Hmm... it looks like all of the examples in that paper do have monotonic data.

There might be a little more to this issue than just that error check.  I ran this little python code to check what the scipy implementation of pchip gives on one of my data sets:
```
from scipy.interpolate import PchipInterpolator as pchip
x=[1./60., 1./20., 1./10., 1./5.]
y1=[0.715954, 0.719298, 0.715713, 0.715393]
pc=pchip(x,y1)
pc(1./15.)
```
This gives: 0.7183938131513283

When I try the MOOSE MonotonicCubicInterpolation class on that same data (with that error check disabled), I get 0.718723.  I wonder if these are not actually using the same algorithm.

**Comment by permcody** [comment]
You might tag the authors. There was a discussion about this object recently on the mailing list.

**Comment by bwspenc** [comment]
@permcody I already tagged him.  I found the source code for the scipy implementation (which gives the same result as MATLAB in my test case).  It's installed on our machines in:
/opt/moose/miniconda/lib/python2.7/site-packages/scipy/interpolate/_cubic.py
I guess I need to look carefully through it and see what it's doing differently.  It looks like it's doing some special treatment of edge cases, per its documentation:
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.interpolate.PchipInterpolator.html#scipy.interpolate.PchipInterpolator

**Comment by lindsayad** [comment]
The whole premise of the Fritsch and Carlson paper is that f_i < f_{i+1} for i = 1, 2, ..., n - 1 or f_i > f_{i+1} for i = 1,2, ..., n - 1. I believe I implemented their algorithm faithfully; however, if you find an error in the algorithm please let me know. If you believe you can extend the algorithm to use cases where you don't want to produce a monotone function then maybe we can remove the error check and generalize the name. However, the use case that I envisioned for this and the issue I was trying to address (#7158) and which I believe @WilkAndy wanted addressed, was guaranteeing monotone function construction for monotone data, data here meaning monotonically increasing or decreasing dependent variable

**Comment by WilkAndy** [comment]
However this works out, i want to echo @lindsayad 's comment that the point of this object was to ensure monotonicity, and of course that means the data must be monotonic.   If you want to generalise to something else, great!   But make sure there is some flag that ensures monotonicity of the spline.

It's very easy to enter monotonic data and the resulting spline is not monotonic.  That gives all sorts of convergence problems and nonphysical behaviour.  @lindsayad was addressing this problem.

**Comment by bwspenc** [comment]
I agree that the Fritsch & Carlson paper does assume that the data is monotonic.  However, if you look at the documentation for the MATLAB pchip function (which supposedly implements the Fritsch & Carlson algorithm), the second example they show uses non-monotonic data:
https://www.mathworks.com/help/matlab/ref/pchip.html
Here's an important point from the bottom of that page: 
> The cubic interpolant P(x) is shape preserving. The slopes at the xj are chosen in such a way that P(x) preserves the shape of the data and respects monotonicity. Therefore, on intervals where the data is monotonic, so is P(x), and at points where the data has a local extremum, so does P(x).

It sounds to me like their variant of the algorithm would meet both your needs and mine without any special options.  We don't have access to the MATLAB code to figure out what they're doing, but the scipy implementation seems to give identical results to MATLAB's implementation in my limited testing, and we (I) can look at that to see if they did anything special.

**Comment by WilkAndy** [comment]
That sounds good @bwspenc .  If someone can implement the scipy/matlab stuff then it would be great.  i bet the matlab and scipy codes are identical!

**Comment by bwspenc** [comment]
I need to look into it more, but I think they're just doing something really simple like setting the derivative to zero at the data points that are extrema.

**Comment by lindsayad** [comment]
@bwspenc Have you looked into this, e.g. comparison of the scipy algorithm and the algorithm here? If not, I will start investigating.

**Comment by bwspenc** [comment]
@lindsayad No, I haven't yet other than that I looked through your code, and it looks like you are setting the derivative to zero at the points where the sign changes, which is essential for this to work.  I think if you just disable the error check, the current code does generate a decent fit for non-monotonic data, but the results are a little different from those of matlab/scipy.

The next thing I was going to do was develop a unit test with non-monotonic data in MOOSE where I'm sampling the function at enough points where I can plot them out and visually see what's going on, and then generate an equivalent in scipy for comparison.

If you've got a chance to look into that, I definitely wouldn't complain!

**Comment by permcody** [comment]
@bwspenc - any resolution on this ticket? It's unclear what action should be taken from here.

**Comment by bwspenc** [comment]
This is still an open issue, and I would like to get it resolved. @lindsayad we should talk about this.

**Comment by lindsayad** [comment]
@bwspenc So the algorithms are indeed different between what I've done and what is implemented in SciPy and presumably matlab (as a surrogate I'm testing with octave). I (and Fritsch) use a three-point centered difference formula to calculate the derivatives while scipy and matlab use a harmonic mean. Three-point centered differences have second-order accuracy for calculating the derivatives; I don't know what the order accuracy is for the harmonic mean without some testing/research but it doesn't appear to be second order. Indeed it is unable to exactly approximate a quadratic function which the centered-difference can.

For example, in octave:
```
octave:13> x = [0 2 4 6 8 10];
octave:14> y = [0 4 16 36 64 100];
octave:15> xq1 = 0:1:10;
octave:16> p = pchip(x, y, xq1)
p =

 Columns 1 through 9:

     0.00000     1.25000     4.00000     8.87500    16.00000    24.95833    36.00000    48.97917    64.00000

 Columns 10 and 11:

    80.93750   100.00000
```
You can see that approximation is not exact at the new nodes. However, as shown in our unit test for `MonotoneCubicInterpolation` the approximation is exact. I'm going to conduct a similar test with a quadratic including the extrema, and once I have that right, then I'll remove the monotonic data checking.

**Comment by WilkAndy** [comment]
Fascinating, thanks for the update, @lindsayad
