### ISSUE TITLE
Refactor PermutationTensor into RankTwo, RankThree, and RankFourTensor classes

### ISSUE THREAD

**Issue by mangerij** [idaholab/moose#8987]
### Description of the enhancement or error report

We have a small function defined as eps(unsigned int i, unsigned int j, unsigned int k) which is

http://mathworld.wolfram.com/PermutationTensor.html

It has its own class in /utils but it really should just be a member of the three tensor classes. 

### Rationale for the enhancement or information for reproducing the error

Makes the code more lightweight. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Not sure which app uses this, should be an easy fix anyway.

**Comment by permcody** [comment]
Closed by #9015
