### ISSUE TITLE
precheck trailing whitespace check needed?

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#8998]
### Description of the enhancement or error report

We check for trailing whitespace in the git pre-check, but that's probably no longer necessary

### Rationale for the enhancement or information for reproducing the error

Doesn't clang format pick these things up?  Possibly similar for other pre-check checks.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

git pull request checks

**Comment by brianmoose** [comment]
The trailing whitespace check also checks `*.i` and `*.py` files. We could break the `*.[Ch]` check out though.
Similar for the tab check, although I don't know if clang format removes **all** tabs or just tabs used for indentation (we currently don't allow tabs anywhere).

We could stop doing the style check though as that just checks for proper spacing around control keywords, which clang format should get.

**Comment by permcody** [comment]
We still need part of those checks. I think it's a good idea to check for banned keywords and of course whitespace in the non-C++ files.

**Comment by WilkAndy** [comment]
Thanks guys,

a
