### ISSUE TITLE
MaskedBodyForce has incomplete Jacobian

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9004]
### Description of the enhancement or error report
`MaskedBodyForce` has an incomplete Jacobian implementation if the masking material property depends on non-linear variables. We should add a `MatBodyForce` or `MatSource` (like `MatDiffusion` etc.) that uses the `DerivativeMateriaInterface` to provide correct Jacobians. The combination of a prefactor, a MooseFunction, and a material property is getting a little messy already.

### Rationale for the enhancement or information for reproducing the error
Better convergence with strongly variable dependent body forces.

### Identified impact
Added capability

**Comment by laagesen** [comment]
To try to improve the performance of the grand potential based fission gas bubble swelling model, I'm going to implement the Jacobians. After discussing with @dschwen we decided to leave the kernel name as is.

**Comment by laagesen** [comment]
Also I am going to add documentation.
