### ISSUE TITLE
INS coefficients as MaterialProperties

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#9008]
@jwpeterson may want to discuss this...

### Description of the enhancement or error report

Currently in Navier Stokes, properties like density, viscosity, heat capacity, and thermal conductivity are `Reals` provided directly from the input file. These properties could be more flexible if they were made into MaterialProperties. Then they could be provided as constants via `GenericConstantMaterial`, as functions via `GenericFunctionMaterial`, or as functions of coupled variables via `DerivativeParsedMaterial` etc.

### Rationale for the enhancement or information for reproducing the error

Greater flexibility for the user. Not really any current way to use INS kernels if properties aren't constants.

### Identified impact

Expand usability of the INS kernels.

**Comment by jwpeterson** [comment]
:+1: Seems like a straightforward change...

**Comment by jwpeterson** [comment]
You may want to use the `FluidProperties` module for this. I think it is already used on the compressible side and is probably appropriate for INS as well.

**Comment by lindsayad** [comment]
@jwpeterson Did you write the compressible pieces of this module as well? Certainly a lot more going on in compressible than in incompressible.
