### ISSUE TITLE
speed up Rank[Two/Four]Tensor

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#9029]
### Description of the enhancement or error report

There is a lot of low-hanging fruit for speedup in tensor calculations.  Smarter data layout and indexing mostly.  PR coming.

### Rationale for the enhancement or information for reproducing the error

The utils tensor classes are used heavily in some apps (BISON, MARMOT, etc.) accounting for significant fractions of many simulations' run time.

### Identified impact

Make things run faster - no API or behavior changes required.

**Comment by mangerij** [comment]
There is now a RankThreeTensor as well.

**Comment by mangerij** [comment]
So how much faster does this make things? It certainly makes the code harder to read for the uninitiated.

**Comment by rwcarlsen** [comment]
I updated the PR description with a couple numbers.

**Comment by permcody** [comment]
@rwcarlsen - I'm ready to merge this. We'll want to capture this work in the report we'll write soon.
