### ISSUE TITLE
Handle special case keywords that are handled by MOOSE internally

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9048]
### Description of the enhancement or error report

There are certain keywords that MOOSE handles internally but are not available in the JSON dump for validation. These keywords include "all" and "none" but there may be others. I believe those two keywords in particular exist in the `Outputs` system and may appear in several blocks.

### Rationale for the enhancement or information for reproducing the error

Improve validation code, remove errors from the NEAMS Workbench from unknown values.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Better NEAMS Workbench integration.

**Comment by permcody** [comment]
tag @brandonlangley

**Comment by brianmoose** [comment]
How do you want this to look in the JSON dump?
Have a "reserved_names" for the parameter that would contain "all" and "none"?
A "reserved_names" might more logically be put on the "Outputs" block since you can't have subblocks with reserved names.

**Comment by permcody** [comment]
Well I guess the question is, what sort of API do we create on the MOOSE side to add these reserved names. One option might be adding extra methods to the InputParameters object (which is the only thing you can use during the dump process). I don't think that you should go into the JSON dumper and just add extra things to dump. I'd prefer if this information was registered elsewhere first.

**Comment by brianmoose** [comment]
Don't worry, I definitely want to register this information somewhere. I guess my question was more along the lines of do we want to register reserved words on a parameter by parameter basis, at the block level, or even at the parameter type level? The latter two would probably be added to the syntax tree, which we also have access to during the dump. For example:
 `syntax.registerReservedBlockNames("Outputs", outputwarehouse.getReservedNames())`
Or we could associate the reserved names with the type name, ie "OutputName".

**Comment by permcody** [comment]
We may need more than one solution. `active` for instance works with every single block and is a parameter name, not a value. Things like "all" and "none" are parameter values. You are welcome to take a look and propose a solution.
