### ISSUE TITLE
Add support for GetPot from command line

### ISSUE THREAD

**Issue by jhaase1** [idaholab/moose#9051]
### Description of the enhancement or error report
Based on this thread https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/moose-users/we17nDuyEeY/wLqKxOoTCgAJ

From Cody Permann:

GetPot should be doing all substitutions before MOOSE gets ahold of any parameters. It's an independent feature set that you can "just use". The fact that it kind of works, but kind of doesn't from the command line will take a little digging. You're welcome to open a ticket but I probably won't have time to jump on it right away. In the meantime you might just remove the GetPot expression and set the values directly with the assumption that you are working in standard SI units.

### Rationale for the enhancement or information for reproducing the error
Allow changing of simulation without needing to modify input file

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
Thanks!

**Comment by permcody** [comment]
@rwcarlsen - When you get a chance you might want to take a look at this issue (and associated thread) and see if this is something that can be handled by the new parser.

**Comment by rwcarlsen** [comment]
This should be fixed and just work with the new parser.  Somebody can reopen if they disagree.  New parser merges CLI params into the main parsed tree before doing substitutions or anything else.
