### ISSUE TITLE
address hasMaterialProperty calls in PorousFlow

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9076]
### Description of the enhancement or error report

I just learnt that hasMaterialProperty doesn't really work.  I need to figure out whether PorousFlow is affected.

### Rationale for the enhancement or information for reproducing the error

See comment in #7987

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by WilkAndy** [comment]
hasMaterialProperty is only used for error checking in PorousFlow.  This is fine: if hasMaterialProperty returns false (due to "poor" ordering of Materials in input file, for instance) then the relevant pieces of codes will just produce a mooseError.  They won't crash with some segfault or any other hard-to-debug error.  Therefore i'm just going to add a little bit of description to the mooseError messages.

**Comment by WilkAndy** [comment]
Closing this as i only use hasMaterialProperty in BCs and DiracKernels, so there's no potential for a Material ordering problem.

**Comment by permcody** [comment]
@WilkAndy - If you want this for error purposes, simply call it in your `initialSetup()` method. At that point all `Materials` and `Actions` have been run so you know for sure whether or not a a property is available.
