### ISSUE TITLE
Add ANN octree neighbor search library as a contrib to MOOSE

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9097]
### Description of the enhancement or error report
https://www.cs.umd.edu/~mount/ANN/ provides fast exact and approximate nearest neighbor search algorithm implementations. We'd like to add it as a contrib lib to MOOSE. It is licensed under LGPL, which is compatible.

### Rationale for the enhancement or information for reproducing the error
Nearest neighbor node searches are important for contact problems. Preliminary profiling shows that ANN is faster by up to two orders of magnitude for a typical contact problem. 

### Identified impact
This will enables us to perform more frequent neighbor searches for contact, improving the robustness of contact problems.

**Comment by rwcarlsen** [comment]
Have you looked at this library: https://github.com/mariusmuja/flann ?

**Comment by rwcarlsen** [comment]
Or even nifty-er: https://github.com/jlblancoc/nanoflann

**Comment by permcody** [comment]
The cool part of nanoflann is it's already in libMesh!

**Comment by dschwen** [comment]
Are you kidding me....

**Comment by sveerara** [comment]
I have not looked at flann or nanoflann. I compared the performance of ANN and https://github.com/jbehley/octree for different point clouds and ANN was performing better than the other library. I will look at nanoflann.

**Comment by permcody** [comment]
We've been using it for years! Talk to @jwpeterson, we are actually using it in MOOSE.

**Comment by jwpeterson** [comment]
Yes, I'm planning to use it for automatic mortar segment generation. I just opened a [ticket](https://github.com/libMesh/libmesh/issues/1337) the other day asking if we should upgrade the version.

**Comment by sveerara** [comment]
@jwpeterson is there an example of where it is used in MOOSE?

**Comment by dschwen** [comment]
nanoflann is _not_ approximate though, right?

**Comment by jwpeterson** [comment]
Why would it not be approximate nearest node? It has "ANN" in the name after all...

**Comment by jwpeterson** [comment]
"This library is a fork (and a subset) of the flann library by Marius Muja and David G. Lowe, and born as a child project of MRPT."

**Comment by dschwen** [comment]
https://github.com/jlblancoc/nanoflann/blame/master/README.md#L59

**Comment by jwpeterson** [comment]
I guess I don't understand the nomenclature then. When I use it, I ask for e.g. the closest 3 points. I thought this was what "approximate" referred to.

**Comment by dschwen** [comment]
_Approximate_ nearest neighbor search has a non-zero probability of returning a close second nearest neighbor instead of the first nearest neighbor. Doesn't matter for our application (in fact non-approximate is probably what we want). But the comment in libMesh should be changed.

**Comment by jwpeterson** [comment]
> But the comment in libMesh should be changed.

![fine](https://cloud.githubusercontent.com/assets/1775907/25917845/ac25dbd0-3586-11e7-8ce5-56279c8acb9e.jpeg)

**Comment by dschwen** [comment]
![14944475877461300384190](https://cloud.githubusercontent.com/assets/202302/25919869/500fe58c-358d-11e7-837f-4bf11eaf08b3.jpg)
