### ISSUE TITLE
PorousFlow: move capillary pressure to user objects?

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9105]
### Description of the enhancement or error report
Should the capillary pressure functions in `porous_flow` be moved to user objects?

### Rationale for the enhancement or information for reproducing the error
The capillary pressure can't be there own materials because we end up with a cyclic dependency issue, so we currently have them in a namespace, and have a different pressure-saturation material for each capillary pressure. This is true for the 1 phase, 2 phase and compositional fluid state materials. 

If we want to add another capillary pressure, we then need to add a whole heap of new materials that are basically just copy and pastes of current materials with different capillary pressures (e.g. need a 1 phase, 2 phase PP, 2 phase PS, water-ncg, brine-co2 (which is nearly ready) etc version of the current materials with the new capillary pressure. This seems like a pretty inefficient way to do this.

If the capillary pressure was a user object, we could reduce the number of materials and just swap out use objects in the input file at run-time.

What do you think @WilkAndy?

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Need to change a heap of test input files...

**Comment by WilkAndy** [comment]
It's sort of hard to know what's best without trying some things!  I see your problem about having to create lots of very similar Materials.  The only "problem" i can think of immediately is the input file getting even more obscure.  But i'm quite pleased that my Actions have been able to cover up most of that, so i don't think we should worry too much.
I'm glad you've got water-ncg and brine-co2 by the way!

**Comment by cpgr** [comment]
I've run into this issue again. I'm making an initial condition so that the user can specify pressure and saturation rather than pressure and total mass fraction summed over all phases. Turns out I need the capillary pressure in this IC as well, so now I need to enter capillary pressure in two materials and an initial condition. This seems to be a recipe for input file mistakes, and a good use case for putting capillary pressure into a user object.

I might push ahead with this for the brine-co2 model, and we could support two ways of implementing capillary pressure for a while. I can use the equations in the namespace so there is no real code duplication at least, and if we decide that it is a bad thing to do, we can change it pretty easily.

**Comment by WilkAndy** [comment]
Oh dear, this seems like a mess.  I don't want to have two ways of doing things for very long, if at all.  Of course it's all a tiny bit painful for users when we change something like this, but honestly the pain is over in about minute (much less pain than you rewriting all those test input files!).  I can't see any disadvantages to the UOs, except that initial pain.

Seems like we go around in circles a bit before finding things that work (or work for a while anyway!).

**Comment by cpgr** [comment]
It does feel like that! I can't really think of a better way of doing capillary pressure than a user object (ironically, it is what I had in quoll and what you had in the richards module) so that we don't end up with a heap more materials and having to put things like van Genuchten parameters in several spots in the input file.

**Comment by WilkAndy** [comment]
I'm pretty sure the only reason we (I?) opted for a Material was to attempt to reduce the size of input files.
