### ISSUE TITLE
Peacock loading Exodus file issues

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9111]
### Description of the enhancement or error report

 [ ] - If you launch peacock with an input file and move to the "Exodus Viewer" tab, you cannot load an exodus file without first running the input file.
 [ ] - If you try to load an adaptive Exodus result directly from the command line, nothing happens:
(e.g. `peacock foo.e-s001`)

### Rationale for the enhancement or information for reproducing the error

Information for reproducing is given in the description.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Peacock usability

**Comment by permcody** [comment]
Ping @brianmoose

**Comment by brianmoose** [comment]
`peacock -r foo.e-s001` works as expected.
Without the `-r` flag we just scan the command line arguments looking for `*.e` files.
I guess we can also pick up `*.e-s[0-9]+` files

**Comment by permcody** [comment]
I'd vote for adding the additional re. Either it should work the same way, or we should require people to use flags.
