### ISSUE TITLE
Relaxation For Picard Iteration

### ISSUE THREAD

**Issue by jarons** [idaholab/moose#9115]
### Description of the enhancement
I would like to add a relaxation factor for multi-apps using Picard Iteration. In other words, add code that can change Block Gauss-Seidel into Successive OverRelaxation.
``` 
_u = w * _u + (1 - w) * _u_previous_pic_it
```
where 0 < w < 2. 
I think I can do this with an AuxKernel: Transfer assigns the values to an AuxVar, then use the AuxKernel on timestep_begin to modify the values. I would need to figure out how to store copies of the AuxVar from the previous Picard iteration.
Other approaches might be to modify a Transfer or a UserObject to handle this.
Let me know what you think the best way to accomplish this would be, and I'll give it a try.

### Rationale for the enhancement
For multi-apps coupled with Picard Iteration, this could help improve the convergence rate or stability.
 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Impact varies widely depending on the way it's implemented. If we only need a new AuxKernel, impact is minimal. Otherwise some objects like Transfers/MultiApps/Executioners may need to be modified.

**Comment by friedmud** [comment]
You wouldn't do this with an Auxiliary Kernel... it would just require some normal MOOSE coding.

It would be done similarly to the way Transfer Interpolation is done.  See:

https://github.com/idaholab/moose/blob/devel/framework/src/multiapps/TransientMultiApp.C#L44
https://github.com/idaholab/moose/blob/devel/framework/src/multiapps/TransientMultiApp.C#L126
https://github.com/idaholab/moose/blob/devel/framework/src/multiapps/TransientMultiApp.C#L196

Let me know if you have any questions...
