### ISSUE TITLE
Logic error in ElementLoopUserObject::execute()

### ISSUE THREAD

**Issue by Chuban** [idaholab/moose#9117]
### Error report
While running the CNSFV portion of the NS module with the fluid variables restricted to a subdomain, a runtime error was encountered while switching from a MOOSE generated mesh to one created in CUBIT.  The simulation converged to a solution using the MOOSE generated mesh, but crashed with the CUBIT mesh due to some block restricted user objects failing to initialize correctly.  The error was triggered by the combination of block restricted user objects and the alternate element numbering scheme used by CUBIT.

### Proposed solution
The error has been traced to `ElementLoopUserObject::execute()` in the rDG module.  This function loops over all of the mesh elements and should perform calculations on those elements inside the subdomains to which the user object has been restricted.  If a subdomain check fails, a `break` statement is called, which skips the evaluation of subsequent mesh elements and results in incomplete initialization.  The `break` statement should be changed to `continue` so that all mesh elements are considered.

### Identified impact
This error can prevent rDG module based simulations from running.  The proposed solution is not expected to have any negative impacts.

**Comment by friedmud** [comment]
I concur.
