### ISSUE TITLE
Peacock 2 Execute Font Too Large

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9122]
### Description of the enhancement or error report

The default font for the Execute tab is entirely too large.  It looks out of place compared to the other text on the tab and it shows far too little information.  Compare it to the default terminal font in the following screenshot:

![peacock2_font](https://cloud.githubusercontent.com/assets/870705/26028793/6e6dcbec-37f5-11e7-899c-3abd064abe27.png)

I think it should match the default Terminal font size (10pt).  Apple chose that default for a reason... and most people use it!

### Rationale for the enhancement or information for reproducing the error
Too little information displayed while executing

### Identified impact
Better usability.

**Comment by brianmoose** [comment]
We are using the default font for Qt. We use `<pre></pre>` for the execute output which uses a monospace font, which seems to be larger than the regular font. We can certainly hard code a smaller font size or even have it as a preference.

**Comment by friedmud** [comment]
A preference would be nice but I also think the default should be smaller.
On a laptop you can't see much of the log at all currently.

**Comment by permcody** [comment]
Closed by #9177 (User can control the size via preference)
