### ISSUE TITLE
Documentation: LaTeX subscripts in references not rendering on website

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9139]
### Description of the enhancement or error report
Subscripts in BibTeX references are not being rendered properly - e.g.: H$_2$O in a article title should be displayed as H<sub>2</sub>O but are being displayed as the raw LaTeX `H$_2$O`. See #9127 for example

### Rationale for the enhancement or information for reproducing the error
Make the references look better

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Better readability

**Comment by aeslaughter** [comment]
Super/sub scripts are now directly exist in MooseDown.
