### ISSUE TITLE
Deprecate Richards module

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9159]
### Description of the enhancement or error report

Deprecate entire Richards module.

### Rationale for the enhancement or information for reproducing the error

I think it is superseded by the PorousFlow module.  Here are some thoughts from Cody:

1) Remove Richards from the ALL_MODULES := yes target in the makefile to stop compiling it into people's application immediately
2) Adjust "make test_subs" so that CIVET quits looking at testing the module
3) Put a big red warning in the constructor of the RichardsApp to tell people that it's deprecated and not supported

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by WilkAndy** [comment]
i realised i can't remove Richards completely as the BaHun App depends on it, and that is still being actively run.

**Comment by brianmoose** [comment]
Another thing worth checking is making sure `modules/run_tests` still works. It uses the executable in `modules/combined` to run any tests it can find under `modules`, including any tests under `richards`. If the richards module is not compiled into combined, tests under `richards` will likely fail.

**Comment by permcody** [comment]
Yes, definitely!

**Comment by WilkAndy** [comment]
Thanks @brianmoose for the tip about run_tests

a

**Comment by WilkAndy** [comment]
I'm closing this issue because i don't think Richards can be realistically removed for another year or so.  It's still being used by people here at CSIRO and elsewhere.
