### ISSUE TITLE
Requested features, bugs, and nitpicks for documentation system

### ISSUE THREAD

**Issue by tolman42** [idaholab/moose#9162]
### Description of the enhancement or error report

* Remove the macro feature and change the associated error message to let users know that macros aren't supported.
* More specific error message for when the executable listed in app_syntax.yml doesn't exist.
* BISON docs don't link correctly to MOOSE source code when MOOSE subobjects are referenced.
* Using inline math in article titles in bibtex files don't render correctly in the generated html bibliography
* Term search functionality
* The tilde comes out weird when generating pdf's

### Rationale for the enhancement or information for reproducing the error

As I move old BISON documentation into the new system, I encounter a number of bugs and/or nitpicks that aren't vital to the function of the system as a whole since I find small workarounds.  But they are things that would be nice to have addressed eventually.  I'm using this issue as a place to keep a list of such as they pop up and are taken care of. 

Also, I get feature requests from the team every now and again.  Again, nothing vital, but small things that would improve the experience for everyone.

The list is roughly in order of most important to least important.

### Identified impact

Only the documentation system.

**Comment by aeslaughter** [comment]
> Be able to reference tables

This already works.

> The image/figure feature doesn't work with pdf's.

As far as I know html cannot render pdfs, this would require some sort of plugin.

**Comment by aeslaughter** [comment]
Closing, I would like specific tickets for MooseDocs related tasks moving forward. I am considering the basic system complete at this point, so future work should be targeted and have a associated issue.
