### ISSUE TITLE
Are the custom_partitioner tests supposed to work on more than 2 procs?

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9182]
### Description of the enhancement or error report

```for num in $(seq 1 24); do METHOD=dbg ./run_tests -p $num --re 'mesh/custom_partitioner.custom_linear_partitioner$' || break; done```

Breaks for me as soon as it gets to 3 processors.  It took me a while to discover that this breaks even when I'm not forcing --distributed-mesh.

In the tests file it seems to be allowing anywhere from 2 to 4 processors to run this test?  How can that possibly work, when the test is comparing processor_id() values against a gold standard that has a 2-processor partitioning hard coded?

**Comment by permcody** [comment]
That sounds wrong to me. Partitioning is kind of based on the number of
processors ;) Probably should be locked to exactly two. I didn't make that
test but it's probably just a mistake.
