### ISSUE TITLE
compute gradient and vectorValue in LinearCombinationFunction

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9186]
### Description of the enhancement or error report

Currently LinearCombinationFunction only computes the "value".  Enhance it to combine the "gradient" and "vectorValue" too.

### Rationale for the enhancement or information for reproducing the error

Is there something wrong with this proposal?  I think i'm missing something!

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by andrsd** [comment]
> Is there something wrong with this proposal?

No. It should be possible, `gradient` and `vectorValue` are both defined in `Function`. Probably add a MooseEnum that will determine what should be combined. Its default should be `value`, unless you want to update everyone's input file :-)
