### ISSUE TITLE
PorousFlow: negative saturation in theis test with brine-co2

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9192]
### Description of the enhancement or error report
I noticed that when the amount of CO2 injected in `theis_brineco2.i` is enough to form a gas phase, the first saturation reported is negative - see https://github.com/idaholab/moose/blob/devel/modules/porous_flow/tests/fluidstate/gold/theis_brineco2_csvout.csv

After checking the code to make sure that negative saturations are not possible (they aren't), I tracked it down to the choice of `AuxVariable` for saturation. Specifically, using a `FIRST` order monomial with a `PointValue` postprocessor seems to be the culprit here - even though gas saturation is always positive, this reports a small negative value at the chosen point.

### Rationale for the enhancement or information for reproducing the error
Negative gas saturation is not physical - even though the code didn't provide a negative saturation, using a `FIRST MONOMIAL AuxVariable` with a `PointValue postprocessor` at this point gives a negative saturation.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Make the resulting `csv` data look correct

**Comment by cpgr** [comment]
I'll fix this tonight - might have to play around a bit to make sure that the sampled output is "more correct"

**Comment by cpgr** [comment]
Hmm, I want to output values of an elemental auxvariable along a line, but using a biased mesh means that I am doubling up sampling some elements, making the plot look like a staircase when using constant monomials. I think I need something like an elemental value vectorpostprocessor. Like an elemental variable equivalent to `nodalvaluesampler`.

**Comment by permcody** [comment]
I don't think having a biased mesh has anything to do with it. If you are sampling monomials won't you always have a staircase effect?

**Comment by cpgr** [comment]
I'll get a staircase using constant monomials if I sample the same element more than once - e.g.
![block](https://cloud.githubusercontent.com/assets/7664823/26662995/318e8bf0-46cb-11e7-8605-6f304a0a7a15.png)

This must have been why I used first order monomials originally - the plot is smooth then
![smooth](https://cloud.githubusercontent.com/assets/7664823/26663026/5e7afeb4-46cb-11e7-82a9-42950111dd09.png)

But you can see the artefact where saturation drops below zero. I haven't come up with a robust way of getting these plots using elemental aux variables. I'm thinking it might be best to remove that output and just test the similarity solution on the nonlinear variables - if that works then it follows that the other derived properties will too.
