### ISSUE TITLE
EigenProblem failures on steady problems

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9196]
### Description of the enhancement or error report

NonlinearEigenSystem::solve() attempts to use a time integrator which, for steady problems, is NULL; this may segfault or may throw an exception depending on build configuration.

### Rationale for the enhancement or information for reproducing the error

```METHOD=dbg ./run_tests --re problems/eigen_problem``` on a system configured with SLEPc will result in two failures.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This is probably fixable internally by copying the idiom in use in NonlinearSystemBase; I'll try that out now.

Someone should probably enable SLEPc on the Civet builds, so this stuff doesn't regress again in the future.

**Comment by permcody** [comment]
Tag @brianmoose and @milljm and @fdkong
