### ISSUE TITLE
Fixup Module App Directory Naming With stork.sh

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9206]
### Description of the enhancement or error report

When using `stork.sh` to generate a new module with multiple words it doesn't name the directory correctly.  As an example I just tried to create a module like so:

```bash
scripts/stork.sh module RayTracing
```

Which creates `modules/raytracing`... but it should really create `modules/ray_tracing`.  We just need to find the camel-case letters and put underscores in there.

### Rationale for the enhancement or information for reproducing the error
Try the above command

### Identified impact
Just more consistency in directory generation

**Comment by permcody** [comment]
There is a utility for doing camel case to underscores and back again in MooseUtils.

**Comment by friedmud** [comment]
Unfortunately, stork.sh is a Bash script... so it's going to need to be
done with awk or sed...

**Comment by permcody** [comment]
Or perl ;)
