### ISSUE TITLE
stork.sh broken when creating modules

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9207]
### Description of the enhancement or error report
Something is up with `stork.sh` when creating a module.  It creates most things correctly... but completely forgets the `include/base/WhatevsApp.h` file!

### Rationale for the enhancement or information for reproducing the error
Just try to create a new module.

### Identified impact
It will work.

**Comment by friedmud** [comment]
I'm going to fix this up right now

**Comment by friedmud** [comment]
Wait: this looks intentional.  But why?  The module doesn't work without this file!

@rwcarlsen any comment on:

https://github.com/idaholab/moose/blob/devel/scripts/stork.sh#L83

Can't understand why we would remove that...

**Comment by rwcarlsen** [comment]
[facepalm]
