### ISSUE TITLE
Resizing your browser can make MooseDocs toolbar render incorrectly

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9210]
### Description of the enhancement or error report

If you size down your webpage just a little (somewhere between 1/2 and 3/4 of my laptop screen) the text on the top will wrap down into the whitespace below making the menus invisible. This isn't ideal for navigation.

### Rationale for the enhancement or information for reproducing the error

Just size your browser down a little bit.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Moose Docs usability

**Comment by dschwen** [comment]
FYI the mobile version of the doc page is currently unusable (no navigation elements) at all.

**Comment by aeslaughter** [comment]
The real fix for this might be to move to Bootstrap, which shouldn't be too much work.

**Comment by brianmoose** [comment]
Yeah, I think bootstrap is much better than materialize at being responsive.

**Comment by permcody** [comment]
Closed by #10244
