### ISSUE TITLE
Check for an unknown prereq (cyclic dependency)

### ISSUE THREAD

**Issue by milljm** [idaholab/moose#9224]
### Description of the enhancement or error report
We need a check for a missing prereq in the test file (typos etc). Currently, TestHarness bombs out, instead of proceeding to labeling this test as failed due to a cyclic dependency.

### Rationale for the enhancement or information for reproducing the error
We are raising an exception instead of properly handling this error.

### Identified impact
None

**Comment by permcody** [comment]
Well that's because that new method was running after instead of before the
actual run test. This is a new bug ;)

**Comment by milljm** [comment]
Sweet! =D

**Comment by permcody** [comment]
Tag @milljm  - This is fixed in the new TestHarness - however we need a unit test for it. Let's leave this open until there's a test to prevent a regression.

**Comment by permcody** [comment]
Closed by #9225
