### ISSUE TITLE
Use kd-tree for k nearest neighbor search in contact search algorithm

### ISSUE THREAD

**Issue by sveerara** [idaholab/moose#9246]
### Description of the enhancement or error report

Use kd-tree for k nearest neighbor search in contact search algorithm instead of naive compare-each-with-each approach.

### Rationale for the enhancement or information for reproducing the error

Kd-trees are more efficient for calculating neighbors for multiple slave nodes from a master node set. The nanoflann library in Libmesh can be used to replace the existing k nearest neighbor search in `NearestNodeLocator.C` and `SlaveNeighborhoodThread.C`

### Identified impact

Faster determination of neighbors

**Comment by permcody** [comment]
Closed by #9247,
