### ISSUE TITLE
Allow comments in csv data files for DelimitedFileReader

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9284]
### Description of the enhancement or error report
Addition to DelimitedFileReader to ignore comments at the start of a data file

### Rationale for the enhancement or information for reproducing the error
It is sometimes useful to have some meta data in data files that might be read by DelimitedFileReader that provides some information about the data. It would be nice if DelimitedFileReader could ignore some comment lines at the start of the file.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Additional feature

**Comment by permcody** [comment]
@aeslaughter

**Comment by aeslaughter** [comment]
What should the comment symbol be?

**Comment by cpgr** [comment]
How about something simple like

      ___            ___
     /   \          /   \   
     \_   \        /  __/
      _\   \      /  /__
      \___  \____/   __/   This is a comment
          \_       _/
            | @ @  \_
            |
          _/     /\
         /o)  (o/\ \_
         \_____/ /
           \____/

**Comment by permcody** [comment]
Lol

**Comment by rwcarlsen** [comment]
How about ``#`` - same as python, getpot, bash, etc.  Do we ignore them everywhere?  What about inline comments?

**Comment by permcody** [comment]
closed by #9791.
