### ISSUE TITLE
PorousFlow failures on pearcey.hpc.csiro.au

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9286]
### Description of the enhancement or error report

Tagging @cpgr .   These aren't disastrous, but let's fix them:

wil04q@pearcey-login:~/projects/moose/modules/porous_flow/tests/fluidstate> ../../porous_flow-opt -i theis_tabulated.i 
<snip>
*** ERROR ***
The number of columns read (0) does not match the number of columns expected (1) based on the first row of the file when reading row 2 in file fluid_properties.txt.

jacobian/heat_advection01.i   should have its tol set to >1.32932e-07

jacobian.waterncg_liqiud gives the following error:
jacobian.waterncg_liqiud: Testing hand-coded Jacobian, if the ratio is
jacobian.waterncg_liqiud: O(1.e-8), the hand-coded Jacobian is probably correct.
jacobian.waterncg_liqiud: Run with -snes_test_display to show difference
jacobian.waterncg_liqiud: of hand-coded and finite difference Jacobian.
jacobian.waterncg_liqiud: Norm of matrix ratio 75.2202 difference 3954.85 (user-defined state)
jacobian.waterncg_liqiud: 
jacobian.waterncg_liqiud: 
jacobian.waterncg_liqiud: 
jacobian.waterncg_liqiud: 
jacobian.waterncg_liqiud: *** ERROR ***
jacobian.waterncg_liqiud: Pressure -1 is out of range in Water97FluidProperties::inRegion
jacobian.waterncg_liqiud: 
jacobian.waterncg_liqiud: 

jacobian.brineco2_liquid gives the following error:
jacobian.brineco2_liquid: Testing hand-coded Jacobian, if the ratio is
jacobian.brineco2_liquid: O(1.e-8), the hand-coded Jacobian is probably correct.
jacobian.brineco2_liquid: Run with -snes_test_display to show difference
jacobian.brineco2_liquid: of hand-coded and finite difference Jacobian.
jacobian.brineco2_liquid: Norm of matrix ratio 9.3621 difference 617.084 (user-defined state)
jacobian.brineco2_liquid: 
jacobian.brineco2_liquid: 
jacobian.brineco2_liquid: 
jacobian.brineco2_liquid: 
jacobian.brineco2_liquid: *** ERROR ***
jacobian.brineco2_liquid: Parameters out of range in CO2FLuidProperties::rho
j
### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by cpgr** [comment]
Haha - look at the norm of matrix ratios!

The tabulated properties one will be a stale file data file hanging around, as I recently changed the file parsing. I'll investigate the jacobians - was this compiled using intel?

**Comment by WilkAndy** [comment]
no, this was compiled using

/apps/gcc/4.9.3/bin/gcc

but Ondrej (computer guy) said he used his custom intel-mkl and other custom stuff.

**Comment by cpgr** [comment]
I rebuilt everything on pearcey using both intel 16.0.1.150 and gcc 4.9.3 (that took a long time!), and all of the tests passed.

I can see how the tabulated properties test would fail, however, if there was an old properties file there. I'll put in a PR now to add a properties file, forcing the test to run with the newer csv format, which will fix this problem.

**Comment by WilkAndy** [comment]
Hmmm, what modules did you have loaded?  Ondrej and I have been building moose for about a week, trying different libraries and so on.

**Comment by cpgr** [comment]
For intel:

    intel-mkl/11.3.2
    intel-cc/16.0.1.150
    intel-fc/16.0.1.150
    openmpi/1.8.8-mellanox

For gcc:

    gcc/4.9.3
    openmpi/1.8.8-mellanox-gcc

**Comment by WilkAndy** [comment]
how about a petsc module?

**Comment by cpgr** [comment]
This might be it - I had previously built petsc 3.6.4 for testing and it looks like lib mesh built against that. I'm rebuilding with one of the petsc modules now. I'll let you know if it makes a difference.

**Comment by cpgr** [comment]
Ok, if I build with the `petsc/3.5.2-gcc-mpi-opt` module, I get these failures (and another one as well - `poro_elasticity.pp_generation` diffs due to different csv file lengths).

**Comment by cpgr** [comment]
Looks like it is the finite differencing in this case: adding `-mat_fd_type ds` gives:

- jacobians/waterncg_liquid
`Norm of matrix ratio 6.20304e-06 difference 0.000326137 (user-defined state)`

- jacobians/brineco2_liquid
`Norm of matrix ratio 5.1846e-07 difference 3.41733e-05 (user-defined state)`

- jacobians/heat_advection01
`Norm of matrix ratio 2.86425e-08 difference 9.22605e-08 (user-defined state)`

**Comment by cpgr** [comment]
It looks like petsc switched the default value of `-mat_fd_type` from `wp` to `ds` somewhere between 3.5.2 and 3.6.4

**Comment by WilkAndy** [comment]
oh, that's interesting. i'd prefer to change the expected norms to be a bit bigger, at least for the heat_advection01 case rather than running with -mat-fd-type=ds because that looks bodgy to me.

**Comment by WilkAndy** [comment]
To close off this issue, do you want to run those two Jacobian tests with a specific -mat_fd_type , @cpgr ?

**Comment by cpgr** [comment]
I have switched back to Petsc 3.6.4 so can't test these atm to make sure that they work. Does adding -mat_fd_type ds make them pass for you?

**Comment by WilkAndy** [comment]
Yea, i also needed to change the tolerance on waterncg.  I'll put in a PR and let you review.

a

**Comment by cpgr** [comment]
I had another thought. Does adding `scaling=1e6` to the `z` variable improve this? It could be due to the really small values of `z` used in the initial condition to make sure that it is only in the liquid phase is making it hard for the finite difference jacobian to be accurately calculated

**Comment by WilkAndy** [comment]
I tried different "scaling" values for z, but it didn't make any difference.

**Comment by WilkAndy** [comment]
Thanks @cpgr - Jacobian works on Pearcey for me now
