### ISSUE TITLE
Tensor mechanics thermal expansion stress free temperature

### ISSUE THREAD

**Issue by reverendbedford** [idaholab/moose#9291]
### Description of the enhancement or error report
If stress_free_temperature is not specified in the solid mechanics kernel it defaults to the initial temperature field.  This could be some non-uniform temperature field.

Tensor Mechanics requires the definition of some constant stress_free_temperature field.

I would like a way to define a non-uniform stress free temperature at the start of a simulation, either through the solid mechanics behaviour or by allowing the user to specify an interpolation function for the stress-free temperature.

### Rationale for the enhancement or information for reproducing the error
I have simulations that start off with a non-uniform temperature field and I would like to have the simulations start at zero eigenstrain.

### Identified impact
I'm still learning the code base, but it may be a simple change to ComputeThermalExpansionEigenstrainBase.

**Comment by dschwen** [comment]
We could allow passing in an AuxVariable for `stress_free_temperature` (which could be set to the temperature in an AuxKernel that runs on `initial` only).

**Comment by bwspenc** [comment]
I think @dschwen's suggestion is a reasonable way to go about this.

**Comment by reverendbedford** [comment]
Ah well I should have checked the thread before I started coding, but they'll be a pull request in a second here implementing the solid mechanics behaviour (if you don't give a stress_free_temperature it will use the initial temperature field).  That covers my case, I don't know if there's a need or interest in having a completely arbitrary reference temperature, separate from the initial temperature field.

**Comment by bwspenc** [comment]
I never liked how solid_mechanics defaulted to using the initial temperature by default because it wasn't explicitly clear what was going on from the input file. I'd like to see that you have to explicitly ask for that behavior somehow if you want it.

**Comment by bwspenc** [comment]
Also, I haven't looked at your code yet, but the way tensor_mechanics has thermal strains implemented, it always computes the total thermal strain, rather than the incremental thermal strain (as is done in solid_mechanics).  That means that you would have to have the initial temperature stored in a way that can be retrieved at every quadrature point at any time in the analysis (probably using an AuxVariable).

**Comment by dschwen** [comment]
Yeah, agreed. But this would come out of the proposed design automatically, because the user will have to set up an AuxVariable and an AuxKernel explicitly to get this behavior. The _only_ change necessary in `ComputeThermalExpansionEigenstrainBase` is to change the `addParam<Real>` to an addCoupledVar` (and change, member  and access (add `[_qp]`) accordingly).

**Comment by bwspenc** [comment]
Perfect.  That sounds like a good solution.

**Comment by reverendbedford** [comment]
New pull request incoming with this solution implemented.  The new keyword to the thermal expansion materials based off ComputeThermalExpansionEigenstrainBase is "stress_free_aux", the name of the aux variable with the stress free temperature.

You can use it as:
      [./thermal_strain]
            type= ComputeThermalExpansionEigenstrain
            thermal_expansion_coeff = 2.11E-5
            temperature = T
            eigenstrain_name = eigenstrain
            stress_free_aux = stressfree
      [../]

      [./stressfree]
            order = CONSTANT
            family = MONOMIAL
      [../]

With, for example, one of:

      [./set_stress_free]
            type = ConstantAux
            value = 600.0
            variable = stressfree
      [../]
      
      [./set_stress_free]
            type = FunctionAux
            function = varied_temps
            variable = stressfree
      [../]

      [./set_stress_free]
            type = ParsedAux
            variable = stressfree
            args = 'T'
            function = 'T'
            execute_on = initial
      [../]

Is there an easier way of doing the last one, for my information?  I feel like there should be an easier way to set an AuxVariable to a variable value.

The first pointlessly gives you the old behaviour with the new method.  I left the old stress_free_temperature scalar parameter in the material and if you provide both it and stress_free_aux it will default to the old behaviour and ignore the AuxVariable.

**Comment by dschwen** [comment]
Reverend, see my comments on the PR we do not need a new parameter for this. Also, you should not be using a CONSTANT/MONOMIAL AuxVariable here, it needlessly reduces the fidelity.
