### ISSUE TITLE
Rejig tabulated fluid properties tests to delete generated csv files

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9307]
### Description of the enhancement or error report
To make the tabulated fluid property tests more robust, delete the generated csv files before running the tests to ensure that no stale files are present once #9304 has been addressed.

### Rationale for the enhancement or information for reproducing the error
As the file format was changed, some tests may fail if an old property file is present, as the reader will attempt to read them in. To make the testing robust, we can delete these files before running the tests.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Improve test robustness

**Comment by GiudGiud** [comment]
The new design does not exhibit this problem anymore. It does not rely on saving / reading with the same file name

Closed by #28021
