### ISSUE TITLE
--dump [SearchString] option no longer works

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9316]
### Description of the enhancement or error report

It appears that the SearchString option no longer works in conjunction with the `--dump` CLI option. I believe this was broken somewhat recently with the formatting changes of the object names.

### Rationale for the enhancement or information for reproducing the error

Try running `./moose_test-opt --dump SimpleDiffusion`, nothing is printed. It used to print only sections matching the pattern given on the command line. Without this functionality, users have to grep through the output which can be annoying when they know the name of the object they want.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Useability

Tag @brianmoose

**Comment by permcody** [comment]
Nevermind, SimpleDiffusion isn't an object - I know that, but my use case was faulty. I was trying to dump an intermediate class that **wasn't** registered

**Comment by friedmud** [comment]
This ticket is :1st_place_medal: 

😆

**Comment by permcody** [comment]
Easy mistake, once you get into the modules there are lots of intermediate classes that look like objects you might put in an input file but they aren't registered. In trying to reproduce I used SimpleDiffusion which was really dumb... Oh well.
