### ISSUE TITLE
We need phase field actions that create variables and corresponding kernels

### ISSUE THREAD

**Issue by tonkmr** [idaholab/moose#9336]
### Description of the enhancement or error report
When a user creates a new variable on either conserved type or noncoserved type for a standard phase field model, the corresponding kernels are always the same. We can automate this addition to make things easier on the user.

### Rationale for the enhancement or information for reproducing the error
These actions will simplify syntax and reduce the complexity for new users. Advanced users or advanced models could still use the standard syntax. This will be especially useful for conserved variables because we can automate the choice between a direct solve and a split solve.

### Identified impact
2 new actions will be created (one for conserved and one for nonconserved). These actions will not be required and all old syntax will still function the same.

**Comment by tonkmr** [comment]
I plan to work on this

**Comment by dschwen** [comment]
The problem with split vs. non split is that the tone kernels are on different variables, so source, sink, or reaction kernels need to be on different variables as well.

**Comment by tonkmr** [comment]
My plan is to first implement these the way we currently do things. Any additional terms (sources, sinks, etc), will be added using the kernel block in the usual way and we will just have to tell the user that they need to do all terms that modify cdot equation with variable = chemical potential.

However, I also plan to see if we still need to reverse the equations for the solve to work. If we don't, then we can switch it.

**Comment by dschwen** [comment]
Yes, I was wanting to investigate that well (reversal). By the way, why are we always using third order hermite for the non split and never second order Lagrange?

**Comment by tonkmr** [comment]
If I remember correctly, second order doesn't actually give you access to the second order derivatives of the shape functions. The third order hermites were the only option that provided what we needed.

**Comment by dschwen** [comment]
I'll check that. Second order Lagrange also needs a mesh with second order elements. Maybe that was not easily available back in the day. Now we have `second_order = true`

**Comment by dschwen** [comment]
Yeah, I cannot get that to converge after the second timestep (modified `moose/modules/phase_field/examples/cahn-hilliard/Parsed_CH.i`). Maybe @jwpeterson can chime in?

**Comment by dschwen** [comment]
(I learned something today) Continuity is required. Lagrange has C<sup>1</sup>, but we need C<sup>2</sup>. Otherwise the existence of a solution is not guaranteed. I ran into that in #9329, too

**Comment by permcody** [comment]
Well only if you are a Fortran programmer... Lagrange is C0 and Hermites
are C1.
