### ISSUE TITLE
hidden stuff in PhaseField Polycrystal

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9345]
### Description of the enhancement or error report

My compiler gives:

> In file included from /home/wil04q/projects/moose/modules/phase_field/include/userobjects/PolycrystalVoronoi.h:10:0,
                 from /home/wil04q/projects/moose/modules/phase_field/include/userobjects/PolycrystalHex.h:10,
                 from /home/wil04q/projects/moose/modules/phase_field/src/base/PhaseFieldApp.C:218:
/home/wil04q/projects/moose/modules/phase_field/include/userobjects/PolycrystalUserObjectBase.h:62:16: warning: âvirtual libMesh::Real PolycrystalUserObjectBase::getVariableValue(unsigned int, const libMesh::Node&) constâ was hidden [-Woverloaded-virtual]
   virtual Real getVariableValue(unsigned int op_index, const Node & n) const
                ^
In file included from /home/wil04q/projects/moose/modules/phase_field/include/userobjects/PolycrystalHex.h:10:0,
                 from /home/wil04q/projects/moose/modules/phase_field/src/base/PhaseFieldApp.C:218:
/home/wil04q/projects/moose/modules/phase_field/include/userobjects/PolycrystalVoronoi.h:26:16: warning:   by âvirtual libMesh::Real PolycrystalVoronoi::getVariableValue(unsigned int, const libMesh::Point&) constâ [-Woverloaded-virtual]
   virtual Real getVariableValue(unsigned int op_index, const Point & p) const override;
                ^

Please just close this issue if this is intentional.  (I won't be fixing it - i have no idea what PolyCrystal is supposed to do.)

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
Thanks! This actually does need to be fixed. I'll submit a patch.
