### ISSUE TITLE
SideAverageValue postprocessor reports nan along y-axis boundary

### ISSUE THREAD

**Issue by sapitts** [idaholab/moose#9352]
### Description of the enhancement or error report
In RZ simulations the post processor `SideAverageValue` reports `nan` when the boundary being queried is along the y-axis (x=0).  In these cases the `_coords` value, which is used to calculate the side volume, is zero ([ln 723](https://github.com/idaholab/moose/blob/devel/framework/src/base/Assembly.C#L723) ). @permcody and/or @andrsd would you take a look at this input file and point me in the correct direction to fix this behavior please?

### Rationale for the enhancement or information for reproducing the error
 The attached input file, created within the heat_conduction module, demonstrate the nan values seen when applying SideAverageValue to the centerline boundary in an RZ geometry.  The temperature nodal value at a node along the centerline is also included as a post processor to demonstrate that the temperature is correctly calculated.
[centerlinetemp_rz.i.zip](https://github.com/idaholab/moose/files/1089837/centerlinetemp_rz.i.zip)

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Ability to query field values along the center axis of RZ simulations, e.g.  centerline temperature in BISON simulations

**Comment by YaqiWang** [comment]
I think this behavior is desired. Side is in a dimension of mesh dimension minus one, thus the area of a center-line side is indeed zero...
We could add a parameter `on_axiasymmetric_line` default to false in SideIntegralPostprocessor to remove the coordinate factor at https://github.com/idaholab/moose/blob/devel/framework/src/postprocessors/SideIntegralPostprocessor.C#L64
You will need to assure the coordinate is RZ when this parameter is set to true. But this parameter changes the meaning of side...

**Comment by permcody** [comment]
@sapitts, we had a discussion here in the MOOSE cube. We believe Yaqi is correct. With the RZ coordinate system, we are calculating an area here, not a length as you might expect. The area of that sweep would be zero because the radius on the axis is zero. The length would be non-zero and I guess that's what you are expecting here. Stop in and lets talk about options for getting what you need. We'd like to avoid creating RZ specific objects (we've been down that road before).

**Comment by andrsd** [comment]
@YaqiWang Your proposed solution is not going to fix it - it is just fixing it partyl. @sapitts is using SideAverageValue, so that would need a fix in `::volume()` so it is not using `_current_side_volume` but the element length. That's what gives her that NaN, the PPS divides by zero in the end computation of the average...

**Comment by sapitts** [comment]
We'd like to be able to use some method to pull the average temperature along the centerline in RZ and 1.5D simulations. I'm stuck on the proper way to reconcile the need to calculate a length while not creating an RZ specific object. I'll stop by to ask for help in person after I get out BISON training this afternoon

**Comment by jasondhales** [comment]
See AxisymmetricCenterlineAverageValue.  Kyle added this a while back.

**Comment by sapitts** [comment]
Wonderful!  thanks!

**Comment by permcody** [comment]
We should consider making this automatic (i.e. merging these two objects). This is definitely a special case that arises because of the coordinate transformation and we've worked to remove all of those from MOOSE and the modules.

**Comment by sapitts** [comment]
Looks like I'd have to overwrite the `computeIntegral` method in `SideIntegralPostprocessor`, ([ln 60](https://github.com/idaholab/moose/blob/devel/framework/src/postprocessors/SideIntegralPostprocessor.C#L60)) and then add in the check on the coordinate system with the `computeIntegral` implementation in `AxisymmetricCenterlineAverageValue`, ([ln 40] (https://github.com/idaholab/moose/blob/devel/framework/src/postprocessors/AxisymmetricCenterlineAverageValue.C#L40)).  Is that what you had in mind @permcody ?

**Comment by permcody** [comment]
I'm not sure. As you've already pointed out, you'll get a value when the radius != 0, and that value even makes sense. I think we'd need a flag to say whether you wanted a "length" or "surface" value here.

**Comment by friedmud** [comment]
I think I would vote for being able to override the coordinate system per
MOOSE object.  So you could say "coord_sys = XYZ" in this object's block
and it would be treated as if it were in an XYZ coordinate system instead
of whatever the global coordinate system is set to.

Could be generally useful.

Derek

**Comment by andrsd** [comment]
Hello to `CoordinateInterface` 😄

**Comment by permcody** [comment]
Useful maybe but fraught with logical errors. What would it mean to say your materials were RZ but your kernels were Cartesian? Would the user assume that we were only computing one plane of materials? It seems like the bizarre combinations could really add up when you start coupling systems to one and other. 

Yes that would solve this particular problem, but I'm not sure I'm buying into the override idea. I think the reason this is logically difficult to reason about is that these coordinates effectively change the notion of dimension.

**Comment by friedmud** [comment]
What do you mean?  Firstly, Materials don't have anything to do with coordinate systems.  The only objects that do anything with coordinate systems are objects that _integrate_ values (Kernels, Postprocessors, some UserObjects, elemental AuxKernels, etc.).

This option would be no different from `use_displaced_mesh`.  Yep: you can screw it up.  Yep: you can get it wrong.  Just don't do it.  It will be marked as `Advanced`... and we'll add documentation that explains what it does.  It's up to people not to do anything stupid.

We could name it `advanced_coordinate_system_override_only_do_this_if_you_really_know_you_need_to`

**Comment by permcody** [comment]
Yeah - I know you are only screwing with the coordinate multiplier for the integral. It just seems like a weird concept because I try to picture what changing the coordinate override would mean physically (like acting in 2D vs 3D).

**Comment by friedmud** [comment]
Well: it would look like exactly what we want in this case: a line integral
instead of a surface integral...

**Comment by YaqiWang** [comment]
Most combinations of `Problem/coord_sys` and object coord_sys are not valid.

**Comment by friedmud** [comment]
It all depends on what you're up to.  Like in this case: it would feel "wrong" to integrate a SideAverageValue PP in XYZ... but it's _not_.

Same could happen in Spherical at the center.

I could dream up many other scenarios.  Again, it's just like `use_displaced_mesh`.  It often "feels" wrong to have a mix of objects using/not-using the displaced mesh... but sometimes it makes sense.

**Comment by permcody** [comment]
I'm not arguing against this case. I'm just arguing against adding the ability to override this in all integral type objects.

**Comment by andrsd** [comment]
That's why we'd use the interface and add it to just user objects first. Later, we could add it to other systems if we found a use for it...
