### ISSUE TITLE
Minor clean up in fluid_properties

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9353]
### Description of the enhancement or error report
Fix a number of typos, missing class descriptions, etc in the `fluid_properties` module

### Rationale for the enhancement or information for reproducing the error
Reduce typos and inconsistencies in the `fluid_properties` module

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
None really

**Comment by cpgr** [comment]
@andrsd, I'm fixing a number of documentation typos etc in the fluid properties that I have written, and noticed that there are some unimplemented functions without a return, and some with. For example:
````
Real foo(Real p)
{
mooseError("Not implemented");
}
````
compared to
````
Real foo(Real p)
{
mooseError("Not implemented");
return 0;
}
````

Is there a preference? Obviously the `return` is never reached, so should I remove them to make it consistent?

**Comment by permcody** [comment]
Do not put the return statement in. We've marked `mooseError()` with the special `[[no return]]` attribute so the compiler knows that flow control isn't returned. That makes the return unreachable and the compiler can/will complain about that under certain configurations (e.g. static analysis).

**Comment by cpgr** [comment]
Thanks Cody, I'll remove the unused return statements in these user objects
