### ISSUE TITLE
run_tests with check-input

### ISSUE THREAD

**Issue by gardnerru** [idaholab/moose#9359]
### Description of the enhancement or error report
Recently the --check-input flag was added to the run_tests script. If you run run_tests --check-input the script does indeed only run items that have check_input = true in the test file, but if you run run_tests without options it will run the tests and the syntax check. Would it be possible to only run check-input when it is called?
 
### Rationale for the enhancement or information for reproducing the error
I tested this Jun 21 with moose sha c3b2aba26d (built with bison sha 6464a62816c).

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

It takes a bit more time to complete the run_tests script but more importantly for anyone that is running the script for testing with PBS, an extra folder is created for the testing output. It becomes annoying when someone is looking through the results.

**Comment by permcody** [comment]
I think I'd rather run everything as the default. However, since you are scripting this anyway how 'bout another parameter to explicitly turn it off? --no-check-input, or --check-input=false?

**Comment by gardnerru** [comment]
oohhh I can get behind that.

**Comment by permcody** [comment]
Tag @milljm
