### ISSUE TITLE
MeshModifier to add face elements along side sets

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9371]
### Description of the enhancement or error report
Add lower dimensional elements along the faces of a chosen sideset.

### Rationale for the enhancement or information for reproducing the error
Easy setup of meshes to couple mixed dimensional problems.

### Identified impact
Added capability.

**Comment by friedmud** [comment]
We may be able to reuse / repurpose some of the code from `libMesh::BoundaryInfo::sync`: https://github.com/libMesh/libmesh/blob/bb0d1e4851df123b32cbefdb9ef114a504b30831/src/mesh/boundary_info.C#L171

**Comment by dschwen** [comment]
How about 861d057 ? As I mentioned on the ML, I think I implemented almost this in `MortarPeriodicMesh` already. 

P.S.: I'm in a talk, so this is completely untested.

**Comment by friedmud** [comment]
Great idea using build_side ! Wish I had thought of that!

Now - any ideas on how to do sidesets on the lower dimension surfaces?
