### ISSUE TITLE
FEProblemBase::_current_boundary_id is not thread safe

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9372]
### Description of the enhancement or error report

`FEProblemBase::_current_boundary_id` is not thread safe but it is available for use in many `BoundaryRestrictable` objects. There is only a single copy of this member but it is set from the threaded compute loops. Looks like this was added back in 2014 as "active boundary id".

### Rationale for the enhancement or information for reproducing the error

This very old ticket can reproduce this issue:
https://github.com/idaholab/moose/issues/2906

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This is a public member so it could potentially be several objects, but we aren't seeing these with our test suite now. I'll attempt to survey the getter to see if it's widespread.

**Comment by permcody** [comment]
Looks like `_current_boundary_id` is only being used in moose_test objects. That means we can just rip this out rather than fix this.

**Comment by friedmud** [comment]
Just... wow. Rip it out!
