### ISSUE TITLE
Ability to unhide syntax from the commandline in moosedocs.py

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9383]
### Description of the enhancement or error report
Until all `hide` statements are eliminated from `app_syntax.yml` generating new stubs is an awkward process

* comment out hide statement in `app_syntax.yml` 
* `./moosedocs.py check --generate`
* don't forget to uncomment hide statement in `app_syntax.yml` or you might accidentally commit the change

### Rationale for the enhancement or information for reproducing the error
Will make it slightly less painful to build up documentation

### Identified impact
Added capability

**Comment by aeslaughter** [comment]
I don't want to make this easy, we need to document all the systems so nothing is hidden. Then when a new object is added you MooseDocs will error, then you create actual documentation not just a stub.

In the short term, don't add stubs. Just wait until the system is documented and add the actual docs.

**Comment by aeslaughter** [comment]
The list of hidden objects is not explicit (see #9618) so this is no longer relevant.
