### ISSUE TITLE
Some problem with plasticity

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9391]
### Description of the enhancement or error report

I think Martin is finding that plasticity is activated when it should be.

### Rationale for the enhancement or information for reproducing the error

See this thread on moose-users:

https://groups.google.com/forum/#!topic/moose-users/hl2wcUnfFGA

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Bug fix?  Erroneous model?

**Comment by WilkAndy** [comment]
Error report should be:

I think Martin is finding that plasticity is activated when it should **NOT** be.

**Comment by mlesueur** [comment]
I'm seeing a jump in the strain_increment in plasticity that I can't explain. Attached is the input file showing the issue.
You can visualise _strain_incr_rr_ or the postprocessors _pl_dissip_ or _mises_strain_rate_ to see the problem.
[issue_jumps_strain_increment.txt](https://github.com/idaholab/moose/files/1104943/issue_jumps_strain_increment.txt)

**Comment by WilkAndy** [comment]
Thanks @miesueur .  I haven't explored your input file in detail, so this might be a silly question, but how do you know the strain-rate jumps aren't correct?  What i mean is that when dealing with finite elements that aren't infinitesimally small, and when applying a smoothly increasing stress on the boundary, you could get one quadpoint failing, causing a sudden jump in strain rate, and then after a while another quadpoint will fail, causing another sudden jump, etc.  Of course it depends on your actual problem.  But in these cases i guess all you can expect is that the average strain rate is correct, not that it is exactly correct at all times.

**Comment by WilkAndy** [comment]
Sorry, i misread your github name, @mlesueur .

**Comment by mlesueur** [comment]
Andy you are correct, applying uniform_refine once halved my jumps. This problem is then just due to finite elements.
![half](https://user-images.githubusercontent.com/11986570/27718167-70b83550-5d8d-11e7-99b6-56b17f033a46.png)
Not to close this issue too soon, I would like to draw your attention on yet another problem. 
This 1D simulation is an isotropic extension. If you export stress_11 and stress_22, you see however that they are not equal. But they should be, and a finer mesh did not seem to solve this issue.
You can see it in the input file I attached in my first post.

**Comment by WilkAndy** [comment]
OK, i'll have a look as soon as possible, @mlesueur ,

a

**Comment by WilkAndy** [comment]
I'm either confused (likely, sorry!) or you made a typo @mlesueur .   When you use RSPHERICAL, i thought that if your AuxKernel was

>   [./some_var]
    type = RankTwoAux
    variable = some_var
    rank_two_tensor = stress
    index_i = 1
    index_j = 1
  [../]

you'd be measuring some_var = stress_theta_theta, right.  So, including these AuxKernels into your input file:

>   [./stress_tt]
    type = RankTwoAux
    variable = stress_tt
    rank_two_tensor = stress
    index_i = 1
    index_j = 1
    execute_on = timestep_end
  [../]
  [./stress_pp]
    type = RankTwoAux
    variable = stress_pp
    rank_two_tensor = stress
    index_i = 2
    index_j = 2
    execute_on = timestep_end
  [../]

and visualising stress_tt and stress_pp i see that they're the same.

**Comment by mlesueur** [comment]
You are right @WilkAndy. It seems that as MaterialTensorIntegral and ElementIntegralVariablePostprocessor do not give the same results.
I upload here a modified input file. If you run it, you can see that stress_rr and stress_rr_2 are the same but stress_tt and stress_tt_2 are different, any idea why ?
[issue_jumps_strain_increment.txt](https://github.com/idaholab/moose/files/1136363/issue_jumps_strain_increment.txt)

**Comment by WilkAndy** [comment]
This is because of the different orders of interpolation of your stress_tt AuxVariable, which is a constant monomial, and the stress MaterialProperty, which is evaluated at quadpoints (so it is more exact than the constant monomial).

The stress_tt AuxVariable gets picked up by the stress_tt_2 ElementIntegralVariablePostprocessor, while the stress MaterialProperty gets picked up by the MaterialTensorIntegral.  You're just lucky that the stress_rr and stress_rr_2 Postprocessors are the same in this particular case.

As you increase the fineness of the mesh you will get less and less difference between the MaterialTensorIntegral and ElementIntegralVarialePostprocessor.
