### ISSUE TITLE
Line sources

### ISSUE THREAD

**Issue by snschune** [idaholab/moose#9394]
### Description of the enhancement or error report
Line sources can be implemented as a collection of point sources. They are useful in
many applications - cables in electrostatics/dynamics. I want to use them for solving some
very interesting transient neutronics problems featuring line sources. 

### Rationale for the enhancement or information for reproducing the error
Many sources can be abstracted to be line sources. Currently we can set this up 
using a collection of PointSources hacked in by hand. This can be automated.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Implement a new DiracKernel that sets up a collection of PointSources. This is done by 
supplying parsed expressions `x(s), y(s), z(s)` and a source strength along `s` e.g. `q(s)`.
Then you distribute a user-defined number of PointSources along the curve, best at points corresponding to Gaussian quadrature points. The rest is standard MOOSE handling of multiple Dirac points.

**Comment by WilkAndy** [comment]
Exciting!

This is a start of something that might become a much bigger suite of code.  Keep in mind that people might want to define lines as polylines defined by (strength,x,y,z) from files, or splines defined via files, or polylines defined by points in the input file, or strengths defined as functions of Variables (so Jacobians must be considered) or goodness knows what else!
