### ISSUE TITLE
Create SamplerMultiApp to launch Multiapps given a Sampler object.

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#9402]
### Description of the enhancement or error report
A Sampler object is responsible for creating a set of samples (DenseVectors) from Distributions. A MultiApp is needed that will launch one application for each row in each of the DenseVectors.

When this is working, there will be a corresponding Transfer for moving the sampled data to the sub application 

### Rationale for the enhancement or information for reproducing the error
This is needed to complete basic stochastic runs using pure C++

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This is a new feature, there should be no impact.

**Comment by friedmud** [comment]
Hmmm - where do you see this object ending up?  It sounds a bit specific
(but not entirely).  Is this going into a module?

**Comment by permcody** [comment]
stochastic_tools

**Comment by friedmud** [comment]
👍
