### ISSUE TITLE
Build broken on Falcon

### ISSUE THREAD

**Issue by bwspenc** [idaholab/moose#9432]
### Description of the enhancement or error report
I get the following compile error on Falcon:
```
moose/modules/phase_field/include/ics/SmoothCircleFromFileIC.h:43:48: error: array must be initialized with a brace-enclosed initializer
   std::array<int, 4> _col_map = {-1, -1, -1, -1};
```

### Rationale for the enhancement or information for reproducing the error
Compile with the `moose-dev-gcc` module.
I followed the advice of this thread, and added a second set of braces, and that works:
https://stackoverflow.com/questions/32912921/whats-wrong-with-this-inline-initialization-of-stdarray

### Identified impact
Build is broken.

**Comment by bwspenc** [comment]
@itgreenquist It looks like this was your code.

Thoughts anyone on how to deal with this?  @permcody @dschwen ?  It's easy enough to add a second set of braces, but that won't prevent this from happening again.

**Comment by dschwen** [comment]
Adding the extra braces and a comment as to why they are needed should be fine for now. My vote would be to take that compiler (gcc 4.9.2) off the list of supported compilers eventually.

**Comment by permcody** [comment]
@dschwen - we are working on a package to test our minimum compilers on PRs. This will help with these kinds of problems. Supporting these older compilers is necessary to support cluster builds, especially when a cluster is running one of those ~~crappy~~ stable enterprise Linux flavors. Same reason it took us so long to get to C++11.
