### ISSUE TITLE
SideSetsAroundSubdomain does not respect depends_on

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9447]
### Description of the enhancement or error report

I will describe the problem tomorrow!

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
Haha - Well July 5th is pretty much over for you and I don't see a description!

**Comment by WilkAndy** [comment]
Hmmm, i guess that compared with you i actually live in tomorrow, so i can't use the excuse "it's not tomorrow yet" !

**Comment by WilkAndy** [comment]
See the PR that i'm about to submit.
I create a new block using SubdomainBoundingBox and attempt to put sidesets around that block using SideSetsAroundSubdomain.  MOOSE crashes.  Alternatively,
I create a new block using SubdomainBoundingBox and attempt to put sidesets around that block using SideSetsBetweenSubdomains.  MOOSE does the right thing.

**Comment by dschwen** [comment]
Link to the CIVET output: https://www.moosebuild.org/job/99301/

**Comment by WilkAndy** [comment]
As i said on the PR - i don't have the skill and/or time to fix this at the moment, so i'm hoping someone else will be able to

**Comment by permcody** [comment]
Notes: I don't see how this could be a `depends_on` issue. That parameter is used for sorting the objects into the correct order and isn't something an individual modifier controls. If I had to guess, I'd say that this is a mesh prepared issue of some sort. When you chain up these modifiers, there's always a chance that one modifier might be using methods that aren't really setup to work yet after a previous modifier makes changes to the mesh data structure. Sometimes an extra "prepare()" call is needed to fixup the mesh data structure. This is where I'd start. It's actually a quick fix if I'm correct.
