### ISSUE TITLE
Avoid redundant computation of scalar kernel residual components

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9450]
### Description of the enhancement or error report

NonlinearSystemBase appears to call computeResidual() or computeJacobian() on all ScalarKernel objects on all processors, then accumulates the results with addResidualScalar() or addJacobianScalar() on all processors.  The redundant computation and assembly should be eliminated.

### Rationale for the enhancement or information for reproducing the error

Eliminating an assembly operation with O(N_procs) cost (because the processor which owns those residual entries + matrix rows will need to receive communication from every other processor) should improve scalability for problems with SCALAR variables.

Fixing this properly should simultaneously allow me to improve the dubious code at https://github.com/idaholab/moose/blob/devel/framework/src/base/MooseVariableScalar.C#L65-L76 which allows SCALAR dof values to end up uninitialized (well, 0).  The flaw there is unlikely to be a problem in most codes (where SCALAR dofs are semilocal and thus initialized on every single processor), but I've managed to trigger it in corner cases (where N_proc > N_elem + 1), and I can imagine real cases (where users have restricted coupling with SCALAR variables to only subdomains which are strict subsets of the whole mesh) where this could lead to incorrect results.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

My current plan is to examine each scalar kernel's variable dof_indices, then compute and assemble residual/jacobian values only on processors for which at least one DoF index is local.  I'm testing that now and should have a cleaned up PR tomorrow.

One design decision which will have to be made in the PR: when we reinit a MooseVariableScalar and we discover that it lacks semilocal data on the current processor, what do we do *instead* of letting the corresponding array values remain 0 or uninitialized?  We can't just throw an error right away, because user code may want to reinit() without expecting to test those values (for example, to test if their indices are local, as I'm doing).  If we truncate the arrays then future access screams and dies in dbg mode on libstdc++, but that seems too dangerous for other configurations.  I'm leaning toward "fill them with NaNs", which is a bit hard to debug but which at least prevents misusage from being mistaken for a correct result.  Alternatively I could test _GLIBCXX_DEBUG and truncate arrays if it's in use or fill with NaNs if not.

Copying @friedmud and @permcody since I'm moving my discussion with them from Gitter to here, and @andrsd at Cody's suggestion.

**Comment by andrsd** [comment]
Would it make sense to ghost the DoFs for scalar variables? Just asking, I do not know if that's even possible...

**Comment by roystgnr** [comment]
Ghosting all DoFs for scalar variables is almost always what happens!  Typically scalar variables are each coupled to at least one other non-scalar variable, and at least one of those other variables is present on every processor, and so libMesh ends up ghosting every scalar variable on every processor.

But there are a few ways in which this might fail to happen.  "When we try to use way too many processors, some don't own any elements" is the corner case that trips in the MOOSE tests.  "Some scalar variables might couple only to subdomain-restricted variables that don't exist on every processor" is the first real case I thought of above.  "Some scalar variables might only directly couple to other scalar variables" would also break currently.

We could add a "scalar variables always get ghosted everywhere even if we don't think we need them everywhere" option, but I'd rather not.  Pushing scalar values everywhere isn't as bad as pulling scalar residuals from everywhere (O(log N) in the worst case, vs O(N)), IIRC, but it's still an unnecessary cost I'd rather avoid.

And this *should* all be fixed by #9451, if I ever get around to figuring out exactly what that broke.  I burned a day finding a workaround in a crazy bug, apparently in the old MKL version I'm using, that breaks about 50 moose/modules tests, so I haven't even started looking at the test which actually regressed yet, except to notice that I can reproduce it.

**Comment by andrsd** [comment]
Ok, makes sense. Thanks!
