### ISSUE TITLE
Checkpoint files not being deleted

### ISSUE THREAD

**Issue by charliefolsom** [idaholab/moose#9453]
### Description of the enhancement or error report
I am choosing to keep only two checkpoint files during the simulation and in the past all previous time steps were deleted but now it keeps a *_mesh.cpr-1-0 for each time step resulting in a lot of extra files.

### Rationale for the enhancement or information for reproducing the error
Run a case keeping two checkpoints and these extra file should remain

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This creates a lot of wasted storage space

**Comment by permcody** [comment]
We recently patched this (I believe). Are you running a current version of MOOSE? I can find the exact commit if you want to know the date. For now, tell us the date of your last hash. I'm going to assume you are running in parallel too? Are you running threads? Anything else special? Again, this might be fixed already but we'd like to make sure.

**Comment by charliefolsom** [comment]
I just updated and those files are gone now. Thanks.

**Comment by permcody** [comment]
Issue had already been fixed.
