### ISSUE TITLE
Implementing Material::timestepSetup is not safe

### ISSUE THREAD

**Issue by agiorla** [idaholab/moose#9459]
### Description of the enhancement or error report
Material::timestepSetup is called on objects with an invalid qrule (with _qrule->npoints() == (unsigned int) -1), leading to segmentation fault when a derived class implements it. Example of code that fails:

void 
Material::timestepSetup() 
{
  for (_qp = 0; _qp < _qrule->n_points(); ++_qp)
    // do something at qp (e.g. computeQpProperties)
}

### Rationale for the enhancement or information for reproducing the error
Multiple Materials need their properties to be set only at the timestepSetup() and not at each iteration of the non-linear solver. Having a safe timestepSetup() would help in developing such Materials, and thus reduce the computational time for these Materials.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Probably internal change to how Material::timestepSetup() is called. Solving this issue would allow developers to override timestepSetup() for Material-derived classes.

**Comment by friedmud** [comment]
This is just a documentation/understanding problem.

`timeStepSetup()` is not intended for computing properties.  It is called exactly one time each time step for you to be able to set up / reset internal data.

Note: for normal material properties there is no "storage" so there is no way to compute material properties once per timestep.

**Comment by agiorla** [comment]
To be honest I fail to understand the logic.

I am writing a set of Material with stateful properties that are expensive to calculate, and that, in certain cases (which will be the mostly used cases probably), do not change during the solver iterations. I would like to compute these properties only once per time step if I can, to reduce computational time.

timestepSetup() seems to me the most intuitive place to do these calculations.

Alternatively, how can I check in computeQpProperties() that I am in the first iteration of the solver?

**Comment by permcody** [comment]
As Derek said, timeStepSetup() is called exactly **once** per timestep for a given material, not once per element or quadrature point (potentially millions of calls). Big difference. Creating an extra sweep over the mesh is fairly expensive.

Have you done any profiling yet to see if your stateful materials are actually causing a slowdown for you? Like most things in MOOSE, those calculations are perfectly distributed so the more processors you run on the faster those computations go while other things become the bottleneck. While it may turn out that this calculation is indeed expensive, it's worth making sure first.

To answer your question though, no we currently do not have a mechanism for telling you which iteration you are on in the solver.

**Comment by agiorla** [comment]
Here is some computational time for a simple test (1920 elements, 7533 dofs, on a Workstation, 2 time steps), using code from PR #9413 

Full computation (1 thread) => 79s
Full computation (6 threads) => 16s
Properties computed at time step begin only (1 thread) => 34s
Properties computed at time step begin only (6 threads) => 7.5s

I think it is important to compute these only once, regardless of how it is done. I would prefer to have a timestepSetup that can sweep through elements (with a flag to activate that sweep only when it needs to be activated), but I could live with a way to know whether I am in the first solver iteration or not.

**Comment by agiorla** [comment]
Also, this relates to PR #9438 which deals with similar issues (properties that are not changed during solver iterations).

**Comment by YaqiWang** [comment]
You might use aux variables, which can be evaluated at designated time, including timestep_begin. 

Or you can check `FEProblemBase::getCurrentExecuteOnFlag()` out. In your `Material::computeProperty()`, you can check if the evaluation is at timestep_begin, if so do the evaluations, otherwise simply skip. I believe you will get the desired behavior by doing this.

**Comment by agiorla** [comment]
I cannot use AuxVariable as I am dealing with vectors of RankTwoTensor and RankFourTensor of arbitrary size...

I tried to check FEProblemBase::getCurrentExecuteOnFlag() during Material::computeQpProperties and I got either EXEC_NONE, EXEC_LINEAR and EXEC_NONLINEAR during the solve, EXEC_TIMESTEP_END once per qp after the solve, but never EXEC_TIMESTEP_BEGIN. Is that an intended behavior, or is there a way to force Moose to call computeQpProperties on EXEC_TIMESTEP_BEGIN?

**Comment by permcody** [comment]
Normally only stateful materials are stored (e.g. materials where an "Old" or "Older" state is specifically requested or in some cases explicitly declared). We compute all other properties on a given element for an immediate calculation elsewhere (like for use in a residual), we use those values, then we immediately overwrite them as we move to the next element. This has an obvious space advantage as you can compute several large properties without ever storing a large number of them. If your properties aren't specifically declared to be stateful then those values don't persist in memory so trying to compute them once is already a dead end.

If those timings you gave are representative for your larger problems, then you will have to first force all your properties to be stateful and make sure memory doesn't become an issue, then we can work on a solution for only computing them once. This isn't the first time this issue has been raised, but most other developers find that the storage costs and other disadvantages of using stateful properties aren't worth trying to reduce the on-the-fly computation costs.

**Comment by agiorla** [comment]
Thanks a lot for your explanations, it makes a lot of sense now (and I understand the tradeoff between computational time vs memory). I will see what needs to be stateful or not in my code.

**Comment by dschwen** [comment]
The hackish way (yeah, yeah, bring it on...) would be to set a `bool` flag to true in `timeStepSetup`, and check in `computeQpProperties`, do a computation if it is true and set it to false. That way a property is only computed once per timestep. But it better only rely on data that is constant over the mesh and does not change (much) during the timestep!

**Comment by permcody** [comment]
That would only work for the first element/first quadrature point. 

If I had a dollar for every time somebody suggested that solution... I'd have like $6 by now.

**Comment by agiorla** [comment]
I am interested in properties that are not uniform over the mesh (otherwise it would be to easy...) 

How can I make a property stateful without declaring an "old" state?

**Comment by YaqiWang** [comment]
Another hackish way... You can add a dummy UO executed on timestep_begin, which is using one of the properties declared in your material. This will ensure the evaluation of the material.

What do you mean `properties that are not uniform over the mesh`?

**Comment by agiorla** [comment]
@YaqiWang yes, that's indeed another possibility, thanks for the suggestion.

For "properties that are not uniform over the mesh", I was referring to @dschwen comment "But it better only rely on data that is constant over the mesh ..."

**Comment by rwcarlsen** [comment]
I agree that this issue was about a misused API and isn't a necessarily a bug, but segfaulting sure is a terrible way to fail.

**Comment by dschwen** [comment]
To expand on Yaqi's suggestion, your UserObject could be an ElementUserObject that maintains its own storage for this one single "property" and computes it whenever you set it to execute (timestep begin, non linear iteration, etc.)

**Comment by permcody** [comment]
> I agree that this issue was about a misused API and isn't a necessarily a bug, but segfaulting sure is a terrible way to fail.

This wasn't a segfault in MOOSE though and that's important to understand. I agree that the framework should never segfault (at least in devel or dbg mode). The issue is that the _qp index is initialized to -1 which is probably a good idea to cause immediate failure when used outside of the design scope. A value of zero would give us a worse situation where the user might be under the erroneous impression that the qp loop is working in this method when it is not.

**Comment by agiorla** [comment]
@permcody going back to your comment => "Normally only stateful materials are stored (e.g. materials where an "Old" or "Older" state is specifically requested or in some cases explicitly declared)." 

How is it possible to declare explicitly a property as stateful (without declaring and "Old" or "Older" property?)

**Comment by rwcarlsen** [comment]
Properties are automatically promoted to stateful if somebody tries to
retrieve an old/older value of that property (i.e.
getMaterialPropertyOld...).

**Comment by permcody** [comment]
In MOOSE stateful equals old or older. We don't have the ability to just make a stateful "current" property.
