### ISSUE TITLE
Material property, declared in multiple materials on multiple subdomains, values persist if one material doesn't explicitly assign in computeQpProperties

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#9460]
### Description of the enhancement or error report

Material property, declared in multiple materials on multiple subdomains, values persist if one material doesn't explicitly assign in computeQpProperties

### Rationale for the enhancement or information for reproducing the error

Here's an example. Here's the relevant input block with two different materials on different subdomains:
```
[Materials]
  [./fuel]
    type = MsreFuelTwoGrpXSFunctionMaterial
    block = 'fuel'
  [../]
  [./moder]
    type = GraphiteTwoGrpXSFunctionMaterial
    block = 'moder'
  [../]
[]
```
In both materials, I have this in the constructor:
```c++
    _fissxs(declareProperty<std::vector<Real>>("fissxs")),
```
Then (before I detected this issue) in the Graphite material `computeQpProperties` method:
```c++
  _fissxs[_qp].resize(2, 0);
```
and no assignments. While in the Fuel material `computeQpProperties`:
```c++
  _fissxs[_qp].resize(2, 0);
  _fissxs[_qp][0] = (1.30E-03 + -1.41E-04 * std::log(_T[_qp] / T0)) * rho / rho0;
  _fissxs[_qp][1] = (2.18E-02 + -1.22E-02 * std::log(_T[_qp] / T0)) * rho / rho0;
```
What I found during debugging is that the last computed values for `_fissxs[_qp]` coming from the Fuel material were then used as the values for kernels in the Graphite material domain, when I naively assumed they would be zero.

I think you could argue that this is my mistake as opposed to MOOSE's. I don't know how you would detect that I didn't make any assignments in my Graphite material. However, this could be something that could catch other users by surprise, albeit not very often.

### Identified impact

Naive users (like me in this case!) assume that a material on another subdomain won't have any effect on their current subdomain. This can lead to very surprising simulation results.

**Comment by lindsayad** [comment]
@rwcarlsen ^

**Comment by rwcarlsen** [comment]
I think this could only be happening if MOOSE is actually using the wrong material object (data) for your ``fissxs`` property - i.e. it is returning the ``MsreFuelTwoGrpXSFunctionMaterial``property data object when you try ty get the ``fissxs`` property in the ``moder`` block.  This is because material property names live in an effectively global namespace and are clobbering each other.  I don't think there is a quick way to fix this short of just disallowing same-named properties altogether including ones defined on different blocks.  hmm...

**Comment by lindsayad** [comment]
I think disallowing same-named properties altogether would be unsatisfactory to a lot of users; I wouldn't like it myself. Perhaps a way to issue a warning when same-name material properties are used on different blocks? "Make sure you do assignments in all your `computeQpProperties` methods!"

Is there a good reason why material property names are global entities? Seems like they should be block restricted

**Comment by rwcarlsen** [comment]
Have you confirmed that making the actual assignments solves the problem?  It seems that that wouldn't be enough to fix the issue.

**Comment by lindsayad** [comment]
Yes,
```c++
  for (unsigned i = 0; i < 2; i++)
  {
    _nsf[_qp][i] = 0;
    _fissxs[_qp][i] = 0;
    _d_nsf_d_temp[_qp][i] = 0;
    _d_fissxs_d_temp[_qp][i] = 0;
  }
  for (unsigned i = 0; i < 6; i++)
  {
    _beta_eff[_qp][i] = 0;
    _decay_constant[_qp][i] = 0;
    _d_beta_eff_d_temp[_qp][i] = 0;
    _d_decay_constant_d_temp[_qp][i] = 0;
  }
```
made all the difference which I would expect since materials are computed on demand.

**Comment by rwcarlsen** [comment]
Ah - I understand now.  Both material objects share the same underlying data store object for ``fissxs`` [facepalm].  There is no way to detect this since we can't know whether or not a particular memory address is written into or not.  Like you said the best we could do is warn when the user has multiple materials providing the same property on different blocks.  Another option to consider would be zeroing property values before all calls to computeQpProperties - which would at least make unset properties always be consistent(ly zero).  But that would be a (minor?) performance hit *everybody* would have to always pay.  No good options :-/

**Comment by permcody** [comment]
> Ah - I understand now.  Both material objects share the same underlying data store object for ``fissxs`` [facepalm].  

Really? This is a design feature and really isn't that bad. Users can retrieve the memory location for the material property computations that they can use in a Kernel or some other object that might be active over the whole domain while having several materials filling in that property in the corresponding blocks. There should be a sanity check to make sure that all requested properties are then supplied and I swear this code use to work. However, I think several different devs have tried to work on it over the years and it's probably in a sorry state. 

I don't think we want to change the design though, the shared storage is just fine. It should be an error if that property isn't supplied in part of the domain where it's being used.

**Comment by rwcarlsen** [comment]
@permcody - I was facepalming my misunderstanding - not necessarily the MOOSE design.

**Comment by lindsayad** [comment]
@permcody The property is being supplied. However, the values being supplied are actually values computed from the other material's (on the other subdomain) `computeQpProperties` method if the user doesn't do any assignments in the current material's `computeQpProperties`

**Comment by permcody** [comment]
> if the user doesn't do any assignments in the current material's computeQpProperties

So this is really a flaw in the Material then, right? The material claimed to be supplying the property, then didn't. I suppose this could happen even without subdomain restriction but users would normally get zero (probably) and the error would be quickly found.

**Comment by rwcarlsen** [comment]
It depends on what you mean by "supplied".  It declared the property, it just didn't assign any values to it in computeQpProperties.

**Comment by permcody** [comment]
Yeah, I mean "declare == supplied", this is a fundamental assumption in the Materials system. Declaring is a contract for providing the property.

**Comment by lindsayad** [comment]
@permcody I would more or less tend to agree with you. This almost assuredly would not have come up if I wasn't dealing with a MaterialProperty that's a vector of Reals. Without thinking about the fact that the names are global, I had this in my Graphite material:
```
 _fissxs[_qp].resize(2, 0);
```
I thought that I would be starting with a zero length vector and would then resize it to be filled with zeros. But since it had already been properly sized in my other material, the zero filling never happened.

**Comment by rwcarlsen** [comment]
Regardless of the (un)niceness of the current behavior, I think I'd have to vote that we don't change anything here barring any large redesign of the material system.

**Comment by friedmud** [comment]
To me: it looks like everything is working as intended.  It looks like @lindsayad simply made an assumption that wasn't true.

To be 100% clear the memory used to store a property MUST be a shared memory location to allow single Kernels to have a reference to that memory but receive different values as you traverse the mesh.  It's fundamental to the design of MOOSE where we return references to memory locations and use them with the understanding that their contents are being managed by MOOSE.

**Comment by lindsayad** [comment]
I'm going to contend that I was peer pressured into making this issue :-) I did say:
> I think you could argue that this is my mistake as opposed to MOOSE's. I don't know how you would detect that I didn't make any assignments in my Graphite material. However, this could be something that could catch other users by surprise, albeit not very often.
Closing this.

**Comment by permcody** [comment]
Right, to be clear, I still want MOOSE to detect the case where a material isn't supplied on a portion of the domain and I think now we are all clear that this wasn't the case here.

**Comment by rwcarlsen** [comment]
But originally it wasn't clear if there really was a bug or a simple
improvement we could make to MOOSE.  The discussion here helped us
understand that there isn't anything we need to fix - which is a fine
outcome.

**Comment by lindsayad** [comment]
:+1:
