### ISSUE TITLE
moose documentation doesn't display correctly

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9473]
### Description of the enhancement or error report

On browsers that are too narrow, the top bar containing "Getting started, Documentation, Utilities, Help" doesn't visibly contain those pull-down menus .  Actually, they're there, but they're invisible (i have to randomly click on the top bar and suddenly a drop-down menu appears).

### Rationale for the enhancement or information for reproducing the error

Firefox 39.0

If someone tells me how to attach a picture to a github issue i can do that, if it's helpful.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
Yeah - This isn't a firefox issue. This happens on all browsers. I already reported the issue here: #9210. I'll close this since it's a duplicate. @aeslaughter or @brianmoose, any ideas on how to fix? This is a pretty big usability issue.
