### ISSUE TITLE
Large amounts of scalar variables perform poorly on simulation setup

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9480]
### Description of the enhancement or error report
Simulations with 100s of scalar variables (i.e. N=500) take a substantial time (20-30sec) in libmesh initNonlinearSystem (writing this from memory). It looks like there is an O(N^2) complexity somewhere related to scalar variable system setup.
Tagging @xianmingbai 

### Rationale for the enhancement or information for reproducing the error
I'll prepare an example case.

### Identified impact
Poor performance

**Comment by permcody** [comment]
How many processors?, we were discussing this just the other day. Scalar DOFS are normally ghosted to all processors so the amount of extra work may add up. @roystgnr - may have a bit more to add here. We can certainly profile your test to take a look.

**Comment by dschwen** [comment]
This is on a single core. That model does not converge at all on more cores. It is a cluster dynamics simulation.

**Comment by permcody** [comment]
Well then, should be uber-simple to profile that!

**Comment by friedmud** [comment]
My guess: the sparsity for the Jacobian is not getting set right...

**Comment by andrsd** [comment]
We had the same report in RELAP-7. The reported tracked it down into libMesh, but no action was taken to fix it AFAIK.

**Comment by dschwen** [comment]
> My guess: the sparsity for the Jacobian is not getting set right...
 Yeah, seconded

**Comment by roystgnr** [comment]
> The reported tracked it down into libMesh, but no action was taken to fix it AFAIK.

Could you point me to that report?

**Comment by andrsd** [comment]
@roystgnr He told me about it when he was on site a few years ago. There was no issue opened for it or anything else done in that regard on **his side**. I though he was going to fix it himself and I do not believe he reported it to libMesh devs. That's what I meant by "no action was taken to fix it".

**Comment by roystgnr** [comment]
Damn.  I was cringing, waiting for the embarrassing details of "Roy knew about some libMesh problem a year ago and then just forgot to fix it", but really "There's some libMesh problem for which we've now lost the details and have to reinvestigate" is even worse.  Fingers crossed that @dschwen's example case replicates cleanly.

There's obviously going to be O(N_scalar_vars^2) code in libMesh setup routines (that's the size of that part of the Jacobian, after all!) but 20-30 seconds for 500 variables sounds way too long, so there may be a nasty coefficient there we can cut down.

**Comment by dschwen** [comment]
Hmm, just _adding_ the variables is not causing any slowness. I continue to investigate.

**Comment by dschwen** [comment]
Aaaah, adding a `SMP` preconditioner with `full = true` triggers it!

Minimal input:

```
[Mesh]
  type = GeneratedMesh
  dim = 1
[]

[LotsOfVariables]
  [./scalars]
    number = 1000
    family = SCALAR
    order = FIRST
  [../]
[]

[Problem]
  kernel_coverage_check = false
[]

[Preconditioning]
  [./SMP]
    type = SMP
    full = true
  [../]
[]

[Executioner]
  type = Steady
[]
```

**Comment by YaqiWang** [comment]
This `LotsOfVariables` action seems quite useful ;-)

**Comment by roystgnr** [comment]
See if the n_vars^2 loop in SingleMatrixPreconditioner.C is at fault?

The new sparse CouplingMatrix class was designed to allow efficient memory usage and read iteration, at the expense of write speed, because I expected even the "expensive" write would still be negligible.  If write speed is a problem, it would be easy to fix; cm.make_all_ones() could be an O(1) operation.

**Comment by dschwen** [comment]
Weird, looking at the CouplingMatrix code it looks like there should only be one single range (range_type) object that just gets increased...
Or are we looping in the wrong order...?

**Comment by dschwen** [comment]
I'm profiling this now. But I'm ready to add an `assign` call to `CouplingMatrix`. As the description states _Coupling matrices are typically either full or very sparse_, so providing a fast call to fill the matrix completely seems like a good idea.

**Comment by dschwen** [comment]
Profiler says 97% of the time (i.e. almost all of setup) is spent in and below `libMesh::SparsityPattern::Build::handle_vi_vj()`

**Comment by roystgnr** [comment]
Yeah, it should basically just be a few conditional evaluations and a range_end++ on every iteration of the loop, because you are looping over column indices on the inner loop.  But that's still O(N^2).

Let's not create more special methods just yet, though; wait and see whether this shows up in profiling.  Even the current implementation ought to be taking milliseconds at most!

**Comment by roystgnr** [comment]
Hmm... do you also have a significant number of elements?  If so, then we're probably adding the "scalar dofs couple to other scalar dofs" entries *over* and *over*, on top of the "scalar dofs couple to element dofs" entries which change each time.

**Comment by dschwen** [comment]
See above, the mesh is a 1D single element mesh!

**Comment by dschwen** [comment]
This is the relevant part of the inverted call tree:
```
430848.0ms   99.7%	0.0	 	void* libMesh::Threads::run_body<libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*>, libMesh::SparsityPattern::Build>(void*)
430825.0ms   99.7%	8677.0	 	 libMesh::SparsityPattern::Build::operator()(libMesh::StoredRange<libMesh::MeshBase::const_element_iterator, libMesh::Elem const*> const&)
419125.0ms   96.9%	134698.0	 	  libMesh::SparsityPattern::Build::handle_vi_vj(libMesh::Elem const*, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> > const&, unsigned int)
157422.0ms   36.4%	51081.0	 	   libMesh::DofMap::dof_indices(libMesh::Elem const*, std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&, unsigned int, int) const
117114.0ms   27.1%	63666.0	 	   libMesh::DofMap::find_connected_dofs(std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&) const
4806.0ms    1.1%	3571.0	 	   <Unknown Address>
3920.0ms    0.9%	3920.0	 	   void std::__1::__sort<std::__1::__less<unsigned int, unsigned int>&, unsigned int*>(unsigned int*, unsigned int*, std::__1::__less<unsigned int, unsigned int>&)
635.0ms    0.1%	635.0	 	   operator delete(void*)
225.0ms    0.0%	225.0	 	   DYLD-STUB$$operator delete(void*)
119.0ms    0.0%	16.0	 	   void std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >::__push_back_slow_path<unsigned int const&>(unsigned int const&&&)
78.0ms    0.0%	78.0	 	   DYLD-STUB$$operator new(unsigned long)
64.0ms    0.0%	64.0	 	   std::__1::__tree<libMesh::GhostingFunctor*, std::__1::less<libMesh::GhostingFunctor*>, std::__1::allocator<libMesh::GhostingFunctor*> >::destroy(std::__1::__tree_node<libMesh::GhostingFunctor*, void*>*)
39.0ms    0.0%	31.0	 	   std::__1::enable_if<(__is_forward_iterator<std::__1::__wrap_iter<unsigned int*> >::value) && (is_constructible<unsigned int, std::__1::iterator_traits<std::__1::__wrap_iter<unsigned int*> >::reference>::value), std::__1::__wrap_iter<unsigned int*> >::type std::__1::vector<unsigned int, libMesh::Threads::scalable_allocator<unsigned int> >::insert<std::__1::__wrap_iter<unsigned int*> >(std::__1::__wrap_iter<unsigned int const*>, std::__1::__wrap_iter<unsigned int*>, std::__1::__wrap_iter<unsigned int*>)
5.0ms    0.0%	5.0	 	   DYLD-STUB$$free
2199.0ms    0.5%	1507.0	 	  <Unknown Address>
351.0ms    0.0%	351.0	 	  DYLD-STUB$$operator delete(void*)
265.0ms    0.0%	265.0	 	  DYLD-STUB$$void std::__1::__sort<std::__1::__less<unsigned int, unsigned int>&, unsigned int*>(unsigned int*, unsigned int*, std::__1::__less<unsigned int, unsigned int>&)
202.0ms    0.0%	202.0	 	  operator delete(void*)
5.0ms    0.0%	5.0	 	  DYLD-STUB$$free
1.0ms    0.0%	0.0	 	  libMesh::DofMap::find_connected_dofs(std::__1::vector<unsigned int, std::__1::allocator<unsigned int> >&) const
23.0ms    0.0%	0.0	 	 <Unknown Address>
1241.0ms    0.2%	0.0	 	main
1.0ms    0.0%	0.0	 	<Unknown Address>
1.0ms    0.0%	1.0	 	__cxx_global_var_init
1.0ms    0.0%	1.0	 	_GLOBAL__sub_I_adjoint_re.stdout.fn426622.fn.inl.gov.69939.yX3BBW.ii
1.0ms    0.0%	1.0	 	_GLOBAL__sub_I_Nemesis.stdout.fn426622.fn.inl.gov.17685.PGezYD.ii
```

**Comment by dschwen** [comment]
Ugh, I forgot that I added the `AddLotsOfVariablesAction`. It is in 0c28737.

**Comment by dschwen** [comment]
It doesn't look like this was ever resolved. I just rebased my test classes and the test case still takes forever to set up.

**Comment by roystgnr** [comment]
Damn, no, it wasn't resolved.  I should have time to look at it again now, though.  Do you have your test case set up in a branch that'd be easy for me to replicate timings with?

**Comment by dschwen** [comment]
The branch is here: https://github.com/dschwen/moose/tree/add_lots_of_variables_9480 
It is rebased and I just committed the file that I pasted in an above comment.

**Comment by dschwen** [comment]
Oh, by the way I'm not just trying to be a pest. There is an actual usecase for this that I'm working on: coupling to mean field rate theory (which requires hundreds of ODEs).

**Comment by andrsd** [comment]
And, another use case is RELAP-7. Junctions are adding scalar variables and big complex models will have hundreds of them, eventually. So, this will help a lot.

**Comment by YaqiWang** [comment]
Not meant to put more pressure: is this related with slow set up with large number of variables not scalar variables?

**Comment by dschwen** [comment]
Good question. The action in my branch can easily test that.

**Comment by dschwen** [comment]
Yeah, looks like it. Setting family to lagrange and order to first also incurs a super slow setup time in the above example.

**Comment by YaqiWang** [comment]
Good to know. Thanks @dschwen .

**Comment by roystgnr** [comment]
Damn it.  I think I see a refactoring that will save 90% on runtime, and that should have been obvious to me back in July.

> Not meant to put more pressure

In hindsight, the problem was *clearly* "not enough pressure", not "too much pressure".

This will take a little time to get right (my first attempt would have silently broken sparsity construction for coupling with ghosted elements, so even after catching that I'm feeling paranoid) but I'll try to get a PR up ASAP.

**Comment by roystgnr** [comment]
Hmm... the correct version won't show nearly as much speedup on coupling between ghosted elements.  But that's rare; coupling within elements is the much much more common case.

**Comment by dschwen** [comment]
Further up we speculated about an _O(N^2)_ complexity. The plot below shows it is worse. This looks like _O(N^3)_!

![out](https://user-images.githubusercontent.com/202302/35645336-b72febf0-0688-11e8-877c-2762a6753b4c.png)

**Comment by roystgnr** [comment]
I've found a bug in the CouplingMatrix iterators' code which is leading to redundant work - at first glance it looks like O(N^3) redundant work.  Working on a fix now.

**Comment by roystgnr** [comment]
How urgent is further improvement here?

There's definitely still lots of room for optimization (see https://github.com/libMesh/libmesh/pull/1582#issuecomment-365027202 for details), but I think "test case setup now takes 1sec instead of 100sec" is about as far as I can safely take that first input file as a benchmark to focus on.  

Subsequent improvements are likely to involve slight tradeoffs, so it would be good if I could have use case info (number of elements of each type, number of variables of each type, CouplingMatrix sparsity or lack thereof) for a few real problems.

**Comment by dschwen** [comment]
I have refreshed my test branch in 9ee07a31b78f6405a0d09ebe6652cb218a4abaa0. Adding 1000 scalar variables now takes almost no time at all. Somewhere along the way there was a _ginormous_ improvement! I'm opening a PR for the `AddLotsOfVariables test and add a test that will ensure we do not regress on this speedup.

**Comment by dschwen** [comment]
This was fixed sometime in 2018, but we don't have a reliable way of regression testing this. Might as well just close this issue.
