### ISSUE TITLE
getMaterialProperty in DGKernel is not checked for integrity

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9482]
### Description of the enhancement or error report
Looks like `DGKernel::getMaterialProperty` is not mark the consumer of the material property, thus the problem integrity check is not covering the case where `DGKernel` is trying to use a un-declared property.

### Rationale for the enhancement or information for reproducing the error
DG kernels may not properly set up.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Input robustness.

**Comment by YaqiWang** [comment]
Here is a test!
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 2
  ny = 2
[]

[Debug]
  show_material_props = true
[]

[MeshModifiers]
  [./subdomain1]
    type = SubdomainBoundingBox
    bottom_left = '0 0 0'
    top_right = '0.5 0.5 0'
    block_id = 1
  [../]
[]

[Variables]
  [./u]
    order = FIRST
    family = MONOMIAL
  [../]
[]

[Kernels]
  [./diff]
    type = DiffMKernel
    variable = u
    mat_prop = prop1
    offset = 0
  [../]
  [./force]
    type = BodyForce
    variable = u
  [../]
[]

[DGKernels]
  [./dgdiffusion]
    type = DGDiffusion
    variable = u
    epsilon = 1
    sigma = 4
    diff = prop2
  [../]
[]

[BCs]
  [./vacuum]
    type = VacuumBC
    variable = u
    boundary = 'left right left bottom'
  [../]
[]

[Materials]
  [./mat1]
    type = GenericConstantMaterial
    block = '0 1'
    prop_names = 'prop1'
    prop_values = '1'
  [../]
  [./mat2]
    type = GenericConstantMaterial
# missing block 0 here, we should see an error!
    block = '1'
    prop_names = 'prop2'
    prop_values = '2'
  [../]
[]

[Postprocessors]
  [./unorm]
    type = ElementL2Norm
    variable = u
  [../]
[]

[Executioner]
  type = Steady
[]

[Outputs]
  exodus = true
[]
```

**Comment by permcody** [comment]
I don't have time to work on this right now but it should be very easy to fix. We've just been intercepting the calls in other objects and keeping track of these things. I believe we do it in AuxKernel for instance.

**Comment by YaqiWang** [comment]
While fixing this, I noticed two corner cases we miss the coverage check, see 18e60a2. We need to fix them in the future.

**Comment by lindsayad** [comment]
@YaqiWang you should fix the coverage for IntegratedBC (#5309) as well :-)

**Comment by YaqiWang** [comment]
Ah, did not realize an issue has already been created. It is too complicated because the property could be provided through volume-face materials or boundary materials. First there should be something in place to make sure the two sets of materials are not providing the same properties. We basically need a map in type `std::map<BoundaryID, std::set<SubdomainID>>` for all the blocks to any boundary and perform checks from there. Neighboring check on the other hand will be easier. It is a perfect moose project ;-)

**Comment by YaqiWang** [comment]
The three tests contained in these two commit https://github.com/idaholab/moose/pull/9495/commits/5c033e61a5ce9b43ec23c1b7041b339ced403d3d and https://github.com/idaholab/moose/pull/9495/commits/18e60a2030e1447f3df2853b9a340d5a456b1c14 can be used when the right fix is in place.
