### ISSUE TITLE
Minor issues on the new SLEPc eigen executioner

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9522]
### Description of the enhancement or error report
The executioner is great and working properly! However, I noticed several minor issues:

1. with `gipm.i`, default `n_basis_vectors` by commenting out it throws a PETSc error: `The value of minv must be less than mpd minus blocksize`, which does not give much useful info.
2. with `gipm.i`, it appears the 18th iteration is outputted twice, while the first one is garbage. This seems true with `ane.i` as well.

3. with `ane.i`, there is no convergence history like what we have with PJFNK solver. For extremely large problem, lack of screen output may frustrate users because they will have no idea what the current progress is and how far the estimated convergence will be.

4. with `ane.i`, the converged value is `34.7623` inconsistent with the one outputted by the postprocessor `0.028766782866964`. Probably we are outputting on the screen with 1/lambda. And the eigenvalue should be smallest but not `LARGEST_MAGNITUDE`.

5. with `ane.i`, I got with the new solver by turning `Outputs/print_perf_log=true`
```
|   compute_jacobian()                       23         0.0165      0.000717    0.0165      0.000717    3.73     3.73     |
|   compute_residual()                       355        0.0984      0.000277    0.1723      0.000485    22.26    38.96    |
```
while with the old solver, I got
```
|   compute_jacobian()                       15         0.0117      0.000778    0.0117      0.000778    3.68     3.68     |
|   compute_residual()                       173        0.0562      0.000325    0.1103      0.000638    17.71    34.77    |
```
I am concerned with the increasing of the residual and jacobian evaluations.

6. with `ane.i`, with my SLEPc+PETSc build (master debug version), I got few warnings at the end
```
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
Option left: name:-i value: ane.i
Option left: name:-snes_mf_operator (no value)
```
which should be removed.

### Rationale for the enhancement or information for reproducing the error
See above. I might have more in the future on using this new solver.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Better user experience. Tag @fdkong

**Comment by YaqiWang** [comment]
Tag @fdkong.

**Comment by fdkong** [comment]
Thanks for your report @YaqiWang. I do not know why  I did not receive this via email.  I will be working all these issues one by one.

**Comment by YaqiWang** [comment]
@fdkong I guess this issue can be closed.

**Comment by fdkong** [comment]
Yes,
