### ISSUE TITLE
Add sideset tagging to ElementDeleterBase

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9533]
### Description of the enhancement or error report
It would be useful to be able to assign a boundary ID to the cut surface exposed by element deleting classes (derived from `ElementDeleterBase`)

### Rationale for the enhancement or information for reproducing the error
Will make these classes more useful. BCs can be added to the holes.

### Identified impact
Added capability

**Comment by YaqiWang** [comment]
Thanks! I actually wanted this for a while, although this can be achieved by existing mesh modifiers to add boundary before deletion.

**Comment by dschwen** [comment]
@YaqiWang it cannot. Your suggestion only works in case of the BlockDeleter. I have derived a class that cuts ellipsoidal holes from meshes and snaps the nodes to the ellipsoid surface. At no point do I have a second subdomain I could use for marking the boundary.

**Comment by YaqiWang** [comment]
Right. I am glad to see this capability.
