### ISSUE TITLE
JIT fails when too many parsed materials are used

### ISSUE THREAD

**Issue by tophmatthews** [idaholab/moose#9549]
### Description of the enhancement or error report
When many (100s?) of parsed materials are used, JIT sometimes, but not always, fails with text like

```error: unable to open output file '/var/folders/gm/p_n04c_95lz9v6cbqbw1j0vw0000gp/T/tmp_jit_ixSjxn-f0857a.o': 'Too many open files'
1 error generated.
JIT compile failed.
ccache: error: /Users/topher/.ccache/ccache.conf: Too many open files
JIT compile failed.




*** Info ***
Failed to JIT compile expression, falling back to byte code interpretation.


Error creating AD cache tmp file ./tmp_adc_7Y1d4q.
Error creating JIT tmp file ./tmp_jit_2hZO5k.
Error creating JIT tmp file ./tmp_jit_bqrtaF.
Error creating AD cache tmp file ./tmp_adc_KegtDw.
Error creating JIT tmp file ./tmp_jit_NbShiy.
(and so on)...
```

### Rationale for the enhancement or information for reproducing the error
This occurs in FEClusterDynamics clusters in MARMOT which uses behind the scenes actions to create many parsed and derivative parsed materials. The fix now is to set `enable_jit=false`

### Identified impact
Improves the robustness of JIT?

**Comment by tophmatthews** [comment]
ping @dschwen

**Comment by dschwen** [comment]
Hmmm, one is a ccache error. The others are possibly related. Looks like _Too many open files_ is the issue here. Let me check if I forgot to close files.
Is this a parallel / threaded run? The materials should be JIT compiled sequentially, so it should make no difference whether you have 1, 10, 100, or 1000 materials (unless file handles are left open).

**Comment by dschwen** [comment]
Yep, that's it. `mkstemp` does not only create an empty file, it also opens it. And I never store or close that open file handle. 

I have opened https://github.com/libMesh/libmesh/issues/1386 since the issue is in libMesh. Lets continue this over there.
