### ISSUE TITLE
getMaterialPropertyDerivative fails with constant props in MultiApp setting

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#9557]
### Description of the enhancement or error report

If `getMaterialPropertyDerivative` is called in different dimension applications in a `MultiApp` and the property is constant in both apps (e.g. the derivative property is zero in both apps), then you will get an assertion error when running in `dbg` mode. From some preliminary investigation, I believe this is because a 'zero property' is created with size equal to the number of quadrature points of the app that is initialized first, and then this property is never resized.

### Rationale for the enhancement or information for reproducing the error

This error can be reproduced by running the following input files with `PhaseFieldApp` compiled in dbg mode.

Master:
```
[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 1
  ny = 1
[]

[Variables]
  [./diffused]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./diff]
    type = MatDiffusion
    variable = diffused
    D_name = diffusivity
  [../]
[]

[BCs]
  [./bottom]
    type = DirichletBC
    variable = diffused
    boundary = 'bottom'
    value = 1
  [../]

  [./top]
    type = DirichletBC
    variable = diffused
    boundary = 'top'
    value = 0
  [../]
  [./left]
    type = DirichletBC
    variable = diffused
    boundary = 'left'
    value = 1
  [../]
  [./right]
    type = DirichletBC
    variable = diffused
    boundary = 'right'
    value = 0
  [../]
[]

[Materials]
  [./blockDiffusivity]
    type = DerivativeParsedMaterial
    f_name = diffusivity
    function  = '1.0'
    args = diffused
    derivative_order = 1
  [../]
[]

# [Materials]
#   [./blockDiffusivity]
#     type = GenericConstantMaterial
#     prop_names = 'D'
#     prop_values = '1'
#   [../]
# []

[Executioner]
  type = Transient
  num_steps = 1
  solve_type = 'PJFNK'
[]

[Outputs]
  execute_on = 'timestep_end'
  exodus = true
[]

[MultiApps]
  [./loopApp]
    type = TransientMultiApp
    app_type = PhaseFieldApp
    execute_on = timestep_begin
    positions = '0 0 0.0'
    input_files = 'sub_simple.i'
  [../]
[]
```
Sub:
```
[Mesh]
  type = GeneratedMesh
  dim = 1
  nx = 1
[]

[Variables]
  [./diffused]
    order = FIRST
    family = LAGRANGE
  [../]
[]

[Kernels]
  [./diff]
    type = MatDiffusion
    variable = diffused
    D_name = diffusivity_sub
  [../]
[]

[BCs]
  [./left]
    type = DirichletBC
    variable = diffused
    boundary = 'left'
    value = 1
  [../]
  [./right]
    type = DirichletBC
    variable = diffused
    boundary = 'right'
    value = 0
  [../]
[]

[Materials]
  [./blockDiffusivity]
    type = DerivativeParsedMaterial
    f_name = diffusivity_sub
    function  = '1.0'
    args = diffused
    derivative_order = 1
  [../]
[]

# [Materials]
#   [./blockDiffusivity]
#     type = GenericConstantMaterial
#     prop_names = 'D'
#     prop_values = '1'
#   [../]
# []

[Executioner]
  type = Transient
  num_steps = 1
  solve_type = 'PJFNK'
[]

[Outputs]
  execute_on = 'timestep_end'
  exodus = true
[]
```
### Identified impact

This is a bit of a corner case, so not high priority; I'm a bit surprised we ever ran into it. But if it happened once, it can happen again. There are easy hacks to get around this, e.g. specify a function like `1.0 + 1e-16*diffused`, but it would be nice for this to work as expected.

**Comment by dschwen** [comment]
Alex, could you check if f590c2ac90 fixes this issue?

**Comment by lindsayad** [comment]
Works like a charm!

**Comment by dschwen** [comment]
Great, PR opened. We might want to go over the code and check if this bites us in other places. I've always assumed that `getMaxQps()` does just that, get me the maximum number of QPs in an element in the simulation. But it only does so on a per app basis.
