### ISSUE TITLE
Parser stalls indefinitely for certain input files 

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9571]
### Description of the enhancement or error report
Open and closing tags in variable blocks (possibly elsewhere, too) cause the parser to stall (possibly run into an infinite loop). 

### Rationale for the enhancement or information for reproducing the error

Minimal input to reproduce the bug:
```
[Variables]
  [./a][../]
[]
```

### Identified impact
Bad behavior. Malformed input should not cause the code to stall indefinitely.

**Comment by dschwen** [comment]
For full backward compatibility it should go into an infinite loop, too.

**Comment by rwcarlsen** [comment]
Moose (c++) parser or the python one?  Also, does it loop forever in other blocks (not just ``Variable``)? And does it still break if the closing tag is on a separate line?  The new parser works.

**Comment by dschwen** [comment]
The old C++ parser is the one that locks up. The new parser will have a common C++/python (cython) code base, right?

It does not lock up if the closing block is on a separate line.

**Comment by rwcarlsen** [comment]
New parser (mostly) doesn't care about whitespace.  You will soon be able to have one-line input files!

We haven't fully decided if we prefer python bindings to the new c++ parser or just have a separate but similarly architected new python parser (which I have already written) with a shared set of tests between the two.

**Comment by dschwen** [comment]
> You will soon be able to have one-line input files!

Will we have an _Obfuscated MOOSE Contest_ as well?
