### ISSUE TITLE
Avoid redundant computation in AuxScalarKernel too

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9576]
### Description of the enhancement or error report

The same problem that I described in #9450 with respect to SCALAR terms in residual evaluations also occurs in AuxScalarKernels, and in the new form it's still a threat to scalability, a future serious bug that could occur if people ever restrict scalar variable processor support via CouplingMatrix and subdomain-restricted variables, and an immediate trivial bug that does occur if we throw way too many processors at tiny test suite problems.

### Rationale for the enhancement or information for reproducing the error

```METHOD=dbg ./run_tests -p 13 --re kernels/ode.test_expl```

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This should just take a few lines of code to fix, and since the redundant computations are being accumulated via set() rather than add(), fixing this incarnation of the problem shouldn't give us the same linear system conditioning headaches that #9451 did.

**Comment by roystgnr** [comment]
Hmmm... here we actually *need* to be redundant, because we're putting the results into the local copy of the AuxVariable, not into the Aux system's solution vector.  So the performance-harming redundancy is actually in the insert() step, and all we need to worry about in the kernels is correctness in the non-semilocal-dofs case.

**Comment by permcody** [comment]
Is there more work to do on this ticket?

**Comment by roystgnr** [comment]
Doesn't look like it.  Civet was as happy with #9581 as I was.
