### ISSUE TITLE
CNSFV failure while varying the number of processes

### ISSUE THREAD

**Issue by Chuban** [idaholab/moose#9591]
### Description of the error
When using the CNSFV portion of the NS module, varying the number of processes can cause MOOSE errors.  These seem to originate in the `ElementLoopUserObject` class.  The simulation in which the errors have been observed contains two blocks separated by an interface.  User objects that inherit from `ElementLoopUserObject` are restricted to one of those blocks and the errors occur for elements on the interface.  The error is triggered by not finding an expected cached value.

### Proposed corrective action
As the error only appears for some numbers of processes, it is suspected it be related to the partitioning of the mesh and the communication between the processes.  Currently, `ElementLoopUserObject::onInterface()` is an empty function.  `ElementLoopUserObject::onInternalSide()`, in contrast, performs a check on the processor ids of the current and neighbor elements and initiates communication by editing `_interface_elem_ids`.  Defining `onInterface()` in a manner similar to `onInternalSide()` appears to resolve the problem.

### Identified impact
none

**Comment by permcody** [comment]
@yidongxiainl or @andrsd - perhaps you guys can take a look at this. Looks like he's proposing a new callback in here as well as providing a fix.

**Comment by Chuban** [comment]
I don't have an immediate need for the extra callback.  It was only included to keep the code structurally similar to `onInternalSide()`.
