### ISSUE TITLE
Element caches can contain dangling pointers

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9592]
### Description of the enhancement or error report

The DiracKernel::_point_cache map contains Elem pointers, but I don't see any facility for removing such pointers when the underlying element has been deleted via mesh coarsening, user mesh modification, or distributed mesh remoting.

I'm not sure where else this sort of cache is maintained in MOOSE, so the problem might not be limited to DiracKernel.

### Rationale for the enhancement or information for reproducing the error

```
METHOD=dbg ./run_tests -p 7 --distributed-mesh --re 'dirackernels/point_caching.point_caching_adaptive_refinement'
```
results in a segmentation fault for me and (in opt mode, at least) on Civet.  This issue therefore blocks #1500.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

I'm actually not sure what the best way to fix this is.  "Just mark the class as ReplicatedMesh-only and move on" isn't sufficient, since at least in theory there are ways to trigger the same failure on ReplicatedMesh too.

My first wild idea would be to add an optional functor or functor chain, which would be called from libMesh delete_elem(), and which would be set at the app or middleware level to allow higher-level objects to react when an element is about to disappear.  We'd do the same with delete_node() for completeness.

There may be less intrusive options, though.  Could we use MeshChangedInterface here to just clear caches after a prepare_for_use()?

**Comment by permcody** [comment]
@jwpeterson might have a little insight on this.

If it's just cache, I'd suggest just clearing the cache on mesh changed. While that might throw away a lot of reusable information, I'd rather do that than have stale information any day.

**Comment by jwpeterson** [comment]
> If it's just cache, I'd suggest just clearing the cache on mesh changed.

Yeah, this cache code was not written to handle the case where elements are being *deleted*, so while it doesn't need to be recreated every time the Mesh changes, it should probably be thrown out any time elements are deleted. Unfortunately we don't currently have a way of distinguishing between those two situations...
