### ISSUE TITLE
Miscellaneous small tidies in my TensorMechanics things

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9602]
### Description of the enhancement or error report

@bwspenc identified a few things in PR #9536 that should be changed, predominantly in my TensorMechanics code.  

### Rationale for the enhancement or information for reproducing the error

Tidy, neatness, uniformity of code.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by WilkAndy** [comment]
Also i have changed ```super_lu = true``` to ```superlu = true``` in combined_creep_plasticity/tests.

Pinging @sapitts

**Comment by sapitts** [comment]
oops, thanks @WilkAndy
