### ISSUE TITLE
misc module tests fail in debug mode

### ISSUE THREAD

**Issue by brianmoose** [idaholab/moose#9621]
### Description of the enhancement or error report

`dynamic_loading/dynamic_obj_registration.dynamic_object_loading`
and
`dynamic_loading/dynamic_obj_registration.dynamic_object_loading_syntax`
both fail with `METHOD=dbg` using the `run_tests` in the `misc` directory.

This is caused by a MooseWarning in MooseApp.C that is only enabled in debug mode. It is the message saying it can't find the registration name in a library.
Since we run tests with `--error` these tests only fail in debug mode. Without `--error` then the tests pass.

### Rationale for the enhancement or information for reproducing the error

Build modules in dbg mode. Then build the `misc` executable. In the `misc` directory, do a `run_tests`. 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Allow running `misc` tests in debug mode.

**Comment by permcody** [comment]
Oh yes... Perhaps we just need to turn on `allow_warnings`
