### ISSUE TITLE
MOOSEDocs updates

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9638]
### Description of the enhancement or error report

This ticket is here to reference for updates to the MOOSEDocs pages themselves.

### Rationale for the enhancement or information for reproducing the error

Ticket for improving documentation, or correcting errors in documentation.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No code changes, only documentation improvements.

**Comment by WilkAndy** [comment]
moosedocs.py (in porous_flow/doc) should have

`MOOSE_DIR = os.getenv('MOOSE_DIR', os.path.join(os.getcwd(), '..', '..', '..', '..', 'moose'))`

ie, two extra sets of '..'

**Comment by WilkAndy** [comment]
When building the doco from porous_flow/doc (which is super fast, by the way!) the top "banner" bar says 

"MOOSE Tensor_Mechanics Module"

instead of PorousFlow Module

**Comment by tophmatthews** [comment]
@aeslaughter `SetupInterface.md`: quite should be quiet fyi

**Comment by permcody** [comment]
Closing ticket - many PRs merged and it's very vague - not specific.
