### ISSUE TITLE
TestHarness --skip-config-checks is broken

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9645]
### Description of the enhancement or error report

The --skip-config-checks is broken. It appears that the default of PETSC_RELEASE_VERSION causes all tests to be skipped because it is never updated with this option.

### Rationale for the enhancement or information for reproducing the error

```./run_tests --skip-config-checks```

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This feature isn't widely used but is handy for certain test situations. It doesn't affect operation.

**Comment by permcody** [comment]
Looks like this feature has been superseded. It should just be removed.

**Comment by brianmoose** [comment]
FYI, I think raven uses this so they can use the test harness without using libmesh.

**Comment by permcody** [comment]
Closed by #9760.
