### ISSUE TITLE
Grab header from input files for inclusion in Moose Markdown

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9654]
### Description of the enhancement or error report

We'd like to grab the text at the top of input files for inclusion into the MOOSE Markdown files. Display the text as pre-formatted (fixed-width) in the HTML rendered page.

### Rationale for the enhancement or information for reproducing the error

New enhancement

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Better usability - none

**Comment by aeslaughter** [comment]
see #9657

**Comment by permcody** [comment]
#9760 was referenced in error - ignore
