### ISSUE TITLE
Add CSVTimeSequenceStepper

### ISSUE THREAD

**Issue by agiorla** [idaholab/moose#9698]
### Description of the enhancement or error report
Add a CSVTimeSequenceStepper that reads a sequence of time steps from a CSV (or similar file)

### Rationale for the enhancement or information for reproducing the error
Provides the user the possibility to input time sequences from CSV-like files (for example from previous simulations), which is more practical with very long time sequences

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Add one new TimeStepper class and associated unit test

**Comment by permcody** [comment]
Just an FYI - We have a CSV reader in MOOSE. You should be able to use that utility and existing time steppers to make this work without writing a bunch of new code.

**Comment by agiorla** [comment]
Yes, that's what I used ^^
