### ISSUE TITLE
Recovery segfaults with new contact_adaptivity test

### ISSUE THREAD

**Issue by roystgnr** [idaholab/moose#9703]
### Description of the enhancement or error report

We get a segmentation fault on our new contact_adaptivity test, which may hint at underlying problems with recovery + AMR + stateful material properties.

### Rationale for the enhancement or information for reproducing the error

Using a build incorporating #9702, remove the ```recover = false``` line from modules/combined/test/tests/contact_adaptivity/tests, then run ```./run_tests --recover --re 'contact_initial_adaptivity'```

When running the new test with --recover, the second half of the test segfaults (even in dbg mode, with no preceding assertion failure!) at the line ```p->load(stream)```, MaterialProperty.h:96, because ```p``` is null here.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

This probably extends to other combinations of adaptivity, recovery, and stateful material properties.  I don't know how extensive the fix might need to be.

**Comment by permcody** [comment]
MOOSE disables repartitioning for any AMR + stateful material run because we don't have the ability to redistribute material properties. Maybe with all of the tweaking of turning renumbering on/off, we have one more corner case left for dealing with this specific combination during recovery.
