### ISSUE TITLE
MooseDocs content re-organization?

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#9728]
@idaholab/moose-team I need opinions on the following, it would be a large change to MooseDocs, but may make life easier in the long run. I am not complete sold on it, so I need opinions, which I know you all have.

### Description of the enhancement or error report
I am floating the idea about organizing documentation content to be located within the framework and submodule directories.

### Rationale for the enhancement or information for reproducing the error
Applications are beginning to include documentation from MOOSE and modules in their own applications. Currently the framework/modules documentation can cross link across modules. Therefore, when an application is including documentation (e.g., from Tensor Mechanics) the module might link to other modules that are not part of the application, thus creating a situation where the application cannot have a clean documentation build. 

To help manage this, I propose that all framework documentation exist in framework/docs and be self contained. Similarly, each module should include framework documentation, but otherwise be self contained. Finally, the current moose/docs would pull in all the docs from framework and modules to build the main site. The main advantages include making sure that modules documentation does not cross link, so application can use it, and it would be possible to build docs at  a framework and module level which will reduce compile times and docs building.

When I started the MooseDocs I was going to do this, but could not due to how the YAML dump was formatted. However, we have now the JSON dump which provides better information. So this should now be possible.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
This changes how we write and organize documentation, this would impact everyone using the MooseDocs system.

**Comment by rwcarlsen** [comment]
Seems reasonable to me.
