### ISSUE TITLE
Add a pre-build step in the Makefile

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9732]
### Description of the enhancement or error report
Add a target in the MOOSE build system that is always executed before the main build.

### Rationale for the enhancement or information for reproducing the error
Some apps (cough) require a build step _before_ any source files are built.

### Identified impact
Added capability

**Comment by YaqiWang** [comment]
Ah, Rattlesnake actually has one, which applies a small MOOSE patch before the main build. In this way, more print-outs can be added in case that tests fail on test boxes but cannot be reproduced locally...

**Comment by permcody** [comment]
We decided not to do this. Closing...
