### ISSUE TITLE
`tests/controls/time_periods/dgkernels/dgkernels.i` fails with mpiexec -n 4 on linux with distributed mesh

### ISSUE THREAD

**Issue by andrsd** [idaholab/moose#9735]
### Description of the enhancement or error report

The test segfaults on 4 procs. Runs fine on 2 procs.

### Rationale for the enhancement or information for reproducing the error

1. compile on linux
2. run `mpiexec -n 4 ../../../../moose_test-dbg --n-threads=1 -i dgkernels.i --distributed-mesh`

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Unknown.

**Comment by brianmoose** [comment]
As an additional note, this problem was introduced in #9456 , it was working fine before.

**Comment by YaqiWang** [comment]
I will take a look to see if there is any obvious reason.

**Comment by andrsd** [comment]
Most likely [this](https://github.com/idaholab/moose/pull/9736/commits/387b28d61645915686fa6785913db2761121799c)

**Comment by YaqiWang** [comment]
Oh, great. Let us see if it can fix the test.
