### ISSUE TITLE
Guarantee::CONSTANT_IN_TIME incorrect and/or too strict

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9749]
### Description of the enhancement or error report

In TensorMechanics we ```issueGuarantee(_elasticity_tensor_name, Guarantee::CONSTANT_IN_TIME)``` in various ElasticityTensor classes.  However, in ```ComputeElasticityTensorBase``` there is a ```elasticity_tensor_prefactor``` Function that may be time dependent.  If that's the case then suddenly our guarantee isn't correct.

I'm unsure of what's a nice way of getting around this.

Another related problem is that our guarantee is too strict in some cases that are important to me.  As far as I can see, when we check the guarantee we actually only need a zero time derivative between the start time and end time of the particular time step.  This isn't just being pedantic.  In my simulations I might choose to have a time-varying elasticity tensor, but it is actually constant for t<=0.  Then it's physically meaningful to apply initial stresses.  Only for t>0 does my elasticity tensor start to change.  But the current setup of MOOSE forbids me to do this.

Looking for comments from @sapitts , @bwspenc , @dschwen 

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by dschwen** [comment]
We need to check if the prefactor material property issues that guarantee as a necessary prerequisite.

**Comment by WilkAndy** [comment]
The prefactor is just a Function.  We could revoke the guarantee if the prefactor has been supplied by the user, but we'd have to do that in all derived classes.  I don't think we can revoke the guarantee in the base class (```ComputeElasticityTensorBase```) as its constructor is called before the derived classes' constructors.
