### ISSUE TITLE
Input file include directive support

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#9755]
### Description of the enhancement or error report

Some around these parts were thinking it might could somewhat maybe potentially be sort of a little bit useful to introduce some kind of "include" syntax support for moose input files - i.e. allow some syntax to cause the contents of another file to be pasted into the file.  There are two implementation approaches we could take:

1. pre-processor approach:  The include directive/syntax doesn't have to be valid getpot/hit syntax.  We would have more freedom choosing the syntax, but then this becomes its own language that needs separate definition/implementation in addition to files that include the directive not being validatable (syntax-wise) without always first running the preprocessor and having substituted files available.

2. post-processor approach: include directive/syntax is more limited - must be valid getpot/hit.  Files with unprocessed includes are still valid and can still be parsed/validated.  Can use all existing functionality in hit API for building post-processor and operating on the syntax tree.

I prefer option 2.  The two basic options for syntax would be:

* ``[include:path/to/file][]``
* ``include = path/to/file``

We can change what the actual word (i.e. ``include``) is and/or perhaps add some special character(s)?  @idaholab/moose-team @dschwen @sapitts @bwspenc - thoughts?

### Rationale for the enhancement or information for reproducing the error

Help users reuse input file content and refactor larger input file setups into smaller digestible pieces.

### Identified impact

None - just adding a new input file syntax that shouldn't affect existing valid inputs.

**Comment by dschwen** [comment]
I have no strong opinion but out of option 2 I would prefer variant 1.

**Comment by andrsd** [comment]
If we went with `include = path/to/file`, would not that prevent people from creating an input parameter with name `include`? Like in this example:
```
[Block]
  [object]
    include = path/to/file
  []
[]
```

**Comment by rwcarlsen** [comment]
@andrsd - Correct.  If we go with the bare parameter approach, I would suggest making the include word more "special" with maybe a (valid hit) special character like ``+include``.

**Comment by andrsd** [comment]
Yeah, a special character in front of it should do the trick, but then I'd say let's drop the `=`.

**Comment by rwcarlsen** [comment]
Dropping the ``=`` makes it invalid syntax - that would require approach 1.

**Comment by dschwen** [comment]
I find the _pseudo parameter_ approach confusing.

**Comment by rwcarlsen** [comment]
I also am not a big fan of the parameter approach - it is easier for a (human) reader to not notice or to get lost among the other parameters.  The block header syntax is more obvious and indicative of something special going on.

**Comment by dschwen** [comment]
If you are supporting variable expansion you could also use an approach similar to Makefiles

`${include path/to/file.i}`

**Comment by YaqiWang** [comment]
If `include` file is only allowed on 0-th level, problem is gone.

**Comment by rwcarlsen** [comment]
@dschwen - but that would still have to go inside a parameter value/string - it can't just float by itself.  It feels a bit odd to have a parameter-value-level initiated construct cause syntax-tree level rewriting.

**Comment by andrsd** [comment]
> Dropping the = makes it invalid syntax

Since the parser is under our control now, we can define new syntax for our needs.

**Comment by rwcarlsen** [comment]
@andrsd - yes, but for my comments, I was replying in the context of approach 2.  You are proposing

3.  new syntax approach: modify the hit language to include a special include directive.

I am not really a fan of this approach.  It requires creating new hit APIs and mucking with parsing logic which is much more tricky than a few simple (already trivially supported) AST operations.

**Comment by permcody** [comment]
@friedmud - you might want to chime in on this thread.

**Comment by andrsd** [comment]
I think that adding a new lexeme and syntax that implies file inclusion is cleaner approach than reusing the current syntax and assign it a meaning based on a context. As long as the language is LL(1), parsing is trivial and enhancing the grammar is trivial as well.

However, if most people will agree on 1 or 2, then be it.

**Comment by permcody** [comment]
@YaqiWang brings up a good point. Where would this parameter be valid? If you nested it under, say the `[Kernels]` block would you allow that block to be absent in the included file? I would vote against this, but we have to decide exactly how this should work. Forcing it at level-0 might be a good restriction.

I want to see some use cases. Right now, I feel like we are solving a problem that we haven't invented yet. I'm sure there are people out there that think this is a "nice to have" but are there any strong drivers?

**Comment by rwcarlsen** [comment]
@permcody - The include mechanism should be plain simple - literally pasting the contents of the included file where the include directive is.  I think would be a bad idea to try to do anything more sophisticated.

@andrsd - It is LL(1).  And it would certainly be aesthetically cleaner, but not necessarily a cleaner implementation.  I wouldn't be entirely opposed to adding an official "directive" extension syntax to the language - where we parse the directives as directive nodes.  But I'd still rather have plugins/extensions" perform the actual logic that decides/executes based on the directive.

**Comment by dschwen** [comment]
If you do 
`#include "path/to/file.i"`
it would be a valid HIT file (comment)...

We could syntax highlight this to make it clear it is a directive.

**Comment by fdkong** [comment]
> If you do
> #include "path/to/file.i"

I like this one. 

> it would be a valid HIT file (comment)...
> 
> We could syntax highlight this to make it clear it is a directive.

**Comment by rwcarlsen** [comment]
I think it is a bad idea to have comments be anything other than computer-ignored notes for human readers.  If you use comment syntax, you can't comment out or toggle between include directives.  It also becomes tricky if you are looking for a problem that cropped up, but you keep ignoring changes to comments because "how could a comment make my test fail?".  It is nice to keep comment changes as benign - it makes code review much easier.

**Comment by andrsd** [comment]
@dschwen I am definitely against assigning a special meaning to comments. Bad idea.

**Comment by andrsd** [comment]
@rwcarlsen Directives would be fine with me.

**Comment by dschwen** [comment]
>  If you use comment syntax, you can't comment out or toggle between include directives.

Of course you could `##include ...`
But I can see how that is not an ideal solution...

**Comment by rwcarlsen** [comment]
On the directive syntax front we could do something like:

```
!directivename "arg with spaces" arg-without-spaces...
```

**Comment by friedmud** [comment]
I read through the options here... let me chime in:

1.  I have not been the biggest fan of "include" capability.  I really worry that it's going to create a monster: spaghetti input files no one can understand when the "right" answer is to write custom Actions instead.

That said...

2.  Let's stay away from `#include`... comments should be comments... and we don't want this to get confused with the actual C++

3.  So far I like `+include "path/to/foo"`

**Comment by rwcarlsen** [comment]
For original issue - see #2504.

**Comment by rwcarlsen** [comment]
I am also hesitant to introduce functionality like this.  Maybe it would be better to encourage users needing this type of thing to use their own text templating solutions.

If we move forward with this, we also need to decide how we want to handle including files that include files - do we disallow it?  And all the problems mentioned in #2504 like cyclical includes and having trouble piecing together all the right files in the right way to make a simulation work.

**Comment by andrsd** [comment]
So, one possible use case for this would be in RELAP-7. Let's say I develop a complicated control logic setup and want to reuse it. I can imagine that users will not want to write custom actions (they are just code hamsters, not code monkeys), but including a section into an input file would be very welcome.

This could apply for plant models as well.

But again, it is more of an option at this stage, because nobody really asked for this just yet.

**Comment by tophmatthews** [comment]
Did this go anywhere @rwcarlsen @dschwen ? Is there a way to include another file via input file with the new parser?

**Comment by rwcarlsen** [comment]
Current moose does not support this.  I've done some work to add this functionality, but finishing it is currently not a priority right now.  So - you'll get it probably sometime between a month from now and a few years from now.

**Comment by tophmatthews** [comment]
> So - you'll get it probably sometime between a month from now and a few years from now.

well, at least you're honest :)

**Comment by YaqiWang** [comment]
Not sure if this is related. I'd like to create an input file for a subapp in a master `action` based on the master input file. The subapp input file will possibly reuse `Mesh`, `Materials` blocks and have few minor changes in `Executioner` and some other blocks. I was hoping to have something like
```
parser.removeBlock(const std::string & input_block_name);
parser.removeParam<T>(const std::string & path_to_param);
parser.addParam<T>(const std::string & path_to_param, const T & value);
parser.writeInputFile(const std::string & new_file_name);
```
If this is unrelated with this issue and deserves another separate issue, please let me know. Tag @permcody @rwcarlsen @friedmud

**Comment by rwcarlsen** [comment]
@YaqiWang - I think that is a bit different.  Currently you can generate HIT syntax to write to a file using the hit API, but there is no way to do any sort of validation until you try to initialize a simulation with it.  In order for you to clone/modify certain portions of the master input file, we would need to expose the parsed hit tree through a public API.  Currently it is hidden inside the Parser object.  @permcody - what do you think about exposing the parsed hit tree to the world?

**Comment by dschwen** [comment]
I have stated my opinion why I now think and `include` directive is a bad idea elsewhere. Let me dig it up...

**Comment by friedmud** [comment]
After a lengthy discussion on Slack - I think we settled on `!include` being used as direct substitution... but only allowed at the top level.

Also:  HIT will make the following true:

```
[SomeBlock]
  junk = 8
  stuff = 10
[]
[SomeBlock]
  stuff = 12
  otherstuff = 14
[]
```
Will be equal to:
```
[SomeBlock]
  junk = 8
  stuff = 12
  otherstuff = 14
[]
```

This is the way it always was in GetPot of old.
