### ISSUE TITLE
Cannot use a new boundary name like 1_something?

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9765]
### Description of the enhancement or error report
Today someone try to use mesh modifier to add a new side set with the new name as `1_2`. But then MOOSE combined the newly added sides into an existing side set into `1_2` and erased the existing side set. Looks like it is this line causing issue:
https://github.com/idaholab/moose/blob/devel/framework/src/mesh/MooseMesh.C#L1025

I suspect that `1_2` string successfully converted to id=1. If so, that line is not safe and need to be fixed. I do not think `1_2` is a valid number though.

### Rationale for the enhancement or information for reproducing the error
Fix insanity.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
I am surprised that nobody hits this before.

**Comment by permcody** [comment]
We have hit this before. Starting of names with numbers is a bad idea in
general but it really fails here. Yes it can be fixed.

**Comment by YaqiWang** [comment]
Thanks!
