### ISSUE TITLE
Chemical reactions documentation and example

### ISSUE THREAD

**Issue by cpgr** [idaholab/moose#9769]
### Description of the enhancement or error report
Adds documentation of chemical reactions module

### Rationale for the enhancement or information for reproducing the error
Chemical reactions module is poorly documented

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)
Make this module easier to understand for a new user

**Comment by permcody** [comment]
Closed by #9770.
