### ISSUE TITLE
Add framework test for CoupledTimeDerivative

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#9786]
### Description of the enhancement or error report

Don't currently cover CoupledTimeDerivative in the framework test suite.

### Rationale for the enhancement or information for reproducing the error

Even though tests exist for this kernel in the phase field module, a framework kernel should have a framework test.

### Identified impact

Improve our code coverage.

**Comment by lindsayad** [comment]
@dschwen Do you have a favorite test that could be put in the framework test suite? Other than reading issue #5286, I've no other experience in the use of `CoupledTimeDerivative`/how it should it behave.

**Comment by permcody** [comment]
If he does, great. If not, don't worry about making a realistic simulation. Just couple in some variable (we love using Diffusion with Dirichlet conditions) and use that to compute the DT. It's super easy to verify the correct solution that way.
