### ISSUE TITLE
Add vector-less fill API to RankFourTensor 

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9790]
### Description of the enhancement or error report
RankFourTensor has a bunch of fill calls that all pass around std::vectors with runtime length checking. Length is in many cases known at compile time. 

### Rationale for the enhancement or information for reproducing the error
Fewer temporary containers and runtime size checking. Should be faster.

### Identified impact
Added capability

**Comment by mangerij** [comment]
How exactly is something "known" at compile time? Isn't it different for every system?

**Comment by dschwen** [comment]
Very philosophical question... ...d we ever _really_ know anything at compile time? 🤔 

D'Uh, of course we do! 

* [Here](https://github.com/idaholab/moose/blob/devel/modules/tensor_mechanics/src/materials/ComputeVariableIsotropicElasticityTensor.C#L100)
* [Here](https://github.com/idaholab/moose/blob/devel/framework/src/utils/RankFourTensor.C#L732)
* [Heeeere](https://github.com/idaholab/moose/blob/devel/framework/src/utils/RankFourTensor.C#L759)
* [aaand here](https://github.com/idaholab/moose/blob/devel/framework/src/utils/RankFourTensor.C#L771)
* and... gee, look for yourself! Whenever the second argument to `fillFromInputVector` is hardcoded we know it _at compile time_.
