### ISSUE TITLE
Peacock 2 Mesh Highlighting Workflow Worse than Peacock 1

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9800]
### Description of the enhancement or error report
I understand why someone would think that checkboxes are better: why not be able to turn on multiple?  But they aren't.

Several reasons:
1.  This is the big one: with Peacock 1 you could easily select the "Boundaries" or "Blocks" drop-down and use the up/down arrow keys on the keyboard to scroll through them and quickly see that everything was good
2.  It does no good to highlight more than one because they are all drawn in red and there's no way to tell what's what
3.  Going through all of them is now painful.  You have to click (in-fact, using the keyboard arrows and space bar to try to select blocks/boundaries in the lists doesn't even work... but even if it did it would be clunky) on each one... then un-click then click the next one.  Takes forever if you have more than a few blocks/boundaries/
4.  It feels like Paraview.  Very clicky...
5.  It wastes space.  The dropdown boxes were very small.

Let's return these to dropdown boxes underneath the render window

### Rationale for the enhancement or information for reproducing the error
Just use it

### Identified impact
Peacock 2 workflow is not as streamlined as it could be for inspecting meshes

**Comment by brianmoose** [comment]
I agree that having a single drop down makes cycling through them much easier.
It would probably be very simple to make the keyboard shortcuts work with the current checkboxes. It looks like it is just responding to the wrong Qt signal.

I think it just boils down to whether there are use cases where someone might want to highlight more than one block/boundary/nodeset at a time.

@aeslaughter @permcody Thoughts?

**Comment by permcody** [comment]
Derek's arguments are pretty reasonable. I'm not sold on the change from the old peacock here, so I'd suggest returning to the previous functionality.

**Comment by aeslaughter** [comment]
Old behavior works for me.
