### ISSUE TITLE
Add normal and lognormal distributions to the stochastic tools module

### ISSUE THREAD

**Issue by cbolisetti** [idaholab/moose#9813]
## Description of the enhancement or error report
Adding normal and lognormal distributions to the existing distributions in the stochastic tools module

### Rationale for the enhancement or information for reproducing the error
Normal and lognormal distributions are widely used in general. The immediate use will be for the stochastic simulations using Mastodon. 

### Identified impact
Adding two new distributions. These distributions will require external boost.

**Comment by aeslaughter** [comment]
closed by #9847
