### ISSUE TITLE
Add anisotropic Allen-Cahn kernel

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9821]
### Description of the enhancement or error report
Current Allen-Cahn kernel only works with scalar mobilities.

### Rationale for the enhancement or information for reproducing the error
Needed by external user P.T. Shower

### Identified impact
Added capability

**Comment by pt6** [comment]
Thank you for working on this! After seeing some in-situ TEM of precipitate growth in my alloy system, I'm convinced that anisotriopic phase mobility will be the key to understanding the far-from-equilibrium shapes that the precipitates assume. I'm sorry I couldn't sort out the issue myself, let me know if there's any useful input I can have.

**Comment by pt6** [comment]
Have you had any luck with this? If it's too time consuming, I can do my homework and try to figure out how to impliment the new kernel. Once again, I appreciate all of the help the INL team has given me.

**Comment by pt6** [comment]
I'm not sure how you guys handle things like this, but is it likely that this issue will be addressed in a future version of MOOSE?

**Comment by dschwen** [comment]
The Allen-Cahn equation does not lend itself to the same type of change as the Cahn-Hilliard equation. The mobility here can not be a tensor. You could try implementing a material that returns `L` as a function of the order parameter gradient.
