### ISSUE TITLE
StickyBC - a poor man's version of a Constraint

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9826]
### Description of the enhancement or error report

Add a "StickyBC" to TensorMechanics.  This is a Dirichlet BC enforcing:

u = u_old if u_old satisfies a user-specified condition
nothing if u_old does not satisfy the condition

### Rationale for the enhancement or information for reproducing the error

When mining is simulated, the roof material collapses onto the floor.  Mining proceeds in a certain direction, excavating material, and at a certain distance behind the working face, the roof will collapse.  In fact, this collapse is usually periodic: the roof can hold up for a while, and then the whole thing collapses, then mining proceeds for a bit with the roof holding up, and then it collapses again, etc.

Simulating this with MOOSE is quite difficult at present.  Constraints need to be placed on the roof to prevent it going through the floor, which is obviously unphysical.  The Constraints mean the simulation takes orders of magnitude longer to converge compared with a similar model with no Constraints.

"StickyBC" may solve this (I haven't yet tried).  I know the maximum displacement allowed of the roof - usually it's 3-4 metres downwards.  When MOOSE detects the vertical displacement it greater than this maximum displacement it simply fixes that roof node forever more in the simulation.  Of course there are approximations here!  But I'm hoping this will enable me to approximately simulate this important phenomenon.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Ability to mode the mining example above.

Any comments @sapitts , @bwspenc , @dschwen ?

**Comment by bwspenc** [comment]
This should work. I've done similar things in the past to activate or de-activate Dirichlet BCs based on certain conditions, and that works fine.  This particular BC seems pretty specific to your application, but maybe you can make it general-purpose enough that it would make sense to live in MOOSE.

**Comment by WilkAndy** [comment]
Cool, thanks for the comment @bwspenc 

a
