### ISSUE TITLE
Optimize computeElemValues for CONSTANT MONOMIALS

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#9836]
### Description of the enhancement or error report

Because constant monomials are constant over the element and only have one DOF per element, their calculations don't have to be repeated over dofs or over quadrature points.

### Rationale for the enhancement or information for reproducing the error

Constant monomials are frequently used and `MooseVariable::computeElemValues` shows up frequently in profiling. Reducing this compute time would be a decent optimization.

### Identified impact

Speed up MOOSE when performing calculations with constant monomials.

**Comment by permcody** [comment]
We have to be careful here. I believe it was always intended that you could compute values at the quadrature points and then integrate to produce the elemental value. This might be a design feature, not a flaw. Maybe @friedmud or @andrsd can chime in?

**Comment by andrsd** [comment]
What he is going to do is that instead of interpolating values into q-points, he will set the value directly, because we know what the value is.

**Comment by lindsayad** [comment]
Closed by #9837
