### ISSUE TITLE
Cannot Copy Out of "Python Script" View On Postprocessor Tab in Peacock 2

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9843]
### Description of the enhancement or error report
In Peacock 2 if you view the Python Script you can't copy out of the window that pops up showing you the script.

### Rationale for the enhancement or information for reproducing the error
Would be really nice to be able to make a change and then copy a line or two from the new script to something else.

### Identified impact
None

**Comment by brianmoose** [comment]
I can reproduce this. The first time the window pops up you can copy from the window. If you close it and reopen it you will no longer be able to copy.

**Comment by dschwen** [comment]
This is the sequel to #9052 :-D
