### ISSUE TITLE
canonical hit syntax format/style

### ISSUE THREAD

**Issue by rwcarlsen** [idaholab/moose#9845]
### Description of the enhancement or error report
Come up with a canonical style for MOOSE input files.  Create a tool for automatically formatting them nicely.  Style details should cover things such as:

* indentation: I like four spaces, but most files use two - I don't feel strongly either way.
* consecutive blanks lines: I think we should auto-collapse multiple blank lines to a single blank line
* leading "./": I think we should remove them
* closing "[../]": I think we should just use "[]" everywhere

Other ideas (that aren't too hard to implement)?  I have a mostly working prototype of something like this - it is pretty easy with the new parser.

### Rationale for the enhancement or information for reproducing the error

Make input files look nicer and more consistent.  Consistent indentation helps users spot errors and reason about input better.

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

No API or other incompatible changes required - just making things look nicer.

**Comment by permcody** [comment]
I don't think we should change the simulation parser without making corresponding changes in the python parser.
