### ISSUE TITLE
Page <title> for every documentation page is the same  

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9857]
### Description of the enhancement or error report
Page <title> for every documentation page is the same  (e.g. _MOOSE_ for framework and modules documentation. The template parameter (used in `website.html`-> `include/head.html`) is hardcoded in `website.yml`. The moosedocs build system should append a page title (object name etc.) to this.

### Rationale for the enhancement or information for reproducing the error
Makes it hard to navigate the history.

### Identified impact
Easier navigation

**Comment by aeslaughter** [comment]
This has been fixed.
