### ISSUE TITLE
How to build the library_path in moose

### ISSUE THREAD

**Issue by yongchangli** [idaholab/moose#9880]
When I running pika/problems/1D_full/1D_full.i   by moose, the error always shows that   

 *** ERROR ***
A 'ChemicalPotentialIC' is not a registered object.

We loaded objects from the following libraries and still couldn't find your object:
	(NONE)

Make sure you have compiled the library and either set the "library_path" variable in your input file or exported "MOOSE_LIBRARY_PATH".

But I can find the ChemicalPotentialIC.lo in pika/src/ics. 

It's my first time to use moose, it confused me more than two weeks, I hope some one can help me to solve it.
How can I solve this problem? How to add the library_path to pika? 

[1D_full.txt](https://github.com/idaholab/moose/files/1317784/1D_full.txt)

**Comment by aeslaughter** [comment]
This isn't a MOOSE issue, please put an issue in for Pika: www.github.com/idaholab/pika
