### ISSUE TITLE
ill-defined post-processor can lead to seg fault in parallel runs

### ISSUE THREAD

**Issue by novasr** [idaholab/moose#9889]
### Description of the enhancement or error report
A post processor that doesn't specify a block and operates on a variable that is defined only on one block of a multi-block mesh will run in serial, yet seg fault in parallel. @aeslaughter, I heard you were working on error checking that might catch this type of mistake.

### Rationale for the enhancement or information for reproducing the error
See attached input file and mesh (cubit journal file) to reproduce the seg fault.

### Identified impact
When running large simulations in parallel, this may or may not occur depending on mesh size, number of procs used, and partitioning. 

[multi_proc_error.txt](https://github.com/idaholab/moose/files/1319609/multi_proc_error.txt)
[two_block_demo.txt](https://github.com/idaholab/moose/files/1319610/two_block_demo.txt)

**Comment by aeslaughter** [comment]
I think this might be a separate case then what I was working on, I will have to play around with this a bit. That probably won't happen right away unless this is stopping you from working.

**Comment by novasr** [comment]
Not urgent.

**Comment by WilkAndy** [comment]
Perhaps more urgent than previously thought.  We had another question moose-users about this today.

**Comment by WilkAndy** [comment]
And the poor guy can't even use "block = XXXX" to make his simulation run!

**Comment by permcody** [comment]
@aeslaughter

**Comment by aeslaughter** [comment]
@permcody I will take a look today.
