### ISSUE TITLE
Broken build process

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#9921]
## Rationale
MOOSE framework does not compile. Most likely something is messed up in my environment, but the way this manifests when attempting to build MOOSE is confusing at best.

## Description
Running make fails with with

```
/Users/schwd/Programs/moose/framework/include/base/Moose.h:18:10: fatal error: 'libmesh/perf_log.h' file not found
#include "libmesh/perf_log.h"
```

The file exists in the proper location, though! Looking at the `make -n` output reveals

```
[...] -I/Users/schwd/Programs/INL/grizzly/include/vectorpostprocessors -I -I/Users/schwd/Programs/libmesh/installed/include [...]
```

note the empty `-I`, which causes the following `-I` option for the libmesh include directory to be ignored.

## Impact
Confusing build breakage.

**Comment by dschwen** [comment]
Ugh, ok, the bug is at the app level, when setting a non existing SOMEAPP_DIR the directory is added to the list as an empty string...

**Comment by lbb92** [comment]
How to solve this problem without reinstall?

**Comment by dschwen** [comment]
Reinstall won't help. This points to a bug in the application makefile. Hard to say more without further details from you.
