### ISSUE TITLE
Parser: Integrity checks for subapps is not occuring

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#9929]
## Rationale

It looks like we aren't doing some of the parser checks on subapps (multiapps). This is because the current check is embedded in `MooseApp::executeExecutioner()`, which is never called on subapps. 

## Description

We need to make sure we have the same input file checking occuring on subapps as we do in the main app.

## Impact

Improve framework robustness

**Comment by rwcarlsen** [comment]
This was fixed by #9938.
