### ISSUE TITLE
RunException tester passes if "expect_err" is not provided.

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#9933]
## Rationale

If you create a RunException test, but forget the "expect_err" parameter the tests passes.

## Description

Do the following for the simple diffusion "tests" file.
```
[Tests]
  [./test]
    type = 'RunException'
    input = 'simple_diffusion.i'
#    exodiff = 'simple_diffusion_out.e'
  [../]
[]

```

## Impact

Without fixing this it is easy to create RunException tests that don't test anything.

**Comment by permcody** [comment]
Wow - That one is very old:2c9513abcf1612c338a6f2c30279cde8c76899ba
