### ISSUE TITLE
Please Bring Back Ability To Switch Between Auto and Static Bounds In Exodus Viewer In Peacock

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9934]
## Rationale
New Peacock is missing the radio buttons that allow you to switch between `Auto` and a set "static" min/max for the coloring/legend that existed in Peacock 1.  It seems like if you enter a number and press Enter that will set it to a static bound... but to make it go back to Auto you have to clear the box and hit Enter.

This is annoying for a couple of reasons:

1.  Annoying to have to clear the box to get to Auto
2.  My normal workflow is to find a frame that represents the min/max I want and then switch the radio button over to the "static" mode to hold them there.  That worked fine in the old Peacock... but there's not really a way to do that in the new Peacock.  You have to modify the value in the textbox and press Enter to get it to "stay"... but I don't _want_ to modify it... I just want it to stay!

(Ninja Edit:
3.  It's also non-intuitive currently... there's nothing about the interface that tells you that the current behavior does what it does)

## Description
Run any simulation with a changing min/max and try to switch back and forth multiple times between "auto" and "static" numbers... you'll see how sub-optimal it is now.

## Impact
Just less efficient workflow.  It technically "works" currently... just not as efficiently.

**Comment by aeslaughter** [comment]
I like the new behavior. 

My workflow is to enter a value that I know I want, (i.e., that matches a boundary condition) then leave it alone. In old peacock I would always type a value in the box, forget to press the button, and then the value would be removed.

**Comment by permcody** [comment]
Ha - This is actually why I like preferences. I'm pretty happy that the new peacock is starting to add them. There's no way to make a GUI that suites everyone's workflows. Just take a look at Visit and Paraview!

**Comment by friedmud** [comment]
@aeslaughter I'm not for the value being "removed" (that shouldn't happen... and I don't remember it happening in old Peacock).  The value should stay there until you explicitly click it back to `Auto`.

The new way to do this is completely unintuitive.  There is absolutely nothing about those text boxes that tell you how interacting with them is going to impact things.

This is not a preference thing.  This is a usability thing.  Please don't make Peacock 2 a preference nightmare like Paraview / Visit...

**Comment by friedmud** [comment]
Not really - one is simpler than the other.  This one is just about having
the ability to switch back and forth easily while remembering the value
that was there.

The other one is about having it remember _per variable_.

**Comment by aeslaughter** [comment]
closed by #11627

**Comment by friedmud** [comment]
👍 awesome - thanks for working on this!
