### ISSUE TITLE
Allow double registering of MOOSE objects using different names

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#995]
We should allow double registration of names and allow deprecation of old names.  Derek and I chatted about changing Diffusion to Laplacian but that kernel is used everywhere.  Perhaps for now we should just double register the name, eventually we will deprecate one of the names and then eventually remove the old name altogether.  We'll need a little more machinery in the Factory and Parser to make this all smooth.

**Comment by jwpeterson** [comment]
I think this already works via `registerDeprecatedObjectName`.  For example:
```
registerDeprecatedObjectName(FunctionValuePostprocessor, "PlotFunction", "09/18/2015 12:00");
registerPostprocessor(FunctionValuePostprocessor);
```

**Comment by permcody** [comment]
Well this was more so we could refer to the same object with different names. It was just an idea and I'm fine with abandoning it since it would lead to confusion. People would be off looking for objects that don't exists (in this case "Laplacian").
