### ISSUE TITLE
MooseDocs markdown import needs to be smarter

### ISSUE THREAD

**Issue by aeslaughter** [idaholab/moose#9951]
## Rationale

As we add documentation that is included in other applications the ability to grab markdown content 
from the framework must be flexible to allow for entire modules to be included without getting um-wanted files.

## Description

You can reproduce the problem by adding a new file to MOOSE, if the file is not included in the app it breaks.

## Impact

Improving the import should lessen the burden for keeping include/exclude lists up-to-date.

**Comment by aeslaughter** [comment]
@sapitts I am working on making things better, stay tuned to this issue.

**Comment by permcody** [comment]
I'm not exactly sure of what this ticket means. Are you talking about just referring to other markdown files, are are you downloading something?

If it's the later, I just don't want you to head down a whole where there are solutions. "wget" has been around forever and does expert level mirror of file data for websites including fixing up all links. There's probably a python API for it as well. It may or may not be applicable for this need though.

**Comment by aeslaughter** [comment]
> I'm not exactly sure of what this ticket means. Are you talking about just referring to other markdown files, are are you downloading something?

This is just referring to other markdown files: e.g., BISON getting markdown from MOOSE.

**Comment by sapitts** [comment]
Thank you @aeslaughter ; I truly appreciate your work on the documentation system and your help with our Bison version
