### ISSUE TITLE
CRITICAL!  Peacock 2 _Destroys_ Input File Changes When It Reloads A Binary!

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9974]
## Rationale
‼️‼️‼️

This is absolutely critical!  Peacock 2 can erase (potentially a lot of) work!

In Peacock 2 if you edit a parameter on the Input File tab... but _don't_ save the input file.  Then you change your code and recompile to create a new binary... Peacock 2 dutifully, automatically reloads the binary... and when it does it *_resets_* any and all parameter changes that have been made and not saved!

In fact: even if you edit a parameter and Run on the Execute tab... it will _still_ destroy your parameter edits.

This has silently killed me several times tonight!  Took me a while to figure out what was happening and I lost quite a bit of time to it because I would just go ahead and click `Run` again after recompiling my application... and the code would run with old parameter values!

## Description
See Above

## Impact
Critical bug in Peacock 2 that can cause loss of work.

**Comment by friedmud** [comment]
This one really is critical... still losing edits (and lots of time) to this this morning....

**Comment by brianmoose** [comment]
So what is the desired behavior? Ask the user to save the current input file (if changed) before loading an executable? The syntax of the new executable could be dramatically different, so we can't assume that whatever you are currently working will be valid with the new executable.

**Comment by friedmud** [comment]
This is not at all fixed... see my coment on #10006 

Why are you changing this behavior at all?  The old Peacock worked fine for 8 years... not one sole complained about the fact that it reloaded the binary and left the input file alone (as it should).  While I'm developing I don't want to have to save the input file or reload it or anything.

I don't get it.

**Comment by brianmoose** [comment]
The syntax of the new executable could be dramatically different. Hard paths that used to be there could be gone. What do you want to do with those? Trying to run the input file will fail but there would be no way to fix the input file because those paths don't show up in the editor any more.

**Comment by permcody** [comment]
Yes, it all comes down to assumptions of how people work. The syntax can change and often does but @friedmud's assumption is that it's only parameters changing, not blocks. The old Peacock does indeed fail in the latter case. However, for the normal case, where you are just changing logic and maybe tweaking parameters, leaving the file alone is handy. From a correctness point of view, @brianmoose is right here.

There may be a compromise here. Perhaps the input file could be left alone if syntax doesn't change, or we could warn people that they need to save if we are reloading syntax. I'm open to ideas.

**Comment by friedmud** [comment]
The reason I don't buy this argument is because there is no reason to believe that what's currently on disk matches the new syntax either: there is no way to know.

The best you can do is NOT destroy information.  Just leave things as they are.

I'm ok with a warning that Hard Paths (Blocks) changed, if they do, when you reload the binary... but no information should ever be lost.

I actually don't thik old Peacock failed in this area.  What it would do is leave the old block there in the tree alongside the new block.

For instance: if you have an input file loaded with a `[Kernels]` block in it and then you go change the syntax to `[AllKernels]`... it should NOT at all destroy the `[Kernels]` block.  Just leave it there!  That might represent hours worth of work getting something just right.  Yes, the tree would have `[Kernels]` and `[AllKernels]` in it - but so what?  At least previewing the input file would still show all of your hard work and then you can copy that out and save it and then rebuild it with the new syntax or whatever. 

This is my point: please do the most you can to not destroy work.  It can't always be perfect... but don't let "perfect" be the enemy of "good enough"...

**Comment by friedmud** [comment]
Just got this for the first time: and it represents _exactly_ what I'm talking about:

<img width="1497" alt="reloading" src="https://user-images.githubusercontent.com/870705/31580985-d5558682-b12c-11e7-8dff-da647fc10e35.png">

I have "in-flight" changes to a test file that I _don't_ want to save at all... nor do I want them destroyed.  I just want to reload the binary and keep moving.

Not only that - but the new behavior "yanks" me to the virtual desktop containing Peacock when I recompile my application.  That's really not cool!

**Comment by friedmud** [comment]
Just another ping on this... just got this again... and again it puts me between a rock and a hard place.  In-flight edits are currently for debugging... I don't really want to save over my input file on the disk... I don't really want to "save" them at all... I just want to reload the binary...

<img width="1399" alt="bah" src="https://user-images.githubusercontent.com/870705/31690685-785e1610-b361-11e7-90ee-811cb137b479.png">

**Comment by permcody** [comment]
Seems like a dangerous game no matter what. I don’t trust peacock to not
crash so inflight edits are already a gamble. I guess yet another
workaround would be to all the user to save to a different file name? Still
doesn’t help if you really want changes to stay loaded in-between binary
changes. Since we are going with preferences these days. Perhaps we could
make this particular choice preference driven. Allow users to just do what
they want if they know that they aren’t going to break the syntax between
compiles.

**Comment by brianmoose** [comment]
I thought we were going to try to detect incompatible syntax changes and only show the dialog in those cases (if the user has changes in the incompatible syntax). Otherwise just keep the user changes and go. Apparently this would be fine 99.999% of the time

**Comment by permcody** [comment]
Right, if you can do that great! Exactly 99.999%!

**Comment by friedmud** [comment]
Still don't really understand the issue - we literally never ran into this
being a problem in the old Peacock.  Like: it was never a thing... the data
in the tree was just left in the tree... simple as that.
