### ISSUE TITLE
Critical! Peacock 2 _Destroys_ blocks that are "deselected"!

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9976]
## Rationale
‼️‼️‼️

This is a *critical* defect in Peacock 2!  If you have any blocks that are "unselected" (their checkbox is not checked) Peacock 2 does NOT write them to the input file if you save!  That means that if you are unlucky enough to save over your old input file you could wipe out tons of work (like I just did)!

That's not at all how unselected blocks should work!  When you deselect a block it should use the `active` capability to set all the blocks that are checked as `active` and leave out the deselected block.  The block should still defnitely get written to the input file!!!

## Description
To see this... just open up any input file... deselect a BC or Kernel and then save out the input file... the deselected block is completely deleted!

## Impact
Potentially losing TONS of work.  If you happen to deselect a few blocks and are unlucky enough to press `Save`... then you just ZAPPED anything and everything in those blocks.  Ugh.

**Comment by brianmoose** [comment]
If the top level parent block is deselected, for example "BCs", then the whole "BCs" block wouldn't be written out, losing any children and changes. That is the desired behavior?

How do we want to handle hard paths, for example "Exectioner/Adaptivity"? If they modify it then deselect it, we still need to write it out and make it inactive? That could get annoying unless there is a way to say "really don't write this block out". The difference being that on a user added block if you want to do that you can just delete the block, something you can't do with a hard path.

**Comment by friedmud** [comment]
At least start by just copying what old Peacock did.  It did the most sane thing to try to save as much work as possible.  Yes, top-level blocks that are commented out were removed.

If we want to fix that we can just as easily allow `active` at the outermost level as well.

I don't understand the issue with hard paths.  Why is it "annoying" to make them inactive?

**Comment by brianmoose** [comment]
The issue with hard paths is that there would be no way to toggle actually writing it to the input file. If I just go and mess around with the parameters in a hard path then decide that I really don't want to include those, those changes will still be written out and the section marked as inactive, cluttering up the input file with things that I don't want.

**Comment by friedmud** [comment]
Understood - can we at least get back the Peacock 1 capability for now...
and then we can handle hard-paths / outer-blocks after some brainstorming?

We should save as much as we can...
