### ISSUE TITLE
Documentation system should allow use of mbox

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#9980]
## Rationale

I'm pretty sure our documentation system doesn't allow the use of \mbox, but I'd like it to, please.

## Description

For instance, if you look at 

http://mooseframework.org/docs/PRs/9939/site/documentation/systems/Kernels/tensor_mechanics/InertialTorque/index.html

you'll see LaTeX errors that probably result from my use of an \mbox inside an equation.

## Impact

Ability to write documentation using \mbox.

**Comment by permcody** [comment]
Good question. There are always a few things that are hard to reconcile between building web pages and PDF documents. There are many ways to create boxes in web pages that are different from creating boxes in PDF documents. I'm not sure we'll be able to support this, but we can take a look. Perhaps somebody can suggest an alternative method for creating the look that you want?

**Comment by WilkAndy** [comment]
I think i primarily use this for displaying "1/2" as a small fraction, eg $$b = \mbox{$\frac{1}{2}$}a$$ (for b = (1/2)a) so that things look nicer in equations.  Almost definitely there is another way of achieving my goal in this case.

**Comment by cpgr** [comment]
I think you can use `\tfrac{1}{2}` to get the desired result

**Comment by WilkAndy** [comment]
Thank you @cpgr.  I'll try that.   For future readers (probably only Cody!): close this issue if you like.

**Comment by permcody** [comment]
Maybe, I'd like to capture all this information on one of our MooseDocs help pages. 

The need to generate MooseDocs offline we hope will be useful for stable releases of our (your) software. It'll be handy to build the docs and let them remain static over time. It doesn't make sense to only have live versions of everything which is why we have done this.

**Comment by aeslaughter** [comment]
We are now using KaTeX for math, we are limited to what they support: https://khan.github.io/KaTeX/function-support.html

**Comment by WilkAndy** [comment]
That KaTeX page is a great resource.  I wanted to edit mooseframework.org to include a link to it, but i no longer seem to have editing rights, boohoo.  Could you please add a "dot point" to the "Moose development" section of http://mooseframework.org/wiki/  that contains a link to that page?   Or put the link somehwere else if you can think of a better place.

**Comment by aeslaughter** [comment]
There is a link in the MooseDocs documentation: http://www.mooseframework.org/docs/moose_docs/site/utilities/moose_docs/moose_markdown/extensions/katex/index.html

**Comment by WilkAndy** [comment]
!!!   I didn't even know those pages existed !!!   A clear link should exist from http://mooseframework.org/documentation/  (i suggest right up the top of that page) to http://www.mooseframework.org/docs/moose_docs/site/index.html .   Or maybe there's a link and i'm just being blind.

**Comment by permcody** [comment]
Yeah, I've learned the hard way as well trying to find documentation about the documentation system! Basically it's all in the MOOSE Docs area but the question is how to make these things easier to find? Sometimes the answers are right there but you don't know what you are looking for? Maybe we need to build a FAQ or something and start populating it.

**Comment by permcody** [comment]
Oh, and one more thing. We aren't editing the wiki or other parts of the mooseframework.org site on purpose. All of our efforts are currently being poured into "Moose Docs" so we don't want to lose edits to the old system. We still need help getting critical mass moved over and existing things documented so we can replace the old with the new.

**Comment by WilkAndy** [comment]
Searchable is the key, i think.   The search in MOOSE Docs certainly doesn't work for me presently.

Regarding the visability of MOOSE Docs: there still should be a link, even if it has a "under construction" disclaimer.

**Comment by aeslaughter** [comment]
The search bar is known to not work, I have not implemented it yet. It is unfortunately not as easy as I hoped so it may be a while before that is done.

**Comment by WilkAndy** [comment]
Aha, no worries, I'm so glad it's you doing it and not me!
