### ISSUE TITLE
Peacock 2 Static Min/Max Should be "per variable"

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#9983]
## Rationale
Related to #9934

In the ExodusViewer tab if you set a static (non-automatic) min/max for a variable... it should ONLY be for that variable (and it should be remembered).

So: if I have three variables: u, v, w

I set the min/max of u to 1.2/3.7

Then I click on v... it should still have automatic bounds.

If I set a max of 3.8/98 for v then click back on u it should go back to the max of 1.2/3.7.

If I click back on v it should be 3.8/98 again

And if I click on w it should still be automatic.

This is the way it worked in Peacock 1 and it makes no sense to apply the min/max of one variable to another (which is what it's currently doing).

## Description
See Above

## Impact
Better workflow

**Comment by aeslaughter** [comment]
> If I set a max of 3.8/98 for v then click back on u it should go back to the max of 1.2/3.7.

This should be working, if it is not there is a bug.

Going to auto for each variable might be useful for your variables, but what about a set of variables that all have the same range. If I have 10 variables that are supposed to be between 0 and 1 when I look at them I have to change the range 10 times.

Again, how can we work with both types of workflows?

**Comment by friedmud** [comment]
I can see that (like with phase field).

So I still suggest _radio buttons_!  The buttons would be: Auto, Static, Global Static

**Comment by aeslaughter** [comment]
closed by #11627
