### ISSUE TITLE
One unnecessary check for material coverage

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9992]
## Rationale
I have a problem which has materials on part of the domain. The other part does not have any materials. Now I am hitting a MOOSE error at https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblemBase.C#L4697.
BTW, I noticed the material coverage check is actually not inside the if statement
```
if (_material_coverage_check)
```
I am not sure if it is intended or a bug.

## Description
I do not think this check is necessary. It is perfectly fine to do a simulation only on part of the domain.

## Impact
Removing a more restrictive check should not impact any applications.

**Comment by permcody** [comment]
I believe this is all working as intended. There are two kinds of checks. Just dummy checks (i.e. this kind where you look for potential error https://github.com/idaholab/moose/blob/devel/framework/src/base/FEProblemBase.C#L4671-L4674) and hard checks (i.e. make sure that a material property that is requested actually exists. There's no way around this check).

The error you are receiving is the dummy check so you can just disable it. If you are missing a property that is being consumed, that's a different problem.

**Comment by YaqiWang** [comment]
The problem is that I do not want to miss the dummy checks on the subdomain where the simulation is on. If I set the parameter to false in the input, I will disable the dummy check completely. Wait, my second thought is that maybe I just do not need this dummy check. Then it is just a little annoying that I have to set the parameter to false. The question is that can we delete this dummy check completely since it is so dummy?

**Comment by permcody** [comment]
> The question is that can we delete this dummy check completely since it is so dummy?

Well we can do anything we want. The problem here is that once again, one size doesn't fit all. This check does make sense for a lot of people, since it does catch issues with the input file but it might just get in the way with your application. Perhaps we can create a programatic way to turn this on/off and you can disable it in your app? It was added several years ago before we had good material property checking. Maybe it's outlived it's usefulness.

**Comment by YaqiWang** [comment]
I am also puzzled that why I am getting this error now but not before. Is something in MOOSE recently changed?

**Comment by YaqiWang** [comment]
While in my input I turned `Debug/show_actions=true`, somehow this parameter interfering with `Problem/material_coverage_check`. I can show you on my computer quickly if you can stop by. It is very strange.

**Comment by YaqiWang** [comment]
I observed that if I have
```
[Debug]
[]
```
in my input, `CheckIntegrityAction` will not be built not otherwise. I do not think this is a desired behavior...

**Comment by permcody** [comment]
Yeah, that's probably not desired. It's possible that the Debug block is associated with the CheckIntegrityAction so if it "exists" we don't build the default one. It might be more complicated than that, but the Action system tries to build lots of things automatically. Sounds like it's unrelated to this issue. Perhaps open a different issue for this specifically?

To answer your other question, no, nothing has changed regarding the material coverage check recently. This has been relatively static for years.

**Comment by YaqiWang** [comment]
Ok, I will create a new one and close this one. `FEProblemBase` does provide the programatic way to disable the check.
