### ISSUE TITLE
CheckIntegrityAction may not be built by ActionWarehouse

### ISSUE THREAD

**Issue by YaqiWang** [idaholab/moose#9997]
## Rationale
If we add
```
[Debug]
[]
```
in an input, we see `CheckIntegrityAction` will not be built by `ActionWarehouse`.

## Description
I am not sure if there are any other cases. But this is not a desired behavior.

## Impact
Fix missing integrity check.

**Comment by YaqiWang** [comment]
I did a little investigation on this. It appears this happens only when I use Rattlesnake executable to run the inputs. @permcody Can one of you to check what is wrong? If we do not want to miss `checkProblemIntegrity` for all runs. I suggest to stop using action to call it but instead call it either directly in `ActionWarehouse` or `FEProblemBase::initialSetup`.

**Comment by permcody** [comment]
What did you do?!  I'll get to it when I can.

**Comment by YaqiWang** [comment]
Could be an opportunity to make the action system more robust ;-)

**Comment by permcody** [comment]
It is very robust. It does a lot of things right within the design I cooked up. This may not even be a MOOSE bug! We'll have to investigate.

**Comment by YaqiWang** [comment]
I guess `check_integrity` task is not supposed to be registered by any other actions. If so, framework may need to add protections on those tasks.

**Comment by permcody** [comment]
Yes! You could argue that people registering new tasks should screw up MOOSE's core but it's not that easy. If you want to start replacing Actions with other Actions or accomplishing a task through some other means this flexibility needs to be there. It's just easy to cause subtle problems when you start messing with satisfying non-required Actions that are actually pretty important.

**Comment by permcody** [comment]
@YaqiWang - Just tried this on a few tests in Rattlesnake and was not able to replicate. Not picking on you, but when you fill out this template, try to be more specific on how to replicate (even if the problem is general).

**Comment by YaqiWang** [comment]
We fixed something in Rattlesnake MR 241. Basically we associated our actions with another task instead of check_integrity. This can be closed.
